openwrt/packages

utils/telldus-core/Makefile
=> telldus-core: remove freebsd hack

utils/cryptsetup/Makefile
=> cryptsetup: fix compilation with full NLS

admin/schroot/Makefile
=> schroot: fix compilation with full NLS

utils/gammu/Makefile
Just disable NLS to fix it.
Maintainer: @aTanW 
=> gammu: fix compilation with full NLS

libs/glib2/Makefile
There's a better and faster way to do this.
=> glib2: remove static library hack

utils/domoticz/Makefile
=> domoticz: fix compilation with full NLS

.github/workflows/entrypoint.sh
PKG_NAME might be something entirely different as the folder containing the test.
=> CI: use PKG_SOURCE not PKG_NAME for test.sh search

utils/mariadb/Makefile, utils/mariadb/files/mysqld.init
Maintainer: me
Compile tested: mvebu/cortexa9, Turris Omnia, TOS 5.2 = OpenWrt 19.07
Run tested: mvebu/cortexa9, Turris Omnia, TOS 5.2 = OpenWrt 19.07, installed and started using init script
Description:
Minor polishing of init script and bump to the newest version in 10.4 branch.
=> MariaDB: cleanup & update

libs/libuhttpd/Makefile
Maintainer: me
Compile tested: (x86,, master)
Run tested: (x86,, master)
Description:
=> libuhttpd: Update to 3.3.1

lang/python/python3-pyroute2/Makefile
Signed-off-by: Martin Matějek <martin.matejek@gmx.com>
Maintainer: me / @mmtj
Compile tested: Turris MOX, cortexa53, OpenWrt master
Run tested: Turris MOX, cortexa53, OpenWrt master
Description: Update to version 0.5.14
=> python3-pyroute2: update to version 0.5.14

lang/python/django-restframework/Makefile, lang/python/django/Makefile
Maintainer: me, @peter-stadler (for django-restframework)
Compile tested: x86  https://github.com/openwrt/openwrt/commit/2a90d308c73f3f254e93fe3c55d4e40eaabc06e3
Run tested: x86 https://github.com/openwrt/openwrt/commit/2a90d308c73f3f254e93fe3c55d4e40eaabc06e3
=> diango,django-restframework: bump versions 

utils/prometheus-node-exporter-lua/Makefile, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/dawn.lua
Add dawn exporter to Makefile.
Add hostname to export.
Compile tested: 621297e86736556f772a3a1e3907c4ad9223bd74
Run tested: r14034-b735bbc
=> prometheus-node-exporter-lua: update dawn exporter

multimedia/motion/Makefile
The buildbots are unable to build this.
=> motion: remove mmal support

net/mbusd/Makefile, net/mbusd/files/mbusd.conf, net/mbusd/files/mbusd.init
Maintainer: me
Compile tested: (rampis, Nexx WT3020 (MT7620), OpenWrt master (r14531))
Run tested: (rampis, Nexx WT3020 (MT7620), OpenWrt master (r14531))
Description:
Mbusd is open-source Modbus TCP to Modbus RTU (RS-232/485) gateway.
=> New package: mbusd

.github/workflows/ci_helpers.sh, .github/workflows/entrypoint.sh
Run tested: NA
Description:
Add some minor helper functions that could be used to produce nicer output during CI runs. How it works can be seen in #13540
=> CI: Add some helper functions

net/pdns/Makefile, net/pdns/patches/100-pdns-disable-pdns.conf-dist.patch
=> pdns: update to 4.3.1

net/pdns-recursor/Makefile, net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch, net/pdns-recursor/patches/200-boost_thread_fix.patch, net/pdns-recursor/patches/300-boost-173.patch, net/pdns-recursor/patches/400-openssl-deprecated.patch
=> pdns-recursor: update to 4.3.4

net/nextdns/Makefile
=> nextdns: Update to version 1.8.6

net/nextdns/Makefile
=> [19.07] nextdns: Update to version 1.8.6

admin/muninlite/Makefile
Signed-off-by: Lars Kruse <devel@sumpfralle.de>
Maintainer: @jmccrohan
Description: update to new upstream release with minor feature additions
=> muninlite: update to new upstream release (2.1.0)

mail/postfix/Makefile
=> postfix: update to 3.5.7

utils/mariadb/test.sh
Maintainer: me
Run tested: NA
Description:
Try to add basic test for MariaDB, mainly to get a feel how CI works. Test to be enhanced later, locally script works, but want to ensure that I got how the whole system works.
=> mariadb: Add basic test

libs/libuhttpd/Makefile
=> libuhttpd: Update to 3.4.0

net/prosody/Makefile, net/prosody/files/prosody.init
=> prosody: update to 0.11.7

libs/qrencode/Makefile
=> qrencode: update to 4.1.1

admin/muninlite/Makefile
Signed-off-by: Kim B. Heino <b@bbbs.net>
Maintainer: @jmccrohan
Description: update to new upstream release with minor feature additions
=> muninlite: update to new upstream release (2.1.1)

utils/reptyr/Makefile, utils/reptyr/test.sh
Maintainer: me
Compile tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master
Run tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master
Description:
- Add package [reptyr](https://github.com/nelhage/reptyr/)
=> reptyr: add package

lang/python/python-contextlib2/Makefile
Maintainer: me
Compile tested: Turris Omnia (master)
Run tested: Turris Omnia (master)
=> python-contextlib2: bump to version 0.6.0.post1

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/share/ddns/default/sitelutions.com.json
Signed-off-by: Florian Eckert <fe@dev.tdt.de>
Maintainer: me / @Ansuel 
Run tested: no use case for this only url update
Description:
This fixes #13101
=> ddns-scripts: update sitelutions url

libs/nss/Makefile
=> nss: update to 3.57

libs/nspr/Makefile
=> nspr: update to 4.29

libs/nss/Makefile
Maintainer: me
Tested: x86
Sorry for not jumping to the latest, I somehow missed the latest version
=> nss: update to 3.58

lang/python/python-tornado/Makefile
Maintainer: me
Compile tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master
Run tested: with example Hello, word - https://pypi.org/project/tornado/
Description:
- Adds new package Tornado (could be in the future dependency for Salt)
=> Add Python package - Tornado

utils/ctop/Makefile
Maintainer: me
Description:
Stable update, it brings an improved and configurable layout.
=> ctop: update to v0.7.4

lang/python/python-dotenv/Makefile
Maintainer: me
Description:
Stable update with minimal changes.
=> python-dotenv: update to v0.15.0

net/chrony/Makefile, net/chrony/files/chrony.conf, net/chrony/files/chrony.config, net/chrony/files/chrony.hotplug, net/chrony/files/chronyd.init
Maintainer: me
Compile tested: x86_64+mips, kvm+archer c2, master+19.07
Run tested: x86_64+mips, kvm+archer c2, master+19.07, tested client and server with and without NTS
Description:
This PR improves the hotplug script and NTS support, changing default configuration and adding new options in UCI.
=> chrony: improve configuration and hotplug script

net/tor/Makefile
[First pull request ever, let me know what to improve, if anything.]
This adds support for disabling bridge/relay support at build time (saving quite a bit of space), and also disabling HTML/manpages documentation generation, which we don't need.
=> Tor: a couple of updates

net/mwan3/Makefile, net/mwan3/files/etc/init.d/mwan3, net/mwan3/files/lib/mwan3/common.sh, net/mwan3/files/lib/mwan3/mwan3.sh, net/mwan3/files/usr/libexec/rpcd/mwan3, net/mwan3/files/usr/sbin/mwan3, net/mwan3/files/usr/sbin/mwan3rtmon, net/mwan3/files/usr/sbin/mwan3track
Signed-off-by: Aaron Goodman <aaronjg@stanford.edu>
Description:
=> mwan3: fix mwan3 'use'

utils/tmux/Makefile
Maintainer: me
Compile tested: ath79, WNDR3800, ﻿r14857+5-df469befdc
Run tested: ath79, WNDR3800, r11651+3-487e0631d0
Description:
=> tmux: update to 3.1c

libs/protobuf/Makefile, libs/protobuf/patches/010-rpath.patch
Signed-off-by: Bruno Randolf <br1@einfach.org>
Compile tested: ar71xx, OpenWRT 19.07
Run tested: ar71xx, OpenWRT 19.07
=> protobuf: Update to version 3.13.0

libs/gpgme/Makefile, libs/libassuan/Makefile, libs/libgpg-error/Makefile, libs/libksba/Makefile, libs/npth/Makefile, utils/cni-plugins/Makefile, utils/cni/Makefile, utils/conmon/Makefile, utils/gnupg/Makefile, utils/gnupg2/Makefile, utils/podman/Makefile, utils/podman/files/containers.conf
Maintainer: me
Run tested: -
Description:
Make libgpgme{,pp} available.
=> [RFC] package gnupg2, libgpgme{,pp} and podman

libs/faad2/Makefile
=> faad2: update to 2.10.0

libs/libgcrypt/Makefile, libs/libgpg-error/Makefile
Maintainer: me
Compile tested: mips_24kc master
Description:
=> Libgcrypt update

libs/vips/Makefile, libs/vips/patches/001-no_introspection.patch, libs/vips/patches/010-reproducible-build.patch
Maintainer: me
Compile tested: mips_24kc master
Description:
=> vips: update to 8.10.2

libs/openldap/Makefile
Maintainer: me
Compile tested: mips_24kc master
Description:
=> openldap: update to 2.4.56

net/memcached/Makefile
=> memcached: update to 1.6.8

utils/lxc/Makefile, utils/lxc/patches/015-getline.patch, utils/lxc/patches/025-remove-unsupported-option.patch
=> lxc: update to 4.0.5

libs/libnpupnp/Makefile, libs/libupnpp/Makefile, sound/upmpdcli/Makefile, sound/upmpdcli/patches/010-unistd.patch
=> upmpdcli updates

utils/domoticz/Makefile, utils/domoticz/patches/010-boost-173.patch, utils/domoticz/patches/020-python39.patch
Added Fedora patch to fix compilation.
Added python3 dependency as it seems it's needed now.
Fixes: https://github.com/openwrt/packages/issues/13757
=> domoticz: fix compilation with python 3.9

net/nginx/Makefile
Maintainer: @Ansuel and @heil
Run tested: x86_64, x86_64 qemu, master, run luci-nginx
Update to newest version, changelog: https://nginx.org/en/CHANGES
=> nginx: update to version 1.19.4

utils/sysstat/Makefile
=> sysstat: update to 12.4.1

lang/python/python-requests/Makefile
Maintainer: me, @BKPepe 
Compile tested: x86 https://github.com/openwrt/openwrt/commit/f276395cda79996d395209700a51bb94a0e25abd
Run tested: x86 https://github.com/openwrt/openwrt/commit/f276395cda79996d395209700a51bb94a0e25abd
=> python-requests: bump to version 2.25.0

libs/alsa-lib/Makefile, libs/alsa-lib/patches/300-snd_plugin.patch, libs/alsa-ucm-conf/Makefile, sound/alsa-utils/Makefile
=> alsa updates

devel/automake/Makefile
=> automake: update to 1.16.3

net/curl/patches/001-openssl-acknowledge-SRP-disabling-in-configure-properly.patch
Maintainer: @kaloz @aparcar 
Compile tested: ramips, mvebu
Run tested: ramips, mvebu
Description:
Ref: https://curl.se/mail/lib-2020-10/0037.html
=> curl: fix build against OpenSSL

multimedia/graphicsmagick/Makefile
Signed-off-by: Robert Högberg <robert.hogberg@gmail.com>
Run tested: no
=> graphicsmagick: Fix package description typo

libs/libnetfilter-cthelper/Makefile
=> libnetfilter-cthelper: import from base

libs/libnetfilter-log/Makefile, libs/libnetfilter-log/patches/0001-build-remove-unnecessary-pkgconfig-config.status-dep.patch, libs/libnetfilter-log/patches/0002-build-remove-unused-lines-in-Makefile.am.patch, libs/libnetfilter-log/patches/0003-build-resolve-automake-1.12-warnings.patch, libs/libnetfilter-log/patches/0004-Add-include-needed-for-integer-type-definition.patch, libs/libnetfilter-log/patches/0005-configure-uclinux-is-also-linux.patch, libs/libnetfilter-log/patches/0006-configure-add-without-ipulog-option-to-disable-libip.patch, libs/libnetfilter-log/patches/0007-include-Sync-with-current-kernel-headers.patch, libs/libnetfilter-log/patches/0008-include-Sync-with-current-kernel-headers.patch
=> libnetfilter-log: import from base

net/lighttpd/Makefile, net/lighttpd/patches/010-meson-lua.patch, net/lighttpd/patches/020-webdav-atfile.patch, net/lighttpd/patches/030-one-shot-pipes.patch
Maintainer: W. Michael Petullo mike@flyn.org
Compile tested: x86-64 OpenWrt master branch (v19.07.4)
Description:
lighttpd: build and bugfix patches
Signed-off-by: Glenn Strauss <gstrauss@gluelogic.com>
=> lighttpd: build and bugfix patches

net/udpxy/Makefile
=> udpxy: update to 1.0-25.0

utils/unrar/Makefile
Add PKG_BUILD_PARALLEL for faster compilation.
=> unrar: update to 6.0.2

net/wavemon/Makefile
=> wavemon: update to 1.9.2

net/zerotier/Makefile, net/zerotier/patches/0001-find-miniupnpc.h-in-staging-directory.patch, net/zerotier/patches/0002-remove-pie.patch, net/zerotier/patches/0003-remove-arm32-conservative-CFLAGS.patch, net/zerotier/patches/0004-accept-external-linker-flags.patch, net/zerotier/patches/0005-link-natpmp.patch, net/zerotier/patches/0006-gcc10.patch, net/zerotier/patches/0007-add-cerrno-header-for-str-errno.patch, net/zerotier/patches/0008-fix-compilation-for-arm_cortex-a7-neon.patch
Maintainer: me
Compile tested: ramips/mt7620, Nexx wt3020, OpenWrt master
Run tested: Starts and connects to public network
This is a backport from master.
=> zerotier: update to 1.6.2

libs/unixodbc/Makefile
=> unixodbc: update to 2.3.9

net/pdns-recursor/Makefile
=> pdns-recursor: update to 4.4.1

multimedia/graphicsmagick/Makefile
Same fix as in imagemagick.
Compile tested: powerpc
=> graphicsmagick: fix compilation with GCC 10

net/i2pd/Makefile, net/i2pd/files/i2pd.config, net/i2pd/files/i2pd.init, net/i2pd/patches/010-config.patch
=> i2pd: Update to 2.35.0

libs/lzo/Makefile
=> lzo: import from base

devel/ninja/Makefile
=> ninja: update to 1.10.2

net/frp/Makefile
Maintainer: @ysc3839 
Compile tested: ath79/nand
Run tested: ath79/nand
=> frp: update to 0.34.3

net/iftop/Makefile, net/iftop/patches/010-gcc10.patch
Moved over from openwrt.git
Maintainer: me
Run tested: CI
=> iftop: add package

lang/php7/test.sh
Maintainer: me
Description:
Add first shot of a CI test script for php7 package.
=> php7: add CI test script

utils/lcd4linux/Makefile, utils/lcd4linux/files/lcd4linux.init
Maintainer: me
Run tested: x86_64, APU3, master
Description:
Switch service to procd.
=> lcd4linux: switch service to procd

net/i2pd/Makefile, net/i2pd/patches/010-config.patch, net/i2pd/patches/020-x86.patch
=> i2pd: backport upstream fix for i386

libs/libarchive/Makefile
=> libarchive: update to 2.5.0

devel/autoconf/Makefile
=> autoconf: update to 2.70

net/bind/Makefile, net/bind/files/bind/named.conf.example, net/bind/files/named.init
See issue #14183 for a description.
=> bind: add support for the 'rndc' utility

admin/sudo/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/cdc8d4b46f0811292fffc6094acd81e854b5f4a5
=> sudo: change maintainer to myself 

libs/libuhttpd/Makefile
=> libuhttpd: Update to 3.5.0

net/openvpn-easy-rsa/Makefile
Fixes dead symlinks under InstallDev.
=> openvpn-easy-rsa: use relative symlinks

utils/ntfs-3g/Makefile
Fixes dead symlinks in InstallDev.
=> ntfs-3g: make symlinks relative

utils/yq/Makefile
=> yq: Update to 4.0.0

libs/libuhttpd/Makefile
=> libuhttpd: Update to 3.6.0

net/ulogd/Makefile, net/ulogd/patches/020-fix-musl.patch, net/ulogd/patches/030-ipfix-add.patch, net/ulogd/patches/040-ipfix-template.patch
These patches have been living in master for a while now.
This backports them to 19.07.
=> [19.07] ulogd: backports from master

utils/uhubctl/Makefile
Maintainer: me
Compile tested: sdk:mvebu-cortexa9:snapshot
Run tested: mvebu-cortexa9-linksys_wrt1900acs:19.07.5
=> uhubctl: update to 2.3.0

admin/sudo/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/cdc8d4b46f0811292fffc6094acd81e854b5f4a5
Run tested: x86 https://github.com/openwrt/openwrt/commit/cdc8d4b46f0811292fffc6094acd81e854b5f4a5
=> sudo: bump to version 1.9.4p2

lang/php7-pecl-imagick/Makefile
=> php7-pecl-imagick: add new package

net/mwan3/Makefile, net/mwan3/files/etc/hotplug.d/iface/15-mwan3, net/mwan3/files/etc/hotplug.d/iface/16-mwan3-user, net/mwan3/files/etc/init.d/mwan3, net/mwan3/files/lib/mwan3/mwan3.sh, net/mwan3/files/usr/sbin/mwan3rtmon
Maintainer: me / @aaronjg 
Description:
Fix some error and add code cleanup.
=> mwan3: minor fixes

libs/vips/Makefile, libs/vips/patches/001-no_introspection.patch, libs/vips/patches/010-reproducible-build.patch
=> vips: update to 8.10.15

net/wget/Makefile
Maintainer: @tripolar @yousong @neheb 
Compile tested: ath79/nand
Run tested: ath79/nand
Description: fix https://github.com/openwrt/packages/pull/13613
=> wget: fix build

lang/node/Makefile, lang/node/patches/003-path.patch, lang/node/patches/004-musl_support.patch, lang/node/patches/007-fix_host_build_on_macos.patch, lang/node/patches/999-delete_unnecessary_libraries_for_host_execute.patch, lang/node/patches/999-localhost-no-addrconfig.patch
Compile tested: head r15324-920b692, aarch64, x86_64
Run tested: (qemu 5.2.0) aarch64, x86_64
Description:
Update to v14.15.3
=> node: update to v14.15.3

net/squid/Makefile
=> squid: update to 4.13

sound/shairport-sync/Makefile, sound/shairport-sync/patches/010-no-cxx.patch
=> shairport-sync: update to 3.3.7

utils/spi-tools/Makefile
=> spi-tools: update to 0.8.6

utils/sysstat/Makefile, utils/sysstat/patches/010-ldflags.patch
=> sysstat: update to 12.4.2

utils/yq/Makefile
=> yq: Update to 4.1.0

libs/tiff/Makefile
=> tiff: update to 4.2.0

libs/libuhttpd/Makefile
=> libuhttpd: Update to 3.7.0

libs/libimobiledevice/Makefile, libs/libimobiledevice/patches/100-ios14.patch, libs/libimobiledevice/patches/110-iOS14.patch, libs/libimobiledevice/patches/120-iOS14.patch
Maintainer: me
Fixes: https://github.com/openwrt/packages/issues/14344
=> imobiledevice: backport iOS 14 backup patch.

lang/node-hid/Makefile, lang/node-hid/patches/000-support_musl.patch
Maintainer: me
Compile tested: head r15359-2160a9d, arm 
Run tested: arm (qemu 5.2.0)
Description:
update to 2.1.1
=> node-hid: update to 2.1.1

lang/node-homebridge/Makefile, lang/node-homebridge/patches/000-add_module_search_path.patch
Maintainer: me
Compile tested: head r15359-2160a9d, arm 
Run tested: arm (qemu 5.2.0)
Description:
update to 1.2.4
=> node-homebridge: update to 1.2.4

lang/node-serialport-bindings/Makefile
Maintainer: me
Compile tested: head r15359-2160a9d, arm
 Run tested: arm (qemu 5.2.0)
Description:
update to 9.0.4
=> node-serialport-bindings: update to 9.0.4

lang/node-serialport/Makefile, lang/node-serialport/patches/000-remove_depends.patch
Maintainer: me
Compile tested: head r15359-2160a9d, arm
 Run tested: arm (qemu 5.2.0)
Description:
update to 9.0.4
=> node-serialport: update to 9.0.4

utils/rtl_433/Makefile
Replace CMAKE_INSTALL with an explicit InstallDev section.
Install conf files.
Maintainer: @TimelessNL 
=> rtl_433: update to 20.11

libs/xr_usb_serial_common/Makefile
Cleaned up Makefile to modern standards.
Compile tested: powerpc
=> xr_usb_serial_common: update to 2017-08-01

net/gitolite/Makefile
Fixes bad symlink under InstallDev.
Compile tested: powerpc
=> gitolite: change symlink from absolute to relative

utils/yq/Makefile
=> yq: Update to 4.2.0

utils/smartmontools/Makefile, utils/smartmontools/patches/001-use-external-drivedb.patch, utils/smartmontools/patches/002-os_mailer-is-mailx.patch, utils/smartmontools/test.sh
Maintainer: me
Compile tested: ath97, WNDR3800, r15387+5-9b1b89229f
Run tested: ath97, WNDR3800, r15339+6-bc99b56d7e
- update to 7.2
- add runtime tests
=> smartmontools: update to 7.2

net/usbip/Makefile, utils/hwdata/Makefile, utils/pciutils/Makefile, utils/pciutils/patches/101-no-strip.patch, utils/pciutils/patches/102-compressed-ids.patch, utils/pciutils/patches/106-hwdata.patch, utils/usbutils/Makefile
Maintainer:  @nbd168 @nunojpg @lucize 
depends on: https://patchwork.ozlabs.org/project/openwrt/patch/20201230033511.3181-1-rosenp@gmail.com/
=> hwdata: introduce package and use

utils/tini/Makefile
Maintainer: @G-M0N3Y-2503 
Fixes: https://github.com/openwrt/packages/issues/12353
Fixes: https://github.com/openwrt/packages/issues/11840
=> tini: fix compilation with glibc

utils/yq/Makefile
Maintainer: me
Compile tested: rockchip rk3328
Run tested: rockchip rk3328
Change log:
https://github.com/mikefarah/yq/releases/tag/v4.2.1
=> yq: Update to 4.2.1

utils/syncthing/Makefile
=> syncthing: bump to 1.12.0

utils/syncthing/Makefile
=> syncthing: bump to 1.12.1

admin/sudo/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/6773bee10753ae181257b544371101646822e80e
Run tested: x86 https://github.com/openwrt/openwrt/commit/6773bee10753ae181257b544371101646822e80e
=> sudo: bump to version 1.9.5p1

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_functions.sh
Compile tested: ath79/nand
Run tested: ath79/nand
Description: Fix path of wget-ssl due to https://github.com/openwrt/packages/pull/14257
=> ddns-scripts: fix wget-ssl path

utils/hwdata/Makefile
Compile tested: ipq40xx, wtr-m2133hp, OpenWrt master
Run tested: ipq40xx, wtr-m2133hp, OpenWrt master
=> hwdata: update to 0.343

net/eoip/Makefile, net/eoip/files/eoip.config, net/eoip/files/eoip.init, net/eoip/patches/100-add_LF_to_pidfile.patch
Maintainer: Bogdik <bogdikxxx@gmail.com>
Compile tested: zbt wr8305rt, dlink dir-300, dlink dir-615
Run tested: zbt wr8305rt mips, OpenWrt last snapshot, tests done
Description: Add Eoip package movement from https://github.com/openwrt/openwrt/pull/3721
=> Add Eoip packege

libs/libmaxminddb/Makefile
Maintainer: me
Compile tested: Turris Omna (TOS6), OpenWrt master
Run tested: Turris Omnia (TOS6), OpenWrt master
Description:
This PR updates libmaxminddb to version 1.5.0
=> libmaxminddb: update to version 1.5.0

libs/pthsem/Makefile
=> pthsem: try to fix ARC compilation

net/samba4/Makefile
Maintainer: me
Compile tested: arm/mvebu (master)
Run tested: arm/qemu (master)
Description:
* update to 4.13.4
=> samba4: update to 4.13.4

net/samba4/Makefile, net/samba4/files/samba.init
Maintainer: me
Compile tested: arm/mvebu (19.07-master)
Run tested:
Description:
* fix for possible exploit #13758
* sanitize all external template/config inputs
* fix some shellcheck warnings
=> [19.07] samba4: fix for #13758

net/ksmbd-tools/Makefile, net/ksmbd-tools/files/ksmbd.init
Maintainer: me
Run tested:
Description:
* fix for possible exploit #13758
* sanitize all external template/config inputs
* fix some shellcheck warnings
=> ksmbd-tools: fix #13758

utils/gl-mifi-mcu/src/module.c
Signed-off-by: Ilya Lipnitskiy <ilya.lipnitskiy@gmail.com>
Compile tested: mt7621, openwrt master with linux 5.10
Run tested: Not tested
Description: proc_create API changed in Linux 5.6
=> gl-mifi-mcu: compatibility with linux >= 5.6

utils/docker-compose/Makefile
Maintainer: me
Description:
Minor update.
=> docker-compose: Update to version 1.28.2

libs/libdaq3/Makefile, net/snort3/Makefile
=> snort3: update to 3.1.0.0

libs/libnetconf2/Makefile, libs/libnetconf2/patches/001-cmake_not_updated.patch, libs/libyang/Makefile, net/netopeer2/Makefile, net/sysrepo/Makefile
Compile tested: ipq40xx, openwrt master
=> Update sysrepo packages

ipv6/miredo/Makefile, ipv6/miredo/patches/001-fix-musl-pthread-non-portable.patch, ipv6/miredo/patches/002-fix-redefinition-ethadr.patch, ipv6/miredo/patches/003-fix-warnings-portable-defined.patch, ipv6/miredo/patches/004-reproducible.patch
=> miredo: add debian reproducibility patch

kernel/ksmbd/Makefile, net/ksmbd-tools/Makefile
=> ksmbd(-tools): update to 3.3.4

libs/nss/Makefile
=> nss: update to 3.61

net/libreswan/Makefile
=> libreswan: update to 4.2

net/netifyd/Makefile, net/netifyd/patches/010-reproducible.patch
=> netifyd: add reproducibility patch

net/uacme/files/run.sh
Run NOT tested: I had problems setting it up at all, but the similar changes worked for the acme package, so I suppose the problem is somewhere else on my side and it should work here, too.
Description: Use nginx-util to add the certificates to the corresponding domain(s) instead of the main config file, which does not contain the ssl* directives anymore.
**Update:** Follow the change for acme (PR #14664): reinserted the code with a modified condition: If the file `/etc/nginx/nginx.conf` exists (it does not by default) and is writable, change it as before.
=> uacme: adopt to new behavior of nginx

utils/yq/Makefile, utils/yq/test.sh
Maintainer: me
Compile tested: rockchip, x86
Description:
Changelog: https://github.com/mikefarah/yq/releases/tag/v4.5.1
=> yq: Update to 4.5.1

mail/alpine/Makefile, mail/alpine/patches/020-reproducible.patch
=> alpine: try to make reproducible

utils/uhubctl/Makefile
Maintainer: me
Compile tested: sdk:mvebu-cortexa9:snapshot
Run tested: mvebu-cortexa9-linksys_wrt1900acs:19.07.6
=> uhubctl: update to 2.4.0

utils/apk/Makefile
=> apk: update to 2.12.2

kernel/ksmbd/Makefile, kernel/ksmbd/patches/01-keep_kmod_metadata.patch, net/ksmbd-tools/Makefile, net/ksmbd-tools/files/ksmbd.init
ping @ynezz @hauke as this is a kernel module, it need to be merged right before a new release is cut. The current version has several bugs including some big endian ones.
=> [19.07] ksmbd(-tools): update to 3.3.4

net/owipcalc/Makefile
As suggested by others, I would like to take care of this tool. I am developing certain tools that rely on the library and also owipcalc.
=> owipcalc: change maintainer

utils/docker-compose/Makefile
Maintainer: me
Description:
It's two updates in a row. Working stable in my test environment.
=> Docker compose update

libs/icu/Makefile
Signed-off-by: Liangbin Lian <jjm2473@gmail.com>
Maintainer: Hirokazu MORIKAWA <morikw2@gmail.com>
Compile tested: macOS 10.15.7
Run tested: skiped
Description:
just a litter fix
=> libs/icu:  fix host compile in macOS

lang/golang/golang-values.mk, lang/golang/golang/Makefile
Maintainer: me
Compile tested: none (see #14833)
Description:
(cherry picked from commit dc587eccb7ad9f12ef4498ecb339a484299c39ba)
=> [openwrt-21.02] golang: Update to 1.16

net/xray-core/Makefile
Maintainer: me
Description:
However, due to some mental issues, I cannot set myself as a maintainer.
=> xray-core: remove myself from maintainters

net/xray-core/Makefile
Maintainer: me
Description:
See #14850.
=> [openwrt-21.02] xray-core: remove myself from maintainters

.github/workflows/multi-arch-test-build.yml
=> CI: enhance package detection logic

utils/mc/Makefile, utils/mc/patches/010-subshell.patch, utils/mc/patches/020-fix-mouse-handling-newer-terminfo.patch, utils/mc/patches/030-fix-cchat_t.patch
=> mc: update to 4.8.26

net/travelmate/Makefile, net/travelmate/files/travelmate.sh
Run tested: GL.iNet GL-MT1300, OpenWrt SNAPSHOT r15875-1bf6d70e60
Description:
* refine the wifi reconfigure logic
=> travelmate: update to 2.0.3

libs/libdrm/Makefile
=> libdrm: update to 2.4.104

utils/docker/Makefile, utils/dockerd/Makefile, utils/dockerd/git-short-commit.sh
Compile tested: x86_x64, VirtualBox, OpenWrt Master
Run tested: x86_x64, VirtualBox, OpenWrt Master
Description:
* Added script to verify/obtain the correct short SHA for a given version
* Minor style update
* Updated docker CLI and the daemon to 20.10.3
=> docker,dockerd: Updated to 20.10.3

net/libreswan/Makefile
=> libreswan: update to 4.3

multimedia/ffmpeg/Makefile
Maintainer: @antonlacon @thess 
=> ffmpeg: update to 4.3.2 / enable parallel build

utils/sysstat/Makefile, utils/sysstat/patches/010-ldflags.patch
=> sysstat: update to 12.4.3

libs/libdrm/Config.in, libs/libdrm/Makefile
Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
=> libdrm: add option to build the nouveau and radeon driver

net/uacme/Makefile
Switched to AUTORELEASE for simplicity.
=> uacme: update to 1.7

utils/yara/Makefile
=> yara: update to 4.0.5

utils/mc/Makefile
=> mc: remove maintainer

utils/syncthing/Makefile
Also start using $(AUTORELEASE)
=> syncthing: update to 1.13.1

net/xray-core/Makefile
Compile tested: ipq40xx, rockchip
Description:
Some minor bug fixes.
Fixes: #14972
=> xray-core: Update to 1.3.1

utils/joe/Makefile
Maintainer: Vitaly Protsko / @aTanW
Description:
Due to repeated requests, all additional functionality data packed as joe-extas
=> joe: new package joe-extras

net/clamav/Makefile, net/clamav/patches/010-musl12x.patch, net/clamav/patches/020-cmake.patch
Convert to using CMake in order to speed up compilation and to fix
compilation under glibc.
=> clamav: update to 0.103.1

lang/php7/Makefile, lang/php7/patches/0050-remove-build-timestamps.patch
Maintainer: me
Description:
Also refresh patch.
=> php7: update to 7.4.16

lang/php8/Makefile, lang/php8/patches/1001-ext-opcache-fix-detection-of-shm-mmap.patch, lang/php8/pecl.mk
=> php8: update to 8.0.3

lang/php7/Makefile, lang/php7/patches/0050-remove-build-timestamps.patch
Maintainer: me
Description:
Also refresh patch.
(cherry picked from commit 87e852fc7189b6deb390784d1741e0120e09045d)
=> [21.02] php7: update to 7.4.16

net/adblock/Makefile, net/adblock/files/README.md, net/adblock/files/adblock.mail, net/adblock/files/adblock.sh, net/adblock/files/adblock.sources
Run tested: PC Engines apu4, OpenWrt SNAPSHOT r16152-bff84f3e8e
Description:
* add adguard_tracking source (list with cname trackers)
* optimize/sort output of active sources in status
* optimize log output in EMails
=> adblock: small update

lang/python/python-websocket-client/Makefile
Maintainer: me
Description:
Small upstream update.
=> python3-websocket-client: update to 0.58.0

.github/workflows/Dockerfile, .github/workflows/ci_helpers.sh, .github/workflows/entrypoint.sh, .github/workflows/formal.yml, .github/workflows/multi-arch-test-build.yml
The CI is working fine with OpenWrt snapshots and 21.02, so backport it.
=> CI: backport GitHub action CI

kernel/ksmbd/Makefile, net/ksmbd-tools/Makefile
=> ksmbd: update to 3.3.6

utils/mandoc/Makefile, utils/mandoc/patches/010-mandoc-1.14.5-fix-gnu-make.patch
=> mandoc: new package

multimedia/ffmpeg/Makefile
Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Maintainer: @antonlacon  @thess 
=> ffmpeg: enable parallel build

net/udpxy/Makefile
=> udpxy: update to 1.0-25.1

utils/unrar/Makefile
=> unrar: update to 6.0.4

admin/sudo/Makefile, admin/sudo/patches/010-cross-compile-fixes.patch
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/d7c8ca4d0b5c18c08e645f010fd0012f54c1c102
Run tested: x86 https://github.com/openwrt/openwrt/commit/d7c8ca4d0b5c18c08e645f010fd0012f54c1c102
=> sudo: update to version 1.9.6p1

libs/msgpack-c/Makefile, net/tmate/Makefile, net/tmate/patches/010-Avoid-initializing-stdout-twice.patch, net/tmate/test.sh
Maintainer: me
Compile tested: rockchip, x86_64
Description:
Tmate is a fork of tmux. It provides an instant pairing solution.
For more details, see https://tmate.io.
=> tmate: add new package

libs/msgpack-c/Makefile, net/tmate/Makefile, net/tmate/patches/010-Avoid-initializing-stdout-twice.patch, net/tmate/test.sh
Run tested: CI
Description:
Backport to 19.07
=> [19.07]tmate: add package

net/banip/Makefile, net/banip/files/banip.sh
Run tested: TP-Link RE650 v1, OpenWrt SNAPSHOT r16249-9ac47ee469
Description:
* fix iptables/chain creation in setups without IPv6 support
=> banip: update 0.7.5-3

utils/btrfs-progs/Makefile
=> btrfs-progs: update to 5.11

libs/check/Makefile
Switch to building with ninja for faster compilation.
Maintainer: @eduardoabinader 
=> check: update to 0.15.2

net/coova-chilli/patches/010-kernel510.patch
=> coova-chili: fix compilation with kernel 5.10

devel/meson/meson.mk, devel/pkgconf/Makefile
=> pkgconf: update to 1.7.4

libs/leptonica/Makefile, libs/leptonica/patches/010-webp.patch, utils/tessdata/Makefile, utils/tesseract/Makefile, utils/tesseract/patches/010-cmake.patch, utils/tesseract/patches/020-musl.patch
=> tesseract updates

net/strongswan/Makefile
=> strongswan: change maintainers

net/netopeer2/Makefile
=> netopeer2: update to 1.1.70

lang/luv/Makefile
=> luv: update to 1.36.0-0

lang/luajit/patches/020-clang.patch
It errors out with this section.
=> luajit: fix compilation with host clang

libs/libical/Makefile, libs/libical/patches/001-disable-icu-and-bdb-support.patch
Refresh and simplify patch.
Maintainer: @jzapater 
=> libical: update to 3.0.9

libs/liborcania/Makefile, libs/libulfius/Makefile
=> libulfus and liborcana updates

utils/fish/Makefile
Maintainer: @jqqqqqqqqqq @halldong 
=> fish: update to 3.2.1

libs/ipfs-http-client/Makefile, libs/ipfs-http-client/patches/001-add-srv-addr.patch
=> ipfs-http-client: update to 2021-03-01

multimedia/icecast/Makefile, multimedia/icecast/files/icecast.init
Signed-off-by: Alexander Egorenkov <egorenar-dev@posteo.net>
Maintainer:  @thess, @andrenarchy
Compile tested: Netgear R9000, OpenWrt SNAPSHOT r16368-9f31c417a2 
Run tested: Netgear R9000, OpenWrt SNAPSHOT r16368-9f31c417a2
=> icecast: fix whitespace in init file

lang/python/python3-pyroute2/Makefile
Signed-off-by: Martin Matějek <martin.matejek@gmx.com>
Maintainer: me / @mmtj 
Compile tested: Turris MOX, cortexa53, OpenWrt master
Run tested: Turris MOX, cortexa53, OpenWrt master
Description: Update to version 0.5.16
=> python3-pyroute2: update to version 0.5.16

lang/python/python-pysocks/Makefile
Maintainer: me
Compile tested: Turris Omnia (TOS6), OpenWrt master
Run tested: Turris Omnia (TOS6), OpenWrt master
Description:
This PR adds new package python-pysocks. It is modern implementation of SocksiPy 
[more info](https://pypi.org/project/PySocks/)
=> python-pysocks: add new package

utils/cache-domains/Makefile, utils/cache-domains/files/cache-domains
Compile tested: x86_x64, QEMU/KVM, `master`
Run tested: x86_x64, QEMU/KVM, `master`
Description:
* Fixed host files directory
* Hid unnecessary output
=> cache-domains: Fixed host files directory

net/uacme/files/run.sh
Compile tested: x86-64, openwrt master (bc2538a)
Run tested: x86-64, openwrt master (bc2538a)
Description:
Prior to this commit, the acme service attempted to obtain certificates
once and then terminated, regardless of whether the certificate could be
obtained or not. This commit introduces a new uci option "retries" to
the "certificate" section. If this option is set to N, the acme service
will attempt to obtain the certificate up to N times before terminating.
There is a waiting pause between the retries to comply with the rate
limits of Let'sEncrypt.
The waiting pause is:
-  2 minutes for staging certificates
- 24 minutes for production certificates
The current "Failed Validation" rate limits of Let'sEncrypt are:
- staging:   60 per hour -> 1 failure every 1 minute …
=> uacme: add retries

net/strongswan/Makefile, net/strongswan/patches/305-minimal_dh_plugin.patch
Maintainer: me, @Thermi
Compile tested: x86_64, generic, master (2ff9686040)
Run tested: for now, just seeing if CI/CD builds... will merge into my tree and rebuild/retest if it does
Description:
=> strongswan: force PIC on all builds

kernel/ksmbd/Makefile, net/ksmbd-tools/Makefile, net/ksmbd-tools/files/ksmbd.init
=> ksmbd: update to 3.3.8

net/openvpn/Makefile, net/openvpn/files/etc/hotplug.d/openvpn/01-user, net/openvpn/files/lib/functions/openvpn.sh, net/openvpn/files/openvpn.init, net/openvpn/files/openvpn.options
I would like to request commit access to the packages repository to ease maintenance of this package.
Maintainer: me
Description:
Backport OpenVPN updates since branch. A security update for OpenVPN has been announced for later in April, this backport eases applying the update. The up/down script fix is important, and it is cleaner to backport all commits.
=> [21.02] Backport OpenVPN update and bugfixes

net/travelmate/Makefile, net/travelmate/files/mikrotik.login, net/travelmate/files/travelmate.sh
Run tested: -
Description:
* fix cp detection proposed by @ChristianKuehnel
* add/adapt mikrotik login script provided by @ChristianKuehnel
=> [19.07] travelmate: minimal change to fix cp detection

lang/python/python3-bottle/Makefile
Maintainer: me
Compile tested: cortexa53, Turris MOX, OpenWrt master
Run tested: cortexa53, Turris MOX, OpenWrt master
Description:
- update to version 0.12.19
=> python3-bottle: update to version 0.12.19

net/squid/Makefile
=> squid: update to 4.14

net/hcxdumptool/Makefile, net/hcxdumptool/patches/010-openssl.patch, net/hcxdumptool/patches/020-stdout.patch, net/hcxtools/Makefile, net/hcxtools/patches/010-openssl.patch
=> hcx(dump)tools: update to 6.1.6

net/strongswan/Makefile, net/strongswan/files/swanctl.init
Maintainer: me, @Thermi
Compile tested: x86_64, generic, head (880c8b4422)
Run tested: same, built and installed on test VM
Description:
Having an explicit hash algorithm with AEAD ciphers is not permitted.
=> strongswan: handle chacha20poly1305 as AEAD

lang/luv/Makefile
Simplify CMake section.
Fix pkgconfig paths.
=> luv: update to 1.40.0-0

net/strongswan/Makefile, net/strongswan/files/gencerts.sh
Maintainer: me, @Thermi
Compile tested: x86_64, generic, head (cb3fb45ed1)
Description:
Style changes that got left out of previous commit.
=> strongswan: change name of config base directory

utils/podman/Makefile, utils/podman/files/podman.init
Compile tested: x86_64, server, recent SnapShot
Run tested: x86_64, server, recent snapshot, tested
Description:
Update podman to version 3.1.1
**Other changes**
- Updated init script: stop pods and containers on shutdown.
- Enable AppArmor support
=> podman: update to 3.1.1

lang/node/Makefile, lang/node/patches/999-fix_icu_conflict.patch
Maintainer: @blogic @ianchi 
Compile tested: 21.02, arm
Run tested: (qemu 5.2.0) arm
Description:
Resolve conflicts between OpenWrt's ICU package and the ICU shipped with node.js.
https://github.com/openwrt/packages/issues/15437
=> [21.02] node: Resolve ICU conflict

net/banip/Makefile, net/banip/files/README.md, net/banip/files/banip.sh
Run tested: TP-Link RE650 v1, OpenWrt SNAPSHOT r16574-f7e00d81bc
Description:
* add a "whitelist only" mode, this option allows to restrict Internet
access from/to a small number of secure websites/IPs, and block access
from/to the rest of the Internet.
=> banip: update to 0.7.7

net/stunnel/Makefile
Maintainer: me
Compile tested: x86_64, APU3, latest openwrt-21.02
Run tested:  no
Description:
Update to the latest upstream version
=> stunnel: update version to 5.59

utils/gummiboot/Makefile, utils/gummiboot/patches/010-fix-missing-includes.patch, utils/gummiboot/patches/020-fix-dev-mapping.patch
Maintainer: Oskari Rauta @oskarirauta
Compile tested: x86_64, server, recent snapshot
Run tested: x86_64, server, recent snapshot
Description:
Simple UEFI boot manager
Requires #15485: gnu-efi
=> gummiboot: add new package

net/xray-core/Makefile, net/xray-core/files/config.json.example
Maintainer: me
Run tested: -
Description:
For more details, please see #15525.
=> [openwrt-21.02] xray-core: remove PROVIDES

utils/attendedsysupgrade-common/Makefile, utils/attendedsysupgrade-common/files/86241a707a30cb7f, utils/attendedsysupgrade-common/files/c06d891233ba699
* Use $(COMMITCOUNT)
* Use SPDX
* Use CA (ucert) public key
* Update repo link
* Update maintainer email
* Format description
=> attendedsysupgrade-common: update to 2021

net/banip/Makefile, net/banip/files/banip.sh
Run tested: TP-Link RE650 v1, OpenWrt SNAPSHOT r16603-14a95b36b1
Description:
* fix pid file processing of the background monitor plus child
processes (bug reported in the forum)
* made the enabled/disabled switch of the background monitor functional
=> banip: update to 0.7.8

lang/python/python-dotenv/Makefile
Maintainer: me
Description:
Small upstream update.
=> python-dotenv: update to v0.17.1

lang/php7/Makefile
Maintainer: me
Run tested: -
Description:
=> php7: update to 7.4.18

lang/php7/Makefile
=> php7: update to 7.4.19

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_functions.sh, net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_updater.sh
Compile tested: mvebu, master
Run tested: mvebu, master: Tested with cloudflare wildcard subdomain, it works
Description:
Fixes ddns-scripts so it will be able to update a wildcard subdomain.
Alternative to https://github.com/openwrt/packages/pull/14737
=> ddns-scripts: Fix for wildcard subdomain 

libs/nspr/Makefile
=> nspr: update to 4.30

libs/nss/Makefile, libs/nss/patches/003-openwrt_fix.patch
=> nss: update to 3.65

net/libreswan/Makefile
=> libreswan: update to 4.4

utils/yq/Makefile
Maintainer: me
Compile tested: rockchip, x86_64
Description:
Bug fixes.
=> yq: Update to 4.9.3

utils/yq/Makefile
Maintainer: me
Description:
Bug fixes.
=> [openwrt-21.02] yq: Update to 4.9.3

utils/gummiboot/Makefile
Run tested: x86_64, recent git, works
Description:
Item was not found on menuconfig, fixing case issue shows item again.
=> gummiboot: fix case in depends..

libs/libsearpc/Makefile, net/seafile-ccnet/Makefile, net/seafile-seahub/Makefile, net/seafile-server/Makefile
=> seafile: remove myself as maintainer of these packages

libs/gnutls/Makefile, libs/gnutls/patches/010-m4.patch
=> gnutls: update to 3.7.2

net/vsftpd/Makefile, net/vsftpd/patches/003-chroot.patch, net/vsftpd/patches/010-openssl-deprecated.patch
=> vsftpd: update to 3.0.4

libs/h2o/Makefile, libs/libfstrm/Makefile, libs/libwslay/Makefile, net/dnsdist/Makefile, net/pdns-recursor/Makefile, net/pdns/Makefile
Maintainer: me, handing over to @Habbie 
Description:
Remove myself as maintainer from PowerDNS Related packages and add Peter van Dijk from PowerDNS as the new maintainer
Signed-off-by: James Taylor <james@jtaylor.id.au>
=> pdns: Change maintainer on pdns packages

utils/tang/Makefile, utils/tang/patches/010-http.patch
=> tang: update to 10

utils/unrar/Makefile
=> unrar: update to 6.0.6

utils/fish/Makefile
=> fish: update to 3.2.2

utils/moreutils/Makefile
=> moreutils: update to 0.65

utils/tcsh/Makefile, utils/tcsh/patches/010-wint.patch
=> tcsh: update to 6.22.04

libs/liborcania/Makefile
Maintainer: me
Compile tested: mvebu, r16754+9-0e459668c5
Run tested: mvebu, r16754+9-0e459668c5
Description:
=> liborcania: update to 2.2.1

lang/php7/Makefile
=> php7: update to 7.4.20

utils/podman/Makefile
Description:
Update package to version 3.2.0
=> podman: update to 3.2.0

utils/crun/Makefile
=> crun: update to 3.2.0

utils/gpsd/Makefile
Maintainer: Maintainer: @psidhu 
=> [21.02] Pull latest changes from gpsd

lang/php8/Makefile
=> php8: update to 8.0.7

lang/python/python-twisted/Makefile, lang/python/python-twisted/patches/001-omit-tkconch.patch, lang/python/python-twisted/patches/002-omit-tests.patch
Maintainer: me
Compile tested: armvirt-32, 2021-06-07 snapshot sdk
Run tested: armvirt-32 (qemu), 2021-06-07 snapshot (called each executable with `--help` only)
Description:
=> python-twisted: Update to 21.2.0, redo patches

lang/python/python-twisted/Makefile, lang/python/python-twisted/patches/001-omit-tkconch.patch, lang/python/python-twisted/patches/002-omit-tests.patch
Maintainer: me
Compile tested: none (cherry picked from #15835)
Description:
(cherry picked from commit 4b6e05d1fdd886133c982247f616115ef401e38c)
=> [openwrt-21.02] python-twisted: Update to 21.2.0, redo patches

utils/prometheus-node-exporter-lua/files/usr/bin/prometheus-node-exporter-lua
Add my email address to the copyright for the file.
Signed-off-by: Kevin Lyda <kevin@lyda.ie>
Description: New PR based on feedback in #15682. Not totally clear who the maintainer is. I also think some other names should be added there because some folks have added really significant features - ones I'll definitely be using!
=> prometheus-node-export-lua: add my email

libs/protobuf/Makefile, libs/protobuf/patches/010-rpath.patch
=> protobuf: update to 3.17.2

lang/python/django/Makefile
Run tested:  n/a
--------------------------------------------------------------
(cherry picked from commit 24a8f5874155398df8e64b29897a511d5d603e03)
=> django: bump to version 3.2.4

net/samba4/Makefile
Maintainer: me
Run tested: arm/qemu (master)
Description:
* update to 4.13.9
=> samba4: update to 4.13.9

net/frp/Makefile
Signed-off-by: Van Waholtz <vanwaholtz@gmail.com>
=> frp: update to 0.37.0

utils/open-vm-tools/Makefile, utils/open-vm-tools/patches/0003-Use-configure-test-for-struct-timespec.patch, utils/open-vm-tools/patches/0005-Use-configure-to-test-for-feature-instead-of-platfor.patch, utils/open-vm-tools/patches/020-no-werror.patch
Bump to 11.3.0.
Signed-off-by: Yuhei OKAWA <tochiro.srchack@gmail.com>
Maintainer: me / @srchack 
target tested: x86_64 (ESXi 7.0)
=> open-vm-tools: update to 11.3.0

net/acme/Makefile, net/acme/files/acme.init, net/acme/files/run.sh
Ran through shellcheck and shfmt.
=> acme: update to 2.9.0

net/nextdns/Makefile
=> nextdns: Update to version 1.33.11

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.33.11

net/nextdns/Makefile
=> [19.07] nextdns: Update to version 1.33.11

libs/libtirpc/Makefile
Maintainer: me
Run tested:
Description:
update to 1.3.2
=> libtirpc: update to 1.3.2

net/samba4/Makefile, net/samba4/patches/001-samba-4.4.0-pam.patch, net/samba4/patches/006-netdb-defines.patch, net/samba4/patches/007-libldb-fix-musl-libc-unkown-type-error.patch, net/samba4/patches/008-samba-4.11-add_missing___compar_fn_t.patch, net/samba4/patches/009-samba-4-11-fix-host-tools-checks.patch.patch, net/samba4/patches/102-samba-4.11-unbundle-libbsd.patch
Maintainer: me
Run tested: arm/qemu (master)
Description:
* update to 4.14.5
=> samba4: update to 4.14.5

net/nextdns/Makefile
=> nextdns: Update to version 1.34.2

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.34.2

net/nextdns/Makefile
=> [19.07] nextdns: Update to version 1.34.2

utils/prometheus-node-exporter-lua/Makefile, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/hostapd_stations.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/wifi.lua
Compile tested: ipq40xx-generic, gl-inet b1300
Run tested: ipq40xx-generic, gl-inet b1300
Description: Correlating data is only possible when we have more metadata, this adds a bunch of labels for each client, that will increase the depth of dashboards to come.
Before:
```
hostapd_station_rx_bytes{station="24:62:ab:41:9e:28",ifname="radio0_vlan120"} 13768
hostapd_station_tx_bytes{station="24:62:ab:41:9e:28",ifname="radio0_vlan120"} 8317
hostapd_station_tx_packets{station="24:62:ab:41:9e:28",ifname="radio0_vlan120"} 94
hostapd_station_rx_packets{station="24:62:ab:41:9e:28",ifname="radio0_vlan120"} 118
hostapd_station_connected_time{station="24:62:ab:41:9e:28",ifname="radio0_vlan120"} 129
hostapd_station_signal{station="24:62:ab:41:9e:28",ifname="radio0_vlan120"} …
```
=> prometheus-node-exporter-lua: hostapd_stations metric and label makeover

libs/libebml/patches/010-gcc11.patch
=> libebml: fix compilation with GCC11

utils/yq/Makefile
Maintainer: me
Compile tested: rockchip, x86_64
Description:
Minor bug fixes.
=> yq: Update to 4.9.7

net/samba4/Makefile, net/samba4/patches/001-samba-4.4.0-pam.patch, net/samba4/patches/006-netdb-defines.patch, net/samba4/patches/007-libldb-fix-musl-libc-unkown-type-error.patch, net/samba4/patches/008-samba-4.11-add_missing___compar_fn_t.patch, net/samba4/patches/009-samba-4-11-fix-host-tools-checks.patch.patch, net/samba4/patches/102-samba-4.11-unbundle-libbsd.patch
Maintainer: me
Compile tested: arm
Description:
* update to 4.14.5
=> [21.02] samba4: update to 4.14.5

libs/ibrcommon/Makefile, libs/ibrdtn/Makefile, net/ibrdtn-tools/Makefile, net/ibrdtnd/Makefile
=> ibrdtn stuff: fix compilation with GCC11

utils/yq/Makefile
Maintainer: me
Compile tested: rockchip
Description:
Including a hotfix.
=> yq: Update to 4.9.8

utils/sane-backends/Makefile
Maintainer: me
Compile tested: ath79 and x86_64
Run tested: build fix
=> [21.02] sane-backends fix usbid generation (backport)

lang/luaossl/Makefile
Signed-off-by: Siger Yang <sigeryeung@gmail.com>
Maintainer: me
Compile tested: mipsel_24kc, 19.07.3
Run tested: YOUKU YK1
Description:
=> luaossl: add luaossl(rel-20200709) to feeds

utils/telldus-core/Makefile, utils/telldus-core/patches/970-gcc11.patch
=> telldus-core: fix compilation with GCC11

lang/erlang/Makefile
Fails to compile with it on.
Maintainer: @cretingame
=> erlang: disable PIE

net/uacme/Makefile
=> uacme: update to 1.7.1

utils/spi-tools/Makefile
=> spi-tools: update to 1.0.0

utils/yq/Makefile
Maintainer: me
Compile tested: ipq807x, rockchip
Description:
Bug fixes
=> yq: Update to 4.11.2

net/travelmate/Makefile, net/travelmate/files/chs-hotel.login, net/travelmate/files/db-bahn.login, net/travelmate/files/generic-user-pass.login, net/travelmate/files/h-hotels.login, net/travelmate/files/julianahoeve.login, net/travelmate/files/telekom.login, net/travelmate/files/travelmate.init, net/travelmate/files/travelmate.mail, net/travelmate/files/travelmate.sh, net/travelmate/files/travelmate.vpn, net/travelmate/files/travelmate_ntp.hotplug, net/travelmate/files/vodafone.login, net/travelmate/files/wifionice.login
Run tested: TP-RE650, OpenWrt SNAPSHOT, r17174-f7ab41acc9
Description:
* code cleanup
* add auto login script for Julianahoeve beach resort (NL)
* add auto login script for Vodafone hotspots (DE)
* add auto login script for telekom hotspots (DE)
* enhance captive portal detection to support html redirects as well
* change default captive portal detection url to
'detectportal.firefox.com'
=> travelmate: update to 2.0.4

libs/libndpi/Makefile
- libmaxminddb config option
Maintainer: me
Compile tested: ARMv7, mvebu, r17114+10-349e2b7e65
Run tested: ARMv7, mvebu, r17114+10-349e2b7e65
=> libndpi: update to 4.0

net/irssi/test.sh
Run tested: 
Turris Omnia, mvebu, SoC Marvell Armada 385, OpenWrt 19.07.7
```
root@turris:/# irssi --version 2>&1 | grep "$2"
irssi 1.2.2 (20190829 0225)
```
Description:
- With this file, it will be run tested by CI
=> irssi: add test.sh

lang/python/numpy/Makefile
Maintainer: me
Compile tested: n/a ; tested with defconfig / menuconfig
=> numpy: fix circular dependency

devel/gitlab-runner/Makefile
=> gitlab-runner: update to 14.0.1

utils/fish/Makefile
Maintainer: @jqqqqqqqqqq @halldong 
=> fish: update to 3.3.1

libs/alsa-lib/Makefile, libs/alsa-ucm-conf/Makefile, sound/alsa-utils/Makefile
=> alsa stuff: update to 12..5.1

net/nextdns/Makefile
=> nextdns: Update to version 1.35.0

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.35.0

net/nextdns/Makefile
=> [19.07] nextdns: Update to version 1.35.0

utils/ykclient/Makefile
Also replace dependency with + one.
Maintainer: @stuwilkins 
=> ykclient: remove pointless PKG_BUILD_DEPENDS

kernel/ksmbd/Makefile
keeping this here until a new release is to be cut. A really nasty file bug crept in the 3.3.4 release: https://github.com/cifsd-team/cifsd/issues/498
ping @hauke
=> ksmbd updates for 19.07

libs/cyrus-sasl/Makefile
=> cyrus-sasl: add optional sasldb package

kernel/ksmbd/Makefile, net/ksmbd-tools/Makefile
=> ksmbd: update to 3.4.0

utils/collectd/Makefile
=> collectd: enable cpufreq plugin for mediatek

net/xinetd/Makefile, net/xinetd/files/xinetd.init
this is needed for pr in luci with xinetd ipv6 support commits
=> xinetd: support for anonym configs

lang/python/python-sqlalchemy/Makefile
Maintainer: me
Compile tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master
Run tested: Turris Omnia, mvebu (cortex-a9), OpenWrt master
Description:
- [1.4.22 changelog](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-1.4.22)
=> python-sqlalchemy: update to version 1.4.22

net/travelmate/Makefile, net/travelmate/files/travelmate.sh
Run tested: TP-Link RE650 v1, OpenWrt SNAPSHOT r17322-8b7517465b
Description:
* scan for open uplinks even if no other station has been added/configured
=> travelmate: update to 2.0.5-2

utils/collectd/Makefile
Tested on AX3600
Signed-off-by: Matthew Hagan <mnhagan88@gmail.com>
=> collectd-mod-cpufreq: enable for ipq807x

net/samba4/files/samba.init
to allow graceful stop of the daemon
=> samba4: set stoplevel

net/ksmbd-tools/files/ksmbd.init
to allow graceful stop of the daemon
=> ksmbd: set stoplevel

utils/watchcat/Makefile, utils/watchcat/files/migrate-watchcat, utils/watchcat/files/watchcat.init, utils/watchcat/files/watchcat.sh
Cosmetic fixes mainly.
Maintainer: @roger-
=> watchcat: run through shfmt

net/unbound/Makefile, net/unbound/patches/010-configure_uname.patch, net/unbound/patches/100-example-conf-in.patch
Maintainer: me
Tested: linksys-wrt3200acm
Description: update unbound to 1.3.2
=> unbound: update to 1.3.2

net/softethervpn5/patches/010-engines.patch
=> softethervpn5: fix compilation without engines

net/nfdump/patches/010-fPIE.patch
=> nfdump: fix compilation with PKG_ASLR

net/vsftpd/Makefile
=> vsftpd: update to 3.0.5

lang/golang/golang-compiler.mk, lang/golang/golang-values.mk, lang/golang/golang/Makefile
Maintainer: me
Compile tested: armvirt-32/armvirt-64/malta-be/x86-generic/x86-64, 2021-08-15 snapshot sdk
Run tested: armvirt-32/armvirt-64/malta-be/x86-generic/x86-64 (qemu), 2021-08-15 snapshot
Description:
=> golang: Update to 1.17

net/aria2/Makefile
Maintainer: me
Description: Bump aria2 version
=> aria2: bump to v1.36.0

utils/airos-dfs-reset/Makefile, utils/airos-dfs-reset/files/airos-dfs-reset, utils/airos-dfs-reset/files/airos-dfs-reset.config, utils/airos-dfs-reset/files/airos-dfs-reset.init
=> airos-dfs-reset: cherry-pick into 21.02

net/fakepop/Makefile, net/fakepop/patches/010-fPIC.patch
Maintainer: @foxtrot 
Fixes: #13554
=> fakepop: fix compilation with PKG_ASLR

net/nextdns/Makefile
=> [19.07] nextdns: Update to version 1.36.0

kernel/ksmbd/Makefile, kernel/ksmbd/patches/010-no-acl.patch, net/ksmbd-tools/Makefile
ping @Vladdrako @egorenar  @fda77 @ptpt52
=> ksmbd stuff: update to 3.4.1

net/nfs-kernel-server/Makefile
=> nfs-kernel-server: update to 2.5.4

net/banip/Makefile, net/banip/files/banip.dns, net/banip/files/banip.hotplug, net/banip/files/banip.init, net/banip/files/banip.mail, net/banip/files/banip.service, net/banip/files/banip.sh, net/banip/files/banip.sources
Run tested: PC Engines apu4, OpenWrt SNAPSHOT r17417-38cb500516
Description:
* switch to unencrypted http downloads for ipdeny.com due to persistant certificate issues
* compact json generator code (tested with report files > 2MB)
* various code cleanups and optimizations
=> banip: update 0.7.10

lang/golang/golang-compiler.mk, lang/golang/golang-values.mk, lang/golang/golang/Makefile
Maintainer: me
Compile tested: none (cherry picked from #16435)
Description:
(cherry picked from commit d0aab6b8bc1a687f0c7b62ac2c92be36e2bdd8bd)
=> [openwrt-21.02] golang: Update to 1.17

net/xray-core/patches/100-go-1.17-deps.patch
Maintainer: me
Description:
cherry picked from commit dcd3f288e441dac264f4c34e19270e75d38933eb
=> [openwrt-21.02] xray-core: fix build under go 1.17

lang/php8/Makefile, lang/php8/patches/0007-Add-support-for-use-of-the-system-timezone-database.patch, lang/php8/patches/0022-Use-system-timezone.patch, lang/php8/patches/0041-Add-patch-to-remove-build-timestamps-from-generated-.patch
=> php8: update to 8.0.10

lang/php7/Makefile, lang/php7/patches/0032-Use-system-timezone.patch, lang/php7/patches/0041-Add-patch-to-remove-build-timestamps-from-generated-.patch
=> php7: update to 7.4.23

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/lib/ddns/update_gandi_net.sh
Maintainer: @feckert / @Ansuel 
Description:
Added error checks similar to the ones used in `ddns-scripts-pdns` (#16429)
=> ddns-scripts: better error management for gandi

net/ieee8021xclient/Makefile
Signed-off-by: David Yang <mmyangfl@gmail.com>
=> ieee8021x: depend on wpa_supplicant (#16525)

net/wg-installer/Makefile
=> wg-installer: fix dependencies

net/nextdns/Makefile
=> nextdns: Update to version 1.37.0

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.0

net/nextdns/Makefile
=> [19.07] nextdns: Update to version 1.37.0

net/nextdns/Makefile
=> nextdns: Update to version 1.37.1

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.1

net/nextdns/Makefile
=> [19.07] nextdns: Update to version 1.37.1

net/samba4/Makefile, net/samba4/patches/102-samba-4.11-unbundle-libbsd.patch
Maintainer: me
Compile tested: arm/master
Description:
* update to 4.14.7
=> samba: update to 4.14.7

net/samba4/Config.in, net/samba4/Makefile, net/samba4/files/samba.init, net/samba4/patches/102-samba-4.11-unbundle-libbsd.patch
Maintainer: me
Compile tested: arm
Description:
* update to 4.14.7
* remove domain if fqdn was set
* allow disabling wsdd2 in menuconfig
=> [openwrt-21.02] samba: update to 4.14.7

net/wsdd2/Makefile
Maintainer: me
Compile tested: arm/master
Run tested:
Description:
* update to git (2021-08-09)
* switch to Netgear repo
=> wsdd2: update to git (2021-08-09), switch to Netgear repo

libs/libuhttpd/Makefile
Speeds up compilation and potentially fixes it.
Maintainer: @zhaojh329 
=> libuhttp: don't build examples

net/nextdns/Makefile
=> nextdns: Update to version 1.37.2

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.2

net/nextdns/Makefile
=> [19.07] nextdns: Update to version 1.37.2

lang/python/django/Makefile
Maintainer: me
picked from #16588 
=> [21.02] django: bump to version 3.2.7

devel/autoconf/Makefile, devel/autoconf/test.sh
Maintainer:  @neheb 
Compile tested: cherry picked from #16614 
Run tested: 
Description:
=> [21.02]autoconf: fix shebang

utils/parted/Config.in, utils/parted/Makefile, utils/parted/test.sh
> `arch: x86_64
> 5.10.43.3-microsoft-standard-WSL2
> version:  [openwrt-21.02 601864c](https://github.com/openwrt/openwrt/tree/601864c09eae5b22620bc7942ceae13c2f081f1e)
Run tested: 
> arch: aarch64 
> device: raspberry pi 4
> version: OpenWrt 21.02-SNAPSHOT r16282-601864c09e
Description:
(cherry picked from commit 5ad56ca3407973980109a42c66995cd31fe1f456)
Signed-off-by: Ren Zongjia <acooler15@foxmail.com>
=> [21.02]parted: add new package

lang/php7/Makefile, lang/php7/patches/0032-Use-system-timezone.patch, lang/php7/patches/0041-Add-patch-to-remove-build-timestamps-from-generated-.patch
=> [21.02] php7: update to 7.4.23

net/v2raya/Makefile, net/v2raya/files/v2raya.config, net/v2raya/files/v2raya.init
Maintainer: me
Compile tested: ipq807x, rockchip
Description:
- Added conffiles
- Refreshed init srcipt to adapt the new arguments
- Renamed package name to lowercase (suggestion from upstream)
- Updated dependencies and license
This closes #16511.
=> v2raya: Update to 1.5.3

mail/dovecot/Makefile, mail/dovecot/patches/050-fix-dovecot-config-for-cross-compile.patch
=> dovecot: update to 2.3.16

net/openfortivpn/Makefile
=> openfortivpn: update to 1.17.1

libs/dtc/Makefile
Faster and more parallel friendly.
=> dtc: switch to compiling with meson

net/openvswitch/Makefile, net/openvswitch/README.md, net/openvswitch/files/openvswitch.config, net/openvswitch/files/openvswitch.init
Compile tested: master r17554-da5bb885e1 on x86/64
Run tested: master r17554-da5bb885e1 on x86/64
=> openvswitch: add option for failure mode and fix build with libunbound enabled

utils/apparmor/Makefile
=> apparmor: fix include path

libs/libuwsc/patches/010-gcc11.patch
Bad if identation is now an error.
Maintainer: @zhaojh329 
=> libuwsc: fix compilation with GCC11

devel/pkgconf/Makefile
=> pkgconf: update to 1.8.0

libs/openblas/Makefile, libs/openblas/patches/001-adjust-mips-el-arch.patch
Maintainer: me
Compile tested: mips64_octeonplus, mipsel  https://github.com/openwrt/openwrt/commit/2c9a07ed28e87bbe2d221d48aaa19b04672646a5
Fixes #16649 
=> libs: openblas: fix build failures on MIPSEL and MIPS64 archs

libs/protobuf/Makefile
=> protobuf: update to 3.17.3

libs/minizip/Makefile
=> minizip: update to 3.0.3

libs/nlohmannjson/Makefile
=> nlohmannjson: update to 3.10.2

admin/sudo/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/fc050c7b53116b6e3f2c31797b27cfc76af60e74
Run tested: x86 https://github.com/openwrt/openwrt/commit/fc050c7b53116b6e3f2c31797b27cfc76af60e74
=> sudo: bump to version 1.9.8p2

lang/python/openpyxl/Makefile
Maintainer: me
From master #16761 
=> [21.02] openpyxl: bump to version 3.0.9

lang/python/pillow/Makefile, libs/libwebp/Makefile, libs/libwebp/patches/010-mips16.patch
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/fc050c7b53116b6e3f2c31797b27cfc76af60e74
Run tested: x86 https://github.com/openwrt/openwrt/commit/fc050c7b53116b6e3f2c31797b27cfc76af60e74
Requested via: #16732
Continuing from #16765  
=> libwebp: bump to 1.2.1 and add myself as maintainer ; pillow: add webp support 

lang/python/python-websockets/Makefile, lang/python/python3-package.mk
Maintainer: me
Description: A python library for websocket servers and clients.
=> python-websockets: new package

utils/unrar/Makefile
Compile tested: x86_64, docker openwrtorg/sdk
Run tested: x86_64, docker openwrtorg/sdk, compile
Description:
update to 6.0.7
=> unrar: update to 6.0.7

utils/mariadb/Makefile, utils/mariadb/patches/130-c11_atomics.patch, utils/mariadb/patches/190-replace-hostname-in-mysqld_safe.patch
Maintainer: me
Compile tested: mvebu, Turris Omnia, Turris OS 5.4 = OpenWrt 19.07
Run tested: mvebu, Turris Omnia, Turris OS 5.4 = OpenWrt 19.07, it runs
Description:
Update to the latest stable version.
=> mariadb: Update to version 10.4.21

net/rclone/Makefile, net/rclone/patches/010-disable-plugins.patch, net/rclone/test.sh
Maintainer: @ElonH, me
Compile tested: ipq807x, rockchip
Description:
- Disabled unused plugins and re-enabled CGO.
- Fixed test script
Changelog: https://rclone.org/changelog/#v1-57-0-2021-11-01
=> rclone: Update to 1.57.0

utils/podman/Makefile, utils/podman/files/containers.conf
A lot of changes since 3.3.1.
Full (long) lists of release notes between
versions are available at
https://github.com/containers/podman/releases
Compile tested: x86_64, pc, recent snapshot
Run tested: x86_64, pc, recent snapshot
=> podman: update to 3.4.1

lang/php7-pecl-redis/Makefile
=> php7-pecl-redis: update to 5.3.4

kernel/v4l2loopback/Makefile, multimedia/v4l2rtspserver/patches/001_live555_sprintf_format, multimedia/v4l2tools/Makefile
Maintainer: michel.promonet@free.fr
Compile tested: (arch:arm7, model:bcm2709, OpenWrt master)
Run tested:  ( arch:arm7, model:bcm2709, OpenWrt master, start v4l2tool to compress YUYV to JPEG on vitual v4l2loopback device, and stream RTSP using v4l2rtspserver)
Description:
Hi,
This is an update to take into account comments on https://github.com/openwrt/packages/pull/17033.
Best Regards,
Michel.
=> Fix comment on https://github.com/openwrt/packages/pull/17033

net/nextdns/Makefile
=> nextdns: Update to version 1.37.4

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.4

net/conntrack-tools/Makefile, net/conntrack-tools/patches/001-endianness_fix.patch, net/conntrack-tools/patches/002-conntrackd-do-not-include-conntrack-ID-in-hashtable-cmp.patch
Maintainer: @jow @neheb 
Run tested: Edge Router 4
=> [21.02] conntrack-tools: backport some fixes

net/zerotier/Makefile
Maintainer: me
Compile tested: ath79/generic
=> zerotier: update to 1.8.3

net/yggdrasil/Makefile
Signed-off-by: George Iv <zhoreeq@users.noreply.github.com>
Description: bump version to 0.4.2
=> yggdrasil: bump to 0.4.2

net/nebula/Makefile
Maintainer: me
Description:
* update binaries to version 1.5.0 (thanks @jefferyto)
* update maintainer's email address
(cherry picked from commit 1421440174b80b7f9e9562217aa3951c6688839e)
=> [21.02] nebula: update to 1.5.0

net/curl/Makefile, net/curl/patches/200-no_docs_tests.patch
Maintainer: me
Description:
* bump version to 7.80.0
* update maintainer email address
(cherry picked from commit 80ef61729b18c28b76a1ee64d7af7251031a2496)
=> [21.02] curl: update to 7.80.0

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.5

net/yggdrasil/Makefile, net/yggdrasil/files/yggdrasil.defaults
Description:
Cherrypicking from #17153
=> [21.02] Bump yggdrasil to 0.4.2

net/nextdns/Makefile
=> nextdns: Update to version 1.37.6

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.6

net/nextdns/Makefile
=> nextdns: Update to version 1.37.7

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.7

lang/node/Makefile
Compile tested: 21.02, arm
Run tested: (qemu 6.1.0) arm
Description:
Update to v14.18.2
=> [21.02] node: bump to 14.18.2

multimedia/gst1-libav/Makefile, multimedia/gst1-plugins-bad/Makefile, multimedia/gst1-plugins-base/Makefile, multimedia/gst1-plugins-good/Makefile, multimedia/gst1-plugins-ugly/Makefile, multimedia/gstreamer1/Makefile
=> gstreamer1: update to 1.18.5

utils/yara/Makefile
=> yara: update to 4.1.3

sound/mpc/Makefile
=> mpc: update to 0.34

libs/libmpdclient/Makefile
=> libmpdclient: update to 2.20

net/ariang/Makefile
=> ariang: update to 1.2.3

utils/canutils/Makefile
=> canutils: update to 2021.08.0

utils/exfatprogs/Makefile
=> exfatprogs: update to 1.1.3

sound/shairport-sync/Makefile
Maintainer: @thess @mikebrady 
=> shairport-sync: update to 3.3.9

mail/alpine/Makefile
=> alpine: update to 2.25

lang/php7/Makefile
=> [21.02] php7: update to 7.4.27

libs/jsoncpp/Makefile
=> jsoncpp: update to 1.9.5

libs/alsa-lib/Makefile, libs/alsa-ucm-conf/Makefile, sound/alsa-utils/Makefile
=> alsa: updates to 1.2.6

libs/neon/Makefile, libs/neon/patches/010-no-xmlto.patch
Add patch to get rid of xmlto dependency.
Maintainer: @fededim 
=> neon: update to 0.32.1

lang/php8/Makefile
Maintainer: me
Run tested: -
Description:
=> php8: update to 8.1.1

libs/minizip/Makefile
=> minizip: update to 3.0.4

utils/prometheus-node-exporter-lua/Makefile, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/entropy.lua
=> prometheus-node-exporter-lua: Added entropy.lua.

net/stubby/Makefile, net/stubby/files/stubby.init
fixes #17421
Maintainer: @neheb, @jonathanunderwood
=> stubby: quote address value in config

net/wg-installer/Makefile, net/wg-installer/wg-server/hotplug.d/99-mesh-olsrd
Add hotplug-olsrd to automatically mesh with olsrd via new wireguard links.
=> wg-installer: add hotplug script for olsr

net/wg-installer/Makefile, net/wg-installer/wg-server/hotplug.d/99-mesh-olsrd
Add hotplug-olsrd to automatically mesh with olsrd via new wireguard
links.
(cherry picked from commit d35c22951bfabb9b34133471fe1e389909d2007b)
=> [21.02] wg-installer: add hotplug script for olsr

net/wg-installer/wg-client/wg-client-installer.sh, net/wg-installer/wg-server/lib/wg_functions.sh
The ipv4 address space was not allowed.
=> wg-installer: fix ipv4 meshing via olsr

net/wg-installer/common/wg.sh
Add script to cleanup unused wireguard interfaces.
=> wg-installer: add cleanup script

net/wg-installer/common/wg.sh
Add script to cleanup unused wireguard interfaces.
(cherry picked from commit 714b51c6309e4abc7c000bb9250119104fc2757a)
=> [21.02] wg-installer: add cleanup script

lang/python/django/Makefile
Compile tested: x86 https://github.com/openwrt/openwrt/commit/962c58558010bd302793ac24284c4f9db8fe287f
Run tested: x86 https://github.com/openwrt/openwrt/commit/962c58558010bd302793ac24284c4f9db8fe287f
=> django: bump to version 4.0.1

net/wg-installer/common/wg.sh
The wrong function was called.
=> wg-installer: fix cleanup script

net/wg-installer/common/wg.sh, net/wg-installer/wg-server/config/wgserver.conf, net/wg-installer/wg-server/lib/wg_functions.sh
Generate new keys on every new connection.
=> wg-installer: generate new keys for every connection

net/wg-installer/wg-server/config/wgserver.conf, net/wg-installer/wg-server/hotplug.d/99-mesh-babeld, net/wg-installer/wg-server/hotplug.d/99-mesh-olsrd
Add options to set link costs in mesh routing daemons.
=> wg-installer: allow defining link costs for hotplugs

net/ddns-scripts/files/usr/lib/ddns/update_cloudflare_com_v4.sh
Signed-off-by: Glen Huang <heyhgl@gmail.com>
Description:
=> ddns-scripts-cloudflare: fix shell conditional

net/knxd/Makefile, net/knxd/patches/010-link.patch
the link variable conflicts with the link() function.
Maintainer: @tru7 
=> knxd: fix compilation with newer glibc

utils/mmc-utils/Makefile
Maintainer: me
Description:
While at, update project's reference URL.
=> mmc-utils: update to latest git head

net/smcroute/Makefile
Maintainer: me
Compile tested: ath79/generic, carambola2
=> smcroute: update to version 2.5.5

net/wg-installer/common/wg.sh, net/wg-installer/wg-client/wg-client-installer.sh, net/wg-installer/wg-server/lib/wg_functions.sh
Use "ip addr" instead of "ip addres" or "ip a".
=> wg-installer: cosmetic changes

net/wg-installer/common/wg.sh, net/wg-installer/wg-client/config/wgclient.conf, net/wg-installer/wg-client/lib/rpcd_ubus.sh, net/wg-installer/wg-client/wg-client-installer.sh, net/wg-installer/wg-server/config/wgserver.conf, net/wg-installer/wg-server/hotplug.d/99-mesh-babeld, net/wg-installer/wg-server/hotplug.d/99-mesh-olsrd, net/wg-installer/wg-server/lib/install_wginstaller_user.sh, net/wg-installer/wg-server/lib/wg_functions.sh, net/wg-installer/wg-server/wginstaller.sh
Use shellcheck to rework the code. Use "export" to return variables from a function call. Further, fix typos.
=> wg-installer: rework code

net/wg-installer/wg-client/lib/rpcd_ubus.sh, net/wg-installer/wg-server/lib/wg_functions.sh
Check if a peer is already existing with a given public key. Introduce a response code for signaling why the server rejected the request.
=> wg-installer: check if a key is already inserted

net/wg-installer/Makefile, net/wg-installer/wg-server/lib/wg_functions.sh
Check if the key exists which is given by
option wg_key '/etc/wgserver/wg.key'
=> wg-installer: create wireguard key if it does not exist

net/vallumd/Makefile, net/vallumd/files/vallumd.conf, net/vallumd/files/vallumd.init
Maintainer: me
Compile tested: OpenWrt master r18531-0f50d3daff on qoriq
Run tested: OpenWrt master r18531-0f50d3daff on qoriq
=> vallumd: bump to 0.2.0

lang/python/micropython/Makefile, lang/python/micropython/patches/000-Makefile-no-errors.patch, lang/python/micropython/patches/030-target-no-darwin.patch
Maintainer: me
Compile tested: armvirt-32, 2022-01-16 snapshot sdk
Description:
=> micropython: Update to 1.18, refresh patches

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Run tested: -
Description:
=> php8: update to 8.1.2

multimedia/gerbera/patches/010-fmt.patch
Maintainer:
Compile tested: powerpc64
=> gerbera: fix compilation with fmt 8.1

libs/flac/Makefile
Fixes compilation with powerpc64
Compile tested: powerpc64
=> flac: disable vsx

utils/lrzsz/Makefile, utils/lrzsz/patches/200-format.patch
Found with -Wformat.
Maintainer: @kuoruan 
Compile tested: ppc64
=> lrzsz: fix various format warning

libs/libradiotap/patches/010-format.patch
Found with -Wformat
Maintainer: @PolynomialDivision 
Compile tested: ppc64
=> libradiotap: fix bad format

utils/rtklib/Makefile, utils/rtklib/patches/010-musl.patch, utils/rtklib/patches/020-no-gfortran.patch
Maintainer: Nuno Goncalves <nunojpg@gmail.com>
Compile tested: MT76x8, Onion Omega 2, openwrt 21.02
Run tested: MT76x8, Onion Omega 2, openwrt 21.02
Description:
update to 4.14.11; fix patches
=> rtklib: update to 2.4.3 b34 (latest) version 

utils/yq/Makefile
Maintainer: me
Description:
- https://github.com/openwrt/packages/pull/17680
- https://github.com/openwrt/packages/pull/17734
=> [openwrt-21.02] yq: Update to 4.18.1

admin/sudo/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/0c635cf830bc9bb46005f5f8ac414c80e1bcab4e
Run tested: x86 https://github.com/openwrt/openwrt/commit/0c635cf830bc9bb46005f5f8ac414c80e1bcab4e
-----------------------------------------------------------------
=> sudo: bump to version 1.9.9

net/xray-core/Makefile, net/xray-core/files/vpoint_vmess_freedom.json
Maintainer: me
Description:
- cherry picked from commit d8d261f #17787
=> [openwrt-21.02] xray-core: Update to 1.5.3

net/jool/files/jool-nat64.conf.json, net/jool/files/jool-siit.conf.json
Compile tested: latest master
Run tested: wrt3200acm
Description:
Update the default configuration files to match the upstream example
ones.
=> jool: update default config

utils/docker/Makefile, utils/dockerd/Makefile
Compile tested: x86_x64, QEMU/KVM, `openwrt-21.02`
Run tested: x86_x64, QEMU/KVM, `openwrt-21.02`
Description:
Updated docker to 20.10.12 and required dependencies
=> Docker: Updated to 20.10.12

net/phantap/Makefile
Maintainer: me
Run tested: ath79 / GL-AR150
Description:
e80be64 Remove disable_eap_hack
b066ce2 Switch to nftables / firewall4
4d88b0b Do not harcode build flags
=> phantap: switch to nftables

utils/auc/src/auc.c, utils/uvol/files/lvm.sh, utils/uvol/files/ubi.sh
Maintainer: me
Description: just using CI to see if it builds alright (and use artifacts for local test)
=> [DONT MERGE] update auc and uvol

utils/shared-mime-info/Makefile, utils/shared-mime-info/patches/001-shared-mime-info-2.1-fix-build.patch, utils/shared-mime-info/patches/002-shared-mime-info-2.1-no-xmlto.patch
=> shared-mime-info: new package

lang/cqueues/Makefile
Signed-off-by: Siger Yang <siger.yang@outlook.com>
Maintainer: me
Compile tested: mipsel_24kc, 21.02.1
Run tested: YOUKU YK1
Description:
=> cqueues: add cqueues(rel-20200726) to feeds

kernel/ksmbd/Makefile, kernel/ksmbd/patches/01-keep_kmod_metadata.patch, net/ksmbd-tools/Makefile
=> ksmbd: update to 3.4.4

libs/totem-pl-parser/Makefile, libs/totem-pl-parser/patches/totem-pl-parser-3.26.6-initialize.patch
=> totem-pl-parser: new package

net/uacme/Makefile
Maintainer: me
Tested x86
Fixes: #17837
=> uacme: pack ualpn.sh

net/yggdrasil/Makefile
Signed-off-by: George Iv <zhoreeq@users.noreply.github.com>
Description:
minor version bump
=> yggdrasil: bump to 0.4.3

net/tcpreplay/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/cbfce9236754700a343632fff8e035acbc1b1384
Run tested: same version
=> tcpreplay: bump to version 4.4.1

net/samba4/waf-cross-answers/powerpc64.txt
Needed for QoriQ target
Compile tested: ppc64
=> samba: add ppc64 support

utils/sumo/Makefile, utils/sumo/patches/010-gtest.patch
=> sumo: update to 1.12

utils/mksh/Makefile
Maintainer: @mirabilos 
Description:
Remove myself from maintainers.
=> mksh: resign as maintainer

utils/nsutils/Makefile
Description:
Linux namespace utilities
NSUtils suite includes a number of utilities to list, add/remove tag, and join namespaces.
=> nsutils: new package

libs/nss/Makefile
=> nss: update to 3.76

libs/nspr/Makefile
=> nspr: update to 4.33

net/nextdns/Makefile
=> nextdns: Update to version 1.37.10

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.10

lang/python/python-jsonschema/Makefile, lang/python/python-jsonschema/patches/001-setup.patch
Maintainer: @jmarcet 
Compile tested: armvirt-32, 2022-03-06 snapshot sdk
Run tested: armvirt-32 (qemu), 2022-03-06 snapshot
Description:
=> python-jsonschema: Update to 4.4.0

utils/yq/Makefile
Maintainer: me
Description:
- #17951 
- #18040
=> [openwrt-21.02] yq: Update to 4.22.1

utils/attendedsysupgrade-common/Makefile, utils/attendedsysupgrade-common/files/86241a707a30cb7f, utils/attendedsysupgrade-common/files/c06d891233ba699, utils/auc/src/auc.c
Maintainer: me, @aparcar
Run tested: -
Description:
Cherry-pick (and slightly edit) forgotten commit a54b9570ad6abc0b3e1079e881d1dbe9a475e33d and sync auc with master branch by picking commits 19c135685f7b9eefbf75b5a96b780f4fa2b46f19, d27ecdcc49f2d91a8758ff4c416385d6d57cf2e6, 6b041752a00d125a4e651aa56f6abae0e06a59b6 and c0d2c82528e19a304164dade96e9b019114b8fb0
=> attendedsysupgrade backports for 21.02

admin/sudo/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/41be1a2de2f84f532a7eb1c11ece99811ca47ba5
Run tested: same version
=> sudo: bump to version 1.9.10

utils/slide-switch/Makefile
Maintainer: me
Compile tested: armvirt-32, 2022-03-06 snapshot sdk; x86-64, 21.02.1 sdk
Run tested: ath79 (GL-AR750), 21.02.1
Description:
=> slide-switch: Update to 1.0.0

lang/php8/Makefile
=> php8: update to 8.1.4

net/horst/Makefile, net/horst/patches/010-ncurses63.patch
=> horst: fix compilation with ncurses 6.3

net/xray-core/Makefile
Maintainer: me
Description:
- #18113
=> [openwrt-21.02] xray-core: Update to 1.5.4

net/rclone/Makefile, net/rclone/patches/010-disable-plugins.patch
Maintainer: @ElonH, me
Run tested: raspberrypi-3b
Description:
- Backported from #18107
=> [openwrt-21.02] rclone: Update to 1.58.0

net/xray-core/Makefile
Maintainer: me
Description:
- #18113
=> [openwrt-22.03] xray-core: Update to 1.5.4

utils/yq/Makefile
Maintainer: me
Description:
- #18114
=> [openwrt-22.03] yq: Update to 4.23.1

lang/golang/golang-build.sh, lang/golang/golang-package.mk, lang/golang/golang-values.mk, lang/golang/golang/Makefile, lang/golang/golang/patches/001-cmd-link-use-gold-on-ARM-ARM64-only-if-gold-is-available.patch
Maintainer: me
Compile tested: armvirt-32 / x86-64, 2022-03-17 snapshot sdk
Run tested: armvirt-32 (qemu), 2022-03-17 snapshot
Description:
=> golang: Update to 1.18, update patch

utils/jq/Makefile
Signed-off-by: Marko Ratkaj <markoratkaj@gmail.com>
Maintainer: me / markoratkaj@gmail.com / <@ratkaj>
Compile tested: bcm27xx, RPi3, OpenWrt master
Run tested: bcm27xx, RPi3, OpenWrt master
Description:
No longer associated with Sartura, old mail is inactive so switching to private email.
Sry for spamming pull requests, will merge once checks pass..
=> jq: update maintainer email

libs/file/Makefile
Signed-off-by: Marko Ratkaj <markoratkaj@gmail.com>
Maintainer: me / markoratkaj@gmail.com / <@ratkaj>
Compile tested: bcm27xx, RPi3, OpenWrt master
Run tested: bcm27xx, RPi3, OpenWrt master
Description:
No longer associated with Sartura, old mail is inactive so switching to private email.
Sry for spamming pull requests, will merge once checks pass..
=> file: update maintainer email

utils/vim/Makefile
Signed-off-by: Marko Ratkaj <markoratkaj@gmail.com>
Maintainer: me / markoratkaj@gmail.com / <@ratkaj>
Compile tested: bcm27xx, RPi3, OpenWrt master
Run tested: bcm27xx, RPi3, OpenWrt master
Description:
No longer associated with Sartura, old mail is inactive so switching to private email.
Sry for spamming pull requests, will merge once checks pass..
=> vim: update maintainer email

multimedia/gst1-libav/patches/020-ffmpeg5.patch
=> gst1-libav: fix compilation with ffmpeg5

utils/yq/Makefile
Maintainer: me
Description:
- Backported from: #18175
=> [openwrt-22.03] yq: Update to 4.24.2

net/nextdns/Makefile
=> nextdns: Update to version 1.37.11

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.37.11

utils/domoticz/Makefile, utils/domoticz/patches/990-python3.10_fix.patch, utils/domoticz/patches/991-linux_crash_when_formating_py.patch, utils/domoticz/patches/992-prevent_crash_processing_py.patch, utils/domoticz/patches/994-compile_err_whitout_py.patch, utils/domoticz/patches/995-make_sure_compile_works_without_py.patch
change to codeload
backport python 3.10 plugin loading
Tested x86_64
=> domoticz: update to 2022.1

net/xfrpc/Makefile, net/xfrpc/files/xfrpc.conf, net/xfrpc/files/xfrpc.init
Maintainer: me
Compile tested: x86/64, OpenWrt SNAPSHOT r19355-80f79beb95
Run tested: x86/64, OpenWrt SNAPSHOT r19355-80f79beb95
Description:
Description:
xfrpc is a fast reverse proxy client rewriting in c language
compared with golang frpc, xfrpc can run on almost all devices supporting openwrt system
=> xfrpc: fast reverse proxy client in c language

net/pdns-recursor/Makefile, net/pdns/Makefile, net/pdns/patches/100-pdns-disable-pdns.conf-dist.patch
Maintainer: me
Compile tested: right here in Github Actions
Run tested: on Docker/amd64
Description:
=> pdns, pdns-recursor: update to 4.6.2

devel/flex/Makefile, devel/flex/patches/100-disable-tests-docs.patch, devel/flex/patches/200-build-AC_USE_SYSTEM_EXTENSIONS-in-configure.ac.patch
=> flex: new package

devel/bison/Makefile
=> bison: new package

net/pdns-recursor/patches/300-cve-2022-27227.patch, net/pdns/patches/200-cve-2022-27227.patch
Maintainer: me
Compile tested: pending in CI for this PR
Run tested: will do that later
Description:
https://doc.powerdns.com/recursor/security-advisories/powerdns-advisory-2022-01.html
=> pdns, pdns-recursor: patch for  CVE-2022-27227

utils/yq/Makefile, utils/yq/test.sh
Maintainer: me
Description:
- #18294
- #18306
=> [openwrt-22.03] yq: Update to 4.24.5

utils/yq/Makefile, utils/yq/test.sh
Maintainer: me
Run tested: raspberrypi 3b
Description:
- #18294
- #18306
=> [openwrt-21.02] yq: Update to 4.24.5

utils/ubnt-manager/files/ubnt-manager.sh
Maintainer: @PolynomialDivision
=> ubnt-manager: run through shellcheck

net/xray-core/Makefile
Maintainer: me
Description:
- #18368
=> [openwrt-21.02] xray-core: Update to 1.5.5

net/cloudreve/Makefile
Maintainer: me
Description:
- Backported from #18329
=> [openwrt-22.03] cloudreve: Update to 3.5.1

net/xray-core/Makefile
Maintainer: me
Description:
- #18368
=> [openwrt-22.03] xray-core: Update to 1.5.5

lang/php8/Makefile
Maintainer: me
Run tested: -
Description:
=> php8: update to 8.1.5

net/dnsdist/Makefile
Maintainer: me
Run tested: cherrypicked from master where I tested this - will test this one after build too
Description:
=> dnsdist 1.7.1 (for 22.03)

.github/issue_template
Maintainer: @aparcar et al
Description:
Hi all,
Fix a typo in issue template.
Kind regards,
Seb
=> github: fix typo in issue template

utils/podman/Makefile
Once again, a huge list of changes.
List of changes available at:
https://github.com/containers/podman/releases
=> podman: update to 4.1.0

libs/vips/Makefile
=> vips: update to 8.12.2

libs/openldap/Makefile
=> openldap: update to 2.6.2

lang/luaexpat/Makefile
=> luaexpat: update to 1.4.1

net/dmapd/Makefile
=> dmapd: update to 0.0.91

utils/hexedit/Makefile
Viewer and editor in hexadecimal or ASCII for files or devices
Signed-off-by: Nita Vesa <werecatf@outlook.com>
Maintainer: me
Compile tested: ath79, ramips, amd64, OpenWrt 21.02.3 and ipq40xx on trunk
Run tested: ath79 and amd64 on OpenWrt 21.02.3, ipx40xx on trunk
=> hexedit: Add new package

.github/workflows/multi-arch-test-build.yml
Description:
Fixes https://github.com/openwrt/packages/issues/15267.
=> ci: Look for changed packages in the PR branch only

.github/workflows/multi-arch-test-build.yml
Description:
Fixes https://github.com/openwrt/packages/issues/15267.
(cherry picked from commit 6b2294ac379ecae55993a8faa583910423f620e7)
=> [openwrt-21.02] ci: Look for changed packages in the PR branch only

.github/workflows/multi-arch-test-build.yml
Description:
This version builds packages as a normal user instead of as root.
=> ci: Use openwrt/gh-action-sdk@v5

.github/workflows/multi-arch-test-build.yml
Reverts openwrt/packages#18566
=> Revert "ci: Use openwrt/gh-action-sdk@v5"

net/frr/Makefile
=> frr: drop elfutils/host dependency

net/acme/files/run.sh
Use nft instead of iptables to open port 80 in the firewall when getting a
cert. Since nft doesn't allow deleting a rule by its contents, capture and
save the handle when creating the rule, and use that to delete.
-------
Maintainer: me
Run tested: nope
=> acme: switch from iptables to nft

lang/node/Makefile, lang/node/patches/003-path.patch, lang/node/patches/004-musl_support.patch, lang/node/patches/007-fix_host_build_on_macos.patch, lang/node/patches/010-execvp-arg-list-too-long.patch, lang/node/patches/999-cast_for_mips32.patch, lang/node/patches/999-delete_unnecessary_libraries_for_host_execute.patch, lang/node/patches/999-deps-v8-src-trap-handler-trap-handler.h.patch, lang/node/patches/999-localhost-no-addrconfig.patch, lang/node/patches/999-v8_zlib_support.patch
 Run tested: (qemu 6.2.0) arm
Description:
This update also changes npm from v6 to v8.
This change also requires node module packages to be modified.
Each package will be updated later.
(cherry picked from commit 28be0c92c2f883df59b346631868d45c215098f4)
=> [22.03] node: Major update from v14 to v16

net/openconnect/Config.in, net/openconnect/Makefile, net/openconnect/files/openconnect.sh
Details in each commit message. I don't believe any of them is controversial. :)
Run tested: mediatek/mt7622 (Belkin RT3200)
=> openconnect: three misc fixes

net/dnsproxy/Makefile
Maintainer: me
Description:
- #18601
- #18612
=> [openwrt-22.03] dnsproxy: Update to 0.43.0

.circleci/Dockerfile, .circleci/config.yml
Maintainer: @champtar, @thess
Description:
=> CircleCI: Add 22.03 public keys, 18.06 v2 gpg key, 18.06 usign key

net/strongswan/files/swanctl.init
Maintainer: @pprindeville @Thermi
Run tested: aarch64-cortexa53 OpenWrt 22.03-rc1 (Linksys E8400)
Description: Cherry-pick of #18390 for OpenWrt 22.03.
=> strongswan: support child rekey by bytes and packets

lang/php8/Makefile
=> php8: update to 8.1.6

libs/nss/Makefile, libs/nss/patches/003-openwrt_fix.patch
=> nss: update to 3.78

libs/nspr/Makefile
=> nspr: update to 4.34

net/libreswan/Makefile
=> libreswan: update to 4.7

net/pdns-recursor/Makefile, net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch
(cherry picked from commit b6247214350e67d9e16dcb3016a47b51f838bc2c)
Maintainer: me
Run tested:
Description:
=> [openwrt-22.03] pdns-recursor: update to 4.7.0

lang/php8/Makefile
=> [22.03] php8: update to 8.1.6

net/openfortivpn/Makefile
=> openfortivpn: update to 1.17.3

net/xray-core/Makefile, net/xray-core/patches/010-Fix-build-in-legacy-golang-version.patch
Maintainer: me
Description:
- Backported from: #18637
- Added an upstreamed patch to fix build in go 1.17.
=> [openwrt-21.02] xray-core: Update to 1.5.6

utils/yq/Makefile
Maintainer: me
Description:
- Backported from: #18638
=> [openwrt-22.03] yq: Update to 4.25.2

admin/openwisp-config/Makefile
=> [OpenWrt 19.07] openwisp-config: update to 1.0.0

net/openconnect/Makefile, net/openconnect/files/openconnect.sh
Miscellaneous improvements for the OpenConnect netifd protocol plug-in. Details in each commit message.
Run tested:
ramips/mt7621 (Redmi AC2100)
=> openconnect: netifd plug-in improvements

libs/libndpi/Makefile
- removed clunky sed patching, issue was fixed upstream
Signed-off-by: lns <matzeton@googlemail.com>
Maintainer: me
=> libndpi: update to 4.2

utils/miniflux/Makefile
Maintainer: me
Run tested: armv7l, Turris Omnia, OpenWrt master
=> miniflux: update to 2.0.37

libs/libtirpc/Makefile, net/nfs-kernel-server/Makefile
=> libtirpc: don't build host shared libraries

net/cshark/patches/010-gcc12.patch
=> cshark: fix compilation with GCC12

utils/prometheus-node-exporter-lua/Makefile, utils/prometheus-node-exporter-lua/files/etc/config/prometheus-node-exporter-lua, utils/prometheus-node-exporter-lua/files/etc/init.d/prometheus-node-exporter-lua, utils/prometheus-node-exporter-lua/files/usr/bin/prometheus-node-exporter-lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/hostapd_ubus_stations.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/netclass.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/openwrt.lua
Maintainer: me
Compile/run tested: Turris Omnia / 22.03-SNAPSHOT, r19441-3cfe050c4a
=> [22.03] prometheus-node-exporter-lua: backport recent commits

net/dnsdist/Makefile
Maintainer: me
Run tested: 
Description:
=> dnsdist: update to 1.7.2

lang/python/django/Makefile
(cherry picked from commit b9a47cc470b19346049d394d4992f5ebdada0702)
=> [22.03] django: bump to version 4.0.5

net/v2raya/Makefile, net/v2raya/files/v2raya.init
Maintainer: me
Run tested: rdmi ax6s
Description:
- Backported from #18776
=> [openwrt-22.03] v2raya: Update to 1.5.8.1

libs/libowfat/Makefile, libs/libowfat/patches/020-cflags.patch
=> libowfat: try to fix compilation under ARC

net/xray-core/Makefile
Maintainer: me
Description:
- #18783
=> [openwrt-22.03] xray-core: Update to 1.5.8

lang/luajit/Makefile, lang/luajit/patches/040-softfloat-ppc.patch, lang/luajit/patches/050-ppc-softfloat.patch, lang/luajit/patches/060-ppc-musl.patch
=> luajit: backport softfloat ppc support

utils/fish/Makefile
Various other cleanups.
Maintainer: @jqqqqqqqqqq 
Compile tested: arm
=> fish: update to 3.5.0

multimedia/yt-dlp/Makefile
=> yt-dlp: update to 2022.6.22.1

admin/openwisp-config/Makefile
=> openwisp-config: update to 1.0.1

net/acme/files/run.sh
Use nft instead of iptables to open port 80 in the firewall when getting a
cert. Since nft doesn't allow deleting a rule by its contents, capture and
save the handle when creating the rule, and use that to delete.
Signed-off-by: Toke Høiland-Jørgensen <toke@toke.dk>
(cherry picked from commit d926da5182a4547e5248dad3e3e59abcd41d126f)
Run tested: Fritzbox 3370, 22.03.0-rc1
Backported to 22.03 since nft is the default there
=> [22.03] acme: switch from iptables to nft (backport)

admin/openwisp-monitoring/Makefile
=> [19.07] openwisp-config: update to 1.0.1

admin/openwisp-config/Makefile
=> [21.02] openwisp-config: update to 1.0.1

libs/gnutls/Makefile
Maintainer: @bobafetthotmail 
None of the patches got upstreamed?
=> gnutls: update and cleanups

net/zerotier/Makefile, net/zerotier/patches/0001-fix-makefile.patch, net/zerotier/patches/0002-fix-compilation-for-arm_cortex-a7-neon.patch
Maintainer: me
Run tested: Nexx 3020
Zerotier starts and connects to the public demo network-.
=> zerotier: update to 1.10.1

libs/libndpi/Makefile
Maintainer: me / @utoni
Compile tested: mvebu, ARMv7, r19971+10-416d4483e8
Run tested: mvebu, ARMv7, r19971+10-416d4483e8
=> libndpi: update to 4.4

net/pdns/Makefile
=> pdns: update to 4.6.3

net/spoofer/Makefile
=> spoofer: update to 1.4.8

net/pdns-recursor/Makefile, net/pdns/Makefile
Maintainer: me
Compile tested: on master
Run tested: x864_64 docker
Description:
22.03 backport of #18923 and #18924
=> [22.03] pdns 4.6.3, pdns-recursor 4.71

net/xray-core/Makefile
Maintainer: me
Description:
- #18961
=> [openwrt-22.03] xray-core: Update to 1.5.9

net/curl/patches/100-wolfssl.patch
options.h header is needed now.
ping @cotequeiroz
=> curl: fix compilation with wolfSSL

libs/liborcania/Makefile, libs/libulfius/Makefile, libs/libulfius/patches/0001-cmake-pc-orcania-found.patch
Maintainer: me / @utoni
Compile tested: mvebu, ARMv7, r19971+10-416d4483e8
Run tested: mvebu, ARMv7, r19971+10-416d4483e8
=> libulfius: update to 2.7.10

utils/sexpect/Makefile
Signed-off-by: Clark Wang <dearvoid@gmail.com>
Maintainer: Clark Wang <dearvoid@gmail.com>
Compile tested: 21.02.3-ramips-mt7621
Run tested: 21.02.3-ramips-mt7621 (Netgear R6220)
Description:
=> sexpect: updated to 2.3.11

utils/prometheus-node-exporter-lua/Makefile, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/selinux.lua
=> prometheus-node-exporter-lua: Added selinux.lua.

lang/php8/Makefile
=> php8: update to 8.1.9

utils/yq/Makefile
Maintainer: me
Description:
- Backported from: #19124
=> [openwrt-22.03] yq: Update to 4.27.2

net/ariang/Makefile
Maintainer: @Ansuel @neheb
Description:
cherry-pick from: #19163
=> [22.03] ariang: update to 1.2.4

net/frp/Makefile
Run tested: (x86_64, OpenWrt 21.02.3, tests done)
Description:
cherry-pick from: #19162
=> [22.03] frp: update to 0.44.0

net/ddns-scripts/Makefile
Maintainer: @chris5560 / @FlorianFieber ?
Compile tested: N/A, docs change.
Run tested: N/A, docs change.
Description:
Fix a super quick typo.
=> Fix typo in ddns-scripts: s/ganid/gandi/

net/acme-acmesh/files/hook.sh
Signed-off-by: Glen Huang <heyhgl@gmail.com>
Description:
=> acme: Fix acme path

net/knot/Makefile
Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.0 (hbl)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.0 (hbl)
Description:
- Release patch
=> knot: update to version 3.2.0

libs/liburcu/Makefile, libs/liburcu/patches/010-no-tests.patch
Description:
- update of the library
=> liburcu: update to version 0.13.2

net/nginx/Config_ssl.in, net/nginx/Makefile
Maintainer: Thomas Heil
Description:
=> nginx: support gzip static mudule

net/v2raya/Makefile
Maintainer: me
Description:
- Backported from #19243
=> [openwrt-22.03] v2raya: Update to 1.5.9.1698.1

net/ddns-scripts/files/usr/share/ddns/default/simply.com.json, net/ddns-scripts/files/usr/share/ddns/list
Maintainer: @tomsommer
Description:
Add Simply.com ddns provider. Large danish/scandinavian DNS provider
=> ddns-scripts: Add Simply.com provider

net/telnet-bsd/Makefile, net/telnet-bsd/patches/001-telnet-bsd-1.2-fbsd.patch, net/telnet-bsd/patches/002-dont-compile-telnetd.patch, net/telnet-bsd/patches/telnet-bsd-1.2-format-security.patch, net/telnet-bsd/patches/telnet-bsd-1.2-musl.patch
net/telnet-bsd: Add telnet-bsd 1.2 to repo
Patch sources:
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-misc/telnet-bsd/files
https://ftp.uni-erlangen.de/gentoo-portage/net-misc/telnet-bsd/files
Template for excluding telnetd:
https://github.com/theeternalsw0rd/telnet-macos
[set me as maintainer, add patches suggested by @pkgadd]
=> telnet-bsd: add package

utils/yq/Makefile
Maintainer: me
Description:
- Backported from: #19283
=> [openwrt-22.03] yq: Update to 4.27.3

net/xray-core/Makefile
Maintainer: me
Description:
- Backported from: #19284
=> [openwrt-22.03] xray-core: Update to 1.5.10

lang/php8/Makefile
=> php8: update to 8.1.10

multimedia/ffmpeg/Makefile
Bump to latest upstream version
=> ffmpeg: update to 5.1.1

net/v2ray-core/Makefile, net/v2ray-core/files/v2ray.conf, net/v2ray-core/files/v2ray.init, net/v2ray-core/test.sh, net/v2ray-geodata/Makefile, net/xray-core/Makefile
Maintainer: me
Compile tested: ipq40xx/generic, ramips/mt7621, rockchip/armv8, x86/64
Run tested: P&W R619AC / NanoPi R2S / x64 (via VMware)
Description:
Project V is a set of network tools that help you to build your own computer network.
It secures your network connections and thus protects your privacy.
For more details, see https://www.v2fly.org/en_US/guide/faq.html
=> v2ray-core: add new package

net/curl/Config.in, net/curl/Makefile, net/curl/patches/100-wolfssl.patch, net/curl/patches/200-no_docs_tests.patch
Maintainer: me
This reverts commit 312ab68be498f0d895d8d4dc5b2f0fc857e45eb9.
=> curl: Revert "curl: update to 7.85.0"

admin/openwisp-config/Makefile, admin/openwisp-monitoring/Makefile
Not sure if you want gpl-3.0-only or gpl-3.0-or-later for the makefile?
=> openwisp: cleanup Makefiles

libs/libsoup3/Makefile
=> libsoup3: add

libs/libowfat/Makefile, libs/libowfat/patches/030-pure.patch
Ported Fedora patch.
Compile tested: Fedora 37
=> libowfat: fix glibc compilation

net/gatling/Makefile, net/gatling/patches/010-decrease_optimisation.patch, net/gatling/patches/020-configure_features.patch, net/gatling/test.sh
Gatling is a high-performance webserver from fefe. It gives a
fairly decent feature-set at really small size. And its fast.
Signed-off-by: Martin Hübner <martin.hubner@web.de>
Maintainer: me
Compile tested: OpenWrt 21.02.3, ath79/generic, TP-Link Archer C5 v1 and ramips/mt76x8, GL-MT300N v2
Run tested: OpenWrt 21.02.3, ath79/generic, TP-Link Archer C5 v1
=> gatling: add package gatling

net/xray-core/Makefile
Maintainer: me
Description:
- Backported from: #19402
=> [openwrt-22.03] xray-core: Update to 1.6.0

utils/yq/Makefile
Maintainer: me
Description:
- Backported from: #19398
=> [openwrt-22.03] yq: Update to 4.27.5

libs/openblas/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/3f814ecd2408da6ac96f741d3d6331ce93b79734
=> openblas: bump to version 0.3.21

multimedia/ffmpeg/Makefile
Bump to latest upstream version
=> ffmpeg: update to 5.1.2

net/curl/Makefile
Maintainer: me
Description:
* fixes https://github.com/openwrt/packages/issues/19456
(cherry picked from commit c812153f8d4f73b3f82cb19e3b98c84ca680eecb)
=> [22.03] curl: bugfix: github source url

net/nextdns/Makefile, net/nextdns/files/nextdns.defaults
Maintainer: @rs
Backported from master
=> [openwrt-22.03] nextdns: initialize nextdns from /etc/uci-defaults 

net/samba4/Makefile, net/samba4/waf-cross-answers/aarch64.txt, net/samba4/waf-cross-answers/arc.txt, net/samba4/waf-cross-answers/arm.txt, net/samba4/waf-cross-answers/armeb.txt, net/samba4/waf-cross-answers/i386.txt, net/samba4/waf-cross-answers/mips.txt, net/samba4/waf-cross-answers/mips64.txt, net/samba4/waf-cross-answers/mips64el.txt, net/samba4/waf-cross-answers/mipsel.txt, net/samba4/waf-cross-answers/powerpc.txt, net/samba4/waf-cross-answers/powerpc64.txt, net/samba4/waf-cross-answers/riscv64.txt, net/samba4/waf-cross-answers/x86_64.txt
=> samba4: update to 4.14.14

net/acme-acmesh/Makefile, net/acme-common/files/acme.sh
Signed-off-by: Glen Huang <i@glenhuang.com>
Maintainer: me / @tohojo
Description:
=> acme: fix acmesh dnsapi dependencies

net/dnsproxy/Makefile
Maintainer: me
Description:
- #19430
- #19504
=> [openwrt-22.03] dnsproxy: Update to 0.45.2

utils/rrdtool1/Makefile
Signed-off-by: Ryan Shi <qweaszxcdf@users.noreply.github.com>
Description: original source is invalid and it's a working one
fix https://github.com/openwrt/packages/issues/19493
=> rrdtool: update PKG_SOURCE_URL

utils/yq/Makefile
Maintainer: me
Description:
- #19559
=> [openwrt-22.03] yq: Update to 4.28.1

net/v2ray-core/Makefile, net/v2ray-core/files/v2ray.conf, net/v2ray-core/files/v2ray.init, net/v2ray-core/test.sh, net/v2ray-geodata/Makefile, net/xray-core/Makefile
Maintainer: me
Compile tested: mediatek/mt7622, ramips/mt7621, rockchip/armv8, x86/64
Run tested: Redmi AX6S, Newifi D2, NanoPi R4S
Description:
- Backported from: #19327
=> [openwrt-22.03] v2ray-core: add new package

net/arp-scan/Makefile
Maintainer: Sergey Urushkin <urusha.v1.0@gmail.com>
Compile tested: mediatek:mt7622
Run tested: mediatek:mt7622
Signed-off-by: Andrew Sim <andrewsimz@gmail.com>
=> arp-scan: update to latest 1.9.8 

net/mwan3/Makefile, net/mwan3/files/lib/mwan3/mwan3.sh, net/mwan3/files/usr/sbin/mwan3track
Maintainer: me
Description:
- Change log message to debug on already added route
- Only send disconnected event if interface was connected before
=> mwan3: update to version 2.11.3

net/pdns/Makefile, net/pdns/patches/100-pdns-disable-pdns.conf-dist.patch
Maintainer: me
Compile tested: before PRing, in CI (various archs)
Run tested: openwrt master in amd64 docker
Description:
=> pdns: update to 4.7.0

libs/nss/Makefile, libs/nss/patches/003-openwrt_fix.patch, libs/nss/patches/020-getopt.patch
=> nss: update to 4.84

net/libreswan/Makefile, net/libreswan/patches/020-limits.patch
=> libreswan: update to 4.9

net/uacme/Makefile
=> uacme: update to 1.7.3

net/cloudflared/files/cloudflared.init, net/dnsproxy/files/dnsproxy.init, net/v2ray-core/files/v2ray.init, net/v2raya/files/v2raya.init, net/xray-core/files/xray.init
Maintainer: me
Run tested: Redmi AX6S
Description:
- cherry-picked from #19617
=> [openwrt-22.03] treewide: fix procd service inactive

net/openfortivpn/Makefile
=> openfortivpn: update to 1.19.0

lang/node/Makefile, lang/node/patches/003-path.patch, lang/node/patches/999-delete_unnecessary_libraries_for_host_execute.patch, lang/node/patches/999-localhost-no-addrconfig.patch, lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch, lang/node/patches/999-v8_zlib_support.patch
Run tested: (qemu 7.1.0) arm
Description:
Update to v16.18.0
(cherry picked from commit 5851aa8062f5b8a239e241410c144764b8eb1d88)
=> [22.03] node: bump to v16.18.0

net/v2ray-geodata/Makefile, net/xray-core/Makefile
Maintainer: me
Description:
- Cherry-picked from: #19712
=> [openwrt-22.03] xray-core: Update to 1.6.1

lang/luaexpat/Makefile
=> luaexpat: trim trailing spaces

utils/hub-ctrl/Makefile
=> hub-ctrl: trim trailing spaces

net/announce/Makefile
=> announce: trim trailing spaces

net/pdns/Makefile
Maintainer: me
Run tested: Docker openwrt/rootfs on arm64 (pi4)
Description:
=> pdns: update to 4.7.2

libs/libjpeg-turbo/Makefile
=> libjpeg-turbo: update to 2.1.4

utils/yq/Makefile
Maintainer: me
Description:
- Cherry-picked from: #19751
=> [openwrt-22.03] yq: Update to 4.29.2

libs/liblz4/Makefile
=> liblz4: update to 1.9.4

libs/libtins/Makefile
=> libtins: update to 4.4

sound/owntone/Makefile
Maintainer: me
Compile tested: x86_64, r18609
Run tested: no
Description:
Version update
=> owntone: Update to 28.5

net/squid/Config.in
=> squid: trim trailing space

net/lynx/Makefile
=> lynx: trim trailing space

net/mini_snmpd/Makefile
=> mini_snmpd: trim trailing spaces

libs/libupnpp/Makefile
=> libupnpp: update to 0.22.2

libs/libvpx/Makefile
=> libvpx: update to 1.12.0

libs/libgpg-error/Makefile, libs/libgpg-error/patches/010-add-arc-support.patch
=> libgpg-error: update to 1.46

libs/libfido2/Makefile
=> libfido2: update to 1.12.0

libs/libdrm/Makefile, libs/libdrm/patches/010-64bit.patch
=> libdrm: update to 2.4.114

libs/libuhttpd/Makefile, libs/libuhttpd/patches/100-wolfssl_5_support.patch
=> libuhttpd: update to 3.14.1

libs/tiff/Makefile
=> tiff: update to 4.4.0

libs/libxerces-c/Makefile
=> libxerces-c: update to 3.2.4

libs/speex/Makefile
=> speex: update to 1.2.1

net/acme-common/files/acme.sh
=> acme: simplify flock usage

net/strongswan/files/swanctl.init
Compile tested: x86_64, generic, HEAD (c3b9f00aaa)
Description:
Issue #19757
=> strongswan: Fix PSK's when using multiple connections

libs/libmaxminddb/Makefile
=> libmaxminddb: update to 1.7.1

net/openthread-br/Makefile, net/openthread-br/files/openthread.conf, net/openthread-br/files/otbr-agent.init, net/openthread-br/patches/999-fixes.patch
Test building OpenThread package against 22.03 branch.
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>
(cherry picked from commit ff49c0c02b290a3939b8a7f25fd58c160a904dbb)
Description:
=> openthread-br: new package

net/v2ray-geodata/Makefile, net/xray-core/Makefile
Maintainer: me
Description:
- Cherry-picked from: #19874
=> [openwrt-22.03] xray-core: Update to 1.6.3

net/gg/Makefile
Maintainer: me
Description:
- Cherry-picked from: #19873
=> [openwrt-22.03] gg: Update to 0.2.14

net/xray-core/Makefile
Maintainer: me
Description:
Cherry-picked from:
- #19284
- #19402
- #19712
- #19784
- #19874
=> [openwrt-21.02] xray-core: Update to 1.6.3

libs/expat/Makefile
=> expat: update to 2.5.0

net/ariang/Makefile
Maintainer: @Ansuel @neheb
Description:
cherry-pick from: #19908
=> [22.03] ariang: update to 1.3.2

lang/php7/Makefile
=> [21.02] php7: update to 7.4.33

net/ariang/Makefile
Maintainer: @Ansuel / Cc: @neheb 
Compile tested: n/a (source files only)
Description:
backport changes from master branch
=> [openwrt-21.02] ariang: update to 1.3.2

net/unbound/Makefile, net/unbound/patches/010-configure-uname.patch, net/unbound/patches/100-example-conf-in.patch
Maintainer: me
Tested: Linksys WRT3200ACM
Description: update to 1.17.0
=> unbound: update to 1.17.0

net/yggdrasil/Makefile
Signed-off-by: George Iv <zhoreeq@users.noreply.github.com>
Description:
minor version bump
=> yggdrasil: bump to 0.4.7

net/https-dns-proxy/Makefile
=> https-dns-proxy: update Makefile package descrition

net/https-dns-proxy/Makefile
Maintainer: me
(cherry picked from commit 0765fb0790e41d9fbee7e22a7e33022dc943d3fd)
=> [22.03] https-dns-proxy: update Makefile package descrition

net/privoxy/Makefile
fixes: #19949
Signed-off-by: Josh Powers <powersj@fastmail.com>
Maintainer:
Description:
=> privoxy: fix postinst missing $

net/librespeed-go/Makefile, net/librespeed-go/files/librespeed-go.config, net/librespeed-go/files/librespeed-go.init
Maintainer: me
Description:
Go backend for LibreSpeed.
https://github.com/librespeed/speedtest-go
=> [RFC] librespeed-go: add new package

lang/php8/Makefile
=> php8: update to 8.1.13

libs/nss/Makefile, libs/nss/patches/010-nanosleep.patch
=> nss: update to 3.85

net/vallumd/Makefile, net/vallumd/patches/001-CMake-skip-git-magic-if-no-.git-dir-exists.patch
Maintainer: me
Download from Codeberg, bump to latest version.
=> vallumd: updates

utils/syncthing/Makefile
=> syncthing: update to 1.22.2

utils/syncthing/Makefile
=> [22.03] syncthing: update to 1.22.2

net/pdns-recursor/Makefile, net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch
Maintainer: me
Run tested: x86_64 docker 
Description:
=> pdns-recursor: update to 4.8.0

net/igmpproxy/Makefile
Maintainer: Jan Pavlinec [jan.pavlinec@nic.cz](mailto:jan.pavlinec@nic.cz) @ja-pa
Description: There is a newer version available for igmpproxy that adds some nice features some may find useful (like me)
=> igmpproxy: update to version 0.4.0

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr.init
Maintainer: me
Compile tested: x86_64, Sophos SG-135, OpenWr 22.03.2
Run tested: x86_64, Sophos SG-135, OpenWr 22.03.2, install, start
Description:
=> pbr: bugfix: Makefile, rt_tables fix

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr.init
Maintainer: me
Compile tested: x86_64, Sophos SG-135, OpenWr 22.03.2
Run tested: x86_64, Sophos SG-135, OpenWr 22.03.2, install, start
(cherry picked from commit edbcb97b78d36a813e6aa04f6b6ff9bc20be2eb3)
=> [22.03] pbr: bugfix: Makefile, rt_tables fix

libs/vips/Makefile
=> vips: update to 8.13.3

lang/luaexpat/Makefile
=> luaexpat: update to 1.5.1

lang/luasec/Makefile
=> luasec: update to 1.2.0

libs/openldap/Makefile, libs/openldap/patches/001-automake-compat.patch
=> openldap: update to 2.6.3

lang/luasocket/Makefile, lang/luasocket/patches/0001-Add-interface-support.patch
=> luasocket: update to 3.1.0

multimedia/gst1-libav/Makefile, multimedia/gst1-plugins-bad/Makefile, multimedia/gst1-plugins-bad/patches/010-distutils.patch, multimedia/gst1-plugins-base/Makefile, multimedia/gst1-plugins-base/patches/010-distutils.patch, multimedia/gst1-plugins-good/Makefile, multimedia/gst1-plugins-good/patches/010-distutils.patch, multimedia/gst1-plugins-ugly/Makefile, multimedia/gst1-plugins-ugly/patches/010-distutils.patch, multimedia/gstreamer1/Makefile, multimedia/gstreamer1/patches/010-gstplugin-use-lazy-symbol-binding.patch, multimedia/gstreamer1/patches/020-distutils.patch
=> gst1-libav through gstreamer1: update to 1.20.4

multimedia/motion/Makefile, multimedia/motion/patches/010-no-po-man.patch
Signed-off-by: Robert N <nrobert13@gmail.com>
Description:
=> motion: update to 4.5.0

net/pbr/Makefile
Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, install pbr
=> pbr: add provides: pbr to variants

libs/libmaxminddb/Makefile
=> libmaxminddb: install pkgconfig file

utils/syncthing/Makefile
=> syncthing: update to 1.23.0

utils/syncthing/Makefile
=> [22.03] syncthing: update to 1.23.0

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/lib/ddns/update_pdns.sh
Maintainer: me
Compile tested: @JFroch manually tested
Closes #20200
=> ddns-scripts: Allow setting root record for pdns script

net/boinc-wrapper/Makefile, net/boinc-wrapper/test.sh
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>
=> boinc-wrapper: add new package

utils/conmon/Makefile, utils/conmon/patches/010-remove-libdl-dep.patch
Description:
[Changelogs](https://github.com/containers/conmon/releases)
=> conmon: update to 2.1.5

multimedia/gphoto2/patches/001-automake-compat.patch
=> gphoto2: fix compilation with BUILD_NLS

mail/alpine/Makefile
=> alpine: fix old URL

net/socat/Makefile
=> socat: update to 1.7.4.4

utils/pigz/Makefile, utils/pigz/patches/001.patch
=> pigz: update to 2.7

utils/pcsc-tools/Makefile, utils/pcsc-tools/patches/001-disable-atr.patch
=> pcsc-tools: update to 1.6.1

net/foolsm/Makefile
=> foolsm: update to 1.0.21

utils/flashrom/Makefile
=> flashrom: update to 1.2.1

lang/python/python3-libsemanage/Makefile
=> python3-libsemanage: fix URL

lang/python/python3-libselinux/Makefile
=> python3-libselinux: fix URL

net/xinetd/Makefile
Something went wrong here. Switch to git tarballs.
=> xinetd: fix URL

libs/libxml2/Makefile, libs/libxml2/patches/010-iconv.patch
=> libxml2: build with cmake

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr.init
Maintainer: me
Compile tested: x86_64, Sophos SG-105, OpenWrt 22.03.3
Run tested: x86_64, Sophos SG-105, OpenWrt 22.03.3, start, verify status
Description:
* improve install/uninstall messages
* fix ips add command
* add boot() to init file
=> pbr: update to 1.0.1-14

utils/stress/Makefile, utils/stress/patches/010-usleep.patch
=> stress: update to 1.0.5

ipv6/miredo/Makefile
Keep miredo.conf modified configuration upon upgrades
Signed-off-by: ValdikSS ValdikSS <iam@valdikss.org.ru>
=> miredo: add miredo.conf conffile

libs/efivar/Makefile, libs/efivar/patches/002-musl-compat.patch, libs/efivar/patches/005-skip-docs.patch
Compile tested: x86-64, recent git
Run tested: x86-64, recent git
Description:
efivar library. Required by my another PR #20277 (efibootmgr)
=> efivar: new package

utils/efibootmgr/Makefile
Compile tested: x86-64, recent git
Run tested: x86-64, recent git
Description:
Linux user-space application to modify the Intel Extensible Firmware Interface (EFI) Boot 
Manager. This application can create and destroy boot entries, change the boot order, change the next running 
boot option, and more.
Depends on my another PR #20276 (efivar library)
=> efibootmgr: new package

net/frp/Makefile, net/frp/test.sh
=> [22.03] frp: update to 0.46.1

libs/libwebp/Makefile, libs/libwebp/patches/010-mips16.patch
Maintainer: me
Compile tested: x86 https://github.com/openwrt/commit/6e3acebe35cfc584e145e495b175ae5308d2f2bc
Run tested: x86 https://github.com/openwrt/commit/6e3acebe35cfc584e145e495b175ae5308d2f2bc
=> libwebp: bump to version 1.3.0

devel/nasm/Makefile
Compile tested: x86-64, recent git
Run tested: x86-64, recent git
Description:
nasm compiler
=> nasm: new package

utils/mv88e6xxx_dump/Makefile
Maintainer: me
Compile tested: mvebu turris omnia / master https://github.com/openwrt/openwrt/commit/2a20dc717a897efe54f241636ee1566b695dbc7d
Run tested: no (I don't have access to my router for now)
Description:
This might help debug issues like https://github.com/openwrt/openwrt/issues/11877
=> mv88e6xxx_dump: add new packages to debug switch issues

utils/mv88e6xxx_dump/Makefile
cherry picked from commit 167c6234d01e72da447e47e2c1b3f7a3195aab83
Maintainer: me
Compile tested: no (on master only)
Run tested: no
Description:
=> [22.03] mv88e6xxx_dump: add new packages to debug switch issues

admin/sudo/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/059263dd6e9bed5cb0f817a9fe0bd287db921200
Run tested: x86 https://github.com/openwrt/openwrt/commit/059263dd6e9bed5cb0f817a9fe0bd287db921200
=> sudo: bump to version 1.9.12p2

net/sing-box/Makefile, net/sing-box/files/sing-box.conf, net/sing-box/files/sing-box.init, net/sing-box/test.sh
Maintainer: me
Compile tested: x86_64 snapshot
Run tested: x86_64 snapshot
=> sing-box: add new package

lang/php8/Makefile
=> [22.03] php8: update to 8.1.15

libs/libgpiod/Makefile
=> libgpiod: update to 1.6.4

libs/nss/Makefile, libs/nss/patches/010-nanosleep.patch
=> nss: update to 3.88.1

net/zerotier/Makefile, net/zerotier/patches/0001-fix-makefile.patch
Maintainer: me
Compile tested: ramips/mt7620, OpenWrt master
Run tested: Nexx wt3020, connect to public network, list peers
=> zerotier: update to 1.10.3

libs/libdrm/Makefile
=> libdrm: update to 2.4.115

utils/gddrescue/Makefile
=> gddrescue: update to 1.27

net/zerotier/Makefile, net/zerotier/patches/0001-fix-makefile.patch
Maintainer: me
Compile tested: ramips/mt7620, OpenWrt master
Run tested: Nexx wt3020, connect to public network, list peers
=> [22.03] zerotier: update to 1.10.3

net/uacme/Makefile
=> uacme: update to 1.7.4

multimedia/gst1-libav/Makefile, multimedia/gst1-plugins-bad/Makefile, multimedia/gst1-plugins-base/Makefile, multimedia/gst1-plugins-base/patches/010-distutils.patch, multimedia/gst1-plugins-good/Makefile, multimedia/gst1-plugins-ugly/Makefile, multimedia/gstreamer1/Makefile, multimedia/gstreamer1/patches/020-distutils.patch
Compile tested: imx6 (cortex a9) - all plugins
Run tested: imx6 (cortex a9)
=> Bumps gstreamer framework to 1.20.5

lang/lua-eco/Makefile
Signed-off-by: Jianhui Zhao [zhaojh329@gmail.com](mailto:zhaojh329@gmail.com)
Maintainer: me
Description:
Release notes for 2.0.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.0.0
=> lua-eco: update to 2.0.0

net/netbird/Makefile, net/netbird/files/netbird.init
NetBird is an open-source VPN management platform built on top of WireGuard® making it easy to create secure private networks for your organization or home. It requires zero configuration effort leaving behind the hassle of opening ports, complex firewall rules, VPN gateways, and so forth.
Description: Netbird is similar vpn service as tailscale and zerotier.
=> netbird: new package

net/v2raya/Makefile, net/v2raya/files/v2raya.config, net/v2raya/files/v2raya.init, net/v2raya/patches/019-fix-simple-obfs.patch, net/v2raya/patches/020-feat-add-nftables-support.patch
Maintainer: me
Description:
Backport a pending PR to add nftables support.
Upstream: https://github.com/v2rayA/v2rayA/pull/805
=> v2raya: backport and switch to nftables

net/pdns-recursor/Makefile
Maintainer: me
Compile tested: in CI
Description:
=> pdns-recursor: update to 4.8.3

net/frp/Makefile, net/frp/files/frpc.init, net/frp/files/frps.init
=> [22.03] frp: update to 0.48.0

libs/protobuf-c/Makefile
=> protobuf-c: update to 1.4.1

.github/workflows/formal.yml, .github/workflows/multi-arch-test-build.yml
Run tested: CI
Description:
- Build packages as a normal user
- Fix actions deprecation warnings
=> [openwrt-21.02] CI: backport changes from master branch

net/netbird/Makefile
Bug fixes & refactor
Release notes:
- Fix: send remote agents updates when peer re-authenticates
=> netbird: update to 0.14.3

lang/rust/Makefile, lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
Maintainer: me
Compile tested: aarch64 master
Run tested: aarch64 master
Description: Version bump
=> rust-lang: Version 1.68.0

net/udpspeeder/Makefile
Maintainer: Nishant Sharma <nishant@hopbox.in>
Compile tested: mvebu, ARMv7, r21599+10-5c7e4a9d2e
Run tested: mvebu, ARMv7, r21599+10-5c7e4a9d2e
=> udpspeeder: bump to 20230206.0

libs/liburcu/Makefile
Description:
- update of the library
=> liburcu: update to version 0.14.0

libs/libndpi/Makefile
Maintainer: me / @utoni
Compile tested: mvebu, ARMv7, r21599+10-5c7e4a9d2e
Run tested: mvebu, ARMv7, r21599+10-5c7e4a9d2e
=> libndpi: Update to 4.6

net/strongswan/Makefile, net/strongswan/patches/0904-gmpdh-Plugin-that-implements-gmp-DH-functions-in-an-.patch
Compile tested: x86_64, generic, HEAD (0a35d3f992)
Run tested: same, deployed to production router
Description:
Update to 5.9.10
=> strongswan: Update to 5.9.10

net/transmission/Makefile
Maintainer: me
Compile tested: arm_cortex-a7
Description: transmission: update to version 4.0.2
=> transmission: update to version 4.0.2

net/dnslookup/Makefile
Maintainer: me
Compile tested: ipq807x/generic
Run tested: redmi-ax6
Description:
Fix build with go1.20
=> dnslookup: Update to 1.9.1

net/sing-box/Makefile
Maintainer: me
Description:
This is a minor version update that contains many new features and some bug fixes.
=> sing-box: update to 1.2.0

utils/cni-plugins-nft/Makefile
Changelog:
- docs: update install instructions
- upgrade to go1.19
Compile tested: x86_64, latest_git
=> cni-plugins-nft: update to 1.0.12

lang/perl-text-csv_xs/Makefile
Maintainer: me
Compile tested: x86_64, generic, HEAD (c98e09f01b)
Run tested: untested
Description:
=> perl-text-csv_xs: Update to 1.50

net/tinyproxy/Makefile, net/tinyproxy/files/tinyproxy.config, net/tinyproxy/files/tinyproxy.init, net/tinyproxy/patches/120-fix_INET6.patch
Maintainer: Jo-Philipp Wich <jo@mein.io>
Compile tested: amd64
Run tested: amd64 tests done
Description:
- Added BasicAuth support
=> tinyproxy: Update to 1.11.1

net/strongswan/Makefile, net/strongswan/files/swanctl.init
Maintainer: @pprindeville @Thermi
Compile tested: 22.03.2 x86-64
Run tested: 22.03.2 x86-64
Description:
Since I got no response, I went ahead and implemented it. This fixes #20663
=> strongswan: add support for pools section

net/sshtunnel/Makefile, net/sshtunnel/files/uci_sshtunnel
Maintainer: Nuno Goncalves <nunojpg@gmail.com>
Compile tested: no, because no code was changed
Run tested: no, because no code was changed
=> sshtunnel: fix type, case and whitespace issues

utils/apk/Makefile, utils/apk/patches/010-openssl-deprecated.patch
Compile tested: ipq807x/generic
Run tested: redmi-ax6
Description:
bump to the latest tag.
=> apk: Update to 2.12.11

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
=> php8: update to 8.2.5

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
=> [22.03] php8: update to 8.1.18

net/dnsdist/Makefile
=> dnsdist: update to 1.8.0

net/obfs4proxy/Makefile
Maintainer: me
Compile tested: armvirt-32, 2023-04-16 snapshot sdk
Description:
=> obfs4proxy: Update to 0.0.14

net/pdns/Makefile
=> pdns: update to 4.7.4

net/pdns-recursor/Makefile
=> pdns-recursor: update to 4.8.4

net/sscep/Makefile
Maintainer: me
Compile tested: No
Run tested: No
Description: Corrected license information as requested here https://github.com/openwrt/packages/pull/20683#issuecomment-1512719443.
=> scep: fix license

utils/qemu/Makefile, utils/qemu/patches/0001-configure-allow-disable-fortify_source.patch, utils/qemu/patches/0007-qga-invoke-separate-applets-for-guest-shutdown-modes.patch, utils/qemu/patches/0010-no-tests.patch
Signed-off-by: Vladimir Ermakov [vooon341@gmail.com](mailto:vooon341@gmail.com)
Compile tested: x86_64, OpenWrt master (https://github.com/openwrt/openwrt/commit/1416b9bbe9d3455c7ab64543a65236fea213a978)
Description:
- Version updated to 8.0.0
- Added option to use ZStd compression
=> qemu: update to 8.0.0
