openwrt/packages

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

Description: Update HAProxy to v2.4.17

[openwrt-22.03] haproxy: Update HAProxy to v2.4.17

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

Description: Update HAProxy to v2.2.24

[openwrt-21.02] haproxy: Update HAProxy to v2.2.24

---

net/vpnc/Makefile

Maintainer: @lipnitsk
Compile tested: arm_cortex-a7_neon-vfpv4, OpenWRT 21.02, docker image openwrtorg/sdk:ipq40xx-generic-21.02.3
Run tested: arm_cortex-a7_neon-vfpv4, OpenWRT 21.02 on Teltonika RUTX08, installed compiled package, connected to two different VPN concentrators using dh2, dh5 and dh14 key exchange groups
Description:
The new version of vpnc supports additional DH groups for improved key exchange security.
See #18565

vpnc: Update to 0.5.3+git20220517

---

net/stubby/files/stubby.init

Force restart stubby if any of the trigger interfaces goes up or down.
Avoids DoT DNS lookup timeouts when default route changes, in case of multiple
upstream interfaces.
Run tested: latest 22.03, two upstream wan interfaces in stubby "trigger" config in /etc/config/stubby

stubby: restart on trigger interfaces

---

devel/gcc/Makefile

Maintainer: me
Description:
Should fix https://github.com/openwrt/packages/pull/18532#issuecomment-1137816824.

gcc: depend on libzstd

---

net/vpnc/Makefile

Maintainer: @lipnitsk
Compile tested: arm_cortex-a7_neon-vfpv4, OpenWRT 21.02, docker image openwrtorg/sdk:ipq40xx-generic-21.02.3
Run tested: arm_cortex-a7_neon-vfpv4, OpenWRT 21.02 on Teltonika RUTX08, installed compiled package, connected to two different VPN concentrators using dh2, dh5 and dh14 key exchange groups
Description:
The new version of vpnc supports additional DH groups for improved key exchange security.
See #18565

[openwrt-22.03] vpnc: Update to 0.5.3+git20220517

---

net/vpnc/Makefile

Maintainer: @lipnitsk
Compile tested: arm_cortex-a7_neon-vfpv4, OpenWRT 21.02, docker image openwrtorg/sdk:ipq40xx-generic-21.02.3
Run tested: arm_cortex-a7_neon-vfpv4, OpenWRT 21.02 on Teltonika RUTX08, installed compiled package, connected to two different VPN concentrators using dh2, dh5 and dh14 key exchange groups
Description:
The new version of vpnc supports additional DH groups for improved key exchange security.

[openwrt-21.02] vpnc: Update to 0.5.3+git20220517

---

lang/node/Makefile

 Compile tested: 21.02, arm
 Run tested: (qemu 6.2.0) arm
Description:
Updates OpenSSL to 1.1.1o (No impact in openwrt)
Upgrade npm to v6.14.17.
etc...

[21.02] node: bump to v14.19.3

---

net/dnslookup/Makefile

Maintainer: me
Compile tested: rockchip
Description:
- Backported from: #18613

[openwrt-22.03] dnslookup: Update to 1.7.0

---

lang/php8/Makefile

[21.02] php8: update to 8.0.19

---

net/cloudflared/Makefile

Maintainer: me
Description:
Release note:
- https://github.com/cloudflare/cloudflared/commit/08a8101308a4d32cf53e13940afeea49b49fbc42
- https://github.com/cloudflare/cloudflared/commit/919227fc91ba0be49a14111ffbda6f012fd2f8a2

cloudflared: Update to 2022.5.3

---

utils/yq/Makefile

Maintainer: me
Description:
Release note: https://github.com/mikefarah/yq/releases/tag/v4.25.2

yq: Update to 4.25.2

---

net/xray-core/Makefile

Maintainer: me
Description:
Updated geodata to latest version while at it.
Release note: https://github.com/XTLS/Xray-core/releases/tag/v1.5.6

xray-core: Update to 1.5.6

---

net/pdns-recursor/Makefile
net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch

Maintainer: me
Compile tested: waiting for CI
Run tested: will do that after CI build
Description:

pdns-recursor: update to 4.7.0

---

.github/workflows/multi-arch-test-build.yml

Description:
The previous build errors with v5 have been fixed. This version builds packages as a normal user instead of as root.

ci: Use openwrt/gh-action-sdk@v5

---

lang/node/Makefile
lang/node/patches/003-path.patch
lang/node/patches/999-localhost-no-addrconfig.patch

Compile tested: head, aarch64, arm, i386, x86_64, mipsel (pistachio)
 Run tested: (qemu 7.0.0) aarch64
Description:
Update from  v16.15.0
Changed handling of host's npm problems due to npm updates.

node: bump to v16.15.0

---

utils/yq/Makefile

Maintainer: me
Description:
- Backported from: #18638

[openwrt-21.02] yq: Update to 4.25.2

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream update.
What's Changed:
- fix TestLocalComposeUp which fail locally and bump compose-go to
1.2.7 by @glours
- attach only to services declared by project applying profiles by
@ndeloof
- Add ddev's e2e test by @ulyssessouza
- Fix local run of make e2e-compose-standalone by @ulyssessouza
- fix: prevent flickering prompt when pulling same image from N
services by @maxcleme
- add tags property to build section by @glours
- update golang version to 1.18 by @glours
- bump compose-go to 1.2.6 by @maxcleme
- add e2e tests to verify env variables priority by @glours
- Import dotenv file to os environment by @ulyssessouza
New Contributors:
- @maxcleme made their first contribution
Signed-off-by: Javier …

docker-compose: Update to version 2.6.0

---

libs/openblas/Makefile

Run tested: riscv64
Description:
Specify target as RISCV64_GENERIC when compiling the package on a riscv64 target. (C910V wouldn't work as the SoCs covered by the sifiveu target don't have the V instruction set extension.)
Signed-off-by: Zoltan HERPAI <wigyori@uid0.hu>

openblas: compile with RISCV64_GENERIC target on riscv64 arch

---

net/yggdrasil/files/yggdrasil.init

Maintainer:  @aparcar 
Compile tested: 22.03, mips24kc, mikrotik hap
Run tested: 22.03, mips24kc, mikrotik hap
Description:
Previously it was using killall with procd respand enabled
This was causing yggdrasil to restart after being killed
```
root@r3test-hap:/# service yggdrasil stop ; echo $? ; sleep 10s ; ps | grep yggdrasil
Terminated
143
6701 root      653m S    /usr/sbin/yggdrasil -useconffile /tmp/yggdrasil.conf
6748 root      1308 S    grep yggdrasil
```
Now it's just using whatever procd is using and see there, it actually stops
```
root@r3test-hap:/# service yggdrasil stop ; echo $? ; sleep 10s ; ps | grep yggdrasil
0
6802 root      1308 S    grep yggdrasil
```
I assume there was some procd bug that kept it from being used properly

yggdrasil: stop properly

---

net/yggdrasil/files/yggdrasil.init

Previously it was using killall with procd respand enabled
This was causing yggdrasil to restart after being killed
root@r3test-hap:/# service yggdrasil stop ; echo $? ; sleep 10s ; ps | grep yggdrasil
Terminated
143
6701 root      653m S    /usr/sbin/yggdrasil -useconffile /tmp/yggdrasil.conf
6748 root      1308 S    grep yggdrasil
Now it's just using whatever procd is using and see there, it actually stops
root@r3test-hap:/# service yggdrasil stop ; echo $? ; sleep 10s ; ps | grep yggdrasil
0
6802 root      1308 S    grep yggdrasil
I assume there was some procd bug that kept it from being used properly
Signed-off-by: Maciej Krüger <mkg20001@gmail.com>
(cherry picked from commit 17bb2d25191704d0526bd1bdc0e9060dbf02e12b)
Compile tested: 22.03, mips24kc, mikrotik hap …

[22.03] yggdrasil: stop properly

---

net/samba4/waf-cross-answers/riscv64.txt

Description:
Add waf-cross-answers for compiling on riscv64 arch, required for sifiveu target.
Signed-off-by: Zoltan HERPAI <wigyori@uid0.hu>

samba4: add riscv64 support

---

libs/libndpi/Makefile

libndpi: fix pcre2 dependency name

---

net/ksmbd-tools/Makefile

Major changes are:
Add support for Heimdal as the Kerberos 5 implementation.
Add smbd max io size parameter.
Accept global share options.

ksmbd-tools: update to 3.4.5

---

utils/ntfs-3g/Makefile

ntfs-3g: update to 2022.5.17

---

libs/glib2/Makefile
libs/glib2/patches/007-openwrt-libintl.patch

glib2's meson.build runs check cc.has_function('ngettext', args :
osx_ldflags) and, if successful, it never looks for non-libc libintl.
For musl and glibc this test is always successful.
glib2 unconditionally sets ENABLE_NLS, so during compile <libintl.h>
gets included always. But then we have a disconnect when the OpenWrt pkg
is being built with BUILD_NLS=y, because the <libintl.h> will be from
libintl-full but glib2 will not link to libintl-full.
With BUILD_NLS=n there's no problem, because the <libintl.h> will be
from libc.
In lieu of proper libintl detection in glib2's meson build, removing the
SED call from the Makefile together with the added patch sorts this out.
The SED call can be removed because when we force libintl-full use, the
meson build will put the necessary linker flag …

glib2: update libintl handling

---

net/netatalk/Makefile
net/netatalk/patches/100-fix-segfaults.patch

Maintainer: nobody, last updated by @dangowrt 
Compile tested: Turris Omnia, mvebu/cortex-a9, OpenWrt 21.02.3
Run tested: N/A, confirmed to be working across multiple GNU/Linux distributions
Description:
This commit backports pending PR, which solves segfaults:
- https://github.com/Netatalk/Netatalk/pull/174
To fix issues with segfaults described here:
- https://github.com/openwrt/packages/issues/18571
- https://github.com/Netatalk/Netatalk/issues/175

patches/packages: netatalk: backport pending PR to fix segfaults

---

net/xray-core/Makefile

Maintainer: me
Description:
Release note: https://github.com/XTLS/Xray-core/releases/tag/v1.5.7

xray-core: Update to 1.5.7

---

utils/beep/Makefile
utils/beep/patches/0001-GNUmakefile-comment-out-D_FORTIFY_SOURCE.patch

Maintainer: n/a
Compile tested: OpenWrt 21.02.03, Turris Omnia, mvebu/cortex-a9 and Rasberry Pi 4 CM, OpenWrt master
Description:
My commit was sitting for some time in my stash and I did not have time to finish it. Let's solve it once for all.
Changed Git repository, which is used for Fedora packaging
https://github.com/johnath/beep/issues/11#issuecomment-450277122
Fixed CVEs:
CVE-2018-0492 - https://nvd.nist.gov/vuln/detail/CVE-2018-0492
CVE-2018-1000532 - https://nvd.nist.gov/vuln/detail/CVE-2018-1000532
cc: @zpc0 who were findling around this package
Related to https://github.com/openwrt/packages/pull/18697 which was created in the same repository, where force pushes are not allowed.

beep: change git repository includes CVE fixes

---

net/xray-core/files/xray.init

Maintainer: me
Description:
This fixes "too many open files" error caused by max-file limitation
when xray processes large traffic.
Fixes: #18701

xray-core: increase nofile limitation

---

net/dnsproxy/Makefile

Maintainer: me
Description:
Release note: https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.43.1

dnsproxy: Update to 0.43.1

---

net/dnsproxy/Makefile

Maintainer: me
Description:
- #18704

[openwrt-22.03] dnsproxy: Update to 0.43.1

---

net/xray-core/Makefile
net/xray-core/files/xray.init

Maintainer: me
Description:
- #18694
- #18705

[openwrt-22.03] xray-core: Update to 1.5.7

---

net/memcached/Makefile

memcached: update to 1.6.15

---

lang/node/Makefile
lang/node/patches/003-path.patch
lang/node/patches/999-localhost-no-addrconfig.patch

 Compile tested: 22.03, arm
 Run tested: (qemu 7.0.0) arm
Description:
Update from  v16.15.0
Changed handling of host's npm problems due to npm updates.
(cherry picked from commit fcfd2599d9fad84301a42b9597e9a71bdd0f267f)

[22.03] node: bump to v16.15.0

---

net/udpspeeder/files/udpspeeder-init

udpspeeder support a simple xor encryption, add the option to its init script
```
common options, must be same on both sides:
-k,--key              <string>        key for simple xor encryption. if not set, xor is disabled
```

udpspeeder: add key option

---

net/openvpn/Makefile
net/openvpn/patches/002-add-wolfssl-support.patch
net/openvpn/patches/100-mbedtls-disable-runtime-version-check.patch
net/openvpn/patches/210-build_always_use_internal_lz4.patch
net/openvpn/patches/220-disable_des.patch

Maintainer: me / @mkrkn 
Compile tested: ramips/mt7620 TP-Link Archer C50 v1, ramips/mt7621 Xiaomi Mi router 3 Pro, ath79/generic TP-Link WDR-3500
Run tested: ramips/mt7620 TP-Link Archer C50 v1, ramips/mt7621 Xiaomi Mi router 3 Pro, ath79/generic TP-Link WDR-3500
Added limited support for OpenSSL 3.0
Fixed some bugs

openvpn: update to 2.5.7

---

utils/mqttled/Makefile
utils/mqttled/files/mqttled.config
utils/mqttled/files/mqttled.init

Maintainer: me
Compile tested: mips_24kc / 21.02.03 / Lenovo Y1
Run tested: mips_24kc / 21.02.03 / Lenovo Y1
PyPi: https://pypi.org/project/mqttled/
Description:
Control of LEDs through MQTT. Published LED information to MQTT broker. Sub'd to the broker and translates commands to manual LED control through echo 'trigger' > /sys/class/leds/led/trigger
Configured through UCI

New Package: mqttled-0.1.0

---

lang/node/Makefile
lang/node/patches/999-delete_unnecessary_libraries_for_host_execute.patch
lang/node/patches/999-v8_zlib_support.patch

Compile tested: head, aarch64, arm, i386, x86_64, mipsel (pistachio)
 Run tested: (qemu 7.0.0) aarch64
Description:
Upgrade npm to 8.11.0
Suppressed unnecessary builds.

node: bump to v16.15.1

---

libs/libpsl/Makefile
libs/libpsl/patches/020-iconv.patch

Was needed with the Autotools build.

libpsl: remove iconv link flag

---

net/ksmbd-tools/Makefile
net/ksmbd-tools/patches/010-meson.patch

Fixes compilation without libiconv-stub.

ksmbd-tools: only add -liconv with BUILD_NLS

---

lang/node/Makefile
lang/node/patches/999-delete_unnecessary_libraries_for_host_execute.patch
lang/node/patches/999-v8_zlib_support.patch

 Run tested: (qemu 7.0.0) arm
Description:
Upgrade npm to 8.11.0
Suppressed unnecessary builds.
(cherry picked from commit d8dc54ceea04070a6999c5a3b2e86225fec0d498)

[22.03] node: bump to v16.15.1

---

multimedia/ttymidi-sysex/Makefile
multimedia/ttymidi-sysex/files/ttymidi-sysex.defaults
multimedia/ttymidi-sysex/files/ttymidi-sysex.init

This adds an improved version of [ttymidi](https://github.com/cjbarnes18/ttymidi) with full support for SysEx MIDI messages.

ttymidi-sysex: add package

---

multimedia/rtpmidid/Makefile
multimedia/rtpmidid/files/rtpmidid.init

Add RTP MIDI server package allowing to import/export local MIDI clients or hardware devices to the local network using Apple's RTP MIDI protocol.

rtpmidid: add package

---

utils/telegraf/Makefile

Maintainer:
me
Run tested:
Description:
Add package with version 1.23.0

telegraf: update to version 1.23.0

---

utils/telegraf/Makefile

(cherry picked from commit e8f6600851557f89a77389db7840ce0a45494df7)
Maintainer:
me
Run tested:
Description:
Add package with version 1.23.0 on openwrt 21.02

[21.02] telegraf: update to version 1.23.0

---

utils/telegraf/Makefile

(cherry picked from commit e8f6600851557f89a77389db7840ce0a45494df7)
Maintainer:
me
Run tested:
Description:
Add package with version 1.23.0 on openwrt 22.03

[22.03] telegraf: update to version 1.23.0

---

net/dnsdist/Makefile

(cherry picked from commit 573829d625fecdd90e3a7e3e7f195e7d8875833a)
Maintainer: me
Run tested:
Description:

[22.03] dnsdist: update to 1.7.2

---

utils/prometheus-node-exporter-lua/Makefile
utils/prometheus-node-exporter-lua/files/etc/init.d/prometheus-node-exporter-lua

Maintainer: me
Compile/Run tested: tested by @Hurricos
Description:
Instead of waiting for interface to be up,
wait for it to have IPs, as this is what we need.
Also do not call procd_open_instance when not ready.

prometheus-node-exporter-lua: fix waiting for interface

---

utils/prometheus-node-exporter-lua/Makefile
utils/prometheus-node-exporter-lua/files/etc/init.d/prometheus-node-exporter-lua

Maintainer: me
Compile / run tested: turris omnia
Description:
Instead of waiting for interface to be up,
wait for it to have IPs, as this is what we need.
Also do not call procd_open_instance when not ready.
Signed-off-by: Etienne Champetier <champetier.etienne@gmail.com>
(cherry picked from commit 1dd46bca627a876158a05be14a0c91948d037445)

[22.03] prometheus-node-exporter-lua: fix waiting for interface

---

sound/owntone/Makefile
sound/owntone/files/owntone.conf

Maintainer: me
Compile tested: x86_64, r18609
Run tested: no
Description:
Update to 28.4, incl. install web UI, remove libantlr3c dependency, add Spotify support to description, update conf file

owntone: update to 28.4

---

net/v2raya/Makefile
net/v2raya/files/v2raya.init

Maintainer: me
Description:
1. Switched to use prebuilt web files to get rid of massive Node.js.
2. Increased nofile limitation to avoid "too many open files" error.
Release note: https://github.com/v2rayA/v2rayA/releases/tag/v1.5.8.1

v2raya: Update to 1.5.8.1

---

net/cloudflared/Makefile

Maintainer: me
Description:
Release note:
- https://github.com/cloudflare/cloudflared/commit/6c3d2fc33977e4de6309d478c704d008751efc36
- https://github.com/cloudflare/cloudflared/commit/7d0a2710003588a58b2535270624d0db571ea9df
- https://github.com/cloudflare/cloudflared/commit/420e80ea501d532365955e8383d4bfffd1078602

cloudflared: Update to 2022.6.2

---

net/unbound/Makefile
net/unbound/patches/010-configure-uname.patch

Signed-off-by: Stijn Segers <foss@volatilesystems.org>
Compile tested: mvebu/cortexa72, RB5009UG+S+IN
Run tested: mvebu/cortexa72, RB5009UG+S+IN
Description: Update to 1.16.0

unbound: update to 1.16.0

---

net/xray-core/Makefile

Maintainer: me
Description:
Release note: https://github.com/XTLS/Xray-core/releases/tag/v1.5.8

xray-core: Update to 1.5.8

---

net/cloudflared/Makefile

Maintainer: me
Run tested: rdmi ax6s
Description:
- Backported from #18775

[openwrt-22.03] cloudflared: Update to 2022.6.2

---

net/ksmbd-tools/Makefile
net/ksmbd-tools/patches/010-meson.patch

It changed the binaries from sbin to bin, breaking the init script.
Change it back.
@ptpt52 does this fix it?

ksmbd-tools: fix meson build

---

net/xray-core/Makefile

Maintainer: me
Description:
- #18783

[openwrt-21.02] xray-core: Update to 1.5.8

---

utils/restic/Makefile

Maintainer: unchanged, it was Markus Weippert markus@gekmihesg.de
Compile tested: SDK for OpenWrt 21.02.3
Run tested: xRX200 rev 1.2, AVM FRITZ!Box 7360 V2, OpenWrt 21.02.3
Description:
Updated to version 0.13.1
Signed-off-by: Tom Stöveken <tom@naaa.de>

restic: update to 0.13.1

---

libs/hidapi/Makefile
libs/hidapi/patches/020-iconv.patch

Switch to cmake.
Maintainer: @paulfertser 

hidapi: update to 0.12.0

---

net/xtables-addons/Makefile

Updated to kernel 5.10.121+ changes
Maintainer: me / @jow-
Compile tested: ramips/mt7620 TP-Link Archer C50 v1, ramips/mt7621 Xiaomi Mi router 3 Pro, ath79/generic TP-Link WDR-3500
Run tested: ramips/mt7620 TP-Link Archer C50 v1, ramips/mt7621 Xiaomi Mi router 3 Pro, ath79/generic TP-Link WDR-3500
Due to commit 6950ee32c1879818de03f13a9a5de1be41ad2782 "lsm,selinux: pass flowi_common instead of flowi to the LSM hooks" in 5.10.121 kernel xtables-addons need to be updated

xtables-addons: update to 3.21

---

net/knot-resolver/Makefile
net/knot-resolver/patches/030-fix-policy-hack.patch

Compile and run tested on these two routers:
- Turris Omnia, mvebu/cortex-a9, Turris OS 6.0 based on OpenWrt 21.02.3
- Turris 1.1, powerpc/8540, Turris OS 6.0 based on OpenWrt 21.02.3
Changelog for versions:
- 5.4.4 [1]
- 5.5.0 [2]
- 5.5.1 [3]
[1] https://www.knot-resolver.cz/2022-01-05-knot-resolver-5.4.4.html
[2] https://www.knot-resolver.cz/2022-03-15-knot-resolver-5.5.0.html
[3] https://www.knot-resolver.cz/2022-06-14-knot-resolver-5.5.1.html

knot-resolver: update to version 5.5.1

---

lang/php7/Makefile

Maintainer: me
Description:
This fixes:
- CVE-2022-31625
- CVE-2022-31626

[21.02] php7: update to 7.4.30

---

lang/php8/Makefile
lang/php8/patches/0041-Add-patch-to-remove-build-timestamps-from-generated-.patch

Maintainer: me
Description:
This fixes:
- CVE-2022-31625
- CVE-2022-31626

[21.02] php8: update to 8.0.20

---

utils/irqbalance/files/irqbalance.config
utils/irqbalance/files/irqbalance.init

Allow the user to specify the level at which irqbalance assumes the cache
domains are partitioned. Keep the default value of 2.
Maintainer: @hnyman

irqbalance: handle deepestcache option

---

libs/libgd/Makefile

Compile tested: aarch64, Turris MOX, OpenWrt 19.07
Run tested: -
Description: I needed the pkgconfig file for an unrelated build that won't go to openwrt, but I think it makes sense to upstream this change.

[19.07] libgd: install pkgconfig file

---

net/dnsdist/Makefile

Maintainer: me
Compile tested: openwrt master, built on Debian 11; openwrt 19.07, built on Debian 11
Run tested: openwrt master on edgerouter lite; openwrt 19.07 on tp-link archer c7 v5 (after locally backporting this change to 19.07)
Description:
luajit provides higher performance for requests handled in Lua hooks.
It also enables access to dnsdist functionality only exposed via FFI,
and allows configurations/hooks to call functions in any C library
without providing separate bindings.

dnsdist: switch from liblua to luajit

---

utils/collectd/files/lua-scripts/dsl.lua

- Handle bool values correctly. We get the values as bool, but collectd
requires a bool value to be numeric in the range [0, 1].
- Remove profile and mode values. Those are strings, which cannot be
represented by collectd.
- Update collectd type for some values.
- Fix latn value being present twice.
Signed-off-by: Dominik Riebeling <bluebrother@posteo.de>

collectd: Fix various issues with lantiq dsl metrics.

---

net/dnsdist/Makefile

backport of #18787 for 22.03
luajit provides higher performance for requests handled in Lua hooks.
It also enables access to dnsdist functionality only exposed via FFI,
and allows configurations/hooks to call functions in any C library
without providing separate bindings.
(cherry picked from commit 283b269c7c0f164311b11d459953b1b34f6974cf)
Description:

(22.03) dnsdist: switch from liblua to luajit

---

admin/syslog-ng/Makefile
admin/syslog-ng/files/syslog-ng.conf

Maintainer: me
Compile and run tested: Turris 1.1, powerpc_8540, OpenWrt 21.02.3
- Changelog:
https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-3.37.1
- Bump config version

syslog-ng: update to version 3.37.1

---

lang/python/python-websocket-client/Makefile

Maintainer: me
Description:
New upstream update
- Fix unclosed socket error
- Update header dict access
- Add utf8 workaround to docs

python-websocket-client: update to 1.3.3

---

libs/protobuf/Makefile

The cherry-pick done in 022aef6 includes changing the build setup from
cmake to ninja, but it was overlooked that this was actually reverted in
2e654b1.
The ninja build results in headers not being installed for the host pkg,
so protobuf-c/host can't be build.
This commit reverts the package back to cmake.
Compile tested: ath70 21.02 sdk
Description:
Fix commit 022aef6 from @neheb committed by @BKPepe (see related [build failures](https://downloads.openwrt.org/releases/faillogs-21.02/)).
Kind regards,
Seb

[21.02] protobuf: fix 022aef6

---

lang/php8/Makefile

Maintainer: me
Description:
This fixes:
- CVE-2022-31625
- CVE-2022-31626

php8: update to 8.1.7

---

utils/docker-compose/Makefile

Maintainer: me
Description:
Enhancements:
- Support for setting secret from env variable by @ndeloof
Fixes:
- Do not start unrelated dependencies on run by @laurazard
- Fix service not found errors when using --no-deps by @nicksieger
- Respect COMPOSE_REMOVE_ORPHANS env var on down by @nicksieger
- Fix project level bind mounts volumes by @ulyssessouza
- Respect deploy.limits.cpus and deploy.limits.pids by @glours
Internal:
- Upgrade: Go v1.18.3 by @thaJeztah
- Upgrade: compose-go v1.2.8 by @milas
- Upgrade: buildx v0.8.2 by @dependabot
- Upgrade: containerd v1.6.6 by @dependabot

docker-compose: Update to version 2.6.1

---

utils/yq/Makefile

Maintainer: me
Description:
- Backported from: #18825

[openwrt-21.02] yq: Update to 4.25.3

---

net/tgt/Makefile

Maintainer: me
Compile tested: ath79, WNDR3800, r19934-9d06e5a773
Run tested: ath79, WNDR3800, running in a chroot on a r15339+6-bc99b56d7e system. tgtd is able to export a LUN with a file used as a backing store.
Description:
- update to 1.0.83

tgt: update to 1.0.83

---

libs/totem-pl-parser/Makefile

The totem-pl-parser library seems to rely on freedesktop.org's MIME-type
definitions to parse playlist files. Without them, parsing will produce
a TOTEM_PL_PARSER_RESULT_IGNORED error.
Maintainer: me
Description:

totem-pl-parser: depend on shared-mime-info

---

libs/libradcli/Makefile

- Removed duplicate function definition from util.h
- Increased size of dictionary vendor and values to 32-bits from 16;
this breaks the ABI from the previous release.
- Corrected a string termination issue in rc_avpair_tostr()
- Added functions to create dictionary without a file:
rc_dict_addattr
rc_dict_addval
rc_dict_addvend

radcli: uptdate to 1.3.0

---

admin/openwisp-monitoring/Makefile

Run tested: ath79, ramips, OpenWrt 19, OpenWrt 21
Description:
netjson-monitoring: utility script which returns monitoring information output in [NetJSON DeviceMonitoring format](https://netjson.org/docs/what.html#devicemonitoring)
openwisp-monitoring: daemon which collects and sends the NetJSON DeviceMonitoring data to [OpenWISP Monitoring](https://github.com/openwisp/openwisp-monitoring)
Package home page and documentation: https://github.com/openwisp/openwrt-openwisp-monitoring.

[19.07] openwisp-monitoring: added 0.1.1

---

admin/openwisp-monitoring/Makefile

Run tested: ath79, ramips, OpenWrt 19, OpenWrt 21
Description:
netjson-monitoring: utility script which returns monitoring information output in [NetJSON DeviceMonitoring format](https://netjson.org/docs/what.html#devicemonitoring)
openwisp-monitoring: daemon which collects and sends the NetJSON DeviceMonitoring data to [OpenWISP Monitoring](https://github.com/openwisp/openwisp-monitoring)
Package home page and documentation: https://github.com/openwisp/openwrt-openwisp-monitoring.

[22.03] openwisp-monitoring: added 0.1.1

---

admin/openwisp-monitoring/Makefile

Run tested: ath79, ramips, OpenWrt 19, OpenWrt 21
Description:
netjson-monitoring: utility script which returns monitoring information output in [NetJSON DeviceMonitoring format](https://netjson.org/docs/what.html#devicemonitoring)
openwisp-monitoring: daemon which collects and sends the NetJSON DeviceMonitoring data to [OpenWISP Monitoring](https://github.com/openwisp/openwisp-monitoring)
Package home page and documentation: https://github.com/openwisp/openwrt-openwisp-monitoring.

[21.02] openwisp-monitoring: added 0.1.1

---

libs/gnutls/Makefile

Configure.ac syntax changed to:
Old: --without-libbrotli --without-libzstd (also --with-*)
New: --without-brotli --without-zstd (also --with-*)
https://github.com/gnutls/gnutls/commit/6b794e49d1a14e43f9e08023f958364712c3c89a
Fixes: 6385813ddfb4 ("gnutls: update to 3.7.5")

  gnutls: adjust to new configure.ac syntax

---

net/netifyd/Makefile
net/netifyd/files/netifyd.init

Signed-off-by: Darryl Sokoloski <darryl@sokoloski.ca>
Maintainer: Darryl Sokoloski / @dsokoloski
Compile tested: arm_cortex-a15_neon-vfpv4, TP-Link Archer C2600, master
Run tested: TP-Link Archer C2600
Netify Agent v4.2.0 stable release incorporates a host of new features and improvements such as a completely new application definitions implementation, a new applications configuration file-format, Netify API integration with automatic application/protocol category updates, refined classifications using "soft-dissectors", support for applying application categories to lists of custom domains, significant memory utilization reductions, and a complete reintegration of the latest nDPI master branch.
- Decoupled application definitions from nDPI.  The Agent now processes all application …

netifyd: Updated to v4.2.0.

---

net/autossh/Makefile
net/autossh/files/autossh.hotplug
net/autossh/files/autossh.init

Compile tested: (x86_64, VirtualBox, OpenWrt v21.02.3)
Run tested: (x86_64, VirtualBox, OpenWrt v21.02.3, tests done)
Description:
Service gets stopped whenever any of the interfaces trigger down
Convert autossh into procd instances
Add new autossh config options in UCI to handle ssh port forwarding

autossh: improve uci and procd support

---

net/tor/Makefile

From the changelog…
o Major bugfixes (congestion control, TROVE-2022-001):
- Fix a scenario where RTT estimation can become wedged, seriously
degrading congestion control performance on all circuits. This
impacts clients, onion services, and relays, and can be triggered
remotely by a malicious endpoint. Tracked as CVE-2022-33903. Fixes
bug 40626; bugfix on 0.4.7.5-alpha.
o Minor features (fallbackdir):
- Regenerate fallback directories generated on June 17, 2022.
o Minor features (geoip data):
- Update the geoip files to match the IPFire Location Database, as
retrieved on 2022/06/17.
o Minor bugfixes (linux seccomp2 sandbox):
- Allow the rseq system call in the sandbox. This solves a crash
issue with glibc 2.35 on Linux. Patch from pmu-ipf. Fixes bug
40601; bugfix on 0.3.5.11.
o Minor …

tor: bump to 0.4.7.8 stable

---

utils/ncdu/Makefile
utils/ncdu/patches/900-use-alternative-color.patch

Upstream bump and add a patch to use a blue highlight color for the dark color scheme (`--color dark`) as some users find the default bright green is too intense.  Note that invoking ncdu without the `--color` switch at use uses the upstream default bright green, so users will need to call ncdu with `--color dark` in order to get the blue color.
@neheb @clehner

ncdu: update to 1.17 and add blue option

---

net/kea/files/kea.init

Maintainer: @rosysong
Run tested: NA
Description:
Kea expects /var/run/kea to exist. Without it, errors occur:
Mon Jun 13 10:31:45 2022 daemon.err kea-dhcp6[2977]: Unable to use interprocess sync lockfile (No such file or directory): /var/run/kea/logger_lockfile

kea: create /var/run/kea in init script

---

net/modemmanager/files/modemmanager.proto

A network restart where netifd is cleanly restarted involves bringing
the network interfaces down. The 'modemmanager' protocol handler will
run a mmcli --simple-disconnect in this case, but only if there are
bearer objects found.
If the network restart happened *during* the connection attempt
procedure, while the modem is e.g. being registered in the network, no
bearer objects exist yet, and so, we would skip doing anything during
the interface teardown operation. This would lead to the original
connection attempt succeeding, so leaving the modem in ModemManager
in connected state, while the associated interface in netifd is
reported down.

modemmanager: explicitly disconnect even if no bearers found

---

libs/libarchive/Makefile

Description:
libarchive looks for ext2fs headers during configure, and if it finds
them it will expect to find them during compile, or on the rare occasion
when they aren't it will fail:
libarchive/archive_entry.c:59:55: fatal error: ext2fs/ext2_fs.h: No such file or directory
As we just need headers for some type constants, let's re-use headers
from tools/e2fsprogs package which are always available.

libarchive: fix ext2fs build race error condition

---

utils/collectd/files/lua-scripts/dsl.lua

- Handle bool values correctly. We get the values as bool, but collectd
requires a bool value to be numeric in the range [0, 1].
- Remove profile and mode values. Those are strings, which cannot be
represented by collectd.
- Update collectd type for some values.
- Fix latn value being present twice.
Cherry-picks eb632da5bbd732bbffc2761fbb191267ef2375d0
Signed-off-by: Dominik Riebeling <bluebrother@posteo.de>

[22.03] collectd: Fix various issues with lantiq dsl metrics.

---

net/xtables-addons/Makefile
net/xtables-addons/patches/001-fix-kernel-version-detection.patch
net/xtables-addons/patches/200-add-lua-packetscript.patch

Compile tested: mvebu/cortexa9, Linksys WRT1900ACS v2,  `openwrt-22.03 - 5c7aed8b1e7336686860479cc6f0716ca6bf7016`
Run tested: mvebu/cortexa9, Linksys WRT1900ACS v2,  `openwrt-22.03 - 5c7aed8b1e7336686860479cc6f0716ca6bf7016`
Description:
Basically the same as in https://github.com/openwrt/packages/pull/18802 with the remaining commits. Because the  kernel in the `openwrt-22.03` branch as been updated to 5.10.127 (commit 6b44a6e73184593845d3521b1e21fd44e3a9d2f4)
Also included cherry picked commits from master:
- xtables-addons: add PKG_LICENSE_FILES and use SPDX  (https://github.com/openwrt/packages/commit/b4d00c1c203850644387378c37410f6216c998cf)
- xtables-addons: fix various warning in lua patch (https://github.com/openwrt/packages/commit/1cd93b673bfc01969946072a3d69896 …

xtables-addons: update to 3.21 (backport to openwrt-22.03 branch)

---

net/cloudflared/Makefile

Maintainer: me
Description:
Release note:
- https://github.com/cloudflare/cloudflared/commit/6a6ba704f1d5b83e5fa6e8f6e80c6243b3018c2a
- https://github.com/cloudflare/cloudflared/commit/ac7fdd5572007bb8b5ccb7d466f0461ee9977627
- https://github.com/cloudflare/cloudflared/commit/06f7ba45233942b72349685fb7ede38c2783dd65

 cloudflared: Update to 2022.7.1

---

net/dnslookup/Makefile

Maintainer: me
Description:
Upgraded all go dependencies.

dnslookup: Update to 1.7.1

---

lang/python/python-cryptography/Makefile
lang/python/python-cryptography/patches/0004-disable-rust.patch

Maintainer: me
Compile tested: armvirt-32, 2022-07-03 snapshot sdk
Description:
Fixes https://github.com/openwrt/packages/issues/18876.
Fixes https://github.com/openwrt/packages/issues/18879.

python-cryptography: Fix failing build

---

lang/python/python-cryptography/Makefile
lang/python/python-cryptography/patches/0004-disable-rust.patch

Maintainer: me
Compile tested: none (cherry picked from #18883)
Description:
Fixes https://github.com/openwrt/packages/issues/18876.
Fixes https://github.com/openwrt/packages/issues/18879.
(cherry picked from commit 9e3b7d78837b7181b859472894aa243a2eae595b)

[openwrt-21.02] python-cryptography: Fix failing build

---

net/clamav/Makefile
net/clamav/patches/020-iconv.patch

Fixes compilation without libiconv-stub.

clamav: use standard CMake find_package for iconv

---

net/ser2net/Makefile
net/ser2net/files/ser2net.init

Maintainer: me
Run tested: -
Description:
Usually, no other local service depends on the start of ser2net, so
let's start it later in the boot process.

ser2net: schedule start later during boot (fixes #18872)

---

libs/elektra/Makefile
libs/elektra/patches/010-iconv.patch

CMake's find_package works fine. No need to override.
Maintainer: @haraldg 

elektra: remove custom iconv handling

---

utils/telegraf/Makefile

Maintainer:
me
Run tested:
Description:
Add package with version 1.23.1

telegraf: Update to version 1.23.1

---

libs/libv4l/Makefile

Maintainer: Ted Hess <thess@kitschensync.net>
Compile tested: (mipsbe, 8dev Rambutan, OpenWrt v22.03.0-rc4)
Run tested: (mipsbe, 8dev Rambutan, OpenWrt v22.03.0-rc4)
Description:
`libudev-zero` dependency causes issues when other `libudev` provider is present, e.g. `eudev`. Especially, it was trying to select both `libudev-zero` and `libudev` what caused the conflict in my case.
Instead, when `libudev` is used, it just looks for any available package which provides the library.

libv4l: Change dependency from libudev-zero to libudev

---

net/apinger/Makefile
net/apinger/files/apinger-hotplug
net/apinger/files/apinger.config
net/apinger/files/apinger.init
net/apinger/files/iface.hotplug
net/apinger/files/user.hotplug
net/apinger/patches/030-apinger-no_exit.patch
net/apinger/patches/040-srcip.patch
net/apinger/patches/050-statusformat.patch

- convert apinger into procd instances
- generate instance specific apinger.conf from uci
- hotplug handling for apinger alarms
- restart apinger interface instance on ifup action of interface
- don't exit on packet count mismatch, allows to use apinger as monitor
for multiple targets handling
- add srcip option to target configuration, allows specifying source ip
used to monitor target
- allow creating status file in script parseable format
Patches are ported against latest version of apinger and referenced from
https://git.pld-linux.org/?p=packages/apinger.git;a=summary
Signed-off-by: Jaymin Patel <jem.patel@gmail.com>
Maintainer: @samm-git
Run tested:  x86-64, aarch64, virtual box, marvell_armada-3720-db, v21.02.3
Description:
Now apinger can be used to manage multiple …

apinger: improve uci and procd support

---

libs/libarchive/Makefile

This is backport of 797945dfaa0e7de8d6b0ada472bda63bb27f0cdc commit.
Description:
libarchive looks for ext2fs headers during configure, and if it finds
them it will expect to find them during compile, or on the rare occasion
when they aren't it will fail:
libarchive/archive_entry.c:59:55: fatal error: ext2fs/ext2_fs.h: No such file or directory
As we just need headers for some type constants, let's re-use headers
from tools/e2fsprogs package which are always available.

[22.03] libarchive: fix ext2fs build race error condition

---

libs/libarchive/Makefile

This is backport of 797945dfaa0e7de8d6b0ada472bda63bb27f0cdc commit.
Description:
libarchive looks for ext2fs headers during configure, and if it finds
them it will expect to find them during compile, or on the rare occasion
when they aren't it will fail:
libarchive/archive_entry.c:59:55: fatal error: ext2fs/ext2_fs.h: No such file or directory
As we just need headers for some type constants, let's re-use headers
from tools/e2fsprogs package which are always available.

[21.02] libarchive: fix ext2fs build race error condition

---

libs/libarchive/Makefile

This is backport of 797945dfaa0e7de8d6b0ada472bda63bb27f0cdc commit.
Description:
libarchive looks for ext2fs headers during configure, and if it finds
them it will expect to find them during compile, or on the rare occasion
when they aren't it will fail:
libarchive/archive_entry.c:59:55: fatal error: ext2fs/ext2_fs.h: No such file or directory
As we just need headers for some type constants, let's re-use headers
from tools/e2fsprogs package which are always available.

[19.07] libarchive: fix ext2fs build race error condition

---

net/pdns-recursor/Makefile

pdns-recursor: update to 4.7.1

---

net/gsocket/Makefile
net/gsocket/test.sh

Signed-off-by: Ralf Kaiser <skyper@thc.org>
Maintainer: Ralf Kaiser @SkyperTHC
Compile tested: mips_24kc, Openwrt 22.03.0-rc4
Run tested: mips_24kc
Description:
Global Socket allows two workstations on different private networks to
communicate with each other. Through firewalls and through NAT - like
there is no firewall.
The TCP connection is secured with AES-256 and using OpenSSL's SRP
protocol (RFC 5054). It does not require a PKI and has forward
secrecy and (optional) TOR support.
The gsocket tools derive temporary session keys and IDs and connect
two TCP pipes through the Global Socket Relay Network (GSRN). This is
done regardless and independent of the local IP Address or geographical
location.
The session keys (secrets) never leave the workstation. The GSRN sees only
the encrypted …

gsocket: add a new package

---

utils/telegraf/Makefile

Maintainer:
me
Run tested:
Description:
Add package with version 1.23.2

telegraf: Update to version 1.23.2

---

libs/liborcania/Makefile

Maintainer: me
Compile tested: mvebu, ARMv7, r19971+10-416d4483e8
Run tested: mvebu, ARMv7, r19971+10-416d4483e8
updating `libulfius` needs more time as it needs some modification afais

liborcania: bump to 2.3.0

---

net/dnslookup/Makefile

Maintainer: me
Compile tested: rockchip
Description:
- Backported from: #18882

[openwrt-22.03] dnslookup: Update to 1.7.1

---

utils/telegraf/Makefile

(cherry picked from commit https://github.com/openwrt/packages/commit/591f8cad333b36962aefbeccc6b0fa77e5826429)
Maintainer:
me
Run tested:
Description:
Add package with version 1.23.2 on openwrt 22.03

[22.03] telegraf: update to version 1.23.2 on openwrt 22.03

---

utils/telegraf/Makefile

(cherry picked from commit https://github.com/openwrt/packages/commit/591f8cad333b36962aefbeccc6b0fa77e5826429)
Maintainer:
me
Run tested:
Description:
Add package with version 1.23.2 on openwrt 21.02

[21.02] telegraf: update to version 1.23.2 on openwrt 21.02

---

libs/libnpupnp/Makefile

libnpupnp: update to 4.2.3

---

libs/libxcrypt/Makefile

Build position independent to fix compilation.
Maintainer: 

libxcrypt: update to 4.4.28

---

libs/pcre2/Makefile

Otherwise the host zlib gets picked up.
Maintainer: @InBetweenNames 

pcre2: add zlib build dependency

---

admin/sudo/Makefile

GCC12 doesn't implement some security flags used by sudo.

sudo: don't build with MIPS16

---

utils/watchcat/Makefile
utils/watchcat/files/watchcat.init
utils/watchcat/files/watchcat.sh

Compile tested: ipq806x, R7800, 22.03.0-rc1
Run tested: ipq40xx, MR8300, 22.03.0-rc1
recent commiters: @rozhuk-im @neheb and @nickberry17 
Description:
* added a new mode, `run_script` to run a script, with similar logic to the `restart_iface` mode.  I need this to be able to restart *only* wan6, but not wan, on the same underlying interface eth0.
* added explicit IPv4/IPv6 support for the ping
* fixed incomplete support for unlockbands configuration value
* cleaned up some logging commands
I've got corresponding luci changes in https://github.com/openwrt/luci/pull/5824

watchcat: add support for running a script

---

libs/glib2/Makefile

No longer present. The original reason for having it was an unfortunate
side effect of the way meson uses HOST_LDFLAGS. Since the transistion to
use dependency('iconv'), this is no longer relevant.

glib2: remove libiconv/host build dependency

---

mail/postfix/Makefile

Maintainer: @Shulyaka
Compile tested: aarch64, Turris MOX, OpenWrt 21.02
Run tested: -
Description: https://cdn.postfix.johnriley.me serves a certificate for a different domain name. This commit should be backported to all branches, should I make a separate PR for each branch even for a simple change like this or would it be easier for you to just cherry pick it manually?

postfix: fix download failure

---

net/restic-rest-server/Makefile
net/restic-rest-server/files/etc/config/restic-rest-server
net/restic-rest-server/files/etc/init.d/restic-rest-server

Maintainer: Tom Stöveken <tom@naaa.de>, Markus Weippert handed over, see: https://github.com/openwrt/packages/pull/18715#issuecomment-1153567619
Compile tested: SDK for OpenWrt 21.02.3
Run tested: x86/64, J&W Technologies I1171D001 Intel(R) Celeron(R) CPU N3160 @ 1.60GHz, OpenWrt 21.02.3
Description:
Updated to version 0.11.0
Added new configuration parameters
Signed-off-by: Tom Stöveken <tom@naaa.de>

restic-rest-server: update to 0.11.0

---

net/xray-core/Makefile

Maintainer: me
Description:
Release note: https://github.com/XTLS/Xray-core/releases/tag/v1.5.9

xray-core: Update to 1.5.9

---

utils/yq/Makefile

Maintainer: me
Description:
Release note: https://github.com/mikefarah/yq/releases/tag/v4.26.1

yq: Update to 4.26.1

---

libs/slang2/Makefile

Using --with-iconv like this causes -liconv to get added, which is not
desirable.
Maintainer: @jefferyto

slang2: try to fix compilation without BUILD_NLS

---

net/xray-core/Makefile

Maintainer: me
Description:
- #18961

[openwrt-21.02] xray-core: Update to 1.5.9

---

utils/yq/Makefile

Maintainer: me
Description:
- #18960

[openwrt-21.02] yq: Update to 4.26.1

---

net/wifidog/Makefile
net/wifidog/patches/030-wolfssl-options.patch

Needs an extra header. pthread.h is also no longer implicitly included.
Maintainer: @mhaas 

wifidog: fix compilation with more recent wolfssl

---

net/geth/Makefile

Fix compilation with latest iconv changes.
Does anyone even use this?

geth: update to 1.10.20

---

libs/opusfile/Makefile

Fixes compilation under some hosts.
Some small cleanups for consistency between packages.
Maintainer: @eduardoabinader 
Fixes: https://github.com/openwrt/packages/issues/18983

opusfile: add autoreconf

---

utils/docker-compose/Makefile

Maintainer: me
Description:
What's Changed:
- Enhancements:
- add support of environment secret during build step by @glours
- Fixes:
- networks: prevent issues due to duplicate names by @milas
- Use appropriate dependency condition for one-shot containers when
running compose up --wait by @laurazard
- Fix environment variable expansion by @ulyssessouza in
compose-spec/compose-go#276
- Validate depended-on services exist in consistency check by
@laurazard in compose-spec/compose-go#281
- Fix hash usage in environment values by @ulyssessouza in
compose-spec/compose-go#283
- build: respect dependency order for classic builder by @milas
- fix: panic caused by empty string argument by @nicksieger
- (re)start should …

docker-compose: Update to version 2.7.0

---

lang/python/django/Makefile

Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-34265

[21.02] django: bump to version 3.2.14

---

lang/python/django/Makefile

Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-34265

django: bump to version 4.0.6

---

multimedia/yt-dlp/Makefile

yt-dlp: update to 2022.7.18

---

lang/python/python3/Makefile
lang/python/python3/patches/026-openssl-feature-flags.patch
lang/python/python3/patches/028-host-python-support-ssl-with-libressl.patch

Based upon patches from OpenBSD[0] and Gentoo[1].
Switched to the LibreSSL provided LIBRESSL_VERSION_NUMBER macro, which
makes OPENWRT_HOST_BUILD redundant.
[0] https://github.com/openbsd/ports/tree/master/lang/python/3.10/patches
[1] https://github.com/gentoo/libressl/tree/master/dev-lang/python/files
Signed-off-by: Andre Heider <a.heider@gmail.com>
Compile tested: ipq40xx/master
Run tested: no
This fixes the build error reported in https://github.com/openwrt/openwrt/pull/10299#issuecomment-1188755924
Just compile time tested.

python3: update patches for libressl to fix hashlib build error

---

net/curl/Config.in

The decision to switch the default to wolfSSL was taken because of
hostapd back from when curl was in base. Unfortunately, not only is
wolfSSL bigger but it has also been causing issues recently. There's
also no relation between hostapd and curl.
https://github.com/openwrt/openwrt/issues/10302 as an example.

curl: switch default SSL to mbedTLS

---

lang/erlang/Makefile
lang/erlang/patches/030-crypto-Make-configure-flag-disable-otp-test-engine.patch
lang/erlang/patches/031-Update-configure-scripts.patch
lang/erlang/patches/032-crypto-do-disable-otp-test-engine-for-LibreSSL-3.5.0.patch
lang/erlang/patches/033-Update-configure-scripts.patch

Cherry-pick four upstream commits that prevent building of
otp_test_engine when LibreSSL-3.5.0 is used.
Since OpenWrt bumped LibreSSL to 3.5.3 the erlang host builds fail to
complete.
```
CC	../priv/obj/x86_64-pc-linux-gnu/otp_test_engine.o
otp_test_engine.c: In function 'test_engine_md5_init':
otp_test_engine.c:144:34: error: dereferencing pointer to incomplete type 'EVP_MD_CTX' {aka 'struct env_md_ctx_st'}
#define data(ctx) ((MD5_CTX *)ctx->md_data)
^~
```
Also switch to AUTORELEASE.
Maintainer: Arnaud Sautaux (didn't find github handle)
Compile tested: ath79 master sdk
Description:
Add upstream commits to make erlang/host compile again.

erlang: workaround LibreSSL-3.5.0 compat issues

---

lang/ruby/patches/001-fix-build-with-libressl-3.5.patch
lang/ruby/patches/002-fix-operator-precedence.patch

Compile tested: armv8(rockchip r4s) OpenWrt master SNAPSHOT
Run tested: armv8(rockchip r4s) OpenWrt master SNAPSHOT
Description:
LibreSSL 3.5 and later (https://github.com/openwrt/openwrt/commit/5451b03b7ceb2315445c683fe174e28bbdd49c2f) provide and need to use
PEM_write_bio_PrivateKey_traditional()
upstream commit:
https://github.com/ruby/openssl/commit/e25fb0d0d86da5a9398ebdc9216b2ea89f80fa3d
https://github.com/ruby/openssl/commit/b02815271fcc295cb8b07ef740684b88a10f2760
Signed-off-by: ZiMing Mo <msylgj@immortalwrt.org>

ruby: fix build with LibreSSL over v3.5

---

net/modemmanager/files/25-modemmanager-net
net/modemmanager/files/25-modemmanager-tty
net/modemmanager/files/25-modemmanager-wwan

Definition of mm_log() was changed in
45a56a889943b437f78fa2bfca3d5d8ac555c77e but 25-modemmanager* weren't
changed.
Signed-off-by: Arkadiusz Drabczyk <arkadiusz@drabczyk.org>
Compile tested: x86-64 Slackware OS, CONFIG_TARGET_ipq40xx, OpenWrt 22.03.0-rc4
Run tested: armv7l, InHand Networks VG710, OpenWrt 22.03.0-rc4
The purpose of the test was to check if 'event processed' logs show up in logread:
root@OpenWrt:~# logread  | grep 'event processed'
Wed Jul 13 11:48:57 2022 daemon.info ModemManager[4273]: hotplug: add network interface br-lan: event processed
Description:

modemmanager: fix mm_log() invocations in 25-modemmanager* files

---

utils/telegraf/Makefile

Maintainer:
me
Run tested:
Description:
Add package with version 1.23.3

telegraf: Update to version 1.23.3

---

utils/telegraf/Makefile

(cherry picked from commit https://github.com/openwrt/packages/commit/281d156a35830003e3844af6f195958715731dfb)
Maintainer:
me
Run tested:
Description:
Add package with version 1.23.3 on openwrt 22.02

[21.02] telegraf: Update to version 1.23.3

---

utils/telegraf/Makefile

(cherry picked from commit https://github.com/openwrt/packages/commit/281d156a35830003e3844af6f195958715731dfb)
Maintainer:
me
Run tested:
Description:
Add package with version 1.23.3 on openwrt 22.03

[22.03] telegraf: Update to version 1.23.3

---

libs/zmq/Makefile
libs/zmq/patches/020-no-libbsd.patch

Not really needed for anything. Patch taken from upstream.
ping @guijan

zmq: remove libbsd dependency

---

net/curl/Config.in

Maintainer: me
Description:
The decision to switch the default to wolfSSL was taken because of
hostapd back from when curl was in base. Unfortunately, not only is
wolfSSL bigger but it has also been causing issues recently. There's
also no relation between hostapd and curl.
(cherry picked from commit 0a65e4c6fa84e13a1732c26260615c1ad5efea5b)

[22.03] curl: switch default SSL to mbedTLS

---

net/isc-dhcp/files/dhcpd.init

Maintainer: me
Compile tested: x86_64, generic, HEAD (a7be143646)
Description:
Drop use of `allow-update` and this will later conflict with `update-policy` lines added for remote DHCP servers.

isc-dhcp: don't use allow-update in bind config

---

lang/php8/Makefile

Maintainer: me
Description:
This fixes:
- CVE-2022-31627

php8: update to 8.1.8

---

utils/hfsprogs/Makefile

Wikipedia says "[Starting with macOS 10.15, HFS disks can no longer be read](https://en.wikipedia.org/wiki/MacOS_10.15)". hfsprogs also deals with the related HFS+ filesystem, Wikipedia says HFS+ was "[replaced with the Apple File System (APFS), released with macOS High Sierra](https://en.wikipedia.org/wiki/HFS_Plus)". This means support for HFS was removed from macOS in 2019, and HFS+ was deprecated in 2017.
Maybe we could drop this package instead? Tell me if so.
Signed-off-by: Guilherme Janczak <guilherme.janczak@yandex.com>
Compile tested: x64 glibc master
Description:
```
hfsprogs uses libbsd for strlcpy(), but the strlcpy() calls are inside
`#ifdef` and don't show up on the OpenWRT package.
```

hfsprogs: remove unused libbsd

---

utils/tar/Makefile

fixes compilation when deselecting options.
note that compiling without CONFIG_PACKAGE_TAR_GZIP will result in an unupgradable system. See: https://github.com/openwrt/luci/issues/5893

tar: add PKG_CONFIG_DEPENDS

---

multimedia/ffmpeg/Makefile
multimedia/ffmpeg/patches/050-glibc.patch

Bump to latest upstream version, manually rebased: 050-glibc.patch
Tested using: ffmpeg -f lavfi -i testsrc=duration=10:size=1280x720:rate=30 testsrc.mpg
Resulting mpg was good.

ffmpeg: update to 5.1

---

utils/domoticz/files/domoticz.init

The domoticz init script didn't properly read the "disabled"
configuration parameter and instead the service was always started.
Signed-off-by: Robert Högberg <robert.hogberg@gmail.com>
Maintainer: @dwmw2
Run tested: ath79, D-Link DIR-825 B1, OpenWrt 21.02.3 - I have verified that starting domoticz with and without "disabled" set works as expected

domoticz: fix read of "disabled" uci configuration parameter

---

net/stunnel/Makefile

Maintainer: me
Compile tested: x86_64 and lantiq_xrx200, APU3, latest master
Run tested:  x86_64, APU3, `stunnel -h`
Description:
update version to 5.65
`stunnel -h`
```
root@st-dev-07 ~ # stunnel -h
[.] stunnel 5.65 on x86_64-openwrt-linux-gnu platform
[.] Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
[!] Invalid configuration file name "-h"
[!] realpath: No such file or directory (2)
```

stunnel: update version to 5.65

---

net/apinger/Makefile
net/apinger/files/apinger.init
net/apinger/files/apinger.rpc
net/apinger/files/graphs.sh
net/apinger/files/iface.hotplug
net/apinger/patches/060-format-alarm-list.patch

- add rrdtool1 and rrdcgi1 dependency for RRD graphs
- add RPC to get an overview and update graphs
- fix interface hotplug to restart apinger instance
- add patch to split alarms list in the status
Signed-off-by: Jaymin Patel <jem.patel@gmail.com>
Maintainer: @samm-git @feckert 
Run tested: x86-64, aarch64, virtual box, marvell_armada-3720-db, v21.02.3
Description:
Add RRD configuration support in UCI
Apinger already has built-in support for RRD, expose it to UCI to generate RRD files and graphs.

apinger: add rrd graph support

---

libs/libxml2/Makefile

Needed for applications that use libxml-2.0.pc Libs.private params
to link with -liconv library.
Signed-off-by: Alin Nastac <alin.nastac@gmail.com>

libxml2: add libiconv path to pkg-config file

---

utils/lcdproc/Makefile

Maintainer: me, @haraldg 
Compile tested: x86_64, generic, HEAD (a7be143646)
Run tested: none... I have no compatible hardware
Description:
Configure attempts to detect a parallel port by reading from `0x350`. Obviously this is not cross-compile friendly.

lcdproc: don't detect parallel port on build host

---

utils/realtek-poe/Makefile

Maintainer: Hurricos <hurricos@gmail.com>
Compile tested: realtek 8038x,  Engenius WES2910P, OpenWrt snapshot
Run tested: realtek 8038x,  Engenius WES2910P, OpenWrt snapshot, started daemon, observed PoE outputs working
Description:
The realtek-poe package is used to configure the Power-over-Ethernet
controller found on Realtex 838x based switches. On many such
switches, the PoE doesn't work without this package.
Signed-off-by: Alexandru Gagniuc <mr.nuke.me@gmail.com>

realtek-poe: Package to control PoE for Realtek 838x devices

---

utils/docker-compose/Makefile

Maintainer: me
Run tested: master x86-64
Description:
[Changelog](https://github.com/docker/compose/releases)

docker-compose: Update to version 2.9.0

---

lang/python/python-jsonschema/Makefile

python-jsonschema: Update to 4.9.0

---

lang/python/django/Makefile

Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-34265
(cherry picked from commit b0ddec3161969728b671018753a5eaca84e2e57a)

[22.03] django: bump to version 4.0.6

---

libs/gnutls/Makefile
net/chrony/Makefile
net/gensio/Makefile

This prevents building of unused packages during OpenWRT image build

Avoid building unused package dependencies

---

net/fail2ban/patches/010-python3.10_compat.patch

Maintainer: @erdoukki
Compile tested: x86_64, OpenWrt master
Compile tested: x86_64, docker, OpenWrt master
Description: 89d5d2e091c8da10a1c963158a6de92b05079116 only patched importing MutableMapping from collections, but importing Mapping has to be patched too
Closes: #18681
This should also be backported to 22.03
cc @ryzhovau

fail2ban: fix patch for python 3.10

---

utils/lcdproc/Makefile

Maintainer: me, @haraldg 
Compile tested: x86_64, generic, HEAD (a7be143646)
Run tested: no install
Description:
Only support parallel-port drivers on x86/x86_64 hardware.

lcdproc: don't enable LPT support on non-x86 architectures

---

net/kea/Makefile

Maintainer: @rosysong
Compile tested: OpenWrt master r20212-beeb49740b x86/64
Run tested: OpenWrt master r20212-beeb49740b x86/64

kea: bump to 2.0.3

---

lang/python/python-paho-mqtt/Makefile

The uuid module has been split out into a separate package with the update to Python 3.10, so it needs to be added as a dependency here.
This also applies to the 22.03 branch.
Maintainers: @BKPepe, @commodo

python-paho-mqtt: add missing dependency

---

lang/luajit/patches/300-PPC-e500-with-SPE-enabled-use-soft-float.patch

makes LuaJit builds for mpc85xx targets with SPE ISA extension
enabled possible
Quoting inner commit message:
This allows building LuaJit for systems with Power ISA SPE
extension[^1] support by using soft float on LuaJit side.
While e500 CPU cores support SPE instruction set extension
allowing them to perform floating point arithmetic natively,
this isn't required. They can function with software floating
point to integer arithmetic translation as well,
just like FPU-less PowerPC CPUs without SPE support.
Therefore I see no need to prevent them from running LuaJit
explicitly.
[^1]: https://www.nxp.com/docs/en/reference-manual/SPEPEM.pdf
Signed-off-by: Pali Rohár <pali@kernel.org>
Signed-off-by: Šimon Bořek <simon.borek@nic.cz>
Maintainer: @milani
Compile and run tested: mpc85xx/p2020, …

luajit: patch: PPC/e500 SPE: use soft float instead of failing

---

libs/mxml/Makefile

Maintainer: me
Compile tested: x86_64, r18609
Run tested: no
Description:
Update to 3.3.1 (just a fix for a POSIX thread cleanup bug)

mxml: update to 3.3.1

---

utils/yq/Makefile

Maintainer: me
Description:
Release note: https://github.com/mikefarah/yq/releases/tag/v4.27.2

yq: Update to 4.27.2

---

libs/gnutls/Makefile

- libgnutls: Fixed double free during verification of pkcs7 signatures.
Reported by Jaak Ristioja (#1383). [GNUTLS-SA-2022-07-07, CVSS: medium]
[CVE-2022-2509]
- libgnutls: gnutls_hkdf_expand now only accepts LENGTH argument less than or
equal to 255 times hash digest size, to comply with RFC 5869 2.3.
- libgnutls: Length limit for TLS PSK usernames has been increased
from 128 to 65535 characters (#1323).
- libgnutls: AES-GCM encryption function now limits plaintext
length to 2^39-256 bits, according to SP800-38D 5.2.1.1.
- libgnutls: New block cipher functions have been added to transparently
handle padding.  gnutls_cipher_encrypt3 and gnutls_cipher_decrypt3 can be
used in combination of GNUTLS_CIPHER_PADDING_PKCS7 flag to automatically
add/remove padding if the length of the original …

gnutls: update to 3.7.7

---

net/openconnect/README
net/openconnect/files/openconnect.sh

Add support for the `--proxy` and `--reconnect-timeout` options, which we have been using in production for a couple of years now via this out-of-tree patch.

OpenConnect proxy support

---

utils/squashfs-tools/Config.in

Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/beeb49740bb4f68aadf92095984a2d1f9a488956 
Run tested: x86 https://github.com/openwrt/openwrt/commit/beeb49740bb4f68aadf92095984a2d1f9a488956 
----------------------
Requested via:
https://github.com/openwrt/packages/issues/19111
PKG_RELEASE is set to AUTORELEASE, so no need to bump.

squashfs-tools: enable zstd compression by default

---

utils/squashfs-tools/Config.in

Maintainer: me
Compile tested: on PR https://github.com/openwrt/packages/pull/19114
Run tested: on PR https://github.com/openwrt/packages/pull/19114
Requested via:
https://github.com/openwrt/packages/issues/19111
PKG_RELEASE is set to AUTORELEASE, so no need to bump.
(cherry picked from commit f0d45ba3401df4559b17370a19f7800894365d6a)

[22.03] squashfs-tools: enable zstd compression by default

---

utils/prometheus-node-exporter-lua/Makefile
utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/realtek-poe.lua

Maintainer: `Gregor Michels <hirnpfirsich@brainpeach.de>`
Compile tested: for `realtek rtl838x` on `amd64` (`snapshot`)
Run tested: `realtek rtl838x`, `Zyxel GS190010HP`, (`snapshot`)
Description:
```
exposes PoE metrics obtained from realtek-poe
realtek_poe_switch_info{mcu="ST Micro ST32F100 Microcontroller",firmware="v22.4"} 1
realtek_poe_switch_budget_watts 77
realtek_poe_switch_consumption_watts 5
realtek_poe_port_priority{device="lan1"} 1
realtek_poe_port_priority{device="lan2"} 1
[...]
realtek_poe_port_consumption_watts{device="lan1"} 0
realtek_poe_port_consumption_watts{device="lan2"} 0
[...]
realtek_poe_port_state{device="lan1",state="Disabled"} 0
realtek_poe_port_state{device="lan1",state="Searching"} 1
[...]
(states: Disabled, Searching, Delivering power, Fault, Other fault, …
```

prometheus-node-exporter-lua: add realtek-poe exporter

---

utils/yq/Makefile

Maintainer: me
Description:
- #19124

[openwrt-21.02] yq: Update to 4.27.2

---

utils/watchcat/Makefile
utils/watchcat/files/watchcat.sh

Fix for issue #19010
Signed-off-by: John Kohl <jtk.git@bostonpog.org>
Maintainer: @roger-
Compile tested: ramips , 22.03.0-latest
Run tested: ramips, 22.03.0-latest
recent commiters: @rozhuk-im @neheb and @nickberry17

watchcat: fix broken ping invocation for no-address-family configuration

---

net/strongswan/Makefile

Maintainer: me, @pprindeville
Compile tested: x86_64, generic, HEAD (23c77384f3)
Description:
Just a test compile with the CI for now, don't know if that is going to work out all right.

strongswan: try to model kdf optional dependencies

---

net/shadowsocks-libev/Makefile
net/shadowsocks-libev/files/ss-rules/chain.uc

Maintainer: me
Run tested: x86/64 qemu
Supersedes: https://github.com/openwrt/packages/pull/18852
Fixes: https://github.com/openwrt/packages/issues/18850

shadowsocks-libev: ss-rules: setup policy rules for udp/ip6

---

net/shadowsocks-libev/Makefile
net/shadowsocks-libev/files/shadowsocks-libev.init

Maintainer: me
Run tested: x86/64 qemu
Description:
Remove nft rules file generated by ss-rules if ss-rules was or should be
turned off for by configuration.  Use "fw4 restart" instead of "fw4
reload" to force the runtime rule reloading
Ref: https://github.com/openwrt/packages/pull/17937#issuecomment-1207357037

shadowsocks-libev: ss-rules: nft rule cleanup on reload

---

net/strongswan/Makefile

Compile tested: x86_64, generic, HEAD (23c77384f3)
Description:
Everything needs mgf1 plugin.

strongswan: bundle mgf1 with everything

---

net/ksmbd-tools/Makefile
net/ksmbd-tools/files/ksmbd.hotplug
net/ksmbd-tools/files/ksmbd.init

Maintainer: me / @neheb / @jow-
Description:
```
ksmbd-tools: add package with hotplug.d script for auto sharing
One of common use cases for SMB3 server in routers is sharing hotplugged
drives. Users make many attempts setting that up which often are not
optimal.
This script handles it in the cleanest way by using:
1. hotplug.d mount subsystem
2. runtime config in the /var/run/config/
It provides a working basic solution that can be later adjusted by
modifying provided hotplug script.
A pretty much idential solution was part of the samba36 package. It was
added in the OpenWrt commit ef1efa756e0d0 ("samba36: add package with
hotplug.d script for auto sharing") as an answer for feature required by
the Rosinson company.
```
```
ksmbd-tools: append config from /var/run/config/ for runtime …
```

ksmbd-hotplug: add package with hotplug script for auto-sharing

---

net/unbound/Makefile
net/unbound/patches/010-configure-uname.patch

Description: Update to 1.16.2, fix CVE-2022-30698 and CVE-2022-30699.
Signed-off-by: Pascal Ernster <git@hardfalcon.net>

unbound: update to 1.16.2, fix CVE-2022-30698, CVE-2022-30699

---

libs/libwebp/Makefile

Maintainer: me
Compile tested: x86 https:://github.com/openwrt/commit/beeb49740bb4f68aadf92095984a2d1f9a488956
Run tested: x86 https:://github.com/openwrt/commit/beeb49740bb4f68aadf92095984a2d1f9a488956

libwebp: bump to version 1.2.4

---

lang/python/python-websockets/Makefile

Maintainer: @paper42 
Compile tested: Turris Omnia, mvebu/cortex-a9, OpenWrt 21.02.3
Run tested: same, tested by @aleksan4eg 
Description:
- Update to [the version 10.3](https://websockets.readthedocs.io/en/stable/project/changelog.html)
- Updated copyright in the Makefile

python-websockets: update to version 10.3

---

net/rsync/patches/010-fix-CVE-2022-29154.patch
net/rsync/patches/011-more-improvements-to-file-list-checking.patch
net/rsync/patches/012-a-few-more-minor-changes.patch
net/rsync/patches/013-handle-a-trailing-slash.patch

The rsync package is vulnerable to CVE-2022-29154[1], which is not yet in a non-preview release. This commit applies the upstream commit to fix it and several subsequent commits needed to fix bugs the initial fix introduced[2].
1. https://rsync.samba.org/ftp/rsync/NEWS#SECURITY_FIXES-3.2.5
2. https://bugs.archlinux.org/task/75558

rsync: fix CVE-2022-29154

---

net/rclone/files/rclone.init

Signed-off-by: Liangbin Lian <jjm2473@gmail.com>
Maintainer: Elon Huang <elonhhuang@gmail.com>
Run tested: ARS2, arm64, openwrt 21.02.3
Description:
fix rclone init script on CIDR format ipaddr

rclone: fix init script on CIDR format ipaddr

---

utils/tree/Makefile

Update Makefile to use new source URL and corresponding variables due to old source url stating, "notice this site is likely going to be shutdown after over 28 years. I will likely be moving all my code-bases to https://gitlab.com/OldManProgrammer"[1]
1. http://mama.indstate.edu/users/ice/tree
Maintainer: @neheb @hbl0307106015

tree: update upstream source

---

utils/opendoas/Makefile
utils/opendoas/patches/configure-ignore-invalid-arguments.patch
utils/opendoas/patches/makefile-remove-chown.patch

Maintainer: me
Compile tested: aarch64, Turris MOX, OpenWrt master
Run tested: aarch64, Turris MOX, OpenWrt master
Description: opendoas is a port of OpenBSD doas to Linux, it replaced sudo in the main alpine repository with 3.15.
if someone wants to test this, add this to `/etc/doas.conf`:
```
permit nopass <user> as root
```
and try running doas id -u as `<user>`

opendoas: add package

---

net/strongswan/Makefile

Compile tested: x86_64, generic, HEAD (f038a169a0)
Description:
Originally by Noel Kuntze, and refined by Stijn Tintel.

strongswan: Add dependency to virtual package strongswan-mod-socket

---

utils/stress-ng/Makefile
utils/stress-ng/patches/010-dont_define_fortify.patch
utils/stress-ng/patches/020-stress-sysinval-fix-fstat-fstat64-compat-check.patch

Signed-off-by: Guilherme Janczak <guilherme.janczak@yandex.com>
Compile tested: x64, latest snapshot SDK as of today

stress-ng: update to 0.14.03

---

utils/opendoas/Makefile

Maintainer: me
Run tested: no
Description: When PAM is available, the build system will detect and use it, but the
package dependency was missing.
cc @neheb

opendoas: fix build with PAM

---

net/ariang/Makefile

Maintainer: @Ansuel @neheb
Changelog: https://github.com/mayswind/AriaNg/releases
Signed-off-by: Van Waholtz <vanwaholtz@gmail.com>

ariang: update to 1.2.4

---

net/lighttpd/Makefile

Description:
* update to lighttpd 1.4.66 release hash
Signed-off-by: Glenn Strauss [gstrauss@gluelogic.com](mailto:gstrauss@gluelogic.com)

lighttpd: update to lighttpd 1.4.66 release hash

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

Description: Update HAProxy to v2.6.2

haproxy: Update HAProxy to v2.6.2

---

net/iperf/Makefile

Enabling fast sampling to support four digit (e.g., 1.0000) precision in reports' timestamps. Useful for sub-millisecond sampling.
Changelog: https://sourceforge.net/p/iperf2/code/ci/2-1-8/tree/README
Signed-off-by: Alberto Martinez-Alvarez <amteza@gmail.com>
Compile tested: ath79, ramips, bcm27xx

iperf: Updated to 2.1.8

---

net/frp/Makefile

Run tested: (x86_64, OpenWrt 21.02.3, tests done)
Description:
changlog: https://github.com/fatedier/frp/releases

frp: update to 0.44.0

---

utils/mqttled/Makefile
utils/mqttled/files/mqttled.config

Signed-off-by: Tom Grime <tom.grime@gmail.com>
Compile tested: lantiq/xrx200 HH5A 21.02.03
Run tested: lantiq/xrx200 HH5A 21.02.03
Description:
Bump to support RGB LEDs and fix brightness control

mqttled: update to 0.1.2

---

utils/bluld/Makefile

Maintainer: @ktgeek 
Compile tested: aarch64 / glibc
Run tested: no
Description:
Remove the extra include for kernel headers from this user space
application. These extra includes are causing compile errors when
compiling with glibc. User space applications should not need such
headers.

bluld: Do not include kernel headers into user space application

---

utils/telegraf/variant-small/plugins/outputs/all/all.go

Maintainer:
me
Run tested:
Description:
Add influxdb2 output plugin to package version small

telegraf: Add influxdb2 output plugin to package version small

---

utils/telegraf/variant-small/plugins/outputs/all/all.go

Maintainer:
me
Run tested:
Description:
Add influxdb2 output plugin to package version small on openwrt 22.03

[22.03] telegraf: Add influxdb2 output plugin to package version small

---

utils/telegraf/variant-small/plugins/outputs/all/all.go

Maintainer:
me
Run tested:
Description:
Add influxdb2 output plugin to package version small on openwrt 21.02

[21.02] telegraf: Add influxdb2 output plugin to package version small

---

utils/telegraf/Makefile

Maintainer:
me
Run tested:
Description:
Add package with version 1.23.4

telegraf: Update to version 1.23.4

---

utils/telegraf/Makefile

(cherry picked from commit https://github.com/openwrt/packages/commit/e4555e03ee86ef62cf09ce1436c865d5eb472960)
Maintainer:
me
Run tested:
Description:
Add package with version 1.23.4 on openwrt 21.02

[21.02] telegraf: Update to version 1.23.4

---

utils/telegraf/Makefile

(cherry picked from commit https://github.com/openwrt/packages/commit/e4555e03ee86ef62cf09ce1436c865d5eb472960)
Maintainer:
me
Run tested:
Description:
Add package with version 1.23.4 on openwrt 22.03

[22.03] telegraf: Update to version 1.23.4

---

multimedia/yt-dlp/Makefile

yt-dlp: update to 2022.8.14

---

utils/miniflux/Makefile

miniflux: update to 2.0.38

---

admin/zabbix/Makefile

Compile tested: x86_64, APU3, latest openwrt master
Run tested: x86_64, APU3, latest openwrt master
Description:
If fping is not installed on the system the following message is show if
hosts should be monitored via icmp.
Log-Message:
"At least one of '/usr/sbin/fping', '/usr/sbin/fping6' must exist. Both
are missing in the system."
To fix this also, add a dependency to 'fping' for 'zabbix-server' and
'zabbix-proxy' for installation to allow icmp hosts monitoring.

zabbix: add fping dependency

---

net/travelmate/Makefile
net/travelmate/files/chs-hotel.login
net/travelmate/files/generic-user-pass.login
net/travelmate/files/h-hotels.login
net/travelmate/files/julianahoeve.login
net/travelmate/files/telekom.login
net/travelmate/files/tplink-omada.login
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.mail
net/travelmate/files/travelmate.sh
net/travelmate/files/travelmate.vpn
net/travelmate/files/travelmate_ntp.hotplug
net/travelmate/files/vodafone.login
net/travelmate/files/wifibahn.login

Compile tested: not relevant, script only
Run tested: GL.iNet GL-MT1300, OpenWrt SNAPSHOT r20333-a9eb5cce7e
Description:
* vpn support can be disabled (enabled by default), fixes #19107 (see trm_vpn option)
* vpn support can be limited to certain interfaces (see trm_vpnifacelist list option)
* openvpn support works now per instance (same as wireguard today)
* add an auto-login script for tplink-omada hotspots provided by Sebastian Muszynski <basti@linkt.de>
* remove pipefail command, see #19043 for reference

travelmate: update 2.1.0

---

net/coova-chilli/patches/020-libxt_coova-Use-constructor-instead-of-_init.patch

Maintainer: @teslamint 
Compile tested: aarch64/glibc
Run tested: no
The _init() function collides with a _init() function in crti.o.
This results in the following error in OpenWrt:
arc-openwrt-linux-gnu/bin/ld: libxt_coova.o: in function `_init':
/lib/gcc/arc-openwrt-linux-gnu/11.3.0/crti.o:(.init+0x4): first defined here
collect2: error: ld returned 1 exit status
make[7]: *** [Makefile:22: libxt_coova.so] Error 1
Fix this by suing a constructor attribute instead. This function will
still be called after the shared library was loaded.
Send upstream here: https://github.com/coova/coova-chilli/pull/556

coova-chilli: Fix compile problem with _init()

---

net/dnscrypt-proxy2/Makefile

Run tested: Linksys_wrt32x, mvebu (cortex-a9),  OpenWrt 22.03.0-rc6
Description:
update to version [2.1.2](https://github.com/DNSCrypt/dnscrypt-proxy/releases/tag/2.1.2)
Fixes: https://github.com/openwrt/packages/issues/19149

dnscrypt-proxy2: update to version 2.1.2

---

utils/pciutils/Makefile
utils/pciutils/patches/107-avoid-addng-multiple-version-tags.patch

Compile tested: OpenWrt 21.02.03, Turris 1.1 router, powerpc/8540
Run tested: OpenWrt 21.02.03, Turris 1.1 router, powerpc/8540
Description:
While building pciutils 3.8.0 for OpenWrt 21.02 includes target
mvebu/cortex-a9, mvebu/cortex-a53 and powerpc/8540, it fails because of
this error:
-I<turris1x/ws/build/staging_dir/toolchain-powerpc_8540_gcc-8.4.0_musl/include>   -c -o filter.o filter.c
{standard input}: Assembler messages:
{standard input}:6: Error: multiple versions [`pci_filter_init@@LIBPCI_3.8'|`pci_filter_init@LIBPCI_3.3'] for symbol `pci_filter_init_v38'
{standard input}:8: Error: multiple versions [`pci_filter_parse_slot@@LIBPCI_3.8'|`pci_filter_parse_slot@LIBPCI_3.3'] for symbol `pci_filter_parse_slot_v38'
{standard input}:10: Error: multiple versions …

pciutils: backport patch to fix compilation with older binutils

---

utils/openocd/Makefile

Maintainer: @paulfertser
Compile tested: OpenWrt master r20360-832e7b8172 bcm27xx/bcm2711
Run tested: OpenWrt master r20360-832e7b8172 bcm27xx/bcm2711

openocd: enable bcm2835gpio on bcm27xx

---

utils/stress-ng/Makefile

Maintainer: me
Compile tested: x86  https://github.com/openwrt/openwrt/commit/beeb49740bb4f68aadf92095984a2d1f9a488956
Run tested: x86  https://github.com/openwrt/openwrt/commit/beeb49740bb4f68aadf92095984a2d1f9a488956
Fixes: https://github.com/openwrt/packages/issues/19210
If libjpeg isn't selected by another package, all is fine.
But if it is selected, the stress-ng build will see it and try to build the
jpeg stressor. This would usually fail sometime and link-time.
In any case, it's better to just pick-up libjpeg as a dependency of
stress-ng. If people want to stress their system with this tool, they can
probably expect libjpeg as well.

stress-ng: add libjpeg dep

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Compile tested: x86_64, Sophos SG-135, OpenWrt 22.03.0-rc6
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.0-rc6
Description:
* Update maintainer's email address
* Style Make and init file to OpenWrt standard
* Rename dnsmasq and unbound-related variables to better reflect
their use
* New 'allow' CLI parameter to quickly unblock domain(s)
* Switch to uci wrappers
* Beautify the output of the 'check' CLI parameter
* Better handling of output files directory creation error
* Support for (upcoming) dnsmasq nftsets

simple-adblock: update to 1.9.0-1

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Description:
* Update maintainer's email address
* Style Make and init file to OpenWrt standard
* Rename dnsmasq and unbound-related variables to better reflect
their use
* New 'allow' CLI parameter to quickly unblock domain(s)
* Switch to uci wrappers
* Beautify the output of the 'check' CLI parameter
* Better handling of output files directory creation error
* Support for (upcoming) dnsmasq nftsets
(cherry picked from commit 3b686b08a54df89582af7092465fc5f0c76fed31)

[22.03] simple-adblock: update to 1.9.0-1

---

libs/boost/patches/010-mips1.patch

Compile tested: octeonplus mips64 using musl
Description:
This commit restores the patch for libboost_context for mips64 given
that the upstream update added in 1.80.0 does not fully fixes the issue.
Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

boost: restores patch for libboost_context for mips64

---

net/pdns-recursor/Makefile

Maintainer: me
Run tested: after CI
Description:
security update - https://doc.powerdns.com/recursor/security-advisories/powerdns-advisory-2022-02.html

pdns-recursor: update to 4.7.2

---

net/pdns-recursor/Makefile

(cherry picked from commit 0e660c9f501e3dde48bb7c4ead37ced7120542af)
Maintainer: me
Run tested: after CI
Description:
security update - https://doc.powerdns.com/recursor/security-advisories/powerdns-advisory-2022-02.html

[22.03] pdns-recursor: update to 4.7.2

---

libs/libgd/Makefile

Maintainer: @jow- introduced by @flyn-org in https://github.com/openwrt/packages/commit/0762c72cc53c0e5504981f09d243e71674070fca
The full variant should conflict with the default variant. This prevents that
libgd and libgd-full could be installed side by side, and also, the full
variant should provide the libgd. Otherwise, if you install libgd-full,
you can not install vnstat.
Fixes: https://forum.turris.cz/t/updater-okpg-collision-of-dependencies/17520/3

libgd: add conflicts to each other

---

utils/vim/Makefile

Description:
This adds conflicts between the variants,
because they provide the same files, and it should not be
possible to install them side by side. Otherwise, it might happen that
half files would be from one variant and the other half from the
other.
Also, adds provides as if you request to install ``vim`` and
``vim-full``, then the request could be satisfied even they collide,
because ``vim-full`` provides ``vim`` package.
Fixes: https://forum.turris.cz/t/installing-vim-fuller-breaks-automatic-updates/16720

vim: variants conflict with each other

---

net/v2raya/Makefile

Maintainer: me
Description:
Release note: https://github.com/v2rayA/v2rayA/releases/tag/v1.5.9.1698.1

v2raya: Update to 1.5.9.1698.1

---

lang/python/django/Makefile

Fixes: https://nvd.nist.gov/vuln/detail/CVE-2022-36359

[21.02] django: bump to version 3.2.15

---

lang/python/django/Makefile

Fixes: https://nvd.nist.gov/vuln/detail/CVE-2022-36359

[22.03] django: bump to version 4.0.7

---

lang/python/django/Makefile
lang/python/python-evdev/Makefile
lang/python/python-pytz/Makefile

Maintainer: me, @peter-stadler (for Django)
Compile tested: x86  https://github.com/openwrt/openwrt/commit/beeb49740bb4f68aadf92095984a2d1f9a488956
Run tested: x86  https://github.com/openwrt/openwrt/commit/beeb49740bb4f68aadf92095984a2d1f9a488956

django, python-{evdev,pytz}: bump versions

---

lang/lua-eco/Makefile

Maintainer: @zhaojh329 
Run tested: none -- verified that it does not change packaged library
Description:
Currently, lua-eco will add dependencies to all SSL libraries that are
selected, even though it will only use one of them.  That means that the
package downloaded from the regular repository will install OpenSSL,
wolfSSL and mbedTLS, even though it will only use OpenSSL.
Fix that by adding a built option so that the default can be changed at build-time.  To maintain the author's intention, a default symbol is computed based on what libraries are being built into the image, or just selected as a module.  Originally, the order or preference was OpenSSL, wolfSSL, then mbedTLS.
One change was made to the original order: if OpenSSL and wolfSSL are both …

lua-eco: rework SSL library dependency & selection

---

lang/python/python-uci/Makefile

Maintainer: me
- Release notes:
https://gitlab.nic.cz/turris/pyuci/-/tags/v0.9.0
- Update copyright while at it.

python-uci: update to version 0.9.0

---

admin/syslog-ng/Makefile
admin/syslog-ng/files/syslog-ng.logrotate

Compile tested: glinet-b1300, turris-omnia, 19.07, 22.03
Run tested: glinet-b1300, turris-omnia, 19.07, 22.03
Description:
With heavy system logging which goes by default into `/var/log/messages`
log file which is usually placed in tmpfs/RAM one can trigger OOM killer
fairly easily, thus killing random processes and in some cases making
system unusable.
This is likely happening due to the fact, that Linux by default uses 1/2
of available RAM for tmpfs, which might be for example an issue on low
RAM devices with ath10k wireless.
So let's fix it by adding logrotate functionality which should limit the
size of `/var/log/messages` log file to 1M by default, but could be
tweaked by config knob if needed be.

syslog-ng: fix OOM issues by adding support for logrotate

---

net/simple-adblock/files/simple-adblock.init

Maintainer: me
Compile tested: x86_64, Sophos SG-135, OpenWrt 22.03.0-rc6
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.0-rc6, test allow command

simple-adblock: bugfix for allow command

---

net/simple-adblock/files/simple-adblock.init

Maintainer: me
Compile tested: x86_64, Sophos SG-135, OpenWrt 22.03.0-rc6
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.0-rc6, test allow command
(cherry picked from commit 717499e62b59e0a03b9550de56cadc6885b05b2d)

[22.03] simple-adblock: bugfix for allow command

---

lang/python/python-pycares/Makefile

Maintainer: @dynasticorpheus 
Compile / Run tested: Linksys_wrt32x, mvebu (cortex-a9), OpenWrt 22.03.0-rc6
Description: Add new package [pycares](https://pypi.org/project/pycares/)

python-pycares: add new package

---

libs/libssh2/Makefile

Release Notes:
https://www.libssh2.org/changes.html

libssh2: update to 1.10.0

---

libs/libpam/Makefile

Release Notes:
https://github.com/linux-pam/linux-pam/releases/tag/v1.5.2
Install the pkgconfig files for provided libraries.

libpam: update to 1.5.2

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream [release](https://github.com/docker/compose/releases).
Third one in a few hours.

docker-compose: Update to version 2.10.2

---

net/xray-core/Makefile

Maintainer: me
Description:
Release note: https://github.com/XTLS/Xray-core/releases/tag/v1.5.10
Closes: #19274

xray-core: Update to 1.5.10

---

net/gg/Makefile

Maintainer: me
Description:
Fix compile in Go 1.19
Release note: https://github.com/mzz2017/gg/releases/tag/v0.2.9

gg: Update to 0.2.9

---

utils/yq/Makefile

Maintainer: me
Description:
Release note: https://github.com/mikefarah/yq/releases/tag/v4.27.3

yq: Update to 4.27.3

---

net/tinc/Makefile
net/tinc/files/tinc.init

Signed-off-by: Erwan MAS <erwan@mas.nom.fr>
Run tested: Linksys WRT1900ACS with 21.02.3 on mvebu/cortexa9 
Description:
backport of :
- use 'uci_get_state' instead of 'uci -P /var/state get'  ( 440d3c04505719df09e39706e6af7c470a49d458 )
- add creation of hosts directory for each network configuration ( fb99d50c1edd4be765bef6d55bee26bfb90576b6 )

tinc: backport  from master modifications 

---

libs/libssh/Makefile

Release Notes:
https://www.libssh.org/2022/08/26/libssh-0-10-0/

libssh: update to 0.10.0

---

net/openvpn/Makefile

Maintainer: me / @mkrkn 
Compile tested: ath79/generic, ramips/mt7620, ramips/mt7621
Run tested: ath79/Archer C7v2, mt7620/Xiaomi Mi-Mini, mt7621/Xiaomi Mi Router 3 Pro
Engine support is deprecated in OpenSSL 3.0 and for OpenSSL 3.0 the default
is to disable engine support as engine support is deprecated. For ath79 architecture
build with autodetection engine support fails, so explicitly set off for now.

openvpn-2.5.7: explicitly disable engine parameter for openssl variant

---

lang/luaossl/Makefile

Maintainer: me
Compile tested: mipsel_24kc, YOUKU YK1, 21.02.1
Run tested: mipsel_24kc, YOUKU YK1, 21.02.1
```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio (double int32)
> for k, v in pairs(require('openssl')) do print(k, v) end
NO_MDC2	true
NO_NEXTPROTONEG	true
NO_RC5	true
NO_UNIT_TEST	true
NO_RFC3779	true
NO_SEED	true
NO_IDEA	true
NO_MD2	true
SSLEAY_VERSION	0
SHLIB_VERSION_NUMBER	1.1
NO_EC2M	true
OPENSSL_VERSION_NUMBER	269488335
NO_SCTP	true
NO_CAMELLIA	true
NO_WHIRLPOOL	true
SSLEAY_CFLAGS	1
SSLEAY_DIR	4
extensionSupported	function: 0x4132f0
SSLEAY_BUILT_ON	2
SSLEAY_PLATFORM	3
version	function: 0x134a1e0
VERSION_NUMBER	269488335
NO_STATIC_ENGINE	true
VERSION_TEXT	OpenSSL 1.1.1l  24 Aug 2021
SHLIB_VERSION_HISTORY	
SSLEAY_VERSION_NUMBER	269488335
> 
```
Description:

luaossl: update to rel-20220711

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

Description: Update HAProxy to v2.6.4

haproxy: Update HAProxy to v2.6.4

---

libs/libssh/Makefile

Release notes:
https://www.libssh.org/2022/09/02/libssh-0-10-2/
Maintainer: @mislavn (but is not responding?)
Run tested: no

libssh: update to 0.10.2

---

net/gg/Makefile

Maintainer: me
Description:
- Backported from: #19282

[openwrt-22.03] gg: Update to 0.2.9

---

utils/yq/Makefile

Maintainer: me
Description:
- Backported from: #19283

[openwrt-21.02] yq: Update to 4.27.3

---

net/dnsproxy/Makefile

Maintainer: me
Description:
Release note: https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.44.0

dnsproxy: Update to 0.44.0

---

net/dnslookup/Makefile

Maintainer: me
Description:
Fix build in Go 1.19

dnslookup: Update to 1.7.3

---

libs/libtorrent-rasterbar/Makefile

Run tested: -
Description:
Release note: https://github.com/arvidn/libtorrent/releases/tag/v2.0.7

libtorrent-rasterbar: Update to 2.0.7

---

net/dnsproxy/Makefile

Maintainer: me
Description:
- Backported from: #19300

[openwrt-22.03] dnsproxy: Update to 0.44.0

---

net/dnslookup/Makefile

Maintainer: me
Description:
- Backported from: #19298

[openwrt-22.03] dnslookup: Update to 1.7.3

---

utils/mariadb/patches/210-no-altivec.patch

MariaDB's PPC64 CRC32 support requires AltiVec, which QoriQ does not
support. Disable it.
Maintainer: @miska 
Compile tested: ppc64

mariadb: fix compilation with ppc64

---

libs/libssh/Makefile

Release notes:
https://www.libssh.org/2022/09/05/libssh-0-10-3/
Maintainer: @mislavn (but is not responding?)
Run tested: no

libssh: update to 0.10.3

---

libs/ldns/Makefile

Tested: Linksys WRT-3200ACM
Description: ldns update to 1.8.3

ldns: update to 1.8.3

---

net/memcached/Makefile

Release Notes:
- 1.6.16: https://github.com/memcached/memcached/wiki/ReleaseNotes1616
- 1.6.17: https://github.com/memcached/memcached/wiki/ReleaseNotes1617
Run tested: mikrotik sxtsq 5ac

memcached: update to 1.6.17

---

net/nextdns/Makefile
net/nextdns/files/nextdns.defaults

Maintainer: @rs 
When nextdns is prepackaged into firmware, the post install section does not run. This PR moves that logic into /etc/uci-defaults/nextdns to cover both cases.
The same as https://github.com/openwrt/packages/pull/19045 , but addresses the comments in the original MR.
Signed-off-by: Marc Benoit <marcb62185@gmail.com>

nextdns: initialize nextdns from /etc/uci-defaults

---

libs/libfmt/Makefile

Maintainer: me
Run tested: ath79, tp-link Archer C7 v4, trunk, compiled with knxd package
Description:
new upstream release

libfmt: bump to upstream version 9.1.0

---

net/miniupnpd/Makefile
net/miniupnpd/files/firewall4.include
net/miniupnpd/files/miniupnpd.defaults.nftables
net/miniupnpd/files/miniupnpd.init
net/miniupnpd/files/nftables.d/chain-post/dstnat/20-miniupnpd.nft
net/miniupnpd/files/nftables.d/chain-post/forward/20-miniupnpd.nft
net/miniupnpd/files/nftables.d/chain-post/srcnat/20-miniupnpd.nft
net/miniupnpd/files/nftables.d/table-post/20-miniupnpd.nft

Maintainer: currently unassigned
Compile tested: r20484+1-6790e1a892 x86/64 QEMU, r20484+1-6790e1a892 mt7621 er-x
Run tested: mt7621, er-x
Description from the commit:
- Bump to the latest Git version in order to increase the package version
for simpler opkg upgrade of the broken version
- (Re-)Introduce PKG_RELEASE into the package, omitting it may lead to
opkg segmentation faults under certain circumstances
- Utilize automatic include hooks to drop the isolated miniupnpd table
in favor to chains within the main inet fw4 table, otherwise PCP is
unreliable as the upnp table might accept traffic which is later
rejected by fw4
- Install a fw4 script hook to restart miniupnpd on fw4 restarts and
reloads in order to repopulate the upnp chains with forward rules
- Register the used miniupnpd …

miniupnpd: rework firewall4 integration

---

net/squid/patches/020-libxml-drop-xmlSetFeature.patch

Run tested: -
Description:
Add a patch which removes a call in Libxml2Parser.cc to 'xmlSetFeature'.
This function belongs to the 'depreciated' API part and is not
available in OpenWrt builds.
According to my understanding, this call can be removed safely since
it disables the feature "substitute entities" which is disabled by default.

squid: fix compilation with libxml (refs #19099)

---

multimedia/yt-dlp/Makefile

yt-dlp: update to 2022.9.1

---

admin/syslog-ng/Makefile
admin/syslog-ng/files/syslog-ng.conf

Maintainer: me
Compile tested and run tested on: OpenWrt 21.02.3, Turris Omnia, mvebu/cortex-a9
Description:
- Release notes: https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-3.38.1
- Update the configuration file to use version 4.0 as mentioned in the release notes to try the latest changes

syslog-ng: update to version 3.38.1

---

libs/sx1302_hal/Makefile
libs/sx1302_hal/patches/000-edit_cflags.patch
libs/sx1302_hal/patches/001-add_compatibility_with_basicstation.patch
libs/sx1302_hal/test.sh
net/basicstation/Makefile
net/basicstation/files/etc/config/basicstation
net/basicstation/files/etc/init.d/basicstation
net/basicstation/patches/000-include_sys_time.patch
net/basicstation/src/CMakeLists.txt
net/basicstation/test.sh

Maintainer: me
Compile tested: x86_64, lantiq_xrx200, latest openwrt-21.02, latest openwrt-22.03
Run tested: x86_64, lanitq_xrx200, latest openwrt-21.02, latest openwrt-22.03
Description:
(LoRa) Basicstation is an implementation of a LoRa packet forwarder and is intended to be run on the host of a LoRa-based gateway. Basicstation forwards RF packets recieved by a concentrator to a LoRaWAN network server (LNS). It also transmits RF packets received from the LNS to one or multiple LoRa end devices.
Further information: https://lora-developers.semtech.com/build/software/lora-basics/lora-basics-for-gateways
The SX1302 hardware abstraction layer is required by the basicstation to control the concentrator based on SX1302/SX1303 chip.
Testing:
Several Class-A end devices from different …

basicstation, sx1302_hal: initial commit

---

lang/python/python-docker/Makefile

Maintainer: me
Description:
New upstream version.
`python3-packaging` is a new dep, `python3-urllib3` should have been there earlier, and I haven't found any use of `python3-six` within the package anymore, it is just referenced in a text file but I'm not sure if I'm missing anything.

python-docker: Update to 6.0.0

---

lang/python/python-dotenv/Makefile

Maintainer: me
Description:
New upstream version.
I've added `python3-click` as dependency since the standalone `dotenv` was being installed but failed to run without it. Furthermore, the error you get says to `pip install dotenv[cli]` which doesn't show in any way the `click` dep.
Added:
- CLI: add support for invocations via 'python -m'.
- load_dotenv function now returns False.
- CLI: add --format= option to list command.
Fixed:
- Drop Python 3.5 and 3.6 and upgrade GA
- Use open instead of io.open.
- Improve documentation for variables without a value
- Add parse_it to Related Projects
- Update README.md
- Improve documentation with direct use of MkDocs

python-dotenv: update to v0.21.0

---

lang/python/python-websocket-client/Makefile

Maintainer: me
Description:
New upstream version.
- Fix stack growth bug when `run_forever` reconnects
- Add doctest CI for sphinx docs code examples (d150099)
- General docs improvements
- Fix automatic reconnect with `run_forever`
- Allow a timeout to be set when using a proxy

python-websocket-client: update to 1.4.1

---

net/aria2/Makefile
net/aria2/files/aria2.init

The original procd_add_jail_mount "$config_file" will cause the init script unable to start the aria2 process.
Maintainer: me
Compile tested: (Linux MIPS, OpenWrt 21.02.1)
Run tested: (Linux MIPS, OpenWrt 21.02.1)
Description:
Re-mount `$config_file` inside `$config_dir` in jail will cause all files unreadable, thus unable to start the service, besides the second `procd_add_jail_mount_rw "$dir" "$config_dir"` already includes the `$config_file`.
Also, it is necessary to read-only all certificate files, so update `procd_add_jail_mount "$config_file"` to `procd_add_jail_mount "$ca_certificate" "$certificate" "$rpc_certificate" "$rpc_private_key"`.

aria2: fix aria2.init re-mount issue

---

lang/python/python3/patches/030-bpo-43112-detect-musl-as-a-separate-SOABI-GH-24502.patch
lang/python/python3/patches/131-configure_ac-switch-PLATFORM_TRIPLET-suffix-to-musl.patch

Patch 030:
Backported from Python main branch[^1] for Python to distinguish between glibc and musl libc SOABI.
Patch 131:
Changes PLATFORM_TRIPLET -gnu/-musl suffix detection (performed by the backported patch)
to be based on the target OS instead of the building OS.
See included patches for more detailed descriptions.
Specifically this fixes cross-compilation for mpc8548 CPUs with SPE instructions[^2] enabled.
[^1]: merged to python:main as https://github.com/python/cpython/pull/24502 'bpo-43112: detect musl as a separate SOABI'
[^2]: https://www.nxp.com/docs/en/reference-manual/SPEPEM.pdf
Co-authored-by: Pali Rohár <pali@kernel.org>
Signed-off-by: Šimon Bořek <simon.borek@nic.cz>
Maintainer: @jefferyto
Compile and run tested: mpc85xx/p2020, Turris 1.x, OpenWrt 21.02 and master

python3: backport and fix target musl libc detection

---

net/aria2/Makefile
net/aria2/files/aria2.init

Maintainer: @Narakuku 
Description:
Re-mount '$config_file' inside the '$config_dir' will cause aria2 process unable to start.
Signed-off-by: Naraku J <74468372+Narakuku@users.noreply.github.com>
(cherry picked from commit 3eba8468e1e93e5f66df20aa3f8ebe5d3f1cffea)

[22.03] aria2: Fix aria2.init start issue

---

lang/python/python3-iperf3/Makefile
net/iperf3/Makefile

```
iperf3: add shared libiperf library and link iperf3 dynamically
Add library for creating own functions with iperf3 functionality.
Example: https://github.com/esnet/iperf/blob/master/examples/mis.c
This library is needed by python3-iperf3.
Build iperf3 binary with dynamically linked libiperf3. However, still
build iperf3-ssl as static binary due to a lack of shipping two libiperf
versions.
```
```
python3-iperf3: add iperf3 python wrapper
This wrapper gives us an easy to use api for using iperf3 in python.
```
Compile tested: belkin rt3200
Run tested: belkin rt3200

iperf3/python-iperf3: add python-iperf3 and necessary libs

---

net/smartdns/Makefile

Maintainer: me
Compile tested: TL-WR703N/OpenWrt SNAPSHOT r20402-f0adf253fd

smartdns: bump to 1.2022.38

---

utils/tree/Makefile

Upstream update
Maintainer:  @hbl0307106015

tree: bump to 2.0.4

---

net/rsync/Makefile

Bump to latest upstream release.

rsync: bump to 3.2.6

---

libs/libqmi/Makefile

Signed-off-by: Maxim Anisimov [maxim.anisimov.ua@gmail.com](mailto:maxim.anisimov.ua@gmail.com)
Maintainer: Nicholas Smith [nicholas@nbembedded.com](mailto:nicholas@nbembedded.com)
on amd64 for mipsel_24kc on https://git.openwrt.org/openwrt/openwrt.git commit https://github.com/openwrt/packages/commit/54f493ed9d283620d8bbf468df5c024eed383dbb
Run tested:
Zbtlink ZBT-WG3526

libqmi: bump to 1.30.8

---

net/modemmanager/Makefile

Signed-off-by: Maxim Anisimov [maxim.anisimov.ua@gmail.com](mailto:maxim.anisimov.ua@gmail.com)
Maintainer: Nicholas Smith [nicholas@nbembedded.com](mailto:nicholas@nbembedded.com)
on amd64 for mipsel_24kc on https://git.openwrt.org/openwrt/openwrt.git commit 54f493ed9d283620d8bbf468df5c024eed383dbb
Run tested:
Zbtlink ZBT-WG3526
This pull request depends on https://github.com/openwrt/packages/pull/19348

modemmanager: bump to 1.18.12

---

libs/liboil/Makefile

Fixes a compile error when glib2 is missing.
get rid of nls.mk. iconv/gettext is not used. This was previously here because of glib2.
Compile tested: mips64 WSL

liboil: small cleanups

---

net/iperf3/Makefile

In the Makefile the library installation was accidentally called "Package/iperf3/install" and not "Package/libiperf3/install". Fix this typo. Thanks to Hartmut spotting this.
Also the iperf3-ssl does not need to depend on libiperf3.
Fixes ae48be8e2157 ("iperf3: add shared libiperf library and link iperf3 dynamically")
Compile tested: Belkin
Run tested: Belkin

iperf3: fix install section of Makefile and dependencies

---

multimedia/gst1-plugins-base/Makefile

gst1-plugins-base: remove liboil dependency

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream update.
[Changelog](https://github.com/docker/compose/releases)

docker-compose: Update to version 2.11.0

---

net/keepalived/Config.in
net/keepalived/Makefile
net/keepalived/files/keepalived.init
net/keepalived/files/usr/libexec/rpcd/keepalived

keepalived: add status rpc and service improvement
- enable json by default to generate json stats
- add rpc to generate json status
- add kmod-nf-ipvs dependencies for virtual servers
- set default vip labels on virtual interfaces
- set process name for keepalived child processes
Signed-off-by: Jaymin Patel <jem.patel@gmail.com>
Run tested: x86-64, aarch64, virtual box, master
Description:
- add RPC to generate JSON status and fix dependencies for ipvs
**We need this for https://github.com/openwrt/luci/pull/5965**

keepalived: add status rpc and service improvement

---

lang/python/python-flask-socketio/Makefile

Compile tested: aarch64, Turris MOX, OpenWrt 21.02
Run tested: aarch64, Turris MOX, OpenWrt 21.02
Description:

python-flask-socketio: update to 5.3.1

---

utils/collectd/Makefile

Temporarily disable nut plugin by marking it BROKEN. Apparently the upstream collectd plugin is not yet compatible with nut 2.8.0.
I tried the upstream PR 4043, but it does not help, as it apparently requires at least one specific UPS type to be defined/compiled.
nut . . . . . . . . . no (required data types for NUT API were not detected) (dependency error)
If there is a requirement to specify some UPS data type when compiling nut, it might be problematic for the generic OpenWrt buildbot context.
Maintainer: me

collectd: disable nut plugin (incompatibility with nut 2.8.0)

---

multimedia/midisport-firmware/Makefile
multimedia/midisport-firmware/files/midisport-firmware.hotplug

Add package with user-space loaded firmware for M-Audio USB MIDI interfaces.
Implement OpenWrt-specific hotplug script which uses 'fxload' from libusb examples.
Depends on https://github.com/openwrt/openwrt/pull/10716

midisport-firmware: add package

---

net/nut/Makefile
net/nut/patches/001-clients-upsclient.h-ensure-time_t-is-defined.patch

Maintainer: none listed
Compile tested: mediatek/mt7622, aarch64, openwrt master
Description:
Add --without-linux-i2c to configure arguments to avoid using i2c if found in the staging dir.
Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>
---
Adding a commit with an upstream patch that fixes collectd build:
```
src/nut.c:40:2: error: #error "Unable to determine the UPS connection type."
40 | #error "Unable to determine the UPS connection type."
|  ^~~~~
src/nut.c:46:3: error: unknown type name 'collectd_upsconn_t'
```
The failure to detect UPS was due to `time_t` not being defined by nut `upsclient.h`.

nut: avoid picking up libi2c dependency, fix collectd build

---

net/nextdns/Makefile

Maintainer: @rs 
Update to version 1.37.11

[openwrt-22.03] nextdns: Update to version 1.37.11 

---

lang/python/python-jsonschema/Makefile
lang/python/python-jsonschema/patches/001-setup.patch

Maintainer: me
Description:
New upstream [release](https://github.com/python-jsonschema/jsonschema/releases).

python-jsonschema: Update to 4.15.0

---

utils/collectd/Makefile
utils/prometheus-node-exporter-lua/Makefile

This depends on https://github.com/openwrt/openwrt/pull/10586
It simplifies and cleans up the dependencies of consumers of the dsl ubus stats.
Maintainers: @champtar @jow- @hnyman 
I tested prometheus, but not collectd, so cc @jekkos @feckert

prometheus/collectd: adapt dependencies for the dsl collector 

---

utils/collectd/Makefile

Re-enable the nut plugin (remove BROKEN mark).
Nut itself has been patched to provide better compatible time_t.
I have not not run-tested the plugin, so it is still possible that the fixes from upstream collectd PR 4043 are needed.
Compile tested: ipq806x/R7800

collectd: re-enable nut plugin

---

utils/grep/Makefile

We should use libpcre2 instead of libpcre in the new grep version.
Run tested: ipq40xx avm fritz!box 4040

grep: use libpcre2

---

utils/telldus-core/Makefile
utils/telldus-core/patches/100-add_includes.patch

Needed for memset.
Maintainer: @PeterFromSweden

telldus-core: add missing include

---

net/v2ray-geodata/Makefile
net/xray-core/Makefile

Maintainer: me
Description:
Release note: https://github.com/XTLS/Xray-core/releases/tag/v1.6.0

xray-core: Update to 1.6.0

---

libs/jose/Makefile
libs/jose/patches/010-whole.patch

When libjose is built statically, it must use --whole-archive as it uses GCC's constructor attribute to initialize itself.
Maintainer: @Tiboris 
Compile tested: Fedora 36
ping @nilsmeyer @jilroy

jose: fix static library usage

---

utils/collectd/files/collectd.init

Compile tested: not needed, script changes
Run tested: x86_64, APU3, OpenWrt lastest
Description:
The network plugin from collectd also has the option to encrypt the
metrics when sending them to another server. Until now, this was not
possible via the UCI. This commit adds that feature.
Tests:
I have set up a telegraf server with the required encryption and configurred the collectd via uci to send the data in encrypted form.
**UCI-Config:**
```
config network_server
option host '172.16.2.250'
option port '25826'
option SecurityLevel 'Encrypt'
option Username 'VR2-106149'
option Password 'Ahchae4w'
```
**Collectd-output:**
```
<Plugin network>
<Server "172.16.2.250" "25826">
SecurityLevel "Encrypt"
Username "VR2-106149"
Password "Ahchae4w"
</Server>
Forward true …
```

collectd: extend network uci plugin

---

lang/php8/Makefile

Maintainer: me
Description:
(cherry picked from commit 026a672ad10898705f57f421ad09cf083bdfec13)

[22.03] php8: update to 8.1.10

---

libs/libxml2/Makefile

Maintainer: me
Description:
This fixes:
- CVE-2022-2309
Release Notes:
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.0
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.1
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.2
Also drop removed docbook compile switch.
Disable PKG_FIXUP to allow backporting.

libxml2: update to 2.10.2 (closes #19288)

---

net/knot/Makefile

Maintainer: @Payne-X6
Compile tested: aarch64, Turris MOX, OpenWrt 21.02
Run tested: aarch64, Turris MOX, OpenWrt 21.02
Description: This is a bugfix release, so it should go to all supported stable versions including 21.02, it's currently only in master and 22.03.

[21.02] knot: update to version 3.2.1

---

net/lighttpd/Makefile

Description:
update to lighttpd 1.4.67 release hash
Signed-off-by: Glenn Strauss [gstrauss@gluelogic.com](mailto:gstrauss@gluelogic.com)

lighttpd: update to lighttpd 1.4.67 release hash

---

net/gg/Makefile

Maintainer: me
Description:
Allow `gg sudo` and `gg su`.
Release note: https://github.com/mzz2017/gg/releases/tag/v0.2.11

gg: Update to 0.2.11

---

utils/yq/Makefile

Maintainer: me
Description:
Release note: https://github.com/mikefarah/yq/releases/tag/v4.27.5

yq: Update to 4.27.5

---

libs/libtorrent-rasterbar/Makefile

Run tested: -
Description:
- Backported from #19304

[openwrt-21.02] libtorrent-rasterbar: Update to 2.0.7

---

libs/libtorrent-rasterbar/Makefile

Run tested: -
Description:
- Backported from #19304

[openwrt-22.03] libtorrent-rasterbar: Update to 2.0.7

---

net/wifi-presence/Makefile

Maintainer: me / @awilliams 
OpenWRT 22.03.0
- arm_arm1176jzf-s_vfp
- arm_arm926ej-s
- arm_cortex-a15_neon-vfpv4
- arm_cortex-a5_vfpv4
- arm_cortex-a7
- arm_cortex-a7_neon-vfpv4
- arm_cortex-a7_vfpv4
- arm_cortex-a8_vfpv3
- arm_cortex-a9
- arm_cortex-a9_neon
- arm_cortex-a9_vfpv3-d16
- arm_fa526
- arm_mpcore
- arm_xscale
- i386_pentium-mmx
- i386_pentium4
- mips64_octeonplus
- mips_24kc
- mips_4kec
- mips_mips32
- mipsel_24kc
- mipsel_24kc_24kf
- mipsel_74kc
- mipsel_mips32
Run tested:
- Tested on 2 different routers running OpenWRT 22.03.0 for 24+ hours
Description:
This version better decodes SSID names which contain emoji, control characters, and other non-ascii characters.
https://github.com/awilliams/wifi-presence/pull/8

wifi-presence: Update to version v0.2.0

---

net/bind/Makefile

Fixes multiple security issues:
CVE-2022-38178 - Fix memory leak in EdDSA verify processing
CVE-2022-3080 - Fix serve-stale crash that could happen when
stale-answer-client-timeout was set to 0 and there was
a stale CNAME in the cache for an incoming query
CVE-2022-2906 - Fix memory leaks in the DH code when using OpenSSL 3.0.0
and later versions. The openssldh_compare(),
openssldh_paramcompare(), and openssldh_todns()
functions were affected
CVE-2022-2881 - When an HTTP connection was reused to get
statistics from the stats channel, and zlib
compression was in use, each successive
response sent larger and larger blocks of memory,
potentially reading past the end of the allocated
buffer
CVE-2022-2795 - Prevent excessive resource use while processing large
delegations
Signed-off-by: Noah …

bind: bump to 9.18.7

---

libs/libmspack/Makefile
utils/open-vm-tools/Makefile
utils/open-vm-tools/files/telinit
utils/open-vm-tools/files/tools.conf

Maintainer: @neheb  @srchack
Compile tested: x86_64, VMware-Image, OpenWrt latest master
Run tested: x86_64, VMware-Image, OpenWrt latest master
Description:
VMware offers the option of creating machines as templates and then cloning them.
In order for this to work with an OpenWrt Image, the cloned system must be customizable to set the for example the following options.
- Hostname
- IP
For this to work the open-vm-tools in OpenWrt must first support it.
This pullrequest enables the necessary compilation options and also adds the necessary lib dependencies.
In addition, the Perl script on the VMware-ESXi must be extended so that it also recognizes the OpenWrt distribution.
For this I have patched the perl script on the ESXi that works with my setup.
Patches: …

open-vm-tools: enable clone customization

---

net/aria2/Makefile
net/aria2/files/aria2.init

Maintainer: me
Compile tested: (Linux MIPS, OpenWrt 21.02.1)
Run tested: (Linux MIPS, OpenWrt 21.02.1)
Description:
Merge from #18270

aria2: Fix aria2.init start issue

---

libs/libcli/Makefile
net/netsniff-ng/Makefile

Maintainer: @utoni (netsniff-ng) and myself (libcli)
Compile tested: Lantiq xRX200 BT Home Hub 5A
Run tested: Lantiq xRX200 BT Home Hub 5A
Preconditions:
Description:
mausezahn is a multicast traffic generator and heavily used by kernel selftests (`tools/testing/selftests/net/forwarding/`). packaging mausezahn is a pre-condition for an upcoming package with these kernel selftests
netsniff-ng's `configure` script is smart enough to auto-detect which dependencies are available and based on that which tools to build. building mausezahn without netsniff-ng and vice versa is possible, meaning we don't need to pull in libcli for netsniff-ng builds or pull in zlib for mausezahn buillds

netsniff-ng: build and package mausezahn and it's dependency libcli

---

net/pdns-recursor/Makefile

Maintainer: me
Run tested: x86_64 in Docker
Description:

pdns-recursor: update to 4.7.3

---

net/knot-resolver/Makefile
net/knot-resolver/patches/010-fix-lmdb.patch
net/knot-resolver/patches/030-fix-policy-hack.patch

Compile tested: aarch64, Turris MOX, OpenWrt 21.02 (tested on Turris OS which has a separate package for knot-resolver)
Run tested: aarch64, Turris MOX, OpenWrt 21.02
Description: fixes CVE-2022-40188, this update should be backported to all stable branches.
cc @BKPepe

knot-resolver: update to 5.5.3

---

libs/glib2/patches/020-locale.patch

Fixes compilation with non English locale.
ping @zxlhhyccc

glib2: backport locale fix

---

net/dnslookup/Makefile

Maintainer: me
Description:
Added `DNS-over-HTTP/3` support.
Release note: https://github.com/ameshkov/dnslookup/releases/tag/v1.8.0

dnslookup: Update to 1.8.0

---

net/dnsproxy/Makefile

Maintainer: me
Description:
Added `DNS-over-HTTP/3` support.
Release note: https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.45.0

dnsproxy: Update to 0.45.0

---

net/lighttpd/Makefile

Description:
update to lighttpd 1.4.67 release hash (from lighttpd 1.4.66)
includes backport of security bugfix to 22.03
Signed-off-by: Glenn Strauss [gstrauss@gluelogic.com](mailto:gstrauss@gluelogic.com)

lighttpd: update to lighttpd 1.4.67 release hash - backport to openwrt 22.03

---

net/lighttpd/Makefile

Description:
update to lighttpd 1.4.67 release hash (from lighttpd 1.4.65)
includes backport of security bugfix to 21.02
Signed-off-by: Glenn Strauss [gstrauss@gluelogic.com](mailto:gstrauss@gluelogic.com)

lighttpd: update to lighttpd 1.4.67 release hash - backport to openwrt 21.02

---

utils/yq/Makefile

Maintainer: me
Description:
- Backported from: #19398

[openwrt-21.02] yq: Update to 4.27.5

---

net/gg/Makefile

Maintainer: me
Description:
- Backported from: #19401

[openwrt-22.03] gg: Update to 0.2.11

---

net/gatling/Makefile
net/gatling/patches/010-decrease_optimisation.patch
net/gatling/patches/020-configure_features.patch
net/gatling/test.sh

Gatling is a high-performance webserver from fefe. It gives a fairly decent feature-set at really small size. And its fast.
Co-authored-by: Josef Schlehofer <pepe.schlehofer@gmail.com>
Signed-off-by: Martin Hübner <martin.hubner@web.de>
(cherry picked from commit 83ff83e32055dc50b01fffe7bae9ea113655756b)
Compile tested: see commit in master-branch #19136
Run tested: see commit in master-branch #19136

gatling: backport package gatling to 22.03

---

net/snowflake/Makefile
net/snowflake/files/snowflake-proxy.init

Package [Tor's Snowflake](https://snowflake.torproject.org) system components so users can offer e.g. a standalone Snowflake proxy on their routers or other devices.
Compile tested: arm_cortex-a53
Run tested: Belkin RT3200, snapshot
More users should try `snowflake-proxy`, esp. also on MIPS systems.

snowflake: add package

---

net/snowflake/Makefile
net/snowflake/files/snowflake-proxy.init

Package Tor's Snowflake system components so users can offer e.g. a standalone Snowflake proxy on their routers or other devices.
(cherry picked from commit cf120a7effd5d13a7f705b5eb9d22410b73d71f3)
Maintainer: @dangowrt, me
Compile tested: 22.03 Linksys E8450
Run tested: 22.03 Linksys E8450

[22.03] snowflake: add package

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.sources

Signed-off-by: james-mcguire <jamesm51@gmail.com>
Maintainer: @dibdot
Run tested: ARMv7, ipq806x, Netgear R7800, working locally with 22.03
Description: Adds a new blocklist [source](https://github.com/lightswitch05/hosts) to adblock

adblock: add lightswitch05 source

---

lang/php8-pecl-xdebug/Makefile

Maintainer: me
Description:
This add the Xdebug pecl extension as requested in 19424.

php8-pecl-xdebug: add package (refs #19424)

---

net/squid/patches/020-libxml-drop-xmlSetFeature.patch

Run tested: -
Description:
Add a patch which removes a call in Libxml2Parser.cc to 'xmlSetFeature'. This function belongs to the 'depreciated' API part and is not available in OpenWrt builds.
According to my understanding, this call can be removed safely since it disables the feature "substitute entities" which is disabled by default.
(cherry picked from commit 3ec47dc85cc4b191be1b2fee3195680343f770e1)

[22.03] squid: fix compilation with libxml (fixes #19099)

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

Description: Update HAProxy to v2.6.6

haproxy: Update HAProxy to v2.6.6

---

utils/docker-compose/Makefile

docker-compose: Update to version 2.11.1

---

net/tor/Makefile

Release Notes:
https://forum.torproject.net/t/urgent-stable-release-0-4-5-14-0-4-6-12-and-0-4-7-10
Maintainer: 
Compile tested: Bananapi BPI-R64
Run tested: Bananapi BPI-R64

tor: update to 0.4.7.10

---

lang/lua-eco/Makefile

Compile tested: mediatek/mt7622 aarch64_cortex-a53, master
Run tested: tested with `make menuconfig`--does not change the installed binaries.
Description:
libwolfsslcpu-crypto has to be taken into consideration when selecting the default SSL backend.
Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

lua-eco: adapt SSL choice to libwolfsslcpu-crypto

---

net/curl/Makefile

Maintainer: me
Description:
* fixes https://github.com/openwrt/packages/issues/19456

curl: bugfix: github source url

---

admin/zabbix/Makefile
admin/zabbix/patches/010-change-agentd-config.patch
admin/zabbix/patches/110-reproducible-builds.patch

Updated to 6.2.3 version.
Compile tested: aarch64 cortex-a53
Run tested: aarch64 cortex-a53
Signed-off-by: Scott Roberts <ttocsr@gmail.com>

zabbix: update to 6.2.3

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.conf
net/simple-adblock/files/simple-adblock.conf.update
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.0, test lists downloads/adblocking.
Description:
* remove obsolete block-lists from config
* add removal of obsolete lists to config-update
* add AdGuard team's block-list to config
* improve allow command
* improve nftset support
* move config load to uci_load_validate, which required some code refactoring which looks dramatic, but isn't
* always use dnsmasq_restart instead of dnsmasq_hup for all dns resolution options for dnsmasq

simple-adblock: update to 1.9.1-1

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_functions.sh
net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_lucihelper.sh
net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_updater.sh

```
ddns-scripts: add explicit "-d" switch for Dry Run
It was a bit confusing to use *verbosity* level for Dry Run mode. Add
explicity switch for it and designed DRY_RUN variable to make code
easier to understand.
```
```
ddns-scripts: rename variable: s//ERR_UPDATE/RETRY_COUNT/
Rename variable to make code easier to understand. This variable
specifies how many times in row ddns script tried to update IP without a
success.
Previous name ("ERR_UPDATE") didn't suggest it was for counting
anything. It also didn't specify was error was it related to.
```
```
ddns-scripts: replace IP type (name) "local" with "current"
Local suggests something related to the local network or available
locally only. All that code related to the "local" IP was actually
dealing with *current* device external IP …
```

ddns-scripts: clean up code a bit to make it easier to understand

---

lang/python/python3/Makefile

Oversight from when the expat host build was removed.
Maintainer: @commodo @jefferyto

python3: use tools/expat for host build

---

net/unbound/Makefile
net/unbound/patches/010-configure-uname.patch

Compile tested: All Turris routers (Turris 1.x, Turris Omnia, Turris MOX) on all OpenWrt supported versions and as well with OpenWrt 19.07
Run tested: TBD
Description:
Changelog: https://www.nlnetlabs.nl/projects/unbound/download/#unbound-1-16-3
- Fixes: [CVE-2022-3204](https://nlnetlabs.nl/downloads/unbound/CVE-2022-3204.txt)

unbound: update to version 1.16.3

---

utils/bandwidthd/Makefile
utils/bandwidthd/patches/040-64bit-time-t.patch

Should fix crashing errors under musl 1.2
Maintainer: @padre-lacroix 
Fixes: https://github.com/openwrt/packages/issues/19352
I think.

bandwidthd: fix format warnings

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.conf
net/simple-adblock/files/simple-adblock.conf.update
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Description:
* remove obsolete block-lists from config
* add removal of obsolete lists to config-update
* add AdGuard team's block-list to config
* improve allow command
* improve nftset support
* move config load to uci_load_validate, which required some code refactoring which looks dramatic, but isn't
* always use dnsmasq_restart instead of dnsmasq_hup for all dns resolution options for dnsmasq
(cherry picked from commit f8c5fd93e7e055e2425729e812fe0d1e4aab8032)

[22.03] simple-adblock: update to 1.9.1-1

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Compile tested: x86_64, Sophos SG-135w, OpenWrt 22.03.0
Run tested: x86_64, Sophos SG-135w, OpenWrt 22.03.0, dns resolution, test canary domains
Description:
* switch to using uci wrappers instead of direct uci calls
* add support for iCloud canary domains https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay

https-dns-proxy: uci wrappers & iCloud canary domains

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Description:
* switch to using uci wrappers instead of direct uci calls
* add support for iCloud canary domains https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay
(cherry picked from commit 749b03ffbffbdf208bd589db6526c939d404ba79)

[22.03] https-dns-proxy: uci wrappers & iCloud canary domains

---

net/dnsproxy/Makefile

Maintainer: me
Description:
Release note:
https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.45.1
https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.45.2

dnsproxy: Update to 0.45.2

---

net/gg/Makefile

Maintainer: me
Description:
Release note:
https://github.com/mzz2017/gg/releases/tag/v0.2.12
https://github.com/mzz2017/gg/releases/tag/v0.2.13

gg: Update to 0.2.13

---

net/dnslookup/Makefile

Maintainer: me
Description:
- Backported from: #19431

[openwrt-22.03] dnslookup: Update to 1.8.0

---

libs/libmodbus/Makefile

Maintainer: me
Run tested: mxs, custom board
Description:

libmodbus: update to 3.1.8

---

lang/lua-eco/Makefile
libs/libuhttpd/Makefile
libs/libuwsc/Makefile
net/coova-chilli/Makefile
net/curl/Makefile
net/lighttpd/Makefile
net/openvpn/Makefile
net/strongswan/Makefile
net/wifidog/Makefile
utils/rtty/Makefile

Maintainer:  @zhaojh329, @teslamint, @mhaas
Description:
As wolfSSL is having hard time maintaining ABI compatibility between
releases, we need to manually force rebuild of packages depending on
libwolfssl and thus force their upgrade. Otherwise due to the ABI
handling we would endup with possibly two libwolfssl libraries in the
system, including the patched libwolfssl-5.5.1, but still have
vulnerable services running using the vulnerable libwolfssl-5.4.0.
So in order to propagate update of libwolfssl to latest stable release
done in commit [ec8fb542ec3e4](https://github.com/openwrt/openwrt/commit/ec8fb542ec3e4f584444a97de5ac05dbc2a9cde5) ("wolfssl: fix TLSv1.3 RCE in uhttpd by
using 5.5.1-stable (CVE-2022-39173)") which fixes several remotely …

treewide: fix security issues by bumping all packages using libwolfssl

---

lang/php8/Makefile

Maintainer: me
Compile tested: sunxi, cortexa7
Run tested: -
Description:
This fixes:
- CVE-2022-31628
- CVE-2022-31629

[22.03] php8: update to 8.1.11

---

lang/php7/Makefile

Maintainer: me
Description:
This fixes:
- CVE-2022-31628
- CVE-2022-31629

[21.02] php7: update to 7.4.32

---

lang/php8/Makefile
lang/php8/patches/0041-Add-patch-to-remove-build-timestamps-from-generated-.patch

Maintainer: me
Description:
This fixes:
- CVE-2022-31629
- CVE-2022-31628

[21.02] php8: update to 8.0.24

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.0, start twice, verify no duplicates for canary domains

https-dns-proxy: bugfix: prevent canary domains duplicates

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.config
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.0, start/stop
Description:
* add setting to enable/disable blocking access to iCloud Private Relay resolvers
* add setting to enable/disable blocking access to Mozilla resolvers
* rename variables loaded from config in the init script

https-dns-proxy: add settings for canary domains

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.config
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.0, start/stop
Description:* add setting to enable/disable blocking access to iCloud Private Relay resolvers
* add setting to enable/disable blocking access to Mozilla resolvers
* rename variables loaded from config in the init script
(cherry picked from commit 4ff71d8e4cd7cd4b3f4cc0d4d832ead512edef08)

[22.03] https-dns-proxy: add settings for canary domains

---

net/mwan3/Makefile
net/mwan3/files/lib/mwan3/common.sh

Signed-off-by: Denys Yarkovyi <dyarkovoy@gmail.com>
Compile tested: RTL8380, Netgear GS308T v1, OpenWrt OpenWrt SNAPSHOT r20775-165b66d910
Run tested: RTL8380, Netgear GS308T v1, OpenWrt OpenWrt SNAPSHOT r20775-165b66d910, routes are being added correctly
Description:
This solves https://github.com/openwrt/packages/issues/19488 by supporting a routing modifier "offload"

mwan3: support offload routing modifier

---

libs/libuhttpd/Makefile
libs/libuwsc/Makefile
net/coova-chilli/Makefile
net/curl/Makefile
net/lighttpd/Makefile
net/openvpn/Makefile
net/strongswan/Makefile
net/wifidog/Makefile
utils/rtty/Makefile

Backports 845d81ca0976c82829addc23e9e8b95885c910ee (#19513), we need to wait until [all targets in 22.03](https://buildbot.openwrt.org/openwrt-22.03/images/) have [fixed libwolfssl available](https://github.com/openwrt/openwrt/commit/ce59843662961049a28033077587cabdc5243b15), otherwise this update wouldn't have any effect.

[22.03] treewide: fix security issues by bumping all packages using libwolfssl

---

net/lighttpd/Makefile

Description:
lighttpd: remove deprecated modules
All of 2022, each lighttpd release has repeated announcements deprecating some minor modules for which full replacements written in lua are available and can be run using [lighttpd mod_magnet](https://wiki.lighttpd.net/Docs_ModMagnet).  The latest release announcement can be found at: https://www.lighttpd.net/2022/9/17/1.4.67/
From the **Future Scheduled Behavior Changes** section of the annoucement:
*    Continue gradual deprecation of “mini-application” lighttpd modules
for which mod_magnet lua implementations are better and more flexible.
Please post on lighttpd forums to share feedback if you use these modules.
Forums: …

lighttpd: remove deprecated modules

---

lang/node/Makefile

Compile tested: head, aarch64, arm, i386, x86_64, mipsel (pistachio) 
Run tested: (qemu 7.1.0) aarch64
Description:
Update to v16.17.1
* CVE-2022-32212: DNS rebinding in --inspect on macOS (High) * Insufficient fix for macOS devices on v18.5.0
* CVE-2022-32222: Node 18 reads openssl.cnf from /home/iojs/build/ upon startup on MacOS (Medium)
* CVE-2022-32213: HTTP Request Smuggling - Flawed Parsing of Transfer-Encoding (Medium) * Insufficient fix on v18.5.0
* CVE-2022-32215: HTTP Request Smuggling - Incorrect Parsing of Multi-line Transfer-Encoding (Medium) * Insufficient fix on v18.5.0
* CVE-2022-35256: HTTP Request Smuggling - Incorrect Parsing of Header Fields (Medium)
* CVE-2022-35255: Weak randomness in WebCrypto …

node: bump to v16.17.1

---

net/tor/Makefile

Release Notes:
https://forum.torproject.net/t/urgent-stable-release-0-4-5-14-0-4-6-12-and-0-4-7-10
Maintainer: @hauke 
Run tested: noone

[21.02] tor: update to 0.4.7.10

---

net/isc-dhcp/files/dhcpd.init

Maintainer: me
Compile tested: x86_64, generic, HEAD (60738feded)
Description:
If named already is aware of the dynamic zones and their configuration, then we don't need to reload it.

isc-dhcp: avoid gratuitous reload of named

---

utils/lcd4linux/Makefile
utils/lcd4linux/files/lcd4linux.init

Run tested: x86_64, APU3 OpenWrt master, tests done
Description:
* Until now, the configuration must be stored under '/etc/lcd4linux.conf'. So that the configuration can also be changed dynamically, it makes sense to store this under /tmp and load them from this directory. The init script first checks whether there is a configuration under '/etc/lcd4linux.conf' and only then does it try to find it under '/tmp/lcd4linux.conf'. If there is no configuration, an error message is shown.
* Setting the DEBUG variable in the init script to '1' enables the
lcd4linux verbose mode, by setting the arg '-vv'. The option also
redirects the error and stdout to the syslog.

lcd4linux: minor init improvments

---

libs/libuhttpd/Makefile
libs/libuwsc/Makefile
net/coova-chilli/Makefile
net/curl/Makefile
net/lighttpd/Makefile
net/openvpn/Makefile
net/strongswan/Makefile
net/wifidog/Makefile
utils/rtty/Makefile

Backports f624e41f38e82e3b2df83e309e7bb00b68ad0091 (#19521), we need to wait until [all targets in 21.02](https://buildbot.openwrt.org/openwrt-21.02/images/) have [fixed libwolfssl available](https://github.com/openwrt/openwrt/commit/914d91274162ba7e125fcfc781b1128b7c42a856), otherwise this update wouldn't have any effect.

[21.02] treewide: fix security issues by bumping all packages using libwolfssl

---

admin/zabbix/Makefile

opkg does not offer ssl varients of zabbix-agentd. resolve this by adding ssl varients.
Compile tested: aarch64 cortex-a53
Run tested: aarch64 cortex-a53
Signed-off-by: Scott Roberts <ttocsr@gmail.com>
Supersedes: https://github.com/openwrt/packages/pull/17846

zabbix: add variants for SSL support

---

lang/python/python-crcmod/Makefile
lang/python/python-pycrate/Makefile
net/qcsuper/Makefile

Maintainer: me
Compile tested: x86-64 / ipq40xx-generic
Run tested: apu4d4 / GL.iNet GL-AP1300
Description:
QCSuper is a diagnostic tool which allows to capture cellular frames using a Qualcomm USB modems debug port.

qcsuper: add Package w/ necessary dependencies

---

lang/node/Makefile

Compile tested: 21.02, arm 
Run tested: (qemu 7.1.0) arm
Description:
Update to v14.20.1
* CVE-2022-32212: DNS rebinding in --inspect on macOS (High)
* CVE-2022-32213: bypass via obs-fold mechanic (Medium)
* CVE-2022-35256: HTTP Request Smuggling Due to Incorrect Parsing of Header Fields (Medium) More detailed information on each of the vulnerabilities can be found in September 22nd 2022 Security Releases blog post.

[21.02] node: bump to v14.20.1

---

utils/cpusage/Makefile
utils/cpusage/src/cpusage.c

This PR adds the new package "cpusage" to OpenWrt packages. Cpusage is a small utility that prints cpu usage per second as output.
Signed-off-by: Thomas Huehn <thomas.huehn@hs-nordhausen.de>
Compile tested:  latest trunk OpenWrt apu2, r20885
Run tested:  latest trunk OpenWrt apu2, r20885, PCengines APU2d4
Description:
Cpusage is a small utility that prints cpu usage per second as output.
It makes it handy to monitor cpu usage as csv trace while perfoming router/wifi experiments.

cpusage: add new package

---

utils/yq/Makefile

Maintainer: me
Description:
Release note: https://github.com/mikefarah/yq/releases/tag/v4.28.1

yq: Update to 4.28.1

---

net/gg/Makefile

Maintainer: me
Description:
- Backported from: #19506

[openwrt-22.03] gg: Update to 0.2.13

---

net/iperf3/Makefile

Release Notes:
https://groups.google.com/g/iperf-dev/c/_DgSWrpl9Gk?pli=1
Run tested: ipq40xx

iperf3: update to 3.12

---

net/rsync/patches/010-fix-really-silly-bug-with-relative-rules.patch
net/rsync/patches/011-fix-bug-with-validating-remote-filter-rules.patch

Upstream is requesting that packagers cherry-pick two commits to fix the current release.[1]
1. https://www.mail-archive.com/rsync@lists.samba.org/msg33576.html

rsync: incorporate upstream fixes

---

libs/gnutls/Makefile

Release Notes:
https://lists.gnupg.org/pipermail/gnutls-help/2022-September/004765.html
Run tested: no

gnutls: update to 3.7.8

---

utils/yq/Makefile

Maintainer: me
Description:
- Backported from: #19559

[openwrt-21.02] yq: Update to 4.28.1

---

net/unbound/files/defaults.sh
net/unbound/files/unbound.sh

Run tested: unbound 1.16.2 with these changes and uci "unbound_control"="4", with self-generated certificates in /etc/unbound, ensure that unbound-control on a remote system can successfully interact with the server.
Description: unbound prepends the config dir path to the cert file name config values. This change makes the cert file name values in the generated unbound.conf be only the file names and corresponding path changes in unbound.sh for the cert files. Also, update unbound.sh to copy the cert files from /etc/unbound to /var/lib/unbound

unbound: update control cert uci processing

---

net/curl/patches/300-curl-wolfssl.m4-error-out-if-wolfSSL-is-not-usable.patch

Compile tested: x86/64 21.02
Description:
When we explicitly declare, that we would like to have curl built with wolfSSL support using `--with-wolfssl` configure option, then we should make sure, that we either endup with curl having that support, or it shouldn't be available at all, otherwise we risk, that we end up with regressions like following:
```
configure:25299: checking for wolfSSL_Init in -lwolfssl
configure:25321: x86_64-openwrt-linux-musl-gcc -o conftest [snip]
In file included from target-x86_64_musl/usr/include/wolfssl/wolfcrypt/dsa.h:33,
from target-x86_64_musl/usr/include/wolfssl/wolfcrypt/asn_public.h:35,
from target-x86_64_musl/usr/include/wolfssl/ssl.h:35,
from conftest.c:47: …
```

curl: error out if wolfSSL is not usable

---

net/stunnel/Makefile

Maintainer: me
Compile tested: x86_64 and lantiq_xrx200, latest OpenWrt master
Run tested: x86_64, APU3, latest OpenWrt version, execute `stunnel`
Description:
```
root@vrrp-master / # stunnel
[.] stunnel 5.66 on x86_64-openwrt-linux-gnu platform
[.] Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
[.] Reading configuration from file /etc/stunnel/stunnel.conf
[.] UTF-8 byte order mark not detected
[.] FIPS mode disabled
[ ] No PRNG seeding was required
[ ] Initializing service [dummy]
[ ] stunnel default security level set: 2
[ ] Ciphers: HIGH:!aNULL:!SSLv2:!DH:!kDHEPSK
[ ] TLSv1.3 …
```

stunnel: update version to 5.66

---

net/curl/patches/300-curl-wolfssl.m4-error-out-if-wolfSSL-is-not-usable.patch

Maintainer: me
Description:
When we explicitly declare, that we would like to have curl built with wolfSSL support using `--with-wolfssl` configure option, then we should make sure, that we either endup with curl having that support, or it shouldn't be available at all, otherwise we risk, that we end up with regressions like following:
configure:25299: checking for wolfSSL_Init in -lwolfssl
configure:25321: x86_64-openwrt-linux-musl-gcc -o conftest [snip]
In file included from target-x86_64_musl/usr/include/wolfssl/wolfcrypt/dsa.h:33,
from target-x86_64_musl/usr/include/wolfssl/wolfcrypt/asn_public.h:35,
from target-x86_64_musl/usr/include/wolfssl/ssl.h:35,
from conftest.c:47:
target-x86_64_musl/usr/include/wolfssl/wolfcrypt/integer.h:37:14: fatal error: wolfssl/wolfcrypt/sp_int.h: No …

[21.02] curl: error out if wolfSSL is not usable

---

lang/python/django-restframework/Makefile

Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/3848cf458ef998fc9971edd6a01cc9cdb43fbef9
Run tested: same version

django-restframework: bump to version 3.14.0

---

net/tailscale/Makefile
net/tailscale/test.sh

Description: --version reporting doesn't work well if it's not specified in go ldflags. Is it possible to test two binaries from two packages like this?

tailscale: fix --version

---

net/samba4/Makefile

Adding perlbase-json-pp to samba4-libs dependencies was the wrong approach and caused samba packages not to be offered by menuconfig. AFAIK perlbase-json-pp is a perl helper to building samba4 and seems to be already included in perl/host so use that instead to fix the menuconfig issues.
Signed-off-by: Andrew Sim <andrewsimz@gmail.com>

samba4: change perl dependency to fix menuconfig

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.1, test dns resolution
Description:
* upstream bugfix: Add a forgotten 'NULL' initialize for ca_info if not manually set
* make init script PKG_VERSION variable readonly so that a shellcheck excettion can be removed
* add procd interface trigger to 'wan6' if IPv6 wan interface name cannot be obtained on start

https-dns-proxy: upstream bugfix for ca_info

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.1, test dns resolution
Description:
* upstream bugfix: Add a forgotten 'NULL' initialize for ca_info if not manually set
* make init script PKG_VERSION variable readonly so that a shellcheck excettion can be removed
* add procd interface trigger to 'wan6' if IPv6 wan interface name cannot be obtained on start
(cherry picked from commit bca5d0ed8e4791b0c31b624c6fbc3e43e9c0a2a8)

[22.03] https-dns-proxy: upstream bugfix for ca_info

---

net/keepalived/Makefile
net/keepalived/files/etc/hotplug.d/keepalived/501-rpcd
net/keepalived/files/etc/hotplug.d/keepalived/505-system
net/keepalived/files/etc/hotplug.d/keepalived/509-ucitrack
net/keepalived/files/etc/hotplug.d/keepalived/511-firewall
net/keepalived/files/etc/hotplug.d/keepalived/551-dnsmasq
net/keepalived/files/etc/hotplug.d/keepalived/555-dropbear
net/keepalived/files/etc/hotplug.d/keepalived/600-uhttpd
net/keepalived/files/etc/hotplug.d/keepalived/700-luci
net/keepalived/files/etc/hotplug.d/keepalived/810-files
net/keepalived/files/etc/init.d/keepalived-inotify
net/keepalived/files/keepalived.init
net/keepalived/files/lib/functions/keepalived/common.sh
net/keepalived/files/lib/functions/keepalived/hotplug.sh
net/keepalived/files/usr/bin/keepalived-rsync-inotify
net/keepalived/files/usr/libexec/keepalived/rpc/sync.sh
net/keepalived/files/usr/libexec/rpcd/keepalived
net/keepalived/files/usr/share/keepalived/scripts/rsync.sh

keepalived: high-availability files and data sync
add new package keepalived-sync to synchronize files and data between master and backup node. The master node uses SSH over rsync to send and the backup node will use inotifywatch to watch received files.
The master node can track rsync.sh script to send configuration file on a backup node based on the vrrp_script configuration of the same script.
The backup node will have a keepalived-inotify service, which would watch for newly received files and it would call hotplug event. Each service can keep its respective script under the keepalived hotplug directory and executes commands to stop, start service or update any config in real-time.
Whenever a switchover will happen, the backup node would have the latest config and data files from the …

keepalived: high-availability files and data sync

---

net/nebula/Makefile
net/nebula/files/nebula.init
net/nebula/files/nebula.proto
net/nebula/test.sh

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.1, bring interface up, test connectivity between nodes
Description:
This commit contains the following:
* Update binary to version 1.6.1
* Update README URLs in the Makefile to link OpenWrt-specific info
* Separate the binary, the init script and netifd script into 3 packages: nebula, nebula-service and nebula-proto accordingly
* implement yml parser for init script to fetch variables from it
* add the netifd script for nebula protocol
* update test file to address all built packages

nebula: implement netifd support

---

net/ddns-scripts/Makefile

Maintainer: I can't find anyone in the Makefile and looking at history doesn't help
Run tested: -
Description:
* ddns-scripts-services: provide ddns-scripts_service
* ddns-scripts-cloudflare: provide ddns-scripts_digitalocean.com-v2
* ddns-scripts-freedns: provide ddns-scripts_freedns_42_pl
* ddns-scripts-godaddy: provide ddns-scripts_godaddy.com-v1
* ddns-scripts-noip: provide ddns-scripts_no-ip_com
* ddns-scripts-nsupdate: provide ddns-scripts_nsupdate
* ddns-scripts-route53: provide ddns-scripts_route53-v1
* ddns-scripts-cnkuai: provide ddns-scripts_cnkuai_cn
https://github.com/openwrt/packages/pull/13509 by @feckert renamed many ddns-scripts packages, but didn't include a PROVIDES for the old package names to make updates work well. …

ddns-scripts: add PROVIDES for old package names

---

net/ddns-scripts/Makefile

Run tested: no
Description: Fixes mistake in dbe79e409d4d772d607364b47116a108508bb466 (#19597), the cloudflare PROVIDES got mixed up with digitalocean.
I am sorry about this mistake
cc @BKPepe @feckert

ddns-scripts: fix cloudflare&digitalocean provides

---

net/cloudflared/files/cloudflared.init
net/dnsproxy/files/dnsproxy.init
net/v2ray-core/files/v2ray.init
net/v2raya/files/v2raya.init
net/xray-core/files/xray.init

Maintainer: me
Run tested: NanoPi R2S
Description:
Exit directly will result procd service inactive and uci configuration changes are no longer monitored.

treewide: fix procd service inactive

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.init
net/adblock/files/adblock.sh
net/adblock/files/adblock.sources

Run tested: Turris Omnia, OpenWrt SNAPSHOT r20964-b58f3c573d
Description:
* made the reporting/top statistics flexible, see "top_count" parm in CLI or in LuCI (default 10), fixes #19622
* added the new blocklist source cpbl (provided by PascalCoffeeLake@gmail.com)
* added/separated Easylist/Easyprivacy blocklist sources (provided by PascalCoffeeLake@gmail.com)
* added reg_jp blocklist_source (provided by PascalCoffeeLake@gmail.com)
* removed the easylist addons from the other regional lists
* removed the second/obsolete pl regional list and renamed the first one to "reg_pl"
* updated the readme

adblock: update 4.1.5

---

net/lighttpd/Makefile

Description:
lighttpd: document crypto lib options in Makefile
Follow-up from https://github.com/openwrt/packages/issues/18851
I suspect there will be some discussion about how to do this, and perhaps to create an option in the config, so I will mark this as a draft.
---
Please note that due to a merge (https://github.com/openwrt/packages/commit/845d81ca0976c82829addc23e9e8b95885c910ee)  which occurred after https://github.com/openwrt/packages/pull/19498 was submitted but before the PR was merged, PKG_RELEASE was not bumped twice, as it should have been.  I do not think it a big deal since the end result is that the package was rebuilt.  However, the change made in the PR might not get to people until the next package …

lighttpd: document crypto lib options in Makefile

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.1, boot/start/stop
Description:
* make PKG_VERSION of the init script readonly to remove shellcheck exception SC1091
* replace exit with return in the the procd scripts per: https://github.com/openwrt/packages/pull/19617
* remove custom boot() function as it prevented creation of procd firewall object on start on boot
* improve performance of allowing domains code
@jow- if you can have a look at the (now-removed) boot() function and advise what's in it causing the firewall procd object not to be created on start on boot, please let me know.

simple-adblock: update to 1.9.2-1

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.1, boot/start/stop
Description:
* make PKG_VERSION of the init script readonly to remove shellcheck exception SC1091
* replace exit with return in the the procd scripts per: https://github.com/openwrt/packages/pull/19617
* remove custom boot() function as it prevented creation of procd firewall object on start on boot
* improve performance of allowing domains code
(cherry picked from commit 3ba54553ca7bd93b9d0db7d28693fa05c7c7aa87)

[22.03] simple-adblock: update to 1.9.2-1

---

net/nebula/Makefile
net/nebula/files/nebula.init
net/nebula/files/nebula.proto
net/nebula/test.sh

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.1, bring interface up, test connectivity between nodes
Description:
This commit contains the following:
* Update binary to version 1.6.1
* Update README URLs in the Makefile to link OpenWrt-specific info
* Separate the binary, the init script and netifd script into 3 packages: nebula, nebula-service and nebula-proto accordingly
* implement yml parser for init script to fetch variables from it
* add the netifd script for nebula protocol
* update test file to address all built packages
* make the PKG_VERSION variable of init/proto scripts readonly
(cherry picked from commit 51902f92066da5b127f2ee8c07b48903c664906d)

[22.03] nebula: implement netifd support

---

net/dnsproxy/Makefile

Maintainer: me
Description:
Release note:
https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.45.4

dnsproxy: Update to 0.45.4

---

admin/btop/Makefile
admin/btop/test.sh

Maintainer: me
Compile tested: ramips/mt7621, rockchip/armv8, x86/64
Run tested: NanoPi R2S
Description:
Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
https://github.com/aristocratos/btop

btop: add new package

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.config
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested:  x86_64, Sophos SG-135, OpenWrt 22.03.2, start, observe no unnecessary dnsmasq restarts
Description:
* fixes https://github.com/openwrt/packages/issues/19631
Thanks @dibdot!

https-dns-proxy: bugfix: remove wan6 from procd triggers

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start, stop, observe DHCP config
Description:
* bugfix: canary domains persistence (as described in https://forum.openwrt.org/t/https-dns-proxy-canary-domain-persistance/139967)
* minor: remove global variables and make them local in service_start/service_stop/service_triggers
* minor: split DEFAULT_BOOTSTRAP into BOOTSTRAP_CF and BOOTSTRAP_GOOGLE for better code readability

https-dns-proxy: bugfix: remove canary domains

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start, stop, observe DHCP config
Description:
* bugfix: canary domains persistence (as described in https://forum.openwrt.org/t/https-dns-proxy-canary-domain-persistance/139967)
* minor: remove global variables and make them local in service_start/service_stop/service_triggers
* minor: split DEFAULT_BOOTSTRAP into BOOTSTRAP_CF and BOOTSTRAP_GOOGLE for better code readability
(cherry picked from commit 92a45c3985cab20907205c9187a9c9394d07b4db)

[22.03] https-dns-proxy: bugfix: remove canary domains

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start service, check ubus entries
Description:
* remove unnecessary procd_add_reload_interface_trigger

simple-adblock: remove unnecessary procd_add_reload_interface_trigger

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start service, check ubus entries
Description:
* remove unnecessary procd_add_reload_interface_trigger
(cherry picked from commit ef067f6304b36ed036b07f241819521d3ba10991)

[22.03] simple-adblock: remove unnecessary procd_add_reload_interface_trigger

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start service, check ubus entries
Description:
* When $wan/$wan6 are empty but double-quoted, it leads to creation of an interface trigger with empty interface

https-dns-proxy: bugfix: prevent creation of empty interface trigger

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start service, check ubus entries
Description:
* When $wan/$wan6 are empty but double-quoted, it leads to creation of an interface trigger with empty interface
(cherry picked from commit 425cef2f8c0fd9f90d5f39c9777c877be09c2547)

[22.03] https-dns-proxy: bugfix: prevent creation of empty interface trigger

---

net/dnsproxy/Makefile

Maintainer: me
Description:
- #19625

[openwrt-22.03] dnsproxy: Update to 0.45.4

---

sound/squeezelite/Makefile

Signed-off-by: Robert Högberg <robert.hogberg@gmail.com>
Compile tested: ath79, D-Link DIR-825 B1, OpenWrt 21.02
Run tested: ath79, D-Link DIR-825 B1, OpenWrt 21.02 - playing an https radio URL works

squeezelite: add SSL support

---

net/boinc/Makefile
net/boinc/files/boinc-client.init

Maintainer:  @N30dG
The boinc app is running as root, yet downloads pre-compiled binaries from external sources. It is safer to run in a jail.
Signed-off-by: Marc Benoit <marcb62185@gmail.com>

boinc: run the executable in ujail

---

net/isc-dhcp/files/dhcpd.init

Maintainer: me
Compile tested: x86_64, generic, HEAD (60738feded)
Description:
For the default route (0/0), the prefix is 0, therefore 0 destination octets are specified, and the destination descriptor is just the width (0), with no subsequent octets of subnet portion.

isc-dhcp: support sending explicit default route

---

net/iputils/Makefile

Description: iputils-ping6 was a subpackage of the iputils package providing the ping4 and ping6 command before iputils was moved from core to packages. Currently ping4 and ping6 are replaced by ping -4/-6 and compatibility symlinks are only installed when explicitly told so with an option, but the functionality is always provided by iputils-ping.

iputils: provide iputils-ping6 in iputils-ping

---

net/xfrpc/files/xfrpc.init

Compile tested: x86_64, OpenWrt 21.02.2 r16495-bf0c965af0
Run tested: x86_64, OpenWrt 21.02.2 r16495-bf0c965af0
Description:
1. allow server_addr as ip or domain
2. add subdomain support 

xfrpc: allow server_addr as ip or domain

---

net/adguardhome/files/adguardhome.init

Signed-off-by: James White <james@jmwhite.co.uk>
Maintainer: @dobo90 @alaviss 
Description:
There have been various reports of AdGuardHome not starting on boot. It is due to certain network race conditions being present
Here's an example: https://github.com/openwrt/packages/issues/18585
Bumping the start value slightly may resolve the most common like network binds not being able. It will however probably not solve all issues, but we want to keep the START value fairly reasonable given DNS should be available relatively early in the boot process.

adguardhome: Increase init start value to avoid network race conditions

---

utils/mariadb/Makefile
utils/mariadb/patches/100-fix_hostname.patch
utils/mariadb/patches/180-relax-mysql_install-db-wrt-pam-tool.patch
utils/mariadb/patches/190-replace-hostname-in-mysqld_safe.patch
utils/mariadb/patches/200-no-selinux.patch

Maintainer: me
Compile tested: mvebu, Turris Omnia, OpenWrt 21.02
Run tested: mvebu, Turris Omnia, OpenWrt 21.02, runs, client is able to connect
Description:
Keeping the major version, bumping just a minor version. It includes various bug fixes and security fixes. For details, see:
https://mariadb.com/kb/en/mariadb-10426-release-notes/
https://mariadb.com/kb/en/mariadb-10425-release-notes/
https://mariadb.com/kb/en/mariadb-10424-release-notes/
https://mariadb.com/kb/en/mariadb-10423-release-notes/
While at it, also switching to AUTORELEASE and refreshing patches.

[21.02] mariadb: Update to the latest version 10.4.26

---

lang/node/Makefile
lang/node/patches/003-path.patch
lang/node/patches/999-delete_unnecessary_libraries_for_host_execute.patch
lang/node/patches/999-localhost-no-addrconfig.patch
lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch
lang/node/patches/999-v8_zlib_support.patch

 Compile tested: head, aarch64, arm, i386, x86_64, mipsel (pistachio) 
Run tested: (qemu 7.1.0) aarch64
Description:
Update to v16.18.0

node: bump to v16.18.0

---

net/softflowd/Makefile
net/softflowd/patches/030-Use-lld-for-time_t-always.patch

Add upstreamed patch to fix segmentation fault reported in [1].
[1] https://github.com/openwrt/packages/issues/19655
Maintainer: @rvandegrift 
Compile tested: 22.03 ath79 SDK
Run tested: ath79 22.03, also tested by @HolgerHees (see issue #19655)
Description:
Fix time64 issue resulting in segfault. Patch applied upstream.

softflowd: use %lld for time_t always

---

net/samba4/Makefile
net/samba4/patches/021-source4-msgsock-nvram-fix.patch

* update to 4.17.1
* changelog: https://www.samba.org/samba/history/samba-4.17.1
* refresh patch
Signed-off-by: Andrew Sim <andrewsimz@gmail.com>
Maintainer: no one
Compile tested: mediatek: mt7622
Run tested: mediatek: mt7622

samba4: update to 4.17.1

---

utils/docker-compose/Makefile

docker-compose: Update to version 2.12.2

---

net/softflowd/Makefile
net/softflowd/patches/030-Use-lld-for-time_t-always.patch

Add upstreamed patch to fix segmentation fault reported in [1].
[1] https://github.com/openwrt/packages/issues/19655
(cherry picked from commit 7d019635b1490248e0efc487b3723a4cd07b39d7)
Maintainer: @rvandegrift
Compile tested: 22.03 ath79 SDK
Run tested: ath79 22.03, also tested by @HolgerHees (see issue #19655)
Description:
Fix time64 issue resulting in segfault. Patch applied upstream.

[22.03] softflowd: use %lld for time_t always

---

net/acme-acmesh/files/hook.sh
net/acme-common/Makefile
net/acme-common/files/acme-notify.sh
net/acme-common/files/acme.config
net/acme-common/files/acme.sh
net/haproxy/files/acme.hotplug
net/haproxy/files/haproxy.init
net/nginx/Makefile
net/nginx/files/acme.hotplug
net/nginx/files/nginx.init

- Move notifying logic out of acme hooks
- Prevent concurrent running of `acme get`
- Use procd instead of hotplug to reload services (leaving hotplug for user scripts only)
- Fix a bug where switching from staging to production didn't trigger the renew event
Signed-off-by: Glen Huang <i@glenhuang.com>
Description:
Using hotplug to reload a service can inadvertently restarting it if it was stopped, as pointed out by @ptpt52.
This PR make services use procd instead, which is how it should be properly done IMO. It also moves the actual notifying logic out of hooks, since they really shouldn't be concerned about how to actually do that.
@tohojo, if you think the design is good I will change other related services too.

acme: refactor

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested:  x86_64, Sophos SG-135, OpenWrt 22.03.2, test empty dnsmasq servers, check ubus entries
Description:
* bugfix: properly restore empty server config for dnsmasq (to address issue brought up in https://github.com/stangri/source.openwrt.melmac.net/pull/162)
* better handling of non-existant wan/wan6 interface for triggers
* add resolver url to ubus data for future-proofing WebUI js move

https-dns-proxy: bugfix: restore empty server; misc improvements

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested:  x86_64, Sophos SG-135, OpenWrt 22.03.2, test empty dnsmasq servers, check ubus entries
Description:
* bugfix: properly restore empty server config for dnsmasq (to address issue brought up in https://github.com/stangri/source.openwrt.melmac.net/pull/162)
* better handling of non-existant wan/wan6 interface for triggers
* add resolver url to ubus data for future-proofing WebUI js move
(cherry picked from commit fbc63cb9f6ac808803038cfb2775c90085fdc989)

[22.03] https-dns-proxy: bugfix: restore empty server; misc improvements

---

utils/mariadb/files/mysqld.init

Maintainer: me
Compile tested: mvebu, Turris Omnia, OpenWrt 21.02
Run tested: mvebu, Turris Omnia, OpenWrt 21.02, runs, client is able to connect
Description:
We had been creating "rundir" but it was never used, probably leftover from some removed function. At the same time, we were setting quite strict rights to the socket directory (while comments sugested otherwise).
Fix for #19641

mariadb: Drop unused rundir fix socket dir perms

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, verify ubus triggers

simple-adblock: service_triggers improvements

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, verify ubus triggers
(cherry picked from commit 188d3328407259cff81ed08c8d7a906239d9677c)

[22.03] simple-adblock: service_triggers improvements

---

net/lighttpd/patches/010-fix-dummy-Sec-WebSocket-Key-in-proxy_and_cgi.patch

Maintainer: @gstrauss 
Compile tested: all Turris routers
Description:
It was requested in https://gitlab.nic.cz/turris/os/packages/-/issues/873
- Backports: https://github.com/lighttpd/lighttpd1.4/commit/cda9b71653bb6a633957f653fa08e819b32e601e

lighttpd: backport patch to fix dummy Sec-WebSocket-Key

---

libs/libwebsockets/Makefile

Compile tested: Turris 1.1, OpenWrt 21.02.5, mpc85xx/p2020
Run tested: 
- **conflicts OpenSSL and full variant:**
Before:
```
root@turris:~# opkg list-installed | grep libwebsockets
libwebsockets-openssl - 3.1.0-2
root@turris:~# opkg install libwebsockets-full
Installing libwebsockets-full (3.1.0-2) to root...
Downloading https://repo.turris.cz/hbk/omnia/packages/packages/libwebsockets-full_3.1.0-2_arm_cortex-a9_vfpv3-d16.ipk
Collected errors:
* check_data_file_clashes: Package libwebsockets-full wants to install file /usr/lib/libwebsockets.so
But that file is already provided by package  * libwebsockets-openssl
* check_data_file_clashes: Package libwebsockets-full wants to install file /usr/lib/libwebsockets.so.14
But that file is already provided by package  * …
```

libwebsockets: full variant provides OpenSSL

---

.github/workflows/formal.yml
.github/workflows/multi-arch-test-build.yml

Update checkout and upload-artifact action to v3 to mute nodejs deprecation warning.

ci: update github actions to v3

---

sound/squeezelite/Makefile

Signed-off-by: Robert Högberg <robert.hogberg@gmail.com>
Compile tested: ath79, D-Link DIR-825 B1, OpenWrt 21.02
Run tested: ath79, D-Link DIR-825 B1, OpenWrt 21.02 - I've verified that playing opus and mp3 files works

squeezelite: add opus codec support

---

utils/bandwidthd/Makefile
utils/bandwidthd/patches/040-64bit-time-t.patch

Fixes issue #19510 with the change in time_t with musl 1.2
Signed-off-by: Jean-Michel Lacroix <lacroix@lepine-lacroix.info>
Maintainer: me
Compile tested: mips_24kc for a Archer C7 v2
Run tested: Run tested: Qualcomm Atheros QCA9558 ver 1 rev 0, TP-Link Archer C7 v2, OpenWRT SNAPSHOT r21042-d4571e98ab
Description:
Fixes issue https://github.com/openwrt/packages/issues/19510 with the change in time_t with musl 1.2 on a 32 bits system.
Tested and found to creating the graphs correctly.

bandwidthd: fix time_t problem

---

libs/libwebsockets/Makefile

Compile tested: no, only verified by ``make menuconfig``
Run tested: no, only verified by ``make menuconfig``
While running `make menuconfig`, it was discovered then there is a recursive dependency like this:
```
tmp/.config-package.in:59138:error: recursive dependency detected! tmp/.config-package.in:59138:	symbol PACKAGE_libwebsockets-openssl is selected by PACKAGE_libwebsockets-mbedtls tmp/.config-package.in:59122:	symbol PACKAGE_libwebsockets-mbedtls depends on PACKAGE_libwebsockets-openssl
```
It is not possible with the recently added conflicts that two packages (OpenSSL and full variant, which uses OpenSSL as well), which are almost the same provides the same named package libwebsockets as their conflict - Mbed TLS.
Fixes: …

libwebsockets: fix recursive dependency

---

net/dnsproxy/Makefile

Maintainer: me
Description:
Release note:
https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.46.0
https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.46.1
https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.46.2

dnsproxy: Update to 0.46.2

---

net/atlas-probe/Makefile
net/atlas-probe/patches/003-Fix-SIGSEGV-caused-by-time_t-casted-to-long-on-32bit.patch
net/atlas-probe/patches/005-Mute-some-no-previous-prototype-compilation-warning.patch
net/atlas-probe/patches/006-Cast-sockaddr_in6-to-sockaddr-to-mute-compilation-wa.patch
net/atlas-probe/patches/007-Cast-size_t-to-long-to-mute-warning-on-32bit-systems.patch

Changes to time_t cause SIGSEGV error on 32bit system and cause ripe atlas malfunction. (registration successful but no traffic) Also introduce minor patch to fix some compilation warning.
While at it move PKG_RELEASE to AUTORELEASE macro.
---
These patch are pushed upstream and under review (https://github.com/RIPE-NCC/ripe-atlas-software-probe/issues/74 and .https://github.com/RIPE-NCC/ripe-atlas-probe-measurements/pull/11) These were tested on a mt7621 WAX202

atlas-probe: fix SIGSEGV error on 32bit system

---

utils/bandwidthd/Makefile
utils/bandwidthd/patches/040-64bit-time-t.patch

Maintainer: me
Compile tested: mips_24kc on 22.03
Run tested: Qualcomm Atheros QCA9558 ver 1 rev 0, TP-Link Archer C7 v2, OpenWRT 22.03.0 r19685-512e76967f
Description:
Fixes issue #19510 with the change in time_t with musl 1.2
Signed-off-by: Jean-Michel Lacroix <lacroix@lepine-lacroix.info>
(cherry picked from commit 61d1a86)

[22.03] bandwidthd: fix time_t problem

---

libs/gdbm/Makefile

**Maintainer**: @Naoir (but they haven't been active on GitHub 2016)
**Compile tested**: `openwrt-sdk-22.03.2-mvebu-cortexa9`
**Run tested**: **none**, I'm not familiar with `gdbm`, so I don't know how to test it.
It seems low risk though, since `gdbm` will automatically be built without readline support, depending on which order packages are built.
**Description**:
By default, `gdbm` configures/builds with `readline` and curses support if they exist.
This can cause race conditions when compiling `gdbm` and `ncurses` in parallel, as `gdbm` may try to link to `ncurses` when it doesn't exist.
Additionally, it also means that the built `.ipk` might have a hidden dependency on the `readline` and `ncurses` shared libraries.
This commit forces `gdbm` to skip using `readline`/`ncurses`, since …

gdbm: configure with `--without-readline`

---

multimedia/ffmpeg/Makefile

Maintainer: @thess @antonlacon 
Compile tested: Turris Omnia, OpenWrt 21.02.5, mvebu/cortex-a9
Run tested: Turris Omnia, OpenWrt 21.02.5, mvebu/cortex-a9
Description:
Motivation of this change is that full variants provides the mini variant and as well audio-dec package, thus you can not install both as it fails with the following output:
```
Collected errors:
* check_data_file_clashes: Package libffmpeg-audio-dec wants to install file /usr/lib/libavcodec.so.58 But that file is already provided by package  * libffmpeg-full
* check_data_file_clashes: Package libffmpeg-audio-dec wants to install file /usr/lib/libavcodec.so.58.91.100 But that file is already provided by package  * libffmpeg-full
* check_data_file_clashes: Package libffmpeg-audio-dec wants to install file …
```

ffmpeg: add conflicts and provides

---

utils/attendedsysupgrade-common/Makefile
utils/attendedsysupgrade-common/files/86241a707a30cb7f
utils/attendedsysupgrade-common/files/8a11255d14aef6c8

The old key was overwritten during a machine migration and the current worker key is no longer valid. To create new valid worker certificates this commit adds a new CA pubkey.
To update running OpenWrt devices via a client one needs to force install it or upgrade to the latest version of
`attendedsysupgrade-common` - I'm sorry for the inconvenience.

attendedsysupgrade-common: update ASU CA pubkey

---

net/dnsproxy/Makefile

Maintainer: me
Description:
- Cherry-picked from: #19713

[openwrt-22.03] dnsproxy: Update to 0.46.2

---

net/curl/Makefile

Maintainer: me
Description:
this patch AFAIK fixes compilation when CONFIG_BUILD_NLS is enabled.
_Originally posted by @neheb in https://github.com/openwrt/packages/issues/19563#issuecomment-1296334225_

curl: include nls.mk

---

net/apcupsd/Makefile
net/apcupsd/patches/010-fix-usb.patch

Seems to be from a time when pkgconfig returned the wrong path.
Maintainer: @tru7 

apcupsd: remove header file patch

---

utils/yq/Makefile

Maintainer: me
Description:
Release note:
https://github.com/mikefarah/yq/releases/tag/v4.28.2
https://github.com/mikefarah/yq/releases/tag/v4.29.1
https://github.com/mikefarah/yq/releases/tag/v4.29.2

yq: Update to 4.29.2

---

net/kadnode/Makefile
net/kadnode/files/kadnode.init

Compile+Run tested: Nexx WT3020, ramips/mt7620, OpenWrt master
Tested: without cahnge: kadnode does not start, with change: kadnode starts

kadnode: fix newlines in config file

---

net/curl/Makefile

Maintainer: me
Description:
this patch AFAIK fixes compilation when CONFIG_BUILD_NLS is enabled.
_Originally posted by @neheb in https://github.com/openwrt/packages/issues/19563#issuecomment-1296334225_
(cherry picked from commit d66435208cabfe84b3f24ee47781cb90f94bbadc)

[22.03] curl: include nls.mk

---

libs/libedit/Makefile

Description:
- update of the library on which `knot` depends on

libedit: update to version 20221030-3.1

---

sound/pulseaudio/Makefile

Compile tested: Raspberry PI 4 CM, aarch64_cortex-a72_musl, OpenWrt snapshot
Description:
- Many changes, see the commit descriptions

Improvements for Pulseaudio package (conflicts, autorelease, simplifying)

---

net/curl/Makefile

Maintainer: me
Compile tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, tested compile as a standalone package only
Description:
* discovered and fixed by @ptpt52 [here](https://github.com/openwrt/packages/commit/88009b2d5e394c1822ec55734b63b434981a2a9d#commitcomment-88604318)

curl: bugfix: building as selected package doesn't break build

---

lang/php8/Makefile
lang/php8/patches/0025-php-5.4.9-fixheader.patch
lang/php8/patches/1004-disable-phar-command.patch

Maintainer: me
Description:
This fixes:
- CVE-2022-31630
- CVE-2022-37454

php8: update to 8.1.12

---

sound/mpd/Makefile

`pulseaudio` is provided by both `pulseaudio-daemon` and `pulseaudio-daemon-avahi`.
Fixes: #19187
Fixes: 2ed62adc5914 ("mpd: enable pulseaudio in full package")
----
Compile tested: `ath79/generic`: `tplink_tl-wr1043nd-v4` (following **jow-**'s [example](https://forum.openwrt.org/t/luci-rewrite-in-ucode-testers-wanted/137250))
Run tested: `ipq40xx/generic`: `glinet_gl-b1300`

mpd: depend the full variant on pulseaudio instead of pulseaudio-daemon

---

net/openvpn/Makefile
net/openvpn/files/openvpn.init

Maintainer: @AuthorReflex  / @mkrkn
Compile tested: lantiq/xrx200, x86/64
Run tested: lantiq/xrx200, x86/64
Description:
In some situations you need to set the compress param without an algorithm. Compression will be turned off, but the packet framing for compression will still be enabled, allowing a different setting to be pushed later.
As it is not possible to have options with optional values at the moment, I've introduced a pseudo value "frames_only" which will be removed in the init script.
I'm re-sending this PR after openvpn moved from openwrt core to packages feed: https://github.com/openwrt/openwrt/pull/2694
After this got merged, I'll create a PR for luci as well.

openvpn: add possibility to set param "compress" without algorithm

---

sound/pulseaudio/Makefile

Compile tested: verified that conffiles in the packages are correct now
Description:
- Fixes: https://github.com/openwrt/packages/pull/19733#issuecomment-1298842720
Thanks @hnyman for reporting!

pulseadio: fix conffiles for pulseadio-daemon-avahi package

---

net/dnsdist/Makefile

dnsdist: update to 1.7.3

---

net/xray-core/Makefile

Maintainer: me
Description:
Release note: https://github.com/XTLS/Xray-core/releases/tag/v1.6.2

xray-core: Update to 1.6.2

---

net/zerotier/Makefile

Compile tested: ramips/mt7620 (Nexx WT3020)
Description: minor revision update

zerotier: update to 1.10.2

---

utils/yq/Makefile

Maintainer: me
Description:
- Cherry-picked from: #19751

[openwrt-21.02] yq: Update to 4.29.2

---

libs/libnpupnp/Makefile

libnpupnp: update to 5.0.0

---

libs/libarchive/Makefile

libarchive: update to 3.6.1

---

utils/librespeed-cli/Makefile

Maintainer: me
Description: The binary name is speedtest-cli, but speedtest-cli is usually a different package in distributions.

librespeed-cli: add package

---

admin/nload/Makefile
admin/nload/test.sh

Signed-off-by: Jacky Guo <leickwell@hotmail.com>
Maintainer: me
Compile tested: aarch64/mt7622), ramips/mt7628
Run tested: Redmi AX6S, Minew G1-C
Description:
A console application which monitors network
traffic and bandwidth usage in real time.
https://github.com/rolandriegel/nload

nload: add new package

---

utils/sms-tool/Makefile

Signed-off-by: Andrey Butirsky <butirsky@gmail.com>
Maintainer: @obsy
Compile tested: ramips-mt76x8-snapshot
Description:
SMS Tool for 3G/4G modem

sms-tool: SMS Tool for 3G/4G modem

---

utils/dos2unix/Makefile
utils/dos2unix/test.sh

Maintainer: me
Compile tested: all targets
Run tested: nanopi-r2s, x64
Description:
dos2unix - text file format converters
includes:
dos2unix - DOS/Mac to Unix text file format converter (dos2unix/mac2unix)
unix2dos - Unix to DOS/Mac text file format converter (unix2dos/unix2mac)
https://waterlan.home.xs4all.nl/dos2unix.html

dos2unix: add new package

---

utils/lxc/files/lxc-auto.init

Maintainer: @ratkaj @BKPepe 
Fixes this message from image builder:
```
Finalizing root filesystem...
/build/openwrt-imagebuilder/build_dir/target-x86_64_musl/root-x86/etc/init.d/lxc-auto: line 3: /lib/functions.sh: No such file or directory
Enabling boot
Enabling cgroupfs-mount
Enabling collectd
```
Closes https://github.com/openwrt/packages/issues/19292
Signed-off-by: Marc Benoit <marcb62185@gmail.com>

lxc-auto: made init script compatible with image builder

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.config
net/https-dns-proxy/files/https-dns-proxy.defaults
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, verify config
Description:
* rename wan6_trigger to procd_trigger_wan6
* rename update_dnsmasq_config to dnsmasq_config_update
* add the uci-defaults file to run sed on config file
* update Makefile to include uci-defaults file

https-dns-proxy: rename options

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.config
net/https-dns-proxy/files/https-dns-proxy.defaults
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, verify config
Description:
* rename wan6_trigger to procd_trigger_wan6
* rename update_dnsmasq_config to dnsmasq_config_update
* add the uci-defaults file to run sed on config file
* update Makefile to include uci-defaults file
(cherry picked from commit 6bd055284c4f1f633e3d1cd857dc14adbe27c2f5)

[22.03] https-dns-proxy: rename options

---

libs/libseccomp/Makefile

libseccomp: update to 2.5.4

---

libs/libcap-ng/Makefile

libcap-ng: update to 0.8.3

---

libs/log4cplus/Makefile

log4cplus: update to 2.0.8

---

libs/libshout/Makefile

libshout: update to 2.4.6

---

sound/mpd/Makefile

Description:
- cherry-picked #19728

[21.02] mpd: depend the full variant on pulseaudio instead of pulseaudio-daemon

---

sound/mpd/Makefile

Description:
- cherry-picked #19728

[22.03] mpd: depend the full variant on pulseaudio instead of pulseaudio-daemon

---

libs/libgpg-error/Makefile

Upstream deprecated it while not fixing libgcrypt not to use it.
ping @hnyman

libgpg-error: install gpg-error-config again

---

lang/php8/Makefile
lang/php8/patches/0025-php-5.4.9-fixheader.patch
lang/php8/patches/1004-disable-phar-command.patch

Maintainer: me
Description:
This fixes:
- CVE-2022-31630
- CVE-2022-37454
(cherry picked from commit 58b47869c018389218821c4f0947710b693847f4)

[22.03] php8: update to 8.1.12

---

net/xray-core/Makefile

Maintainer: me
Description:
- Cherry-picked from: #19784

[openwrt-22.03] xray-core: Update to 1.6.2

---

net/samba4/Makefile

update samba to 4.17.2
* CVE-2022-3437: There is a limited write heap buffer overflow in the GSSAPI unwrap_des() and unwrap_des3() routines of Heimdal (included in Samba). https://www.samba.org/samba/security/CVE-2022-3437.html
* CVE-2022-3592: A malicious client can use a symlink to escape the exported directory.
https://www.samba.org/samba/security/CVE-2022-3592.html
Signed-off-by: Andrew Sim <andrewsimz@gmail.com>
Compile tested: mediatek, mt7622
Run tested:

samba4: update to 4.17.2

---

libs/libarchive/patches/001-libarchive-Do-not-include-sys-mount.h-when-linux-fs.h-is-present.patch

Compile tested: mips_24kc_glibc
This backports a build fix for libarchive when compiling against glibc 2.36.

libarchive: Backport build fix for glibc 2.36

---

libs/libowfat/Makefile
libs/libowfat/patches/012-remove-deprecated.patch

Maintainer: @danwrt 
Compile tested: mips_24kc_glibc
This fixes the following error message seen when compiling against glibc 2.36:
from scan/scan_httpdate.c:3:
include/sys/cdefs.h:338:65: error: macro "__has_attribute" requires an identifier
338 | #if __GNUC_PREREQ (3,2) || __glibc_has_attribute (__deprecated__)

libowfat: Fix compile with glibc 2.36

---

admin/sudo/Makefile

Maintainer: me
Compile tested: x86, mips64, aarch64 https://github.com/openwrt/openwrt/commit/41691ce9ac10b3aaaf7c05e6e5b55b626f66949b
Run tested: x86  https://github.com/openwrt/openwrt/commit/41691ce9ac10b3aaaf7c05e6e5b55b626f66949b
Fixes: https://github.com/openwrt/packages/issues/19816

sudo: bump to verison 1.9.12p1

---

net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, test init script with: start, stop, dl
Description:
* update default config file to list options alphabetically
* rearrange some of the init script code to support transition of WebUI to javascript
* rename wan6_trigger to procd_trigger_wan6 for readability
(cherry picked from commit 7393b744574a72430f491183853729d941c634ea)

[22.03] simple-adblock: update to 1.9.2-4

---

libs/libssh/Makefile

libssh: update to 0.10.4

---

net/strongswan/Makefile
net/strongswan/patches/0904-gmpdh-Plugin-that-implements-gmp-DH-functions-in-an-.patch

Compile tested: x86_64, generic, HEAD (#c3b9f00aaa)
Description:
Update to 5.9.8 and drop scepclient.

strongswan: Update to 5.9.8

---

lang/python/python-crcmod/Makefile
lang/python/python-pycrate/Makefile
net/qcsuper/Makefile

Maintainer: me
Compile tested: x86-64 / ipq40xx-generic
Run tested: apu4d4 / GL.iNet GL-AP1300
Description:
QCSuper is a diagnostic tool which allows to capture cellular frames using a Qualcomm USB modems debug port.

qcsuper: add package with dependencies

---

libs/taglib/Makefile

taglib: update to 1.13

---

libs/libsoup3/Makefile

libsoup3: update to 3.2.1

---

net/gg/Makefile

Maintainer: me
Description:
Release note:
https://github.com/mzz2017/gg/releases/tag/v0.2.14

gg: Update to 0.2.14

---

net/v2ray-geodata/Makefile
net/xray-core/Makefile

Maintainer: me
Description:
Release note: https://github.com/XTLS/Xray-core/releases/tag/v1.6.3
- - -
BTW, is commit access still available for applying?
https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#gaining-commit-access

xray-core: Update to 1.6.3

---

net/isc-dhcp/files/dhcpd.init

Maintainer: me
Compile tested: x86_64, generic, HEAD (c3b9f00aaa)
Description:
Compare config files after regenerating the new version.

isc-dhcp: Fix logic to detect if the config file is unchanged

---

net/openvpn/Makefile

Maintainer: @mkrkn
Compile tested: ramips/mt7620, ramips/mt621, bcm47xx/legacy
Run tested: TP-Link Archer C50, Xiaomi Mi Router 3 pro, Asus WL-500gpv2
Mostly bugfix release
For details refer to https://github.com/OpenVPN/openvpn/blob/v2.5.8/Changes.rst

openvpn: update to 2.5.8

---

utils/hwinfo/patches/060-glibc-2-36-includes-fsconfig-itself-make-linux-fs-h.patch

Maintainer: @bobafetthotmail 
Compile tested: mips_24kc_glibc
This backports a build fix for hwinfo when compiling against glibc 2.36.

hwinfo: Backport build fix for glibc 2.36

---

net/modemmanager/files/modemmanager.proto

modemmanager: fix unquoted strings when launching pppd

---

net/privoxy/Makefile

Maintainer:
Description:
This adds the missing protocol (e.g. /tcp and /udp) to the entry in /etc/services. If the entry already exists, it will add the /tcp to it. Otherwise, it will look and add the tcp and udp entries if either is missing.
fixes: #19665
Signed-off-by: Josh Powers <powersj@fastmail.com>

privoxy: correctly format /etc/services additions

---

utils/qemu/Makefile

The total uncompressed size increase (qemu-system-x86_64 and the new libusb dependency) is less than 1%.
Compile tested: built with the current SDK docker image on x86_64 for x86_64
Run tested: `qemu-system-x86_64 -device help` now returns `usb_host` and I can correctly pass a physical device to the VM.

qemu: enable usb passthrough by default

---

utils/yq/Makefile

Maintainer: me
Description:
Release note:
https://github.com/mikefarah/yq/releases/tag/v4.30.1

yq: Update to 4.30.1

---

admin/btop/Makefile
admin/btop/files/btop.sh

Maintainer: me
Description:
btop reads the `LANG` env variable to delect if the system has utf8
support, which exists on common Linux distributions.
However, OpenWrt does not ship it, and results in btop reporting
"No UTF-8 locale detected!". Users have to manually pass `--utf-force`
to make btop happy.
To make it OOTB, append `--utf-force` argument by default via alias.
While at it, update btop to 1.2.13.
Closes: #19729

btop: append --utf-force argument by default

---

net/siit/Makefile
net/siit/src/siit.c

Maintainer: 
Compile tested: aarch64 kernel 6.1rc1 WIP
Run tested: no
Description:
```
siit-1.2/siit.c:1379:9: error: implicit declaration of function 'random_ether_addr' [-Werror=implicit-function-declaration]
1379 |         random_ether_addr(dev->dev_addr);
|         ^~~~~~~~~~~~~~~~~
```
Linux 3.6 renamed random_ether_addr to eth_random_addr [0] Linux 5.16 removed random_ether_addr [1]
[0]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0a4dd594982a321699000218715e28664ec49169 [1]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ba530fea8ca1b57ee71d4e62f287a5d7ed92f789

siit: fix kernel 5.16 compile

---

net/nextdns/Makefile

nextdns: Update to version 1.38.0

---

net/ariang/Makefile

Maintainer: @Ansuel @neheb
Changelog: https://github.com/mayswind/AriaNg/releases/tag/1.3.2

ariang: update to 1.3.2

---

net/frp/Makefile

Run tested: (x86_64, OpenWrt 22.03, tests done)
Description:
changlog: https://github.com/fatedier/frp/releases/tag/v0.45.0

frp: update to 0.45.0

---

net/frp/Makefile

Run tested: (x86_64, OpenWrt 22.03, tests done)
Description:
cherry-pick from: #19910

[22.03] frp: update to 0.45.0

---

lang/php8/Makefile

[21.02] php8: update to 8.0.25

---

net/acme-acmesh/files/hook.sh

Signed-off-by: Glen Huang <i@glenhuang.com>
Description:
This was an omission from my part in the initial PR.
Since uhttpd uses `.crt` as the certification extension name, I think the standard name in acme package should follow that convention, and we should make the change when there aren't many acme packages that have adopted the new architecture.
This change should be backward-compatible, since it only affects new certificates.

acme: make certificates use .crt as the extension

---

utils/jq/Makefile

Compile tested: x86 openwrt 22.03.0
Run tested: x86 openwrt 22.03.0 test done
Description:
change jq source from github to openwrt source, because openwrt hacked/changed jq
[#lede10195](https://github.com/coolsnowwolf/lede/issues/10195) mentioned this problem.

jq: fix hash mismatch problem

---

libs/sqlite3/Config-lib.in
libs/sqlite3/Makefile

Run tested: nanopi-r2s (only checked sqlite3-cli's `.help` command)
Description:
Added a new option for SQLITE3_COLUMN_METADATA.
Minor cleanup Makefile.
Fixes: CVE-2022-35737
Fixes: https://github.com/openwrt/packages/issues/19758

sqlite3: Update to 3.40.0

---

utils/lm-sensors/patches/001-Add_support_for_dev_name_formatted_like_a000000.wifi.patch

Maintainer: @jow- Jo-Philipp Wich <jow@openwrt.org>
Compile tested: ipq4019, a customized router, v21.02.3 and v22.03.0
Run tested: ipq4019, a customized router, v21.02.3 and v22.03.0, see below mentioned issue 
Description:
Detail at #10623 
I found out that openwrt can patch patches on its own, lm-sensors repository seems not very active now, so we can fix it here now until upstream fix it.

lm-sensors: Add support for dev_name formatted like "a000000.wifi"

---

libs/libgpg-error/Makefile

Packages like libassuan and libksba would not compile after updating libgpg-error to 1.46. This was because gpg-error.m4 (and thus the affected packages' configure scripts) relies on gpgrt-config, which in turn needs access to gpg-error.pc. This modifies the libgpg-error build process to copy gpg-error.pc to OpenWrt's staging directory, so that it is available for subsequent dependent package builds.
Fixes: https://github.com/openwrt/packages/issues/19880
Description:

libgpg-error: copy gpg-error.pc to staging directory

---

net/nextdns/Makefile

[21.02] nextdns: Update to version 1.38.0

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.conf
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, download lists
Description:
* introduce the new curl_max_file_size option
* prevent warnings/errors to be displayed each time the load_environment is invoked
* better organize dl_command appendixes
* implement support for downloading/using external dnsmasq config file
* refactor adb_check and adb_allow for better readability
* update default values for some options in the uci_load_validate call
* update reload trigger to include curl options

simple-adblock: update to 1.9.3-1

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.conf
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, download lists
Description:
* introduce the new curl_max_file_size option
* prevent warnings/errors to be displayed each time the load_environment is invoked
* better organize dl_command appendixes
* implement support for downloading/using external dnsmasq config file
* refactor adb_check and adb_allow for better readability
* update default values for some options in the uci_load_validate call
* update reload trigger to include curl options
(cherry picked from commit f11ce28bafc8ae202261d6af7ade35d596385f8c)

[22.03] simple-adblock: update to 1.9.3-1

---

net/ooniprobe/Makefile

Compile tested: CI (immortalwrt/packages#527)
Run tested: CI (immortalwrt/packages#527)
Description:
Fix build with Go 1.19. #19652

ooniprobe: Update to 3.16.5

---

utils/librespeed-cli/Makefile

Maintainer: me
Description: upstream names the binary librespeed-cli and this avoids a conflict with python3-speedtest-cli
cc @1715173329

librespeed-cli: rename binary to librespeed-cli

---

net/wifi-presence/Makefile

This version handles the new hostapd connect message format, as introduced in: https://github.com/openwrt/openwrt/commit/8cb995445a26ee124e40b8ef97cc0ddd9d10f82a
See https://github.com/awilliams/wifi-presence/pull/13 and https://github.com/awilliams/wifi-presence/issues/12 for more details.
cc/ @jmccrohan

wifi-presence: Update to version v0.3.0

---

multimedia/tvheadend/Makefile
multimedia/tvheadend/files/tvheadend.init

Maintainer: me
Compile tested: host x86-64, target mvebu, OpenWrt git master (yesterday)
Run tested: Linksys WRT-1900ACv1, OpenWrt r19971
Tests done:
- install package = OK
- /etc/init.d/tvheadend start = OK
- /etc/init.d/tvheadend stop = OK
- start server manually in console foreground = OK (no unusual errors)
- open web interface = OK
- scan local DVB-C network = OK
- check EPG = loads OK
- stream a TV channel to a desktop PC = OK
- check temporary EPG DB file = OK (EPGDB symlink created, permissions set, not empty)
Did not test:
- initial setup, when no previous configuration exists (but no changes were done here, so it should be OK)
Description:
Latest commit to the tvheadend master branch fixes an issue that affects OpenWrt users:
EPG database file overwrites tvheadend symlink with a …

tvheadend: update to git master 2022-11-20

---

libs/liburing/Makefile

Maintainer: Christian Lachner <gladiac@gmail.com> (**/me**)
Compile tested: mipsel, mips74k, ipq806x, x86, arc700
Description: Update to v2.3
- Updated download URL and hash

liburing: Update to v2.3

---

net/knot/Makefile

Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.0 (hbk)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.0 (hbk)
Description:
- Release upgrade (https://www.knot-dns.cz/2022-11-20-version-323.html)

knot: update to version 3.2.3

---

utils/gnupg/Makefile

This fixes a segfault because gnupg/g10/options.h struct opt is otherwise not shared between the different compilation units, resulting in `opt.homedir` being `NULL` when passed to make_filename. Most subcommands are affected, including `--list-keys`, `-i`, and `--export-ownertrust`.
```console
$ gpg1 -i
gpg: signal 11 caught ... exiting
Segmentation fault
(gdb) bt
#0  0x00007f17bb2185e2 in strlen (s=s@entry=0x0) at src/string/strlen.c:17
#1  0x0000000000460ea0 in make_filename (first_part=first_part@entry=0x0) at gnupg-1.4.23/util/fileutil.c:174
#2  0x000000000040ee42 in keydb_add_resource (url=url@entry=0x46bfe3 "secring.gpg", flags=flags@entry=4, secret=secret@entry=1)
at gnupg-1.4.23/g10/keydb.c:238
#3  0x00000000004062ee in main (argc=<optimized out>, argv=<optimized out>) at …
```

gnupg: compile with -fcommon

---

net/pdns-recursor/Makefile

pdns-recursor: update to 4.7.4

---

.github/workflows/check-autorelease-deprecation.yml

Autorelease causes some issues like heavy bandwidth usage as well as non-deterministic package releases whenever someone doesn't use the full git log.
With this comment all modified packages are checked and if they use the autorelease feature, kindly comment to the user to change that.
Signed-off-by: Paul Spooren <paul.spooren@rhebo.com>

CI: deprecate $(AUTORELEASE) via comments

---

net/acme-acmesh/Makefile
net/acme-acmesh/files/hook.sh

Signed-off-by: Glen Huang <i@glenhuang.com>
Description:
This should make #19936 backward-compatible.

acme: ensure symlinks for renewed certificates

---

net/samba4/files/samba.init

Compile tested: arm64, Easepi ARS2, openwrt 21.02.3
Run tested: arm64, Easepi ARS2, openwrt 21.02.3
Description:
support both user map and valid users on same time.
`valid users` is for validate logining user, `user map` is map user to root after login, there is not conflicts.
Signed-off-by: Liangbin Lian <jjm2473@gmail.com>

samba4: support both user map and valid users on same time

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, restart service
Description:
* instead of doing stop/start which involves restarting dnsmasq twice, kill the existing service instances on restart instead

https-dns-proxy: improve performance on restart

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, restart service
Description:
* instead of doing stop/start which involves restarting dnsmasq twice, kill the existing service instances on restart instead
(cherry picked from commit e6d746a0baa184db3caf7a088179356c798a96d3)

[22.03] https-dns-proxy: improve performance on restart

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start service
Description:
* Fixes https://github.com/openwrt/packages/issues/19978, thank you @parona-source for the report/patch!

simple-adblock: bugfix: detect dnsmasq ipset support

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start service
Description:
* Fixes https://github.com/openwrt/packages/issues/19978, thank you @parona-source for the report/patch!
(cherry picked from commit cc10774e6e3799ac86af83d8c35c6a37fd73c15a)

[22.03] simple-adblock: bugfix: detect dnsmasq ipset support

---

net/microsocks/Makefile
net/microsocks/files/microsocks.config
net/microsocks/files/microsocks.init

Initial version 1.0.3
Signed-off-by: Mateusz Korniak <matkorgithubcom@ant.gliwice.pl>
Compile tested: mipsel_24kc, Ubuntu
Run tested: mipsel_24kc , Netgear WAC104, OpenWrt 21.02.3 r16554-1d4dea6d4f / LuCI openwrt-21.02 branch git-22.083.69138-0a0ce2a
Tested on production load for few weeks now, without issues.
Description:
Tiny TCP/IP only, SOCKS5 only proxy server.
Note: PR contains all changes from older PR https://github.com/openwrt/packages/pull/18999

microsocks: add low resource SOCKS5 TCP/IP only proxy server

---

net/lighttpd/Makefile
net/lighttpd/files/lighttpd.conf
net/lighttpd/files/lighttpd.init

Description:
* lighttpd.init: print stderr trace if lighttpd.conf validation fails
* lighttpd.conf: variables, documentation comments, configuration guidance
* lighttpd-mod-rrdtool: add dependency on rrdtool1
lighttpd.conf shipped with openwrt differs from upstream source tree `doc/config/lighttpd.conf`, but openwrt uses upstream `doc/config/conf.d/*`.  Some variables defined in upstream source tree `doc/config/lighttpd.conf` are not available in lighttpd.conf shipped with openwrt, leading to broken lighttpd configs on openwrt with lighttpd-mod-rrdtool and lighttpd-mod-webdav openwrt packages.
This PR updates the lighttpd.conf shipped with openwrt to define missing variables, and updates lighttpd.init to create additional …

lighttpd: lighttpd.conf vars, doc comments, config guidance

---

.github/workflows/check-autorelease-deprecation.yml

If it doesn't exists, don't confuse the contributors.

ci: only comment AUTORELEASE deprecation if exists

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start/stop
Description:
* store all error/warning messages with the error text id so that they can be made localizable for the luci app

simple-adblock: localizable error/warning messages

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start/stop
Description:
* store all error/warning messages with the error text id so that they can be made localizable for the luci app
(cherry picked from commit 8047d2ccb716ac90f267cc2ceb3723c15c375bd2)

[22.03] simple-adblock: localizable error/warning messages

---

net/bpfcountd/Makefile
net/bpfcountd/files/etc/bpfcountd.filters
net/bpfcountd/files/etc/config/bpfcountd
net/bpfcountd/files/etc/init.d/bpfcountd

Maintainer: me
Compile tested: x86-generic, OpenWrt master (60fc93b35935)
Run tested: KVM / qemu-standard-pc-i440fx-piix-1996, OpenWrt master (60fc93b35935); configured eth0+eth1 and checked output with socat on the bpfcountd UNIX socket
Description:
bpfcountd was created to obtain packet statistics in larger networks without stressing the cpu resources. bpfcountd will count the amount of packages and bytes over time (for each defined rule). The rules are defined using the tcpdump filter syntax (bpf). The collected data is provided on a unix socket in plaintext.
https://github.com/lemoer/bpfcountd/

bpfcountd: add initial package

---

lang/php8/Makefile

Maintainer: me
Description:
(cherry picked from commit 056051da496078ebaa45d25d6fe6cbb392a60ec1)

[22.03] php8: update to 8.1.13

---

multimedia/tvheadend/Config.in
multimedia/tvheadend/Makefile

Maintainer: me
Compile tested: no.
Run tested: no. Tested only the menuconfig.
Description:
Building for arc, mips and powerpc platforms fails if -O3 and LTO optimizations are enabled. This patch removes that option for everything other than arm and x86_64. These are known to work. Fixes issue #19923.
Also fixes a typo in the description.

tvheadend: add conditions for -O3 and LTO optimizations

---

utils/docker-compose/Makefile

Maintainer: me
Description:
Since version 2.13.0, the cpu limit option in compose files version 2, does not work anymore.
I get [this error](https://github.com/SUSE/docker/blob/3e0025e2fc137f51e95758618e1b42627fe6ea1c/daemon/daemon_unix.go#L539):
"does not support CPU percent. Percent discarded."
I verified it happens just by changing compose, so it is not the kernel or the system.
Other than that it is working just fine, but I'd like to solve the issue.

docker-compose: Update to version 2.14.0

---

libs/libqmi/Config.in
libs/libqmi/Makefile

Maintainer: @BKPepe @nemesisdesign @aleksander0m 
Compile tested: x86_64, latest owrt-21.02
Run tested: no
Description:
Fix compilation for libqmi. Since merging of https://github.com/openwrt/packages/pull/19648 the libqmi does not build anymore. I got the following error.
`
SHELL= flock /home/feckert/workspace/openwrt/LDM-owrt-21.02/build/openwrt/tmp/.libqmi-1.30.8.tar.xz.flock -c '          /home/feckert/workspace/openwrt/LDM-owrt-21.02/build/openwrt/scripts/download.pl "/home/feckert/dl" "libqmi-1.30.8.tar.xz" "862482ce9e3ad0bd65d264334ee311cdb94b9df2863b5b7136309b41b8ac1990" "" "https://www.freedesktop.org/software/libqmi"
`
I already updated the HASH but then I got another error that `No rule to make target` !
Only the backport of the latest master changes fixes my issues.
If I am …

libqmi: fix build regressions

---

net/snort3/Makefile
net/snort3/patches/900-fix_build_for_archs_contain_plus.patch

This should be merged before https://github.com/openwrt/packages/pull/19989

snort3: update to 3.1.48.0-1

---

net/tailscale/Makefile

Compile tested: arm64, Belkin RT3200, Openwrt 22.03
Run tested: arm64, Belkin RT3200, Openwrt 22.03
Description: Update Tailscale version to the latest stable
Signed-off-by: Stanislav Petrashov <s@petrashov.ru>

tailscale: update to v1.32.0

---

lang/python/django/Makefile

Maintainer: @commodo and me
Description: fix CVE-2022-41323

django: bump version 3.2.16

---

net/bpfcountd/files/etc/init.d/bpfcountd

Maintainer: me
Compile tested: x86-generic
Run tested: KVM / qemu-standard-pc-i440fx-piix-1996
Description:
The original idea of the extra namespace variable was to set up bpfcountd from other daemons etc. independent of what a user configured in /etc/config/bpfcountd for instance. Like:
```
$ UCI_CONFIG_DIR=/var/run/bpfcountd/gluon-config \
/etc/init.d/bpfcountd start "" gluon
```
However there are still issues with this approach:
1) Instance specific stop calls like:
```
$ /etc/init.d/bpfcountd stop <instance-name> <namespace>"
```
will not  stop the according namespaced instance, as the stop() in /etc/rc.common will call procd_kill() without the namespace prefix. And we can't overwrite that behaviour. And asking a user to use "... start \<in\> \<ns\>" and "... stop \<ns\>.\<in\>" is …

bpfcountd: remove incomplete/broken namespace feature

---

net/natmap/files/natmap.config
net/natmap/files/natmap.init

Maintainer: me
Compile tested: x86-64, 22.03.2
Run tested: x86-64, 22.03.2
Description:
When writing luci app, I found that `ipv4` and `ipv6` options should be merged into single option, for better user experience. Sorry for my mistake.
This PR should be backported to 22.03.2.

natmap: merge "ipv4" and "ipv6" options into single "family" option

---

net/snort3/Makefile
net/snort3/files/homenet.lua
net/snort3/files/local.lua
net/snort3/files/snort.config
net/snort3/files/snort.init

This commit adds `/etc/snort/local.lua` and `/etc/snort/homenet.lua` for user defined config options which is more simplistic than modifying upstream files directly. That can be tedious and decisive to maintain in sync with upstream changes.  The init script has been adjusted accordingly.
Acknowledgment to amish who maintains the Arch Linux [snort-nfqueue package](https://aur.archlinux.org/packages/snort-nfqueue) for these ideas and initial code.
Another modification is dropping the following args in the call to `/usr/bin/snort` by the init system as these options are provided in `/etc/snort/local.lua`:
* --daq-dir /usr/lib/daq/
* -A "$alert_module"
Instructions to configure snort3:
```
1. Edit /etc/snort/homenet.lua and redefine HOME_NET and EXTERNAL_NET, for example:    
HOME_NET = [[ …
```

snort3: unified configs: local.lua and homenet.lua

---

net/snowflake/Makefile
net/snowflake/files/snowflake-proxy.init

Package Tor's Snowflake system components so users can offer e.g. a standalone Snowflake proxy on their routers or other devices.
Signed-off-by: Daniel Golle [daniel@makrotopia.org](mailto:daniel@makrotopia.org)
(cherry picked from commit https://github.com/openwrt/packages/commit/cf120a7effd5d13a7f705b5eb9d22410b73d71f3)
Maintainer: @dangowrt, me

[21.02] snowflake: add package

---

lang/python/django/Makefile

Maintainer: @commodo and me
Compile tested: x86_64, qemu, master snapshot
Run tested: x86_64, qemu, master snapshot, serve etebase
Description: fix CVE-2022-41323

django: bump version 4.1.3

---

net/privoxy/Makefile

- **Maintainer**: `PKG_MAINTAINER` field is blank.
- **Compile tested**: Tested with my PR https://github.com/openwrt/packages/pull/19964 that causes the `multi-arch-test-build.yml` action to fail if the `opkg install ...` command fails.
In https://github.com/aloisklink/packages/pull/1, you can see that before this change, `arm_cortex-a15_neon-vfpv4` and `aarch64_cortex-a53` fails, but after this change, `opkg install` succeeds
- **Run tested**: Not tested on any real devices.
Fix the indentation of the `preinst`/`postinst` scripts for the `privoxy` package.
Because these scripts didn't start with `#!/bin/sh` (they instead started with the TAB character), `/bin/sh` was not used to start them.
On `x86_64` and `i386_pentium-mmx`, this seems to be fine, but when using …

privoxy: fix `preinst`/`postinst` indentation

---

.github/workflows/entrypoint.sh

**Maintainer:** N/A (not a package, GitHub CI)
**Compile tested:** N/A
**Run tested:** Tested with a PR on my fork: https://github.com/aloisklink/packages/pull/1
Enable `errexit` and `nounset` [POSIX shell options][1] in `.github/workflows/entrypoint.sh` so that the script fails if any command within the script fails.
Fixes: https://github.com/openwrt/packages/issues/19953
[1]: https://pubs.opengroup.org/onlinepubs/9699919799//utilities/V3_chap02.html#set
---
This mainly helps debug errors in the `preinst`/`postinst` scripts, as they will cause `opkg install "$PKG"` to return with a non-zero exit code, which will then cause the `entrypoint.sh` script to immediately exit, and cause GitHub Actions CI to fail.
The same should also apply to the `prerm`/`postrm` scripts when …

github-ci: error on any shell errors

---

net/tailscale/Makefile

Signed-off-by: Carlo Alberto Ferraris <cafxx@strayorange.com>
Run tested: N/A (but I manually added the same line in the backup/restore configuration, and tailscale continued working correctly after a sysupgrade)
Description: Fixes #19774

tailscale: preserve tailscaled state file

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, run filter on OISD file
Description:
* OISD dnsmasq config files switched from using address= to server=

simple-adblock: support new OISD dnsmasq config

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, run filter on OISD file
Description:
* OISD dnsmasq config files switched from using address= to server=
(cherry picked from commit 3950f0ce99844425805887a8e312db6c911fe398)

[22.03] simple-adblock: support new OISD dnsmasq config

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, restart service

https-dns-proxy: fix restart

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/https-dns-proxy.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, restart service
(cherry picked from commit 75ac50ca895e9e042afe9c4a64a367e3863e471f)

[22.03] https-dns-proxy: fix restart

---

net/pdns/Makefile

Maintainer: me
Run tested: docker/qemu mips_24kc-master
Description:

pdns: update to 4.7.3

---

net/knot/Makefile

Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.0 (hbk)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.0 (hbk)
Description:
- Release upgrade (https://www.knot-dns.cz/2022-12-12-version-324.html)

knot: update to version 3.2.4

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/lib/ddns/update_gandi_net.sh

Compile tested: (dynamic script, so no compilation)
Run tested:
- arch: ath79/generic
- model: TP-Link Archer C7 v2
- version: OpenWrt 22.03.2 r19803-9a599fee93 / LuCI openwrt-22.03 branch git-22.288.45147-96ec0cd
- tests done: Replaced the script file, `rm /var/run/ddns/* /var/log/ddns/* && service ddns restart`, checked that the logs look like expected. Tried triggering an update when rate-limited to test the added timeout.
Description:
- Some gandi.net updates seemed flaky, but it was hard to know from the logs what went wrong, so I added to the logs
- the executed curl command to be able to test it manually
- the curl exit status
- Turns out sometimes the request would just hang, and eventually curl would return with exit status `35`. I think that it's better to …

ddns-scripts: update_gandi_net: improve logging & add timeout

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested:  x86_64, Sophos SG-135, OpenWrt 22.03.2, install, start with dnsmasq.nftset option.
Description:
* fixes https://github.com/openwrt/openwrt/issues/11481 thanks to:
* https://github.com/mistepien for reporting
* https://github.com/dave14305 for diagnosing

simple-adblock: bugfix: add dnsmasq.nftset to uci_load_validate

---

lang/ruby/Makefile

This release includes a security fix.
- CVE-2021-33621: HTTP response splitting in CGI
For more details:
- https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-0-5-released/
Description:

ruby: update to 3.0.5

---

net/simple-adblock/Makefile
net/simple-adblock/files/simple-adblock.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, install, start with dnsmasq.nftset option.
Description:
* fixes https://github.com/openwrt/openwrt/issues/11481 thanks to:
* https://github.com/mistepien for reporting
* https://github.com/dave14305 for diagnosing
(cherry picked from commit fff884e67f62f0ee16bb95507c782d25a6d91eea)

[22.03] simple-adblock: bugfix: add dnsmasq.nftset to uci_load_validate

---

net/openssh/Makefile

Description:
Version bump to 9.1p1

openssh: update to 9.1p1

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, install/start

pbr: detect missing iptables

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, install/start
(cherry picked from commit a86985879fa117782dc232122819e9bbb93be175)

[22.03] pbr: detect missing iptables

---

utils/stress-ng/patches/001-disable-xxhash-and-libegl-stressors.patch

Maintainer: me
Compile tested: x86 22.03  https://github.com/openwrt/openwrt/commit/83c70346ac89c556b5bda8bcd88b7ee93fed6d7f
Run tested: x86 22.03  https://github.com/openwrt/openwrt/commit/83c70346ac89c556b5bda8bcd88b7ee93fed6d7f

stress-ng: adjust build with xxhash & libegl

---

lang/perl/Config.in

Perl threads seem to be supported and working for aarch64, and including aarch64 here would allow packages like freeswitch-mod-perl to become available from the standard OpwnWrt package repository for popular routers such as the Linksys E8450 and Belkin RT3200.
Signed-off-by: Doug Thomson <dwt62f+github@gmail.com>
Compile tested:  aarch64_cortex-a53, OpenWrt 22.03.2
Run tested: Linksys E8540 (Mediatek  mt7622), OpenWrt 22.03.2
Description:
When I set up my new Linksys E8450 router I was puzzled to find that I could not install the freeswitch-mod-perl package - it simply does not exist in the repository. Tracing this back (thanks to @micmac1), it turns out that mod-perl requires Perl threads, and that the Perl threads option defaults to disabled for the aarch64 …

perl: enable threading support for aarch64 by default

---

net/acme-acmesh/Makefile
net/acme-acmesh/files/hook.sh
net/acme-common/files/acme.sh
net/haproxy/Makefile
net/haproxy/files/acme.hotplug

This adds an export of the canonical paths for certificates and challenges so
the contract for consumers becomes explicit. Also contains a couple of cleanups
to make use of those exports in the hook scripts.
Cc @hgl

acme: Export the canonical paths for certificates and challenges

---

utils/miniflux/Makefile

miniflux: update to 2.0.41

---

net/openappid/Makefile

Traditionally, Snort rules are based upon packet analysis.  OpenAppID enables detection of applications/cloud applications on the network.
This package provides OpenAppID and signature files used by OpenAppID to detect network traffic from certain applications can be used to identify rogue application use, detect malicious applications and implement various application policies, such as application blacklisting, limiting application usage, and enforcing conditional controls.
To use, for example, edit `/etc/snort/local.lua` and add the following section at a minimum:
```
appid = {
app_detector_dir = '/usr/lib/openappid',
log_stats = true,
app_stats_period = 60,
}
```

OpenAppID: add new package

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.14.1)

docker-compose: Update to version 2.14.1

---

utils/dosfstools/Makefile

Run tested: NA
Description:
Both mirrors provided in the Makefile only serve gzipped tarballs.

dosfstools: fix PKG_SOURCE

---

libs/apr-util/Makefile

Maintainer: Thomas Heil, but I can't find a github nickname and it seems like they are not active in OpenWrt since 2018
Compile tested: armv7, Turris Omnia, OpenWrt master
Run tested: no
Description: Build reliably fails with -j20 for me with OpenWrt master and Debian 11, it works with -j1. It seems like this was also reported [here](https://github.com/openwrt/packages/issues/17669#issuecomment-1019166192)
```
/bin/bash /build/build/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr/share/build-1/libtool --silent --mode=compile ccache_cc   -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/build/build/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/apr-1.7.0=apr-1.7.0 -Wformat …
```

apr-util: disable parallel build

---

utils/lxc/files/lxc-auto.init

Maintainer: @ratkaj @BKPepe
A back port of https://github.com/openwrt/packages/pull/19316 
Fixes this message from image builder:
```
Finalizing root filesystem...
/build/openwrt-imagebuilder/build_dir/target-x86_64_musl/root-x86/etc/init.d/lxc-auto: line 3: /lib/functions.sh: No such file or directory
Enabling boot
Enabling cgroupfs-mount
Enabling collectd
Closes https://github.com/openwrt/packages/issues/19292
```
Signed-off-by: Marc Benoit [marcb62185@gmail.com](mailto:marcb62185@gmail.com)

[22.03] lxc-auto: made init script compatible with image builder

---

utils/dos2unix/Makefile

Compile tested: malta/be
Description:
Without this patch the build uses the msgfmt application which is
provided by the host tool gettext in OpenWrt. Instead of adding the
dependency to gettext remove NLS support.
This fixes the following build error:
-------------------------------------------
msgfmt -c po/da.po -o po/da.mo
make[4]: msgfmt: No such file or directory
make[4]: *** [Makefile:472: po/da.mo] Error 127

dos2unix: Deactivate NLS support

---

libs/boost/Makefile

Maintainer:  @ClaymorePT 
Compile tested: Octeon PLus
Description:
This commit updates boost to version 1.81.0
A new library is available:
- URL [[1]]: A library for parsing, modifying, and printing URLs using only C++11, from Vinnie Falco and Alan de Freitas. Features include fast compilation, strong invariants, and strict compliance using a memory-friendly approach.
More info about Boost 1.81.0 can be found at the usual place [[2]].
[1]: https://www.boost.org/doc/libs/1_81_0/libs/url/doc/html/index.html
[2]: https://www.boost.org/users/history/version_1_81_0.html
Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

boost: Updates package to version 1.81.0

---

mail/postfix/Makefile
mail/postfix/patches/502-detect-glibc.patch

Compile tested: malta/be
Description:
This backports a change from postfix 3.8, I do not know exactly why it detects Linux 6 here, but this is needed to fix compilation with glibc 2.36.

postfix: Fix compile against glibc 2.36

---

net/smcroute/Makefile

Bring it up to the latest stable version.
Signed-off-by: Alexey Smirnov <s.alexey@gmail.com>
Maintainer: @mwarning

smcroute: update to 2.5.6

---

net/tor/Makefile

Bring it up to the latest stable version. Changelog details on each commit.
Maintainer: @tripolar [seems unresponsive, though. @BKPepe?]

tor: bump to latest stable

---

libs/libdaq3/Makefile

libdaq3: update to 3.0.10

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr.init

Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, start, ensure polices are enforced.
Description:
* add more error/warning messages
* better return statements from ips/nftset functions
* better error/warning handling when inserting policies
* comment out unnecessary nft set/ipst clean ups
* shellchecked status functions
(cherry picked from commit 5bec4a25415e751c4000bdb4b18f662ac2f1a98d)

[22.03] pbr: update to 1.0.1-1

---

utils/exfatprogs/Makefile

Maintainer: me
Description:
CHANGES:
* fsck.exfat: Keep traveling files even if there is a corrupted directory entry set.
* fsck.exfat: Introduce the option "b" to recover a boot sector even if an exFAT filesystem is not found.
* fsck.exfat: Introduce the option "s" to create files in "/LOST+FOUND", which have clusters allocated but was not belonged to any files.
* fsck.exfat: Rename '.' and '..' entry name to the one user want.
NEW FEATURES:
* fsck.exfat: Repair corruptions of an exFAT filesystem. Please refer to fsck.exfat manpage to see what kind of corruptions can be repaired.
* exfat2img: Dump metadata of an exFAT filesystem. Please refer to exfat2img manpage to see how to use it.
BUG FIXES:
* fsck.exfat: Fix an infinite loop while …

exfatprogs: update to version 1.2.0

---

utils/lvm2/Makefile
utils/lvm2/patches/002-const-stdio.patch
utils/lvm2/patches/003-no-mallinfo.patch
utils/lvm2/patches/004-missing-includes.patch

Maintainer: me
Description:
Version 2.03.17 - 10th November 2022
====================================
Add new options (--fs, --fsmode) for FS handling when resizing LVs.
Fix 'lvremove -S|--select LV' to not also remove its historical LV right away.
Fix lv_active field type to binary so --select and --binary applies properly.
Switch to use mallinfo2 and use it only with glibc.
Error out in lvm shell if using a cmd argument not supported in the shell.
Fix lvm shell's lastlog command to report previous pre-command failures.
Extend VDO and VDOPOOL without flushing and locking fs.
Add --valuesonly option to lvmconfig to print only values without keys.
Updates configure with recent autoconf tooling.
Fix lvconvert --test --type vdo-pool …

lvm2: update LVM2 to 2.03.17 and DM to 1.02.187

---

utils/cni-plugins/Makefile
utils/cni/Makefile

Maintainer: me, @oskarirauta, @aparcar 
Description:
Update [`cni`](https://github.com/containernetworking/cni) to [1.1.2](https://github.com/containernetworking/cni/releases/tag/v1.1.2)
Update [`cni-plugins`](https://github.com/containernetworking/plugins) to to [1.1.1](https://github.com/containernetworking/plugins/releases/tag/v1.1.1)

update `cni` and `cni-plugins`

---

libs/postgresql/Makefile
libs/postgresql/patches/700-no-arm-crc-march-change.patch

Maintainer: me
Description:
This release contains a variety of fixes from 14.5.
See https://www.postgresql.org/docs/release/14.6/ for details.

postgresql: update to version 14.6

---

net/natmap/Makefile
net/natmap/files/natmap.config
net/natmap/files/natmap.init

Maintainer: me
Compile tested: x86-64, 22.03.2
Run tested: x86-64, 22.03.2
Description:
The bind port (-b) can be used with forward port (-p), so expose this option in config file.
Please backport this PR to 22.03 branch when merging, thanks!

natmap: add forward_port option

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release [Changelog](https://github.com/docker/compose/releases/tag/v2.14.2)

docker-compose: Update to version 2.14.2

---

net/uacme/Makefile
net/uacme/files/run.sh

Description: Here is an attempt to make uacme compatible with nft firewall implementation.
This has been missing as identified in https://github.com/openwrt/packages/issues/16818

uacme: use UCI instead of iptables for firewall configuration

---

net/natmap/Makefile
net/natmap/files/natmap.config
net/natmap/files/natmap.init

Maintainer: me
Compile tested: x86-64, 22.03.2
Run tested: x86-64, 22.03.2
Description:
The bind port (-b) can be used with forward port (-p), so expose this option in config file.

[22.03] natmap: add forward_port option

---

lang/node/Makefile
lang/node/patches/003-path.patch

Compile tested: head, aarch64, arm, i386, x86_64, mipsel (pistachio) 
Run tested: (qemu 7.2.0) aarch64
Description:
Update to v16.19.0
*OpenSSL 1.1.1s
*Root certificates updated to NSS 3.85
*Time zone update to 2022f

node: bump to v16.19.0

---

multimedia/motion/Makefile

Maintainer:  @mips171 (original Roger D <rogerdammit [at] gmail.com>)
Compile tested: (ARM, Linksys, OpenWrt version 22.03.2)
Description:
Package compile fails without.

Fix motion gettext

---

net/snort3/Makefile
net/snort3/files/local.lua

snort3: update to 3.1.50.0

---

utils/lxc/Makefile
utils/lxc/patches/001-build-detect-where-struct-mount_attr-is-declared.patch
utils/lxc/patches/002-build-detect-sys-pidfd.h-availability.patch
utils/lxc/patches/003-build-check-for-FS_CONFIG_-header-symbol-in-sys-moun.patch
utils/lxc/patches/011-tree-wide-wipe-direct-or-indirect-linux-mount.h-incl.patch
utils/lxc/patches/012-tree-wide-use-struct-clone_args-directly.patch
utils/lxc/patches/013-tree-wide-use-struct-open_how-directly.patch

Compile tested: malta/be
Description:
Backport patches from upstream lxc master to fix compilation against glibc 2.36.
The changes were added in these pull requests:
https://github.com/lxc/lxc/pull/4179
https://github.com/lxc/lxc/pull/4181

lxc: Fix compilation with glibc 2.36

---

mail/pigeonhole/Makefile

pigeonhole: update to 0.5.19

---

libs/hwloc/Makefile

hwloc: update to 2.8.0

---

lang/python/Werkzeug/Makefile

Maintainer: me
Description:
Fix router to restore the 2.1 strict_slashes == False behaviour
whereby leaf-requests match branch rules and vice versa.
pallets/werkzeug#2489
Fix router to identify invalid rules rather than hang parsing them,
and to correctly parse / within converter arguments.
pallets/werkzeug#2489
Update subpackage imports in werkzeug.routing to use the import as
syntax for explicitly re-exporting public attributes.
pallets/werkzeug#2493
Parsing of some invalid header characters is more robust.
pallets/werkzeug#2494
When starting the development server, a warning not to use it in a
production deployment is always shown. pallets/werkzeug#2480
LocalProxy.__wrapped__ is always set to the wrapped object when the
proxy is …

Werkzeug: update to version 2.2.2

---

lang/node/Makefile
lang/node/patches/003-path.patch

Run tested: (qemu 7.2.0) arm
Description:
*OpenSSL 1.1.1s
*Root certificates updated to NSS 3.85
*Time zone update to 2022f
(cherry picked from commit f8bd5eaa6edcf437130118295380c93f2acdfdc3)

[22.03] node: bump to v16.19.0

---

lang/node/Makefile

Compile tested: 21.02, arm
 Run tested: (qemu 7.2.0) arm
Description:
* CVE-2022-43548: DNS rebinding in --inspect via invalid octal IP address (Medium)
* OpenSSL 1.1.1s
* Root certificates updated to NSS 3.85
* Time zone update to 2022f

[21.02] node: bump to v14.21.2

---

utils/zyxel-reset/Makefile

Maintainer: me
Compile tested: ath79 / realtek
Run tested: Realtek / ZyXEL GS1900-8HP
Description:
Add the zyxel-reset package.
This package allows to trigger a factory-reset for ZyXEL devices by sending a magic LLDP package while the device-to-reset is booting.
This is useful for remote-resetting a ZyXEL device running stock firmware connected to a switch using OpenWrt. It also allows to reset devices which do not have a reset-button such as the NWA55AXE.
Signed-off-by: David Bauer <mail@david-bauer.net>

zyxel-reset: add package

---

lang/golang/golang/patches/010-cmd-compile-turn-off-jump-tables-when-spectre-retpolines-.patch

Description:
Upstream commit: golang/go@156578067111742b55718066c91b8ec66d35e03d
Fixes: #20026

golang: backport an upstream fix for non-retpoline-compatible error

---

libs/libgpiod/Makefile

Maintainer: @mhei or @neheb 
Compile tested: x86_64, APU3, master
Run tested: x86_64, APU3, OpenWrt master,tests done)
Description:
This library needs the kernel config option 'CONFIG_GPIO_CDEV_V1=y' to be set. If this is not set, the tool 'gpioinfo' produces the error message 'error creating line iterator'. Add the missing kernel config option to build CDEV with API Version 1 fixes this. Other distributions does have the same issue: https://bugs.gentoo.org/807334
```
gpiochip3 - 7 lines:
line   0: "front-led1" "apu:green:1" output active-low [used]
line   1: "front-led2" "apu:green:2" output active-low [used]
line   2: "front-led3" "apu:green:3" output active-low [used]
line   3: "front-button" "front button" input active-low [used]
line   4:    "simswap"       unused  output …
```

libgpiod: add missing kernel build options via KCONFIG

---

libs/libarchive/Makefile
libs/libarchive/patches/CVE-2022-36227.patch

Description: If you would prefer me to drop the update commits and fix the CVE, let me know and I can drop them, but these versions also fix some less important CVEs.

[21.02] libarchive: update to 3.5.3, fix CVE-2022-36227

---

libs/libarchive/Makefile
libs/libarchive/patches/CVE-2022-36227.patch

Description: If you would prefer me to drop the update commit and fix the CVE, let me know and I can drop them, but these versions also fix some less important CVEs.

[22.03] libarchive: update to 3.5.3, fix CVE-2022-36227

---

net/bind/Makefile

Compile tested: x86_64, generic, HEAD (fb15cb4ce95)
Description:
Picking up fix to [GL #2895](https://gitlab.isc.org/isc-projects/bind9/-/issues/2895) which has been problematic.

bind: update to version 9.18.10

---

net/strongswan/Makefile

Run tested: NA
Description:
Fixes: #16691
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>

strongswan: fix typo in strongswan-mod-nonce description

---

net/telnet-bsd/Makefile
net/telnet-bsd/patches/001-telnet-bsd-1.2-fbsd.patch
net/telnet-bsd/patches/002-dont-compile-telnetd.patch
net/telnet-bsd/patches/telnet-bsd-1.2-format-security.patch
net/telnet-bsd/patches/telnet-bsd-1.2-musl.patch

The telnet-bsd package currently only exist in master: this PR aims to bring it into current stable release.
It is a leaf package, sole provider and not affecting existing things, so hopefully backporting should be acceptable.

[22.03 backport] telnet-bsd: add package

---

utils/tree/Makefile

tree: bump to 2.1.0

---

lang/python/python-websocket-client/Makefile

Maintainer: me
Description:
New upstream update. [Changelog](https://github.com/websocket-client/websocket-client/blob/master/ChangeLog)

python-websocket-client: update to 1.4.2

---

lang/python/python-paramiko/Makefile

Maintainer: me
Description:
New upstream update. [Changelog](https://www.paramiko.org/changelog.html)

python3-paramiko: update to version 2.12.0

---

lang/python/python-jsonschema/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/python-jsonschema/jsonschema/releases)

python-jsonschema: Update to 4.17.3

---

lang/python/python-docker/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/docker-py/releases)

python-docker: Update to 6.0.1

---

net/bind/Makefile
net/bind/files/named.init

Compile tested: x86_64, generic, HEAD (fb15cb4ce95)
Run tested: same, running on production router
Description:
On startup, my logging fills up with noise about not being able to reach the IPv6 addresses of the root name servers:
```
Dec 27 17:14:24 OpenWrt named[9965]: network unreachable resolving '_.org/A/IN': 2001:500:200::b#53
Dec 27 17:14:24 OpenWrt named[9965]: network unreachable resolving '_.org/A/IN': 2001:500:9f::42#53
Dec 27 17:14:24 OpenWrt named[9965]: network unreachable resolving '_.org/A/IN': 2001:dc3::35#53
Dec 27 17:14:24 OpenWrt named[9965]: network unreachable resolving '_.org/A/IN': 2001:500:1::53#53
```
This is normal.  My MSP (Sparklight) doesn't do IPv6.  To eliminate this noise, we can pass `-4` to named when it gets started.

bind: start up with -4 if not listening on ipv6 addresses

---

libs/libtorrent-rasterbar/Makefile

Run tested: -
Description:
Release note: https://github.com/arvidn/libtorrent/releases/tag/v2.0.8

libtorrent-rasterbar: Update to 2.0.8

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.15.0)

docker-compose: Update to version 2.15.0

---

net/udphp-client/Makefile

Maintainer: me
Compile tested: (mipsel_24kc, mt7621, 22.03.2)
Run tested: (mipsel_24kc, mt7621, 22.03.2, tests done)
Description:
udphp is UDP protocol hole punching tool, main goal to establish direct connection between two hosts behind GCNAT or inaccessible NAT servers

udphp-client: new package

---

utils/dfu-programmer/Makefile
utils/dfu-programmer/patches/000-remove-docs-etc.patch

The project website http://dfu-programmer.github.io seams dead, but there are new releases on github. They just released 1.0.0, update to it.
I removed docs, bash-completion and the fedora spec file from configure.ac to fix cross compilation problems.
Signed-off-by: Stefan Hellermann <stefan@the2masters.de>
Maintainer: me
Compile tested: ath79 (tplink wdr4300) + mt7622 (ubnt unifi 6 lr)
Run tested: ath79 (tplink wdr4300)

dfu-programmer: update to 1.0.0

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/share/ddns/default/strato.com.json

Maintainer: ?
Compile tested: x86 ath79 ramips
Run tested: x86 ath79 ramips
Description:
ddns-scripts: add strato ipv6 support

ddns-scripts: add strato ipv6 support

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/lib/ddns/update_luadns_v1.sh
net/ddns-scripts/files/usr/share/ddns/default/luadns.com-v1.json

This PR adds support for updating DNS records on the LuaDNS API.
Compile tested: mips_24kc, Dongwon T&I DW02-412H, from HEAD
Run tested: mips_24kc, Dongwon T&I DW02-412H, openwrt-22.03.2, tests done
Signed-off-by: Jihoon Han <rapid_renard@renard.ga>

ddns-scripts: add support for LuaDNS

---

lang/php8/Makefile

Maintainer: me
Description:
This fixes:
- CVE-2022-31631

php8: update to 8.2.1

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.15.1)

docker-compose: Update to version 2.15.1

---

net/speedtestpp/Makefile
net/speedtestpp/patches/01-remove-libxml-dependency.patch

Description:
Added patch https://github.com/nuclon/SpeedTest/commit/b7db370449cfe2b453c22b74a660701f78bd7ce3 to remove dependency for libxml2 and dropped out AUTORELEASE while at it.
Size reduction whilst libxml2 in no longer required, fits better on devices with small rootfs..

speedtestpp: drop libxml2 dependency

---

net/knot/Makefile
net/ocserv/Makefile

Maintainer: @salzmdan  @nmav 
Compile tested: ipq806x/R7800,  CI (in this PR)
Run tested: -
Knot and ocserv are currently broken in buildbot for both master and 22.03 due to libmaxminddb detection.
Disable detection in both.
(Libmaxmind got a pkgconfig file a few days ago with #20215 , which caused the libraryt to be detected by knot and ocserv, breaking the buildbot compilation of those packages. Fix things with configure.ac options to disable detection.)
This needs to be backported to 22.03, too.

Knot, ocserv: disable libmaxminddb detection

---

net/frp/Makefile
net/frp/test.sh

Run tested: (x86_64, OpenWrt 22.03, tests done)
Description:
Version 0.46.0 added support for the quic protocol between frpc and frps.
changlog:
https://github.com/fatedier/frp/releases/tag/v0.46.0
https://github.com/fatedier/frp/releases/tag/v0.46.1

frp: update to 0.46.1

---

net/xinetd/Makefile
net/xinetd/files/xinetd.init

This extension is based on the issue https://github.com/openwrt/luci/issues/6151 and implements the requested `redirect` feature.
The redirect option from within the uci config file which is written as `[ipv6addr]:port` or `ipv4addr:port` has to be converted to the format `ipaddr port` to be understood by xinetd.

xinetd: add processing of redirect option in init script

---

devel/gcc/Makefile
devel/gcc/patches/12.2.0/002-case_insensitive.patch
devel/gcc/patches/12.2.0/003-dont-choke-when-building-32bit-on-64bit.patch
devel/gcc/patches/12.2.0/010-documentation.patch
devel/gcc/patches/12.2.0/110-Fix-MIPS-PR-84790.patch
devel/gcc/patches/12.2.0/230-musl_libssp.patch
devel/gcc/patches/12.2.0/300-mips_Os_cpu_rtx_cost_model.patch
devel/gcc/patches/12.2.0/810-arm-softfloat-libgcc.patch
devel/gcc/patches/12.2.0/820-libgcc_pic.patch
devel/gcc/patches/12.2.0/840-armv4_pass_fix-v4bx_to_ld.patch
devel/gcc/patches/12.2.0/850-use_shared_libgcc.patch
devel/gcc/patches/12.2.0/851-libgcc_no_compat.patch
devel/gcc/patches/12.2.0/870-ppc_no_crtsavres.patch
devel/gcc/patches/12.2.0/881-no_tm_section.patch
devel/gcc/patches/12.2.0/900-bad-mips16-crt.patch
devel/gcc/patches/12.2.0/910-mbsd_multi.patch
devel/gcc/patches/12.2.0/920-specs_nonfatal_getenv.patch
devel/gcc/patches/12.2.0/960-gotools-fix-compilation-when-making-cross-compiler.patch
devel/gcc/patches/12.2.0/970-macos_arm64-building-fix.patch

Copy patch from gcc 11 to gcc 12 and add missing hash.
---
@hnyman lets see... we asked for gcc 12 support ages ago and here we are....

gcc: add support for gcc 12

---

net/ztdns/Makefile

Compile tested: x86_64 / recent git
Run tested: x86_64 / recent git
Description:
ztDNS is a dedicated DNS server for a ZeroTier virtual network.
ztdns is alternative to Zerotier's own zeronds.
Package requested by @ehrenmann1977 here https://github.com/uxbh/ztdns/issues/30
I used palonsoro's repository as it comes with newer Go support and compiles without patching.
I would rather had provided official zeronds- but unfortunately it is written in rust, and (cross-)compiling
rust code in openwrt buildroot does not currently seem to be officially supported, there were solutions though-
but it seemed a bit too complicated. If one day, openwrt would provide support for rust as well, I might take this
into re-consideration, but for now- I hope ztdns brings joy for …

ztdns: new package

---

libs/faad2/Makefile

Switch to local tarballs. Smaller and faster.

faad2: update to 2.10.1

---

utils/stress-ng/Makefile

Maintainer: me
Compile tested: x86 (https://github.com/openwrt/openwrt/commit/68f983ba4102faac55211c6c6e799641ed3e3da6)
Run tested: x86 (https://github.com/openwrt/openwrt/commit/68f983ba4102faac55211c6c6e799641ed3e3da6)

stress-ng: bump to version 0.15.01

---

net/safe-search/Makefile
net/safe-search/files/safe-search.defaults

Maintainer: @farmergreg
Description:
The safe-search package creates symlinks in a configured additional hosts directory. The link targets are inside another directory which has to be made available to dnsmasq as well.
Now that support for adding additional paths to dnsmasq was added by commit openwrt/openwrt@aa12a0fdd1c5a004281633c5b0758da1781bb41c implement adding this path using the existing uci-defaults script.

safe-search: fix use with dnsmasq in ujail

---

libs/tiff/Makefile
libs/tiff/patches/010-CVE-2022-2519.patch
libs/tiff/patches/020-CVE-2022-2520.patch

Seems upstream wants to get rid of it.
Backport upstream patches fixing several CVEs.

tiff: don't use AUTORELEASE

---

libs/libmad/Makefile

libmad: update URL to use codeberg

---

utils/qfirehose/Makefile

Compile tested: x86_64, x86_64, recent git
Run tested: x86_64, x86_64, recent git
Description:
Utility to flash firmware updates to quectel modems (ON YOUR OWN RISK!).
Verified to work, tested on Quectel EP06 with firmware EP06ELAR03A08M4G -> EP06ELAR04A06M4G.
After flashing required a AT command for selecting USB2 instead of USB3 for modem to appear into system,
minimal instructions included in package description. Software is not licensed/"totally open source" for customers of Quectel.

qfirehose: new package

---

utils/bc/Makefile

Seems Debian no longer offers ftp.
Maintainer: @br101

bc: use @DEBIAN
