openwrt/packages

lang/perl-compress-bzip2/Makefile
=> perl-compress-bzip2: update to 2.28

net/netperf/Makefile
netperf.org is gone now. Only github is left.
=> netperf: use git tarball

utils/rtl-sdr/Makefile
Upstream switched URLs.
Maintainer: @acinonyx
=> rtl-sdr: switch to git tarball

utils/podman/Makefile, utils/podman/patches/010-do-not-build-docs.patch
Compile tested: x86-64, recent git
Run tested: x86-64, recent git
Description:
Update podman to 4.3.1
catatonit is no longer required, works without.
[Release notes](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md)
=> podman: update to 4.3.1

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr.init
Maintainer: me
Run tested: x86_64, Sophos SG-135, OpenWrt 22.03.2, install, test basic configuration
Description:
Bugfixes:
* better error information for empty tid/mark and failure to resolve domains
* better handling of entries in /etc/iproute2/rt_tables
Updates:
* introduce nft_user_set_policy and nft_user_set_counter to control options for user nft sets this service creates
* use counters in internal nft sets
=> pbr: update to 1.0.1-10

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr.init
Maintainer: me
Compile tested: x86_64, Sophos SG-105, OpenWrt 22.03.3
Run tested: x86_64, Sophos SG-105, OpenWrt 22.03.3, start, verify status
Description:
* improve install/uninstall messages
* fix ips add command
* add boot() to init file
Also includes previous commits:
Bugfixes:
* better error information for empty tid/mark and failure to resolve domains
* better handling of entries in /etc/iproute2/rt_tables
Updates:
* add provides: pbr to variants
* introduce nft_user_set_policy and nft_user_set_counter to control options for user nft sets this service creates
* use counters in internal nft sets
(cherry picked from commit f4f899f6f992db1e92f02881649e1580958dae18)
=> [22.03] pbr: update to 1.0.1-14

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Compile tested: x86_64, Sophos SG-105, OpenWrt 22.03.3
Run tested: x86_64, Sophos SG-105, OpenWrt 22.03.3, install, start.
=> simple-adblock: update sed for allowing domains

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Compile tested: x86_64, Sophos SG-105, OpenWrt 22.03.3
Run tested: x86_64, Sophos SG-105, OpenWrt 22.03.3, install, start.
(cherry picked from commit 4b77f94b5398111c839f7fe0f48b52a1087585b0)
=> [22.03] simple-adblock: update sed for allowing domains

utils/acpica-unix/Makefile, utils/acpica-unix/patches/0001-ACPI_CAST_PTR-cast-through-void.patch, utils/acpica-unix/patches/0002-Linux-non-kernel-Use-use-uintptr_t-for-ACPI_UINTPTR_.patch, utils/acpica-unix/patches/0003-debug-use-UINT_PTR_T-to-store-stack-boundaries.patch
Maintainer: @pprindeville 
Compile tested: x86_64, APU3, latest version
Run tested: x86_64, APU3, latest version
Description:
Update version to 20221020
Remove deprectated AUTORELEASE feature
Backport pending [patches](https://github.com/acpica/acpica/pull/776) from upstream repository to fix gcc12 build [issue](https://github.com/acpica/acpica/issues/771)
=> acpica-unix: update version and fix gcc12 build

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/share/ddns/default/hosting.de.json, net/ddns-scripts/files/usr/share/ddns/list
Add hosting.de provider. To use dynamic DNS you have to create a DDNS host with a separate DDNS user.
Note: As of 2023-01-17 hosting.de does not work with wget which will fail with `400: Bad Request` (it will work with `--auth-no-challenge`). You should use curl instead. I have reported that to the provider.
Maintainer: ?
=> ddns-scripts: add hosting.de provider

utils/lrzsz/Makefile, utils/lrzsz/patches/001-siginterrupt-after-the-call-to-signal-otherwise-ymod.patch, utils/lrzsz/patches/002-may-be-security-fix-avoid-possible-underflow.patch, utils/lrzsz/patches/100-install_delete_fix.patch, utils/lrzsz/patches/200-format.patch
This updates to v0.12.21rc from 1999 (sic), which was never officially released. There're fixes in there, and it's what debian ships, so let's use that too. While at it, use debian's autohell hack and package description too.
Patch 1 fixes a hang with musl.
Patch 2 fixes CVE-2018-10195, add PKG_CPE_ID while at it.
Refesh the rest.
Fixes: CVE-2018-10195
Signed-off-by: Andre Heider <a.heider@gmail.com>
Maintainer: Hsing-Wang Liao @kuoruan 
Run tested: ipq40xx
=> lrzsz: update to v0.12.21rc and fix a CVE

libs/libuhttpd/Makefile, libs/libuhttpd/patches/100-wolfssl_5_support.patch
Libuhttpd is currently broken in 21.02 due to wolfssl incompatibility.
Update the package to the level in 22.03 in order to fix things.
PR for CI testing.
=> [21.02] fix libuhttpd 

net/wifidog/Makefile, net/wifidog/patches/030-wolfssl-options.patch
Unbreak wifidog in 21.02 by cherry-picking the same fix for wolfssl as in master and 22.03
(cherry picked from commit 4605f98b413b4b0433199e4fe6d3685344cbf933)
PR for CI testing.
=> [21.02] wifidog: fix compilation with more recent wolfssl

net/atlas-sw-probe/Makefile
Compile tested: Turris 1.1, mpc85xx/p2020, OpenWrt 21.02.5
Run tested: Turris 1.1, mpc85xx/p2020, OpenWrt 21.02.5
They were added in these commits [1] [2] and if they are not included, the RIPE Atlas SW Probe does not work correctly.
This should also prevent this from happening in the future as it now. We include all files with .sh extension file type.
[1] https://github.com/RIPE-NCC/ripe-atlas-software-probe/commit/70ced29fc3217dd8d61e2b78506b6103ded100aa
[2] https://github.com/RIPE-NCC/ripe-atlas-software-probe/commit/71a4ff0e68c55464f766ddb9f1dfe21b22e530db
Fixes: https://github.com/openwrt/packages/issues/20338
=> atlas-sw-probe: add more binaries

utils/crun/Makefile
Description:
Fixes: ad0aa1b2fc64e8 ("crun: update to 1.7.2")
Related discussion: #20262
=> crun: add libgcrypt dependency

lang/php8/Makefile
Maintainer: me
Description:
This fixes:
- CVE-2022-31631
=> [21.02] php8: update to 8.0.27

utils/uvol/Makefile, utils/uvol/files/autopart.defaults
Compile tested: x86_64, generic, HEAD (0a35d3f992)
Description:
Handle case of integral free size in megabytes; also simplify free size computation.
Fixes issue #20343
=> uvol: fix regression in handling fractional megabytes free

net/pbr/Makefile, net/pbr/files/etc/config/pbr, net/pbr/files/etc/init.d/pbr.init
Maintainer: me
Run tested:  x86_64, Sophos XG-105w, OpenWrt 22.03.3, test proper processing of IPv6 in policies
Description:
* fixes https://github.com/openwrt/packages/issues/20352
Thanks @PussAzuki
=> pbr: bugfix: fix is_domain()

net/pbr/Makefile, net/pbr/files/etc/config/pbr, net/pbr/files/etc/init.d/pbr.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, test proper processing of IPv6 in policies
Description:
* fixes https://github.com/openwrt/packages/issues/20352
(cherry picked from commit e7e4a013be73253d68107971e470344deb918d96)
=> [22.03] pbr: bugfix: fix is_domain()

net/pdns-recursor/Makefile
Maintainer: me
Run tested: amd64 docker rootfs
Description:
=> pdns-recursor: update to 4.8.1

utils/ncdu/Makefile, utils/ncdu/patches/900-use-alternative-color.patch
Upstream bump
Description: @clehner
=> ncdu: update to 1.18

lang/php8/Makefile
Maintainer: me
Description:
This fixes:
- CVE-2022-31631
=> [22.03] php8: update to 8.1.14

net/nextdns/Makefile
=> nextdns: Update to version 1.39.0

net/banip/Makefile, net/banip/files/README.md, net/banip/files/banip.sources
Maintainer: #20391 - dibdot
Compile tested: openWRT 21.02.5
Run tested: openWRT 21.02.5
Description:
Checkout issue 20391. Fissionrelays is down so that the list has been updated to the mentioned list by maintainer (dibdot).
Do a version dump, so that these lists will be updated. Also updated overview + example in README.
=> [21.02] banip: renew tor urls

kernel/ksmbd/Makefile
```
ksmbd requires ASN.1 grammar compiler so it depends on CONFIG_ASN1. It
should select kmod-asn1-decoder for above reason.
Due to some problems with kmod-asn1-decoder in the past ksmbd was
selecting kmod-nf-nathelper-extra instead. That was affecting network
performance in kernel as each loaded conntrack module adds some overhead
to packets processing.
Fix this unwanted side effect by depending on kmod-asn1-decoder
directly.
Link: http://lists.openwrt.org/pipermail/openwrt-devel/2023-January/040298.html
```
=> ksmbd: select ASN1 explicitly to reduce dependencies

net/nextdns/Makefile
=> [22.03] nextdns: Update to version 1.39.4

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.39.4

net/nextdns/Makefile
=> nextdns: Update to version 1.39.4

net/snort3/Makefile
=> snort3: update to 3.1.53.0

net/bind/Makefile
Compile tested: x86/master (WIP)
Run tested: x86/master (WIP)
Description:
Fixes CVEs:
*  CVE-2022-3924: Fix serve-stale crash when recursive clients
soft quota is reached.
* CVE-2022-3736: Handle RRSIG lookups when serve-stale is
active.
* CVE-2022-3094: An UPDATE message flood could cause named to
exhaust all available memory. This flaw was addressed by adding
a new "update-quota" statement that controls the number of
simultaneous UPDATE messages that can be processed or
forwarded. The default is 100. A stats counter has been added to
record events when the update quota is exceeded, and the XML and
JSON statistics version numbers have been updated.
=> bind: update to 9.18.11

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
Description: Update HAProxy to v2.6.8
=> haproxy: update to v2.6.8

net/bind/Makefile
Fixes multiple CVEs. Upstream changelog is
https://ftp.isc.org/isc/bind9/9.16.37/CHANGES
CVEs fixed:
CVE-2022-3924: Fix serve-stale crash when recursive clients soft quota
is reached.
CVE-2022-3736: Handle RRSIG lookups when serve-stale is active.
CVE-2022-3094: An UPDATE message flood could cause named to exhaust all
available memory. This flaw was addressed by adding a
new "update-quota" statement that controls the number of
simultaneous UPDATE messages that can be processed or
forwarded. The default is 100. A stats counter has been
added to record events when the update quota is
exceeded, and the XML and JSON statistics version
numbers have been updated.
Signed-off-by: Noah Meyerhans <frodo@morgul.net>
Maintainer: me
Compile tested: malta/19.07
Run tested: malta/19.07 runtime tests
=> bind: bump to 9.16.37

kernel/v4l2loopback/Makefile
Signed-off-by: Michel Promonet <michel.promonet@free.fr>
Maintainer: @mpromonet 
Compile tested: sunxi-cortexa7-friendlyarm_nanopi-neo-air, openwrt master@a63430eac3
Run tested: sunxi-cortexa7-friendlyarm_nanopi-neo-air, openwrt master@a63430eac3, it create a v4l2 loopback device
Description:
=> v4l2loopback: upgrade to v0.12.7

libs/nghttp2/Makefile
Signed-off-by: An Phuc Nguyen <phucan.nguyen@daum.net>
Compile tested: ramips/mt7621, Xiaomi Mi Router 4A Gigabit, OpenWrt SNAPSHOT r0-0a15bb6
Run tested: ramips/mt7621, Xiaomi Mi Router 4A Gigabit, OpenWrt SNAPSHOT r0-0a15bb6
=> nghttp2: update to 1.51.0

lang/python/python3-host.mk, lang/python/python3-package.mk, lang/python/setup.py.shim
Maintainer: @jefferyto
Compile tested: x86 https://github.com/openwrt/commit/6e3acebe35cfc584e145e495b175ae5308d2f2bc
Run tested: x86 https://github.com/openwrt/commit/6e3acebe35cfc584e145e495b175ae5308d2f2bc
------------------------------------------------------------------------
A new PEP 517 (https://www.python.org/dev/peps/pep-0517/) has defined that Python packages can be shipped without any `setup.py` file, and that a `pyproject.toml` file is sufficient.
A `setup.py` shim layer is suggested as a method for running the build.
For these cases, we will add a support in the OpenWrt build-system to provide the default `setup.py` shim layer in case this file does not exist, but there is a `pyproject.toml` file.
We also seem to need to tweak the shim layer with the PKG_VERSION, otherwise …
=> python-build: add support for pyproject.toml files (reboot of #17130)

lang/python/python3/Makefile, lang/python/python3/files/python3-package-pip.mk
Compile tested: x86 https://github.com/openwrt/openwrt/commit/7396263680b951211f33f2aa266b11bdd0047adc
Run tested: x86 https://github.com/openwrt/openwrt/commit/7396263680b951211f33f2aa266b11bdd0047adc
-------------------------------------
Fixes:
https://github.com/openwrt/packages/issues/12707
Seems to work.
Looking into the 'venv' lib, it seems it's installing pip & setuptools inside a virtual environment.
`python3-pip` is already ~6 MB.
This adds another ~3 MB.
But, this gives users the ability to run Python virtual environments, which is a pretty common feature of Python in production cases (usually web stuff).
=> python3: add 'ensurepip' to python3-pip sub-package

net/openssh/Makefile
Description:
Version bump to 9.2p1
Fix openssh-server-pam build (Fixes #20291)
=> openssh: update to 9.2p1

net/autossh/Makefile, net/autossh/files/autossh.config, net/autossh/files/autossh.init
Maintainer: @jempatel, @neheb 
Compile tested: x86 22.03.3
Run tested: x86 22.03.3
Description:
It's not possible to pass quoted string as a single argument using uci, which makes it impossible to supply proxy string to dropbear.
Additional option solves this issue.
Signed-off-by: ValdikSS <iam@valdikss.org.ru>
=> autossh: Add dropbear proxy (-J) support

net/autossh/Makefile, net/autossh/files/autossh.init
In case of disabled configuration instances in the top of configuration file, enabled instances won't be started as the first disabled instance would result in init script termination.
Signed-off-by: ValdikSS <iam@valdikss.org.ru>
Maintainer: @bk138
=> autossh: return from instance function, not exit the script

net/pdns-recursor/Makefile
=> pdns-recursor: update to 4.8.2

net/tailscale/Makefile, net/tailscale/README.md, net/tailscale/patches/010-fake_iptables.patch, net/tailscale/patches/020-tailscaled_fake_iptables.patch, net/tailscale/patches/030-default_to_netfilter_off.patch, net/tailscale/test.sh
Maintainer: Jan Pavlinec / @ja-pa
- Update tailscale to version 1.36.0
- Patch iptables support
Tailscale does not (yet) support nftables.
Tailscale allows running with --netfilter=off allowing end-user to create his own firewall rules, but this affects only tailscale cli, not tailscaled daemon, so connection cannot be made without error telling that tailscaled was unable to determine execute iptables for determining it's version.
There is a work-around for those who do not want nft-iptables compatibility package; they can create a script to /usr/bin/iptables which responds to --version argument and echos fake version string
and on any other arguments or no arguments, just exits.
After this procedure and starting tailscale …
=> tailscale: update to 1.36.0

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.conf.update, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, download lists
Description:
* add boot() function which waits for network. Interface to come up
* switch oisd.nl hosts entry to domains
* remove erroneous oisd substitution from config-update file
=> simple-adblock: update to 1.9.3-7

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.conf.update, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, download lists
Description:
* add boot() function which waits for network. Interface to come up
* switch oisd.nl hosts entry to domains
* remove erroneous oisd substitution from config-update file
(cherry picked from commit 8c8384611b0a8f5d9e6aca46e8cf72918c74198b)
=> [22.03] simple-adblock: update to 1.9.3-7

net/bind/Makefile, net/bind/files/named.init
Bug was introduced in a7b770eec4370087a5ccd27887386dac9266214e and results in bind always stating with the `-4` flag.
Signed-off-by: Rucke Teg <rucketeg@protonmail.com>
Compile tested: bcm2711, master
Run tested: bind starts without `-4` flag if ipv6 address is routable
=> bind: Fix ipv6 detection logic

lang/python/python-chardet/Makefile, lang/python/python-evdev/Makefile
Maintainer: me, @paulo-raca (co-maintainer for evdev)
Compile tested: x86 https://github.com/openwrt/openwrt/commit/059263dd6e9bed5cb0f817a9fe0bd287db921200
Run tested: x86 https://github.com/openwrt/openwrt/commit/059263dd6e9bed5cb0f817a9fe0bd287db921200
=> python-{chardet,evdev}: bump versions

utils/stress-ng/Makefile, utils/stress/Makefile, utils/stress/patches/010-usleep.patch
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/059263dd6e9bed5cb0f817a9fe0bd287db921200
Run tested: x86 https://github.com/openwrt/openwrt/commit/059263dd6e9bed5cb0f817a9fe0bd287db921200
=> stress/stress-ng: bump versions

net/dnscrypt-proxy2/Makefile
Compile tested: Linksys WRT32X / OpenWrt SNAPSHOT r21885-f86658e269 
Run tested: Linksys WRT32X / OpenWrt SNAPSHOT r21885-f86658e269 
Description: dnscrypt-proxy2: update to version 2.1.4
Signed-off-by: Fabian Lipken <dynasticorpheus@gmail.com>
=> dnscrypt-proxy2: update to version 2.1.4

lang/php8/Makefile
=> php8: update to 8.2.2

net/unbound/Makefile, net/unbound/patches/010-configure-uname.patch
Compile tested: Turris 1.1, mpc85xx/p2020, OpenWrt 21.02.5
Run tested: Turris 1.1, mpc85xx/p2020, OpenWrt 21.02.5
Release notes:
- https://www.nlnetlabs.nl/news/2023/Jan/12/unbound-1.17.1-released/
=> unbound: update to version 1.17.1

utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.16.0)
=> docker-compose: Update to version 2.16.0

net/gsocket/Makefile
Signed-off-by: Ralf Kaiser <skyper@thc.org>
Maintainer: Ralf Kaiser @SkyperTHC
Compile tested: mips_24kc, Openwrt 22.03.0-rc4
Run tested: mips_24kc
Description:
Global Socket allows two workstations on different private networks to
communicate with each other. Through firewalls and through NAT - like
there is no firewall.
The TCP connection is secured with AES-256 and using OpenSSL's SRP
protocol (RFC 5054). It does not require a PKI and has forward
secrecy and (optional) TOR support.
The gsocket tools derive temporary session keys and IDs and connect
two TCP pipes through the Global Socket Relay Network (GSRN). This is
done regardless and independent of the local IP Address or geographical
location.
The session keys (secrets) never leave the workstation. The GSRN sees only
the encrypted …
=> gsocket: upstream update to 1.4.39

lang/python/python-websocket-client/Makefile
=> python-websocket-client: update to 1.5.1

utils/irqbalance/Makefile, utils/irqbalance/patches/001-upstream-fix-aarch64-irq-parsing.patch
Add upstream fix for AARCH64 irq name parsing.
https://github.com/Irqbalance/irqbalance/pull/253
> On arm64 SoCs like TI's K3 SoC and few other SoCs,
> IRQ names don't get parsed correct due to which they
> end up being classified into wrong class. Fix this by
> considering last token to contain IRQ name always.
The fix seems to enable e.g. RT3200 to notice a few more interrupts and start balancing them.
Run tested: mt7622/RT3200
... PR for CI testing ...
=> irqbalance: Add upstream fix for AARCH64 irq name parsing

utils/conmon/Makefile
Description:
Update conmon to version 2.1.6
**Changes**
Bug fixes
- Fix OOM watcher for cgroupv2 oom_kill events
Misc
- Use --detach instead of -d
- ctrl: drop fifo perms to 0660
[Release notes](https://github.com/containers/conmon/releases/tag/v2.1.6)
=> conmon: update to 2.1.6

net/cloudreve/Makefile
Maintainer: me
Description:
Dropped architectures that are no longer supported[^1][^2] by upstream.
Release note:
- https://github.com/cloudreve/Cloudreve/releases/tag/3.7.0
- https://github.com/cloudreve/Cloudreve/releases/tag/3.7.1
[^1]: https://github.com/cloudreve/Cloudreve/issues/1640
[^2]: https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures
=> cloudreve: Update to 3.7.1

net/kcptun/Makefile, net/kcptun/files/kcptun.config, net/kcptun/files/kcptun.init
Maintainer: Dengfeng Liu <liudf0716@gmail.com>, Chao Liu <expiron18@gmail.com>
Compile tested: x86_64, OpenWrt 22.03-SNAPSHOT r19160+900-7ea2f3d6e2
Run tested: x86_64, OpenWrt 22.03-SNAPSHOT r19160+900-7ea2f3d6e2
Description:
add support for port-range dailer, port-range listener
=> kcptun: update to version 20230207

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf.update, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, config update, lists dl/process
Description:
* update default config for new oisd.nl lists
* conf.update file to migrate oisd.nl lists to the new format
* introduce AdBlockPlus lists support (new oisd.nl format)
* longer wait for WAN up/gateway detection
* make load_environemnt only execute once to suppress duplicate warnings/errors
PS. While I was testing this, oisd.nl has brought back the old domains
lists as well, so this version supports both as I'm unclear as to
why the "big" ABPlus list is only 6.2Mb where as the "big" domains
list is whopping 19.9Mb.
=> simple-adblock: update to 1.9.4-1

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf.update, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, config update, lists dl/process
Description:
* update default config for new oisd.nl lists
* conf.update file to migrate oisd.nl lists to the new format
* introduce AdBlockPlus lists support (new oisd.nl format)
* longer wait for WAN up/gateway detection
* make load_environemnt only execute once to suppress duplicate warnings/errors
PS. While I was testing this, oisd.nl has brought back the old domains
lists as well, so this version supports both as I'm unclear as to
why the "big" ABPlus list is only 6.2Mb where as the "big" domains
list is whopping 19.9Mb.
(cherry picked from commit …
=> [22.03] simple-adblock: update to 1.9.4-1

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, config update, lists dl/process
Description:
* implement procd_boot_wan_timeout support
* update config with oisd ABPlus and domains lists
=> simple-adblock: implement procd_boot_wan_timeout support

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, config update, lists dl/process
Description:
* implement procd_boot_wan_timeout support
* update config with oisd ABPlus and domains lists
(cherry picked from commit 587cd4d0d7dbce12b4ba031477739f070a7c5873)
=> [22.03] simple-adblock: implement procd_boot_wan_timeout support

net/kcptun/Makefile, net/kcptun/files/kcptun.config, net/kcptun/files/kcptun.init
Maintainer: Dengfeng Liu <liudf0716@gmail.com>, Chao Liu <expiron18@gmail.com>
Compile tested: x86_64, OpenWrt 22.03-SNAPSHOT r19160+900-7ea2f3d6e2
Run tested: x86_64, OpenWrt 22.03-SNAPSHOT r19160+900-7ea2f3d6e2
Description:
add support for port-range dailer, port-range listener
=> [22.03] kcptun: update to version 20230207

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, start/dl
=> simple-adblock: bugfix: ensure directory for jsonFile is created

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, start/dl
(cherry picked from commit 2bb10d0c2c9a2517acea9cadeaf2d390066f72f4)
=> [22.03] simple-adblock: bugfix: ensure directory for jsonFile is created

lang/python/django/Makefile
Fixes:
https://nvd.nist.gov/vuln/detail/CVE-2023-23969
=> [21.02] django: bump to version 3.2.18

lang/python/django/Makefile
Fixes:
https://nvd.nist.gov/vuln/detail/CVE-2023-23969
=> django: bump to version 4.1.7

lang/node/Makefile, lang/node/patches/003-path.patch
 Compile tested: 21.02, arm
 Run tested: (qemu 7.2.0) arm
Description:
Thursday February 16 2023 Security Releases
* CVE-2023-23918: Node.js Permissions policies can be bypassed via process.mainModule (High)
* CVE-2023-23920: Node.js insecure loading of ICU data through ICU_DATA environment variable (Low) More detailed information on each of the vulnerabilities can be found in February 2023 Security Releases blog post.
=> [21.02] node: bump to v14.21.3

lang/node/Makefile, lang/node/patches/003-path.patch
Compile tested: head, aarch64, arm, i386, x86_64, mipsel (pistachio) 
Run tested: (qemu 7.2.0) aarch64
Description:
Thursday February 16 2023 Security Releases
* CVE-2023-23918: Node.js Permissions policies can be bypassed via process.mainModule (High)
* CVE-2023-23919: Node.js OpenSSL error handling issues in nodejs crypto library (Medium)
* CVE-2023-23936: Fetch API in Node.js did not protect against CRLF injection in host headers (Medium)
* CVE-2023-24807: Regular Expression Denial of Service in Headers in Node.js fetch API (Low)
* CVE-2023-23920: Node.js insecure loading of ICU data through ICU_DATA environment variable (Low) More detailed information on each of the vulnerabilities can be found in …
=> node: bump to v16.19.1

net/transmission/files/transmission.init
Signed-off-by: Salim B <git@salim.space>
Maintainer: @dangowrt / CC: @neheb
Run tested: OpenWrt 22.03 snapshot
The transmission UCI config options
- `config_overwrite`
- `incomplete_dir_enabled`
- `watch_dir_enabled`
are all booleans, so we have to retrieve them using `config_get_bool` in order to make sure they are properly interpreted in case the user sets them to a keyword (`true`/`false`, `on`/`off` etc.) and not an integer (`0`/`1`), cf. https://openwrt.org/docs/guide-developer/config-scripting#reading_booleans
=> transmission: retrieve boolean config opts using `config_get_bool`

net/knot/Makefile
Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.2.4 (hbk)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.2.4 (hbk)
Description:
- Release upgrade (https://www.knot-dns.cz/2023-02-02-version-325.html)
=> knot: update to version 3.2.5

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.config, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, use https-dns-proxy for dns resolution
Description:
* config file update
* introduce boot() function
Signed-off-by: Stan Grishin [stangri@melmac.ca](mailto:stangri@melmac.ca)
=> https-dns-proxy: 2022-10-15-11 update

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.config, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, use https-dns-proxy for dns resolution
Description:
* config file update
* introduce boot() function
(cherry picked from commit 30aefce999bab3c24ce06594ee2f411cf2d8c72f)
=> [22.03] https-dns-proxy: 2022-10-15-11 update

.github/workflows/multi-arch-test-build.yml
backport of #17100 + #17105, with corrrected commit message prefixes (`CI:`)
=> backport artifact metadata generation to 21.02

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/share/ddns/default/easydns.com.json
easydns.com has supported IPv6 for awhile now using the same update URL as IPv4. This duplicates the IPv4 entry for IPv6 to enable support for it.
=> ddns-scripts: enable IPv6 for easydns.com

utils/miniflux/Makefile, utils/miniflux/files/miniflux.conf, utils/miniflux/files/miniflux.init
Maintainer: me
Description: add BASE_URL to the init script, this is useful when running in a subpath and not directly on the root of a domain
=> miniflux: update to 2.0.42

net/tor/Makefile
Maintainers: @hauke (Hauke Mehrtens) and @tripolar (Peter Wagner)
Build system: Arch Linux x86_64
Build tested: r7800 OpenWrt git master (r22104-01262c921c)
Run tested: r7800 OpenWrt git master (r22104-01262c921c)
=> tor: update to version 0.4.7.13

lang/node/Makefile, lang/node/patches/003-path.patch
Run tested: (qemu 7.2.0) arm
Description:
Thursday February 16 2023 Security Releases
* CVE-2023-23918: Node.js Permissions policies can be bypassed via process.mainModule (High)
* CVE-2023-23919: Node.js OpenSSL error handling issues in nodejs crypto library (Medium)
* CVE-2023-23936: Fetch API in Node.js did not protect against CRLF injection in host headers (Medium)
* CVE-2023-24807: Regular Expression Denial of Service in Headers in Node.js fetch API (Low)
* CVE-2023-23920: Node.js insecure loading of ICU data through ICU_DATA environment variable (Low) More detailed information on each of the vulnerabilities can be found in February 2023 Security Releases blog post. …
=> [22.03] node: bump to v16.19.1

lang/perl-www-curl/patches/230-curl_7.88_compat.patch, net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, use with https-dns-proxy
Description:
* https://curl.se/changes.html#7_88_1
=> curl: update to 7.88.1

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/share/ddns/default/njal.la.json, net/ddns-scripts/files/usr/share/ddns/list
Description: Add njal.la provider. Use the key as password. Username is not needed.
Maintainer: me / @chris5560
Compile tested: x86-64 (APU2), ath79 (Archer C7) 
Run tested: x86-64 (APU2)
Fixes https://github.com/openwrt/packages/issues/16311
Signed-off-by: Tobias Hilbig <web.tobias@hilbig-ffb.de>
=> ddns-scripts: Add njal.la provider

utils/sed/Makefile
Maintainer: @RussellSenior
Compile tested: aarch64 bananapi-r3 openwrt-git
Run tested: aarch64 bananapi-r3 openwrt-git
Description: sed has not depended on libpcre for a very long time from before sed 4.8 which was the first version added to OpenWrt
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=22801
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=22647
=> sed: remove old libpcre dependency

net/nfs-kernel-server/Makefile, net/nfs-kernel-server/patches/110-move-hardcoded-rundir.patch, net/nfs-kernel-server/patches/130-musl-svcgssd-sysconf.patch, net/nfs-kernel-server/patches/200-fix-macos-build.patch
Also added patch that is from alpine's same package to assist building on musl.
Some overrides for hostpkg configure were also necessary to make it possible to build **on** musl.
Maintainer: Peter Wagner / @tripolar 
=> nfs-kernel-server: update to v2.6.2

net/acme-common/Makefile, net/acme-common/files/acme.init
Description:
I'm not sure if directly writing to `$IPKG_INSTROOT/etc/crontabs/root` works. Will just leave uci-defaults alone for the time being. Using image builder is on my todo list tho, will update uci-defaults once I get to that.
=> acme: fix incompatibilty with image builder

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
Description: Update HAProxy to v2.6.9
- This release fixes a critial flaw known as CVE-2023-25725. See: http://git.haproxy.org/?p=haproxy-2.6.git;a=commit;h=73be199c4f5f1ed468161a4c5e10ca77cd5989d8
=> haproxy: update to v2.6.9

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
Description: Update HAProxy to v2.4.22
- This release fixes a critial flaw known as CVE-2023-25725. See: http://git.haproxy.org/?p=haproxy-2.4.git;a=commit;h=486cd730485c8a119ef65b3f792134b56e7941b4
=> haproxy: update to v2.4.22

net/sing-box/Makefile
Maintainer: me
Run tested: (x86_64, OpenWrt 22.03, tests done)
Description:
1. Add `kmod-inet-diag` as a dependency (https://github.com/openwrt/packages/pull/20486#issuecomment-1430610086)
2. Remove redundant `default n` (https://github.com/openwrt/packages/pull/20486#discussion_r1113008854)
=> sing-box: update to 1.1.6

utils/conmon/Makefile
- Fix leaking symbolic links in the opt_socket_path directory
- cgroup: Stumble on if we can't set up oom handling
=> conmon: update to 2.1.7

net/netbird/Makefile
Update from 0.12.0 -> 0.14.2
A lot of changes due to update of so many versions.
Release notes of all versions between 0.12.0 -> 0.14.2 is
available at https://github.com/netbirdio/netbird/releases
=> netbird: update to 0.14.2

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
Description: Update HAProxy to v2.2.29
- This release fixes a critial flaw known as CVE-2023-25725. See: http://git.haproxy.org/?p=haproxy-2.2.git;a=commit;h=4a4c90c2b04444d92c58873cfb19052f20280bc2
=> haproxy: update to v2.2.29

libs/tiff/Makefile
Commit 81d2b72 added a package providing libdeflate. Tiff by default links to it, causing a build error.
Package libtiff is missing dependencies for the following libraries: libdeflate.so.0
This commit forces libdeflate use off to avoid this. No revision bump is done because the package is currently not compiling anyway.
Compile tested: ath79 master
Description: fix current packaging issue
=> tiff: force libdeflate support to off

multimedia/yt-dlp/Makefile
Maintainer: me
Description: this release fixes throttling issues which is the reason for also backporting it to 22.03 in #20612, 21.02 doesn't have yt-dlp
=> yt-dlp: update to 2023.3.4

lang/lua-eco/Makefile
Signed-off-by: Jianhui Zhao [zhaojh329@gmail.com](mailto:zhaojh329@gmail.com)
Maintainer: me
Description:
Release notes for 2.1.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.1.0
=> lua-eco: update to 2.1.0

net/samba4/Makefile, net/samba4/patches/021-source4-msgsock-nvram-fix.patch
* update to 4.17.5
* changelog: https://www.samba.org/samba/history/samba-4.17.5
* refresh patch
* CVE-2022-42898: Samba's Kerberos libraries and AD DC failed to guard against integer overflows when parsing a PAC on a 32-bit system, which allowed an attacker with a forged PAC to corrupt the heap. https://www.samba.org/samba/security/CVE-2022-42898.html
* CVE-2022-37966: This is the Samba CVE for the Windows Kerberos RC4-HMAC Elevation of Privilege Vulnerability disclosed by Microsoft on Nov 8 2022.
A Samba Active Directory DC will issue weak rc4-hmac session keys for use between modern clients and servers despite all modern Kerberos implementations supporting the aes256-cts-hmac-sha1-96 cipher.
On Samba Active Directory DCs and members 'kerberos encryption types = legacy' would force …
=> samba4: update to 4.17.5

net/cni-protocol/Makefile, net/cni-protocol/files/cni.sh
simple protocol support script for netifd.
netifd protocol support for cni networks makes
defining network for podman and other similar
systems using cni networking much easier and simpler.
with cni protocol support, on a cni network, where firewall and portmapper is disabled, you may control firewalling with openwrt's standard firewall configuration.
for example, create a container that hosts web content on port 80 with static ip on your cni network, if your network is 10.88.0.0/16, use for eg. 10.88.0.101 as your containers static ip address. Create a zone, cni to your firewall and add your interface to it. You could manage all this without protocol support, but this makes it a bit easier, especially when this is requirement for my upcoming luci protocol support for same thing- so no …
=> cni-protocol: new package

net/udp-broadcast-relay-redux-openwrt/Makefile, net/udp-broadcast-relay-redux-openwrt/files/udp-broadcast-relay-redux.init
Maintainer:  @accwebs 
Compile tested: None, modified directly on my filesystem
Run tested: openwrt 22.03.3 ipq806x generic netgear_r7800
Description:
Added `cgroupsns` to jail, otherwise you get this failure:
```
Mon Mar  6 14:46:05 2023 user.err : jail: Not using namespaces, capabilities or seccomp !!!
```
Error is here, seems to indicate that we're running a jail without using any capability. https://lxr.openwrt.org/source/procd/jail/jail.c#L2847
Decided to use minimal effort approach
**Before:** Service "started successfully" and showed as "running", but `ps |grep udp` showed nothing, and actual packet forwarding didn't happen. Mentioned error message was logged on `logread -f`
**After:** Service works.
Modified this locally on my router, works well.
=> udp-broadcast-relay-redux-openwrt: add cgroupsns to jail

lang/lua-eco/Makefile
Signed-off-by: Jianhui Zhao [zhaojh329@gmail.com](mailto:zhaojh329@gmail.com)
Maintainer: me
Description:
Release notes for 2.2.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.2.0
=> lua-eco: update to 2.2.0

lang/rust/Config.in, lang/rust/Makefile, lang/rust/maturin/Makefile, lang/rust/patches/0001-Update-xz2-and-use-it-static.patch, lang/rust/rust-host.mk, lang/rust/rust-package.mk, lang/rust/rust_config.mk, utils/ripgrep/Makefile
A rebase and then rework of #13916 with the current stable rust.
=> Another attempt to support the rust language

libs/libgpiod/Makefile
Maintainer: me
Description:
This updates this library to the latest major version.
For the Python binding switch to the Py3Package infrastructure.
And while at, also introduce the C++ binding, too.
=> libgpiod: update to 2.0 and introduce C++ binding

libs/icu/Makefile
Maintainer: me 
Compile tested: head, aarch64 
Run tested: aarch64 (qemu 7.2.0)
Description:
fix build error with ccache:
https://github.com/openwrt/packages/issues/20618
=> icu: fix ccache issue

net/netifyd/Makefile
Maintainer: Darryl Sokoloski / @dsokoloski
Compile tested: arm_cortex-a15_neon-vfpv4, TP-Link Archer C2600, master
Run tested: TP-Link Archer C2600
- Properly handle interface down events for PCAP capture threads.
- Don't flag the category JSON file as a configuration file.
- Don't clear device addresses until afer plugins have been called.
- Enabled application lookups for DNS hostnames.  IP-block lookups for DNS addresses remains disabled (https://gitlab.com/netify.ai/public/netify-agent/-/issues/57).
- Fixed duplicate risks being added to DNS flows (after a reset).
- Fixed bug where custom domains were not being searched (walked) properly.
- Fixed early DNS/LLMNR packet processing.
- Throw exception instead of silently ignoring invalid bucket IDs.
- Fixes for builds with plugin and/or …
=> netifyd: update to v4.4.1

lang/perl-www-curl/patches/230-curl_7.88_compat.patch, net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-105w, OpenWrt 22.03.3, use with https-dns-proxy
Description:
* https://curl.se/changes.html#7_88_1
(cherry picked from commit 678bad7e86c51aa96dc2f9336f7ff32b19c6de99)
=> [22.03] curl: update to 7.88.1

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Compile tested: x86_64, Sophos XG-105wr2, OpenWrt 22.03.3
Run tested:  x86_64, Sophos XG-105wr2, OpenWrt 22.03.3, install/start/stop
Description:
* move network.sh and jshn.sh includes into load_validate_config function to prevent errors when adding the package to image with the Image Builder
* add @bongochong compressed domains block-list to the config
=> simple-adblock: update init file and config

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Compile tested: x86_64, Sophos XG-105wr2, OpenWrt 22.03.3
Run tested: x86_64, Sophos XG-105wr2, OpenWrt 22.03.3, install/start/stop
Description:
* move network.sh and jshn.sh includes into load_validate_config function to prevent errors when adding the package to image with the Image Builder
* add @bongochong compressed domains block-list to the config
(cherry picked from commit 35f4830de79f332dd532fcb26e704d1356f99c94)
=> [22.03] simple-adblock: update init file and config

utils/lolcat/Makefile
Bump to the latest stable release.
=> lolcat: update to version 1.4

net/snort3/Makefile
=> snort3: update to 3.1.56.0

libs/libdaq3/Makefile
=> libdaq3: update to 3.0.11

net/strongswan/Makefile, net/strongswan/patches/0905-undef-wolfssl-RNG.patch
Compile tested: x86_64, generic, HEAD (fb15cb4ce95)
Description:
Update to version 5.9.9.
=> strongswan: Update to 5.9.9

.github/workflows/multi-arch-test-build.yml
Run tested: CI
Description:
- Removed arc_archs - archs38 was marked as source-only [^1].
- Renamed powerpc_8540 to powerpc_8548 [^2].
[^1]: https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=c01641bcc7236d2e2de3ea65444b0cf2898df351
[^2]: https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=2cad88b99fdae9766de84e6c1cb56f111eb53748
=> CI: update build architectures

net/zerotier/Makefile, net/zerotier/patches/0001-fix-makefile.patch
Maintainer: me
Compile tested: ramips/mt7620, Nexx wt3020, OpenWrt master
Run tested: ramips/mt7620, Nexx wt3020, OpenWrt master
Tested: ZeroTier starts
Description:
Minor changes: https://github.com/zerotier/ZeroTierOne/blob/dev/RELEASE-NOTES.md
=> zerotier: update to 1.10.4

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/share/ddns/default/mythic-beasts.com-v2.json, net/ddns-scripts/files/usr/share/ddns/list
Use USERNAME as the key, PASSWORD as the secret.
Mythic Beasts API v1 is still available, but v2 use is encouraged.
Maintainer: ?
Compile tested: ipq806x (Archer C2600)
Run tested: ipq806x (Archer C2600)
=> ddns-scripts: Add v2 API for mythic-beasts.com provider

libs/sqlite3/Config-lib.in, libs/sqlite3/Makefile
Description:
Removed `SQLITE3_JSON1` option as it was dropped by upstream.
=> sqlite3: Update to 3.41.1

libs/libjpeg-turbo/Makefile
Allow build of libjpeg as a static library as well; one is provided for libpng and possibly for other
formats as well.
Maintainer: Rosen Penev / @neheb
Description:
I have a application that can draw graphical content to frame buffer, including few image formats and
jpg is amongst supported formats. As software is meant for displaying a _boot splash_ and started early
from initrd, static linking is encouraged. But this would require static archive from libjpeg to be possible.
Static archive is not added to package, only to development libraries by this PR.
=> libjpeg-turbo: enable static library building

net/zerotier/Makefile
zerotier has executable stack.
`
[   11.343143] process '/usr/bin/zerotier-one' started with executable stack
`
executable stacks are not recommend, possibly provide a threat and there seems to be no real advantage of executable stack with zerotier - so let's build it without instead.
Some chatter about [executable stacks](https://security.stackexchange.com/questions/210785/how-and-why-is-executable-stack-dangerous) and a older feature request on [same subject](https://github.com/zerotier/ZeroTierOne/issues/1179) at zerotier's repository for reference.
Maintainer: Moritz Warning / @mwarning
=> zerotier: do not allow executable stack

net/miniupnpd/Makefile
Maintainer: NA
Run tested: NA
Untested as I don't run 22.03. CI should do compile tests, and if someone who does run 22.03 would be so kind to test this and report back, that would be appreciated.
=> miniupnpd: bump to 2.3.3

lang/php8/Makefile
Maintainer: me
Run tested: -
Description:
This fixes:
- CVE-2023-0567
- CVE-2023-0568
- CVE-2023-0662
=> php8: update to 8.2.3

lang/php8/Makefile
Maintainer: me
Run tested: -
Description:
This fixes:
- CVE-2023-0567
- CVE-2023-0568
- CVE-2023-0662
=> [22.03] php8: update to 8.1.16

lang/php8/Makefile
Maintainer: me
Run tested: -
Description:
This fixes:
- CVE-2023-0567
- CVE-2023-0568
- CVE-2023-0662
=> [21.02] php8: update to 8.0.28

lang/golang/golang-values.mk, lang/golang/golang/Makefile
Maintainer: me
Compile tested: none (cherry picked from #20661)
Description:
Includes fix for CVE-2023-2453 (crypto/elliptic: specific unreduced P-256 scalars produce incorrect results).
This also includes makefile updates for Go 1.19.
(cherry picked from commit 8677ed11e30b78de526dfacca58f24e041ff7833)
=> [openwrt-22.03] golang: Update to 1.19.7

multimedia/yt-dlp/Makefile
Maintainer: me
Description: this release fixes throttling issues which is the reason for also backporting it to 22.03, 21.02 doesn't have yt-dlp
=> [22.03] yt-dlp: update to 2023.3.4

net/git/Makefile, net/git/patches/100-configure_for_crosscompiling.patch, net/git/patches/200-imapsend_without_curl.patch, net/git/patches/300-openssl-deprecated.patch
Run tested: armv7l, Turris Omnia, OpenWrt 21.02, tested git clone and gitweb
Description: GITWEB_* variable values don't work as they should since 2.38, so let's remove them and add a workaround. This issue was reported in https://lore.kernel.org/git/80eb3972-4960-5727-ce86-acc3a4425fd4@nic.cz/T/#u
earlier today I opened #20506 which is a small security update, this PR replaces it, but I will leave whether you choose to merge the small security update first and then this one or merge this PR and close the small security update to you.
=> git: update to 2.39.2

net/strongswan/Makefile, net/strongswan/patches/730-strongswan-5.1.0-5.9.7_cert_online_validate.patch
Maintainer: @pprindeville || @stintel
Run tested: X86_64, APU3, branch openwrt-22.03
Description:
Add backport fix for the following CVE:
[CVE-2022-40617](https://www.strongswan.org/blog/2022/10/03/strongswan-vulnerability-(cve-2022-40617).html)
=> strongswan: backport CVE fix

net/openssh/Makefile
Description:
Version bump to 9.3p1
=> openssh: update to 9.3p1

libs/rpcsvc-proto/Makefile
After recent autotools update, rpcsvc-proto no longer compiles without autoreconf fixup because automake 1.15 is not found.
Maintainer: Rosen Penev / @neheb
Description:
latest version of open-vm-tools 12.2.0 needs rpcgen provided by this package which did not build.
@neheb mentioned as maintainer as package does not have maintainer but has been doing merges for this.
=> rpcsvc-proto: fix build with updated autotools

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
Description: Update HAProxy to v2.6.10
- See changes: http://git.haproxy.org/?p=haproxy-2.6.git;a=shortlog
=> haproxy: update to v2.6.10

libs/pcre2/Makefile, net/gensio/Makefile, utils/swig/Makefile
Issue reporter:  @jefferyto 
Maintainer: @InBetweenNames (pcre2), @nxhack + @blogic (swig), @WereCatf (gensio)
Run tested: mxs, Duckbill - only a basic Python module import with output of version string
Description:
As reported in #20604, the python3-gensio package cannot be built at the moment due to missing pcre support in swig.
This PR thus adds a host build for pcre as proposed by @jefferyto, it modifies the swig package to use it and finally adjusts the gensio package itself slightly.
=> gensio: fix python bindings build by using a pcre enabled host swig (fixes #20604)

utils/collectd/Makefile
Description:
Per
https://github.com/openwrt/packages/pull/19396#issuecomment-1480780893
prefix ltq-dsl-app with a @ character to fix the compilation issues witnessed in PR #19396 and #20662
Compile tested: x86_64, git master
Run tested: No
=> collectd: Fix ltq-dsl compilation errors

utils/syncthing/Makefile
Compile tested: ipq807x/generic
Description:
Fixed build with go 1.20
=> syncthing: Update to 1.23.2

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
Description: Update to v2.6.11
- This release includes a fix for an OOB write. The official notes do not list a CVE entry but I guess there is a chance for security implications
- See changes: http://git.haproxy.org/?p=haproxy-2.6.git;a=shortlog
=> haproxy: update to v2.6.11

net/samba4/Makefile, net/samba4/patches/009-samba-4-11-fix-host-tools-checks.patch.patch, net/samba4/patches/021-source4-msgsock-nvram-fix.patch, net/samba4/patches/102-samba-4.11-unbundle-libbsd.patch
Compile tested: Mediatek mt7622, Totolink A8000RU
Run tested:
Description: Update the Samba package to version 4.18.0
Samba release history: https://www.samba.org/samba/history/samba-4.18.0.html
=> Samba4:  Update to version 4.18.0

net/netbird/Makefile
Release Notes
Management
- Introduce a new ACL engine based on Rego (Open Policy Agent) for firewall control
- Personal access tokens generation as a first iteration toward public API release
- Add Keycloak support as an IDP manager
Agent
- Introduce a Firewall interface to apply granular access control (e.g., connection direction, port, or protocol level)
- Make the agent run on Android (mobile support)
Changelog
- Feat rego default policy
- Don't drop Rules from file storage after migration to Policies
- Add version info command to signal server
- Feat firewall controller interface
- Adding Personal Access Token generation
- Exchange proxy mode via signal
- Fix connstate indication
- Mobile
- PAT persistence
- Add Keycloak Idp Manager
- Adjustments for the change server flow
- Disable …
=> netbird: update to 0.14.5

net/sing-box/Makefile
Maintainer: me
Description:
Bug fixes. Refer to https://github.com/SagerNet/sing-box/releases/tag/v1.2.1.
=> sing-box: update to 1.2.1

net/natmap/Makefile, net/natmap/files/natmap.config
Maintainer: @ysc3839 
Description:
1. update to 20230322
2. update stun server address
=> natmap: update to 20230322

net/curl/Config.in, net/curl/Makefile
- changed Config.in to enable unix sockets support by default
- release number bumped
Maintainer: Stan Grishin / @stangri 
Description:
socket support is very handy when communicating with
various REST APIs.
Size increases are very small, nearly unnoticiable.
Tested-by: Stan Grishin <stangri@melmac.ca>
=> curl: enable unix sockets by default

utils/gummiboot/Makefile, utils/gummiboot/patches/015-gummiboot-aarch64-support.patch
New version contains mostly bug fixes.
Full list of changes: https://cgit.freedesktop.org/gummiboot/log/
Description:
Remove $(AUTORELEASE)
Also disable man page generation, fixes building on host without necessary utils for generating man pages.
=> gummiboot: update to 48.1

net/natmap/Makefile, net/natmap/files/natmap.config
Compile tested: ramips-mt7621, 22.03
Description:
1. update to 20230322
2. update stun server address
=> [22.03] natmap: update to 20230322

net/transmission-web-control/Makefile
Transmission 4.0 web interface files changed from /web to /public_html
This fixes https://github.com/openwrt/packages/issues/20737
Run tested: Netgear Nighthawk X4S R7800, OpenWrt SNAPSHOT r22310
=> transmission-web-control: fix web interface files path

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
Description: Update to v2.6.12
- See changes: http://git.haproxy.org/?p=haproxy-2.6.git;a=shortlog
=> haproxy: update to v2.6.12

lang/golang/golang-compiler.mk, lang/golang/golang-values.mk, lang/golang/golang/Makefile, lang/golang/golang/patches/001-cmd-link-use-gold-on-ARM-ARM64-only-if-gold-is-available.patch
Maintainer: me
Compile tested: armvirt-32, 2023-03-13 snapshot sdk; armvirt-64/malta-be, 2023-03-05 snapshot sdk
Run tested: armvirt-32, 2023-03-13 snapshot; armvirt-64/malta-be, 2023-03-05 snapshot
Description:
Includes fixes for:
* 1.20.1:
* CVE-2022-41722: path/filepath: path traversal in filepath.Clean on Windows
* CVE-2022-41723: net/http: avoid quadratic complexity in HPACK decoding
* CVE-2022-41724: crypto/tls: large handshake records may cause panics
* CVE-2022-41725: net/http, mime/multipart: denial of service from excessive resource consumption
* 1.20.2:
* CVE-2023-24532: crypto/elliptic: specific unreduced P-256 scalars produce incorrect results
=> golang: Update to 1.20.2, refresh patch

.github/workflows/entrypoint.sh
Description:
836b4e1c734f9705bfd8db0da0c04214c2647932 added `--force-removal-of-dependent-packages` but it does not do what the commit message says it does.
When package A depends on package B (package B is a dependency of package A; package A is a dependent of package B), trying to remove package B while package A is installed will result in an error. Adding `--force-removal-of-dependent-packages` in this case will cause the removal of package B and package A (package B's dependent).
But in the case of the CI testing step, it is package A that is being installed and removed. Removing package A with
`--force-removal-of-dependent-packages` will not cause package B (package A's dependency) to be removed.
This …
=> CI: Add --autoremove, ignore removal errors

lang/python/python-aio-mqtt-mod/Makefile, lang/python/python-ble2mqtt/Makefile, lang/python/python-bleak/Makefile, lang/python/python-dbus-fast/Makefile
Compile tested: Unfortunately not (I tried without success to build this out on my machine but I think this is more of a failure in my setup.)  Hopefully CI will test this.
Run tested: Unfortunately not
Description: [ble2mqtt](https://github.com/devbis/ble2mqtt) is an interesting python package unfortunately it requires [Bleak](https://github.com/hbldh/bleak) which requires [dbus-fast](https://github.com/Bluetooth-Devices/dbus-fast) and this latter package cannot be successfully installed on a router with 128MB of RAM using pip (it runs out of memory and crashes).  This PR packages the dependencies for ble2mqtt but dbus-fast is the priority here.
=> Package dependencies for ble2mqtt python package

net/snort3/Makefile
=> snort3: update to 3.1.58.0

net/curl/Makefile
Maintainer: me
Compile tested: x86-64, Sophos XG-135r3, OpenWrt 22.03.3
Run tested: x86-64, Sophos XG-135r3, OpenWrt 22.03.3, test functionality with `https-dns-proxy`
Description:
* https://curl.se/changes.html#8_0_1
=> curl: update to 8.0.1

lang/rust/Makefile, lang/rust/rust-package.mk, lang/rust/rust-values.mk
also add new variable CARGO_VARS to make it possible to pass environment variables for cargo process.
This is necessary when for example, cross-compiling netavark.
Maintainer: Luca Barbato / @lu-zero 
Description:
example of CARGO_VARS usage is available [here](https://github.com/oskarirauta/openwrt-rust/blob/main/net/netavark/Makefile) -  netavark requires pointing protoc binary to it (staging_dir/hostpkg/bin/protoc) as environment value PROTOC.
=> rust: update to 1.68.1

multimedia/ffmpeg/Makefile
Maintainer: @antonlacon, @thess 
Compile tested: OpenWrt 21.02.5, mvebu - cortexa9 - Turris Omnia
Fixes: [CVE-2020-21041](https://nvd.nist.gov/vuln/detail/cve-2020-21041)
=> [21.02] ffmpeg: update to version 4.3.5

lang/rust/Makefile
Maintainer: me / @lu-zero
Compile tested: master aarch64
Description: Version bump
=> rust: update to 1.68.2

utils/pax-utils/Config.in, utils/pax-utils/Makefile
Description:
A suite of ELF tools to aid auditing systems.
Contains various ELF related utils for ELF32, ELF64 binaries useful for displaying PaX and security info on a large groups of binary files.
=> pax-utils: add new package

libs/openblas/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/0eebc6f0ddb0791406d30530e3fc25d39428bd5a
Run tested: x86 https://github.com/openwrt/openwrt/commit/0eebc6f0ddb0791406d30530e3fc25d39428bd5a
=> openblas: bump to version 0.3.23

utils/stress-ng/Makefile, utils/stress-ng/patches/001-disable-gpu-stressor.patch, utils/stress-ng/patches/002-disable-xxhash.patch
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/0eebc6f0ddb0791406d30530e3fc25d39428bd5a
Run tested: x86 https://github.com/openwrt/openwrt/commit/0eebc6f0ddb0791406d30530e3fc25d39428bd5a
=> stress-ng: bump to version 0.15.06

utils/squashfs-tools/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/0eebc6f0ddb0791406d30530e3fc25d39428bd5a
Run tested: x86 https://github.com/openwrt/openwrt/commit/0eebc6f0ddb0791406d30530e3fc25d39428bd5a
Also, enable xattr support.
=> squashfs-tools: bump to version 4.6.1

net/strongswan/Makefile
Compile tested: x86_64, generic, HEAD (c98e09f01b)
Run tested: same, deployed on production router
Description:
Fixes CI/CD build issues on GitHub.
=> strongswan: Fix CI/CD complaints about kmod dependencies

net/isc-dhcp/Makefile
Maintainer: me
Compile tested: x86_64, generic, HEAD (c98e09f01b)
Run tested: same, deployed on production router
Description:
Fixes CVE-2022-2928 and CVE-2022-2929
=> isc-dhcp: Update to 4.4.3-P1

net/snort3/Makefile
=> snort3: update to 3.1.59.0

lang/python/python-ble2mqtt/Makefile, lang/python/python-ble2mqtt/files/ble2mqtt.init, lang/python/python-bleak/Makefile
Maintainer: me
Compile tested: ath79 22.03.3 SDK
Run tested: Netgear r6260 snapshot successfully run ble2mqtt as a daemon and collected data over BLE.
Description:
Follow up to #20633.  This bumps the version of Bleak to get a bugfix, adds a missing dependency to ble2mqtt and also adds an init script (from the upstream README) to the ble2mqtt package.
=> Python ble2mqtt

net/sscep/Makefile, net/sscep/test.sh
Maintainer: @johnfzc
Compile tested: rampis, glinet_gl-mt300n-v2, 22.03.3
Run tested: rampis, glinet_gl-mt300n-v2, 22.03.3
Description: SSCEP client from certnanny, it was previously packaged in OpenWrt and removed at some point, I've been maintaining it outside of the tree since.
=> sscep: add package

net/apinger/Makefile, net/apinger/files/apinger-hotplug, net/apinger/files/apinger.config, net/apinger/files/apinger.init, net/apinger/files/apinger.rpc, net/apinger/files/graphs.sh, net/apinger/files/iface.hotplug, net/apinger/files/user.hotplug, net/apinger/patches/030-apinger-no_exit.patch, net/apinger/patches/040-srcip.patch, net/apinger/patches/050-statusformat.patch, net/apinger/patches/060-format-alarm-list.patch
@jempatel  @jow- @samm-git 
The LuCI app luci-app-apinger was recently backported&cherry-picked to 22.03 by @jow- , but that LuCI app apparently requires the apinger-rrd that does not exist in 22.03.  
(discussion in https://forum.openwrt.org/t/luci-app-apinger-in-22-03/156835 ) 
Cherry-pick the apinger-rrd commit from master, and also the preceding procd conversion by @jempatel as the rrd commit might build on that for some extent.
Would be great if somebody really using apinger would run-test it in 22.03
Maintainer: @samm-git 
Compile tested: CI testing in this PR
Run tested: -
=> Apinger: backport apinger-rrd and the procd conversion to 22.03

lang/node/Makefile, lang/node/patches/999-localhost-no-addrconfig.patch, lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch
Compile tested: head, aarch64, arm, i386, x86_64, mipsel (pistachio) 
Run tested: (qemu 7.2.0) aarch64
Description:
Update to v18.16.0
Fixed a bug when selecting arm-fpu for vfpv3-d16.
Add initial support for single executable applications 
Replace url parser with Ada
=> node: bump to v18.16.0

lang/ruby/Makefile, lang/ruby/patches/100-musl.patch
Maintainer: me
Compile tested: no (22.03 cannot be built in too recent machines)
Run tested: no
Description:
=> [22.03] ruby: update to 3.0.6

libs/boost/Makefile
Compile tested: bcm27xx (bcm2711) - used development snapshot from the 17th of April.
Description:
This commit updates boost to version 1.82.0
A new header-only library is available:
- MySql: a C++11 client for the MySQL database server, based on Boost.Asio, from Ruben Perez. [[1]]
More info about Boost 1.82.0 can be found at the usual place [[2]].
[1]: https://www.boost.org/doc/libs/1_82_0/libs/mysql/doc/html/index.html
[2]: https://www.boost.org/users/history/version_1_82_0.html
Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>
=> boost: Updates package to version 1.82.0

net/curl/Makefile
Maintainer: me
Compile tested: x86-64, Sophos XG-135r3, OpenWrt 22.03.3
Run tested: x86-64, Sophos XG-135r3, OpenWrt 22.03.3, test functionality with https-dns-proxy
Description:
* https://curl.se/changes.html#8_0_1
(cherry picked from commit 5640b7c94a6b90a2563c072b6080793f5fd86a1c)
=> [22.03] curl: update to 8.0.1

net/knxd/Makefile, net/knxd/patches/0100-version.patch
Maintainer: me
Description:
new upstream release
=> knxd: bump to new upstream release 0.14.58

net/bind/Makefile
Run tested: -
Description: the libmaxminddb package recently added a pkgconfig file which caused the geoip feature to be enabled automatically and the package to fail when it has a new unexpected dependency
=> [21.02] bind: disable geoip because of maxminddb dep

net/lighttpd/Makefile
Description:
* fix package DEPENDS syntax  (follow-up from #20799)
* adjust packages for built-in modules (save some disk space)
@1715173329 I believe this addresses issues uncovered in #20799 and is compatible with 21.02 and 22.03 branches.
Reviewing tmp/.packageinfo looks better to me.
=> lighttpd: fix package DEPENDS syntax

net/nginx/Config_ssl.in, net/nginx/Makefile
Split DAV_EXT from standard nginx DAV config as additional WebDAV methods are provided by an external module.
---
Maintainer: me
=> nginx: split DAV_EXT from standard nginx DAV config

.github/workflows/entrypoint.sh, .github/workflows/multi-arch-test-build.yml
Maintainer: ping @aparcar @neheb @BKPepe @1715173329 
Compile tested: PRs in my fork (with dummy packages to test the Test via Docker step: https://github.com/jefferyto/openwrt-packages/actions/runs/4739914724/jobs/8415178055?pr=9)
Description:
To test each package, the CI-built target package (ipk) file is installed, but currently the target package's dependencies are installed from the standard opkg feeds.
There are cases when the CI-built target packages should be installed/tested together:
* If a pull request contains several new packages that depend on each other, the test step will fail as the new dependencies cannot be found in the current packages feed.
* If a pull request upgrades a source package that builds several target packages that depend on each other, the …
=> CI: Add local feed for CI-built packages

utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream update. [Release notes](https://github.com/docker/compose/releases/tag/v2.17.3).
=> docker-compose: Update to version 2.17.3

net/strongswan/Makefile, net/strongswan/files/swanctl.init
Compile tested: x86_64, generic, HEAD (c3cb2d48da)
Description:
Drop remnants of rewrite of `ipsec.init`.
=> strongswan: local_gateway unused in swanctl.init

net/snort3/Makefile
=> snort3: update to 3.1.60.0

net/strongswan/Makefile
Compile tested:  x86 22.03.3
Run tested: x86 22.03.3
Without nonce, charon won't start, so it's not an optional plugin. I asked one of the strongSwan maintainers (ecdsa), and he confirmed this:
> It definitely has to be enabled unconditionally. The only other
> provider for the NONCE_GEN plugin feature is in charon-tkm, so
> completely irrelevant on OpenWrt
=> strongswan: enable nonce unconditionally

net/strongswan/Makefile
Compile tested: x86-64 22.03.3
Run tested: x86-64 22.03.3
Description:
Without these charon will warn with messages like:
```
plugin 'kdf': failed to load - kdf_plugin_create not found and no plugin file available
plugin 'drbg': failed to load - drbg_plugin_create not found and no plugin file available
```
=> strongswan: add missing PKG_MOD_AVAILABLE

net/openssh/Makefile
Compile tested: x86-64 22.03.3
Run tested: x86-64 22.03.3
Description:
The root user is usually the user that clients ssh into with, so in most cases its authorized_keys determines what clients are allowed to ssh into this device. Without preserving this file, they could potentially be locked out after upgrading.
=> openssh: preserve authorized_keys

lang/python/python3-find-stdlib-depends.sh
Maintainer: me
Run tested: tested with borgbackup package
Description:
This updates the python3-find-stdlib-depends.sh script for these changes:
* The gdbm (dbm.gnu) package was merged into the dbm package in 78f6c2c5ad2fd3de8a33a1cddb02204177cf60ad.
* The uuid module was split into a separate package in 4e05541782edeb06b51d691dadf52648df24c940.
=> python: Update find stdlib script

lang/ruby/Makefile, libs/yaml/Makefile
Ruby uses extensions (.so files) that might also depend on other libraries. When the linker builds an executable, it will refer to the path it found the library, including those in the stagging dir. However, when it links a shared library (like ruby exts), it will let that dependency to be resolved at runtime.
During host and target build, ruby build script runs ruby scripts. When it loads a ext that depends on another library, it will, by default, look for the system libraries to satisfy that, breaking the build when it fails. Setting LD_LIBRARY_PATH to the stagging lib dir is a valid workaround.
Ruby can also be built statically linking all exts into ruby executable. That will make the linker point to the stagging library path, fixing the issue. It was used in the past but, at some …
=> ruby: statically link extensions into host ruby

utils/kmod/Makefile
Kmod does not comile anymore with latest autotools update. Update to a
more recent version. Version 30 does not compile either, so use 29.
Import a patch to fix compiling without gtkdocize.
Maintainer: @jdub @neheb 
=> kmod: update to 30

net/iperf3/Makefile
Release Notes:
https://software.es.net/iperf/news.html#iperf-3-13-released
Maintainer: @nbd
Run tested: Linksys E8450 (OpenWrt Snapshot)
=> iperf3: update to 3.13

net/acme-common/Makefile
Compile tested: x86-64 master
Run tested: x86-64 master
Description:
opkg runs uci-defaults if a package installs one, in acme-common's case that's identical to postinst.
prerm shouldn't be run by the image builder, so it's unnecessary to check IPKG_INSTROOT
=> acme: remove redundant postinst

net/libreswan/Makefile
=> libreswan: update to 4.10

utils/restic/Makefile
Maintainer: Tom Stöveken <tom@naaa.de>
Compile tested: SDK for OpenWrt 22.03.4
Run tested: x86/64 @ Intel(R) Celeron(R) CPU N3160 @ 1.60GHz, OpenWrt 22.03.4
Description:
Updated to version 0.15.2
=> restic: update to 0.15.2

lang/python/python-eventlet/Makefile
old eventlet is not working well with python3.10
```
root@turris:~# python3
Python 3.10.9 (main, Feb  9 2023, 10:37:45) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
File "/usr/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
File "/usr/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
File "/usr/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
File "/usr/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
File …
```
=> python-eventlet: bump to version 0.33.3

net/samba4/Config.in, net/samba4/Makefile
Maintainer: nobody?
Description:
I was trying to solve [this issue](https://bugzilla.samba.org/show_bug.cgi?id=10541) which showed up in my btrfs backed shares when they were accessed from a MacOS client.
Upon checking out samba's repo, it became clear the issue was within quotas and that they were opt in. After that I checked whether I could disable them in OpenWrt and that's when I saw we had them coupled to the VFS modules.
Turns out quotas can be disabled entirely, indeed solving the issue, and VFS modules are not affected, they get built, installed and can be used without issues. To my surprise, I could not only enable back a TimeMachine share I had and use it without the logs being flooded, but I also could keep the `fruit:time …
=> samba4: decouple quotas from vfs option

net/lighttpd/Makefile, net/lighttpd/patches/030-meson-check-FORCE_._CRYPTO.patch, net/lighttpd/patches/031-mod_mbedtls-check-MBEDTLS_DEBUG_C.patch, net/lighttpd/patches/032-meson-build-fix-for-builtin_mods.patch
Description:
build fixes for lighttpd meson
One recently reported issue: https://forum.openwrt.org/t/bpi-r3-issue-install-lighttpd/158867
=> lighttpd: build fixes

utils/zoneinfo/Makefile
Maintainer: @Wedmer 
Compile tested: ipq807x/DL_WRX36
Run tested: CI
Based on forum discussions every now and then, it seems that the zoneinfo packages are not quite clear and thier usage is not straightforward. E.g. https://forum.openwrt.org/t/php8-cli-timezone-database-segfault-at-34/152342/6 . Our structure has been mostly unchanged since 2015 (or even earlier), and the IANA timezone database and abbreviations have evolved since then.
Tweak the zoneinfo package to better match the current file structure in the upstream time zone database. Add missing aliases. Make some clarifications.
* Combine -northmerica and -southamerica into -america, as all current official America/xxx definitions were already in -northamerica and only the unofficial/deprecated Brazil/xxx, Chile and Argentina …
=> zoneinfo: adjust to current timezone data file structure

net/openssh/files/sshd.init
Configure the openssh server to respawn. Reload by sending SIGHUP
Maintainer: @SibrenVasse 
Description:
Improvements to the OpenSSH init script. Respawning is added so that the OpenSSH server gets restarted in case it crashes. Reloading is implemented by sending SIGHUP to the OpenSSH server process. Before it would not re-read for example /etc/ssh/sshd_config when "/etc/init.d/sshd reload" was run.
=> openssh: add respawn and reloading via signal

lang/python/python-calver/Makefile, lang/python/python-hatchling/Makefile, lang/python/python-trove-classifiers/Makefile
Maintainer: me
Compile tested: armvirt-32, 2023-04-10 snapshot sdk
Description:
hatchling 1.14.0 added trove-classifiers as a dependency; trove-classifiers in turn depends on calver.
=> python-hatchling: Update to 1.14.0, add new host-only dependencies

net/kea/Makefile, net/kea/files/kea.init, net/kea/patches/003-no-test-compile.patch, net/kea/patches/004-replace-rev-with-awk.patch, net/kea/patches/010-openssl-deprecated.patch
Maintainer: @pangpang, @rosysong 
Compile tested: x86_64, generic, HEAD (c3cb2d48da)
Run tested: built but not installed yet
Description:
Update to 2.2.0
=> kea: Update to 2.2.0

.github/workflows/entrypoint.sh, utils/cache-domains/Makefile, utils/cache-domains/pre-test.sh
Description:
Some packages variants have conflicting dependencies with the base packages and the CI test will fail to install before anything can be done by the packages to setup the system for install.
This change adds a pre-test.sh that runs before the install so things like the default libustream variant can be swapped out as shown in the updated cache-domains.
=> ci, cache-domains: added pre-test.sh CI step

utils/sedutil/Makefile
Maintainer: me
Description:
The Drive Trust Alliance Self Encrypting Drive Utility
Tool to leverage Self Encrypting Drives (SED), common today among NVMEs.
[A Practical Guide to Use of Opal Drives](https://develop.trustedcomputinggroup.org/wp-content/uploads/2019/05/Opal_Drive_Guide_v1_Final_20190515.pdf)
It installs both `sedutil-cli` and `linuxpba`. I've only tested the former in OpenWrt. `linuxpba`, although interesting, makes booting, installing & upgrading quite more complex, and it's not compatible with 4K formatted drives, which is also the native format of modern NVME drives.
I think the most interesting option is using the former directly, from a preinit script, having the `boot` & `openwrt` partitions unencrypted.
[This …
=> sedutil: Add new package

.github/workflows/multi-arch-test-build.yml, net/sing-box/Makefile
Maintainer: @aparcar @neheb @BKPepe @1715173329
Compile tested: CI modifications are tested on my local machine. Besides, the workflow has run successfully.
Description:
The QEMU provided by Ubuntu supports emulating mips_24kc for a long time. Use it instead of the docker `aptman/qus` to enable runtime test for mips_24kc.
QEMU supports emulating mips_24kc since https://github.com/qemu/qemu/commit/77d119dd335f910c7f953a265726e3753c69a0bb. Both [`aptman/qus`](https://github.com/dbhi/qus) and [`multiarch/qemu-user-static`](https://github.com/multiarch/qemu-user-static) use an older version of `qemu-binfmt-conf.sh`.
Update sing-box to trigger the runtime test.
=> CI: Enable runtime_test for mips_24kc

net/pbr/Makefile, net/pbr/files/etc/hotplug.d/firewall/70-pbr, net/pbr/files/etc/hotplug.d/iface/70-pbr, net/pbr/files/etc/init.d/pbr.init, net/pbr/files/etc/uci-defaults/90-pbr, net/pbr/files/etc/uci-defaults/91-pbr, net/pbr/files/usr/share/pbr/pbr.firewall.include
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.4
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.3, test basic policies routing
Description:
*** MAKEFILE ***
* remove libubus dependency as it was causing issues https://forum.openwrt.org/t/policy-based-routing-pbr-package-discussion/140639/318
* move firewall hotplug directory/file creation out of default section into pbr and pbr-iptables packages sections in preparation for dropping it from pbr
* fix no new line after output when uninstalling packages
*** UCI-DEFAULTS ***
* only add firewall include to firewall config if the include file exists
* add shellcheck exception to netifd uci-defaults file
*** SCRIPTS ***
* more informative logging for firewall and iface hotplug scripts
* more informative logging for …
=> pbr: update to 1.1.1-1

net/pbr/Makefile, net/pbr/files/etc/hotplug.d/firewall/70-pbr, net/pbr/files/etc/hotplug.d/iface/70-pbr, net/pbr/files/etc/init.d/pbr.init, net/pbr/files/etc/uci-defaults/90-pbr, net/pbr/files/etc/uci-defaults/91-pbr, net/pbr/files/usr/share/pbr/pbr.firewall.include
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.4
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.3, test basic policies routing
Description:
*** MAKEFILE ***
* remove libubus dependency as it was causing issues https://forum.openwrt.org/t/policy-based-routing-pbr-package-discussion/140639/318
* move firewall hotplug directory/file creation out of default section into pbr and pbr-iptables packages sections in preparation for dropping it from pbr
* fix no new line after output when uninstalling packages
*** UCI-DEFAULTS ***
* only add firewall include to firewall config if the include file exists
* add shellcheck exception to netifd uci-defaults file
*** SCRIPTS ***
* more informative logging for firewall and iface hotplug scripts
* more informative logging for …
=> [22.03] pbr: update to 1.1.1-1

utils/rtl_433/Makefile
Maintainer: @TimelessNL 
Compile tested: ath79, D-Link DIR-825 B1, master and branch 22.03
Run tested: ath79, D-Link DIR-825 B1, branch 22.03, receiving data with USB dongle works
=> rtl_433: update to 22.11

net/nginx/Config_ssl.in, net/nginx/Makefile
Fix compilation error for stream module not converted to use the PACKAGE config flag and a missing required dependency for the DAV ext module.
Drop additional config for STREAM module since they are now included and built by default.
Fixes: 65a676ed56fb ("nginx: introduce support for dynamic modules")
Fixes: #20906
---
@EdiTurn @zcy85611 Can you test this?
=> nginx: fix compilation error for nginx-full

net/smartdns/Makefile
Compile tested: x86_64 openwrt docker image
Run tested: latest docker image, 21d02e598a
=> smartdns: bump to 1.2023.42

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
Description: Update to v2.6.13
- See changes: http://git.haproxy.org/?p=haproxy-2.6.git;a=shortlog
=> haproxy: update to v2.6.13

libs/gnutls/Makefile, libs/gnutls/patches/010-m4.patch, libs/gnutls/patches/020-dont-install-m4-files.patch
Fixes: https://github.com/openwrt/openwrt/issues/12542 
The detailed list of changes follows:
* Version 3.8.0 (released 2023-02-09)
** libgnutls: Fix a Bleichenbacher oracle in the TLS RSA key exchange. Reported by Hubert Kario (#1050). Fix developed by Alexander Sosedkin. [GNUTLS-SA-2020-07-14, CVSS: medium] [CVE-2023-0361]
** libgnutls: C++ library is now header only. All definitions from gnutlsxx.c have been moved into gnutlsxx.h. Users of the C++ interface have two options:
1. include gnutlsxx.h in their application and link against the C library. (default)
2. include gnutlsxx.h in their application, compile with GNUTLS_GNUTLSXX_NO_HEADERONLY macro defined and link against the C++ library.
** libgnutls: GNUTLS_NO_STATUS_REQUEST flag and %NO_STATUS_REQUEST priority modifier have been …
=> gnutls: update to v3.8.0

net/crowdsec-firewall-bouncer/Makefile
Update crowdsec-firewall-bouncer to latest upstream release version 0.0.26
Maintainer: Kerma Gérald gandalf@gk2.net
Run tested: ipq40xx/generic, Fritzbox 4040, Openwrt 22.03.5
=> crowdsec-firewall-bouncer: new upstream release version 0.0.26

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr.init, net/pbr/files/etc/uci-defaults/90-pbr
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, start & verify no error messages and IPv6 gw
Description:
* suppress RTNETLINK errors when inserting ipv6 routes
* only display global scope IPv6 gateways in status/WebUI
* stop and disable vpn-policy-routing when migrating
=> pbr: ipv6 & migration bugfixes

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr.init, net/pbr/files/etc/uci-defaults/90-pbr
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, start & verify no error messages and IPv6 gw
Description:
* suppress RTNETLINK errors when inserting ipv6 routes
* only display global scope IPv6 gateways in status/WebUI
* stop and disable vpn-policy-routing when migrating
(cherry picked from commit c2739705b98ebe37bb43f1650745c5e2336f163a)
=> [22.03] pbr: ipv6 & migration bugfixes

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 22.03
Run tested:  x86_64, Sophos XG-135r3, OpenWrt 22.03, test dns hijacking
Description:
* add family to firewall json objects, due to report that without explicit family declaration the hijacking didn't work for IPv6
=> simple-adblock: add family to firewall json objects

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 22.03
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03, test dns hijacking
Description:
* add family to firewall json objects, due to report that without explicit family declaration the hijacking didn't work for IPv6
(cherry picked from commit 0b84504670465876c8469da7dfb42f27d34db501)
=> [22.03] simple-adblock: add family to firewall json objects

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 22.03
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03, test dns hijacking
Description:
* use shared memory to store output data
* add family option to firewall json objects, due to reports that IPv6 hijacking doesn't work without explicit family declaration
=> https-dns-proxy: fixes/improvements

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 22.03
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03, test dns hijacking
Description:
* use shared memory to store output data
* add family option to firewall json objects, due to reports that IPv6 hijacking doesn't work without explicit family declaration
(cherry picked from commit 25801ddf7435e535fc0684911abdf6022549409f)
=> [22.03] https-dns-proxy: fixes/improvements

net/libreswan/Makefile, net/libreswan/patches/020-limits.patch
Release Notes:
https://github.com/libreswan/libreswan/releases/tag/v4.10
Fixes: CVE-2023-23009
(cherry picked from commit 130e63931fe99b1e47989bb708543c5ebc12152a)
Run tested: no
@lucize Is there any reason you did not update to a newer version on 22.03? Can we also go to 4.10 on 22.03 or do you want to leave it as 4.7. We may than have to backport the fix.
=> [22.03] libreswan: update to 4.10

mail/dovecot/Makefile
Issue https://github.com/openwrt/packages/issues/20677 Solved by micmac1 https://github.com/openwrt/packages/issues/20677#issuecomment-1483774965 
Maintainer: Lucian Cristian,lucian.cristian@gmail.com<@lucize>
Compile tested: (Ubuntu 22.04 ramips r22400-1558bbd116)
Run tested: (ramips r22400-1558bbd116 mt7621, autorun on startup)
Description:
compile with imagebuilder master with no other packages than dovecot for arch ramips. does not build.
Looking at the provided logs autoreconf fails because the iconv macro is missing (iconv.m4). If I remember correctly the macro was provided earlier by libiconv package, but that's no longer the case.
=> dovecot: Fix iconv macro is missing compile error

.github/workflows/multi-arch-test-build.yml
Maintainer: @aparcar (ping @neheb, @BKPepe, @1715173329)
Compile tested: test PR on my own fork ([with ipks](https://github.com/jefferyto/openwrt-packages/actions/runs/4934827250/jobs/8820347865), [no ipks](https://github.com/jefferyto/openwrt-packages/actions/runs/4934647133/jobs/8819952556))
Description:
* **[CI: Run "apt-get update" before installing signify-openbsd](https://github.com/openwrt/packages/commit/fc4cac029af9101501e6d28419f99b40598b1627)**
I forgot to add a `apt-get update` in #20845 :sweat_smile: 
* **[CI: Do package run-tests only if target packages were built](https://github.com/openwrt/packages/commit/817968f5c003edb034c7fbdf653662bf671e7b5a)**
Currently, the package run-test phase will fail for PRs that only add/update host-only packages, as no target …
=> CI: Run "apt-get update", do package run-tests only if target packages were built

utils/lxc/Makefile, utils/lxc/files/lxc-auto.init
```
The default runtime directory used by LXC is /run which doesn't exist
in OpenWrt. It causes errors like:
Failed to create lock for foo
lxc-create: foo: tools/lxc_create.c: main: 260 Failed to create lxc container
There has been workaround for that in the lxc-auto.init but it requires
installing "lxc-auto" package. Replacing that "ln -s" workaround with
Makefile specifying RUNTIME_PATH define allows using pure "lxc" in
OpenWrt (without the "lxc-auto").
```
=> lxc: set RUNTIME_PATH to the /var/run

libs/glib2/Makefile
Compile tested: x86_64, openwrt master
fixes #20219 
Description:
If buildsystem does not have a internet connection, then the build fails. This is because of the fact, that glib2 is downloading and building the missing dependencies during host compilation.
This cannot be allowed to happen. The package must also be built without an internet connection.
Adding the missing host build dependency and removing the 'forcefallback' fixes this issue.
=> glib2: fix host build offline build

libs/libvorbis/Makefile, libs/libvorbis/patches/010-cmake_soname.patch
When building with cmake we don't get libvorbis*.so.N which means that some applications may fail to dynamically load libvorbis libraries.
This seems to be a problem specific to cmake (autotools builds work).
Compile tested: ath79, D-Link DIR-825, 22.03
Run tested: ath79, D-Link DIR-825, 22.03, I've verified that squeezelite now can dynamically load libvorbisfile.so.3
=> libvorbis: fix soname of shared libraries

net/netavark/Makefile, net/netavark/files/netavark-config, net/netavark/files/netavark-wrapper
podman is moving from cni to netavark. Netavark supports currently only iptables, so I was in touch some time ago with mainstream maintainer and provided a "none" firewall driver - to make it possible to use netavark without firewalling features. This was merged to mainstream. Driver cannot be selected at this time without environment variable that selects it, so I made a config file for openwrt and a wrapper script that takes advantage of it, since you cannot set it as a setting in containers.conf at this moment.
Available options are iptables, nftables and none - but selecting nftables just tells user that nftables isn't yet supported.
firewall "none" driver is not yet included in release, so that's why we use git version instead. I chose latest commit instead of commit with none …
=> netavark: add new package

net/aardvark-dns/Makefile
aardvark-dns is companion for netavark #20995, recent cni replacement on podman git version used instead of release, to maintain maximal compatibility with netavark, also using git version.
Description:
Aardvark-dns is an authoritative dns server for A/AAAA container records. It can forward other requests to configured resolvers.
Maintainer: oskarirauta / @oskarirauta
=> aardvark-dns: add new package

lang/python/python-eventlet/Makefile
Compile tested: armv7l, Turris Omnia, OpenWrt 22.03
Run tested: armv7l, Turris Omnia, OpenWrt 22.03
Description: As described in #20891, eventlet 0.30 doesn't work with Python 3.10. The package was updated on master, but 22.03 also uses Python 3.10, so has to be backported.
@ja-pa we are using this package in Turris, would you mind if I adopted this package from you?
cc @shenek
=> [22.03] python-eventlet: bump to version 0.33.3 (backport from master)

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, test IPv6 routes
Description:
* add missing space in str_contains
* unquote variable to make sure IPv6 rotues are added
* add IPv6 routes display to status output in nft mode
(cherry picked from commit 643e501c8d0209dbbc683447b4df0c4b2b9aed08)
=> [22.03] pbr: bugfix: create IPv6 routes

net/xtables-addons/Makefile, net/xtables-addons/patches/001-fix-kernel-version-detection.patch, net/xtables-addons/patches/100-add-rtsp-conntrack.patch, net/xtables-addons/patches/200-add-lua-packetscript.patch
Use `kmalloc` and remove conflicting `#include <stdarg.h>`, to fix the following build warnings treated as errors since https://github.com/openwrt/openwrt/commit/b2d1eb717b6597e0145c98fc5f9f88a7dc219513
```
error: ISO C90 forbids variable length array 'buf' [-Werror=vla]
error: "va_start" redefined [-Werror]
error: "va_arg" redefined [-Werror]
error: "va_copy" redefined [-Werror]
getstr(s)==NULL is always false
```
Compile tested: WRT3200ACM
@Ansuel @aparcar @neheb @pprindeville
=> xtables-addons: bump to 3.24, fix build errors since b2d1eb7

mail/dovecot/Makefile, mail/pigeonhole/Makefile
Maintainer: @lucize, @flyn-org
Run tested: -
Description:
Update dovecot and also bump pigeonhole to keep version in sync.
All commits are picked from the main development branch and snapshot builds there have completed on buildbot successfully.
=> [22.03] update dovecot pigeonhole

lang/python/python-incremental/Makefile
Maintainer: me
Compile tested: armvirt-32, 2023-05-08 snapshot sdk
Description:
Fixes: 8d81b6732757 ("python-incremental: Update to 22.10.0, redo patch, add host build")
=> python-incremental: Add missing host build dependencies

net/lighttpd/Makefile, net/lighttpd/patches/020-meson-mod_webdav_min.patch, net/lighttpd/patches/030-mod_h2-HTTP-2-separate-mod.patch
Description:
backport #20980, but omit commits which change default cryptolib used by lighttpd
* update to lighttpd 1.4.70 release hash
* include mod_h2 in base package
=> lighttpd: update to lighttpd 1.4.70 release hash - backport to openwrt 22.03

net/lighttpd/Makefile, net/lighttpd/patches/020-meson-mod_webdav_min.patch, net/lighttpd/patches/030-mod_h2-HTTP-2-separate-mod.patch, net/lighttpd/patches/030-restore-removed-modules.patch, net/lighttpd/patches/040-revert-test_mod_evasive.patch
Description:
backport #20980, but omit commits which change default cryptolib used by lighttpd
This PR follows #21012: backport to 22.03.
Thie PR preserves lighttpd modules deprecated and removed in openwrt 22.03, same as in previous lighttpd 1.4.69 backport to openwrt 21.02
* update to lighttpd 1.4.70 release hash
* include mod_h2 in base package
=> lighttpd: update to lighttpd 1.4.70 release hash - backport to openwrt 21.02

net/transmission/Makefile
Update transmission to latest v4.0.3 release
Changelog: https://github.com/transmission/transmission/releases/tag/4.0.3
Maintainer: Daniel Golle <daniel@makrotopia.org>
Compile tested: mediatek/filogic on latest master
Run tested: mediatek/filogic on latest master
=> transmission: Update to v4.0.3

libs/libpng/Makefile
Changelog:
https://github.com/glennrp/libpng/blob/v1.6.39/CHANGES
Maintainer: @jow
@jow- Can you maybe runtest? This release does not seem to fix CVE-2022-3857 at least it is not mentioned in the relase notes nor I find a commit. :/
=> libpng: update to 1.6.39

libs/nspr/Makefile
Maintainer: me
Inspired from #21031
=> nspr: fix musl compile

net/crowdsec-firewall-bouncer/Makefile
Update crowdsec-firewall-bouncer to latest upstream release version 0.0.27
Run tested: ipq40xx/generic, Fritzbox 4040, Openwrt 22.03.5
=> crowdsec-firewall-bouncer: new upstream release version 0.0.27

admin/btop/Makefile
_LARGEFILE64_SOURCE has to be defined in the source, or CFLAGS can be used to pass -D_LARGEFILE64_SOURCE to allow to keep using LFS64 definitions.
Fixes errors in the form of:
Compiling src/linux/btop_collect.cpp
src/linux/btop_collect.cpp: In function 'Mem::mem_info& Mem::collect(bool)': src/linux/btop_collect.cpp:1082:58: error: aggregate 'Mem::collect(bool)::statvfs64 vfs' has incomplete type and cannot be defined
1082 |                                         struct statvfs64 vfs;
|                                                          ^~~
src/linux/btop_collect.cpp:1083:79: error: invalid use of incomplete type 'struct Mem::collect(bool)::statvfs64'
1083 |                                         if (statvfs64(mountpoint.c_str(), &vfs) < 0) {
| …
=> btop: fix compilation with musl 1.2.4

libs/alsa-lib/Makefile, libs/alsa-lib/patches/200-usleep.patch, libs/alsa-ucm-conf/Makefile, sound/alsa-utils/Makefile
Maintainer: @thess @tripolar (cc @neheb)
Description:
* updated source url (prefer https rather than http/ftp)
* fixed build with musl 1.2.4
=> alsa: update to 1.2.9

net/libreswan/Makefile
Fixes https://libreswan.org/security/CVE-2023-30570
Maintainer: me
Tested x86_64
=> libreswan: update to 4.11

utils/acl/Makefile, utils/acl/patches/103-chacl-Use-portable-version-of-dirent-and-readdir.patch
Description:
Backport an upstream fix to replace these old functions.
Fixes: #21051
=> acl: fix compilation with musl 1.2.4

net/openssh/Makefile
Compile tested: mips_24k, gl.inet AR150
Run tested: mips_24k, gl.inet AR150, installed individual packages with and (in the case of sftp ones) without dependencies.
Description:
OpenSSH 9.1p1 removed remaining dependencies and stopped linking sftp,
sftp-server and scp against libcrypto or libz.  This change moves those
package dependencies from the default to those that still need them.
In particular, this will allow sftp-server to be installed for use with
Dropbear without needing to install zlib or openssl.
=> Remove dependencies on sftp packages and use CDN for downloads.

libs/libpciaccess/Makefile, libs/libpciaccess/patches/010-linux_sysfs-Use-pwrite-pread-instead-of-64bit-versions.patch
Description:
Backported an upstream commit to fix build with musl 1.2.4.
=> libpciaccess: Update to 0.17

utils/acpid/Makefile, utils/acpid/patches/010-Replace-stat64-with-stat.patch
Maintainer: Thomas Heil / cc @neheb
Description:
Backported an upstream commit to fix build with musl 1.2.4.
=> acpid: Update to 2.0.34

mail/mblaze/Makefile, mail/mblaze/patches/010-mlist-use-fixed-width-integer-types-for-struct-linux_dire.patch
Description:
Backport an upstream fix to replace these old data types.
=> mblaze: fix compilation with musl 1.2.4

utils/xfsprogs/Makefile
=> xfsprogs: fix compilation with musl 1.2.4

utils/btrfs-progs/Makefile
Description:
Fixed build issue with musl 1.2.4.
=> btrfs-progs: Update to 6.3

multimedia/xupnpd/Makefile
=> xupnpd: fix compilation with musl 1.2.4

libs/gnutls/Makefile, libs/gnutls/patches/030-unistring-optional.patch
Since a few days staging_dir/host/share/aclocal/ contains new m4 files (libunistring-base.m4, libunistring-optional.m4, libunistring.m4 etc.) that get applied during autoreconf. This changes the libunistring setup enough that we run into problem (builds fail).
Load the libunistring-optional gnulib module in configure.ac to be able to add/use the new configure switch "--with-included-libunistring".
This is at most a workaround. This should be followed up with gnutls upstream to clean this up.
Compile tested:sdk ath79
Description:
This is regarding the gnutls build failure reported in issue #20969. It was suspected that this is related to gcc-13, but as it turns out it's just a broken interaction between gnutls and updated autoreconf macros.
=> gnutls: load libunistring-optional gnulib module

utils/oath-toolkit/Makefile
This package seems to be missing an InstallDev section. Had a compile failure for an application that needs to compile against liboath
Maintainer:  @famz
Compile tested: arm cortex-a7 ipq40xx, p2w_r619ac-128m, OpenWrt 22.03
Run tested:  arm cortex-a7 ipq40xx, p2w_r619ac-128m, OpenWrt 22.03
Description:
Some application like ocserv need liboath to enable otp feature, add InstallDev section to export include and pkgconfig files
Details in https://gitlab.com/openconnect/ocserv/-/issues/508#note_1388900513
=> oath-toolkit: add InstallDev section

lang/perl/Makefile
Compile tested: ipq807x/master
Description:
_LARGEFILE64_SOURCE has to be defined in the source, or CFLAGS can be used to pass -D_LARGEFILE64_SOURCE to allow to keep using LFS64 definitions.
=> perl: fix compilation with musl 1.2.4

libs/libupm/Makefile, libs/libupm/patches/011-gcc-13-compatibility-fixes.patch
Maintainer: @blogic, me
 Compile tested: head (with gcc13), aarch64
 Run tested: (qemu-8.0.0) aarch64
Description:
Workaround for errors with GCC13
https://github.com/openwrt/packages/issues/20994
patch
https://github.com/oskarirauta/local-overrides/blob/main/libs/libupm/patches/011-gcc-13-compatibility-fixes.patch
=> libupm: Workaround for errors with GCC13

libs/gpgme/Makefile
=> gpgme: fix compilation with musl 1.2.4

lang/python/python-attrs/Makefile
Maintainer: me
Compile tested: armvirt-32, 2023-05-15 snapshot sdk
Run tested: armvirt-32 (qemu), 2023-05-15 snapshot
Description:
The package now uses pyproject.toml-based builds with additional build dependencies.
=> python-attrs: Update to 23.1.0

net/tgt/Makefile
Description:
while at it bump to latest version 1.0.86
=> tgt: Update to 1.0.86

net/crowdsec/Makefile, net/crowdsec/patches/001-fix_config_data_dir.patch
Update crowdsec to latest upstream release version 1.5.1
Run tested: ipq40xx/generic, Fritzbox 4040, Openwrt 22.03.5
Description: update to latest version of upstream
=> crowdsec: new upstream release version 1.5.1

net/arp-scan/Makefile
arp-scan complains about missing libcap dependency. Add it as package dependency to fix compilation.
Maintainer: @urusha
Run tested: no
=> arp-scan: fix missing libcap dependency

utils/inotify-tools/Makefile
Fixes errors in the form of:
inotifytools.c: In function 'inotifytools_watch_recursively_with_exclude': inotifytools.c:1335:30: error: storage size of 'my_stat' isn't known
1335 |         static struct stat64 my_stat;
|                              ^~~~~~~
inotifytools.c:1342:36: error: implicit declaration of function 'lstat64'; did you mean 'lstat'? [-Werror=implicit-function-declaration]
1342 |                         if ( -1 == lstat64( next_file, &my_stat ) ) {
|                                    ^~~~~~~
|                                    lstat
inotifytools.c:1335:30: error: unused variable 'my_stat' [-Werror=unused-variable]
1335 |         static struct stat64 my_stat;
|                              ^~~~~~~
inotifytools.c: In function 'isdir':
inotifytools.c:1621:30: error: …
=> inotify-tools: fix compilation with musl 1.2.4

utils/mariadb/Makefile
Maintainer: @miska
Description:
=> mariadb: fix compilation with musl 1.2.4

utils/docker-compose/Makefile
Maintainer: me
Run tested:  master x86-64
Description:
New upstream release. [Release notes](https://github.com/docker/compose/releases)
=> docker-compose: Update to version 2.18.1

lang/python/python3-packages/Makefile
Compile tested: armvirt-32, 2023-05-08 snapshot sdk
Description:
This sets `PYTHON3_PKG_BUILD:=0` so that python3-package.mk does not set any default build recipes.
=> python3-packages: Set PYTHON3_PKG_BUILD:=0

net/cloudflared/files/cloudflared.init
Compile tested: N/A no compilation related changes
Description:
Allows user to provide a token for Cloudflare tunnel. When provided along with credentials, this will take precedence.
=> cloudflared: support setting tunnel token

libs/efivar/Makefile, libs/efivar/patches/003-Use-off_t-instead-of-off64_t.patch
Backport an upstream fix to replace these old data types.
=> efivar: fix compilation with musl 1.2.4

libs/gnutls/Makefile, libs/gnutls/patches/040-build-use-clang-format-on-off-annotation.patch
Description:
Zabbix verifies the version of gnutls by search in the header gnutls.h. This is done with 'cat' and 'egrep'. The problem here is now that the preprocess definition did changed in gnutls.h, so the regex does not match anymore.
The following error message acourse in the log:
> configure: error: GnuTLS library version requirement not met (>= 3.1.18)
To fix this backport an upstream patch to let the regex work again.
Original PR: https://github.com/openwrt/packages/pull/20967
Cc: @feckert
=> gnutls: fix build with zabbix

utils/mariadb/Makefile, utils/mariadb/patches/300-gcc-13-compatibility-fix.patch
fixes this error with gcc 13:
```
- Configuring done (51.2s)
-- Generating done (0.3s)
-- Build files have been written to: /usr/src/openwrt/build_dir/target-x86_64_musl/mariadb-10.9.3
touch /usr/src/openwrt/build_dir/target-x86_64_musl/mariadb-10.9.3/.configured_73ad54549cf584414d16280358124567
rm -f /usr/src/openwrt/build_dir/target-x86_64_musl/mariadb-10.9.3/.built
touch /usr/src/openwrt/build_dir/target-x86_64_musl/mariadb-10.9.3/.built_check
MAKEFLAGS="" /usr/src/openwrt/staging_dir/host/bin/ninja  -j1 -C /usr/src/openwrt/build_dir/target-x86_64_musl/mariadb-10.9.3 
ninja: Entering directory `/usr/src/openwrt/build_dir/target-x86_64_musl/mariadb-10.9.3'
[88/1406] Building C object libmariadb/libmariadb/CMakeFiles/mariadb_obj.dir/__/plugins/pvio/pvio_socket.c.o
In file included from …
```
=> mariadb: fix gcc 13 building

lang/python/python3-libselinux/Makefile
=> python3-libselinux: fix compilation with musl 1.2.4

net/gensio/Makefile
Compile tested: armvirt-32, 2023-05-15 snapshot sdk
Description:
If the build host has the Go compiler installed, then configure will detect this and will try to compile gensio's Go support, leading to a build failure.
This disables Go support entirely to fix this build failure.
=> gensio: Fix build on build host with Go compiler

utils/evtest/Makefile
Maintainer: @psidhu
Run tested: -
Description:
Just selecting this package resulted in a build error:
/home/mhei/openwrt.git/staging_dir/hostpkg/bin/python3: No module named asciidoc
make[4]: *** [Makefile:856: evtest.xml] Error 1
Since we usually do not need the man page, just prevent to build it by pre-setting two environments variables. Then the makefile warns about, but don't try to build.
=> evtest: don't build man page

libs/libgpg-error/Makefile
=> libgpg-error: update to 1.47

lang/php8-pecl-mcrypt/Makefile
=> php8-pecl-mcrypt: update to 1.0.6

net/natmap/Makefile
Maintainer: @ysc3839 @heiher 
Description:
1. Update to 20230519.
2. Add myself to maintainers.
=> [22.03] natmap: update to 20230519

net/openvpn/Makefile, net/openvpn/files/openvpn.init
Maintainer: @mkrkn 
Compile tested: mvebu, Turris Omnia, TOS 7.0 ~ OpenWrt 22.03
Run tested: mvebu, Turris Omnia, TOS 7.0 ~ OpenWrt 22.03, custom scripts reacting to those events work
Description:
OpenVPN supports more hooks than just 'up' and 'down'. Especially reacting to 'route-up' and 'route-pre-down' events could be important. When routing table changes, it can make sense to adapt firewall, run some tests or change even more routes. This change passes those events to hotplug, so it is easy to react to them without changing configuration files provided by VPN provider.
=> openvpn: Add more hotplug events

net/nginx-util/Makefile, net/nginx-util/files/uci.conf.template, net/nginx/Makefile, net/nginx/files/nginx.init
Uci defaults script are run only on first installation. On package upgrade, the ubus module for the nginx-mod-luci is not installed in the nginx conf. Fix this by adding a post install script.
Fixes: 65a676ed56fb ("nginx: introduce support for dynamic modules")
Fixes: #20904
---
@anomeome can you test? I assume your problem was with upgrading the package right? or it was from a clean image?
=> nginx: fix missing module entry on package update

net/tailscale/Makefile
=> tailscale: update to 1.40.1

net/transmission/Makefile
Compile tested: OpenWrt r22977, built on x86-64 Gentoo Linux
Run tested: bcm27xx, Raspberry Pi 3B+, 64bit
Description:
Fixes issue #21016.
=> transmission: add missing nls.mk include

net/ocserv/Config.in, net/ocserv/Makefile, utils/oath-toolkit/Makefile
Maintainer: @nmav, @famz 
Compile tested: arm cortex-a7 ipq40xx, p2w_r619ac-128m, OpenWrt 22.03
Run tested: arm cortex-a7 ipq40xx, p2w_r619ac-128m, OpenWrt 22.03
Description:
base on https://github.com/openwrt/packages/pull/21111#issuecomment-1554902135 and https://github.com/openwrt/packages/pull/21035#issuecomment-1554311549
Split liboath from oath-toolkit (from @1715173329 )
Add option enable OTP feature and also fix build error
Add oath PAM authentication module
=> oath-toolkit and ocserv: Adjusting dependencies, split liboath from oath-toolkit, add oath pam module

net/curl/Makefile, net/curl/patches/200-no_docs_tests.patch
=> curl: update to 8.1.0

libs/inih/Makefile, utils/xfsprogs/Makefile, utils/xfsprogs/patches/120-disable_assert.patch
Description:
Changelogs:
```
xfsprogs-6.2.0 (24 Mar 2023)
xfs_repair: fix incorrect dabtree hashval comparison (Darrick J. Wong)
mkfs: protofile can now create directories with spaces  in their names (Darrick J. Wong)
mkfs: check dirent names when reading protofile (Darrick J. Wong)
xfs_io: fix bmap command not detecting realtime files with xattrs (Darrick J. Wong)
xfs_io: set fs_path when opening files on foreign filesystems (Darrick J. Wong)
xfs_scrub: fix broken realtime free blocks unit conversions (Darrick J. Wong)
xfs_spaceman: fix broken -g behavior in freesp command (Darrick J. Wong)
xfs_admin: correctly parse IO_OPTS parameters (Catherine Hoang)
Fix autoconf during debian package builds (Dave Chinner)
xfs_admin: …
```
=> xfsprogs: Update to 6.2.0

lang/perl/Makefile, lang/perl/perlbase.mk
Enabling Perl tests causes failure during build.
Files that should be installed into packages, are
missing or in different location.
This PR removes missing files/paths and replaces
paths that have changed with working ones.
Most likely, test files have been relocated during time and this portion hasn't been updated when
perl package has updated.
Fixes #21127
Maintainer: @pprindeville @1715173329
=> perl: fix tests

utils/borgbackup/Makefile
Maintainer: @julienmalik 
Compile tested: armvirt-32, 2023-05-15 snapshot sdk
Description:
lang/python is meant for Python libraries and other packages closely related to the Python language. It makes more sense for borgbackup to be in utils instead.
=> borgbackup: Move from lang/python into utils

utils/borgbackup/Makefile
Compile tested: none (cherry pick from #21099)
Description:
lang/python is meant for Python libraries and other packages closely related to the Python language. It makes more sense for borgbackup to be in utils instead.
(cherry picked from commit 5059cfccae8fda6837481569bdf3fff02144d614)
=> [openwrt-23.05] borgbackup: Move from lang/python into utils

libs/postgresql/Makefile
Release Notes:
https://www.postgresql.org/docs/release/15.2/
Fixes: CVE-2022-41862
@dangowrt Could you run-test? Otherwise, I need to make up some postgresql installation myself.
=> postgresql: update to 15.2

lang/python/python3/Makefile
Maintainer: me
Compile tested: none (cherry pick of #21166)
Description:
configure will try to link with libbsd for the flock function, even when flock is available without it.
Fixes: https://github.com/openwrt/packages/issues/21161
Fixes: 2445fe9fb25e ("python3: Update to 3.11.3, refresh/redo patches")
(cherry picked from commit 60bf01cb606344619e002901646171da1e69c0f9)
=> [openwrt-23.05] python3: Fix unnecessary linking with libbsd

net/uwsgi/Makefile, net/uwsgi/patches/003-hard-code-Linux-as-compilation-os.patch
Maintainer: @Ansuel (ping @peter-stadler)
Compile tested: armvirt-32, 2023-05-21 snapshot sdk
Description:
This version includes support for Python 3.11.
This also:
* Updates Build/Compile to only build selected subpackages.
* Removes the submenu in menuconfig; there are too few subpackages to justify the extra complexity.
Fixes: https://github.com/openwrt/packages/issues/21163
=> uwsgi: Update to 2.0.21, refresh patches

net/openvpn-easy-rsa/Makefile, net/openvpn-easy-rsa/patches/100-Make-package-reproducible.patch
Version 3.0.9 of EasyRSA introduces OpenSSL 3 (3.0.3) support.
For other changes, see:
- https://github.com/OpenVPN/easy-rsa/releases/tag/v3.0.9
- https://github.com/OpenVPN/easy-rsa/releases/tag/v3.1.0
- https://github.com/OpenVPN/easy-rsa/releases/tag/v3.1.1
- https://github.com/OpenVPN/easy-rsa/releases/tag/v3.1.2
- https://github.com/OpenVPN/easy-rsa/releases/tag/v3.1.3
Closes #21142
Maintainer: me
Compile tested: master on x86/64 (noarch package)
Run tested: x86/64 vm creating a CA with some certs.
Description:
=> openvpn-easy-rsa: update to 3.1.3

sound/squeezelite/Makefile
The squeezelite packages were lacking some features/codecs (ssl, opus, wma, dsd and resampling) and required manual compilation to enable these features/codecs.
Now there are 3 packages available that hopefully should satisfy most users:
* full - This package enables all features and codecs.
* dynamic - This package only enables PCM/AIFF and MP3 codecs and all other features/codecs can be added by manually installing OpenWrt packages.
* custom - This package allows for customizing squeezelite.
@neheb, I dropped dependency on BUILD_PATENTED which you added in 10c087a98c2ab8e5dcf569a052987b10e3e582e4. I removed the dependency because it looks like BUILD_PATENTED only controls which video codecs to include in ffmpeg and squeezelite uses libffmpeg-audio-dec which doesn't contain any video …
=> squeezelite: restructure package variants

net/curl/Makefile
Maintainer: me
Description:
* https://curl.se/changes.html#8_1_1
=> curl: update to 8.1.1

net/nginx/Makefile, net/nginx/patches/nginx-mod-dav-ext/100-drop-libxslt-dep.patch, net/nginx/patches/nginx-mod-lua/100-no_by_lua_block.patch, net/nginx/patches/nginx-mod-rtmp/100-bigedian.patch
Compile tested: x86-64 master
Run tested: x86-64 master
Description:
Since modules now follow a naming convention, there is an opportunity to eliminate redundant code.
However, during the process, I found the following:
1. `CONFIG_NGINX_GEOIP_MODULE` didn't exist in Config_ssl.in, so it was never compiled. I tried to compile it, but nginx complained about the missing GeoIP library, which currently doesn't seem to exist in openwrt/packages? I removed the corresponding code for now, can restore if the GeoIP library exists.
2. ~~In menuconfig, if `nginx-full` is selected, it won't set any `CONFIG_NGINX_*` variables, leading `nginx-mod-dav-ext` to miss its `+@NGINX_DAV` dependency~~.
3. `nginx-full` depends on `nginx-mod-*`, which in turn depend on `nginx-ssl`, leading to …
=> nginx: refactor

.github/workflows/multi-arch-test-build.yml
Add concurrency rules to skip redundant build to skip extra build test on force push on pull request.
=> CI: add concurrency rules to skip redundant build

net/curl/Makefile, net/curl/patches/200-no_docs_tests.patch
Maintainer: me
(cherry picked from commit b2904dff93e805c1d72407ff765fe17a68046e86)
=> [23.05] curl: update to 8.1.0

net/uwsgi/Makefile, net/uwsgi/patches/003-hard-code-Linux-as-compilation-os.patch
Maintainer: @Ansuel (ping @peter-stadler)
Compile tested: none (cherry pick from #21171)
Description:
This version includes support for Python 3.11.
This also:
* Updates Build/Compile to only build selected subpackages.
* Removes the submenu in menuconfig; there are too few subpackages to justify the extra complexity.
Fixes: https://github.com/openwrt/packages/issues/21163
(cherry picked from commit 4d8cc440a4341d0074269db76e1b9b29deeb2db4)
=> [openwrt-23.05] uwsgi: Update to 2.0.21, refresh patches

net/tailscale/Makefile, net/tailscale/patches/010-fake_iptables.patch
=> tailscale: update to 1.42.0

lang/python/numpy/Makefile, lang/python/numpy/patches/001-unpin-build-dependencies.patch
Maintainer: me
Compile tested: x86 & x86_64 https://github.com/openwrt/openwrt/commit/c815ecdebd77c3484f2cd0ef21e4c69d274ef33a
Run tested: x86 & x86_64 https://github.com/openwrt/openwrt/commit/c815ecdebd77c3484f2cd0ef21e4c69d274ef33a
Need to also fix build for GCC 13 + musl.
=> numpy: bump version to 1.24.3

net/curl/Makefile, net/curl/patches/200-no_docs_tests.patch
Maintainer: me
(cherry picked from commit b2904dff93e805c1d72407ff765fe17a68046e86)
=> [22.03] curl: update to 8.1.0

lang/python/django/Makefile
Run tested: no
Fixes CVE-2023-31047
Link: https://nvd.nist.gov/vuln/detail/CVE-2023-31047
=> [21.02] django: bump to version 3.2.19

lang/python/python-greenlet/Makefile
Fix build with Python 3.11.
Maintainer: @ja-pa / cc @commodo 
=> python-greenlet: Update to 2.0.2

utils/apparmor/Makefile, utils/apparmor/patches/100-add-missing-cstdint-include.patch
Maintainers: 
me
@CodeFetch 
@paper42
@cotequeiroz 
Compile tested: x86_64, latest git (gcc 13)
Description:
fixes following error, when building with gcc 13:
```
In file included from profile.h:21,
from profile.cc:15:
capability.h:46:6: error: variable or field '__debug_capabilities' declared void
46 | void __debug_capabilities(uint64_t capset, const char *name);
|      ^~~~~~~~~~~~~~~~~~~~
capability.h:46:27: error: 'uint64_t' was not declared in this scope
46 | void __debug_capabilities(uint64_t capset, const char *name);
|                           ^~~~~~~~
capability.h:1:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
+++ |+#include <cstdint>
1 | /*
capability.h:46:44: error: expected primary-expression before 'const'
46 | …
```
=> apparmor: gcc 13 compatibility fix

lang/python/pillow/Makefile, lang/python/python-evdev/Makefile
Maintainer: @commodo (python-evdev, pillow), @paulo-raca (python-evdev)
Compile tested: armvirt-32, 2023-05-21 snapshot sdk
Description:
setuptools 64.0.0 deprecated the use of `--global-option` to [pass build parameters][1]. This replaces the use of `--global-option` with `--build-option`.
[1]: https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6400
=> python-packages: Replace --global-option with --build-option

lang/python/pillow/Makefile, lang/python/python-evdev/Makefile
Maintainer: @commodo (python-evdev, pillow), @paulo-raca (python-evdev)
Compile tested: none (cherry pick from #21199)
Description:
setuptools 64.0.0 deprecated the use of `--global-option` to [pass build parameters][1]. This replaces the use of `--global-option` with `--build-option`.
[1]: https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v6400
(cherry picked from commit b76fa19b26027f8472617598c19b9e071eef81bb)
=> [openwrt-23.05] python-packages: Replace --global-option with --build-option

devel/ragel/Makefile
This is a new package for ragel which is a dependency for another new package vectorscan
=> ragel: new package to build vectorscan

lang/python/python-bcrypt/Makefile
Description:
This is the last released version before bcrypt's Rust rewrite; this package can be further updated after the OpenWrt Rust toolchain has stablized.
This also renames the source package from bcrypt to python-bcrypt to match other Python packages, and updates the list of dependencies.
=> bcrypt: Update to 3.2.2, rename source package

lang/python/python-hatch-fancy-pypi-readme/Makefile
=> python-hatch-fancy-pypi-readme: Update to 23.1.0

lang/python/python-gmpy2/Makefile, libs/libmpc/Makefile, libs/libmpc/patches/001-only-src.patch, libs/mpfr/Makefile, libs/mpfr/patches/001-only-src.patch
Maintainer: me
Compile tested: armvirt-32/armvirt-64/malta-be/x86-generic/x86-64, 2023-02-21 snapshot sdk
Run tested: armvirt-32/armvirt-64/malta-be/x86-generic/x86-64 (qemu), 2023-02-21 snapshot
Description:
This updates python-gmpy2 to 2.1.5 and adds packages for two new dependencies, mpfr and mpc.
=> python-gmpy2: Update to 2.1.5; add new dependencies

lang/python/python-typing-extensions/Makefile
Description:
This also updates the SPDX license identifier, title, description and URL for the package.
=> python-typing-extensions: Update to 4.6.2

lang/python/python-click-log/Makefile
Description:
This renames the source package from click-log to python-click-log to match other Python packages.
This also updates the package to download from PyPI, and updates the package title, URL, and dependencies.
=> click-log: Update to 0.4.0, rename source package

utils/collectd/Makefile, utils/collectd/files/collectd.uci, utils/collectd/files/usr/share/collectd/plugin/tcpconns.json
Maintainer: @jow- , @hnyman 
Compile tested: aarch64_cortex-a53, ipq807x/generic, r22604+4-a247f49794
Run tested: aarch64_cortex-a53, ipq807x/generic, r22604+4-a247f49794
Description:
enable summarized stats for tcp connections, https://collectd.org/wiki/index.php/Plugin:TCPConns#Summary_of_all_ports
=> collectd: enable AllPortsSummary for tcpconns plugin

utils/zile/Makefile
Maintainer: thess
Compile tested: several
Run tested: arm_cortex-a15, mipsel_24kc, x86
Description:
It is no longer required since gnulib is now local to host build environment (tools/gnulib).
=> Zile: Remove autoreconf

lang/python/python-jinja2/Makefile
Description:
This renames the source package from Jinja2 to python-jinja2 to match other Python packages.
This also updates the package license files, title, and list of dependencies.
=> Jinja2: Update to 3.1.2, rename source package

lang/python/python-markupsafe/Makefile
Description:
This renames the source package from MarkupSafe to python-markupsafe to match other Python packages.
This also updates the package title and description.
=> MarkupSafe: Update to 2.1.2, rename source package

lang/python/python-werkzeug/Makefile
Description:
This renames the source package from Werkzeug to python-werkzeug to match other Python packages.
This also updates the package title, description, and list of dependencies.
=> Werkzeug: Update to 2.3.4, rename source package

net/curl/Makefile
Maintainer: me
Description:
* https://curl.se/changes.html#8_1_1
(cherry picked from commit b126e765cc8bc100336ea42fab5f655c0d4c6325)
=> [22.03] curl: update to 8.1.1

net/curl/Makefile
Maintainer: me
Description:
* https://curl.se/changes.html#8_1_1
(cherry picked from commit b126e765cc8bc100336ea42fab5f655c0d4c6325)
=> [23.05] curl: update to 8.1.1

lang/python/python-hatch-fancy-pypi-readme/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21220)
Description:
(cherry picked from commit 9f8a5fb25b22933dc25c72bc8df59db6ac080a68)
=> [openwrt-23.05] python-hatch-fancy-pypi-readme: Update to 23.1.0

lang/python/python-typing-extensions/Makefile
Compile tested: none (cherry picked from #21222)
Description:
This also updates the SPDX license identifier, title, description and URL for the package.
(cherry picked from commit f45f067f3f9726acfb0d5edd193731bc587ff54f)
=> [openwrt-23.05] python-typing-extensions: Update to 4.6.2

lang/python/python-bcrypt/Makefile
Compile tested: none (cherry picked from #21223)
Description:
This is the last released version before bcrypt's Rust rewrite; this package can be further updated after the OpenWrt Rust toolchain has stablized.
This also renames the source package from bcrypt to python-bcrypt to match other Python packages, and updates the list of dependencies.
(cherry picked from commit 3def783d3c72effdb87b1168315e51295cebc20f)
=> [openwrt-23.05] bcrypt: Update to 3.2.2, rename source package

lang/python/python-click-log/Makefile
Compile tested: none (cherry picked from #21224)
Description:
This renames the source package from click-log to python-click-log to match other Python packages.
This also updates the package to download from PyPI, and updates the package title, URL, and dependencies.
(cherry picked from commit 67a854aee28f6a360af1c595fdea396c9193b6e9)
=> [openwrt-23.05] click-log: Update to 0.4.0, rename source package

lang/python/python-jinja2/Makefile
Compile tested: none (cherry picked from #21225)
Description:
This renames the source package from Jinja2 to python-jinja2 to match other Python packages.
This also updates the package license files, title, and list of dependencies.
(cherry picked from commit 572387f0cb41f21c72a33533280a58723b7ed570)
=> [openwrt-23.05] Jinja2: Update to 3.1.2, rename source package

lang/python/python-markupsafe/Makefile
Compile tested: none (cherry picked from #21226)
Description:
This renames the source package from MarkupSafe to python-markupsafe to match other Python packages.
This also updates the package title and description.
(cherry picked from commit 5602cc85d393bef68bc7104529aee12937dbe4c0)
=> [openwrt-23.05] MarkupSafe: Update to 2.1.2, rename source package

lang/python/python-werkzeug/Makefile
Compile tested: none (cherry pick from #21227)
Description:
This renames the source package from Werkzeug to python-werkzeug to match other Python packages.
This also updates the package title, description, and list of dependencies.
(cherry picked from commit 574d43fca627bdaee03f43a1be10ba35dd9dd26d)
=> [openwrt-23.05] Werkzeug: Update to 2.3.4, rename source package

net/respondd/Makefile, net/respondd/files/respondd.config, net/respondd/files/respondd.init
Maintainer: me
Compile tested: mpc85xx-p1020 / mediatek-filogic
Run tested: Extreme WS-AP3825 / ASUS TUF-AX4200
Description:
respondd is a server distributing information within a network.
For doing so, respondd spawns a UDP socket (in Gluon 1001/udp), optionally joining a multicast group. When a request is received, the information requested is transmitted to the requester.
All information is organized in a non-hierarchical namespace. Each entry identifies a request name (e.g. statistics, nodeinfo, ...) implemented by at least one "provider" C module. The respond is the result of merging the outputs of all providers for the given request name.
=> respondd: add new package

lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 2.3.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.3.0
=> lua-eco: update to 2.3.0

net/nfs-kernel-server/Makefile
Compile tested: ipq807x/generic, r22604+4-a247f49794
Run tested: ipq807x/generic, r22604+4-a247f49794, mount nfs share
Description: remove libwrap from the dependencies since none of the binaries actually depend on it.
Cc: @neheb , @1715173329
=> nfs-kernel-server: remove libwrap from the dependencies

.github/workflows/multi-arch-test-build.yml
Maintainer: @aparcar (ping @neheb, @BKPepe, @1715173329)
Description:
https://github.com/openwrt/openwrt/pull/9980 was merged earlier this week.
=> CI: Add build test for riscv64_riscv64, sort build architectures in alphabetical order 

lang/golang/golang-values.mk
Maintainer: me
Compile tested: sifiveu-generic, 2023-06-02 snapshot sdk (compiled golang, obfs4proxy, tor-fw-firewall packages)
Run tested: none (can't get sifive_unleased image to load in qemu :sweat:)
Description:
Bring on the faillogs :laughing:
=> golang: Enable riscv64 for Go compiler and packages

admin/zabbix/Makefile
Description:
Zabbix moved the 6.2 directory from "stable" into "oldstable". This adds the "oldstable" URL to `PKG_SOURCE_URL`.
=> zabbix: Add "oldstable" source URL

lang/rust/Makefile, lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
Compile tested: current master, aarch64
Description: It should fix the musl-1.2 issues on time_t affected platforms.
=> rust: update to 1.70.0

lang/python/python3-bottle/Makefile
=> python3-bottle: Update to 0.12.25

lang/python/numpy/Makefile, lang/python/numpy/patches/001-unpin-build-dependencies.patch
Description:
Need to also fix build for GCC 13 + musl.
cherry picked from commit 8f176e30f3dae121e374be4ca7f641cc157ea152
=> [openwrt-23.05] numpy: bump version to 1.24.3

lang/python/python-typing-extensions/Makefile
Compile tested: armvirt-32, 2023-06-04 snapshot sdk
Description:
=> python-typing-extensions: Update to 4.6.3

lang/python/python3-bottle/Makefile
Fix build with Python 3.11.
cherry picked from commit a6980eb933bb3843afefc4d28d70811926d2f03e
=> [openwrt-23.05] python3-bottle: Update to 0.12.25

utils/gawk/Makefile
Disable mpfr detection to fix a build error due to (unncessary) missing dependency:
```
Package gawk is missing dependencies for the following libraries:
libgmp.so.10
libmpfr.so.6
```
=> gawk: disable mpfr detection

lang/python/python-passlib/Makefile
Compile tested: armvirt-32, 2023-06-04 snapshot sdk
Run tested: armvirt-32 (qemu), 2023-06-04 snapshot
Description:
This renames the source package from passlib to python-passlib to match other Python packages.
This also updates the package URL and list of dependencies.
=> passlib: Update to 1.7.4, rename source package

lang/rust/Makefile, lang/rust/patches/0001-Update-xz2-and-use-it-static.patch, lang/rust/patches/0002-Bumped-libc-version.patch
Fixes build with musl 1.2.4.
Upstream commit: https://github.com/rust-lang/rust/commit/032857e7e403f654129c45dc7e6718a9ad49e377
=> rust: bump libc to 0.2.146

lang/python/python-typing-extensions/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21275)
Description:
(cherry picked from commit b638f3f8c00950d3ff39bd7e5f31735b8a473120)
=> [openwrt-23.05] python-typing-extensions: Update to 4.6.3

net/knot/Makefile
Description:
- Release upgrade (https://www.knot-dns.cz/2023-06-06-version-327.html)
=> knot: update to version 3.2.7

lang/php8/Makefile
Maintainer: me
Run tested: no
Description:
The buildbots failed for the mentioned platform with the following error: (I shortened the pathnames and broke long lines a little bit for readability)
.../lib/gcc/riscv64-openwrt-linux-musl/12.3.0/../../../../
riscv64-openwrt-linux-musl/bin/ld: Zend/zend_execute_API.o: in function `.L533':
zend_execute_API.c:(.text+0x1b1c): undefined reference to `__atomic_exchange_1' .../riscv64-openwrt-linux-musl/bin/ld: Zend/zend_atomic.o:
in function `zend_atomic_bool_exchange':
zend_atomic.c:(.text+0xc): undefined reference to `__atomic_exchange_1' collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:350: sapi/cli/php] Error 1
Inspired by the blog post[1], linking to libatomic explicitly seems to do the trick.
[1] A …
=> php8: fix linking on riscv64 platform

lang/python/python-asgiref/Makefile
Maintainer: @peter-stadler 
Compile tested: armvirt-32, 2023-06-04 snapshot sdk
Run tested: armvirt-32, 2023-06-04 snapshot
Description:
This renames the source package to python-asgiref to match other Python packages.
This also updates the package title and URL.
=> python3-asgiref: Update to 3.7.2, rename source package

net/openvpn/Makefile, net/openvpn/files/openvpn.init
Maintainer:  @mkrkn 
Compile tested: ramips/mt7621
Run tested:  ramips/mt7621 Xiaomi MI router 3 Pro
Description:
In f8a8b71e26b9bdbf86fbb7d4d1482637af7f3ba4 introduced new hotplug events. For server config, ipchange hotplug event produces an error. So, make ipchange hotplug event for client only
Fixes https://github.com/openwrt/packages/issues/21200
=> openvpn: fix ipchange hotplug event

libs/avahi/Makefile, libs/avahi/patches/200-Fix-NULL-pointer-crashes-from-175.patch, libs/avahi/patches/201-Avoid-infinite-loop-in-avahi-daemon-by-handling-HUP-event.patch, libs/avahi/patches/202-avahi_dns_packet_consume_uint32-fix-potential-undefined-b.patch, libs/avahi/patches/203-Do-not-disable-timeout-cleanup-on-watch-cleanup.patch, libs/avahi/patches/204-Emit-error-if-requested-service-is-not-found.patch, libs/avahi/patches/205-conf-file-line-lengths.patch
 Compile tested: head, aarch64, arm, i386, x86_64
Description:
Imported patches included in debian and other package.
* 200-Fix-NULL-pointer-crashes-from-175.patch
CVE-2021-3502
A flaw was found in avahi 0.8-5. A reachable assertion is present in avahi_s_host_name_resolver_start function allowing a local attacker to crash the avahi service by requesting hostname resolutions through the avahi socket or dbus methods for invalid hostnames. The highest threat from this vulnerability is to the service availability.
* 201-Avoid-infinite-loop-in-avahi-daemon-by-handling-HUP-event.patch
CVE-2021-3468
A flaw was found in avahi in versions 0.6 up to 0.8. The event used to signal the termination of the client connection on the avahi Unix socket is …
=> avahi: Import patches for security fixes

lang/python/python-asgiref/Makefile
Maintainer: @peter-stadler
Compile tested: none (cherry picked from #21291)
Description:
This renames the source package to python-asgiref to match other Python packages.
This also updates the package title and URL.
(cherry picked from commit b098f2ac40b74117ed596cbecb2ab9abfa4388e1)
=> [openwrt-23.05] python3-asgiref: Update to 3.7.2, rename source package

net/acme-acmesh/Makefile
Important security fix.
Maintainer: me
=> acme-acmesh: Bump to version 3.0.6

net/acme/Makefile
Important security fix.
Maintainer: me
=> net/acme: Bump acme.sh to v3.0.6

utils/lcd4linux/Makefile
Description:
cherry picked from commit 917ea9d214fe4a6ef8e000c50761ac6d302f8162
=> [openwrt-23.05] lcd4linux: fix build error for custom build

libs/avahi/Makefile, libs/avahi/patches/200-Fix-NULL-pointer-crashes-from-175.patch, libs/avahi/patches/201-Avoid-infinite-loop-in-avahi-daemon-by-handling-HUP-event.patch, libs/avahi/patches/202-avahi_dns_packet_consume_uint32-fix-potential-undefined-b.patch, libs/avahi/patches/203-Do-not-disable-timeout-cleanup-on-watch-cleanup.patch, libs/avahi/patches/204-Emit-error-if-requested-service-is-not-found.patch, libs/avahi/patches/205-conf-file-line-lengths.patch
Maintainer: @thess 
Compile: 23.05, aarch64, arm, i386, x86_64
Description:
Imported patches included in debian and other package.
* 200-Fix-NULL-pointer-crashes-from-175.patch
CVE-2021-3502
A flaw was found in avahi 0.8-5. A reachable assertion is present in avahi_s_host_name_resolver_start function allowing a local attacker to crash the avahi service by requesting hostname resolutions through the avahi socket or dbus methods for invalid hostnames. The highest threat from this vulnerability is to the service availability.
* 201-Avoid-infinite-loop-in-avahi-daemon-by-handling-HUP-event.patch
CVE-2021-3468
A flaw was found in avahi in versions 0.6 up to 0.8. The event used to signal the termination of the client connection on the avahi Unix socket is not …
=> [23.05] avahi: Import patches for security fixes

libs/avahi/Makefile, libs/avahi/patches/200-Fix-NULL-pointer-crashes-from-175.patch, libs/avahi/patches/201-Avoid-infinite-loop-in-avahi-daemon-by-handling-HUP-event.patch, libs/avahi/patches/202-avahi_dns_packet_consume_uint32-fix-potential-undefined-b.patch, libs/avahi/patches/203-Do-not-disable-timeout-cleanup-on-watch-cleanup.patch, libs/avahi/patches/204-Emit-error-if-requested-service-is-not-found.patch, libs/avahi/patches/205-conf-file-line-lengths.patch
Maintainer: @thess 
Compile: 22.03, aarch64, arm, i386, x86_64
Description:
Imported patches included in debian and other package.
* 200-Fix-NULL-pointer-crashes-from-175.patch
CVE-2021-3502
A flaw was found in avahi 0.8-5. A reachable assertion is present in avahi_s_host_name_resolver_start function allowing a local attacker to crash the avahi service by requesting hostname resolutions through the avahi socket or dbus methods for invalid hostnames. The highest threat from this vulnerability is to the service availability.
* 201-Avoid-infinite-loop-in-avahi-daemon-by-handling-HUP-event.patch
CVE-2021-3468
A flaw was found in avahi in versions 0.6 up to 0.8. The event used to signal the termination of the client connection on the avahi Unix socket is not …
=> [22.03] avahi: Import patches for security fixes

libs/avahi/Makefile, libs/avahi/patches/200-Fix-NULL-pointer-crashes-from-175.patch, libs/avahi/patches/201-Avoid-infinite-loop-in-avahi-daemon-by-handling-HUP-event.patch, libs/avahi/patches/202-avahi_dns_packet_consume_uint32-fix-potential-undefined-b.patch, libs/avahi/patches/203-Do-not-disable-timeout-cleanup-on-watch-cleanup.patch, libs/avahi/patches/204-Emit-error-if-requested-service-is-not-found.patch, libs/avahi/patches/205-conf-file-line-lengths.patch
Maintainer: @thess 
Compile tested: 21.02, aarch64, arm, i386, x86_64
Description:
Imported patches included in debian and other package.
* 200-Fix-NULL-pointer-crashes-from-175.patch
CVE-2021-3502
A flaw was found in avahi 0.8-5. A reachable assertion is present in avahi_s_host_name_resolver_start function allowing a local attacker to crash the avahi service by requesting hostname resolutions through the avahi socket or dbus methods for invalid hostnames. The highest threat from this vulnerability is to the service availability.
* 201-Avoid-infinite-loop-in-avahi-daemon-by-handling-HUP-event.patch
CVE-2021-3468
A flaw was found in avahi in versions 0.6 up to 0.8. The event used to signal the termination of the client connection on the avahi Unix socket is …
=> [21.02] avahi: Import patches for security fixes

net/transmission/files/transmission.init
Run tested: OpenWrt 22.03.5 on WD My Book Live
Description:
It's not possible to configure custom Transmission web home as corresp. environment variable gets overwritten by the command that sets CA bundle environment variable.
The fix is to replace `procd_set_param` with `procd_append_param`.
=> transmission: Fix env variables passing

net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, test resolution with https-dns-proxy
Description:
* https://curl.se/changes.html#8_1_2
=> curl: update to 8.1.2

libs/gnu-efi/Makefile
update library + add new package containing efi programs provided by gnu-efi library.
Maintainer: me
=> gnu-efi: update to version 3.0.17

utils/crun/Makefile
Description:
Moved to from git to release version,
but release version does not have submodule
libocispec included, so additional download added.
Release notes: https://github.com/containers/crun/releases
=> crun: update v1.8.5

net/nginx/Makefile, net/nginx/patches/nginx/101-feature_test_fix.patch, net/nginx/patches/nginx/201-ignore-invalid-options.patch
Bump nginx to new 1.25.0 release.
Changes:
*) Feature: experimental HTTP/3 support.
Every patch automatically refreshed.
=> nginx: bump to new 1.25.0 release

net/aardvark-dns/Makefile
aardvark-dns v1.6.0 was released,
so instead of using git version, use release -
similarly like netavark.
Very much hasn't changed but list of changes
is in git commit log of aardvark-dns.
Maintainer: me
=> aardvark-dns: update to v1.6.0

libs/glib2/Makefile, libs/glib2/patches/006-c99.patch
Compile tested: mipsel_24kc_24kf master
Description:
A compiler bug (suspiciously) blocks gnulib compilation for mipsel_24kc_24kf. While we had this patch to disable gnulib, it was accidentally removed by 5d27631d9fbca076eb6377fc8c10f474ce9f4fea. Add it back to fix the long broken build for mipsel_24kc_24kf.
Fixes: #19511
=> glib2: disable gnulib printf

libs/glib2/Makefile, libs/glib2/patches/006-c99.patch
Compile tested: mipsel_24kc_24kf master
Description:
A compiler bug (suspiciously) blocks gnulib compilation for mipsel_24kc_24kf. While we had this patch to disable gnulib, it was accidentally removed by 5d27631d9fbca076eb6377fc8c10f474ce9f4fea. Add it back to fix the long broken build for mipsel_24kc_24kf.
Fixes: #19511
=> [23.05] glib2: disable gnulib printf

net/netavark/Makefile
netavark v1.6.0 was released, so instead of using
git version, use release. Does not contain very
much of changes, but list is available from netavark's commit log.
Maintainer: me
=> netavark: update to v1.6.0

libs/libmraa/Makefile
Maintainer: @blogic me
Compile tested: head, riscv64
Run tested: N/A 
Description:
Addresses buildbot errors
> CMake Error at CMakeLists.txt:193 (message):
>  Only x86, arm, mips, PERIPHERALMAN and mock platforms currently supported
=> libmraa: riscv64 not supported

net/cloudreve/Makefile
Maintainer: me
Description:
Updated cloudreve and added missing web frontend assets archive.
=> cloudreve: Update to 3.8.0

lang/php8/Makefile
Maintainer: me
Run tested: -
Description:
This reverts commit a2e76e49787e97253c02d72d27e3d304d68ff488.
Now that the issue is fixed on gcc side (see openwrt/openwrt@7b4a966), we can revert this workaround here.
=> php8: revert workaround to fix linking on riscv64 platform

.github/workflows/multi-arch-test-build.yml, lang/golang/golang-values.mk, lang/rust/rust-package.mk, lang/rust/rust-values.mk, libs/libmraa/Makefile
Maintainer: @aparcar for CI (Cc @jefferyto), @jefferyto for golang, @lu-zero for rust, @nxhack for libmraa
Run tested: ci
Description:
The support for riscv64 has been backported to 23.05 branch: openwrt/openwrt@4a281a778999, so let's enable it here too.
=> [openwrt-23.05] backport riscv64 support

net/strongswan/Makefile, net/strongswan/files/swanctl.init
Compile tested: x86_64, generic, HEAD (9519a62549)
Description:
Don't interpolate `"$1"` as the config name everywhere, and pick a better name for parsing ESP and IKE `crypto-proposal`'s.
=> strongswan: clean up parser

.github/workflows/multi-arch-test-build.yml, utils/collectd/Makefile, utils/qemu/Makefile
Maintainer: @hnyman @jow- for collected, @yousong for qemu, @aparcar for ci 
Description:
armvirt target has been renamed to armsr (Arm SystemReady),
so the dependency need to be changed as well.
Related to https://github.com/openwrt/openwrt/pull/12832
=> treewide: change references from armvirt to armsr

lang/python/python-ble2mqtt/Makefile, lang/python/python-bleak/Makefile, lang/python/python-dbus-fast/Makefile
Maintainer: me
Run tested: pending
Description: https://github.com/openwrt/packages/pull/21319 backport for 23.05. Update python-ble2mqtt, python-dbus-fast, python-bleak packages
=> [23.05] Update python-ble2mqtt, python-dbus-fast, python-bleak

lang/php8/Makefile
Maintainer: me
Run tested: mxs (I2SE Ducbkill)
Description:
(cherry picked from commit 1db2070f0092ea4675e04913e97f76a3fb1e6691)
=> [23.05] php8: update to 8.2.7

utils/mhz/Makefile
mhz is a tool for mathematically calculating the current CPU frequency, it has proven to be a really good help while developing CPU frequency scaling solutions as it allows to independently prove that scaling actually works.
Now that the author has added a license we can package it for all to use.
Compile tested: ipq807x
Run tested: ipq807x
=> mhz: add new package

utils/arp-whisper/Makefile, utils/arp-whisper/files/arp-whisper.init, utils/arp-whisper/files/etc/arp-whisper/arp-whisper
Maintainer: me
Compile tested: Qualcomm Atheros QCA956X ver 1 rev 0, TP-Link Archer C7 v5, OpenWrt 22.03.2 
Run tested: Qualcomm Atheros QCA956X ver 1 rev 0, TP-Link Archer C7 v5, OpenWrt 22.03.2 r19803-9a599fee93
Description:
arp-whisper listens to ARP requests on a network interface and responds to them based on a list of IP-MAC address mappings defined in a configuration file
I am the upstream author and maintainer of this software.
=> arp-whisper: Add new package

.github/workflows/multi-arch-test-build.yml, utils/collectd/Makefile, utils/qemu/Makefile
=> [openwrt-23.05] treewide: change references from armvirt to armsr

net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, test resolution with https-dns-proxy
Description:
* https://curl.se/changes.html#8_1_2
(cherry picked from commit 5afd8e088a1ad0b9b1074ac61460101a48e7e551)
=> [22.03] curl: update to 8.1.2

net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, test resolution with https-dns-proxy
Description:
* https://curl.se/changes.html#8_1_2
(cherry picked from commit 5afd8e088a1ad0b9b1074ac61460101a48e7e551)
=> [23.05] curl: update to 8.1.2

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, test proper fw objects (by @professor-jonny), test mdns object
Description:
bugfix: proper mdns object creation
bugfix: prevent fw errors by allowing custom interfaces in config
=> https-dns-proxy: update to 2023-05-25-2

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, test proper fw objects (by @professor-jonny), test mdns object
Description:
bugfix: proper mdns object creation
bugfix: prevent fw errors by allowing custom interfaces in config
(cherry picked from commit a31640ac7cfab78c75808e22fc7fc2da48bd8e7f)
=> [22.03] https-dns-proxy: update to 2023-05-25-2

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 22.03.5, test proper fw objects (by @professor-jonny), test mdns object
Description:
bugfix: proper mdns object creation
bugfix: prevent fw errors by allowing custom interfaces in config
(cherry picked from commit a31640ac7cfab78c75808e22fc7fc2da48bd8e7f)
=> [23.05] https-dns-proxy: update to 2023-05-25-2

net/nmap/patches/041-proxyfix.patch, net/nmap/patches/042-proxyfix.patch, net/nmap/patches/043-proxyfix.patch
Maintainer: @rockdrilla, @diizzyy, @nunojpg
Compile tested: x86 23.03.5
Run tested: x86 23.03.5
Description:
ncat utility from nmap package has a bug in 7.90 and 7.91 version which prevent it from working via proxy.
23.05 and master has updated version of nmap/ncat/nping 7.93, but 22.03 is still on 7.91. Apply the patches to fix the issue.
=> nmap: fix ncat proxy mode with upstream patches

net/modemmanager/Makefile, net/modemmanager/files/modemmanager.common, net/modemmanager/files/modemmanager.proto
Maintainer: @aleksander0m
Run tested: x86/64, APU3, OpenWrt latest
Description:
1. On small systems with many virtual devices, the modem manager sometimes could not start because it took too long until all devices for the modem were recognised. This is because all system events that are stored in the file events.cache have to be processed. To speed up the processing, all devices under /sys/devices/virtual are now filtered out so that they do not have to be processed.
2. If an alias name is used for the modem, then a check if the device exists in sysfs does not work. To fix this remove the check if the sysfs device exists. The protocoll handler already checks if the modemmanger is responsible for this device on the next line.
=> modemmanager: do not cache virtual device events and fix alias check

lang/node/Makefile, lang/node/patches/003-path.patch
Description:
Update to v18.16.1
* CVE-2023-30581: mainModule.__proto__ Bypass Experimental Policy Mechanism (High)
* CVE-2023-30585: Privilege escalation via Malicious Registry Key manipulation during Node.js installer repair process (Medium)
* CVE-2023-30588: Process interuption due to invalid Public Key information in x509 certificates (Medium)
* CVE-2023-30589: HTTP Request Smuggling via Empty headers separated by CR (Medium)
* CVE-2023-30590: DiffieHellman does not generate keys after setting a private key (Medium)
* OpenSSL Security Releases (Depends on shared library provided by OpenWrt)
* OpenSSL security advisory 28th March.
* …
=> node: June 20 2023 Security Releases

lang/node/Makefile, lang/node/patches/003-path.patch
 Compile tested: 23.05, aarch64, arm
Description:
Update to v18.16.1
* CVE-2023-30581: mainModule.__proto__ Bypass Experimental Policy Mechanism (High)
* CVE-2023-30585: Privilege escalation via Malicious Registry Key manipulation during Node.js installer repair process (Medium)
* CVE-2023-30588: Process interuption due to invalid Public Key information in x509 certificates (Medium)
* CVE-2023-30589: HTTP Request Smuggling via Empty headers separated by CR (Medium)
* CVE-2023-30590: DiffieHellman does not generate keys after setting a private key (Medium)
* OpenSSL Security Releases (Depends on shared library provided by OpenWrt)
* OpenSSL security advisory 28th March.
* OpenSSL security …
=> [23.05] node: June 20 2023 Security Releases

net/openelp/Makefile, net/openelp/files/openelp.init, net/openelp/test.sh
Maintainer: me
Compile tested: x86_64, OpenWrt SNAPSHOT, r23051-d6fef27f2dd4
Run tested: x86_64, OpenWrt SNAPSHOT, r23051-d6fef27f2dd4
Description:
OpenELP is an open source EchoLink proxy for Linux and Windows. It aims to be efficient and maintain a small footprint, while still implementing all of the features present in the official EchoLink proxy.
I am the upstream author and maintainer of this software.
=> openelp: Add new package

libs/c-ares/Makefile
Compile tested: head, aarch64, arm, i386, mipsel, x86_64
Run tested: aarch64 (qemu 8.0.2)
Description:
This is a security and bugfix release.
Security
o CVE-2023-32067. High. 0-byte UDP payload causes Denial of Service
o CVE-2023-31147. Moderate. Insufficient randomness in generation of DNS query IDs
o CVE-2023-31130. Moderate. Buffer Underwrite in ares_inet_net_pton()
o CVE-2023-31124. Low. AutoTools does not set CARES_RANDOM_FILE during cross compilation
Fixing libcares.pc
The pkg-config file libcares.pc in version 1.19.1 has been changed to be unsuitable for OpenWrt
and causes build errors with Openwrt packages that use libcares.
For this reason, libcares.pc was replaced.
=> c-ares: bump to 1.19.1

lang/python/python-ble2mqtt/Makefile
Maintainer: me
Run tested: pending
Description: This was broken when the init script was added in openwrt/packages@408502ee0.  Found when updating my device.
=> python-ble2mqtt: fix installation of python program

libs/c-ares/Makefile
Compile tested: 22.03, aarch64, arm, i386, x86_64
Run tested: aarch64 (qemu 8.0.2)
Description:
This is a security and bugfix release.
Security
o CVE-2023-32067. High. 0-byte UDP payload causes Denial of Service
o CVE-2023-31147. Moderate. Insufficient randomness in generation of DNS query IDs
o CVE-2023-31130. Moderate. Buffer Underwrite in ares_inet_net_pton()
o CVE-2023-31124. Low. AutoTools does not set CARES_RANDOM_FILE during cross compilation
Fixing libcares.pc
The pkg-config file libcares.pc in version 1.19.1 has been changed to be unsuitable for OpenWrt
and causes build errors with Openwrt packages that use libcares.
For this reason, libcares.pc was replaced.
(cherry picked from commit …
=> [22.03] c-ares: bump to 1.19.1

lang/python/python-ble2mqtt/Makefile
Run tested: pending
Description: This was broken when the init script was added in https://github.com/openwrt/packages/commit/408502ee0.
(cherry picked from commit 5cf30460555ba0687bbd61769c30edfb43e39949)
=> [23.05] python-ble2mqtt: fix installation of python program

libs/h2o/Makefile, libs/h2o/patches/700-no-mime-map.patch, libs/h2o/patches/800-smaller-write-buffer.patch
Maintainer: @Habbie 
Compile tested: TP-Link Archer C7 AC1750 v5, 19.07 and 21.02
Run tested: TP-Link Archer C7 AC1750 v5, 19.07 and 21.02
Description:
Right now the dnsdist package is the sole user of the h2o library, and given the orientation taken by the project (see https://github.com/h2o/h2o/issues/3230) I don't think this will change. dnsdist itself is planning on dropping the dependency in the next version, 1.9. Given dnsdist's needs, this pull request reduces the flash and runtime memory footprint of the h2o library, and thus of the dnsdist program, by:
- dropping the yaml dependency
- not initializing the big mime types map at startup
- reducing the default HTTP/2 buffer
Signed-off-by: Remi Gacogne <remi.gacogne@powerdns.com>
=> h2o: Reduce the flash and runtime memory footprint

net/vsftpd/Makefile
=> vsftpd: fix compilation with musl 1.2.4

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
- New major LTS release (https://www.mail-archive.com/haproxy@formilux.org/msg43600.html)
Maintainer: @gladiac
Compile tested: ramips/mt7621 OpenWrt 23.05-SNAPSHOT r23183-848759c236
Run tested: ramips/mt7621 OpenWrt 23.05-SNAPSHOT r23183-848759c236
=> haproxy: update to v2.8.0

libs/libpfring/Makefile, libs/libpfring/patches/0001-fix-cross-compiling.patch, libs/libpfring/patches/002-implement-probabilistic-sampling.patch, libs/libpfring/patches/100-fix-compilation-warning.patch
Maintainer: BangLang Huang | @neheb 
Compile tested: aarch64 armvirt
Run tested: no
Description:
- Update libpr-ring to released 8.2.0 for the linux 5.17 fix: https://github.com/ntop/PF_RING/commit/4e4480b88fe345e26951fa3ce4860f479685b91c
- Use a not-yet-released upstream patch for linux 5.18 fix: https://github.com/ntop/PF_RING/commit/7765d21fb64a32890f377941f64ba3ebce98bcf5
Linux changes:
- 5.16 https://github.com/torvalds/linux/commit/887069f424550ebdcb411166733e1d05002b58e4
- 5.17 https://github.com/torvalds/linux/commit/359745d78351c6f5442435f81549f0207ece28aa
- 5.18 https://github.com/torvalds/linux/commit/2655926aea9beea62c9ba80c032485456fd848f0
A `CONFIG_ALL_KMODS=y` build with work-in-progress kernel 6.1rc1 stopped on this package
=> libpfring bump to 8.4.0 for compile fix for linux 5.18

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
https://github.com/openwrt/packages/pull/21366
=> [23.05] haproxy: update to v2.8.0

net/bind/Makefile
Fixes CVEs:
- CVE-2023-2828: The overmem cleaning process has been improved, to prevent the cache from significantly exceeding the configured max-cache-size limit.
- CVE-2023-2911: A query that prioritizes stale data over lookup triggers a fetch to refresh the stale data in cache. If the fetch is aborted for exceeding the recursion quota, it was possible for named to enter an infinite callback loop and crash due to stack overflow.
The complete list of changes is available in the upstream release notes at
https://ftp.isc.org/isc/bind9/cur/9.18/doc/arm/html/notes.html#notes-for-bind-9-18-16
Maintainer: me
Compile tested: malter/master
Run tested: malta. Recursive name resolution with and without DNSSEC validation. `dig`, `rndc` functionality.
=> bind: bump to 9.18.16

net/knot/Makefile
Description:
- Release upgrade (https://www.knot-dns.cz/2023-06-26-version-328.html)
=> knot: update to version 3.2.8

net/coova-chilli/Makefile, net/coova-chilli/patches/011-kernel517.patch
Maintainer: @teslamint | @neheb
Compile tested: aarch64 armvirt
Run tested: no
Description:
Add patch to fix linux 5.17 removal of PDE_DATA: https://github.com/torvalds/linux/commit/359745d78351c6f5442435f81549f0207ece28aa
A `CONFIG_ALL_KMODS=y` build with work-in-progress kernel 6.1rc1 stopped on this package
=> coova-chilli compile fix for linux 5.17

lang/python/python-gnupg/Makefile
Maintainer: me
Run tested: armsr-armv7 (qemu), 2023-06-24 snapshot
Description:
This also removes the dependency on gnupg as there are two packages for gpg, gnupg and gnupg2; this library should work with either one.
=> python-gnupg: Update to 0.5.0

net/strongswan/Makefile
Compile tested: x86_64, generic, HEAD (9519a62549)
Description:
Update to 5.9.11 which has a lot of good fixes.
=> strongswan: Update to 5.9.11

net/inadyn/Makefile
Compile tested: mipsel_24kc, Netgear R6220, master
Run tested: mipsel_24kc, Netgear R6220, 23.05 branch, verified that updating dynamic dns address works
=> inadyn: update to 2.11.0

lang/python/python-libmodbus/Makefile
Maintainer: me
Run tested: armsr-armv7 (qemu), 2023-06-24 snapshot
Description:
This also adds a source package (python3-libmodbus-src).
=> python-libmodbus: Update to 0.6.2

lang/python/python-service-identity/Makefile
Maintainer: me
Run tested: armsr-armv7 (qemu, imported package in python only), 2023-06-24 snapshot
Description:
This adds new build dependencies as the package switched to pyproject.toml-based builds.
=> python-service-identity: Update to 23.1.0

lang/python/python-markupsafe/Makefile
Maintainer: me
Description:
The host build will be used for mako (to be added later).
=> python-markupsafe: Update to 2.1.3, add host build

net/netbird/Makefile
1. Release notes: https://github.com/netbirdio/netbird/releases/tag/v0.21.2 https://github.com/netbirdio/netbird/releases/tag/v0.21.3 https://github.com/netbirdio/netbird/releases/tag/v0.21.4 https://github.com/netbirdio/netbird/releases/tag/v0.21.5 https://github.com/netbirdio/netbird/releases/tag/v0.21.6 https://github.com/netbirdio/netbird/releases/tag/v0.21.7
2. Update GO_PKG_LDFLAGS, because of https://github.com/netbirdio/netbird/commit/292ee260ad564d1e65199b1cb3430b0cd7ba9646
3. Define the configuration file.
Signed-off-by: Salem Huang <solohoh@hotmail.com>
(cherry picked from commit b9b785b00ba59ec2fb3835492c3a78606812b3f1)
Compile tested: x86, openwrt-23.05/latest git
Run tested: aarch64_generic, openwrt-23.05/latest git
=> [openwrt-23.05] netbird: update to 0.21.7

net/netbird/Makefile
1. Release notes: 
https://github.com/netbirdio/netbird/releases/tag/v0.21.2
https://github.com/netbirdio/netbird/releases/tag/v0.21.3
https://github.com/netbirdio/netbird/releases/tag/v0.21.4
https://github.com/netbirdio/netbird/releases/tag/v0.21.5
https://github.com/netbirdio/netbird/releases/tag/v0.21.6
https://github.com/netbirdio/netbird/releases/tag/v0.21.7
2. Update GO_PKG_LDFLAGS, because of https://github.com/netbirdio/netbird/commit/292ee260ad564d1e65199b1cb3430b0cd7ba9646
3. Define the configuration file.
Compile tested: x86, latest git
Run tested: aarch64_generic, latest git
=> netbird: update to 0.21.7

net/sing-box/Makefile
Maintainer: me
Description:
This is a minor version update. Some new features require updating the server side to version 1.3.0 and later.
Changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.3.0
=> sing-box: update to 1.3.0

lang/python/click/Makefile, lang/python/itsdangerous/Makefile, lang/python/pyodbc/Makefile, lang/python/python-gnupg/Makefile, lang/python/python-libmodbus/Makefile, lang/python/python-markupsafe/Makefile, lang/python/python-werkzeug/Makefile
Compile tested: N/A (cherry picked from #21442)
Description:
This was requested in https://github.com/openwrt/packages/pull/21227#issuecomment-1567676980.
(cherry picked from commit b5dbf77501b4b4921ebd4d6abc6389875b64d3fa)
=> [openwrt-23.05] python-packages: Take over maintainership from Daniel Golle

multimedia/grilo-plugins/Makefile, multimedia/grilo/Makefile
Maintainer: me
Description:
This updates both the grilo and grilo-plugins packages to 0.3.16, which makes use of libsoup3 rather than libsoup. The plugins package had to drop the opensubtitles plugin because that plugin is not yet compatible with libsoup3.
=> Update grilo and grilo-plugins to 0.3.16

lang/python/python-websocket-client/Makefile
Maintainer: me
Description:
- 1.6.1
- Fix Dispatcher keyboard interrupt. Should solve reconnect loop with rel
- 1.6.0
- Fix teardown issue when ping thread is not properly ended
- Fix double ping wait time on first ping
- Minor typehints improvements
- 1.5.3
- Add logic to avoid error in the case where content-length header does not exist, bug introduced in 1.5.2
- Fix wsdump.py script typing, bug introduced in 1.5.2
- 1.5.2
- Add typehints
- Fix pytype errors
- Fix args passed to logging function
- Standardize PEP 3101 formatting
- Add more verbose exception for unsuccessful handshake
=> python-websocket-client: update to 1.6.1

utils/docker-compose/Makefile
=> docker-compose: Update to version 2.19.1

lang/python/python-service-identity/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21440)
Description:
This adds new build dependencies as the package switched to pyproject.toml-based builds.
(cherry picked from commit e1ef13a30c8e5bc687e917edce75f75c60e56a86)
=> [openwrt-23.05] python-service-identity: Update to 23.1.0

lang/python/python-libmodbus/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21460)
Description:
This also adds a source package (python3-libmodbus-src).
(cherry picked from commit 40b9f05a5818e3793271902771a8a6b9d93f8075)
=> [openwrt-23.05] python-libmodbus: Update to 0.6.2

lang/python/python-markupsafe/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21462)
Description:
The host build will be used for mako (to be added later).
(cherry picked from commit ff51716aaae66c3e307b07f019f17aee3e455d03)
=> [openwrt-23.05] python-markupsafe: Update to 2.1.3, add host build

lang/python/python-dotenv/Makefile
Maintainer: me
Description:
- 1.0.0:
- What's Changed: - Handle situations where the cwd does not exist. - Add python-decouple as a related project - Drop support for python 3.7, add python 3.12-dev
- 0.21.1:
- Added: - Use Python 3.11 non-beta in CI - Modernize variables code - Modernize main.py and parser.py code - Improve conciseness of cli.py and init.py - Improve error message for get and list commands when env file can't be opened - Updated Licence to align with BSD OSI template
=> python-dotenv: update to v1.0.0

lang/python/python-typing-extensions/Makefile
Compile tested: armsr-armv7, 2023-07-01 snapshot sdk
Description:
=> python-typing-extensions: Update to 4.7.1

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
=> haproxy: update to v2.8.1

lang/python/python-docker/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://docker-py.readthedocs.io/en/stable/change-log.html)
=> python-docker: Update to 6.1.3

lang/python/python-typing-extensions/Makefile
Maintainer: me, @ja-pa 
Compile tested: none (cherry picked from #21491)
Description:
(cherry picked from commit 207d01c3a918bf6452c5962660a605bb0d8b8d6b)
=> [openwrt-23.05] python-typing-extensions: Update to 4.7.1

libs/liburing/Makefile
Maintainer: Christian Lachner <gladiac@gmail.com> (**/me**)
Compile tested: mipsel, mips74k, ipq806x, x86, arc700
Description: Update to v2.4
- Updated download URL and hash
=> liburing: Update to v2.4

net/nginx/Makefile
Maintainer: Thomas Heil <heil@terminal-consulting.de> & Ansuel Smith <ansuelsmth@gmail.com>
Run tested: master x86-64
Description:
This PR adds [ngx_http_geoip2_module](https://github.com/leev/ngx_http_geoip2_module) to suppport MaxMind GeoIP2 databases, which can be freely downloaded, for instance with a script like below.
I was never able to get anything out of the current geoip module, whereas with this I have access logs with city & country, and we already have [libmaxminddb](https://github.com/openwrt/packages/tree/master/libs/libmaxminddb) in the tree.
```
❯ cat /etc/update-geodb.sh
#!/bin/sh
set -e
URL=https://cdn.jsdelivr.net
_url1="${URL}$( curl ${URL}/npm/geolite2-city/    2>/dev/null | grep 'npm/geolite2-city@.\+GeoLite2-City.mmdb.gz'       | cut …
```
=> nginx: add support for MaxMind GeoIP2 databases

net/nginx/Config_ssl.in, net/nginx/Makefile
Maintainer: Thomas Heil <heil@terminal-consulting.de> Ansuel Smith <ansuelsmth@gmail.com>
Compile tested: Xiaomi AX3600 ARM64
Run tested: Xiaomi AX3600 ARM64 on latest main/master
Description:
This commit updates nginx to 1.25.1 and adds support for http/3. This is an experimental version and isn't fully supported because nginx is being built with the regular OpenSSL and the regular one doesn't support quic.
Signed-off-by: Tiago Gaspar <tiagogaspar8@gmail.com>
=> nginx: update and add quic module

net/nginx/Makefile
We currently have a more or less circular dependency with nginx ssl and
full variant.
FULL variant depends on every nginx module. Every nginx module depends
on nginx-ssl.
Since nginx-full depends on an nginx module, nginx-ssl is installed as
module depends on it and then the installation fails as nginx-full
conflicts with nginx-ssl.
nginx-full in it's meaning is nginx built with every config selected and
it should not have module as dependency. In fact an user should always
install them separetly as while other things, local modification to the
nginx config file are required to include the just installed module.
To fix this circular dependency problem, drop the dependency on every
nginx module for FULL variant.
Fixes: https://github.com/openwrt/packages/issues/21300
Signed-off-by: …
=> nginx: don't install all module for FULL variant

net/net-mtools/Makefile, net/net-mtools/patches/001-mreceive-refactor-multicast-joining-to-separate-func.patch, net/net-mtools/patches/002-mreceive-join-IGMP-group-by-interface.patch, net/net-mtools/patches/003-mreceive-support-IPv6.patch, net/net-mtools/patches/004-msend-support-IPv6.patch, net/net-mtools/patches/005-mreceive-msend-add-new-I-option-to-the-help-text.patch, net/net-mtools/patches/006-msend-send-a-limited-number-of-test-packets.patch, net/net-mtools/patches/100-mreceive-msend-fix-wrong-version-in-v-output.patch, net/net-mtools/test.sh
Add new package to debug multicast setups. This is required to use kselftests script for network testing.
net-mtools is used instead of mtools as it does conflicts with another package that is also called mtools.
=> net-mtools: Add new package to debug multicast setups

net/frp/Makefile
Run tested: (x86_64, OpenWrt snapshot)
XTCP is incompatible with previous versions since 0.49.0.
Changelog:
https://github.com/fatedier/frp/releases/tag/v0.49.0
https://github.com/fatedier/frp/releases/tag/v0.50.0
https://github.com/fatedier/frp/releases/tag/v0.51.0
=> frp: update to 0.51.0

admin/btop/Makefile
Maintainer: Tianling Shen <cnsztl@immortalwrt.org>
Description:
Fix building with `USE_LTO` enabled:
```
Linking and optimizing binary...
../../../staging_dir/toolchain-x86_64_gcc-12.3.0_musl/include/fortify/stdio.h: In function '__to_xstring.constprop':
../../../staging_dir/toolchain-x86_64_gcc-12.3.0_musl/include/fortify/stdio.h:70:28: error: inlining failed in call to 'always_inline' 'vsnprintf': function body can be overwritten at link time
70 | _FORTIFY_FN(vsnprintf) int vsnprintf(char *__s, size_t __n, const char *__f,
|                            ^
/mnt/caches/openwrt/openwrt-master-x64/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/x86_64-openwrt-linux-musl/include/c++/12.3.0/ext/string_conversions.h:111:32: note: called from …
```
=> btop: opt out of lto usage

libs/libre2/Makefile
Fixes compilation with GCC13
Maintainer:
=> libre2: update to 2023-02-01

net/snort3/Makefile
Upstream bump
Build-tested: x86_64/AMD 5800U
Run-tested: x86_64/AMD 5800U
=> snort3: update to 3.1.65.0

net/tailscale/Makefile
=> tailscale: update to 1.44.0

libs/nlohmannjson/Makefile
Compile tested: OpenWRT-23.05-rc2, arm_cortex-a7_neon-vfpv4, mips_24kc
Run tested: arm_cortex-a7_neon-vfpv4 (Linksys MR8300), mips_24kc (tplink_archer-a7), OpenWrt 23.05-rc2)
* Update package nlohmannjson to version 3.11.2.
* Version 3.11.2 is source compatible with 3.10.2 so no package should fail to compile
Signed-off-by: Volker Christian <me@vchrist.at>
=> Nlohmannjson: Update to version 3.11.2

libs/libaio/Makefile
Maintainer:
Description:
Fix building with `USE_LTO` enabled.
```
ccache x86_64-openwrt-linux-musl-gcc -shared -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -ffile-prefix-map=/home/jmarcet/src/openwrt/openwrt-master-x64/build_dir/target-x86_64_musl/libaio-0.3.113=libaio-0.3.113 -ffunction-sections -fdata-sections -flto=auto -fno-fat-lto-objects -Wformat -Werror=format-security -DPIC -fpic -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro  -I/home/jmarcet/src/openwrt/openwrt-master-x64/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/usr/include -I/home/jmarcet/src/openwrt/openwrt-master-x64/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/include/fortify -I/home/jmarcet/src/openwrt/openwrt-master-x64/staging_dir/toolc …
```
=> libaio: opt out of lto usage

utils/sedutil/Makefile, utils/sedutil/patches/010-gcc13.patch
=> sedutil: fix compilation with GCC13

lang/python/python-editables/Makefile
Maintainer: me
Compile tested: armsr-armv7, 2023-07-09 snapshot sdk
Description:
The build backend was changed from setuptools to flit-core.
=> python-editables: Update to 0.4

lang/python/python-click/Makefile
Maintainer: me
Compile tested: armsr-armv7, 2023-07-09 snapshot sdk
Description:
This renames the source package to python-click to match other Python packages.
This also updates the package dependencies, licence file, package title and description.
=> click: Update to 8.1.4, rename source package

net/ooniprobe/Makefile
Compile tested: armsr-armv7, 2023-07-09 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-07-09 snapshot
Description:
This version includes support for Go 1.20 (specifically 1.20.5).
This also:
* Adds a workaround for musl 1.2.4 compatibility in [mattn/go-sqlite3][1]
* Sets `GO_PKG_BUILD_PKG` to build the main binary (ooniprobe) only
* Updates the package license; the project was relicensed in [3.13.0][2]
[1]: https://github.com/mattn/go-sqlite3/issues/1164
[2]: https://github.com/ooni/probe-cli/pull/446
=> ooniprobe: Update to 3.18.0

sound/shairport-sync/Makefile, sound/shairport-sync/files/shairport-sync.init
'name' may contains '%h' or '%v', printf will fail on that
Maintainer: Ted Hess <thess@kitschensync.net>, Mike Brady <mikebrady@eircom.net>
Description:
=> shairport-sync: fix init script

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Description:
(cherry picked from commit 75bd8ebde41dc1959ee4cdd0d8da51df1a417b04)
=> [23.05] php8: update to 8.2.8

net/ooniprobe/Makefile
Compile tested: none (cherry picked from #21557)
Description:
This version includes support for Go 1.20 (specifically 1.20.5).
This also:
* Adds a workaround for musl 1.2.4 compatibility in [mattn/go-sqlite3][1]
* Sets `GO_PKG_BUILD_PKG` to build the main binary (ooniprobe) only
* Updates the package license; the project was relicensed in [3.13.0][2]
[1]: https://github.com/mattn/go-sqlite3/issues/1164
[2]: https://github.com/ooni/probe-cli/pull/446
(cherry picked from commit dc7382ec65c4f22bb1e363f7d89c3c427ade4b5d)
=> [openwrt-23.05] ooniprobe: Update to 3.18.0

lang/python/python-click/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21553)
Description:
This renames the source package to python-click to match other Python packages.
This also updates the package dependencies, licence file, package title and description.
(cherry picked from commit 5710f272dbef52f9186fc36c022071cee7789651)
=> [openwrt-23.05] click: Update to 8.1.4, rename source package

lang/python/python-editables/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21555)
Description:
The build backend was changed from setuptools to flit-core.
(cherry picked from commit 9a5f66acc37d77ddfe98b87fcdcbd260365c9c70)
=> [openwrt-23.05] python-editables: Update to 0.4

lang/python/python-mako/Makefile
Maintainer: me
Compile tested: armsr-armv7/x86-64, 2023-07-09 snapshot sdks
Description:
Mako was removed in 60ce07b9a1d5c7a53297f177f10af68f3304be9e; at the time we were using host pip to install host Python packages and so having this package was not necessary.
With the move away from host pip and toward proper host packages, it would be better to have a Mako host-only package here to support the mesa package in the video feed.
This re-imports the package from the abandoned packages feed, updates the makefile with current Python package conventions, and updates the package to the latest version.
=> python-mako: Re-import host-only package from abandoned packages repo

lang/python/python-babel/Makefile
Compile tested: armsr-armv7, 2023-07-09 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-07-09 snapshot
Description:
Also updated dependencies for the new version.
=> python-babel: Update to 2.12.1, add host build

lang/golang/golang-build.sh, lang/golang/golang-compiler.mk, lang/golang/golang-host-build.mk, lang/golang/golang-package.mk, lang/golang/golang-values.mk, lang/golang/golang/Makefile, lang/golang/golang/files/go-gcc-helper, lang/golang/golang/test.sh
Maintainer: me
Description:
Includes fix for CVE-2023-29406 (net/http: insufficient sanitization of Host header).
This also updates the copyright information for various Go packaging files.
=> golang: Update to 1.20.6

utils/jq/Makefile, utils/jq/patches/0010-C99-compatibility-enhancements-for-the-configure-scr.patch
Commit 4bb18b04 added _GNU_SOURCE to jq's Makefile to fix a segfault. This has since been fixed upstream, so this commit backports the upstream patch instead. This keeps things closer to upstream, and it will prevent the Makefile from containing a redundant fix once upstream releases the next version.
=> jq: remove _GNU_SOURCE from Makefile and instead backport patch

lang/golang/golang-build.sh, lang/golang/golang-compiler.mk, lang/golang/golang-host-build.mk, lang/golang/golang-package.mk, lang/golang/golang-values.mk, lang/golang/golang/Makefile, lang/golang/golang/files/go-gcc-helper, lang/golang/golang/test.sh
Maintainer: me
Compile tested: none (cherry picked from #21590)
Description:
Includes fix for CVE-2023-29406 (net/http: insufficient sanitization of Host header).
This also updates the copyright information for various Go packaging files.
(cherry picked from commit 8000a7f7691e733dd27dea30bed32dfc3d805ffb)
=> [openwrt-23.05] golang: Update to 1.20.6

lang/python/python-mako/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21566)
Description:
Mako was removed in 60ce07b9a1d5c7a53297f177f10af68f3304be9e; at the time we were using host pip to install host Python packages and so having this package was not necessary.
With the move away from host pip and toward proper host packages, it would be better to have a Mako host-only package here to support the mesa package in the video feed.
This re-imports the package from the abandoned packages feed, updates the makefile with current Python package conventions, and updates the package to the latest version.
(cherry picked from commit 666ea9397789b79aca402cbdab7d090f78623845)
=> [openwrt-23.05] python-mako: Re-import host-only package from abandoned packages repo

lang/rust/Makefile, lang/rust/patches/0001-Update-xz2-and-use-it-static.patch, lang/rust/patches/0002-Bumped-libc-version.patch, lang/rust/rust-values.mk
Maintainer: @lu-zero / cc: @1715173329 
Run tested: 
Description:
This merges the changes from pull-request #21571 into the `openwrt-23.05` branch by cherry picking these commits from the `master` branch:
```
git cherry-pick -x f489e019ac4a15e974518d9928ef913a157d135a
git cherry-pick -x 971d326768b962dc4acdea181ae58b72c609e119
```
=> [openwrt-23.05] rust: Update to 1.71.0 + compile host package per target

net/transmission/Makefile, net/transmission/files/transmission-daemon.json
Compile tested: no need, it's a config file
Run tested: Raspberry Pi 3B+, OpenWrt r22977
Description:
Fixes many crashes on my system. I found this missing syscall by looking at auditd logs. Unfortunately I didn't keep them.
=> transmission: add ftruncate syscall to seccomp

utils/cpusage/Makefile
Maintainer: @thuehn
Description:
Remove deprecated AUTORELEASE.
Commit 0c10c224be81 only handles the case where AUTORELEASE is used in PKG_RELEASE thus this package was left behind. Let's fix this up.
This packages is untouched since 23.05 branching. It should be straightforward applying this patch also to that branch.
=> cpusage: remove AUTORELEASE

net/snowflake/Makefile, net/snowflake/patches/0001-Bump-minimum-required-version-of-go.patch, net/snowflake/patches/0002-Update-dependencies.patch
Tor projects tries to migrate away from git.torproject.org [0,1]. We
need to adjust PKG_SOURCE and GO_PKG name.
Changelog:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/2fa8fd9188078eaa169f1edd16815deae4004c6c
[0] - https://gitlab.torproject.org/tpo/anti-censorship/team/-/issues/86
[1] - https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/82cc0f38f73c4ca4e12d22173562a092ebd4dea0
Maintainer: @dangowrt, me
=> snowflake: update to 2.6.0

net/snowflake/Makefile, net/snowflake/patches/0001-Bump-minimum-required-version-of-go.patch, net/snowflake/patches/0002-Update-dependencies.patch
Tor projects tries to migrate away from git.torproject.org [0,1]. We need to adjust PKG_SOURCE and GO_PKG name. Further, we need to backport patches to fix compiling on riscv64, so add:
- 0001-Bump-minimum-required-version-of-go.patch
- 0002-Update-dependencies.patch
Changelog:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/2fa8fd9188078eaa169f1edd16815deae4004c6c
[0] - https://gitlab.torproject.org/tpo/anti-censorship/team/-/issues/86
[1] - https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/82cc0f38f73c4ca4e12d22173562a092ebd4dea0
(cherry picked from commit 0281f7594b31a5a947c26b895343daedc8a808e8)
Maintainer: me
=> [23.05] snowflake: update to 2.6.0

net/snowflake/Makefile, net/snowflake/patches/0001-Bump-minimum-required-version-of-go.patch, net/snowflake/patches/0002-Update-dependencies.patch
Tor projects tries to migrate away from git.torproject.org [0,1]. We need to adjust PKG_SOURCE and GO_PKG name. Further, we need to backport patches to fix compiling on riscv64, so add:
- 0001-Bump-minimum-required-version-of-go.patch
- 0002-Update-dependencies.patch
Changelog:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/2fa8fd9188078eaa169f1edd16815deae4004c6c
[0] - https://gitlab.torproject.org/tpo/anti-censorship/team/-/issues/86
[1] - https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/82cc0f38f73c4ca4e12d22173562a092ebd4dea0
(cherry picked from commit 0281f7594b31a5a947c26b895343daedc8a808e8)
Run tested: …
=> [22.03] snowflake: update to 2.6.0

multimedia/v4l2camera/Makefile, multimedia/v4l2camera/files/v4l2camera.config, multimedia/v4l2camera/files/v4l2camera.init, multimedia/v4l2camera/patches/001_live555_sprintf_format.patch
Maintainer: @mpromonet
Compile tested: (sunxi, nanopi neo air, OpenWrt latest)
Run tested: (sunxi, nanopi neo air, OpenWrt latest, enable service, start it and connect to http server, connect with vlc to rtsp server)
Description:
Add v4l2camera that provide a simple web server to RTSP server feeded with V4L2 capture device
=> v4l2camera: add new package

utils/docker-compose/Makefile
=> docker-compose: Update to version 2.20.2

lang/python/python-unidecode/Makefile
Description:
This renames the source package to python-unidecode to match other Python packages.
=> python3-unidecode: Update to 1.3.6, rename source package

lang/python/python-netifaces/Makefile
Description:
This renames the source package to python-netifaces to match other Python packages.
=> python3-netifaces: Update to 0.11.0, rename source package

lang/python/python-babel/Makefile
Compile tested: none (cherry picked from #21581)
Description:
Also updated dependencies for the new version.
(cherry picked from commit 0174cea69757589be50b9dd774394ce18cf61dae)
=> [openwrt-23.05] python-babel: Update to 2.12.1, add host build

net/snort3/Makefile
Upstream bump
Maintainer:  @flyn-org
=> snort3: update to 3.1.66.0

lang/rust/Makefile
Description:
```
When user runs `make clean` command, everything in `$(STAGING_DIR)`
(where we installed rust) will be removed, but `$(BUILD_DIR_HOST)`
(where we compiled rust and stored build stage) is untouched.
So when user starts a new build after that, OpenWrt buildroot will
still consider `rust` is installed already, resulting the build error
"cargo: command not found".
Fix this by moving to target build dir as well.
Fixes: f489e019ac4a ("rust: compile host package per target")
```
cc @brocaar
=> rust: put host build dir to target build dir

lang/node/Makefile, lang/node/patches/990-delete_unnecessary_libraries_for_host_execute.patch, lang/node/patches/991-v8_zlib_support.patch, lang/node/patches/992-v8_add_include_dirs.patch, lang/node/patches/999-localhost-no-addrconfig.patch, lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch
Run tested: (qemu 8.0.3) aarch64
Description:
Update to v18.17.0
*Ada 2.0
Node.js v18.17.0 comes with the latest version of the URL parser, Ada. This update brings significant performance improvements to URL parsing, including enhancements to the url.domainToASCII and url.domainToUnicode functions in node:url.
*Web Crypto API
Web Crypto API functions' arguments are now coerced and validated as per their WebIDL definitions like in other Web Crypto API implementations. This further improves interoperability with other implementations of Web Crypto API.
=> node: bump to v18.17.0

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.conf.update, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, start, update config, pause
Description:
* fix permission to dnsmasq files for ad-blocking
* add pause function to pause the ad-blocking temporarily
* introduce pause_timeout option to control default pause time
* update default config and config-update file
* use $param instead of $1 in adb_start()
=> simple-adblock: dnsmasq access bugfix & misc improvements

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.conf.update, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, start, update config, pause
Description:
* fix permission to dnsmasq files for ad-blocking
* add pause function to pause the ad-blocking temporarily
* introduce pause_timeout option to control default pause time
* update default config and config-update file
* use $param instead of $1 in adb_start()
(cherry picked from commit dea274cc333ab99e42b569bf412c23e0dfd8a87a)
=> [22.03] simple-adblock: dnsmasq access bugfix & misc improvements

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.conf, net/simple-adblock/files/simple-adblock.conf.update, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, start, update config, pause
Description:
* fix permission to dnsmasq files for ad-blocking
* add pause function to pause the ad-blocking temporarily
* introduce pause_timeout option to control default pause time
* update default config and config-update file
* use $param instead of $1 in adb_start()
(cherry picked from commit dea274cc333ab99e42b569bf412c23e0dfd8a87a)
=> [23.05] simple-adblock: dnsmasq access bugfix & misc improvements

net/nebula/Makefile, net/nebula/files/nebula.init, net/nebula/files/nebula.proto, net/nebula/test.sh
Maintainer: me
Compile tested: x86-64, Sophos XG-135r3, OpenWrt 23.05.0-rc1
Run tested: x86-64, Sophos XG-135r3, OpenWrt 22.03.5, test connectivity
Description:
* update binaries to 1.7.2
* move sharedMemoryOutput variable declaration into output function as it doesn't need to be global
* rename parse_yaml function to yaml_parse
* add TODOs for future development
=> nebula: update to 1.7.2 (and cosmetic fixes)

net/nebula/Makefile, net/nebula/files/nebula.init, net/nebula/files/nebula.proto, net/nebula/test.sh
Maintainer: me
Compile tested: x86-64, Sophos XG-135r3, OpenWrt 23.05.0-rc1
Run tested: x86-64, Sophos XG-135r3, OpenWrt 22.03.5, test connectivity
Description:
* update binaries to 1.7.2
* move sharedMemoryOutput variable declaration into output function as it doesn't need to be global
rename parse_yaml function to yaml_parse
* add TODOs for future development
(cherry picked from commit 204e6076d352d5c7232e18de0fcf58503ef6ae9b)
=> [23.05] nebula: update to 1.7.2 (and cosmetic fixes)

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, start/stop
=> https-dns-proxy: improve CLI messaging

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, start/stop
(cherry picked from commit 649fbcf9fcab34df3d39b0642cd5b566eefb569e)
=> [22.03] https-dns-proxy: improve CLI messaging

net/https-dns-proxy/Makefile, net/https-dns-proxy/files/https-dns-proxy.init
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, start/stop
(cherry picked from commit 649fbcf9fcab34df3d39b0642cd5b566eefb569e)
=> [23.05] https-dns-proxy: improve CLI messaging

utils/base16384/Makefile, utils/base16384/test.sh
Maintainer: me
Compile tested: x86/64, Generic PC, OpenWrt 22.03.2 r19803-9a599fee93
Run tested: x86/64, Generic PC, OpenWrt 22.03.2 r19803-9a599fee93
Signed-off-by: 源 文雨 <fumiama@foxmail.com>
=> base16384: bump to version 2.2.4

libs/easyloggingpp/Makefile
Maintainer: me@vchrist.at
Changelog from upstream:
- Ensuring the build on ARM64 works
- Update gtest and cmake now requires C++14 because of that
- arm_cortex-a7_neon-vfpv4, 
- mips_24kc, 
- aarch64_cortex-a53
Run tested: 
- Linksys MR8300 (arm_cortex-a7_neon-vfpv4)
- GL.iNet GL-A1800 (arm_cortex-a7_neon-vfpv4)
- TP-Link Archer A7 (mips_24kc),
- GL.iNet GL-MT3000 (aarch64_cortex-a53)
=> easyloggingpp: Update version to 9.97.1

net/modemmanager/Makefile, net/modemmanager/README.md, net/modemmanager/files/modemmanager.proto
Compile tested: no (changed bash script only)
Run tested: ramips, DWR-921, openwrt-19.07 branch (git-21.044.30835-34e0d65) / OpenWrt 19.07.7 r11306-c4a6851c72
Tested connection using netifd with and without plmn setting
Description: 
This change allows to set network operator MCC:MNC and connect to different network with better signal quality and speed.
=> modemmanager: support setting plmn

net/modemmanager/Makefile, net/modemmanager/files/modemmanager.proto
Maintainer: @mips171 @aleksander0m 
Compile tested: not needed script changes
Run tested: x86_64 / lantiq_xrx200
Description:
- Do not set proto_notify_error on teardown
- Add missing proto_init_update in teardown
=> modemmanager: improve teardown handling

lang/python/python-netifaces/Makefile
Compile tested: none (cherry picked from #21604)
Description:
This renames the source package to python-netifaces to match other Python packages.
(cherry picked from commit 935f791e764b350facee5cea4463ef78db700059)
=> [openwrt-23.05] python3-netifaces: Update to 0.11.0, rename source package

lang/python/python-unidecode/Makefile
Compile tested: none (cherry picked from #21608)
Description:
This renames the source package to python-unidecode to match other Python packages.
(cherry picked from commit 35d6cdf8bbbecb3795102dab5d2f22e86e43218f)
=> [openwrt-23.05] python3-unidecode: Update to 1.3.6, rename source package

net/knxd/Makefile, net/knxd/patches/0100-version.patch
Maintainer: me
Description:
new upstream release 0.14.59
=> knxd: new upstream version 0.14.59

net/transmission/Makefile, net/transmission/files/transmission-daemon.json
Compile tested: no need, it's a config file
Run tested: Raspberry Pi 3B+, OpenWrt r22977
Description:
Fixes this crash:
```
root@RPi3OpenWrt:/# grep -i seccomp /var/log/audit/audit.log
type=SECCOMP msg=audit(1689503903.597:16): auid=4294967295 uid=224 gid=1012 ses=4294967295 pid=1752 comm="transmission-da" exe="/usr/bin/transmission-daemon" sig=31 arch=c00000b7 syscall=285 compat=0 ip=0x7fa3b0eefc code=0x80000000
root@RPi3OpenWrt:/# ausyscall 285
copy_file_range
root@RPi3OpenWrt:/#
```
=> transmission: add copy_file_range syscall to seccomp

lang/python/python-execnet/Makefile
Description:
The package changed to the hatchling build backend and removed the dependency on apipkg.
=> python-execnet: Update to 2.0.2

lang/python/python-async-timeout/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-07-16 snapshot
Description:
=> python-async-timeout: Update to 4.0.2

lang/python/python-maxminddb/Makefile
Description:
This renames the source package to python-maxminddb to match other Python packages.
=> python3-maxminddb: Update to 2.4.0, rename source package

lang/python/python-apipkg/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-07-16 snapshot
Description:
=> python-apipkg: Update to 3.0.1

lang/python/python-pyroute2/Makefile
Maintainer: @mmtj
Description:
This renames the source package to python-pyroute2 to match other Python packages.
This also updates/simplifies the package dependencies.
=> python3-pyroute2: Update to 0.7.9, rename source package

lang/python/python-aiohttp/Makefile, lang/python/python-aiosignal/Makefile, lang/python/python-charset-normalizer/Makefile, lang/python/python-frozenlist/Makefile
Maintainer: @BKPepe (python-aiohttp), me (new dependencies)
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-07-16 snapshot
Description:
This updates aiohttp to 3.8.5 and adds new dependencies (charset-normalizer, frozenlist, aiosignal). This version of aiohttp also depends on async-timeout >= 4 (#21610).
=> python-aiohttp: Update to 3.8.5, add new dependencies

lang/python/python-sqlparse/Makefile
Maintainer: @peter-stadler
Run tested: armsr-armv7 (qemu), 2023-07-16 snapshot 
Description:
This renames the source package to python-sqlparse to match other Python packages.
This also updates the build dependencies; package now uses the flit-core build backend.
=> python3-sqlparse: Update to 0.4.4, rename source package

lang/python/python-awesomeversion/Makefile
=> python-awesomeversion: Update to 23.5.0, update dependencies

lang/python/python-aiohttp/Makefile, lang/python/python-aiosignal/Makefile, lang/python/python-charset-normalizer/Makefile, lang/python/python-frozenlist/Makefile
Maintainer: @BKPepe (python-aiohttp), me (new dependencies)
Compile tested: none (cherry-picked from #21611)
Description:
This updates aiohttp to 3.8.5 and adds new dependencies (charset-normalizer, frozenlist, aiosignal). This version of aiohttp also depends on async-timeout >= 4 (#21656).
=> [openwrt-23.05] python-aiohttp: Update to 3.8.5, add new dependencies

lang/python/python-async-timeout/Makefile
Compile tested: none (cherry picked from #21610)
Description:
(cherry picked from commit e0c13a145d60676d85fff6bad6c018d204f19856)
=> [openwrt-23.05] python-async-timeout: Update to 4.0.2

lang/python/python-sqlparse/Makefile
Maintainer: @peter-stadler
Compile tested: none (cherry picked from #21607)
Description:
This renames the source package to python-sqlparse to match other Python packages.
This also updates the build dependencies; package now uses the flit-core build backend.
(cherry picked from commit aa44ed23ce0da733c0580719b1f21a6adbd848f1)
=> [openwrt-23.05] python3-sqlparse: Update to 0.4.4, rename source package

lang/python/python-execnet/Makefile
Compile tested: none (cherry picked from #21612)
Description:
The package changed to the hatchling build backend and removed the dependency on apipkg.
(cherry picked from commit 0218c9067a3847ecf779213d722e6f0c909d1203)
=> [openwrt-23.05] python-execnet: Update to 2.0.2

lang/python/python-pyroute2/Makefile
Maintainer: @mmtj
Compile tested: none (cherry picked from #21606)
Description:
This renames the source package to python-pyroute2 to match other Python packages.
This also updates/simplifies the package dependencies.
(cherry picked from commit c5c02c060bd9480bb47cd5f9631f72d099c4cbe8)
=> [openwrt-23.05] python3-pyroute2: Update to 0.7.9, rename source package

lang/python/python-awesomeversion/Makefile
Compile tested: none (cherry picked from #21615)
Description:
(cherry picked from commit 446e52ab26da9b619d8d7c1fe3790bea1aa2a606)
=> [openwrt-23.05] python-awesomeversion: Update to 23.5.0, update dependencies

lang/python/python-atomicwrites/Makefile
Compile tested: none (cherry picked from #21614)
Description:
(cherry picked from commit d5ac6e103eb11d29f4e822fadb727225e0e80992)
=> [openwrt-23.05] python-atomicwrites: Update to 1.4.1

lang/python/python-apipkg/Makefile
Compile tested: none (cherry picked from #21613)
Description:
(cherry picked from commit bbf35edc5f5181ac8b1762a1c448d1b9be05c0f1)
=> [openwrt-23.05] python-apipkg: Update to 3.0.1

lang/python/python-maxminddb/Makefile
Compile tested: none (cherry picked from #21602)
Description:
This renames the source package to python-maxminddb to match other Python packages.
(cherry picked from commit ca7fdf61dc128ab80917d8c415bd9676462d04ee)
=> [openwrt-23.05] python3-maxminddb: Update to 2.4.0, rename source package

net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, test usage with https-dns-proxy
Description:
* https://curl.se/changes.html#8_2_0
=> curl: update to 8.2.0

lang/python/python-certifi/test.sh
Maintainer: me
Compile tested by github actions
Run tested by github actions
Description:
This loads the module, which should return the path of the CA bundle and verifies that the file exists.
=> python-certifi: add github runtime test

libs/libudev-zero/Makefile
Maintainer: Taylor Brown <taylorami@hotmail.com> / Daniel Golle <daniel@makrotopia.org>
Compile tested: x86_64, Ubuntu Hyper-V Virtual Machine, OpenWrt 23.03.5
Run tested: x86_64, Hyper-V Virtual Machine, OpenWrt 22.03.5
Description:
Upgraded libudev-zero to 1.0.3 to resolve a [known compatibility issue](https://github.com/openwrt/openwrt/issues/12350) with usbip in recent versions of OpenWrt.
I have simply bumped the package version to the latest and updated the hash. I tested the build and package in my environment to confirm that it works and addresses this issue.
_*This is my first contribution to OpenWrt, and appreciate any feedback to help maintain the style and quality standards of the project._
Signed-off-by: taylorami@hotmail.com
=> Bump libudev-zero to 1.0.3 (latest)

net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, test usage with https-dns-proxy
Description:
* https://curl.se/changes.html#8_2_0
(cherry picked from commit a276cebd9ee8bd5f63b9693fb885529f951375b8)
=> [23.05] curl: update to 8.2.0

net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, test usage with https-dns-proxy
Description:
* https://curl.se/changes.html#8_2_0
(cherry picked from commit a276cebd9ee8bd5f63b9693fb885529f951375b8)
=> [22.03] curl: update to 8.2.0

net/curl/Makefile
Maintainer: me
Run tested:  x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, test function of https-dns-proxy
Description:
* https://curl.se/changes.html#8_2_1
=> curl: update to 8.2.1

net/knot/Makefile
Description:
- Release upgrade (https://www.knot-dns.cz/2023-07-27-version-329.html)
=> knot: update to version 3.2.9

net/snort3/Makefile
=> snort3: update to 3.1.67.0

utils/lxc/Makefile
Bump to latest upstream release.
Maintainer: @ratkaj @BKPepe
=> lxc: update to 5.0.3

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
=> [openwrt-23.05] haproxy: update to v2.8.1

lang/python/python-cachetools/Makefile
=> python-cachetools: Update to 5.3.1

utils/docker/Makefile, utils/dockerd/Makefile, utils/runc/Makefile
Compile tested: x86_x64, QEMU/KVM, openwrt-23.05
Run tested: x86_x64, QEMU/KVM, openwrt-23.05
Description:
Updated docker to v23.0.5 and required dependencies
master PR https://github.com/openwrt/packages/pull/21698
=> Docker: Backport 24.0.5 to openwrt-23.05

net/openssh/Makefile
Description:
Version bump to 9.3p2
=> openssh: update to 9.3p2

lang/python/python-certifi/Makefile, lang/python/python-certifi/test.sh
Maintainer: @cotequeiroz
Compile tested: none (cherry picked from #21671 and #21680)
Description:
=> [openwrt-23.05] python-certifi: Update to 2023.7.22, add github runtime test

utils/collectd/Makefile
Run tested: no
Description:
* fix ampq1 vs. amqp1 typo
* unif configure args handling for collectd-mod-smart
=> collectd: fix amqp1 naming and unify configure args for collectd-mod-smart

utils/cryptsetup/Makefile
Maintainer: me
Run tested: -
Description:
Cryptsetup 2.6.1 Release Notes
==============================
Stable bug-fix release with minor extensions.
All users of cryptsetup 2.6.0 should upgrade to this version.
* bitlk: Fixes for BitLocker-compatible on-disk metadata parser (found by new cryptsetup OSS-Fuzz fuzzers).
- Fix a possible memory leak if the metadata contains more than one description field.
- Harden parsing of metadata entries for key and description entries.
- Fix broken metadata parsing that can cause a crash or out of memory.
* Fix possible iteration overflow in OpenSSL2 PBKDF2 crypto backend. OpenSSL2 uses a signed integer for PBKDF2 iteration count. As cryptsetup uses an unsigned value, this can lead to overflow and a decrease in the …
=> cryptsetup: update to version 2.6.1

libs/libksba/Makefile
Maintainer: me
Run tested: -
Description:
+ commit 557999424ebd13e70d6fc17e648a5dd2a06f440b
Correctly detect write errors while creating CMS objects.
+ commit 9ced7706f2738128aa5068727ea348c44f42e16e
* src/cms.c (write_encrypted_cont): Take care of write errors.
build: Sync libtool from libgpg-error for 64-bit Windows.
+ commit a920c2ff1a723031e8c6b8b61632bad46a740c83
* build-aux/ltmain.hs: Update from libgpg-error.
tests: Use -no-fast-install LDFLAGS for Windows.
+ commit 74fb95dbaf70d97b67793b29497b1e7b29a5e2f1
* tests/Makefile.am [HAVE_W32_SYSTEM] (AM_LDFLAGS): Conditionalize.
build: Update gpg-error.m4.
+ commit 53b9fa1d58ba522ca0eea4fe460719722e6e1ef5
* m4/gpg-error.m4: Update from libgpg-error master.
+ commit …
=> libksba: update to version 1.6.4

libs/libassuan/Makefile
Maintainer: me
Run tested: -
Description:
+ commit 6b50ee6bcdd6aa81bd7cc3fb2379864c3ed479b8
Flush data before clearing the confidential flag.
+ commit 0fc31770fa6277c57940b774d4049d7a3ad148e8
* src/context.c (assuan_end_confidential): Flush data.
build: Fix listing m4 files.
+ commit e686c85e207e52130388c68018ac2e75b7fb574a
* m4/Makefile.am (EXTRA_DIST): Add ax_cc_for_build.m4 and gpg-error.m4.  Remove sys_socket_h.m4.
build: Better cross build support.
+ commit 1939b040ca2301270a7f5be4e3049c551bf73dab
* configure.ac: Use AX_CC_FOR_BUILD.
* src/Makefile.am: Use EXEEXT_FOR_BUILD.
* m4/ax_cc_for_build.m4: New from libgpg-error.
tests: Use -no-fast-install LDFLAGS for Windows.
+ commit 32d9abf299ec5b217c5751d8dcf8cbb5989bdd9c
* tests/Makefile.am …
=> libassuan: update to version 2.5.6

libs/gpgme/Makefile
Maintainer: me
Run tested: -
Description:
2023-07-07  Werner Koch  <wk@gnupg.org>
Release 1.21.0.
+ commit 5bf3e6d0754a179b316f90a885371af99bc03ea1
2023-06-23  NIIBE Yutaka  <gniibe@fsij.org>
build: Add BUILT_SOURCE for better dependency.
+ commit 05ac1ce09ff199c715805cf601ea6d65e26c1fff
* Makefile.am (BUILT_SOURCE): Add conf/config.h.
2023-06-21  Ingo Klöcker  <dev@ingo-kloecker.de>
qt: Support reading signed/encrypted archives directly from a file.
+ commit 1c2459a5927866931808141ac6c4157cd5e3a157
* lang/qt/src/decryptverifyarchivejob.cpp, lang/qt/src/decryptverifyarchivejob.h (DecryptVerifyArchiveJob): Add member functions setInputFile, inputFile.
* lang/qt/src/decryptverifyarchivejob_p.h (DecryptVerifyArchiveJobPrivate): Add member m_inputFilePath.
* …
=> gpgme: update to version 1.21

libs/postgresql/Makefile, libs/postgresql/patches/700-no-arm-crc-march-change.patch
Maintainer: me
Run tested: BPi-R4 V00
Description:
Fixes security issues:
* CVE-2023-2454
* CVE-2023-2455
See release notes for details:
https://www.postgresql.org/about/news/postgresql-153-148-1311-1215-and-1120-released-2637/
=> postgresql: update to version 15.3

net/libcurl-gnutls/Makefile
Maintainer: me
Run tested: BPi-R4 V00
Description:
See cURL changes for details:
https://curl.se/changes.html
=> libcurl-gnutls: update to version 8.2.1

libs/file/Makefile
CC @ratkaj
Fixes #21583
* Be more strict in selecting linked in libraries during configuration time
* Add missing dependency on binary package libzstd
Both changes made in one pull-request because they are closely related.
=> file: Fix FTBFS due to missing dependency

lang/rust/Makefile
Description:
Version 1.71.1 (2023-08-03)
\===========================
- Fix CVE-2023-38497: Cargo did not respect the umask when extracting dependencies
- Fix bash completion for users of Rustup
- Do not show `suspicious_double_ref_op` lint when calling `borrow()`
- Fix ICE: substitute types before checking inlining compatibility
- Fix ICE: don't use `can_eq` in `derive(..)` suggestion for missing method
- Fix building Rust 1.71.0 from the source tarball
=> rust: Update to 1.71.1

lang/python/python-cachetools/Makefile
Compile tested: none (cherry picked from #21670)
Description:
(cherry picked from commit 2eabda9a1ecd7aff1f340f4175395680a041b0f1)
=> [openwrt-23.05] python-cachetools: Update to 5.3.1

lang/python/python-colorama/Makefile
Compile tested: none (cherry picked from #21673)
Description:
(cherry picked from commit 54f9f2777c79ef41013b02320a7050e5bae16d39)
=> [openwrt-23.05] python-colorama: Update to 0.4.6

net/openssh/Makefile, net/openssh/patches/900-sshd_config-include-dir.patch
Compile tested: x86_64, generic, HEAD (d54f3b2cfd)
Description:
Most distros allow dropping site configuration files into `/etc/sshd_config.d/` so that you don't have to tweak the main server configuration file.
=> openssh: add server config subdirectory

lang/python/micropython/patches/050-py-stackctrl-fix-gcc-13.patch
Maintainer: @jefferyto jefferyto
Compile tested: arm, bcm27xx-bcm2708 (rpi), OpenWrt master
Description:
On host PC using GCC 13, stackctrl.c fails to compile with the following error:
../py/stackctrl.c: In function 'mp_stack_ctrl_init': ../py/stackctrl.c:32:32: error: storing the address of
local variable 'stack_dummy'
in 'mp_state_ctx.thread.stack_top' [-Werror=dangling-pointer=]
32 |     MP_STATE_THREAD(stack_top) = (char *)&stack_dummy;
../py/stackctrl.c:31:18: note: 'stack_dummy' declared here
31 |     volatile int stack_dummy;
|                  ^~~~~~~~~~~
In file included from ../py/runtime.h:29,
from ../py/stackctrl.c:27:
../py/mpstate.h:296:23: note: 'mp_state_ctx' declared here
296 | extern mp_state_ctx_t mp_state_ctx;
|                       ^~~~~~~~~~~~
cc1: …
=> micropython: fix stackctrl compilation for GCC 13

net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, test function of https-dns-proxy
Description:
* https://curl.se/changes.html#8_2_1
(cherry picked from commit 82dbc1c4d519c3ec93220247f3ffb2ac354c89fd)
=> [22.03] curl: update to 8.2.1

net/curl/Makefile
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, test function of https-dns-proxy
Description:
* https://curl.se/changes.html#8_2_1
(cherry picked from commit 82dbc1c4d519c3ec93220247f3ffb2ac354c89fd)
=> [23.05] curl: update to 8.2.1

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
=> simple-adblock: force_dns_port validation bugfix

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
(cherry picked from commit 173d163f0935bd21e667fcd9a895718112d71718)
=> [22.03] simple-adblock: force_dns_port validation bugfix

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
(cherry picked from commit 173d163f0935bd21e667fcd9a895718112d71718)
=> [23.05] simple-adblock: force_dns_port validation bugfix

net/xtables-addons/Makefile
Compile tested: x86_64, generic, HEAD (626892e5ec)
Run tested: same, running on production router
Description:
The `db-ip` database has been problematic in its accuracy, so adding back support for using the freemium MaxMind GeoLite2 databases.
=> xtables-addons: add packaging for xt_asn, et al

libs/libxcrypt/Makefile
Upstream bump required to fix build issues reported here: https://forum.openwrt.org/t/i-cannot-build-my-image-due-to-failure-in-libxcrypt/168114
=> libxcrypt: update to 4.4.36

multimedia/yt-dlp/Makefile
Maintainer: @paper42 
Compile tested: apm821xx, WD My Book Live, snapshot r23552+4
Run tested: not yet (the missing packages were installed manually via `opkg`)
Description:
Added missing python3-{logging,uuid} dependencies.
Before the fix, `yt-dlp` aborted due to missing `python3-logging` and `python3-uuid`.
=> yt-dlp: add missing dependencies

lang/python/python-engineio/Makefile
=> python-engineio: Update to 4.5.1

lang/python/python-socketio/Makefile
=> python-socketio: Update to 5.8.0

lang/python/python-flask-socketio/Makefile
=> python-flask-socketio: Update to 5.3.5

lang/python/python-flask-babel/Makefile
=> python-flask-babel: Update to 3.1.0

utils/gptfdisk/Makefile
Fixed by defining `TARGET=linux`, as suggested in the `README`.
By default `TARGET` is derived from the host using `uname -s`,
which produces build errors on a non-linux hosts:
```
TARGET is not set; trying to determine target based on host OS....
Detected OS is Darwin
Build target is macos
...
x86_64-openwrt-linux-musl-g++: error: unrecognized command-line option '-arch'
```
Compile tested: (target x64, OpenWrt master, host: macOS 13.5)
@neheb @1715173329 @aparcar @dhewg
=> gptfdisk: fix incorrect TARGET on non-linux host

net/chrony/Makefile
Maintainer: me
Compile tested: mipsel, cudy wr1300, 22.03
Run tested: mipsel, cudy wr1300, 22.03, NTP+NTS client
=> chrony: update to 4.4

net/chrony/Makefile
Maintainer: me
Compile tested: mipsel, cudy wr1300, 22.03
Run tested: mipsel, cudy wr1300, 22.03, NTP+NTS client
=> [23.05] chrony: update to 4.4

lang/node/Makefile
Run tested: (qemu 8.0.3) aarch64
Description:
Update to v18.17.1
* CVE-2023-32002: Policies can be bypassed via Module._load (High)
* CVE-2023-32006: Policies can be bypassed by module.constructor.createRequire (Medium)
* CVE-2023-32559: Policies can be bypassed via process.binding (Medium)
* OpenSSL Security Releases  (Depends on shared library provided by OpenWrt)
* OpenSSL security advisory 14th July.
* OpenSSL security advisory 19th July.
* OpenSSL security advisory 31st July
=> node: August 2023 Security Releases

lang/node/Makefile
Compile tested: 22.03, aarch64, arm 
Run tested: (qemu 8.0.3) arm
Description:
Update to v16.20.2
* CVE-2023-32002: Policies can be bypassed via Module._load (High)
* CVE-2023-32006: Policies can be bypassed by module.constructor.createRequire (Medium)
* CVE-2023-32559: Policies can be bypassed via process.binding (Medium)
* OpenSSL Security Releases  (Depends on shared library provided by OpenWrt)
* OpenSSL security advisory 14th July.
* OpenSSL security advisory 19th July.
* OpenSSL security advisory 31st July
=> [22.03] node: August 2023 Security Releases

lang/node/Makefile
Run tested: (qemu 8.0.3) arm
Description:
Update to v18.17.1
* CVE-2023-32002: Policies can be bypassed via Module._load (High)
* CVE-2023-32006: Policies can be bypassed by module.constructor.createRequire (Medium)
* CVE-2023-32559: Policies can be bypassed via process.binding (Medium)
* OpenSSL Security Releases  (Depends on shared library provided by OpenWrt)
* OpenSSL security advisory 14th July. 
* OpenSSL security advisory 19th July. 
* OpenSSL security advisory 31st July
(cherry picked from commit 153f0b3d83dcbab5e05f7c1b38067071e96a30aa)
=> [23.05] node: August 2023 Security Releases

utils/collectd/Makefile
Compile tested: x86_64, APU3
Run tested: no
Description:
Fix missing dependencies for 'collectd-mod-disk' to 'libudev' if collectd-mod-smart is not enabled.
```
Package collectd-mod-disk is missing dependencies for the following libraries:
libudev.so.1
```
The package 'collect-mod-disk' is now build always with 'libudev' support, independent of the enable/disable build state of 'collectd-mod-smart'.
=> collectd: fix implicit dependence for collect-mod-disk to libudev

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
=> haproxy: update to v2.8.2

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
=> [openwrt-23.05] haproxy: update to v2.8.2

lang/python/python-flask-babel/Makefile
Compile tested: none (cherry picked from #21705)
Description:
(cherry picked from commit c579a4ab0e71b6112a593969ffb900faa46af7e5)
=> [openwrt-23.05] python-flask-babel: Update to 3.1.0

lang/python/python-flask-seasurf/Makefile
Compile tested: none (cherry picked from #21708)
Description:
(cherry picked from commit 68c434dd6a92917351ffd9d39c7dfed1b64f51ef)
=> [openwrt-23.05] python-flask-seasurf: Update to 1.1.1

lang/python/python-flask-socketio/Makefile
Compile tested: none (cherry picked from #21704)
Description:
(cherry picked from commit 58c9de9ede61a1a7b7c31cedc79140fd7a2c4344)
=> [openwrt-23.05] python-flask-socketio: Update to 5.3.5

lang/python/python-click/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21745)
Description:
(cherry picked from commit d86deca765a0bc8e801900fcce805d615ea9baad)
=> [openwrt-23.05] python-click: Update to 8.1.6

net/openssh/Makefile
Description:
Version bump to 9.4p1
=> openssh: update to 9.4p1

lang/python/python-jmespath/Makefile
Description:
This also updates the Python dependency from python3 to python3-light.
=> python-jmespath: Update to 1.0.1

lang/python/python-iniconfig/Makefile
=> python-iniconfig: Update to 2.0.0

net/v2raya/Makefile
Maintainer: me
Description:
https://github.com/v2rayA/v2rayA/releases/tag/v2.1.3
added [Juicity](https://github.com/juicity/juicity) support
=> v2raya: Update to 2.1.3

net/wget/Makefile
Compile tested: ramips, trunk
Run tested: ramips, Cudy M1800, trunk, wget usage
Description:
From the webpage of pcre:
> The older, but still widely deployed PCRE library, originally released in 1997, is at version 8.45. This version of PCRE is now at end of life, and is no longer being actively maintained. Version 8.45 is expected to be the final release of the older PCRE library, and new projects should use PCRE2 instead.
https://github.com/openwrt/openwrt/commit/c39b0646f3f2d96d40f601209859175af8537b6d
https://github.com/openwrt/openwrt/commit/e3e6652a550df389ffc0b1ba1f57bdfb81d34a46
=> wget: use pcre2

lang/ruby/Makefile, lang/ruby/patches/010-fix-riscv64-build.patch
Compile tested: sifiveu/generic
Description:
Fix build by adding missing macros.
The patch is taken from:
https://lists.openembedded.org/g/openembedded-core/message/161168
See also:
https://gitlab.alpinelinux.org/alpine/aports/-/issues/13667
=> ruby: fix riscv64 build

utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Release notes](https://github.com/docker/compose/releases/tag/v2.20.3)
=> docker-compose: Update to version 2.20.3

lang/ruby/Makefile, lang/ruby/patches/010-fix-riscv64-build.patch
Compile tested: sifiveu/generic
cherry-picked from #21812
=> [openwrt-23.05] ruby: fix riscv64 build

utils/reptyr/Makefile
Compile tested: rockchip/armv8, sifiveu/generic
Run tested: nanopi-r2s (i dont have a riscv64 board to test, so only did it on arm64)
Description:
```
* 0.10.0 (Jun 04, 2023)
- Add arm7 and aarch64 support for FreeBSD
* 0.9.0 (Jun 12, 2022)
- Add RISCV64 support on Linux
- Fix tty-stealing on PowerPC
```
=> reptyr: Update to 0.10.0

utils/smartmontools/Makefile, utils/smartmontools/patches/002-os_mailer-is-mailx.patch
Maintainer: me
Compile tested: ipq807x, r23300+3-86bc525d00
Run tested: ipq807x, r23300+3-86bc525d00, `smartctl --xall /dev/sda` works
Description:
- update to 7.4
- refresh patches
=> smartmontools: update to 7.4

net/tgt/Makefile
Maintainer: me
Compile tested: ipq807x, r23300+3-86bc525d00
Run tested: ipq807x, r23300+3-86bc525d00, exporting a file as a LUN works fine
Description:
=> tgt: update to 1.0.87

utils/qemu/Makefile
As of OpenWrt main branch commit [e505873e65f72 ](https://github.com/openwrt/openwrt/commit/e505873e65f72) ("armsr: armv8: enable KVM host") [merged 2023-08-15], armsr/armv8 has KVM host support. We can now enable QEMU host for this target.
For example, you can run OpenWrt armsr/armv8 as a guest like so:
```
qemu-system-aarch64 -nographic -M virt -cpu host --enable-kvm \
-bios u-boot.bin -smp 1 -m 1024 \
-drive file=openwrt-armsr-armv8-generic-ext4-combined.img,format=raw,index=0,media=disk
```
A compatible u-boot.bin can be obtained from u-boot-qemu_armv8/u-boot.bin that is built with the armsr target and available from downloads.openwrt.org.
(It would be nice to package EDK2 and u-boot for QEMU usage, sometime in the future)
Compile tested: armv8/armsr, OpenWrt …
=> qemu: enable host support for armsr/armv8

net/modemmanager/Makefile, net/modemmanager/files/modemmanager.proto
Maintainer: @mips171 Please also have a look at this change @aleksander0m 
Compile tested: x86_64, APU3, latest openwrt master
Run tested: x86_64, APU3, latest openwrt master,  test done = yes
Description:
* [fix white spaces](https://github.com/openwrt/packages/commit/dbf23705c50b898d5f2ce2fe4e7418d2f3a931c8)
* [remove unneeded teardown error reporting](https://github.com/openwrt/packages/commit/5fa043000fdf97fda36d06cac005209fcda5910e)
* [add setting for allowed and preferred mode](https://github.com/openwrt/packages/commit/015106346ca1d6b71a83bb6c16be42112f1fc4ae)
=> modemmanager: setting allowed and preferred mode

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Description:
* fix validation for force_dns_port when missing in config
* fix validation for dns_instance when * or - are used
=> simple-adblock: bugfixes for uci_load_validate

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Description:
* fix validation for force_dns_port when missing in config
* fix validation for dns_instance when * or - are used
(cherry picked from commit ad8aa084c18af6fd878e578453d7077deb5c223e)
=> [22.03] simple-adblock: bugfixes for uci_load_validate

net/simple-adblock/Makefile, net/simple-adblock/files/simple-adblock.init
Maintainer: me
Description:
* fix validation for force_dns_port when missing in config
* fix validation for dns_instance when * or - are used
(cherry picked from commit ad8aa084c18af6fd878e578453d7077deb5c223e)
=> [23.05] simple-adblock: bugfixes for uci_load_validate

lang/php8/Makefile
Maintainer: me
Run tested: no
Description:
The initial fix was done in a2e76e497.
Later we could revert it with 5779ae4c5 since a global fix in gcc was deployed.
But now, PHP itself applied a workaround/fix in 8.2.8, so that we now require the initial fix again.
=> php8: fix linking on riscv64 platform (again)

net/frp/Makefile
Run tested: (x86_64, OpenWrt snapshot)
Description:
Includes some bug fixes and adds support for GO 1.21. Fix #21832.
Changelog:
https://github.com/fatedier/frp/releases/tag/v0.51.1
https://github.com/fatedier/frp/releases/tag/v0.51.2
https://github.com/fatedier/frp/releases/tag/v0.51.3
=> frp: update to 0.51.3

lang/python/python-more-itertools/Makefile
Description:
The package has changed to the flit-core build backend.
=> python-more-itertools: Update to 10.1.0

lang/python/python-msgpack/Makefile
=> python-msgpack: Update to 1.0.5, add host Cython dependency

lang/python/python-psycopg2/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-08-06 snapshot
Description:
This also adds a source package (python-psycopg2-src).
=> python-psycopg2: Update to 2.9.7, update list of dependencies

lang/python/python-jmespath/Makefile
Compile tested: none (cherry picked from #21750)
Description:
This also updates the Python dependency from python3 to python3-light.
(cherry picked from commit cde28d04e67a522bc7b6ecce90a3664d0c1a6f03)
=> [openwrt-23.05] python-jmespath: Update to 1.0.1

lang/python/python-iniconfig/Makefile
Compile tested: none (cherry picked from #21757)
Description:
(cherry picked from commit 8a8991dfbfdcecce28a791262ee721ff09689481)
=> [openwrt-23.05] python-iniconfig: Update to 2.0.0

libs/libyang/Makefile
Maintainer:  @jsmolic 
Description:
Update needed for frr 9.0
Tested: x86_64
Also compile tested libnetconf2 and sysrepo, that are using this dependecie
=> libyang: update to 2.1.80

lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 2.3.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.4.0
=> lua-eco: update to 2.4.0

utils/syncthing/Makefile
Compile tested: x86-64
Description:
Disable quic temporarily to support GO 1.21 https://github.com/syncthing/syncthing/issues/9034.
=> syncthing: update to 1.23.7

lang/rust/rust-values.mk
Fixes the commit 105fa3920e which was intended to make rust/host build on aarch64 darwin working again. However, the fix contains a mistake because it sets RUSTC_TARGET_ARCH instead of RUSTC_HOST_ARCH. Thus, the fix doesn't work.
This properly sets the correct variable RUSTC_HOST_ARCH.
Fixes: 105fa3920e ("rust: fix host build on aarch64 darwin")
Description:
I made a mistake while transferring my fix from my testing repo to the fork. I wasn't careful enough with the PR and just recognized this while backporting my fix to 23.05. Sorry for that.
In the fix before I used RUSTC_TARGET_ARCH but it must be RUSTC_HOST_ARCH to actually change the target triple used for compiling rust/host.
cc @PolynomialDivision
=> rust: correct mistake in previous host-build fix

net/tunneldigger-broker/Makefile, net/tunneldigger-broker/files/config.default, net/tunneldigger-broker/files/hook-connection-rate-limit, net/tunneldigger-broker/files/hook-mtu-changed, net/tunneldigger-broker/files/hook-setup, net/tunneldigger-broker/files/tunneldigger-broker.init, net/tunneldigger-broker/files/tunneldigger.sh
Maintainer: @PolynomialDivision 
Compile tested: X86-64, KVM-VM  Snapshot with the SDK
Run tested: X86-64, KVM-VM Snapshot with the imagebuilder
Description:
Update /lib/functions/tunneldigger.sh to use config_foreach and add a new function to determine if bridge ports should be isolated (default 0, or not isolated).  Add functionality to the setup and mtu_changed hooks to incorporate the new bridge port isolation settings. Update the default config file to match new settings in v0.4.0. Add new hook function for rate limiting.
A config bridge section can now look like this:
config bridge
option interface 'br-mybridge1446'
option mtu '1466'
option isolate '1' # default 0
=> tunneldigger-broker updates

lang/rust/rust-values.mk
Compile tested: yes
Description:
Backport of #21837 and #21845 to OpenWrt 23.05
I wasn't quite sure how to backport this because I had a mistake in the first PR, nevertheless it got merged and then submitted a second PR to fix that. Usually backporting seems to be done just by cherry-picking. Please tell me if that should be done in another way.
~~(cherry picked from 105fa3920e and c287e98af2)~~
(squashed 105fa3920e and c287e98af2)
=> [openwrt-23.05] rust: fix host build on aarch64 darwin

lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 2.4.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.4.0
=> [openwrt-23.05 ] lua-eco: update to 2.4.0

lang/python/python-more-itertools/Makefile
Compile tested: none (cherry picked from #21792)
Description:
The package has changed to the flit-core build backend.
(cherry picked from commit 96880b435b7e4c861c85b9e761e250262e127c25)
=> [openwrt-23.05] python-more-itertools: Update to 10.1.0

lang/python/python-msgpack/Makefile
Compile tested: none (cherry picked from #21793)
Description:
(cherry picked from commit 53d3fc6f4402754855eae992b6e7a84c9a1c71fe)
=> [openwrt-23.05] python-msgpack: Update to 1.0.5, add host Cython dependency

lang/python/python-psycopg2/Makefile
Compile tested: none (cherry picked from #21797)
Description:
This also adds a source package (python-psycopg2-src).
(cherry picked from commit 3a5f9999ca8224aa9a065504f5c0368afbedada0)
=> [openwrt-23.05] python-psycopg2: Update to 2.9.7, update list of dependencies

net/unbound/Makefile, net/unbound/patches/200-remove-SSL-unexpected-eof-messages.patch
Compile tested: aarch64, arm-cortex
Run tested: Linksys E8450/Netgear R7800, trunk
Description:
After OpenSSL update to v3+, Unbound log spamed with `SSL_read crypto error:0A000126:SSL routines::unexpected eof while reading` messages due to remote not sending disconnect.
Refs: https://github.com/NLnetLabs/unbound/issues/812 and https://github.com/NLnetLabs/unbound/issues/846
This is a backport of: https://github.com/NLnetLabs/unbound/commit/d7e776114114c16816570e48ab3a27eedc401a0e and can be removed with the next release/update of Unbound here.
=> Unbound: Silence SSL unexpected eof messages

net/natmap/Makefile
Maintainer: @ysc3839 @heiher 
Description:
1. Update to 20230820.
=> natmap: update to 20230820

net/natmap/Makefile
Maintainer: @ysc3839 @heiher 
Description:
1. Update to 20230820.
=> [openwrt-23.05] natmap: update to 20230820

net/tunneldigger-broker/Makefile, net/tunneldigger-broker/files/config.default, net/tunneldigger-broker/files/hook-connection-rate-limit, net/tunneldigger-broker/files/hook-mtu-changed, net/tunneldigger-broker/files/hook-setup, net/tunneldigger-broker/files/tunneldigger-broker.init, net/tunneldigger-broker/files/tunneldigger.sh
Maintainer: @PolynomialDivision
Compile tested: X86-64, KVM-VM openwrt-23.05-rc2 with the SDK
Run tested: X86-64, KVM-VM openwrt-23.05-rc2 with the imagebuilder
Description:
Update /lib/functions/tunneldigger.sh to use config_foreach and add a new function to determine if bridge ports should be isolated (default 0, or not isolated). Add functionality to the setup and mtu_changed hooks to incorporate the new bridge port isolation settings. Update the default config file to match new settings in v0.4.0. Add new hook function for rate limiting.
A config bridge section can now look like this:
config bridge
option interface 'br-mybridge1446'
option mtu '1466'
option isolate '1' # default 0
Cherry-picked from master
=> [openwrt-23.05 ] tunneldigger-broker updates

net/tunneldigger-broker/Makefile, net/tunneldigger-broker/files/config.default, net/tunneldigger-broker/files/hook-connection-rate-limit, net/tunneldigger-broker/files/hook-mtu-changed, net/tunneldigger-broker/files/hook-setup, net/tunneldigger-broker/files/tunneldigger-broker.init, net/tunneldigger-broker/files/tunneldigger.sh
Maintainer: @PolynomialDivision
Compile tested: X86-64, KVM-VM openwrt-22.03.05 with the SDK
Run tested: X86-64, KVM-VM openwrt-22.03.05 with the imagebuilder
Description:
Update /lib/functions/tunneldigger.sh to use config_foreach and add a new function to determine if bridge ports should be isolated (default 0, or not isolated). Add functionality to the setup and mtu_changed hooks to incorporate the new bridge port isolation settings. Update the default config file to match new settings in v0.4.0. Add new hook function for rate limiting.
A config bridge section can now look like this:
config bridge
option interface 'br-mybridge1446'
option mtu '1466'
option isolate '1' # default 0
Cherry-picked from master
=> [openwrt-22.03] tunneldigger-broker updates

net/v2ray-core/Makefile, net/v2ray-core/patches/001-DNS-over-QUIC-should-not-have-http-1.1-and-h2-ALPNs-.patch, net/v2ray-core/patches/002-Migrate-to-quic-go-v0.36.0-2561.patch, net/v2ray-core/patches/003-fix-panic-in-dns-over-quic-when-address-is-a-ip.patch, net/v2ray-core/patches/004-feat-bulit-in-qtls-cipher-suite-implementation.patch, net/v2ray-core/patches/010-chore-go-update-dependencies.patch
Maintainer: me
Description:
Fix build for Go 1.21.
=> v2ray-core: backport upstream Go 1.21 updates

net/xray-core/Makefile, net/xray-core/patches/00-fix-go1.21-build.patch
Maintainer: me
Description:
Fix build for Go 1.21.
Upstream PR: https://github.com/XTLS/Xray-core/pull/2479
=> xray-core: backport pending patch for Go 1.21 update

lang/python/python-pyfuse3/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-08-13 snapshot
Description:
=> python-pyfuse3: Update to 3.3.0, update list of dependencies

lang/python/python-pyparsing/Makefile
Description:
The package has changed to the flit-core build backend.
=> python-pyparsing: Update to 3.1.1

lang/python/python-pytest-xdist/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-08-13 snapshot
Description:
=> python-pytest-xdist: Update to 3.3.1, update list of dependencies

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Run tested: -
Description:
This fixes:
- CVE-2023-3824
=> php8: update to 8.2.9

libs/nlohmannjson/Makefile
Compile tested: OpenWRT-23.05-rc2, arm_cortex-a7_neon-vfpv4, mips_24kc
Run tested: arm_cortex-a7_neon-vfpv4 (Linksys MR8300), mips_24kc (tplink_archer-a7), OpenWrt 23.05-rc2)
* Update package nlohmannjson to version 3.11.2.
* Version 3.11.2 is source compatible with 3.10.2 so no package should fail to compile
* From version 3.11.2 on forward template declarations are collected in the file json_fwd.hpp. The json.hpp still contains all template definitions. Because in most compilation units of a software package only the file json_fwd.hpp needs to be included, the compilation process is accelerated a lot.
=> [openwrt-23.05]  nlohmannjson: Update to version 3.11.2

lang/python/python-py/Makefile
Compile tested: none (cherry picked from #21858)
Description:
(cherry picked from commit f9e3847599753f9489303ac21f74a1e724597ef8)
=> [openwrt-23.05] python-py: Update to 1.11.0, update list of dependencies

lang/python/python-pyfuse3/Makefile
Compile tested: none (cherry picked from #21859)
Description:
(cherry picked from commit a9b23f4683473da0ebdedc0d3279aab1f3a92c31)
=> [openwrt-23.05] python-pyfuse3: Update to 3.3.0, update list of dependencies

lang/python/python-pyparsing/Makefile
Compile tested: none (cherry picked from #21861)
Description:
The package has changed to the flit-core build backend.
(cherry picked from commit dbe5283ed07497eab5cc1fd3c29553747fec878b)
=> [openwrt-23.05] python-pyparsing: Update to 3.1.1

lang/python/python-pytest-xdist/Makefile
Compile tested: none (cherry picked from #21864)
Description:
(cherry picked from commit 6facae339e1cf25decbc811d5dac1977b4a0d9f6)
=> [openwrt-23.05] python-pytest-xdist: Update to 3.3.1, update list of dependencies

net/knot/Makefile
Description:
- Release upgrade (https://www.knot-dns.cz/2023-08-28-version-330.html)
- Enable QUIC support
=> knot: update to version 3.3.0

net/modemmanager/Makefile
Maintainer: @mips171 
Compile tested: x86_64, APU3, master
Run tested: x86_64, APU3, master
Description:
In order to use the dbus interfaces via the command gdbus-codegen, the xml files must be copied into the building staging directory, so that other programmes can use them during compilation.
=> modemmanager: copy dbus interfaces file to staging

lang/python/python-tornado/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-08-20 snapshot sdk
Description:
=> python-tornado: Update to 6.3.3, update list of dependencies

lang/python/python-trio/Makefile
Run tested: armsr-armv7 (qemu), 2023-08-20 snapshot sdk
Description:
=> python-trio: Update to 0.22.2, update list of dependencies

net/libreswan/Makefile
fix CVE-2023-38710, CVE-2023-38711, CVE-2023-38712
Maintainer: me
Tested: x86_64
=> libreswan: update to 4.12

libs/libre2/Makefile
=> libre2: fix pkgconfig paths

lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 2.5.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.5.0
=> lua-eco: update to 2.5.0

libs/dmx_usb_module/patches/100-fix-compilation-warning-wrong-cast.patch
Maintainer: no one
Compile tested: N/A, CI will do its job
Description:
Recently, there was pushed patch, which fixed only part to get it working with Linux kernel 6.2+, but it was only local change and it did not use the changes, which are going to be included in the upcoming dmx_usb_module release.
This commit use the commit from the upstream repository: https://github.com/lowlander/dmx_usb_module/commit/eeecf40c3eb3dbdf1981c508080ab3aa61e105e2
Fixes: e15d9f75dac2888b9d863c6f2d1c19637631c1fb ("dmx_usb_module: fix compilation warning")
Reference below this commit ⬆️ inside comments
=> dmx_usb_module: use upstream commit to fix compilation with kernel 6.2+

net/tor/Makefile
First release of the 0.4.8.x series, see the changelog [1] for what's new.
[1] https://gitlab.torproject.org/tpo/core/tor/-/raw/tor-0.4.8.4/ChangeLog
Maintainer: @hauke 
Run tested: tor-basic, mediatek/mt7622 (Belkin RT3200)
=> tor: update to 0.4.8.4 stable

net/knot-resolver/Makefile, net/knot-resolver/patches/010-fix-lmdb.patch
Compile tested: all Turris routers (Turris MOX - Marvell Armada 3720, Turris Omnia - Marvell Armada 385, Turris 1.0 and Turris 1.1 - PowerPC Freescale P2020), the latest changes from OpenWrt 21.02 and OpenWrt 22.03 branches
Run tested: same as above
Changelog:
https://www.knot-resolver.cz/2023-01-26-knot-resolver-5.6.0.html
https://www.knot-resolver.cz/2023-08-22-knot-resolver-5.7.0.html
=> knot-resolver: update to version 5.7.0

libs/libucontext/Makefile, libs/libucontext/patches/010-return_values_fix.patch, libs/libucontext/patches/020-honor_return_values_fix.patch
Maintainer: @VolkerChristian
Description (from libucontext github page):
libucontext ([https://github.com/kaniini/libucontext](https://github.com/kaniini/libucontext)) is a library which provides the ucontext.h C syscall API. Unlike other implementations, it faithfully follows the kernel process ABI when doing context swaps. libucontext is used on almost all musl distributions to provide the legacy ucontext.h API.
This is a development package only. No need to install a package on the router. It is used to link libraries/applications against it which need the system calls
- makecontext
- swapcontext
- getcontext
- setcontext
E.g. the asynchronous API of libmariadb (c-connector) uses this calls. Because libmusl didn't provide that system calls this asynchronous API is currently (without …
=> libucontext: Add package

utils/mhz/Makefile, utils/mhz/patches/0001-Makefile-allow-overriding-CC-and-CFLAGS.patch
Maintainer: me
Compile tested: mvebu, a9/Turris Omnia and ipq807x/Qnap 301W
Run tested: ipq807x/Qnap 301W
Description:
It seems that the Makefile has both CC and CFLAGS hardcoded and does not allow overriding them by ones being passed by the buildsystem.
This works fine until CONFIG_PKG_ASLR_PIE_ALL is selected, then building will fail with:
```
arm-openwrt-linux-muslgnueabi/bin/ld.bfd: mhz.o: relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
arm-openwrt-linux-muslgnueabi/bin/ld.bfd: mhz.o(.text+0x75c): unresolvable R_ARM_CALL relocation against symbol `__aeabi_l2d@@GCC_3.5
```
So, lets add a patch pending upstream that allows both CC and CFLAGS to be overriden so that ones passed by the buildsystem are actually …
=> mhz: respect CC and CFLAGS passed by buildsystem

net/snort3/Makefile
Upstream bump
```
o"  )~   Version 3.1.69.0
Using DAQ version 3.0.12
Using OpenSSL 3.0.10 1 Aug 2023
Using ZLIB version 1.2.13
Using Hyperscan version 5.4.2 2023-08-29
```
=> snort3: update to 3.1.69.0

lang/python/python-rsa/Makefile
Compile tested: none (cherry picked from #21908)
Description:
(cherry picked from commit a694ed7b0c0c85108f37f7562e606a30d30638ac)
=> [openwrt-23.05] python-rsa: Update to 4.9, update list of dependencies

lang/python/python-slugify/Makefile
Compile tested: none (cherry picked from #21912)
Description:
(cherry picked from commit 1ec68a6e98ec0c1a7256023baee1f9b01ccbf5d2)
=> [openwrt-23.05] python-slugify: Update to 8.0.1, update list of dependencies

lang/python/python-tornado/Makefile
Compile tested: none (cherry picked from #21914)
Description:
(cherry picked from commit e7a8d18385e6d1de27d0501940259ab23e50be6f)
=> [openwrt-23.05] python-tornado: Update to 6.3.3, update list of dependencies

lang/python/python-trio/Makefile
Compile tested: none (cherry picked from #21915)
Description:
(cherry picked from commit 6b6ea7efe1c8e2584a0c788f06ef826f1030c6e9)
=> [openwrt-23.05] python-trio: Update to 0.22.2, update list of dependencies

lang/python/python-websocket-client/Makefile
Maintainer: me
Description:
- Add support for SSLKEYLOGFILE environment variable
- Add support for callable header arguments
- Change handling of proxy environment variables, is_secure set to true now prevents http_proxy from getting used
=> python-websocket-client: update to 1.6.2

utils/qemu/Makefile
**This is a backport/cherry pick of https://github.com/openwrt/packages/pull/21831**
armsr/armv8 has KVM support since 23.05-rc3 (see https://github.com/openwrt/openwrt/commit/88e7fe874124c7c6daf99b7716205cd91fbe6bc3)
------------------------- 
As of OpenWrt main branch commit [e505873e65f72 ](https://github.com/openwrt/openwrt/commit/e505873e65f72)("armsr: armv8: enable KVM host") [merged 2023-08-15], armsr/armv8 has KVM host support. We can now enable QEMU host for this target.
For example, you can run OpenWrt armsr/armv8 as a guest like so:
qemu-system-aarch64 -nographic -M virt -cpu host --enable-kvm \
-bios u-boot.bin -smp 1 -m 1024 \
-drive file=openwrt-armsr-armv8-generic-ext4-combined.img,format=raw,index=0,media=disk
A compatible u-boot.bin can be obtained from …
=> [openwrt-23.05] qemu: enable host support for armsr/armv8

net/croc/Makefile
croc is a tool written in Go for sending files from one device to another over the internet using a relay. It runs on multiple platforms, provides end-to-end encryption and works without port forwarding and fixed IP/DynDNS.
Maintainer: me (@jonasjelonek)
Build system: x86_64 Linux
Compile tested: aarch64_cortex-a53, BananaPi R64
Run tested: aarch64_cortex-a53, BananaPi R64
Description:
The description above already summarizes quite well whats the purpose of this tool. A more detailed description can be found [here](https://schollz.com/tinker/croc6/), and there are several examples of its usage in the git [here](https://github.com/schollz/croc).
I use it quite a lot, e.g. when I build new images on my build server (which isn't in my LAN) to transfer it directly to the device …
=> croc: new package

lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 2.5.0: https://github.com/zhaojh329/lua-eco/releases/tag/v2.5.0
=> [openwrt-23.05] lua-eco: update to 2.5.0

lang/python/python-ubus/Makefile
Maintainer: @whooo
Run tested: armsr-armv7 (qemu, ubus connect/disconnect only), 2023-08-25 snapshot
Description:
=> python-ubus: Update to 0.1.2

lang/python/python-urllib3/Makefile
=> python-urllib3: Update to 2.0.4

lang/python/python-voluptuous-serialize/Makefile
=> python-voluptuous-serialize: Update to 2.6.0

admin/syslog-ng/Makefile, lang/python/python-astral/Makefile, lang/python/python-awesomeversion/Makefile, lang/python/python-babel/Makefile, lang/python/python-cachetools/Makefile, lang/python/python-flask-babel/Makefile, lang/python/python-flask-seasurf/Makefile, lang/python/python-flask-session/Makefile, lang/python/python-markdown/Makefile, lang/python/python-paho-mqtt/Makefile, lang/python/python-pyotp/Makefile, lang/python/python-pyrsistent/Makefile, lang/python/python-requests/Makefile, lang/python/python-schedule/Makefile, lang/python/python-sentry-sdk/Makefile, lang/python/python-slugify/Makefile, lang/python/python-sqlalchemy/Makefile, lang/python/python-tornado/Makefile, lang/python/python-uci/Makefile, lang/python/python-unidecode/Makefile, lang/python/python-voluptuous-serialize/Makefile, lang/python/python-voluptuous/Makefile, lang/python/python-yaml/Makefile, lang/python/python3-bottle/Makefile, lang/python/ruamel-yaml/Makefile, lang/python/text-unidecode/Makefile, net/dnscrypt-proxy2/Makefile, utils/reptyr/Makefile, utils/sshpass/Makefile
Since February 2023, I decided to no longer work with Turris, I mean CZ.NIC company due to some reasons how the development goes and since that day my work address is not available and not sure if there is some redirect to someone else, but if anyone wants to reach me, use my email address, where they can find me.
____
Also, it does not require to bump PKG_VERSION. My first thought of doing this was like, hey, I am not going to use these packages personally except syslog-ng and they are needed for Turris, so in the future, guys from Turris show up to take maintainership of these packages or there will be some alias, but... nope. That didn't happen and I haven't noticed that someone from Turris is active here as I was. Lets hope for brighter future now.
=> treewide: change my no longer used email

lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 2.5.1: https://github.com/zhaojh329/lua-eco/releases/tag/v2.5.1
=> lua-eco: update to 2.5.1

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/share/ddns/default/desec.io.json
Compile tested: OpenWrt 23.0.5
Run tested: Raspberry Pi 4B
Description:
desec.io ddns update is not working, after testing the endpoint I got a 301, after a bit of search I found out we are supposed to use https instead of http
more info here: https://talk.desec.io/t/301-from-update-dedyn-io/644/2
=> ddns-scripts: desec.io - update url to https

net/modemmanager/Makefile, net/modemmanager/files/10-report-down, net/modemmanager/files/modemmanager.proto
Maintainer: @mips171 , @aleksander0m
Compile tested: x86_64, APU3, latest openwrt master
Run tested: x86_64, APU3, latest openwrt master, test done = yes
Description:
The proto_send_update function is sending a notification to netifd during the teardown section.
However, netifd filters link-update-notifications executed during teardown, as indicated here: [Netifd-Code-Snippet]( https://git.openwrt.org/?p=project/netifd.git;a=blob;f=proto-shell.c;h=bc3c41dcba85ac46cff02db88b9d3ee8e9fc2a57;hb=HEAD#l515)
This was leading to a Permission Denied error due to its behavior, making proto_send_update ineffective during teardown.
To address the issue, the proto_send_update function has been removed from the teardown section.
This prevents the Permission Denied error while ensuring proper operation …
=> modemmanager: Fix Permission Denied error

lang/lua-eco/Makefile
(cherry picked from commit 4af428ec71af88470903d3459b720727714cde16)
Maintainer: me
Description:
Release notes for 2.5.1: https://github.com/zhaojh329/lua-eco/releases/tag/v2.5.1
=> [openwrt-23.05] lua-eco: update to 2.5.1

libs/libedit/Makefile
Description:
- update of the library on which `knot` depends on
=> libedit: update to version 20230828-3.1

net/modemmanager/Makefile
Maintainer: @mips171 
Compile tested: x86_64, generic, HEAD
Description:
Seeing failing build of package when MBIM is disabled.
=> modemmanager: handle no *.conf files being installed

utils/cache-domains/Makefile, utils/cache-domains/files/cache-domains, utils/cache-domains/files/test.sh
Description:
This fix dnsmasq failing to startup once configured since the cache-domains config files are not included in the jail that dnsmasq runs inside.
Also, I've reduces the writes by symlinking each file to the dnsmasq directory instead of writing them all to one big file.
=> cache-domains: Fixed config files being outside of jail

lang/python/python-ubus/Makefile
Maintainer: @whooo
Compile tested: none (cherry picked from #21945)
Description:
(cherry picked from commit 99d8554bcd1a16e2276ffb706c3f1e823ece65f3)
=> [openwrt-23.05] python-ubus: Update to 0.1.2

lang/python/python-urllib3/Makefile
Compile tested: none (cherry picked from #21946)
Description:
(cherry picked from commit 1b2811920a5c6b02963a449bed51fb7b92d01fcc)
=> [openwrt-23.05] python-urllib3: Update to 2.0.4

net/haproxy/Makefile, net/haproxy/get-latest-patches.sh
=> haproxy: update to v2.8.3
