net/obfs4proxy/Makefile
Maintainer: me
Compile tested: none (cherry picked from #20826)
Description:
(cherry picked from commit 0759341cd8bbc28a499a1098889be108ef91612f)
=> [openwrt-22.03] obfs4proxy: Update to 0.0.14

lang/python/python-pyasn1/Makefile
Maintainer: me
Compile tested: armvirt-32, 2023-04-23 snapshot sdk
Description:
=> python-pyasn1: Update to 0.5.0

lang/python/python-zope-interface/Makefile, lang/python/python-zope-interface/patches/001-omit-tests.patch
Maintainer: me
Compile tested: armvirt-32, 2023-04-16 snapshot sdk
Description:
=> python-zope-interface: Update to 6.0, refresh patch

lang/python/python-idna/Makefile
Maintainer: me
Compile tested: armvirt-32, 2023-04-16 snapshot sdk
Description:
=> python-idna: Update to 3.4

net/librespeed-go/Makefile, net/librespeed-go/files/librespeed-go.init
Maintainer: me
Run tested: redmi-ax6
Description:
This fixes "permission denied" error when access files as a normal user.
Fixes: #20868
=> librespeed-go: update file permissions for ujail

libs/slang2/Makefile, libs/slang2/patches/001-skip-terminfo-dir-test.patch
Maintainer: me
Compile tested: none (cherry pick from #20827)
Description:
(cherry picked from commit 47d67e43bf7447fdba3f30d88b217118d8846b41)
=> [openwrt-22.03] slang2: Update to 2.3.3, refresh patches

net/tailscale/Makefile, net/tailscale/patches/010-fake_iptables.patch, net/tailscale/patches/020-tailscaled_fake_iptables.patch, net/tailscale/patches/030-default_to_netfilter_off.patch
Maintainer: Jan Pavlinec <jan.pavlinec1@gmail.com>
=> tailscale: update to 1.40.0

utils/coreutils/Makefile, utils/coreutils/patches/001-no_docs_man_tests.patch
Compile tested: Ubuntu Linux 22.04, macOS 12.6.5
Run tested: x64, WRT3200ACM, TL-WR1043ND v4
[1] https://github.com/openwrt/packages/issues/20933
[2] https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62404
@neheb @1715173329 @Ansuel @mpratt14 @Arunmor1510 @stangri
=> coreutils: update to 9.3

lang/python/django/Makefile, lang/python/python-requests/Makefile
Maintainer: me (for both), @peter-stadler (for Django), @BKPepe (for requests)
Compile tested: x86 https://github.com/openwrt/openwrt/commit/4e5aac472935ce3ba3abc9bd72b880951843092b
Run tested: x86 https://github.com/openwrt/openwrt/commit/4e5aac472935ce3ba3abc9bd72b880951843092b
=> python-{django,requests}: bump versions

net/arp-scan/Makefile
Release Notes:
https://github.com/royhills/arp-scan/releases/tag/1.10.0
Maintainer: @urusha 
=> arp-scan: update to 1.10.0

libs/nss/Makefile
=> nss: update to 3.89.1

net/openfortivpn/Makefile
=> openfortivpn: update to 1.20.3

utils/apk/Makefile, utils/apk/patches/010-openssl-deprecated.patch
Description:
* Fixed build issue with musl 1.2.4.
* Refreshed patches.
=> apk: Update to 2.14.0

lang/python/python-packaging/Makefile
Maintainer: me, @ja-pa 
Compile tested: armvirt-32, 2023-05-15 snapshot sdk
Description:
=> python-packaging: Update to 23.1

lang/php8/Makefile
=> php8: update to 8.2.6

net/natmap/Makefile
Maintainer: @ysc3839 @heiher 
Description:
1. Update to 20230519.
2. Add myself to maintainers.
=> natmap: update to 20230519

libs/libgcrypt/Makefile
=> libgcrypt: update to 1.10.2

libs/libsoup3/Makefile
=> libsoup3: update to 2.6.4

lang/luasec/Makefile
=> luasec: update to 1.3.1

net/nfdump/Makefile
=> nfdump: update to 4.2.0

libs/openldap/Makefile
=> openldap: update to 2.6.4

admin/syslog-ng/Makefile
=> syslog-ng: update to 4.2.0

multimedia/gst1-libav/Makefile, multimedia/gst1-plugins-bad/Makefile, multimedia/gst1-plugins-bad/patches/010-distutils.patch, multimedia/gst1-plugins-base/Makefile, multimedia/gst1-plugins-base/patches/010-distutils.patch, multimedia/gst1-plugins-good/Makefile, multimedia/gst1-plugins-good/patches/010-distutils.patch, multimedia/gst1-plugins-ugly/Makefile, multimedia/gst1-plugins-ugly/patches/010-distutils.patch, multimedia/gstreamer1/Makefile, multimedia/gstreamer1/patches/020-distutils.patch
Maintainer: me
Description:
* gstreamer1
* gst1-plugins-base
* gst1-plugins-good
* gst1-plugins-bad
* gst1-plugins-ugly
* gst1-libav
=> gstreamer1: update to 1.22.3

net/freeradius3/Makefile, net/freeradius3/patches/002-disable-session-cache-CVE-2017-9148.patch, net/freeradius3/patches/010-openssl-deprecated.patch
Maintainer: LucileQ
Compile tested: mediatek, GL-MT3000, master
Run tested: mediatek, GL-MT3000, master, tests done
Description:
=> freeradius3: Update to 3.0.26

net/acme-acmesh/Makefile, net/acme-acmesh/files/hook.sh, net/acme-common/Makefile, net/acme-common/files/acme.init
Compile tested: x64 master
Run tested: x64 master
Description:
Please check the commit messages for details. Two changes:
1. Don't let clients deal with deprecated values.
2. Standardize key type values.
=> acme: improve

net/apfree-wifidog/Makefile, net/apfree-wifidog/files/wifidogx.conf, net/apfree-wifidog/files/wifidogx.init
Maintainer: @liudf0716 
1. support fw4
2. support openssl3.0
=> apfree-wifidog: Update to 6.02.1939

net/pdns/Makefile, net/pdns/patches/100-pdns-disable-pdns.conf-dist.patch
=> pdns: update to 4.8.0

net/netbird/Makefile
Release notes: https://github.com/netbirdio/netbird/releases
=> netbird: update to 0.21.1

utils/podman/Makefile
Contains several bug fixes.
Package now contains additional tool quadlet.
=> podman: update to v4.5.1

net/tunneldigger-broker/Makefile, net/tunneldigger-broker/files/config.default, net/tunneldigger-broker/files/hook-mtu-changed, net/tunneldigger-broker/files/hook-setup, net/tunneldigger-broker/files/hook-teardown, net/tunneldigger-broker/files/tunneldigger-broker.init, net/tunneldigger-broker/files/tunneldigger.sh, net/tunneldigger/Makefile, net/tunneldigger/files/config.default, net/tunneldigger/files/tunneldigger.init
Maintainer: me
Run tested: mt7621
=> [23.05] tunneldigger: add new package

net/tunneldigger-broker/Makefile, net/tunneldigger-broker/files/config.default, net/tunneldigger-broker/files/hook-mtu-changed, net/tunneldigger-broker/files/hook-setup, net/tunneldigger-broker/files/hook-teardown, net/tunneldigger-broker/files/tunneldigger-broker.init, net/tunneldigger-broker/files/tunneldigger.sh, net/tunneldigger/Makefile, net/tunneldigger/files/config.default, net/tunneldigger/files/tunneldigger.init
Maintainer: me
Run tested: mt7621
=> [22.03] tunneldigger: add new package

lang/python/python-ble2mqtt/Makefile, lang/python/python-bleak/Makefile, lang/python/python-dbus-fast/Makefile
Maintainer: me
Run tested: pending
Description:
Update python-ble2mqtt, python-dbus-fast, python-bleak packages
=> Update python-ble2mqtt, python-dbus-fast, python-bleak

net/krb5/Makefile
=> krb5: update to 1.21

lang/php8/Makefile
Maintainer: me
Run tested: Duckbill
=> php8: update to 8.2.7

lang/php8/Makefile
=> [22.03] php8: update to 8.1.20

lang/php8/Makefile
Maintainer: me
Run tested: I2SE Duckbill (mxs)
=> [21.02] php8: update to 8.0.29

devel/gitlab-runner/Makefile, devel/gitlab-runner/patches/010-test.patch, devel/gitlab-runner/test.sh
* Added test.sh script
* Fixed build with riscv64
* Passed package version via go ldflags
* Refreshed patches
* Removed useless test binaries from package
Maintainer: @ja-pa / Cc: @neheb 
Compile tested: armv8 / riscv64
=> gitlab-runner: Update to 16.0.2

lang/python/click/Makefile, lang/python/itsdangerous/Makefile, lang/python/pyodbc/Makefile, lang/python/python-gnupg/Makefile, lang/python/python-libmodbus/Makefile, lang/python/python-markupsafe/Makefile, lang/python/python-werkzeug/Makefile
Description:
This was requested in https://github.com/openwrt/packages/pull/21227#issuecomment-1567676980.
=> python-packages: Take over maintainership from Daniel Golle

lang/python/python-werkzeug/Makefile
=> python-werkzeug: Update to 2.3.6

lang/python/python-pluggy/Makefile
Maintainer: me, @ja-pa 
Description:
=> python-pluggy: Update to 1.2.0

lang/python/python-werkzeug/Makefile
Maintainer: me
Compile tested: none (cherry picked from #21463)
Description:
(cherry picked from commit acc915083d44386cb4890818ddacd8221573b7b0)
=> [openwrt-23.05] python-werkzeug: Update to 2.3.6

net/pdns-recursor/Makefile, net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch
Maintainer: me
Run tested: docker x86_64
Description:
=> pdns-recursor: update to 4.9.0

net/pdns/Makefile
=> pdns: update to 4.8.1

utils/dfu-programmer/Makefile
Changes:
* Add `--erase-first` option
Maintainer: me
Run tested: ath79
Description: Simple upgrade of package dfu-programmer to version 1.1.0
=> dfu-programmer: update to 1.1.0

net/iperf3/Makefile
Release Notes:
https://github.com/esnet/iperf/blob/master/RELNOTES.md
=> iperf3: update to 3.14

net/nginx-util/Makefile, net/nginx-util/src/ubus-cxx.hpp
=> nginx-util: fix compilation with GCC13

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Compile tested: mxs, riscv64
=> php8: update to 8.2.8

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
=> [22.03] php8: update to 8.1.21

net/tailscale/Makefile, net/tailscale/patches/010-fake_iptables.patch
=> tailscale: update to 1.44.0

admin/sudo/Makefile, admin/sudo/patches/020-no-owner-change.patch
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/816933bee6e6b68156f6aeea083117208bf859f8
Run tested: x86 https://github.com/openwrt/openwrt/commit/816933bee6e6b68156f6aeea083117208bf859f8
=> sudo: bump to verison 1.9.14p1

libs/libwebp/Makefile, libs/libwebp/patches/010-mips16.patch
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/816933bee6e6b68156f6aeea083117208bf859f8
Run tested: x86 https://github.com/openwrt/openwrt/commit/816933bee6e6b68156f6aeea083117208bf859f8
=> libwebp: bump to version 1.3.1

lang/rust/Makefile, lang/rust/patches/0001-Update-xz2-and-use-it-static.patch, lang/rust/patches/0002-Bumped-libc-version.patch, lang/rust/rust-values.mk
Run tested: NanoPi R2S
Description:
- Merged PR #21544 with @jefferyto's suggestion
- rust: Update to 1.71.0
Cc: @brocaar
=> rust: Update to 1.71.0

.github/workflows/entrypoint.sh
Description:
Currently, the run-test code tries to find the package source directory based on the directory name only. This fails for the Go compiler package because there is more than one directory named "golang".
This uses the full path listed in the "Source:" line of the control file to find the package source directory.
This also:
* Checks for the test script earlier, to avoid installing and removing ipk files when there is no test script to be run
* Makes `PKG_VERSION` parsing more lenient, as the package may not have a `PKG_RELEASE`, e.g. attendedsysupgrade-common
=> CI: Fix finding test script

libs/libnvme/Makefile, utils/nvme-cli/Makefile
Maintainer: me
Compile tested: aarch64
Run tested: bpi-r3
Description: lib + cli for diagnosing/manipulating nvme
=> nvme-cli: Add new package

libs/easyloggingpp/Makefile
Maintainer: me@vchrist.at
Compile tested: OpenWRT-23.05-rc2, arm_cortex-a7_neon-vfpv4, mips_24kc
Run tested: arm_cortex-a7_neon-vfpv4 (Linksys MR8300), mips_24kc (tplink_archer-a7), OpenWrt 23.05-rc2)
Description:
Easylogging++ is single header efficient logging library for C++ applications. It is extremely powerful, highly extendable and configurable to user's requirements.
Signed-off-by: Volker Christian <me@vchrist.at>
=> easyloggingpp: Add package

lang/python/python-atomicwrites/Makefile
=> python-atomicwrites: Update to 1.4.1

lang/python/python-awscli/Makefile, lang/python/python-boto3/Makefile, lang/python/python-botocore/Makefile, lang/python/python-s3transfer/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-07-16 snapshot
Description:
=> python-{awscli,boto3,botocore,s3transfer}: Update to latest versions, update dependencies

lang/python/python-awscli/Makefile, lang/python/python-boto3/Makefile, lang/python/python-botocore/Makefile, lang/python/python-s3transfer/Makefile
Compile tested: none (cherry picked from #21617)
Description:
=> [openwrt-23.05] python-{awscli,boto3,botocore,s3transfer}: Update to latest versions, update dependencies

utils/docker/Makefile, utils/dockerd/Makefile, utils/runc/Makefile
Description:
Updated docker to v23.0.5 and required dependencies
=> Docker: Update to 24.0.5

lang/python/python-docutils/Makefile
Run tested: armsr-armv7 (qemu), 2023-07-23 snapshot
Description:
=> python-docutils: Update to 0.20.1

lang/python/python-colorama/Makefile
Run tested: armsr-armv7 (qemu), 2023-07-23 snapshot
Description:
=> python-colorama: Update to 0.4.6

lang/python/python-cachelib/Makefile
Maintainer: @shenek
Description:
=> python-cachelib: Update to 0.10.2

lang/python/python-certifi/Makefile
Maintainer: @cotequeiroz
Description:
=> python-certifi: Update to 2023.7.22

lang/python/python-ciso8601/Makefile
Run tested: armsr-armv7 (qemu), 2023-07-23 snapshot
Description:
=> python-ciso8601: Update to 2.3.0

lang/python/python-contextlib2/Makefile
=> python-contextlib2: Update to 21.6.0

lang/python/python-dns/Makefile
=> python-dns: Update to 2.4.1

net/i2pd/Makefile, net/i2pd/patches/010-config.patch
Maintainer: @yangfl (David Yang)
Compile tested: mipsel_24k, MT7621, 22.03.5
Run tested: mipsel_24k, MT7621, 22.03.5
=> i2pd: update to version 2.48.0

lang/python/python-cachelib/Makefile
Maintainer: @shenek
Compile tested: none (cherry picked from #21669)
Description:
(cherry picked from commit d6d4222e9751f974356cce6dbaf77c7b12dfc5ad)
=> [openwrt-23.05] python-cachelib: Update to 0.10.2

lang/python/python-ciso8601/Makefile
Compile tested: none (cherry picked from #21672)
Description:
(cherry picked from commit 197c34e62dfdf37eccd248f6f5c72bec1f63d4a8)
=> [openwrt-23.05] python-ciso8601: Update to 2.3.0

lang/python/python-contextlib2/Makefile
Compile tested: none (cherry picked from #21674)
Description:
(cherry picked from commit c0552ae0d411c4768a1e9b9500e1570d86761b13)
=> [openwrt-23.05] python-contextlib2: Update to 21.6.0

lang/python/python-dns/Makefile
Compile tested: none (cherry picked from #21675)
Description:
(cherry picked from commit 03f78eff74a5e37a61314e27f428768aeddbba46)
=> [openwrt-23.05] python-dns: Update to 2.4.1

lang/python/python-docutils/Makefile
Compile tested: none (cherry picked from #21676)
Description:
(cherry picked from commit c2a725ec0029c78eb24eb5784bb99e6f7f69ffe7)
=> [openwrt-23.05] python-docutils: Update to 0.20.1

net/i2pd/Makefile, net/i2pd/patches/010-config.patch
Maintainer: me
Description: backport as requested #21741
=> [openwrt-22.03] i2pd: update to version 2.48.0

net/i2pd/Makefile, net/i2pd/patches/010-config.patch
Maintainer: me
Description: backport as requested https://github.com/openwrt/packages/issues/21741
=> [openwrt-23.05] i2pd: update to version 2.48.0

libs/libnvme/Makefile, utils/nvme-cli/Makefile
Description: Change the categories as per @jefferyto suggestion.
=> nvme-cli: Fix categorization

lang/python/python-flask-httpauth/Makefile
=> python-flask-httpauth: Update to 4.8.0

lang/python/python-flask-login/Makefile
=> python-flask-login: Update to 0.6.2, update list of dependencies

lang/python/python-flask-seasurf/Makefile
=> python-flask-seasurf: Update to 1.1.1

lang/python/python-click/Makefile
=> python-click: Update to 8.1.6

lang/python/python-ifaddr/Makefile
=> python-ifaddr: Update to 0.2.0

lang/python/python-multidict/Makefile
=> python-multidict: Update to 6.0.4, update list of dependencies

lang/python/python-netdisco/Makefile
=> python-netdisco: Update to 3.0.0, update list of dependencies

lang/python/python-influxdb/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-08-06 snapshot
Description:
=> python-influxdb: Update to 5.3.1

lang/python/python-engineio/Makefile
Compile tested: none (cherry picked from #21702)
Description:
(cherry picked from commit 466dfed2f20caf23da40928950a664d1e773d7f3)
=> [openwrt-23.05] python-engineio: Update to 4.5.1

lang/python/python-socketio/Makefile
Compile tested: none (cherry picked from #21703)
Description:
(cherry picked from commit 7e931594c7b20f11863d7816531dd583bce728b7)
=> [openwrt-23.05] python-socketio: Update to 5.8.0

lang/python/python-flask-httpauth/Makefile
Compile tested: none (cherry picked from #21706)
Description:
(cherry picked from commit f5411f260a1701c26885ef71d2d2499ff8e582cd)
=> [openwrt-23.05] python-flask-httpauth: Update to 4.8.0

lang/python/python-flask-login/Makefile
Compile tested: none (cherry picked from #21707)
Description:
(cherry picked from commit d91ddd5d75b84b39e97f1f5eedc9a1bc91e85614)
=> [openwrt-23.05] python-flask-login: Update to 0.6.2, update list of dependencies

lang/python/python-ifaddr/Makefile
Compile tested: none (cherry picked from #21747)
Description:
(cherry picked from commit fbc3629ecabb35d9d91eb4fedd8b56b5813a64ec)
=> [openwrt-23.05] python-ifaddr: Update to 0.2.0

lang/python/python-jsonpath-ng/Makefile
=> python-jsonpath-ng: Update to 1.5.3

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Description:
This fixes:
- CVE-2023-3823
- CVE-2023-3824
=> [22.03] php8: update to 8.1.22

lang/php8/Makefile
=> [21.02] php8: update to 8.0.30

lang/python/python-distro/Makefile
Maintainer: @jmarcet
Description:
=> python-distro: Update to 1.8.0

lang/python/python-markdown/Makefile
=> python-markdown: Update to 3.4.4, update list of dependencies

lang/python/python-influxdb/Makefile
Compile tested: none (cherry picked from #21748)
Description:
(cherry picked from commit f477ad0ef9f1f67a9eaa316688812dcab76413c1)
=> [openwrt-23.05] python-influxdb: Update to 5.3.1

lang/python/python-jsonpath-ng/Makefile
Compile tested: none (cherry picked from #21751)
Description:
(cherry picked from commit 8bf67793bc17a032d9e4315cea518c9510b1c5b0)
=> [openwrt-23.05] python-jsonpath-ng: Update to 1.5.3

lang/python/python-multidict/Makefile
Compile tested: none (cherry picked from #21794)
Description:
(cherry picked from commit d219b6d28fe240295cfff9027409e8ce6d3c80af)
=> [openwrt-23.05] python-multidict: Update to 6.0.4, update list of dependencies

lang/python/python-netdisco/Makefile
Compile tested: none (cherry picked from #21795)
Description:
(cherry picked from commit da25e997259e0999a0531fca2a4269c7c7f4fdd4)
=> [openwrt-23.05] python-netdisco: Update to 3.0.0, update list of dependencies

lang/python/python-markdown/Makefile
Compile tested: none (cherry picked from #21791)
Description:
(cherry picked from commit ec19051980414c4466551d3dab9e53d16ca3f297)
=> [openwrt-23.05] python-markdown: Update to 3.4.4, update list of dependencies

lang/python/python-distro/Makefile
Maintainer: @jmarcet
Compile tested: none (cherry picked from #21790)
Description:
(cherry picked from commit 0068a50193e887746128e456a8a8802322e5f6e9)
=> [openwrt-23.05] python-distro: Update to 1.8.0

admin/bottom/Makefile
Compile tested: aarch64 23.05 and mainline
Run tested: bpi-r3 
Description: Bottom is a top/htop workalike with few additional features, written in rust.
=> bottom: New package

lang/python/python-py/Makefile
=> python-py: Update to 1.11.0, update list of dependencies

lang/python/python-pyotp/Makefile
=> python-pyotp: Update to 2.9.0, update list of dependencies

lang/python/python-pyrsistent/Makefile
=> python-pyrsistent: Update to 0.19.3, update list of dependencies

lang/python/python-pytest/Makefile
=> python-pytest: Update to 7.4.0, update list of dependencies

lang/lua-lsqlite3/Makefile
=> lua-lsqlite3: add build VARIANT for Lua5.3

lang/lua-lsqlite3/Makefile
=> [openwrt-23.05 ] lua-lsqlite3: add build VARIANT for Lua5.3

libs/easyloggingpp/Makefile
Maintainer: [me@vchrist.at](mailto:me@vchrist.at)
Compile tested: OpenWRT-23.05-rc2, arm_cortex-a7_neon-vfpv4, mips_24kc
Run tested: arm_cortex-a7_neon-vfpv4 (Linksys MR8300), mips_24kc (tplink_archer-a7), OpenWrt 23.05-rc2)
Description:
Easylogging++ is single header efficient logging library for C++ applications. It is extremely powerful, highly extendable and configurable to user's requirements.
=> [openwrt-23.05] easyloggingpp: Add package

net/v2raya/Makefile
Maintainer: me
Description:
Fixed ssr bug and added tuic protocol.
Release notes:
https://github.com/v2rayA/v2rayA/releases/tag/v2.2.0
https://github.com/v2rayA/v2rayA/releases/tag/v2.2.1
=> v2raya: Update to 2.2.1

lang/python/python-pyotp/Makefile
Compile tested: none (cherry picked from #21860)
Description:
(cherry picked from commit 001c2cbe0d3ab8e78c18adea504ea2320ab496eb)
=> [openwrt-23.05] python-pyotp: Update to 2.9.0, update list of dependencies

lang/python/python-pyrsistent/Makefile
Compile tested: none (cherry picked from #21862)
Description:
(cherry picked from commit 383b8c1658c5f9e39e17352f857338d0e6b46d16)
=> [openwrt-23.05] python-pyrsistent: Update to 0.19.3, update list of dependencies

lang/python/python-pytest/Makefile
Compile tested: none (cherry picked from #21863)
Description:
(cherry picked from commit b130986e1734576de957df37dfc4451756f2d070)
=> [openwrt-23.05] python-pytest: Update to 7.4.0, update list of dependencies

libs/file/Makefile
Description:
Update to the most recent version 5.44
=> [openwrt-23.05] file: Update to version 5.44

net/pdns-recursor/Makefile
Run tested: docker amd64
Description:
=> pdns-recursor: update to 4.9.1

net/zerotier/Makefile, net/zerotier/files/etc/init.d/zerotier, net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-paths.patch, net/zerotier/patches/0002-remove-PIE-options.patch, net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch, net/zerotier/patches/0004-add-missing-libatomic.patch, net/zerotier/patches/0005-remove-noexecstack.patch
Maintainer: me
Compile tested: ramips/mt7620 (Nexx WT3020),  OpenWrt master
Run tested: same as compiled
```
root@OpenWrt:~# zerotier-cli  -v
1.12.1
root@OpenWrt:~# zerotier-cli status
200 info 8ce63a4313 1.12.1 ONLINE
````
=> zerotier: update to 1.12.1

net/v2raya/Makefile, net/v2raya/patches/010-go-version.patch
Maintainer: me
Compile tested: mediatek/filogic
Run tested: redmi ax6000
Description:
- cherry picked from PR #21934 
- added a patch to fix build with Go 1.20
=> [openwrt-23.05] v2raya: Update to 2.2.1

lang/python/python-schedule/Makefile
Run tested: armsr-armv7 (qemu), 2023-08-20 snapshot sdk
Description:
=> python-schedule: Update to 1.2.0

lang/python/python-schema/Makefile
Run tested: armsr-armv7 (qemu), 2023-08-20 snapshot sdk
Description:
=> python-schema: Update to 0.7.5

lang/python/python-sentry-sdk/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-08-20 snapshot sdk
Description:
=> python-sentry-sdk: Update to 1.29.2, update list of dependencies

lang/python/python-pluggy/Makefile
=> python-pluggy: Update to 1.3.0

net/nginx/Makefile
=> nginx: fix erroneous new line escape in Makefile

libs/nss/Makefile, libs/nss/patches/010-nanosleep.patch
=> nss: update to 3.93

libs/libre2/Makefile
Need the suffixed library too.
Maintainer:
=> libre2: fix install

lang/python/python-schedule/Makefile
Compile tested: none (cherry picked from #21909)
Description:
(cherry picked from commit 53dadf2c50a8635aab23e12110f1823b8b041512)
=> [openwrt-23.05] python-schedule: Update to 1.2.0

lang/python/python-schema/Makefile
Compile tested: none (cherry picked from #21910)
Description:
(cherry picked from commit 8c7709b911df9f85189a9c71cfc196702f4cb338)
=> [openwrt-23.05] python-schema: Update to 0.7.5

lang/python/python-sentry-sdk/Makefile
Compile tested: none (cherry picked from #21911)
Description:
(cherry picked from commit f279ae9418fff4f83bd16b353ef008e548d82cd7)
=> [openwrt-23.05] python-sentry-sdk: Update to 1.29.2, update list of dependencies

lang/python/python-sqlalchemy/Makefile
Compile tested: none (cherry picked from #21913)
Description:
This also adds a build dependency on python-cython/host.
(cherry picked from commit 8b6a817af298364134f3ec37cbb8bfda48b2a35f)
=> [openwrt-23.05] python-sqlalchemy: Update to 2.0.20, update list of dependencies

lang/python/python-pluggy/Makefile
Compile tested: none (cherry picked from #21941)
Description:
(cherry picked from commit 88632b7b64309fb18cdd83ddef5076bb66d4b21c)
=> [openwrt-23.05] python-pluggy: Update to 1.3.0

net/zerotier/Makefile, net/zerotier/files/etc/init.d/zerotier, net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-paths.patch, net/zerotier/patches/0002-remove-PIE-options.patch, net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch, net/zerotier/patches/0004-add-missing-libatomic.patch, net/zerotier/patches/0005-remove-noexecstack.patch
Maintainer: me
Description:
Apply all patches from master until ZeroTier 1.12.1 execept https://github.com/openwrt/packages/commit/35f4ef76e0c88b690ec55f26aed072c4c5989eff
=> [openwrt-23.05] zerotier: update to 1.12.1

net/zerotier/Makefile, net/zerotier/files/etc/init.d/zerotier, net/zerotier/patches/0001-fix-makefile.patch, net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-paths.patch, net/zerotier/patches/0002-remove-PIE-options.patch, net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch, net/zerotier/patches/0004-add-missing-libatomic.patch, net/zerotier/patches/0005-remove-noexecstack.patch
Maintainer: me
Description:
Apply all patches from master until ZeroTier 1.12.1 execept https://github.com/openwrt/packages/commit/35f4ef76e0c88b690ec55f26aed072c4c5989eff
=> [openwrt-22.03] zerotier: update to 1.12.1

net/zerotier/Makefile, net/zerotier/files/etc/init.d/zerotier, net/zerotier/patches/0001-fix-makefile.patch, net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-paths.patch, net/zerotier/patches/0002-remove-PIE-options.patch, net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch, net/zerotier/patches/0004-add-missing-libatomic.patch, net/zerotier/patches/0005-remove-noexecstack.patch
Maintainer: me
Description:
Apply all patches from master until ZeroTier 1.12.1 execept https://github.com/openwrt/packages/commit/35f4ef76e0c88b690ec55f26aed072c4c5989eff
=> [openwrt-21.03] zerotier: update to 1.12.1

lang/python/python-voluptuous/Makefile
=> python-voluptuous: Update to 0.13.1, update list of dependencies

lang/python/python-wcwidth/Makefile
=> python-wcwidth: Update to 0.2.6

lang/python/python-websockets/Makefile
Maintainer: @paper42 
Description:
=> python-websockets: Update to 11.0.3, update list of dependencies

lang/python/python-voluptuous/Makefile
Compile tested: none (cherry picked from #21947)
Description:
(cherry picked from commit 6c7a53bd7da4d8eeb49429f0321bfa0ce59a311c)
=> [openwrt-23.05] python-voluptuous: Update to 0.13.1, update list of dependencies

lang/python/python-wcwidth/Makefile
Compile tested: none (cherry picked from #21949)
Description:
(cherry picked from commit 3684df0dc356a9c5b1e7c51cc43e203c7254c8e5)
=> [openwrt-23.05] python-wcwidth: Update to 0.2.6

libs/slang2/Makefile
Maintainer: me
Description:
Please see the individual commit messages for details.
=> slang2: Avoid building dependencies unless necessary, remove pcre module

lang/python/python-websockets/Makefile
Compile tested: none (cherry picked from #21950)
Description:
(cherry picked from commit 98453732e2b7f74234776445844609f3b4dc70d0)
=> [openwrt-23.05] python-websockets: Update to 11.0.3, update list of dependencies

net/pdns/Makefile
Compile tested: in github CI
Description:
=> pdns: update to 4.8.2

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
=> php8: update to 8.2.10

lang/python/python-cryptodomex/Makefile, lang/python/python-cryptodomex/patches/001-fix-libgmp-loading.patch, lang/python/python-cryptodomex/patches/002-omit-tests.patch
Run tested: armsr-armv7 (qemu), 2023-09-03 snapshot
Description:
=> python-cryptodomex: Update to 3.18.0, refresh patches

lang/python/python-yaml/Makefile
Run tested: armsr-armv7 (qemu), 2023-09-03 snapshot
Description:
=> python-yaml: Update to 6.0.1

lang/python/python-crcmod/Makefile
Maintainer: @blocktrron
Description:
=> python-crcmod: Fix package section

lang/python/django/Makefile, lang/python/numpy/Makefile, lang/python/python-chardet/Makefile
Maintainer: me, @peter-stadler (for Django)
Compile tested: x86 https://github.com/openwrt/openwrt/commit/7f54d9ba1aa9796e218b554633a4e05906a9ac7f
Run tested: x86 https://github.com/openwrt/openwrt/commit/7f54d9ba1aa9796e218b554633a4e05906a9ac7f
=> chardet,numpy,django: bump versions

net/dnsdist/Makefile
Run tested: x86_6 docker
Description:
=> dnsdist: update to 1.8.1

lang/python/python-yaml/Makefile
Compile tested: none (cherry picked from #22035)
Description:
(cherry picked from commit 60315a663884b9cf76f787eca10714bfc085335e)
=> [openwrt-23.05] python-yaml: Update to 6.0.1

net/nextdns/Makefile
=> nextdns: Update to version 1.40.1

net/nextdns/Makefile
=> [22.03] nextdns: Update to version 1.40.1

net/nextdns/Makefile
=> [21.02] nextdns: Update to version 1.40.1

lang/perl-text-csv_xs/Makefile
Maintainer: me
Compile tested: x86_64, generic, HEAD (9194fcb1a4)
Description:
Routine update to upstream latest.
=> perl-text-csv_xs: Update to 1.51

utils/setools/Makefile
Compile tested: armsr-armv7, 2023-09-16 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-09-16 snapshot
Description:
=> setools: Update to 4.4.3

utils/setools/Makefile
Compile tested: none (cherry picked from #22155)
Description:
(cherry picked from commit 0ea5e63b15065b79fc6d9fef799e3947750c8368)
=> [openwrt-23.05] setools: Update to 4.4.3

net/mwan3/Makefile, net/mwan3/files/lib/mwan3/common.sh, net/mwan3/files/lib/mwan3/mwan3.sh, net/mwan3/files/usr/libexec/rpcd/mwan3
Maintainer: me
Compile tested: not needed
Run tested: x86_64, APU3, master
Description:
Some updates for `ubus call mwan3 status` and `mwan3 status` see commits description in this PR.
=> mwan3: update ubus and status view

lang/python/django/Makefile
(cherry picked from commit 331b5f75f4b4d5b71c6db9bd6658b6eeef01d891)
=> [23.05] django: bump to version 4.2.5

net/mdnsresponder/Makefile, net/openthread-br/Makefile, net/openthread-br/patches/100-rest-support-deleting-the-dataset.patch
=> openthread-br: fix actually building

mail/exim/Makefile, mail/exim/patches/000-preliminary-fixes-for-ZDI-vulns.patch
Maintainer: me
Run tested: -
Description:
Apply preliminary hotfix for some (three?) of the 0-day vulnerabilities reported by ZDI.
(cherry picked from commit db85d9ead6c3258757e199ad1fbd5bd20c9aac5f)
=> [23.05] exim: apply hotfix for some ZDI reported vulnerabilities

mail/exim/Makefile, mail/exim/patches/000-preliminary-fixes-for-ZDI-vulns.patch
Maintainer: me
Run tested: -
Description:
Apply preliminary hotfix for some (three?) of the 0-day vulnerabilities reported by ZDI.
(cherry picked from commit db85d9ead6c3258757e199ad1fbd5bd20c9aac5f)
=> [22.03] exim: apply hotfix for some ZDI reported vulnerabilities

net/aardvark-dns/Makefile
changes:
- dependency updates
Maintainer: me
=> aardvark-dns: update to 1.8.0

lang/python/python-pyopenssl/Makefile, lang/python/python-pyopenssl/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-09-24 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-09-24 snapshot
Description:
=> python-pyopenssl: Update to 23.2.0

lang/python/python-packaging/Makefile, lang/python/python-packaging/test.sh
Compile tested: armsr-armv7, 2023-10-03 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-10-03 snapshot
Description:
=> python-packaging: Update to 23.2

lang/python/python-pyopenssl/Makefile, lang/python/python-pyopenssl/test.sh
Maintainer: me
Compile tested: none (cherry picked from #22246)
Description:
(cherry picked from commit bb278a015c6b76ca2c9fdf6663dbd7428777915e)
=> [openwrt-23.05] python-pyopenssl: Update to 23.2.0

lang/python/python-bcrypt/Makefile, lang/python/python-bcrypt/test.sh
Maintainer (to be): me
Compile tested: none (cherry picked from #22247)
Description:
(cherry picked from commit 6b3da46777bb5d029a4933481ee5939efa7c7109)
=> [openwrt-23.05] python-bcrypt: Update to 4.0.1, add myself as maintainer

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
=> php8: update to 8.2.11

net/nextdns/Makefile
=> nextdns: Update to version 1.41.0

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.41.0

net/nextdns/Makefile
=> [22.03] nextdns: Update to version 1.41.0

net/kea/Makefile, net/kea/patches/003-no-test-compile.patch
Maintainer: @rosysong
Compile tested: OpenWrt master r24096-9536446965 x86/64
Run tested: OpenWrt master r24096-9536446965 x86/64
=> kea: bump to latest stable version

net/cni-protocol/Makefile, net/cni-protocol/files/cni.sh
Changes to protocol file and it's description.
Works better now and restarts firewall automaticly when tunnel comes available. More informative/guiding description.
Maintainer: me
Compile tested: x86_64/latest git
Run tested: x86_64/latest git
=> cni-protocol: update protocol

net/ddns-scripts/Makefile
Description: closes #20800
I am not sure how to run this `Makefile`. I tried to drop it inside the `openwrt` root tree, then run `make`, but it didn't work, so couldn't test how this works...
=> ddns-scripts: add samples to package

lang/perl-text-csv_xs/Makefile
Maintainer: me
Compile tested: x86_64, generic, HEAD (12584395dc)
Description:
Update to 1.52
=> Perl text csv xs update 1.52

lang/luajit2/Makefile, lang/luajit2/patches/010-lua-path.patch
=> luajit2: update to v2.1-20231006

net/netbird/Makefile
Changelog:
- Add Pagination for IdP Users Fetch by @bcmmbaga in #1210
- Rework peer connection status based on the update channel existence by @surik in #1213
- Fix nil pointer exception in group delete by @pappz in #1211
- Fix/key backup in config script by @pappz in #1206
[Full changelog](https://github.com/netbirdio/netbird/compare/v0.23.8...v0.23.9)
Maintainer: me
=> netbird: update to 0.23.9

net/pdns/Makefile, net/pdns/files/pdns.conf-dist
Maintainer: me
Run tested: Docker openwrt/rootfs x86_64
Description:
=> pdns: update to 4.8.3

net/nginx/Config_ssl.in, net/nginx/Makefile
Add option to compile STREAM REAL IP module.
Closes: #22310
=> nginx: add option to compile STREAM REAL IP module

lang/php8/Makefile
=> php8: update to 8.2.12

lang/php8/Makefile, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Compile tested: mxs, Duckbill
=> [22.03] php8: update to 8.1.25

net/zerotier/Makefile, net/zerotier/files/etc/init.d/zerotier
Signed-off-by: adam-qomodo
Maintainer: me
Description: Fixes a typo in a message
=> zerotier: fix typo

libs/postgresql/Makefile, libs/postgresql/patches/700-no-arm-crc-march-change.patch, libs/postgresql/patches/900-pg_ctl-setuid.patch
Maintainer: me
Run tested: -
Description:
Update to latest PostgreSQL version 14 for OpenWrt 22.03.
=> [22.03] postgresql: update to version 14.9

net/sing-box/Makefile
see changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.6.0
Description:
=> sing-box: update to v1.6.0

lang/python/pyodbc/Makefile, lang/python/python-pyodbc/Makefile, lang/python/python-pyodbc/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-10-28 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-10-28 snapshot
Description:
=> pyodbc: Update to 5.0.1, rename source package, fix segmentation fault

net/sing-box/Makefile
see changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.6.0
Signed-off-by: Leo Douglas <douglarek@gmail.com>
(cherry picked from commit 84c431702e97ba70228ec45b60482163fc0d974d)
Description:
=> [openwrt-23.05] sing-box: update to v1.6.0

lang/python/python-constantly/Makefile, lang/python/python-constantly/patches/001-unpin-setuptools.patch, lang/python/python-constantly/test.sh, lang/python/python-versioneer/Makefile
Maintainer: me
Compile tested: armsr-armv7, 2023-10-28 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-10-28 snapshot
Description:
=> python-constantly: Update to 23.10.4, add new build dependency

lang/python/python-mako/Makefile
Maintainer: me
Compile tested: armsr-armv7-2023-11-10 snapshot sdk
Description:
=> python-mako: Update to 1.3.0

lang/python/pipx/Makefile, lang/python/pipx/test.sh, lang/python/python-argcomplete/Makefile, lang/python/python-argcomplete/patches/001-unpin-setuptools.patch, lang/python/python-argcomplete/test.sh, lang/python/python-userpath/Makefile, lang/python/python-userpath/patches/0001-Handle-OSErrors-when-running-show-path-commands.patch, lang/python/python-userpath/patches/0001-Use-Sh-as-base-class-for-Bash-and-Zsh.patch, lang/python/python-userpath/patches/0002-Add-support-for-ash-Almquist-shell.patch, lang/python/python-userpath/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-11-05 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-11-05 snapshot
Description:
pipx is a tool to install Python command-line applications, each installed in its own virtual environment.
=> pipx: Add new package, add new dependencies

net/dhtd/Makefile, net/dhtd/files/dhtd.config, net/dhtd/files/dhtd.init
Maintainer: me
Compile tested: ramips/mt7620, Nexx wt3020, OpenWrt master at [516a3176a671c4b8f344db39dbc0e003fbb841b8](https://github.com/openwrt/openwrt/commit/516a3176a671c4b8f344db39dbc0e003fbb841b8)
Run tested: same as compile target
Description:
A small DHTd daemon that utilizes the BitTorrent network and offers a command interface control unitility (dhtd-ctl).
=> dhtd: new package

libs/libnpupnp/Makefile, libs/libupnpp/Makefile, sound/upmpdcli/Makefile, sound/upmpdcli/patches/010-gcc13.patch
=> upmpcli: update and fix with GCC13

net/tailscale/Makefile
=> tailscale: Update to 1.54.0

utils/gummiboot/Makefile, utils/gummiboot/patches/030-fix-efi-conflicts.patch
Changes:
- fixes conflicts with EFI headers mentioned in issue #22433
Maintainer: me
=> gummiboot: release bump

net/dhtd/Makefile, net/dhtd/files/dhtd.config, net/dhtd/files/dhtd.init
Maintainer: me
Compile tested: yes (OpenWrt 23.05.2)
Run tested: no (cherry-picked from master and trivial dependencies)
=> [openwrt-23.05] dhtd: new package

net/gensio/patches/0001-Ensure-that-ax_python_devel_found-is-defined.patch
Run tested: -
Description:
This hopefully resolves the buildbot issues finally.
Upstream PR: https://github.com/cminyard/gensio/pull/69
=> gensio: add patch to fix python detection

net/dhtd/Makefile, net/dhtd/files/dhtd.config, net/dhtd/files/dhtd.init
(cherry picked from commit 819cf67a338611681d2bee7ee37eec5864110fc3)
Maintainer: me
Compile tested: done for master
Run tested: done for master
=> [openwrt-23.05] dhtd: update to 0.2.4

multimedia/yt-dlp/Makefile
Compile tested: Netgear XR700 ARMv7 Processor rev 4 (v7l), OpenWrt SNAPSHOT r24502-1127d0a212d9
Run tested: Netgear XR700 ARMv7 Processor rev 4 (v7l), OpenWrt SNAPSHOT r24502-1127d0a212d9
=> yt-dlp: bump to version 2023.11.16

net/strongswan/Makefile, net/strongswan/patches/0900-src-Patch-for-building-with-musl-on-openwrt-taken-ve.patch, net/strongswan/patches/0904-gmpdh-Plugin-that-implements-gmp-DH-functions-in-an-.patch
Compile tested: x86_64, generic, HEAD (59a66d3c9b)
Run tested: same, not installed
Description:
Bump source to 5.9.12
=> strongswan: Update to 5.9.12

lang/python/python-jsonschema-specifications/Makefile, lang/python/python-jsonschema-specifications/test.sh, lang/python/python-jsonschema/Makefile, lang/python/python-jsonschema/test.sh, lang/python/python-referencing/Makefile, lang/python/python-referencing/test.sh, lang/python/python-rpds-py/Makefile, lang/python/python-rpds-py/test.sh
Maintainer: @jmarcet, me (new dependencies)
Compile tested: armsr-armv7, 2023-10-11 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-10-11 snapshot
Description:
=> python-jsonschema: Update to 4.19.1, add new dependencies

lang/python/python-idna/Makefile, lang/python/python-idna/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-11-26 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-11-26 snapshot
Description:
This also adds a test.sh script for the packages feed CI.
=> python-idna: Update to 3.6

net/netifyd/Config.in, net/netifyd/Makefile
Maintainer: Darryl Sokoloski / @dsokoloski
Compile tested: arm_cortex-a15_neon-vfpv4, TP-Link Archer C2600, master
Run tested: TP-Link Archer C2600
https://gitlab.com/netify.ai/public/netify-agent/-/releases/v4.4.7
=> netifyd: Updated to v4.4.7

net/netbird/Makefile
Changelog: https://github.com/netbirdio/netbird/releases/tag/v0.24.3
Maintainer: me
=> netbird: update to version 0.24.3

.github/workflows/formal.yml, CONTRIBUTING.md
Compile tested: not applicable here
Run tested: not applicable here
Description: fix some typos and grammar.
=> CONTRIBUTING.md: fix typos

net/uspot/Makefile
Maintainer: me
Compile tested: ath79, ramips - OpenWrt 23.05
Run tested: ath79, ramips - OpenWrt 23.05
Description:
A captive portal system for OpenWrt
If accepted, a backport to 23.05 would be nice: it's been fairly thoroughly tested there :)
=> uspot: add package

net/dhtd/Makefile
Maintainer: me
Compile tested: only pipeline
Run tested: only on laptop. Only minimal changes.
Description:
* add more status output
=> dhtd: udpate to 0.2.6

lang/python/pipx/Makefile, lang/python/python-platformdirs/Makefile, lang/python/python-platformdirs/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-12-03 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-12-03 snapshot
Description:
=> pipx: Update to 1.3.2, add new dependencies, add new dependency package

utils/cligen/Makefile
Some review comments came in after merge, so we'll address them here.
Compile tested: x86_64, generic, HEAD (ae500e62e2)
Run tested: same, installed on VM
Description:
=> Cligen review comments

libs/cyrus-sasl/Makefile
=> cyrus-sasl: create libsasl2-utils package for programs

net/snort3/Makefile
Michael invited me to co-maintain[1].
1. https://github.com/openwrt/packages/pull/22830#issuecomment-1848997029
=> snort3: add myself as a co-maintainer

lang/python/pipx/Makefile
Maintainer: me
Compile tested: armsr-armv7, 2023-12-10 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-12-10 snapshot
Description:
=> pipx: Update to 1.3.3

lang/php8/Makefile, lang/php8/patches/0022-Use-system-timezone.patch, lang/php8/patches/0025-php-5.4.9-fixheader.patch, lang/php8/patches/1004-disable-phar-command.patch
=> php8: update to 8.3.0

lang/php8/Makefile
=> [22.03] php8: update to 8.1.26

lang/php8/Makefile
=> [23.05] php8: update to 8.2.13

utils/syncthing/Makefile
Run tested: (x86_64, OpenWrt snapshot)
Description:
No breaking changes between 1.24.0 and 1.27.0. And I've added myself to the maintainer list.
=> syncthing: update to 1.27.1

libs/openblas/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/493f7f5eeec4e97ff9da9cfb23c26d7c273b44c9
Run tested: x86 https://github.com/openwrt/openwrt/commit/493f7f5eeec4e97ff9da9cfb23c26d7c273b44c9
=> openblas: bump to version 0.3.25

admin/sudo/Makefile, admin/sudo/patches/020-no-owner-change.patch, admin/sudo/test.sh
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/493f7f5eeec4e97ff9da9cfb23c26d7c273b44c9
Run tested: x86 https://github.com/openwrt/openwrt/commit/493f7f5eeec4e97ff9da9cfb23c26d7c273b44c9
=> sudo: bump to verison 1.9.15p4

net/dnsdist/Makefile
=> dnsdist: update to 1.8.3

net/pdns/Makefile
=> pdns: update to 4.8.4

net/alist/Makefile, net/alist/files/alist.config, net/alist/files/alist.init, net/alist/test.sh
Maintainer: me
Run tested: mediatek/filogic, rockchip/armv8, x86/64
Description:
AList is a file list/WebDAV program that supports multiple storages, powered by Gin and Solidjs.
Official documentation: https://alist.nn.ci
=> alist: add new package

utils/mariadb/Makefile, utils/mariadb/files/mysqld.config, utils/mariadb/files/mysqld.init
Maintainer: @miska
Run tested: -
Description: Just a few minor things, I stumbled over in my last review. Should not affect runtime/build behavior.
=> mariadb: minor whitespace and typo fixes

net/tailscale/Makefile
Maintainer: @ja-pa @oskarirauta 
Signed-off-by: Shi JiaYang <shi05275@163.com>
=> tailscale: Update to 1.56.1

lang/python/django/Makefile, lang/python/django/test.sh
Compile tested: x86 https://github.com/openwrt/openwrt/commit/493f7f5eeec4e97ff9da9cfb23c26d7c273b44c9
Run tested: x86 https://github.com/openwrt/openwrt/commit/493f7f5eeec4e97ff9da9cfb23c26d7c273b44c9
=> django: bump to version 5.0

libs/xmlrpc-c/Makefile
Compile tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2
Run tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2, tested with internal software
Description: copy `*.pc` files into the staging directory.
=> libs/xmlrpc-c: install pkgconf files

lang/php8/Makefile, lang/php8/patches/1004-disable-phar-command.patch
=> [23.05] php8: update to 8.2.14

lang/php8/Makefile, lang/php8/patches/1004-disable-phar-command.patch
=> [22.03] php8: update to 8.1.27

lang/php8/Makefile
=> php8: update to 8.3.1

utils/containerd/Makefile, utils/docker/Makefile, utils/dockerd/Makefile, utils/runc/Makefile
Description:
Updated docker to v24.0.7 and required dependencies
=> Docker: Update to 24.0.7

lang/php8-pecl-mcrypt/Makefile
=> php8-pecl-mcrypt: update to 1.0.7

libs/libsoup3/Makefile
=> libsoup3: update to 3.4.4

net/krb5/Makefile
=> krb5: update to 1.21.2

libs/libgcrypt/Makefile
=> libgcrypt: update to 1.10.3

libs/vips/Makefile
=> vips: update to 8.15.1

utils/shared-mime-info/Makefile, utils/shared-mime-info/patches/001-no-xmllint.patch
=> shared-mime-info: update to 2.4

lang/luasec/Makefile
=> luasec: update to 1.3.2

libs/hwloc/Makefile
=> hwloc: update to 2.10.0

libs/libdmapsharing/Makefile, libs/libdmapsharing/patches/001-disable_pixbuf.patch
=> libdmapsharing: update to 3.9.13

net/nfdump/Makefile
=> nfdump: update to 1.7.3

libs/openldap/Makefile
=> openldap: update to 2.6.6

mail/pigeonhole/Makefile
=> pigeonhole: update to 0.5.21

lang/python/python-networkx/Makefile
=> python-networkx: update to 3.2.1

utils/semodule-utils/Makefile
=> semodule-utils: update to 3.6

lang/python/python-sqlalchemy/Makefile
=> python-sqlalchemy: update version 2.0.23

lang/python/python-zope-event/Makefile
Maintainer: @predators46 
Description:
python-zope-event: add python-zope-event
https://pypi.org/project/zope.event/
source code
https://github.com/zopefoundation/zope.event
=> python-zope-event: add python-zope-event

net/netbird/Makefile
Description:
Release notes
https://github.com/netbirdio/netbird/releases/tag/v0.25.2
=> netbird: update to version 0.25.2

lang/python/python-msgpack/Makefile
=> python-msgpack: update version 1.0.7

lang/python/python-zeroconf/Makefile
=> python-zeroconf: update version 0.131.0

net/hs20/Makefile, net/hs20/patches/010-libxml-212.patch
=> hs20: fix compilation with libxml 2.12

lang/python/python-gevent/Makefile
Maintainer: @predators46 
Description:
python-gevent: add python-gevent
https://pypi.org/project/gevent/
https://www.gevent.org/development/installing_from_source.html
source code
https://github.com/gevent/gevent
=> python-gevent: add python-gevent

net/dhtd/Makefile
Maintainer: me
Compile tested: on Debian only  since there are only minor changes
Run tested: no
=> dhtd: update to 1.0.1

mail/dovecot/Makefile
=> dovecot: update to 2.3.21

net/i2pd/Makefile
=> i2pd: Update to 2.50.2

net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* somehow parts of the code of the init script got different between the main branch and release branch, this PR fixes that.
=> [23.05] adblock-fast: sync with main branch

admin/sudo/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/622340f6c10a492c03e6d0c0ee004da1c43270bc
Run tested: x86  https://github.com/openwrt/openwrt/commit/622340f6c10a492c03e6d0c0ee004da1c43270bc
=> sudo: bump to verison 1.9.15p5

net/evilginx2/Makefile
=> evilginx2: add new package

net/pdns-recursor/Makefile, net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch
also fix license variable
Maintainer: me
Run tested: x86_64 Docker openwrt/rootfs
Description:
=> pdns-recursor: Build rec-5.0.1, adding Rust dependencies

net/i2pd/Makefile
https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Ai2pd%3Ai2pd
Maintainer: @yangfl 
=> net/i2pd: assign PKG_CPE_ID

lang/python/python-ble2mqtt/Makefile, lang/python/python-dbus-fast/Makefile
Maintainer: me
Description: minor version bumps of two packages
=> python-ble2mqtt: update to 0.2.2

lang/php8/Makefile, lang/php8/patches/1004-disable-phar-command.patch
=> php8: update to 8.3.2

net/atftp/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:atftp_project:atftp
Maintainer: @myszsoda
=> net/atftp: assign PKG_CPE_ID

utils/crun/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:crun_project:crun
=> utils/crun: assign PKG_CPE_ID

admin/atop/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:atop_project:atop
=> admin/atop: assign PKG_CPE_ID

utils/acl/Makefile
https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Aacl_project%3Aacl
=> utils/acl: assign PKG_CPE_ID

net/bwm-ng/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:bwm-ng_project:bwm-ng
=> net/bwm-ng: assign PKG_CPE_ID

lang/php8/Makefile, lang/php8/patches/1004-disable-phar-command.patch
=> [23.05] php8: update to 8.2.15

utils/pv/Makefile
=> utils/pv: assign PKG_LICENSE_FILES

utils/unrar/Makefile, utils/unrar/patches/100-makefile_fixes.patch
=> unrar: update to 6.2.12

net/curl/Makefile, net/curl/patches/200-no_docs_tests.patch
* https://curl.se/changes.html#8_6_0
Compile-tested: ath79/generic (TP-Link Archer C7 v2), mediatek/filogic (GL.iNet GL-MT6000)
Run-tested: not tested yet
=> curl: update to 8.6.0

utils/grep/Makefile
=> grep: update to 3.11

multimedia/imagemagick/Makefile
Description:
- Use official source URL
- Add libstdcpp dependency
- Don't set configure options which are matching default values
=> imagemagick: update to 7.1.1-27

net/nextdns/Makefile
=> nextdns: Update to version 1.42.0

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.42.0

net/nextdns/Makefile
=> [22.03] nextdns: Update to version 1.42.0

devel/make/Makefile
=> make: update to 4.4.1

utils/procps-ng/Makefile, utils/procps-ng/patches/100-no-tests-docs.patch
Description:
- Update the patch
=> procps-ng: update to 4.0.4

net/iputils/Makefile, net/iputils/patches/001_version_fix.patch
Run tested: Turris Omnia running OpenWrt master
=> iputils: bump to 20240117

multimedia/graphicsmagick/Makefile
=> graphicsmagick: update to 1.3.42

libs/libmaxminddb/Makefile
=> libmaxminddb: update to 1.9.1

libs/freetype/Makefile
Description:
- change package URL to HTTPS
=> freetype: update to 2.13.2

libs/libsamplerate/Makefile
Description:
- Update package/source URLs to official ones
- Change license according to upstream
=> libsamplerate: update to 0.2.2

utils/gnuplot/Makefile, utils/gnuplot/patches/020-fix-mips-and-powerpc.patch
Maintainer: @datafl4sh 
Description:
- Add patch for MIPS and PowerPC systems
=> gnuplot: update to 6.0.0

libs/opus/Makefile, libs/opus/patches/010-fix-arm-build.patch
Maintainer: @thess @antonlacon 
Description:
- Add patch to fix build on ARM
=> opus: update to 1.4

net/subversion/Makefile, net/subversion/patches/301-cross-compilation-macos.patch
Maintainer: me
Description:
- Adopt the package
- Remove default configure options
- Rebase the patch
=> subversion: update to 1.14.3

sound/mpg123/Makefile
Maintainer: @wigyori 
Description:
- Use package official URL
- Fix license name
=> mpg123: update to 1.32.4

devel/autoconf/Makefile
=> autoconf: update to 2.72

libs/alsa-ucm-conf/Makefile
=> alsa-ucm-conf: update to 1.2.11

sound/alsa-utils/Makefile
=> alsa-utils: update to 1.2.11

devel/automake/Makefile
=> automake: update to 1.16.5

utils/hwdata/Makefile
=> hwdata: update to 0.379

libs/openldap/Makefile
Description:
- Remove dead mirror URL
- Clean-up configure args
=> openldap: update to 2.6.7

net/git-lfs/Makefile
Description:
- Update package URLs to the official ones
=> git-lfs: update to 3.4.1

net/gitolite/Makefile, net/gitolite/patches/0100-avoid-ssh-keygen.patch
Description:
- Use git for sources since no proper tarball is available
- Switch package URL to HTTPS
- Refresh the patch
=> gitolite: update to 3.6.13

utils/pigz/Makefile
Maintainer: @xinxijishuwyq 
Description:
- Fix license name
=> pigz: update to 2.8

devel/diffutils/Makefile, devel/diffutils/patches/010-ppc.patch
Maintainer: @roger-
Description:
- Switch package URL to HTTPS
- Refresh the patch
=> diffutils: update to 3.10

utils/xxhash/Makefile
Maintainer: @julienmalik 
Description:
- Switch URL to the official one
=> xxhash: update to 0.8.2

net/openvpn/Makefile, net/openvpn/files/openvpn.options
Maintainer: @AuthorReflex
Compile tested: x86_64, latest master
Run tested: x86_64, latest master
Description:
You maybe want to disable the DCO support, so let's add this option.
=> openvpn: add OpenVPN option disable-dco

libs/cjson/Makefile
=> cjson: update to 1.7.17

libs/file/Makefile
Description:
- Remove default and non-existent configure options
=> file: update to 5.45

libs/libx264/Makefile, libs/libx264/patches/001-fix-x32-build-by-disabling-asm.patch, libs/libx264/patches/002-dont-default-to-cortex-a9-with-neon.patch
Maintainer: @ianchi
Description:
- Fix CPU type detection to enable asm on ARM
=> libx264: update to 2024-01-13 revision

libs/avahi/Makefile, libs/avahi/patches/300-CVE-2023-38469.patch, libs/avahi/patches/301-CVE-2023-38470.patch, libs/avahi/patches/302-CVE-2023-38471.patch, libs/avahi/patches/303-CVE-2023-38472.patch, libs/avahi/patches/304-CVE-2023-38473.patch
This commit is interesting. Version 0.9 is in rc1 right now.
=> avahi: backport CVE fixes from upstream

libs/giflib/Makefile, libs/giflib/patches/010-CVE-2022-28506.patch, libs/giflib/patches/020-CVE-2023-39742.patch
=> giflib: fix CVEs

net/tcpreplay/Makefile, net/tcpreplay/patches/010-CVE-2023-4256.patch
=> tcpreplay: backport CVE fix

utils/gawk/Makefile
=> gawk: update to 5.3.0

utils/bash/Makefile
Maintainer: @Naoir 
Description:
- Switch package URL to HTTPS
=> bash: update to 5.2.21

net/p910nd/files/p910nd.hotplug, net/p910nd/files/p910nd.init
Maintainer: Philipp Kerling [pkerling@casix.org](mailto:pkerling@casix.org) @ptpt52 
Run tested: 
- ath79, Archer c7v2, 23.05.2, extensive testing
- x86_64, VM, 22.03.6, extensive testing
Description:
Improvements to init and small hotplug refactor
Refer to individual commit messages. Series can be squashed on merge.
Review welcome: @pprindeville @jow- @hnyman
=> p910nd: init improvements and hotplug refactor + improvements

libs/libao/Makefile, libs/libao/patches/010-CVE-2017-11548.patch
=> libao: backport fix for CVE-2017-11548

utils/moreutils/Makefile, utils/moreutils/patches/001_disable-manuals.patch
=> moreutils: update to 0.68

libs/libmpdclient/Makefile
=> libmpdclient: update to 2.22

libs/log4cplus/Makefile
Maintainer: @rosysong @hbl0307106015
=> log4cplus: update to 2.1.1

libs/libupnp/Makefile
=> libupnp: update to 1.14.18

libs/libxerces-c/Makefile
=> libxerces-c: update to 3.2.5

libs/libnpupnp/Makefile
=> libnpupnp: update to 6.1.0

libs/libcap-ng/Makefile
=> libcap-ng: update to 0.84

net/netbird/Makefile
changes: https://github.com/netbirdio/netbird/compare/v0.25.2...v0.25.8
Maintainer: me
=> netbird: update to 0.25.8

utils/qemu/Makefile, utils/qemu/patches/0001-configure-allow-disable-fortify_source.patch, utils/qemu/patches/0010-no-tests.patch
Compile tested: x86_64, OpenWrt master (https://github.com/openwrt/openwrt/commit/713dc12960dd6146706a364905904b58d4d586d4)
Description:
- Version updated to 8.2.0
=> qemu: update to 8.2.0

lang/php8/Makefile, lang/php8/patches/1004-disable-phar-command.patch
=> php8: update to 8.3.3

multimedia/fswebcam/Makefile
Maintainer: @nicolas-thill 
Description:
- Remove dead mirror
=> fswebcam: update to 20200725

lang/php8/Makefile, lang/php8/patches/1004-disable-phar-command.patch
=> [23.05] php8: update to 8.2.16

utils/dump1090/Makefile
Description:
- Fix version to be properly configured
=> dump1090: update to 9.0

utils/logrotate/Makefile
=> logrotate: update to 3.21.0

net/sing-box/Makefile
Maintainer: me
Description:
This release contains some bug fixes.
Changelogs: https://github.com/SagerNet/sing-box/compare/v1.8.4...v1.8.7
=> sing-box: update to 1.8.7

net/apfree-wifidog/Makefile, net/apfree-wifidog/files/wifidogx.init
Description:
https://github.com/liudf0716/apfree-wifidog/releases/tag/7.02.1977
=> apfree-wifidog: update to 7.02.1977

net/apfree-wifidog/Makefile, net/apfree-wifidog/files/wifidogx.init
Description:
https://github.com/liudf0716/apfree-wifidog/releases/tag/7.02.1977
=> [23.05] apfree-wifidog: update to 7.02.1977

net/apfree-wifidog/Makefile, net/apfree-wifidog/files/wifidogx.init
Description:
https://github.com/liudf0716/apfree-wifidog/releases/tag/7.02.1977
=> [22.03] apfree-wifidog: update to 7.02.1977

net/chrony/Makefile
Maintainer: @mlichvar 
Compile tested: Not tested 
Run tested: Not tested 
Description:
Close this forum topic
[Suggestion: State the difference between chrony and chrony-nts in package description](https://forum.openwrt.org/t/suggestion-state-the-difference-between-chrony-and-chrony-nts-in-package-description/187392)
(First time doing pull request. Do I need to test this? I can spin up a VM if needed)
=> chrony: update package description

libs/libfstrm/Makefile
=> libfstrm: add second maintainer

net/pdns-recursor/Makefile
Maintainer: me+ @rgacogne 
Run tested: x86_64 Docker openwrt/rootfs
Description:
=> pdns-recursor: update to 5.0.3, plus add maintainer

net/uacme/files/run.sh
Run tested: with Step-CA
Description:
Adds support for using a custom CA with `uacme` (e.g. a private Step-CA deployed on the local network), as well as the `TLS-ALPN-01` challenge type. The patch was originally described in https://forum.openwrt.org/t/custom-ca-for-ssl-certificates/160156/3.
These modifications assume the following extra keys in the `acme` section:
```
option acme_url <CA_DIRECTORY_URL>
option acme_staging_url <CA_DIRECTORY_URL>
```
as well as an additional key in the specific `certificate` section:
```
option tls 1
``` 
to enable `TLS-ALPN-01`
This is not really ideal, I think the challenge type should be an explicit key combining all the different modes, but I didn't want to change the OpenWrt default too much.
In addition to those changes, I've …
=> uacme: Add support custom CAs and TLS-ALPN-01 challenge

net/yggdrasil/Makefile
Compile tested: ARMv7, ZyXEL NBG6817, master branch
Run tested: ARMv7, ZyXEL NBG6817, 23.05.2
=> yggdrasil: bump to 0.5.5

utils/whois/Makefile
=> whois: update to 5.5.21

net/unbound/files/unbound_srv.conf
Closes openwrt/luci#6993
spell fix in included file
=> unbound: spell fix

utils/xz/Makefile, utils/xz/patches/001-relative-pkg-config-paths.patch
=> xz: update to 5.6.1

net/pdns/Makefile, net/pdns/files/pdns.conf-dist, net/pdns/patches/100-pdns-disable-pdns.conf-dist.patch
Maintainer: me
Run tested: openwrt in docker x86_64
Description:
=> pdns: update to 4.9.0 and add maintainer

net/dnsdist/Makefile
Maintainer: me
Run tested: docker x86_64 openwrt/rootfs
Description:
=> dnsdist: update to 1.9.1 and add maintainer

libs/expat/Makefile
=> expat: update to 2.6.2

lang/erlang/Makefile
=> erlang: update to 26.2.3

net/git-lfs/Makefile
=> git-lfs: update to 3.5.1

utils/unrar/Makefile, utils/unrar/patches/100-makefile_fixes.patch
=> unrar: update to 7.0.7

utils/hwdata/Makefile
=> hwdata: update to 0.380

net/squid/Makefile
=> squid: update to 6.8

libs/libstrophe/Makefile
=> libstrophe: update to 0.13.1

net/netbird/Makefile
changes: https://github.com/netbirdio/netbird/compare/v0.25.8...v0.26.3
=> netbird: update to 0.26.3

net/nebula/Makefile
=> nebula: prepare migration to APK

utils/cligen/Makefile
Compile tested: x86_64, generic, HEAD (8de4cc77a6d)
Run tested:same, installed on test VM
Description:
Update to 7.0.0
=> cligen: Update to 7.0.0

lang/perl-text-csv_xs/Makefile
Maintainer: me
Compile tested: x86_64, generic, HEAD (8de4cc77a6)
Description:
Upgrade to 1.53
=> perl-text-csv_xs: Update to 1.53

net/netbird/Makefile
changes: https://github.com/netbirdio/netbird/compare/v0.26.3...v0.26.6
=> netbird: update to 0.26.6

utils/clixon/Makefile
Compile tested: x86_64, generic, HEAD (8de4cc77a6)
Description:
=> clixon: Update to 7.0.1

libs/libpng/Makefile
=> libpng: update to 1.6.43

utils/hwdata/Makefile
=> hwdata: update to 0.381

multimedia/graphicsmagick/Makefile
Maintainer: me
Description:
- Set project URL to HTTP since HTTPS one is broken
=> graphicsmagick: update to 1.3.43

lang/python/numpy/Makefile, lang/python/numpy/patches/003-without-vendored-meson.patch
=> numpy: update to 1.26.4

net/dnsdist/Makefile
Run tested: amd64 docker openwrt/rootfs
Description:
=> dnsdist: update to 1.9.3

utils/pciutils/Makefile, utils/pciutils/patches/101-no-strip.patch
=> pciutils: update to 3.12.0

multimedia/imagemagick/Makefile
=> imagemagick: update to 7.1.1.30

utils/qemu/Makefile
Compile tested: x86-64 on latest master
Description:
- Use HTTPS for project URLs
=> qemu: update to 8.2.2

libs/libdrm/Makefile
=> libdrm: update to 2.4.120

libs/libevdev/Makefile
=> libevdev: update to 1.13.1

utils/mc/Makefile
=> mc: update to 4.8.31

utils/moreutils/Makefile, utils/moreutils/patches/001_disable-manuals.patch
=> moreutils: update to 0.69

net/socat/Makefile
=> socat: update to 1.8.0.0

net/pdns/Makefile, net/pdns/patches/200-dnsproxy-endian.patch
Maintainer: me
Compile tested: not yet
Description:
=> pdns: unbreak bigendian builds

libs/mtdev/Makefile
=> mtdev: update to 1.1.7

net/squid/Makefile
Run tested: arm_cortex-a9_neon, master branch
What's new: https://github.com/squid-cache/squid/blob/v6/ChangeLog
=> squid: update to 6.9

lang/python/django-restframework/Makefile, lang/python/django/Makefile
Maintainer: me (for all), @peter-stadler for Django
Compile tested: x86 https://github.com/openwrt/openwrt/commit/5b1d6d4607e4a062319225dd8930541cd1974ebe
Run tested: x86 https://github.com/openwrt/openwrt/commit/5b1d6d4607e4a062319225dd8930541cd1974ebe
=> django,django-restframework: bump versions

net/geoip-shell/DETAILS.md, net/geoip-shell/Makefile, net/geoip-shell/NOTES.md, net/geoip-shell/OpenWrt-README.md, net/geoip-shell/README.md, net/geoip-shell/SETUP.md
Maintainer: Anton Khazan / antonk / @friendly-bits
Compile tested: x86-64 v23.05.3
Run tested: x86-64 VM with OpenWrt v23.05.2, WNDR3700 v2 with OpenWrt SFE r15568-b3eccbca7c (approximately 2021 release)
Description:
Flexible geoip blocker with user-friendly command-line interface
This is my first pull request, sorry in advance if something is wrong with it.
Please note that I'm stripping comments from the code in this package to reduce its size. You can read the code with comments in the project's repository.
=> geoip-shell: add package

utils/yara/Makefile
Move away from codeload for smaller and better tarballs.
=> yara: update to 4.5.0

utils/xxhash/Makefile
=> xxhash: build with cmake 

lang/python/python-lxml/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/5b1d6d4607e4a062319225dd8930541cd1974ebe
Run tested: x86 https://github.com/openwrt/openwrt/commit/5b1d6d4607e4a062319225dd8930541cd1974ebe
=> python-lxml: bump to version 5.2.1

lang/luasocket/Makefile
=> luasocket: switch to local tarballs

libs/nghttp3/Makefile
Maintainer: Tianling Shen <cnsztl@immortalwrt.org>
=> nghttp3: Use APK style release number

net/nebula/Makefile
Maintainer: Tianling Shen <cnsztl@immortalwrt.org>
=> nebula: Use APK style release number

net/nebula/Makefile
Maintainer: Stan Grishin <stangri@melmac.ca>
Signed-off-by: Sean Khan <datapronix@protonmail.com>
(cherry picked from commit 3cbb7474c3fad4b01f8ee065b1c045c4b7fb523f)
=> [23.05] nebula: Use APK style release number

net/nextdns/Makefile
=> nextdns: Update to version 1.43.0

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.43.0

net/nextdns/Makefile
=> [22.03] nextdns: Update to version 1.43.0

net/nextdns/Makefile
=> nextdns: Update to version 1.43.1

net/nextdns/Makefile
=> nextdns: Update to version 1.43.3

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.43.3

net/nextdns/Makefile
=> [22.03] nextdns: Update to version 1.43.3

net/uspot/Makefile
Maintainer: me
Compile tested: ath79/generic
Run tested: ath79/generic
Description: uspot: update to Git HEAD (2024-05-03)
=> uspot: update to Git HEAD (2024-05-03)

net/uspot/Makefile
Maintainer: me
Compile tested: ath79/generic
Run tested: ath79/generic
Description: [23.05] uspot: update to Git HEAD (2024-05-03)
cherry picked from commit 5181ce4a483711791329a13e07d29f9321d85178
=> [23.05] uspot: update to Git HEAD (2024-05-03)

net/zerotier/Makefile, net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-paths.patch, net/zerotier/patches/0002-remove-PIE-options.patch, net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch, net/zerotier/patches/0004-add-missing-libatomic.patch, net/zerotier/patches/0005-remove-noexecstack.patch
Maintainer: me
Compile tested: ramips/mt7620, OpenWrt master
Run tested: ramips/mt7620, OpenWrt master, ZerotTier starts
=> zerotier: update to 1.14.0

utils/bottlerocket/Makefile, utils/bottlerocket/patches/010-gcc14.patch
implicit int errors now.
Maintainer: @computersforpeace
=> bottlerocket: fix compilation with GCC 14

net/aggregate/Makefile, net/aggregate/patches/010-gcc14.patch
Implicit int is now an error.
Maintainer: @nikil
=> aggregate: fix compilation with GCC 14

lang/node/Makefile, lang/node/patches/003-path.patch, lang/node/patches/202-node_gyp.patch, lang/node/patches/999-localhost-no-addrconfig.patch, lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch
Run tested: (qemu 9.0.0) aarch64
Description:
Update to v20.13.1
https://github.com/nodejs/node/releases/tag/v20.13.0
https://github.com/nodejs/node/releases/tag/v20.13.1
=> node: bump to v20.13.1

lang/vala/Makefile, lang/vala/patches/010-gcc14.patch
=> vala: fix compilation with GCC14

utils/rrdtool1/Makefile, utils/rrdtool1/patches/200-gcc14.patch
gnu standard is needed. Easier to remove the CFLAG.
=> rrdtool1: fix compilation with GCC14

net/apinger/Makefile, net/apinger/patches/070-gcc14.patch
Header is missing.
Maintainer: @samm-git
=> apinger: fix compilation with GCC 14

utils/screen/Makefile, utils/screen/patches/010-ptyh.patch
=> screen: fix compilation with GCC 14

net/eoip/Makefile, net/eoip/patches/010-gcc14.patch, net/eoip/patches/100-add_LF_to_pidfile.patch
Wrong pointer and missing header.
Maintainer: @bogdik
=> eoip: fix compilation with gcc14

net/dcwapd/Makefile, net/dcwapd/patches/010-gcc14.patch
Old bug in rapidjson.
Maintainer: @csonsino
=> dcwapd: fix compilation with GCC 14

utils/attr/Makefile, utils/attr/patches/200-basename.patch
=> attr: fix compilation with GCC 14

net/netbird/Makefile
changes: https://github.com/netbirdio/netbird/compare/v0.27.3...v0.27.7
=> netbird: update to 0.27.7

net/libndp/Makefile, net/libndp/patches/010-gcc14.patch
Added GCC 14 patch as well.
Maintainer: @dermoth
=> libndp: update to 1.8

libs/libroxml/Makefile, libs/libroxml/patches/020-gcc14.patch
Need casts for integer conversion
=> libroxml: fix compilation with GCC14

net/nfdump/Makefile, net/nfdump/patches/010-gcc14.patch
Add patch fixing compilation with GCC14.
=> nfdump: update to 1.7.4

net/udptunnel/Makefile, net/udptunnel/patches/010-gcc14.patch
Missing int in main.
Maintainer: @jandelgado maybe
=> udptunnel: fix compilation with GCC14

utils/setserial/Makefile, utils/setserial/patches/030-gcc14.patch
=> setserial: fix compilation with GCC14

utils/nvme-cli/Makefile, utils/nvme-cli/patches/010-gcc14.patch
=> nvme-cli: fix compilation with GCC14

utils/quota/Makefile, utils/quota/patches/010-gcc14.patch
=> quota: fix compilation with GCC14

libs/liburing/Makefile
Maintainer: Christian Lachner <gladiac@gmail.com> (**/me**)
Description: Update to v2.6
- Updated download URL and hash
=> liburing: Update to v2.6

net/pdns-recursor/Makefile
Maintainer: me
Compile tested: yes
Description:
=> pdns-recursor: update to 5.0.5

net/nebula/Makefile
=> nebula: drop maintainership

net/nextdns/Makefile
=> nextdns: Update to version 1.43.5

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.43.5

net/nextdns/Makefile
=> [22.03] nextdns: Update to version 1.43.5

utils/klish/Makefile, utils/klish/patches/010-shell_execute_fix.patch
Proper types are now needed.
Maintainer: @t-umeno
=> klish: fix compilation with GCC14

libs/libshout/Makefile, libs/libshout/patches/010-gcc14.patch
=> libshout: fix compilation with GCC14

net/acme-common/Makefile
=> acme-common: v1.2.0

libs/libnpupnp/Makefile, libs/libupnpp/Makefile, sound/upmpdcli/Makefile
=> upmpdcli and friends: update

libs/opus/Makefile
Maintainer: @thess @antonlacon
=> opus: update to 1.5.2

net/xfrpc/Makefile, net/xfrpc/files/xfrpc.conf, net/xfrpc/files/xfrpc.init
Description:
This version is compatible with FRPS 0.58.0 
=> xfrpc: update to 3.05.661

multimedia/gst1-libav/Makefile, multimedia/gst1-plugins-bad/Makefile, multimedia/gst1-plugins-base/Makefile, multimedia/gst1-plugins-good/Makefile, multimedia/gst1-plugins-good/patches/010-gcc14.patch, multimedia/gst1-plugins-ugly/Makefile, multimedia/gstreamer1/Makefile
=> gstreamer: update to 1.22.12

net/net-snmp/Makefile, net/net-snmp/patches/161-project_types.patch, net/net-snmp/patches/750-ieee802dot11.patch, net/net-snmp/patches/751-gcc-14-fix.patch, net/net-snmp/patches/900-musl-compat.patch
=> net-snmp: fix compilation with GCC 14

net/xfrpc/Makefile, net/xfrpc/files/xfrpc.conf, net/xfrpc/files/xfrpc.init
Description:
This version is compatible with FRPS 0.58.0 
=> 【23.05】xfrpc: update to 3.05.661

libs/libgpg-error/Makefile
=> libgpg-error: update to 1.49

libs/vips/Makefile
=> vips: update to 8.15.2

lang/python/python-selinux/Makefile
=> python-selinux: update to 3.6

utils/pciutils/Makefile, utils/pciutils/patches/110-gcc14.patch
=> pciutils: fix compilation with GCC14

libs/openblas/Makefile
Potentially fixes compilation.
=> openblad: avoid leaking host paths

libs/libjpeg-turbo/Makefile
=> libjpeg-turbo: update to 3.0.3

libs/libssh/Makefile
=> libssh: fix bad pkgconfig paths

utils/hwdata/Makefile
=> hwdata: update to 0.383

multimedia/imagemagick/Makefile
=> imagemagick: update to 7.1.1.33

lang/erlang/Makefile
=> erlang: update to 27.0

net/lynx/Makefile
=> lynx: update to 2.9.2

libs/libarchive/Makefile
=> libarchive: update to 3.7.4

utils/prometheus-node-exporter-lua/Makefile, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/hostapd_stations.lua
Maintainer: me
- fix incorrect interface name mapping in hostapd_stations exporter
Commit from #23683 slightly modified
=> prometheus-node-exporter-lua-hostapd_stations: fix not reporting metrics

net/fping/Makefile
Run tested: WRT3200ACM, arm_cortex-a9_neon, GCC 14
=> fping: update to 5.2

net/xray-core/Makefile
Description:
xray-core: Update to 1.8.13
=> [23.05] xray-core: update to 1.8.13

multimedia/v4l2camera/Makefile
Need to link against libasound.
Maintainer: @mpromonet
=> v4l2camera: fix compilation when ALSA is found

libs/libv4l/Makefile, libs/libv4l/patches/100-meson-utils.patch
=> libv4l: fix compilation without utils

net/ostiary/Makefile, net/ostiary/patches/010-gcc14.patch
Wrong pointer type.
Maintainer: @CGretski
=> ostiary: fix compilation with GCC14

libs/gdbm/Makefile
Just make the library instead of everthing.
Maintainer: @Naoir
=> gdbm: update to 1.23

utils/sane-backends/Makefile, utils/sane-backends/patches/010-basename.patch
=> sane-backends: fix compilation with GCC14

net/natmap/Makefile
Maintainer: @ysc3839,@heiher 
Description:
natmap: update to 20240603
=> natmap: update to 20240603

net/pdns-recursor/Makefile, net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch
Maintainer: me
Run tested: x86_64 openwrt docker/rootfs
Description:
=> pdns-recursor: update to 5.0.6

utils/zsh/Makefile, utils/zsh/patches/006-52383-Avoid-incompatible-pointer-types-in-terminfo-g.patch, utils/zsh/patches/010-gcc14.patch
Upstream backport and local patch.
Maintainer: @msva 
Fixes: https://github.com/openwrt/packages/issues/24344
=> zsh: fix compilation with GCC14

lang/perl/Makefile, lang/perl/patches/020-gcc14.patch
Need the header for fegetround.
Maintainer: @Naoir @pprindeville 
ping @predators46 
Fixes: https://github.com/openwrt/packages/issues/24343
=> perl: fix compilation with GCC14

libs/libnvme/Makefile, utils/nvme-cli/Makefile, utils/nvme-cli/patches/020-replace_uint16_t
Run tested: arm_cortex-a9_neon, GCC 14, LTO
=> libnvme and nvme-cli update

utils/logrotate/Makefile
Run tested: arm_cortex-a9_neon, GCC 14, LTO
=> logrotate: update to 3.22.0

utils/gnuplot/Makefile
Maintainer: @datafl4sh 
Run tested: arm_cortex-a9_neon, GCC 14, LTO
=> gnuplot: update to 6.0.1

net/snowflake/Makefile
ChangeLog:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/blob/main/ChangeLog
=> snowflake: update to 2.9.2

net/ifstat/Makefile, net/ifstat/patches/010-gcc14.patch
Need explicit int.
Maintainer: @nikil
=> ifstat: fix compilation with GCC14

lang/lzmq/Makefile, lang/lzmq/patches/010-gcc14.patch
=> lzmq: fix compilation with GCC14

utils/collectd/Makefile, utils/collectd/patches/940-nut-int.patch
=> collectd: fix compilation with GCC14

net/apfree-wifidog/Makefile, net/apfree-wifidog/files/wifidogx.conf, net/apfree-wifidog/files/wifidogx.init
Description:
https://github.com/liudf0716/apfree-wifidog/releases/tag/7.06.2008
=> apfree-wifidog: update to 7.06.2008

utils/hplip/Makefile, utils/hplip/patches/010-libusb_fix.patch, utils/hplip/patches/030-replace_unsafe_memcpy_with_memmove.patch, utils/hplip/patches/070-respect-cflags.patch
See: https://developers.hp.com/hp-linux-imaging-and-printing/release_notes
Maintainer: me
Compile tested: ath78
Run tested: none (no HW to test)
Description:
=> hplip: update to 3.23.12

utils/prometheus-node-exporter-lua/Makefile, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/hostapd_stations.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/hwmon.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/mwan3.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/nat_traffic.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/netclass.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/textfile.lua, utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/thermal.lua
Maintainer: me
Description: 
backport all recent fixes from master
=> [23.05] prometheus-node-exporter-lua: sync with master

net/yggdrasil-jumper/Makefile
Maintainer: me
Compile tested: x86_64 generic SNAPSHOT
Run tested: x86_64 generic SNAPSHOT
[Changes](https://github.com/one-d-wide/yggdrasil-jumper/releases/tag/v0.3.1)
=> yggdrasil-jumper: bump to 0.3.1

net/dnsdist/Makefile
=> dnsdist: update to 1.9.5

multimedia/yt-dlp/Makefile
Maintainer: @paper42 
Compile tested: aarch64 531b3f667c40405581a398a9648a0e6c27909a87
Run tested: none 
Description:
none
=> yt-dlp: Update to 2024.5.27

net/freeradius3/Makefile, net/freeradius3/patches/002-disable-session-cache-CVE-2017-9148.patch, net/freeradius3/patches/003-freeradius-fix-error-for-expansion-of-macro.patch, net/freeradius3/patches/004-get-hostname-from-proc-in-radtest.patch, net/freeradius3/patches/010-openssl-deprecated.patch, net/freeradius3/patches/020-fix-freeradius3-krb5.patch
Maintainer:
Run tested:
Description:
https://github.com/FreeRADIUS/freeradius-server/releases/tag/release_3_2_4
don't make the DH file. It's not needed for OpenSSL >=1.1.0
https://github.com/FreeRADIUS/freeradius-server/commit/afbf93b9679f4011e397610e26dd4f05992ea981
update freeradius version 3.2.4
added freeradius3 package module
refresh patch
=> freeradius3: update version 3.2.4

utils/docker-compose/Makefile
=> Docker compose

net/natmap/Makefile
Maintainer: @ysc3839,@heiher
Description:
natmap: update to 20240603
=> [23.05]natmap: update to 20240603

net/xray-core/Makefile
Run tested: armv8, snapshot
Description:
xray-core: Update to 1.8.16
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.13...v1.8.16
=> [23.05]xray-core: update to 1.8.16

utils/moreutils/Makefile
Maintainer:  @nikil
Description: binary ts need perlbase-time package
=> moreutils: fix depencies for ts

net/natmap/Makefile
Maintainer: @ysc3839,@heiher
Description:
natmap: update to 20240603
=> [22.03]natmap: update to 20240603

utils/opensc/Makefile, utils/opensc/patches/001-fix-build.patch, utils/pcsc-lite/Makefile, utils/pcsc-tools/Makefile
Maintainer: me
Run tested: -
Description:
Update smartcard related libraries and tools.
=> update pcsc-lite, pcsc-tools and opensc

net/databag/Makefile, net/databag/files/databag.config, net/databag/files/databag.init
Maintainer: me / @balzack
Compile tested: v23.05.0
Run tested: tested on raspberry pi zero
Description:
A federated messaging service designed for embedded systems.
project repo: https://github.com/balzack/databag
resubmitting the PR as I bungled the last squash merge
=> databag: add package

utils/owut/Makefile
- fix up versioning in Makefile
- change package description doc link to wiki entry instead of github
- pick up recent fixes
Maintainer: me
=> owut: update to 2024.06.24

utils/sumo/Makefile, utils/sumo/patches/010-gtest.patch, utils/sumo/patches/020-gcc14.patch
=> sumo: update to 1.16.0

libs/xmlrpc-c/Makefile
Add nls.mk as libxml2 needs it.
=> xmlrpc-c: update to 1.59.03

libs/libtalloc/Makefile, libs/libtalloc/patches/100-Remove_libbsd_dependency_check.patch
=> libtalloc: update to 2.42

libs/mxml/Makefile, net/uwsgi/Makefile, utils/jq/Makefile
Maintainer: @Ansuel @peter-stadler @ejurgensen @ratkaj 
Compile tested: not necessary
Run tested: not necessary
=> treewide: Add PKG_CPE_IDs

net/pdns-recursor/Makefile
Run tested: x86_64 openwrt/rootfs docker
Description:
=> pdns-recursor: update to 5.0.7

net/wifischedule/Makefile, net/wifischedule/net/usr/bin/wifi_schedule.sh
| | |
--- | ---
Maintainer | @neheb
Compile tested | _it's all a script!_
Run tested | Archer C7-v2
This is almost complete rewrite of the script. It fixes a lot of bugs, and makes it more robust, portable and maintainable. There's still room for improvements though.
What's the purpose of the kernel module unload feature? Can it be obliterated?
I also plan to change logging from a special file to standard logger, and remove the logging and crontab tabs from luci-app as they will no longer serve any purpose. PRs next time.
=> wifischedule: make it not utter garbitsch

lang/erlang/Makefile
Description:
Disable host build of wx - it slows down the build and is not used anyway
=> erlang: update to 27.0.1

multimedia/yt-dlp/Makefile
Compile tested: ARMv7 Processor rev 4 (v7l)
Run tested: ARMv7 Processor rev 4 (v7l)
=> yt-dlp: bump to version 2024.7.9

net/krb5/Makefile
=> krb5: update to 1.21.3

utils/clixon/Makefile
Compile tested: x86_64, generic, HEAD (04818d5857)
Run tested: untested
Description:
=> clixon: Update to 7.1.0

utils/cligen/Makefile
Compile tested: x86_64, generic, HEAD (04818d5857)
Run tested: untested
Description:
=> cligen: Update to 7.1.0

lang/perl-text-csv_xs/Makefile, lang/perl-text-csv_xs/patches/900-fix-format-warnings.patch
Maintainer: me
Compile tested: x86_64, generic, HEAD (04818d5857)
Description:
=> perl-text-csv_xs: Update to 1.55

net/dante/Makefile, net/dante/patches/010-gcc14.patch
Also added some configure fixes.
=> dante: fix compilation with GCC14

utils/openzwave/Makefile, utils/openzwave/patches/010-gcc14.patch
Null pointer dereference. This looks like a bug fix actually...
Maintainer: @dwmw2
=> openzwave: fix compilation with GCC14

admin/fluent-bit/Makefile
* add package fluent-bit v3.1.0
=> fluent-bit: add package

multimedia/imagemagick/Makefile
=> imagemagick: update to 7.1.1.35

net/dnsdist/Makefile
Maintainer: me and @rgacogne 
Run tested: openwrt/rootfs docker x86_64
Description:
=> dnsdist: update to 1.9.6

utils/owut/Makefile
Maintainer: me / @efahl
Compile tested: x86/64 snapshot
Description:
Minor bug fixes and several enhancements.
=> owut: update to 2024.07.21

utils/tesseract/Makefile
=> tesseract: update to 5.4.1

net/clamav/Makefile
=> clamav: update to 1.3.1

net/openfortivpn/Makefile
=> openfortivpn: update to 1.22.1

libs/libmaxminddb/Makefile
=> libmaxminddb: update to 1.10.0

lang/perl/Makefile
Maintainer: @Naoir @pprindeville 
Compile tested: x86_64, qemu, master
Compile tested: aarch64, mt7986 rfb, fork based on 23.05.2.  <= This has removed the failures mentioned in the log messages, but did not fix all races on 23.02.
Run tested: x86_64, qemu, master, Ran ` perl -E 'say("hello")'`
I could not see any races on master after applying this patch. On 23.05.2 I still see other races, but this patch seems to fix all occurences of the race described in the commit message and in the linked Debian bug report. Admittedly the testing on master was less thorough compared to the testing on 23.05.2, but I can confirm that this patch successfuly fixes one race and does not create any known new issues, so I think it is good to merge
~~Currently in draft status, because I am still waiting to …
=> perl: Run make depend to fix build race condition

multimedia/imagemagick/Makefile
=> imagemagick: update to 7.1.1.36

net/boinc/Makefile, net/boinc/patches/001-avoidExtraDependencies
Maintainer: @N30dG @smoe
Description:
- Refresh a patch
=> boinc: update to 8.0.4

admin/bottom/Makefile
=> bottom: update to 0.9.7

libs/minizip/Makefile
=> minizip: update to 4.0.7

multimedia/rtpmidid/Makefile, multimedia/rtpmidid/patches/010-gcc14.patch, multimedia/rtpmidid/patches/020-fmt10.patch
=> rtpmidi: fix compilation with GCC14 and fmt10.2

net/pbr/Makefile, net/pbr/README.md, net/pbr/files/etc/config/pbr-iptables, net/pbr/files/etc/init.d/pbr-iptables, net/pbr/files/etc/uci-defaults/91-pbr-nft, net/pbr/files/usr/share/nftables.d/chain-post/dstnat_lan/30-pbr.nft, net/pbr/files/usr/share/nftables.d/table-post/30-pbr.nft, net/pbr/files/usr/share/pbr/pbr.user.aws-iptables, net/pbr/files/usr/share/pbr/pbr.user.netflix-iptables, net/pbr/files/usr/share/pbr/pbr.user.wg_server_and_client
Maintainer: me
Description:
This version is the final version supporting iptables and:
* it separates the old iptables/nft-capable init script from the new nft-only init script
* the new nft-script is a significant rewrite of the old recursive calls/policy parsing and tries to create inlline nft sets which offers performance improvements
=> pbr: update to 1.1.6-20

libs/liblz4/Makefile
Switch to normal tarballs.
Maintainer: @dajhorn
=> liblz4: update to 1.10.0

utils/bc/Makefile, utils/bc/patches/001-disable-doc.patch, utils/bc/patches/002-notice-read-and-write-errors-on-input-and-output.patch, utils/bc/patches/003-dc-fix-exit-code-of-q-command.patch, utils/bc/patches/004-no-gen-libmath.patch
Maintainer: @br101 
Description:
- Switch to GNU package URLs
- Switch license to GNU-3.0
- Manually rebase one patch
- Add 3 more patches from [Buildroot project](https://github.com/buildroot/buildroot/tree/master/package/bc)
=> bc: update to 1.07.1

libs/elektra/Makefile, libs/elektra/patches/010-gcc13.patch
Adjusted lua dependency.
Maintainer: @haraldg
=> elektra: update to 0.9.14

admin/sudo/Makefile, admin/sudo/test.sh
The goal here is compatibility with APK.
ping @aparcar
=> sudo: modify version to Alpine Linux one

net/freeradius3/Makefile
autoreconf messes things up.
Fixed a typo regarding unixodbc.
Maintainer: 
This build system is trash. No wonder this Makefile is huge.
=> freeradius3: fix when host readline is present

net/cloudflared/Makefile
Description:
**_cloudflared: update to 2024.8.3_**
TUN-8591 login command without extra text
remove code that will not be executed
remove code that will not be executed
**_For more information, visit https://github.com/cloudflare/cloudflared/compare/2024.8.2...2024.8.3_**
=> cloudflared: Update to 2024.8.3

net/dnsproxy/Makefile, net/dnsproxy/files/dnsproxy.config, net/dnsproxy/files/dnsproxy.init
Maintainer: me
Description:
Fixes: #24869
Cc: @p-w-p
=> dnsproxy: add hosts configurations

lang/python/django/Makefile, lang/python/numpy/Makefile, lang/python/numpy/patches/003-without-vendored-meson.patch, lang/python/numpy/patches/004-workaround-for-multiple-top-level-packages-discovered.patch
Maintainer: me for both, @peter-stadler for Django
Compile tested: x86 https://github.com/openwrt/openwrt/commit/cf765b1be685d316ac6ad914008ca4c166d13a6a
Run tested: x86 https://github.com/openwrt/openwrt/commit/cf765b1be685d316ac6ad914008ca4c166d13a6a
=> django,numpy: bump versions

utils/mc/Makefile
=> mc: update to 4.8.32

multimedia/imagemagick/Makefile
=> imagemagick: update to 7.1.1.37

net/dhtd/Makefile
Maintainer: me
Backport from master branch. Fixes bugs&crashes.
=> dhtd: updates from master

net/clamav/Makefile
=> clamav: update to 1.4.0

admin/rsyslog/Makefile
=> rsyslog: update to 8.2408.0

multimedia/imagemagick/Makefile
=> imagemagick: update to 7.1.1.38

libs/sqlite3/Makefile
Description:
- Change package URL to HTTPS
=> sqlite: update to 3460100

utils/hwdata/Makefile
=> hwdata: update to 0.387

net/curl/Makefile, net/curl/patches/200-no_docs_tests.patch
Maintainer: me
Description:
- Refresh a patch
=> curl: update to 8.10.0

net/memcached/Makefile
=> memcached: update to 1.6.31

utils/sexpect/Makefile
=> sexpect: update to 2.3.14

net/curl/Makefile
Maintainer: me
Compile tested:arm_cortex-a9_neon, GCC 14
Description:
Contains fix to the issue reported by @diizzyy here - https://github.com/openwrt/packages/pull/24960
=> curl: update to 8.10.1

utils/exfatprogs/Makefile
=> exfatprogs: update to 1.2.5

libs/nghttp2/Makefile
=> nghttp2: update to 1.63.0

net/clamav/Makefile
=> clamav: update to 1.4.1

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr
Maintainer: me
Description:
* implement system health check on start for required fw4 table/chains
* add error messages for failed health checks
* move resolver check & config from load_package_config to load_environment
* no longer filter only static rules for pbr_* tables
=> pbr: update to 1.1.7-15

admin/openwisp-monitoring/Makefile
=> openwisp-monitoring: update to 0.2.0

utils/containerd/Makefile, utils/docker/Makefile, utils/dockerd/Makefile, utils/runc/Makefile
Description:
**_containerd: Update to 1.7.22_**
https://github.com/containerd/containerd/releases/tag/v1.7.21
https://github.com/containerd/containerd/releases/tag/v1.7.22
**_For more information, visit https://github.com/containerd/containerd/compare/v1.7.20...v1.7.22_** 
**_runc: Update to 1.1.14_**
https://github.com/opencontainers/runc/releases/tag/v1.1.14
**_For more information, visit https://github.com/opencontainers/runc/compare/v1.1.13...v1.1.14_** 
**_docker: Update to 27.3.1/dockerd: Update to 27.3.1_**
https://github.com/moby/moby/releases/tag/v27.2.0
https://github.com/moby/moby/releases/tag/v27.2.1
https://github.com/moby/moby/releases/tag/v27.3.0
https://github.com/moby/moby/releases/tag/v27.3.1 …
=> docker: Update to 27.3.1

net/tailscale/Makefile
https://github.com/tailscale/tailscale/releases/v1.74.1
Maintainer: me
Compile tested: aarch64_cortex-a53 @ SNAPSHOT
Run tested: aarch64_cortex-a53 @ SNAPSHOT
=> tailscale: Update to 1.74.1

utils/qemu/Makefile, utils/qemu/patches/0001-configure-allow-disable-fortify_source.patch, utils/qemu/patches/0007-qga-invoke-separate-applets-for-guest-shutdown-modes.patch, utils/qemu/patches/0010-no-tests.patch
Compile tested: x86_64, OpenWrt master (https://github.com/openwrt/openwrt/commit/fb3d681783409a05587f1f5176e54abfcf2343a1)
Description:
- Version updated to 9.1.0
=> qemu: update to 9.1.0

net/dnsdist/Makefile
Run tested: amd64 docker openwrt/rootfs
=> dnsdist: update to 1.9.7

.vscode/settings.json
Signed-off-by: Andrey Butirsky <butirsky@gmail.com>
Maintainer: me
Description:
VS Code setting to auto signoff commits.
@hauke
=> meta: VS Code: Git: Always Sign Off

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr, net/pbr/files/usr/share/nftables.d/chain-post/dstnat/30-pbr.nft, net/pbr/files/usr/share/nftables.d/chain-post/dstnat_lan/30-pbr.nft, net/pbr/files/usr/share/nftables.d/table-post/30-pbr.nft, net/pbr/files/usr/share/pbr/pbr.user.aws
Maintainer: me
Description:
* switch to dstnat chain from dstnat_lan chain for dns & tor policies (thanks @egc112)
* re-introduce procd_lan_interface for better LAN detection
* improve is_domain function
* introduce health-check for requried fw4 chains
* bugfix: avoid double counters for dns policies
* bugfix: remove faulty counters for tor policies
* rename interface_process to process_interface for better code readability
* overhaul pbr.user.aws script for a much better performance and more compact (gzipped) storage of the ranges json locally (thanks @bigsmile74)
=> pbr: update to 1.1.7-21

multimedia/go2rtc/Makefile, multimedia/go2rtc/files/go2rtc.init
Maintainer: me / @vooon 
Compile tested: x86_64, OpenWrt master
Run tested: x86_64, OpenWrt master
Description:
Improve security a bit by dropping root privileges. Also instruct procd to respawn.
=> go2rtc: run service as regular user

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/lib/ddns/update_huaweicloud_com.sh, net/ddns-scripts/files/usr/share/ddns/default/huaweicloud.com.json
Maintainer:  @feckert
Run tested: mediatek/filogic
Description:
add ddns-scripts for huaweicloud
=> add ddns-scripts for huaweicloud

admin/openwisp-config/Makefile
=> [23.05] openwisp-config: update to 1.1.0

admin/openwisp-monitoring/Makefile
=> [23.05] openwisp-monitoring: update to 0.2.0

net/pdns/Makefile, net/pdns/patches/100-pdns-disable-pdns.conf-dist.patch
Description:
with gratitude to @robimarko for fixing the blocker in maxminddb
=> pdns: update to 4.9.2

net/wifischedule/net/etc/init.d/wifi_schedule
Fixes: https://github.com/openwrt/packages/issues/25064
=> wifischedule: fix init.d START

libs/libuwifi/Makefile
Fix version to be apk compatible.
Maintainer: @br101
=> libuwifi: update to latest master

lang/luasoap/Makefile
Adds compatibility with apk.
Maintainer: @ahappyforest
=> luasoap: update to latest release

utils/pservice/Makefile
=> pservice: modify date for apk compatibility

net/nginx-util/Makefile, net/nginx/Makefile, net/nginx/files/nginx.init, net/nginx/patches/nginx/105-optional-libexslt.patch, net/nginx/patches/nginx/106-libxslt-fix-detection.patch
Enough transition period has passed for nginx dummy package. Finally
drop it for good and add Provides for nginx default.
=> nginx: minor fixes

net/softethervpn/Makefile, net/softethervpn/patches/100-gcc14.patch
=> softethervpn: fix compilation with GCC14

net/nginx/Makefile
Module needs updating.
Maintainer: @Ansuel
=> nginx: fix compilation with GCC14

net/tunneldigger-broker/Makefile
Maintainer: @PolynomialDivision
=> tunneldigger-broker: fix APK version

net/gatling/Makefile, net/gatling/patches/040-gcc14.patch
Headers are missing.
Maintainer: @Akira25
=> gatling: fix compilation with GCC14

net/inadyn/Makefile, net/inadyn/patches/010-strdupa.patch
Backport patch fixing compilation with GCC14.
Maintainer:
=> inadyn: update to 2.12.0

net/snowflake/Makefile
ChangeLog:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/blob/v2.10.1/ChangeLog?ref_type=tags
=> snowflake: update to 2.10.1

net/nginx/Makefile
Modify EXTRA_DEPENDS in package section to meet APK packaging requirements.
Maintainer: @Ansuel
Compile tested: bcm2711 4f8ad90a9de0c63df2520ce0b7023b7a0fbfbf8d
Description:
Support APK
=> nginx: Support APK versioning

utils/avrdude/Makefile
=> avrdude: fix compilation with full NLS

net/modemmanager/Makefile, net/modemmanager/files/etc/init.d/modemmanager, net/modemmanager/files/lib/netifd/proto/modemmanager.sh
Maintainer: me
Run tested: x86_64 with an EC25, APU3, OpenWrt latest
Description:
See commits
=> modemmanager: small changes/fixes/improvements in proto handling

utils/lpac/Makefile, utils/lpac/patches/0001-driver-add-uqmi-backend.patch
Parameter is not void but void pointer.
Maintainer: @blocktrron
=> lpac: fix compilation with GCC14

lang/vala/Makefile
Need to override a pointless configure var.
=> vala: update to 0.56.17

lang/perl/perlmod.mk
Compile tested: https://github.com/openwrt/packages/issues/23706#issuecomment-2467765005
Description:
Make the package version compatible with apk.
=> perl: perlmod: make version apk compatible

admin/atop/Makefile
nls.mk is missing.
Maintainer: @utoni
=> atop: fix compilation with full NLS

net/pdns-recursor/Makefile
Compile tested: github actions (pre and post APK)
Run tested: docker openwrt/rootfs (pre and post APK)
Description:
~~filing this as a draft PR because I tested this before the APK switch~~
now also tested as APK, ready to go
=> pdns-recursor: update to 5.1.3

utils/owfs/Makefile
Adjust version to be compatible with apk's semanting versioning.
Compile tested: mediatek/mt7622 RT3200
=> owfs: Make version apk compatible

admin/openwisp-monitoring/Makefile
=> openwisp-monitoring: update to 0.2.1

ipv6/tayga/Makefile, ipv6/tayga/patches/010-gcc14.patch
Header is needed for musl.
Maintainer: @oskar456
=> tayga: fix compilation with GCC14

net/nbd/Makefile, net/nbd/patches/010-gcc14.patch
=> nbd: fix compilation with GCC14

admin/debootstrap/Makefile
Adjust version to match apk semantic rules.
Compile tested: DL-WRX36
=> debootstrap: Make version apk compatible

net/yggdrasil/Makefile
Maintainer: @wfleurant
Compile tested: MT7620, ASUS RT-AC51U
Run tested: ASUS RT-AC51U
Description:
bump version
=> yggdrasil: bump to 0.5.10

net/yggdrasil/Makefile
Maintainer: @wfleurant
Compile tested: MT7620, ASUS RT-AC51U
Run tested: ASUS RT-AC51U
Description:
bump version in 23.05
=> [23.05] yggdrasil: bump to 0.5.10

net/adblock-fast/Makefile, net/adblock-fast/files/etc/init.d/adblock-fast, net/adblock-fast/files/etc/uci-defaults/90-adblock-fast
Maintainer: me
Description:
* temporary hack until https://github.com/openwrt/openwrt/pull/16806 is merged
* catch up to snapshots version
=> [23.05] adblock-fast: bugfix: dnsmasq instances confdir hack

net/adblock-fast/Makefile, net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Run tested: x86_64, Dell EMC Edge620, OpenWrt snapshot
Description:
* temporary hack until https://github.com/openwrt/openwrt/pull/16806 is merged
* catch up to snapshots version
=> [24.10] adblock-fast: bugfix: dnsmasq instances confdir hack

net/zerotier/Makefile, net/zerotier/files/etc/config/zerotier, net/zerotier/files/etc/init.d/zerotier, net/zerotier/files/etc/uci-defaults/80-zt-migration, net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-path.patch, net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-paths.patch, net/zerotier/patches/0002-remove-PIE-options.patch, net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch, net/zerotier/patches/0004-add-missing-libatomic.patch, net/zerotier/patches/0005-remove-noexecstack.patch
Maintainer: me
Compile tested: TBD
Run tested: TBD
Description:
The configuration structure changes. But the upgrade script manages this.
=> [23.05] zerotier: backport updates for 1.14.1

net/microsocks/Makefile, net/microsocks/patches/001-use-a-bigger-thread-stack-by-default.patch, net/microsocks/patches/002-mute-warning-about-shadow-declaration-of-bind_addr.patch, net/microsocks/patches/003-improve-throughput-in-copyloop-using-bigger-buffer.patch
Maintainer: @matkor
Description:
Fix segmentation fault with newer musl and improve throughput.
=> microsocks: backport upstream fixes

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr
=> pbr: improve status_service output

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr
=> [24.10] pbr: improve status_service output

net/pdns/Makefile
Maintainer: me & @rgacogne 
Run tested: docker x86_64
Description:
=> pdns: update to 4.9.3

net/nextdns/Makefile
=> nextdns: Update to version 1.44.0

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.44.0

net/dnsdist/Makefile
Maintainer: me & @rgacogne 
Description:
=> dnsdist: update to 1.9.8

net/nextdns/Makefile
=> nextdns: Update to version 1.44.3

net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT ~r28146-52b6c92479~ r28146-52b6c92479 |
**Tests Performed:**
- Partially revert: https://github.com/openwrt/packages/commit/7b3d033ab651dd11e0db5fb099d106c9e09a2dc6
- Revert: Also fixes issue of not being able to build with musl >1.2.4,
The issue has been resolved as of March 2024. For more details, see:
https://github.com/mattn/go-sqlite3/issues/1164#issuecomment-1975022901
- Changelog:
- …
=> netbird: update to 0.35.1 and revert fix to build with musl >1.2.4

net/nextdns/Makefile
=> [24.10] nextdns: Update to version 1.44.3

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.44.3

libs/vips/Makefile
=> vips: update to 8.16.0

libs/hwloc/Makefile
=> hwloc: update to 2.11.2

libs/libgpg-error/Makefile, libs/libgpg-error/patches/001-cross-compile-fix.patch
=> libgpg-error: update to 1.51

libs/libgcrypt/Makefile
=> libgcrypt: 1.11.0

utils/fuse-overlayfs/Makefile
=> fuse-overlayfs: update to 1.14

libs/openldap/Makefile
=> openldap: update to 2.6.9

libs/libsoup3/Makefile
=> libsoup3: update to 3.6.1

net/pbr/Makefile
=> pbr: Makefile bugfixes

multimedia/gst1-libav/Makefile, multimedia/gst1-plugins-bad/Makefile, multimedia/gst1-plugins-base/Makefile, multimedia/gst1-plugins-good/Makefile, multimedia/gst1-plugins-ugly/Makefile, multimedia/gstreamer1/Makefile
=> Update GStreamer packages to 1.24.10

net/uanytun/Makefile, net/uanytun/patches/010-gcc14.patch
Wrong cast type.
Maintainer: ping @equinox0815
=> uanytun: fix compilation with GCC14

net/tmate/Makefile, net/tmate/patches/010-gcc14.patch
=> tmate: fix compilation with GCC14

libs/libtorrent-rasterbar/Makefile
=> libtorrent-rasterbar: Update to 2.0.10

net/vsftpd/Makefile, net/vsftpd/files/vsftpd.conf, net/vsftpd/files/vsftpd.init, net/vsftpd/files/vsftpd.uci
* update init script to use procd
* update init script to process UCI
Signed-off-by: Mohd Husaam Mehdi <husaam.mehdi@iopsys.eu>
=> vsftpd: update init script to use procd and publish service

lang/rust/Makefile
Compile tested: arm64, Xiaomi AX3600, OpenWrt Main
Run tested: arm64, Xiaomi AX3600, OpenWrt Main
Description: rust: update to 1.84.0
=> rust: update to 1.84.0

utils/tree/Makefile
Changelog: https://github.com/Old-Man-Programmer/tree/blob/master/CHANGES
=> tree: bump to 2.2.1

net/nextdns/Makefile
=> nextdns: Update to version 1.44.4

net/rsync/Makefile
Changelog: https://download.samba.org/pub/rsync/NEWS#3.4.1
=> rsync: update to 3.4.1

net/nextdns/Makefile
=> [24.10] nextdns: Update to version 1.44.4

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.44.4

net/antiblock/Makefile, net/antiblock/files/etc/config/antiblock, net/antiblock/files/etc/init.d/antiblock, net/antiblock/test.sh
Maintainer: me
Compile tested: ASUS RT-AX59U 23.05.5, ASUS RT-AX53U 23.05.5, OpenWrt x86
Run tested: ASUS RT-AX59U 23.05.5, ASUS RT-AX53U 23.05.5, OpenWrt x86
Description:
AntiBlock program proxies DNS requests. The IP addresses of the specified domains are added to the routing table for routing through the specified interface.
=> [24.10] antiblock: add new package

net/pdns-recursor/Makefile, net/pdns-recursor/patches/100-disable-recursor.yml-dist.patch
Maintainer: me & @rgacogne 
Run tested: openwrt x86_64 docker
Description:
=> pdns-recursor: update to 5.2.0

lang/php8-pecl-redis/Makefile
Maintainer: me
Run tested: mxs (Duckbill)
=> php8-pecl-redis: update to 6.1.0

lang/php8-pecl-http/Makefile
Maintainer: me
Run tested: mxs (Duckbill)
=> php8-pecl-http: update to 4.2.6

net/yggdrasil/Makefile
Maintainer: William Fleurant / @wfleurant
Compile tested: OpenWrt v24.10.0-rc5
Run tested: MediaTek MT7621
=> yggdrasil: update to 0.5.12

net/adblock-fast/Makefile, net/adblock-fast/files/etc/config/adblock-fast, net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Description:
* bugfix: more robust boot-up start
* bugfix: processing of StevenBlack lists
* new remote block-list: CERT.pl
=> adblock-fast: bugfixes: boot-up, StevenBlack list, new CERT.pl source

net/frr/Makefile, net/frr/files/daemons, net/frr/files/frrcommon.sh
add packing mgmtd, pim6d and update helper scripts
Maintainer: me
Tested x86_64
Backport will be needed for RIP functionality
=> frr: 10.2.1 fixes

net/frr/Makefile, net/frr/files/daemons, net/frr/files/frrcommon.sh
add mgmtd to fix RIP and static routing  and pim6d 
Maintainer: me
Compile tested x86
=> [23.05] frr: 10.2.1 fixes

net/frr/Makefile, net/frr/files/daemons, net/frr/files/frrcommon.sh
add mgmtd to fix RIP and static routing and pim6d
Maintainer: me
Compile tested x86
=> [24.10] frr: 10.2.1 fixes

lang/lua-cjson/Makefile, lang/lua-cjson/patches/001-add-support-lua5-3.patch
=> lua-cjson: add build VARIANT for Lua5.3

net/pdns/Makefile
=> pdns: update to 4.9.4

net/antiblock/Makefile, net/antiblock/files/etc/config/antiblock, net/antiblock/files/etc/init.d/antiblock
Maintainer: me
Compile tested: ASUS RT-AX59U 24.10.0
Run tested: ASUS RT-AX59U 24.10.0
Description:
Updated hashmap version.
In the code, almost all the url words have been replaced with domain.
Fixed a bug in the service of getting gateway from VPN name.
=> antiblock: Update to 2.0.1

net/antiblock/Makefile, net/antiblock/test.sh
Maintainer: me
Compile tested: ASUS RT-AX59U 24.10.0
Run tested: ASUS RT-AX59U 24.10.0
Description:
Fixed a bug using a non-thread-safe hashmap.
=> [24.10] antiblock: Update to 2.0.2

net/curl/Makefile, net/curl/patches/200-no_docs_tests.patch
bump curl to latest 8.12.1
Signed-off-by: Rudy Andram <rmandrad@gmail.com>
=> curl: bump to 8.12.1

net/nextdns/Makefile
=> nextdns: Update to version 1.44.6

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.44.6

net/nextdns/Makefile
=> [24.10] nextdns: Update to version 1.44.6

net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r28824-4387de9445 |
```
```
- Changelog:
- Update to [0.36.7](https://github.com/netbirdio/netbird/releases/tag/v0.36.7)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.36.5...v0.36.7
- N/A
--- …
=> netbird: update to 0.36.7

net/nextdns/Makefile
=> nextdns: Update to version 1.45.0

net/nextdns/Makefile
=> [24.10] nextdns: Update to version 1.45.0

net/nextdns/Makefile
=> [23.05] nextdns: Update to version 1.45.0

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/share/ddns/default/ydns.io.json
Maintainer: @ACI0419
Description:
ddns-scripts: Update ydns.io.json to accept both 'good' and 'nochg' as valid responses for IPv4 and IPv6 updates.
=> ddns-scripts: Update ydns.io.json

net/natmap/Makefile
Compile tested: x86_64, 24.10
Run tested: x86_64, 24.10
Description: Update to 20250221.
=> natmap: update to 20250221

net/natmap/Makefile
Compile tested: x86_64, 23.05
Run tested: x86_64, 23.05
Description: Update to 20250221.
=> [23.05] natmap: update to 20250221

net/tailscale/Makefile
Maintainer: me / @SuperSandro2000
Description:
https://github.com/tailscale/tailscale/releases/v1.80.3
=> tailscale: Update to 1.80.3

lang/python/django/Makefile, lang/python/numpy/Makefile, lang/python/python-evdev/Makefile, lang/python/python-pytz/Makefile
Maintainer: me
Compile tested: x86 main
Run tested: x86 main
=> numpy,evdev,pytz,openblas,django: bump versions

net/natmap/Makefile
Maintainer: @ysc3839 and me
Description: update to 20250318
=> natmap: update to 20250318

net/natmap/Makefile
Maintainer: me
Description: update to 20250318
=> [24.10] natmap: update to 20250318

net/fsh/Makefile
Maintainer: me
Description: update to 4.9.0
=> [24.10] fsh: update to 4.9.0

net/snowflake/Makefile
ChangeLog:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/6472bd86cdd5d13fe61dc851edcf83b03df7bda1
Compile tested: filogic OpenwrtOne
=> snowflake: update to 2.11.0

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/lib/ddns/update_scaleway_com.sh, net/ddns-scripts/files/usr/share/ddns/default/scaleway.com.json
Compile tested: ???
Run tested: AVM FritzBox 4040
=> ddns-scripts: add support for Scaleway DNS 

net/acme-common/Makefile, net/acme-common/files/acme.init, net/acme-common/files/acme.uci-defaults
Maintainer: me / @tohojo 
Compile tested: no only scrip changes
Run tested: x86_64, APU3
Description:
[acme: fix service_triggers on config change](https://github.com/TDT-AG/packages/commit/90cc5f65eefecf9a90327af475cbed0f4d4bd1b9)
[acme: remove lock handling](https://github.com/TDT-AG/packages/commit/1d3e9d5e1e2e7d7017c14a8d55bf31da3d09d9d1)
[acme: remove crontab entry if service is stopped](https://github.com/TDT-AG/packages/commit/ad30faec08a0dbabd6fcedb0a26a18cf21210773)
=> acme: start and stop fixes

libs/inih/Makefile
Maintainer: me
Description:
release note: https://github.com/benhoyt/inih/releases/tag/r59
=> inih: Update to r59

net/knot/patches/02_knot.conf.patch
Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbl)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbl)
Description:
- Fixes #26149
=> knot: fix patch for configuration sample file

net/zerotier/Makefile, net/zerotier/patches/0006-add-support-for-miniupnpc-2.2.8.patch
Maintainer: me
Cherry-picked from master
=> [openwrt-24.10] zerotier: add patch to support miniupnpc 2.2.8 

net/ddns-scripts/Makefile, net/ddns-scripts/files/usr/lib/ddns/update_porkbun_v3.sh
Maintainer: @feckert  @cahorn 
Compile tested: mediatek/filogic, GL.iNet GL-MT6000, MAIN SNAPSHOT
Run tested: mediatek/filogic, GL.iNet GL-MT6000, MAIN SNAPSHOT
Description:
This fixes issue: https://github.com/openwrt/packages/issues/26181
=> ddns-script: Change CURL call and redirect output in update_porkbun_v3

sound/fluidsynth/Makefile, sound/libxmp/Makefile, sound/wavpack/Makefile
Maintainer: me
Run tested: -
Description:
Update libraries (mostly) used for game music playback.
=> fluidsynth, libxmp, wavpack: update packages

net/kea/Makefile, net/kea/patches/020-boost-187.patch
Add upstream backport for compatibility with Boost 1.87
=> kea: update to 2.6.2

multimedia/ffmpeg/Makefile, multimedia/ffmpeg/patches/020-gcc14.patch
Maintainer: @thess @antonlacon
ping @1715173329
=> ffmpeg: fix compilation with GCC14

mail/mailsend/Makefile, mail/mailsend/patches/010-gcc14.patch
Also fix CFLAGS not being passed.
@GeorgeSapkin think this is subject to removal?
=> mailsend: fix compilation with GCC14

net/ntpd/Makefile, net/ntpd/patches/010-gcc14.patch
Add small patch fixing compilation with GCC14.
=> ntpd: update to 4.2.8p18

utils/cligen/Makefile, utils/clixon/Makefile
Maintainer: me
Compile tested: x86_64, HEAD, generic
Run tested: compiled only
Description:
=> Update clixon, cligen

net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29467-ecc0f549c4 |
```
```
- Changelog:
- Update to [0.43.2](https://github.com/netbirdio/netbird/releases/tag/v0.43.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.43.1...v0.43.2
- N/A …
=> netbird: update to 0.43.2

net/unbound/Makefile, net/unbound/patches/010-configure-uname.patch
Maintainer: me
Test: WRT3200ACM
Description: Unbound 1.23.0
=> unbound: update to 1.23.0

net/pdns/Makefile
=> pdns: update to 4.9.5

net/acme-acmesh/Makefile
=> acme-acmesh: Bump to v3.1.1

utils/owut/Makefile
Maintainer: me
Run tested: x86/64 main snapshot
Bug fixes:
efahl/owut@8353c4e9e255 argparse: add a file path parser type
efahl/owut@724c990d6cc0 owut: avoid redirects on upstream queries
=> owut: update to 2025.05.12

mail/alpine/Makefile, mail/alpine/patches/030-gcc14.patch
Wrong function prototypes.
Maintainer: @pesintta
=> alpine: fix compilation with GCC14

net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29467-ecc0f549c4 |
```shell
reboot
```
- Changelog:
- Update to [0.44.0](https://github.com/netbirdio/netbird/releases/tag/v0.44.0) …
=> netbird: update to 0.44.0

utils/owut/Makefile
Maintainer: me
Bug fixes:
efahl/owut@8353c4e9e255 argparse: add a file path parser type
efahl/owut@724c990d6cc0 owut: avoid redirects on upstream queries
(cherry picked from commit 444353f7ce298b7ac59a720d1f0544fb82e1d38c)
=> [24.10] owut: update to 2025.05.12

net/static-neighbor-reports/README.md
Define VAP on first use and fix some typos.
Maintainer: @blocktrron
Compile tested: n/a readme
Run tested: n/a readme
Description: Define VAP on first use and fix some typos.
Signed-off-by: @andybjackson  <andybjackson@hotmail.com>
=> static-neighbor-reports: Update README.md

lang/lua-cjson/Makefile, lang/lua-cjson/patches/001-add-support-lua5-x.patch
=> lua-cjson: add build VARIANT for Lua5.4

lang/perl-class-inspector/Makefile, lang/perl-file-sharedir/Makefile, lang/perl-future-asyncawait/Makefile, lang/perl-future-asyncawait/src/Makefile.PL, lang/perl-future/Makefile, lang/perl-future/src/Makefile.PL, lang/perl-io-async/Makefile, lang/perl-io-async/src/Makefile.PL, lang/perl-io-socket-ssl/Makefile, lang/perl-net-ssleay/Makefile, lang/perl-net-ssleay/patches/001-prefix.patch, lang/perl-struct-dumb/Makefile, lang/perl-struct-dumb/src/Makefile.PL, lang/perl-xs-parse-keyword/Makefile, lang/perl-xs-parse-keyword/src/Makefile.PL, lang/perl-xs-parse-sublike/Makefile, lang/perl-xs-parse-sublike/src/Makefile.PL
Maintainer: Jens Wagner <jens@wagner2013.de>
Compile tested: aarch64_cortex-a53, RPi3, 24.10.1
Run tested: mipsel_24kc, RT-AX53U, 24.10.0, various Perl snippets
Description: Modules for modern Perl development
=> Perl modules for IO::Socket::SSL, IO::Async and Future::AsyncAwait

utils/rtty/Makefile
(cherry picked from commit e63935b86a3073d2ee3ac70c4a32191534abb697)
=> [24.10] rtty: update to 8.1.3

net/antiblock/Makefile, net/antiblock/files/etc/init.d/antiblock
1) Added the ability to disable routes without deleting them.
=> antiblock: Update to 2.1.2r2

libs/vips/Makefile
=> vips: update to 8.16.1

libs/libgcrypt/Makefile
=> libgcrypt: update to 1.11.1

libs/libexif/Makefile, libs/libexif/patches/100-no_doc.patch
=> libexif: update 0.6.25

utils/fuse-overlayfs/Makefile
=> fuse-overlayfs: update to 1.15

libs/openldap/Makefile
=> openldap: update to 2.6.10

libs/libgpg-error/Makefile
=> libgpg-error: update to 1.55

lang/python/python-networkx/Makefile
=> python-networkx: update to 3.5

net/antiblock/Makefile, net/antiblock/files/etc/init.d/antiblock
1) Added the ability to disable routes without deleting them.
=> [24.10] antiblock: Update to 2.1.2r2

lang/lua-cjson/Makefile, lang/lua-cjson/patches/001-add-support-lua5-x.patch
(cherry picked from commit ae118bed1815773dd4d5ff3245be72b4182d47ec)
=> [24.10] lua-cjson: add build VARIANT for Lua5.4

net/dufs/Makefile, net/dufs/files/dufs.config, net/dufs/files/dufs.init
Maintainer: me
Description:
Dufs is a distinctive utility file server that supports static serving, uploading, searching, accessing control, webdav...
=> dufs: add new package

net/tailscale/Makefile
**Maintainer:** me / @mochaaP 
**Description:** update to 1.84.2
---
- **OpenWrt Target/Subtarget:** arm_cortex-a7_neon-vfpv4
- **OpenWrt Device:** AVM FRITZ!Box 7530
---
```bash
```
=> tailscale: update to 1.84.2

net/ariang/Makefile
Maintainer: Ansuel Smith <ansuelsmth@gmail.com>
Compile tested: aarch64 master
Run tested: MT-6000
Description:
=> ariang: bump to 1.3.10

utils/prometheus-node-exporter-lua/Makefile, utils/prometheus-node-exporter-lua/files/usr/bin/prometheus-node-exporter-lua
netclass collector scrape time goes from 230ms to 170ms
=> prometheus-node-exporter-lua: use buffered io, remove concat

utils/tang/patches/100-tang-show-keys-use-wget.patch
**Maintainer:** @Tiboris  @nmav 
refresh patches
---
not necessary, patch stays identical, no change in code
---
- [ x ] I have reviewed the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
=> [23.05] tang: Refresh patches

utils/quota/Makefile, utils/quota/patches/001-setproject-fix-openat-call.patch
backport upstream commit d9852bd5b76ca65f283929e803b87343942ecb1f
=> quota: fix setproject binary

libs/postgresql/Makefile
See https://www.postgresql.org/docs/17/release-17-5.html
---
---
=> postgresql: update to 17.5

libs/libp11/Makefile, libs/libp11/patches/001-fix-install.patch
See release notes since 0.4.13:
https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.14
https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.15
https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.16
---
---
=> libp11: update to 0.4.16

utils/cligen/Makefile, utils/cligen/patches/010-gcc15.patch
Upstream has this fixed in a massive patch.
**Maintainer:** @pprindeville
=> cligen: fix compilation with GCC 15

net/sing-box/Makefile
changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.11.15
---
---
```bash
```
=> sing-box: Update to 1.11.15

net/strongswan/Makefile, net/strongswan/patches/0904-gmpdh-Plugin-that-implements-gmp-DH-functions-in-an-.patch
**Maintainer:** me, @Thermi 
Update to 6.0.2
---
Installed on test VM
HEAD
x86_64/generic
Supermicro SYS-D5018-FN4T
---
```bash
```
N/A
=> strongswan: Update to 6.0.2

net/hev-socks5-server/Makefile
**Description:** update to 2.9.0
---
---
=> hev-socks5-server: update to 2.9.0

net/hev-socks5-tproxy/Makefile
**Description:** update to 2.9.0
---
---
=> hev-socks5-tproxy: update to 2.9.0

net/hev-socks5-tunnel/Makefile
**Description:** update to 2.12.0
---
---
=> hev-socks5-tunnel: update to 2.12.0

libs/cyrus-sasl/Makefile, libs/cyrus-sasl/patches/020-gcc15.patch
**Maintainer:** @flyn-org 
Cherry pick from maintainer's fork
---
```bash
```
=> cyrus-sasl: fix build with GCC 15.1

net/tailscale/Makefile
**Maintainer:** me / @mochaaP 
**Description:** update to 1.86.2
---
- **OpenWrt Target/Subtarget:** arm_cortex-a7_neon-vfpv4
- **OpenWrt Device:** AVM FRITZ!Box 7530
---
```bash
```
=> tailscale: update to 1.86.2

libs/rpcsvc-proto/Makefile
**Maintainer:** none
Remove unneeded autoreconf.
---
- **OpenWrt Version:** snapshot 
- **OpenWrt Device:** n/a
---
=> rpcsvc-proto: Update to 1.4.4

utils/cligen/Makefile, utils/cligen/patches/010-gcc15.patch, utils/clixon/Makefile
**Maintainer:** me, @olofhagsand
Update `cligen` and `clixon` to 7.5.0
---
HEAD
x86_64/generic
Supermicro SYS-D5018-FN4T
---
```bash
```
=> Update cligen clixon 7.5.0

net/sing-box/Makefile
changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.12.0
---
---
=> sing-box: update to 1.12.0

utils/syncthing/Makefile, utils/syncthing/files/stdiscosrv.conf, utils/syncthing/files/stdiscosrv.init, utils/syncthing/files/strelaysrv.conf, utils/syncthing/files/strelaysrv.init
**Maintainer:** @brvphoenix, me
Fix discovery and relay extra args and update configuration option examples.
Fixes: #26952
CC: @tedcriss
---
---
=> syncthing: fix discovery and relay extra args

net/uspot/Makefile
**Description:** Update uspot to Git HEAD (2025-08-02)
(cherry picked from commit 3d76208 + adjustments for 23.05 PKG_MIRROR_HASH)
=> [23.05] uspot: update to Git HEAD (2025-08-07)

net/sing-box/Makefile
changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.12.0
(cherry picked from commit 654fa2f5f3842b85672bb1d9a277a438672bb347)
---
---
=> [24.10] sing-box: update to 1.12.0

net/pbr/Makefile, net/pbr/files/etc/init.d/pbr
Maintainer: me
Compile tested: x86_64, Dell EMC Edge 640vn, OpenWrt 24.10.2
Run tested: x86_64, Dell EMC Edge 640vn, OpenWrt 24.10.2
Description:
* bugfix: json init was destroying procd_triggers and screwing boot up fixes https://github.com/openwrt/packages/issues/27194
* improvement: explicit printf calls in get_text
=> pbr: update to 1.1.8-34

lang/perl/perl-file-rsyncp/Makefile, lang/perl/perl-file-rsyncp/patches/010-gcc15.patch
Fix compilation with GCC15.
**Maintainer:** ???
=> perl-file-rsyncp: update to 0.76

admin/gkrellmd/Makefile
Fixes compilation with GCC15.
**Maintainer:** @pnd10
=> gkrellmd: update to 2.4.0

libs/libjpeg-turbo/Makefile
=> libjpeg-turbo: update to 3.1.1

utils/nnn/Makefile, utils/nnn/patches/musl-fts.patch
- Release notes: https://github.com/jarun/nnn/compare/v4.9...v5.1
**Maintainer:** @BKPepe
---
---
=>  nnn: update to version 5.1

net/yggdrasil/Makefile
**Maintainer:** @wfleurant
cherry picked from commit 8daa597
---
---
```bash
```
=> [24.10] yggdrasil: update to 0.5.12

utils/micro/Makefile, utils/micro/test.sh
Modern and intuitive terminal-based text editor
https://micro-editor.github.io
**Maintainer:** @gargullia
---
---
```bash
```
=> micro: add new package

net/lksctp-tools/Makefile
=> lksctp-tools: update to 1.0.21

libs/libconfig/Makefile
Fixes compilation with GCC 15.
**Maintainer:** @nbd168
=> libconfig: update to 1.8.1

libs/pixman/Makefile
**Maintainer:** @yousong 
See https://gitlab.freedesktop.org/pixman/pixman/-/commits/pixman-0.46.4 for changes since pixman-0.43.4.
---
- **OpenWrt Version:** -
- **OpenWrt Target/Subtarget:** -
---
=> pixman: update to version 0.46.4

net/tailscale/Makefile
**Maintainer:** me / @mochaaP / @jefferyto / @GeorgeSapkin
**Description:** update tailscale to 1.88.1
---
- **OpenWrt Target/Subtarget:** arm_cortex-a7_neon-vfpv4
- **OpenWrt Device:** AVM FRITZ!Box 7530
---
```bash
```
=> golang: update to 1.25.1, tailscale: update to 1.88.1 

utils/cmdpad/Makefile, utils/cmdpad/patches/010-gcc15.patch
There's no parameter to this function.
**Maintainer:** @thess
=> cmdpad: fix compilation with GCC 15

net/dnsdist/Makefile
**Maintainer:** me + @rgacogne 
fixes CVE-2025-4820, CVE-2025-4821, CVE-2025-7054
---
- **OpenWrt Target/Subtarget:** x86_64 container
- **OpenWrt Device:** x86_64 container
---
```bash
```
=> dnsdist: update to 2.0.1

libs/giflib/Makefile, libs/giflib/patches/200-verify-color-in-range.patch
Fixes:
CVE-2022-28506
CVE-2023-48161
CVE-2024-45993
CVE-2025-31344
Closes #26277
=> giflib: Add Gentoo patch to fix various CVEs

libs/xmlrpc-c/Makefile
=> xmlrpc-c: [Security] Remove obsolete "-internal" variant

net/ddns-scripts/files/usr/lib/ddns/update_cloudflare_com_v4.sh
**Maintainer:** @feckert 
adjust comments documenting the already supported API Token auth
adjust comments with URLs that changed in the meantime
adjust comment regarding CF API documentation URL, points to the scripts relevant DNS section
---
_-No test runs were conducted since only comments changed-_
---
=> ddns-scripts-cloudflare: document API Token auth in comments
