openwrt/packages

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> [openwrt-23.05] haproxy: update to v2.8.3

- lang/python/python-pyserial/Makefile
Maintainer: @mickeprag
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-09-03 snapshot
Description:
> python-pyserial: Update to 3.5, update list of dependencies

- lang/python/python-zeroconf/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-09-03 snapshot
Description:
The package changed to the poetry-core build backend (and also requiring python-cython/host).
> python-zeroconf: Update to 0.97.0, update list of dependencies

- lang/python/python-zipp/Makefile
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-09-03 snapshot
Description:
> python-zipp: Update to 3.16.2, update list of dependencies

- lang/python/python-ruamel-yaml/Makefile
Run tested: armsr-armv7 (qemu), 2023-09-03 snapshot
Description:
This renames the source package to python-ruamel-yaml to match other Python packages.
> ruamel-yaml: Update to 0.17.32, rename source package

- lang/python/python-xmltodict/Makefile
Run tested: armsr-armv7 (qemu), 2023-09-03 snapshot
Description:
This renames the source package to python-xmltodict to match other Python packages.
> xmltodict: Update to 0.13.0, rename source package

- libs/slang2/Makefile
Maintainer: me
Compile tested: none (cherry picked from #22020)
Description:
Please see the individual commit messages for details.
> [openwrt-23.05] slang2: Avoid building dependencies unless necessary, remove pcre module

- net/openvpn/Makefile
- net/openvpn/patches/101-Fix-EVP_PKEY_CTX_-compilation-with-wolfSSL.patch
Maintainer: @mkrkn 
Compile tested: ramips/mt7620, ramips/mt7621
Run tested: Xiaomi mi router 3 pro, Xiaomi mi-mini, Xiaomi miwifi-r3
Small bugfix release
For details refer to https://github.com/OpenVPN/openvpn/blob/v2.6.6/Changes.rst
Also, set depends on DCO kernel module when ENABLE_DCO flag is set.
> openvpn: update to 2.6.6

- utils/ncdu/Makefile
Upstream bump
Description: @clehner
> ncdu: update to 1.18.1

- libs/libssh/Makefile
Maintainer:  @neheb @PolynomialDivision 
Compile tested: librerouter-v1 ath79 OpenWrt main development branch
Run tested: librerouter-v1 ath79 OpenWrt, successfully run tmate which depends on libssh
Description:
Since 2017 libssh supports to be compiled against libmbedtls instead of libopessl, OpenWrt ships mbedtls by default, while depending on OpenSSL increase image size by almost 1.5MB unnecessarily.
> libssh: compile against MbedTLS instead of OpenSSL

- lang/python/python-xmltodict/Makefile
Compile tested: none (cherry picked from #22039)
Description:
This renames the source package to python-xmltodict to match other Python packages.
(cherry picked from commit 4872c325808357c0cb81a4367d053cc5b5468028)
> [openwrt-23.05] xmltodict: Update to 0.13.0, rename source package

- lang/python/python-zeroconf/Makefile
Compile tested: none (cherry picked from #22036)
Description:
The package changed to the poetry-core build backend (and also requiring python-cython/host).
(cherry picked from commit 8957d34d09eac268815ba8abc8ec5bcb1cd0f1f4)
> [openwrt-23.05] python-zeroconf: Update to 0.97.0, update list of dependencies

- lang/rust/rust-package.mk
- lang/rust/rust-values.mk
Compile tested: armsr-armv7, 2023-09-09 snapshot sdk
Description:
This allows other packages access to `RUST_ARCH_DEPENDS` by including rust-values.mk, instead of rust-package.mk which also sets `Build/Compile`.
> rust: Move RUST_ARCH_DEPENDS into rust-values.mk

- lang/python/python-zipp/Makefile
Compile tested: none (cherry picked from #22037)
Description:
(cherry picked from commit 202140aeff26f5f61ff8ae0016093e857a55b50d)
> [openwrt-23.05] python-zipp: Update to 3.16.2, update list of dependencies

- lang/python/python-ruamel-yaml/Makefile
Compile tested: none (cherry picked from #22038)
Description:
This renames the source package to python-ruamel-yaml to match other Python packages.
(cherry picked from commit fdff92f0855d40d65a77d47e0e0db8e23f75a1f3)
> [openwrt-23.05] ruamel-yaml: Update to 0.17.32, rename source package

- lang/python/python-cryptodome/Makefile
- lang/python/python-cryptodome/patches/001-fix-libgmp-loading.patch
- lang/python/python-cryptodome/patches/002-omit-tests.patch
Compile tested: none (cherry picked from #22040)
Description:
(cherry picked from commit 03f1f4b9bb426670ddf4b870ed4dfbe354e19fcf)
> [openwrt-23.05] python-cryptodome: Update to 3.18.0, refresh patches

- lang/python/python-cryptodomex/Makefile
- lang/python/python-cryptodomex/patches/001-fix-libgmp-loading.patch
- lang/python/python-cryptodomex/patches/002-omit-tests.patch
Compile tested: none (cherry picked from #22041)
Description:
(cherry picked from commit a1b3595550ebc6db9f21bce7a1a958bf7accedbe)
> [openwrt-23.05] python-cryptodomex: Update to 3.18.0, refresh patches

- lang/python/python-pyserial/Makefile
Maintainer: @mickeprag
Compile tested: none (cherry picked from #22042)
Description:
(cherry picked from commit 4f3a0fe6232f7746e80c68b5d5f51797c6984896)
> [openwrt-23.05] python-pyserial: Update to 3.5, update list of dependencies

- lang/python/python-crcmod/Makefile
Maintainer: @blocktrron
Compile tested: N/A (cherry picked from #22043)
Description:
(cherry picked from commit 8e5ca3fc3e78d92a2e9cfa1ac1696f5151351816)
> [openwrt-23.05] python-crcmod: Fix package section

- net/snort3/Makefile
```
o"  )~   Version 3.1.70.0
Using DAQ version 3.0.12
Using OpenSSL 3.0.10 1 Aug 2023
Using ZLIB version 1.2.13
Using Hyperscan version 5.4.2 2023-09-07
```
> snort3: update to 3.1.70.0

- net/tailscale/README.md
- net/tailscale/files/tailscale.conf
- net/tailscale/files/tailscale.init
Compile tested: `mips_24kc` @ SNAPSHOT
Run tested: `aarch64_cortex-a53` @ 22.03.5, `mips_24kc` @ SNAPSHOT
Description:
This changes the default firewall method used by Tailscale to nftables. The 'autodetection' mode is [only supported by arm64 and amd64](https://github.com/tailscale/tailscale/blob/dc7aa98b768bf82017aa5cc82a62dd4d685f811d/util/linuxfw/linuxfw_unsupported.go#L4C58-L4C58) for now. This causes mips devices to not do proper detection and incorrectly default back to iptables.
I added a fw_mode variable to the tailscale.conf file that could be set to iptables for easy conversion for someone still using iptables. I was able to test on an older mips device and my current aarch64 without issues.
Also a few readme updates to bring it up to the current …
> tailscale: set nftables as default

- admin/syslog-ng/Makefile
- admin/syslog-ng/files/syslog-ng.conf
Maintainer: me
Compile tested: MacBook Pro, A1990, OpenWrt 22.03 for Turris Omnia, mvebu/cortexa9
Run tested: N/A, since I could not compile it for OpenWrt 21.02 due to Darwin platform, which resulted in cherry-picking a few commits to that branch, hopefully to be compiled, because the latest Turris OS version, which is now 6.3.1 still runs EoL, thus in the meantime, I prepared locally build env for OpenWrt 22.03, where it works.
Once, I confirm it that it works on the router, I will set my PR as ready instead of draft.
Description:
Makefile changes:
- Since version 4.3.0, there is required to use pcre2 instead of pcre 
Reference: https://github.com/syslog-ng/syslog-ng/pull/4537 (not mentioned in the release notes in tag :( )
- Disable c++ support by default to avoid picking and including …
> syslog-ng: update to version 4.3.1

- net/dnscrypt-proxy2/Makefile
Maintainer: me
Compile tested: Nope, I was not able to compile it on MacBook A1990, while using OpenWrt 22.03. The previous version was just fine. Preparing currently env with OpenWrt master to give it another try until then draft.
Description:
- Fixes compilation with Go 1.21+.
Fixes #21881
> dnscrypt-proxy2: update to version 2.1.5

- net/zerotier/Makefile
see changelog: https://github.com/zerotier/ZeroTierOne/releases/tag/1.12.2.
Maintainer: @mwarning 
> zerotier: update to 1.12.2

- kernel/ovpn-dco/Makefile
Maintainer: @AuthorReflex
Compile tested: x86_64, latest master
Run tested: x86_64, latest master
Description:
We have to add an "IPV6:" in front of the kmod-udptunnel6 to fix redundant dependencies with the openvpn-* packages.
> ovpn-dco: fix package dependencies

- libs/libucontext/Makefile
- libs/libucontext/patches/010-return_values_fix.patch
- libs/libucontext/patches/020-honor_return_values_fix.patch
Description (from libucontext github page):
libucontext (https://https://github.com/kaniini/libucontext) is a library which provides the ucontext.h C API. Unlike other implementations, it faithfully follows the kernel process ABI when doing context swaps. libucontext is used on almost all musl distributions to provide the legacy ucontext.h API.
This package is meant as a development package. There is no need to install a package on the router if an application or library is linked against the static libraries. Though, shared libraries are provided also.
It is used to link libraries/applications against it which need the system calls
* makecontext
* swapcontext
* getcontext
* setcontext
E.g. the asynchronous API of libmariadb (c-connector) uses this system calls. Because libmusl didn't …
> [openwrt-23.05] libucontext: Add package

- lang/rust/rust-package.mk
- lang/rust/rust-values.mk
Compile tested: none (cherry picked from #22095)
Description:
This allows other packages access to `RUST_ARCH_DEPENDS` by including rust-values.mk, instead of rust-package.mk which also sets `Build/Compile`.
(cherry picked from commit 985738b3991611be3b0b85e2b47cfb3ef0bbc335)
> [openwrt-23.05] rust: Move RUST_ARCH_DEPENDS into rust-values.mk

- net/curl/Makefile
Compile tested: MacBook A1990, MacOS Version 13.5.1 (22G90)
Run tested: Turris Omnia, OpenWrt 22.03, mvebu/cortexa9
```
root@turris:~# curl -V
curl 8.3.0 (arm-openwrt-linux-muslgnueabi) libcurl/8.3.0 OpenSSL/1.1.1v nghttp2/1.44.0
Release-Date: 2023-09-13
Protocols: file ftp ftps http https mqtt
Features: alt-svc HSTS HTTP2 HTTPS-proxy IPv6 Largefile SSL threadsafe
```
Fixes:
CVE-2023-38039 [1]
[1] https://curl.se/docs/CVE-2023-38039.html
> curl: update to version 8.3.0

- utils/conmon/Makefile
Bug fixes:
- stdio: ignore EIO for terminals
- ensure console socket buffers are properly sized
- conmon: drop return after pexit()
- ctrl: make accept4 failures fatal
- logging: avoid opening /dev/null for each write
- oom: restore old OOM score
- Use default umask 0022
Misc changes:
- cli: log parsing errors to stderr
- Changes to build conmon for riscv64
- Changes to build conmon for ppc64le
- Fix close_other_fds on FreeBSD
Maintainer: me
> conmon: update to 2.1.8

- utils/crun/Makefile
Changes:
- support arbitrary idmapped mounts. Now it is possible to specify a mapping for any type of mount, not only bind mounts.
- add support for "ridmap" mount option to support recursive idmapped mounts.
- fix check for oom_score_adj. Write the oom_score_adj file even when the new value is 0.
- features: Support mountExtensions.
- correctly handle unknown signal string when it doesn't start with a digit.
- do not attempt to join again already joined namespace.
- wasmer: use latest wasix API.
- refresh libocispec
Maintainer: me
> crun: update to 1.9

- utils/podman/Makefile
- utils/podman/patches/010-do-not-build-docs.patch
patch refreshed.
Changelog:
- Fixed a performance issue when calculating diff sizes in overlay. The podman system df command should see a significant performance improvement.
- Fixed a bug where containers in a pod would use the pod restart policy over the set container restart policy.
- Fixed a bug in the Compat Build endpoint where the pull query parameter did not parse 0/1 as a boolean.
- Updated the containers/storage library to v1.48.1
Maintainer: me
> podman: update to 4.6.2

- net/netavark/Makefile
Changelog: https://github.com/containers/netavark/compare/v1.6.0...v1.7.0
Maintainer: me
> netavark: update to 1.7.0

- net/aardvark-dns/Makefile
Changelog: https://github.com/containers/aardvark-dns/compare/v1.6.0...v1.7.0
Maintainer: me
> aardvark-dns: update to 1.7.0

- net/curl/Makefile
Compile tested: MacBook A1990, MacOS Version 13.5.1 (22G90)
Run tested: Turris Omnia, OpenWrt 22.03, mvebu/cortexa9
Release notes:
https://curl.se/changes.html#8_3_0
Fixes:
CVE-2023-38039 [1]
[1] https://curl.se/docs/CVE-2023-38039.html
Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>
(cherry picked from commit 07c0a5eab8fe073fabcba999e6176fec93bd696b)
> [22.03] curl: update to version 8.3.0

- net/curl/Makefile
Compile tested: MacBook A1990, MacOS Version 13.5.1 (22G90)
Run tested: Turris Omnia, OpenWrt 22.03, mvebu/cortexa9
Release notes:
https://curl.se/changes.html#8_3_0
Fixes:
CVE-2023-38039 [1]
[1] https://curl.se/docs/CVE-2023-38039.html
Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>
(cherry picked from commit 07c0a5eab8fe073fabcba999e6176fec93bd696b)
> [23.05] curl: update to version 8.3.0

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, allow domain
Description:
* fix sed command to properly remove allowed domains from block-file
> adblock-fast: bugfix: remove domains on allow

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, allow domain
Description:
* fix sed command to properly remove allowed domains from block-file
(cherry picked from commit bce310bfcd41a20b85fbe85fdcdf47ab1d5032bf)
> [23.05] adblock-fast: bugfix: remove domains on allow

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/hotplug.d/iface/90-https-dns-proxy
- net/https-dns-proxy/files/etc/hotplug.d/online/30-https-dns-proxy
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, verify encrypted dns resolution on boot
Description:
* replace existing hotplug.d script with the new one
> https-dns-proxy: improve boot up start

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/hotplug.d/iface/90-https-dns-proxy
- net/https-dns-proxy/files/etc/hotplug.d/online/30-https-dns-proxy
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, verify encrypted dns resolution on boot
Description:
* replace existing hotplug.d script with the new one
(cherry picked from commit 22d21e28a79a5246e4f6068cbc0be59e5226c486)
> [22.03] https-dns-proxy: improve boot up startup

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/hotplug.d/iface/90-https-dns-proxy
- net/https-dns-proxy/files/etc/hotplug.d/online/30-https-dns-proxy
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, verify encrypted dns resolution on boot
Description:
* replace existing hotplug.d script with the new one
> [23.05] https-dns-proxy: improve boot up startup

- multimedia/ffmpeg/Makefile
Maintainer: @thess , @antonlacon 
Compile tested: MacBook, macOS Ventura Version 13.5.2 (22G91), model A1990
Run tested: Will be shortly run tested on Turris Omnia, mvebu/cortexa9, OpenWrt 22.03.
Fixes CVEs:
CVE-2022-3964 [1]
CVE-2022-3965 [2]
[1] https://nvd.nist.gov/vuln/detail/CVE-2022-3964
[2] https://nvd.nist.gov/vuln/detail/CVE-2022-3965
> ffmpeg: update to version 5.1.3

- net/transmission/Makefile
- net/transmission/files/transmission-daemon.json
- net/transmission/files/transmission.init
Compile tested: mediatek_filogic
Run tested: BananaPi R3
Description:
There are some important transmission fixes not applied to 23.05 branch. It was constantly crashing the service.
> [23.05] Transmission backports from master

- lang/perl-cgi/Makefile
Maintainer: me, @Naoir
Compile tested: x86_64, generic, HEAD (9194fcb1a4)
Description:
Routine update to upstream latest.
> perl-cgi: Update to 4.57

- utils/podman/Makefile
podman still seems to use catatonit with
rootless containers. It seems that it is
possible to use alternatives, such as tini,
but maybe go the same way they went on mainstream.
This PR just adds catatonit to depends.
Maintainer: me
> podman: depend on catatonit

- utils/collectd/Makefile
We currently have more package architectures supporting CPU frequency scaling than earlier, and the package architecture vs. CPU target SDK matching does not fully reflect that. (E.g. aarch64_cortex-a53 is currently using bcm27xx/bcm2710)
Simplify things by removing the target dependency and let the plugin be built for all architectures.
Compile tested: CI testing via this PR
Run tested: -
Reference to issue [#12965 in OpenWrt bug tracker](https://github.com/openwrt/openwrt/issues/12965) and https://forum.openwrt.org/t/where-is-collectd-mod-cpufreq-gone/162459
> collectd: remove target dependency from cpufreq plugin

- net/knot/Makefile
Description:
- Release upgrade (https://www.knot-dns.cz/2023-09-11-version-331.html)
> knot: update to version 3.3.1

- utils/slirp4netns/Makefile
v1.2.2 changes:
- Enabled reproducible builds
v1.2.1 changes:
- sandbox: Add support for escaping resolv.conf symlinks. This fixes usage in WSL environments which symlinks /etc/resolv.conf under a shared location under /mnt.
Maintainer: me
> slirp4netns: update to 1.2.2

- net/bind/Makefile
Compile tested: MacBook, macOS Ventura Version 13.5.2 (22G91), model A1990
Run tested: Turris Omnia, the latest changes from the OpenWrt 22.03 branches with one tweak - kernel 5.15 LTS known as Turris OS 7.0.0, which was not released to end-users so far, mvebu/cortex-a9
**Named works, dig works.**
Release notes:
https://downloads.isc.org/isc/bind9/9.18.18/doc/arm/html/notes.html#notes-for-bind-9-18-18 https://downloads.isc.org/isc/bind9/9.18.17/doc/arm/html/notes.html#notes-for-bind-9-18-17
> bind: update to version 9.18.18

- lang/rust/Makefile
- lang/rust/files/cargo-config
- lang/rust/rust-package.mk
- lang/rust/rust-values.mk
Compile tested: x86-generic, 2023-09-09 snapshot sdk
Run tested: x86-generic (qemu, ran `ripgrep --version`), 2023-09-09 snapshot
Description:
In order to use `$(RUSTC_TARGET_ARCH)` in `HOST_BUILD_DIR`, the line to include rust-values.mk in the Rust makefile was moved in f489e019ac4a15e974518d9928ef913a157d135a, causing it to be included before package.mk is included.
This had the side effect of preventing "-lssp_nonshared" from being added to `RUSTC_LDFLAGS`, because `PKG_SSP` is indirectly set by package.mk (package.mk includes hardening.mk, hardening.mk sets `PKG_SSP`).
There is a deeper issue; it is the Rust package's `PKG_SSP` value that causes `RUSTC_LDFLAGS` to be set and written to the Cargo config file. For packages that use Rust to build, their `PKG_SSP` …
> rust: Set rustflags by environment variable

- lang/node/Makefile
- lang/node/patches/999-localhost-no-addrconfig.patch
Description:
Update to v18.18.0
> node: bump to v18.18.0

- lang/node/Makefile
- lang/node/patches/999-localhost-no-addrconfig.patch
Description:
Update to v18.18.0
(cherry picked from commit 86355454094ce47f47a468727897e335ba2f316d)
> [23.05] node: bump to v18.18.0

- libs/libdrm/Makefile
Hi, 
Unbreak using libdrm program compile in 21.02. The error is  missing <drm.h>，so i just cherry-picking the same fix commit cb8c0ba for libdrm as in master.
> [21.02] libdrm: install all headers (cherry-picking)

- lang/rust/Makefile
- lang/rust/files/cargo-config
- lang/rust/rust-package.mk
- lang/rust/rust-values.mk
Compile tested: none (cherry picked from #22134)
Description:
In order to use `$(RUSTC_TARGET_ARCH)` in `HOST_BUILD_DIR`, the line to include rust-values.mk in the Rust makefile was moved in f489e019ac4a15e974518d9928ef913a157d135a, causing it to be included before package.mk is included.
This had the side effect of preventing "-lssp_nonshared" from being added to `RUSTC_LDFLAGS`, because `PKG_SSP` is indirectly set by package.mk (package.mk includes hardening.mk, hardening.mk sets `PKG_SSP`).
There is a deeper issue; it is the Rust package's `PKG_SSP` value that causes `RUSTC_LDFLAGS` to be set and written to the Cargo config file. For packages that use Rust to build, their `PKG_SSP` value does not affect the linker flag.
This sets rustflags with the …
> [openwrt-23.05] rust: Set rustflags by environment variable

- lang/python/python-networkx/Makefile
Compile tested: armsr-armv7, 2023-09-16 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-09-16 snapshot
Description:
This renames the source package to python-networkx to match other Python packages.
> python3-networkx: Update to 3.1, rename source package

- libs/czmq/Makefile
Maintainer:  @ja-pa 
Compile tested: MacBook, macOS Ventura Version 13.5.2 (22G91), model A1990
Run tested: Turris Omnia, the latest changes from the OpenWrt 22.03 branches with one tweak - kernel 5.15 LTS known as Turris OS 7.0.0, which was not released to end-users so far, mvebu/cortex-a9
Description:
It seems like the libpcre dependency was added by mistake. While checking in the source code of czmq (Makefile.am, CMakeLists.txt), I see there are several dependencies, but there isn't PCRE.
Fixes: 936a48a ("czmq: add new package")
> czmq: drop libpcre dependency

- net/netifyd/Config.in
- net/netifyd/Makefile
Maintainer: Darryl Sokoloski / @dsokoloski
Compile tested: arm_cortex-a15_neon-vfpv4, TP-Link Archer C2600, master
Run tested: TP-Link Archer C2600
- Fixed mbedTLS crashes and TLS handshake errors when the nDPI-bundled libgcrypt "lite" version conflicts with the system version (via libcurl).
- Fixed linking order issue with libini.
- Fixed non-portable static linking warning with libndpi.
- Write flows to sockets regardless if "add_flows" is true.
- Fixed compilation error if _DIRENT_HAVE_D_RECLEN isn't defined.
- Fixed Agent path.
- [OpenWrt] Switch to "grep -E" as "egrep" is deprecated.
- Fixed possible ndAddr crash: return a const reference for cached strings.
> netifyd: Updated to v4.4.7

- utils/mg/Makefile
- utils/mg/patches/001-cross_compile_openwrt.patch
- utils/mg/patches/901-use_pcre.patch
Maintainer: me 
Compile tested: head, aarch64
Run tested: aarch64 (qemu-8.1.0)
Description:
Switch pcre to pcre2
https://github.com/openwrt/packages/issues/22006
> mg: switch pcre to pcre2

- net/nginx/Makefile
Maintainer: Thomas Heil <heil@terminal-consulting.de>, Ansuel Smith <ansuelsmth@gmail.com>
Compile tested: Xiaomi AX3600 on the latest main
Run tested: Xiaomi AX3600 on the latest main
Description:
Update nginx to the latest version which brings mainly fixes to HTTP/3 (QUIC).
While at it update brotli to the latest version.
> nginx: update nginx and brotli

- lang/luajit2/Makefile
- lang/luajit2/patches/010-lua-path.patch
Maintainer: Thomas Heil <heil@terminal-consulting.de> & Ansuel Smith <ansuelsmth@gmail.com>
Run tested: master x86-64
Description:
This PR switches luajit to [OpenResty's fork](https://github.com/openresty/luajit2), so we get rid of:
```
$ nginx -c /etc/nginx/nginx.conf
2023/05/05 09:45:00 [alert] 12167#0: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
```
when using a lua module like [nginx-lua-prometheus](https://github.com/knyar/nginx-lua-prometheus)
> luajit2: add new package, OpenResty's mantained branch of luajit

- net/tailscale/Makefile
Compile tested: mips_24kc @ SNAPSHOT
Run tested: aarch64_cortex-a53` @ 22.03.5 on Linksys E8450 & mips_24kc @ SNAPSHOT on GL.iNet GL-AR750
Description:
update to v1.48.2
Release notes:
https://github.com/tailscale/tailscale/releases/tag/v1.48.2
> tailscale: update to version 1.48.2

- lang/python/python-bidict/Makefile
Compile tested: armsr-armv7, 2023-09-16 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-09-16 snapshot
Description:
The package no longer has a build dependency on setuptools-scm.
> python-bidict: Update to 0.22.1

- utils/btrfs-progs/Makefile
Hey, Karel, I am so sorry, but it seems I did not my job very carefully. Mea culpa! I missed only this package, when I was taking maintainership from you https://github.com/openwrt/packages/pull/22030 since you used work address instead of your personal one. I thought I did it alright, but you know, just starting with this device and getting used to that. :)
Compile tested: MacBook, macOS Ventura Version 13.5.2 (22G91), model A1990
Run tested: Turris Omnia, the latest changes from the OpenWrt 22.03 branches with one tweak - kernel 5.15 LTS known as Turris OS 7.0.0, which was not released to end-users so far, mvebu/cortex-a9 
Release notes:
https://github.com/kdave/btrfs-progs/releases/tag/v6.5.1
> btrfs-progs: update to version 6.5.1

- net/crowdsec/Makefile
Update crowdsec to latest upstream release version 1.5.4
Package tested. not able to test run due to limited space (package is big)
Description: update to latest version of upstream
> crowdsec: new upstream release version 1.5.4

- libs/libmariadb/Makefile
- libs/libmariadb/patches/010-link-to-libucontext.patch
Maintainer:  @miska
Description:
The asynchronous API of libmariadb uses cooperative multi threading by using the system calls
* makecontext
* swapcontext
* getcontext
* setcontext of the ucontext.h C-API.
Thus additionally link libmariadb to libucontext which is an library providing these system calls on platforms not supporting them out of the box - like musl based platforms.
Compile tested on:
- aarch64_cortex-a53
- aarch64_cortex-a72
- aarch64_generic
- arm_arm926ej-s
- arm_cortex-a15_neon-vfpv4
- arm_cortex-a7
- arm_cortex-a7_neon-vfpv4
- arm_cortex-a7_vfpv4
- arm_cortex-a9
- arm_cortex-a9_neon
- arm_cortex-a9_vfpv3-d16
- arm_fa526
- arm_mpcore
- arm_xscale
- i386_pentium-mmx
- mips_24kc
- mips64_octeonplus
- mipsel_24kc
- mipsel_24kc_24kf
- mipsel_74kc
- mipsel_mips32
- mips_mips32 …
> libmariadb: Fix async API by linking to libucontext

- net/transmission/Makefile
If a firmware build with curl without mbedtls, transmission installed from openwrt official repo will fail to start
Maintainer: Daniel Golle <daniel@makrotopia.org>
Description:
For example, a firmware build with curl with libopenssl, and firmware build without libmbedtls, install transmission from openwrt official repo, then transmission will fail to start.
> transmission: fix depends on libmbedtls

- net/samba4/Makefile
Maintainer: @Gingernut1978
Description:
Fixes various security issues. For detailed history see:
* https://www.samba.org/samba/history/samba-4.18.6.html
* https://www.samba.org/samba/history/samba-4.18.5.html
* https://www.samba.org/samba/history/samba-4.18.4.html
* https://www.samba.org/samba/history/samba-4.18.3.html
* https://www.samba.org/samba/history/samba-4.18.2.html
* https://www.samba.org/samba/history/samba-4.18.1.html
> [23.05] samba4: update to 4.18.6

- net/samba4/Makefile
Maintainer: @Gingernut1978
Description:
Fixes various security issues. For detailed history see:
* https://www.samba.org/samba/history/samba-4.18.6.html
* https://www.samba.org/samba/history/samba-4.18.5.html
* https://www.samba.org/samba/history/samba-4.18.4.html
* https://www.samba.org/samba/history/samba-4.18.3.html
* https://www.samba.org/samba/history/samba-4.18.2.html
* https://www.samba.org/samba/history/samba-4.18.1.html
Related to #22156 and #22157
> samba4: update to 4.18.6

- multimedia/ffmpeg/Makefile
- multimedia/ffmpeg/patches/060-fix-assembling-with-binutils-2.41.patch
fix addresses issue when building ffmpeg with binutils v2.41 that is documented [here](https://trac.ffmpeg.org/ticket/10405)
Fixes: #22170
Remarks:
Patch is merged to ffmpeg upstream and will be included in next release of ffmpeg, so patch applies only to current version and is removed when package is updated to next version of ffmpeg.
Upstream patch refreshed.
> ffmpeg: fix assembling with binutils v2.41

- net/crowdsec/Makefile
Update crowdsec to latest upstream release version 1.5.4
Build tested: package build checked, no run test due to limited space
Description: update to latest version of upstream
(cherry picked from commit 7528bf76821eb9234d4665752371c85496ca5b89)
> [22.03] crowdsec: new upstream release version 1.5.4

- net/crowdsec/Makefile
Update crowdsec to latest upstream release version 1.5.4
Build tested: package build checked, no run test due to limited space
Description: update to latest version of upstream
(cherry picked from commit 7528bf76821eb9234d4665752371c85496ca5b89)
> [23.05] crowdsec: new upstream release version 1.5.4

- net/zerotier/Makefile
see changelog: https://github.com/zerotier/ZeroTierOne/releases/tag/1.12.2.
Signed-off-by: Leo Douglas <douglarek@gmail.com>
(cherry picked from commit 0343dffefa2b1b5dbd731516ed0a9431d6ed4cae)
Maintainer: @mwarning
Description:
> [23.05] zerotier: update to 1.12.2

- lang/luajit/Makefile
- lang/luajit2/Makefile
- net/dnsdist/Makefile
- net/knot-resolver/Makefile
- net/nginx/Makefile
- net/snort/Makefile
- net/snort3/Makefile
Add HAS_LUAJIT_ARCH dependency to any user of luajit to fix circular
dependency limitation.
Fixes: https://github.com/openwrt/packages/issues/22192
> treewide: add HAS_LUAJIT_ARCH dependency to luajit user

- net/nginx-util/Makefile
- net/nginx-util/src/CMakeLists.txt
- net/nginx-util/src/regex-pcre.hpp
Convert to pcre2 library as pcre is EOL. No functional change intended.
@peter-stadler Can you check this? Not strictly pcre2 usage but at least c++ format :D
> nginx-util: move to pcre2

- net/iperf3/Makefile
see changelog: https://github.com/esnet/iperf/releases/tag/3.15.
Signed-off-by: Leo Douglas <douglarek@gmail.com>
(cherry picked from commit 8a223d4724d996db13bc8077035b27562b5e8fbd)
Description:
> [23.05] iperf3: update to 3.15

- net/modemmanager/Makefile
- net/modemmanager/files/modemmanager.common
Maintainer: @mips171 , @aleksander0m
Compile tested: x86_64, APU3, latest openwrt master
Run tested: x86_64, APU3, latest openwrt master, test done = yes
Description:
Modified the code to correctly determine modem availability based on the sysfs path provided in the 'device' option, instead of relying  on the 'proto' value. This ensures proper configuration for custom-made protos that do not match the "modemmanager" identifier.
> modemmanager: Remove hardcoded proto check

- net/openvswitch/Makefile
Compile tested: x86-64, OpenWrt master (d1521889066ce9698187ae56111cf591b09c10c5)
Run tested: Not run tested. This is a build fix that does not affect runtime.
Description:
The openvswitch build trips over a number of warnings during the manpage-check step if groff 1.23 is installed on the build host, resulting in a failed build.
As this check is optional, and we don't even install the manpages, simply override the groff configure check to never detect groff.
Supersedes #22161, as it turned out that several additional patches would've been necessary to make the groff check pass depending on the build host distro.
Closes #21991
> openvswitch: disable groff manpage check

- net/snort3/Makefile
```
o"  )~   Version 3.1.71.0
Using DAQ version 3.0.12
Using OpenSSL 3.0.11 19 Sep 2023
Using ZLIB version 1.2.13
Using Hyperscan version 5.4.2 2023-09-23
```
> snort3: update to 3.1.71.0

- libs/libwebp/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/ff95f859ebf710d2914472a3feeeb0d187d14459
Run tested:x86 https://github.com/openwrt/openwrt/commit/ff95f859ebf710d2914472a3feeeb0d187d14459
-----------------------------------------------------------_
From https://github.com/webmproject/libwebp/releases/tag/v1.3.2
- 9/13/2023: version 1.3.2 This is a binary compatible release.
* security fix for lossless decoder (chromium: #1479274, CVE-2023-4863)
> libwebp: bump to version 1.3.2

- net/tailscale/Makefile
Run tested: `aarch64_cortex-a53` @ SNAPSHOT
> tailscale: Update to 1.50.0

- net/bind/Makefile
CVE fixes:
CVE-2023-3341 - Previously, sending a specially crafted message over the control channel could cause the packet-parsing code to run out of available stack memory, causing named to terminate unexpectedly.
CVE-2023-4236 - A flaw in the networking code handling DNS-over-TLS queries could cause named to terminate unexpectedly due to an assertion failure under significant DNS-over-TLS query load.
Maintainer: me
Run tested: mvebu, openwrt 22.03. DNS secondary/slave service, DNSSEC, recursive validation, etc.
Description:
See https://ftp.isc.org/isc/bind9/cur/9.18/doc/arm/html/notes.html for the complete upstream changelog.
> bind: bump to 9.18.19

- net/stunnel/Makefile
Maintainer: me
Compile tested: x86_64 and lantiq_xrx200,
Run tested: x86_64, start without config
Description:
update version to 5.71
```
root@G3-10940 /root# stunnel
[ ] Initializing inetd mode confiroot@G3-10940 /sys/class/leds/khan:red:led8 # stunnel
[.] stunnel 5.71 on x86_64-openwrt-linux-gnu platform
[.] Compiled/running with OpenSSL 3.0.11 19 Sep 2023
[.] Reading configuration from file /etc/stunnel/stunnel.conf
[.] UTF-8 byte order mark not detected
[.] FIPS mode disabled
[ ] No PRNG seeding was required
[ ] Initializing service [dummy]
[ ] Initializing context [dummy]
[ ] …
```
> stunnel: update version to 5.71

- lang/python/python-bidict/Makefile
Compile tested: none (cherry picked from #22151)
Description:
The package no longer has a build dependency on setuptools-scm.
(cherry picked from commit 04344131087473289f0d9cfff0ffb196ac3376bd)
> [openwrt-23.05] python-bidict: Update to 0.22.1

- lang/python/python-typing-extensions/Makefile
- lang/python/python-typing-extensions/test.sh
Compile tested: armsr-armv7, 2023-09-24 snapshot sdk
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-09-24 snapshot
Description:
> python-typing-extensions: Update to 4.8.0

- lang/python/python-networkx/Makefile
Compile tested: none (cherry picked from #22153)
Description:
This renames the source package to python-networkx to match other Python packages.
(cherry picked from commit 77cebb0d0391e7f6f8594a4b046beac702124609)
> [openwrt-23.05] python3-networkx: Update to 3.1, rename source package

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Run tested:  x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, test downloads
Description:
* also nicer file type output in high verbosity
> adblock-fast: better error reporting when nothing to do

- net/net-snmp/Makefile
- net/net-snmp/patches/200-add-pcre2-support.patch
- net/net-snmp/patches/201-Run-autoreconf.patch
- net/net-snmp/patches/202-Improve-pcre2-support.patch
Add upstream patch adding support for pcre2 and update dependency to require libpcre2 instead of libpcre.
--without-pcre is now needed to exclude support for pcre and only require pcre2.
> net-snmp: move to PCRE2 library

- mail/exim/Makefile
- mail/exim/patches/000-preliminary-fixes-for-ZDI-vulns.patch
Maintainer: me
Run tested: -
Description:
Apply preliminary hotfix for some (three?) of the 0-day vulnerabilities reported by ZDI.
> exim: apply hotfix for some ZDI reported vulnerabilities

- utils/crun/Makefile
changelog 1.9.2:
- cgroup: reset the inherited cpu affinity after moving to cgroup. Old kernels do that automatically, but new kernels remember the affinity that was set before the cgroup move, so we need to reset it in order to honor the cpuset configuration.
changelog 1.9.1:
- utils: ignore ENOTSUP when chmod a symlink. It fixes a problem on Linux 6.6 that always refuses chmod on a symlink.
- build: fix build on CentOS 7
- linux: add new fallback when mount fails with EBUSY, so that there is not an additional tmpfs mount if not needed.
- utils: improve error message when a directory cannot be created as a component of the path is already existing as a non directory.
Maintainer: me
> crun: update to 1.9.2

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.0.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.0.0
> lua-eco: update to 3.0.0

- net/netavark/Makefile
changelog:
- iptables: improve error when ip6?tables commands are missing
- docs: Convert markdown with go-md2man instead of mandown
- iptables: drop invalid packages
- bump rust edition to 2021
- Add ACCEPT rules in firewall for bridge network with internal dns
- Add vrf support for bridges
> netavark: update to 1.8.0

- lang/python/python-typing-extensions/Makefile
- lang/python/python-typing-extensions/test.sh
Compile tested: none (cherry picked from #22214)
Description:
(cherry picked from commit cb8648679b01982131eda7b2e74aff02f9a7499e)
> [openwrt-23.05] python-typing-extensions: Update to 4.8.0

- utils/prometheus-node-exporter-lua/Makefile
Compile and run tested: NO
Description:
In the OpenWrt routing feed, package bmx6 and luci-app-bmx6 were removed because the LuCI app was vulnerable to several CVEs, as found by dependabot. It has been reporting it for a few months and has even created an issue. These two packages are not maintained in OpenWrt as well in upstream.
Users should switch to the bmx7 package.
Fixes: 9fb9d9343ea27d6dbb5008ece10c0c843dd2c781 ("bmx6: drop package") in the routing feed
See: https://github.com/openwrt/routing/pull/1021
> prometheus-node-exporter-lua: drop bmx6 package

- libs/libwebp/Makefile
- libs/libwebp/patches/010-mips16.patch
Maintainer: me
From https://github.com/webmproject/libwebp/releases/tag/v1.3.2
- 9/13/2023: version 1.3.2 This is a binary compatible release.
* security fix for lossless decoder (chromium: #1479274, CVE-2023-4863)
(cherry picked from commit 90c6cb239002b1581b249ed19c3d7475fa78e5f1)
> [23.05] libwebp: bump to version 1.3.2

- lang/python/python-cffi/Makefile
- lang/python/python-cffi/patches/001-unpin-setuptools.patch
- lang/python/python-cffi/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-10-03 snapshot sdk
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-10-03 snapshot
Description:
This includes a patch to unpin the version of setuptools required for build; the required version is newer than the version bundled with Python 3.11. This patch should not be necessary when Python 3.12 is available.
> python-cffi: Update to 1.16.0

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, start/dl/stop
Description:
* improve processing of dnsmasq config files
* do not run sed/show error if allow_filter is empty
(cherry picked from commit 0dc2aa2e7d67b6b4bce3d3bae9b14e67b90ff0c1)
> [23.05] adblock-fast: update to 1.0.0-5

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc2, start/dl/stop
Description:
* improve processing of dnsmasq config files
* do not run sed/show error if allow_filter is empty
> adblock-fast: update to 1.0.0-5

- multimedia/ffmpeg/Config.in
- multimedia/ffmpeg/Makefile
Otherwise one cannot produce *.avi containers needed for some H.264 camera codecs.
Maintainer: @graysky2 
Compile tested: default arch, v22.03.5
Run tested: openwrt-22.03.5-ramips-mt7621-zbtlink_zbt-wg3526-32m
Description:
I did not copy-paste the message but it will complain `-f avi` cannot produce AVI.
> ffmpeg: Add avi muxer

- lang/python/python-cffi/Makefile
- lang/python/python-cffi/patches/001-unpin-setuptools.patch
- lang/python/python-cffi/test.sh
Maintainer: me
Compile tested: none (cherry picked from #22283)
Description:
This includes a patch to unpin the version of setuptools required for build; the required version is newer than the version bundled with Python 3.11. This patch should not be necessary when Python 3.12 is available.
(cherry picked from commit dd5af62695e2c0fcf421adfffbea92f37d1a652d)
> [openwrt-23.05] python-cffi: Update to 1.16.0

- admin/syslog-ng/Makefile
- admin/syslog-ng/files/syslog-ng.conf
Maintainer: me
Compile tested: MacBook A1990, Sonoma 14.0 for Turris Omnia router
Run tested: Turris Omnia, mvebu/cortexa9, OpenWrt 22.03
Description:
- Release notes:
https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-4.4.0
- Bump config file
> syslog-ng: update to version 4.4.0

- net/knot/Makefile
Maintainer: @salzmdan @Payne-X6
Compiled on: MacBook A1990, Sonoma 14.0
Run tested: Turris 1.1, powerpc_8540, Turris OS 6.4.1 (based on OpenWrt 21.02)
Release notes:
https://www.knot-dns.cz/2023-09-10-version-3210.html
https://www.knot-dns.cz/2023-07-27-version-329.html
https://www.knot-dns.cz/2023-06-26-version-328.html
https://www.knot-dns.cz/2023-06-06-version-327.html
> [21.02] Knot DNS: update to version 3.2.10

- multimedia/ffmpeg/Makefile
Fixes: #12320
Maintainer: @graysky2
Compile tested: default arch, v22.03.5
Run tested: openwrt-22.03.5-ramips-mt7621-zbtlink_zbt-wg3526-32m
Description:
After plain enable of libffmpeg-custom and ffmpeg-custom which adds:
- CONFIG_PACKAGE_libbz2=m
- CONFIG_PACKAGE_libffmpeg-custom=m
- CONFIG_FFMPEG_CUSTOM_GPL=y
- CONFIG_PACKAGE_zlib=m
- CONFIG_PACKAGE_ffmpeg-custom=m
I get on v22.03.5 compilation error:
```
cp -fpR /.../openwrt-git/build_dir/target-mips_24kc_musl/ffmpeg-custom/ffmpeg-5.1/ipkg-install/usr/bin/ffmpeg /.../openwrt-git/build_dir/target-mips_24kc_musl/ffmpeg-custom/ffmpeg-5.1/ipkg-mips_24kc/ffmpeg-custom/usr/bin/
cp: cannot stat '/.../openwrt-git/build_dir/target-mips_24kc_musl/ffmpeg-custom/ffmpeg-5.1/ipkg-install/usr/bin/ffmpeg': No such file or directory
make[2]: *** …
```
> ffmpeg: fix compilation error of ffmpeg-custom

- lang/python/python-twisted/Makefile
- lang/python/python-twisted/patches/001-omit-tkconch.patch
- lang/python/python-twisted/patches/002-omit-tests.patch
- lang/python/python-twisted/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-10-03 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-10-03 snapshot
Description:
> python-twisted: Update to 23.8.0, rework patches

- net/openssh/Makefile
Chanelog: https://www.openssh.com/txt/release-9.5
> openssh: bump to 9.5p1

- net/crowdsec-firewall-bouncer/Makefile
Update crowdsec-firewall-bouncer to latest upstream release version 0.0.28
Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.0-rc3
> crowdsec-firewall-bouncer: new upstream release version 0.0.28

- net/keepalived/Makefile
- net/keepalived/files/keepalived.init
Maintainer: me
Compile tested: x86_64, APU3, master
Run tested: x86_64, APU3, only `keepalived --version`
Description:
- Update to version 2.2.8 See release-notes https://www.keepalived.org/release-notes/Release-2.2.8.html
- Add PING_CHECK config via uci for real server
- Add notify_up and notify_down handling for virtual server
```
root@G3-10940 ~ # keepalived --version
Keepalived v2.2.8 (04/04,2023), git commit v2.2.7-154-g292b299e+
Copyright(C) 2001-2023 Alexandre Cassen, <acassen@gmail.com>
Built with kernel headers for Linux 5.15.132
Running on Linux 5.15.132 #0 SMP Mon Sep 25 13:22:59 2023
Distro: APOS master-Poochie-16-ga5d38f732
configure options: --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --disable-dependency-tracking --program-prefix= …
```
> keepalived: update to version 2.2.8

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc4
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc4
Description:
* escape dots in grep command to properly identify hosts files
> adblock-fast: bugfix: properly identify hosts-files

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc4
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.0-rc4
Description:
* escape dots in grep command to properly identify hosts files
(cherry picked from commit 13a88d0b79142f385d77baaa390211673bf6b9c0)
> [23.05] adblock-fast: bugfix: properly identify hosts-files

- net/crowdsec-firewall-bouncer/Makefile
Update crowdsec-firewall-bouncer to latest upstream release version 0.0.28
Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.0-rc4
(cherry picked from commit 401d242)
> [22.03] crowdsec-firewall-bouncer: new upstream release version 0.0.28

- net/crowdsec-firewall-bouncer/Makefile
Update crowdsec-firewall-bouncer to latest upstream release version 0.0.28
Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.0-rc4
(cherry picked from commit https://github.com/openwrt/packages/commit/401d242)
> [23.05] crowdsec-firewall-bouncer: new upstream release version 0.0.28

- libs/libvpx/Makefile
v1.13.0
This release includes more Neon and AVX2 optimizations, adds a new codec control to set per frame QP, upgrades GoogleTest to v1.12.1, and includes numerous bug fixes.
v1.13.1
This release contains two security related fixes. One each for VP8 and VP9.
- https://crbug.com/1486441 (CVE-2023-5217)
- Fix bug with smaller width bigger size (CVE-2023-44488)
Fixes #22318
Maintainer: me
Compile tested: ath79_generic,mediatek_filogic,x86_64
```
root@OpenWrt:~# opkg update
root@OpenWrt:~# opkg install /tmp/libvpx*.ipk /tmp/gst1-mod-vpx*.ipk
root@OpenWrt:~# opkg install gstreamer1-utils gst1-mod-vpx gst1-mod-videotestsrc gst1-mod-matroska gst1-mod-hls uhttpd
root@OpenWrt:~# /etc/init.d/uhttpd start
root@OpenWrt:~# cd /www && gst-launch-1.0 videotestsrc is-live=true ! vp8enc …
```
> libvpx: update to 1.13.1

- lang/python/python-twisted/Makefile
- lang/python/python-twisted/patches/001-omit-tkconch.patch
- lang/python/python-twisted/patches/002-omit-tests.patch
- lang/python/python-twisted/test.sh
Maintainer: me
Compile tested: none (cherry picked from #22291)
Description:
(cherry picked from commit 00841f98731fe7599c7f2cae2bf4e08599833647)
> [openwrt-23.05] python-twisted: Update to 23.8.0, rework patches

- net/sshtunnel/Makefile
- net/sshtunnel/files/sshtunnel.init
- net/sshtunnel/files/uci_sshtunnel
**Maintainer:** @nunojpg
**Compile tested:** OpenWrt 23
**Run tested:** tested in VirtualBox and Turris
This is the same PR as was in the #21263. 
I just removed the branch accidentally and now have to recreate the PR.
The only difference is that I changed dependency line: now it will depend ether on dbclient or openssh-client.
I copied the depends line from pppossh package but improved it to be more precise and depend on the dbclient and not just on the dropbear package.
The PR also contains update for the pppossh with the same depends change so @yousong please have a look.
> sshtunnel: support Dropbear

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.0.1: https://github.com/zhaojh329/lua-eco/releases/tag/v3.0.1
> lua-eco: update to 3.0.1

- net/lighttpd/Makefile
- net/lighttpd/patches/020-meson-mod_webdav_min.patch
Description:
* update to lighttpd 1.4.72 release hash
> lighttpd: update to lighttpd 1.4.72 release hash

- net/esp2net/Makefile
- net/esp2net/files/esp2net.config
- net/esp2net/files/esp2net.init
Maintainer: me
Run tested: ATH79, TP-Link TL-WDR3600, master
Description: Espressif ESP chip network monitor and flash proxy
> esp2net: add Espressif ESP chip USB-Network proxy

- net/sing-box/Makefile
* Enable `with_ech` ~~and `with_dhcp`~~, just like upstream
* See changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.5.2
Description:
> sing-box: update to v1.5.2

- net/tailscale/Makefile
Run tested: `aarch64_cortex-a53` @ SNAPSHOT
> tailscale: Update to 1.50.1

- net/v2ray-geodata/Makefile
"Iran Hosted Domains" is a comprehensive list of Iranian domains and services that are hosted within the country.
Compile tested: (x86,mediatek,ath79, 22.03.5,23.05.0-rc4, snapshot)
Run tested: (x86,mediatek,ath79, 22.03.5,23.05.0-rc4, snapshot)
Description:
"Iran Hosted Domains" is a comprehensive list of Iranian domains and services that are hosted within the country and and work similarly to the present geosite list.
usage: ext:iran.dat:ir
More info : https://github.com/bootmortis/iran-hosted-domains/
> v2ray-geodata: add package v2ray-geosite-ir

- net/pppossh/Makefile
Compile tested: OpenWrt 23
Run tested: tested in VirtualBox and Turris
Description: The package should not only depend on a package dropbear but on the dbclient. Otherwise the dbclient may be disabled during compilation and the dependency will be not satisfied.
Same I did in the #22159
> pppossh: depend on dbclient

- utils/procs/Makefile
- utils/procs/files/etc/procs/procs.toml
Compile tested: x86_64, container image: docker.io/openwrt/sdk:latest (4c7b0adaed32)
Run tested: x86_64, Vm Openwrt 22.03.5
Description:
Procs is a modern, feature-rich alternative to the 'ps' command written in Rust
> procs: Add new package

- net/librespeed-go/Makefile
- net/librespeed-go/files/librespeed-go.init
Maintainer: Tianling Shen cnsztl@immortalwrt.org @1715173329 
Compile tested: x86_64, x86/64, 22.03.5
Run tested: x86_64, x86/64, 22.03.5
Description:
Make the daemon reload after the tls certificate is updated
> librespeed-go: Reload the daemon after modifying the tls certificate

- net/sing-box/Makefile
* Enable `with_ech` and `with_dhcp`, just like upstream
* See changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.5.2
Signed-off-by: Leo Douglas <douglarek@gmail.com>
sing-box: ShadowsocksR is marked as deprecated since v1.5.0
Signed-off-by: Leo Douglas <douglarek@gmail.com>
sing-box: remove dhcp by default
Signed-off-by: Leo Douglas <douglarek@gmail.com>
(cherry picked from commit bf7ce353b8af9a36411525306abcde23e860e76d)
Description:
> [openwrt-23.05] sing-box: update to v1.5.2

- net/samba4/Makefile
Description:
Update to the latest stable version in 4.18 series, for details, see https://www.samba.org/samba/history/samba-4.18.7.html
> samba4: Update to version 4.18.7

- lang/python/python-zope-interface/Makefile
- lang/python/python-zope-interface/patches/001-omit-tests.patch
- lang/python/python-zope-interface/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-10-07 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-10-07 snapshot
Description:
This also updates the list of dependencies and adds a test.sh script for the packages feed CI.
> python-zope-interface: Update to 6.1, refresh patch

- net/curl/Makefile
Compile tested: mvebu, Turris Omnia, Turris OS 6 = OpenWrt 21.02
Run tested: mvebu, Turris Omnia, Turris OS 6 = OpenWrt 21.02, can download a website
Description:
For detailed changes, see https://curl.se/changes.html#8_4_0
Switching to tar.bz2 for the time being as tar.xz is not yet available.
> curl: Update to version 8.4.0

- net/curl/Makefile
Compile tested: mvebu, Turris Omnia, Turris OS 6 = OpenWrt 21.02
Run tested: mvebu, Turris Omnia, Turris OS 6 = OpenWrt 21.02, can download a website
Description:
For detailed changes, see https://curl.se/changes.html#8_4_0
Switching to tar.bz2 for the time being as tar.xz is not yet available.
Fixes CVE-2023-38546 and CVE-2023-38545.
Backport of #22365
> [23.05] curl: Update to version 8.4.0

- net/curl/Makefile
Compile tested: mvebu, Turris Omnia, Turris OS 6 = OpenWrt 21.02
Run tested: mvebu, Turris Omnia, Turris OS 6 = OpenWrt 21.02, can download a website
Description:
For detailed changes, see https://curl.se/changes.html#8_4_0
Switching to tar.bz2 for the time being as tar.xz is not yet available.
Fixes CVE-2023-38546 and CVE-2023-38545.
Backport of https://github.com/openwrt/packages/pull/22365
> [22.03] curl: Update to version 8.4.0

- utils/zsh/Makefile
- utils/zsh/patches/001-50658-test-Enable-to-switch-between-C-UTF-8-locales-.patch
- utils/zsh/patches/002-51723-migrate-pcre-module-to-pcre2.patch
- utils/zsh/patches/003-51728-assign-pcre-named-capture-groups-to-a-hash.patch
- utils/zsh/patches/004-51738-support-pcre-s-alternative-DFA-matching-algori.patch
- utils/zsh/patches/005-51877-do-not-build-pcre-module-if-pcre2-config-is-no.patch
Changes:
- use libpcre2 instead of libpcre
- patch Src/Modules/pcre.c: source from mainstream's git (23.9.2023)
- patch configure.ac and config.h.in: replace libpcre with libpcre2 and remove missing AC_PROG_LN
- patch Src/Makefile.in: use LN_S instead of LN
- patch Test/V07pcre.ztst: add some libpcre2 specific tests
- use autoconf: git version no longer supports traditional configure script, so it was easier to patch configure.ac
Maintainer: @msva
Description:
zsh is my favourite shell. I found issue #22006 which mentioned zsh and that's where idea originated.
Patch can be removed when official zsh is next time updated (might take quite some time)
> zsh: use libpcre2 instead of libpcre

- utils/catatonit/Makefile
no functional changes from catatonit 0.1.7, but license change from GPL-3.0-or-later to GPL-2.0-or-later.
Switch package source to release version from git commit version.
Maintainer: me
> catatonit: update to 0.2.0

- lang/python/python-websocket-client/Makefile
Maintainer: me
Description:
- 1.6.4
- Add support for HTTP 307 and 308 redirect codes
- 1.6.3
- Fix type hints issues
- Add support for Python beta release 3.12 in CI
- Add maintainer email in setup.py
> python-websocket-client: update to 1.6.4

- lang/node/Makefile
Description:
Update to v18.18.1
This release addresses some regressions that appeared in Node.js 18.18.0:
-  (Windows) FS can not handle certain characters in file name nodejs/node#48673
-  18 and 20 node images give error - Text file busy (after re-build images) nodejs/docker-node#1968
-  libuv update in 18.18.0 breaks webpack's thread-loader nodejs/node#49911
> node: bump to v18.18.1

- lang/rust/Makefile
- lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
- lang/rust/patches/0002-rustc-bootstrap-cache.patch
- lang/rust/patches/0003-bump-libc-deps-to-0.2.146.patch
changelog at https://github.com/rust-lang/rust/releases/tag/1.73.0
> rust: update to 1.73.0

- utils/conmon/Makefile
Backport conmon update 2.1.8 to openwrt 23.05
Maintainer: me
> [openwrt-23.05] conmon: update to 2.1.8

- utils/crun/Makefile
crun backport update to version 1.9.2
I have received several issue reports on difficulties and problems with podman containers with _stable_ release version of openwrt. So I am backporting up to date versions to be able help solve these issues.
Maintainer: me
> [openwrt-23.05] crun: update to 1.9.2

- utils/slirp4netns/Makefile
backport slirp4netns update 1.2.2 for openwrt-23.05
Maintainer: me
> [openwrt-23.05] slirp4netns: update to 1.2.2

- net/netavark/Makefile
backport netavark 1.8.0 update to openwrt-23.05
Maintainer: me
> [openwrt-23.05] netavark: update to 1.8.0

- net/aardvark-dns/Makefile
backport update aardvark-dns to 1.8.0 for openwrt-23.05
Maintainer: me
> [openwrt-23.05] aardvark-dns: update to 1.8.0

- utils/podman/Makefile
backport update podman to 4.7.1 for openwrt-23.05
differences to development tree: musl-1.2.4 patch not included, because it's not used in openwrt-23.05
Maintainer: me
> [openwrt-23.05] podman: update to 4.7.1

- net/cni-protocol/Makefile
- net/cni-protocol/files/cni.sh
backport update cni-protocol package to 20231008 for openwrt-23.05
Maintainer: me
> [openwrt-23.05] cni-protocol: update to 20231008

- lang/node/Makefile
 Compile tested: 23.05, aarch64, arm 
Description:
This release addresses some regressions that appeared in Node.js 18.18.0:
-  (Windows) FS can not handle certain characters in file name nodejs/node#48673
-  18 and 20 node images give error - Text file busy (after re-build images) nodejs/docker-node#1968
-  libuv update in 18.18.0 breaks webpack's thread-loader nodejs/node#49911
(cherry picked from commit b2079b87d1425f69feb89b8fa9f48f0a913e8fb2)
> [23.05] node: bump to v18.18.1

- utils/prometheus-node-exporter-lua/Makefile
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/thermal.lua
Maintainer: @dhewg @champtar @jpds @PolynomialDivision @mweinelt (committed `Makefile` within the last two years)
Compile tested: N/A (the script is not compiled)
Run tested: aarch64, Raspberry Pi 4 Model B,  OpenWrt 22.03.0, r19685-512e76967f;
- Say `opkg install prometheus-node-exporter-lua` (plus some more exporters)
- Install the `thermal.lua` script in the `/usr/lib/lua/prometheus-collectors` directory
- Say `/etc/init.d/prometheus-node-exporter-lua restart`
- Manually inspect exported metrics with `wget -O- -4 http://localhost:9100/metrics`:
```
node_thermal_temp{thermal_zone="0"} 50.147
node_scrape_collector_duration_seconds{collector="thermal"} 0.00015020370483398
node_scrape_collector_success{collector="thermal"} 1
```
Description:
This was the most straightforward way I could …
> prometheus-node-exporter-lua: Add thermal collector

- lang/python/python-maturin/Makefile
Compile tested: armsr-armv7, 2023-10-07 snapshot sdk
Description:
Python packages that use maturin to build do not call the maturin program directly; they use the [maturin build backend][1]. This build backend is a Python library provided with maturin that interfaces with the maturin program.
This changes the maturin package to use the Python build process so that the build backend is installed correctly.
This also renames the source package to python-maturin and moves it into the lang/python directory.
[1]: https://www.maturin.rs/#source-distribution
> maturin: Update to 1.3.0, build as Python (host-only) package

- net/openconnect/Makefile
- net/openconnect/files/openconnect.sh
Add support for the OpenConnect option `--pfs`.
Designed to require perfect forward secrecy.
> openconnect: add support for option --pfs

- utils/prometheus-node-exporter-ucode/Makefile
- utils/prometheus-node-exporter-ucode/files/base/conntrack.uc
- utils/prometheus-node-exporter-ucode/files/base/cpu.uc
- utils/prometheus-node-exporter-ucode/files/base/entropy.uc
- utils/prometheus-node-exporter-ucode/files/base/filefd.uc
- utils/prometheus-node-exporter-ucode/files/base/loadavg.uc
- utils/prometheus-node-exporter-ucode/files/base/meminfo.uc
- utils/prometheus-node-exporter-ucode/files/base/netclass.uc
- utils/prometheus-node-exporter-ucode/files/base/netdev.uc
- utils/prometheus-node-exporter-ucode/files/base/selinux.uc
- utils/prometheus-node-exporter-ucode/files/base/time.uc
- utils/prometheus-node-exporter-ucode/files/base/uname.uc
- utils/prometheus-node-exporter-ucode/files/config
- utils/prometheus-node-exporter-ucode/files/extra/dnsmasq.uc
- utils/prometheus-node-exporter-ucode/files/extra/ltq-dsl.uc
- utils/prometheus-node-exporter-ucode/files/extra/netstat.uc
- utils/prometheus-node-exporter-ucode/files/extra/openwrt.uc
- utils/prometheus-node-exporter-ucode/files/extra/snmp6.uc
- utils/prometheus-node-exporter-ucode/files/extra/uci_dhcp_host.uc
- utils/prometheus-node-exporter-ucode/files/extra/wifi.uc
- utils/prometheus-node-exporter-ucode/files/extra/wireguard.uc
- utils/prometheus-node-exporter-ucode/files/init
- utils/prometheus-node-exporter-ucode/files/metrics.uc
- utils/prometheus-node-exporter-ucode/files/run.sh
- utils/prometheus-node-exporter-ucode/test.sh
- utils/rpcd-mod-wireguard/Makefile
- utils/rpcd-mod-wireguard/src/CMakeLists.txt
- utils/rpcd-mod-wireguard/src/api.c
- utils/rpcd-mod-wireguard/src/wireguard.c
- utils/rpcd-mod-wireguard/src/wireguard.h
This is a port of `prometheus-node-exporter-lua` to ucode.
It's in it's early stages, hence the draft status.
It includes all the collectors from the base package of its lua counterpart.
The only additional ones are `openwrt` and `ltq-dsl` at this point. I might port some more, but certainly not all of them since I don't use some.
Feedback very welcome :)
Notes:
Support for `# HELP` lines, but not yet used.
`# HELP` and `# TYPE` lines only get printed once, just before the first metric (solves e.g. #19508).
No issue, just an observation: the labels are in order as specified. Lua reorders. e.g.:
lua:
`node_openwrt_info{revision,target,board_name,id,model,release,system} 1`
ucode:
`node_openwrt_info{board_name,id,model,release,revision,system,target} 1`
The netclass collector uses all …
> prometheus-node-exporter-ucode: add new package

- lang/python/python-zope-interface/Makefile
- lang/python/python-zope-interface/patches/001-omit-tests.patch
- lang/python/python-zope-interface/test.sh
Maintainer: me
Compile tested: none (cherry picked from #22344)
Description:
This also updates the list of dependencies and adds a test.sh script for the packages feed CI.
(cherry picked from commit 7e8f7b28d74ca2044309dff9c789dec055ee43c5)
> [openwrt-23.05] python-zope-interface: Update to 6.1, refresh patch

- lang/rust/rust-values.mk
Compile tested: NXP i.MX6 Cortex-A9, master as of 66f6c20e45aa0eb2649d1e0552eab9e138e38601 and ac8ca9c86a4af19b24704cae7881094a09520e0e
Run tested: NXP i.MX6 Cortex-A9, master as of ac8ca9c86a4af19b24704cae7881094a09520e0e
Description:
Patch the target triple for Rust with glibc to include hard floating point support.
The GNU target triple used elsewhere does not include hard float support, instead `-mfloat-abi=hard` is passed separately. For Rust it must be included in the target triple. This was already being done for musl, this commit adds the same patching for glibc.
Without this patch Rust compilation fails with an error like this (abbreviated to fit the line length):
ld: error: libstd.so uses VFP register arguments, ... does not
ld: failed to merge target …
> rust: fix build with glibc, ARM and hard floats

- net/isc-dhcp/files/dhcpd.init
Maintainer: me
Run tested: no
Description:
With https://github.com/openwrt/openwrt/pull/12925, 'BROADCAST' will no longer be set if there is no local broadcast address (instead of setting the global broadcast address). Prepare for the merger but stay compatible with the old version of ipcalc.
> isc-dhcp: refuse to add empty DHCP ranges 

- net/samba4/Makefile
Description:
Mainly security release, fixing CVE-2023-3961, CVE-2023-4091, CVE-2023-4154, CVE-2023-42669 and CVE-2023-42670. For more details see: https://www.samba.org/samba/history/samba-4.18.8.html
> samba4: Update to version 4.18.8

- net/samba4/Makefile
Description:
Update to the latest stable version in 4.18 series, for details, see
https://www.samba.org/samba/history/samba-4.18.7.html
Backport of https://github.com/openwrt/packages/pull/22348
> [23.05] samba4: Update to version 4.18.7

- net/samba4/Makefile
Description:
Update to the latest stable version in 4.18 series, for details, see
* https://www.samba.org/samba/history/samba-4.18.7.html
* https://www.samba.org/samba/history/samba-4.18.6.html
* https://www.samba.org/samba/history/samba-4.18.5.html
* https://www.samba.org/samba/history/samba-4.18.4.html
* https://www.samba.org/samba/history/samba-4.18.3.html
* https://www.samba.org/samba/history/samba-4.18.2.html
* https://www.samba.org/samba/history/samba-4.18.1.html
Backport of #22348
> [22.03] samba4: Update to version 4.18.7

- utils/cudy-bdinfo/Makefile
Maintainer: me
Compile tested: mediatek-filogic / master
Run tested: mediatek-filogic / master / Cudy WR3000
Description:
This program can be used to obtain information stored on the bdinfo parition found on routers from Shenzhen Cudy Technology.
While this tool is not necessary for operation with OpenWrt, it can be helpful to decrypt information generated by the stock firmware as well as to obtain additional device-specific information.
> cudy-bdinfo: add package

- lang/node/Makefile
Description:
Update to v18.18.2
* CVE-2023-44487: nghttp2 Security Release (High) (Depends on shared library provided by OpenWrt)
* CVE-2023-45143: undici Security Release (High)
* CVE-2023-38552: Integrity checks according to policies can be circumvented (Medium)
* CVE-2023-39333: Code injection via WebAssembly export names (Low)
More detailed information on each of the vulnerabilities can be found in October 2023 Security Releases blog post.
> node: Friday October 13 2023 Security Releases

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/030-src-logging.c-fix-crash.patch
Maintainer: me
Description:
* finally fixes https://github.com/openwrt/packages/issues/19366
* simplify service_triggers
* improve output for dnsmasq restart
* improve grep/sed dependencies
* remove interface hotplug
> https-dns-proxy: bugfix: logging crashing instances on ath79

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/030-src-logging.c-fix-crash.patch
Maintainer: me
Description:
* finally fixes https://github.com/openwrt/packages/issues/19366
* simplify service_triggers
* improve output for dnsmasq restart
* improve grep/sed dependencies
* remove interface hotplug
(cherry picked from commit 38c026250f2bdae36fbd5bba6a9d529fb7082ed1)
> [22.03] https-dns-proxy: bugfix: logging crashing instances on ath79

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/030-src-logging.c-fix-crash.patch
Maintainer: me
Description:
* finally fixes https://github.com/openwrt/packages/issues/19366
* simplify service_triggers
* improve output for dnsmasq restart
* improve grep/sed dependencies
* remove interface hotplug
(cherry picked from commit 38c026250f2bdae36fbd5bba6a9d529fb7082ed1)
> [23.05] https-dns-proxy: bugfix: logging crashing instances on ath79

- lang/node/Makefile
Run tested: (qemu 8.1.2) aarch64
Description:
* CVE-2023-44487: nghttp2 Security Release (High) (Depends on shared library provided by OpenWrt)
* CVE-2023-45143: undici Security Release (High)
* CVE-2023-38552: Integrity checks according to policies can be circumvented (Medium)
* CVE-2023-39333: Code injection via WebAssembly export names (Low)
More detailed information on each of the vulnerabilities can be found in October 2023 Security Releases blog post.
(cherry picked from commit 9101a21e535d2247b3fb85e0660f7bb0dd4a4290)
> [23.05] node: Friday October 13 2023 Security Releases

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/share/ddns/default/ipnodns.ru.json
- net/ddns-scripts/files/usr/share/ddns/list
This is addition to #22237. I work directly from Chrome. Hope this online commit would be satisfactory. 
OS version: OpenWrt 23.05.0-rc4 r23482-7fe85ce1f2
ddns-scripts version 2.8.2-37
Subitted file has been working smoothly for about 2 weeks. Regards
Description:
> ddns-scripts: add new DDNS provider ipnodns.ru

- net/net-snmp/Makefile
- net/net-snmp/patches/203-if-mib-data_access-interface.c-plug-a-leak-with-pcre.patch
Backport patch fixing memory leak for PCRE2 present upstream.
Fixes: #22428
---
@stintel
> net-snmp: backport patch fixing memory leak for PCRE2

- net/conntrack-tools/Makefile
Release Notes:
https://marc.info/?l=netfilter&m=169598613909790&w=2
Furthermore, switch to "tar.xz".
Maintainer: @jow
> conntrack-tools: update to 1.4.8

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.23.0)
> docker-compose: Update to version 2.23.0

- utils/nerdctl/Makefile
contaiNERD CTL - Docker-compatible CLI for containerd,
with support for Compose, Rootless, eStargz, OCIcrypt, IPFS, ...
Compile tested: aarch64 23.05-rc4 and master
Run tested: bpi-r3
Description: First step for using directly containerd
> nerdctl: New package

- net/shadowsocks-libev/Makefile
- net/shadowsocks-libev/patches/100-Upgrade-PCRE-to-PCRE2.patch
Convert package to PCRE2 by porting a pending patch from a closed PR.
The PR is old but the code never changed and is simple enough to check the changes. The patch apply directly with no changes (aside from commenting out the travis CI file)
The PR was never merged as PCRE2 at times was too new and they were trying to find a better regex lib.
---
@BKPepe look what I found. If the stats are high enough, we can consider using this patch... the code is very little and use basic pcre API.
> shadowsocks-libev: convert to PCRE2

- lang/python/micropython-lib/Makefile
- lang/python/micropython-lib/patches/004-unix-ffi-re-convert-to-PCRE2.patch
Maintainer: Jeffery To <jeffery.to@gmail.com> @jefferyto 
Add pending patch (https://github.com/micropython/micropython-lib/pull/737) converting the package to PCRE2.
> micropython-lib: move to PCRE2

- net/conntrack-tools/Makefile
Release Notes:
https://marc.info/?l=netfilter&m=169598613909790&w=2
Furthermore, switch to "tar.xz".
(cherry picked from commit af666be21fac7ba06bd8bbd7d70c15cb60c1bd7c)
Maintainer: @jow
> [23.05] conntrack-tools: update to 1.4.8

- net/tor/Makefile
- net/tor/files/tor.init
procd requires init script name, not the path to executable
Signed-off-by: ValdikSS ValdikSS <iam@valdikss.org.ru>
Maintainer: @rsalvaterra
> tor: fix daemon reloading

- utils/stress-ng/Makefile
- utils/stress-ng/patches/002-core-stress-Add-musl-gcc-detection-and-HAVE_COMPILER.patch
- utils/stress-ng/test.sh
Maintainer: me
Compile tested: x86_64 https://github.com/openwrt/openwrt/commit/e66eed033f9f9d27fc839d81d3a03d4fad1b9b5b
With GCC 12 there is no issue.
With GCC 13, there is a compilation issue on x86_64. Fixes https://github.com/openwrt/packages/issues/22373
Fixes https://github.com/openwrt/packages/issues/22373
> stress-ng: backport immintrin.h header detection for GCC 13

- utils/acpica-unix/Makefile
Maintainer: @pprindeville 
Compile tested: x86_64, ---, OpenWrt master
Run tested: 
Description:
In order to build additional ACPI tables during the build process, this package needs to be build for the host system.
> acpica-unix: add host build

- multimedia/gst1-libav/Makefile
- multimedia/gst1-plugins-bad/Makefile
- multimedia/gst1-plugins-bad/patches/010-distutils.patch
- multimedia/gst1-plugins-base/Makefile
- multimedia/gst1-plugins-good/Makefile
- multimedia/gst1-plugins-good/patches/010-distutils.patch
- multimedia/gst1-plugins-ugly/Makefile
- multimedia/gstreamer1/Makefile
Compile tested: imx6
Run tested: imx6
Description:
This bumps all gstreamer components to 1.22.6
Incremental notes can be found [here](https://gstreamer.freedesktop.org/releases/1.22/#1.22.4)
> gstreamer: bump all parts to 1.22.6

- mail/exim/Makefile
- mail/exim/patches/100-localscan_dlopen.patch
Maintainer: me
Run tested: -
Description:
Fixes vulnerabilities:
- Improper Neutralization of Special Elements (CVE-2023-42117)
- dnsdb Out-Of-Bounds Read (CVE-2023-42119)
> exim: update to version 4.96.2

- net/transmission/Makefile
Update Transamission to 4.0.4 stable release
Changelog: https://github.com/transmission/transmission/releases/tag/4.0.4
Maintainer: Daniel Golle <daniel@makrotopia.org>
Compile tested: Mediatek Filogic on latest snapshot
Run tested: Mediatek Filogic on latest snapshot
> transmission: update to 4.0.4

- net/snowflake/Makefile
Release Notes:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/tags/v2.7.0
Run tested: mt7622
> snowflake: update to 2.7.0

- net/snowflake/Makefile
Release Notes:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/tags/v2.7.0
Proxy churn is removed and because of that also distinctcounter: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/6393af6bab0f7c3c95b11352d5c582d2000062fa
(cherry picked from commit 2496d74340e90b8a50ddb312c0841d26f52c4821)
Run tested: mt722
> [23.05] snowflake: update to 2.7.0

- libs/nghttp3/Makefile
Maintainer: me
Description:
* add new package to allow building of curl with HTTP/3 support
PS. I'd like to solicit feedback on cherry-picking it for 23.05 as well.
> nghttp3: add new package

- net/curl/Config.in
- net/curl/Makefile
Maintainer: me
Description:
* these changes along with 2 PRs below and using non-standard openssl library allow for building curl with HTTP/3 support
* https://github.com/openwrt/packages/pull/22443
* https://github.com/openwrt/packages/pull/22444
> curl: prepare for HTTP/3 support

- libs/ngtcp2/Makefile
Maintainer: me
Description:
* add new package to allow building of curl with HTTP/3 support
PS. I'd like to solicit feedback on cherry-picking it for 23.05 as well.
> ngtcp2: add new package

- libs/nghttp3/Makefile
Maintainer: me
Description:
* add new package to allow building of curl with HTTP/3 support
* switch to using cmake
(cherry picked from commit b1d4241cdf27dbf2ea4f2c78de6bbb3b7e876652)
> [23.05] nghttp3: add new package

- libs/ngtcp2/Makefile
Maintainer: me
Description:
* add new package to allow building of curl with HTTP/3 support
* switch to using cmake
(cherry picked from commit f6e57976402f51bd7b7bbe9dacad7153543b3002)
> [23.05] ngtcp2: add new package

- net/curl/Config.in
- net/curl/Makefile
Maintainer: me
Description:
* these changes along with 2 PRs below and using non-standard openssl library allow for building curl with HTTP/3 support
* https://github.com/openwrt/packages/pull/22443
* https://github.com/openwrt/packages/pull/22444
(cherry picked from commit 6bd2b89d839026c3365da7205359b1568f955e6b)
> [23.05] curl: prepare for HTTP/3 support

- net/modemmanager/Makefile
- net/modemmanager/files/modemmanager.common
Maintainer: @mips171. Please also have a look at this change @aleksander0m
Compile tested: x86_64, lantiq_xrx200 latest openwrt master
Run tested:  x86_64, lantiq_xrx200 latest openwrt master, test done = yes
On slower targets, it can happen that modems are not recognized correctly. During startup, the sysfs_cache is cleared, and then it waits for mmcli -L to complete. If a hotplug event occurs during this waiting time, the device attempts to report itself. However, the mmcli --report-kernel-event command fails, but it is still marked as "processed" in the sysfs cache. As a result, the modem is never further processed.
To address this issue, I propose two commits:
1. [remove sysfscache after dbus ready](https://github.com/openwrt/packages/commit/4125f74085dadc8bbc8a9133eda5246ab0a82d62) …
> Modemmanager fix race condition

- net/snort3/Makefile
Upstream bump
```
o"  )~   Version 3.1.73.0
Using DAQ version 3.0.12
Using OpenSSL 3.0.11 19 Sep 2023
Using Hyperscan version 5.4.2 2023-10-26
```
> snort3: update to 3.1.73.0

- net/restic-rest-server/Makefile
Maintainer: Tom Stöveken <tom@naaa.de>
Compile tested: Ubuntu 23.04 x64 / OpenWrt SNAPSHOT @ 6cf27094e9209250dbd45f8b042530c3b23f0a42
Run tested: Linksys WRT32X / OpenWrt SNAPSHOT r24002-e3559fb445
Description:
update to [0.12.1](https://github.com/restic/rest-server/compare/v0.11.0...v0.12.1)
cc: @Torxgewinde
> restic-rest-server: update to 0.12.1

- net/tor/Makefile
Bring our Tor up to the latest stable release.
Maintainer: @BKPepe, @hauke 
Run tested: mediatek/mt7622
> tor: update to the latest stable release (0.4.8.7)

- net/apinger/Makefile
- net/apinger/files/apinger.init
- net/apinger/files/apinger.rpc
fixed bug in init_apinger_config - debug/status_interval/rrd_interval were never set correctly
fixed bug in apinger_status - send and receive were swapped 
added ability top use ipv6 on wan6 (has to be fixed in luci-app-apinger as well)
Maintainer: @samm-git,  @hnyman, @jempatel
Compile tested: ARMv8 Processor rev 4, FriendlyElec NanoPi R4S, OpenWrt 22.03.3
Run tested: ARMv8 Processor rev 4, FriendlyElec NanoPi R4S, OpenWrt 22.03.3
Description: see above
> apinger: fixed bugs in apinger.init and apinger.rpc

- net/modemmanager/Makefile
- net/modemmanager/files/modemmanager.common
- net/modemmanager/files/modemmanager.init
- net/modemmanager/files/usr/sbin/ModemManager-wrapper
Maintainer: @mips171. Please also have a look at this change @aleksander0m
Compile tested: x86_64, lantiq_xrx200 latest openwrt master
Run tested: x86_64, lantiq_xrx200 latest openwrt master, test done = yes
There are situations where the cleanup of interfaces doesn't work as expected. For instance, when ModemManager crashes, cleanup is not triggered. Even if cleanup were to be triggered, the interfaces cannot be queried because the mmcli command is no longer available after a crash. To address this issue, I propose two commits:
1. [ improve cleanup of ifaces](https://github.com/openwrt/packages/commit/0d7a557462702617f73cb17b34aa2e2149ed3151)
2. [move iface cleanup to wrapper script](https://github.com/openwrt/packages/commit/c49aff8595dfaa765f8049dc59bee597eff64d56)
> modemmanager improve cleanup

- utils/qemu/Makefile
- utils/qemu/patches/0001-configure-allow-disable-fortify_source.patch
- utils/qemu/patches/0006-util-mmap-alloc-fix-missing-MAP_SYNC.patch
- utils/qemu/patches/0010-no-tests.patch
Compile tested: x86_64, OpenWrt master (https://github.com/openwrt/openwrt/commit/75aeb7ed627ba5ea6f10f365b232bed21e40b502)
Description:
Version updated to 8.1.2
> qemu: update to 8.1.2

- net/knot/Makefile
- net/knot/patches/03_libdnssec_pkcs11_support.patch
Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.4.4 (hbk)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 6.4.4 (hbk)
Description:
- Release upgrade (https://www.knot-dns.cz/2023-10-20-version-332.html)
> knot: update to version 3.3.2

- net/aircrack-ng/Makefile
- net/aircrack-ng/patches/104-build-add-option-to-disable-bsd-library-inclusion.patch
- net/aircrack-ng/patches/105-build-support-strlcat-strlcpy-from-musl-or-recent-gl.patch
Currently aircrack-ng try to link with libbsd if it does detect the library in staging_dir. This is the case with buildbot where every package is selected and compiled.
Fix this by adding a pending patch that permits to disable libbsd inclusion even if detected and set the related config flag.
aircrack-ng use 2 function of libbsd and it's not worth to include the entire library for 2 simple function for string manipulation.
Maintainer: Rick Farina <zerochaos@gentoo.org>
> aircrack-ng: fix wrong inclusion of libbsd if detected

- lang/rust/Makefile
- lang/rust/patches/0002-rustc-bootstrap-cache.patch
Compile tested: armsr-armv7/armsr-armv8/ath79-generic/malta-be/octeon-generic/pistachio-generic/ramips-mt7620/sifiveu-generic/x86-64/x86-generic, 2023-10-23 snapshot sdks
Run tested: armsr-armv7/armsr-armv8/malta-be/x86-64/x86-generic (qemu, basic ripgrep run test), 2023-10-23 snapshot
Description:
Please see the individual commit messages for details.
For the compile error if build dir and `DL_DIR` are on separate filesystems, the issue was first described in https://github.com/openwrt/packages/pull/22457.
For the compile error on mipsel_24kc+24kf, the [mipsel_24kc_24kf faillogs](https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc_24kf/packages/) show that all Rust packages do not build. Building locally, this is the error for rust/host (from the …
> rust: Fix compile error if build dir and DL_DIR on separate filesystems, compile error for mipsel_24kc+24kf

- multimedia/tvheadend/Config.in
- multimedia/tvheadend/Makefile
Drop support for PCRE as it's now EOL and won't receive any security updates anymore.
> tvheadend: drop support for PCRE

- net/freeradius3/Makefile
switch to PCRE2 implementation https://github.com/openwrt/packages/issues/22006
Maintainer: @odmdas / @neheb
Compile tested: tested on mediatek unifi-6-lr-v1 with musl openwrt 23.05
Run tested: tested on mediatek unifi-6-lr-v1 with musl openwrt-23.05 with sample configuration (& internal setup ...)
Description:
libpcre is EOL with no further (security) fixes.
use libpcre2 instead
> freeradius3: switch to pcre2

- libs/efivar/Makefile
- libs/efivar/patches/006-build-util-c-separately-for-makeguids.patch
- utils/dmidecode/Makefile
- utils/efibootmgr/Makefile
Maintainer: @Noltari @jefferyto @oskarirauta  @1715173329 
Compile tested:  armsr-armv8, 2023-09-20 snapshot 
Run tested: armsr-armv8 (NXP i.MX8plus, Kontron Box), 2023-09-20 snapshot
Description: 
These packages can be used on Arm SystemReady platforms
> Armsr target support for dmidecode/efivar/efibootmgr

- admin/zabbix/Makefile
Move to PCRE2 library as PCRE is not EOL and won't receive any security updates anymore.
Maintainer: Etienne CHAMPETIER <champetier.etienne@gmail.com> @champtar
> zabbix: move to PCRE2 library

- admin/zabbix/Makefile
- admin/zabbix/patches/110-reproducible-builds.patch
Maintainer:  @champtar 
Compile tested: x86_64 and lantiq_xrx200
Run tested: lantiq_xrx200 only starting zabbix-agentd
Description:
Switch to current stabl version 6.4.7.
See release notes: https://www.zabbix.com/rn/rn6.4.7
So that the new version builds cleanly. The 'libevent2-pthreads' must be added as dependency.
Test:
```
root@VR2-106149 ~ # zabbix_agentd --version
zabbix_agentd (daemon) (Zabbix) 6.4.7
Revision 4e555c6d64d 26 September 2023
Copyright (C) 2023 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.
This product includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit …
```
> zabbix: update to version 6.4.7

- net/speedtestcpp/Makefile
changes:
- fixes a bug where science notations (exponentials) are displayed during tests during high speed bursts
Maintainer: me
Compile tested: x86_64/recent git
Run tested: x86_64/recent git
> speedtestcpp: update to 1.20.3

- libs/efivar/Makefile
- libs/efivar/patches/006-build-util-c-separately-for-makeguids.patch
- utils/dmidecode/Makefile
- utils/efibootmgr/Makefile
Maintainer: @Noltari @jefferyto @oskarirauta  @1715173329
Compile tested: armsr-armv8
Run tested: armsr-armv8 (NXP i.MX8plus, Kontron Box)
Description:
These packages can be used on Arm SystemReady platforms
Cherry picked from master branch
> [openwrt-23.05] Armsr target support for dmidecode/efivar/efibootmgr

- lang/rust/Makefile
- lang/rust/patches/0002-rustc-bootstrap-cache.patch
Compile tested: none (cherry picked from #22504)
Description:
Please see #22504 for details.
> [openwrt-23.05] rust: Fix compile error if build dir and DL_DIR on separate filesystems, compile error for mipsel_24kc+24kf

- lang/python/python-cryptography/Makefile
- lang/python/python-cryptography/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-10-28 snapshot sdk
Run tested: armsr-armv7 (qemu), 2023-10-28 snapshot
Description:
This also adds a CPE ID for the package and updates the test.sh script to use an assert.
> python-cryptography: Update to 41.0.5

- net/wavemon/Makefile
Maintainer: me / @neheb 
Compile tested: ipq40xx / OpenWRT Master
Run tested: ipq40xx / OpenWRT Master
Description:
This series bumps wavemon which is currently broken today.
The main reason for this is being out of sync with current supported mac80211 stack.
Each call ends in "no supported wireless interfaces found!"
This bump makes the package fully working again.
> Wavemon: bump to 9.5.0

- libs/newt/Makefile
- libs/newt/test.sh
Maintainer: me
Compile tested: armsr-armv7, 2023-10-28 snapshot sdk
Run tested: armsr-armv7 (qemu, basic loading tests only), 2023-10-28 snapshot
Description:
> newt: Update to 0.52.24, add test.sh script for packages feed CI

- net/haproxy/Makefile
Move to PCRE2 as PCRE is EOL and won't receive any more security update anymore.
Maintainer: Thomas Heil <heil@terminal-consulting.de>, Christian Lachner <gladiac@gmail.com>
> haproxy: move to PCRE2

- libs/libndpi/Makefile
- libs/libndpi/patches/001-Move-from-PCRE-to-PCRE2.patch
Bump to release 4.8 to make it easier to backport PCRE2 support patch.
Backport patch for PCRE2 support as PCRE is EOL and won't receive any
support updates anymore.
Maintainer: Banglang Huang <banglang.huang@foxmail.com>, Toni Uhlig <matzeton@googlemail.com>
> libndpi: bump to release 4.8 + PCRE2

- sound/owntone/Makefile
Maintainer: me
Compile tested: x86, VM, OpenWrt trunk
Run tested: x86, VM, OpenWrt trunk
Description:
Update to 28.8, see [changelog](https://raw.githubusercontent.com/owntone/owntone-server/master/ChangeLog)
> owntone: Update to 28.8

- lang/python/pyodbc/Makefile
Maintainer: me
Compile tested: none (cherry picked from #22561)
Description:
4.0.36 included a change to [decimal parsing][1] that requires the decimal module. Trying to load the pyodbc module without python3-decimal installed would lead to a segmentation fault.
This adds python3-decimal as a dependency.
This also adds python3-uuid as a dependency as the module can [accept and return uuid objects][2].
[1]: https://github.com/mkleehammer/pyodbc/commit/6b107a2bcaf7379e5ba182007b6ecae1bc2fc931
[2]: https://github.com/mkleehammer/pyodbc/commit/2ad7a9ced7c9c33232c173668c0830a484cc92f3
Fixes: f02f3ee8c768 ("pyodbc: Update to 4.0.39")
(cherry picked from commit 668a0f9dd8baa2fb6275ff0e022b6f1bf390b7c2)
> [openwrt-23.05] pyodbc: Fix segmentation fault

- libs/psqlodbc/Makefile
Compile tested: armsr-arm7, 2023-10-28 snapshot sdk
Description:
This updates the path for odbc_config as it was moved from `$(STAGING_DIR_HOST)/bin` to `$(STAGING_DIR)/host/bin` (in commit 61de50de5f787b08e06de9425ec409c8fd1ffcbf).
> psqlodbc: Fix build

- net/iperf3-mt/Makefile
This adds a multithreaded variant of iperf3 as a package. This variant is still experimental, developed in the mt branch of the iperf repository and expected to be merged when it is considered stable.
Maintainer: me / @jonasjelonek
Compile tested: aarch64_cortex-a53 (BananaPi R64) + x86/64 (APU2C4), OpenWrt snapshot
Run tested: aarch64_cortex-a53 (BananaPi R64) + x86/64 (APU2C4), OpenWrt snapshot
Description:
The main iperf3 that we already have as a package, has no support for multithreading yet. However, the developers are working already on that in the `mt` branch of the [iperf Github repository](https://github.com/esnet/iperf/tree/mt) and release this as 3.XX-mt versions. This multithreaded iperf3 is still considered experimental, however, in my tests I couldn't notice any …
> iperf3-mt: new package

- net/strongswan/Makefile
Maintainer: @pprindeville @Thermi
Compile tested: x86_64, 23.05.0
Run tested: x86_64, 23.05.0, configured the `eap-dynamic` as authentication method for a connection. MacOS Sonoma native VPN client connected using `eap-tls`, while Android phone native VPN client is using `eap-mschapv2`.
```
uptime: 2 hours, since Oct 22 09:03:55 2023
worker threads: 16 total, 11 idle, working: 4/0/1/0
job queues: 0/0/0/0
jobs scheduled: 0
IKE_SAs: 0 total, 0 half-open
loaded plugins: charon aes des rc2 sha2 sha1 md4 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pgp dnskey sshkey pem openssl fips-prf gmp xcbc hmac attr kernel-netlink resolve socket-default connmark vici updown eap-identity eap-mschapv2 eap-dynamic eap-tls xauth-generic
```
Description:
This plugin acts as a proxy that …
> strongswan: add eap-dynamic plugin

- net/nmap/Makefile
- net/nmap/patches/010-Build-based-on-OpenSSL-version.patch
Compile tested: nmap with OpenSSL 1.1 on OpenWrt 22.03 for Turris Omnia, mvebu/cortex-a9
Description:
The latest nmap version 7.9.3 currently fails to compile with OpenSSL 1.1 [1], it required to backport upstream patch to fix the compilation. [2]
[1] https://github.com/nmap/nmap/issues/2516
[2] https://github.com/nmap/nmap/commit/d6bea8dcdee36a3902cece14097993350306f1b6
**This is required for OpenWrt 22.03, but it does not mind to have it on OpenWrt master and thus backport it to OpenWrt 23.05 and OpenWrt 22.03.**
> nmap: backport fix to be able to compile it with OpenSSL 1.1

- net/crowdsec-firewall-bouncer/Makefile
- net/crowdsec-firewall-bouncer/files/crowdsec-firewall-bouncer.initd
* added ujail for crowdsec-firewall-bouncer
* set nice to reduce priority for process
Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.0
(cherry picked from commit a8df73ce7277134c5bd318b3e63cc14e2c70e9a7)
> [23.05] crowdsec-firewall-bouncer: add ujail

- net/crowdsec-firewall-bouncer/Makefile
- net/crowdsec-firewall-bouncer/files/crowdsec-firewall-bouncer.initd
* added ujail for crowdsec-firewall-bouncer
* set nice to reduce priority for process
Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.0
(cherry picked from commit a8df73ce7277134c5bd318b3e63cc14e2c70e9a7)
> [22.03] crowdsec-firewall-bouncer: add ujail

- net/tinc/Makefile
- net/tinc/files/tinc.init
Maintainer: @ErwanMAS
Run tested: OpenWrt 23.05.0 x86/64
Description:
Fetch Ed25519 public keys from UCI host sections.
Update options and syntax to current version.
> tinc: fetch ed25519 public keys from uci

- net/pptpd/Makefile
- net/pptpd/files/pptpd.init
Run tested: OpenWrt 23.05.0 x86/64
Description:
Use boolean options and fix the relevant init error.
> pptpd: use boolean options

- net/udp-broadcast-relay-redux-openwrt/Makefile
- net/udp-broadcast-relay-redux-openwrt/files/udp-broadcast-relay-redux.init
- net/udp-broadcast-relay-redux-openwrt/files/udp_broadcast_relay_redux.config
Maintainer: @accwebs 
Compile tested: ath79/generic, TP-Link Archer C7 v2, OpenWrt 23.05.0 r23497-6637af95aa
Run tested: same as above, configured the option to use with an IoT device and I could finally communicate with it
> udp-broadcast-relay-redux-openwrt: add multicast config option

- net/quassel-irssi/Makefile
- net/quassel-irssi/patches/100-Fix-compilation-error-with-new-version-of-irssi.patch
Add patch fixing compilation error with new version of irssi where the renamed some functions.
Fixes: #22384
> quassel-irssi: fix compilation error with new version of irssi

- lang/php8/Makefile
Maintainer: me
Compile tested: riscv64, mxs
Description:
Backport latest update and dependency fix for riscv64.
> [23.05] php8: update to 8.2.12

- .github/workflows/multi-arch-test-build.yml
Description:
The updated version of gh-action-sdk will return compiled packages and build logs for both build success and build errors.
This ensures these artifacts are always uploaded. This also sets the V environment variable to enable verbose build output.
> CI: Update sdk action, always upload artifacts

- utils/nano/Makefile
- utils/nano/files/ucode.nanorc
Description:
Introduce local syntax highlighting support for ucode scripts, like it is done already for uci configuration files.
Ref: https://github.com/jow-/ucode/issues/178
Compile tested: not applicable
Run tested: tested by opening various ucode files in nano-full - 7.2-2 on OpenWrt SNAPSHOT, r24256-1d6f9bdfc @ ramips/mt7621
> nano: add syntax highlighting for ucode scripts

- net/iperf3/Makefile
When selecting both iperf3 and iperf3 ssl, there is a problem that both packages install same binary file.
This patch fixes this issue by adding conflict between those packages.
Maintainer: Felix Fietkau @nbd168 
Compile tested: aarch64 / 2023-10-18 snapshot
Run tested: aarch64, raspberry Pi 4, 2023-10-18 snapshot
Description:
This fixes conflict when building Iperf3 by adding appropriate dependencies/conflicts.
> iperf3: Fix dependecy conflict with iperf3-ssl

- net/snort3/Makefile
Upstream bump
```
o"  )~   Version 3.1.74.0
Using DAQ version 3.0.13
Using Hyperscan version 5.4.2 2023-11-08
```
> snort3: update to 3.1.74.0

- libs/libdaq3/Makefile
> libdaq3: update to 3.0.13

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.0.2: https://github.com/zhaojh329/lua-eco/releases/tag/v3.0.2
> lua-eco: update to 3.0.2

- utils/tang/Makefile
- utils/tang/files/tang.init
Maintainer: me
Run tested: -
Description:
This corrects the permissions of generated files and sets the right maintainer.
Resolves: #22632
> tang: set the right permissions to keys

- net/sstp-client/Makefile
- net/sstp-client/patches/200-openssl-deprecated.patch
Compile tested: OpenWrt master
Run tested: ipq40xx
Description:
After 1.0.18, this project moved from SourceForge to gitlab
Also, since 1.0.19, the configure script is not present by default anymore, so we need to add autoreconf to generate it
Release notes:
https://gitlab.com/sstp-project/sstp-client/-/releases
> sstp-client: bump to 1.0.19

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
- net/adblock-fast/files/etc/uci-defaults/90-adblock-fast
Maintainer: me
Description:
* update Makefile copyright info
* organize functions shared between the init script, uci-defaults and luci app in alphabetical order
* update error, warning and status messaging
* use single quotes instead double quotes for static text labels
* better warning for missing recommended packages
* rename dns function to resolver to better reflect its purpose
* improve resolver cleanup code
* move _resolver_config function inside resolver function to improve code readlibity
* rename _process_file_url to process_file_url_wrapper to better reflect its purpose
* add preflight check for available RAM vs total size of block lists
* move _config_add_url_size …
> adblock-fast: update to 1.0.1-1

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
- net/adblock-fast/files/etc/uci-defaults/90-adblock-fast
Maintainer: me
Description:
* update Makefile copyright info
* organize functions shared between the init script, uci-defaults and luci app in alphabetical order
* update error, warning and status messaging
* use single quotes instead double quotes for static text labels
* better warning for missing recommended packages
* rename dns function to resolver to better reflect its purpose
* improve resolver cleanup code
* move _resolver_config function inside resolver function to improve code readlibity
* rename _process_file_url to process_file_url_wrapper to better reflect its purpose
* add preflight check for available RAM vs total size of block lists
* move _config_add_url_size …
> [23.05] adblock-fast: update to 1.0.1-1

- net/tailscale/Makefile
> tailscale: Update to 1.52.1

- net/unbound/Makefile
- net/unbound/files/dnsmasq.sh
- net/unbound/patches/010-configure-uname.patch
Maintainer: me
Tested: Linksys WRT3200ACM
Description: update to 1.19.0 and bring PR \22594 along
Fixes: #22594
Fixes: #22593
> unbound: update to 1.19.0

- net/gensio/Makefile
Run tested: no
Description:
Buildbots spottet this error that when dns_sd library is available, then gensio's configure will pick it up. This is not desired since we already link to libavahi for the mdns stuff, so let's disable dnssd lookup explicitly.
> gensio: prevent accidental use of dns_sd

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* ensure downloaded block-lists end with newline
* turn free/total RAM checks into functions calls
> adblock-fast: bugfix: ensure downloaded block-lists end with newline

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* ensure downloaded block-lists end with newline
* turn free/total RAM checks into functions calls
(cherry picked from commit 3787b4135584ad2a6510dbd883406d30575dce5c)
> [23.05] adblock-fast: bugfix: ensure downloaded block-lists end with newline

- net/sing-box/Makefile
see changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.6.4
Description:
> sing-box: update to v1.6.4

- net/freeradius3/Makefile
Compile tested: armsr-armv7, 2023-11-10 snapshot sdk
Description:
If pcre is built before freeradius, then freeradius' configure will detect pcre and freeradius will be built with pcre functionality enabled. This causes a "missing dependencies" error at the end of package build.
This passes `--without-pcre` to configure to disable this autodetection.
This also removes the dependency on libpcre2 as freeradius v3 does not have support for pcre2.
Fixes: 19ec30255f13 ("freeradius3: switch to pcre2")
Fixes: https://github.com/openwrt/packages/issues/22574
> freeradius3: Fix build when pcre is present

- net/gensio/Makefile
Run tested: -
Description:
libudev seems to be required only for cm108gpio gensio which is a relatively special one. Let's disable it and also the libudev lookup, so that there is no need to link/use libudev.
(While at, sort the without arguments alphabetically.)
> gensio: disable cm108gpio gensio and prevent using libudev

- utils/fx/Makefile
Maintainer: me
Compile tested: Ubuntu 23.04 x64 / OpenWrt SNAPSHOT @ 36b1dd75fd9da1ea13f1ce1ee679c6b3c9c402cc
Description:
[Fx](https://github.com/antonmedv/fx/releases/tag/31.0.0) is a dual-purpose command-line tool tailored for JSON, providing both a terminal-based JSON viewer and a JSON processing utility.
> fx: add new package

- net/pdns-recursor/Makefile
> pdns-recursor: update to 4.9.2 and fix conffile path

- utils/pps-tools/Makefile
- utils/pps-tools/patches/001-time_t_64bit.patch
musl 1.2.0 switched to use 64-bit time_t everywhere, including 32-bit architectures, causing garbage values to be printed from ppswatch and ppstest.
Use the correct format string for the affected printf statements and explicitly cast to long long to avoid potential compatibility issues with 32-bit glibc.
Maintainer: @MASHtm 
Compile tested: arm, cloudengines_pogoe02, 23.05.0
Run tested: arm, cloudengines_pogoe02, 23.05.0
> pps-tools: use %lld in printf for 64-bit time_t

- sound/pulseaudio/Makefile
Reportedly was inadvertendly being compiled against libwrap per https://github.com/openwrt/packages/commit/aafc57c1ded5450419b9690056163acf3d19d51f#comments
If libraries/libwrap (tcp wrapper library) was built before pulseaudio, 
Libwrap was detected at the meson configuration stage of pulseaudio and used since this commit:
https://github.com/pulseaudio/pulseaudio/commit/156e16f941789c5d53cdb0c46be480c64e3149f1
However, pulseaudio can not find libwrap.so.0 during the openwrt building process at some stage. 
Therefor, compilation against libwrap is disabled.
> pulseaudio: disable compiling against libwrap (was Include +libwrap dependency)

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.23.1)
> docker-compose: Update to version 2.23.1

- utils/fuse3/Makefile
Add PKG_BUILD_DEPENDS to fix potential problems.
> fuse3: update to 3.16.2

- net/freeradius3/Makefile
Maintainer: none (ping @odmdas, @neheb)
Compile tested: none (cherry picked from #22666)
Description:
If pcre is built before freeradius, then freeradius' configure will detect pcre and freeradius will be built with pcre functionality enabled. This causes a "missing dependencies" error at the end of package build.
This passes `--without-pcre` to configure to disable this autodetection.
This also removes the dependency on libpcre2 as freeradius v3 does not have support for pcre2.
Fixes: 19ec30255f13 ("freeradius3: switch to pcre2")
Fixes: https://github.com/openwrt/packages/issues/22574
(cherry picked from commit 92aadf7e4acfaf89ef83b43244027e10f7f80d1f)
> [openwrt-23.05] freeradius3: Fix build when pcre is present

- net/strongswan/Makefile
- net/strongswan/files/swanctl.init
Maintainer: Philip Prindeville <philipp@redfish-solutions.com>, Noel Kuntze <noel.kuntze@thermi.consulting>
Compile tested: Archer C7 v4 on latest master
Run tested: Archer C7 v4 on latest master
Description:
Add support for replay window configuration in UCI.
> strongswan: swanctl: add support for replay window

- libs/liburing/Makefile
Maintainer: Christian Lachner <gladiac@gmail.com> (**/me**)
Compile tested: mipsel, mips74k, ipq806x, x86, arc700
Description: Update to v2.5
- Updated download URL and hash
> liburing: Update to v2.5

- net/snort3/Makefile
- net/snort3/patches/010-gcc13.patch
> snort3: fix compilation with gcc13

- net/netbird/Makefile
- net/netbird/files/netbird.init
Release notes: https://github.com/netbirdio/netbird/releases/tag/v0.24.2
Also fixes issue of not being able to build with musl (>1.2.4)
Maintainer: me
> netbird: update to version 0.24.2

- net/openvpn/Makefile
- net/openvpn/patches/100-mbedtls-disable-runtime-version-check.patch
- net/openvpn/patches/101-Fix-EVP_PKEY_CTX_-compilation-with-wolfSSL.patch
- net/openvpn/patches/102-Disable-external-ec-key-support-when-building-with-wolfSSL.patch
- net/openvpn/patches/103-define-LN_serialNumber-for-wolfSSL.patch
Maintainer: @mkrkn
Compile tested: ramips/mt7620, ramips/mt7621
Run tested: Xiaomi mi router 3 pro, Xiaomi mi-mini, Xiaomi miwifi-r3
Is a regression fix release for previous release that containing bugfixes and security fixes.
Security Fixes (included in 2.6.7):
CVE-2023-46850 OpenVPN versions between 2.6.0 and 2.6.6 incorrectly use a send buffer after it has been free()d in some circumstances, causing some free()d memory to be sent to the peer. All configurations using TLS (e.g. not using --secret) are affected by this issue.
CVE-2023-46849 OpenVPN versions between 2.6.0 and 2.6.6 incorrectly restore --fragment configuration in some circumstances, leading to a division by zero when --fragment is used. On platforms where division by zero is fatal, this will cause an OpenVPN crash.
For …
> openvpn: update to 2.6.8

- utils/gl-puli-mcu/Config.in
- utils/gl-puli-mcu/Makefile
- utils/gl-puli-mcu/src/gl-puli-mcu.c
Compile tested: GL.iNet GL-XE300, GL.iNet GL-XE3000
Run tested: GL.iNet GL-XE300, GL.iNet GL-XE3000
Description:
I'm working on the support for GL.iNet GL-XE3000 (Puli AX) in OpenWrt, and I adapted this package in order to be able to retrieve the battery status on this new target.
> gl-puli-mcu: Adaptation for GL.iNet XE3000 (Puli AX)

- net/acme-acmesh/Makefile
Maintainer: @tohojo @hgl
Description: Update to 3.0.7.
Signed-off-by: Kevin White [kwhite@kevbo.org](mailto:kwhite@kevbo.org)
> acme-acmesh: Update to 3.0.7

- lang/python/python-fnv-hash-fast/Makefile
- lang/python/python-fnvhash/Makefile
- lang/python/python-lru-dict/Makefile
- lang/python/python-orjson/Makefile
Specific module versions added:
- python-fnvhash v0.1.0
- python-fnv-hash-fast v0.5.0
- python-lru-dict v1.3.0
- python-orjson v3.9.10
Maintainer: me
- arch: arm_cortex-a9_vfpv3-d16
- model: Linksys WRT1900ACS
- OpenWRT versions:
-- 23.05.0 r23497-6637af95aa (note: had to back-port python-maturin from master)
-- master
Run tested:
- arch: arm_cortex-a9_vfpv3-d16
- model: Linksys WRT1900ACS
- OpenWRT version: 23.05.0 r23497-6637af95aa
- successful install and run of HomeAssistant v2023.11.1
Description:
These three compiled modules are required by the latest release (2023.11.1) for the HomeAssistant project. While HomeAssistant is not yet supported on openwrt, I was able to get 2023.11.1 working and may at some point add a package to openwrt. For now, these modules may be …
> Added python-fnv-hash-fast, python-lru-dict, and python-orjson

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.0.2: https://github.com/zhaojh329/lua-eco/releases/tag/v3.1.0
> lua-eco: update to 3.1.0

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v2.8.4

- net/dhtd/Makefile
- net/dhtd/files/dhtd.config
- net/dhtd/files/dhtd.init
(cherry picked from commit 819cf67a338611681d2bee7ee37eec5864110fc3)
Maintainer: me
Compile tested: ramips/mt7620, Nexx wt3020, OpenWrt master ([255d5c9bf8430bea8ee342b0132be0787b509634](https://github.com/openwrt/openwrt/commit/255d5c9bf8430bea8ee342b0132be0787b509634))
Run tested: same as compile version, tested: bootstrap, search and print results, execute script on result
> dhtd: update to 0.2.4

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> [openwrt-23.05] haproxy: update to v2.8.4

- net/gensio/Makefile
- net/gensio/patches/0001-Ensure-that-ax_python_devel_found-is-defined.patch
- net/gensio/patches/0002_ax_python_devel-fix-serial.patch
- net/gensio/patches/0003-Revert-ax_pkg_swig.m4-to-latest-vanilla-version.patch
Run tested: -
Description:
The built-in swig/python detection does not works well when system-wide m4 macros are available with same name but different content.
So make the configure stuff compatible, resp. workaround a little bit.
Upstream PRs are pending for review.
It seems also necessary to pass the PYTHON_LIBS environment during the compile phase.
> gensio: add patches/fixes to workaround swig and python detection

- net/sing-box/Makefile
Maintainer: me
Changes: https://github.com/SagerNet/sing-box/compare/v1.6.4...v1.6.6
> sing-box: update to 1.6.6

- lang/rust/Makefile
- lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
- lang/rust/patches/0002-rustc-bootstrap-cache.patch
- lang/rust/patches/0003-bump-libc-deps-to-0.2.146.patch
Compile tested: mediatek/filogic
Description:
- Bumped libc to 0.2.147 to align deps.
- Refreshed patches.
Release note: https://releases.rs/docs/1.74.0/
> rust: Update to 1.74.0

- utils/sockread/Makefile
- utils/sockread/src/main.c
* cleanup code style
* allow arguments to be passed from the command line
Maintainer: me
Compile tested: ramips/mt7620, Nexx wt3020, OpenWrt master ([0f283ab4c9d9b7971a19172ca5d15035c801cb24](https://github.com/openwrt/openwrt/commit/0f283ab4c9d9b7971a19172ca5d15035c801cb24))
> sockread: cleanup code and allow arguments

- net/unbound/Makefile
- net/unbound/files/dnsmasq.sh
Run tested: OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8
Description:
The function `create_host_record_from_host` fails if the `dns` option is not set in the host entry.
This sets a default to the `dns` variable in order to fix this error.
Fixes: #22691
> unbound: fix `create_host_record_from_host` error when `dns` is not set

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/config/adblock-fast
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* fix boot()
* reintroduce procd_boot_delay variable to control delay of service start on boot
* introduce `check_lists` command to check enabled block-lists for domain(s)
* use config_get_bool instead of config_get for boolean options
> adblock-fast: bufgix: fix boot()

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/config/adblock-fast
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* fix boot()
* reintroduce procd_boot_delay variable to control delay of service start on boot
* introduce `check_lists` command to check enabled block-lists for domain(s)
* use config_get_bool instead of config_get for boolean options
(cherry picked from commit 96ad0ab6fda173b27d9392f7c16d1e9bea327662)
> [23.05] adblock-fast: bufgix: fix boot()

- utils/docker-compose/Makefile
> docker-compose: Update to version 2.23.3

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_route53_v1.sh
Maintainer: @chris5560, @maxberger, @dibdot
Compile tested: : N/A
Run tested:  OpenWrt 23.05.0, r23497-6637af95aa, amd64 
Description:
This fixes the Invalid Resource Record: FATAL problem: ARRDATAIllegalIPv4Address error message described in https://forum.openwrt.org/t/route53v1-script-error/160068
Signed-off-by: Max Berger <max@berger.name>
> ddns-scripts: Fix Route53 provider

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* fix call to is_number to is_integer
* improve boot()
> adblock-fast: bugfix: call to missing function

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* fix call to is_number to is_integer
* improve boot()
(cherry picked from commit ffb396bca93ba5675ec0f999cf2dc9397b28e138)
> [23.05] adblock-fast: bugfix: call to missing function

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/020-src-options.c-add-version.patch
> https-dns-proxy: fix unintentional call of service_stopped in boot()

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/020-src-options.c-add-version.patch
Maintainer: me
(cherry picked from commit 2e9f6c44460a48876cd85cde3557ce373693df6b)
> [22.03] https-dns-proxy: fix unintentional call of service_stopped in boot()

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/020-src-options.c-add-version.patch
Maintainer: me
(cherry picked from commit 2e9f6c44460a48876cd85cde3557ce373693df6b)
> [23.05] https-dns-proxy: fix unintentional call of service_stopped in boot()

- utils/mc/Makefile
- utils/mc/patches/010-subshell.patch
- utils/mc/patches/020-fix-mouse-handling-newer-terminfo.patch
- utils/mc/patches/030-mc-mksh-subshell-v2.patch
Description:
* News: http://midnight-commander.org/wiki/NEWS-4.8.30
* remove obsolete / adapt changed options
Maintainer: n/a
Compile tested: x86_64, APU1
Run tested: x86_64, APU1
> mc: bump to release 4.8.30

- lang/luajit2/Makefile
> luajit2: update to v2.1-20231117

- net/dhtd/Makefile
Maintainer: me
Compile tested:  ramips/mt7620, OpenWrt master
Run tested: minimal changes
> dhtd: update to 0.2.5

- net/travelmate/Makefile
- net/travelmate/files/hreward.login
Signed-off-by: Marc Bulling @forceu
Maintainer: @dibdot
Compile tested: GL.iNet GL-MT3000 ARMv8 OpenWrt 23.05.0-rc3
Run tested: GL.iNet GL-MT3000 ARMv8 OpenWrt 23.05.0-rc3
Description: Add autologin for Deutsche Hospitality hotels (e.g. Steigenberger)
Original PR was #22704, but I had too many problems editing the commits to meet the requirements
> travelmate: Add h-reward hotel wifi autologin

- lang/node/Makefile
- lang/node/patches/003-path.patch
Run tested: (qemu 8.1.3) aarch64
Description:
* --experimental-default-type flag to flip module defaults
* Detect ESM syntax in ambiguous JavaScript
* New flush option in file system functions
* Experimental WebSocket client
* vm: fix V8 compilation cache support for vm.Script
> node: bump to v20.10.0

- utils/podman/Makefile
- utils/podman/files/containers.conf
- utils/podman/patches/010-do-not-build-docs.patch
Changelog: https://github.com/containers/podman/releases
I also updated containers.conf - it has gotten quite a many new options. I added crun to depends, every other distribution seems to ship it with podman, and after all it is a default OCI Container Runtime for podman anyway and has a super low footprint, so shouldn't be a problem for anyone running containers, after all you need some storage for that anyway.
Maintainer: me
> podman: update to version 4.8.0

- net/aardvark-dns/Makefile
Changelog:
- update trust-dns to hickory
- never report an error when the syslog init fails
- dependency updates
Maintainer: me
> aardvark-dns: update to version 1.9.0

- net/mosquitto/Makefile
Switch to CMake. Allows faster compilation.
Small Makefile cleanups.
> mosquitto: update to 2.0.18

- net/wifischedule/Makefile
- net/wifischedule/README.md
- net/wifischedule/net/etc/init.d/wifi_schedule
- net/wifischedule/net/usr/bin/wifi_schedule.sh
- Fixed _get_wireless_interfaces, thanks to @Trekky12
- Check schedule during router startup
Fixes: https://github.com/newkit/wifischedule/pull/9
Maintainer: @newkit
Tested: TP-Link WDR3600 with OpenWRT 23.05
Signed-off-by: Nils Koenig openwrt@newk.it
> wifischedule: updated to 1.0.5-1

- .github/workflows/entrypoint.sh
Compile tested: tested in https://github.com/jefferyto/openwrt-packages/pull/18 ([GA run](https://github.com/jefferyto/openwrt-packages/actions/runs/7014564500/job/19082480680?pr=18))
Description:
Commit 18d3c529fa4ab8dafcf6c147cf3cb55792d8ca10 caused `CI_HELPER` to be set to `''` (two single quotes), leading to an error when test.sh tries to source `$CI_HELPER`.
`CI_HELPER` is not set anywhere else and not passed into the container environment, so there is no need to test if it has a value.
This fixes the value of `CI_HELPER`.
Fixes: 18d3c529fa4a ("github-ci: error on any shell errors")
> CI: Fix CI_HELPER

- mail/postfix/Makefile
After the change from PCRE to PCRE2 when enabling POSTFIX_PCRE the resulting postfix build no longer reports pcre as an available module. (postfconf -m). This is caused by using the wrong syntax for the HAS_PCRE build flag (HAS_PCRE2 vs HAS_PCRE=2). This fixes the build flag to use the correct syntax.
Maintainer: @Ansuel
Compile tested: aarch64, Redmix AX6000, 23.05.2
Run tested: aarch64, Redmix AX6000, 23.05.2, tried to send mail with postfix configured to use pcre tables
> postfix: Fix enabling PCRE support

- net/snort3/Makefile
Upstream bump
```
o"  )~   Version 3.1.75.0
Using DAQ version 3.0.13
Using Hyperscan version 5.4.2 2023-11-20
```
> snort3: update to 3.1.75.0

- libs/libsocketcan/Makefile
Maintainer: @yegorich 
Compile tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2
Run tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2, tested with internal software
Description: readd and update the libsocketcan package from OpenWrt 14.07:
https://git.archive.openwrt.org/?p=14.07/packages.git;a=blob;f=libs/libsocketcan/Makefile;hb=a2d1927140548a805970f0859150556ea0b22a78
> libsocketcan: new package

- libs/nghttp3/Makefile
Maintainer: me
Description:
* Changelog: https://github.com/ngtcp2/nghttp3/releases/tag/v1.1.0
> nghttp3: update to 1.1.0

- libs/ngtcp2/Makefile
Maintainer: me
Description:
* Changelog: https://github.com/ngtcp2/ngtcp2/releases/tag/v1.1.0
> ngtcp2: update to 1.1.0

- libs/nghttp3/Makefile
Maintainer: me
Description:
* Changelog: https://github.com/ngtcp2/nghttp3/releases/tag/v1.1.0
(cherry picked from commit 353bdb9cf08d3921bcae90d75a84665a329501db)
> [23.05] nghttp3: update to 1.1.0

- libs/ngtcp2/Makefile
Maintainer: me
Description:
* Changelog: https://github.com/ngtcp2/ngtcp2/releases/tag/v1.1.0
(cherry picked from commit 05cf7cff10d39429d8faa3bb05afeb3f09aab13b)
> [23.05] ngtcp2: update to 1.1.0

- net/snort/Makefile
- net/snort/patches/900-Convert-project-to-PCRE2.patch
Update to relase 2.9.20 to make it easier to apply experimental PCRE2
support patch.
Add experimental PCRE2 support patch as PCRE is EOL and won't receive
any new updates anymore.
Since PCRE2 API changed, also snort plugins API changed and require some
tweka for any user downstream that compile custom plugins. The examples
are all updated and conversion patch contains additional info on the
changes required to the plugins.
Plugins needs to be compiled and require updates anyway so there isn't a
problem with user trying to load incompatible plugins.
> snort: bump to release 2.9.20 + experimental PCRE2

- libs/libsocketcan/Makefile
Maintainer: @yegorich 
Compile tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2
Run tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2, tested with internal software
Description:
The following line appeared twice:
include $(INCLUDE_DIR)/package.mk
> libs/libsocketcan: remove double line

- lang/node/Makefile
- lang/node/patches/003-path.patch
- lang/node/patches/004-musl_support.patch
 Compile tested: 23.05, aarch64, arm 
Run tested: (qemu 8.1.3) aarch64
Description:
* npm updated to v10
* ESM and customization hook changes
* New node:module API register for module customization hooks; new initialize hook
* import.meta.resolve unflagged
* --experimental-default-type flag to flip module defaults
> [23.05] node: bump to v18.19.0

- net/ariang/Makefile
Compile tested: AXT1800 (an qualcommax/ipq60xx) and x86
Run tested: AXT1800 (an qualcommax/ipq60xx) and x86
Description:
Fix the problem that cannot create new task after clearing checksum option
Other bug fix and user interface optimization
Support overriding aria2 global settings with empty content when create new download task (#712)
Other bug fix and user interface optimization
Update Traditional Chinese translation (#705, thx @ChiaYen-Kan)
Other bug fix and user interface optimization
Add check-integrity to task settings tab (#693, thx @raytrap)
Fix a spelling mistake (#696, thx @rusq)
Some issues occuered and I have to re open a new Pull (old one is #22120 )
> ariang: Update from 1.3.2 to 1.3.6

- utils/cligen/Makefile
Compile tested: x86_64, generic, HEAD (703d667a0c)
Description:
CLIgen is a Command-Line Interface generator
cc: @olofhagsand
> cligen: Initial packaging

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
- net/adblock-fast/files/etc/uci-defaults/90-adblock-fast
Maintainer: me
Description:
* add support for smartdns
* switch from using `uci` commands to `uci_` functions
* rename `_resolver_config` to `_dnsmasq_instance_config`
* introduce `_smartdns_instance_config`
* improve resolvers restart code on changes
* update load_validate_config to allow for smartdns option
> adblock-fast: add support for smartdns

- utils/clixon/Makefile
- utils/clixon/files/clixon.init
- utils/clixon/files/netconf-subsystem.conf
- utils/clixon/files/restconf.xml
Compile tested: x86_64, generic, HEAD (66f6c20e45)
Description:
Clixon is a YANG-based configuration manager, with interactive CLI, NETCONF and RESTCONF interfaces, an embedded database and transaction mechanism.
cc: @olofhagsand
> clixon: Initial packaging

- net/dhtd/Makefile
(cherry picked from commit 3c011d8aa190bc5d9b2eb5552bba14f7de072734)
Maintainer: me
> [openwrt-23.05] dhtd: udpate to 0.2.6

- net/fail2ban/Makefile
- net/fail2ban/patches/101-move-global-groups-to-start-of-expression-python-3.11-compat.patch
- net/fail2ban/patches/102-wrap-global-flags-to-local-flags-if-supported-by-RE-engine-in-the-python-version.patch
Maintainer: @erdoukki
Compile tested: none (cherry picked from #22742)
Description:
This backports 2 commits from [upstream][1]; the other 3 are not strictly necessary. One of the patches has been updated to remove a change to a regex that does not exist in 0.11.2.
[1]: https://github.com/fail2ban/fail2ban/pull/3267
Fixes: https://github.com/openwrt/packages/issues/22736
(cherry picked from commit 0d9cc4aed202c9126966f7a9e73eaa7f48d51b6b)
> [openwrt-23.05] fail2ban: Fix compatibility with Python 3.11

- net/iperf3/Makefile
notable changes:
- multithreading support
changelog: https://github.com/esnet/iperf/releases/tag/3.16
Signed-off-by: Jonas Jelonek <jelonek.jonas@gmail.com>
(cherry picked from bdb6d2a37f)
Compile tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt 23.05 snapshot
Run tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt 23.05 snapshot
Description:
see changelog for all changes. Most notably, the developers already included the multithreading support in this mainline version.
> [openwrt-23.05] iperf3: update to 3.16

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* do not use standalone grep-package dependent syntax to get the remote file size
* various bugfixes to prevent attempts to change/commit if dnsmasq/smartdns are not installed
(cherry picked from commit 496d9b71ab83b1cfcc8c71c894de432ff841616c)
> [23.05] adblock-fast: bugfixes: getsize/resolver

- net/snort3/Makefile
Changelog: https://github.com/snort3/snort3/releases/tag/3.1.76.0
```
o"  )~   Version 3.1.76.0
Using DAQ version 3.0.13
Using Hyperscan version 5.4.2 2023-12-03
```
> snort3: update to 3.1.76.0

- utils/irqbalance/Makefile
- utils/irqbalance/patches/010-meson.patch
- utils/irqbalance/patches/020-mark-EINVAL-error-permanent.patch
Irqbalance 1.9.3 changed the handling of certain errors. Specifically EINVAL, trying to set an invalid CPU core, was changed to be a temporary error, causing log spam from repeated balancing runs in some devices. See log and strace below. Mark EINVAL as permanent.
This errors seems to surface on 23.05 only on some devices, but not all. 
And when I briefly tested, the unpatched 1.9.3 seemed to work in R7800 main/master build (with kernel 6.1) but fail with 23.05.  So I initially author this fix just for 23.05 
Also correct the version in our own meson.build patch.
Log and strace:
```
Sat Dec  9 10:17:27 2023 daemon.warn irqbalance: Cannot change IRQ 48 affinity: Invalid argument
open("/proc/irq/48/smp_affinity", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = 6 mmap2(NULL, 4096, …
```
> [23.05] irqbalance: Fix log spam and correct meson version

- utils/syncthing/Makefile
- utils/syncthing/files/syncthing.init
Run tested: linksys_e8450-ubi aarch64_cortex-a53
Description:
Fixes issue #22760, duplicate command line options at service startup.
> syncthing: fix duplicate command line parameters on service

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* remove empty lines from the combined list to allo optimization code to work properly
> adblock-fast: bugfix: block domains from config when not using block-lists

- net/curl/Makefile
- net/curl/patches/200-no_docs_tests.patch
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.2, test https-dns-proxy works.
Description:
* https://curl.se/changes.html#8_5_0
> curl: update to 8.5.0

- net/nebula/Makefile
- net/nebula/files/nebula.proto
Maintainer: me
Description:
* https://github.com/slackhq/nebula/releases/tag/v1.8.0
> nebula: update to 1.8.0

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* improve allow-listing reliability by running sed from the script-file instead of the command-line
* fix user for smartdns files ownership
> adblock-fast: better allow-listing

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
* improve allow-listing reliability by running sed from the script-file instead of the command-line
* fix user for smartdns files ownership
(cherry picked from commit 693287e9610b379111b1c2a5a7589a576a8ce663)
> [23.05] adblock-fast: better allow-listing

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/020-src-options.c-add-version.patch
Maintainer: me
Description:
* only restart firewall when needed
> https-dns-proxy: only restart firewall when needed

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/020-src-options.c-add-version.patch
Maintainer: me
Description:
* only restart firewall when needed
(cherry picked from commit 8b6635bae9717babbc3dcf1347cf4727fc15f9bd)
> [22.03] https-dns-proxy: only restart firewall when needed

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/020-src-options.c-add-version.patch
Maintainer: me
Description:
* only restart firewall when needed
(cherry picked from commit 8b6635bae9717babbc3dcf1347cf4727fc15f9bd)
> [23.05] https-dns-proxy: only restart firewall when needed

- utils/syncthing/Makefile
- utils/syncthing/files/syncthing.init
- This patch fixes 9d17ba1 and #22760
Signed-off-by: Eric Fahlgren <ericfahlgren@gmail.com>
(cherry picked from commit 6849a9df90d8c9c99dd50356b8f969d64026c16d)
Description:
Backport fix to 23.05
> [23.05] syncthing: fix duplicate command line parameters on service

- net/tgt/Makefile
Maintainer: me
Compile tested: aarch64_cortex-a53, qualcommax/ipq807x, r24583+3-5fec4d6cd5
Run tested: aarch64_cortex-a53, qualcommax/ipq807x, r24583+3-5fec4d6cd5, running in a chroot at r23300+3-86bc525d00. I/O on a file as a backing store works
Description:
> tgt: update to 1.0.89

- lang/python/python-typing-extensions/Makefile
Compile tested: armsr-armv7, 2023-12-10 snapshot sdk
Run tested: armsr-armv7 (qemu, basic module loading only), 2023-12-10 snapshot
Description:
> python-typing-extensions: Update to 4.9.0

- net/unbound/Makefile
- net/unbound/files/dnsmasq.sh
Run tested: OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8
Description: Backport #22594 and #22721
> [23.05] unbound: create extra host records from DHCP static leases

- net/snowflake/Makefile
Release Notes:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/blob/v2.8.0/ChangeLog
> snowflake: update to 2.8.0

- libs/davici/Makefile
- utils/swanmon/Makefile
- utils/swanmon/test.sh
Maintainer: me
Compile tested: x86_64, lantiq_xrx200
Run tested: lantiq_xrx200, 22.03.5
Description:
swanmon is a tool for querying strongswan status information _in JSON, unlike swanctl_ via the [vici protocol](https://github.com/strongswan/strongswan/blob/master/src/libcharon/plugins/vici/README.md) using the added [davici](https://github.com/strongswan/davici) library package.
Example output:
```shell
~ swanmon help
Usage: swanmon [COMMAND]
commands:
help              Shows swanmon help
version           Returns daemon and system specific version information
stats             Returns IKE daemon statistics and load information
list-sas          Lists currently active IKE_SAs and associated CHILD_SAs
get-conns         Return a list of connection names loaded exclusively over vici …
```
> swanmon: add package

- net/curl/Makefile
- net/curl/patches/200-no_docs_tests.patch
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.2, test https-dns-proxy works.
Description:
* https://curl.se/changes.html#8_5_0
(cherry picked from commit 6501290c17fb2c65e0fb589da94d121ff89e7d5e)
> [23.05] curl: update to 8.5.0

- net/nebula/Makefile
- net/nebula/files/nebula.proto
Maintainer: me
Description:
* https://github.com/slackhq/nebula/releases/tag/v1.8.0
(cherry picked from commit e9b04f32a4ded93260ca04c35bb0e317ea27d238)
> [23.05] nebula: update to 1.8.0

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v2.8.5

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* move reload/restart logic from json() to config_cache()
* improve fw4 restart decision logic
* no longer store reload/restart info in ubus/status json file
* rename variables pointing to run-time information
* create dns_set_output_values to reuse code in principal all and luci app
* improve append_url to store collected URLs in an alternative variable
> adblock-fast: update to 1.1.1-1

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* move reload/restart logic from json() to config_cache()
* improve fw4 restart decision logic
* no longer store reload/restart info in ubus/status json file
* rename variables pointing to run-time information
* create dns_set_output_values to reuse code in principal all and luci app
* improve append_url to store collected URLs in an alternative variable
(cherry picked from commit bab17f480c638350aa3734d7757bbae353c1c740)
> [23.05] adblock-fast: update to 1.1.1-1

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> [openwrt-23.05] haproxy: update to v2.8.5

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.1.2: https://github.com/zhaojh329/lua-eco/releases/tag/v3.1.2
> lua-eco: update to 3.1.2

- libs/libtorrent-rasterbar/Makefile
Run tested: -
Description:
Switch to use release tarball to avoid try_signal hack.
Release note: https://github.com/arvidn/libtorrent/releases/tag/v2.0.9
> libtorrent-rasterbar: Update to 2.0.9

- net/chrony/Makefile
- net/chrony/files/chrony.ntp-hotplug
- net/chrony/files/chronyd.init
Maintainer: me
Compile tested: (mips, Archer C5v1, 23.05)
Run tested: (mips, Archer C5v1, 23.05, NTP client+server)
Description:
Update to latest release and add an ntp hotplug provider script.
> chrony: update to 4.5 and add ntp hotplug

- net/mosh/Makefile
The mosh-server and mosh-client packages are related to SSH.
Maintainer: @neheb @tymmej
Compile tested: OpenWrt master
Run tested: VirtulBox amd64
Description:
The mosh package is located in `net` folder while its makefile section is set to `utils`.
I didn't found it in the menuconfig because expected to see it in net/SSH section.
The PR moves it to the more appropriate section.
> mosh: Move section net/Network/SSH

- libs/hyperscan/Makefile
Hyperscan is a high performance regular expression matching library from Intel that runs on x86 platforms and offers support for Perl Compatible Regular Expressions (PCRE) syntax, simultaneous matching of groups of regular expressions, and streaming operations.
This has utility in speeding up snort3.
> hyperscan: new package for speeding up regex ops

- libs/gpgme/Makefile
gpgme license is wrong since the addition of the package in commit https://git.openwrt.org/?p=feed/packages.git;a=commit;h=3e39633b75e7d26f3666bce9c2e97d268f0fd068
Indeed, gpgme has been licensed under LPGL-2.1+ since version 1.0.2 back in 2004 [1]:
```
Noteworthy changes in version 1.0.2 (2004-12-28)
------------------------------------------------
* Changed the license of the library to the GNU Lesser General Public License (LGPL), version 2.1 or later.
```
[1] https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=NEWS;h=2475a877a40817f575accd22a386bfd5f0a66aad;hb=HEAD
> gpgme: Fix license

- utils/exfatprogs/Makefile
Maintainer: me
Run tested: -
Description:
exfatprogs 1.2.1 - released 2023-05-17
======================================
CHANGES :
* fsck.exfat: Repair zero size directory.
* fsck.exfat: Four small clean-ups.
> exfatprogs: update to version 1.2.1

- admin/debian-archive-keyring/Makefile
- admin/debootstrap/Makefile
Maintainer: me
Run tested: -
Description:
Update debootstrap and debian-archive-keyring to latest stable release.
> debootstrap: update to 1.0.128+nmu2+deb12u1

- utils/pcsc-lite/Makefile
Maintainer: me
Run tested: -
Description:
Add configure argument to keep polkit disabled as per before 2.0.1.
2.0.1: Ludovic Rousseau
24 November 2023
- SCardConnect(): return SCARD_W_SECURITY_VIOLATION when needed (polkit)
- SCardCancel(): return SCARD_S_SUCCESS even if the client already finished
- polkit is enabled by default
- libpcscspy: fix a crash with NULL pointers
- Doxygen: fix SCardBeginTransaction() documentation
- fix pcscd internal thread safety issues (clang -fsanitize=thread)
- Some other minor improvements
9 June 2023
2.0.0: Ludovic Rousseau
9 June 2023
- Adjust USB drivers path at run-time via environment variable PCSCLITE_HP_DROPDIR
- Add '--disable-polkit' option
- Reset eventCounter when a reader is removed
- Add "polkit" in "pcscd …
> pcsc-lite: update to version 2.0.1

- utils/pcsc-tools/Makefile
- utils/pcsc-tools/patches/001-disable-atr.patch
Maintainer: -
Run tested: -
Description:
See https://pcsc-tools.apdu.fr/Changelog for details.
> pcsc-tools: update to version 1.7.0

- utils/base16384/Makefile
Maintainer: me
Compile tested: x86/64, Generic PC, OpenWrt 22.03.2 r19803-9a599fee93
Run tested: x86/64, Generic PC, OpenWrt 22.03.2 r19803-9a599fee93
Signed-off-by: 源 文雨 <fumiama@foxmail.com>
> base16384: bump to version 2.2.5

- net/libcurl-gnutls/Makefile
- net/libcurl-gnutls/patches/0001-gnutls-fix-build-with-disable-verbose.patch
Maintainer: me
Run tested: -
Description:
https://curl.se/changes.html#8_5_0
Pick upstream patch to fix build with gnuTLS and verbose strings removed. The patch should be removed with the next version bump.
> libcurl-gnutls: update to version 8.5.0

- utils/ccid/Makefile
- utils/ccid/patches/010-macos.patch
Maintainer: me
Run tested: -
Description:
1.5.4 - 29 October 2023, Ludovic Rousseau
- fix a regression introduced in 1.5.3
1.5.3 - 25 October 2023, Ludovic Rousseau
- Add support of - ACS ACR1552 1S CL Reader - ACS ACR1552 CL Reader - ACS ACR1581 - ACS ACR40T ICC Reader - ACS ACR40U ICC Reader - ACS WalletMate 1S CL Reader - Aktiv Rutoken SCR 3101 NFC Reader - CIRIGHT ONE PASS U2F - Dexon Tecnologias Digitais LTDA eSmartDX - Excelsecu Card reader - GHI NC001 - Identiv uTrust Token Flex - SpringCard M519 with idProduct: 0x6212 - SpringCard M519 with idProduct: 0x621A - WCMi SD5931
- parse: create output.bin file
- udev: Disable USB-persist for CCID devices
- configure: fail if flex is not found
- Some other minor improvements
1.5.2 - 31 January 2023, …
> ccid: update to version 1.5.4

- net/openvpn/Makefile
- net/openvpn/files/openvpn.init
Maintainer: @jow- @AuthorReflex 
Run tested: x86_64, APU3, latest openwrt master
Description:
OpenVPN configurations that have a uci entry, the enable/enabled option can be used to control whether the OpenVPN connection should be started at system startup or not.
OpenVPN configurations that are located under `/etc/openvpn/` are always started at system boot. To ensure that these connections can also be started later, they must **not** be started automatically during system boot. This can be prevented with the following new uci section entry in the OpenVPN configuration.
```
config globals 'globals'
option autostart '0'
```
These OpenVPN configurations can then be started later with the command `/etc/init.d/openvpn start <name>`.
> openvpn: start openvpn connection located under '/etc/openvpn' not only on system start

- net/gnunet/Makefile
Maintainer: me
Run tested: -
Description:
v0.20.0:
- GNUNET_TESTING_get_testname_from_underscore renamed to GNUNET_STRINGS_get_suffix_from_binary_name and moved from libgnunettesting to libgnuneutil
- Move GNUNET_s into libgnunetutil.
- re-introduce compiler annotation for array size in signature
- function-signature adjustment due to compiler error
- GNUNET_PQ_get_oid removed, GNUNET_PQ_get_oid_by_name improved
- Added GNUNET_PQ_get_oid_by_name
- added GNUNET_PQ_get_oid()
- Added new CCA-secure KEM and use in IDENTITY encryption
- Add KEM API to avoid ephemeral private key management
- Add new GNUNET_PQ_event_do_poll() API to gnunet_pq_lib.h
- Added API to support arrays in query results
- Improve PQ API documentation.
- API for array types extended for …
> gnunet: update to version 0.20.0

- net/snort3/Makefile
Changelog: https://github.com/snort3/snort3/releases/tag/3.1.77.0
```
o"  )~   Version 3.1.77.0
Using DAQ version 3.0.13
Using Hyperscan version 5.4.2 2023-12-20
```
Maintainer: @flyn-org @graysky2
> snort3: update to 3.1.77.0

- net/curl/Makefile
- net/curl/patches/200-no_docs_tests.patch
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.2, test https-dns-proxy works.
Description:
* https://curl.se/changes.html#8_5_0
(cherry picked from commit 6501290c17fb2c65e0fb589da94d121ff89e7d5e)
> [22.03] curl: update to 8.5.0

- libs/boost/Makefile
Compile tested: ramips/mt7621 
Description:
This commit updates boost to version 1.84.0
New available libraries:
* [Cobalt](https://www.boost.org/libs/cobalt/): Basic algorithms and types for C++20 coroutines, from Klemens Morgenstern.
* [Redis](https://www.boost.org/libs/redis/): Redis async client library built on top of Boost.Asio, from Marcelo Zimbres Silva.
More info about Boost 1.84.0 can be found [at the usual place](https://www.boost.org/users/history/version_1_84_0.html).
>  boost: Updates package to version 1.84.0

- net/strongswan/Makefile
- net/strongswan/files/swanctl.init
Compile tested: na
Run tested: aarch64/mt7622 Linksys E8450
Description:
Add interface triggers if interfaces to listen to are specified in `/etc/config/ipsec`. This fixes the "running with no instances" scenario after rebooting a router.
I've been running this for a month to good effect.
Fixes #20848
> strongswan: trigger reload when interfaces are specified

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.2.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.2.0
> lua-eco: update to 3.2.0

- net/nebula/Makefile
Maintainer: me
Description:
* https://github.com/slackhq/nebula/releases/tag/v1.8.1
> nebula: update to 1.8.1

- utils/exfatprogs/Makefile
Description:
```
exfatprogs 1.2.2 - released 2023-10-26
======================================
CHANGES :
* exfat2img: Allow dumps for read-only devices.
* fsck.exfat: Revert Repairing zero size directory.
NEW FEATURES :
* fsck.exfat: Repair duplicated filename.
* mkfs.exfat: Add the option "q" to print only error messages.
* mkfs.exfat: Add the option "U" to set volume GUID.
* tune.exfat: Add the option "U" / "-u" to set or print volume GUID.
BUG FIXES:
* fsck.exfat: Fix some out-of-bounds memory accesses.
* fsck.exfat: Change not to delete volume GUID directory entry.
```
> exfatprogs: Update to 1.2.2

- net/sshtunnel/Makefile
- net/sshtunnel/files/sshtunnel.init
- net/sshtunnel/files/uci_sshtunnel
Maintainer: @nunojpg
Compile tested: master, VirtualBox
Run tested: master, VirtualBox, TurrisOS. Both OpenSSH and Dropbear
Description:
The PR replaces https://github.com/openwrt/packages/pull/22967.
It turned out that instead of generation of a temp file we can use procd_append_param command -o "ProxyCommand=$ProxyCommand" that will make a trick with quoting.
The replacing of placeholders %h and %p is not needed because it's done by ssh client itself.
Additionally I made the code simpler and faster.
I removed the line of @lars18th from config so now the PR doesn't have his code but only mine.
> sshtunnel: Add support for "ProxyCommand" [v6]

- utils/zoneinfo/Makefile
Maintainer: me
Compile tested: TI OMAP3/4/AM33xx, default, OpenWRT master
Description:
The 2023d release of the tz code and data is available.
This release contains the following changes:
Briefly:
Ittoqqortoormiit, Greenland changes time zones on 2024-03-31.
Vostok, Antarctica changed time zones on 2023-12-18.
Casey, Antarctica changed time zones five times since 2020.
Code and data fixes for Palestine timestamps starting in 2072.
A new data file zonenow.tab for timestamps starting now.
Changes to future timestamps
Ittoqqortoormiit, Greenland (America/Scoresbysund) joins most of
the rest of Greenland's timekeeping practice on 2024-03-31, by
changing its time zone from -01/+00 to -02/-01 at the same moment
as the spring-forward transition.  Its clocks will therefore not …
> zoneinfo: Updated to 2023d release.

- lang/python/django/Makefile
Compile tested n/a
-----------------------------------------
To address
https://nvd.nist.gov/vuln/detail/CVE-2023-43665
> [23.05] django: bump to version 4.2.8

- lang/rust/Makefile
- lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
- lang/rust/patches/0002-rustc-bootstrap-cache.patch
- lang/rust/patches/0003-bump-libc-deps-to-0.2.146.patch
- lang/rust/rust-values.mk
Description:
- unexport host sccache env variable
- update to 1.75.0
changelog: https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html
> rust: Update to 1.75.0

- net/sing-box/Makefile
Maintainer: @brvphoenix 
Description:
1. Fix V2Ray transport `path` validation behavior
2. Fixes and improvements
> sing-box: Update to 1.7.7

- net/sing-box/Makefile
Maintainer: @brvphoenix 
Description:
1. Fix V2Ray transport `path` validation behavior
2. Fixes and improvements
> [23.05] sing-box: Update to 1.7.7

- utils/fuse-overlayfs/Makefile
> fuse-overlayfs: update to 1.13

- lang/python/python-websocket-client/Makefile
> python-websocket-client: update to 1.7.0

- lang/python/python-greenlet/Makefile
Description:
updates and add the host that python-gevent needs
> python-greenlet: update version 3.0.2

- lang/python/python-dbus-fast/Makefile
Maintainer: @QuintinHill 
Description:
> python-dbus-fast: update version 2.21.0

- lang/python/pyproject-metadata/Makefile
Maintainer: @predators46 
Description:
pyproject-metadata: add pyproject-metadata
https://pypi.org/project/pyproject-metadata/
source code
https://github.com/FFY00/python-pyproject-metadata
add the pyproject-metadata package that numpy requires
> pyproject-metadata: add pyproject-metadata

- lang/python/python-docker/Makefile
> python-docker: Update to 7.0.0

- lang/python/python-distro/Makefile
> python3-distro: update to version 1.9.0

- utils/syncthing/Makefile
- utils/syncthing/files/syncthing.init
The goup does not always have the same name as user, and when I try to run syncthing with nobody I get an error. Since nobody belongs to the group nogroup, I added some code to find out which group user belongs to.
Maintainer:  @aparcar @brvphoenix
Description:
> syncthing: fix group in syncthing.init

- lang/python/python-bleak/Makefile
- lang/python/python-dbus-fast/Makefile
Maintainer: me
Compile tested: fairly trivial will rely on CI for this.
Run tested: ath79 wndr3700v4 manual installed dependency
Description: fix up of 64fa106.
> Add missing python3-bleak dependency

- net/openvpn/Makefile
- net/openvpn/files/etc/hotplug.d/openvpn/01-user
- net/openvpn/files/openvpn.init
Maintainer: @mkrkn  @neheb
Compile tested: aarch64, cortex-a53, OpenWRT Master
Run tested: Dynalink DL-WRX36
Description:
[A previous commit](https://github.com/openwrt/packages/commit/f8a8b71e26b9bdbf86fbb7d4d1482637af7f3ba4) from @miska has added more script event options. However it looked like that commit was not complete as it stops the use of the script events route-up, route-pre-down, and ipchange when those are placed in the openvpn config file.
This PR fixes a regression that makes it problematic to specify certain event options in the OpenVPN configuration file.
Discussion in [this thread](https://forum.openwrt.org/t/openvpn-custom-route-up-script-in-23-05-rc2/167105/13) and [here](https://forum.openwrt.org/t/openvpn-route-up-and-route-pre-down-broken-in-23-05/176568)
Please …
> Openvpn: add missing script event options

- net/snort3/Makefile
This PR adds the ability of snort to process rules that target swf and pdf files requiring lzma decompression to look for
malicious payloads therein.  This change only increases the size of the snort3 executable by a fraction of a KB and the added
dependency of liblzma (based on currently offered 5.4.4-1) is only a 169 KB shared object.  Based on CPU requirements of snort,
x86 users likely represent the majority user-base and space their rootfs is not an issue as it may be for lower-powered SoCs.
Size of snort3-3.1.76.0-2: 7354403 bytes
Size of snort3-3.1.76.0-3: 7354435 bytes
Maintainer: me and @flyn-org
> snort3: compile with lzma support

- net/snort3/Makefile
- net/snort3/files/main.uc
- net/snort3/files/snort.config
- net/snort3/files/snort.uc
Allow use of rules as-defined, and don't override their actions.  This is generally the best way to use the ruleset, and overriding their actions should only be undertaken when you fully understand how it affects their use.
Maintainer: @flyn-org @graysky2 
> snort3: add missing action-override option

- libs/libsodium/Makefile
- libs/libsodium/patches/001-revert-f5076db5f8ef27.patch
- libs/libsodium/patches/100-minimal-build-with-ed25519-core.patch
Maintainer: @damianorenfer 
Compile and run-tested: bcm2711 (rpi4), mt7622 (Linksys E8450), ath79 (TP-Link Archer C7 v5)
Fixes https://github.com/openwrt/packages/issues/22171.
Unfortunately, latest libsodium-1.0.19.tar.gz extracts to libsodium-stable. That's why I had to update PKG_BUILD_DIR, maybe (hopefully) this can be reverted on next libsodium release.
> libsodium: Update to 1.0.19 and fix patches

- net/wifischedule/Makefile
- net/wifischedule/net/usr/bin/wifi_schedule.sh
Maintainer: @newkit
Compile tested: mediatek/fiilogic Sinovoip Banana Pi R3, snapshot kernel 6.1.69
Run tested: mediatek/fiilogic Sinovoip Banana Pi R3, snapshot kernel 6.1.69
Description:
1. Make the new `startup()` function in `/usr/bin/wifi_schedule.sh`
respect the global `enabled` config flag; in particular, make no
changes to `/etc/config/wireless` when wifi_schedule is disabled.
2. Make the new `/etc/init.d/wifi_schedule` service script executable.
Fixes: e0d7181a6
Closes: #22973
Closes: #22988
> wifischedule: fix startup problems

- net/nginx/Makefile
Maintainer: Thomas Heil <heil@terminal-consulting.de> Christian Marangi <ansuelsmth@gmail.com>
Compile tested: X86 Fedora
Run tested: Ax3600
Description:
Update nginx to the latest version.
> nginx: update to 1.25.3

- net/nebula/Makefile
Maintainer: me
Description:
* https://github.com/slackhq/nebula/releases/tag/v1.8.1
(cherry picked from commit 731d594ee31df8c0fadf980f29939461d13bc395)
> [23.05] nebula: update to 1.8.1

- sound/shairport-sync/Makefile
Maintainer: @mikebrady  / @thess 
**Compile tested:** 
- arch: armv8
- model: NanoPi R4S
- OpenWRT version: 23.05
**Run tested:** 
- arch: armv8
- model: NanoPi R4S
- OpenWRT version: OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256
- tests:
-- [x] shairport-sync 4.3.2 installed on NanoPi R4S
-- [x] shairport-sync -V reports 'pipe' support
```
root@test-router-hw1:~# /usr/bin/shairport-sync -V
4.3.2-libdaemon-OpenSSL-Avahi-ALSA-pipe-soxr-metadata-sysconfdir:/etc
```
-- [x] shairport-sync to write to default pipe on NanoPi R4S with UCI's shairport-sync's 'pipe-name' set to /etc/shairport-sync-audio
0.
```
root@test-router-hw1:~# ls -alh /tmp/shairport-sync-*
prw-rw-rw-    1 root     root           0 Dec 20 11:58 /tmp/shairport-sync-audio
prw-rw-rw- …
```
> shairport-sync: pipe audio backend support enabled

- net/openssh/Makefile
- net/openssh/patches/010-better_fzero-call-detection.patch
Release notes: https://www.openssh.com/txt/release-9.6
Maintainer:  @SibrenVasse, @tripolar 
Compile tested: bcm2711, rpi4, master
Run tested: bcm2711, rpi4, master
> openssh: bump to 9.6p1

- net/sing-box/Makefile
Maintainer: @brvphoenix 
Description:
New features for v1.8.0:
1. Migrate cache file from Clash API to independent options
2. Introducing Rule Set
3. Add `sing-box geoip`, `sing-box geosite` and `sing-box rule-set` commands
4. Allow nested logical rules
5. Independent `source_ip_is_private` and `ip_is_private` rules
6. Add context to JSON decode error message
7. Reject internal fake-ip queries
8. Add GSO support for TUN and WireGuard system interface
9. Add `idle_timeout` for URLTest outbound   
...
For details, please see https://github.com/SagerNet/sing-box/releases/tag/v1.8.0
Please read the migration guide before upgrading: https://sing-box.sagernet.org/migration/
> sing-box: update to 1.8.0

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* the pause command used to incorrectly cause block-lists reload, this has been fixed in this version
(cherry picked from commit dfeeabbebf7fa337f02fa24d40a488e2acfccbbb)
> [23.05] adblock-fast: bugfix: pause command

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* the pause command used to incorrectly cause block-lists reload, this has been fixed in this version
> adblock-fast: bugfix: pause command

- net/uspot/Makefile
Maintainer: me
Compile tested: ath79/generic, ramips/mt7621, x86/64
Run tested: ath79/generic, ramips/mt7621, x86/64 - OpenWrt 23.05
Description: uspot update to Git HEAD (2024-01-09)
**Please cherry-pick into 23.05 once merged :)**
> uspot: update to Git HEAD (2024-01-09)

- net/knxd/Makefile
- net/knxd/patches/0100-version.patch
Maintainer: me
Description:
new upstream release 0.14.60
> knxd: bump to upstream version 0.14.60

- .github/workflows/formal.yml
This goes in accordance with the Linux Kernel:
> using a known identity (sorry, no anonymous contributions.)
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n442
> ci: no longer require real name

- net/sing-box/Makefile
Maintainer: @brvphoenix 
Description:
New features for v1.8.0:
1. Migrate cache file from Clash API to independent options
2. Introducing Rule Set
3. Add `sing-box geoip`, `sing-box geosite` and `sing-box rule-set` commands
4. Allow nested logical rules
5. Independent `source_ip_is_private` and `ip_is_private` rules
6. Add context to JSON decode error message
7. Reject internal fake-ip queries
8. Add GSO support for TUN and WireGuard system interface
9. The legacy LWIP stack has been deprecated and removed
10. Add `idle_timeout` for URLTest outbound
11. Added some new uTLS fingerprints
...
Release notes: https://github.com/SagerNet/sing-box/releases/tag/v1.8.0
The new version has some breaking changes and may stop working after …
> [23.05] sing-box: Update to 1.8.0

- lang/node/Makefile
- lang/node/patches/007-fix_host_build_on_macos.patch
- lang/node/patches/204-v8_gyp.patch
- lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch
Run tested: (qemu 8.2.0) aarch64
Description:
* crypto: update root certificates to NSS 3.95 (Node.js GitHub Bot)
* doc: add MrJithil to collaborators (Jithil P Ponnan)
* doc: add Ethan-Arrowood as a collaborator (Ethan Arrowood)
* (SEMVER-MINOR) esm: add import.meta.dirname and import.meta.filename (James Sumners)
* fs: add c++ fast path for writeFileSync utf8 (CanadaHonk)
* (SEMVER-MINOR) module: remove useCustomLoadersIfPresent flag (Chengzhong Wu)
* (SEMVER-MINOR) module: bootstrap module loaders in shadow realm (Chengzhong Wu)
* (SEMVER-MINOR) src: add --disable-warning option (Ethan Arrowood)
* [SEMVER-MINOR) src: create per isolate proxy env template (Chengzhong Wu)
* (SEMVER-MINOR) src: make …
> node: bump to v20.11.0

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.24.0)
It recreates all the running containers on `docker compose up`
> docker-compose: Update to version 2.24.0

- net/tailscale/Makefile
Modify Makefile to combine tailscale and tailscaled according to Tailscale documentatio (https://tailscale.com/kb/1207/small-tailscale)
Maintainer: Jan Pavlinec
Compile tested: Debian 12, x86_64, Openwrt HEAD
Run tested: APU2 x86_64, OpenWrt 23.05.2
Description:
Modify Makefile to combine tailscale and tailscaled according to [Tailscale documentation](https://tailscale.com/kb/1207/small-tailscale). The new package is called 'tailscale'.
This resulted for the x86_64 in an exec of 31MB + the symlink. Before it was 29MB (tailscaled) and 10MB (tailscale)
Issue:
<del>Right now you have to force deinstall the package 'tailscaled' before you can install the combined 'tailscale/d'. Trying to update without removing 'tailscaled' results in an error that 'tailscaled' is already provided by another …
> tailscale: create combined tailscale/tailscaled

- libs/openblas/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/622340f6c10a492c03e6d0c0ee004da1c43270bc
Run tested: x86  https://github.com/openwrt/openwrt/commit/622340f6c10a492c03e6d0c0ee004da1c43270bc
> openblas: bump to version 0.3.26

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* allow top-level domains in the blocked-domains options fixes https://github.com/openwrt/packages/issues/23125
> adblock-fast: update to 1.1.1-3

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* allow top-level domains in the blocked-domains options fixes https://github.com/openwrt/packages/issues/23125
(cherry picked from commit 0f059b6523f3720441cf608cbd9769265d859de6)
> [23.05] adblock-fast: update to 1.1.1-3

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.24.1)
> docker-compose: Update to version 2.24.1

- lang/python/python-jsonschema/Makefile
> python-jsonschema: Update to 4.21.0

- net/snort3/Makefile
Upstream bump
```
o"  )~   Version 3.1.78.0
Copyright (C) 2014-2024 Cisco and/or its affiliates. All rights reserved.
Using DAQ version 3.0.14
Using Hyperscan version 5.4.2 2024-01-15
Using LZMA version 5.4.4
```
Maintainer: me
> snort3: update to 3.1.78.0

- utils/bcm27xx-eeprom/Makefile
- utils/bcm27xx-eeprom/patches/0001-rpi-eeprom-update-OpenWrt-defaults.patch
- utils/bcm27xx-eeprom/patches/0002-rpi-eeprom-update-change-default-include-path.patch
- utils/bcm27xx-eeprom/patches/0003-rpi-eeprom-update-chmod-silent-f-is-not-supported.patch
- utils/bcm27xx-eeprom/patches/0004-rpi-eeprom-config-replace-nano-with-vi-as-default-ed.patch
Maintainer: me
Compile tested: bcm27xx/bcm2711
Run tested: bcm27xx/bcm2711
Description: Updates Raspberry Pi 4 EEPROM and adds Raspberry Pi 5 EEPROM support.
Adds separate packages for Raspberry Pi 4 (bcm2711-eeprom) and Raspberry Pi 5 (bcm2712-eeprom).
> bcm27xx-eeprom: update and split into bcm2711/bcm2712

- net/tailscale/Makefile
Run tested: `aarch64_cortex-a53` @ SNAPSHOT
> tailscale: Update to 1.58.0

- lang/python/python-jsonschema/Makefile
> python-jsonschema: Update to 4.21.1

- lang/python/python-orjson/Makefile
Relevant changes since 3.9.10:
- Improve performance of serializing. str is significantly faster. Documents using dict, list, and tuple are somewhat faster.
- FIXED: Minimal musllinux_1_1 build due to sporadic CI failure.
Maintainer: me
Compile tested: arm_cortex-a9_vfpv3-d16, Linksys WRT1900ACS, master
Run tested: arm_cortex-a9_vfpv3-d16, Linksys WRT1900ACS, 23.05.0 r23497-6637af95aa
Description:
Updates python-orjson from 3.9.10 -> 3.9.12. Fixes from upstream include:
- Improve performance of serializing. str is significantly faster. Documents using dict, list, and tuple are somewhat faster.
- FIXED: Minimal musllinux_1_1 build due to sporadic CI failure.
> python-orjson: update to version 3.9.12

- libs/libvpx/Makefile
There is not a single CVEs under cpe:/a:john_koleszar:libvpx so use cpe:/a:webmproject:libvpx:
https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Awebmproject%3Alibvpx
Maintainer: @luizluca
> libs/libvpx: fix PKG_CPE_ID

- libs/apr/Makefile
There is not a single CVE under cpe:/a:apache:apr
so use cpe:/a:apache:portable_runtime:
https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Aapache%3Aportable_runtime
> libs/apr: fix PKG_CPE_ID

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.24.3)
> docker-compose: Update to version 2.24.3

- net/tcpreplay/Makefile
There is not a single CVE under cpe:/a:appneta:tcpreplay so use cpe:/a:broadcom:tcpreplay:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:broadcom:tcpreplay
> net/tcpreplay: fix PKG_CPE_ID

- utils/cryptsetup/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:cryptsetup_project:cryptsetup
> utils/cryptsetup: assign PKG_CPE_ID

- net/tailscale/Makefile
Run tested: `aarch64_cortex-a53` @ SNAPSHOT
> tailscale: Update to 1.58.2

- net/natmap/Makefile
Compile tested: armvirt-64, snapshot; ramips-mt7621, 23.05
Description:
1. Update to 20240126.
> natmap: update to 20240126

- net/sing-box/Makefile
Maintainer: me
Description:
This release contains some bug fixes.
Changelogs: https://github.com/SagerNet/sing-box/compare/v1.8.0...v1.8.4
> sing-box: update to 1.8.4

- libs/libdaq3/Makefile
Changelog: https://github.com/snort3/libdaq/releases/tag/v3.0.14
> libdaq3: update to 3.0.14

- net/sing-box/Makefile
Maintainer: me
Description:
Cherry picked from commit 49ab3e0018948ebcbad676f5640c3ca7e3984db5.
> [23.05] sing-box: update to 1.8.4

- net/natmap/Makefile
Compile tested: armvirt-64, snapshot; ramips-mt7621, 23.05
Description:
1. Update to 20240126.
> [openwrt-22.03] natmap: update to 20240126

- net/natmap/Makefile
Compile tested: armvirt-64, snapshot; ramips-mt7621, 23.05
Description:
1. Update to 20240126.
> [openwrt-23.05] natmap: update to 20240126

- lang/python/python-bleak/Makefile
- lang/python/python-dbus-fast/Makefile
Maintainer: me
Compile tested: None for backport
Run tested: None for backport
Description: https://github.com/openwrt/packages/pull/22919 and https://github.com/openwrt/packages/pull/22965 backports to 23.05.
CC: @predators46
> [23.05] Add missing python3-bleak dependency

- lang/python/python-dotenv/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/theskumar/python-dotenv/releases/tag/v1.0.1)
> python-dotenv: update to v1.0.1

- .github/workflows/check-autorelease-deprecation.yml
- .github/workflows/formal.yml
- .github/workflows/multi-arch-test-build.yml
Description:
Fix Node.js 16 deprecation warning.
Ref: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> ci: bump checkout/upload-artifact to v4

- net/knot/Makefile
Description:
- Release upgrade (https://www.knot-dns.cz/2024-01-24-version-334.html)
> knot: update to version 3.3.4

- multimedia/gst1-plugins-bad/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:freedesktop:gst-plugins-bad
> multimedia/gst1-plugins-bad: assign PKG_CPE_ID

- libs/freetype/Makefile
There is not a single CVE under cpe:/a:freetype:freetype2 so use cpe:/a:freetype:freetype:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:freetype:freetype
> libs/freetype: fix PKG_CPE_ID

- utils/domoticz/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:domoticz:domoticz
> utils/domoticz: assign PKG_CPE_ID

- libs/libinput/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:freedesktop:libinput
> libs/libinput: assign PKG_CPE_ID

- net/fail2ban/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:fail2ban:fail2ban
> net/fail2ban: assign PKG_CPE_ID

- utils/pax-utils/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:gentoo:pax-utils
> utils/pax-utils: assign PKG_CPE_ID

- lang/python/python-docker/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:docker:docker-py
> lang/python/python-docker: assign PKG_CPE_ID

- libs/libmbim/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:freedesktop:libmbim
Maintainer: @Linaro1985
> libs/libmbim: assign PKG_CPE_ID

- utils/augeas/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:augeas:augeas
> utils/augeas: assign PKG_CPE_ID

- utils/cgroupfs-mount/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:cgroupfs-mount_project:cgroupfs-mount
> utils/cgroupfs-mount: assign PKG_CPE_ID

- net/openvpn/Makefile
- net/openvpn/files/openvpn.init
Maintainer: @mkrkn  @neheb
Compile tested: armv7, cortexA15, OpenWRT 23.05
Run tested: Linksys EA8500
Compile tested: armv8, cortexA53, OpenWRT main
Run tested: Dynalink DL-WRX36
Description:
Script-security is always 2 and cannot be changed from the openvpn config file due to a missing rule in openvpn.init.
This is discussed in issue #23014
This patch adds the missing rule in openvpn.init to parse script-security from the openvpn config file.
Signed-off-by: Erik Conijn <egc112@msn.com>
> openvpn: add missing script-security

- multimedia/ffmpeg/Makefile
Maintainer: @thess @antonlacon
Compile tested: bcm2711/RPi4B
Run tested: bcm2711/RPi4B (using h264_v4l2m2m encoder/decoder)
Description:
Enable V4L2 support on ffmpeg-full package.
> ffmpeg: add V4L2 support

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.24.4)
> docker-compose: Update to version 2.24.4

- utils/vim/Makefile
vim is licensed under its own Vim license:
https://spdx.org/licenses/Vim.html
> utils/vim: add license info

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.24.5)
> docker-compose: Update to version 2.24.5

- libs/libjpeg-turbo/Makefile
Compile tested: ARMv7, Linksys WRT3200ACM, master branch
Description:
- Switch source URL to Github since upstream migrated there
- Remove CMake options which are obsolete or match default values
- Don't disable arithmetic encoding/decoding since it's the standard
> libjpeg-trubo: update to 3.0.2

- libs/tiff/Makefile
Compile tested: ARMv7, Linksys WRT3200ACM, master branch
Description:
- Don't set CMake options which are on by default
> tiff: update to 4.6.0

- devel/automake/Makefile
automake is licensed under GPL-2.0-or-later, not GPL-3.0-or-later: https://git.savannah.gnu.org/cgit/automake.git/tree/COPYING indeed switch to GPL-3.0-or-later was reverted a long time ago (i.e. before its addition to openwrt) by
https://git.savannah.gnu.org/cgit/automake.git/commit/?id=fcf2f56062e384455ec8b1aed943af33f20c27c7
While at it, add the license file
Fixes: c6ac1e3f76ecd92d02d82c5729bbd1f2bd64922b
> devel/automake: fix license

- net/tor/Makefile
tor is licensed under BSD-3-Clause
Maintainer: @hauke 
> net/tor: add license

- libs/libev/Makefile
libev is licensed under BSD-2-Clause or GPL-2.0-or-later since its addition to openwrt
While at it, assign PKG_LICENSE_FILES
Fixes: 67b39f8f9b703e2cf95616b8e591ec76278a5846
Compile tested: Not neeed
> libs/libev: fix license

- libs/libdaq3/Makefile
> libs/libdaq3: assign PKG_LICENSE_FILES

- net/nebula/Makefile
- net/nebula/files/README.md
- net/nebula/files/nebula.upgrade
Maintainer: me
Description:
The following fixes have been applied to Makefile:
* fix the nebula license type
* add PKG_CPE_ID
* remove unneeded call to Build/Compile
* add leading spaces to descriptions
* add Package/nebula/conffiles definition
* remove unneeded /lib/upgrade/keep.d files
* no longer install actual license file
Kudos to @BKPepe for feedback on a similar package which lead to these fixes
> nebula: update to 1.8.2-2

- libs/libpam/Makefile
linux-pam:linux-pam is a better CPE ID than kernel:linux-pam as this CPE ID has the latest CVEs (whereas kernel:linux-pam only has a SUSE-specific CVE): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:linux-pam:linux-pam
Fix: 6f74b0c4f15a095b1069a8aaeb19a32dfbc7539a
> libs/libpam: fix PKG_CPE_ID

- net/krb5/Makefile
mit:kerberos_5 is a better CPE ID than mit:kerberos as this CPE ID has the latest CVEs (whereas mit:kerberos only has CVEs until 2018): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:mit:kerberos_5
Fix: 299e5b0a9bce19d6e96cb9ff217028b36ee2dd36
> net/krb5: fix PKG_CPE_ID

- libs/libpsl/Makefile
> libpsl: update to 0.21.5

- libs/vips/Makefile
libvips:libvips is a better CPE ID than vips:vips as this CPE ID has the latest CVEs (whereas vips only has an old CVE from 2010):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:libvips:libvips
Fix: 299e5b0a9bce19d6e96cb9ff217028b36ee2dd36
> libs/vips: fix PKG_CPE_ID

- net/nebula/Makefile
- net/nebula/files/README.md
- net/nebula/files/nebula.upgrade
Maintainer: me
Description:
The following fixes have been applied to Makefile:
* fix the nebula license type
* add PKG_CPE_ID
* remove unneeded call to Build/Compile
* add leading spaces to descriptions
* add Package/nebula/conffiles definition
* remove unneeded /lib/upgrade/keep.d files
* no longer install actual license file
* add the README file
Kudos to @BKPepe and @1715173329 for feedback which lead to these fixes
(cherry picked from commit ae22bea8ddda7dd4409ea436e34c39073c954d8d)
> [23.05] nebula: update to 1.8.2-2

- utils/squashfs-tools/Makefile
There is not a single CVE linked to phillip_lougher:squashfs so use squashfs-tools_project:squashfs-tools instead:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:squashfs-tools_project:squashfs-tools
> utils/squashfs-tools: fix PKG_CPE_ID

- admin/sudo/Makefile
sudo_project:sudo is a better CPE ID than todd_miller:sudo as this CPE ID has the latest CVEs (whereas todd_miller:sudo only has CVEs up to 2016): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:sudo_project:sudo
Fixes: 8ce9f30c421255c514b1b2e41fc92eafd7976583 (sudo: Update to 1.8.24)
> admin/sudo: fix PKG_CPE_ID

- net/curl/Makefile
- net/curl/patches/200-no_docs_tests.patch
Maintainer: me
Description:
* https://curl.se/changes.html#8_6_0
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>
(cherry picked from commit 0f2c98d53f1aec96c21a707fc0e1a01b5a53a840)
> [22.03] curl: update to 8.6.0

- net/curl/Makefile
- net/curl/patches/200-no_docs_tests.patch
Maintainer: me
Description:
* https://curl.se/changes.html#8_6_0
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>
(cherry picked from commit 0f2c98d53f1aec96c21a707fc0e1a01b5a53a840)
> [23.05] curl: update to 8.6.0

- net/cloudflared/files/cloudflared.config
- net/cloudflared/files/sample_config.yml
The config.yml is an example of a tunnel local configuration. But the cloudlfared treat it as a real config and fails to start. So to avoid problems let's comment all the statements.
The `url: http://localhost:8000` is not a valid config option.
Additionally add a smale of configuring ingres rules.
The cloudflared.config has missing option token.
Compile tested: not needed
Run tested: VBox
> cloudflared: refine config.yml

- lang/python/python-aiohttp/Makefile
aiohttp:aiohttp is a better CPE ID than aio-libs_projet:aiohttp as this CPE ID has the latest CVEs (whereas aio-libs_project:aiohttp only has one CVE from 2018):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:aiohttp:aiohttp
Fixes: 2edf5034f1c09fe60af52087abe7b6fcef9433fc (python-aiohttp: add a new package)
> lang/python/python-aiohttp: fix PKG_CPE_ID

- libs/tiff/Makefile
tiff is licensed under its own "libtiff" license and not BSD-3-Clause
Fixes: 364de5bc3f16eba42f93d36e848b998b3579e39e (tiff: add licensing information)
> libs/tiff: fix license

- net/nmap/Makefile
- net/nmap/patches/030-ncat-drop-ca-bundle.patch
Maintainer: @nunojpg
Compile-tested: ath79/generic (TP-Link Archer C7 v2), mediatek/filogic (GL.iNet GL-MT6000)
Run-tested: mediatek/filogic (GL.iNet GL-MT6000)
Description:
- nmap: ncat: use default CA bundle
- nmap: unify SSL dependencies
> Nmap: adjust SSL dependencies

- libs/libgd/Makefile
libgd is licensed under its own "GD" license and not MIT
Fixes: 60feea09c9d343f648045e5e85e7788e75d4e039 (libgd: import from oldpackages, add myself as maintainer, add license...)
> libs/libgd: fix license

- lang/python/python-urllib3/Makefile
There is not a single CVE linked to urllib3_project:urllib3 so use python:urllib3 instead:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:python:urllib3
Fixes: 6dcaa769d8ce8921dc3bfaf78ab9a8c1cef4a9b9 (python-urllib3: update to version 1.25)
> lang/python/python-urllib3: fix PKG_CPE_ID

- lang/python/python-requests/Makefile
There is not a single CVE linked to python-requests:requests so use python:requests instead:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:python:requests
Fixes: ceadbcbb64de727c3a974e552d9a723d532e4e40 (treewide: add PKG_CPE_ID for cvescanner)
> lang/python/python-requests: fix PKG_CPE_ID

- libs/redis/Makefile
There is not a single CVE linked to pivotal_software:redis so use redis:redis instead:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:redis:redis
Fixes: ceadbcbb64de727c3a974e552d9a723d532e4e40 (treewide: add PKG_CPE_ID for cvescanner)
> libs/redis: fix PKG_CPE_ID

- net/vsftpd/Makefile
vsftpd_project:vsftpd is a better CPE ID than beasts:vsftpd as this CPE ID has the latest CVEs (whereas beasts:vsftpd only has CVEs up to 2015): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:vsftpd_project:vsftpd
Fixes: 1371b7be878382b8b52cd73ff72a3a41d28013c4 (vsftpd: Fix compilation without ECC or deprecated APIs)
Maintainer:
> net/vsftpd: fix PKG_CPE_ID

- net/tinc/Makefile
tinc-vpn:tinc is a better CPE ID than tinc:tinc as this CPE ID has the latest CVEs (whereas tinc:tinc only has CVEs up to 2002): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:tinc-vpn:tinc
Maintainer: @ErwanMAS
> net/tinc: fix PKG_CPE_ID

- net/tinyproxy/Makefile
tinyproxy_project:tinyproxy is a better CPE ID than banu:tinyproxy as this CPE ID has the latest CVEs (whereas banu:tinyproxy only has CVEs up to 2012):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:tinyproxy_project:tinyproxy
> net/tinyproxy: fix PKG_CPE_ID

- utils/tmux/Makefile
tmux_project:tmux is a better CPE ID than nicholas_marriott:tmux as this CPE ID has the latest CVE (whereas nicholas_marriott:tmux only has a CVE from 2011):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:tmux_project:tmux
> utils/tmux: fix PKG_CPE_ID

- utils/zsh/Makefile
zsh:zsh is a better CPE ID than zsh_project:zsh as this CPE ID has the latest CVEs (whereas zsh_project:zsh only has CVEs up to 2017): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:zsh:zsh
Fixes: ff056fcffcacf2632505bb108bf8e8c2a3cef09c (zsh: Update to 5.6.2)
Maintainer: @msva
> utils/zsh: fix PKG_CPE_ID

- net/boinc/Makefile
boinc_project:boinc has never been a valid CPE ID so use rom_walton:boinc instead:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:rom_walton:boinc
Fixes: 9c2bd865c715cad8646157d6bbfb669d9970c322 (boinc: new package for distributed computing/data acquisition)
Maintainer: @N30dG 
> net/boinc: fix PKG_CPE_ID

- net/ntpd/Makefile
Replace "Unique" by the standard SPDX identifier for NTP license: https://spdx.org/licenses/NTP.html
Fixes: 1aff45c6dd36f2a5875eadaeae2ed93da8ff6d45 (ntpd: add SPDX license information)
Maintainer:
> net/ntpd: fix license

- utils/zoneinfo/Makefile
Maintainer: me
Compile tested: TI OMAP3/4/AM33xx, default, OpenWRT master
Description:
The 2024a release of the tz code and data is available.
This release contains the following changes:
Briefly:
Kazakhstan unifies on UTC+5 beginning 2024-03-01.
Palestine springs forward a week later after Ramadan.
zic no longer pretends to support indefinite-past DST.
localtime no longer mishandles Ciudad Ju?rez in 2422.
Changes to future timestamps
Kazakhstan unifies on UTC+5.  This affects Asia/Almaty and
Asia/Qostanay which together represent the eastern portion of the
country that will transition from UTC+6 on 2024-03-01 at 00:00 to
join the western portion.  (Thanks to Zhanbolat Raimbekov.)
Palestine springs forward a week later than previously predicted
in 2024 and 2025.  (Thanks …
> zoneinfo: Updated to 2024a release

- lang/python/python-paho-mqtt/Makefile
python-paho-mqtt is licensed under EPL-2.0, not EPL-1.0, since version 1.6.0 and
https://github.com/eclipse/paho.mqtt.python/commit/fabe7500fb6fde31fd98c619e0117d1c651fd18d
While at it, add LICENSE.txt to PKG_LICENSE_FILES
Fixes: 784f2a519bb8cdfaa973070f65ff9a3a481e5cd1 (python-paho-mqtt: bump to version 1.6.1)
> lang/python/python-paho-mqtt: fix license

- utils/lrzsz/Makefile
PKG_CPE_ID was missing ":lrzsz"
Fixes: 6d6c4b21b5e22a9f1058db5b61521a298e00a5f0 (lrzsz: update to v0.12.21rc and fix a CVE)
Maintainer: @kuoruan
> utils/lrzsz: fix PKG_CPE_ID

- libs/expat/Makefile
There is not a single CVE linked to libexpat:expat so use libexpat_project:libexpat instead:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:libexpat_project:libexpat
Fixes: 70c62ef2d77aef5d8a27ccca2b147bc2a69dc7f8 (expat: update to version 2.2.7 (security fix))
> libs/expat: fix PKG_CPE_ID

- libs/libidn2/Makefile
There is not a single CVE linked to libidn2_project:libidn2 so use gnu:libidn2 instead:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:gnu:libidn2
Fixes: ceadbcbb64de727c3a974e552d9a723d532e4e40 (treewide: add PKG_CPE_ID for cvescanner)
Maintainer:
> libs/libidn2: fix PKG_CPE_ID

- net/miniupnpc/Makefile
cpe:/a:miniupnp_project:miniupnpc is the correct CPE ID for miniupnpc: https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:miniupnp_project:miniupnpc
Maintainer:
> net/miniupnpc: fix PKG_CPE_ID

- multimedia/motion/Makefile
motion_project:motion is a better CPE ID than lavrsen:motion as this CPE ID has the latest CVE (whereas lavrsen:motion only a CVE from 2008): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:motion_project:motion
> multimedia/motion: fix PKG_CPE_ID

- net/nbd/Makefile
There is not a single CVE linked to network_block_device:nbd so use network_block_device_project:network_block_device instead: https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:network_block_device_project:network_block_device
Maintainer: @marcin1j
> net/nbd: fix PKG_CPE_ID

- lang/python/python-pip/Makefile
There is not a single CVE linked to python:pip so use pypa:pip instead: https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:pypa:pip
Moreover, CPE_ID missed PKG_ prefix
Fixes: eee273507b868ad5f6f7e744d513c85330967906 (python3: Split pip into separate source package)
Maintainer: @jefferyto
> lang/python/python-pip: fix PKG_CPE_ID

- utils/gpsd/Makefile
gpsd_project:gpsd is a better CPE ID than berlios:gps_daemon as this CPE ID has the latest CVEs (whereas berlios:gps_daemon only has one CVE from 2004):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:gpsd_project:gpsd
Maintainer: @psidhu
> utils/gpsd: fix PKG_CPE_ID

- utils/ntfs-3g/Makefile
tuxera:ntfs-3g is a better CPE ID than ntfs-3g:ntfs-3g as this CPE ID has the latest CVEs (whereas ntfs-3g:ntfs-3g only has one CVE from 2007): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:tuxera:ntfs-3g
> utils/ntfs-3g: fix PKG_CPE_ID

- utils/zstd/Makefile
Description:
- Don't set Meson options which are matching defaults
> zstd: update to 1.5.5

- lang/python/python-ble2mqtt/Makefile
- lang/python/python-dbus-fast/Makefile
Maintainer: me
Description: minor version bumps of two packages (https://github.com/openwrt/packages/pull/23173) backported to 23.05.
>  [23.05] python-ble2mqtt: update to 0.2.2

- utils/telldus-mqtt/Makefile
- utils/telldus-mqtt/files/telldus-mqtt
Extends functionality of exisiting telldus-core package
Maintainer: @PeterFromSweden
Compile tested: bcm2708/RPiB/openwrt23.05.0, mvebu/cortexa9/openwrt23.05.0
Run tested: bcm2708/RPiB/openwrt23.05.0, mvebu/cortexa9/openwrt23.05.0
Description:
Extends functionality of exisiting telldus-core package
> telldus-mqtt: add new package in utils

- net/snort3/Makefile
- net/snort3/files/main.uc
- net/snort3/files/nftables.uc
- net/snort3/files/snort-mgr
- net/snort3/files/snort-rules
- net/snort3/files/snort.uc
Reporting
- Use json alert data for 10x speed improvement in report generation
- Include both gid and sid, plus packet direction in report output
- Add by-date incident filtering
- Add verbose mode which displays actual rules triggered and their source
- Attempt to look up host names from IPs in verbose mode
- Clean up display of port number involved in incidents
Rules
- Complete downloader for subscription rules using oinkcode (only tested with snort.org's "free" tier subscription)
- Auto-detect multiple rules files and include them in lua 'ips.rules'
- Add '--backup' option to copy out current rules before installing new
- Add '--persistent' option to 'snort-rules', storing in persistent location
CLI interface
- Completely rework command line option parsing in all user scripts
- Allow …
> snort3: finish up several incomplete capabilities

- libs/libsndfile/Makefile
Description:
- Update package URL to the official one
- Update source URL to the official one
- Modernize CMake options
- Fixup pkgconfig file
- Enable mpg123 support per users request (+7kB)
> libsndfile: update to 1.2.2

- libs/libstrophe/Makefile
Maintainer: @changeway 
Description:
- Use common Github URL
- Add missing zlib dependency
> libstrophe: update 0.13.0

- lang/perl-time-moment/Makefile
Maintainer: me
Compile tested: arm_cortex-a9_vfpv3-d16, Linksys WRT1900ACS, OpenWrt 23.05.0
Run tested: arm_cortex-a9_vfpv3-d16, Linksys WRT1900ACS, OpenWrt 23.05.0
Tests:
- Loaded module:
```
root@storage:/tmp# perl -MTime::Moment -e '1'
root@storage:/tmp# 
```
- Executed test file from module: `https://raw.githubusercontent.com/chansen/p5-time-moment/master/eg/us_federal_holidays.pl`. NOTE: This script (not the module) requires the "enum" module, which is pure perl, so can be via CPAN through `perl -MCPAN -e 'install enum'` for the purposes of testing this script.
```
root@storage:/tmp# perl us_federal_holidays.pl 
ok 1 - U.S. federal holidays for year 1997
ok 2 - U.S. federal holidays for year 1998
ok 3 - U.S. federal holidays for year 1999
ok 4 - U.S. federal holidays for year 2000
ok …
```
> perl-time-moment: new module for Time::Moment v0.44

- CONTRIBUTING.md
Compile tested: not applicable here
Run tested: not applicable here
Description:
As a new contributor to this repository, the language in `CONTRIBUTING.md` was unclear and resulted in some unnecessary back and forth with reviewers. I believe these clarifications should assist future contributors.
- Corrects the commit _subject_ being referred to as a "description"
- Links the official OpenWrt patch submission standards for commit messages
> CONTRIBUTING.md: Clarify pull request requirements

- net/mwan3/Makefile
- net/mwan3/files/lib/mwan3/common.sh
Description: This updates mwan3 to use network_get_preferred_ipaddr6 instead of network_get_ipaddr6 if possible to determine a source ip for the connectivity checks. This avoids issues where the first ip address that is returned from network_get_ipaddr6 does not work anymore while the preferred one returned from network_get_preferred_ipaddr6 works.
This partially fixes <https://github.com/openwrt/packages/issues/21782>.
Important: This is useless without <https://github.com/openwrt/openwrt/pull/14333>
> mwan3: use network_get_preferred_ipaddr6

- lang/python/python-yaml/Makefile
There is not a single CVE linked to pyyaml_project:pyyaml so use pyyaml:pyyaml instead:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:pyyaml:pyyaml
Fixes: c06a04c754bdcfdb2ea0bd1d654128863a2b6738 (python-yaml: update to version 5.1)
> lang/python/python-yaml: fix PKG_CPE_ID

- net/fping/Makefile
Description:
- Don't set default configure arg
> fping: update to 5.1

- net/knxd/Makefile
- net/knxd/patches/0100-version.patch
Maintainer: me
Description:
new upstream release 0.14.61
> knxd: bump to upstream version 0.14.61

- libs/libmariadb/Makefile
- libs/libmariadb/patches/010-link-to-libucontext.patch
Maintainer: @miska 
Description:
- Use single official source URL
- Rebase the patch
> libmariadb: update to 3.1.23

- libs/alsa-lib/Makefile
- libs/alsa-lib/patches/100-link_fix.patch
- libs/alsa-lib/patches/200-usleep.patch
Maintainer: @thess @tripolar 
Description:
- Change package URL to HTTPS
> alsa-lib: update to 1.2.11

- libs/minizip/Makefile
Description:
- Don't set default cmake option
- Switch URL to the official one
> minizip: update to 4.0.4

- libs/libinput/Makefile
Description:
- Switch sources to git since no proper tarball is available
- Switch URL to HTTPS
- Don't set default Meson options
> libinput: update to 1.25.0

- libs/libffi/Makefile
Description:
- Use proper tarball URL
- Use HTTPS for package URL
- Don't set default configure option
> libffi: update to 3.4.4

- net/iptraf-ng/Makefile
Description:
- Update package URLs
- Remove rvnamed-ng target since it was merged into iptraf-ng
> iptraf-ng: update to 1.2.1

- libs/libfastjson/Makefile
Maintainer: @dubek 
Description:
- Use HTTPS for source URL
> libfastjson: update to 1.2304.0

- utils/usbutils/Makefile
Description:
- Add mandatory usbids dependency
> usbutils: update to 017

- net/autossh/Makefile
- net/autossh/files/autossh.init
Maintainer: @jempatel / @neheb 
Compile tested: x86_64 b7f9742da8
Run tested: Netgear R6220, OpenWrt 23.05.2, r23630-842932a63d 
Description:
Previous change made localport option required, which broke older configs and was not documented in any tutorials regarding autossh package (e.g. https://openwrt.org/docs/guide-user/services/ssh/autossh).
This change makes in-config forwarding only optional, restoring original configuration template valid.
New localport & remoteport options are still accepted, however extra test is performed to ensure both of these options are provided as expected by ssh command.
> autossh: make forwarding optional

- multimedia/v4l2camera/Makefile
Maintainer: @mpromonet 
Compile tested: allwinner H3, nanopi neo air, openwrt latest
Run tested: allwinner H3, nanopi neo air, openwrt latest
Description:
fix build for [mipsel_24kc_24kf/packages/v4l2camera/compile.txt](https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc_24kf/packages/v4l2camera/compile.txt)
> v4l2camera: Update Makefile to fix mips build

- net/lynx/Makefile
Description:
Latest update had some broken faillogs, e.g. https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a72/packages/lynx/compile.txt (while CI and local builds were all right):
```
In file included from ../../WWW/Library/Implementation/UCDefs.h:11,
from ./makeuctb.c:31:
../../WWW/Library/Implementation/HTUtils.h:801:10: fatal error: bsd/stdlib.h: No such file or directory
801 | #include <bsd/stdlib.h>  /* prototype for arc4random.h */
```
Hopefully this fix will eliminate those fails.
> lyncx: fix wrongful include of 'bsd/stdlib.h' is some environments

- net/squid/Makefile
- net/squid/patches/010-no-buildcxxflags.patch
Description:
- Switch URL to HTTPS
- Remove default/obsolete configure options
- Fix and refresh the patch
> squid: update to 6.7

- net/nbd/Makefile
Maintainer: @marcin1j 
Description:
- Use up-to-date project URLs
- Use up-to-date configure args
- Drop obsolete std=gnu99 from CFLAGS
> nbd: update to 3.25

- libs/json-glib/Makefile
Maintainer: @micmac1 
Description:
- Don't set default Meson option
> json-glib: update to 1.8.0

- net/squid/Config.in
- net/squid/Makefile
- net/squid/patches/020-fix-nettle-configure.patch
Description:
- Remove non-existing 'dlmalloc' option
- Use 'with-cap' instead of 'with-libcap'
- Use 'with-xml2' instead of 'with-libxml2'
- Patch configure.ac to properly handle 'with-nettle'
Fixes faillogs error:
```
Package squid is missing dependencies for the following libraries:
libcap.so.2
libnettle.so.8
libxml2.so.2
```
> squid: fix configure options

- net/net-snmp/Makefile
- net/net-snmp/patches/000-cross-compile.patch
- net/net-snmp/patches/010-HOST-MIB-hr_filesys-fix-compile-error.patch
- net/net-snmp/patches/100-debian-statistics.patch
- net/net-snmp/patches/160-no_ldconfig.patch
- net/net-snmp/patches/161-project_types.patch
- net/net-snmp/patches/170-ldflags.patch
- net/net-snmp/patches/200-add-pcre2-support.patch
- net/net-snmp/patches/201-Run-autoreconf.patch
- net/net-snmp/patches/202-Improve-pcre2-support.patch
- net/net-snmp/patches/203-if-mib-data_access-interface.c-plug-a-leak-with-pcre.patch
- net/net-snmp/patches/990-remove-semicolon-check-in-macros.patch
Compile tested: ramips/mt7621, ramips/mt76x8, ath79
Run tested: xiaomi mi router 3 pro, keenetic extra II, tp-link tl-wdr4300
Adjust patches for current version changes
Module "disk" renamed to "disk_hw"
Internal type "unknown" changed to "u_int32_t"
Add patch with removing macro syntax checking for successful build
> net-snmp: update to 5.9.4

- net/tgt/Makefile
- net/tgt/patches/100-musl-compat.patch
Maintainer: me
Compile tested: r25115+3-7181eb9f81, qualcommax/ipq807x
Run tested: r25115+3-7181eb9f81, qualcommax/ipq807x in a chroot on r23300+3-86bc525d00, exporting a file as a lun works
Description:
- update to 1.0.90
- refresh patches
> tgt: update to 1.0.90

- utils/attr/Makefile
- utils/attr/patches/100-no-gettext_configure.patch
- utils/attr/patches/101-no-gettext_autogen.patch
Maintainer: me
Compile tested: r25115+3-7181eb9f81, qualcommax/ipq807x
Run tested: r25115+3-7181eb9f81, qualcommax/ipq807x in a chroot on r23300+3-86bc525d00, setfattr/getfattr works, rsync can copy xattrs
Description:
- update to 2.5.2
- refresh patches
> attr: update to 2.5.2

- libs/libssh2/Makefile
> libssh2: update to 1.11.0

- net/iodine/Makefile
- net/iodine/patches/010-cross-compile.patch
- net/iodine/patches/101-musl-workaround-incomplete-nameser-h.patch
Maintainer: me / @jow- / @svlobanov / @neheb / @ja-pa / @champtar / @mstorchak
Compile tested: `IPQ40XX` `AVM FRITZ!Box 7520/7530` `23.05.2`
Run tested: `IPQ40XX` `AVM FRITZ!Box 7520/7530` `23.05.2` `server start`+`client connect`
Description:
`v0.8.0` release [implements IPv6 support](https://github.com/yarrick/iodine/compare/v0.7.0...v0.8.0).
> Bump iodine 0.8.0

- libs/confuse/Makefile
- libs/confuse/patches/010-CVE-2022-40320.patch
> confuse: fix CVE-2022-40320

- libs/postgresql/Makefile
Fixes CVE-2023-39417 and CVE-2023-39418
> postgesql: update to 15.6

- libs/libmicrohttpd/Makefile
Fixes CVE-2023-27371
Maintainer: @lynxis
> libmicrohttpd: update to 0.9.77

- libs/zlog/Makefile
- libs/zlog/patches/010-cmake.patch
Rework to use local tarballs. Smaller and more stable.
Build with cmake. Faster and simpler. Needs a small patch though.
License was updated.
Fixes CVE-2021-43521
> zlog: update to 1.2.17

- libs/libusb-compat/Makefile
Description:
- Update package URL
> libusb-compat: update to 0.1.8

- utils/tio/Makefile
Description:
- Switch to Meson build
- Fix license file name
- Add libinih dependency
> tio: update to 2.7

- libs/redis/Makefile
Fixes CVE-2022-24735 and CVE-2022-24736
> redis: update to 6.2.14

- utils/stlink/Makefile
Maintainer: me
Compile tested: mipsel_24kc / ramips/mt7621
Run tested: -
Description:
stlink is an open source toolset to program and debug STM32 devices and boards manufactured by STMicroelectronics.
Resulting binary packages:
* stlink - library and shared chip info data
* st-info - a programmer and chip information tool
* st-flash - a flash manipulation tool
* st-trace - a logging tool to record information on execution
* st-util - a GDB server
> stlink: add packages

- utils/stlink/Makefile
Maintainer: me
Run tested: -
Description:
stlink is an open source toolset to program and debug STM32 devices and boards manufactured by STMicroelectronics.
Resulting binary packages:
* stlink - library and shared chip info data
* st-info - a programmer and chip information tool
* st-flash - a flash manipulation tool
* st-trace - a logging tool to record information on execution
* st-util - a GDB server
(cherry picked from commit e609f6acdf3e4619d691d5325efb9cc8a9a1b9fa)
> [23.05] stlink: add packages

- net/snort3/Makefile
- net/snort3/files/main.uc
- Add missing 'ucode' package dependencies in Makefile
- Proto-ify the ConfigItem objects
- Fix indentation and tab usage
- Add modelines to enforce proper formatting
Maintainer: @flyn-org @graysky2
> snort3: clean up ucode usage

- net/proxychains-ng/Makefile
Maintainer   : myself
Build system : Arch Linux x86_64
Build tested : r7800 OpenWrt git master (r25151-2a2abed0be)
Run tested   : r7800 OpenWrt git master (r25151-2a2abed0be)
Regular update to upstream proxychains-ng 4.17.
> proxychains-ng: update to version 4.17

- multimedia/imagemagick/Makefile
Maintainer: me
Description:
- Use .xz for PKG_SOURCE
~- Re-enable mips16~
> imagemagick: update to 7.1.1-28

- lang/python/python-aiohttp/Makefile
> python-aiohttp: update to 3.9.3

- libs/libv4l/Makefile
- libs/libv4l/patches/010-intl.patch
- libs/libv4l/patches/020-musl.patch
meson now available.
Added 2 patches to fix missing intl dependency and musl support.
> libv4l: update to 1.26.1

- utils/prometheus-node-exporter-ucode/Makefile
- utils/prometheus-node-exporter-ucode/files/extra/wifi.uc
Some properties may not yet be available, properly guard them.
Fixes error like:
```
daemon.err uhttpd[2116]: error running collector 'wifi':
daemon.err uhttpd[2116]: left-hand side expression is null
```
Maintainer: me
Compile tested: ipq40xx_generic, ramips_mt7621, mediatek_filogic
Run tested: ipq40xx_generic, ramips_mt7621, mediatek_filogic
> prometheus-node-exporter-ucode: fix sporadic wifi errors and warnings

- net/pdns-recursor/Makefile
Run tested: docker openwrt/rootfs (x86_64)
Description:
> pdns-recursor: update to 5.0.2 (fixes CVE-2023-50387, CVE-2023-50868)

- libs/efivar/Makefile
efivar fails to build with mold linker, so it should be opted out. I also added missing maintainer.
Maintainer: me
> efivar: disable mold linker

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.24.6)
> docker-compose: Update to version 2.24.6

- net/pdns-recursor/Makefile
Maintainer: me
Run tested: docker openwrt/rootfs:x86_64-openwrt-23.05
Description:
> pdns-recursor: update to 4.8.6 (fixes CVE-2023-50387, CVE-2023-50868)

- net/netavark/Makefile
- net/netavark/files/netavark-config
- net/netavark/files/netavark-wrapper
changelogs: https://github.com/containers/netavark/releases
wrapper script and config file removed as they have become obsolete, firewall driver is now configured in containers.conf
Maintainer: me
> netavark: update to 1.10.3

- libs/glib2/Makefile
- libs/glib2/patches/006-c99.patch
- libs/glib2/patches/010-pcre.patch
- libs/glib2/patches/020-locale.patch
Maintainer:  @neheb
Compile tested: lantiq_xrx200 and x86_64
Run tested: x86_64, APU3 with modemmanager
Description:
* revert latest changes to get back to working version 2.74.0
* do not set default meson options
* Update to  latest version 2.74.7 in series 2.74.x and refresh patches
> glib2: revert latest changes to get back to working version 2.74.0

- lang/node/Makefile
Run tested: (qemu 8.2.1) aarch64
Description:
Update to v20.11.1
* CVE-2024-21892 - Code injection and privilege escalation through Linux capabilities- (High)
* CVE-2024-22019 - http: Reading unprocessed HTTP request with unbounded chunk extension allows DoS attacks- (High)
* CVE-2024-21896 - Path traversal by monkey-patching Buffer internals- (High)
* CVE-2024-22017 - setuid() does not drop all privileges due to io_uring - (High)
* CVE-2023-46809 - Node.js is vulnerable to the Marvin Attack (timing variant of the Bleichenbacher attack against PKCS#1 v1.5 padding) - (Medium)
* CVE-2024-21891 - Multiple permission model bypasses due to improper path traversal sequence …
> node: February 14 2024 Security Releases

- net/aardvark-dns/Makefile
changelogs: https://github.com/containers/aardvark-dns/releases
Maintainer: me
> aardvark-dns: update to 1.10.0

- net/bind/Makefile
Fixes CVEs:
- CVE-2023-50387: Validating DNS messages containing a lot of DNSSEC signatures could cause excessive CPU load, leading to a denial-of-service condition.
- CVE-2023-50868: Preparing an NSEC3 closest encloser proof could cause excessive CPU load, leading to a denial-of-service condition.
- CVE-2023-4408: Parsing DNS messages with many different names could cause excessive CPU load.
- CVE-2023-5517: Specific queries could cause named to crash with an assertion failure when nxdomain-redirect was enabled.
- CVE-2023-5679: A bad interaction between DNS64 and serve-stale could cause named to crash with an assertion failure, when both of these features were enabled.
Run tested:  _pending_
> bind: bump to 9.18.24

- net/slirp4netns/Makefile
changelog:
- Fix some FD leaks (#334, thanks to @giuseppe)
As package belongs to network category, I moved it from utils to network folder
Maintainer: me
> slirp4netns: update to 1.2.3

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* allow users to specify list of interfaces/networks to force the DNS Hijacking on
> adblock-fast: add force_dns_interface setting

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* allow users to specify list of interfaces/networks to force the DNS Hijacking on
(cherry picked from commit eafdd63d675a84c3a80a86f7af8c1fd4fb823caa)
> [23.05] adblock-fast: add force_dns_interface setting

- utils/conmon/Makefile
bug fixes:
- Fix incorrect free in conn_sock
- logging: Respect log-size-max immediately after open
- fix some issues flagged by SAST scan
- src: fix write after end of buffer
- src: open all files with O_CLOEXEC
- oom-score: restore oom score before running exit command
new features:
- Forward more messages on the sd-notify socket
- logging: -l passthrough accepts TTYs
Maintainer: me
> conmon: update to 2.1.10

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v2.8.6

- lang/node/Makefile
Run tested: (qemu 8.2.1) aarch64
Description:
Update to v18.19.1
* CVE-2024-21892 - Code injection and privilege escalation through Linux capabilities- (High)
* CVE-2024-22019 - http: Reading unprocessed HTTP request with unbounded chunk extension allows DoS attacks- (High)
* CVE-2023-46809 - Node.js is vulnerable to the Marvin Attack (timing variant of the Bleichenbacher attack against PKCS#1 v1.5 padding) - (Medium)
* CVE-2024-22025 - Denial of Service by resource exhaustion in fetch() brotli decoding - (Medium)
* undici version 5.28.3
* npm version 10.2.4
> [23.05] node: February 14 2024 Security Releases

- libs/openblas/Makefile
Run tested: arm_cortex-a9+neon, Linksys WRT3200ACM, master branch
> openblas: enable ARM-specific optimizations

- net/unbound/Makefile
- net/unbound/patches/010-configure-uname.patch
Fixes: CVE-2023-50387, CVE-2023-50868
Release notes: https://nlnetlabs.nl/news/2024/Feb/13/unbound-1.19.1-released/
Run tested: BPi-R3, mediatek/filogic, OpenWrt 23.05.2
> unbound: update to latest upstream release version 1.19.1

- net/openconnect/Makefile
- net/openconnect/files/openconnect.sh
Retry when resolveip fails as it seems to be causing issues on startup depending on various unpredictable parameters.
Resolves: 23185
Maintainer: me
Description:
Retry when resolveip fails as it seems to be causing issues on startup depending on various unpredictable parameters.
> openconnect: make host dependency more resilient

- libs/libuv/Makefile
Compile tested: head aarch64, arm
 Run tested: aarch64 (qemu 8.2.1)
Description:
Update to 1.48.0
CVE-2024-24806 : Improper Domain Lookup that potentially leads to SSRF attacks
Vulnerabilities fixed
* CVE-2024-24806 / GHSA-f74f-cvh7-c6q6
* linux: disable io_uring on ppc64 and ppc64le
* linux: disable io_uring on hppa below kernel 6.1.51
* win/spawn: optionally run executable paths with no file extension (We recommend that most users consider setting this by default) Important Bugs Fixed
* unix,win: fix busy loop with zero timeout timers
> libuv: fix CVE-2024-24806

- net/snort3/Makefile
- net/snort3/patches/100-remove-HAVE_HS_COMPILE_LIT-to-work-around-upstream-b.patch
Increases snort's IPS fast pattern matching by 2x (compared to the ac_full engine) and 3x (compared to ac_bfna).  This is most noticeable for users of large rules sets and when doing deep flow inspection.
For more see: https://blog.snort.org/2020/09/snort-3-hyperscan-.html
Maintainer: me @flyn-org
> snort3: build against hyperscan

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> [openwrt-23.05] haproxy: update to v2.8.6

- net/strongswan/Makefile
- net/strongswan/files/ipsec.config
Description:
Without it, using uci to manipulate ipsec config can result in errors, making it much difficult to use in uci-defaults for example.
> strongswan: add empty config

- libs/libuv/Makefile
Compile tested: 23.05 aarch64, arm 
Run tested: aarch64 (qemu 8.2.1)
Description:
Update to 1.48.0
CVE-2024-24806 : Improper Domain Lookup that potentially leads to SSRF attacks
Vulnerabilities fixed
* CVE-2024-24806 / GHSA-f74f-cvh7-c6q6 0f2d7e7, 3530bcc and e0327e1 Notable Changes
* linux: disable io_uring on ppc64 and ppc64le #4285
* linux: disable io_uring on hppa below kernel 6.1.51 #4224
* win/spawn: optionally run executable paths with no file extension #4292 (We recommend that most users consider setting this by default) Important Bugs Fixed
* unix,win: fix busy loop with zero timeout timers #4250, #4304.
(cherry picked from commit 02a982bc10e8278905d0b76ac073b82192576433)
> [23.05] libuv: fix CVE-2024-24806

- net/unbound/Makefile
- net/unbound/patches/010-configure-uname.patch
Fixes: CVE-2023-50387, CVE-2023-50868
Release notes: https://nlnetlabs.nl/news/2024/Feb/13/unbound-1.19.1-released/ 
Run tested: BPi-R3, mediatek/filogic, OpenWrt 23.05.2 with updated packages from snapshot
(cherry picked from commit 35ba14e50c6c90b3cc32538573d02a3b4f5b9184)
> [23.05] unbound: update to latest upstream release version 1.19.1

- utils/rtty/Makefile
Maintainer: me
Description:
Release notes for 8.1.1: https://github.com/zhaojh329/rtty/releases/tag/v8.1.1
> rtty: update to 8.1.1

- net/libcurl-gnutls/Makefile
Description:
- Missing --without-nghttp3 was leaking host includes and breaking the build
- Remove or rename deprecated configure options
- Add --disable-libcurl-option to reduce package size
- Use .xz instead of .bz2 for PKG_SOURCE
> libcurl-gnutls: fix build

- libs/libpng/Makefile
- libs/libpng/patches/200-ccache.patch
Description:
- Don't set default and rename renamed CMake options
- Enable NEON optimizations
- Rebase the patch
> libpng: update to 1.6.42

- libs/libiio/Makefile
CMake build is passing host paths in pkgconfig file.
Maintainer: @mhei
> libiio: fix pkgconfig paths

- libs/glib2/Makefile
There's some weird issue where -lpcre2 is not being passed. Fixes vala/host which links to static libraries.
> glib2: use internal pcre2 for host

- utils/ripgrep/Makefile
Description:
- Link pcre2 dynamically
- it was linked statically and libpcre2 dependency was useless
- it magically fixes build error when global LTO is enabled
- it reduces resulting binary size
- Use 'release-lto' cargo profile to further reduce binary size
'rg' binary sizes comparision (arm_cortex-a9+neon):
- 4293KB: unmodified
- 4018KB: dynamic libpcre2
- 3521KB: dynamic libpcre2 + release-lto
> ripgrep: update to 14.1.0

- net/clamav/Makefile
Maintainer: @ratkaj @lucize 
Description:
- Add build-time Rust dependency
- Don't set default and rename changed CMake options
> clamav: update to 1.3.0

- utils/rtl_433/Makefile
Maintainer: NightNL@outlook.com
Compile tested: sunxi/cortexa8, bcm27xx/bcm2708
Run tested: oLinuXino-Lime-A10, Raspberry Pi B (1-st gen)
> rtl_433: update to 23.11

- net/coova-chilli/Makefile
- net/coova-chilli/patches/020-libxt_coova-Use-constructor-instead-of-_init.patch
**Compile tested:**
rockchip/armv8/friendlyarm_nanopi-r5c-squashfs
**Run tested:** 
on rockchip/armv8/friendlyarm_nanopi-r5c-squashfs
Loading the libxt-coova module, and using coova-chilli
Before this commit Trying to load the libxt-coova module would result into an error:
```
root@OpenWRT:~# iptables -m coova -h
iptables v1.8.8 (nf_tables): Couldn't load match `coova':No such file or directory
Try `iptables -h' or 'iptables --help' for more information.
```
After this commit it loads correctly:
```
iptables -m coova -h
iptables v1.8.8 (legacy)
Usage: iptables -[ACD] chain rule-specification [options]
[...]
coova match options:
--name name                 Name of the table to be used. 'chilli' used if none given.
--source                    Indicates the source direction …
```
> coova-chilli: fix libxt-coova not loading properly from iptables ( openwrt/packages#23092 )

- net/openvpn/Makefile
- net/openvpn/patches/100-mbedtls-disable-runtime-version-check.patch
Compile tested: ramips/mt7621, ramips/mt7620, ramips/mt76x8 
Run tested: Xiaomi Mi Router 3 Pro, Xiaomi Mi Router R3, Asus RT-AC1200
Description:
- license change is now complete, and all code has been re-licensed under the new license (still GPLv2, but with new linking exception for Apache2 licensed code). Code that could not be re-licensed has been removed or rewritten.
- add support for building with mbedTLS 3.x.x
- new option "--force-tls-key-material-export" to only accept clients that can do TLS keying material export to generate session keys (mostly an internal option to better deal with TLS 1.0 PRF failures).
- Windows: bump vcpkg-ports/pkcs11-helper to 1.30
- Log incoming SSL alerts in easier to understand form and move logging from "--verb 8" to …
> openvpn: update to 2.6.9

- lang/python/micropython/Makefile
package fails to build with mold linker due to unregocnized flag.
> micropython: disable mold

- utils/tesseract/Makefile
Maintainer: @vk496 
Description:
- Fix NEON mis-detection which was breaking builds on some platforms
Mis-detected NEON error which this PR fixes:
```
ld.bfd: libtesseract.so.5.3.3: undefined reference to `tesseract::DotProductNEON(float const*, float const*, int)'
ld.bfd: libtesseract.so.5.3.3: undefined reference to `tesseract::IntSimdMatrix::intSimdMatrixNEON'
```
> tesseract: update to 5.3.4

- multimedia/imagemagick/Makefile
Package imagemagick is missing dependencies for the following libraries: libzip.so.5.
Fixes: 7b697342e9fc ("imagemagick: update to 7.1.1-28")
Maintainer: @krant
Compile tested: Netgear XR700 ARMv7 Processor rev 4 (v7l), OpenWrt SNAPSHOT r25160-388cb43b8773
Run tested: Netgear XR700 ARMv7 Processor rev 4 (v7l), OpenWrt SNAPSHOT r25160-388cb43b8773
> imagemagick: add missing libzip dependency

- utils/sysstat/Makefile
Depending only on 'xz' hides the package when 'xz-utils' is not selected.
Last update in #23494 introduced 'xz' dependency incorrectly. Thanks to @nxhack for spotting the issue.
> sysstat: add missing xz-utils dependency

- net/lighttpd/Makefile
- net/lighttpd/patches/020-meson-mod_webdav_min.patch
Description:
update to lighttpd 1.4.74 release hash
Release notes:
https://www.lighttpd.net/2024/2/19/1.4.74/
> lighttpd: update to lighttpd 1.4.74 release hash

- libs/gperftools/Makefile
Thread-caching malloc provided by this package improves snort3 performance.  I have been running with this for over five months now without issues.  Avg CPU usage is down.  Another user reported higher throughput achieved with snort3 compiled with this on samba transfers on system with CPU-limited snort performance.[1]
1. https://forum.openwrt.org/t/some-help-with-a-makefile-gperftools/165656/22
Maintainer: 
@flyn-org - just a heads up that this and hyperscan (see https://github.com/openwrt/packages/pull/21471) improve snort3 performance.  I have a draft Makefile for snort3 that incorporates both.  Sneak peak: https://github.com/graysky2/packages/commit/a017d4bf1fe7d2ccf7c1664e0d064d25c78f4c1c
> gperftools: add new package

- utils/avrdude/Makefile
Description:
- libftdi, libhidapi, libusb-0.1 was incorrectly leaking into the build.
- libgpiod was incorrectly missing out despite LINUXGPIO feature was explicitly requested.
> avrdude: fix dependencies

- libs/c-ares/Makefile
Description:
- Update package URL
- Don't set default CMake options
> c-ares: update to 1.27.0

- net/conserver/Makefile
- net/conserver/patches/002-addrsmatch-freeaddrinfo.patch
When looping through addrinfo lists in AddrsMatch, keep a copy of the original addrinfo pointers to free instead of ending up at the terminating NULLs and trying to free those.
OpenWRT uses musl in which freeaddrinfo(NULL) is not safe (which is fine, it's not required by the spec) so this fixes a segfault.
Compile tested: mips_24kc,  gl.inet 6416, master
Run tested: mips_24kc, gl.inet 6416, OpenWrt SNAPSHOT, r25153-869df9ecdf with tests below, plus running in "production" on a gl.inet gl-ar150 on 23.05.2.
Description:
This was submitted and accepted upstream as https://github.com/bstansell/conserver/pull/98.
Tests:
root# uname -a
Linux glinet6416 5.15.148 #0 Wed Feb 14 15:22:53 2024 mips GNU/Linux
root# cat /etc/conserver/conserver.cf
config * { }
default full { rw *; …
> conserver: free correct addrinfo to prevent crash.

- net/snort3/Makefile
Changelog: https://github.com/snort3/snort3/releases/tag/3.1.81.0
```
o"  )~   Version 3.1.81.0
Copyright (C) 2014-2024 Cisco and/or its affiliates. All rights reserved.
Using DAQ version 3.0.14
Using OpenSSL 3.0.13 30 Jan 2024
Using ZLIB version 1.3.1
Using Hyperscan version 5.4.2 2024-02-16
Using LZMA version 5.4.6
```
> snort3: update to 3.1.81.0

- utils/tmux/Makefile
Maintainer: me
Compile tested: aarch64_cortex-a53, Dynalink DL-WRX36, r25309+3-c378927ef8
Run tested: aarch64_cortex-a53, Dynalink DL-WRX36, r25309+3-c378927ef8 in a chroot running on r23300+3-86bc525d00 in a chroot. tmux works as expected
Description:
> tmux: update to 3.4

- multimedia/rtpmidid/Makefile
Get rid of codeload and use local tarballs.
Fixes compilation with newer fmt.
Minor cleanups.
> rtpmidi: update to 23.12

- net/snort3/Makefile
Should provide increases in snort3 performance thanks to thread- caching malloc provided by gperftools.  Avg CPU usage is down. Another user reported higher throughput achieved with snort3 compiled with this on samba transfers on system with CPU-limited snort3 performance.[1]
1. https://forum.openwrt.org/t/some-help-with-a-makefile-gperftools/165656/22
Co-maintainer: @flyn-org
> snort3: build against gperftools-runtime

- lang/rust/Makefile
- lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
- lang/rust/patches/0002-rustc-bootstrap-cache.patch
- lang/rust/patches/0003-bump-libc-deps-to-0.2.146.patch
Run tested: ARMv7, Linksys WRT3200ACM - build and run ripgrep package
Description:
- Use .xz for source archive
> rust: update to 1.76.0

- utils/inotify-tools/Makefile
Description:
- Workaround superfluous linking with libstdccp
> inotify-tools: update to 4.23.9.0

- utils/dump1090/Makefile
Compile tested: arm926ej-s
Description:
Package CPU features detection is not supporting soft float ARM. So we disable it altogether.
> dump1090: fix soft float ARM build

- utils/mc/Makefile
Now that libe2p is separated from e2fsprogs;
midnight commander needs it added to depends.
Maintainer: unknown
Description:
I recently requested libe2p package separation from e2fsprogs; it had impact on a single package: midnight commander.
This PR adds libe2p to depends, nothing more.
> mc: depend on libe2p

- net/dnsdist/Makefile
Maintainer: @Habbie 
XSK support is set to `auto` by default and on some hosts it is detected as `on` and leads to (from [faillog](https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a5_vfpv4/packages/dnsdist/full/compile.txt)):
```
In file included from dnsdist-backend.cc:32:
xsk.hh:28:10: fatal error: bits/types/struct_timespec.h: No such file or directory
28 | #include <bits/types/struct_timespec.h>
```
Here we disable XSK so configure will behave more deterministically and hopefully fix the builders.
> dnsdist: disable XSK to fix the build

- devel/ragel/Makefile
This is a new package for ragel which is a dependency for another new package vectorscan
(cherry picked from commit fa76c4df5c857ee564bf2f2eaeedfea5b497b1e7)
> ragel: new package to build hyperscan

- utils/inotify-tools/Makefile
Compile tested: AMD Geode
Thanks to @feckert for reporting this bug.
Previous commit (#23533) removed unnecessary linking with libstdc++ but introduced another error on x86 platforms:
```
undefined reference to `__stack_chk_fail_local'
```
Fix it by explicitly linking libssp_nonshared.a
> inotify-tools: fix link error on x86

- utils/rtl_433/Makefile
Maintainer: -
Run tested: -
Description:
Cherry-picked from master branch to openwrt-23.05.
> [23.05] rtl_433: update to 23.11

- lang/lua-struct/Makefile
- utils/mt5311/Makefile
- utils/mt5311/files/ebm-read
- utils/mt5311/files/init.lua
Maintainer: me, @jasle 
Compile tested:  mediatek filogic MT7986 bpi-r3
Run tested: mediatek filogic MT7986 bpi-r3
Description:
Utilities for working with Metanoia/Proscend VDSL2 SFP Modems from @jimdigriz.
This Package only contain the parts needed for using it from shell or lua, not the snmp part, because it is currently mentioned as work in progress.
Also contains new package `lua-struct`, a dependency for the mt5311 utilities.
> Add metanoia mt5311 vdsl modem tools

- net/natmap/Makefile
Description:
1. Update to 20240303.
> natmap: update to 20240303

- net/natmap/Makefile
Description:
1. Update to 20240303.
> [23.05] natmap: update to 20240303

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/020-src-options.c-add-version.patch
Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.2, start/stop/name resolution
Description:
* update to upstream 2023-11-19 (changes: https://github.com/aarond10/https_dns_proxy/commit/489c57efd46983e688579974a2ab7aeaa7df8d83)
* bugfix: include resolveip dependency in Makefile (fixes https://github.com/openwrt/packages/issues/23567)
* minor update for failed healthcheck logging
> https-dns-proxy: update to upstream 2023-11-19

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
- net/https-dns-proxy/patches/020-src-options.c-add-version.patch
Maintainer: me
Description:
* update to upstream 2023-11-19 (changes: https://github.com/aarond10/https_dns_proxy/commit/489c57efd46983e688579974a2ab7aeaa7df8d83)
* bugfix: include resolveip dependency in Makefile (fixes https://github.com/openwrt/packages/issues/23567)
* minor update for failed healthcheck logging
(cherry picked from commit bd501dd89c65857c060ca1ac034bc2fe7846b4e7)
> [23.05] https-dns-proxy: update to upstream 2023-11-19

- utils/eza/Makefile
eza is a substitute for ls command with icons and colors and more. Common for those who use ohmyzsh or similar shell stylers.
Maintainer: Jonas Jelonek / @jonasjelonek 
> eza: add new package

- utils/lsd/Makefile
ls deluxe. Substitute for ls command with style.
Popular amongst people who use ohmyzsh and similar shell stylers.
Maintainer: me
> lsd: add new package

- libs/c-ares/Makefile
- Update package URL
- Don't set default CMake options
Signed-off-by: krant <aleksey.vasilenko@gmail.com>
(cherry picked from commit 0858accfda87e09df019c2e8ba4ab51f6323f17e)
^^^ @krant original commit message ^^^
Compile tested: 23.05, aarch64, arm, i386, x86_64
Run tested: aarch64 (qemu 8.2.1) node.js, mosquitto-client working
Description:
This is a security, feature, and bugfix release.
Security:
Moderate. CVE-2024-25629. Reading malformatted /etc/resolv.conf,
/etc/nsswitch.conf or the HOSTALIASES file could result in a crash.
[GHSA-mg26-v6qh-x48q](https://github.com/c-ares/c-ares/security/advisories/GHSA-mg26-v6qh-x48q)
Features:
New function ares_queue_active_queries() to retrieve number of in-flight
queries. https://github.com/c-ares/c-ares/pull/712
New function …
> [23.05] c-ares: update to 1.27.0

- admin/syslog-ng/Makefile
- admin/syslog-ng/files/syslog-ng.conf
Maintainer: me
Compile tested: MacBook A1990, Sonoma 14.3.1 for Turris Omnia router
Run tested: Turris Omnia, mvebu/cortexa9, OpenWrt 22.03
Description:
1. Updated to version 4.6.0
- https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-4.6.0
- https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-4.5.0
2. Bump config file
> syslog-ng: update to version 4.6.0

- utils/eza/Makefile
Maintainer: me
Description:
- Release notes: https://github.com/eza-community/eza/releases/tag/v0.18.6
- fix typo in description in Makefile (caused weird output in make menuconfig)
> eza: update to 0.18.6

- admin/zabbix/Makefile
- admin/zabbix/files/zabbix_helper_mac80211.c
Description
---
The musl libc only implements POSIX basename() but provided a GNU header kludge in <string.h>, which is removed in musl 1.2.5 [1]. Use the standard <libgen.h> header to avoid compilation warnings like:
```
zabbix-6.4.7/zabbix-extra-mac80211/zabbix_helper_mac80211.c:37:11: warning: implicit declaration of function 'basename' [-Wimplicit-function-declaration]
37 |     phy = basename(phy);
|           ^~~~~~~~
zabbix-6.4.7/zabbix-extra-mac80211/zabbix_helper_mac80211.c:37:9: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
37 |     phy = basename(phy);
|         ^
zabbix-6.4.7/zabbix-extra-mac80211/zabbix_helper_mac80211.c:38:10: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast …
```
> zabbix: zabbix_helper_mac80211.c: add <libgen.h> header

- net/modemmanager/Makefile
- net/modemmanager/files/usr/share/ModemManager/modemmanager.common
Virtual netdevices created for multiplexing should not be skipped when reporting events, otherwise it is not possible to setup the data connection.
Add these exceptions in mm_report_event function.
Run tested: 23.05.0-rc1 r23069-e2701e0f33 imx/imx8
Tested with data connection:
mmcli -m 0 --create-bearer="apn=default,ip-type=ipv4,multiplex=requested"
mmcli -m 0 -b 1 --connect
fixes #23550 
Not very proficient in scripting, apologize if the change is wrong.
> modemmanager: report events for virtual netdevices

- utils/irqbalance/Makefile
- utils/irqbalance/files/irqbalance.init
I have some strange issues with irqbalance sometimes overwriting smp_affinity values for banned/ignored IRQs. The issue is reproduceable and is mitigated when I change theway how the irqbalance command line is built. The only difference between the resulting command is that there is only one space between the -t parameter and the first -i parameter value.
> irqbalance: Update init script to remove duplicate spaces

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.24.7)
> docker-compose: Update to version 2.24.7

- net/gnunet/Makefile
- net/gnunet/patches/010-DHTU-ship-dhtu-conf.patch
- net/gnunet/patches/020-curl-no-runtime-test.patch
Maintainer: me
Run tested: -
Description:
This release marks a noteworthy milestone in that it includes a completely new transport layer. It lays the groundwork for fixing some major design issues and may also already alleviate a variety of issues seen in previous releases related to connectivity. This change also deprecates our testbed and ATS subsystem.
This is a new major release. It breaks protocol compatibility with the 0.20.x versions. Please be aware that Git master is thus henceforth (and has been for a while) INCOMPATIBLE with the 0.20.x GNUnet network, and interactions between old and new peers will result in issues. In terms of usability, users should be aware that there are still a number of known open issues in particular with respect to …
> gnunet: update to version v0.21.0

- net/modemmanager/Makefile
- net/modemmanager/files/usr/lib/ModemManager/connection.d/10-report-down
Maintainer: me / @aleksander0m 
Run tested: x86_64, APU3
Description:
There are situation for mobile routers, that the ModemManager can not stay connected to the mobile network in OpenWrt. There can have various reasons. In order for the system to reconnect automatically, the netifd must be informed that it must re-establish the connection.
The modem manager already does have a script callback handling which is already used by the modemmanager in openwrt. Currently the modem is marked as not unavailable when a disconnected event is detected.
The behavior was changed with this commit, so that a reconnect of the interface is now triggerd via the netifd if the modem disconnects.
Testcases:
* Start a connection via netifd modemmanager proto
* …
> modemmanager: reconnect interface if the modemmanager detects a disconnect

- net/lighttpd/Makefile
Description:
lighttpd: update to lighttpd 1.4.75 release hash
Release notes:
https://www.lighttpd.net/2024/3/13/1.4.75/
> lighttpd: update to lighttpd 1.4.75 release hash

- .github/workflows/multi-arch-test-build.yml
With the commit 01e5cfc "CI: Add target/arch tags (no suffix) for snapshot images"[1] the os/platform is set for all images, which is usually different from what the GitHub action runner uses (x86). The Docker deamon still tries to fetch the x86 version and fails.
This commit explicitly sets the fitting arch.
[1]: https://github.com/openwrt/docker/commit/01e5cfccd73a72ecab730496607c7c22b904f366
Description:
> ci: set correct arch for rootfs tests

- utils/collectd/Makefile
Compile tested: not needed only Makefile change
Run tested: not needed only Makefile change
Description:
Add missing license information.
See https://github.com/collectd/collectd/blob/main/COPYING
> collectd: add license informations

- net/gping/Makefile
gping is ping but with a graph. It graphically plots ping results over time in terminal, allows multiple hosts to ping in parallel, uses coloured output and can also plot the execution time of arbitrary commands.
Maintainer: me
Description: see package description above or in the commit message.
This is more of a nice-to-have package, but I find it quite useful to have the ping plotted, to see how it fluctuates, and also to plot exec time of any other command.
PS: The `Build/Compile` needs to be overwritten in the Makefile since gping uses Cargo Workspaces.
> gping: new package

- utils/eza/Makefile
Maintainer: me
Description:
- Release notes: https://github.com/eza-community/eza/releases/tag/v0.18.7
> eza: update to 0.18.7

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.25.0)
Compose files with `version=2.4` show now a warning saying it is obsolete.
> docker-compose: Update to version 2.25.0

- multimedia/minisatip/Makefile
The configure option which depends on openSSL is named --disable-dvbca and not --disable-dvbaes
This fixes the following warning:
configure: WARNING: unrecognized options: --disable-dependency-tracking, --disable-nls, --disable-dvbaes
When the option is not set configure will check if openssl is available and compile against openssl if it find openssl. This breaks the build because openssl is not defined as a package dependency.
Maintainer: @danielkucera 
Compile tested: malta/be
Run tested: no
> minisatip: Fix configure option for openssl

- sound/espeak/Makefile
Apparently it goes away when passing --as-needed.
> espeak: remove libstdcpp dependency

- net/adguardhome/files/adguardhome.init
Maintainer: @dobo90 
Run tested: @iljah and @mangkoran 
Description:
This should allow the service to be activated even earlier during the boot process and also avoids race condition against network.
~~I've not tested this change yet since I'm not affected by this issue.
@iljah if you can compile your own packages, please test this.~~
Fixes #21868.
> adguardhome: wait for interfaces to be up at boot

- net/unbound/Makefile
- net/unbound/patches/010-configure-uname.patch
Compile tested: Turris Omnia (mvebu/armv7) on self-compiled OpenWrt master
Run tested: Turris Omnia (mvebu/armv7) on self-compiled OpenWrt master, using as a home network DNS server (and using the dnsmasq script for local device names)
Description:
Update from 1.19.1 to 1.19.3 (1.19.2 fixes CVE-2024-1931 only, 1.19.3 is a general bugfix release). Maybe worth backporting to stable due to the security fix?
> unbound: update to 1.19.3

- utils/fx/Makefile
Maintainer: @dynasticorpheus  
Compile tested: Ubuntu 23.04 x64 / OpenWrt SNAPSHOT @ 36b1dd75fd9da1ea13f1ce1ee679c6b3c9c402cc
Description: Update to [33.0.0](https://github.com/antonmedv/fx/compare/32.0.0...33.0.0)
> fx: update to 33.0.0

- sound/shairport-sync/Makefile
--as-needed gets rid of it apparently.
> shairport-sync: get rid of libstdcpp

- admin/syslog-ng/Makefile
Maintainer: me
Compile tested: MacBook A1990, Sonoma 14.3.1 for Turris Omnia router
Run tested: Turris Omnia, mvebu/cortexa9, OpenWrt 22.03
Description:
Since version 4.4.0, syslog-ng added compression to http() destination using zlib from curl. [1] However, zlib is currently disabled in curl [2] and it prevented syslog-ng to start.
This commit changes the configuration opinion to enable http module only if zlib support is enabled for curl and as well it adds dependency for zlib (in that case). If the zlib is disabled, then it disables http module, so syslog-ng can start and thus zlib dependency is not required.
[1] https://gitlab.nic.cz/turris/os/packages/-/issues/932
[2] https://github.com/openwrt/packages/blob/93cbaacbfb13048ad378520a7afea7c9027dd1d6/net/curl/Config.in#L134
Fixes: …
> syslog-ng: enable http module based on zlib support in curl

- net/nginx/Makefile
- net/nginx/patches/nginx/102-sizeof_test_fix.patch
Compile tested: x86, x86_64 QEMU, master
Run tested: x86, x86_64 QEMU, master, `wget --no-check-certificate https://localhost`
Description:
When CONFIG_USE_LTO=y, the int-size detection script will fail because a variable gets optimised out. Mark it as volatile to fix the issue.
> nginx: Fix compilation with LTO

- lang/lualanes/Makefile
Maintainer: @first-leon 
Compile tested: MacBook A1990, Sonoma 14.3.1 for Turris Omnia router
Run tested: Turris Omnia, mvebu/cortexa9, OpenWrt 22.03
Description:
1. Update it to version 3.16.3
Release notes: https://github.com/LuaLanes/lanes/releases/tag/v3.16.3
2. Change to download tarball instead of checking out Git sources In the previous commit (in the Fixes tag), it was changed to Git sources without any reason. Let's revert it back. Let's use again tagged release. Fixes: https://github.com/openwrt/packages/pull/23121#pullrequestreview-1917612521
Fixes: b93e5b45b1daac827d429b51d8763226268f2b9a ("lualanes: Version bump to v3.16.2")
> lualanes: update to version 3.16.3 and use tarball

- utils/telldus-mqtt/Makefile
Maintainer:  @PeterFromSweden
Compile tested: bcm2708/RPiB/openwrt23.05.2, mvebu/cortexa9/openwrt23.05.2
Run tested: bcm2708/RPiB/openwrt23.05.2, mvebu/cortexa9/openwrt23.05.2
Description:
Fixed bug in connection state check causing telldus-mqtt to terminate.
> telldus-mqtt: bump to 0.3

- lang/php8/Makefile
Maintainer: me
Upstream's changelog: https://www.php.net/ChangeLog-8.php#8.3.4
> php8: update to 8.3.4

- net/microsocks/Makefile
- net/microsocks/files/microsocks.config
- net/microsocks/files/microsocks.init
Maintainer: Mateusz Korniak / @matkor
Compile tested: ipq806x, Netgear Nighthawk X4S R7800
Run tested: ipq806x, Netgear Nighthawk X4S R7800, OpenWrt 23.05-SNAPSHOT r23786-2f2eceab13 / LuCI openwrt-23.05 branch git-24.067.02086-146a8f1
Have been using a custom build of microsocks on the latest commit of the 1.0.4 release, for over 2 months. 
Description:
Updated package microsocks to version 1.0.4. Added configuration flag for the newly added quiet mode. 
Setup the config file so that quiet mode is enabled by default. On frequent use of the proxy, the per-site-visit logging quickly fills up the limited log history, therefore it makes sense from a usability perspective for it to be turned off by default.
> microsocks: update to 1.0.4

- libs/libdeflate/Makefile
Description:
- Use proper tarball URL.
> libdeflate: update to 1.19

- multimedia/minisatip/Makefile
Maintainer: @danielkucera 
Description:
- Configure option 'dvbaes' renamed to 'dvbca'
> minisatip: update to 1.3.4

- net/tgt/Makefile
- net/tgt/patches/100-musl-compat.patch
Maintainer: me
Compile tested: aarch64_cortex-a53, r25557+3-8fb23465ca
Run tested: aarch64_cortex-a53, ipq807x, Dynalink DL-WRX36, r25557+3-8fb23465ca in a chroot on r23300+3-86bc525d00. Exporting a file as a iSCSI target works.
Description:
- update to 1.0.91
- refresh patches
> tgt: update to 1.0.91

- net/pbr/Makefile
- net/pbr/files/etc/config/pbr
- net/pbr/files/etc/config/pbr.iptables
- net/pbr/files/etc/hotplug.d/iface/70-pbr
- net/pbr/files/etc/init.d/pbr
- net/pbr/files/etc/uci-defaults/90-pbr
- net/pbr/files/etc/uci-defaults/91-pbr
- net/pbr/files/usr/share/pbr/firewall.include
- net/pbr/files/usr/share/pbr/pbr.user.aws
- net/pbr/files/usr/share/pbr/pbr.user.netflix
- net/pbr/files/usr/share/pbr/pbr.user.wg_server_and_client
- net/pbr/test.sh
Maintainer: me
Description:
This update includes the following changes:
1. Makefile
* update copyright
* attempt to implement the proper variants to avoid luci-app dependency on both variants
* quietly stop service on uninstall
2. Config-file
* add the list of dnsmasq instances to target in supported dnsmasq modes
* for default pbr variant, set the `resolver_set` to `dnsmasq.nftset`
* for iptables pbr variant, set the `resolver_set` to `dnsmasq.ipset`
* add the `nft_file_support` (disabled by default)
* introduce `procd_boot_delay` to delay service start on boot
* introduce the following nft set creation options:
* nft_set_auto_merge
* nft_set_counter 
* nft_set_flags_interval 
* …
> pbr: update to 1.1.4-5

- net/tailscale/Makefile
https://github.com/tailscale/tailscale/releases/tag/v1.62.0
Compile not tested, needs Go 1.22 (#23475)
Signed-off-by: Zephyr Lykos \<self@mochaa.ws>
> tailscale: Update to 1.62.0

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.26.0)
> docker-compose: Update to version 2.26.0

- net/openvpn/Makefile
Compile tested: ramips/mt7621, ramips/mt7620, ramips/mt76x8
Run tested: Xiaomi Mi Router 3 Pro, Xiaomi Mi Router R3, Asus RT-AC1200
Description:
This is a bugfix release containing several security fixes specific to the Windows platform.
Bug fixes
---------
- Windows: if the win-dco driver is used (default) and the GUI requests use of a proxy server, the connection would fail.  Disable DCO in this case.
- Compression: minor bugfix in checking option consistency vs. compiled-in algorithm support
- systemd unit files: remove obsolete syslog.target
Security fixes
--------------
- CVE-2024-27459: Windows: fix a possible stack overflow in the interactive service component which might lead to a local privilege escalation.
- CVE-2024-24974: Windows: disallow …
> openvpn: update to 2.6.10

- multimedia/imagemagick/Makefile
Maintainer: me
Description:
- Don't ignore version suffix (upstream 7.1.1-29 becomes 7.1.1.29)
- Avoid superfluous libstdcpp dependency
> imagemagick: update to 7.1.1.29

- libs/gost_engine/Makefile
- libs/gost_engine/patches/030-dont-build-provider.patch
- libs/gost_engine/patches/040-dont-build-tests.patch
This version contains minor bugfixes.
It fixes a compile problem with GCC 13.
Changes: https://github.com/gost-engine/engine/compare/v3.0.1...v3.0.3
Maintainer: Artur Petrov <github@phpchain.ru>
Compile tested: aarch64
Description:
> gost_engine: Update to version 3.0.3
