net/snort3/Makefile
net/snort3/patches/110-packet_capture-Fix-compilation-with-GCC-13.patch

This fixes a compile problem with GCC 13.
Maintainer: @flyn-org, @graysky2
Compile tested: aarch64 + gcc 13
Description:
Upstream PR: https://github.com/snort3/snort3/pull/352

snort3: Fix compilation with GCC 13

---

utils/nnn/Makefile
utils/nnn/patches/musl-fts.patch

Maintainer: me
Compile tested: MacBook A1990, Sonoma 14.3.1 for Turris Omnia router
Run tested: Turris Omnia, mvebu/cortexa9, OpenWrt 22.03.6 and perfomed basics tests that the applications runs
Description:
Release notes:
https://github.com/jarun/nnn/compare/v4.4...v4.9
and refresh patch

nnn: update to version 4.9

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr

Maintainer: me
Description:
* remove dependencies/references to opkg
* simplify wan/wan6 discovery

pbr: prepare migration to APK

---

net/nebula/Makefile

Maintainer: me
(cherry picked from commit 9cb2dbd23ce740fb6f03a190327dc60ab7c6884d)

[23.05] nebula: prepare migration to APK

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

adblock-fast: prepare migration to APK

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
(cherry picked from commit 706592edccd0fb562f9d1966c6a360e9dc099fb1)

[23.05] adblock-fast: prepare migration to APK

---

net/https-dns-proxy/Makefile
net/https-dns-proxy/files/etc/init.d/https-dns-proxy
net/https-dns-proxy/patches/020-src-options.c-add-version.patch

Maintainer: me
(cherry picked from commit dae56fd2a5d4ac579dff5d151cefe45b8d873bd6)

[23.05] https-dns-proxy: prepare migration to APK

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/share/ddns/default/servercow.de.json
net/ddns-scripts/files/usr/share/ddns/list

Run tested: x86-64 22.03
Description:
Add ddns provider servercow.de.
Description of usage at https://cp.servercow.de/plugin/support_manager/knowledgebase/view/46/dns-update-through-fritzbox-router/

ddns-scripts: Add servercow.de as DDNS provider

---

lang/perl-cgi/Makefile

Maintainer: me
Compile tested: x86_64, generic, HEAD (8de4cc77a6d)
Run tested: same, installed on sandbox router
Description:
Update to 4.64.

perl-cgi: Update to 4.64

---

utils/clixon/Makefile

Compile tested: x86_64, generic, HEAD (8de4cc77a6d)
Run tested:same, installed on test VM
Description:
Update to 7.0.0

clixon: Update clixon to 7.0.0

---

lang/rust/Makefile
lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
lang/rust/patches/0002-rustc-bootstrap-cache.patch
lang/rust/patches/0003-bump-libc-deps-to-0.2.146.patch

Run tested: ARMv7, Linksys WRT3200ACM, by ripgrep package
Description:
- Restore patch hunk mis-deleted in dccb910
- Remove --enable-missing-tools configure option deleted in the upstream

rust: update to 1.77.0

---

net/nginx/Makefile

Maintainer: @heil @Ansuel
Compile tested: compiled for Turris Omnia
Run tested: running flawlessly for weeks on Turris Omnia (compiled from master)
Description:
Update NGINX to 1.25.4. Maybe worth backporting to stable branch(es) as there are some major CVE fixes (for HTTP3, which is turned off by default in OpenWrt, however).

nginx: update to 1.25.4

---

net/uspot/Makefile

Maintainer: me
Compile tested: ath79/generic, ramips/mt7621, x86/64
Run tested: ath79/generic, ramips/mt7621, x86/64 - OpenWrt 23.05
Description: uspot: update to Git HEAD (2024-03-25)
**Please cherry-pick into 23.05 once merged :)**

uspot: update to Git HEAD (2024-03-25)

---

lang/rust/Makefile
lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
lang/rust/patches/0002-rustc-bootstrap-cache.patch
lang/rust/patches/0003-bump-libc-deps-to-0.2.146.patch

Description:
backport rust updates to 23.05 branch.

[openwrt-23.05] rust: update to 1.77.0

---

utils/eza/Makefile

Maintainer: me
Description:
Release notes:
0.18.8 - https://github.com/eza-community/eza/releases/tag/v0.18.8
0.18.9 - https://github.com/eza-community/eza/releases/tag/v0.18.9

eza: update to 0.18.9

---

libs/ngtcp2/Makefile

Maintainer: me
Description:
* update PKG_RELEASE to be apk-compatible
* update PKG_SOURCE/PKG_SOURCE_URL so that it builds
* drop dependency on libopenssl as other SSL libs start to support HTTP/3

ngtcp2: update to 1.4.0

---

libs/nghttp3/Makefile

Maintainer: me
Description:
* update PKG_RELEASE to be apk-compatible
* update PKG_SOURCE/PKG_SOURCE_URL so that it builds

nghttp3: update to 1.2.0

---

net/tailscale/Makefile

https://github.com/tailscale/tailscale/releases/tag/v1.62.1

tailscale: Update to 1.62.1

---

net/ksmbd-tools/Makefile

Solved strange package version 0~ to match apk format.
Compile tested: mediatek/filogic GL.iNet GL-MT6000 OpenWRT snapshot r25663-ce0cf80dac
Run tested: mediatek/filogic GL.iNet GL-MT6000 OpenWRT snapshot r25663-ce0cf80dac
Tested
-add new user
-mod existing user
Description:
Previous version
ksmbd-avahi-service `0~3.5.1-r1`
ksmbd-hotplug `0~3.5.1-r1`
ksmbd-server` 0~3.5.1-r1`
Actual:
ksmbd-avahi-service` 3.5.1-r2`
ksmbd-hotplug` 3.5.1-r2`
ksmbd-server `3.5.1-r2`

kmsbd-tools: fix version after apk changes

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.26.1)

docker-compose: Update to version 2.26.1

---

admin/htop/Makefile

Default CONFIG_HTOP_LMSENSORS to y so users just need to install libsensors, no need to build your own, but no need to pay the size price when you don't use it.  Closes #23700.

htop: build with CONFIG_HTOP_LMSENSORS=y

---

net/tor/Makefile

Bugfix release, see the changelog [1] for what's new.
[1] https://gitlab.torproject.org/tpo/core/tor/-/raw/tor-0.4.8.10/ChangeLog
Run tested (tor-basic): mediatek/filogic, mediatek/mt7622, ramips/mt7621

tor: update to 0.4.8.10 stable

---

lang/lua-eco/Makefile

Maintainer: me
Description:
Release notes for 3.3.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.3.0

lua-eco: update to 3.3.0

---

lang/luajit2/Makefile

luajit2: update to v2.1-20240314

---

net/wgsd/Makefile
net/wgsd/README.md
net/wgsd/files/Corefile
net/wgsd/files/wgsd-coredns.init

Maintainer: me / @vooon
Compile tested: ramips / Asus ax53u / OpenWrt master, 
Run tested: ramips / Asus ax53u / OpenWrt master - client, x64_64 - coredns
Description:
Adds [WGSD](https://github.com/jwhited/wgsd), a service that enables use cases such as:
- Building a mesh of WireGuard peers from a central registry
- Dynamic discovery of WireGuard Endpoint addressing (both IP address and port number)
- NAT-to-NAT WireGuard connectivity where [UDP hole punching](https://en.wikipedia.org/wiki/UDP_hole_punching) is supported.
Provides two packages:
- wgsd-coredns - a DNS-SD server
- wgsd-client - a client, which query DNS server and update wireguard peers

wgsd: add package

---

kernel/mdio-netlink/Makefile
net/mdio-tools/Makefile

Maintainer: me
Compile tested: qualcommax, Dynalink WRX-36, main
Run tested: qualcommax, Dynalink WRX-36, main
Description:
In light of the recent XZ events, it seems that using the tag as the source version reference is not ideal as it can be updated by the upstream lets switch to using the full commit hash as the source.
This also should fix the APK semantic versioning by setting PKG_VERSION as well updating the PKG_MIRROR_HASH which got broken by recent APK changes.

mdio-tools: use commit hash as the source version

---

net/apcupsd/Makefile

Maintainer: @tru7
Run tested: Xiaomi Mi router 3,  Back-UPS XS 800CI (usb-hid connection)
Description:
On GCC13 build fails:
toolchain-mipsel_24kc_gcc-13.2.0_musl/lib/libsupc++.a(eh_alloc.o): in function `std::__sv_check(unsigned int, unsigned int, char const*)': toolchain-mipsel_24kc_gcc-13.2.0_musl/gcc-13.2.0-final/mipsel-openwrt-linux-musl/libstdc++-v3/include/string_view:73: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)' collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:33: apcupsd] Error 1
Workaround found at https://lore.kernel.org/buildroot/87wmsbk386.fsf@48ers.dk/T/

apcupsd: fix gcc 13 compliation error

---

lang/python/python-orjson/Makefile

Relevant changes since previous 3.9.13:
- FIXED: Fix crash serializing str introduced in 3.9.11
- FIXED: Implement recursion limit of 1024 on orjson.loads()
- FIXED: Use byte-exact read on str formatting SIMD path to avoid crash
- Build now depends on Rust 1.72 or later
- Support serializing numpy.float16 (numpy.half)
- sdist uses metadata 2.3 instead of 2.1
- Improve Windows PyPI builds
Maintainer: me
Compile tested: arm_cortex-a9_vfpv3-d16, Linksys WRT1900ACS, master
Run tested: arm_cortex-a9_vfpv3-d16, Linksys WRT1900ACS, 23.05.0 r23497-6637af95aa
Description:
Updates python-orjson from 3.9.13 -> 3.10.0. Fixes from upstream (from v3.9.14, v3.9.15, and v3.10.0) include:
- FIXED: Fix crash serializing str introduced in 3.9.11
- FIXED: Implement recursion limit of 1024 on orjson.loads()
- …

python-orjson: update to version 3.10.0

---

utils/cryptsetup/Makefile

Maintainer: me
Run tested: -
Description:
The most notable change is the introduction of (optional) support for hardware OPAL disk encryption. However, as this requires Linux 6.4 or later, support for OPAL is implicitely disabled until targets used for the package build have been updated to Linux 6.6.
See release notes for 2.7.0 and 2.7.1 for more details:
https://cdn.kernel.org/pub/linux/utils/cryptsetup/v2.7/v2.7.0-ReleaseNotes
https://cdn.kernel.org/pub/linux/utils/cryptsetup/v2.7/v2.7.1-ReleaseNotes

cryptsetup: update to version 2.7.1

---

net/libcurl-gnutls/Makefile

Maintainer: me
Run tested: -
Description:
See https://curl.se/changes.html#8_7_1

libcurl-gnutls: update to verison 8.7.1

---

net/curl/Makefile
net/curl/patches/200-no_docs_tests.patch

Maintainer: me
Description:
* update to 8.7.1: https://curl.se/changes.html#8_7_1
* use the new --disable-docs flag for configure
* update 200-no_docs_tests.patch
* switch to APK-compatible revision

curl: update to 8.7.1

---

utils/nano/Makefile
utils/nano/files/ucode.nanorc

Description:
Text between interpreter line and start of first directive should only highlighted as uninterpreted when running in template mode, so adjust the match rule accordingly.
Fixes: #23761

nano: fix syntax highlighting for raw ucode scripts

---

utils/collectd/Makefile

Compile tested: bcm27xx/bcm2708, sunxi/cortexa8
Run tested: A10-oLinuXino-Lime, Rasberry Pi B (1-st gen)
Description:
Very handy and small [statsd](http://github.com/collectd/collectd/wiki/Plugin-StatsD) input plugin without additional dependencies.

collectd: enable statsd plugin

---

libs/dmx_usb_module/Makefile
libs/dmx_usb_module/patches/101-fix-kernel-6.6-builds.patch

Maintainer: @FriedZombie
Compile tested: cortexa53,ti-k3,master branch
Run tested: no
Description:
Fix compiling the dmx_usb_module module against kernel 6.6.

dmx_usb_module: fix 6.6 kernel compile

---

utils/base16384/Makefile

Maintainer: me
Compile tested: x86/64, Generic PC, OpenWrt 22.03.2 r19803-9a599fee93
Run tested: x86/64, Generic PC, OpenWrt 22.03.2 r19803-9a599fee93
Signed-off-by: 源 文雨 <fumiama@foxmail.com>

base16384: bump to version 2.3.0

---

utils/fx/Makefile

Maintainer: @dynasticorpheus  
Compile tested: Ubuntu 23.04 x64 / OpenWrt SNAPSHOT @ 36b1dd75fd9da1ea13f1ce1ee679c6b3c9c402cc
Description: Update to [34.0.0](https://github.com/antonmedv/fx/compare/33.0.0...34.0.0)

fx: update to 34.0.0

---

net/ksmbd-tools/Makefile

Major changes are:
- Add durable handles parameter to ksmbd.conf.
- Add payload_sz in ksmbd_share_config_response to validate ipc response.
- Fix UAF and cleanups.
Compile tested: mediatek/filogic GL.iNet GL-MT6000 OpenWRT snapshot r25843-4d69e130c6
Run tested: mediatek/filogic GL.iNet GL-MT6000 OpenWRT snapshot r25843-4d69e130c6
Tested
-add new user
-mod existing user
please cherry-pick to 23.05, thanks a lot

ksmbd-tools: update to version 3.5.2

---

lang/node/Makefile
lang/node/patches/003-path.patch
lang/node/patches/202-node_gyp.patch
lang/node/patches/204-v8_gyp.patch
lang/node/patches/999-localhost-no-addrconfig.patch
lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch

Run tested: (qemu 8.2.1) aarch64
Description:
Update to v20.12.1
This is a security release
* CVE-2024-27983 - Assertion failed in node::http2::Http2Session::~Http2Session() leads to HTTP/2 server crash- (High)
* CVE-2024-27982 - HTTP Request Smuggling via Content Length Obfuscation - (Medium)
* llhttp version 9.2.1
* undici version 5.28.4
Changed to use gz according to main-snapshot

node: April 3, 2024 Security Releases

---

lang/node/Makefile
lang/node/patches/003-path.patch

Run tested: (qemu 8.2.1) aarch64
Description:
Update to v18.20.1
* CVE-2024-27983 - Assertion failed in node::http2::Http2Session::~Http2Session() leads to HTTP/2 server crash- (High)
* CVE-2024-27982 - HTTP Request Smuggling via Content Length Obfuscation - (Medium)
* llhttp version 9.2.1
* undici version 5.28.4
Changed to use gz according to main-snapshot

[23.05] node: April 3, 2024 Security Releases

---

libs/glib2/Makefile

some compile error happens when building.
Linking to libiconv-full fixes this.
refer to: https://github.com/openwrt/openwrt/commit/63dd14b906e9eb27bc878b95ac6777a3624b1135
fix this error: 
```
ninja: Entering directory `/home/nasbdh9/openwrt/build_dir/hostpkg/glib-2.74.7/openwrt-build'
[1/240] Linking target glib/gtester
FAILED: glib/gtester
/home/nasbdh9/openwrt/staging_dir/host/bin/gcc  -o glib/gtester glib/gtester.p/gtester.c.o -L/home/nasbdh9/openwrt/staging_dir/host/lib -L/home/nasbdh9/openwrt/staging_dir/hostpkg/lib -L/home/nasbdh9/openwrt/staging_dir/target-x86_64_musl/host/lib -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group glib/libglib-2.0.a -pthread -lm -Wl,--end-group
/usr/bin/ld: glib/libglib-2.0.a(gconvert.c.o): in function `try_conversion': …
```

glib2: link libiconv when building host pkg

---

utils/base16384/Makefile

Maintainer: me
Compile tested: x86/64, Generic PC, OpenWrt 22.03.2 r19803-9a599fee93
Run tested: x86/64, Generic PC, OpenWrt 22.03.2 r19803-9a599fee93
Signed-off-by: 源 文雨 <fumiama@foxmail.com>

base16384: bump to version 2.3.1

---

mail/exim/Makefile
mail/exim/patches/010-allow-json-dynamic-lookup.patch
mail/exim/patches/030-openssl-deprecated.patch
mail/exim/patches/100-localscan_dlopen.patch
mail/exim/patches/200-fix-build.patch
mail/exim/patches/210-no-exim_id_update.patch
mail/exim/patches/300-avoid-time-printf.patch

Maintainer: me
Run tested: -
Description:
**IPv6 has accidentally been disabled in all Exim builds since the package was introduced in OpenWrt due to a faulty `sed` script. This has now been fixed, so beware that IPv6 is now enabled when updating from previous releases.**
Since Exim version 4.97
-----------------------
JH/s1 Refuse to accept a line "dot, LF" as end-of-DATA unless operating in
LF-only mode (as detected from the first header line).  Previously we did
accept that in (normal) CRLF mode; this has been raised as a possible
attack scenario (under the name "smtp smuggling", CVE-2023-51766).
Exim version 4.97
-----------------
JH/01 The hosts_connection_nolog main option now also controls "no MAIL in
SMTP connection" log lines.
JH/02 Option …

exim: update to 4.97.1

---

kernel/ovpn-dco/Makefile

Fixes builds against kernel 6.6
Maintainer:
Compile tested: AArch64 kernel 6.6
Run tested: no

ovpn-dco: bump version to 0.2.20240320

---

utils/acpica-unix/Makefile

Remove PKG_CAT. No need for it.

acpica-unix: update to 20240321

---

libs/openblas/Makefile

- Add ONLY_CBLAS make flag to skip tests (fixes x86 builds)

openblas: update to 0.3.27

---

net/mosquitto/files/etc/init.d/mosquitto

Compile tested: NanoPi R4s / SNAPSHOTS
Run tested: NanoPi R4s / SNAPSHOTS
Description:
Support anonymous user per listener

mosquitto: support anonymous user per listener in UCI config

---

libs/libarchive/Makefile

Run tested: ARMv7, Linksys WRT3200ACM, master branch, tesseract package depening from this works all right

libarchive: update to 3.7.3

---

net/pppossh/Makefile
net/pppossh/README.md
net/pppossh/files/pppossh.sh

Maintainer: me
Run tested: x86_64 on qemu kvm, OpenWrt 22.03.5, ifup/down
Description:
This can be useful for things like making the interface on the peer side fixed with value like `ifname xx`

pppossh: add option peer_pppd_options

---

utils/whois/Makefile

Description:
- Don't override PKG_BUILD_DIR since tarball is now properly constructed

whois: update to 5.5.22

---

net/softflowd/Makefile
net/softflowd/files/softflowd.config
net/softflowd/files/softflowd.init

- add '-b' option to enable bidirectional flow probing
Maintainer: @rvandegrift (Makefile) or @stintel (Git history)
Compile tested: cross-compiled on Linux/x86_64 for ramips/mt7621
Run tested: ramips/mt7621, Asus RT-AX53U running OpenWRT 23.05.0
Test procedure:
* download stock config from downloads.openwrt.org
* set router model and `CONFIG_PACKAGE_softflowd=m`
* compile toolchain, softflowd
* upload package to target, install with `opkg`, update config
* `service softflowd restart`
* verify `-b` arg present with `ps | grep softflowd`

softflowd: add '-b' option to config

---

net/curl/Makefile
net/curl/patches/200-no_docs_tests.patch

Maintainer: me
Description:
* update to 8.7.1: https://curl.se/changes.html#8_7_1
* use the new --disable-docs flag for configure
* update 200-no_docs_tests.patch
* switch to APK-compatible revision
(cherry picked from commit 227c8daa159acdc84aad9e06a6a33f7d07263130)

[23.05] curl: update to 8.7.1

---

net/adblock-fast/Makefile

Maintainer: me
Description:
* improve output of Makefile's prerm routines

adblock-fast: improve Makefile's prerm

---

net/adblock-fast/Makefile

Maintainer: me
Description:
* improve output of Makefile's prerm routines
(cherry picked from commit 9eb61fe02da9085f1c211919af38e3c504098f61)

[23.05] adblock-fast: improve Makefile's prerm

---

net/lighttpd/Makefile

Description:
lighttpd: update to lighttpd 1.4.76 release hash
Release notes:
https://www.lighttpd.net/2024/4/12/1.4.76/

lighttpd: update to lighttpd 1.4.76 release hash

---

net/snort3/Makefile
net/snort3/files/main.uc

A recent change in the ucode interpeter caused a failure when using the 'in' operator.
https://github.com/jow-/ucode/commit/be767ae197babd656d4f5d9c2d5013e39ddbe656
Reported in a forum post by @graysky2.
https://forum.openwrt.org/t/194218/28
Maintainer: @flyn-org @graysky2 

snort3: fix issue caused by ucode semantics change

---

net/lighttpd/Makefile

Description: backport #23919
lighttpd: update to lighttpd 1.4.76 release hash
Release notes:
https://www.lighttpd.net/2024/4/12/1.4.76/

lighttpd: update to lighttpd 1.4.76 release hash - backport to openwrt 22.03

---

net/lighttpd/Makefile

Description: backport #23919
lighttpd: update to lighttpd 1.4.76 release hash
Release notes:
https://www.lighttpd.net/2024/4/12/1.4.76/

lighttpd: update to lighttpd 1.4.76 release hash - backport to openwrt 23.05

---

utils/stress-ng/Makefile
utils/stress-ng/patches/001-disable-extra-stressors.patch

Description:
- Refresh the patch

stress-ng: update to 0.17.07

---

kernel/macremapper/Makefile

By defualt Kernel modules follow the version schema from openwrt.git, which happens to be APK compatible. Instead of defining a entirely custom format, use what's already out there.
This patch drops the individual VERSION definition.
Right now, the version becomes 6.1.82.1.1.0-r2
Maintainer: Carey Sonsino <careys@edgewaterwireless.com>
Compile tested: arm64

macremapper: drop VERSION definition in Makefile

---

net/netbird/Makefile

Compile tested: [mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc), [ar71xx-ath79](https://openwrt.org/docs/techref/targets/ar71xx-ath79), generic, TP-Link, [Archer C7](https://openwrt.org/toh/tp-link/archer_c7), v4, OpenWrt SNAPSHOT r25888-ae192c042c
Run tested: [mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc), [ar71xx-ath79](https://openwrt.org/docs/techref/targets/ar71xx-ath79), generic, TP-Link, [Archer C7](https://openwrt.org/toh/tp-link/archer_c7), v4, OpenWrt SNAPSHOT r25888-ae192c042c
~~Compile tested: [mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc), [ar71xx-ath79](https://openwrt.org/docs/techref/targets/ar71xx-ath79), generic, TP-Link, [Archer …

netbird: update to 0.27.3

---

net/rsync/Makefile

Changelog: https://download.samba.org/pub/rsync/NEWS#3.3.0
```
rsync  version 3.3.0  protocol version 31
Copyright (C) 1996-2024 by Andrew Tridgell, Wayne Davison, and others. Web site: https://rsync.samba.org/
Capabilities:
64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
no socketpairs, symlinks, symtimes, hardlinks, no hardlink-specials,
no hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, no ACLs,
no xattrs, optional secluded-args, no iconv, prealloc, stop-at,
no crtimes
Optimizations:
no SIMD-roll, no asm-roll, no openssl-crypto, asm-MD5
Checksum list:
md5 md4 none
Compress list:
zlibx zlib none
Daemon auth list:
md5 md4
```

rsync: update to 3.3.0

---

lang/golang/golang/Makefile

Run tested: nanopi-r2c
Description:
go1.21.9 (released 2024-04-03) includes a security fix to the net/http package, as well as bug fixes to the linker, and the go/types and net/http packages.

[openwrt-23.05] golang: Update to 1.21.9

---

net/snort3/Makefile
net/snort3/patches/110-packet_capture-Fix-compilation-with-GCC-13.patch

1. Update to latest version
2. Remove redundant section in Makefile
Changelog: https://github.com/snort3/snort3/releases/tag/3.1.84.0
```
o"  )~   Version 3.1.84.0
Copyright (C) 2014-2024 Cisco and/or its affiliates. All rights reserved.
Using DAQ version 3.0.14
Using OpenSSL 3.0.13 30 Jan 2024
Using ZLIB version 1.3.1
Using Hyperscan version 5.4.2 2024-04-10
Using LZMA version 5.4.6
```

snort3: update to 3.1.84.0

---

kernel/mtd-rw/Makefile

Maintainer: Joseph C. Lehner <joseph.c.lehner@gmail.com>
Compile tested: arm64
Run tested: -
Description:
By default Kernel modules follow the version schema from openwrt.git, which happens to be APK compatible. Instead of defining a entirely custom format, use what's already out there.
This patch drops the individual PKG_VERSION definition.
Right now, the version becomes 6.1.82.0~7e856206-r2.

mtd-rw: drop PKG_VERSION definition in Makefile

---

net/hcxdumptool/Makefile

hcxdumptool: Update to 6.3.4
Version 6.3.4 has some important fixes for the OpenWrt community. This version properly supports Big-Endian systems (which are many); the previous OpenWrt packaged version crashed on such systems.
Maintainer: Andreas Nilsen <adde88@gmail.com>
Compile tested: (put here arch, model, OpenWrt version) Compiled for GL.iNet E750 running OpenWrt 23.05.2, MIPS Big-Endian
Run tested: Tested working on OpenWrt 23.05.2, MIPS Big-Endian
Description:
- Adds BE support
- Adds internal BPF compilation

hcxdumptool: Update to 6.3.4

---

lang/erlang/Makefile

Run tested: arm_cortex-a9_neon, master branch
What's new - https://erlang.org/download/OTP-26.2.4.README

erlang: update to 26.2.4

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr

Maintainer: me
Description:
* update license to AGPL-3.0-or-later
* rename pbr_get_gateway to pbr_get_gateway4 for better readability
* improve IPv6 "gateway" detection/display on start
* prevent IPv6 interface errors on start
* revert release format

pbr: bugfix: fix IPv6 interface errors

---

lang/php8/Makefile

This fixes:
- CVE-2024-1874
- CVE-2024-2756
- CVE-2024-3096
Maintainer: me
Run tested: -

[22.03] php8: update to 8.1.28

---

libs/libdaq3/Makefile
net/snort3/Makefile

This PR updates both snort3 and libdaq3 to their latest versions in sync with master and also removes reference to a problematic symbol in snort3.  Let me know if multiple commits needs to be squashed or if bumping both snort3 and libdaq3 in one PR is not allowed.

snort3 and libdaq3: sync with master and remove symbol @HAS_LUAJIT_ARCH

---

lang/php8/Makefile

This fixes:
- CVE-2024-1874
- CVE-2024-2756
- CVE-2024-3096
While at, switch to https download URL.
Maintainer: me
Run tested: -

[23.05] php8: update to 8.2.18

---

net/nginx/Makefile

Since the geoip2 package contains both `http` and `stream` versions. It requires the module `ngx_stream` be installed and loaded and produces the error:
```
2024/04/12 18:38:18 [emerg] 4402#0: dlopen() 
"/usr/lib/nginx/modules/ngx_stream_geoip2_module.so" failed 
(Error relocating /usr/lib/nginx/modules/ngx_stream_geoip2_module.so: ngx_stream_complex_value: symbol not found) in /etc/nginx/module.d/ngx_stream_geoip2.module:1
nginx: configuration file /etc/nginx/uci.conf test failed
```
Add dependency so it gets built and installed automatically.
**Run tested**: aarch64, Dynalink DL-WRX36, Master Branch
**Compile tested**: aarch64, qualcommax, Master Branch
**Compile produces follows**:
```
nginx-ssl_1.25.4-r3_aarch64_cortex-a53.ipk
nginx-mod-ubus_1.25.4-r3_aarch64_cortex-a53.ipk …
```

nginx: fix geoip2 dependency on mod ngx_stream

---

net/nginx/Makefile
net/nginx/files-luci-support/60_nginx-luci-support

In current setup, dynamic modules are not autoloaded, requiring users to create and load additional config files.
We should assume that if a user installs additional modules, they want them 'on' by default.
This commit does the following:
1. generates a module load config in `'/etc/nginx/modules.d'` with the
format `'${module_name}'.module`
(i.e. `/etc/nginx/modules.d/ngx_http_geoip2.module`)
2. deletes previous module conf for `'luci'`
`/etc/nginx/modules.d/luci.module` if it exists, this will prevent
`'module already loaded'` errors.
The following is a portion of the final output when using the default uci template `/etc/nginx/uci.conf.template` (via nginx-util):
```
nginx -T -c '/etc/nginx/uci.conf' | grep load_module
nginx: the configuration file /etc/nginx/uci.conf syntax is ok …
```

nginx: autoload dynamic modules

---

net/nginx/Makefile

This commit does the following:
1.) Add module source date
2.) Use new APK style formatting
3.) Switch to 'zst' tarball vs. 'xz'
Note that `SOURCE_DATE` will need to be updated as the commit date of the commit hash changes
Before:
```
nginx-mod-geoip2-1cabd8a1f68ea3998f94e9f3504431970f848fbf.tar.xz
nginx-mod-headers-more-bea1be3bbf6af28f6aa8cf0c01c07ee1637e2bd0.tar.xz
nginx-mod-brotli-25f86f0bac1101b6512135eac5f93c49c63609e3.tar.xz
nginx-mod-rtmp-f0ea62342a4eca504b311cd5df910d026c3ea4cf.tar.xz
nginx-mod-ts-ef2f874d95cc75747eb625a292524a702aefb0fd.tar.xz
nginx-mod-naxsi-d714f1636ea49a9a9f4f06dba14aee003e970834.tar.xz
nginx-mod-lua-c89469e920713d17d703a5f3736c9335edac22bf.tar.xz
nginx-mod-lua-resty-core-2e2b2adaa61719972fe4275fa4c3585daa0dcd84.tar.xz …
```

nginx: Use zst + APK style packaging for modules

---

lang/python/python-yaml/Makefile

Make the python-yaml/host target available for the build environment to be used with e.g. the PKG_BUILD_DEPENDS list.
Compile tested: x86_64, ARM
Description:
Create host target for the python-yaml package. This is needed for an upcoming package (libcamera).

python-yaml: create /host target

---

lang/python/python-jinja2/Makefile

Make the python-jinja2/host target available for the build environment to be used with e.g. the PKG_BUILD_DEPENDS list.
Maintainer:  Michal Vasilek <michal.vasilek@nic.cz>
Compile tested: x86_64, ARM
Description:
Create host target for the python-jinja2 package. This is needed for an upcoming package (libcamera).

python-jinja2: create /host target

---

net/v2ray-geodata/Makefile

Maintainer: me
Description:
According to the documentation[^1] 'PKG_RELEASE' should be a number,
so polulate the APK-style 'r' via 'VERSION' instead.
Ref: #23913
Cc: @qosmio
[^1]: https://openwrt.org/docs/guide-developer/packages#buildpackage_variables

v2ray-geodata: make PKG_RELEASE numeric again

---

lang/php8/Makefile

This fixes:
- CVE-2024-1874
- CVE-2024-2756
- CVE-2024-2757
- CVE-2024-3096
Maintainer: me

php8: update to 8.3.6

---

net/rsync/Config.in
net/rsync/Makefile

Maintainer: me
Compile tested: aarch64_cortex-a53, Dynalink DL-WRX36, r25915+3-c2f52e42b1
Run tested: aarch64_cortex-a53, Dynalink DL-WRX36, r25915+3-c2f52e42b1, copy a file from the router to the build host with --zc={zstd, lz4, zlibx, zlib} and --checksum-choice={xxh128, xxh3, xxh64, xxhash, md5, md4} works
Description:
- add support for xxhash
- add support for lz4
All options are off by default, but taking into account the size change, maybe it makes sense to enable xxhash?
```
$ ls -lna *.ipk
-rw-r--r--    1 500      100          53872 Apr 14 10:54 liblz4-1_1.9.4-r1_aarch64_cortex-a53.ipk
-rw-r--r--    1 500      100          10498 Apr 14 10:48 libxxhash_0.8.2-r1_aarch64_cortex-a53.ipk
-rw-r--r--    1 500      100         332652 Apr 14 10:48 libzstd_1.5.5-r1_aarch64_cortex-a53.ipk …
```

rsync: enable xxhash and lz4

---

libs/ibrcommon/Makefile
libs/ibrcommon/patches/001-fix-build-with-musl.patch

Can be replaced with regular C++.

ibrcommon: remove basename

---

net/socat/Makefile

Compile tested: arm_cortex-a9_neon, master branch
Fixes an error reported in https://github.com/openwrt/packages/commit/5a06e3471ba0a4a49130b22f936c823142680fe1#comments.

socat: fix compile error when ccache is enabled

---

net/tailscale/Makefile

<https://github.com/tailscale/tailscale/releases/v1.64.1>

tailscale: Update to 1.64.1

---

utils/rtty/patches/0001-Support-POSIX-basename-from-musl-libc.patch

Support POSIX basename used in musl libc 1.2.5.
Compile tested: MIPS BE 
Run tested: no
Upstream PR: https://github.com/zhaojh329/rtty/pull/123

rtty: Fix compilation with musl libc 1.2.5

---

lang/lua-eco/patches/0001-Support-POSIX-basename-from-musl-libc.patch

Support POSIX basename used in musl libc 1.2.5.
Compile tested: mips BE
Run tested: no
Upstream PR: https://github.com/zhaojh329/log/pull/2

lua-eco: Fix compilation with musl libc 1.2.5

---

net/udpspeeder/Makefile

Simpler, smaller, and avoids PKG_UNPACK.
Maintainer: @codemarauder @utoni

udpspeeder: use local tarballs

---

net/banip/Makefile
net/banip/files/README.md
net/banip/files/banip-functions.sh
net/banip/files/banip-service.sh
net/banip/files/banip.countries
net/banip/files/banip.feeds

Maintainer: me / @dibdot 
Run tested: Bananapi BPI-R3, OpenWrt SNAPSHOT r25932-338b463e1e
Description:
* added a DDoS protection rules in a new pre-routing chain to prevent common ICMP, UDP and SYN flood attacks and drop spoofed tcp flags & invalid conntrack packets, flood tresholds are configured via 'ban_icmplimit' (default 10/s), 'ban_synlimit' (default 10/s) and 'ban_udplimit' (default 100/s)
* the new pre-routing rules are tracked via named nft counters and are part of the standard reporting, set 'ban_logprerouting' accordingly
* block countries dynamically by Regional Internet Registry (RIR)/regions, e.g. all countries related to ARIN. Supported service regions are: AFRINIC, ARIN, APNIC, LACNIC and RIPE, set 'ban_region' accordingly
* it's now possible to always …

banip: release 0.9.5-1

---

net/curl/Makefile

Maintainer: n/a
Run tested: n/a - only package formalities changed
Description:
* make PKG_RELEASE numeric again
* made a release bump due to  a newly added patch (see https://github.com/openwrt/packages/commit/de4ef9d169a182350796afca778742bf68052af4 for details)
* remove maintainer (as requested in #23890

curl: fix/bump PKG_RELEASE, remove maintainer

---

utils/tini/patches/002-Support-POSIX-basename-from-musl-libc.patch

Support POSIX basename used in musl libc 1.2.5.
This fixes compilation with musl libc 1.2.5.
Upstream PR: https://github.com/krallin/tini/pull/223
Maintainer: @G-M0N3Y-2503 
Compile tested: mips malta be
Description:

tini: Fix compilation with musl libc 1.2.5

---

libs/libmraa/patches/001-mraa-Use-posix-basename.patch

Support POSIX basename used in musl libc 1.2.5.
This backports a patch from upstream git.
Maintainer: @blogic @nxhack 
Compile tested: Mips BE
Run tested: No
Upstream commit: https://github.com/eclipse/mraa/commit/47c3850cddd63cebd9dc48e411963314449118f1

libmraa: Fix compilation with musl libc 1.2.5

---

utils/eza/Makefile

Maintainer: me
Description:
Release notes:
0.18.10: https://github.com/eza-community/eza/releases/tag/v0.18.10
0.18.11: https://github.com/eza-community/eza/releases/tag/v0.18.11

eza: update to 0.18.11

---

utils/usbmuxd/Makefile
utils/usbmuxd/files/usbmuxd.hotplug

If the iPhone restarts while the USB cable is still connected, tethering does not work. This can be fixed by reconnecting.
Fix: if the `hotplug.d` script detects that carrier is disabled (no communication), the USB link is reset, and then the `usbmuxd` service is restarted. Tethering starts even before the iPhone is unlocked. As a side effect, if tethering is not enabled, the iPhone will ding a second time after 5 seconds.
[1] https://github.com/libimobiledevice/usbmuxd/issues/218
[2] https://github.com/openwrt/openwrt/issues/12566#issuecomment-2066305622
Compile and run tested:
- Marvell EBU Armada, Marvell Armada 37x/38x/XP, Linksys WRT3200ACM, [main](https://github.com/openwrt/openwrt/commit/66019e456f60f5ef71a9af0d73502e20b874d114)
- Atheros ATH79, Generic, TP-Link …

usbmuxd: fix tethering not working after iPhone restart

---

libs/gost_engine/Makefile

Avoids PKG_UNPACK hacks.
Added PKG_LICENSE_FILES.
Reordered variables for consistency between packages.
Maintainer: @cotequeiroz
I find it intetesting the original PR is not in here.

gost_engine: switch to local tarballs

---

net/tailscale/Makefile

<https://github.com/tailscale/tailscale/releases/v1.64.2>

tailscale: Update to 1.64.2

---

libs/libwebp/Makefile

Run tested: arm_cortex-a9_neon, master branch
What's new: https://github.com/webmproject/libwebp/commit/dc9505855eac80078868e491f6cfe691243e859b

libwebp: update to 1.4.0

---

net/xtables-addons/Makefile

Fix broken compile with external Toolchain.
Commit 32aaaaa7d379 ("xtables-addons: pass correct flags to compile and install") simplified and dropped the custom Compile/Install in favor of the default one. Problem is that it dropped DESTDIR resulting in the package having problem on finishing install.
The commit then was reworked with c83b8787a5f8 ("xtables-addons: adapt build to EXTERNAL_TOOLCHAIN" that reintroduced DESTDIR and also introduced a useless custom flag to fix wrong ARCH.
ARCH is fixed by kernel.mk and doesn't depend on external Toolchain or not. For ARCH that require fixing, kernel.mk should be fixed instead of adding custom function to packages Makefile.
The real problem was overwriting the MAKE_FLAGS and MAKE_INSTALL_FLAGS
instead of simply appending the additional required …

xtables-addons: fix broken compile with external Toolchain

---

lang/luaexpat/Makefile

Smaller and avoids badly named tarball with just the version.

luaexpat: use local tarballs

---

libs/gperftools/Makefile
utils/dockerd/Makefile
utils/mstflint/Makefile

These packages exclude mips but forget to exclude mips64.

treewide: exclude mips64

---

net/snort3/Makefile

Avoids having a bad tarball name with just the version.

snort3: use local tarballs

---

utils/cni-plugins/Makefile

Avoids having to override PKG_UNPACK.

cni-plugins: use local tarballs

---

utils/cni-plugins-nft/Makefile

Avoids having to override PKG_UNPACK.

cni-plugins-nft: use local tarballs

---

lang/perl/Makefile
lang/perl/patches/920-Revert-perl-127606-adjust-dependency-paths-on-instal.patch

Reverts the changes in https://github.com/Perl/perl5/commit/88efce38149481334db7ddb932f9b74eaaa9765b to resolve the following build error on macOS:
```
/Volumes/wrt3200/openwrt/staging_dir/hostpkg/usr/bin/perl installperl --destdir=/Volumes/wrt3200/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.38.2/ipkg-install WARNING: You've never run 'make test' or some tests failed! (Installing anyway.)
/usr/bin/perl5.38.2
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: input file: /Volumes/wrt3200/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.38.2/ipkg-install/usr/bin/perl5.38.2 is not a Mach-O file
```
[Complete build log](https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/w …

perl: fix not a Mach-O file on macOS

---

lang/node/Makefile

Run tested: (qemu 8.2.2) aarch64
Description:
* CVE-2024-27980 - Command injection via args parameter of child_process.spawn without shell option enabled on Windows

node: bump to v20.12.2

---

net/natmap/Makefile
net/natmap/files/natmap.config
net/natmap/files/natmap.init

Compile tested: x86-generic, snapshot
Run tested: x86-generic, snapshot
Description:
Introduce `log_stdout` and `log_stderr` options for managing logging output.

natmap: add log_std{out,err} options

---

lang/node/Makefile

Run tested: (qemu 8.2.2) aarch64
Description:
* CVE-2024-27980 - Command injection via args parameter of child_process.spawn without shell option enabled on Windows

[23.05] node: bump to v18.20.2

---

net/natmap/Makefile
net/natmap/files/natmap.config
net/natmap/files/natmap.init

Compile tested: x86-generic, 22.03
Run tested: x86-generic, 22.03
Description:
Introduce `log_stdout` and `log_stderr` options for managing logging output.

[22.03] natmap: add log_std{out,err} options

---

net/natmap/Makefile
net/natmap/files/natmap.config
net/natmap/files/natmap.init

Compile tested: x86-generic, 23.05
Run tested: x86-generic, 23.05
Description:
Introduce `log_stdout` and `log_stderr` options for managing logging output.

[23.05] natmap: add log_std{out,err} options

---

sound/shairport-sync/Makefile
sound/shairport-sync/files/shairport-sync.config
sound/shairport-sync/files/shairport-sync.init

Maintainer: @mikebrady 
Compile tested: NanoPi R4s SNAPSHOT
Run tested: NanoPi R4s SNAPSHOT
Description:
- Enable compile time MQTT support in shairport-sync
- Support all shairport-sync related MQTT config in UCI 
Why ?
shairport-sync is remote control capable over MQTT. This, along with a custom script outside the scope of this PR, is needed to stop shairport sync when for instance a mpd / other audio servers are playing

shairport-sync:  mqtt support

---

libs/ngtcp2/Makefile

Maintainer: Tianling Shen <cnsztl@immortalwrt.org>

ngtcp2: Use APK style release number

---

lang/lua-eco/Makefile

Maintainer: me
Description:
Release notes for 3.4.1: https://github.com/zhaojh329/lua-eco/releases/tag/v3.4.1

lua-eco: update to 3.4.1

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.27.0)

docker-compose: Update to version 2.27.0

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3, check the header of the unbound block-list
Description:
* include `server:` directive at the top of unbound file
* update unbound-related outputGzip variable to include full path
* return always_nxdomain for blocked domains
* also update copyright stamp/license
Depends on https://github.com/openwrt/packages/pull/23982 for unbound block-list functionality, otherwise fully functional for dnsmasq/smartdns.

adblock-fast: bugfix: unbound-related fixes

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3
Description:
* include `server:` directive at the top of unbound file
* update unbound-related outputGzip variable to include full path
* return always_nxdomain for blocked domains
* also update copyright stamp/license
(cherry picked from commit 474587a1f44db8b66caca8bdde9c2dd64b480638)

[23.05] adblock-fast: bugfix: unbound-related fixes

---

admin/syslog-ng/Makefile
admin/syslog-ng/files/syslog-ng.conf

Maintainer: me
Compile tested: MacBook A1990, Sonoma 14.4.1
Run tested: Turris Omnia, mvebu/cortexa9, OpenWrt 22.03.6
Release notes:
- https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-4.7.0
- https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-4.7.1
Also bump version in the config file to avoid warning

syslog-ng: update to version 4.7.1

---

net/librespeed-go/Makefile

Run tested: no
Description: This softens a couple of [rough edges that I ran into when trying to use this package.](https://forum.openwrt.org/t/how-do-i-use-the-librespeed-go-package/195804) 
* The first change reorders the description so that the one line you get in the LuCI Software page should read "This is a very lightweight speed test implemented in JavaScript,..." instead of what it currently shows:
* ~~The second is a configuration change to enable it by default, which should allow it to be managed via the Startup page in LuCI. (Without this change, it appears there, but none of the buttons actually work.)~~ dropped now.
I put both of these into the same PR, but I can split them into two if desired.
Neither change was tested locally. I …

ibrespeed-go: config improvements

---

net/snort3/Makefile
net/snort3/patches/900-core-convert-project-to-PCRE2.patch

Add experimental patch and move package to PCRE2 as PCRE is EOL and won't receive any security updates anymore.

snort3: add patch and move to PCRE2

---

net/snort3/Makefile
net/snort3/files/snort-mgr

Parameter not set in two places: /usr/bin/snort-mgr: eval: line 125: options: parameter not set
Reported-by: @klingon888
Maintainer: @flyn-org @graysky2 
Description:
`snort-mgr` fails due to unset variable in two places.

snort3: fix bug with unset variable

---

lang/lua5.4/Makefile
lang/lua5.4/patches-host/001-include-version-number.patch
lang/lua5.4/patches-host/100-no_readline.patch
lang/lua5.4/patches/001-include-version-number.patch
lang/lua5.4/patches/020-shared_liblua.patch
lang/lua5.4/patches/100-no_readline.patch

Add new lua version 5.4 required by new version of nmap.
Patch copied from lua 5.3. Readline patch has to be reworked as lua 5.4 now supports no readline for linux but still needs some tweaks for macos and bsd systems.
Patch shared lib required some rework.
---
@BKPepe is this ok? Required for nmap bump

lua5.4: Add new lua version

---

mail/msmtp/Makefile

Maintainer: no one
Host env: MacBook A1990, Sonoma 14.4.1
Run tested: Turris Omnia, mvebu/cortexa9, OpenWrt 22.03.6
Release notes:
https://marlam.de/msmtp/news/msmtp-1-8-25/

msmtp: update to version 1.8.25

---

net/pdns-recursor/Makefile

Maintainer: me
Compile tested: in github actions
Description:

pdns-recursor: update to 5.0.4, fixes CVE-2024-25583

---

libs/hyperscan/Makefile
libs/hyperscan/patches/0001-CMakeLists.txt-hack-for-our-build-system.patch

Maintainer: me
If building with the project external toolchain, the gcc check fails to set the correct value for TUNE_FLAG to allow the min supported SSSE3 compiler support test to pass.  This patch hacks the file to set to the correct value.
Links to upstream bug reports:
https://github.com/openwrt/openwrt/issues/15216
https://github.com/intel/hyperscan/issues/431
Build system: x86/64 (build system toolchain and x86/64 w/ external toolchain (18-Apr-2024 snapshot)

hyperscan: fix broken build w/ external toolchain

---

libs/gnutls/Makefile
libs/gnutls/patches/010-m4.patch
libs/gnutls/patches/030-unistring-optional.patch

All patches automatically refreshed.
The most important changes are two "medium" CVEs fixed in GnuTLS 3.8.4:
- CVE-2024-28834 / GNUTLS-SA-2023-12-04
A vulnerability was found that the deterministic ECDSA code leaks
bit-length of random nonce which allows for full recovery of the
private key used after observing a few hundreds to a few thousands of
signatures on known messages, due to the application of lattice
techniques.
The issue was reported in the issue tracker as [#1516](https://gitlab.com/gnutls/gnutls/-/issues/1516).
- CVE-2024-28835 / GNUTLS-SA-2024-01-23
When validating a certificate chain with more then 16 certificates
GnuTLS applications crash with an assertion failure.
The issue was reported in the issue tracker as [#1527](https://gitlab.com/gnutls/gnutls/-/issues/1527) and …

gnutls: Update to version 3.8.5

---

utils/containerd/Makefile
utils/docker/Makefile
utils/dockerd/Makefile

Description:
* Updated docker to v26.1.0 and required dependencies
* Added missing Golang compilation file for docker
* Updated GOlang Makefile variables across dependencies
[23.05 Backport PR](https://github.com/openwrt/packages/pull/24065)

Docker: Update to 26.1.0

---

net/speedtest-go/Makefile

This is a Command Line Interface (CLI) and pure Go API to test internet speed using speedtest.net. Its upstream is https://github.com/showwin/speedtest-go
Compile tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.096.15376-b029f06)
Run tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.096.15376-b029f06)
Description: Add new package, a CLI with go to test internet speed

speedtest-go: add new package

---

utils/flashrom/Makefile
utils/flashrom/flashrom.mk

Compile tested: qualcommax-ipq807x
Run tested: edgecore_eap102
Description:
I can't compile the current OpenWrt master branch without this change. I'm not 100% sure if this is the best way to fix it, but I hope it may be useful to somebody who may encounter the same issue.
It seems that newer version of meson do not allow empty arguments but `PROGRAMMER_ARGS` begin with a comma, which is considered as an empty argument.

flashrom: strip leading whitespace from PROGRAMMER_ARGS

---

lang/lua-eco/Makefile

Maintainer: me
Description:
Release notes for 3.5.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.5.0

lua-eco: update to 3.5.0

---

utils/containerd/Makefile
utils/docker/Makefile
utils/dockerd/Makefile

Compile tested: x86_x64, QEMU/KVM, openwrt-23.05
Run tested: x86_x64, QEMU/KVM, openwrt-23.05
Description:
* Updated docker to v26.1.0 and required dependencies
* Added missing Golang compilation file for docker
* Updated GOlang Makefile variables across dependencies
[Master PR](https://github.com/openwrt/packages/pull/24064)

Docker: Update to 26.1.0 Backport

---

net/gensio/patches/0001-Ensure-that-ax_python_devel_found_is_defined.patch

Compile tested: Raspberry Pi
Run tested: -
Description:
This should solve the issue found on the buildbots:
-snip-
...
checking consistency of all components of python development environment... yes ./configure: line 24172: test: =: unary operator expected checking for pam_start in -lpam... (cached) no
...
-snap-
For still unknown reason, AX_PYTHON_DEVEL from the included m4 file is not used which would set the variable the correct way.

gensio: add patch with workaround for buildbots (refs #24047)

---

libs/glib2/Makefile

For the InstallDev target, the pkg-config should point to the glib2 host tools for glib_compile_resources, gdbus_codegen, glib_genmarshal and glib_mkenums instead of pointing to the targets ones as they are unusable by the host machine (due to crosscompiling)
Fix the pkg-config to reference the host tools by replaying the entry and use the prefix_hostpkg variable provided by our pkg-config.
---
This fix the recent error with grilo-plugins trying to use target glib_compile_resources instead of the host one.

libs: glib2: fix provided pkg-config and always use host tools

---

net/openssh/Makefile

Compile tested: master, VirtualBox
Run tested: VirtualBox
Description:
The PR is part of https://github.com/openwrt/openwrt/pull/14174 so please read motivation there.
If will be in a draft state unless a new version of the Dropbear is released.

openssh-keygen: Make ssh-keygen as an alternative to dropbearkey

---

net/ocserv/Makefile

Maintainer: me\
Run tested: -
Description:
ipcalc is a mandatory tool for the test suite, but we do not run it. This patch fixes compilation.

ocserv: set ipcalc explicitly

---

net/nginx/Makefile
net/nginx/patches/nginx/300-fix-deprecated-openssl-3_0.patch

`EVP_CIPHER_CTX_cipher()` function was deprecated in OpenSSL 3.0. As per OpenSSL's recommendation (https://www.openssl.org/docs/manmaster/man3/EVP_CIPHER_CTX_get0_cipher.html) switch to using `EVP_CIPHER_CTX_get0_cipher()` instead.
This would remedy the following:
```
-L/data/code/openwrt/ipq/staging_dir/target-aarch64_cortex-a53_musl/usr/lib -L/data/code/openwrt/ipq/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.2.0_musl/usr/lib -L/data/code/openwr  t/ipq/staging_dir/toolchain-aarch64_cortex-a53_gcc-13.2.0_musl/lib -fuse-ld=mold -Wl,--gc-sections -flto=auto -fuse-linker-plugin -zrelro \
-shared
mold: error: undefined symbol: EVP_CIPHER_CTX_cipher
>>> referenced by <artificial>
>>>               /data/code/openwrt/ipq/tmp/ccBL6cZK.ltrans24.ltrans.o:(ngx_quic_crypto_common.isra.0)>>> …
```

nginx: QUIC: Fix SSL 3.0 deprecated function

---

net/strongswan/Makefile
net/strongswan/files/swanctl.init

Compile tested: x86_64, generic, HEAD (187d704e3b)
Description:

strongswan: Add missing declarations in swanctl

---

net/stunnel/Makefile

Maintainer: me
Compile tested: x86_64/lantiq_xrx200, APU3, OpenWrt latest
Run tested: x86_64, APU3, OpenWrt latest, tests done)
Description:
```
[.] stunnel 5.72 on x86_64-openwrt-linux-gnu platform
[.] Compiled/running with OpenSSL 3.0.13 30 Jan 2024
[!] Invalid configuration file name "-v"
[!] realpath: No such file or directory (2)
```

stunnel: update to version 5.72

---

net/net-tools/Makefile

Maintainer: @Borromini (?)
Compile tested: x86_64, APU3 , OpenWrt latest
Run tested: x86_64, APU3, OpenWrt latest, tests done
Description:
Some user may want or need the full fuctionality of the netstat tool.

net-tools: add netstat utiltiy

---

net/keepalived/Makefile
net/keepalived/patches/0001-vrrp-remove-logging-on-status-output.patch

Maintainer: me
Compile tested: x86_64, APU3, OpenWrt latest
Run tested: x86_64, APU3, OpenWrt latest, tests done
Description:
The 'luci-app-keepalived' uses the status json output to parse this information for the status page. The problem is that when the LuCI status page is open in the browser, the query is logged every 3 second into the syslog. This is not needed and can therefore be removed.
This patch was already merged upstream:
https://github.com/acassen/keepalived/commit/6cce75f4eb65551a61d2e4ba775637b288c1d592

keepalived: add patch to remove log message on json output

---

lang/golang/golang-values.mk

Compile tested: loongarch64/generic
Description:
Bring on the faillogs like #21267 😆

golang: Enable loongarch64 for Go compiler and packages

---

lang/php8/Makefile
lang/php8/patches/1020-php-intl_unbreak_build_with_ICU_75.patch

Maintainer: @mhei 
Compile tested: aarch64, arm, x86_64 
Run tested: (qemu-9.0.0) aarch64
Description:
Preparing to update icu4c to 75.
Created a patch for build errors in php-intl.
```
In file included from /mnt/node/openwrt/staging_dir/target-aarch64_generic_musl/usr/include/unicode/unistr.h:39,
from ext/intl/intl_convertcpp.h:22,
from ext/intl/intl_convertcpp.cpp:17:
/mnt/node/openwrt/staging_dir/target-aarch64_generic_musl/usr/include/unicode/stringpiece.h:133:29: error: 'enable_if_t' in namespace 'std' does not name a template type
133 |             typename = std::enable_if_t<
|                             ^~~~~~~~~~~
/mnt/node/openwrt/staging_dir/target-aarch64_generic_musl/usr/include/unicode/stringpiece.h:133:24: note: 'std::enable_if_t' is only available from C++14 onwards
133 | …
```

php8: Support for icu 75

---

net/openconnect/Makefile
net/openconnect/patches/020-anyconnect.patch

Fixes: #21135
Maintainer: me
Compile tested: arm_cortex-a9+vfpv3-d16_musl_eabi
Run tested: -
Description:
Backport fix for AnyConnect protocol compatibility.

openconnect: backport fix for anyconnect compatibility

---

utils/eza/Makefile

Maintainer: me
Description:
Release notes:
0.18.13: https://github.com/eza-community/eza/releases/tag/v0.18.13
0.18.14: https://github.com/eza-community/eza/releases/tag/v0.18.14
0.18.15: https://github.com/eza-community/eza/releases/tag/v0.18.15

eza: update to 0.18.15

---

net/speedtest-go/Makefile

Update speedtest-go version to 1.7.5
Compile tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.096.15376-b029f06)
Run tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.096.15376-b029f06)
Description: Add new package, a CLI with go to test internet speed

speedtest-go: update to 1.7.5

---

lang/python/python-jsonschema/Makefile

Maintainer: me
Description:
[Release notes](https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst)

python-jsonschema: Update to 4.22.0

---

net/transmission/Makefile
net/transmission/patches/010-temp-mbedtls3-compile.patch

Signed-off-by: Seo Suchan <tjtncks@gmail.com>
Maintainer: Daniel Golle <daniel@makrotopia.org> / @dangowrt (find it by checking history of the package Makefile)
Compile tested: x64, libvirt, master
Run tested:  x64, libvirt, master, downloading a torrent
Description: insert a patch to make it use renamed function names when complied againest  mbedtls3.x, while update to most resent version too.
Fixes: https://github.com/openwrt/packages/issues/24120

transmission: fix compile with mbedtls3.X

---

net/tailscale/Makefile

<https://github.com/tailscale/tailscale/releases/v1.66.1>

tailscale: Update to 1.66.1

---

net/unbound/Makefile
net/unbound/files/unbound.sh

Compile tested: no, trivial change
Run tested: no, I only tested the new elif expression in shell
Description:
* adblock-fast can generate the compatible adb_list-file, but it's only pulled if net/adblock installed, this patch also pulls in the adb_list file if net/adblock-fast is installed.
* also bump PKG_RELEASE

unbound: pull in adblock-fast generated adb_list

---

sound/pianod/Makefile
sound/pianod/patches/010-mbedtls36.patch

pianod: fix mbedtls 3.6 compilation

---

net/pdns-recursor/Makefile

fixes CVE-2024-25583; also includes changes from 4.8.7 that fix regressions introduced with the security fixes in 4.8.6
Maintainer: me
Run tested: docker openwrt/rootfs:x86_64-openwrt-23.05
Description:

pdns-recursor: update to 4.8.8

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3
Description:
* move extra_command and EXTRA_HELP to the top of the init file
* add packageCompat variable for compatibility check with WebUI
* add OutputFilter variables for supported resolvers
* simplify adb_check with the use of OutputFilter variables
* add show_blocklist command to display currently blocked domains

adblock-fast: update to 1.1.2-1

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3
Description:
* move extra_command and EXTRA_HELP to the top of the init file
* add packageCompat variable for compatibility check with WebUI
* add OutputFilter variables for supported resolvers
* simplify adb_check with the use of OutputFilter variables
* add show_blocklist command to display currently blocked domains
(cherry picked from commit fb151d5b8269f458cd54b75975d6a63ad8401b35)

[23.05] adblock-fast: update to 1.1.2-1

---

utils/dump1090/Makefile
utils/dump1090/patches/010-gcc14.patch

Switch to local tarballs. Smaller.

dump1090: fix compilation with GCC14

---

net/bwm-ng/Makefile
net/bwm-ng/patches/010-gcc14.patch

Header is missing.
Maintainer: @Zokormazo

bwm-ng: fix compilation with GCC 14

---

utils/stlink/Makefile
utils/stlink/patches/010-poll.patch
utils/stlink/patches/020-calloc.patch

Switch to local git tarballs. Smaller.
Upstream backport and a local patch.

stlink: fix compilation with GCC 14

---

admin/schroot/Makefile
admin/schroot/patches/020-gcc14.patch

GCC now does not allow assigning an std::locale to an std::string. No idea why it worked originally.
Also fixed compilation with full NLS.
Maintainer: @jmarcet 
ping @trippleflux

schroot: fix compilation with GCC14

---

utils/bluez/Makefile
utils/bluez/patches/207-gcc14.patch

Remove _GNU_SOURCE to avoid redefinition warning.
Maintainer:

bluez: fix compilation with GCC14

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_updater.sh

When a "service ddns reload" is issued, the ddns processes are being duplicated. It seems the culprit is the -1 in the 'killall' command, and removing it fixes the issue, so this commit removes the -1 as workaround of the problem.
Fixes https://github.com/openwrt/packages/issues/23135 and there is more information in the issue. @maxberger wanted to look at it deeply but until then, this code fixes the issue and it seems not to break anything.
Maintainer: @chris5560, @maxberger, @dibdot
Compile tested: qualcommax/ipq807x, Xiaomi AX3600, OpenWrt snapshot
Run tested: qualcommax/ipq807x, Xiaomi AX3600, OpenWrt snapshot, test reload the service and look at the ps processes to confirm all is as expected.

ddns-scripts: fix duplication of processes when reloading

---

net/uwsgi/Makefile
net/uwsgi/patches/040-gcc14.patch

Wrong pointer type is used.
Fixes: https://github.com/openwrt/packages/issues/24160

uwsgi: fix compilation with GCC14

---

sound/shairport-sync/Makefile
sound/shairport-sync/patches/100-mbedtls3fix.patch

Maintainer: @mikebrady
Compile tested: x86_64, generic, main
Description: updated to compatible with mbedtls 3.X as https://github.com/Mbed-TLS/mbedtls/blob/development/docs/3.0-migration-guide.md , and tested it complies without error, but I don't have any apple sound device to test this: @davidandreoletti  could you test if this works? it doesn't use tls as-is so PSA should not be a problem

Shairport-sync: patch to use mbedtls3

---

net/remserial/Makefile
net/remserial/patches/010-gcc14.patch

Missing function declaration.
Maintainer: @nunojpg

remserial: fix compilation with GCC14

---

lang/rust/Makefile
lang/rust/patches/0004-Use-an-helper-to-move-the-files.patch

Maintainer: @1715173329  @lu-zero 
Compile tested: x86_64, -, OpenWrt latest
Run tested: x86_64, -, OpenWrt latest, tests done
Description:
If the download directory is on another filesystem (NFS), then the current implementation of bootstrapping rust fails. Because the `syscall` (rename) does not work on crossing filesystem boundary.
This patch has already been merged upstream.
https://github.com/rust-lang/rust/pull/124975

rust: fix remote filesystem issue

---

net/snort3/Makefile

Other targets should be able to build against gperftools and realize speed and efficiency gains.
Build-tested: bcm27xx/bcm2712
Run-tested: bcm27xx/bcm2712
Maintainer: me @flyn-org

snort3: build against gperftools for more than x86

---

net/net-snmp/patches/750-ieee802dot11.patch
net/net-snmp/patches/751-gcc-14-fix.patch
net/net-snmp/patches/900-musl-compat.patch

Missing header & incompatible pointer type is now an error
Run tested: Test needed, test not done, since I am not using snmpd.
Description:
Functionalities wise not tested but seems to be passed compilation.
I am fairly new in github or git, assistance might be needed from developers.
Sorry for the last 2 failed PR attempt.

net-snmp: fix compilation with GCC 14

---

utils/nsutils/Makefile
utils/nsutils/patches/010-gcc14.patch

nsutils: fix compilation with GCC14

---

libs/unixodbc/Makefile
libs/unixodbc/patches/010-gcc14.patch

unixodbc: fix compilation with GCC14

---

net/tailscale/Makefile

<https://github.com/tailscale/tailscale/releases/v1.66.3>

tailscale: Update to 1.66.3

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

haproxy: update to v2.8.9

---

net/speedtest-go/Makefile

Update speedtest-go version to 1.7.7
Compile tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.130.56871-0191870)
Run tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.130.56871-0191870)
Description: Add new package, a CLI with go to test internet speed

speedtest-go: update to 1.7.7

---

net/sing-box/Makefile

Maintainer: me
Description:
This version fixes some bugs. Changes can be seen in https://github.com/SagerNet/sing-box/compare/v1.8.12...v1.8.14.

sing-box: update to 1.8.14

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

[openwrt-23.05] haproxy: update to v2.8.9

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

Description: Update to v2.4.26
- See changes: http://git.haproxy.org/?p=haproxy-2.4.git;a=shortlog

[openwrt-22.03] haproxy: update to v2.4.26

---

net/dnsdist/Makefile

fixes CVE-2024-25581
Maintainer: me
Compile tested: yes
Description:

dnsdist: update to 1.9.4

---

net/dnsdist/Makefile

fixes CVE-2024-25581
Maintainer: me
Compile tested: yes
Run tested: no, but i tested 1.9.4 on master
Description:

[23.05] dnsdist: update to 1.9.4

---

net/sslh/Makefile
net/sslh/patches/001-configfile-fix.patch

Maintainer: @jmccrohan
Compile tested: x86 32bit, model, OpenWrt master
Run tested: VirtualBox
Description:
The sslh Makefile's default target "all" now also tries to compile a new version sslh-ev. To disable its compilation the Build/Compile is overridden and to call directly "make sslh-select" or "make sslh-fork" depending on CONFIG_SSLH_SELECT.
Some changes from 001-configfile-fix.patch were applied to the upstream and we can remove them. The only left is a notice "sslh command line arguments override the config".

sslh: update to v1.23.1

---

net/tailscale/Makefile

<https://github.com/tailscale/tailscale/releases/v1.66.4>

tailscale: Update to 1.66.4

---

net/sing-box/Makefile

Maintainer: me
Compile tested: (x86_64, OpenWrt-23.05)
Run tested: (x86_64, OpenWrt-23.05, tests done)
Description:
Cherry picked from #24193.

[23.05] sing-box: update to 1.8.14

---

libs/cyrus-sasl/Makefile
libs/cyrus-sasl/patches/010-gcc14.patch

cyrus-sasl: fix compilation with GCC14

---

libs/openldap/Makefile
libs/openldap/patches/030-gcc14.patch

openldap: fix compilation with GCC14

---

libs/nghttp3/Makefile

Maintainer: me
Description:
* switch back to using tar.gz archives, switch to xz was probably unnecessary and the previous problem building from the tagged release gz was probably cache-related
* drop maintainership

nghttp3: drop maintainership

---

.gitignore

This PR adds file ``.gitignore`` to this repository.

Introduce .gitignore

---

net/iperf3/Makefile

Changelogs since last release:
https://github.com/esnet/iperf/releases/tag/3.17
https://github.com/esnet/iperf/releases/tag/3.17.1

iperf3: update to 3.17.1

---

net/acme-common/files/acme.init

Description:
The use_staging option was deprecated in 9d2d8787cafdfb49339766a00ced422fa75cb883. But it still has a bigger priority than the staging option. This happens because config_get_bool returns 0 when the use_staging option wasn't set. So the next check for the staging var emptiness is always false.
As the simplest fix, use the config_get staging that returns a plain string when the option is not set and if it's empty then fallback to the use_staging.
Once the use_staging option is removed we should get back to the config_get_bool staging.
Also use config_get_bool debug.
The luci-app-acme uses the `use_staging` option. I'll send a PR to fix this.

acme-common: fallback to deprecated use_staging if the staging option is not set

---

mail/msmtp/Makefile
mail/msmtp/test.sh

Maintainer: me
Compile tested and run tested: inside GitHub actions
Release notes:
https://marlam.de/msmtp/news/msmtp-1-8-26/

msmtp: update to version 1.8.26

---

libs/libgpiod/Makefile
utils/avrdude/Makefile
utils/avrdude/patches/0001-Add-support-for-libgpiod-v2-API.patch
utils/openocd/Makefile
utils/openocd/patches/0001-jtag-linuxgpiod-adapt-for-libgpiod-v2-API.patch

Maintainer: me, @thess & @paulfertser 
Compile tested: Raspberry Pi 2
Run tested: Raspberry Pi 2B, OpenWrt main branch (9e86e0b33bfa)
Description:
For a long time, it was not possible to update libgpiod to the most recent version since the dependent in-tree packages avrdude and openocd does not supported the v2.x API of libgpiod yet.
Meanwhile, there was some upstream work. For avrdude, the process finished, support is mainlined and will be part of next upstream release. This PR here includes a backport so that broader audience is already capable to test. 
For openocd, the review process is still ongoing, however, there was already feedback by openocd users that the libgpiod v2 support is working as expected. Here too, a condensed backported patch allows to bring this new material to a …

Update libgpiod to 2.1.1 and update dependent packages

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.27.1)

docker-compose: Update to version 2.27.1

---

utils/augeas/Makefile

Seems upstream now releases on GitHub.
Fixes compilation with GCC14.

augeas: update to 1.14.1

---

libs/gost_engine/Makefile
libs/gost_engine/test.sh

Run tested: manually ran the test on mediatek/filogic
Description:
The engine configuration directory was moved to /etc/ssl/modules.cnf.d/,
but the gost_engine package was using /etc/ssl/engines.cnf.d/ by
mistake.
Fixes: https://github.com/openwrt/packages/commit/3b2fcd6b2fde4bebf9eb54441c1c8f14b40e26a9 ("gost_engine: adapt to new engine build config")
---
This fixes a bug described by @MaxSKash while attempting to fix it in 
https://github.com/openwrt/openwrt/pull/15511.
While at it, add CI testing for the package.

gost_engine: fix config installation directory, add CI test

---

net/netbird/Makefile

| [mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc) | [ar71xx-ath79](https://openwrt.org/docs/techref/targets/ar71xx-ath79) | generic | TP-Link | [Archer C7](https://openwrt.org/toh/tp-link/archer_c7) | v4 | OpenWrt SNAPSHOT r26435-f7f8099aa3 |
| ~[mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc)~ | ~[ar71xx-ath79](https://openwrt.org/docs/techref/targets/ar71xx-ath79)~ | ~generic~ | ~TP-Link~ | ~[Archer C7](https://openwrt.org/toh/tp-link/archer_c7)~ | ~v4~ | ~OpenWrt SNAPSHOT r26390-e83a5618d4~ |
| …

netbird: update to 0.27.10

---

devel/gcc/Makefile
lang/perl/Makefile
lang/rust/Makefile
net/net-snmp/Makefile
utils/gpsd/Makefile
utils/gummiboot/Makefile

Update packages to use new toolchain define and drop usage of TOOLCHAIN_DIR.
---
This depends on https://github.com/openwrt/openwrt/pull/13738 that needs to be merged first.

treewide: update packages to use new toolchain define

---

utils/mg/Makefile
utils/mg/patches/902-fix_for_gcc14.patch

Maintainer: me
Compile tested: head, aarch64
Run tested: aarch64 (qemu-9.0.0)
Description:
Addressing compile errors with gcc-14

mg: fix compilation with GCC 14

---

net/croc/Makefile

breaking changes to fix several CVEs. croc v10.x.x cannot be used with with previous croc versions.
release notes:
https://github.com/schollz/croc/releases/tag/v9.6.16
https://github.com/schollz/croc/releases/tag/v9.6.17
(9.6.16 + .17 were later rereleased as 10.0.0)
https://github.com/schollz/croc/releases/tag/v10.0.0
https://github.com/schollz/croc/releases/tag/v10.0.1
https://github.com/schollz/croc/releases/tag/v10.0.2
https://github.com/schollz/croc/releases/tag/v10.0.3
https://github.com/schollz/croc/releases/tag/v10.0.4
https://github.com/schollz/croc/releases/tag/v10.0.5
Maintainer: me
Run tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt snapshot
Description:
(Please tell me if there are to many links as …

croc: update to 10.0.5

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

Description: Update to v3.0.0 LTS
- New major LTS release
- Enabled QUIC support. It still has to be enabled in the haproxy config

haproxy: update to v3.0.0

---

net/acme-common/Makefile
net/acme-common/files/acme.uci-defaults

Maintainer: @tohojo CC @hgl
Compile tested: OpenWrt main branch
Run tested: VirtualBox
Description:
The `webroot` option was deprecated and users should use the /var/run/acme/challenge by default. The folder itself should be exposed to web.
The simplest way to do this is to create a symlink from /www. This is a default web location for most routers and should cover most cases.
Here I extended the acme.uci-defaults script to create the symlink.
If a user doesn't have the /www folder or it's in other place then the symlink creation will be skipped.
Ideally we should send a PR to all web servers to make them unconditionally serve the folder themselves. But that would be a change that is difficult to push. So as a quick solution this should help just today. 
As an additional topic I tried to …

acme-common: create a symlink to webroot

---

net/sing-box/Makefile

Description:  
Update version to 1.9.0.
For details, please see https://github.com/SagerNet/sing-box/releases/tag/v1.9.0

sing-box: update to 1.9.0

---

libs/ngtcp2/Makefile

ngtcp2: fix bad pkgconfig paths

---

libs/ngtcp2/Makefile

Maintainer: me
Description:
* switch back to using tar.gz archives, switch to xz was probably unnecessary and the previous problem building from the tagged release gz was probably cache-related
* drop maintainership

ngtcp2: drop maintainership

---

devel/cargo-c/Makefile

It is useful to build crates as C libraries.
Maintainer: me
Compile tested: OpenWrt git, 
Run tested: x86_64 linux
Description: Since @esaaprillia needs it to package other crates and asked in https://github.com/lu-zero/cargo-c/issues/374 here the host package, I hope we'll share the burden to update it :)
Ideally it gets a release within the week after the release of its matching rust release.

cargo-c: New host package

---

net/sing-box/Makefile

Description:
Cherry picked from #24265.

[23.05] sing-box: update to 1.9.0

---

net/wsdd2/Makefile
net/wsdd2/patches/010-gcc14.patch

struct msghdr under musl uses padding ints for 64-bit, which means we can't direct initialize like this. Switch to initializing each member explicitly.
Maintainer:

wsdd2: fix compilation with GCC14 and 64-bit

---

utils/whois/Makefile

Description:
- ~Override PKG_BUILD_DIR since tarball dir is missing version suffix (again)~
- Switch to local tarball

whois: update to 5.5.23

---

utils/prometheus-node-exporter-lua/Makefile

prometheus-node-exporter-lua: add missing libubus-lua dependency

---

multimedia/gst1-libav/Makefile
multimedia/gst1-plugins-bad/Makefile
multimedia/gst1-plugins-base/Makefile
multimedia/gst1-plugins-good/Makefile
multimedia/gst1-plugins-ugly/Makefile
multimedia/gstreamer1/Makefile

Maintainer: me
Description:
Updates to 1.24.4 and fixes some build errors from the 1.24.3 packages:
- https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/gst1-plugins-base/compile.txt
- https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/gst1-plugins-ugly/compile.txt
- https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/gst1-plugins-bad/compile.txt

Gstreamer update to 1.24.4

---

utils/zstd/Makefile

Run tested: WRT3200ACM, arm_cortex-a9_neon, GCC 14
Description:
- Adopt the package

zstd: update to 1.5.6

---

multimedia/ffmpeg/Makefile
multimedia/ffmpeg/patches/020-ioctl.patch

Requires disabling a warning as there's an incompatibility between musl ioctl and v4l2_ioctl.
Maintainer: @thess @antonlacon

ffmpeg: fix compilation with gcc14

---

net/acme-common/Makefile
net/acme-common/files/acme.init
net/acme-common/files/acme.uci-defaults

Compile tested: OpenWrt main branch, x86
Run tested: VBox
Description:
Add to uci-defaults script a migration from old deprecated options to new:
use_staging to staging
keylength to key_type
remove standalone
add missing validation_method
We still support the old options in the acme.init if old config was copied after installing of the newer version of the acme-common.
So in a year or two we should remove them with the patch:
```patch
diff --git a/net/acme-common/files/acme.init b/net/acme-common/files/acme.init
--- a/net/acme-common/files/acme.init	(revision de3f1b5c4cf22b1ee06e533c8ace619ff75885ac)
+++ b/net/acme-common/files/acme.init	(date 1717240095041)
@@ -25,11 +25,7 @@
load_options() {
section=$1
-	config_get staging "$section" staging
-	# compatibility for old …
```

acme-common: migrate deprecated options

---

lang/node/Makefile

Run tested: (qemu 9.0.0) aarch64
Description:
Update to v20.14.0
* src,permission: throw async errors on async APIs (Rafael Gonzaga)
* (SEMVER-MINOR) test_runner: support forced exit (Colin Ihrig)

node: bump to v20.14.0

---

lang/node/Makefile

Run tested: (qemu 9.0.0) aarch64
Description:
Update to v18.20.3
This release fixes a regression introduced in Node.js 18.19.0 where http.server.close() was incorrectly closing idle connections. A fix has also been included for compiling Node.js from source with newer versions of Clang. The list of keys used to sign releases has been synchronized with the current list from the main branch.
Updated dependencies
* acorn updated to 8.11.3.
* acorn-walk updated to 8.3.2.
* ada updated to 2.7.8.
* c-ares updated to 1.28.1.
* corepack updated to 0.28.0.
* nghttp2 updated to 1.61.0.
* ngtcp2 updated to 1.3.0.
* npm updated to 10.7.0. Includes a fix from npm@10.5.1 to limit the number of open connections npm/cli#7324.
* …

[23.05] node: bump to v18.20.3

---

net/frr/Makefile

Compile tested: lantiq xrx200
Run tested: lantiq xrx200
Description:
You have to enable the CONFIG_TCP_MD5SIG kernel config option to be able to use the BGP MD5 authentication.

frr: add support for BGP MD5 authentication

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_updater.sh

Maintainer: me
Compile tested: no only script changes
Run tested: x86_64, APU3, OpenWrt latest
Description:
Can any of @McGiverGim @jummo @maxberger  check that the change does not generate regressions? 
I had problem with my ddns update and debugged it and the problem is the DNS server check. 
When the ddns update script is started, the system checks whether the configured DNS server can be reached. This is checked with the 'netcat' tool. The tool tries to establish a TCP connection on port 53 of the configured DNS server.
The problem with this implementation is, that this call blocks the ddns update script until 'netcat' returns from the call.
Verfification failed:
If the IP and the port cannot be reached, the netcat call returns immediately.
Verfification successfull:
If the IP and the …

ddns-scripts: do not verify DNS server on start

---

libs/libgpiod/Makefile

Maintainer: Michael Heimpold / @mhei 
Compile tested: ath79, buffalo,wzr-600dhp, r26434-0a861a0c0f
Run tested: ath79, buffalo,wzr-600dhp, r26434-0a861a0c0f
Description:
From NEWS:
libgpiod v2.1.2
===============
Bug fixes:
- fix C++ bindings build using slibtool
- accept the new style automatic GPIO chip labels from gpio-sim in bash tests
Misc:
- relicense C++ bindings under LGPL-2.1-or-later

libgpiod: update to 2.1.2

---

net/keepalived/Makefile
net/keepalived/files/keepalived.config

Maintainer: me
Run tested: no
Description:
fixes #24021 
This is not supported by keepalived uci configuration handling.
If a script should be called by a notify event, then the script must be placed under the directory '/etc/hotplug.d/keepalived'.

keepalived: remove not supported notify script handling

---

utils/prometheus-node-exporter-lua/Makefile
utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/netclass.lua

Fixes a315c40b7232bbc83582685c98e41466d84d7a35
[initial fix]
Signed-off-by: René Treffer <treffer@measite.de>
[fixup René version]
Signed-off-by: PichetGoulu <pichet@nosuid.be>
[actual commit]
Signed-off-by: Etienne Champetier <champetier.etienne@gmail.com>
Maintainer: me
Fixes #19508

prometheus-node-exporter-lua: fix netclass duplicate TYPE lines

---

.github/workflows/formal.yml

It was decided that we should require to use real name once again. There was discussion about it on the mailing list [1], which was based on the commit in different OpenWrt repo [2]
This reverts commit 7e6cd98ad481184b1a620a9862aa3713d1ab85cc.
[1] https://lists.openwrt.org/pipermail/openwrt-devel/2024-April/042711.html
[2] https://github.com/openwrt/actions-shared-workflows/commit/12d9551f2d07ec34ac813da8612c8014fb393af6
Recent discussion about this was here: https://github.com/openwrt/packages/pull/23072#issuecomment-2018331887 and here: https://github.com/openwrt/packages/pull/23072#issuecomment-2018331887

Revert "ci: no longer require real name"

---

libs/libpfring/Makefile
libs/libpfring/patches/0001-fix-cross-compiling.patch
libs/libpfring/patches/002-implement-probabilistic-sampling.patch
libs/libpfring/patches/100-fix-compilation-warning.patch
libs/libpfring/patches/101-kernel-pf_ring-better-define-sa_data-size.patch

Maintainer: BangLang Huang
Description:
backport patch fixing compilation error for sa_data

[openwrt-23.05] libpfring: backport patch fixing compilation error for sa_data

---

libs/nghttp2/Makefile

Maintainer: @dedeckeh 
Description:
- Switch source back to .xz according to CONTRIBUTING.md

nghttp2: update 1.62.1

---

net/iperf3/Makefile
net/iperf3/patches/010-y2k.patch
net/iperf3/patches/020-big-endian.patch

iperf3: fix usage with big endian

---

utils/stress-ng/Makefile

Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/5b1d6d4607e4a062319225dd8930541cd1974ebe
Run tested: x86 https://github.com/openwrt/openwrt/commit/5b1d6d4607e4a062319225dd8930541cd1974ebe

stress-ng: bump to version 0.17.08

---

net/sing-box/Makefile

Description:
sing-box: update to 1.9.2

sing-box: update to 1.9.2

---

lang/erlang/Makefile

Description:
Latest Erlang update incorrectly detects THP as always enabled, which leads to segmentation fault on systems without transparent hugepages. Here we manually override configure flag by checking actual option of target kernel.

erlang: fix mis-detection of transparent hugepages

---

net/sing-box/Makefile

Description:
sing-box: update to 1.9.3

sing-box: update to 1.9.3

---

libs/libdaq3/Makefile

Changelog: https://github.com/snort3/libdaq/releases/tag/v3.0.15
```
o"  )~   Version 3.1.84.0
Copyright (C) 2014-2024 Cisco and/or its affiliates. All rights reserved.
Using DAQ version 3.0.15
Using OpenSSL 3.0.13 30 Jan 2024
Using PCRE version 10.42 2022-12-11
Using ZLIB version 1.3.1
Using Hyperscan version 5.4.2 2024-05-26
Using LZMA version 5.4.6
```

libdaq3: update to 3.0.15

---

lang/php8/Makefile
lang/php8/patches/0025-php-5.4.9-fixheader.patch
lang/php8/patches/1004-disable-phar-command.patch

Maintainer: me
Compile tested: mxs, bcm27xx
Run tested: Raspberry Pi
Description:
This fixes:
- CVE-2024-4577
- CVE-2024-5458
- CVE-2024-5585
Changelog: https://www.php.net/ChangeLog-8.php#8.3.8

php8: update to 8.3.8

---

lang/php8/Makefile
lang/php8/patches/0025-php-5.4.9-fixheader.patch
lang/php8/patches/1004-disable-phar-command.patch

Maintainer: me
Run tested: mxs (Duckbill)
Description:
This fixes:
- CVE-2024-4577
- CVE-2024-5458
- CVE-2024-5585
Changelog: https://www.php.net/ChangeLog-8.php#8.2.20

[23.05] php8: update to 8.2.20

---

lang/php8/Makefile

Maintainer: me
Description:
This fixes:
- CVE-2024-4577
- CVE-2024-5458
- CVE-2024-5585

[22.03] php8: update to 8.1.29

---

net/unbound/Makefile
net/unbound/files/unbound.sh

Compile tested: no, trivial change
Run tested: Tested by a user on the forum: https://forum.openwrt.org/t/adblock-fast-ad-blocking-service-for-dnsmasq-smartdns-and-unbound/170530/238
Description:
* adblock-fast can generate the compatible adb_list-file, but it's only pulled if net/adblock installed, this patch also pulls in the adb_list file if net/adblock-fast is installed.
* also bump PKG_RELEASE
(cherry picked from commit d7d1743c834dffeb7e3ea0c9ee16ec587788f0ca)

[23.05] unbound: pull in adblock-fast generated adb_list

---

net/tor/Makefile

Minor release, see the changelog [1] for what's new.
[1] https://gitlab.torproject.org/tpo/core/tor/-/blob/tor-0.4.8.12/ChangeLog
Maintainer: @hauke @tripolar 
Run tested: mediatek/filogic (tor-basic)

tor: update to 0.4.8.12 stable

---

lang/php8/Makefile
lang/php8/patches/1020_workaround-external-libgd-feature-detection.patch

Maintainer: me
Compile tested: mxs, bcm27xx
Run tested: Raspberry Pi
Description:
This is an alternative approach to #24209. Instead of switching to bundled/internal libgd, workaround the capability detection by giving the information to the build system directly.
PHP's original approach does not work when cross-compiling, but since it is known which features are enabled in OpenWrt's build, we can directly enable these features here, too.
This is not that future prove, but should do the job for the moment until a proper solution was discussed with upstream.

php8: workaround libgd capability detection (refs #23846)

---

net/modemmanager/Makefile
net/modemmanager/README.md
net/modemmanager/files/lib/netifd/proto/modemmanager.sh

Maintainer: @feckert  / @aleksander0m
Run tested: lantiq_xrx200
Description:
Currently, the proto handler stops if a connection cannot be established during setup. There are scenarios where the user does not want the connection to be re-established (for example, with an incorrect username/password). On the other hand, there are also scenarios where the user wants the connection to be established at all costs. For this, I have added a new option that covers such scenarios.

modemmanager: improve reconnect handling

---

utils/btrfs-progs/Makefile

GCC14 is now supported in this release.
Release notes: https://github.com/kdave/btrfs-progs/releases/tag/v6.9
Compile tested: aarch64 at dbfb023f9f3bd647b00cf6cc83bfcf3857dac449
Run tested: aarch64 at dbfb023f9f3bd647b00cf6cc83bfcf3857dac449
Description:

btrfs-progs: update to 6.9

---

utils/prometheus-node-exporter-lua/Makefile
utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/nat_traffic.lua

Compile tested:  -
Run tested: `arm_cortex-a15_neon-vfpv4/ipq806x/generic/22.03.5 r20134-5f15225c1e`
Fixes duplicates samples for NAT gauge
Fixes #24166
_Disclaimer: this is my first time writing Lua._
I've patched my device manually and will monitor the behaviour during the next few hours.

prometheus-node-exporter-lua: remove duplicated nat samples

---

lang/lua-eco/Makefile

Maintainer: me
Description:
Release notes for 3.5.2: https://github.com/zhaojh329/lua-eco/releases/tag/v3.5.2

lua-eco: update to 3.5.2

---

utils/eza/Makefile

release notes:
0.18.16: https://github.com/eza-community/eza/releases/tag/v0.18.16
0.18.17: https://github.com/eza-community/eza/releases/tag/v0.18.17
0.18.18: https://github.com/eza-community/eza/releases/tag/v0.18.18
Maintainer: me
Run tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt snapshot

eza: update to 0.18.18

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

haproxy: update to v3.0.1

---

utils/prometheus-node-exporter-lua/Makefile
utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/mwan3.lua

Run tested:
- x86_64 on Docker r22073-f06bd5bdb8
- mvebu/cortexa9 on 19.07.9 r11405-2a3558b0de
Description:
Adds prometheus collector for mwan3

prometheus-node-exporter-lua: Add optional mwan3 collector

---

libs/libvpx/Makefile

This release includes enhancements and bug fixes.
This release is ABI compatible with the previous release.
See: https://github.com/webmproject/libvpx/releases/tag/v1.14.1
Maintainer: me
Description:

libvpx: update to 1.14.1

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

haproxy: update to v3.0.2

---

lang/ruby/Makefile
lang/ruby/ruby_find_pkgsdeps
lang/ruby/ruby_missingfiles

Ruby 3.3 adds a new parser named Prism, uses Lrama as a parser generator, adds a new pure-Ruby JIT compiler named RJIT, and many performance improvements especially YJIT.
See: https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
The 3.3.1 release includes security fixes.
- CVE-2024-27282: Arbitrary memory address read vulnerability with Regex search
- CVE-2024-27281: RCE vulnerability with .rdoc_options in RDoc
- CVE-2024-27280: Buffer overread vulnerability in StringIO
See: https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/
The 3.3.2 release includes many bug-fixes.
See: https://www.ruby-lang.org/en/news/2024/05/30/ruby-3-3-2-released/
Packaging changes since 3.2.2:
- New packages: ruby-prism and ruby-rjit
- Added /usr/bin/rdbg to ruby-debug
- Added …

ruby: update to 3.3.3

---

net/tailscale/Makefile

Description:
https://github.com/tailscale/tailscale/releases/tag/v1.68.0

tailscale: Update to 1.68.0

---

lang/ruby/Makefile

The 3.2.3 release includes many bug-fixes. This release also includes the update of uri.gem to 0.12.2 which contains the security fix.
- CVE-2023-36617: ReDoS vulnerability in URI
See: https://www.ruby-lang.org/en/news/2024/01/18/ruby-3-2-3-released/
The 3.2.4 release includes security fixes. Please check the topics below for details.
- CVE-2024-27282: Arbitrary memory address read vulnerability with Regex search
- CVE-2024-27281: RCE vulnerability with .rdoc_options in RDoc
- CVE-2024-27280: Buffer overread vulnerability in StringIO
See: https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-2-4-released/
Maintainer: me
Description:

[23.05] ruby: update to 3.2.4

---

libs/libfido2/Makefile

Maintainer: @linosgian 
Run tested: NA
Description: libfido2 is licensed under the BSD 2-clause license as per: https://github.com/Yubico/libfido2/
Update package Makefile to correctly reflect this.

libfido2: fix license info in Makefile

---

libs/libcbor/Makefile

Maintainer: @linosgian 
Run tested: NA
Description:
libcbor is licensed under the MIT license as per:
https://github.com/PJK/libcbor/tree/master#license
Update package Makefile to reflect the same

libcbor: fix license info in Makefile

---

net/knxd/Makefile
net/knxd/patches/0100-version.patch

Maintainer: me
Run tested: ath79, tp-link Archer C7 v4, trunk, compiled with knxd package
Description:
new upstream release 0.14.62

knxd: bump to new release 0.14.62

---

net/xray-core/Makefile

Description:
xray-core: Update to 1.8.15
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.13...v1.8.15

xray-core: update to 1.8.15

---

net/frr/Makefile

(refer to openwrt/openwrt#15690)
Due to changes in elfutils in order to
simplify the build for static libraries only,
the zlib functions that libelf depends on
are no longer linked within the static libelf library.
If frr were to use pkg-config, no change would be necessary,
however, the AC_CHECK_LIB macro is used, so add the link manually.
Compile tested: host build
Run tested: no

frr: link zlib in host build

---

net/dnslookup/Makefile

Description:
dnslookup: update to 1.11.0
For more information, visit https://github.com/ameshkov/dnslookup/compare/v1.10.1...v1.11.0

dnslookup: update to 1.11.0

---

net/yggdrasil/Makefile

Maintainer: @wfleurant
Compile tested: armv8
Run tested: uap-ac / fixes for big endian routers
Description:
- bumped version, on gear testing @neilalexander
- updated desc

yggdrasil: bump to 0.5.6

---

net/v2raya/Makefile

Description:
v2raya: update to 2.2.5.2
Fix: docker dev environment build.
Remove "is-text" in button style.
Add tun mode with sing-tun.
Publish docker images on Github Container Registry.
Ci: add separated singtun workflow.
Full Changelog: https://github.com/v2rayA/v2rayA/compare/v2.2.5.1...v2.2.5.5

v2raya: update to 2.2.5.5

---

net/curl/Makefile
net/curl/patches/010-mbedtls-v3.6.0-workarounds.patch

Maintainer: @krant
Compile tested: aarch64 531b3f667c40405581a398a9648a0e6c27909a87
Run tested: aarch64 531b3f667c40405581a398a9648a0e6c27909a87, just simple connection test
Description:
tlsv1.3 support is broken in curl 8.8.0 with mbedtls 3.6.0.  
See https://github.com/curl/curl/issues/13653 and https://github.com/Mbed-TLS/mbedtls/issues/9210 for more details.  
A workaround was implemented in upsteam codes, see https://github.com/curl/curl/commit/0c4b4c1e93c8e869af230090f32346fdfd548f21 and https://github.com/curl/curl/commit/5f9017d4e28096b4589c4d5ee4f18cae086ba777  
This commit includes patches generated from upstream commits.  
Fixes #24365 #24386

curl: upstream backports for mbedtls

---

net/tailscale/Makefile

<https://github.com/tailscale/tailscale/releases/v1.68.1>

tailscale: Update to 1.68.1

---

net/aardvark-dns/Makefile

Description:
changelogs:https://github.com/containers/aardvark-dns/compare/v1.10.0...v1.11.0

aardvark-dns: update to 1.11.0

---

admin/qbee-agent/Makefile
admin/qbee-agent/files/qbee-agent.init

Maintainer: @jonhenrik13
Compile tested: mipsel_24kc, x86_64, mips_24kc
Run tested: mipsel_24kc, x86_64, mips_24kc
Description:
qbee-agent is the fleet management agent from qbee.io released under Apache-2.0 license. It provides configuration management capabilities, inventory information, remote access, metrics and more. In version 2024.23 it also has support for the opkg package manager.

qbee-agent: new package qbee-agent 2024.23

---

net/natmap/Makefile

Maintainer: @ysc3839,@heiher
Description:
Fix the issue of not resetting PKG_RELEASE to 1 in https://github.com/openwrt/packages/pull/24318
Sorry for this oversight.

natmap: reset PKG_RELEASE to 1

---

net/xray-core/Makefile

Run tested: armv8, snapshot
Description:
xray-core: Update to 1.8.16
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.15...v1.8.16

xray-core: update to 1.8.16

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.27.2)

docker-compose: Update to version 2.27.2

---

net/dnsdist/Makefile
net/dnsdist/files/dnsdist.config
net/dnsdist/files/dnsdist.init

Maintainer: @Habbie @rgacogne
Run tested: x86_64, OpenWrt 23.05.2
These options allow running dnsdist as a non-root user.
Further notes/points for discussion:
* I noted that the dnsdist package creates a `dnsdist` user/group, which seems like a good candidate for the default of `uid` and `gid`. However, I left it at the current implicit default of `root`, since the change might break existing setups.
* The options might be more aptly named `user` and `group`, since dnsdist accepts names as well as IDs. But I decided to stick with the wording dnsdist uses for its parameters.

dnsdist: add config options for --uid and --gid

---

net/openvpn/Config-wolfssl.in
net/openvpn/Makefile
net/openvpn/patches/100-mbedtls-disable-runtime-version-check.patch
net/openvpn/patches/101-Fix-EVP_PKEY_CTX_-compilation-with-wolfSSL.patch

Compile tested: ramips/mt7621, ramips/mt7620, ramips/mt76x8
Run tested: Xiaomi Mi Router 3 Pro, Xiaomi Mi Router R3, Asus RT-AC1200
Description:
This is a bugfix release containing several security fixes.
Security fixes
--------------
- CVE-2024-4877: Windows: harden interactive service pipe. Security scope: a malicious process with "some" elevated privileges could open the pipe a second time, tricking openvn GUI into providing user credentials (tokens),  getting full access to the account openvpn-gui.exe runs as.
- CVE-2024-5594: control channel: refuse control channel messages with nonprintable characters in them. Security scope: a malicious openvpn peer can send garbage to openvpn log, or cause high CPU load.
- CVE-2024-28882: only call schedule_exit() …

openvpn: update to 2.6.11

---

libs/boost/Makefile

Compile tested: bcm27xx (bcm2712) and x86_64 - used development snapshot from the 27th of April. 
Description:
This commit updates boost to version 1.85.0
New available libraries:
* *Charconv:* A high quality implementation of \<charconv\> in C++11, from Matt Borland. [2]
* *Scope:* A collection of scope guard utilities and a unique_resource wrapper, from Andrey Semashev. [3]
More info about Boost 1.85.0 can be found at the usual place [1].
[1]: https://www.boost.org/users/history/version_1_85_0.html
[2]: https://www.boost.org/libs/charconv/
[3]: https://www.boost.org/libs/scope/

boost: Updates package to version 1.85.0

---

net/netatalk/Makefile
net/netatalk/files/afpd.init

Maintainer: @APCCV / Antonio Pastor
Commit restores package after it was removed from OpenWrt 21.02.
Compile tested: ipq806x - OpenWrt 23.05.3, r23809
- Compiled using SDK for 23.05.3.
Run tested: ipq806x - OpenWrt 23.05.3, r23809. Tests included:
- opkg install of package
- edit config file to create network shares
- connect to shares from MacOS (both vintage 10.13 and 14.4)
- stored, modify and delete files in share from Finder
- check and update file Information (properties) from Finder
- configured share to be used for TimeMachine backup
- create a backup (full backup - initial backup)
- create incremental backups
- enter Time Machine and browse backups
Description:
Netatalk package was removed in 2023 as it was stale and used old 3.1.13 version from 2018.
This commit uses the latest …

netatalk: update to 3.2.0

---

lang/node/Makefile
lang/node/patches/202-node_gyp.patch
lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch

Run tested: (qemu 9.0.1) aarch64
Description:
Update to v20.15.0
* test_runner: support test plans
* inspector: introduce the --inspect-wait flag
* zlib: expose zlib.crc32()
* cli: allow running wasm in limited vmem with --disable-wasm-trap-handler

node: bump to v20.15.0

---

libs/keyutils/Makefile

Maintainer: @dangowrt / @neheb
Compile tested: x86-generic OpenWRT 7ccd7dac7e
Run tested: as above
Description:
The kernel knows about /sbin/request-key *at that path*, and the shipped configuration file presumes that /sbin/key.dns_resolver and /bin/keyctl are the correct paths.

keyutils: Package into the right directories

---

net/kafs-client/Makefile
net/kafs-client/patches/res_query.patch

Maintainer: me / @nwf
Compile tested: x86/generic dcc4307205
Run tested: x86/generic dcc4307205
Description:
[kAFS](https://docs.kernel.org/filesystems/afs.html) is the Linux in-kernel implementation of the Andrew File System client / "cache manager".  [kafs-client](https://gitlab.com/linux-afs/kafs-client) is a small collection of user-space programs that support it, including:
- Loading lists of known AFS cells ("CellServDB")
- Providing dynamic cell and server discovery using DNS via `request-key`
- Feeding the kernel AFS authentication tokens derived from users' Kerberos tickets (`aklog-kafs`)
Please note:
- some functionality in this package is not expected to work correctly until #24421 lands.
- As per @robimarko's request on https://github.com/openwrt/openwrt/pull/15761, this …

kafs-client: introduce package

---

utils/docker/Makefile

Description:
docker: Update to 26.1.4
For more information, visit https://github.com/docker/cli/compare/v26.1.0...v26.1.4

docker: Update to 26.1.4

---

utils/containerd/Makefile

Description:
Update Go version to 1.21.11 (https://github.com/containerd/containerd/pull/10298)
Remove uses of alias (https://github.com/containerd/containerd/pull/10277platforms.Platform)
Migrate log imports to (https://github.com/containerd/containerd/pull/10269github.com/containerd/log)
Migrate errdefs package to (https://github.com/containerd/containerd/pull/10266github.com/containerd/errdefs)
Fix usage of "unknown" platform (https://github.com/containerd/containerd/pull/10261)
For more information, visit https://github.com/containerd/containerd/compare/v1.7.15...v1.7.18

containerd: Update to 1.7.18

---

utils/owut/Makefile

owut (OpenWrt Update Tool) is a command line program that gathers information from the various openwrt.org build sites and reports status on various aspects of builds and package availability. It also shows many details about your current configuration and installed packages, allowing it to create, download, verify and install new images containing the user-installed packages.
It is written completely in 'ucode', allowing for user customization on the installed device, without the need for compilers and linkers.
Documentation is available at https://github.com/efahl/owut 
Forum thread at https://forum.openwrt.org/t/owut-openwrt-upgrade-tool/200035
Maintainer: me @efahl
Compile tested: x86 generic SNAPSHOT
Run tested: x86 generic SNAPSHOT

owut: add new package

---

lang/lua-ffi/Makefile

Lua-ffi is a portable lightweight C FFI for Lua, based on libffi and aiming to be mostly compatible with LuaJIT FFI, but written from scratch in C language.
Maintainer: me
Compile tested: (x86, x86, master)
Run tested: (x86, x86, master, tests done)
Description:
https://github.com/zhaojh329/lua-ffi

lua-ffi: Add package

---

libs/libjwt/Makefile

Maintainer: me
Run tested: -
Description:
Add package for JWT C Library built against OpenSSL.

libjwt: add package

---

sound/shairport-sync/Makefile
sound/shairport-sync/files/shairport-sync.config
sound/shairport-sync/files/shairport-sync.init

Prelude:
- The original PR was closed by mistake (again) - this time I found bug in my rebase script: https://github.com/openwrt/packages/pull/23836 - This new PR supersedes it.
- The last comment on the previous PR is [here](https://github.com/openwrt/packages/pull/23836#issuecomment-2049006604)
Maintainer: @mikebrady
Compile tested: NanoPi R4s / SNAPSHOTS
Run tested: NanoPi R4s / SNAPSHOTS
Description:
shairport-sync expects statistics/log_verbosity/log_output_to settings
to be in the diagnostics section of shairport-sync's native config.
Prior to this commit, these settings were either missing (log_output_to)
or generated in the incorrect (general) native config section bloc.

shairport-sync: fixed diagnostics settings

---

net/mwan3/Makefile
net/mwan3/files/usr/sbin/mwan3

Maintainer:  @feckert
Compile tested: APU, 23.05.2
Run tested: APU, 23.05.2, execution of programs or shell builtins via `mwan3 use`
Previously the "use" command had the following shortcomings:
* a subprocess was created instead of replacing the shell process
* whitespace in arguments was not handled correctly
Implementation detail:
In shell context the `"$@"` expression should be used (instead of `$*`). This allows the safe handling of arguments containing whitespace.
Closes: #20001

mwan3: "use" action: run process via `exec` and handle whitespace

---

admin/zabbix/Makefile
admin/zabbix/patches/010-change-agentd-config.patch
admin/zabbix/patches/110-reproducible-builds.patch

Compile tested: ipq806x/wg2600hp3, ramips/wn-ax2033gr
Run tested: ipq806x/wg2600hp3, ramips/wn-ax2033gr
Description:
- Update to latest stable version.
- Fix agentd build error.

zabbix: update to 7.0.0

---

utils/dockerd/Makefile

Description:
dockerd: Update to 26.1.4
For more information, visit https://github.com/moby/moby/compare/v26.1.0...v26.1.4
Dependent on:
https://github.com/openwrt/packages/pull/24452

dockerd: Update to 26.1.4

---

net/knot/Makefile

Maintainer: @Payne-X6
Compile tested: rockchip/armv8, nanopi-r4s, be37ab6e51 snapshot build
Run tested: rockchip/armv8, nanopi-r4s, be37ab6e51 snapshot build, running on my main router
Description: EXTRA_DEPENDS now requires an `r` before the `PKG_RELEASE` because of
https://github.com/openwrt/openwrt/commit/e8725a932e16eaf6ec51add8c084d959cbe32ff2.
Fixes https://github.com/openwrt/packages/issues/23735

knot: fix EXTRA_DEPENDS release versions

---

net/tinc/Makefile
net/tinc/files/tinc.init

Maintainer: me
Run tested: mvebu/cortexa9/linksys_wrt1900acs   snapshot 
Description:
the variable NETNAME that is exported in tinc-up , was not set correctly

tinc: fix regression bring by commit fd61f2d

---

net/tinyproxy/Makefile
net/tinyproxy/files/tinyproxy.init

Run tested: Xiaomi Mi Router 3G, OpenWrt 22.03.5, r20134-5f15225c1e
Description:
Fixes generation of upstream record as reported in #19942

tinyproxy: fix upstream config generation

---

net/speedtest-netperf/Makefile
net/speedtest-netperf/files/README.md
net/speedtest-netperf/files/speedtest-netperf.sh

**Author/ Maintainer**: me
**Compile tested**: against `openwrt/master` for `malta/mips` (package is arch-independent) 
**Run tested**: EA6350v3 (ipq40xx/generic), PC (x86_64)
**Description**:
Support measuring ping latency and CPU details at idle as a baseline before measuring under data transfer loading. This allows better determination of Latency Under Load, a critical bufferbloat parameter. The CPU details can also be used to verify idle conditions or examine CPU frequency against ping variations and jitter.
Change the default test duration to 30 seconds, which is adequate for SQM tuning while reducing bandwidth consumption for upstream netperf servers.
Change the default ping host from gstatic.com to one.one.one.one, which is widely available and generally shows lower latency.
When …

speedtest-netperf: add idle latency measurement

---

net/modemmanager/Makefile
net/modemmanager/files/lib/netifd/proto/modemmanager.sh

This make source based IPv6 routing option available for modemmanager case dhcpv6
cc @feckert 
I post here without test. I am not really clear how the modemmanager work

modemmanager: add sourcefilter option support

---

net/net-snmp/Makefile

Description: 
Since IPv6 is present in everyday use, we need to include
information about IPv6 addresses & routes in SNMP
Example:
IP-MIB::ipAddressOrigin.ipv6
IP-MIB::ipAddressOrigin[ipv6]["00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01"] = manual
IP-MIB::ipAddressOrigin[ipv6]["fd:00:00:09:02:55:00:00:00:00:00:00:00:00:01:01"] = manual
IP-MIB::ipAddressOrigin[ipv6]["fe:80:00:00:00:00:00:00:0c:00:09:ff:fe:06:01:01"] = linklayer
IP-MIB::ipAddressOrigin[ipv6]["fe:80:00:00:00:00:00:00:0c:02:09:ff:fe:00:01:01"] = linklayer
IP-MIB::ipAddressOrigin[ipv6]["fe:80:00:00:00:00:00:00:ae:84:c6:ff:fe:25:8c:ce"] = linklayer
Tested:
23.05-snapshot
master snapshot
with LibreNMS, OpenWRT device IPv6 Addresses & Routes are properly recognized

net-snmp: include ipv6 address & route mibs

---

net/miniupnpd/Makefile

and change title to term used in LuCi
Maintainer:
Compile tested: not tested on OpenWrt
Run tested: not tested on OpenWrt

miniupnpd: Update package to 2.3.6

---

net/dnslookup/Makefile

Fixed unnecessary error when running with no arguments.
Run tested: armv8, snapshot
Description:
Fixed unnecessary error when running with no arguments: https://github.com/ameshkov/dnslookup/pull/72

dnslookup: Update to 1.11.1

---

utils/mhz/Makefile
utils/mhz/patches/0001-Makefile-allow-overriding-CC-and-CFLAGS.patch

Maintainer: @robimarko 
Run tested: mvebu, Turris Omnia, Turris OS 7 = OpenWrt 22.03, it compiles
Description:
The package repeatedly fails to compile with the errors mentioned in the commit message. On our newer branch, tracking OpenWrt 23.05, the build does not fail. Backporting this patch fixed the problem on the current branch, tracking OpenWrt 22.03.

[22.03] mhz: backport build fix

---

net/strongswan/Makefile
net/strongswan/files/swanctl.init

Run tested: mvebu, Turris Omnia, Turris OS 7 = OpenWrt 22.03, it runs
Description:
User complained about the error caused by non-existing reference to swanctl_append4. I was able to reproduce it and after noticing the second fix I reproduced also managed to reproduce it. After applying the fixes from 23.05 everything worked. 
Reference to our forum:
- https://forum.turris.cz/t/turris-os-7-0-is-in-rc/19755/20

[22.03] strongswan: backport fixes from 23.05

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.28.1)

docker-compose: Update to version 2.28.1

---

libs/libjwt/Makefile

Maintainer: me
Compile tested: x86_64, mips_24kc
Description:
Add package for JWT C Library built against OpenSSL.
(cherry picked from commit 57fdc5d2b98e6bdd96f8f0f6f0448579bc3ddbad)
This package is needed to update asterisk in telephony feed to version 20.8.1 which no longer comes with a built-in JWT implementation.

[23.05] libjwt: add package

---

net/aardvark-dns/Makefile

Description:
changelogs:https://github.com/containers/aardvark-dns/compare/v1.9.0...v1.11.0

[23.05]aardvark-dns: update to 1.11.0

---

net/freeradius3/Makefile

Maintainer:
Run tested:
Description:
freeradius-3.2.4 had a build failure in the snapshoot release but it builds successfully when doing a pull request
https://downloads.openwrt.org/snapshots/faillogs/aarch64_generic/packages/freeradius3/compile.txt
https://github.com/openwrt/packages/pull/24417
as a solution we need to add
```
PKG_BUILD_PARALLEL:=0
```
to prevent freeradius3 from doing the build in parallel

freeradius3: add PKG_BUILD_PARALLEL:=0

---

utils/fx/Makefile

Maintainer: @dynasticorpheus 
Compile tested: Ubuntu 23.04 x64 / OpenWrt SNAPSHOT @ https://github.com/openwrt/packages/commit/36b1dd75fd9da1ea13f1ce1ee679c6b3c9c402cc
Description: Update to [35.0.0](https://github.com/antonmedv/fx/compare/34.0.0...35.0.0)

fx: update to 35.0.0

---

utils/docker/Makefile
utils/dockerd/Makefile
utils/runc/Makefile

Description:
runc: Update to 1.1.13
This is the thirteenth patch release in the 1.1.z release branch of runc. It
brings in Go 1.22.x compatibility and fixes a few issues, including an
occasional wrong nofile rlimit in runc exec, and a race between runc list and
runc delete.
For more information, visit https://github.com/opencontainers/runc/releases/tag/v1.1.13
docker: Update to 27.0.2
For more information, visit https://github.com/docker/cli/compare/v26.1.4...v27.0.2
dockerd: Update to 27.0.2
For more information, visit https://github.com/moby/moby/compare/v26.1.4...v27.0.2

docker: Update to 27.0.2

---

net/dnsproxy/Makefile

Description:
dnsproxy: Update to 0.71.2
For more information, visit https://github.com/AdguardTeam/dnsproxy/compare/v0.71.1...v0.71.2

dnsproxy: Update to 0.71.2

---

utils/hwinfo/Makefile

util-linux uuid is used now.
Maintainer: @bobafetthotmail

hwinfo: remove uuid hacks

---

utils/lxc/Makefile
utils/lxc/patches/020-lxc-checkconfig.patch
utils/lxc/patches/025-remove-unsupported-option.patch

Changelog: https://discuss.linuxcontainers.org/t/lxc-6-0-lts-has-been-released/19567
Required libdbus as a depends for liblxc.  I verified that both lxc-create and lxc-checkconfig work with the rebases to the following patches but do please review:
- 020-lxc-checkconfig.patch
- 025-remove-unsupported-option.patch

lxc: update to 6.0.1

---

libs/unixodbc/Makefile
libs/unixodbc/patches/010-gcc14.patch

Wrong pointer type. This time found on 64-bit.

unixobdc: fix compilation with GCC14 again

---

net/apinger/Makefile
net/apinger/patches/050-statusformat.patch

Needs to be 64-bit.
Maintainer: @samm-git

apinger: fix time_t format

---

libs/p11-kit/Makefile
libs/p11-kit/patches/010-format.patch

Upstream backport fixing 32-bit -Wformat warning.

p11-kit: update to 0.25.3

---

utils/lpac/Makefile

Compile tested: qualcommax/ipq60xx, main
Run tested: qualcommax/ipq60xx, main
Description:
Update the LPAC tool to version 2.0.2 which contains several fixes.
The new QMI over QRTR driver is left disabled by default now.
Release notes:
https://github.com/estkme-group/lpac/releases/tag/v2.0.2

lpac: update to 2.0.2

---

libs/glib2/Makefile
libs/glib2/patches/003-valgrind.h-mips16-fix.patch
libs/glib2/patches/006-c99.patch
libs/glib2/patches/010-pcre.patch
libs/glib2/patches/021-Remove-packaging-module-dependency.patch

Compile tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2
Run tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2, tested with internal software
Description: update package to version 2.80.3
- Explicitly disable gobject introspection option
- Set runtime_dir to `/var/run` as current glib2 version sets this option to `/run` by default (see this [commit](https://gitlab.gnome.org/GNOME/glib/-/commit/30995f9dd7c24314c362a3e30102b89196bcef84))
-  Add a patch that removes the Python packaging module dependency

libs/glib2: update to 2.80.3

---

net/openssh/Makefile

Release notes: https://www.openssh.com/txt/release-9.8
* 9.8p1 fixes CVE-2024-6387
* Adjusted Makefile to provide `/usr/lib/sshd-session`
* Given the troubles with -fzero-call-used-regs and all the broken checks, makes sense to skip it
Maintainer: @SibrenVasse, @tripolar

openssh: bump to 9.8p1

---

net/miniupnpc/Makefile
net/miniupnpc/patches/100-no-fPIC.patch

Maintainer: n/a
Compile tested: sunxi/cortexa53
Description:
Updated binary path, rebased patches.

miniupnpc: Update to 2.2.8

---

utils/lpac/Config.in
utils/lpac/Makefile

Compile tested: qualcommax/ipq60xx, main
Run tested: qualcommax/ipq60xx, main
Description:
Currently, lpac will be built with the PCSC and AT APDU backends by default and its not configurable in OpenWrt.
Since smart card reads are not really common on OpenWrt devices lets disable PCSC backend by default so we dont have to include PCSC lib and daemon by default.
AT backend is left enabled by default since it has no external dependecies and all modems have it.
QMI over QRTR backend is not selectable even though it is part of the 2.0.2 relase since it requires unstable libqmi 1.35.4 or newer and we are still using 1.34 stable branch.

lpac: make APDU backends configurable

---

utils/i2csfp/Makefile

Maintainer: me
Run tested: ongoing
Description:
Add i2csfp utility which comes handy when dealing with some SFP modules.

i2csfp: add package

---

lang/rust/rust-values.mk

Compile tested: armv5te, kirkwood, latest snapshot
Run tested: armv5te, kirkwood, latest snapshot, rust program run test
Description:
Currently, armv5 and armv6 targets are both using armv6 rustc. Without this patch, rust programs in armv5 targets throw illegal instruction error.
This pull request depends on https://github.com/openwrt/openwrt/pull/15855

rust: select correct architecture for armv5

---

utils/lpac/Makefile

Compile tested: qualcommax/ipq60xx, main
Run tested: qualcommax/ipq60xx, main
Description:
Turns out that having a comment for QMI over QRTR in the CMAKE_OPTIONS will drop anything after it, so lets move the comment above CMAKE_OPTIONS.
Fixes: 34f9d96b4cc3 ("lpac: make APDU backends configurable")

utils: lpac: fix passing CMAKE options

---

net/openvpn/Makefile
net/openvpn/files/openvpn.init

_Maintainer:_  @neheb @BKPepe
_Run tested:_ OpenWRT x86-64 snapshot with custom .ovpn config and `script-security 0` setting, see below.
_Description:_
External scripts may only be specified for OpenVPN with `script-security 2` or higher, otherwise OpenVPN fails at tunnel startup with an error.
In some circumstances where the remote OpenVPN server is not fully trusted, setting `script-security` to `0` or `1` might still be a good practice and should be allowed. This changes the previously hardcoded hotplug scripts to only be added if `script-security 2` or higher is used.
logread from a current OpenWRT x86-64 snapshot failing on a custom config with `script-security 0`:
```
Tue Jul  2 20:25:54 2024 daemon.notice openvpn(custom_config)[4720]: TUN/TAP device tap0 opened
Tue Jul  2 20:25:54 …
```

openvpn: fix startup with script-security lower than 2

---

net/tailscale/Makefile

Description:
tailscale: Update to 1.68.2
Fixed: [Tailnet lock](https://tailscale.com/kb/1226/tailnet-lock) validation of rotation signatures now permits multiple nodes signed by the same pre-signed reusable auth key.
For more information, visit https://github.com/tailscale/tailscale/compare/v1.68.1...v1.68.2

tailscale: Update to 1.68.2

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r26730-17099f2760 |
- Changelog:
- [v0.28.3](https://github.com/netbirdio/netbird/releases/tag/v0.28.3)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.27.10...v0.28.3 …

netbird: update to 0.28.3

---

utils/eza/Makefile

Maintainer: me
Compile tested: x86-64, APU board, OpenWrt snapshot
Run tested: x86-64, APU board, OpenWrt snapshot
Release notes:
0.18.19: https://github.com/eza-community/eza/releases/tag/v0.18.19
0.18.20: https://github.com/eza-community/eza/releases/tag/v0.18.20
0.18.21: https://github.com/eza-community/eza/releases/tag/v0.18.21

eza: update to 0.18.21

---

net/openssh/Makefile
net/openssh/patches/100-fix-incompatible-ptr-GCC-14.1.patch

The `ssh_systemd_notify` function is causing compilation errors when built against GCC 14.1. This is due to an incompatible pointer type being passed to the `connect` function.
`connect` function expects a pointer to `struct sockaddr`, but was receiving a pointer to `struct sockaddr_un`.
Maintainer: Peter Wagner <tripolar@gmx.at>
Related issue: https://github.com/openwrt/packages/issues/24514

openssh: fix incompatible ptr type error GCC 14.1

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r26844-37636a8752 |
- Changelog:
- [v0.28.4](https://github.com/netbirdio/netbird/releases/tag/v0.28.4)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.28.3...v0.28.4
Compiled …

netbird: update to 0.28.4

---

multimedia/motion/Makefile

With ffmpeg support, motion can encode videos and process network camera streams. It is a small code base and buinding it twice will not significantly impact a full build.
Maintainer: @neheb @roger-
Compile tested: 23.05 and trunk
Run tested: 23.05 monitoring both a local and a remote camera

motion: add non/ffmpeg variants

---

utils/pcsc-lite/Makefile

Compile tested: HEAD (e74ead224), mips64-octeon
Run tested: As above.  OpenVPN using pkcs11-helper doesn't work without, does with file installed.
Description:
74ee2fa4899 failed to notice that libpcsclite now supports redirection, as of https://salsa.debian.org/rousseau/PCSC/-/commit/1faab672aa1f926cf943d8b814ae15636dddd22c (first present in upstream release 2.1.0).  It's important to include the real implementation, even if redirection permits loading others.

pcsc-lite: install libpcsclite_real.{a,so*}, too

---

utils/lolcat/Makefile

No changelog, but only a single commit since last version, fixing uncoloured stderr interleaved with coloured stdout.
Maintainer: me
Run tested: octeon

lolcat: bump to 1.5

---

net/banip/files/README.md

Maintainer: @dibdot
Description:
Mb (Megabits) changed to MB (Megabytes).

banip: Correct Mb to MB when referring to RAM in README.md

---

lang/luasocket/Makefile

Compile tested: ath79/generic OpenWRT 23.05.3
Run tested: ath79/generic OpenWRT 23.05.3
Description: Includes the serial module for luasockets (which is already being built) in the final package.  This allows using socket.select() on a serial port (eg /dev/ttyACM0) which is the easiest way to use a serial-port with coroutines.  For instance copas can now be used via:
```
local copas = require("copas")
local serial = require("socket.serial")
copas.addthread(function()
tty = copas.wrap(serial("/dev/ttyACM0"))
l, e = tty:receivepartial()
while not e do
print(">" .. l)
l, e = tty:receivepartial()
end
end)
copas()
```

Enable serial moduls for luasockets

---

net/dnsproxy/Makefile

Description:
dnsproxy: Update to 0.72.0
For more information, visit https://github.com/AdguardTeam/dnsproxy/compare/v0.71.2...v0.72.0

dnsproxy: Update to 0.72.0

---

lang/node/Makefile

Compile tested: 23.05, aarch64, arm
Run tested: (qemu 9.0.1) aarch64
Description:
CVE-2024-36138 - Bypass incomplete fix of CVE-2024-27980 (High)
CVE-2024-22020 - Bypass network import restriction via data URL (Medium)

[23.05] node: July 8, 2024 Security Releases

---

lang/lua-cjson/Makefile

Current domain (kyne.com.au) has expired, so the current `PKG_SOURCE_URL` is non-existent.
See https://github.com/mpx/lua-cjson/commit/718f27293a981fb5e9e662e9aec0b7cf78317da6b
Signed-off-by: bretello <bretello@distruzione.org>

lua-cjson: fix broken PKG_SOURCE_URL

---

lang/luajit2/Makefile

luajit2: update to v2.1-20240626

---

utils/kitty-terminfo/Makefile

Maintainer: @moetayuko 
Compile tested: qualcommax/ipq807x, Dynalink WRX-36
Run tested: qualcommax/ipq807x, Dynalink WRX-36
Description:
Update kitty-terminfo to the current kitty release of 0.35.2.

kitty-terminfo: update to 0.35.2

---

net/modemmanager/Makefile
net/modemmanager/files/usr/libexec/rpcd/modemmanager

Maintainer: me @mips171 @aleksander0m 
Run tested: x86_64, APU3, OpenWrt latest, tests done)
Description:
The 'modemmanager' uses the 'dbus'. Status information can be retrieved with the 'mmcli' command, this can also be output in json format.
This commit adds a new 'ubus' backend with which this information can be easily accessed via ubus.
```
root@G3-10940 ~ # ubus call modemmanager info
{
"modem": [
{
"imsi": "262029915879434",
"operator": "Vodafone.de",
"technology": "lte",
"device": "Modem1",
"iccid": "89492099166029838939",
"imei": "861107037891430",
"signal": "47"
}
]
}
```
```
root@G3-10940 ~ # ubus call modemmanager dump
{
"modem": [
{
"cdma": {
"evdo-registration-state": "--",
"cdma1x-registration-state": "--",
"activation-state": …
```

modemmanager: add missing ubus status backend via mmcli

---

net/v2raya/Makefile

Description:
chore(deps): bump golang.org/x/net from 0.18.0 to 0.23.0 in /service
For more information, visit https://github.com/v2rayA/v2rayA/compare/v2.2.5.5...v2.2.5.6

v2raya: update to 2.2.5.6

---

net/v2raya/Makefile

Description:
v2raya: update to 2.2.5.5(cherry picked from commit https://github.com/openwrt/packages/commit/edb50c24fc61a14664017981c8ba0b4096d96c0a)
v2raya: update to 2.2.5.6(cherry picked from commit https://github.com/openwrt/packages/commit/5a05a3a2b9c1343c585fbbd291a91807104257d4)
For more information, visit https://github.com/v2rayA/v2rayA/compare/v2.2.5.1...v2.2.5.6

[23.05]v2raya: update to 2.2.5.6

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

haproxy: update to v3.0.3

---

libs/xr_usb_serial_common/Makefile
libs/xr_usb_serial_common/patches/0001-fix-kernel-6.6-builds.patch

Format needs to be %zd, not %ld for size_t.
ping @aduskett @john-tho

xr_usb_serial_common: fix 32-bit compilation

---

net/xray-core/Makefile

Description:
xray-core: Update to 1.8.17
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.16...v1.8.17

xray-core: update to 1.8.17

---

lang/php8/Makefile

Maintainer: me
Compile tested: mxs, bcm27xx
Run tested: bcm27xx (Raspi)
Description:
https://www.php.net/ChangeLog-8.php#8.3.9

php8: update to 8.3.9

---

net/dnsproxy/Makefile

Description:
dnsproxy: Update to 0.67.0(The last version supported by [go 1.21](https://github.com/AdguardTeam/dnsproxy/blob/v0.67.0/go.mod))
For more information, visit https://github.com/AdguardTeam/dnsproxy/compare/v0.66.0...v0.67.0

[23.05]dnsproxy: Update to 0.67.0

---

net/xray-core/Makefile

Description:
xray-core: Update to 1.8.17(cherry picked from commit https://github.com/openwrt/packages/commit/48ea7d33e169dee3513d4b3f22203b0b78df304c)
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.16...v1.8.17

[23.05]xray-core: update to 1.8.17

---

net/krb5/Makefile

Fixes the following CVEs when compared to the last-packaged version, 1.20.1:
CVE-2024-37370
CVE-2024-37371
CVE-2023-36054
Maintainer: me

krb5: update to 1.21.3

---

utils/tree/Makefile

Changelog: version 2.1.3 (07/09/2024)
- Mostly a brown-paper bag release to fix the below regression and add a feature I forgot to add.
- Fix regression in search() function that broke --fromfile (Florian Ernst) (caused by removing too much code while fixing premature sort for --fromfile)
- Allow the -L option to accept its parameter immediately (with no space) instead of requiring it be the next option word. (Trevor Gross)

tree: bump to 2.1.3

---

utils/pcsc-lite/Makefile
utils/pcsc-lite/patches/010-format.patch

Fixes compilation with -Werror=format

pcsc-lite: fix bad formats

---

libs/libupnp/Makefile
libs/libupnp/patches/010-format.patch

libupnp: backport -Wformat fix

---

lang/perl-cgi/Makefile

Maintainer: me, @Naoir 
Compile tested: x86_64, generic, HEAD (5bf463bd9)
Description:

perl-cgi: Update to 4.66

---

net/xray-core/Makefile

Description:
Fixed Log_X_Inner functions, which had incorrect log severity.
Minimum required Golang version  downgraded to 1.21.4
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.17...v1.8.18

xray-core: update to 1.8.18

---

net/v2raya/Makefile

Description:
ci: Fix up Docker images' tag from version number
chore(deps): bump github.com/gin-contrib/cors from 1.3.1 to 1.6.0
For more information, visit https://github.com/v2rayA/v2rayA/compare/v2.2.5.6...v2.2.5.7

v2raya: update to 2.2.5.7

---

net/v2raya/Makefile

Description:
v2raya: update to 2.2.5.7(cherry picked from commit https://github.com/openwrt/packages/commit/ccccd5c92df2b4f80a9e5c43d1e96edf0a6b7e6a)
For more information, visit https://github.com/v2rayA/v2rayA/compare/v2.2.5.6...v2.2.5.7

[23.05]v2raya: update to 2.2.5.7

---

lang/php8/Makefile

Maintainer: me
Description:
https://www.php.net/ChangeLog-8.php#8.2.21

[23.05] php8: update to 8.2.21

---

net/bind/Makefile

Fixes: https://gitlab.isc.org/isc-projects/bind9/-/issues/4586
Compile tested: x86_64, generic HEAD (7bffb3f72b)
Description:
cc: @nmeyerhans @kempniu @oerdnj

bind: bump to 9.18.27

---

net/xray-core/Makefile

Description:
Fix WS reading X-Forwarded-For & Add tests
Fix SplitHTTP race condition when creating new sessions
SplitHTTP: Client supports HTTP/3
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.18...v1.8.19

xray-core: update to 1.8.19

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.29.0)

docker-compose: Update to version 2.29.0

---

net/xray-core/Makefile

Description:
xray-core: update to 1.8.19(cherry picked from commit https://github.com/openwrt/packages/commit/b85b8e869df6a79757d09401911d1000ffea6544)
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.18...v1.8.19

[23.05]xray-core: update to 1.8.19

---

utils/stress-ng/Makefile

Maintainer: me
Compile tested: x86  https://github.com/openwrt/openwrt/commit/d92c42f46990db232c163e20a05c7443d9efd2e1
Run tested:  x86  https://github.com/openwrt/openwrt/commit/d92c42f46990db232c163e20a05c7443d9efd2e1

stress-ng: bump to version 0.18.01

---

net/dnsproxy/Makefile

Description:
Fix race conditions on message ID in DNS-over-HTTPS and DNS-over-QUIC upstream implementations.
For more information, visit https://github.com/AdguardTeam/dnsproxy/compare/v0.72.0...v0.72.1

dnsproxy: Update to 0.72.1

---

net/xray-core/Makefile

Description:
SplitHTTP: Server supports HTTP/3
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.19...v1.8.20

xray-core: update to 1.8.20

---

net/xray-core/Makefile

Description:
xray-core: update to 1.8.20(cherry picked from commit https://github.com/openwrt/packages/commit/c4a706898238b01b0bcfce40710562b382395f5b)
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.19...v1.8.20

[23.05]xray-core: update to 1.8.20

---

net/tailscale/Makefile

Description:
New: Restrict [recommended](https://tailscale.com/kb/1392/auto-exit-nodes) and automatically selected exit nodes using the new AllowedSuggestedExitNodes [system policy](https://tailscale.com/kb/1315/mdm-keys). Applies only to platforms that support [system policies](https://tailscale.com/kb/1315/mdm-keys).
Changed: Improved [NAT traversal](https://tailscale.com/blog/how-nat-traversal-works) for some uncommon scenarios.
Changed: Optimized [sending firewall rules to clients](https://tailscale.com/kb/1018/acls) more efficiently.
Fixed: [Exit node suggestion](https://tailscale.com/kb/1392/auto-exit-nodes) CLI command now prints the hostname (which you can use with the [tailscale …

tailscale: Update to 1.70.0

---

devel/automake/Makefile

Maintainer: @xypron
Description:
automake: update to 1.16.5(cherry picked from commit https://github.com/openwrt/packages/commit/2bcd9a4cd7d8d5fd2c2a25fb18f5e0ec605c335c)

[23.05]automake: update to 1.16.5

---

devel/autoconf/Makefile

Maintainer: @xypron
Description:
autoconf: update to 2.72(cherry picked from commit https://github.com/openwrt/packages/commit/90d316b4286986192fc38bd064e138c336d8960c)

[23.05]autoconf: update to 2.72

---

devel/make/Makefile

Maintainer: @xypron
Description:
make: update to 4.4.1(cherry picked from commit https://github.com/openwrt/packages/commit/532f6e078291d25eb2a17f7de01a69edbe1c090e)

[23.05]make: update to 4.4.1

---

net/openvpn/Makefile

Compile tested: ramips/mt7621, ramips/mt7620,  ramips/mt76x8
Run tested: Xiaomi Mi router 3 pro, Xiaomi Mi router R3, TP-Link MR-3020 v3
Buugfix release. Bug fixes:
- the fix for CVE-2024-5594 (refuse control channel messages with nonprintable characters) was too strict, breaking user configurations with AUTH_FAIL messages having trailing CR/NL characters. This often happens if the AUTH_FAIL reason is set by a script.
- Http-proxy: fix bug preventing proxy credentials caching
For details refer to https://github.com/OpenVPN/openvpn/blob/v2.6.12/Changes.rst

openvpn: update to 2.6.12

---

sound/mpd/Makefile
sound/mpd/patches/040-lib-fmt-support-build-with-libfmt-11.0.0.patch

mpd fails to compile with libfmt v11 because of minor API changes in the library.
https://github.com/MusicPlayerDaemon/MPD/issues/2068
Compile tested: ARMv7 Processor rev 4 (v7l)
Run tested: ARMv7 Processor rev 4 (v7l)

mpd: fix build with libfmt v11

---

net/xray-core/Makefile

Description:
SplitHTTP: Remove unnecessary keepalives
Fix serverside TLS support of SplitHTTP H1/H2
Fix SplitHTTP H3 didn't always reuse QUIC connection
Fix SplitHTTP H3 waited for downResponse before uploading
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.20...v1.8.21

xray-core: update to 1.8.21

---

net/knot/Makefile
net/knot/patches/01_zscanner_tests.patch

Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 	8.0.0 (hbd)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 	8.0.0 (hbd)
Description:
- Release upgrade (https://www.knot-dns.cz/2024-07-22-version-338.html)

knot: update to version 3.3.8

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.29.1)

docker-compose: Update to version 2.29.1

---

utils/containerd/Makefile
utils/docker/Makefile
utils/dockerd/Makefile

Description:
**containerd: Update to 1.7.20**
Fix support for OTLP config
Add API go module
Remove overlayfs volatile option on temp mounts
Update runc binary to v1.1.13
Migrate platforms package to github.com/containerd/platforms
Migrate reference/docker package to github.com/distribution/reference
Fix panic in NRI from nil CRI reference
Support for dropping inheritable capabilities
Make PodSandboxStatus friendlier to shim crashes
Handle empty DNSConfig differently than unspecified
Fix for [cri] ttrpc: closed during ListPodSandboxStats
_For more information, visit https://github.com/containerd/containerd/compare/v1.7.18...v1.7.20_
**docker: Update to 27.1.0**
_For more information, visit …

docker: Update to 27.1.0

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r26990-06b37a5856<br/> ~OpenWrt SNAPSHOT r26969-715634e6d1~ |
- Changelog:
- [v0.28.6](https://github.com/netbirdio/netbird/releases/tag/v0.28.6)
- [v0.28.5](https://github.com/netbirdio/netbird/releases/tag/v0.28.5) …

netbird: update to 0.28.6

---

net/xray-core/Makefile

Description:
xray-core: update to 1.8.21(cherry picked from commit https://github.com/openwrt/packages/commit/ebeeafb99630ea54bd9a14ab0484f213218028aa)
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.20...v1.8.21

[23.05]xray-core: update to 1.8.21

---

libs/c-ares/Makefile

Description:
- Use up-to-date source URL

c-ares: update to 1.32.3

---

utils/docker/Makefile
utils/dockerd/Makefile

Description:
**docker: Update to 27.1.1**
_For more information, visit https://github.com/docker/cli/compare/v27.1.0...v27.1.1_
**dockerd: Update to 27.1.1**
This release contains a fix for [CVE-2024-41110](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-41110) / [GHSA-v23v-6jw2-98fq](https://github.com/moby/moby/security/advisories/GHSA-v23v-6jw2-98fq)
that impacted setups using [authorization plugins (AuthZ)](https://docs.docker.com/engine/extend/plugins_authorization/)
for access control. No other changes are included in this release, and this
release is otherwise identical for users not using AuthZ plugins.
_For more information, visit https://github.com/moby/moby/compare/v27.1.0...v27.1.1_

docker: Update to 27.1.1

---

lang/ruby/Makefile

Ruby 3.3.4 fixes a regression in Ruby 3.3.3 that dependencies are missing in the gemspec of some bundled gems: net-pop, net-ftp, net-imap, and prime. The fix allows Bundler to successfully install those gems on platforms like Heroku. If your bundle install runs correctly now, you may not have this issue. Other changes are mostly minor bug fixes.
See: https://www.ruby-lang.org/en/news/2024/07/09/ruby-3-3-4-released/
Maintainer: me
Compile tested: current main in x86/64
Run tested: current main in x86/64 checking dependencies

ruby: update to 3.3.4

---

admin/rsyslog/Makefile

rsyslog: update to 8.2406.0

---

net/strongswan/Makefile
net/strongswan/files/ipsec.init

Maintainer: Stephen Baker / @prmam
Run tested: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, QEMU Standard PC (Q35 + ICH9, 2009), OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-24.086.45142-09d5a38
Description:
Translate local_subnet and remote_subnet in /etc/config/ipsec into a comma separated list for leftsubnet and rightsubnet in /var/ipsec/ipsec.conf
Resolves #24435

strongswan: comma separated list for {left,right}subnet

---

net/xray-core/Makefile

Description:
SplitHTTP: Rename three options & Reduce server defaults
SplitHTTP: Fix wrong config deserialization
Docker: Add multi-arch builds and Loyalsoldier flavor
CertificateObject: Enable auto-reload for cacert & Add buildChain & Fixes
Fix a nil pointer in Wireguard client logging
SplitHTTP server: Add noSSEHeader
SplitHTTP: More range options, change defaults, enforce maxUploadSize, fix querystring behavior
SplitHTTP client: Add minUploadInterval
WS, HU: Remove unnecessary sleep from test
SplitHTTP server: Fix panic during concurrent Close and Push
Freedom: Don't do raw/splice copy in case of MITM
Fix SplitHTTP Unix domain socket
For more information, visit …

xray-core: update to 1.8.23

---

net/xray-core/Makefile

Description:
xray-core: update to 1.8.23(cherry picked from commit https://github.com/openwrt/packages/commit/b82deed3de4b3fbb7fa337543988ce8d70e567cc)
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.21...v1.8.23

[23.05]xray-core: update to 1.8.23

---

utils/containerd/Makefile
utils/docker/Makefile
utils/dockerd/Makefile

Description:
docker: Update to 27.1.0(cherry picked from commit https://github.com/openwrt/packages/commit/c8d63383add0ec11e53f4f05d15ece6118b1cf41)
dockerd: Update to 27.1.0(cherry picked from commit https://github.com/openwrt/packages/commit/79fac95444e4874a411c1a135ad01b12a8e36007)
containerd: Update to 1.7.20(cherry picked from commit https://github.com/openwrt/packages/commit/79fac95444e4874a411c1a135ad01b12a8e36007)
docker: Update to 27.1.1(cherry picked from commit https://github.com/openwrt/packages/commit/a14185ce28d2b37722b6fe5930ea2b430a4e0494)
dockerd: Update to 27.1.1(cherry picked from commit https://github.com/openwrt/packages/commit/84f20279113d05284de92bc246a1cf9149108ed9)
For more …

[23.05]docker: Update to 27.1.1

---

utils/swig/Makefile

Maintainer: @blogic @nxhack 
Compile tested: arm_cortex-a9_neon, GCC 14 - python-selinux builds all right
Description:
- Switch package URL to HTTPS

swig: update to 4.2.1

---

net/gping/Makefile

Maintainer: me
Compile tested: aarch64 mediatek/filogic (BananaPi R3 Mini), OpenWrt snapshot
Run tested: aarch64 mediatek/filogic (BananaPi R3 Mini), OpenWrt snapshot
Description:
no release notes or diff provided by upstream repository

gping: update to 1.17.3

---

net/dnsproxy/Makefile

Description:
Fixed: General memory performance improvements.
For more information, visit https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.72.2

dnsproxy: Update to 0.72.2

---

utils/xz/Makefile
utils/xz/patches/010-libtool.patch

Compile tested: mips64_octeonplus_64_musl
Fixes https://github.com/openwrt/packages/issues/24699

xz: add patch from upstream to fix mips64/octeon build

---

lang/ruby/Makefile

Ruby 3.2.5 includes many bug-fixes and a security fix in bundled gem rexml.
- CVE-2024-39908: DoS in REXML.
See: https://www.ruby-lang.org/en/news/2024/07/26/ruby-3-2-5-released/
Maintainer: me
Compile tested: x85_64

[23.05] ruby: update to 3.2.5

---

lang/lua-eco/Makefile

Maintainer: me
Description:
Release notes for 3.5.3: https://github.com/zhaojh329/lua-eco/releases/tag/v3.5.3

lua-eco: update to 3.5.3

---

utils/mariadb/Makefile
utils/mariadb/patches/120-fmt10.patch

Maintainer: @miska 
Fixes: https://github.com/openwrt/packages/issues/24721

mariadb: fix compilation with fmt 10.2

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27065-ca4469045f |
- Changelog:
- [v0.28.7](https://github.com/netbirdio/netbird/releases/tag/v0.28.7)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.28.6...v0.28.7
Compiled …

netbird: update to 0.28.7

---

multimedia/mjpg-streamer/Makefile
multimedia/mjpg-streamer/files/mjpg-streamer.init

[ "$enabled" ] returns true whatever non-empty value enabled has, including 0.
Maintainer: @thess @roger- 
Compile tested: main
Run tested: 23.05 manually copying the fixed file
Description:
23.05 also needs this fix

mjpg-streamer: fix option enabled check in init.d

---

net/libcurl-gnutls/Makefile

libcurl-gnutls: update to 8.9.1

---

utils/exfatprogs/Makefile

Description:
- Use proper tarball instead of codeload
- Remove autoreconf - provided configure works all right

exfatprogs: update to 1.2.4

---

net/net-snmp/Makefile
net/net-snmp/files/snmpd.init

Compile tested: x86_64, OpenWrt = 23.05
Run tested: x86_64, OpenWrt = 23.05
Description:
This commit writes the option `hostname` obtained via `uci_get system.@system[0].hostname`  to the `snmpd.conf` file if  `sysName` is not defined in `/etc/config/snmpd`.

net-snmp: set hostname as sysname

---

utils/gawk/Makefile

This makes it possible to build without busybox awk.
Compile tested: OpenWrt master, mips64 octeon
Run tested: OpenWrt master, mips64 octeon
Description:
I had an issue when compiling without BusyBox awk and having gawk, where some scripts in an integration for ModemManager used `awk` and not depending on it. Fair enough, but as `gawk` is an implementation of `awk` we should probably install it as `/usr/bin/awk` like many other tools do.

gawk: set gawk as an alternative to awk

---

net/wgsd/Makefile

Maintainer: @vooon
Description:
wgsd is written in Go, add $(GO_ARCH_DEPENDS) to dependencies to avoid building on unsupported architectures.

wgsd: add missing dependency

---

net/bind/Makefile

Compile tested: x86_64, generic, HEAD (274b18d105)
Run tested: same, running on production router
Description:
cc: @BKPepe @kempniu @oerdnj

bind: bump to 9.20.0

---

net/clamav/Makefile

Maintainer: @lucize @ratkaj 
Description:
clamav needs rust toolchain to build, add $(RUST_ARCH_DEPENDS) to dependencies to avoid building on unsupported architectures.

clamav: add missing dependency

---

net/dnsproxy/Makefile

Description:
Changed: Updated [golibs](https://github.com/AdguardTeam/golibs) dependency.
For more information, visit https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.72.3

dnsproxy: Update to 0.72.3

---

net/cloudflared/Makefile

Description:
cloudflared: update to 2024.8.12
For more information, visit https://github.com/cloudflare/cloudflared/compare/2024.6.1...2024.8.2

cloudflared: Update to 2024.8.2

---

lang/php8/Makefile

Maintainer: me
Compile tested: bcm2708
Run tested: bcm2708, Raspi
Description:
https://www.php.net/ChangeLog-8.php#8.3.10

php8: update to 8.3.10

---

lang/php8/Makefile

Maintainer: me
Compile tested: mxs, bcm2708
Run tested: bcm2708, Raspi
Description:
https://www.php.net/ChangeLog-8.php#8.2.22

[23.05] php8: update to 8.2.22

---

net/modemmanager/Makefile

ModemManager does not depend on Lua by its own, and it should not be a requirement to have Lua to run ModemManager.
@feckert What do you think?
Maintainer: @feckert @aleksander0m 
Compile tested: master OpenWrt, mips64 octeon
Run tested: master OpenWrt, mips64 octeon
Description:
We try to keep our OpenWrt builds slim and this seemed like a low hanging fruit to remove a new, for us, dependency on lua.

modemmanager: make rpcd integration optional

---

net/mwan3/Makefile
net/mwan3/files/lib/mwan3/mwan3.sh

Run tested: armv7l, Netgear R7800, r23853-560965d582, tested by `mwan3 restart`
Description:
The awk expression in mwan3_delete_iface_rules splits the `ip rule list` output by spaces, therefore $1 contains the trailing colon (e.g., "1:", "1000:"). The < and > operators compare such values as strings instead of numbers, producing unexpected results (for example, "1:" > "1000").
Change the field separator to ":" for correct number comparison, so that the right rules are removed.
An example error message that may appear before the fix:
Error: argument "1:" is wrong: preference value is invalid
It happens because `substr($1,0,4)` selects short numbers along with the colon. In other cases wrong rules may be removed, for example, if there is rule 10051, then rule 1005 will …

mwan3: Fix awk expression in mwan3_delete_iface_rules

---

net/dhtd/Makefile

Maintainer: me
Compile tested: ramips/mt76x8, WR902AC, OpenWrt master
Run tested: startup and peering with other instances on the Internet
Description: Fixes a potential segmentation fault.

dhtd: udpate to 1.0.2

---

net/adblock-fast/Makefile
net/adblock-fast/README.md
net/adblock-fast/files/adblock-fast.config.update
net/adblock-fast/files/etc/config/adblock-fast
net/adblock-fast/files/etc/init.d/adblock-fast
net/adblock-fast/files/etc/uci-defaults/90-adblock-fast

Maintainer: me
Description:
This version brings two significant updates:
* support for text labels/names for the external lists
* better processing of the config update files, which cleans up entries with missing URLs
Also:
* new config file contains names for all lists
* it tries to match existing URLs with the names from the new config file and update user config as part of uci-defaults script
* contains minor updates to copyright/license/upstream URL/README
* updates the config update script to remove sysctl.org list as it's outdated
* adds two new remote lists: Hagezi and 1Hosts

adblock-fast: update to 1.1.2-3

---

net/adblock-fast/Makefile
net/adblock-fast/README.md
net/adblock-fast/files/adblock-fast.config.update
net/adblock-fast/files/etc/config/adblock-fast
net/adblock-fast/files/etc/init.d/adblock-fast
net/adblock-fast/files/etc/uci-defaults/90-adblock-fast

Maintainer: me
Description:
This version brings two significant updates:
* support for text labels/names for the external lists
* better processing of the config update files, which cleans up entries with missing URLs
Also:
* new config file contains names for all lists
* it tries to match existing URLs with the names from the new config file and update user config as part of uci-defaults script
* contains minor updates to copyright/license/upstream URL/README
* updates the config update script to remove sysctl.org list as it's outdated
* adds two new remote lists: Hagezi and 1Hosts
(cherry picked from commit …

[23.05] adblock-fast: update to 1.1.2-3

---

net/netatalk/Makefile

Maintainer: Antonio Pastor / @APCCV
Run tested: ipq806x - C2600: start server, connect from MacOS, update TimeMachine backups
Description:
No changes to package other than using latest available upstream code base.

netatalk: Update to 3.2.5

---

libs/boost/Makefile

Compile tested: mvebu, Turris Omnia, Turris OS 8 = OpenWrt 23.05
Run tested: mvebu, Turris Omnia, Turris OS 8 = OpenWrt 23.05, it runs
Description:
Using the filter-out function in the Makefile, the GCC version 6,7,8 and 9 fell to `-std=gnu++20` even though this option can be used just with GCC >=10. The GCC version 8 and 9 do support C++20, but needs to be used as `-std=gnu++2a`.
Ref:
- https://gcc.gnu.org/projects/cxx-status.html#cxx20

[23.05] boost: fix GCC options in Makefile

---

libs/inih/Makefile

Adds compatibility with APK. Switches from codeload to local tarballs. Smaller and simpler.

inih: remove r from version

---

lang/rust/Makefile

Compile tested: aarch64
Description: upstream point release that fixes a couple of small bugs

rust: update to 1.80.1

---

lang/lua-eco/Makefile

A new package lua-eco-packet added since 3.6.0.
Maintainer: me
Description:
Release notes for 3.6.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.6.0

lua-eco: update to 3.6.0

---

net/natmap/Makefile
net/natmap/files/natmap.init

Description:
1. Update to 20240813.

natmap: update to 20240813

---

net/hev-socks5-server/Makefile

Maintainer: @heiher
Description:
1. Update to 2.6.7.

hev-socks5-server: update to 2.6.7

---

net/crowdsec-firewall-bouncer/Makefile
net/crowdsec-firewall-bouncer/files/crowdsec-firewall-bouncer.initd

Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.4
Description: 
- updated to new upstream release version 0.0.29
-  added retry_initial_commit option to init script (by Quba1)
-  aligned namings in script with crowdsec-firewall-bouncer

crowdsec-firewall-bouncer: new upstream release version 0.0.29

---

.github/workflows/check-apk-valid-version.yml

APK uses a deterministic version schema, have the CI check that changed packages actually follow that version schema.

ci: check if packages use an APK compatible version

---

multimedia/mjpg-streamer/Makefile
multimedia/mjpg-streamer/files/mjpg-streamer.init

[ "$enabled" ] returns true whatever non-empty value enabled has, including 0.
(cherry picked from commit 20ea1d9812fe8d6f693e21004d0eaeb5a5128718)
Maintainer: @thess @roger-
Compile tested: main
Run tested: 23.05 manually copying the fixed file
Description:

[23.05] mjpg-streamer: fix option enabled check in init.d

---

net/natmap/Makefile
net/natmap/files/natmap.init

Description:
1. Update to 20240813.

[23.05] natmap: update to 20240813

---

net/hev-socks5-server/Makefile

Maintainer: @heiher
Description:
1. Update to 2.6.7.

[23.05] hev-socks5-server: update to 2.6.7

---

net/unbound/Makefile
net/unbound/files/iptools.sh
net/unbound/files/odhcpd.awk

Compile tested: SNAPSHOT, r27106-74553537f1
Run tested: SNAPSHOT, r27106-74553537f1
Description:
* fix gawk incompatibility in iptools.sh
Since commit 2664e85a640244e6792df5b9c4edfc69669edf19 "/usr/bin/awk" points to gawk (if installed) and no longer to busybox awk. This reveals a long standing gawk incompatibility in iptools.sh, e.g.
```
root@blackhole:~# /etc/init.d/unbound restart
10542
awk: cmd. line:12: warning: escape sequence `\.' treated as plain `.'
awk: cmd. line:12: warning: escape sequence `\.' treated as plain `.'
awk: cmd. line:6: (FILENAME=- FNR=1) fatal: split: second argument is not an array
awk: cmd. line:14: warning: escape sequence `\.' treated as plain `.'
awk: cmd. line:14: warning: escape sequence `\.' treated as plain `.'
awk: cmd. …
```

unbound: fix gawk incompatibility

---

.github/workflows/check-apk-valid-version.yml

This action was mostly based on the autorelease CI job and somehow there is an error that if multiple packages are affected, the path is concatenated instead of adding a space.
Secondly the APK return code 0 wasn't good enough for the if condition and caused it to trigger even on valid versions.

ci: fix APK version detection

---

net/natmap/Makefile
net/natmap/files/natmap.init

Description:
1. Allow binding to a port or port range.

natmap: allow binding to a port or port range

---

net/bind/Makefile

Fixes CVEs:
- CVE-2024-1975: remove sig 0 support
- CVE-2024-4076: qctx-zversion was not being cleared when it should have been leading to an assertion failure if it needed to be reused.
- CVE-2024-1737: An excessively large number of rrtypes per owner can slow down database query processing, so a limit has been placed on the number of rrtypes that can be stored per owner (node) in a cache or zone database. This is configured with the new "max-rrtypes-per-name" option, and defaults to 100.
- CVE-2024-1737: Excessively large rdatasets can slow down database query processing, so a limit has been placed on the number of records that can be stored per rdataset in a cache or zone database. This is configured with the new "max-records-per-type" option, and defaults to 100.
- CVE-2024-0760: …

bind: bump to 9.18.28

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.29.2)

docker-compose: Update to version 2.29.2

---

net/udpxy/Makefile

Maintainer: me
Compile tested: bcm27xx/bcm2711
Run tested: RPi 4B
Description:
Fixes uninitialized address.
Also makes PKG_VERSION compatible with APK (https://github.com/openwrt/packages/issues/23706).

udpxy: update to latest version

---

multimedia/xupnpd/Makefile

Maintainer: me
Compile tested: bcm27xx/bcm2711
Run tested: RPi 4B
Description:
Update xupnpd to latest version.
Full changelog: https://github.com/clark15b/xupnpd/compare/e4e542d9b6d0043d470fda283e2cd325bbb91950...2bc1e741e0efe04cb3150430ff25410093618b4f
Also makes PKG_VERSION compatible with APK (https://github.com/openwrt/packages/issues/23706).

xupnpd: update to latest version

---

.github/workflows/check-apk-valid-version.yml

Using -ne wasn't such a good idea since it would do a numeric compare. Now use -n which checks if the length is non-zero. APK prints the problematic version if - problematic - so this should now do the trick.

ci: final round of APK CI fixes

---

sound/squeezelite/Makefile
sound/squeezelite/files/squeezelite.init

Add logic in squeezelite.init to handle -U <control> cmdline option and squeezelite.options.unmute=<control> uci option.
Run tested: SNAPSHOT r27140-ccc06f6716

squeezelite: handle option to unmute ALSA control

---

kernel/v4l2loopback/Makefile

Use PKG_VERSION for apk compat Need to remove the v.
Maintainer: @mpromonet

v4l2loopback: update to 0.13.2

---

utils/ntfs-3g/Makefile

Maintainer: @thess / @neheb
Compile tested:x86_64
Run tested: QEMU x86_64, master
Description:
This fixes CVE-2022-40284.
Security release 2022.10.3 (Oct 31, 2022)
* Rejected zero-sized runs
* Avoided merging runlists with no runs

ntfs-3g: Bump to 2022.10.3

---

libs/libmspack/Makefile

Reworked PKG_VERSION for apk compatibility.

libmspack: update to 0.11alpha

---

net/basicstation/Makefile
net/basicstation/patches/001-build-with-mbedtls-3.x.patch

Maintainer:  @mars642 
Run tested: no
Description:
The basicstation build fails since the change to the new major version 3.x of mbedtls, because of API changes in the new mbedtls version.
To fix the compilation for new mbedtls version, the waiting pullrequest is backported as a patch.
Thanks to 'Glenn Strauss' to create this PR:
https://github.com/lorabasics/basicstation/pull/198

basicstation: fix compilation for new mbedtls version 3.x

---

net/dnsproxy/Makefile

Description:
**_dnsproxy: Update to 0.73.0_**
Added
The and the options, which control the preliminary resolving , and requests from hosts (5) files before using the upstream servers.--hosts-file-enabled--hosts-filesAAAAAPTR
Note
The functionality is enabled and uses the OS-specific hosts files by default. To disable it, use option.--hosts-file-enabled=false
Changed
The upstream.AddressToUpstream now validates the host as a domain name, as opposed to the hostname validation used before. The same also applies to the proxy.ParseUpstreamConfig function.
The proxy.MessageConstructor interface has been changed to include one additional method .NewMsgNODATA
Removed
proxy.CheckDisabledAAAARequest function, …

dnsproxy: Update to 0.73.0

---

admin/openwisp-config/Makefile

The 'PKG_VERSION' string was missing and only 'PKG_SOURCE_VERSION' string was used.
ping @aparcar

openwisp-config: add missing PKG_VERSION for APK

---

admin/openwisp-monitoring/Makefile

The 'PKG_VERSION' string was missing and only 'PKG_SOURCE_VERSION' string was used.
Maintainer: @nemesifier 
ping @aparcar

openwisp-monitoring: add missing PKG_VERSION for APK

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/share/ddns/default/ovh.com.json

Run tested: x86 on 23.05.4
Description:
ovh.com supports https and IPv6 since March 2024:
https://github.com/ovh/manager/pull/11307/commits/08893f66dcbd040be1125a7003c2c538b98a32b2
New API operates under domain dns.eu.ovhapis.com:
https://help.ovhcloud.com/csm/en-gb-dns-dynhost?id=kb_article_view&sysparm_article=KB0051640
Add IPv6 support, use https and updated domain for ovh.com.

ddns-scripts: Add IPv6 and https for OVH

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/lib/ddns/update_porkbun_v3.sh
net/ddns-scripts/files/usr/share/ddns/default/porkbun.com-v3.json

Maintainer: @cahorn
Run tested: Creation and update of IPv4 A and IPv6 AAAA records through LuCI and CLI/UCI-configured ddns-scripts service on Netgear R6220, MIPS 1004K CPU, OpenWrt 22.03.5 r20134-5f15225c1e.
Description:
Adds DDNS support to the ddns-scripts package/framework/service for the [Porkbun](https://porkbun.com/) DNS provider via its [JSON API](https://porkbun.com/api/json/v3/documentation).
What other DNS provider offers the [dejigamaflipper](https://www.facebook.com/PorkbunLLC/posts/porkbun-the-one-and-only-home-for-the-patented-dejigamaflipper%EF%B8%8Fhttpswwwtiktokcom/3021628838066186/) service?!
Comments, pointers, and constructive criticism welcome as this is my first contribution to the OpenWRT community.

ddns-scripts: add support for Porkbun

---

net/dnsproxy/Makefile

Description:
**_dnsproxy: Update to 0.73.1_**
Fixed: The hosts-file-enabled field of the YAML configuration could not be parsed.
**_For more information, visit https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.73.1_**

dnsproxy: Update to 0.73.1

---

net/knxd/Makefile
net/knxd/patches/0100-version.patch

Maintainer: me
Description:
new upstream release 0.14.63

knxd: bump to version 0.14.63

---

libs/openblas/Makefile

Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/d92c42f46990db232c163e20a05c7443d9efd2e1
Run tested: x86  https://github.com/openwrt/openwrt/commit/d92c42f46990db232c163e20a05c7443d9efd2e1

openblas: bump to version 0.3.28

---

libs/libgpiod/Makefile

Description:
Upstream bug fixes:
- fix C++ tests with recent kernels which introduced stricter reconfigure behavior
- fix a use-after-free bug in python bindings
- fix passing the event clock property to line requests in python bindings
- fix a memory leak in tools
- make sure the string buffers in line-info and chip-info are big enough to not truncate the strings they hold below the size accepted by the kernel
Maintainer: me
Compile tested: mxs (Duckbill), bcm27xx/bcm2708 (Raspi)
Run tested: Raspi

libgpiod: update to 2.1.3

---

utils/docker/Makefile
utils/dockerd/Makefile

Description:
**docker: Update to 27.1.2**
_For more information, visit https://github.com/docker/cli/compare/v27.1.1...v27.1.2_
**dockerd: Update to 27.1.2**
Fix a regression that could result in a ResourceExhausted desc = grpc: received message larger than max error when building from a large Dockerfile.
CLI: Fix docker attach exiting on SIGINT instead of forwarding the signal to the container and waiting for it to exit.
CLI: Fix --device-read-bps and --device-write-bps options not taking effect.
CLI: Fix a panic happening in some cases while running a plugin.
Update BuildKit to v0.15.1.
Update Buildx to v0.16.2.
Update Go runtime to 1.21.13.
_For more information, visit …

docker: Update to 27.1.2

---

net/crowdsec-firewall-bouncer/Makefile
net/crowdsec-firewall-bouncer/files/crowdsec-firewall-bouncer.initd

Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.4
Description:
- updated to new upstream release version 0.0.29
- added retry_initial_commit option to init script (by Quba1)
- aligned namings in script with crowdsec-firewall-bouncer
(cherry picked from commit 5988abae10d9c20d87efe23a6ac5d8645aee51af)
Co-authored-by:  Quba1 <22771850+Quba1@users.noreply.github.com>

[23.05] crowdsec-firewall-bouncer: new upstream release version 0.0.29

---

lang/perl-try-tiny/Makefile

Maintainer: me
Compile tested: x86-64 / master @ 2024-08-17
Run tested: x86-64 / master @ 2024-08-17
Description:
This doesn't include functional changes, but fixes tests with Perl >= 5.41.3.

perl-try-tiny: update to 0.32

---

libs/libuwsc/Makefile

PKG_RELEASE must be an integer.

libuwsc: bump PKG_RELEASE for APK

---

net/tailscale/Makefile

Description:
**_tailscale: Update to 1.72.1_**
[Captive portal detection](https://tailscale.com/kb/1457/captive-portals) is now supported.
The [tailscale cert](https://tailscale.com/kb/1080/cli/#cert) command now contains the --min-validity flag. Use this flag to request a specified minimum remaining validity on the returned certificate. This flag is intended for automation, like cron jobs, that periodically refreshes certificates.
The [tailscale lock](https://tailscale.com/kb/1243/tailscale-lock) command now supports passing keys as files. To pass a key as a file, use the prefix file: followed by the path to the file: file:<path-to-key-file>.
A health warning is now raised if Tailscale is unable to forward DNS queries to …

tailscale: Update to 1.72.1

---

utils/mstflint/Makefile

Maintainer: me
Compile tested: x86_64, Mellanox Spectrum, OpenWrt trunk
Run tested: x86_64, Mellanox Spectrum, OpenWrt trunk, tests done
Description:
This commit updates the `mstflint` package to the latest `4.29.0` release, including the new binaries `mstfwctrl`, `mstlink`, `mstreg`, and `libexpat` as a new dependency.

mstflint: update to 4.29.0

---

net/netbird/Makefile

Compile tested: [mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc), [ar71xx-ath79](https://openwrt.org/docs/techref/targets/ar71xx-ath79), generic, TP-Link, [Archer C7](https://openwrt.org/toh/tp-link/archer_c7), v4, OpenWrt SNAPSHOT r25907-ab9a29a320
Run tested: [mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc), [ar71xx-ath79](https://openwrt.org/docs/techref/targets/ar71xx-ath79), generic, TP-Link, [Archer C7](https://openwrt.org/toh/tp-link/archer_c7), v4, OpenWrt SNAPSHOT r25907-ab9a29a320
Description:
- `netbird` supports the `wireguard` kernel module, but it can work without it in user mode, losing some performance, but we know in advance that `netbird` will run as root, therefore supporting the …

netbird: add kmod-wireguard dependency

---

multimedia/graphicsmagick/Makefile

Maintainer: me
Description:
Explicitly disable gs and libzip in configure to prevent host dependencies leakage.

graphicsmagick: update to 1.3.44

---

net/unbound/Makefile
net/unbound/patches/010-configure-uname.patch

Compile tested: Turris Omnia (mvebu/armv7) on self-compiled OpenWrt master
Run tested: Turris Omnia (mvebu/armv7) on self-compiled OpenWrt master, using as a home network DNS server (and using the dnsmasq script for local device names)
Description:
Update to 1.21.0

unbound: update to 1.21.0

---

net/xray-core/Makefile

Description:
xray-core: update to 1.8.24
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.23...v1.8.24

xray-core: update to 1.8.24

---

libs/liburing/Makefile

Maintainer: @gladiac 
MariaDB and Samba builds okay with uring enabled.

liburing: update to 2.7

---

net/netbird/Makefile
net/netbird/test.sh

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27195-cddda1d44d ~r27195-cddda1d44d~ |
- Changelog:
- [v0.28.9](https://github.com/netbirdio/netbird/releases/tag/v0.28.9)
- [v0.28.8](https://github.com/netbirdio/netbird/releases/tag/v0.28.8) …

netbird: update to 0.28.9 and add test

---

net/xray-core/Makefile

Description:
xray-core: update to 1.8.24(cherry picked from commit https://github.com/openwrt/packages/commit/1c7bd8ba1d116466aba9192e8b589a40a3632df3)
For more information, visit https://github.com/XTLS/Xray-core/compare/v1.8.23...v1.8.24

[23.05]xray-core: update to 1.8.24

---

utils/uhubctl/Makefile

Maintainer: @snh
Compile tested: OpenWrt master, mips64 octeon
Run tested: OpenWrt master, mips64 octeon
Description:
New release containing among other things the patches mentioned in https://github.com/openwrt/packages/pull/24734.
Testing:
```
root@oob-lab-sw1:~# uhubctl -v
2.6.0
root@oob-lab-sw1:~# uhubctl
Current status for hub 4 [1d6b:0003 Linux 6.6.39 xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 2 ports, ppps]
Port 1: 02a0 power 5gbps Rx.Detect
Port 2: 02a0 power 5gbps Rx.Detect
Current status for hub 3 [1d6b:0002 Linux 6.6.39 xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 2 ports, ppps]
Port 1: 0503 power highspeed enable connect [0403:6011 FTDI USB <-> Serial Cable FTYICQ95]
Port 2: 0503 power highspeed enable connect [0bda:b812 Realtek 802.11ac NIC 123456] …
```

uhubctl: update to 2.6.0

---

net/cloudflared/Makefile
net/cloudflared/files/cloudflared.init

Maintainer: me
Description:
Sometimes the wan connection needs time to be established (e.g. cold boot after power loss) and the service may crash as the internet is yet available. Add a trigger to reload the service once the wan interface is up.

cloudflared: reload service if wan inferface has (re)connected

---

libs/apr/Makefile

apache web server builds all right.

apr: update to 1.7.5

---

libs/libmaxminddb/Makefile

rsyslog with libmaxminddb builds all right.

libmaxminddb: update to 1.11.0

---

libs/liburcu/Makefile

Description:
- update of the library `knot` depends on

liburcu: update to version 0.14.1

---

net/knot/Makefile

Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbd)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbd)
Description:
- Release upgrade (https://www.knot-dns.cz/2024-09-02-version-340.html)
- Enabled D-Bus support with libdbus-1 library

knot: update to version 3.4.0

---

.github/workflows/check-apk-valid-version.yml

Run tested: tested locally
Description:
Use return code instead of scraping the stdio of `apk version --check`.

ci: avoid subshell invocation on APK version check

---

net/dhcpcd/Makefile

Maintainer: Marko Ratkaj
Compile tested: x86_64, mediatek/mt7622
Run tested: x86_64, mediatek/mt7622
Description:
Update to 10.0.10. Also fix https://github.com/openwrt/openwrt/issues/16254.

dhcpcd: bump to 10.0.10

---

ipv6/tayga/Makefile
ipv6/tayga/files/tayga-proto.sh

The commit adds options for static mapping, which is essential for 464xlat(clat) usage. 
But routes and firewall rules have to be configured manually.
To use tayga as clat/nat46:
0. specify $ipv4_addr, $prefix, $map_{ipv4,ipv6} properly, and set $noroutes to 1 to prevent creating routes for nat64
1. add custom IPv4 routes to tayga, possibly with a reasonable metric for default route
2. add a SNAT firewall rule for processing IPv4 traffic destined for tayga
3. add firewall rules to allow FORWARD traffic between tayga and WAN6
4. add a $map_ipv6 route to tayga for guiding return traffic
Maintainer: @oskar456
Run tested: aarch64, CMCC RAX3000M, OpenWrt 23.05.4
Description:
See above.

tayga: add options for static mapping

---

lang/php8/Makefile
lang/php8/patches/0007-Add-support-for-use-of-the-system-timezone-database.patch

Maintainer: me
Compile tested: mxs, arm1176
Run tested:  Raspberry Pi
Description:
https://www.php.net/ChangeLog-8.php#8.3.11
A minor adaption to a single patch is required.

php8: update to 8.3.11

---

libs/glib2/Makefile
libs/glib2/patches/006-c99.patch
libs/glib2/patches/010-pcre.patch
libs/glib2/patches/020-locale.patch
libs/glib2/patches/100-CVE-2024-34397-gdbusmessage-Cache-the-arg0-value.patch
libs/glib2/patches/101-CVE-2024-34397-gdbusconnection-Make-a-backport-of-g_set_str-available.patch
libs/glib2/patches/102-CVE-2024-34397-tests-Add-a-data-driven-test-for-signal-subscriptions.patch
libs/glib2/patches/103-CVE-2024-34397-tests-Add-support-for-subscribing-to-signals-from-a-well-.patch
libs/glib2/patches/104-CVE-2024-34397-tests-Add-a-test-case-for-what-happens-if-a-unique-name-d.patch
libs/glib2/patches/105-CVE-2024-34397-tests-Add-test-coverage-for-signals-that-match-the-messag.patch
libs/glib2/patches/106-CVE-2024-34397-gdbusprivate-Add-symbolic-constants-for-the-message-bus-i.patch
libs/glib2/patches/107-CVE-2024-34397-gdbusconnection-Move-SignalData-SignalSubscriber-higher-u.patch
libs/glib2/patches/108-CVE-2024-34397-gdbusconnection-Factor-out-signal_data_new_take.patch
libs/glib2/patches/109-CVE-2024-34397-gdbusconnection-Factor-out-add_signal_data.patch
libs/glib2/patches/110-CVE-2024-34397-gdbusconnection-Factor-out-remove_signal_data_if_unused.patch
libs/glib2/patches/111-CVE-2024-34397-gdbusconnection-Stop-storing-sender_unique_name-in-Signal.patch
libs/glib2/patches/112-CVE-2024-34397-gdbus-Track-name-owners-for-signal-subscriptions.patch
libs/glib2/patches/113-CVE-2024-34397-gdbusconnection-Don-t-deliver-signals-if-the-sender-doesn.patch
libs/glib2/patches/114-CVE-2024-34397-tests-Add-a-test-for-matching-by-two-well-known-names.patch
libs/glib2/patches/115-CVE-2024-34397-tests-Add-a-test-for-signal-filtering-by-well-known-name.patch
libs/glib2/patches/116-CVE-2024-34397-tests-Ensure-that-unsubscribing-with-GetNameOwner-in-flig.patch
libs/glib2/patches/117-CVE-2024-34397-gdbus-proxy-test-Wait-before-asserting-name-owner-has-gon.patch
libs/glib2/patches/118-CVE-2024-34397-gdbusconnection-Allow-name-owners-to-have-the-syntax-of-a.patch
libs/glib2/patches/120-gdbusmessage-Clean-the-cached-arg0-when-setting-the-messa.patch

Compile tested: x86/64, OpenWrt 23.05
Run tested: BPI-R4 + Quectel RM520N-G and ModemManager
Description:
Bump glib2 to 2.74.7 which fixes CVE-2023-29499, CVE-2023-32611, CVE-2023-32636, CVE-2023-32643, CVE-2023-32665 and on top of that backport CVE-2024-34397 fix from Debian Bookworm glib2 package 2.74.6-2+deb12u2. While at it refresh the patches so they apply cleanly.
References: https://security-tracker.debian.org/tracker/source-package/glib2.0
Fixes: CVE-2023-29499, CVE-2023-32611, CVE-2023-32636, CVE-2023-32643, CVE-2023-32665, CVE-2024-34397

[23.05] glib2: update to 2.74.7 to fix several CVEs

---

net/mwan3/Makefile
net/mwan3/files/usr/sbin/mwan3track

The grep parameters in the nping test appear to be in the wrong order. grep expects pattern and then filename.
Run tested:
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.0'
DISTRIB_REVISION='r16279-5cc0535800'
DISTRIB_TARGET='ipq40xx/generic'
DISTRIB_ARCH='arm_cortex-a7_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt 21.02.0 r16279-5cc0535800'
DISTRIB_TAINTS='no-all busybox'
```
Description:
Setting nping as a track_method option in /etc/config/mwan3 would always result in the interface failing all checks and becoming offline.
```
config condition
option interface 'mob2s1a1'
option reliability '1'
option count '1'
option timeout '1'
option down '3'
option up '3'
option track_method 'nping'
list track_ip 'www.google.co.uk'
option interval '2'
```
Changing the line in mwan3track
`result=$(grep …

mwan3: fix grep order for nping track method

---

net/pbr/Makefile
net/pbr/files/etc/config/pbr
net/pbr/files/etc/init.d/pbr
net/pbr/files/etc/uci-defaults/90-pbr
net/pbr/files/etc/uci-defaults/91-pbr-netifd

Maintainer: me
Description:
Makefile:
* remove pbr-iptables flavour
Init-script:
* improve detection of wireguard server and client instances
* integrate wg_server_and_client into init script
* remove traffic_killswitch() and trap() and related options/code
* remove internal nft_file_support variable as fw4 nft file is the only running mode
* improve debug() and is_supported_interface() functions
* improve detection of incompatible user script files
* double-quote some strings due to shellcheck errors
* flush ip rules from pbr tables instead of deleting last one
Other files:
* remove /usr/share/pbr/pbr.user.wg_server_and_client as obsolete
* remove references to the file above …

pbr: update to 1.1.7-7

---

net/chrony/Makefile

Maintainer: me
Compile tested: (mipsel, Cudy WR1300, OpenWrt 23.05)
Run tested: (mipsel, Cudy WR1300, OpenWrt 23.05, NTP server and client, NTS client)
Description:
Update to the latest upstream release

chrony: update to 4.6

---

utils/eza/Makefile

release notes:
0.18.24: https://github.com/eza-community/eza/releases/tag/v0.18.24
0.19.0: https://github.com/eza-community/eza/releases/tag/v0.19.0
0.19.1: https://github.com/eza-community/eza/releases/tag/v0.19.1
0.19.2: https://github.com/eza-community/eza/releases/tag/v0.19.2
Maintainer: me
Run tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt snapshot
Description:
(skipped several versions before updating because there were only little changes, mostly related to the upstream repository's CI)

eza: update to 0.19.2

---

lang/rust/Makefile
lang/rust/patches/0001-Update-xz2-and-use-it-static.patch

Compile tested: arm_cortex-a9_neon, clamav builds fine
Description:
- Automatically refresh one patch
- Other patch is unchanged

rust: update to 1.81.0

---

net/ntpd/Makefile

Maintainer: @ffontaine @hauke @knthm
Compile tested: x86_64 & octeon, master
Run tested: x86_64 & octeon, master
Description:
Fixes #24918 which got introduced with openwrt c364cb8.
Credit for the fix goes to Hirokazu MORIKAWA.
Test:
```
bluecmd@oob-lab-sw3:~$ ntpq -p localhost
remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
129.151.196.70  .STEP.          16 u    -   64    0    0.000   +0.000   0.000
ntp.netnod.se   .STEP.          16 u   19   64    0    0.000   +0.000   0.000
time.cloudflare .STEP.          16 u   78   64    0    0.000   +0.000   0.000
*ntp7.flashdance 194.58.202.148   2 u    6   64    1    1.080   -0.252   0.079
```

ntpd: disable autoreconf fixup

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

Description: Update to v3.0.4
- Fixes CVE-2024-45506

haproxy: update to v3.0.4

---

lang/php8/Makefile
lang/php8/patches/0007-Add-support-for-use-of-the-system-timezone-database.patch

Maintainer: me
https://www.php.net/ChangeLog-8.php#8.2.23

[23.05] php8: update to 8.2.23

---

utils/dockerd/files/dockerd.init
utils/dockerd/files/etc/config/dockerd

Maintainer: @G-M0N3Y-2503 @p-w-p 
Compile tested: x86_64 / master @ 2024-09-07
Run tested: x86_64 / master @ 2024-09-07
Description:
add config options to set http porxy for dockerd, refer to https://docs.docker.com/engine/daemon/proxy/ for details

dockerd: add config options for http proxy

---

utils/nerdctl/Makefile

Compile tested: Ubuntu 23.04 x64 / OpenWrt SNAPSHOT @ https://github.com/openwrt/packages/commit/36b1dd75fd9da1ea13f1ce1ee679c6b3c9c402cc
Description: nerdctl: Docker-compatible CLI for containerd
- Update to [1.7.7](https://github.com/containerd/nerdctl/compare/v1.7.6...v1.7.7)
- Set version information with ldflag

nerdctl: update to 1.7.7

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.29.3)

docker-compose: Update to version 2.29.3

---

libs/expat/Makefile

Compile tested: mvebu/FG-50E, snapshot
- This release contains fixes for CVE-2024-45490, CVE-2024-45491, CVE-2024-45492.
- Since official place for expat development moved from SourceForge to GitHub, SourceForge was removed from PKG_SOURCE_URL.
- Use gzip archive to avoid xz usage.
- Remove DOCBOOK_TO_MAN=OFF from CMAKE_OPTIONS because we already have EXPAT_BUILD_DOCS=OFF, which has same effect.

[Security] expat: update to 2.6.3

---

utils/ripgrep/Makefile
utils/ripgrep/patches/010-fix-riscv64.patch

ripgrep: update to 4.1.1

---

net/mdns-repeater/Makefile
net/mdns-repeater/files/mdns-repeater.init

Maintainer: @axkg
Compile tested: aarch64_cortex-a53, Xiaomi AX6S, snapshot, 23.05.4
Run tested: 23.05.4, snapshot, ramips (Xiaomi Mi Router 4A Gigabit Edition), aarch64_cortex-a53 (AX6S)
Description:
Added `respawn` to procd parameters with default options.
Sometimes `mdns-repeater` quits or crashes, leaving service stopped, requiring manual (re)start. This commit should fix that – and I use this patch this on all my openwrt routers for nearly a year.

add respawn to mdns-repeater init

---

libs/boost/Makefile

Maintainer:  @ClaymorePT 
Compile tested: Used SDK from today -> `openwrt-sdk-bcm27xx-bcm2712_gcc-13.3.0_musl.Linux-x86_64`
Description:
This commit updates boost to version 1.86.0
This update does not bring new libraries.
More info about Boost 1.86.0 can be found at the usual place [1].
[1]: https://www.boost.org/users/history/version_1_86_0.html

boost: Updates package to version 1.86.0

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.29.4)

docker-compose: Update to version 2.29.4

---

net/dnsproxy/Makefile

Description:
**_dnsproxy: Update to 0.73.1_**
Fixed: Get rid of github.com/jessevdk/go-flags dependency.
**_For more information, visit_** https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.73.2

dnsproxy: Update to 0.73.2

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27300-e7ea93e1e3 ~r27300-e7ea93e1e3~ |
- Changelog:
- [v0.29.1](https://github.com/netbirdio/netbird/releases/tag/v0.29.1)
- [v0.29.0](https://github.com/netbirdio/netbird/releases/tag/v0.29.0) …

netbird: update to 0.29.1

---

net/zerotier/Makefile
net/zerotier/files/etc/config/zerotier
net/zerotier/files/etc/init.d/zerotier
net/zerotier/files/etc/uci-defaults/80-zt-migration

Split configuration in global and per-network sections.
This  change is not backwards compatible!
Maintainer: me
Compile tested:  WR902AC-v3 (ramips/mt76x8) with OpenWrt master
Run tested: connects to Zerotier global network

zerotier: split configuration

---

utils/lxc/Makefile

No patches needed to be rebased, simple version bump.

lxc: update to 6.0.2

---

libs/tiff/Makefile

Run tested: WRT3200ACM with imagemagick

tiff: update to 4.7.0

---

net/aardvark-dns/Makefile
net/netavark/Makefile
net/slirp4netns/Makefile
utils/conmon/Makefile
utils/conmon/patches/010-remove-libdl-dep.patch
utils/crun/Makefile
utils/podman/Makefile
utils/podman/patches/010-do-not-build-docs.patch

Description:
bump podman and its dependencies to latest version

podman: Update to 5.2.2

---

net/zerotier/Makefile
net/zerotier/files/etc/config/zerotier
net/zerotier/files/etc/init.d/zerotier
net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-path.patch
net/zerotier/patches/0002-remove-PIE-options.patch
net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch
net/zerotier/patches/0004-add-missing-libatomic.patch
net/zerotier/patches/0005-remove-noexecstack.patch

Maintainer: me
Compile tested: ramips/mt76x8, OpenWrt master
Run tested: same as compiled for, tl-wr902ac-v3

zerotier: update to 1.14.1

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
Description:
* BUGFIX: correctly identify available RAM
* BUGFIX: properly store remote list filesize in config
* shellcheck updates

adblock-fast: bugfixes and shellcheck update

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
Description:
* BUGFIX: correctly identify available RAM
* BUGFIX: properly store remote list filesize in config
* shellcheck updates
(cherry picked from commit 4bdaea90d63ed12af4b513d833de64bac5f0f2b8)

[23.05] adblock-fast: bugfixes and shellcheck update

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr
net/pbr/files/etc/uci-defaults/90-pbr

Maintainer: me
Description:
* allow using WG servers as gateways if explicitly set in supported_interface
* automatically execute user scripts in /etc/pbr.d/
* change the dnsmasq restart logic on start/reload/restart
* further nft file atomic mode-related code cleanup
* fix spelling in error message

pbr: update to 1.1.7-10

---

net/crowdsec-firewall-bouncer/Makefile

Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.4
Description:
updated to new upstream release version 0.0.30

crowdsec-firewall-bouncer: new upstream release version 0.0.30

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

haproxy: update to v3.0.5

---

net/tailscale/README.md

Signed-off-by: John Schmidt <john@schmidthaus.rocks>
Maintainer: @ja-pa @mochaaP
Description:
Removed references to installing two packages. There has only been one package for a year.

tailscale: fix Readme.

---

utils/docker-compose/Makefile

Maintainer: me
Description:
Three new upstream releases. [Changelog](https://github.com/docker/compose/releases)

docker-compose: Update to version 2.29.7

---

net/tgt/Makefile

Maintainer: me
Compile tested: qualcommax/ipq807x, DL-WRX36, r27432+3-93881ec190
Run tested: qualcommax/ipq807x, DL-WRX36, r27432+3-93881ec190, works as expected
Description:

tgt: update to 1.0.93

---

utils/btrfs-progs/Makefile

Description:
- Update package URL

btrfs-progs: update to 6.11

---

utils/stress-ng/Makefile
utils/stress-ng/patches/001-disable-extra-stressors.patch

stress-ng: bump to version 0.18.04

---

net/dnsproxy/Makefile
net/dnsproxy/files/dnsproxy.init

Maintainer: me
Description:
1. Mount hosts files since the daemon is in ujail
2. Set hosts options at last as all other options set after it will be ignored
Drop redundant reload_service func while at it.
Fixes: #25010

dnsproxy: fix set hosts options

---

libs/libmariadb/Makefile
libs/libmariadb/patches/010-link-to-libucontext.patch
libs/libmariadb/patches/020-fix-ucontext-maybe-uninitialized.patch

Maintainer: @miska 
Run tested: WRT3200ACM - addrwatch_mysql runs fine
Description:
- Remove a mirror with invalid certificate
- Manually rebase 010-link-to-libucontext.patch
- Add new 020-fix-ucontext-maybe-uninitialized.patch

libmariadb: update to 3.4.1

---

net/iperf3/Makefile

Description:
Since https://github.com/openwrt/openwrt/commit/3fa5ee0b28b736c5d06af34ed5c3e80f78235fe8 OpenWrt no longer disables SCTP support by default (to unblock its enablement for other packages). It caused the leak of libsctp dependency to iperf3. Here we disable it explicitly to fix the build.
Fixes https://github.com/openwrt/packages/issues/25014.

iperf3: explicitly disable SCTP

---

libs/libgudev/Makefile
libs/libjcat/Config.in
libs/libjcat/Makefile
libs/libqmi/Config.in
libs/libqmi/Makefile
libs/libxmlb/Config.in
libs/libxmlb/Makefile
utils/fwupd/Config.in
utils/fwupd/Makefile
utils/fwupd/files/etc/init.d/fwupd
utils/fwupd/test.sh

Maintainer: me
Compile tested: x86_64, lantiq_xrx200
Run tested: lantiq_xrx200, 23.05
Description:
Adds [fwupd](https://github.com/fwupd/fwupd) and its four required dependecies [libjcat](https://github.com/hughsie/libjcat), [libxmlb](https://github.com/hughsie/libxmlb), [libgusb](https://github.com/hughsie/libgusb) and [libgudev](https://gitlab.gnome.org/GNOME/libgudev).
fwupd allows firmware upgrades for various devices, including many modems via the modem-manager and fastboot options. The package includes a daemon `/usr/libexec/fwupd/fwupd` started by `/etc/init.d/fwupd` and controlled by `/usr/bin/fwupdmgr`, as well as  `/usr/bin/fwupdtool` that can be used without the daemon.

fwupd: add package

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr

Maintainer: me
Description:
* fixes https://github.com/openwrt/packages/issues/24999

pbr: bugfix: filter only static routes for new tables

---

net/iputils/Makefile
net/iputils/patches/001_version_fix.patch

Maintainer: me
Compile tested: x86/master
Run tested: x86/master, basic manual runtime testing
Description:
New upstream release: https://github.com/iputils/iputils/releases/tag/20240905

iputils: bump to 20240905

---

net/squid/Makefile

squid: update to 6.11

---

net/crowdsec-firewall-bouncer/Makefile

Run tested: mediatek/filogic, BPI-R3, Openwrt 23.05.5
Description:
updated to new upstream release version 0.0.31

crowdsec-firewall-bouncer: updated to new upstream release version 0.0.31

---

net/tailscale/Makefile

Maintainer: me
Compile tested: aarch64_cortex-a53 @ SNAPSHOT
Description:
See <https://github.com/tailscale/tailscale/blob/main/build_dist.sh#L40>.
Removed esoteric features, shaves off about 500kb from the final executable.

tailscale: build with less features

---

admin/openwisp-config/Makefile

openwisp-config: update to 1.1.0

---

multimedia/gst1-libav/Makefile
multimedia/gst1-plugins-bad/Makefile
multimedia/gst1-plugins-base/Makefile
multimedia/gst1-plugins-good/Makefile
multimedia/gst1-plugins-ugly/Makefile
multimedia/gstreamer1/Makefile

Maintainer: @neheb @flyn-org 
Compile tested: imx6
Run tested: imx6
Description:
Bumps to the latest 1.24.8 bugfix release

Gstreamer packages bump to 1.24.8

---

net/nut/Makefile

Maintainer: @ruralroots (no MAINTAINER in Makefile, but from latest change)
Compile tested: x86-64 / master @ 2024-08-17
Run tested: x86-64 / master @ 2024-08-17
Description:
nut was recently upgraded to 2.8.1 which includes a change in
configure.ac that uses /run for the pidfile if it exists during build.
Explicitly specify --with-pidpath to use the path that was used with
2.8.0 and prior.
The symptom here was that there'd be leftover processes when nut-monitor
was restarted.
Fixes: 82f36e0c781d ("nut: update to 2.8.1")
Fixes: https://github.com/openwrt/packages/issues/24106

nut: specify pid path during build

---

utils/lsof/Makefile
utils/lsof/patches/000-disable-man.patch

Maintainer: me
Compile tested: aarch64_cortex-a53, qualcommax/ipq807x, r27617+3-a9540a4e33
Run tested: aarch64_cortex-a53, qualcommax/ipq807x, r27617+3-a9540a4e33, works as expected
Description:
- update to 4.99.3
- refresh the patch

lsof: update to 4.99.3

---

utils/tmux/Makefile

Maintainer: me
Compile tested: aarch64_cortex-a53, qualcommax/ipq807x, r27617+3-a9540a4e33
Run tested: aarch64_cortex-a53, qualcommax/ipq807x, r27617+3-a9540a4e33, works as expected
Description:

tmux: update to 3.5

---

utils/stress-ng/Makefile

Changelog: https://github.com/ColinIanKing/stress-ng/releases/tag/V0.18.05

stress-ng: bump to version 0.18.05

---

CONTRIBUTING.md

The documentation stated that `PKG_VERSION` is the OpenWrt version and therefore includes the `PKG_RELEASE`, but this statement was incorrect and has been removed to avoid confusion.
Recently I have done a test commit https://github.com/openwrt/packages/commit/22e430ce78695cab17310066417d8033154300b0# for netbird package, to write this I see others examples and read:
https://github.com/openwrt/packages/blob/86ad54b482fbd987a5fca47cf591a85f9f7b9c58/CONTRIBUTING.md?plain=1#L200-L205
The confusion is, the user can use `PKG_VERSION` to test the version of program, but at same time `PKG_VERSION` includes `PKG_RELEASE` and can't be used to test version?
Let's see how the contributors write their tests:
https://github.com/openwrt/packages/blob/86ad54b482fbd987a5fca47cf591a85f9f7b9c58/utils/yq/tes …

CONTRIBUTING.md: remove incorrect info about `PKG_VERSION`

---

net/hev-socks5-server/Makefile

Maintainer: me
Description: update to 2.6.8

hev-socks5-server: update to 2.6.8

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27644-d03f3dcf3b |
- Changelog:
- [v0.29.4](https://github.com/netbirdio/netbird/releases/tag/v0.29.4)
- [v0.29.3](https://github.com/netbirdio/netbird/releases/tag/v0.29.3)
- [v0.29.2](https://github.com/netbirdio/netbird/releases/tag/v0.29.2) …

netbird: update to 0.29.4

---

lang/php8/Makefile
lang/php8/patches/0025-php-5.4.9-fixheader.patch
lang/php8/patches/1004-disable-phar-command.patch

Maintainer: me
Compile tested: mxs, bcm2711
Run tested: bcm2711 (Raspi)
Description:
This fixes:
- CVE-2024-8925
- CVE-2024-8926
- CVE-2024-8927
- CVE-2024-9026
https://www.php.net/ChangeLog-8.php#8.3.12

php8: update to 8.3.12

---

utils/xz/Makefile

Remove GPL-2.0+ and GPL-3.0+ from `PKG_LICENSE` as GNU GPLv2+ and GPLv3+ are only used for the build system as  stated in [1]( https://github.com/tukaani-project/xz/commit/02ddf09bc3079b3e17297729b9e43f14d407b8fc):
>  The build system contains public domain files, and files that
>  are under GNU GPLv2+ or GNU GPLv3+. None of these files end up
>  in the binaries being built.
Moreover, add 0BSD which is used since version 5.6.0 [2](https://github.com/tukaani-project/xz/commit/689e0228baeb95232430e90d628379db89583d71)
Fixes: b9e87eeb7deb8b3890415b835c9c69764893c023 (xz: import from old packages feed)

utils/xz: fix license

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr
net/pbr/files/etc/init.d/pbr-iptables
net/pbr/files/usr/share/nftables.d/chain-post/dstnat/30-pbr.nft
net/pbr/files/usr/share/nftables.d/chain-post/dstnat_lan/30-pbr.nft
net/pbr/files/usr/share/nftables.d/table-post/30-pbr.nft

Maintainer: me
Description:
* switch from pbr_dstnat_lan to pbr_dstnat chain
* remove counters in traffic_killswitch
* remove double counters (if enabled) in dns policies
* target proper chain in tor policies
PS. Sorry accidentally deleted the feature branch while previous PR was still open.

[23.05] pbr: bugfix for dns & tor policies and traffic_killswitch

---

net/mwan3/Makefile
net/mwan3/files/usr/sbin/mwan3track

Run tested: RUTX12 Router, OpenWrt distribution release 21.02.0
Description: Currently, `check_quality` option is only available for track method `ping`. This PR adds `check_quality` option for track method `httping`.

mwan3: add check_quality for httping

---

net/hev-socks5-server/Makefile

Maintainer: me
Description: update to 2.6.8

[23.05] hev-socks5-server: update to 2.6.8

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27680-ca325ee516 |
- Changelog:
- [v0.30.0](https://github.com/netbirdio/netbird/releases/tag/v0.30.0)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.29.4...v0.30.0
Compiled …

netbird: update to 0.30.0

---

multimedia/go2rtc/Makefile
multimedia/go2rtc/files/go2rtc.init
multimedia/go2rtc/files/go2rtc.yaml

Maintainer: me / @vooon
Compile tested: OpenWrt master,
Run tested: OpenWrt master, x64_64 / gl-b2200 ARMv7
Description:
Adds [go2rtc](https://github.com/AlexxIT/go2rtc), a service that re-streams camera to many other protocols.
WebRTC can use TURN (like coturn) to establish connection in case of dual SNAT.

go2rtc: add package

---

net/xray-core/Makefile

Description:
**_xray-core: update to 24.9.30_**
> [!NOTE]  
> SplitHTTP is now only compatible with v1.8.24. Removed QUIC and DomainSocket transport layers, and eliminated compatibility code for legacy configurations.
**_For more information, visit https://github.com/XTLS/Xray-core/releases/tag/v24.9.30 https://github.com/XTLS/Xray-core/compare/v1.8.24...v24.9.30_**

xray-core: update to 24.9.30

---

utils/tmux/Makefile

Maintainer: me
Compile tested: aarch64_cortex-a53, qualcommax/ipq807x, r27697+4-d51353db26
Run tested: aarch64_cortex-a53, qualcommax/ipq807x, r27697+4-d51353db26, works, no issues so far
Description:

tmux: update to 3.5a

---

lang/php8/Makefile
lang/php8/patches/0025-php-5.4.9-fixheader.patch
lang/php8/patches/1004-disable-phar-command.patch

Maintainer: me
Compile tested: mxs & bcm2708
Run tested: Raspberry Pi
Description:
This fixes:
- CVE-2024-8925
- CVE-2024-8926
- CVE-2024-8927
- CVE-2024-9026
https://www.php.net/ChangeLog-8.php#8.2.24

[23.05] php8: update to 8.2.24

---

lang/php8/Makefile

Maintainer: me
Run tested: Duckbill (mxs)
Description:
This fixes:
- CVE-2024-8925
- CVE-2024-8926
- CVE-2024-8927
- CVE-2024-9026
https://www.php.net/ChangeLog-8.php#8.1.30

[22.03] php8: update to 8.1.30

---

utils/qemu/Makefile
utils/qemu/patches/0007-qga-invoke-separate-applets-for-guest-shutdown-modes.patch

Compile tested: x86_64, OpenWrt master
Description:
I've used wrong type in qemu guest agent patch, found by: @curtdept
Fixes https://github.com/vooon/openwrt-packages/commit/d9da6e792a25e8b34c271d4c3752c7185c77878d#r147673510

qemu: 9.1.0-2: fix guest agent patch

---

net/pdns-recursor/Makefile

fixes CVE-2024-25590
Description:

pdns-recursor: update to 5.1.2

---

net/xray-core/Makefile

Description:
xray-core: update to 24.9.30(cherry picked from commit https://github.com/openwrt/packages/commit/caa09e5377050794be23af8e4bd079bbad137150)
For more information, visit https://github.com/XTLS/Xray-core/releases/tag/v24.9.30 https://github.com/XTLS/Xray-core/compare/v1.8.24...v24.9.30

[23.05]xray-core: update to 24.9.30

---

net/knxd/Makefile
net/knxd/patches/0100-version.patch

Maintainer: me
Description:
new upstream release 0.14.65

knxd: bump to version 0.14.65

---

multimedia/gst1-plugins-good/Makefile

Compile tested: MIPS malta 32 BE
Description:
Deactivate the dependencies to libgudev.
This fixes the build of gst1-plugins-good.
This fixes the following problem:
```
Package gst1-mod-video4linux2 is missing dependencies for the following libraries:
libgudev-1.0.so.0
```

gst1-plugins-good: Remove gudev

---

admin/fluent-bit/Makefile

Maintainer: @rthakur33 
Compile tested: MIPS malta BE 32
Description:
Deactivate the dependencies to libsals2, libzlib and libzstd.
This fixes the build of fluent-bit.
This fixes the following problem:
```
Package fluent-bit is missing dependencies for the following libraries:
libsasl2.so.3
libz.so.1
libzstd.so.1
```

fluent-bit: Deactivate sasl2, zlib and zstd

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27750-4f4cb52e24 |
- Changelog:
- [v0.30.1](https://github.com/netbirdio/netbird/releases/tag/v0.30.1)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.30.0...v0.30.1
Compiled …

netbird: update to 0.30.1

---

libs/libmaxminddb/Makefile

Maintainer: @ja-pa, @krant
Compile tested: qualcommax,ipq807x ,main
Run tested: NO
Description:
libmaxminddb has switched to using `CMAKE_INSTALL_PREFIX`, `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` for generating the pkg-config in upstream commit [1] and thus broke pkg-config file generation in openwrt.
```
It would generate:
prefix=/usr
exec_prefix=/usr
libdir=lib
includedir=include
```
Obviously libdir and includedirs are incorrect for OpenWrt and this would then cause pdns compilation to fail if geoip backend was enabled since it uses pkg-config to get the required flags and passing just lib for LDFLAGS would cause libtool to error out since that path is not valid.
So, lets use SED magic to replace `libdir` and `includedir` with the correct paths, so now pkg-config looks …

libmaxminddb: fixup lib and include dirs in pkg-config

---

net/pdns-recursor/Makefile
net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch

Run tested: docker openwrt/rootfs:x86-64-23.05.5
Description:
fixes CVE-2024-25590
as there is no fix for 4.8.x, this bumps to the latest 4.9.x

[23.05] pdns-recursor: update to 4.9.9

---

net/pdns-recursor/Makefile
net/pdns-recursor/patches/100-disable-recursor.conf-dist.patch

Run tested: docker openwrt/rootfs:x86-64-22.03.7
Description:
fixes CVE-2024-25590
as there is no fix for 4.8.x, this bumps to the latest 4.9.x

[22.03] pdns-recursor: update to 4.9.9

---

libs/srt/Config.in
libs/srt/Makefile
multimedia/gst1-plugins-bad/Makefile

Maintainer: @neheb @flyn-org 
Compile tested: imx6 (all 3 encryption settings + unencrypted)
Run tested: imx6 (all 3 encryption settings + unencrypted - tested using Nimble streamer as receiver)
Description:
This series adds full support for SRT streaming (Secure Reliable Transport)
- The 1st commit adds the lib as a new package
- The 2nd commit enables it within gstreamer (plugins-bad)
Encryption support is present for:
- OpenSSL (using modern EVP mechanism)
- mbedtls
- gnutls

Add support for SRT streaming within gstreamer

---

net/chrony/Makefile

Maintainer: me
Compile tested: ramips, mt7621, OpenWrt 23.05.5
Run tested: ramips, mt7621, OpenWrt 23.05.5, NTP client and server

chrony: update to 4.6.1

---

net/i2pd/Makefile
net/i2pd/files/i2pd.init

Compile tested: 23.05.5 x86-64
Run tested: 23.05.5 x86-64
Description:
* Updating package to 2.54.0
* Changed Makefile to install binary to /usr/bin (as in upstream)
* Updated init.rc script with new path

i2pd: Update to 2.54.0

---

net/modemmanager/Makefile
net/modemmanager/files/lib/netifd/proto/modemmanager.sh
net/modemmanager/files/usr/sbin/ModemManager-monitor

Compile tested: no only script changes
Run tested: x86_64, APU3, latest, tests done
Description:
The main change is:
```
Add pin check attempts:
This new check in the proto modemanager prevents the SIM card from being
blocked and therefore PUK is not required. If the PIN is entered incorrectly
in the 'uci' configuration, it makes no sense to try this several times
until the PUK is required. Should it nevertheless happen that the PUK
is required, then this will logged.
```
The other changes are small fixes and cleanups.

modemmanager: add pin check attempts and fixes

---

libs/libxslt/Makefile
net/nginx/Makefile
net/nginx/patches/nginx-mod-njs/101-feature_test_fix.patch
net/nginx/patches/nginx-mod-njs/102-sizeof_test_fix.patch
net/nginx/patches/nginx-mod-njs/104-endianness_fix.patch
net/nginx/patches/nginx/101-feature_test_fix.patch
net/nginx/patches/nginx/105-optional-libexslt.patch
net/nginx/patches/nginx/201-ignore-invalid-options.patch
net/nginx/patches/nginx/300-fix-deprecated-openssl-3_0.patch

Add support for NJS module. Various patch are required to make this
module correctly compile with the required library mainly related on
detecting config flags.
In doing this, improve feature patch on nginx core.
It's not needed to bump PKG_RELEASE as we are not changing anything in the main package and just introducing a new module.

nginx: Add support for NJS module

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27798-dbc2923cbe |
- Changelog:
- [v0.30.2](https://github.com/netbirdio/netbird/releases/tag/v0.30.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.30.1...v0.30.2
Compiled …

netbird: update to 0.30.2

---

net/keepalived/Makefile
net/keepalived/files/etc/hotplug.d/keepalived/511-firewall
net/keepalived/files/etc/hotplug.d/keepalived/551-dnsmasq
net/keepalived/files/lib/functions/keepalived/hotplug.sh

Compile tested: not yet compiled
Run tested: only tested on v23.05.5 with manually modified files
Description:
I've found some issues in hotpulg.sh called during sync, master/backup switch... and in dnsmasq hotplug handler
I report the commit descriptions:
for **hotpulg.sh**
- some init.d scripts like firewall and sqm do not return the actual state of the service if called with "running" parameter. This result in the init script called with "start" parameter and the service may not load the new configuration. firewall init script is one of this
An option is added in order to skip the "running" check for the service
- when "set_reload_if_sync" is not set in the hotplug script, the service is not expected to reload. That is not true because even if not set, the value …

keepalived: fixes in hotplug script

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
Description:
New features:
* explicitly add allowed domains on download/allow to the dnsmasq.servers config file
Cleanup:
* remove unneeded EXTRA_COMMANDS
* remove unneeded EXTRA_HELP
* remove unnecessary `\n` escapes
* remove unnecessary line breaks from output on download
Optimization:
* simplify is_integer()
* replace long if with case
* more verbose output on download

adblock-fast: explicitly allowing domains for dnsmasq.servers

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27897-b27075e12b |
- Changelog:
- [v0.30.3](https://github.com/netbirdio/netbird/releases/tag/v0.30.3)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.30.2...v0.30.3
Compiled …

netbird: update to 0.30.3

---

net/i2pd/Makefile
net/i2pd/files/i2pd.init

Compile tested: 23.05.5 x86-64
Run tested: 23.05.5 x86-64
Description:
* Updating package to 2.54.0
* Changed Makefile to install binary to /usr/bin (as in upstream)
* Updated init.rc script with new path

[23.05] i2pd: update to 2.54.0

---

net/sstp-client/Makefile
net/sstp-client/patches/100-musl-compat.patch
net/sstp-client/patches/200-openssl-deprecated.patch

Bump sstp-client to 1.0.20 release. This fix compilation error with new PPPd version 2.5.0 as some API changed.
Patch automatically refreshed.
---
Notice: CI might fail as a fix for this has been pushed in openwrt main and maybe the SDK needs to be refreshed.

sstp-client: bump to 1.0.20 release

---

lang/ruby/Makefile

This release is a routine update that includes minor bug fixes.
Link: https://www.ruby-lang.org/en/news/2024/09/03/3-3-5-released/
Maintainer: me
Compile tested: main on mediatek, x86
Another commit was added to handle a build issue with old rust (ubuntu 22.04).

ruby: update to 3.3.5

---

libs/gperftools/Makefile

Changelog: https://github.com/gperftools/gperftools/releases/tag/gperftools-2.16
Maintainer: me

gperftools:  bump to version 2.16

---

net/yggdrasil/Makefile

Maintainer: William Fleurant / @wfleurant
Compile tested: OpenWrt v23.05.5 tag
Run tested: MediaTek MT7621
Description:
bumped version

yggdrasil: bump to 0.5.9

---

libs/ell/Makefile
net/mptcpd/Makefile
net/mptcpd/files/mptcpd.init
net/mptcpd/patches/001-Make-listening-socket-creation-optional.-297.patch
net/mptcpd/patches/002-Support-ELL-0.68-l_netlink_message-API.-303.patch
net/mptcpd/patches/050-ell-only-include-ell-ell.h-header.patch
net/mptcpd/patches/100-include-byteswap-h.patch
net/mptcpd/patches/110-define-bswap_constant_32.patch
net/mptcpd/patches/120-no-format-security.patch
net/mptcpd/patches/130-simplify-log-function.patch
net/mptcpd/patches/140-no-error-h.patch

Maintainer: me
Run tested: -
Description:
Package the Multipath TCP daemon as well as the Embedded Linux Library (ell) it depends on.
Loosely based on prior work of @jeff277
Requires openwrt/openwrt#16786

mptcpd: add package

---

net/tailscale/Makefile

Maintainer: me and @mochaaP
Compile tested: arm_cortex-a7_neon-vfpv4 OpenWrt 23.05.5
Description:

tailscale: update to 1.76.3

---

utils/eza/Makefile

Maintainer: me
Run tested: aarch64 mediatek/filogic (BananaPi R3), OpenWrt snapshot, simple run-test
Release notes:
0.20.1: https://github.com/eza-community/eza/releases/tag/v0.20.1
0.20.2: https://github.com/eza-community/eza/releases/tag/v0.20.2
0.20.3: https://github.com/eza-community/eza/releases/tag/v0.20.3
0.20.4: https://github.com/eza-community/eza/releases/tag/v0.20.4
0.20.5: https://github.com/eza-community/eza/releases/tag/v0.20.5

eza: update to 0.20.5

---

libs/libmicrohttpd/Makefile

Maintainer: @lynxis
Compile tested: not tested
Description: Shorter title, to fix a problem reported [here](https://github.com/openwrt/packages/pull/25208#discussion_r1818506918).

libmicrohttpd: make TITLE shorter

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

adblock-fast: bugfix: fix allowed domains for dnsmasq.servers

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr

Maintainer: me
Description:
Changes from @stangri
* remove unneeded `\n` escapes
* cosmetic improvements to make code more consistent
* remove duplicate uci_get_device()
* add more output on start/stop
* remove wan up detection on boot/start
* address Tor policies errors
* prevent interface_routing() failures for downed interfaces
Changes from @bigsmile74:
* improve is_integer()
* improve is_domain()
* improve filter_options()
* imrove is_ipv4() so that is_ipv4_netmask() can be retired
* improve is_phys_dev so that is_phys_dev_quick() can be retired
* add the dhcp.lan.force=0 warning

pbr: update to 1.1.7-29

---

net/mwan3/files/etc/hotplug.d/iface/16-mwan3-user

Maintainer: me
Run tested: no
Description:
Fixes deadlock with multiple init script calls.
Fixes https://github.com/openwrt/openwrt/issues/15994

mwan3: close flock fd when starting mwan3.user scripts

---

admin/zabbix/Makefile

Compile tested: x86/64/generic - 23.05.4
Run tested: -- Not tested yet --
Description:
`master` branch contains these changes but 23.05 also needs them. They should be backported.

zabbix: Backport libevent dependency to 23.05

---

net/knxd/Makefile
net/knxd/patches/0100-version.patch

Maintainer: me
Description:
new upstream release 0.14.66

knxd: bump to new version 0.14.66

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/usr/lib/ddns/update_porkbun_v3.sh

I noticed that the porkbun updater is changing my wildcard domain A and AAAA records from `*.<domain>.<tld>` to just `<domain>.<tld>` after the first run.
It would appear that Porkbun's API considers a missing `name` key to mean you want to drop the subdomain from the record (see [here](https://porkbun.com/api/json/v3/documentation#DNS%20Edit%20Record%20by%20Domain%20and%20ID)), which is probably not the intended behavior here.
This PR simply adds one line to correct that.

ddns-scripts: porkbun bugfix to not delete subdomain on A/AAAA record

---

net/pptpd/Makefile
net/pptpd/patches/100-musl-compat.patch

Needed forward declaration for missing function.
Removed some no longer needed musl fixes.
Maintainer: 
ping @M95D
Fixes: https://github.com/openwrt/packages/issues/25207

pptp: fix compilation with GCC14

---

utils/docker-compose/Makefile

docker-compose: Update to version 2.30.1

---

utils/attendedsysupgrade-common/Makefile

Compile tested: x86/64 snapshot
Run tested: x86/64 snapshot
Description:
Move the init script to '50-attendedsysupgrade', so it is run in the middle of the init sequence, rather than after all the explicitly ordered ones.  This allows later scripts, specifically the 99-level ones, to modify the contents of the attendedsysupgrade configuration.
A user reported issues with setting values in their ASU-generated custom init script `99-asu-defaults`, and it turned out that the attendedsysupgrade-common script was run after everything else.  Since it's not really important where it runs, I just chose to put it at 50, seems as good a place as any as long as it's after the custom 99- ones.
Ref: https://forum.openwrt.org/t/owut-openwrt-upgrade-tool/200035/191
Our solution …

attendedsysupgrade-common: give the uci-defaults script a run level

---

libs/libseccomp/Makefile

libseccomp: update to 2.5.5

---

net/openconnect/Makefile
net/openconnect/README
net/openconnect/files/openconnect.sh

This allows specifying a custom vpnc-compatible config script.
Maintainer: me
Compile tested: n/a (runtime only)
Run tested: OpenWRT 23.05.5 (Routerich AX3000) with and without set option
Description:
This allows specifying a custom vpnc-compatible config script.

openconnect: introduced script parameter

---

net/pbr/Makefile
net/pbr/files/etc/init.d/pbr
net/pbr/files/etc/uci-defaults/90-pbr
net/pbr/files/etc/uci-defaults/91-pbr-netifd

Maintainer: me
Description:
* bump compat version to accommodate new strings
* update dnsmasq-related code to better support separate confdirs for separate instances
* remove procd_lan_interface as it didn't reflect that it's a list of devices
* introduce procd_lan_device list
* improve the output() function (thanks @bigsmile74)
* remove duplicate uci_get_device
* improve ipv6 detection and interface setup
* improve dhcp force detection for interfaces name differently from lan
* fix array/element parameters for some json operations
* remove unneeded null redirects for `try` calls
* remove (iptables-only) capitalized chain names form validation
* working pbr-netifd flavor

pbr: update to 1.1.7-47

---

net/apfree-wifidog/Makefile
net/apfree-wifidog/files/wifidogx.conf
net/apfree-wifidog/files/wifidogx.init

Description:
https://github.com/liudf0716/apfree-wifidog/releases/tag/7.10.2082

apfree-wifidog: update to 7.10.2082

---

net/adblock-fast/Makefile
net/adblock-fast/files/etc/init.d/adblock-fast

Maintainer: me
Description:
* bump compat version to accommodate new strings
* improve the output() function (thanks @bigsmile74)
* implement support for user-configurable per-instance dnsmasq confdirs for dnsmasq.conf|dnsmasq.ipset|dnsmasq.nftset options

adblock-fast: update to 1.1.2-10

---

net/tgt/Makefile
net/tgt/files/tgt.config
net/tgt/files/tgt.init

Maintainer: me
Run tested: aarch64_cortex-a53, qualcommax/ipq807x, r27617+3-a9540a4e33, thin provisioning works: `du -h` on the backing store file shows the decrease in size on `rm` and `fstrim` at the initiator side. The init script reports and rejects the unsupported combinations.
Description:
enable the `thin_provisioning` option for the rdwr disk targets
Fixes #25065

tgt: enable support for thin_provisioning

---

net/netatalk/Makefile

Maintainer: Antonio Pastor / @APCCV
Compile tested: ipq806x (23.05.3, snapshot)
Run tested: ipq806x - C2600: start server, connect from MacOS, read/write files to home share, create/update TimeMachine backups
Description:
No changes to package other than using latest available upstream code base. Starting Netatalk 4.x build uses meson instead of autotools.

netatalk: Update to 4.0.4

---

admin/atop/Makefile

Maintainer: @utoni @krant 
Compile tested: qualcommax/ipq807x, main
Run tested: Just compile time tested
Description:
If `nls.mk` is not included and `BUILD_NLS` is set compilation will fail with:
```
aarch64-openwrt-linux-musl-gcc atop.o version.o various.o  deviate.o   procdbase.o acctproc.o photoproc.o photosyst.o cgroups.o rawlog.o ifprop.o parseable.o showgeneric.o drawbar.o showlinux.o  showsys.o showprocs.o atopsar.o  netatopif.o netatopbpfif.o gpucom.o  json.o utsnames.o -o atop -lncursesw -lz -lm -lrt -Lstaging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/usr/lib -Lstaging_dir/toolchain-aarch64_cortex-a53_gcc-13.3.0_musl/lib -fuse-ld=bfd -znow -zrelro  -Lstaging_dir/target-aarch64_cortex-a53_musl/usr/lib -lglib-2.0 -lintl …
```

atop: add missing nls.mk include

---

net/kadnode/Makefile
net/kadnode/files/kadnode.init

* add support for mbedtls 3.0.0
* fix newline in init script
Maintainer: me
Description:

[WIP] kadnode: Update to version 2.4.0

---

utils/owut/Makefile

Maintainer: me
Compile tested: x86/64 snapshot
Run tested: x86/64 snapshot
Description:
Move uci-defaults file to run level 51, so it is executed immediately after the attendedsysupgrade-common package's uci-defaults script.
Depends on the already merged https://github.com/openwrt/packages/pull/25234

owut: fix order of uci-defaults

---

net/netatalk/Makefile

Maintainer: Antonio Pastor / @APCCV
Compile tested: ipq806x (23.05.3, snapshot)
Run tested: ipq806x - C2600: start server, connect from MacOS, read/write files to home share, create/update TimeMachine backups. File sharing from MacOS 9.2.
Description:
Backport of Netatalk 4.0.4 (missed 24.10 cutoff by 3h).  Includes:
- bump to 4.0.4 using meson build
- Makefile cleanup
- AppleTalk feature

netatalk: Update to 4.0.4 (backport)

---

net/netatalk/Makefile

Maintainer: me / @APCCV
Compile tested: snapshot SDK ipq806x
Run tested: C2600 - snapshot. Run afpd, file sharing.
Description:
afpstats requires several libraries that would increase significantly final install size.
Eliminating from build removes dependency on GLIBC.
Fixed a typo in description define (that typo has been there for over 10 years...)

netatalk: Remove apfstats feature to solve dependency issues

---

net/netatalk/Makefile

Maintainer: me / @APCCV
Compile tested: snapshot SDK ipq806x
Run tested: C2600 - snapshot. Run afpd, file sharing.
Description:
afpstats requires several libraries that would increase significantly final install size.
Eliminating from build removes dependency on GLIBC.
Fixed a typo in description define (that typo has been there for over 10 years...)

netatalk: Remove apfstats feature to solve dependency issues (backport)

---

utils/docker-compose/Makefile

Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.30.2)

docker-compose: Update to version 2.30.2

---

libs/json-glib/Makefile
libs/libmariadb/Makefile
utils/mariadb/Makefile

As requested on openwrt-devel in October 2024 [1], remove maintainer, including any copyright lines.
[1] https://lists.openwrt.org/pipermail/openwrt-devel/2024-October/043323.html
Maintainer:
Run tested: 
Description:
Thanks for all the support over the years. All the best!

Remove maintainer

---

net/umurmur/patches/100-Add-support-for-mbedtls-3.x.patch

Add pending patch fixing support for MbedTLS 3.x.
Small variation to the provided PR from [0] to remove the dropped mbedtls/certs.h header.
[0] https://github.com/umurmur/umurmur/pull/190

umurmur: add pending patch fixing support for MbedTLS 3.x

---

libs/glib2/Makefile

Description:
Some applications using Glib2 require using glib_compile_schemas during build and deduct the path of that executable via pkg-config. This currently fails as the path is not fixed in gio.pc. Fix that by adding glib_compile_schemas to the sed expression taking care of applying prefix_hostpkg.
(This change is required to build GTK+ in video feed)

glib2: fix pkg-config path for glib_compile_schemas

---

net/ariang/Makefile

Maintainer: @Ansuel (find it by checking history of the package Makefile)
Description:
https://github.com/mayswind/AriaNg/releases
AriaNg 1.3.7 Change Log
1. Each task list page supports independent display order
2. Rpc dropdown list on larger screen would be shown larger
3. Other bug fix and user interface optimization
This version works well on my aarch64_generic platform router.
This upgrade has not changed much, the file names and quantities have not changed.

AriaNg: Update to 1.3.7

---

utils/mstflint/Makefile

Maintainer: me
Compile tested: `x86_64`, Mellanox Spectrum, OpenWrt trunk
Run tested: `x86_64`, Mellanox Spectrum, OpenWrt trunk, tests done
Description:
This commit updates the `mstflint` package to the latest `4.30.0` release.
It also drops the `zlib` dependency because `libsqlite3` and `libxml2` already depend on it.

mstflint: update to 4.30.0

---

lang/lua-eco/Makefile

Maintainer: me
Description:
Release notes for 3.6.1: https://github.com/zhaojh329/lua-eco/releases/tag/v3.6.1

lua-eco: update to 3.6.1

---

lang/node/Makefile
lang/node/patches/999-fix_building_with_system_icu_76.patch

Run tested: (qemu 9.1.1) aarch64
Description:
fix building with system icu 76
ICU 76 decided to reduce overlinking[^1] thus `icu-i18n` will no longer add `icu-uc` when linking to shared libraries. This results in undefined symbols/references when trying to build with system ICU 76.
[^1]: unicode-org/icu@199bc82
ref: https://github.com/nodejs/node/pull/55563

node: Preparing to update ICU to 76

---

utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/nat_traffic.lua

Maintainer: [@champtar](https://github.com/jdbaldry/packages/blob/171f68ffb3f10c023ff0358f0325a041b64ef3fc/utils/prometheus-node-exporter-lua/Makefile#L10)
Note the broken CI is present in the previous change to this package: https://github.com/openwrt/packages/pull/24328

Fix typos in NAT traffic Prometheus collector

---

libs/libgcrypt/Makefile

Description:
Install pkgconfig metadata to allow detection of libgcrypt during build of other packages which rely on pkgconfig.

libgcrypt: use pkgconfig metadata in InstallDev

---

net/ddns-scripts/Makefile

Having both double quotes and parentheses in package description may lead into trouble with apk, if parentheses are located so that they get passed "outside" the quoted parameter, and get interpreted as a token for shell. 
Example, where quoted text containing parentheses `"option param_opt(Optional Parameter)"` gets handled wrong, as the 'opening quote' is actually the closing quote from shell perspective and thus ( is seen as a shell delimiter:
```
ash: -c: line 1: syntax error near unexpected token `('
bash: -c: line 1: `/OpenWrt/e8450/staging_dir/host/bin/fakeroot
/OpenWrt/e8450/staging_dir/host/bin/apk mkpkg --info "name:ddns
-scripts-pdns" --info "version:2.8.2-r51" --info "description:D
ynamic DNS Client scripts extension for "PowerDNS" via API. It
requires: "option …
```

ddns-scripts: Adjust descriptions in Makefile for apk (no parentheses inside double quotes)

---

sound/portaudio/Makefile

Upstream moved. Also switch to local tarballs for smaller size.
Maintainer:

portaudio: update to 19.7.0

---

net/unbound/Makefile
net/unbound/files/odhcpd.sh

Compile tested: aarch64_cortex-a53, trunk
Run tested: aarch64, Linksys E8450 (UBI), trunk build
Description:
Several system hangs observed due to file lock failure resulting in multiple instances of `odphcd.sh` executing causing corruption to `unbound` config data. Current scheme does not provide *atomic* locking. Using `flock` for serialization simplifies the process.

Unbound: fix file lock race in odhcpd.sh

---

net/restic-rest-server/Makefile

restic-rest-server: update to 0.13.0
Maintainer: Tom Stöveken <tom@naaa.de>
Compile tested: SDK for OpenWrt 23.05.5
Run tested: x86/64 @ Intel(R) Celeron(R) CPU N3160 @ 1.60GHz, OpenWrt 23.05.5
Description:
Updated to version 0.13.0
Signed-off-by: Tom Stöveken <tom@naaa.de>

restic-rest-server: update to 0.13.0

---

admin/openwisp-config/Makefile

Update configuration in Makefile to fix #25168
Maintainer: @nemesifier 

openwisp-config: fix Makefile for 1.1.0

---

admin/openwisp-monitoring/Config.in
admin/openwisp-monitoring/Makefile

openwisp-monitoring: fix Makefile for 0.2.0

---

net/net-tools/Makefile

The full implementation of netstat can be useful, for example, showing inodes of sockets or displaying protocol families not supported by the busybox version.
Maintainer: @neheb @mhei
Compile tested: OpenWrt master, armvirt/64, Traverse Ten64 and ramips/mt76x8, GL-Inet GL-MT300N-V2
Run tested: OpenWrt master, armvirt/64, Traverse Ten64 and ramips/mt76x8, GL-Inet GL-MT300N-V2

net-tools: package full netstat implementation

---

net/lftp/Makefile

For some weird reason, it tries to use OS directories. Override.
Maintainer: @fededim

lftp: fix expat under GCC14

---

net/tailscale/Makefile

Compile tested: arm_cortex-a7_neon-vfpv4 OpenWrt 23.05.5
Description:

tailscale: update to 1.76.6

---

net/netbird/Makefile

| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | [Duex](https://duex.com.br/) | [DX B75ZG M.2 Intel LGA 1155 DDR3](https://duex.com.br/produto/placa-mae-dx-b75zg-m-2-intel-lga-1155-ddr3/) | n/a | OpenWrt SNAPSHOT r27897-b27075e12b |
- Changelog:
- [v0.31.0](https://github.com/netbirdio/netbird/releases/tag/v0.31.0)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.30.3...v0.31.0
Compiled …

netbird: update to 0.31.0

---

net/uspot/Makefile

Maintainer: @f00b4r0 
Compile tested: qualcommax/ipq807x, main
Description:
APK versions use dots instead of dashes, so update EXTRA_DEPENDS to make it APK compatible.

uspot: make EXTRA_DEPENDS APK compatible

---

utils/shared-mime-info/Makefile
utils/shared-mime-info/files/shared-mime-info.defaults

Description:
Move post-install script to /etc/uci-defaults so it always runs on the target and doesn't require the host to provide 'update-mime-database'.

shared-mime-info: fix post-install behaviour

---

libs/libdrm/Makefile

Maintainer :@krant
Run tested: mediatek/filogic (BananaPi R4 with panel-mipi-dbi-spi, running weston and glroots based cage)
Description:
Changes since 2.4.120:
ad750dc6 amdgpu: add marketing names from Adrenalin 23.11.1 64144740 amdgpu: add marketing names from PRO Edition for W7700 fb13af43 amdgpu: add marketing names from Windows Steam Deck OLED APU driver dfb8111e amdgpu: add marketing names from amd-6.0
9d9498f4 amdgpu: add marketing name for Radeon RX 6550M 14094328 amdgpu: add marketing names from amd-6.0.1 7ab1cdac xf86drm: ignore symlinks in process_device() 1aa800d4 Revert "xf86drm: ignore symlinks in process_device()" 7c5c742d xf86drm: Don't consider node names longer than the maximum allowed 01f91aa7 meson: make build system happy by …

libdrm: update to 2.4.123

---

sound/wavpack/Makefile

Run tested: mediatek/filogic (BPi-R4)
Description:
Add WavPack audio compression/decompression library.

wavpack: add wavpack library for audio compression

---

libs/glib-networking/Makefile
libs/glib-networking/patches/100-no-tests.patch

Maintainer: me
Description:
Add GIO modules for TLS support as well as defining proxies via well-known environment variables.

glib-networking: add package

---

admin/openwisp-config/Makefile

Description:
Update configuration in Makefile to fix #25168.
Add "/etc/openwisp/" to conf files.
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
(cherry picked from commit 67d4fa3b05e0a8ee0724bc245d6eec318351876a)

[24.10] openwisp-config: fix Makefile for 1.1.0

---

net/dhtd/Makefile

Maintainer: me
Compile tested: ramips/mt76x8, OpenWrt master

dhtd: update to version 1.0.4

---

libs/libpng/Makefile

Description:
Add convenience symlink when building with CONFIG_DEBUG.
Reported by @hnyman in https://github.com/openwrt/openwrt/pull/16899#issuecomment-2471281135

libpng: add symlink to debug library

---

net/isc-dhcp/Makefile

Maintainer: @pprindeville 
Compile tested: qualcomax/ipq807x,master
Description:
Adjust isc-dhcp versioning to be compatible with APK.

isc-dhcp: Use apk-compatible versioning

---

net/privoxy/Makefile

Adjust privoxy version for apk by removing the "-stable"
from the OpenWrt version, although it is still needed for
upstream download archive name.

privoxy: adjust version for apk

---

lang/luajit/Makefile

Like wolfssl[1], adjust version for apk by removing the hyphen.
1. https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=be952e98bc1d768a0da5b84e59a6e7c04a1cdab8
Maintainer: @milani

luajit: fix built for apk naming requirements

---

utils/hwdata/Makefile

Maintainer: @krant ?
Run tested: -
Description:
Make sure hwdata can be used by other packages during build by adding InstallDev section which includes pkgconfig as well as all types of IDs.

hwdata: package pnp.ids and add InstallDev section

---

libs/libgudev/Makefile
multimedia/gst1-plugins-bad/Makefile
multimedia/gst1-plugins-base/Makefile

Maintainer: @flyn-org @thess 
Description:
Package `gl`, `play` and `player` libraries as well as the `opengl` plugin.
Required to build GTK+

gstreamer additions required to build GTK+

---

lang/ruby/Makefile

Maintainer: @luizluca
Compile tested: host
Run tested: host (to build WebKit)
Description:
Ruby JSON modules are used to build WebKitGTK.
Include them in the host build.

ruby: include JSON modules in host build

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

haproxy: update to v3.0.6

---

net/ocserv/files/ocserv.conf.template

This commit comments out the `log-level` line in the template config file to use default value from upstream, default should be 2.
Description:

ocserv: Use default value for log-level in conf

---

utils/btrfs-progs/Makefile
utils/btrfs-progs/files/btrfs-scan.init

Compile tested: x86-64 Gentoo Linux, OpenWrt git main branch
Run tested: mvebu Linksys WRT-1900ACv1, Turris Omnia, OpenWrt git main branch r27964
Overlay on btrfs RAID works. Extroot on btrfs RAID not tested.
Description:
If users choose to build OpenWrt with btrfs-progs included and want to use a btrfs RAID for overlay/extroot,
then devices need to be scanned *before* mounting overlay/extroot. If not, btrfs won't find all RAID drives and fail to mount.
This commit:
- creates a duplicate (symlink) of the btrfs scan script so that it runs both before and after overlay/extroot mount,
- changes the scan command to not depend on blkid (-d),
- outputs the scan results to kernel log to show what's being detected, as the system logger is not yet running.

btrfs-progs: add "btrfs device scan" before overlay/extroot

---

net/knxd/Makefile
net/knxd/patches/0100-version.patch

Maintainer: me
Description:
new upstream release 0.14.67

knxd: bump to new version 0.14.67

---

libs/libesmtp/Makefile
libs/libesmtp/patches/010-gcc14.patch

_GNU_SOURCE is needed for some functions.
Removed now pointless libpthread depedency.
Maintainer: @tru7

libesmtp: fix compilation with GCC14

---

libs/libdbi-drivers/Makefile
libs/libdbi-drivers/patches/010-gcc14.patch

Patch from Alpine Linux.
Maintainer:

libdbi-drivers: fix compilation with GCC14

---

devel/unifdef/Makefile

Maintainer: me
Compile tested: host
Run tested: host (to build WPEWebKit)
Description:
The unifdef utility selectively processes conditional C preprocessor #if and #ifdef directives. It is required to build WebKit ports.

unifdef: add package

---

libs/libmanette/Makefile

Maintainer: me
Description:
libmanette offers painless access to game controllers, from any programming language and with little dependencies.

libmanette: add package

---

utils/bubblewrap/Makefile

Maintainer: me
Description:
Bubblewrap is a container tool for security sandboxes.
Requires:
* https://github.com/openwrt/openwrt/pull/16949

bubblewrap: add package

---

utils/xdg-dbus-proxy/Makefile

Maintainer: me
Description:
xdg-dbus-proxy is a filtering proxy for D-Bus connections. It is used to allow partial access to D-Bus form sandboxed processes, eg. when using bubblewrap.

xdg-dbus-proxy: add package

---

utils/ntfs-3g/Makefile

Maintainer: me
Compile tested: aarch64
Run tested: no
Description:
APK version compliance.
Remove libfuse/int hint from name.
Will merge when checks pass

ntfs-3g: APK version compliance.

---

net/git/Makefile

Maintainer: @tripolar 
Compile tested: head,aarch64, 
Run tested: aarch64 (mediatek/filogic)
Description:
The following error occurs when CONFIG_USE_APK is set.
```
ln /mnt/gl-mt6000-main/openwrt/build_dir/target-aarch64_cortex-a53_musl/git-2.46.2/.pkgdir/git/usr/lib/git-core/git /mnt/gl-mt6000-main/openwrt/build_dir/target-aarch64_cortex-a53_musl/git-2.46.2/.pkgdir/git/usr/bin/git
ln /mnt/gl-mt6000-main/openwrt/build_dir/target-aarch64_cortex-a53_musl/git-2.46.2/.pkgdir/git/usr/lib/git-core/git-shell /mnt/gl-mt6000-main/openwrt/build_dir/target-aarch64_cortex-a53_musl/git-2.46.2/.pkgdir/git/usr/bin/git-shell
touch /mnt/gl-mt6000-main/openwrt/build_dir/target-aarch64_cortex-a53_musl/git-2.46.2/.pkgdir/git.installed
mkdir -p /mnt/gl-mt6000-main/openwrt/staging_dir/target-aarch64_cortex-a53_ …
```

git: use symbolic link

---

admin/openwisp-monitoring/Config.in
admin/openwisp-monitoring/Makefile

Description: 
Cherry picked  886b3fa36d0b82071b10d0169d6950b0aaa6f16c and ca503cc4054d9a13558c7b552886a6dba359a0eb

[24.10] openwisp-monitoring: fix Makefile for 0.2.0
