- admin/openwisp-config/Makefile
Description:
Update configuration in Makefile to fix #25168.
Add "/etc/openwisp/" to conf files.
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
(cherry picked from commit 67d4fa3b05e0a8ee0724bc245d6eec318351876a)
> [23.05] openwisp-config: fix Makefile for 1.1.0

- net/openvpn-easy-rsa/Makefile
- net/openvpn-easy-rsa/patches/100-Make-package-reproducible.patch
Bump openvpn-easy-rsa to 3.2.1 release. All patch automatically refreshed.
---
#25248
> openvpn-easy-rsa: Bump to 3.2.1 release

- multimedia/gphoto2/Makefile
- multimedia/gphoto2/patches/010-pthread.patch
- multimedia/gphoto2/patches/020-gcc14.patch
Upstream backports.
Maintainer: @DocLM
> gphoto2: fix compilation with GCC14

- utils/rtklib/Makefile
Make version compatible with the apk package manager.
Add short explanation about rtklib purpose to the menu item. 
Compile tested: mediatek/filogic MT6000
> rtklib: Make version apk compatible

- lang/luv/Makefile
Make version apk compatible.
Compile tested: mediatek/filogic MT6000
Ps. @milani There are already newer versions of the package, so it might also be updated, but I just looked after the versioning.
> luv: Make version apk compatible

- sound/svox/Makefile
Adjust PKG_VERSION to be compatible with apk's semantic rules.
Maintainer:  @dmrlsn 
Compile tested: mediatek/mt7622 RT3200
> svox: Make version apk compatible

- net/snowflake/Makefile
ChangeLog:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/blob/v2.10.1/ChangeLog?ref_type=tags
(cherry picked from commit d6ad08828d9ef3d740456a227293565fff8cc99c)
Compile tested: trunk
> [24.10] snowflake: update to 2.10.1

- net/netdiscover/Makefile
Adjust version to be compatible with apk's semantic rules.
> netdiscover: Make version apk compatible

- sound/sox/Makefile
Maintainer: me
Compile tested: aarch64, mips_24kc
Run tested: No
Description:
Sox does not build if `configure` finds an installed `wavpack` library header and no library (.so) found
> sox: Remove wavpack (explicitly) from build

- admin/openwisp-monitoring/Config.in
- admin/openwisp-monitoring/Makefile
Description: 
Cherry picked  886b3fa36d0b82071b10d0169d6950b0aaa6f16c and ca503cc4054d9a13558c7b552886a6dba359a0eb
> [23.05] openwisp-monitoring: fix Makefile for 0.2.0

- net/v2ray-core/Makefile
Shorten TITLE variable to fix missing title in ncurses menu. Add SUBMENU variable to make this package appear in `Web Server/Proxies` menu.
Release notes and changes logs in the link below.
Link: https://github.com/v2fly/v2ray-core/releases/tag/v5.22.0
Link: https://github.com/v2fly/v2ray-core/compare/v5.21.0...v5.22.0
Maintainer: @1715173329 :smiling_face_with_three_hearts:   
Compile tested: bcm2711 afffcd09e5f15be53f327a80ee87d391312eb805
Run tested: no, theoretically it should work as is 
Description:
> v2ray-core: Bump to 5.22.0

- net/strongswan/Makefile
- net/strongswan/files/swanctl.init
Maintainer: @pprindeville , @Thermi 
Compile tested: NO, only changed init script
Run tested: mvebu/cortexa9/Turris Omnia/OpenWRT 21.02 (with only the init script updated to the upstream version).
Description:
This PR mainly adds support for configuring EAP-MSCHAPv2 user auth. This is the only one that is sanely supported by Windows clients.
I also fixed a bug with the pools section generation - it got generated once for each remote instead of just once.
And I also added option `send_cert` which forces sending server cert even if nobody asks for it - some clients are easier to configure this way.
I tested the changes on a swanctl-based server configured with two remotes - one IKEv2 PSK, one IKEv2 EAP-MSCHAPv2. The generated configs are valid and the server works.
> Strongswan: Added support for EAP-MSCHAPv2 authentication

- net/hev-socks5-server/Makefile
Maintainer: me
Description: update to 2.6.9
> hev-socks5-server: update to 2.6.9

- net/hev-socks5-tproxy/Makefile
Maintainer: me
Description: update to 2.5.8
> hev-socks5-tproxy: update to 2.5.8

- net/hev-socks5-tunnel/Makefile
Maintainer: me
Description: update to 2.7.5
> hev-socks5-tunnel: update to 2.7.5

- net/alist/Makefile
alist 3.39.4:
- release: Missing installation of zig
-  by @xhofe (0ba75)
web-dist 3.39.2:
- No significant changes.
No release notes available, providing diff in link below instead.
Close: #25405
Link: https://github.com/AlistGo/alist/compare/v3.39.3...v3.39.4
Link: https://github.com/AlistGo/alist-web/compare/3.39.0...3.39.2
Compile tested: bcm2711
Run tested: not
Description:
> alist: Bump to 3.39.4, web-dist to 3.39.2

- net/iperf3/Makefile
- net/iperf3/patches/030-musl-crash.patch
> iperf3: fix crashing with musl

- utils/rtty/Makefile
Maintainer: me
Description:
Release notes for 8.1.3: https://github.com/zhaojh329/rtty/releases/tag/v8.1.3
> rtty: update to 8.1.3

- admin/openwisp-monitoring/Makefile
Description:
Previously, `PKG_SOURCE_VERSION` in the Makefile was incorrectly set to `0.1.1` instead of tracking `PKG_VERSION`. This mismatch caused compilation issues for the package.
This fix ensures `PKG_SOURCE_VERSION` dynamically aligns with `PKG_VERSION` to prevent future discrepancies.
> [23.05] openwisp-monitoring: align PKG_SOURCE_VERSION with PKG_VERSION

- net/speedtest-go/Makefile
Update speedtest-go version to 1.7.9
Compile tested: MediaTek Ralink MIPS MT7621 based boards ZTE E8820S OpenWrt SNAPSHOT r28146+1-52b6c92479 / LuCI Master 24.326.01848
Run tested: MediaTek Ralink MIPS MT7621 based boards ZTE E8820S OpenWrt SNAPSHOT r28146+1-52b6c92479 / LuCI Master 24.326.01848
Description: Update speedtest-go package, a CLI with go to test internet speed
> speedtest-go: update to 1.7.9

- utils/ncdu/Makefile
Release history:
```
* Perform tilde expansion on paths in the config file (from 2.7)
* Fix JSON import of escaped UTF-16 surrogate pairs (from 2.7)
* Fix displaying and exporting zero values when extended info is not available (from 2.6)
* Fix JSON export and import of the “other filesystem” flag (from 2.5)
```
Maintainer: @clehner
> ncdu: update to 1.21

- net/cifs-utils/Makefile
- net/dawn/Makefile
- net/dnscrypt-proxy/Makefile
- net/dnscrypt-proxy2/Makefile
- net/family-dns/Makefile
- net/git-lfs/Makefile
- net/https-dns-proxy/Makefile
- net/mdns-repeater/Makefile
- net/nextdns/Makefile
- net/onionshare-cli/Makefile
- net/smartdns/Makefile
- net/xray-core/Makefile
Add SUBMENU variable for some packages in Network category. Add title for `dnscrypt-proxy` package.
Filesystem:
- cifs-utils
File Transfer:
- onionshare-cli
IP Addresses and Names:
- dnscrypt-proxy2
- family-dns
- https-dns-proxy
- mdns-repeater
- nextdns
- smartdns
Version Control Systems:
- git-lfs
Web Servers/Proxies:
- xray-core
Wireless:
- dawn
Maintainer: Should I ping all maintainers for these packages?
Compile tested: no, simple commit
Run tested: no
Description:
> network: Add SUBMENU variable for some packages

- lang/node/Makefile
- lang/node/patches/003-path.patch
- lang/node/patches/004-musl_support.patch
- lang/node/patches/007-fix_host_build_on_macos.patch
- lang/node/patches/202-node_gyp.patch
- lang/node/patches/203-icu-generic_gyp.patch
- lang/node/patches/204-v8_gyp.patch
- lang/node/patches/999-fix_building_with_system_icu_76.patch
- lang/node/patches/999-localhost-no-addrconfig.patch
- lang/node/patches/999-revert_enable_pointer_authentication_on_arm64.patch
Run tested: (qemu 9.1.1) aarch64
Description:
Upgrade Version 22.11.0 'Jod' (LTS)
This release marks the transition of Node.js 22.x into Long Term Support (LTS) with the codename 'Jod'. The 22.x release line now moves into "Active LTS" and will remain so until October 2025. After that time, it will move into "Maintenance" until end of life in April 2027.
> node: upgrade to 22.11.0 LTS

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* properly process dnsmasq instances' confdirs
* working str_replace()
* updated output()
* bugfixes and updates for error messages
* sanitize StevenBlack's hosts file
> adblock-fast: bugfixes

- lang/php8/Makefile
- lang/php8/patches/0022-Use-system-timezone.patch
- lang/php8/patches/0025-php-5.4.9-fixheader.patch
- lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Run tested: bcm27xx (Raspi)
Description:
This fixes:
- CVE-2024-8932
- CVE-2024-11236
- CVE-2024-11236
- CVE-2024-11234
- CVE-2024-11233
https://www.php.net/ChangeLog-8.php#8.3.14
> php8: update to 8.3.14

- libs/libinput/Makefile
- libs/libwacom/Makefile
Maintainer: me
Compile tested: mediatek/filogic, x86/64
Run tested: BananaPi R4 with USB keyboard, x86/64 laptop
Description:
Update libinput and build with support for tablets using libwacom.
> libinput: update and add support for libwacom

- multimedia/gst1-plugins-bad/Makefile
Compile tested: aarch64/cortex-a53, x86/64
Run tested: BananaPi R4 with MIPI-DBI display, x86/64 laptop
Description:
Build GL and Wayland libraries if GL modules is selected.
> gst1-plugins-bad: fix building GL libraries

- lang/python/django/Makefile
Fixes a bunch of CVEs.
CVE-2024-45230
https://nvd.nist.gov/vuln/detail/CVE-2024-45230
CVE-2024-45231
https://nvd.nist.gov/vuln/detail/CVE-2024-45231
(And maybe a few more).
> django: bump to 4.2.16 [23.05]

- lang/python/python-dateutil/Makefile
Maintainer: me
Compile tested: https://https://github.com/openwrt/openwrt/commit/1bdb6d84046ec1c47f28c57651358470ed212ec3  x86
Run tested: https://https://github.com/openwrt/openwrt/commit/1bdb6d84046ec1c47f28c57651358470ed212ec3    x86
Fixes:
https://github.com/openwrt/packages/pull/23648#issuecomment-2495371925
As weird as this sounds, the only different between the current version (2.9.0.post0) and 2.9.0 is the pinning of `setuptools_scm` to `< 8`. See:  https://github.com/dateutil/dateutil/releases/tag/2.9.0.post0
Also, the APK build doesn't seem to like the 'post0' suffix.
> python-dateutil: "downgrade" to version 2.9.0

- net/nginx/Makefile
- net/nginx/files/nginx.init
update init script to announce http related services over mdns
Signed-off-by: Mohd Husaam Mehdi <husaam.mehdi@iopsys.eu>
> nginx: update init script to publish services over mdns

- lang/python/django/Makefile
- lang/python/numpy/Makefile
- lang/python/python-pytz/Makefile
Maintainer: me, @peter-stadler (as co-maintainer for Django)
Compile tested: https://https://github.com/openwrt/openwrt/commit/1bdb6d84046ec1c47f28c57651358470ed212ec3  x86
Run tested: https://https://github.com/openwrt/openwrt/commit/1bdb6d84046ec1c47f28c57651358470ed212ec3    x86
> numpy,django,python-pytz: bump versions

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.6.2: https://github.com/zhaojh329/lua-eco/releases/tag/v3.6.2
> lua-eco: update to 3.6.2

- sound/mpd/Makefile
This seems to no longer fail compilation.
Use meson's b_lto to turn it on always.
ping @dhewg
> mpd: remove no-lto

- utils/sunwait/LICENSE
- utils/sunwait/Makefile
Maintainer: me
Description:
Sunwait calculates sunrise or sunset times with civil, nautical, astronomical and custom twilights.
It is intended for use in home automation with Windows Task Scheduler or cron. Use it to turn lights on before it gets dark! The program can wait from invocation until the event specified on the command line occurs or it can return immediately indicating if it is day or night. It's best to schedule Sunwait to run a little before the earliest opportunity for the event to occur each year - ie dusk range is 3:30pm to 10:30pm here, so it reasonable to schedule a dusk task at 3pm and allow Sunwait to pause the task for between 30mins and 7 and a half hours. …
> sunwait: initial commit

- utils/sunwait/LICENSE
- utils/sunwait/Makefile
Maintainer: me
Description:
Sunwait calculates sunrise or sunset times with civil, nautical, astronomical and custom twilights.
It is intended for use in home automation with Windows Task Scheduler or cron. Use it to turn lights on before it gets dark! The program can wait from invocation until the event specified on the command line occurs or it can return immediately indicating if it is day or night. It's best to schedule Sunwait to run a little before the earliest opportunity for the event to occur each year - ie dusk range is 3:30pm to 10:30pm here, so it reasonable to schedule a dusk task at 3pm and allow Sunwait to pause the task for between 30mins and 7 and a half hours. …
> [24.10] sunwait: initial commit

- net/stubby/Makefile
- net/stubby/files/stubby.init
Maintainer: unknown
Run tested: manually added to the `/etc/init.d/stubby` on OpenWrt SNAPSHOT `r28091-77cfe8fd15`
fixes #25431
> stubby: ensure appdata directory is present on service start

- lang/php8/Makefile
Maintainer: me
Description:
This fixes:
- CVE-2024-8929
- CVE-2024-8932
- CVE-2024-11233
- CVE-2024-11234
- CVE-2024-11236
https://www.php.net/ChangeLog-8.php#8.1.31
> [22.03] php8: update to 8.1.31

- lang/php8/Makefile
- lang/php8/patches/0025-php-5.4.9-fixheader.patch
- lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Description:
This fixes:
- CVE-2024-8929
- CVE-2024-8932
- CVE-2024-11233
- CVE-2024-11234
- CVE-2024-11236
https://www.php.net/ChangeLog-8.php#8.2.26
> [23.05] php8: update to 8.2.26

- net/keepalived/Makefile
- net/keepalived/files/keepalived.config
Compile tested: lantiq_xrx200, latest master
Run tested: lantiq_xrx200, latest master
Description:
This section was renamed some time ago. Although this would be fixed by the uci-default migration script, we should set this correctly in the example config file right away.
Please also backport this change to the branches openwrt-23.05 and openwrt-24.10.
> keepalived: fix name of globals section in default config

- net/gping/Makefile
Maintainer: me
Compile tested: aarch64 mediatek/filogic (BananaPi R4), OpenWrt snapshot
Run tested: aarch64 mediatek/filogic (BananaPi R4), OpenWrt snapshot
> gping: update to 1.18.0

- utils/eza/Makefile
Maintainer: me
Compile tested: aarch64 mediatek/filogic (BananaPi R4), OpenWrt snapshot
Run tested: aarch64 mediatek/filogic (BananaPi R4), OpenWrt snapshot
Release notes:
0.20.6: https://github.com/eza-community/eza/releases/tag/v0.20.6
0.20.7: https://github.com/eza-community/eza/releases/tag/v0.20.7
0.20.8: https://github.com/eza-community/eza/releases/tag/v0.20.8
0.20.9: https://github.com/eza-community/eza/releases/tag/v0.20.9
0.20.10: https://github.com/eza-community/eza/releases/tag/v0.20.10
> eza: update to 0.20.10

- lang/ruby/Makefile
Ruby 3.3.6 is a routine update that includes minor bug fixes. It also stops warning missing default gem dependencies that will be bundled gems in Ruby 3.5.
Link: https://github.com/ruby/ruby/releases/tag/v3_3_6
Maintainer: me
Compile tested: built on ath79_generic,mediatek_filogic,ramips_mt7620,x86_64
Run tested: none (minor update)
> ruby: update to 3.3.6

- lang/ruby/Makefile
Ruby 3.2.6 is a minor bug fix release.
Link: https://github.com/ruby/ruby/releases/tag/v3_2_6
Maintainer: me
Compile tested: built on ath79_generic,mediatek_filogic,ramips_mt7620,x86_64
Run tested: none (minor update)
> [23.05] ruby: update to 3.2.6

- libs/libdrm/Makefile
Compile tested: x86/pentium4, riscv64
Run tested: -
Description:
- drm_intel should depend on i386||i686 (x86 doesn't exist).
- drm_etnaviv is available on RISC-V as well.
Fixes: e092819cd ("libdrm: split into sub-packages")
> libdrm: fix architecture dependencies of sub-packages

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Run tested: x86_64, Dell EMC Edge620, OpenWrt snapshot
Description:
* temporary hack until https://github.com/openwrt/openwrt/pull/16806 is merged
> adblock-fast: bugfix: dnsmasq instances confdir hack

- net/pbr/Makefile
- net/pbr/files/etc/init.d/pbr
- net/pbr/files/etc/uci-defaults/91-pbr-netifd
- net/pbr/files/usr/share/pbr/pbr.user.aws
Maintainer: me
Description:
* stop building netifd flavour until netifd isuees are resolved
* improve output()
* improve inline_set()
* improve is_config_enabled()
* bugfix is_domain()
* improve is_supported_protocol()
* improve is_supported_interface()
* bugfix is_tor_running()
* improve ipv4_leases_to_nftset()
* improve ipv6_leases_to_nftset()
* add check for ip-full binary on start
* bugfix: load environment on boot
* bugfix: hack around dnsmasq confdir instances
* bugfix: IPv6-related fixes for internet_routing() and status_service()
* improve netifd setup by bringing code into the init script from uci-defaults
* bugfix: do not attempt to use IPv6 prefixes in …
> pbr: 1.1.7-65 bugfixes and improvements

- net/pbr/Makefile
- net/pbr/files/etc/init.d/pbr
- net/pbr/files/etc/uci-defaults/91-pbr-netifd
- net/pbr/files/usr/share/pbr/pbr.user.aws
Maintainer: me
Description:
* stop building netifd flavour until netifd isuees are resolved
* improve output()
* improve inline_set()
* improve is_config_enabled()
* bugfix is_domain()
* improve is_supported_protocol()
* improve is_supported_interface()
* bugfix is_tor_running()
* improve ipv4_leases_to_nftset()
* improve ipv6_leases_to_nftset()
* add check for ip-full binary on start
* bugfix: load environment on boot
* bugfix: hack around dnsmasq confdir instances
* bugfix: IPv6-related fixes for internet_routing() and status_service()
* improve netifd setup by bringing code into the init script from uci-defaults
* bugfix: do not attempt to use IPv6 prefixes in …
> [24.10] pbr: 1.1.7-65 bugfixes and improvements

- net/dhtd/Makefile
Maintainer: me
Compile tested: yes, ramips/mt76x8
Run tested: no, trivial changes
> dhtd: update to 1.0.5

- net/ksmbd-tools/Makefile
- net/ksmbd-tools/patches/030-glib.patch
Compile tested: meditek/filogic MT6000
Run tested: meditek/filogic MT6000
Description: 
- manually refresh patch 030-glib.patch
Major changes are:
fix adduser / addshare prompting on musl libc
fix use of veto files as global share parameter
lookup primary group and don't recurse in ksmbd.conf `@group` handling
fix a leak and an intermittent auth failure in Kerberos 5
add global parameter kerberos support
detailed changelog here: https://github.com/cifsd-team/ksmbd-tools/releases/tag/3.5.3
> ksmbd-tools: update to version 3.5.3

- lang/python/python-urllib3/Makefile
Maintainer: @jefferyto @BKPepe 
Description:
Add hostbuild directives for `python-urllib3`.
This package is a required when building a `python-requests` host package (#25499).
This will ultimately be consumed by the `python-platformio` host package (build system) that I am working on at the [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic) project.
> python-urllib3: add hostbuild

- net/knot/Makefile
Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbl)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbl)
Description:
- Release upgrade (https://www.knot-dns.cz/2024-12-06-version-343.html)
> knot: update to version 3.4.3

- libs/libdeflate/Makefile
Compile tested: kirkwood, ZyXEL NSA-310b and NSA-325v2, OpenWrt v20.05.5
Run tested: kirkwood, ZyXEL NSA-310b and NSA-325v2, OpenWrt v20.05.5, tests done
Description: fixes complie issues under kirkwood platform.
`libdeflate` is a dependency of the `transmission` package, so it was broken on the platform until this update.
Reference: #23626
> libdeflate: update to 1.22 (backport)

- net/tailscale/Makefile
> tailscale: update to 1.78.1

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | n/a | OpenWrt SNAPSHOT ~r28146-52b6c92479~ r28146-52b6c92479 |
- Supersedes: https://github.com/openwrt/packages/pull/25425
- Changelog:
- [v0.34.0](https://github.com/netbirdio/netbird/releases/tag/v0.34.0)
- [v0.34.1](https://github.com/netbirdio/netbird/releases/tag/v0.34.1)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.31.0...v0.34.1
`x86_64` running as container with …
> netbird: update to 0.34.1

- net/ksmbd-tools/Makefile
- net/ksmbd-tools/files/ksmbd.conf.template
- net/ksmbd-tools/files/ksmbd.init
Compile tested: mediatek/filogic MT6000
Run tested: mediatek/filogic MT6000
Description of pull request:
Now for all devices with every size of RAM it is set to: `smb2 max read = 64K`
`smb2 max write = 64K`
`smb2 max trans = 64K`
Instead of fixed value to 64K is better to check RAM size and adjust to:
32 ~ 64MB RAM, set the value to 64K
64 ~ 128MB, set it to 128KB
128 ~ 256MB, set it to 1MB
More than 256MB leave default size to 4MB
With 64MB and 128MB is better also to disable the read/write cache `cache read buffers = no`
`cache write buffers = no`
> ksmbd-tools: adjust smb2 max read/write/trans and cache

- lang/python/python-orjson/Makefile
Relevant changes since previous 3.10.0:
Fixed:
- Serializing numpy.ndarray with non-native endianness raises orjson.JSONEncodeError.
- Fix int serialization on 32-bit Python 3.8, 3.9, 3.10. This was introduced in 3.10.8.
Changed:
- Improve performance of serializing.
- Drop [testing workflow] support for arm7.
- int serialization no longer chains OverflowError to the the __cause__ attribute of orjson.JSONEncodeError when range exceeded.
Maintainer: me
Compile tested:  arm_cortex-a9_vfpv3-d16, Linksys WRT1900ACS, master and aarch64_cortex-a72 just to make sure arm7 worked.
Run tested: arm_cortex-a9_vfpv3-d16, Linksys WRT1900ACS, 23.05.0 r23497-6637af95aa
Description:
Updates python-orjson from 3.10.0 -> 3.10.12
> python-orjson: update to version 3.10.12

- net/netbird/Makefile
- Add myself as maintainer
- Remove `Oskari Rauta <oskari.rauta@gmail.com>`
For the past few months, I have been updating, testing, and occasionally assisting people (both publicly, as seen in at https://github.com/netbirdio/netbird/issues/2268, and privately) with `netbird`. Unfortunately, the original maintainer, @oskarirauta, has been absent for several months, and @hnyman has commented on this here: https://github.com/openwrt/packages/pull/25425#issuecomment-2496006348.
To be honest, I am not an expert in Go or OpenWrt code, but I believe it's better to have someone involved than no one at all. With time and more experience, I have plans for `netbird`, which needs more love, such as UCI integration.
> netbird: change maintainer

- lang/python/python-requests/Makefile
Maintainer: @commodo @BKPepe 
Description:
Add hostbuild directives for `python-requests`.
~Draft for now~, requisite upon #25495 #25496 #25497 #25498 
This package is a host-requirement for PlatformIO and projects which depend on PlatformIO, including the [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic) project.
> python-requests: add hostbuild

- net/acme-common/Makefile
- net/acme-common/files/acme.init
The challenge directory (for webroot challenges) is on a tmpfs, which means it
doesn't exist on boot. @mipopa reported that some web servers (uhttpd in
particular) don't like being configured to serve files from a non-existent
directory. So add a boot() section to the ACME init script that just creates the
challenge directory, and make sure it runs relatively early. That should take
care of the non-existent directory issue, while still keeping the actual
certificate renewal controlled by cron.
-------
Maintainer: me
Compile tested: No
Run tested: No
> acme-common: Create challenge directory on boot

- net/wfb-ng/Makefile
- net/wfb-ng/files/wfb-ng.init
Maintainer: me
Compile tested: (MIPS 74Kc, TP-Link CPE510, openwrt-23.05)
Run tested: (MIPS 74Kc, TP-Link CPE510, tests done)
Description:
WFB-ng is long-range packet radio link based on raw WiFi radio.
Adding it to openwrt base packages will help a lot of it users to use cheap wifi routers (supporting minitoring mode) instead of build custom hardware yourself.
> wfb-ng: Add wfb-ng package

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v3.0.7

- utils/qemu/Makefile
Maintainer:@yousong
Compile tested: x86,x86_64, OpenWrt SNAPSHOT
Description:
qemu need a recent version of python build , this is visible when you build with the docker image of the sdk see https://github.com/openwrt/docker/
error generated during the build : `found no usable tomli, please install it`
> qemu: fix error on python dependency at build

- utils/lrzsz/Makefile
- utils/lrzsz/patches/300-neutralize-autofoo.patch
Maintainer: @kuoruan, Cc: @dhewg 
Run tested: Not yet
Description:
Currently we're seeing random build failures, caused by autofoo being called on very ancient bundled autofoo:
```shell
cd . && aclocal
aclocal.real: warning: autoconf input should be named 'configure.ac', not 'configure.in'
acinclude.m4:2: warning: underquoted definition of AC_REPLACE_GNU_GETOPT
acinclude.m4:2:   run info Automake 'Extending aclocal'
acinclude.m4:2:   or see https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
configure.in:106: error: automatic de-ANSI-fication support has been removed
```
For some reason that `touch` based neutralization introduced in commit 6d6c4b21b5e2 ("lrzsz: update to v0.12.21rc and fix a CVE") doesn't always work.
So lets fix it by …
> lrzsz: fix random build failures by really disabling autofoo

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> [openwrt-24.10] haproxy: update to v3.0.7

- utils/qemu/Makefile
Maintainer:@yousong
Compile tested: x86_64, OpenWrt SNAPSHOT & 24.10-rc2-SNAPSHOT
Run tested: Openwrt x86 VM on Promox x86_64
Description:
allow to build qemu-ga & virtio-console-helper on x86 target .
> qemu: add build for qemu-ga & virtio-console-helper on x86 target

- net/knxd/Makefile
- net/knxd/patches/0100-version.patch
- net/knxd/patches/0110-tcptunserver.patch
Maintainer: me
Description:
new upstream release 0.14.68
> knxd: bump to version 0.14.68

- lang/python/python-pyserial/Makefile
Description:
Add hostbuild directives for `python-pyserial`.
This package is a host-requirement for PlatformIO and projects which depend on PlatformIO, including the [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic) project.
> python-pyserial: add hostbuild

- lang/python/python-pyelftools/Makefile
Maintainer: me
Description:
This package is a host requirement for the PlatformIO build program, currently packaged at the [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic) project.
> python-pyelftools: add package / hostbuild

- utils/lrzsz/Makefile
- utils/lrzsz/patches/300-neutralize-autofoo.patch
(cherry picked from commit https://github.com/openwrt/packages/commit/3e612586041d40ebfafadb65eaa6fc34b2061ee8)
Maintainer: @kuoruan, Cc: @dhewg 
Run tested: Not yet
Description:
Currently we're seeing random build failures, caused by autofoo being called on very ancient bundled autofoo:
```shell
cd . && aclocal
aclocal.real: warning: autoconf input should be named 'configure.ac', not 'configure.in'
acinclude.m4:2: warning: underquoted definition of AC_REPLACE_GNU_GETOPT
acinclude.m4:2:   run info Automake 'Extending aclocal'
acinclude.m4:2:   or see https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
configure.in:106: error: automatic de-ANSI-fication support has been removed
```
For some reason that `touch` based neutralization introduced …
> [24.10] lrzsz: fix random build failures by really disabling autofoo

- utils/lrzsz/Makefile
- utils/lrzsz/patches/300-neutralize-autofoo.patch
(cherry picked from commit 3e612586041d40ebfafadb65eaa6fc34b2061ee8)
Maintainer: @kuoruan, Cc: @dhewg 
Run tested: Not yet
Description:
Currently we're seeing random build failures, caused by autofoo being called on very ancient bundled autofoo:
```shell
cd . && aclocal
aclocal.real: warning: autoconf input should be named 'configure.ac', not 'configure.in'
acinclude.m4:2: warning: underquoted definition of AC_REPLACE_GNU_GETOPT
acinclude.m4:2:   run info Automake 'Extending aclocal'
acinclude.m4:2:   or see https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
configure.in:106: error: automatic de-ANSI-fication support has been removed
```
For some reason that `touch` based neutralization introduced in commit 6d6c4b21b5e2 ("lrzsz: update to …
> [23.05] lrzsz: fix random build failures by really disabling autofoo

- libs/libulfius/Makefile
Depends on PR for liborcania:
- #25526
Maintainer: @utoni -- adding myself as a maintainer as well.
Description:
The current liborcania / libulfius packages do not install to the target, resulting in messages like:
```
Package meshtasticd is missing dependencies for the following libraries:
liborcania.so.2.3
libulfius.so.2.7
```
This change corrects the issue by installing the library `.so`s to the target.
> libulfius: Install library on target

- lang/python/python-click/Makefile
Description:
Add hostbuild directives for `python-click`.
This package is a host-requirement for building projects with PlatformIO, including the [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic) project.
> python-click: add hostbuild

- lang/python/python-tabulate/Makefile
Maintainer: me
Description:
This package is a host requirement for the PlatformIO build program (used for text output). Additionally, it is consumed as a target package by [meshtastic](https://github.com/meshtastic/python). Currently packaged at the [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic) project.
> python-tabulate: add package / hostbuild

- libs/abseil-cpp/Makefile
- libs/abseil-cpp/patches/001-absl-always-use-asm-sgidefs.h.patch
- libs/abseil-cpp/patches/002-Remove-maes-option-from-cross-compilation.patch
- libs/abseil-cpp/patches/003-Remove-neon-option-from-cross-compilation.patch
- libs/abseil-cpp/patches/004-abseil-ppc-fixes.patch
- libs/abseil-cpp/patches/005-Don-t-match-Wnon-virtual-dtor-in-the-flags-are-neede.patch
Maintainer: me
- OpenWRT One master/snapshot (local)
- CI at [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic/actions/runs/12367901614)
Description:
Adds new package `abseil-cpp`. This is a dependency for many Google C libraries / projects. Notably `protobuf` >= 22.x, but also: gRPC, tensorflow, and many others.
Pre-requisite in order to update the `protobuf` package.
https://protobuf.dev/support/migration/#abseil
> abseil-cpp: Add package

- lang/python/python-pypubsub/Makefile
Maintainer: me
- OpenWRT One master/snapshot (local)
- CI at [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic/actions/workflows/multi-arch-build.yml)
Description:
Add `PyPubSub` package.
https://pypi.org/project/PyPubSub/
https://github.com/schollii/pypubsub
> Provides a publish-subscribe API to facilitate event-based or message-based architecture in a single-process application. It is pure Python and works on Python 3.3+.
This is a runtime requirement for [`python-meshtastic`](https://github.com/openwrt-meshtastic/openwrt-meshtastic/blob/main/python-meshtastic/Makefile), packaged at [`openwrt-meshtastic`](https://github.com/openwrt-meshtastic/openwrt-meshtastic).
This package intentionally does not publish source tarballs to PyPI :roll_eyes:. …
> python-pypubsub: Add package

- net/pbr/Makefile
Maintainer: me
Description:
* update to 1.1.8 release version
* APK-style version stamping for init script
> pbr: update to 1.1.8

- net/pbr/Makefile
Maintainer: me
Description:
* update to 1.1.8 release version
* APK-style version stamping for init script
> [24.10] pbr: update to 1.1.8

- utils/lxc/Makefile
No patches needed to be rebased/simple version bump.
> lxc: update to 6.0.3

- net/net-snmp/patches/200-add-pcre2-support.patch
Compile tested: armv7, imx/cortexa7, OpenWrt 23.05
Description:
200-add-pcre2-support.patch uses `#elif defined` 9 times and `#elifdef` twice.
Maybe we can change those two `#elifdef` to `#elif defined` so that it is more consistent and more permissive to GCC 11?
> net-snmp: support compilation with GCC 11 permissively

- libs/libyder/Makefile
Maintainer: me
Description:
New package, `libyder`. See: [babelouest/yder](https://github.com/babelouest/yder)
`yder` is a build dependency for the `meshtasticd` web interface, currently packaged at the [openwrt-meshtastic](https://github.com/openwrt-meshtastic/openwrt-meshtastic) project.
> libyder: add package

- utils/stress-ng/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/commit/d1e9c50d06a8cb618cb85ab489cbcccaec220636
Run tested:  x86 https://github.com/openwrt/commit/d1e9c50d06a8cb618cb85ab489cbcccaec220636
> stress-ng: bump to version 0.18.07

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.7.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.7.0
> lua-eco: update to 3.7.0

- lang/php8/patches/1030-loongarch64-support-for-fibers.patch
Maintainer: me
Compile tested: loongarch64
Run tested: -
Description:
This backported patch is required to fix the build for loongarch64: ...
... loongarch64-openwrt-linux-musl/bin/ld.bfd: Zend/zend_fibers.o: in function `zend_fiber_init_context': zend_fibers.c:(.text+0xb34): undefined reference to `getcontext' ... loongarch64-openwrt-linux-musl/bin/ld.bfd: zend_fibers.c:(.text+0xb38): undefined reference to `getcontext' ... loongarch64-openwrt-linux-musl/bin/ld.bfd: zend_fibers.c:(.text+0xb74): undefined reference to `makecontext' ... loongarch64-openwrt-linux-musl/bin/ld.bfd: zend_fibers.c:(.text+0xb78): undefined reference to `makecontext' ... loongarch64-openwrt-linux-musl/bin/ld.bfd: Zend/zend_fibers.o: in function `.L170': zend_fibers.c:(.text+0xe34): undefined reference to …
> php8: add patch for loongarch64 support

- utils/bcm27xx-eeprom/Makefile
Maintainer: me
Run tested: bcm27xx/bcm2712 (RPi 5)
Description:
Update bcm27xx-eeprom to v2024.11.12-2712
bcm2711:
https://github.com/raspberrypi/rpi-eeprom/blob/v2024.11.12-2712/firmware-2711/release-notes.md#2024-10-10-use-soft-reset-to-preseve-sdram-contents-after-ramoops-latest
https://github.com/raspberrypi/rpi-eeprom/blob/v2024.11.12-2712/firmware-2711/release-notes.md#2024-10-21-fix-pcie-bar-issue-for-some-switches--latest
bcm2712:
https://github.com/raspberrypi/rpi-eeprom/blob/v2024.11.12-2712/firmware-2712/release-notes.md#2024-10-10-add-support-to-override-the-boot-mode-at-power-on-latest
https://github.com/raspberrypi/rpi-eeprom/blob/v2024.11.12-2712/firmware-2712/release-notes.md#2024-10-21-fix-pcie-bar-issue-for-some-switches--latest …
> bcm27xx-eeprom: update to v2024.11.12-2712

- libs/libwebp/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/commit/d1e9c50d06a8cb618cb85ab489cbcccaec220636
Run tested:  x86 https://github.com/openwrt/commit/d1e9c50d06a8cb618cb85ab489cbcccaec220636
> libwebp: bump to version 1.5.0

- utils/imx-uuc/Makefile
Maintainer: me
Description:
This adds two small tools useful only on the Freescale/NXP i.MX23/28 devices, so it is bound to the mxs target:
- sdimage: helper to write the required header for the bootstream, e.g. during bootloader update
- ufb: can be used in conjunction with NXP's host side mfgtool
> imx-uuc: add package 'sdimage' and 'ufb'

- libs/libfmt/Makefile
Maintainer: me
Run tested: ath79, tp-link Archer C7 v4, trunk, compiled with knxd package
Description:
new upstream release 11.1.1
> libfmt: bump to version 11.1.1

- net/knxd/Makefile
Maintainer: me
Description:
add dependency because upstream introduced support for inih
> knxd: add dependency for inih

- net/wget/Makefile
Maintainer: me
Compile tested: mediatek/filogic
Run tested: Openwrt One
Description:
Fix #25625. Update wget-ssl and wget-nossl using differet alternative priorities for /usr/bin/wget.
> wget: update alternative priority

- net/tgt/Makefile
Maintainer: me
Compile tested: aarch64_cortex-a53, qualcommax/ipq807x r28451+3-e0eca57b6e
Run tested: aarch64_cortex-a53, qualcommax/ipq807x r28451+3-e0eca57b6e in a chroot on r27697+4-d51353db26; an ext4 filesystem on a file-backed LUN works fine
Description:
> tgt: update to 1.0.94

- utils/lsof/Makefile
Maintainer: me
Compile tested: aarch64_cortex-a53, qualcommax/ipq807x r28451+3-e0eca57b6e
Run tested: aarch64_cortex-a53, qualcommax/ipq807x r28451+3-e0eca57b6e in a chroot on r27697+4-d51353db26; works as expectecd
> lsof: update to 4.99.4

- libs/boost/Makefile
Caintainer: @ClaymorePT 
Compile tested: openwrt-sdk-bcm27xx-bcm2712_gcc-13.3.0_musl.Linux-x86_64
Description:
This commit updates boost to version 1.87.0
New libraries in this release:
* Boost.Parser [2]: Framework for building parsers, from Zach Laine.
More info about Boost 1.87.0 can be found at the usual place [1].
[1]: https://www.boost.org/users/history/version_1_87_0.html
[2]: https://www.boost.org/libs/parser/
> boost: Updates package to version 1.87.0

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* rework hijack logic to redirect port 53 to the port of active/selected dnsmasq instances
> adblock-fast: Makefile bugfixes and hijack rework

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* rework hijack logic to redirect port 53 to the port of active/selected dnsmasq instances
> [24.10] adblock-fast: Makefile bugfixes and hijack rework

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* rework hijack logic to redirect port 53 to the port of active/selected dnsmasq instances
> [23.05] adblock-fast: Makefile bugfixes and hijack rework

- net/pbr/Makefile
> [24.01] pbr: Makefile bugfixes

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r28146-52b6c92479 |
**Tests Performed:**
- Changelog:
- [v0.35.2](https://github.com/netbirdio/netbird/releases/tag/v0.34.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.35.1...v0.35.2
Compiled package with container [`sdk`](https://github.com/openwrt/docker), and build `openwrt` image with …
> netbird: update to 0.35.2

- utils/cpupower/Makefile
Linux kernel userspace tool to examine and to tune power saving related features of the processor
> cpupower: add new package

- net/natmap/Makefile
Compile tested: x86_64, snapshot; ramips-mt7621, 23.05
Description:
1. Update to 20250101.
> natmap: update to 20250101

- net/natmap/Makefile
Compile tested: ramips-mt7621, 24.10
Run tested: ramips-mt7621, 24.10
Description:
1. Update to 20250101.
> [24.10] natmap: update to 20250101

- net/natmap/Makefile
Compile tested: ramips-mt7621, 23.05
Description:
1. Update to 20250101.
> [23.05] natmap: update to 20250101

- mail/opendkim/Makefile
- mail/opendkim/patches/030-gcc14.patch
> opendkim: fix compilation with GCC14

- net/croc/Makefile
Maintainer: me
Run tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt snapshot, simple file transfer
Release notes:
10.1.2: https://github.com/schollz/croc/releases/tag/v10.1.2
10.1.3: https://github.com/schollz/croc/releases/tag/v10.1.3
10.2.0: https://github.com/schollz/croc/releases/tag/v10.2.0
10.2.1: https://github.com/schollz/croc/releases/tag/v10.2.1
> croc: update to 10.2.1

- utils/eza/Makefile
Maintainer: me
Run tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt snapshot, simple run test with basic options
Release notes:
0.20.11: https://github.com/eza-community/eza/releases/tag/v0.20.11
0.20.12: https://github.com/eza-community/eza/releases/tag/v0.20.12
0.20.13: https://github.com/eza-community/eza/releases/tag/v0.20.13
0.20.14: https://github.com/eza-community/eza/releases/tag/v0.20.14
0.20.15: https://github.com/eza-community/eza/releases/tag/v0.20.15
> eza: update to 0.20.15

- utils/cpupower/Makefile
Maintainer: @graysky2 
Run tested: -
Description:
The initial idea was to have the new package in the existing category, not to create a new one.
Thanks @anomeome for spotting this.
> cpupower: fix category 'utils' -> 'utilities'

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/share/ddns/default/joker.com.json
The existing endpoint can handle IPv6 addresses as well.
I am currently using a `custom` configuration with the settings from this PR to update my IPv6 address.
> [ddns] Support IPv6 for joker.com

- net/bind/Makefile
Compile tested: OpenWRT 24.10 rc5 / malta
Run tested: OpenWRT 24.10 rc5 / malta (manual functional testing
Description:
Latest stable bind 9 release
> bind: bump to 9.20.4

- net/bind/Makefile
Maintainer: me
Compile tested: 23.05/mvebu
Run tested: 23.05/mvebu (basic manual functional testing, `dig` queries against local instance, etc)
Description:
Latest stable release in the 9.18.x branch
> bind: bump to 9.18.32

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.32.2)
> docker-compose: Update to version 2.32.2

- admin/muninlite/Makefile
- admin/muninlite/patches/001-ntpdate-fix-typo-on-graph-title.patch
- admin/muninlite/patches/002-plugin-ntpdate-tolerate-multiple-NTP-servers-e.g.-in.patch
- admin/muninlite/patches/003-Improve-df.patch
- admin/muninlite/patches/004-Fix-previous-change.-The-key-for-config-and-values-w.patch
- admin/muninlite/patches/100-netstat-drop-netstat-s-dep-by-using-proc-net-snmp-da.patch
- admin/muninlite/patches/200-Allow-customizing-the-list-of-monitored-network-inte.patch
- admin/muninlite/patches/201-Add-examples-for-config-with-INTERFACE_NAMES_OVERRID.patch
- admin/muninlite/patches/202-Fix-parameter-not-set-error.patch
- admin/muninlite/patches/203-Make-example-more-portable.patch
- admin/muninlite/patches/204-Remove-example-code-as-requested.patch
Maintainer: Jonathan McCrohan (@jmccrohan)
Compile tested: ramips_mt7621/netgear_wac124
Run tested: ramips_mt7621/netgear_wac124
Description:
The entire /etc/munin should be backed up as it includes user configuration for custom plugins and the muninlite.conf config file which is useful to override the default NTP server.
Also we install muninlite.conf to /etc/munin/.
> muninlite: add /etc/munin to conffiles and install muninlite.conf

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/share/ddns/default/ipv64.net.json
- net/ddns-scripts/files/usr/share/ddns/list
Adds ipv64.net service as DDNS provider
Docs: https://ipv64.net/dyndns_updater_api
> ddns-scripts: add support for ipv64.net

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_dnspod_cn_v3.sh
- net/ddns-scripts/files/usr/share/ddns/default/dnspod.cn-v3.json
Maintainer: FriesI23 Qin / @FriesI23 
Compile tested: should be universal, Debian 12, OpenWrt 23.05.05
Run tested: i386_pentium4, vm on proxmox 8.3 using [openwrt.sh][openwrt.sh], OpenWrt 23.05
Also tested: aarch64_generic, NanoPi R4S, OpenWrt 23.05.04
Description:
ddns-scripts: add support for dnspod.tencentcloudapi.com (aka: dnspod.cn) API v3
> This script copy from [FriesI23/ddns-scripts_tencent_cloud](https://github.com/FriesI23/ddns-scripts_tencent_cloud) which I maintain.
[openwrt.sh]: https://github.com/tteck/Proxmox/raw/main/vm/openwrt.sh
> ddns-scripts: Add dnspod.cn-v3

- net/vsftpd/Makefile
- net/vsftpd/files/vsftpd.init
- net/vsftpd/files/vsftpd.uci
* update UCI to use the traditional vsftpd.conf so that people migrating from non-uci version do not face problems
* if secure_chroot_dir is not provided specifically, then create an empty directory where vsftpd usually expects it
Signed-off-by: Mohd Husaam Mehdi <husaam.mehdi@iopsys.eu>
> vsftpd: handle migration and fix secure_chroot_dir error

- devel/cargo-c/Makefile
Compile tested: aarch64, main
Description: Version bump to keep it in sync with cargo so packages using the new resolver would work fine.
> cargo-c: Version bump

- net/acme-acmesh/Makefile
New upstream release with mostly minor fixes.
Fixes https://github.com/openwrt/packages/issues/24262
> acme-acmesh: Bump to v3.1.0

- libs/liburcu/Makefile
- libs/liburcu/patches/010-no-tests.patch
Description:
- update of the library `knot` depends on
> liburcu: update to version 0.15.0

- net/transmission/Makefile
Have no idea why such dependency was added.
No documentation from transmission that they need
such dependency on build time. On the other hand
saves vast of time during build
Description:
> transmissision: remove build dependency on nodejs

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_cloudflare_com_v4.sh
- net/ddns-scripts/files/usr/share/ddns/default/ipv64.net.json
Maintainer: me
Compile tested: none, shell-only
Run tested: mediatek/mt7622, aarch64_cortex-a53, Linksys E8450 (UBI), SNAPSHOT r0-285bdd2, tested updating A record to the current IPv4 address
Description:
Use the PATCH method which is the intended way to update an existing record with the cloudflare API, and update the "content" (rdata) only, that is, the IP address, leaving any other existing details intact.
In particular this removes the hard-coded 120 second TTL overriding the existing value set at cloudflare.
> ddns-scripts: cloudflare: use PATCH method, minimize changes

- net/rsync/Makefile
Changelog: https://download.samba.org/pub/rsync/NEWS#3.4.0
> rsync: update to 3.4.0

- lang/lua-ffi/Makefile
Maintainer: me
Description:
Release notes for 1.1.0: https://github.com/zhaojh329/lua-ffi/releases/tag/v1.1.0
> lua-ffi: update to 1.1.0

- net/sing-box/Makefile
Description:
sing-box: update to 1.10.7
For more information, visit https://github.com/SagerNet/sing-box/compare/v1.9.7...v1.10.7
> sing-box: Update to 1.10.7

- net/openvpn/Makefile
Compile tested: mediatek/mt7622, ramips/mt7621, ramips/mt7620, ramips/mt76x8, 
Run tested: Xiaomi Redmi AX6s, Beeline Smartbox Turbo+, Xiaomi Mi router R3, TP-Link MR-3020 v3
Feature changes:
- on non-windows clients (MacOS, Linux, Unix) send "release" string from uname() call as IV_PLAT_VER to server
- Windows: protect cached username, password and token in client memory
- Windows: use new API to get dco-win driver version from driver
- Linux: pass --timeout=0 argument to systemd-ask-password, to avoid default timeout of 90 seconds
Security fixes:
- improve server-side handling of clients sending usernames or passwords longer than USER_PASS_LEN
Notable bug fixes:
- FreeBSD DCO: fix memory leaks in nvlist handling
- purge proxy authentication credentials …
> openvpn: update to 2.6.13

- net/antiblock/Makefile
- net/antiblock/files/etc/config/antiblock
- net/antiblock/files/etc/init.d/antiblock
- net/antiblock/test.sh
Maintainer: me
Compile tested: ASUS RT-AX59U 23.05.5, ASUS RT-AX53U 23.05.5, OpenWrt x86
Run tested: ASUS RT-AX59U 23.05.5, ASUS RT-AX53U 23.05.5, OpenWrt x86
Description:
AntiBlock program proxies DNS requests. The IP addresses of the specified domains are added to the routing table for routing through the specified interface.
> antiblock: add new package

- net/sing-box/Makefile
Description:
sing-box: update to 1.10.7(cherry picked from commit https://github.com/openwrt/packages/commit/996c1819e3c68e27783bc7ac081cfcd3dc75ea3b)
For more information, visit https://github.com/SagerNet/sing-box/compare/v1.9.7...v1.10.7
> [24.10]sing-box: Update to 1.10.7

- net/sing-box/Makefile
Description:
sing-box: update to 1.10.7(cherry picked from commit https://github.com/openwrt/packages/commit/996c1819e3c68e27783bc7ac081cfcd3dc75ea3b)
For more information, visit https://github.com/SagerNet/sing-box/compare/v1.9.7...v1.10.7
> [23.05]sing-box: Update to 1.10.7

- utils/docker-compose/Makefile
> docker-compose: Update to version 2.32.4

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r28146-52b6c92479 |
**Tests Performed:**
- Changelog:
- [v0.36.3](https://github.com/netbirdio/netbird/releases/tag/v0.36.3)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.35.2...v0.36.3
Compiled package with container [`sdk`](https://github.com/openwrt/docker), and build `openwrt` image with …
> netbird: update to 0.36.3

- utils/lpac/Makefile
- utils/lpac/files/lpac.sh
- utils/lpac/files/lpac.uci
Updated lpac to 2.2.1 and added support for custom ISD-R AIDs. This allows for a broader range of esim cards with non standard AIDs to be supported. See https://github.com/estkme-group/lpac/pull/181 for additional info.
Compile tested: ramips/mt7621 TP-Link MR600 v2 (EU) (24.10-rc5, snapshot)
Run tested: ramips/mt7621 TP-Link MR600 v2 (EU) (24.10-rc5, snapshot) Verified esim profile management with standard and non-standard AID cards
> lpac: update to 2.2.1, add support for custom ISD-R AID

- utils/syncthing/Makefile
- utils/syncthing/files/syncthing.conf
- utils/syncthing/files/syncthing.init
Update to 1.29.2 and Change logfile path from /etc/syncthing/syncthing log to /var/log/syncthing.log.
This utilizes tmpfs (memory-based storage) to prevent disk usage growth caused by log file accumulation during extended operation.
Benefits:
- Avoids storage saturation from excessive log growth.
- Aligns with best practices for temporary log management.
- For systems using flash storage (e.g., SSDs or eMMC), storing logs in tmpfs avoids flash memory wear caused by frequent writes to /etc/syncthing.
Maintainer: Paul Spooren [mail@aparcar.org](mailto:mail@aparcar.org), Van Waholtz [brvphoenix@gmail.com](mailto:brvphoenix@gmail.com)
Compile tested: x86-64（Ubuntu 24）, master(24.10-rc5)
Run tested: x86-64, master(24.10-rc5), it's running normally.
Description:
The current version is two years …
> syncthing: Update to 1.29.2 and Change logfile path

- net/vsftpd/Makefile
- net/vsftpd/files/vsftpd.init
* I had wrongly used config_get_bool for the option, so fixed it
* this also fixes the issue of /etc/init.d/vsftpd stop not working
Signed-off-by: Mohd Husaam Mehdi <husaam.mehdi@iopsys.eu>
> vsftpd: fix bug related to option conf_file

- net/mwan3/Makefile
- net/mwan3/files/usr/sbin/mwan3track
Compile tested: x86_64, 23.05.5
Description:
In cases where ICMP ECHO is blocked by the ISP or perhaps even just de-prioritized, there can be a lot of ping failures when the link is perfectly fine.  In such cases, doing a DNS query is much more reliable so add a link-test method to use nslookup to do a DNS query.
Also, fix a couple of small bugs in the nping method.
> mwan3: Add support for nslookup track method

- utils/zoneinfo/Makefile
Maintainer: me
Compile tested: TI OMAP3/4/AM33xx, default, OpenWRT master
Description:
This release contains the following changes:
Briefly:
Paraguay adopts permanent -03 starting spring 2024.
Improve pre-1991 data for the Philippines.
Etc/Unknown is now reserved.
Changes to future timestamps
Paraguay will stop changing its clocks after the spring-forward
transition on 2024-10-06, so it is now permanently at -03.
(Thanks to Heitor David Pinto and Even Scharning.)
This affects timestamps starting 2025-03-22, as well as the
obsolescent tm_isdst flags starting 2024-10-15.
Changes to past timestamps
Correct timestamps for the Philippines before 1900, and from 1937
through 1990.  (Thanks to P Chan for the heads-up and citations.)
This includes adjusting local mean time before …
> zoneinfo: Updated to 2025a release.

- net/git/Makefile
If PKG_FORTIFY_SOURCE is not 0 and lto is enabled for package git, git will fail to compile with the following example error:
/openwrt/staging_dir/toolchain-aarch64_generic_gcc-14.1.0_musl/include/stdio.h: In function 'process_curl_messages': /openwrt/staging_dir/toolchain-aarch64_generic_gcc-14.1.0_musl/include/stdio.h:90:8: error: inlining failed in call to 'always_inline' 'fwrite': function body can be overwritten at link time
90 | size_t fwrite(const void *__restrict, size_t, size_t, FILE *__restrict);
|        ^
http.c:355:33: note: called from here
355 |                                 fprintf(stderr, "Received DONE message for unknown request!\n");
|                                 ^
A related issue is openwrt/openwrt#13016 .
This commit set PKG_FORTIFY_SOURCE to 0 if …
> git: Set PKG_FORTIFY_SOURCE to 0 when lto enabled

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_dnspod_cn_v3.sh
Maintainer: FriesI23 Qin / @FriesI23
Compile tested: should be universal, Debian 12, OpenWrt 23.05.05
Run tested: i386_pentium4, vm on proxmox 8.3 using [openwrt.sh](https://github.com/tteck/Proxmox/raw/main/vm/openwrt.sh), OpenWrt 23.05
Also tested: aarch64_generic, NanoPi R4S, OpenWrt 23.05.04
Description:
- Migrate `retry_count` to `retry_max_count` in the script to fix infinite retry loop.
- Fix signature expiration issue during retries.
This script copy from [FriesI23/ddns-scripts_tencent_cloud](https://github.com/FriesI23/ddns-scripts_tencent_cloud) which I maintain.
> ddns-scripts: Update dnspod.cn-v3

- lang/node/Makefile
Compile tested: 23.05, aarch64, arm
Run tested: (qemu 9.2.0) aarch64
Description:
Update to 18.20.6
CVE-2025-23085 - src: fix HTTP2 mem leak on premature close and ERR_PROTO (Medium)
CVE-2025-23084 - path: fix path traversal in normalize() on Windows (Medium)
Dependency update:
CVE-2025-22150 - Use of Insufficiently Random Values in undici fetch() (Medium)
> [23.05] node: January 21, 2025 Security Releases

- net/hev-socks5-tproxy/Makefile
Maintainer: me
Description: update to 2.6.0
> hev-socks5-tproxy: update to 2.6.0

- net/hev-socks5-server/Makefile
> hev-socks5-server: update to 2.7.0

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | QEMU (x86_64) | qemu-system-x86_64 | qemu-9.1.2-2.fc41 | OpenWrt 24.10-SNAPSHOT r28361-3207fe6636 |
**Tests Performed:**
- Changelog:
- Change maintainer:
- Add myself as maintainer
- Remove `Oskari Rauta <oskari.rauta@gmail.com>`
- Cherry picked from 2594fc3e2ebdba785dca3ac3ccf944359c8eb5b1
- PR #25540
- Partially revert: 7b3d033ab651dd11e0db5fb099d106c9e09a2dc6
- Revert: Also fixes issue of not being able to build with musl >1.2.4,
The issue has …
> [24.10] netbird: update to 0.36.3, revert fix to build with musl >1.2.4 and change maintainer

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_cloudflare_com_v4.sh
- net/ddns-scripts/files/usr/lib/ddns/update_dnspod_cn.sh
- net/ddns-scripts/files/usr/lib/ddns/update_dnspod_cn_v3.sh
- net/ddns-scripts/files/usr/lib/ddns/update_godaddy_com_v1.sh
- net/ddns-scripts/files/usr/lib/ddns/update_luadns_v1.sh
If pppoe is used for wan access. script set 'eth1' as interface for curl call. The correct interface is however 'pppoe-wan'.
These scripts use 'network_get_physdev' function to get real device for bind_network but this is wrong. We need instead the l3_device of the the logical interface.
In case if we don't use pppoe connection - 'l3_device' is equal to real device.
Follow P/R:
#14431
And please backport to current stable version.
> ddns-scripts: get l3 device for bind network using curl

- net/nut/Makefile
Maintainer: @neheb (last pr/commit merger)
Compile tested: master branch / Turris Omnia (mvebu)
Run tested: Turris Omnia (mvebu)
Description:
I think the fact that nut_monitor is built by default might be a bug in NUT's configure. Anyway: nut_monitor is not used at all and is being needlessly built. Even worse, the build uses host system's python (not hostpkg python) and if that python is version 3.13, it breaks the build due to removed telnetlib.
> nut: add --without-nut_monitor to configure args

- net/coova-chilli/Makefile
- net/coova-chilli/patches/030-cyassl-renamed-to-wolfssl.patch
Maintainer: Jaehoon You, I can't find the related Github user.
Compile tested: (ramips, yuncore AX820, OpenWrt 24.10)
Run tested: (ramips, yuncore AX820, OpenWrt 24.10)
Description:
Compilation of this package with WolfSSL breaks due to referencing to the old Cyassl naming.
I created an issue upstream: https://github.com/coova/coova-chilli/issues/584, I suggest patching here first, probably the upstream code will need to be updated as well and then the patch can be removed.
> coova-chilli: Fix WolfSSL support

- net/hev-socks5-server/Makefile
Maintainer: me
Description: update to 2.6.9
> [24.10] hev-socks5-server: update to 2.6.9

- net/hev-socks5-server/Makefile
Maintainer: me
Compile tested: x86, 23.05
Run tested: x86, 23.05, tests done
Description: update to 2.6.9
> [23.05] hev-socks5-server: update to 2.6.9

- net/hev-socks5-tproxy/Makefile
Maintainer: me
Description: update to 2.5.8
> [24.10] hev-socks5-tproxy: update to 2.5.8

- net/openssh/Makefile
- net/openssh/files/sshd.init
Starting with OpenSSH 9.8 sessions are handled by a separate binary called sshd-session
Maintainer: @graysky2 
Description:
Without this fix open sessions are not killed on shutdown since the name of the binary has changed.
> openssh: fix killing of active sessions on shutdown

- net/openssh/Makefile
- net/openssh/files/sshd.init
Imitate dropbear init.d-script and make sure we
don't end up with corrupt keys.
This can happen if we use a caching filesystem,
like 'ubifs', and the DUT is powered off during
boot-up.
> openssh: Validate keys and regenerate if needed.

- net/hev-socks5-server/Makefile
Maintainer: me
Compile tested: x86, 23.05
Run tested: x86, 23.05, tests done
> [23.05] hev-socks5-server: update to 2.7.0

- net/hev-socks5-server/Makefile
> [24.10] hev-socks5-server: update to 2.7.0

- net/hev-socks5-tproxy/Makefile
Maintainer: me
Description: update to 2.6.0
> [24.10] hev-socks5-tproxy: update to 2.6.0

- net/banip/Makefile
- net/banip/files/README.md
- net/banip/files/banip.feeds
Block HTTP/3 by including UDP in the feeds that have the 80 443 ports in their flag.
Maintainer: @dibdot 
Run tested: OpenWrt 24.10.0-rc2 r28161-ea17e958b9 on Linksys E8450 (UBI)
Description:
Block HTTP/3 in all feeds that select the HTTP ports.
Note that there's the caveat that it will block 80/udp too as the flag field is not expressive enough to include only 443/udp.
> banip: Block UDP ports for HTTP/3

- net/coova-chilli/Makefile
- net/coova-chilli/patches/030-cyassl-renamed-to-wolfssl.patch
Signed-off-by: Federico Capoano <f.capoano@openwisp.io>
(cherry picked from commit bf3333594a8add333e3d7192107aa7be8bc39a33)
Backporting https://github.com/openwrt/packages/pull/25821.
> [24.10] coova-chilli: Fix WolfSSL support

- net/coova-chilli/Makefile
- net/coova-chilli/patches/030-cyassl-renamed-to-wolfssl.patch
Signed-off-by: Federico Capoano <f.capoano@openwisp.io>
(cherry picked from commit bf3333594a8add333e3d7192107aa7be8bc39a33)
Backporting https://github.com/openwrt/packages/pull/25821.
> [23.05] coova-chilli: Fix WolfSSL support

- net/openssh/Makefile
- net/openssh/files/sshd.init
Run tested: -
Description:
The -r option is not required here but should also not hurt, since it was already tested, that $key is a file.
However, to express the intent of the command more clearly, let's drop it.
Suggested-by: @SibrenVasse in https://github.com/openwrt/packages/pull/25759#issuecomment-2613928718
> openssh: fix recursive key file removal

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/config/adblock-fast
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Description:
* bugfix: more robust boot-up start
* bugfix: processing of StevenBlack lists
* new remote block-list: CERT.pl
> [24.10] adblock-fast: bugfixes: boot-up, StevenBlack list, new CERT.pl source

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Description:
* improvement: Makefile: prepend `r` to PKG_RELEASE in binary and init script versions to match package version
* bugfix: init script: more reliable/robust start on boot
* improvement: init script: more compact output()
* improvement: init script: better DNS Hijack login
* improvement: init script: fold some dnsmasq-related functions into dhcp_backup()
> https-dns-proxy: bugfixes and improvements

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Description:
* improvement: Makefile: prepend `r` to PKG_RELEASE in binary and init script versions to match package version
* bugfix: init script: more reliable/robust start on boot
* improvement: init script: more compact output()
* improvement: init script: better DNS Hijack login
* improvement: init script: fold some dnsmasq-related functions into dhcp_backup()
> [24.10] https-dns-proxy: bugfixes and improvements

- libs/libdaq3/Makefile
Changelog: https://github.com/snort3/libdaq/releases/tag/v3.0.18
> libdaq3: update to 3.0.18

- net/bind/Makefile
Maintainer: me
Description:
Fixes CVEs:
- CVE-2024-12705: DNS-over-HTTPS flooding
- CVE-2024-11187: Limit additional section processing for large RDATA sets
> bind: bump to 9.20.5

- net/bind/Makefile
Maintainer: me
Description:
Fixes CVEs:
- CVE-2024-12705: DNS-over-HTTPS flooding
- CVE-2024-11187: Limit additional section processing for large RDATA sets
> bind: bump to 9.18.33

- utils/cryptsetup/Makefile
Maintainer: me
Run tested: -
Description:
Enable building cryptsetup-reencrypt, integritysetup and veritysetup, add new binary packages for integritysetup and veritysetup.
Changes since version 2.7.4
=================
* Fix possible online reencryption data corruption (only in 2.7.x).
In some situations (initializing a suspended device-mapper device), cryptsetup disabled direct-io device access. This caused unsafe online reencryption operations that could lead to data corruption. The code now adds strict checks (and aborts the operation) and changes direct-io detection code to prevent data corruption.
* Fix a clang compilation error in SSH token plugin.
As clang linker treats missing symbols as errors, the linker phase for the SSH token failed as the …
> cryptsetup: update to version 2.7.5

- net/tailscale/Makefile
> tailscale: update to 1.80.0

- net/sing-box/Makefile
Description:
sing-box: update to 1.11.0
For more information, visit https://github.com/SagerNet/sing-box/compare/v1.10.7...v1.11.0
> sing-box: Update to 1.11.0

- net/strongswan/Makefile
- net/strongswan/patches/0905-wolfssl-parse_error.patch
Compile tested: aarch_64_generic rockchip_armv6_friendlyarm_nanopi-r4s 24.10.0-rc7
Description: Backport https://github.com/strongswan/strongswan/commit/60336ceecbd1cda73aa26dd44cfdaf2e31a046e1 in order to address compile failure in 24.10.0-rc7 which was caused by wolfssl update. Closes #25877.
https://github.com/openwrt/openwrt/issues/17768
> Backport strongswan patch for wolfssl

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_digitalocean_com_v2.sh
Maintainer: me
Compile tested: Compile not tested
Run tested: Architecture: ARMv7 Processor rev 0 (v7l), Platform: ipq806x/generic, Model: Netgear Nighthawk XR500
Description:
DigitalOcean API requires a "type" JSON field to update a DNS record. This adds that while checking for IPv6 to change which record type to use. Without it, the API call fails, making the script unable to update the DNS records for DigitalOcean.
Fixes #25061
> ddns-scripts: add type field for digitalocean API

- net/sing-box/Makefile
Description:
sing-box: update to 1.11.1
For more information, visit https://github.com/SagerNet/sing-box/compare/v1.11.0...v1.11.1
> sing-box: Update to 1.11.1

- net/keepalived/Makefile
- net/keepalived/files/etc/hotplug.d/keepalived/810-files
- net/keepalived/files/lib/functions/keepalived/hotplug.sh
- net/keepalived/files/usr/share/keepalived/scripts/rsync.sh
Compile tested: not yet compiled
Run tested: only tested on v23.05.5 with manually modified files
Description:
This pull request adds support for folder synchronization
An example is in the 810-files file where it is explained how to synchronize all hotplug files of keepalived. Personally, I am currently using the scirpt for this exact purpose
> keepalived: add support for directory sync

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/share/ddns/default/ydns.io.json
- net/ddns-scripts/files/usr/share/ddns/list
Maintainer: @ACI0419
Description:
Add ydns.io provider.  
YDNS is a free and open-source DDNS service provider, with its project available on GitHub at https://github.com/ydns
> ddns-scripts: add ydns.io provider

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r28772-08ebb9e914 |
- Changelog:
- Update to [0.36.5](https://github.com/netbirdio/netbird/releases/tag/v0.36.5)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.36.3...v0.36.5
- N/A
---
The package(s) was compiled with the container …
> netbird: update to 0.36.5

- utils/prometheus-node-exporter-ucode/Makefile
- utils/prometheus-node-exporter-ucode/files/init
Maintainer: @dhewg
Run tested: OpenWrt 24.10.0-rc7, aarch64, mediatek/filogic, BPI-R4
Description:
There is a bug with this package currently where it fails to launch with this error
```
Sun Feb  2 23:35:49 2025 daemon.info uhttpd[4199]: jail: exec-ing /usr/sbin/uhttpd
Sun Feb  2 23:35:49 2025 daemon.err uhttpd[4199]: Runtime error: Unable to dlopen file '/usr/lib/ucode/uci.so': Error loading shared library libuci.so.20250120: No such file or directory (needed by /usr/lib/ucode/uci.so)
Sun Feb  2 23:35:49 2025 daemon.err uhttpd[4199]: In /usr/share/ucode/node-exporter/metrics.uc, line 2, byte 1:
Sun Feb  2 23:35:49 2025 daemon.err uhttpd[4199]:
Sun Feb  2 23:35:49 2025 daemon.err uhttpd[4199]:  `{%`
Sun Feb  2 23:35:49 2025 daemon.err uhttpd[4199]:     ^-- Near here …
```
> prometheus-node-exporter-ucode: fix missing .so mounts in jail

- net/snort3/Makefile
Changelog: https://github.com/snort3/snort3/releases/tag/3.6.3.0
Maintainer: me
> snort3: update to 3.6.3.0

- net/tailscale/Makefile
> [openwrt-24.10] tailscale: update to 1.80.0

- libs/ell/Makefile
Maintainer: me
Compile tested: aarch64/cortex-a53 (also tested mptcpd still builds)
Run tested: -
Description:
Upstream changes:
f99041d Release 0.71
19e448a test-rtnl: fix -std=c23 build failure
22a4388 dbus: fix -std=c23 build failure
65a5b0b cert: fix -std=c23 build failure
91bc3da settings: fix -std=c23 build failure
> ell: update to version 0.71

- utils/lsd/Makefile
Changes:
- rollback term grid to 0.1 
- use cache for user and group in unix, gain 60% improve
- fix lsd pipe output
- Fixed misaligned outputs and unicode-width dependency version
- add subtitle/closed caption icons
Full changelogs since v1.1.1:
- v1.1.2: https://github.com/lsd-rs/lsd/releases/tag/v1.1.2
- v1.1.3: https://github.com/lsd-rs/lsd/releases/tag/v1.1.3
- v1.1.4: does not exist
- v1.1.5:  https://github.com/lsd-rs/lsd/releases/tag/v1.1.5
Compile tested: x86_64, 24.10.x latest git
Run tested: x86_64, 24.10.x latest git
> lsd: update to latest stable/1.1.5

- utils/eza/Makefile
Maintainer: me
Run tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt snapshot, simple base function test
changelogs:
0.20.16: https://github.com/eza-community/eza/releases/tag/v0.20.16
0.20.17: https://github.com/eza-community/eza/releases/tag/v0.20.17
0.20.18: https://github.com/eza-community/eza/releases/tag/v0.20.18
0.20.19: https://github.com/eza-community/eza/releases/tag/v0.20.19
0.20.20: https://github.com/eza-community/eza/releases/tag/v0.20.20
> eza: update to 0.20.20

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v3.0.8

- libs/srt/Makefile
- No API/ABI changes
- Changelog: https://github.com/Haivision/srt/releases/tag/v1.5.4
Maintainer: me
Compile tested: imx6
Run tested: imx6
> libs/srt: bump to 1.5.4

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
Maintainer: me
Description:
* bugfix: working start on boot when interfaces are up (thanks @tmcqueen-materials and @b1ackbeat)
* improvement: better output when setting triggers on start
> https-dns-proxy: bugfix: start on boot

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
Maintainer: me
Description:
* bugfix: working start on boot when interfaces are up (thanks @tmcqueen-materials and @b1ackbeat)
* improvement: better output when setting triggers on start
> [24.10] https-dns-proxy: bugfix: start on boot

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/etc/uci-defaults/50-ddns-migrate-retry-count
- net/ddns-scripts/files/usr/lib/ddns/update_cloudflare_com_v4.sh
- net/ddns-scripts/files/usr/lib/ddns/update_dnspod_cn.sh
- net/ddns-scripts/files/usr/lib/ddns/update_godaddy_com_v1.sh
- net/ddns-scripts/files/usr/lib/ddns/update_luadns_v1.sh
- net/ddns-scripts/samples/ddns.config_sample
Maintainer: FriesI23 Qin / @FriesI23
Compile tested: should be universal, Debian 12, OpenWrt 23.05.05
Run tested: i386_pentium4, vm on proxmox 8.3 using [openwrt.sh](https://github.com/tteck/Proxmox/raw/main/vm/openwrt.sh), OpenWrt 23.05
> I don’t have accounts for these providers, so only tested whether scripts listed below can read new var (`retry_max_count`).
Description:
Finish work from "e3292e4" by change remaining `retry_count` to `retry_max_count`. 
[ddns-scripts: rename variable: s/retry_count/retry_max_count/](https://github.com/openwrt/packages/commit/e3292e4c9766e823ed38160390248dbc61f69c82)
---
> DDns Scripts: Rename 'retry_count' to 'retry_max_count' in custom scripts and sample config

- net/keepalived/Makefile
- net/keepalived/files/keepalived.init
Run tested: only generation of new section
refs https://github.com/openwrt/luci/issues/7475
Description:
If an interface that is being used (or tracked) by a VRRP instance goes to down state, the VRRP instance(s) will, by default, immediately transition to FAULT state, and when all relevant interfaces are back up again the VRRP instance(s) will immediately transition to BACKUP state.
This can cause problems if interfaces are bouncing, and so delays can be specified between the interface state change and the transition to FAULT/BACKUP state. If the interface returns to its original state before the delay expires, no associated VRRP instance state transition will occur.
New uci section 'interface_up_down_delay':
```
config …
```
> keepalived: add new uci section config interface_up_down_delays

- sound/owntone/Makefile
Maintainer: me
Compile tested: x86_64, trunk
Run tested: x86_64, trunk, server initialization tested
Description:
Since version 28.10, OwnTone uses libxml2 instead of mxml, so DEPENDS changed in the Makefile
> owntone: update to 28.11

- net/acme-common/Makefile
- net/acme-common/files/acme.uci-defaults
acme.sh uses `/var/run/acme/challenge/` as a root of webserver, and automaticly create there `.well-known/acme-challenge` while acme request is in progress.
Now webroot method should works with no need of any additional config.
> acme-common: Resolve problem with webroot symlink

- net/adguardhome/Makefile
- net/adguardhome/files/adguardhome.config
- net/adguardhome/files/adguardhome.init
Maintainer: @dobo90 @1715173329
Compile tested: working on it
Description:
> adguardhome: Bump to 0.107.56

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.33.0)
> docker-compose: Update to version 2.33.0

- net/rsync/Makefile
Description:
backport rsync updates to openwrt 24.10 branch.
cc @graysky2
> [openwrt-24.10] rsync: update to 3.4.1

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> [openwrt-24.10] haproxy: update to v3.0.8

- net/adguardhome/Makefile
- net/adguardhome/files/adguardhome.config
- net/adguardhome/files/adguardhome.init
Maintainer: @dobo90 @1715173329
Compile tested: NanoPi R6S 24.10.0
Run tested: NanoPi R6S 24.10.0
Description: Backport/cherry-pick of PR#25521 authored by @Ra2-IFV (Bump last AdGuard Home and go-lang) (resubmitting using "-x" in the cherry-pick).
> [24.10] adguardhome: Update to 0.107.56 (backport)

- net/https-dns-proxy/Makefile
- net/https-dns-proxy/files/etc/init.d/https-dns-proxy
Maintainer: me
Description:
* No more `/sbin/uci: Invalid argument output` when set to not update dnsmasq instances (thanks @tmcqueen-materials for investigation!)
* Do not wait for interface.up on boot, hopefully this resolves the boot-up start for everyone
> https-dns-proxy: bugfixes

- net/tailscale/Makefile
Description:
----
TODO: backport to 24.10 with ``git-cherry-pick -x``
> tailscale: update to 1.80.2

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | QEMU (x86_64) | qemu-system-x86_64 | qemu-9.1.2-3.fc41 | OpenWrt 24.10-SNAPSHOT r28470-315facfce6 |
- Changelog:
- Update to [0.36.7](https://github.com/netbirdio/netbird/releases/tag/v0.36.7)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.36.3...v0.36.7
- Cherry picked from 7ff04e9e300431f4cc3debea424b00df13318e20
- PR [#25782](https://github.com/openwrt/packages/pull/25990)
- N/A
--- …
> [24.10] netbird: update to 0.36.7

- net/mwan3/Makefile
- net/mwan3/files/usr/sbin/mwan3
Maintainer: @feckert @aaronjg
Compile tested: OpenWrt 24.10.0, r28427-6df0e3d02a - turris
Run tested: OpenWrt 24.10.0, r28427-6df0e3d02a - turris
Description:
This redirects the debug output to stderr, allowing `mwan3 use` to be used in
scripts without polluting stdout.
Before:
```shell
mwan3 use wan6 curl -fsSL myip.wtf/json | jq -er '.YourFuckingCountryCode'
jq: parse error: Invalid numeric literal at line 1, column 8
curl: (23) Failure writing output to destination, passed 389 returned 0
```
After:
```shell
mwan3 use wan6 curl -fsSL myip.wtf/json | jq -er '.YourFuckingCountryCode'
Running 'curl -fsSL myip.wtf/json' with DEVICE=eth2 SRCIP=2a02:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx FWMARK=0x3f00 FAMILY=ipv6
DE
```
> mwan3: write `mwan3 use` error/debug messages to stderr instead of stdout

- utils/containerd/Makefile
- utils/docker/Makefile
- utils/dockerd/Makefile
- utils/runc/Makefile
- utils/tini/Makefile
Maintainer: me / @G-M0N3Y-2503 
Run tested: NA
Description:
Help detect when an update will break Docker building / running with unsupported dependency versions.
Examples:
* https://github.com/openwrt/packages/pull/25951
* https://github.com/openwrt/packages/pull/25952
* https://github.com/openwrt/packages/pull/25264
* https://github.com/openwrt/packages/pull/17310
> docker: CI reverse dependency version validation

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/share/ddns/default/dynu.com.json
Prevents IPv6 updates to also update IPv4 (undesirable when behind a CGNAT)
Compile tested: NanoPI R6S, OpenWrt 24.10.0
Run tested: NanoPI R6S, OpenWrt 24.10.0. Confirmed that after this change only IPv6 is updated in DynuDDNS.
Description: Prevents IPv6 updates to also update IPv4 (undesirable when behind a CGNAT)
> ddns-scripts: Add option 'myip=no' to Dynu IPv6 update URL

- net/arp-scan/Makefile
Maintainer: @urusha (recent changes have been made by @PolynomialDivision)
Compile tested: arch: x86, model: 64, OpenWrt version: 24.10.0
```sh
wget https://downloads.openwrt.org/releases/24.10.0/targets/x86/64/openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
tar -xvf openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
cd openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64/
cp feeds.conf.default feeds.conf
sed -i 2d feeds.conf
echo 'src-link packages /home/chris/git/github.com/cpswan/OpenWrt-packages' >> feeds.conf
./scripts/feeds update -a
./scripts/feeds install arp-scan
make V=s package/arp-scan/compile
find . -name *.ipk
python3 -m http.server
```
Run tested: arch: x86, model: 64, OpenWrt version: 24.10.0
```sh
opkg update
opkg install arp-scan
wget …
```
> arp-scan-database: Relocate mac-vendor.txt to /etc/arp-scan

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r28863-ab80e6c684 |
```
```
- Changelog:
- Update to [0.37.0](https://github.com/netbirdio/netbird/releases/tag/v0.37.0)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.36.7...v0.37.0
- N/A
--- …
> netbird: update to 0.37.0

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/etc/uci-defaults/50-ddns-migrate-retry-count
- net/ddns-scripts/files/usr/lib/ddns/update_cloudflare_com_v4.sh
- net/ddns-scripts/files/usr/lib/ddns/update_digitalocean_com_v2.sh
- net/ddns-scripts/files/usr/lib/ddns/update_dnspod_cn.sh
- net/ddns-scripts/files/usr/lib/ddns/update_dnspod_cn_v3.sh
- net/ddns-scripts/files/usr/lib/ddns/update_godaddy_com_v1.sh
- net/ddns-scripts/files/usr/lib/ddns/update_luadns_v1.sh
- net/ddns-scripts/files/usr/share/ddns/default/dnspod.cn-v3.json
- net/ddns-scripts/files/usr/share/ddns/default/dynu.com.json
- net/ddns-scripts/files/usr/share/ddns/default/ipv64.net.json
- net/ddns-scripts/files/usr/share/ddns/default/joker.com.json
- net/ddns-scripts/files/usr/share/ddns/default/ydns.io.json
- net/ddns-scripts/files/usr/share/ddns/list
Compile tested: NanoPI R6S, OpenWrt 24.10.0
Run tested: NanoPI R6S, OpenWrt 24.10.0.
Description: backport/chery pick latest ddns-scripts commits to 24.10 branch
Test environment (24.10.0 updated with 24.10 packages built with this PR):
```
-----------------------------------------------------
OpenWrt 24.10.0, r28427-6df0e3d02a
-----------------------------------------------------
root@router:~# opkg list-installed | grep ddns
ddns-scripts - 2.8.2-r64
ddns-scripts-services - 2.8.2-r64
luci-app-ddns - 25.049.66344~2b8e93c
```
> [24.10] ddns-scripts: backport updates to 24.10 branch

- net/phytool/Makefile
Add phytool, a very useful tool to access MDIO PHY registers.
Maintainer: me
Compile tested: stm32/stm32mp1, stm32mp135f-dk, main branch
Run tested: stm32/stm32mp1, stm32mp135f-dk, main branch, run phytool cmd
> phytool: add phytool package

- utils/lxc/Makefile
- utils/lxc/patches/025-remove-unsupported-option.patch
This commit contains two fixes.
The first add gnu-tar as a dependency for lxc-create which is needed to properly extract the root file system tarball. Without it, symlink target of /bin/tar is busybox and it lacks proper support to extract with xattrs.  The default gnu-tar is actually built without this support as well, but it is able to extract the rootfs tarballs with a warning not an error which is not the case with busybox which ends in an error.
The second is a fix to 025-remove-unsupported-option.patch which both removes bsdtar command as it ends in errors, see below, and circumvents an error when extracting to overlayfs[1].
Error when extracting rootfs tarball with bsdtar:
```
tar --absolute-names --numeric-owner '--xattrs-include=*' -xpJf …
```
> lxc: fix lxc-download

- lang/rust/Makefile
Fixes podman build breakage which was caused by podman depending on netavark, which in turn depends on rust-iptables.
rust-iptables requires rust 1.85.0 since commit 75825cd https://github.com/yaa110/rust-iptables/commit/75825cd9c13db91f697461e6fa91f78c5e927008
Compile tested: rockchip, snapshot
> rust: update to 1.85.0

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.33.1)
> docker-compose: Update to version 2.33.1

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r28898-e1acc7a67b |
```
```
- Changelog:
- Update to [0.37.1](https://github.com/netbirdio/netbird/releases/tag/v0.37.1)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.37.0...v0.37.1
- N/A
--- …
> netbird: update to 0.37.1

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* Properly detect domain lists, fixes https://github.com/openwrt/packages/issues/25973 Thanks @timfeierabend
* Better output when setting triggers
* No wait for ubus network.interface on boot
(cherry picked from commit 9b6d6ad61150c240b8cf04801fb26d0d2d8d3c0c)
> [24.10] adblock-fast: bugfix: detect_file_type()

- net/speedtest-go/Makefile
Update speedtest-go version to 1.7.10
Compile tested: MediaTek Ralink MIPS MT7621 based boards ZTE E8820S OpenWrt SNAPSHOT r28146+1-52b6c92479 / LuCI Master 24.326.01848
Run tested: MediaTek Ralink MIPS MT7621 based boards ZTE E8820S OpenWrt SNAPSHOT r28146+1-52b6c92479 / LuCI Master 24.326.01848
Description: Update speedtest-go package, a CLI with go to test internet speed
> speedtest-go: update to 1.7.10

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_huaweicloud_com.sh
Compile tested: RAX300M
Run tested: RAX300M
Description:
Script will exit when an error occurred.
> ddns-scripts: Fixup huaweicloud

- net/nginx/Makefile
- net/nginx/patches/nginx-mod-njs/104-endianness_fix.patch
Compile tested: x86_64, main
Description:
Currently, we are using Download recipes to download the various modules,
however we are using then with PROTO:=git but SOURCE_VERSION is not set,
only VERSION variable so thus the dl_github_archive.py scripts gets called
with --version="" instead of being actually passed the desired commit hash
and thus actually the git head is fetched.
This explains why currently buildbots are failling with
nginx-mod-njs/104-endianness_fix.patch failling to apply since buildbots
are using prepackaged tarballs which are different than what we get when
manually building.
So, lets set SOURCE_VERSION to make sure we actually fetch the desired
git commit hash.
> nginx: actually fix patch issue

- net/gateway-go/Makefile
Signed-off-by: Yu Fang <yu@iotserv.com>
Maintainer: @IoTServ 
Compile tested: x86-64, OpenWrt master
Run tested: x86-64, OpenWrt master
Description:
upgrade version
> gateway-go: update to 0.3.16

- net/hev-socks5-server/Makefile
Maintainer: me
Description: update to 2.8.0
> hev-socks5-server: update to 2.8.0

- net/hev-socks5-tproxy/Makefile
> hev-socks5-tproxy: update to 2.7.0

- net/hev-socks5-tunnel/Makefile
Maintainer: me
Description: update to 2.9.1
> hev-socks5-tunnel: update to 2.9.1

- net/tgt/Makefile
Maintainer: me
Compile tested: aarch64_cortex-a53, Dynalink DL-WRX36, r28926+3-9a7192c08e
Run tested: aarch64_cortex-a53, Dynalink DL-WRX36, r28926+3-9a7192c08e in a chroot on r27697+4-d51353db26, exporting an image with ext4 fs works
Description:
> tgt: update to 1.0.95

- net/hev-socks5-server/Makefile
Maintainer: me
Description: update to 2.8.0
> [24.10] hev-socks5-server: update to 2.8.0

- net/hev-socks5-tproxy/Makefile
> [24.10] hev-socks5-tproxy: update to 2.7.0

- net/hev-socks5-tunnel/Makefile
Maintainer: me
Description: update to 2.9.1
> [24.10] hev-socks5-tunnel: update to 2.9.1

- net/rsync/Makefile
- net/rsync/patches/001-Some-checksum-buffer-fixes.patch
- net/rsync/patches/002-Another-cast-when-multiplying-integers.patch
- net/rsync/patches/003-prevent-information-leak-off-the-stack.patch
- net/rsync/patches/004-refuse-fuzzy-options-when-fuzzy-not-selected.patch
- net/rsync/patches/005-added-secure_relative_open.patch
- net/rsync/patches/006-receiver-use-secure_relative_open-for-basis-file.patch
- net/rsync/patches/007-disallow-elements-in-relpath-for-secure_relative_open.patch
- net/rsync/patches/008-Refuse-a-duplicate-dirlist.patch
- net/rsync/patches/009-Fix-FLAG_GOT_DIR_FLIST-collission-with-FLAG_HLINKED.patch
- net/rsync/patches/010-range-check-dir_ndx-before-use.patch
- net/rsync/patches/011-make-safe-links-stricter.patch
- net/rsync/patches/012-fixed-symlink-race-condition-in-sender.patch
- net/rsync/patches/013-raise-protocol-version-to-32.patch
- net/rsync/patches/014-Fix-use-after-free-in-generator.patch
Description:
Including CVE fixes for:
CVE-2024-12084
CVE-2024-12085
CVE-2024-12086
CVE-2024-12087
CVE-2024-12088
CVE-2024-12747
The patch list is based on rsync_3.2.7-1+deb12u2 from Debian.
> [openwrt-23.05] rsync: backport bug fixes

- net/nginx/Makefile
Maintainer: @heil @Ansuel
Compile tested: compiled for Turris Omnia (compiled from current master as of creating this PR)
Run tested: Turris Omnia
Description:
Update NGINX to 1.26.3. Fixes [CVE-2025-23419](https://www.cve.org/CVERecord?id=CVE-2025-23419), so possibly worth backporting?
> nginx: update to 1.26.3

- multimedia/gst1-libav/Makefile
- multimedia/gst1-plugins-bad/Makefile
- multimedia/gst1-plugins-base/Makefile
- multimedia/gst1-plugins-good/Makefile
- multimedia/gst1-plugins-ugly/Makefile
- multimedia/gstreamer1/Makefile
Compile tested: imx6
Rutime tested: imx6
Description:
Bumps all gstreamer bits to the latest 1.24.12 state
> Gstreamer: bump to 1.24.12

- lang/rust/Makefile
Description:
Upstream removed CI builds for this (outdated) version.
> [openwrt-23.05] rust: disable download ci llvm

- admin/ipmitool/Makefile
Maintainer: @neheb @ffontaine 
Compile tested: qualcommax/ipq807x, main
Description:
Now that we are building FreeIPMI library ipmitool will detect it and since we are already passing --enable-intf-free it will build support for FreeIPMI as well.
However, --enable-intf-free was previously no-op since it would just fail to detect FreeIPMI and disable support for it but now it seems that buildbots build FreeIPMI first and then ipmitool will fail with missing dependency on FreeIPMI library.
Since FreeIPMI is quite big and previously ipmitool was built without support for it anyway lets disable support for FreeIPMI in ipmitool and if its required it can be made optional or as a package variant later.
This fixes building ipmitool via buildbots again.
> ipmitool: disable FreeIPMI support

- net/tailscale/Makefile
Maintainer: me / @SuperSandro2000 
Description:
https://github.com/openwrt/packages/pull/26089
https://github.com/tailscale/tailscale/releases/v1.80.3
> [24.10] tailscale: update to 1.80.3

- utils/lxc/Makefile
Users running unprivileged containers will need to create /etc/subgid and /etc/subuid and want to have them preserved across updates. This commit adds them to the default backup set.
> lxc: add two files to default backup list

- net/openvpn/Makefile
Run tested: Xiaomi Mi-mini
Feature changes:
- on non-windows clients (MacOS, Linux, Unix) send "release" string from uname() call as IV_PLAT_VER to server
- Windows: protect cached username, password and token in client memory
- Windows: use new API to get dco-win driver version from driver
- Linux: pass --timeout=0 argument to systemd-ask-password, to avoid default timeout of 90 seconds
Security fixes:
- improve server-side handling of clients sending usernames or passwords longer than USER_PASS_LEN
Notable bug fixes:
- FreeBSD DCO: fix memory leaks in nvlist handling
- purge proxy authentication credentials from memory after use
For details refer to https://github.com/OpenVPN/openvpn/blob/v2.6.13/Changes.rst
(cherry-picked …
> [24.10] openvpn: update to 2.6.13

- utils/mc/Makefile
Compile tested: no changes
Run tested: no changes
Description:
Hello,
I'm preparing the migration to a new website. As part of this, we will be dropping the `www` prefix. Also, I have updated the package source to use our official OSU OSL mirror over HTTPS.
Thank you!
P.S. We released 4.8.33 some time ago with built-in support for `mksh`, so if you upgrade, you can drop this patch. I wouldn't dare upgrade the package myself, as I can't build or test it.
/cc @krant
> mc: update project URLs

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r28898-e1acc7a67b |
```
```
- Changelog:
- Update to [0.38.0](https://github.com/netbirdio/netbird/releases/tag/v0.38.0)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.37.1...v0.38.0
- N/A
--- …
> netbird: update to 0.38.0

- net/adguardhome/Makefile
Maintainer: @dobo90 @1715173329 @Ra2-IFV @p-w-p
Compile tested: mediatek/filogic and bcm27xx/bcm2710, 24.10.0
- Also tested with #26116 
Run tested: mediatek/filogic, 24.10.0, Zyxel EX5601-T0 ubootmod (T-56)
- DNS keeps resolving
Description:
- bump Adguard Home version to 0.107.57
- remove unnesessary `node-yarn/host` (replaced with npm upstream) as per [AdguardTeam/AdGuardHome@1afe226](https://github.com/AdguardTeam/AdGuardHome/commit/1afe226ce8f8af179e1eacccf4cdd63823f0c358#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R210-L211)
- remove unnecessary `NODE_OPTIONS=--openssl-legacy-provider` (since Node.js 18.x) as per …
> adguardhome: bump to 0.107.57

- utils/bcm27xx-eeprom/Makefile
- utils/bcm27xx-eeprom/patches/0001-rpi-eeprom-update-OpenWrt-defaults.patch
- utils/bcm27xx-eeprom/patches/0002-rpi-eeprom-update-change-default-include-path.patch
- utils/bcm27xx-eeprom/patches/0003-rpi-eeprom-update-chmod-silent-f-is-not-supported.patch
- utils/bcm27xx-eeprom/patches/0004-rpi-eeprom-config-replace-nano-with-vi-as-default-ed.patch
Maintainer: me
Run tested: bcm27xx/bcm2712
Description: Update bcm27xx-eeprom to v2025-02-12-2712
bcm2711:
- https://github.com/raspberrypi/rpi-eeprom/blob/v2025.02.12-2712/firmware-2711/release-notes.md#2024-12-07-enable-banklow-and-so-numa-by-default-latest
- https://github.com/raspberrypi/rpi-eeprom/blob/v2025.02.12-2712/firmware-2711/release-notes.md#2024-12-07-enable-banklow-and-so-numa-by-default-latest
- https://github.com/raspberrypi/rpi-eeprom/blob/v2025.02.12-2712/firmware-2711/release-notes.md#2025-02-11-recovery-walk-partitions-to-delete-recoverybin-latest
bcm2712:
- https://github.com/raspberrypi/rpi-eeprom/blob/v2025.02.12-2712/firmware-2712/release-notes.md#2024-11-27-rp1fw-add-fifo_state--drain_tx-fix-can_add_program-default
- …
> [24.10] bcm27xx-eeprom: update to v2025-02-12-2712

- net/adguardhome/Makefile
Maintainer: @dobo90 @1715173329 @Ra2-IFV @p-w-p
Compile tested: mediatek/filogic 24.10.0
- Tested both with and without #26116 
Run tested: mediatek/filogic, 24.10.0, Zyxel EX5601-T0 ubootmod (T-56)
- DNS keeps resolving
Description:
This is a backport of #26131 from master to 24.10 branch (commits marked as cherry-picked)
- bump Adguard Home version to 0.107.57
- remove unnecessary `node-yarn/host` (replaced with npm upstream) as per [AdguardTeam/AdGuardHome@1afe226](https://github.com/AdguardTeam/AdGuardHome/commit/1afe226ce8f8af179e1eacccf4cdd63823f0c358#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R210-L211)
- remove unnecessary …
> adguardhome: backport updates to 24.10 branch

- admin/htop/Makefile
Compile tested: qualcommax/ipq807x, DL-WRX36, r28979+3-9a79cdc7ee
Run tested: qualcommax/ipq807x, DL-WRX36, r28979+3-9a79cdc7ee, htop starts, no more complaints on the terminal type
Description:
Without this hint it finds hostpkg version of ncurses and compiles it in statically
Cc: @graysky2 @Explorer09
This is an alternative to #26137, I'm posting it mostly to verify it with GH build checks.
> htop: tell which variant of ncurses to look for

- net/pptpd/Makefile
- net/pptpd/files/pptpd.init
Clear pptp-server existing logins from CHAP_SECRETS file before adding new login data.
Maintainer: None
Compile tested: mipsel_24kc, ramips/mt7621,mikrotik,routerboard-760igs, MikroTik RouterBOARD 760iGS, OpenWrt 22.03.6 r20265-f85a79bcb4
Run tested: mipsel_24kc, ramips/mt7621,mikrotik,routerboard-760igs, MikroTik RouterBOARD 760iGS, OpenWrt 22.03.6 r20265-f85a79bcb4
Description:
The init script only adds information to the CHAP_SECRETS file. When reloading/restarting the pptpd service the CHAP_SECRETS init script duplicates existing and kept logins and does not delete the removed data because the CHAP_SECRETS file is never cleaned.
This change add a sed line that cleans only all "pptp-server" entries from CHAP_SECRETS before adding the current logins, therefore removing the bad behavior.
> pptpd: Fix secrets update

- net/hev-socks5-tproxy/Makefile
Maintainer: me
Description: update to 2.8.0
> hev-socks5-tproxy: update to 2.8.0

- net/arp-scan/Makefile
- net/arp-scan/patches/001-Disable-promiscuous-mode.patch
Maintainer: @PolynomialDivision @neheb @feckert 
Compile tested: mediatek/filogic, latest master
Run tested: mediatek/filogic, latest master
Description:
If you run the arp-scan tool cyclically, the kernel messages for promiscuous mode are very annoying.
This backports an upstream patch to disable the unnecessary promiscuous mode in arp-scan.
> net/arp-scan: Disable promiscuous mode

- utils/stress-ng/Makefile
Maintainer: me
Compile tested: master, x86
Run tested: : master, x86
> stress-ng: bump to version 0.18.11

- net/hev-socks5-tunnel/Makefile
Maintainer: me
Description: update to 2.10.0
> hev-socks5-tunnel: update to 2.10.0

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.34.0)
> docker-compose: Update to version 2.34.0

- utils/dockerd/git-short-commit.sh
As documented by "man git-rev-parse", the "--short" option shortens commit sha1sums to at least "length" characters, equal to core.abbrev if that is specified in ~/.gitconfig.
The development processes of some other open source projects require having a
[core]
abbrev = 12
in the .gitconfig, which is incompatible with the way in which docker wants PKG_GIT_SHORT_COMMIT.
On my system, I get these errors:
```
make[3]: Entering directory 'feeds/packages/utils/dockerd'
(...)
( CLI_MAKEFILE="../docker/Makefile"; CLI_VERSION=$( grep --only-matching --perl-regexp '(?<=PKG_VERSION:=)(.*)' "${CLI_MAKEFILE}" ); if [ "${CLI_VERSION}" != "27.3.1" ]; then echo "ERROR: Expected 'PKG_VERSION:=27.3.1' in '${CLI_MAKEFILE}', found 'PKG_VERSION:=${CLI_VERSION}'"; exit 1; fi )
( …
```
> dockerd: fix build issue with custom core.abbrev value in .gitconfig

- net/curl/Config.in
- net/curl/Makefile
Maintainer: @1715173329 @hnyman 
Compile tested: x86_64, APU3, latest version
Run tested: x86_64 and lantiq_xrx200, APU3, connect to a server with digest auth requirements
Description:
The '--enable-http-auth' compile option in cURL is used to enable support for HTTP authentication methods. This option allows cURL to handle various authentication schemes, such as Basic, Digest, NTLM, and others, which are commonly used in HTTP requests to secure access to resources.
This cURL compile option is default disabled. This should at least be enabled as a compile option in OpenWrt so that it can be switched on if needed.
> curl: add new option HTTP AUTH

- net/hev-socks5-tproxy/Makefile
Maintainer: me
Description: update to 2.8.0
> [24.10] hev-socks5-tproxy: update to 2.8.0

- net/pptpd/Makefile
- net/pptpd/files/pptpd.init
Backported from master
Clear pptp-server existing logins from CHAP_SECRETS file before adding new login data.
Maintainer: None
Compile tested: mipsel_24kc, ramips/mt7621,mikrotik,routerboard-760igs, MikroTik RouterBOARD 760iGS, OpenWrt 22.03.6 r20265-f85a79bcb4
Run tested: mipsel_24kc, ramips/mt7621,mikrotik,routerboard-760igs, MikroTik RouterBOARD 760iGS, OpenWrt 22.03.6 r20265-f85a79bcb4
Description:
The init script only adds information to the CHAP_SECRETS file. When reloading/restarting the pptpd service the CHAP_SECRETS init script duplicates existing and kept logins and does not delete the removed data because the CHAP_SECRETS file is never cleaned.
This change add a sed line that cleans only all "pptp-server" entries from CHAP_SECRETS before adding the current logins, therefore …
> [23.05] pptpd: Fix secrets update

- net/knot/Makefile
Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbl)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbl)
Description:
- Release upgrade (https://www.knot-dns.cz/2025-03-18-version-345.html)
> knot: update to version 3.4.5

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v3.0.9

- libs/libdaq3/Makefile
Changelog: https://github.com/snort3/libdaq/releases/tag/v3.0.19
> libdaq3: update to 3.0.19

- net/snort3/Makefile
Changelog: https://github.com/snort3/snort3/releases/tag/3.7.1.0
Maintainer: me
Note this depends on https://github.com/openwrt/packages/pull/26150
> snort3: update to 3.7.1.0

- net/hev-socks5-tunnel/Makefile
Maintainer: me
Description: update to 2.10.0
> [24.10] hev-socks5-tunnel: update to 2.10.0

- net/antiblock/Makefile
- net/antiblock/files/etc/config/antiblock
- net/antiblock/files/etc/init.d/antiblock
- net/antiblock/test.sh
1) Added the ability to route different domains through different gateways, up to 32 routes.
2) The program has been switched from proxying mode to sniffer mode.
3) Blacklist has been added so that the specified subnets are not added to the routing table.
> antiblock: Update to 2.1.0

- utils/coreutils/Makefile
This fixes the build on GCC 14 and solves issue https://github.com/openwrt/packages/issues/26175
Maintainer: @hnyman
Compile tested: x86/64, QEMU Standard PC (Q35 + ICH9, 2009), r29064-696ad7b1aa09
Compile tested: ath79/generic, TP-Link Archer C7 v4, r29064-696ad7b1aa09
Compile tested: realtek/rtl838x, Netgear GS108T v3, r29064-696ad7b1aa09
Run tested: x86/64, QEMU Standard PC (Q35 + ICH9, 2009), r29064-696ad7b1aa09, booted and used for 7h without issues
Run tested: ath79/generic, TP-Link Archer C7 v4, r29064-696ad7b1aa09, booted and used for 7h without issues
Run tested: realtek/rtl838x, Netgear GS108T v3, r29064-696ad7b1aa09, booted and used for 7h without issues
Signed-off-by: Pascal Ernster <git@hardfalcon.net>
> coreutils: Add PKG_FIXUP:=autoreconf and bump PKG_RELEASE

- utils/coreutils/Makefile
PKG_FIXUP:=autoreconf introduced in this commit[1] to fix builds with GCC 14 does not play well with GCC 13. Apply it conditionally.
I build some coreutils packages under GCC 13 and again under GCC 14 and both completed successfully.
Fixes https://github.com/openwrt/packages/issues/26175
Maintainer: @hnyman
> coreutils: apply PKG_FIXUP conditionally

- net/bind/Makefile
Verbatim copy from upstream's release notes:
Notes for BIND 9.20.7
- New Features
- Implement the min-transfer-rate-in configuration option.
- A new option min-transfer-rate-in has been added to the view and zone configurations. It can abort incoming zone transfers that run very slowly due to network-related issues, for example. The default value is 10240 bytes in five minutes. [GL #3914]
- Add HTTPS record query to host command line tool.
- The host command was extended to also query for the HTTPS RR type by default.
- Implement sig0key-checks-limit and sig0message-checks-limit.
- Previously, a hard-coded limitation of a maximum of two key or message verification checks was introduced when checking a message’s SIG(0) signature, to protect against possible DoS attacks. Two as a maximum …
> bind: bump to 9.20.7

- libs/gnutls/Makefile
- libs/gnutls/patches/010-m4.patch
- libs/gnutls/patches/020-dont-install-m4-files.patch
- libs/gnutls/patches/030-unistring-optional.patch
All patches refreshed.
Verbatim copy from upstream's NEWS file:
* Version 3.8.9 (released 2025-02-07)
** libgnutls: leancrypto was added as an interim option for PQC
The library can now be built with leancrypto instead of liboqs for
post-quantum cryptography (PQC), when configured with
--with-leancrypto option instead of --with-liboqs.
** libgnutls: Experimental support for ML-DSA signature algorithm
The library and certtool now support ML-DSA signature algorithm as
defined in FIPS 204 and based on
draft-ietf-lamps-dilithium-certificates-04. This feature is
currently marked as experimental and can only be enabled when
compiled with --with-leancrypto or --with-liboqs.
Contributed by David Dudas.
** libgnutls: Support for ML-KEM-1024 key encapsulation mechanism
The support for ML-KEM …
> gnutls: Update to version 3.8.9

- net/lighttpd/Makefile
Description:
lighttpd: update to lighttpd 1.4.78 release hash
Release notes:
https://www.lighttpd.net/2025/3/22/1.4.78/
supercedes #25985, which has unfortunately been ignored for 5 weeks.
> lighttpd: update to lighttpd 1.4.78 release hash

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29070-8d1fe32c2c |
```
```
- Changelog:
- Update to [0.38.2](https://github.com/netbirdio/netbird/releases/tag/v0.38.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.38.0...v0.38.2
- N/A
--- …
> netbird: update to 0.38.2

- net/keepalived/Makefile
- net/keepalived/patches/001-vrrp-Don-t-include-linux-if_ether.h-if-not-needed.patch
- net/keepalived/patches/002-vrrp-fix-reading-of-iproute2-conf-files-when-directo.patch
Maintainer: @feckert @scrpi 
Compile tested: OpenWrt master r29070-8d1fe32c2c on x86/64
Run tested: OpenWrt master r29070-8d1fe32c2c on qoriq
Description:
Bump keepalived to the current latest release, 2.3.2.
This requires backporting two upstream commits to avoid a segfault due to the /etc/iproute2/rt_addrprotos.d and
/usr/share/iproute2/rt_addrprotos.d directories not existing on OpenWrt, and the following compile error:
In file included from /home/stijn/Development/OpenWrt/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-13.3.0_musl/include/net/ethernet.h:10,
from vrrp.c:44:
/home/stijn/Development/OpenWrt/openwrt/staging_dir/toolchain-powerpc64_e5500_gcc-13.3.0_musl/include/netinet/if_ether.h:115:8: error: redefinition of 'struct ethhdr'
115 | struct ethhdr {
|        ^~~~~~
In file …
> keepalived: bump to 2.3.2

- utils/zoneinfo/Makefile
Maintainer: me
Compile tested: TI OMAP3/4/AM33xx, default, OpenWRT master
Description:
This release contains the following changes:
Briefly:
New zone for Aysén Region in Chile which moves from -04/-03 to -03.
Changes to future timestamps
Chile's Aysén Region moves from -04/-03 to -03 year-round, joining
Magallanes Region.  The region will not change its clocks on
2025-04-05 at 24:00, diverging from America/Santiago and creating a
new zone America/Coyhaique.  (Thanks to Yonathan Dossow.)  Model
this as a change to standard offset effective 2025-03-20.
Changes to past timestamps
Iran switched from +04 to +0330 on 1978-11-10 at 24:00, not at
year end.  (Thanks to Roozbeh Pournader.)
Changes to code
'zic -l TIMEZONE -d . -l /some/other/file/system' no longer
attempts to create …
> zoneinfo: Updated to 2025b release.

- net/tor/Makefile
Minor release, see the changelog [1] for what's new.
[1] https://gitlab.torproject.org/tpo/core/tor/-/blob/tor-0.4.8.16/ChangeLog
> tor: update to 0.4.8.16 stable

- net/tailscale/Makefile
Maintainer: @mochaaP @SuperSandro2000 
Compile tested: not needed
Run tested: non needed
Description:
- add missing `PKG_CPE_ID` as per #8534
> tailscale: assign PKG_CPE_ID

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29070-8d1fe32c2c |
```
```
- Changelog:
- Update to [0.39.1](https://github.com/netbirdio/netbird/releases/tag/v0.39.1)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.38.2...v0.39.1
- N/A
--- …
> netbird: update to 0.39.1

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> [openwrt-24.10] haproxy: update to v3.0.9

- net/tailscale/Makefile
Run tested: arm_cortex-a7_neon-vfpv4 OpenWrt 24.10.0, connected to my tailscale net and things continued to work
Description:
----
TODO: backport to 24.10 with ``git-cherry-pick -x``, requires #26177 or #26201
> tailscale: update to 1.82.0

- net/modemmanager/Makefile
- net/modemmanager/files/usr/libexec/rpcd/modemmanager
- net/modemmanager/files/usr/sbin/ModemManager-monitor
Maintainer: me
Run tested: x86_64, APU3, OpenWrt version
Description:
```
modemmanager: add missing mmcli timeout option during ubus call
The default 'timeout' value is 30 seconds when calling an mmcli action. That
is too long. For this reason, the mmcli 'timeout' option is specified for
calls and the value is set to 10 seconds.
```
```
modemmanager: fix pending mmcli calls for ModemManager-monitor script
If the ModemManager is stopped via '/etc/init.d/modemmanager', mmcli calls
always remain in the process list. This is because the ModemManager-monitor
call is not terminated properly, as the kill signals are not handled
correctly in the startup script for mmcli. To fix this, the signal handling is refactored.
```
> modemmanager: various fixes

- net/ddns-scripts/Makefile
Description:
ddns-scripts-scaleway description section was not defined as such and was overriding the package definition leading to:
Makefile:839: *** missing separator.  Stop.
Fixes: a7867016c84c ("ddns-scripts: add support for Scaleway DNS")
> ddns-scripts: fix ddns-scripts-scaleway description

- utils/eza/Makefile
Maintainer: me
Run tested: aarch64_cortex-a53 (BananaPi R64), OpenWrt snapshot, simple function test
[release notes]
0.20.21: https://github.com/eza-community/eza/releases/tag/v0.20.21
0.20.22: https://github.com/eza-community/eza/releases/tag/v0.20.22
0.20.23: https://github.com/eza-community/eza/releases/tag/v0.20.23
0.20.24: https://github.com/eza-community/eza/releases/tag/v0.20.24
> eza: update to 0.21.0

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29070-8d1fe32c2c |
```
```
- Changelog:
- Update to [0.39.2](https://github.com/netbirdio/netbird/releases/tag/v0.39.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.39.1...v0.39.2
- N/A
--- …
> netbird: update to 0.39.2

- net/wfb-ng/Makefile
Changes:
1.  FEC optimizations
2.  Added tunnel daemon
3.  Added wfb_tx_cmd utility
Maintainer: me
Compile tested: (ath79_generic, TP-Link CPE510, OpenWrt 24.10)
Run tested: (ath79_generic, TP-Link CPE510, OpenWrt 24.10)
Description:
This is update of wfb-ng to latest release 25.01. In includes three major changes described above and multiple minor improvements. This is backport of https://github.com/openwrt/packages/pull/26233
> wfb-ng: Update to release 25.01

- net/antiblock/Makefile
- net/antiblock/files/etc/config/antiblock
- net/antiblock/files/etc/init.d/antiblock
- net/antiblock/test.sh
1) Added the ability to route different domains through different gateways, up to 32 routes.
2) The program has been switched from proxying mode to sniffer mode.
3) Blacklist has been added so that the specified subnets are not added to the routing table.
4) Log updated.
5) The "output" option has been removed from the service, it is now /tmp/antiblock
> [24.10] antiblock: Update to 2.1.2

- libs/libxslt/Makefile
- libs/libxslt/patches/0001-xsltproc-remove-maxparserdepth-option.patch
Compile tested: ipq95xx, x86/64
Run tested: ipq95xx
Description:
libxml2 was updated in OpenWrt Git tree with commit dec59db8fb1f ("libxml2: update to 2.13.6"), which fixed several CVEs.
Unfortunately this version bump included removal of some features, which leads to build issues of libxslt:
```c
libxslt-1.1.37/xsltproc/xsltproc.c:733:39: error: assignment of read-only variable 'xmlParserMaxDepth'
733 |                     xmlParserMaxDepth = value;
```
So lets fix it by backporting an upstream "fix", which removes that deprecated functionality.
Fixes: [dec59db8fb1f](https://github.com/openwrt/openwrt/commit/dec59db8fb1f176eeffb7a9d864e05eb590141c6) ("libxml2: update to 2.13.6")
References: https://github.com/openwrt/openwrt/pull/18280
----
Related fail logs:
* …
> [23.05] libxslt: fix build breakage after libxml2 CVE fix updates

- net/lighttpd/Makefile
Description:
lighttpd: update to lighttpd 1.4.79 release hash
Release notes:
https://www.lighttpd.net/2025/4/4/1.4.79/
> lighttpd: update to lighttpd 1.4.79 release hash

- net/openvpn/Makefile
- net/openvpn/patches/100-mbedtls-disable-runtime-version-check.patch
Compile tested: mediatek/mt7622, ramips/mt7621, ramips/mt7620, ramips/mt76x8,
Run tested: Xiaomi Redmi AX6s, Beeline Smartbox Turbo+, Xiaomi Mi router R3, TP-Link MR-3020 v3
Security fixes:
​CVE-2025-2704: fix possible ASSERT() on OpenVPN servers using --tls-crypt-v2
Security scope: OpenVPN servers between 2.6.1 and 2.6.13 using --tls-crypt-v2 can be made
to abort with an ASSERT() message by sending a particular combination of authenticated and
malformed packets. No crypto integrity is violated, no data is leaked, and no remote code
execution is possible. This bug does not affect OpenVPN clients.
For details refer to https://github.com/OpenVPN/openvpn/blob/v2.6.14/Changes.rst
> openvpn: update to 2.6.14

- net/znc/Makefile
- utils/crun/Makefile
Commit https://github.com/openwrt/packages/commit/9fc79e2e262270470397f907704689915ec368b6 ("download: don't overwrite VERSION variable")
changed the variable for direct download call from VERSION to
SOURCE_VERSION.
This cause the dl_github_archive script to pass empty value for
--version arg making it always clone HEAD.
Correctly update the variable to SOURCE_VERSION to actually clone the
expected commit HASH.
> treewide: update to use SOURCE_VERSION for submodule download 

- net/zerotier/Makefile
- net/zerotier/patches/0006-add-support-for-miniupnpc-2.2.8.patch
Maintainer: me
Description: This hopefully fixes https://github.com/openwrt/openwrt/issues/18019, but I was not able to reproduce the problem myself.
>  zerotier: add patch to support miniupnpc 2.2.8

- libs/expat/Makefile
Compile tested: mediatek/filogic, 24.10
Run tested: mediatek/filogic on 24.10, Zyxel EX5601-T0 ubootmod (T-56)
- this is a library, individual dependent projects need to be tested
- I used unbound-anchor to generate a root key based on anchor XML
Description:
Addresses CVE-2024-8176 and CVE-2024-50602.
Changelog: https://github.com/libexpat/libexpat/blob/R_2_7_1/expat/Changes
Fixes: https://github.com/openwrt/packages/issues/26255
Related: https://github.com/openwrt/openwrt/pull/18421
> expat: bump to 2.7.1 to fix several CVEs

- net/strongswan/Makefile
- net/strongswan/patches/0005-pf-handler-Accept-loopback-interfaces-as-packet-sour.patch
- net/strongswan/patches/0006-pf-handler-Correctly-bind-packet-socket-to-an-interf.patch
- net/strongswan/patches/0007-dhcp-Add-option-to-bind-the-receive-socket-to-a-diff.patch
Fixes #25801. Adds the following commits to fix DHCP behaviour on Strongswan 5.9.14:
- https://github.com/strongswan/strongswan/commit/abbf9d28b0032cf80b79bcacea3146a60800a6dd
- https://github.com/strongswan/strongswan/commit/00d8c36d6fdf9e8ee99b9f92a64e7e81dbfa4432
- https://github.com/strongswan/strongswan/commit/a50ed3006e8152eb2cf20e9f92f088ecc18081b0
(cherry picked from commit eb91f914b9eaca8886fd69361602fa4c882d2061 #25870)
Compile tested: aarch64, Linksys E8450, OpenWrt 24.10
Run tested:
> strongswan: DHCP on lo fixes backport

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29161-f44984f19c |
```
```
- Changelog:
- Update to [0.40.0](https://github.com/netbirdio/netbird/releases/tag/v0.40.0)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.39.2...v0.40.0
- N/A
--- …
> netbird: update to 0.40.0

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.8.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.8.0
> lua-eco: update to 3.8.0

- admin/ipmitool/Makefile
- admin/ipmitool/patches/0001-Do-not-require-the-IANA-PEN-registry-file.patch
- admin/ipmitool/patches/0002-configure.ac-allow-disabling-registry-downloads.patch
Maintainer: @lynxis 
Compile tested: x86/64 (APU3)
Run tested: x86/64 (APU3)
Description:
Backport upstream commits to disable the download of IANA PEN registry during the build process.
> ipmitool: disable download of IANA enterprise numbers

- utils/enterprise-numbers/Makefile
Maintainer: @lynxis 
Compile tested: x86/64 (APU3)
Run tested: x86/64 (APU3)
Description:
Add new package to provide a fixed version of the IANA Enterprise Numbers registry primarily used by ipmitool
> ipmitool/utils: add new package enterprise-numbers

- net/modemmanager/Makefile
- net/modemmanager/files/lib/netifd/proto/modemmanager.sh
Maintainer: me
Compile tested: no only script changes
Description:
The 'mmcli' also understands the option 'any'.
> modemmanager: add missing any option to allowedmode

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_functions.sh
- net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_lucihelper.sh
- net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_updater.sh
Maintainer: @chris5560 (?)
Phase 1 of a refactor of the DDNS scripts. Goal: scripts no longer open *many* sub-shells or call a number of external utilities like `sed` and `grep` or similar piped chains where the equivalent is available in pure script functionality. (The `url_update` checks found within this change-set avoid spawning six potential sub-shells at every run.)
Refactors make code less shouty and 'stabby'.
I've tested these changes on my system (23.05.5) for a while now and they show an improvement. Otherwise, the refactor achieves synonymous functionality. 
This change-set introduces the ability to stop individual sections (previously missing).
> ddns-scripts: refactoring phase 1 scripting

- net/knot/Makefile
Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbl)
Run tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 8.0.0 (hbl)
Description:
Release upgrade (https://www.knot-dns.cz/2025-04-10-version-346.html)
> knot: update to version 3.4.6

- net/ddns-scripts/Makefile
Oops. 
Should be harmless anyway: the value is simply reassigned. But let's remove any margin for error.
> ddns-scripts: correct bump release

- net/tgt/Makefile
Maintainer: me
Compile tested: Github CI
Run tested: N/A, the change in the source code doesn't propagate to the package
Description:
- Install examples in documentation directory
- Support vtl setup from config files (OpenWrt doesn't rely on this script)
- Fix escaping of commands (same here)
> tgt: update to 1.0.96

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | QEMU (x86_64) | qemu-system-x86_64 | qemu-9.1.3-2.fc41 | OpenWrt SNAPSHOT r29172-eec11fbbb6 |
- Changelog:
- Update to [0.40.1](https://github.com/netbirdio/netbird/releases/tag/v0.40.1)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.40.0...v0.40.1
- N/A
---
The `OpenWrt` image(s) was built using the …
> netbird: update to 0.40.1

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.35.0)
> docker-compose: Update to version 2.35.0

- lang/lua-eco/Makefile
(cherry picked from commit 733425e1da8b4193663938bc57f9554dc014e03b)
> [24.10] lua-eco: update to 3.8.0

- libs/libcbor/Makefile
Maintainer: @linosgian
Description:
musl libc does not support this feature, and for glibc, additional
library libasan is required. Disable it explicitly to avoid build issue
when CONFIG_DEBUG is selected.
Fixes: #25348
Cc: @hnyman @pwned-pixel
> libcbor: disable sanitize by default

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | QEMU (x86_64) | qemu-system-x86_64 | qemu-9.1.3-2.fc41 | OpenWrt SNAPSHOT r29241-e086bb951c |
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | QEMU (x86_64) | qemu-system-x86_64 | qemu-9.1.3-2.fc41 | OpenWrt SNAPSHOT r29242-e17cbd0488 |
- Changelog:
- Update to [0.41.1](https://github.com/netbirdio/netbird/releases/tag/v0.41.1) …
> netbird: update to 0.41.2

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | QEMU (x86_64) | qemu-system-x86_64 | qemu-9.1.3-2.fc41 | OpenWrt 24.10-SNAPSHOT r28575-ba66273943 |
- Changelog:
- Update to [0.39.2](https://github.com/netbirdio/netbird/releases/tag/v0.39.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.36.7...v0.39.2
- Cherry picked from: https://github.com/openwrt/packages/commit/8efe42d86c9bb08e55454dc7d51d14a8e2167f06
- PR: https://github.com/openwrt/packages/pull/26247 …
> [24.10] netbird: update to 0.39.2

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* do not produce an error on empty allow-lists, fixes https://github.com/openwrt/packages/issues/26228
* do not produce an error when swap is available, fixes https://github.com/openwrt/packages/issues/26313
> adblock-fast: bugfixes: empty allow-lists, support for swap

- libs/expat/Makefile
Compile tested: mediatek/filogic, 24.10
Run tested: mediatek/filogic on 24.10.0, Zyxel EX5601-T0 ubootmod (T-56)
- this is a library, individual dependent projects need to be tested
- I used unbound-anchor to generate a root key based on anchor XML
Description:
This is a backport of #26264 from master to 24.10
Addresses CVE-2024-8176 and CVE-2024-50602.
Changelog: https://github.com/libexpat/libexpat/blob/R_2_7_1/expat/Changes
Fixes: https://github.com/openwrt/packages/issues/26255
> expat: backport 2.7.1 to 24.10 to fix several CVEs

- net/openssh/Makefile
This update requires sshd-auth to be packaged due to the authentication bin split introduced in this version.
Changelog: https://www.openssh.com/txt/release-10.0
Maintainer: @SibrenVasse, @tripolar
> openssh: bump to 10.0p1

- utils/syncthing/Makefile
Maintainer: @aparcar, @brvphoenix 
Compile tested: mediatek/filogic, master and 24.10
- also tested with #26201 and #26310
- all intermediate versions compile as well
Run tested: mediatek/filogic, 24.10.0, Zyxel EX5601-T0 ubootmod (T-56)
- all intermediate versions work as well (I've been using them since their releases)
Description:
- bump Syncthing to 1.29.5
Changelogs:
- https://github.com/syncthing/syncthing/releases/tag/v1.29.3
- https://github.com/syncthing/syncthing/releases/tag/v1.29.4
- https://github.com/syncthing/syncthing/releases/tag/v1.29.5
> syncthing: bump to 1.29.5

- net/external-protocol/Makefile
Compile tested: mediatek/filogic, 24.10
Run tested: mediatek/filogic, 24.10.0, Zyxel EX5601-T0 ubootmod (T-56)
Description:
`external.sh` requires `ip` with `-json` flag that is not supported by the BusyBox `ip`.
```bash
$ ls -lh /sbin/ip
lrwxrwxrwx    1 root     root          14 Feb  4 01:09 /sbin/ip -> ../bin/busybox
$ ip --json ad
BusyBox v1.36.1 (2025-02-26 22:32:40 UTC) multi-call binary.
Usage: ip [OPTIONS] address|route|link|neigh|rule [ARGS]
OPTIONS := -f[amily] inet|inet6|link | -o[neline]
ip addr add|del IFADDR dev IFACE | show|flush [dev IFACE] [to PREFIX]
ip route list|flush|add|del|change|append|replace|test ROUTE
ip link set IFACE [up|down] [arp on|off] [multicast on|off]
[promisc on|off] [mtu NUM] [name NAME] [qlen NUM] [address MAC]
[master IFACE …
```
> external-protocol: add missing ip dependency

- net/openvpn/Makefile
- net/openvpn/patches/100-mbedtls-disable-runtime-version-check.patch
Run tested: Xiaomi Mi-mini
Security fixes:
​CVE-2025-2704: fix possible ASSERT() on OpenVPN servers using --tls-crypt-v2
Security scope: OpenVPN servers between 2.6.1 and 2.6.13 using --tls-crypt-v2 can be made
to abort with an ASSERT() message by sending a particular combination of authenticated and
malformed packets. No crypto integrity is violated, no data is leaked, and no remote code
execution is possible. This bug does not affect OpenVPN clients.
For details refer to https://github.com/OpenVPN/openvpn/blob/v2.6.14/Changes.rst
cherry-picked from https://github.com/openwrt/packages/pull/26260
> [24.10] openvpn: update to 2.6.14

- libs/libqmi/Makefile
Maintainer: Nicholas Smith <nicholas@nbembedded.com>
Compile tested: aarch64, Banana Pi-R4, snapshot 4-16-2025
Run tested: aarch64, Banana Pi-R4, snapshot 4-16-2025, ModemManager connects and is working with my RM502Q-AE modem.
Description:
Bump libqmi to 1.36.0 for modemmanager 1.24.0 dependency
Needed for https://github.com/openwrt/packages/pull/26334
> libqmi: bump to 1.36.0

- net/external-protocol/Makefile
Compile tested: mediatek/filogic, 24.10.1 SDK
Run tested: mediatek/filogic, 24.10.1, Zyxel EX5601-T0 ubootmod (T-56)
Description:
This is a backport of #26311 to 24.10.
`external.sh` requires `ip` with `-json` flag that is not supported by the BusyBox `ip`.
Fixes: https://github.com/openwrt/packages/issues/26302
> external-protocol: backport add missing ip dependency to 24.10

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
* do not produce an error on empty allow-lists, fixes https://github.com/openwrt/packages/issues/26228
* do not produce an error when swap is available, fixes https://github.com/openwrt/packages/issues/26313
(cherry picked from commit 392dc2ed72b5f61e09c4cf2e07c8fb08e9d53ae3)
> [24.10] adblock-fast: bugfixes: empty allow-lists, support for swap

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/etc/init.d/ddns
- net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_functions.sh
- net/ddns-scripts/files/usr/lib/ddns/dynamic_dns_updater.sh
Fix daemon start (backgrounding) and the reload alias in the init script.
> ddns-scripts: fix daemon start and reload

- utils/realtek-poe/Makefile
Maintainer: @mrnuke @Hurricos 
Compile tested: realtek/rtl839x (hpe_1920-48g-poe 5d26507a73b166e6a47522478455bb95bc73672b
Run tested: realtek/rtl839x (hpe_1920-48g-poe 5d26507a73b166e6a47522478455bb95bc73672b
Description:
Currently realtek-poe is built for mips-4kec with the realtek/rtl838x target but not built for mips-24kc with the realtek/rtl839x target. The package builds ok but buildbot is not triggering the extra build and the package is missing from mips-24kc repos.
This flag should instruct build systems to build the package for all targets.
> realtek-poe: Builds for all targets

- net/xtables-addons/Makefile
Updated for compatibility with kernel 6.12.
Fix build error: 
```
make[5]: Entering directory '/Volumes/test/openwrt/build_dir/target-x86_64_musl/linux-x86_64/xtables-addons-3.26/extensions'
-n Xtables-addons 3.26 - Linux 
6.12.23
if [ -n "/Volumes/test/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.12.23" ]; then make -C /Volumes/test/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.12.23 M=/Volumes/test/openwrt/build_dir/target-x86_64_musl/linux-x86_64/xtables-addons-3.26/extensions modules; fi;
make[6]: Entering directory '/Volumes/test/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.12.23'
CC [M]  /Volumes/test/openwrt/build_dir/target-x86_64_musl/linux-x86_64/xtables-addons-3.26/extensions/compat_xtables.o
CC [M] …
```
> xtables-addons: bump to 3.27

- net/modemmanager/Makefile
- net/modemmanager/patches/0001-shared-fibocom-don-t-assume-parent-implements-the-fi.patch
Maintainer: Nicholas Smith, defacto @feckert 
Run tested: aarch64/cortex-a53 (BPi-R4)
Description:
Backport commit
https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/commit/046b79a6766b6384db9cd56a9af5d148787bafe4
See also
https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/975
> modemmanager: backport commit fixing crash with Fibocom mtk-7xx modems

- utils/coremark/Makefile
**Maintainer**: @abajk
**Compile tested**: (aarch64, qualcommax, SNAPSHOT)
**Run tested**: (aarch64, qualcommax, SNAPSHOT, tests done)
**Description**:
when there is an error building packages(other than coremark), and re-run with make -j1 V=s, the coremark package will report error
```
mkdir: cannot create directory '.../coremark-d5fad6bd094899101a4e5fd53af7298160ced6ab/aarch64': File exists
```
the root cause is that, in the second run, that folder is already created in the first run, and not removed before the second run.
therefore, use 'mkdir -p' instead of 'mkdir'.
also, add a '/' to the destination folder of the 'cp' command, otherwise it will also report a "file exist" error.
the '-r' is also removed, since $(CP) already have -r
fixes …
> coremark: fix error when it was built in the second run

- utils/jq/Makefile
I modified the makefile, so that it will build two packages: jq and jq-full. The former will remain unchanged and the latter will have a dependency to the oniguruma library, so jq-full will have regex functions enabled.
Compile tested: ath79/generic, GL.iNet GL-AR150, OpenWrt version 24.10.0
Run tested: ath79/generic, GL.iNet GL-AR150, OpenWrt version 24.10.0
Description:
I built a self compiled image and flashed it to my test device. I compiled the package jq-full instead of the unchange package jq.
```
root@OpenWrt:~# opkg list | grep jq
jq-full - 1.7.1-r1
root@OpenWrt:~# echo -n '"abaabbaaabbb"' |  jq -c 'scan("(a+)(b+)")'
["a","b"]
["aa","bb"]
["aaa","bbb"]
```
> jq: provide regex support in additional package jq-full

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
Description: Update to v3.0.10
> haproxy: update to v3.0.10

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29161-f44984f19c |
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29292-320cdff263 |
```
```
- Changelog:
- Update to …
> netbird: update to 0.42.0

- utils/docker-compose/Makefile
Maintainer: me
Description:
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.35.1)
> docker-compose: Update to version 2.35.1

- libs/sqlite3/Makefile
build: x86_64
run tested: x86_64
```
3.47.2 2024-12-07 20:39:59 2aabe05e2e8cae4847a802ee2daddc1d7413d8fc560254d93ee3e72c14685b6c (64-bit)
```
A note to future devs: >= 3.48 includes a change:
====
Refactor the "configure" script used to help build SQLite from [canonical sources](https://sqlite.org/amalg-v-canon.html#canon), to fix bugs, improve performance, and make the code more maintainable.
- This does not affect the "configure" script in the sqlite3-autoconf-NNNNNNN.tar.gz "amalgamation tarball", only the [canonical sources](https://sqlite.org/amalg-v-canon.html#canon). The build system for the amalgamation tarball is unchanged. If you are using the amalgamation tarball, nothing about this change log entry applies to you.
- The key innovation here is that …
> sqlite3: bump to 3.47.2

- net/pdns-recursor/Makefile
Description:
includes fix for CVE-2025-30195 (which was in 5.2.1)
> pdns-recursor: update to 5.2.2

- net/tailscale/Makefile
Run tested: arm_cortex-a7_neon-vfpv4 OpenWrt 24.10.0, connected to my tailscale net and things continued to work
Description:
----
TODO: backport to 24.10 with ``git-cherry-pick -x``, requires #26177 or #26201 or #26310
> tailscale: update to 1.82.5

- utils/ttyd/Makefile
- utils/ttyd/files/ttyd.init
- utils/ttyd/patches/100-log-to-syslog.patch
Breaking Changes
The web terminal is readonly by default now, to make it writable,
use -W option.
Changelog 1.7.7
Bump to 1.7.7
cmake: add static version back
Changelog 1.7.6
workflow: update actions packages
cmake: get version from git ref
Changelog 1.7.5
html: allow overriding client options with URL query
server: add --exit-no-conn option
html: add safari mobile full screen support
html: Add Unicode 11 xterm.js addon
html: upgrade to xterm 5.4.0
add trzszDragInitTimeout option
Changelog 1.7.4
Leverage Docker Layer System
html: update dependencies
build(deps): update zlib version 1.2.13 to 1.3 in cross-build.sh
server: print working directory on start
server: replace --readonly with --writable
server: fix -U option not work
server: do not expose port to public by default
Add -y flag for …
> ttyd: bump to 1.7.7

- libs/libtorrent-rasterbar/Makefile
Description:
- Update to 2.0.11
- enable python package
The python package now works with Python 3.11.
Also simplify Build/InstallDev with CMAKE_INSTALL.
> libtorrent-rasterbar: Update to 2.0.11 and enable python package

- utils/syncthing/Makefile
- utils/syncthing/files/syncthing.conf
- utils/syncthing/files/syncthing.init
Maintainer: @aparcar, @brvphoenix 
Compile tested: mediatek/filogic, 24.10.1 SDK
- also tested with #26201 and #26310
- all intermediate versions compile as well
Run tested: mediatek/filogic, 24.10.1, Zyxel EX5601-T0 ubootmod (T-56)
- all intermediate versions work as well (I've been using them since their releases)
Description:
This is a backport of #25790 and #26320 to 24.10.
- bump Syncthing to 1.29.5
Changelogs:
- https://github.com/syncthing/syncthing/releases/tag/v1.29.2
- https://github.com/syncthing/syncthing/releases/tag/v1.29.3
- https://github.com/syncthing/syncthing/releases/tag/v1.29.4 …
> syncthing: backport 1.29.5 to 24.10

- net/aria2/Makefile
aria2_project:aria2 is a better CPE ID than tatsuhiro_tsujikawa:aria2 as this CPE ID has the latest CVE (whereas tatsuhiro_tsujikawa:aria2 only has CVEs up to 2010):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:aria2_project:aria2
Maintainer: 
> net/aria2: fix PKG_CPE_ID

- net/openfortivpn/Makefile
- net/openfortivpn/files/openfortivpn.sh
Maintainer: Aaron Goodman
Compile tested: MIPS, MT761; OpenWrt 24.10.0
Run tested: MIPS, MT761; OpenWrt 24.10.0; tested: connect to VPN server
> openfortivpn: bump to 1.23.1; add saml login support

- utils/realtek-poe/Makefile
Backport of https://github.com/openwrt/packages/pull/26341
Maintainer: @mrnuke @Hurricos
Compile tested: realtek/rtl839x (hpe_1920-48g-poe 5d26507a73b166e6a47522478455bb95bc73672b
Run tested: realtek/rtl839x (hpe_1920-48g-poe 5d26507a73b166e6a47522478455bb95bc73672b
Description:
Currently realtek-poe is built for mips-4kec with the realtek/rtl838x target but not built for mips-24kc with the realtek/rtl839x target. The package builds ok but buildbot is not triggering the extra build and the package is missing from mips-24kc repos.
This flag should instruct build systems to build the package for all targets.
> [24.10] realtek-poe: Builds for all targets

- utils/i2c-tools/Makefile
Maintainer: me
Run tested: -
Description:
4.4 (2024-10-10)
-------------------
tools: Use getopt
Implement and document option -h
eeprog: Use force option when data comes from a pipe
i2cdetect: Display more functionality bits with option -F
i2cdump: Remove support for SMBus block mode
i2cget: Document SMBus block mode
Fix the return code of option -h
i2cset: Fix the return code of option -h
i2ctransfer: Sort command line options and add to help text
Add an option to print binary data
Drop redundant variable arg_idx
py-smbus: Install in the defined prefix
Use setuptools instead of distutils
> i2c-tools: update to version 4.4

- libs/glib-networking/Makefile
Maintainer: me
Run tested: -
Description:
2.80.1 - January 8, 2025
========================
- OpenSSL: fix crash in complete_handshake (!251, Dario Saccavino)
- OpenSSL: fix invalid free in openssl_get_binding_tls_server_end_point() (!255)
- TLS test should handle G_IO_ERROR_WOULD_BLOCK (!253, Richard Purdie and Alexander Kanavin)
- Updated translations
> glib-networking: update to version 2.80.1

- utils/exfatprogs/Makefile
Maintainer: me
Run tested: -
Description:
exfatprogs 1.2.8 - released 2025-03-04
======================================
BUG FIXES :
* dump.exfat: fix an incorrect output of an entry position in 32-bit system.
* mkfs.exfat: fill an oem sector with zero instead of one.
* exfatprogs: fix compilation on musl based systems due to loff_t type. And update the Github action to validate builds on the system.
exfatprogs 1.2.7 - released 2025-02-03
======================================
NEW FEATURES :
* fsck.exfat: support repairing the upcase table.
CHANGES :
* exfatprogs: make sure to load the tbl preprocessor for man pages.
BUG FIXES :
* exfatprogs: fix a double free memory error.
* dump.exfat: fix a constraint that volume label, bitmap, upcase table must be …
> exfatprogs: update to version 1.2.8

- utils/lvm2/Makefile
- utils/lvm2/patches/002-const-stdio.patch
- utils/lvm2/patches/003-no-mallinfo.patch
Maintainer: me
Run tested: -
Description:
Version 2.03.31 - 27th February 2025
====================================
Reduce 'mandoc -T lint' reported issues for man pages.
Restore support for LVM_SUPPRESS_FD_WARNINGS (2.03.24).
Fix uncache and split cache restoring original state of volume.
Extend use of lockopt skip to more scenarios.
Enhance error path resolving in polling code.
Disallow shared activation of LV with CoW snapshot.
Fix lvmlockd use in lvremove of CoW snapshot, VDO pool, and uncache.
Improve mirror split with opened temporary volumes.
Improve pvmove finish with opened temporary volumes.
Fix backup limit for devices file, handle over 10,000 files.
Ignore reported optimal_io_size not divisible by 4096.
Fix busy-loop in config reading when …
> lvm2: update to version 2.03.31 and libdm version 1.02.205

- libs/libinput/Makefile
- libs/libmanette/Makefile
- libs/libwacom/Makefile
Maintainer: me
Run tested: -
Description:
Update libinput, libwacom and libmanette.
> libinput: update to 1.28.1 (and related libraries)

- libs/gpgme/Makefile
- libs/libassuan/Makefile
- libs/libksba/Makefile
- libs/npth/Makefile
- utils/gnupg2/Makefile
Maintainer: me
Run tested: -
Description:
Update GnuPG and project-related libraries.
> gnupg2: update to 2.4.7 (and related libraries)

- net/strongswan/Makefile
- net/strongswan/files/swanctl.init
Maintainer:  @pprindeville @Thermi
Compile tested: None.  Script only change.
Run tested: aarch64, Linksys E8450 mediatek/mt7622, OpenWrt 23.05.5, checked generated `swanctl.conf` and operation
Description:
Support the [encap] connection configuration option to force UDP encapsulation of ESP packets to work around connectivity issues with middleboxes which block ESP packets.
This work is based on a patch by @aleks-mariusz in https://forum.openwrt.org/t/confusion-regarding-setting-up-ikev2-vpn-service-with-strongswan-using-ipsec-and-swanctl/169587/9 This PR uses `encap` for the option name instead of `force_encapsulation` for consistency with [swanctl.conf](https://docs.strongswan.org/docs/latest/swanctl/swanctlConf.html#:~:text=encap).
Thanks for considering,
Kevin
[encap]: …
> strongswan: swanctl: Add support for encap

- net/strongswan/files/swanctl.init
Maintainer:  @pprindeville @Thermi
Compile tested: None.  Script only change.
Run tested: aarch64, Linksys E8450 mediatek/mt7622, OpenWrt 23.05.5, checked generated `swanctl.conf` and operation
Description:
Both `$overtime` and `$send_cert` are only used in `config_remote()` in `swanctl.init`.  However, unlike the other local option variables, they are not declared local.  This PR does so for consistency, to avoid global namespace pollution, and make the code easier to reason about.
For reference, `$overtime` was added in f9d91f1f47, `$send_cert` in 4b9453b9a4.
Thanks for considering,
Kevin
> strongswan: swanctl: make overtime and send_cert vars local

- net/aria2/Makefile
- net/aria2/files/aria2.init
```
Mon Apr 21 13:30:56 2025 daemon.info aria2c[13301]: jail: exec-ing /usr/bin/aria2c
Mon Apr 21 13:30:56 2025 daemon.err aria2c[13301]: Exception caught
Mon Apr 21 13:30:56 2025 daemon.err aria2c[13301]: Exception: [Platform.cc:125] errorCode=1 OSSL_PROVIDER_load 'legacy' failed.
Mon Apr 21 13:30:56 2025 daemon.err aria2c[13301]:
Mon Apr 21 13:30:56 2025 daemon.info procd: Instance aria2::aria2.main s in a crash loop 6 crashes, 0 seconds since last crash
Mon Apr 21 13:30:56 2025 daemon.info aria2c[13301]: jail: jail (13302) exited with exit: 1
```
Links:
- https://github.com/aria2/aria2/issues/2152
Maintainer: @egorenar @kuoruan 
Compile tested: x86_64, openwrt 24.10.0
Description:
This is a improved version of https://github.com/openwrt/packages/pull/22956 , mount …
> aria2: fix openssl legacy load failed

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.9.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.9.0
> lua-eco: update to 3.9.0

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29334-b0710e964d |
```
```
- Changelog:
- Update to [0.43.0](https://github.com/netbirdio/netbird/releases/tag/v0.43.0)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.42.0...v0.43.0
- N/A
--- …
> netbird: update to 0.43.0

- libs/boost/Makefile
Compile tested:  openwrt-sdk-bcm27xx-bcm2712_gcc-13.3.0_musl.Linux-x86_64 
Description:
This commit updates boost to version 1.88.0
New libraries in this release:
* Hash2 [2]: An extensible hashing framework, from Peter Dimov and Christian Mazakas.
* MQTT5  [3]: MQTT5 client library built on top of Boost.Asio, from Ivica Siladić, Bruno Iljazović, and Korina Šimičević.
More info about Boost 1.88.0 can be found at the usual place [1].
[1]: https://www.boost.org/users/history/version_1_88_0.html
[2]: https://www.boost.org/libs/hash2/
[3]: https://www.boost.org/libs/mqtt5/
> boost: Updates package to version 1.88.0

- sound/wavpack/Makefile
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:wavpack:wavpack
> sound/wavpack: assign PKG_CPE_ID

- utils/lvm2/Makefile
This package fails to build without defining libmvme as a DEPENDS.
```
Package lvm2 is missing dependencies for the following libraries: libnvme.so.1
```
> lvm2: add missing dependency

- libs/libupnp/Makefile
pupnp_project:pupnp is a better CPE ID than libupnp_project:libupnp as this CPE ID has the latest CVEs from 2021 (whereas libupnp_project:libupnp only has CVEs up to 2020): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:pupnp_project:pupnp
> libs/libupnp: fix PKG_CPE_ID

- net/aria2/Makefile
- net/aria2/files/aria2.init
```
Mon Apr 21 13:30:56 2025 daemon.info aria2c[13301]: jail: exec-ing /usr/bin/aria2c
Mon Apr 21 13:30:56 2025 daemon.err aria2c[13301]: Exception caught
Mon Apr 21 13:30:56 2025 daemon.err aria2c[13301]: Exception: [Platform.cc:125] errorCode=1 OSSL_PROVIDER_load 'legacy' failed.
Mon Apr 21 13:30:56 2025 daemon.err aria2c[13301]:
Mon Apr 21 13:30:56 2025 daemon.info procd: Instance aria2::aria2.main s in a crash loop 6 crashes, 0 seconds since last crash
Mon Apr 21 13:30:56 2025 daemon.info aria2c[13301]: jail: jail (13302) exited with exit: 1
```
Links:
- https://github.com/aria2/aria2/issues/2152
Maintainer: @egorenar @kuoruan 
Compile tested: x86_64, openwrt 24.10.0
Description:
This is a improved version of https://github.com/openwrt/packages/pull/22956 , mount …
> [24.10] aria2: fix openssl legacy load failed

- utils/grep/Makefile
Maintainer: Julen Landa Alustiza / @Zokormazo
Compile tested: (rockchip, NanoPi R2S, master branch)
Run tested: the same as above.
Description:
Commit 07b6eec21f57c3cb391b0daf89240b7632b2a49f doesn't work at least now, because `package.mk` initializes the variables to the default values.  You have to modify the variable after including `package.mk` as @zhanhb [commented](https://github.com/openwrt/packages/pull/16551#issuecomment-1073797207).
Fixes: #17826
Related: #16548, #17803, #23778, #16551
> grep: fix that egrep and fgrep workaround doesn't work

- utils/coreutils/Makefile
Fix compilation with gcc 14 by applying the `-std=c23` flag, as suggested by @lededev in https://github.com/openwrt/packages/commit/2d3f68cc8c165b1fa01308f566394cbd7d06766f#commitcomment-153809841
Remove the previous autoreconf fix attempt.
cc @graysky2 
Compile tested: qualcommax/DL-WRX36
Description:
GCC 14 was applied as the default for main/master today. So, aim to fix the issue more permanently.
Related: #26175 , #26195 , #26200
Ps. I am curious to see how the PR goes through CI, as 1/3 of that targets have already got the gcc14 defaults in SDK from buildbot, while 2/3 are still with the old gcc13 SDK.
Pps. As gcc14 has today been set as the default, there can possibly be wider breakage of packages compilation, although @neheb did last year a major effort last year …
> coreutils: Fix gcc14 compilation via std=c17  (or c23)

- net/net-snmp/Makefile
- net/net-snmp/files/snmpd.init
Compile tested: (x86_64, OpenWrt 24.10)
Run tested: (x86_64, OpenWrt 24.10)
Description:
In a previous commit (0b12bee6) hostname was added to snmpd.init. 
To track changes in system, the init file needs to add 'system' to the trigger.
Therefore it is added in this commit.
> net-snmp: add system to trigger

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29334-b0710e964d |
```
```
- Changelog:
- Update to [0.43.1](https://github.com/netbirdio/netbird/releases/tag/v0.43.1)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.43.0...v0.43.1
- N/A
--- …
> netbird: update to 0.43.1

- net/chrony/Makefile
- net/chrony/files/chrony.config
- net/chrony/files/chronyd.init
Maintainer: @mlichvar 
Run tested: 24.10.1
Description:
The existing config sections were anonymous, implying multiple can coexist. Those are now named so that only one shall exist.
Added:
- smoothtime (in case of large frequency offsets)
- systemclock parameters
- logchange
- maxsources (for peers)
- prefer (one server over others)
- interleave (xleave - more accurate transmit timestamps)
> chrony: add configuration parameters

- lang/php8/Makefile
Maintainer: me
Compile tested: bcm2708, mxs
Run tested: Raspberry Pi
Description:
This PR updates to latest PHP version 8.4.6 in the first commit.
In a second commit, it also adjusts the compilation process for the snmp extension module slightly by passing additional autoconf variables. If not given, loading the snmp extension fails with unresolved symbol 'usmHMAC192SHA256AuthProtocol'.
> php8: update to 8.4.6 and fix snmp extension

- net/dnsdist/Makefile
Run tested: x86_64 docker APK
Description:
fixes CVE-2025-30194
> dnsdist: update to 1.9.9

- net/chrony/Makefile
Maintainer: me
Compile tested: mipsel, Cudy WR1300, 24.10
Run tested: mipsel, Cudy WR1300, 24.10, configuration with AES128 key
Description:
gnutls and nettle are already required for NTS. Enable their use for authentication with non-MD5 symmetric keys as the SECHASH feature printed by the configure script.
Also drop the --enable,nts (typo) configure option. It's enabled by default.
> chrony: enable support for non-MD5 keys in nts variant

- net/xfrpc/Makefile
Fixes compilation with GCC14.
Switch to local tarballs instead of codeload. Smaller archives.
> xfrpc: update to 4.04.856

- utils/lrzsz/patches/400-configure-gcc14.patch
Maintainer: @ynezz @neheb 
Compile tested: qualcommax/ipq807x (Cortex-A53), main
Description:
```
Trying to compile with GCC14 will fail on compiler sanity check with: configure:1056:1: error: return type defaults to 'int' [-Wimplicit-int]
1056 | main(){return(0);}
| ^~~~
```
This is due to GCC14 not allowing implicit integer types anymore[1].
So, patch configure to avoid this and make it compile with GCC14.
Proper fix would be to use autoreconf to rebuild configure but configure.in is completely outdated and would likely be more broken when regenerated.
[1] https://gcc.gnu.org/gcc-14/porting_to.html#implicit-int
> lrzsz: fix compilation with GCC14

- net/sing-box/Makefile
Compile tested: mediatek/filogic Xiaomi Redmi ax6000 24.10.0
Run tested: mediatek/filogic Xiaomi Redmi ax6000 24.10.0
Description:
📝 Release Notes
https://github.com/SagerNet/sing-box/releases/tag/v1.11.9
(cherry picked from commit https://github.com/openwrt/packages/commit/c0a996ddd9ee8a16fb79f5495e6fc0196eebf493)
> [24.10] sing-box: Update to 1.11.9

- net/freeradius3/Makefile
- net/freeradius3/patches/002-disable-session-cache-CVE-2017-9148.patch
- net/freeradius3/patches/010-openssl-deprecated.patch
changed to github download URL
build: x86_64
run tested: x86_64
```
radiusd: FreeRADIUS Version 3.2.7, for host x86_64-openwrt-linux-gnu, built on Apr 18 2025 at 00:10:48
FreeRADIUS Version 3.2.7
```
> freeradius3: bump to 3.2.7

- net/aria2/Makefile
Maintainer: @kuoruan 
cc：@1715173329
Compile tested: (aarch, rax3000m, OpenWrt version 24.10, tests done)
Run tested: (aarch, rax3000m, OpenWrt version 24.10, tests done)
Description: fix in full compile a firmware 
* pkg_hash_check_unresolved: cannot find dependency aria2-openssl for aria2
* pkg_hash_fetch_best_installation_candidate: Packages for aria2 found, but incompatible with the architectures configured
* satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-aria2:
* 	aria2-openssl
* opkg_install_cmd: Cannot install package luci-app-aria2.
fix:https://github.com/openwrt/packages/commit/dfa01855b37255f3582ed80b33db7fa7be482aef
> aria2: fix aira2-openssl install failed

- libs/libtirpc/Makefile
Fix compilation with gcc 14 by applying the -std=c99 flag
Closes #26445 
Maintainer:
> libtirpc: fix host build via std=c99

- lang/lua-eco/Makefile
(cherry picked from commit a25bfb468c324a192534658926cf79dd998d8e18)
Maintainer: me
Description:
Release notes for 3.9.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.9.0
> [24.10] lua-eco: update to 3.9.0

- net/dnsdist/Makefile
Run tested: docker x86_64
Description:
fixes CVE-2025-30194
> [24.10] dnsdist: update to 1.9.9

- net/dnsdist/Makefile
Description:
fixes CVE-2025-30194
> [23.05] dnsdist: update to 1.9.9

- net/pbr/Makefile
- net/pbr/files/etc/init.d/pbr
Maintainer: me
Description:
* do not display errors on negated values
* improved output in verbose mode
> pbr: bugfix: no errors on negated values

- net/pbr/Makefile
- net/pbr/files/etc/init.d/pbr
Maintainer: me
Description:
* do not display errors on negated values
* improved output in verbose mode
(cherry picked from commit a443f2e200d46f3b8bc52106295af0c8adfd740a)
> [24.10] pbr: bugfix: no errors on negated values

- utils/syncthing/Makefile
Maintainer: @aparcar, @brvphoenix
Compile tested: HEAD, x86/64
- also tested with #26201 and #26310
Run tested: snapshot, x86/64, QEMU
Description:
> - chore(lib): expose model methods to obtain progress
> - feat(gui): explanation to options enabled or disabled per folder type
> - fix(gui): validate device ID in canonical form
> - fix(config): remove discontinued primary STUN server
> - fix(stun): better error handling
> - chore(config): remove discontinued secondary STUN servers
> - chore(fs): speed up case normalization
> - build(deps): update dependencies
> - feat(fs, config): add support for …
> syncthing: bump to 1.29.6

- libs/libpng/Makefile
- libs/libpng/patches/100-config_fix.patch
This reverts commit 5313dd9be from PR #25324 , related to #25323 and https://github.com/openwrt/openwrt/pull/16899
The additional symlink `libpng16.so -> libpng16d.so` is now unnecessary as OpenWrt main repo PR https://github.com/openwrt/openwrt/pull/18709 commit https://github.com/openwrt/openwrt/commit/703e7d2d5b58e68528cb5fadfc1185bd3904b3d9 changed the cmake build type from 'Debug' to 'RelWithDebInfo', which causes libpng .so to be again compiled with the normal name `libpng16.so` (instead of the debug-styled `libpng16d.so`).
cc due to earlier PRs: @nwf @dangowrt
Compile & run tested with CONFIG_DEBUG enabled : mediatek/filogic MT-6000
> libpng: Revert "libpng: add symlink to debug library" as unnecessary, update to 1.6.48

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Compile tested: MediaTek MT7621 ver:1 eco:3, OpenWrt 24.10.0 r28427-6df0e3d02a
Run tested: MediaTek MT7621 ver:1 eco:3, OpenWrt 24.10.0 r28427-6df0e3d02a
Description:
- Removing hidden carriage return '^M' from curl results
- Removing "grep" command and only "awk" is used to filter the results
Signed-off-by: Nikolay Manev (just.ops@proton.me)
> adblock-fast: Remove non-printable characters from curl results

- multimedia/tvheadend/Config.in
- multimedia/tvheadend/Makefile
- multimedia/tvheadend/patches/010-fix-tvheadend-bug-1786.patch
Maintainer: me
Compile tested: Gentoo Linux, OpenWrt r28997
Run tested: arm_cortex-a9_vfpv3 Turris Omnia r28997
- DVB-C works
- HTSP streaming to Kodi works
- recording works
- IPTV, SAT>IP, HDHomeRun, CA modules not tested - I don't have any of those.
Description:
- update to git master 2024-11-12 (dev stalled since then)
- patch for OpenWrt bug #26422 from [tvheadend PR #1786](https://github.com/tvheadend/tvheadend/pull/1786)
- Options removed:
- imagecache = tvheadend doesn't support disabling it anymore
- Options added:
- detailed (but slow) memory utilization reporting = default off
- Timeshift = default on
- tsfile = currently bugged in tvheadend, commented out / always on
- HDHomeRun server emulation = default on
- Digital Devices DVB CI descrambling cards = default off
- RegEx …
> tvheadend: update to 2024-11-12, new options, patch for bug #26422

- utils/smartmontools/Makefile
- utils/smartmontools/patches/002-os_mailer-is-mailx.patch
Maintainer: me
Compile tested: aarch64_cortex-a53, qualcommax/ipq807x, r29490+3-e31738e83d
Run tested: aarch64_cortex-a53, qualcommax/ipq807x, r29490+3-e31738e83d in a chroot on r28979+3-9a79cdc7ee, `smartctl  --xall /dev/sda` worked
Description:
> smartmontools: update to 7.5

- net/strongswan/Makefile
After reinstalling the packages with the preserved configuration files after a sysupgrade, the reinstalled package config files overwrite what is on disk rather than being placed as conf-opkg. Defining these config files will preserve them appropriately.
Compile tested: aarch64, Linksys E8450, OpenWrt 24.10.0
Run tested: aarch64, Linksys E8450, OpenWrt 24.10.0
Description:
This adds the config files to the `conffiles` target which should signal to opkg (and apk in future) the config files to be left alone if they exist.
I have checked that the resulting opkg package's control.tar.gz has a new `conffiles` metadata file. Installing the package now shows this message:
```bash
Upgrading strongswan-mod-dhcp on root from 5.9.14-r6 to 5.9.14-r7...
Configuring …
```
> strongswan: preserve changed configuration files

- CONTRIBUTING.md
- net/apfree-wifidog/README.md
- net/geoip-shell/README.md
- net/stubby/files/README.md
Maintainer: various
Description:
With this PR i:
* correctly named the reference to a menu-item
* made the contribution text somewhat clearer
* fix openwrt reference with correct capitalization
* fix some typo's in package markdown files
Made this PR with best intentions. No problem if unable to complete this PR.
> wiki: openwrt naming fixes and contribution improvement

- utils/logrotate/Makefile
logrotate_project:logrotate is a better CPE ID than gentoo:logrotate as this CPE ID has the latest CVE (whereas gentoo:logrotate only has CVEs up to 2011):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:logrotate_project:logrotate
> utils/logrotate: fix PKG_CPE_ID

- lang/tcl/Makefile
tcl:tcl is a better CPE ID than tcl_tk:tcl_tk as this CPE ID has the latest CVE (whereas tcl_tk:tcl_tk only has CVEs up to 2008): https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:tcl:tcl
> lang/tcl: fix PKG_CPE_ID

- libs/libuv/Makefile
libuv:libuv is a better CPE ID than libuv_project:libuv as this CPE ID has the latest CVEs (whereas libuv_project:libuv only has a CVE from 2015):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:libuv:libuv
Fixes: f8ecbf529bad57970e4ff8f90484ba58d06b4a39 (libuv: update to 1.32.0)
Maintainer:
> libs/libuv: fix PKG_CPE_ID

- utils/syncthing/Makefile
Maintainer: @aparcar, @brvphoenix
Compile tested: 24.10.1, x86/64
Run tested: 24.10.0, x86/64, QEMU
Description:
- Backport from #26463 to 24.10.
> - chore(lib): expose model methods to obtain progress
> - feat(gui): explanation to options enabled or disabled per folder type
> - fix(gui): validate device ID in canonical form
> - fix(config): remove discontinued primary STUN server
> - fix(stun): better error handling
> - chore(config): remove discontinued secondary STUN servers
> - chore(fs): speed up case normalization
> - build(deps): update dependencies
> - feat(fs, config): add support for …
> [24.10] syncthing: bump to 1.29.6

- utils/stress-ng/Makefile
- utils/stress-ng/patches/001-disable-extra-stressors.patch
- utils/stress-ng/patches/002-disable-atomics-mips-and-ppc.patch
Maintainer: me
Compile tested: x86 http://github.com/openwrt/openwrt/commit/b5fba2035180b7892f33516aa65851051d32c719
Run tested: x86 http://github.com/openwrt/openwrt/commit/b5fba2035180b7892f33516aa65851051d32c719
> stress-ng: bump to version 0.19.00

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
(cherry picked from commit 3d9eb08f8e4c63b7f5d6c057f8d5f7e54ba4158e)
> [24.10] adblock-fast: Fixed non-printable characters and bump PKG_VERSION

- net/acme-acmesh/Makefile
Signed-off-by: Toke Høiland-Jørgensen <toke@toke.dk>
-------
Maintainer: me
Run tested: no
> acme-acmesh: Bump to v3.1.1

- net/bcp38/Makefile
- net/bcp38/files/bcp38.config
- net/bcp38/files/run.sh
Maintainer @tohojo 
Patched respective files on live routers, still worked nicely after.
Run tested: 24.10.1 23.05.5 aarch64 x86/64 ramips
Description:
Add CG-NAT address space to non-routable list, while others are null routed by many intermediaries, cg-nat in particular kits at ttl reminder 55-60 ie half world's away.
Make dhcp filter stricter
> net/bcp38: Add cgnat shared space to bcp38  nonrouteable list

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Description:
adblock-fast: modify gawk statement
(cherry picked from commit 34c02108ce36aa2ef23cef2245ab120273a8e3dd)
> [24.10] adblock-fast: improve the processing of combined list

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29467-ecc0f549c4 |
```
```
- Changelog:
- Update to [0.43.3](https://github.com/netbirdio/netbird/releases/tag/v0.43.3)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.43.2...v0.43.3
- N/A
--- …
> netbird: update to 0.43.3

- net/xtables-addons/Makefile
Maintainer: @namiltd 
Compile tested: x86_64, APU3, master
Run tested: x86_64, APU3, only module load
Description:
The RTSP conntrack and nat does not dependent on iptables, but only on nf_conntrack and nf_nat. The RTSP conntrack module is used as a helper in [firewall4](https://github.com/openwrt/firewall4/blob/master/root/usr/share/firewall4/helpers#L89). Previously, it was not possible to install RTSP kernel module without also installing the not needed iptables modules. However, as firewall4 is based on nftables and not on iptables, this dependency is not necessary.
I did never get an answer from the [mailinglist](https://lists.openwrt.org/pipermail/openwrt-devel/2024-August/043112.html). But from my point of view it made no sense to have a dependency on iptables here. And since it's …
> xtables-addons: remove not needed iptables install dependency for RTSP helpers

- net/wifi-presence/files/wifi-presence.init
Fixed mqttID not taken into account (typo error)
Maintainer: @awilliams / @jmccrohan
Compile tested: mvebu/cortexa9 / r24106-10cc5fcd00
Run tested: mvebu/cortexa9 / r24106-10cc5fcd00
Description:
In `wifi-presence.init` only, `mqttID` variable was written `mqttId`, preventing it from being taken into account.
> wifi-presence: mqttID error

- lang/php8/Makefile
- lang/php8/test.sh
Maintainer: me
Compile tested: mxs, bcm27xx
Run tested: bcm27xx, Raspberry Pi
Description:
https://www.php.net/ChangeLog-8.php#8.4.7
Since some buildbots failed on this PR, I included a second commit which adapts the CI helper script for apk.
> php8: update to 8.4.7 and adapt CI test helper

- libs/tcp_wrappers/patches/001-debian_subset.patch
- libs/tcp_wrappers/patches/006-compilation-warnings.patch
Maintainer: @neheb (last person to touch it)
Compile tested: aarch64, 24.10.1
Description: The portable way is to use `socklen_t`. This fixes int-conversion in both glibc and musl based builds.
> tcp_wrappers: update patches for gcc14

- net/strongswan/Makefile
Maintainer: @lowjoel @kevinoid @peci1 
Compile tested: qualcommax/ipq807x,main
Description:
UCI plugin in strongswan has been broken for years, and now its causing strongswan to fail compilation.
So, instead of the whole strongswan package to be failing and missing from feeds simply make UCI plug depend on @BROKEN.
> strongswan: mark UCI plugin as broken

- admin/zabbix/Makefile
Compile tested: arm64, RK3568, master
Run tested: arm64, RK3568, master
update zabbix to 7.0.12 also fix build error #26482
> zabbix: update to 7.0.12

- lang/php8/Makefile
Maintainer: me
Run tested: ~~not yet~~ mxs, Duckbill
Description:
This fixes:
- CVE-2025-1217
- CVE-2025-1219
- CVE-2025-1734
- CVE-2025-1736
- CVE-2025-1861
https://www.php.net/ChangeLog-8.php#8.1.32
> php8: update to 8.1.32

- lang/php8/Makefile
- lang/php8/patches/0022-Use-system-timezone.patch
- lang/php8/patches/0025-php-5.4.9-fixheader.patch
- lang/php8/patches/1004-disable-phar-command.patch
Maintainer: me
Compile tested: mxs, bcm2709
Run tested: bcm2709 (Raspberry Pi 2B)
Description:
https://www.php.net/ChangeLog-8.php#8.3.21
> [24.10] php8: update to 8.3.21

- net/strongswan/Makefile
- net/strongswan/files/swanctl.init
Maintainer:  @pprindeville @Thermi
Compile tested: None.  Script only change.
Run tested: aarch64, Linksys E8450 mediatek/mt7622, OpenWrt 23.05.5, checked generated `swanctl.conf` and operation
Description:
Support the [send_certreq] connection configuration option to disable offering trusted root CA certificates and reduce the size of the initial IKE packets.
This work is based on a patch by @aleks-mariusz in https://forum.openwrt.org/t/confusion-regarding-setting-up-ikev2-vpn-service-with-strongswan-using-ipsec-and-swanctl/169587/9  This PR uses `send_certreq` for the option name instead of `remote_sendcert` for consistency with [swanctl.conf](https://docs.strongswan.org/docs/latest/swanctl/swanctlConf.html#:~:text=send_certreq).
Thanks for considering,
Kevin
[send_certreq]: …
> strongswan: swanctl: Add support for send_certreq

- net/bind/Makefile
Compile tested: x86_64, generic, HEAD
Run tested: same, installed on production firewall
Description:
> bind: bump to 9.20.8

- utils/fx/Makefile
Maintainer: @dynasticorpheus 
Compile tested: Ubuntu 23.04 x64 / OpenWrt SNAPSHOT @ https://github.com/openwrt/packages/commit/36b1dd75fd9da1ea13f1ce1ee679c6b3c9c402cc
Description: Update to [36.0.2](https://github.com/antonmedv/fx/compare/36.0.1...36.0.2)
> fx: update to 36.0.2

- net/smartdns/Makefile
@pymumu 
- x86_64 AMD KVM OpenWrt `SNAPSHOT r29219-6bbf4a540d / LuCI Master 25.102.73982~04f2d12`
- x86_64 AMD KVM OpenWrt `SNAPSHOT r29219-6bbf4a540d / LuCI Master 25.102.73982~04f2d12`
- Resolves DoH DNS requests as expected.
```
smartdns: Update to version 46.1
Change package source to github codeload.
Trim "Release" prefix from upstream versioning
to make it at least somewhat semantic compliant.
Add two additional folders and two default
config files based on upstream changes.
Signed-off-by: Jonathan Smith <sphere_accompany616@simplelogin.com>
```
Upstream OpenWrt Makefile uses "46.2" as its version, but 46.2 currently doesn't exist. It appears that 46.2 is actually a development version for its new standalone web ui.
> smartdns: Update to version 46.1

- net/bind/Makefile
Compile tested: mvebu, OpenWRT 23.05
Run tested: mvebu, OpenWRT 23.05. Basic DNS functionality. Recursive and authoritative responses.
Description:
Bump openwrt 23.05 to the latest bind 9.18.x release.
> bind: bump to 9.18.36

- utils/fscrypt/Makefile
- utils/fscrypt/files/pam_config
Fscrypt is a high-level tool for the management of Linux native filesystem encryption. fscrypt manages metadata, key generation, key wrapping, PAM integration, and provides a uniform interface for creating and modifying encrypted directories.
Upstream url: https://github.com/google/fscrypt/blob/master/README.md
Build-tested: bcm27xx/bcm2712
Run-tested: bcm27xx/bcm2712
Maintainer: me
> fscrypt: add new package

- admin/syslog-ng/Makefile
oneidentity:syslog-ng is a better CPE ID than balabit:syslog-ng as this CPE ID has the latest CVEs (whereas balabit:syslog-ng only has a CVE from 2000):
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:oneidentity:syslog-ng
Fixes: 5f07bb10948f6ebdf83470c3437c3072aab982e3 (syslog-ng: update to version 3.19.1)
> admin/syslog-ng: fix PKG_CPE_ID

- net/dnsdist/Makefile
Run tested: podman/docker x86_64
Description:
fixes CVE-2025-30193
> dnsdist: update to 1.9.10

- kernel/ovpn-dco/Makefile
Maintainer: @zhaojh329 
Compile tested: ramips/mt7620 (6.12), ramips/mt7621 (6.6)
Run tested: Xiaomi Mi router 3 pro, Beeline smartbox giga
Added compatibility with 6.12 kernel
> ovpn-dco: update to version 0.2.20241216

- net/bind/Makefile
Compile tested: 23.05 (malta)
Run tested: 23.05 (malta) Basic DNS query functionality, recursive and authoritative.
> bind: bump to 9.18.37

- net/tailscale/Makefile
Run tested: arm_cortex-a7_neon-vfpv4 OpenWrt 24.10.0, connected to my tailscale net and things continued to work
Description:
> tailscale: update to 1.84.0

- utils/docker-compose/Makefile
> docker-compose: Update to version 2.36.2

- lang/lua-eco/Makefile
Maintainer: me
Description:
Release notes for 3.10.0: https://github.com/zhaojh329/lua-eco/releases/tag/v3.10.0
> lua-eco: update to 3.10.0

- lang/perl/Makefile
- lang/perl/perlbase.mk
Maintainer: @pprindeville, @Naoir
Compile tested: mvebu-cortexa9, arm_cortex-a9_vfpv3-d16, master: c399f7b94a9ddf98100542157b25df1d5cfe533b
Run tested: mvebu-cortexa9, arm_cortex-a9_vfpv3-d16, 23.05.0
Description:
Attempting to use  `ExtUtils::MakeMaker` after Installing `perlbase-extutils` results in an error:
```
root@storage:~# perl -MExtUtils::MakeMaker -e '1;'
Can't locate ExtUtils/MakeMaker/version/vpp.pm in @INC (you may need to install the ExtUtils::MakeMaker::version::vpp module) (@INC contains: /usr/lib/perl5/5.28) at (eval 4) line 1.
BEGIN failed--compilation aborted at (eval 4) line 1.
Compilation failed in require at /usr/lib/perl5/5.28/ExtUtils/MakeMaker.pm line 9.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.28/ExtUtils/MakeMaker.pm line 9.
Compilation failed in …
```
> perlbase-extutils: Adding required perlbase-version dependency.

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29741-f23ad96e47 |
```shell
reboot
```
- Changelog:
- Update to [0.45.1](https://github.com/netbirdio/netbird/releases/tag/v0.45.1) …
> netbird: update to 0.45.1

- net/openthread-br/Makefile
- net/openthread-br/patches/100-fix-gcc14-build.patch
Compile tested: mediatek/filogic
Description:
This patch is taken from openwrt/openwrt@a41747ac8e82 ("mbedtls: fix build on GCC 14").
Fixes: https://github.com/openwrt/packages/issues/26570
> openthread-br: fix build on GCC 14

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_cloudflare_com_v4.sh
Maintainer: Florian Eckert <fe@dev.tdt.de>
Description:
There is an obvious bug here:
if we want to update example.com.example.com in zone example.com, so `domain=example.com@example.com`, after parsing, the `__HOST` will be `example.com`, not expected `example.com.example.com`.
> ddns-scripts: fix parsing of parameters

- net/crowdsec-firewall-bouncer/Makefile
Description:
updated to new upstream release version 0.0.33
Run tested: mediatek/filogic, BPI-R3, Openwrt 24.10.1
> crowdsec-firewall-bouncer: update to 0.0.33

- lang/rust/Makefile
- lang/rust/patches/0001-Update-xz2-and-use-it-static.patch
- net/netavark/Makefile
Compile tested: rockchip/armv8, tested with bottom and netavark
Run tested: nanopi-r5c (bottom)
Description:
Update rust to 1.85.0
Fixes: #26582
> [openwrt-23.05] rust: update to 1.85.0

- utils/mbpoll/Makefile
Maintainer: Jens Wagner <jens@wagner2013.de>
Compile tested: aarch64_cortex-a53, RPi3, 24.10.1
Run tested: mipsel_24kc, RT-AX53U, 24.10.0, via USB/RTU to Waveshare RTU Relais(B)
Description: mbpoll is a command line interface to Modbus RTU & TCP, it is based on libmodbus.
Supported functions:
- read discrete inputs
- read and write binary outputs (coil)
- read input registers
- read and write output registers (holding register)
> mbpoll: Modbus command line interface

- multimedia/yt-dlp/Makefile
Maintainer: me
Compile tested: HEAD, x86/64
Run tested: snapshot, x86/64, QEMU
- yt-dlp reports the correct version
- tested downloading a few videos
Description:
- bump to 2025.05.22
Changelog: https://github.com/yt-dlp/yt-dlp/releases/tag/2025.05.22
> yt-dlp: bump to 2025.05.22

- net/netbird/Makefile
| [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64) | [x86](https://openwrt.org/docs/techref/targets/x86) | 64 | WOVIBO | B75 M.2 Intel LGA 1155 DDR3 | N/A | OpenWrt SNAPSHOT r29883-d989d9a8ec |
```shell
reboot
```
- Changelog:
- Update to [0.45.2](https://github.com/netbirdio/netbird/releases/tag/v0.45.2) …
> netbird: update to 0.45.2

- libs/liburcu/Makefile
Description:
- update of the library `knot` depends on
> liburcu: update to version 0.15.3

- net/samba4/Makefile
Force the default C version to -std=gnu17.
Maintainer:
> samba4: fix building with GCC 15.1

- net/snort3/Makefile
Removed upstreamed and bumped to latest release:
110-packet_capture-Fix-compilation-with-GCC-13.patch
Changelog: https://github.com/snort3/snort3/releases/tag/3.8.1.0
```
o"  )~   Version 3.8.1.0
Copyright (C) 2014-2025 Cisco and/or its affiliates. All rights reserved.
Using DAQ version 3.0.19
Using Hyperscan version 5.4.2 2025-05-27
Using libpcap version 1.10.5 (with TPACKET_V3)
Using LZMA version 5.6.2
Using OpenSSL 3.5.0 8 Apr 2025
Using PCRE2 version 10.42 2022-12-11
Using ZLIB version 1.3.1
``` 
Maintainer: me
> snort3: update to 3.8.1.0

- mail/bogofilter/Makefile
- mail/bogofilter/patches/010-no-docs.patch
Maintainer: me
Description:
Update bogofilter package to 1.3.0.rc1. This is partially in response to https://github.com/openwrt/packages/pull/26400#issuecomment-2848152109.
> bogofilter: update to 1.3.0.rc1

- net/scapy/Makefile
> scapy: update to 2.6.1

- net/netbird/Makefile
- `netbird` update to [0.45.3](https://github.com/netbirdio/netbird/releases/tag/v0.45.3)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.45.2...v0.45.3
- N/A
```shell
reboot
``` …
> netbird: update to 0.45.3

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/usr/lib/ddns/update_cloudflare_com_v4.sh
Compatible with domain without the `@` symbol, consistent with the previous.
Fixes 8c55d089 ("ddns-scripts: fix parsing of parameters for cloudflare.com")
**Maintainer:** @feckert 
Compatible with domain without the `@` symbol, consistent with the previous.
Fixes 8c55d089 ("ddns-scripts: fix parsing of parameters for cloudflare.com")
---
- **OpenWrt Version:** 24.10.1
- **OpenWrt Device:** Easepi R1
---
> ddns-scripts: fix parsing of parameters for cloudflare.com

- net/fping/Makefile
- net/fping/test.sh
Maintainer: @nikil
Compile tested: OpenWrt 24.10.1 r28597-0425664679
Run tested: OpenWrt 24.10.1 r28597-0425664679
Description:
- update to version 5.3
- added test.sh file for ci testing
Fixes #26223
> fping: update to version 5.3

- lang/golang/golang/Makefile
Fixes https://github.com/openwrt/packages/issues/26446.
---
- armsr-armv7 snapshot sdk, Fedora 42 (gcc 15.1.1)
- malta-be snapshot sdk, Ubuntu 25.04 (gcc 14.2.0)
N/A
---
```bash
```
> golang: Fix host build compatibility with GCC 15

- multimedia/go2rtc/Makefile
- multimedia/go2rtc/patches/0001-v4l2-drop-codegen-file-to-be-able-to-build-with-CGO-.patch
- multimedia/go2rtc/patches/0002-Fix-support-linux-riscv64-1639.patch
- multimedia/go2rtc/patches/0003-add-riscv64-platform-for-v4l2-package.patch
- multimedia/go2rtc/patches/0004-v4l2-eanble-risc-v-64-support.patch
- multimedia/go2rtc/patches/0005-v4l2-fix-riscv64-build-and-go-fmt.patch
- multimedia/go2rtc/patches/0006-v4l2-fix-compile-on-unsupported-arch-mips.patch
Maintainer: me
Compile tested: x86_64, OpenWrt master d63663601d
Run tested: x86_64, Master, camera's continue to work
Description:
- Update version to 1.9.9
- Add patches to fix build with CGO=0
- Fix excludes to drop example binaries
> go2rtc: update to 1.9.9

- utils/bcm27xx-eeprom/Makefile
bcm2711:
https://github.com/raspberrypi/rpi-eeprom/blob/v2025.05.08-2712/firmware-2711/release-notes.md#2025-05-08-implement-tcp-window-for-net-boot-latest
bcm2712:
https://github.com/raspberrypi/rpi-eeprom/blob/v2025.05.08-2712/firmware-2712/release-notes.md#2025-02-12-fixup-change-to-disable-37v-pmic-output-on-cm5-no-wifi-latest
https://github.com/raspberrypi/rpi-eeprom/blob/v2025.05.08-2712/firmware-2712/release-notes.md#2025-03-03-fix-bootloader-pull-configuration-on-2712d0-latest
https://github.com/raspberrypi/rpi-eeprom/blob/v2025.05.08-2712/firmware-2712/release-notes.md#2025-03-10-add-boot_partition-filter-plus-sdram-init-fixes-latest
https://github.com/raspberrypi/rpi-eeprom/blob/v2025.05.08-2712/firmware-2712/release-notes.md#2025-03-19-log-the-fan-speed-at-boot-latest …
> bcm27xx-eeprom: update to v2025-05-08-2712

- libs/libarchive/Makefile
This is a feaure and bugfix release.
New features:
bsdtar: support --mtime and --clamp-mtime (#2601)
lib: mbedtls 3.x compatibility (#2602)
7-zip reader: improve self-extracting archive detection (#2088) xar: xmllite support for the XAR reader and writer (#2388) zip writer: added XZ, LZMA, ZSTD and BZIP2 support (#2137, #2284, #2391) zip writer: added LZMA + RISCV BCJ filter (#2403)
Notable security fixes:
rar: do not skip past EOF while reading (#2584)
rar: fix double free with over 4 billion nodes (#2598) rar: fix heap-buffer-overflow (#2599)
warc: prevent signed integer overflow (#2568)
tar: fix overflow in build_ustar_entry (#2588)
Notable bugfixes:
ibarchive: fix FILE_skip regression (#2642)
compress: Prevent call stack overflow (#2649)
iso9660: always check archive_string_ensure …
> libarchive: bump to 3.8.1

- net/openssh/Makefile
**Maintainer:** @tripolar 
Users don't have access to system-wide settings when running clients like `ssh` and `sftp`.
---
- **OpenWrt Version:** HEAD (7193539c98)
- **OpenWrt Target/Subtarget:** x86_64/generic
- **OpenWrt Device:** PC Engines APU-6
---
```bash
```
> openssh: wrong permissions on /etc/ssh

- net/sing-box/Makefile
**Description:**  
Update sing-box package to the version 1.11.13.  
📝 Release Notes
changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.11.13
---
- **OpenWrt Device:** Xiaomi Redmi ax6000
---
```bash
```
> sing-box: Update to 1.11.13

- utils/bc/Makefile
Force the default C version to -std=gnu17.
Maintainer: @krant
> bc: fix building with GCC 15.1

- libs/oniguruma/Makefile
In addition to version bump, this is the min version needed to compile with GCC 15.1
Maintainer: @cotequeiroz
> oniguruma: bump to 6.9.10

- net/unbound/Makefile
- net/unbound/files/unbound.init
Compile tested: n/a, just comment removal in init script
Run tested: Bananapi BPI-R3, mediatek/filogic, OpenWrt SNAPSHOT r29909-ba674fea40
Description:
* trivial fix for #25963 to workaround the current "10 line parsing limit"
> unbound: bring back the service to the startup menu

- libs/gdbm/Makefile
- libs/gdbm/patches/100-Add-missing-include.patch
Added a patch to fix build for GCC 15.1
Maintainer: @Naoir
> gdbm: bump to 1.25 and include fix for GCC 15.1

- libs/openldap/Makefile
Package has a consistent Config.in file, but it isn't added to all parts of the file.
libopenldap is unable to be built with `--enable-debug` because the Config.in is never attached to `Package/libopenldap/Config`
> libopenldap: Add missing Config.in hook

- utils/rtl_433/Makefile
- utils/rtl_433/files/rtl_433.conf
- utils/rtl_433/files/rtl_433.init
Maintainer: me
Compile tested: x86_64, OpenWRT 24.10 stable branch on 6/3/2025 for aarch64
Runtime tested: aarch64, OpenWRT 24.10 stable brance on 6/3/2025
OpenWRT Device: gl-inet mt6000
Description:
Updates rtl_433 to its latest release. This also adds a simple init script and sample config file.
changelog: https://github.com/merbanan/rtl_433/releases/tag/25.02
> rtl_433: bump version to 25.02

- net/dnsdist/Makefile
**Package details**
Maintainer: me / @rgacogne 
Description: fixes CVE-2025-30193
**Indication of run testing**
OpenWrt version: 24.10
OpenWrt target/subtarget: x86_64
OpenWrt device: docker
**Formalities**
[x] Review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
If your PR contains a patch
[ ] Make sure that it can be applied by `git am`
[ ] It must be refreshed to avoid offsets, fuzzes, etc by `make package/foo/refresh V=s`
[ ] It must be in a way that it is potentially upstreamable (subject, commit description, etc.), and we must try to upstream it so we have fewer patches and fewer.
> [24.10] dnsdist: update to 1.9.10

- utils/rtty/Makefile
changelog: https://github.com/zhaojh329/rtty/releases/tag/v8.1.5
(cherry picked from commit ba10392cb5ad47c483c0e863a4b2874704a5a8cb)
> [24.10] rtty: update to 8.1.5

- libs/ethtool-lua/Makefile
- utils/prometheus-node-exporter-lua/Makefile
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/ethtool.lua
The ethtool-lua library is a partial re-implementation of the [ethtool](https://cdn.kernel.org/pub/software/network/ethtool/). The goal is to provide the CLI queries and configuration options as a Lua API.
The reason for starting this library, was the desire for a nice and efficient way to query DSA switch statistics in the [prometheus-node-exporter-lua](https://openwrt.org/packages/pkgdata/prometheus-node-exporter-lua) on [OpenWRT](https://openwrt.org/) devices. Existing suggestions around the internet focussed mainly on calling the [ethtool](https://cdn.kernel.org/pub/software/network/ethtool/) CLI program and parsing the output. This is neither elegant nor efficient, as the collection time for this implementation was 300% higher on my rtl838x based switch running …
> ethtool-lua + prometheus-node-exporter-lua plugin

- utils/docker-compose/Makefile
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.37.0)
---
---
> docker-compose: Update to version 2.37.0

- utils/syncthing/Makefile
**Maintainer:** @aparcar, @brvphoenix
- Backport 1.29.7 to 24.10 #26710
- Changelog: https://github.com/syncthing/syncthing/compare/v1.29.6...v1.29.7
---
- **OpenWrt Device:** Qemu
---
---
> [24.10] syncthing: bump 1.29.7

- lang/python/python-platformio/Makefile
**Maintainer:** me @vidplace7 
Update host-only package PlatformIO from `v6.1.16` to `v6.1.18` (minor)
---
- **OpenWrt Target/Subtarget:** bcm27xx/bcm2710
- **OpenWrt Device:** Raspberry Pi CM3
---
> python-platformio: Update to v6.1.18

- utils/bluez/Makefile
- utils/bluez/patches/010-adapter-Fix-up-address-type-when-loading-keys.patch
**Maintainer:** none
Backport an upstream patch to fix load link-keys with kernel >= 6.10, see bluez/bluez#973.
---
- **OpenWrt Device:** see immortalwrt/packages#1614
---
```bash
```
> bluez: fix need re-pairing after daemon restarts

- utils/realtek-poe/Makefile
- utils/realtek-poe/files/etc/uci-defaults/30-poe
Maintainer: me
Compile tested: (not yet)
Run tested: (not yet)
This adjustment makes a compromise between those that would prefer not to complicate the realtek-poe.git source repository and those who want to have PoE work out-of-the-box on Realtek switches -- see realtek-poe.git, commit 2df137ee457155 ("realtek-poe/openwrt: Generate config from board.json")
Switches previously booted with OpenWrt will have an /etc/config/poe file already present, and thus the uci-default shall not take effect.
> realtek-poe: build default config from board.json

- net/zerotier/Makefile
`-isystem ext` makes `#include <miniupnpc/miniupnpc.h>` actually include `ext/miniupnpc/miniupnpc.h`.
we should use `$(STAGING_DIR)/usr/include` as a higher priority system include path.
Fix https://github.com/openwrt/openwrt/issues/18019
**Maintainer:** @<github-user>
Fix https://github.com/openwrt/openwrt/issues/18019
---
- **OpenWrt Version: 24.10.1
- **OpenWrt Target/Subtarget: armsr/armv8
- **OpenWrt Device: virtualbox
---
```bash
```
cannot be upstram, this is a part of openwrt cross compiling path hack.
> zerotier: fix system include path

- lang/python/python-certifi/Makefile
- lang/python/python-chardet/Makefile
- lang/python/python-idna/Makefile
- lang/python/python-requests/Makefile
- lang/python/python-urllib3/Makefile
Maintainer: @commodo @BKPepe 
Compile tested: OpenWRT One 24.10 branch
Description:
Add hostbuild directives for python-requests and it's dependencies. Required for PlatformIO 24.10 backport.
Backport to `24.10`
Cherry-picked PRs:
- #25499
- #25498
- #25497
- #25496
- #25495
Related PRs:
- #26743
> [24.10] python-requests (and deps): add hostbuild

- libs/libjemalloc/Makefile
- net/bind/Config.in
- net/bind/Makefile
**Maintainer:** @pprindeville, @nmeyerhans 
Adding the `jemalloc` package, and allowing `bind` to link against it.
---
- **OpenWrt Version:** HEAD
- **OpenWrt Device:** PC Engines APU6
---
```bash
```
> Add jemalloc and integrate into bind

- libs/libulfius/Makefile
**Maintainer:** @utoni
Backport `libulfius` fix to OpenWRT 24.10
> The current liborcania / libulfius packages do not install to the target, resulting in messages like:
> ```
> Package meshtasticd is missing dependencies for the following libraries:
> liborcania.so.2.3
> libulfius.so.2.7
> ```
> This change corrects the issue by installing the library `.so`s to the target.
(cherry picked from commit 6c62e0fcfecf5a322cba368e5410f5e2f693b411)
Related `master` PR:
- #25527
---
- **OpenWrt Target/Subtarget:** bcm27xx/bcm2710
- **OpenWrt Device:** Raspberry Pi CM3
---
> [24.10] libulfius: Install library on target

- libs/liborcania/Makefile
**Maintainer:** @utoni
Backport `liborcania` fix to OpenWRT 24.10
> The current liborcania / libulfius packages do not install to the target, resulting in messages like:
> ```
> Package meshtasticd is missing dependencies for the following libraries:
> liborcania.so.2.3
> libulfius.so.2.7
> ```
> This change corrects the issue by installing the library `.so`s to the target.
(cherry picked from commit 768b995f980f2875f588ab8f90e5b597cfa4f5d8)
Related `master` PR:
- #25526
---
- **OpenWrt Target/Subtarget:** bcm27xx/bcm2710
- **OpenWrt Device:** Raspberry Pi CM3
---
> [24.10] liborcania: Install library on target

- net/zerotier/Makefile
**Maintainer:** @mwarning
backport https://github.com/openwrt/packages/pull/26730
---
- **OpenWrt Version: 24.10.1
- **OpenWrt Target/Subtarget: armsr/armv8
- **OpenWrt Device: virtualbox
---
> [24.10] zerotier: fix miniupnp path

- utils/mstflint/Makefile
If `nls.mk` is not included and `BUILD_NLS` is set compilation will fail with various undefined references to the `libiconv` library. So this commit includes the missing `nls.mk`.
This fixes #26763.
---
- **OpenWrt Version:** OpenWrt Snapshot
- **OpenWrt Device:** Mellanox Spectrum SN2100
---
> mstflint: add missing nls.mk include

- lang/golang/golang/Makefile
**Maintainer:** @jefferyto, @1715173329
Bump to 1.24.4
> go1.24.4 (released 2025-06-05) includes security fixes to the crypto/x509, net/http, and os packages, as well as bug fixes to the linker, the go command, and the hash/maphash and os packages.
Fixes CVE-2025-4673.
Link: https://github.com/golang/go/issues?q=milestone%3AGo1.24.4+label%3ACherryPickApproved
---
---
- go host package reports correct version
- tested building Syncthing
- Syncthing works as expected and shows as compiled with the correct go version
---
> golang: bump to 1.24.4

- utils/fish/Makefile
**Maintainer:** @jqqqqqqqqqq
Update fish to 3.7.1
---
- **OpenWrt Version: 24.10.1**
- **OpenWrt Target/Subtarget: x86/64**
---
```bash
```
> fish: update to 3.7.1

- sound/sox_ng/Makefile
Fix build errors when libspeex-dev (include files) are discovered running `configure` in the buildbots. Speex is an obsolete codec superseded by Opus. Does anyone want/need this?
> sox_ng: Remove (lib)speex un-expected inclusion by discovery

- admin/btop/Makefile
- admin/btop/patches/001-Fix-incorrect-positioning-and-start-symbol-of-second.patch
Uses https://github.com/aristocratos/btop/pull/1156
```
https://patch-diff.githubusercontent.com/raw/aristocratos/btop/pull/1156.patch
```
**Maintainer:** @1715173329
---
---
```bash
```
> btop: add patch to fix download/upload display

- net/dufs/Makefile
- net/dufs/files/dufs.init
This is no longer required after commit openwrt/procd@2e206dbe77ec ("service: add support for triggers on service/instance data changes").
Also remove unused 'name' field.
---
- **OpenWrt Device:** nanopi-r5c
---
> dufs: do not reload firewall manually

- libs/lttng-ust/Makefile
**Maintainer:** @none
Fixes build on platforms without 64-bit atomics.
Should be cherry-picked to 24.10 branch, as it also plagues builds there:
https://downloads.openwrt.org/releases/faillogs-24.10/mips_24kc/packages/lttng-ust/compile.txt
Fixes: https://github.com/openwrt/packages/issues/26575
Changelog: https://github.com/lttng/lttng-ust/compare/v2.13.5...v2.13.9
---
- **OpenWrt Target/Subtarget:** tegra/generic
- **OpenWrt Device:** trimslice
---
- [✅] I have reviewed the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
> lttng-ust: bump version to 2.13.9

- net/samba4/Makefile
If users are building icu we need to depend on the corresponding shared objects to avoid missing library dependencies, for example:
```
libicui18n.so.77
libicuuc.so.77
```
**Maintainer:** 
Although not maintainers, both of these guys helped to bring this to light and troubleshoot: @hnyman @BKPepe 
Add conditional depends based on discussion in https://github.com/openwrt/packages/pull/26683
---
---
```bash
```
> samba4: add conditional depends

- libs/libtheora/Makefile
**Maintainer:** @flyn-org 
Use CONFIGURE_ARGS instead of defining a custom Build/Configure target.
Set --disable-asm on armeb to fix build error:
```
CC       apiwrapper.lo
In file included from state.h:56,
from apiwrapper.h:24,
from apiwrapper.c:21:
arm/armint.h:24:5: error: #error "Big-endian configurations are not supported by the ARM asm. " "Reconfigure with --disable-asm or undefine OC_ARM_ASM."
24 | #   error "Big-endian configurations are not supported by the ARM asm. " \
|     ^~~~~
```
---
- **OpenWrt Target/Subtarget:** ixp4xx
- **OpenWrt Device:** dlink_dsm_g600
(compile tested only)
---
> libtheora: use CONFIGURE_ARGS, fix build on armeb

- net/simple-captive-portal/Makefile
- net/simple-captive-portal/README.md
- net/simple-captive-portal/files/etc/config/simple-captive-portal
- net/simple-captive-portal/files/etc/hotplug.d/net/00-simple-captive-portal
- net/simple-captive-portal/files/etc/init.d/simple-captive-portal
- net/simple-captive-portal/files/etc/simple-captive-portal/index.html
- net/simple-captive-portal/files/usr/share/simple-captive-portal/capabilities.json
- net/simple-captive-portal/files/usr/share/simple-captive-portal/portal.lua
- net/simple-captive-portal/files/usr/share/simple-captive-portal/redirect.lua
This package intercepts/blocks traffic from 'interface' and redirects http requests to a splash page that you can personalize, stored in '/etc/simple-captive-portal/'.
After clicking on 'connect' the MAC of the client is allowed, for 'timeout' seconds (24h), allowing both IPv4 and IPv6.
If your guest interface defaults to input drop or reject (recommended), make sure to allow tcp 8888-8889 on input (and also dns and dhcp).
(cherry picked from commit e0d761e79b1153a84633ca9a1de9644950148316)
> [24.10] simple-captive-portal: add new package

- libs/libical/Makefile
- libs/libical/patches/001-disable-icu-and-bdb-support.patch
**Maintainer:** @jzapater 
Update libical to the latest 3.0.20 version,
refreshing the single patch in the progress.
---
- **OpenWrt Version:** OpenWrt Snapshot
- **OpenWrt Target/Subtarget:** MediaTek ARM/MT7622
- **OpenWrt Device:** BananaPi R64
---
```bash
```
> libical: update to 3.0.20

- libs/libradcli/Config.in
- libs/libradcli/Makefile
**Maintainer:** @PolynomialDivision, @neheb 
Enable toggling TLS support. The provided Config.in was never sourced from the Makefile, making it impossible to toggle TLS support. This commit adds the necessary Makefile glue to fix this.
Also default to TLS disabled, as was the de-facto case since Config.in was never sourced (and thus the default 'y' never enabled).
> libradcli: fix build options, allow TLS build

- utils/fuse3/Makefile
- utils/fuse3/patches/100-fuse_signals.c-fix-build-warning-when-HAVE_BACKTRACE.patch
- utils/fuse3/patches/101-mount_util.c-restore-symlink-check.patch
FUSE utilities: `fusermount3`, `mount.fuse3` and shared libraries: `libfuse3`
1. Update to version 3.17.2
Fix a bug that may result in incorrect behaviour:
``` C
../util/fusermount.c:1069:17: warning: unsigned conversion from 'long long int' to 'long unsigned int' changes value from '8315462406243767374' to '1397118030' [-Woverflow]
1069 |                 0x736675005346544e /* UFSD */,
|                 ^~~~~~~~~~~~~~~~~~
```
2. Fix build warning when `HAVE_BACKTRACE` is not defined
`BT_STACK_SZ` and `backtrace_buffer` are not used when `HAVE_BACKTRACE` is undefined. Wrap them in `#ifdef`
to avoid a build warning:
``` C
../lib/fuse_signals.c:31:14: warning: 'backtrace_buffer' defined but not used [-Wunused-variable]
31 | static void *backtrace_buffer[BT_STACK_SZ];
| …
```
> fuse3: update to version 3.17.2

- utils/prometheus-node-exporter-lua/Makefile
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/nft_counters.lua
Maintainer: me / @Prototik
Compile tested: QEMU x86_64 VM, OpenWrt master branch
Run tested: QEMU x86_64 VM, OpenWrt master branch
Description:
Allows to export named counters statistics from nftables, thus making a more precise tracking to be possible.
> prometheus-node-exporter-lua: add nftables named counters collector

- net/netbird/Makefile
- `netbird` update to [0.49.0](https://github.com/netbirdio/netbird/releases/tag/v0.49.0)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.45.3...v0.49.0
- N/A
Used a "dirty" installation of the `OpenWrt` image instead of starting with a clean state:
```shell
apk add --allow-untrusted < package name >.apk
reboot
``` …
> netbird: update to 0.49.0

- lang/luabitop/Makefile
Remove myself as a maintainer
**Package details**
Maintainer: not me anymore
Description: update to 1.0.3, remove myself as a maintainer
**Indication of run testing**
OpenWrt version: r28979+3-9a79cdc7ee
OpenWrt target/subtarget: qualcommax/ipq807x
OpenWrt device: Dynalink DL-WRX36
**Formalities**
[x] Review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
If your PR contains a patch
[ ] Make sure that it can be applied by `git am`
[ ] It must be refreshed to avoid offsets, fuzzes, etc by `make package/foo/refresh V=s`
[ ] It must be in a way that it is potentially upstreamable (subject, commit description, etc.), and we must try to upstream it so we have fewer patches and fewer.
> luabitop: update to 1.0.3

- utils/prometheus-node-exporter-lua/Makefile
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/mwan3.lua
Request only 'interfaces' status, as we don't use 'connected' and 'policies' status. On my router with 5 wans / 2 tracking IPs per wan, scrape time goes from 1.90s to 1.30s (still pretty slow but better)
(cherry picked from commit caeb4c1834b68c37647143363bf643b8f79040cc)
> prometheus-node-exporter-lua: mwan3: speed up

- utils/shadow/Makefile
**Maintainer:** none
The package libxcrypt was renamed to xcrypt when added to the core repo [^1].
[^1]: https://github.com/openwrt/openwrt/commit/f544392fc3c6c435e4b9acaca5744abb8ccb0a55
---
- **OpenWrt Target/Subtarget:** no
- **OpenWrt Device:** no
---
> shadow: update build dependencies

- utils/prometheus-node-exporter-lua/Makefile
- utils/prometheus-node-exporter-lua/files/usr/bin/prometheus-node-exporter-lua
netclass collector scrape time goes from 230ms to 170ms
(cherry picked from commit 00d420e8013d3bbf0d457eb89718014724333c47)
> [24.10] prometheus-node-exporter-lua: use buffered io, remove concat

- utils/docker-compose/Makefile
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.37.3)
---
---
> docker-compose: Update to version 2.37.3

- libs/glib-networking/Makefile
- sound/fluidsynth/Makefile
- utils/swanmon/Makefile
**Maintainers:**
@dangowrt
@lvoegl
When compiling glib2 with NLS, it automatically sets linker flags to `-lglib-2.0 -lintl` in pkg-config (.pc) files.
Fixes #26810
```
/openwrt/staging_dir/toolchain-x86_64_gcc-14.2.0_musl/lib/gcc/x86_64-openwrt-linux-musl/14.2.0/../../../../x86_64-openwrt-linux-musl/bin/ld.bfd: cannot find -lintl: No such file or directory
/openwrt/staging_dir/toolchain-x86_64_gcc-14.2.0_musl/lib/gcc/x86_64-openwrt-linux-musl/14.2.0/../../../../x86_64-openwrt-linux-musl/bin/ld.bfd: cannot find -lintl: No such file or directory
/openwrt/staging_dir/toolchain-x86_64_gcc-14.2.0_musl/lib/gcc/x86_64-openwrt-linux-musl/14.2.0/../../../../x86_64-openwrt-linux-musl/bin/ld.bfd: cannot find -lintl: No such file or directory …
```
> treewide: include `nls.mk` when depending on glib2

- utils/syncthing/Makefile
- utils/syncthing/files/stdiscosrv.init
- utils/syncthing/files/strelaysrv.init
**Maintainer:** @aparcar, @brvphoenix 
Fixes: #26829
Also fixes file permissions when creating new keys and uses the same user/group as the main service.
---
---
> syncthing: fix relay and discovery args and permissions

- utils/eza/Makefile
release notes:
0.21.5: https://github.com/eza-community/eza/releases/tag/v0.21.5
0.21.6: https://github.com/eza-community/eza/releases/tag/v0.21.6
---
- **OpenWrt Device:** BananaPi R4
> eza: update to 0.21.6

- utils/realtek-poe/Makefile
* Reduce regularly queried items
* Avoid queuing items endlessly to cap memory usage
backport of https://github.com/openwrt/packages/pull/26789 onto 24.10
**Maintainer:** @Hurricos 
Update realtek-poe to latest commit and add the version field (PKG_VERSION) to enable package upgrades (current version is missing version field and has an assumed version of 0.
As per the [spec](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#makefile-contents-should-contain) I have reset the PKG_RELEASE version to 1 due to the version increase with the addition of PKG_VERSION. 
---
- 24.10.1
- main
- realtek/rtl839x
- HPE JG928A
---
> [24.10] realtek-poe: increase version

- multimedia/yt-dlp/Makefile
Changelog: https://github.com/yt-dlp/yt-dlp/releases/tag/2025.06.30
---
---
> yt-dlp: bump to 2025.06.30

- utils/zsh/Makefile
- utils/zsh/files/zprofile
Currently our zsh package does not source /etc/profile which is the expected behavior to setup environment configs.
**Maintainer:** @msva 
---
- **OpenWrt Version:** x86/64
- **OpenWrt Device:** x86/64
---
```bash
```
> zsh: fix shell not sourcing /etc/profile

- utils/lf/Makefile
- utils/lf/test.sh
https://github.com/gokcehan/lf
---
- **OpenWrt Version:** OpenWrt SNAPSHOT r30244+1-1831966406
- **OpenWrt Target/Subtarget:** ramips/mt7621
- **OpenWrt Device:** ASUS RT-AX54
---
- **OpenWrt Version:** OpenWrt SNAPSHOT r30247+1-978d24ce40
- **OpenWrt Device:** ASUS TUF-AX6000
---
```bash
```
> lf: add new package

- utils/syncthing/Makefile
**Maintainer:** @brvphoenix, me?
- Bump syncthing to 1.30.0
Changelog: https://github.com/syncthing/syncthing/releases/tag/v1.30.0
- Add myself as a maintainer instead of @aparcar according to the discussion in #26856
---
---
> syncthing: bump to 1.30.0

- net/tor/Makefile
Minor release, see the changelog [1] for what's new.
[1] https://gitlab.torproject.org/tpo/core/tor/-/blob/tor-0.4.8.17/ChangeLog
> tor: update to 0.4.8.17 stable

- lang/perl/perl-io-socket-ssl/Makefile
**Maintainer:** @jw2013
**Description:** Update to version 2.094
Versions 2.091 to 2.094 provide fixes related to one-sided SSL shutdowns
Changelog: https://metacpan.org/dist/IO-Socket-SSL/changes
---
- **OpenWrt Target/Subtarget:** mipsel_24kc
- **OpenWrt Device:** RT-AX53U
---
> perl-io-socket-ssl: bump to 2.094

- libs/libssh2/Makefile
**Maintainer:** @jslachta
**Description:** Version bump.
Fixes: #26901
---
- **OpenWrt Target/Subtarget:** ath79/generic
- **OpenWrt Device:** TP-Link Archer C7 v4/v5
> libssh2: update to 1.11.1

- net/modemmanager/Makefile
- net/modemmanager/files/lib/netifd/proto/modemmanager.sh
- net/modemmanager/files/usr/lib/ModemManager/connection.d/10-report-down
**Maintainer:** @feckert 
This commit sets default of `disable_modem` to 1 and disconnects modem. If set otherwise it keeps the modem connected.
---
- **OpenWrt Version:** owrt-24.10.2
---
> modemmanager: change to configuration option disable_modem

- libs/libdeflate/Makefile
* The CMake-based build system now supports Apple Framework builds.
* libdeflate now builds for Windows ARM64EC.
* Made another small optimization to the x86 and ARM CRC32 code.
* Fixed a compiler warning on certain platforms (issue ebiggers/libdeflate#416).
* Fixed bug introduced in 1.20 where incorrect checksums could be calculated if
libdeflate was compiled with clang at -O0 and run on a CPU supporting AVX512.
* Fixed bug introduced in 1.20 where incorrect checksums could be calculated in
rare cases on macOS computers that support AVX512 and are running an older
version of macOS that contains a bug that corrupts AVX512 registers.  This
could occur only if code …
> libdeflate: update to 1.24

- libs/libevdev/Makefile
Apart from documentation and improvements for the meson-based build there are two functional changes since 1.13.1:
```
080d1d0 include: sync event codes with kernel 6.9
d06abb8 Always push changed mt events when syncing
```
---
---
> libevdev: update to 1.13.4

- libs/libwacom/Makefile
See release notes for changes
https://github.com/linuxwacom/libwacom/releases/tag/libwacom-2.16.0
https://github.com/linuxwacom/libwacom/releases/tag/libwacom-2.16.1
---
---
> libwacom: update to 2.16.1

- utils/exfatprogs/Makefile
See https://github.com/exfatprogs/exfatprogs/releases/tag/1.2.9
---
---
> exfatprogs: update to 1.2.9

- utils/lvm2/Makefile
- utils/lvm2/patches/002-const-stdio.patch
Version 2.03.33 - 27th June 2025
================================
Various spelling, grammar, formatting, test, and build script improvements.
Override LC_NUMERIC locale if unsuitable for json_std report format.
Repair raid arrays with transiently lost devices.
Version 2.03.32 - 05th May 2025
===============================
Lvconvert vdopool conversion properly validates acceptable LVs.
Accept thin pool data LV as cacheable LV.
Allow using zram block devices (likely for testing).
Fix lvresize when resizing COW snapshots already covering origin.
Fix lvmdbusd read of executed lvm commands output.
Fix construction of DM UUID for cachevol _cdata and _cmeta devices. …
> lvm2: update to 2.03.33 and libdm to 1.02.207

- sound/libxmp/Makefile
See https://github.com/libxmp/libxmp/releases/tag/libxmp-4.6.3
---
---
> libxmp: update to 4.6.3

- devel/unifdef/Makefile
Using GCC compiler on the host breaks the build due to 'constexpr' being a reserved keyword in C22.
Build expecting the sources to be in GNU17 standard fixes that.
---
- **OpenWrt Device:** n/a
---
> unifdef: fix build with GCC 15

- net/netbird/Makefile
- `netbird` update to [0.49.0](https://github.com/netbirdio/netbird/releases/tag/v0.50.1)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.49.0...v0.50.1
- N/A
Used a "dirty" installation of the `OpenWrt` image instead of starting with a clean state:
```shell
reboot
``` …
> netbird: update to 0.50.1

- net/ddns-scripts/files/usr/share/ddns/default/afraid.org-v2-token.json
The URL for update changed and updates were silently failing with HTTP 404. Fixed the URL
**Maintainer:**
contact@ericleung.dev @ericleun
ddns-scripts support affraid.org but the v2 token update is not working and when it is ran it lead to a 404.
This PR updates the URL so it works again.
---
- **OpenWrt Version: 22.03.0 r19685-512e76967f / LuCI openwrt-22.03 branch git-22.245.77528-487e58a
Ran it on my router logs below:
Before my patch
```
Detect local IP on 'interface'
173441       : #> ip -o addr show dev eth0.2 scope global >/var/run/ddns/***.dat 2>/var/run/ddns/***.err
173441       : Local IP ***' detected on interface 'eth0.2'
173441       : Update needed - L: '***' <> R: '***'
173441       : #> /usr/bin/curl -RsS -o /var/run/ddns/***.dat --stderr …
```
> afraid.org-v2-token.json: Fix 404 on update

- net/csshnpd/Makefile
**Maintainer:** @cpswan
Upstream release aligned to MbedTLS 3.6.4
---
- **OpenWrt Version:** SNAPSHOT, r29706
- **OpenWrt Target/Subtarget:** x86_64
- **OpenWrt Device:** x86_64 VM
---
> csshnpd: Bump to c1.0.14 release

- net/netbird/Makefile
- `netbird` update to [0.50.2](https://github.com/netbirdio/netbird/releases/tag/v0.50.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.50.1...v0.50.2
- N/A
Used a "dirty" installation of the `OpenWrt` image instead of starting with a clean state:
```shell
reboot
``` …
> netbird: update to 0.50.2

- net/samba4/Makefile
https://www.samba.org/samba/history/samba-4.22.3.html
**Maintainer:** orphan
---
- **OpenWrt Version:** x86/64
- **OpenWrt Device:** x86/64-glibc
---
```bash
```
> samba4: update to 4.22.3

- net/netbird/Makefile
- `netbird` update to [0.50.2](https://github.com/netbirdio/netbird/releases/tag/v0.50.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.39.2...v0.50.2
- Cherry picked from: bcb6992f4b07b91ff22dc35cfe6dd80112bcd83e
- PR: https://github.com/openwrt/packages/pull/26954
- Cherry picked from: 9d0a14ed4edc7488cd5e999f6b6bae130b32a69c
- PR: https://github.com/openwrt/packages/pull/26948
- Cherry picked from: 5745ffb5475f2d422acc2b90b94ac5aa2b9211f1
- PR: https://github.com/openwrt/packages/pull/26828
- Cherry picked from: f71550540e43e3f17ac8338140b2c2043f284b4b
- PR: https://github.com/openwrt/packages/pull/26682
- Cherry picked from: …
> [24.10] netbird: update to 0.50.2

- sound/openal-soft/Makefile
**Maintainer:** @dangowrt 
Add open source OpenAL implementation for optional audio support in gzdoom.
---
- **OpenWrt Device:** Core i7-7600U laptop with HDAudio
---
> openal-soft: add package

- utils/lsof/Makefile
**Maintainer:** @mstorchak 
Update to 4.99.5
---
- **OpenWrt Version:** r30028+3-2b0b16f1d1
- **OpenWrt Target/Subtarget:** qualcommax/ipq807x
- **OpenWrt Device:** Dynalink DL-WRX36
---
```bash
```
> lsof: update to 4.99.5

- utils/stress-ng/Makefile
- utils/stress-ng/patches/002-disable-atomics-mips-and-ppc.patch
**Maintainer:** @commodo 
update to 0.19.02 and fix glibc fail to build
---
- **OpenWrt Version:** x86/64
- **OpenWrt Device:** x86/64-glibc
---
```bash
```
> Stress ng: update to 0.19.02 and fix glibc fail to build

- libs/abseil-cpp/Makefile
Maintainer: Austin Lane <vidplace7@gmail.com>
Compile tested: latest master, Fedora compiled
Run tested: MT6000
Description:
Hi all,
This pull intends to fix the currect abseil-cpp, it is missing the install section, and it needs the propagate CXX flag to compile correctly with protobuf.
Tested compilation with the protobuf PR and the netdata PR.
> abseil-cpp: Fix compilation with protobuf and add package install

- utils/prometheus-node-exporter-lua/Makefile
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/textfile.lua
A recent change (00d420e80) removed the `output` function, which textfile.lua was using to output metrics.  So use the underlying output handle instead.
**Maintainer:** @champtar 
**Description:** Fixes a small bug that breaks the `textfile.lua` collector
---
- **OpenWrt Target/Subtarget:** ipq806x/generic
- **OpenWrt Device:** Netgear R7800
---
> prometheus-node-exporter-lua: Fix broken textfile collector

- net/strongswan/Makefile
- net/strongswan/patches/0100-work-around-parse_error-clash.patch
**Maintainer:** me, @Thermi 
This symbol is an enum defined both in wolfssl and strongswan.  This creates a clash in C's flat namespace.  A workaround is to redefine it when we include wolfssl headers, but really one of the other should pick a better name.
---
HEAD
mediatek/filogic
Banana Pi-R4
---
> strongswan: fix build issues around PARSE_ERROR

- libs/libpam/Makefile
Apparently, building with mold linking is not supported.
Closes #26996
**Maintainer:** @nmav 
---
- **OpenWrt Version:** x86/64
- **OpenWrt Device:** x86/64-glibc
---
```bash
```
> libpam: fix build with mold linker

- lang/python/python-uci/Makefile
- lang/python/python-uci/patches/0001-Revert-CI-setup.py-removed-and-testing-updates-in-CI.patch
- lang/python/python-uci/patches/0001-pyproject.toml-remove-it-in-favor-of-setup.py.patch
Maintainer: me
https://gitlab.nic.cz/turris/pyuci/-/tags/v0.10.0
https://gitlab.nic.cz/turris/pyuci/-/tags/v0.10.1
https://gitlab.nic.cz/turris/pyuci/-/tags/v0.10.2
https://gitlab.nic.cz/turris/pyuci/-/tags/v0.10.3
# Upstream (pyuci developers) removed setup.py,
I bring it back to be able to compile it despite
that we do support building packages, which are
using pyproject.toml, but the thing here is
that their pyproject.toml requires setuptools 74.1.0 [1] [2], but Python 3.11 is using bundled setuptools and pip [3] [4]. In current version 3.11.13,
there is still outdated version of setuptools, but it looks like that in the newer version, there will be new one [5].
Once, there is released Python 3.11.14 and updated in OpenWrt, these patches can be dropped.
[1] …
> pyuci: update to version 0.10.3 + add two patches

- net/snort3/Makefile
Add conditional to disable gperftools-runtime depends for powerpc and mips due to inability
to compile introduced with 7345b73c3094e2aa2e085954a584ab15a9e3b939
- **OpenWrt Device:** generic
---
```bash
```
> snort3: remove gperftools dep for mips* and powerpc

- lang/perl/perl-html-parser/Makefile
Added `perl/host` to the `HOST_BUILD_DEPENDS` variable to ensure Perl is available during the host build process. This is required for scripts or tools that rely on Perl on the host system.
Fixes: ebfb47aa7448d46f950164e9d5835da5151182b1 ("perl-html-parser: restructure and update to 3.83")
Reported by @dangowrt in https://github.com/openwrt/packages/commit/ebfb47aa7448d46f950164e9d5835da5151182b1#commitcomment-162422317
> perl-html-parser: add perl/host to HOST_BUILD_DEPENDS

- net/bind/Makefile
Fix a possible assertion failure when stale-answer-client-timeout is set to 0. (CVE-2025-40777)
**Maintainer:** @nmeyerhans 
- **OpenWrt Version:** OpenWrt 24.10
- **OpenWrt Target/Subtarget:** qualcommax/ipq807x
- **OpenWrt Device:** Redmi AX6
- **Tested:** recursive queries, authoritative responses, DNSSEC validation, and dynamic updates via nsupdate
> bind: bump to 9.20.11

- sound/fluidsynth/Makefile
See https://github.com/FluidSynth/fluidsynth/wiki/ChangeLog#fluidsynth-247 for details on changes since 2.4.5.
---
- **OpenWrt Device:** raspberrypi-3b
---
> fluidsynth: update to 2.4.7

- net/nebula/Makefile
**Maintainer:** me ( @yingziwu )
- Bump version to 1.9.6
Changelog: https://github.com/slackhq/nebula/releases/tag/v1.9.6
---
---
> nebula: bump version to 1.9.6

- multimedia/gst1-libav/Makefile
- multimedia/gst1-plugins-bad/Makefile
- multimedia/gst1-plugins-base/Makefile
- multimedia/gst1-plugins-good/Makefile
- multimedia/gst1-plugins-ugly/Makefile
- multimedia/gstreamer1/Makefile
**Maintainer:** @thess @flyn-org 
Update GStreamer packages release 1.26.4.
While at it, package v4l2codecs to make use of stateless video encoding and decoding features typical for embedded devices.
---
- **OpenWrt Target/Subtarget:** aarch64/generic
- **OpenWrt Device:** NanoPi R5C (with kernel options for stateless video codecs enabled, PR to openwrt.git will follow)
---
> gstreamer: update to 1.26.4

- net/cloudreve/Makefile
Major update log: https://github.com/cloudreve/cloudreve/releases/tag/4.0.0
Updated assets build commands.
---
- **OpenWrt Device:** nanopi-r5c
---
> cloudreve: Update to 4.3.0

- utils/rtty/Makefile
**Maintainer:** @me
changelog: https://github.com/zhaojh329/rtty/releases/tag/v9.0.1
---
- **OpenWrt Device:** GL-MT3000
---
> rtty: update to 9.0.1

- libs/libmicrohttpd/Makefile
**Maintainer:** @lynxis
**Description:** libmicrohttpd: update to 1.0.2
---
- **OpenWrt Version:** main / c1c11120069b8e04ad4b0c6e815d2e3421944933
- **OpenWrt Target/Subtarget:** ramips/mt7621
- **OpenWrt Device:** TP-Link Archer C6 v3
> libmicrohttpd: update to 1.0.2

- net/sing-box/Makefile
Update sing-box package to the version 1.11.15.
(cherry picked from commit [b9ac3c5](https://github.com/openwrt/packages/commit/b9ac3c5e7d6ffc0f1ee4fc84e166d7f27d807d30))
📝 Release Notes
changelog: https://github.com/SagerNet/sing-box/releases/tag/v1.11.15
---
- **OpenWrt Device:** Xiaomi Redmi AX6000
---
```bash
```
> [24.10] Sing-box update to 1.11.15

- net/natmap/Makefile
**Maintainer:** @ysc3839 and me
update to 20250721
---
---
```bash
```
> natmap: update to 20250721

- net/rsync/Makefile
- net/rsync/files/rsyncd.init
- net/rsync/files/rsyncd.json
**Maintainer:** @mstorchak 
Rsyncd only needs a subset of all capabilities so create a dedicated user with these capabilities. This is better from both a security and an isolation perspective than running as root.
---
```bash
```
> rsync: run as regular user rather than as root

- net/netbird/Makefile
- `netbird` update to [0.51.2](https://github.com/netbirdio/netbird/releases/tag/v0.51.2)
- Full changelog: https://github.com/netbirdio/netbird/compare/v0.50.2...v0.51.2
- N/A
Used a "dirty" installation of the `OpenWrt` image instead of starting with a clean state:
```shell
reboot
``` …
> netbird: update to 0.51.2

- utils/rng-tools/Makefile
- utils/rng-tools/files/rngd.init
**Maintainer:**  @hnyman @nwf @pprindeville ???
For better security and isolation, used the -D option to run as newly created unprivileged user.
---
---
```bash
```
> rngd-tools: run as unprivileged user

- CONTRIBUTING.md
**Maintainer:** N/A
Update the commit subject example in CONTRIBUTING.md to match the documented guidelines,
ensuring it uses lowercase after the package prefix.
---
- **OpenWrt Version:** N/A
- **OpenWrt Target/Subtarget:** N/A
- **OpenWrt Device:** N/A
---
> CONTRIBUTING.md: fix commit subject example format

- utils/docker-compose/Makefile
> docker-compose: Update to version 2.39.1

- admin/atop/Makefile
**Maintainer:** @robimarko 
2.11.0 will not compile with GCC15, so update to 2.12.0. It also fixes CVE-2025-31160.
Fixes: #27085
---
- **OpenWrt Version:** main
- **OpenWrt Target/Subtarget:** ramips/mt7621
- **OpenWrt Device:** no
---
```bash
```
> atop: update to 2.12.0

- net/hev-socks5-tunnel/Makefile
**Description:** update to 2.12.0
---
---
> [24.10] hev-socks5-tunnel: update to 2.12.0

- net/hev-socks5-tproxy/Makefile
**Description:** update to 2.9.0
---
---
> [24.10] hev-socks5-tproxy: update to 2.9.0

- utils/bluez-tools/Makefile
- utils/mstflint/Makefile
**Maintainer:**
- `mstflint` @tk154
- `bluez-tools` @CarlosDerSeher
Change SECTION variable value from `Utilities` to `utils`,
probably a confusion with the variable CATEGORY.
---
- **OpenWrt Version:** N/A
- **OpenWrt Target/Subtarget:** N/A
- **OpenWrt Device:** N/A
---
> msftlint and bluez-tools: fix SECTION variable typo 

- net/softethervpn5/Makefile
For some reason, the ncurses.pc file for the host build gets installed in host instead of hostpkg. Just override the whole thing. The tool built doesn't even use ncurses.
**Maintainer:** nobody
> softethervpn5: fix compilation without OS ncurses

- multimedia/yt-dlp/Makefile
Bump yt-dlp to 2025.07.21
Changelog: https://github.com/yt-dlp/yt-dlp/releases/tag/2025.07.21
---
---
> yt-dlp: bump to 2025.07.21

- utils/dbus/Makefile
**Maintainer:** @robimarko 
Update the 1.16.2 and adapt Makefile to meson build system.
---
- **OpenWrt Target/Subtarget:** x86/64glibc
---
```bash
```
> dbus: update to 1.16.2

- utils/dbus/Makefile
- utils/dbus/files/dbus.init
- utils/dbus/files/dbus.json
**Maintainer:** @robimarko 
Running as a dedicated dbus users is better from both a security and an isolation perspective than running as root.
- **OpenWrt Device:** generic
---
```bash
```
> dbus: run as regular user rather than as root

- net/openlist/Makefile
Fixes https://github.com/openwrt/packages/issues/27011
**Maintainer:** @1715173329
The openlist/alist mount has never been implemented, it is just a placeholder and does not depend on fuse. https://github.com/openwrt/packages/issues/27011
---
- **OpenWrt Version:** 24.10.2
- **OpenWrt Device:** virtualbox
---
```bash
```
> openlist: Remove dependency on fuse

- net/modemmanager/Makefile
**Maintainer:** @feckert 
`/etc/dbus-1/system.d/org.freedesktop.ModemManager1.conf` needs to be 644 so that it can be read to prevent the following since dbus runs as an unprivileged user:
```
dbus-daemon[12465]: Encountered error 'Failed to open "/etc/dbus-1/system.d/org.freedesktop.ModemManager1.conf": Permission denied' while parsing '/etc/dbus-1/system.d/org.freedesktop.ModemManager1.conf
```
---
---
```bash
``` …
> modemmanager: change permissions on dbus file

- net/hev-socks5-tunnel/Makefile
**Description:** update to 2.13.0
https://github.com/heiher/hev-socks5-tunnel/releases/tag/2.13.0
---
---
> hev-socks5-tunnel: update to 2.13.0

- lang/golang/golang-values.mk
**Maintainer:** @jefferyto 
Golang does not support CGO on ppc64:
/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/go-cross/pkg/tool/linux_amd64/link: external linking not supported for linux/ppc64
---
- **OpenWrt Target/Subtarget:** qoriq/generic
- **OpenWrt Device:** qemu
---
> golang: disable CGO for ppc64

- net/openlist/Makefile
Fixes https://github.com/openwrt/packages/issues/27011
(cherry picked from commit 68c60fdc5d8b42b3179fc341e6033288f1aaad06)
**Maintainer:** @1715173329
cherry-picked from master PR #27136
---
- **OpenWrt Version:** 24.10.2
- **OpenWrt Device:** virtualbox
---
```bash
```
> [openwrt-24.10] openlist: Remove dependency on fuse

- lang/php8/Makefile
https://www.php.net/ChangeLog-8.php#8.3.24
---
- **OpenWrt Version:** bcm27xx/bcm2709
- **OpenWrt Target/Subtarget:** bcm27xx/bcm2709
- **OpenWrt Device:** Raspberry Pi Model B
---
```bash
```
> [24.10] php8: update to 8.3.24

- net/knot/Makefile
**Maintainer:** @salzmdan
**Description:** Release upgrade (https://www.knot-dns.cz/2025-07-29-version-348.html)
---
- **OpenWrt Version:** 7.2.2
- **OpenWrt Target/Subtarget:** mvebu/cortexa9
- **OpenWrt Device:** Turris Omnia
---
```bash
```
> knot: update to version 3.4.8

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Compile tested: x86_64, Dell EMC Edge 640vn, OpenWrt 24.10.2
Run tested: x86_64, Dell EMC Edge 640vn, OpenWrt 24.10.2
Description:
fixes: https://github.com/openwrt/packages/issues/27146
supercedes: https://github.com/openwrt/packages/pull/27159
> adblock-fast: bugfixes: status & TLD check with unbound

- CONTRIBUTING.md
**Maintainer:** N/A
Follow the rule from the Submission Guidelines:
https://openwrt.org/submitting-patches#submission_guidelines
And the shared formal check:
https://github.com/openwrt/actions-shared-workflows/blob/ba03db3b5ae747ed9f38df6c96eb4a37a9f7f7c5/.github/workflows/formal.yml#L37-L43
And this commit 07c12180097283a7a53d14d173d7a7e6a1c43be8
---
- **OpenWrt Version:** N/A
- **OpenWrt Target/Subtarget:** N/A
- **OpenWrt Device:** N/A
---
> CONTRIBUTING.md: accept only real names in the SoB

- utils/kmod/patches/020-build-allow-to-install-over-dirty-dir.patch
**Maintainer:** @jdub
When building kmod-32 package for the first time (clean build_dir), it builds and installs fine. When building for 2nd time, sometimes (probably some race condition?) it fails to build in install step with following error:
```shell
for tool in insmod lsmod rmmod depmod modprobe modinfo; do \
ln -s kmod /tmp/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/kmod-32/ipkg-install/usr/bin/$tool; \
done
ln: failed to create symbolic link '/tmp/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/kmod-32/ipkg-install/usr/bin/insmod': File exists
ln: failed to create symbolic link '/tmp/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/kmod-32/ipkg-install/usr/bin/lsmod': File exists
ln: failed to create symbolic link …
```
> kmod: fix build failure in install step over dirty build dir

- net/adguardhome/Makefile
- net/adguardhome/files/adguardhome.config
- net/adguardhome/files/adguardhome.defaults
- net/adguardhome/files/adguardhome.init
- net/adguardhome/files/adguardhome.json
Maintainer: @dobo90, me
Compile tested: mediatek/filogic on 24.10.1; x86/64 on 24.10.1 and snapshot
Run tested: mediatek/filogic on 24.10.1, Zyxel EX5601-T0 ubootmod (T-56); x86/64 on 24.10.1 and snapshot, QEMU
- config migration works as expected
- no config
- old config path
- new config path
- custom config path (warning)
- all the relevant directories have correct permissions set
- version check returns the correct version
- service starts in ujail and can access all relevant files and directories without any permission warnings
- web UI loads with the migrated config
- statistics and query logs keep loading from the configured work directory
- service logs to syslog instead of stdout
- DNS keeps resolving
TODO:
Description:
Run AdGuard Home without …
> adguardhome: run as an unprivileged user

- utils/kmod/patches/020-build-allow-to-install-over-dirty-dir.patch
**Maintainer:** @jdub
When building kmod-32 package for the first time (clean build_dir), it builds and installs fine. When building for 2nd time, sometimes (probably some race condition?) it fails to build in install step with following error:
```shell
for tool in insmod lsmod rmmod depmod modprobe modinfo; do \
ln -s kmod /tmp/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/kmod-32/ipkg-install/usr/bin/$tool; \
done
ln: failed to create symbolic link '/tmp/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/kmod-32/ipkg-install/usr/bin/insmod': File exists
ln: failed to create symbolic link '/tmp/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/kmod-32/ipkg-install/usr/bin/lsmod': File exists
ln: failed to create symbolic link …
```
> [24.10] kmod: fix build failure in install step over dirty build dir

- net/ulogd/Makefile
**Maintainer:** @commodo 
Bump ulogd to version 2.0.9
---
_I have not tested this on an OpenWRT device because I don't have an OpenWRT device available for development purposes. I hope that the maintainer can test._
---
```bash
```
> ulogd: bump to version 2.0.9

- net/uspot/Makefile
**Description:** Update uspot to Git HEAD (2025-08-02)
Makefile edits related to introduction of an eBPF module and a missing dependency in uspotfilter.
---
- **OpenWrt Version:** master / 24.10
- **OpenWrt Target/Subtarget:** ath79/generic, ramips/mt7621, x86/64
Please cherry-pick to 24.10 once merged, thanks 🙏
I'll deal with 23.05 (due to non-cherry-pickable MIRROR_HASH)
> uspot: update to Git HEAD (2025-08-02)

- lang/php8/Makefile
libpcre2's JIT support is controlled with a compile-time flag. When PHP is compiled against it (external libpcre2 - not PHP's bundled version) as in our use-case, then it tries to auto-detect whether JIT support is enalbed or not - but this is done based on a guess when cross-compiling.
So instead of guessing, we need to tell the actual OpenWrt configuration of libpcre2 to PHP.
- **OpenWrt Version:** https://github.com/openwrt/openwrt/commit/93a48afe96444b3f9f2468b959399aecacb2cbb2 
- **OpenWrt Target/Subtarget:** i386/legacy & bcm27xx/bcm2708
- **OpenWrt Device:** VirtualBox VM & Raspberry Pi 2
---
```bash
```
> php8: link PCRE2 JIT usage to actual library configuration

- net/xinetd/Makefile
Cannot use C23 as it uses generic function pointers.
**Maintainer:** @feckert
> xinetd: fix compilation with GCC15

- utils/docker-compose/Makefile
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.39.2)
---
---
> docker-compose: Update to version 2.39.2

- libs/unixodbc/Makefile
Fixes compilation with GCC15. Properly fixing this is too convoluted.
**Maintainer:** @heil
> unixodbc: compile as gnu11

- utils/fx/Makefile
Maintainer: @dynasticorpheus 
Compile tested: Ubuntu 23.04 x64 / OpenWrt SNAPSHOT @ https://github.com/openwrt/packages/commit/36b1dd75fd9da1ea13f1ce1ee679c6b3c9c402cc
Description: Update to [39.0.1](https://github.com/antonmedv/fx/compare/36.0.3...39.0.1)
> fx: update to 39.0.1

- net/krb5/Makefile
Fixes compilation with GCC 15.
The upstream patch fixing compilation is way too huge to backport.
**Maintainer:** @flyn-org
> krb5: build as C11

- utils/mariadb/Makefile
- utils/mariadb/patches/010-MDEV-36427-FTBFS-with-libxml2-2-14-0.patch
**Maintainer:** 
Backport an upstream patch to fix build with libxml 2.14.
---
- **OpenWrt Version:** 23.05 snapshot
- **OpenWrt Device:** none
---
```bash
```
> [openwrt-23.05] mariadb: fix build with libxml 2.14

- net/kea/Makefile
- net/kea/files/kea.init
https://downloads.isc.org/isc/kea/2.6.4/Kea-2.6.4-ReleaseNotes.txt
**Maintainer:** @pangpang, @rosysong
Update to 2.6.4
---
- **OpenWrt Version:** OpenWrt SNAPSHOT r30792-d79bcc6b6a
- **OpenWrt Target/Subtarget:** qualcommax/ipq807x
- **OpenWrt Device:** Redmi AX6
It has been running well on my router for about a week.
Known issue: This program starts too early during boot. After the system starts, you must run service kea-dhcp4 restart for it to work properly.
For details, see: https://github.com/openwrt/packages/issues/26886
---
> kea: update to 2.6.4

- net/strongswan/Makefile
- net/strongswan/patches/0010-wolfssl-Don-t-undef-PARSE_ERROR-as-headers-included-later.patch
**Maintainer:** @pprindeville @Thermi
Backport an upstream patch to fix build with wolfssl 5.7.6.
---
- **OpenWrt Version:** 23.05 snapshot
- **OpenWrt Device:** none
---
```bash
```
> [openwrt-23.05] strongswan: fix build with wolfssl 5.7.6

- net/net-snmp/Makefile
CONFILTS is changed to CONFLICTS to enable condition.
**Maintainer:** @stintel 
CONFILTS seems to be a typo and is changed to CONFLICTS
- **OpenWrt Version:** openwrt-24.10
---
> packages/net-snmp: fix typo

- net/krb5/Makefile
- net/krb5/patches/0001-do-not-set-root-as-owner.patch
Upstream list of changes is available at
https://web.mit.edu/kerberos/krb5-1.22/krb5-1.22.html.
Of note is that this release fixes the build with GCC 15.1.  As with other recent versions, GCC 15.1 transforms some warnings into errors, and this release remediates those warnings, now errors.
Includes patch not meant for upstream.
---
- **OpenWrt Device:** Generic PC
---
> krb5: update to 1.22

- net/lighttpd/Makefile
- net/lighttpd/patches/020-meson-mod_webdav_min.patch
Description:
lighttpd: update to lighttpd 1.4.80 release hash
Release notes:
https://www.lighttpd.net/2025/8/17/1.4.81/
---
```bash
```
> lighttpd: update to lighttpd 1.4.81 release hash

- libs/abseil-cpp/Makefile
**Maintainer:** me (@vidplace7)
- Update abseil-cpp minor rev. Fixes CVE-2025-0838
- Add CPE package ID [cpe:/a:abseil:common_libraries](https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&orderBy=2.3&keyword=cpe%3A2.3%3Aa%3Aabseil%3Acommon_libraries&status=FINAL)
---
- **OpenWrt Device:** OpenWRT One
---
> abseil-cpp: Update to 20240722.1 LTS

- utils/lxc/Makefile
- utils/lxc/patches/030-start-re-introduce-first-SET_DUMPABLE-call.patch
**Maintainer:** @ratkaj 
6.0.5 is a bug fix release, see:
https://discuss.linuxcontainers.org/t/lxc-6-0-5-lts-has-been-released/24438
Full changelog: https://github.com/lxc/lxc/compare/v6.0.4...v6.0.5
Run-tested: x86/64-glibc (Intel N150 based box)
- **OpenWrt Target/Subtarget:**  x86/64-glibc
- **OpenWrt Device:** Intel N150 based PC
---
```bash
```
> lxc: update to 6.0.5

- utils/rtty/Makefile
**Maintainer:** @me
changelog: https://github.com/zhaojh329/rtty/releases/tag/v9.0.2
---
- **OpenWrt Device:** GL-MT3000
---
> rtty: update to 9.0.2

- utils/syncthing/Makefile
- utils/syncthing/files/stdiscosrv.conf
- utils/syncthing/files/stdiscosrv.init
- utils/syncthing/files/strelaysrv.conf
- utils/syncthing/files/strelaysrv.init
**Maintainer:** @brvphoenix, me
I didn't properly test the argument handling in #27127 and there were issues both with discovery and relay services. This PR rewrites the logic to explicitly set each command line argument when necessary, changes the config format for boolean arguments, but handles them in backward-compatible manner.
Fixes: 47644ba ("syncthing: fix discovery and relay extra args")
---
Both services seem to be starting with all the configured arguments as expected this time around.
---
> syncthing: improve discovery and relay argument parsing

- net/gateway-go/Makefile
**Maintainer:** @IoTServ 
upgrade version, support ipv6 transport for remote access
---
- **OpenWrt Version:** x86-64, OpenWrt master
- **OpenWrt Target/Subtarget:** x86-64, OpenWrt master
- **OpenWrt Device:** VM
---
```bash
```
> gateway-go: update to 2.0.10

- lang/python/python3/Makefile
- lang/python/python3/patches/020-uuid.patch
pkgconfig doesn't work correct for these two packages. Just readd the proper paths.
**Maintainer:** @jefferyto
> python3: fix host uuid and ncurses

- libs/vips/Makefile
Upstream list of changes is available at
https://github.com/libvips/libvips/releases/tag/v8.17.1.
---
- **OpenWrt Device:** Generic PC
---
> vips: update to 8.17.1

- net/adblock-fast/Makefile
- net/adblock-fast/files/README.md
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Compile tested: x86_64, Dell EMC Edge 640vn, OpenWrt 24.10.2
Run tested: x86_64, Dell EMC Edge 640vn, OpenWrt 24.10.2
Description:
README:
* update header
Init-script:
* set an earlier start to get triggers to work
* better str_contains
* improve readability of json() by getting rid of cascading case statements
* add new errors/status messages to get_text()
* prepare get_text() for localization by switching to inline printf
* adjust shellcheck disable comments where needed
* parse unbound config for DNS hijack ports
* test if the archived cache exists on boot and proceed to use it if it does
* add trigger waiting status so that luci app can display correct status
> adblock-fast: update to 1.1.4-r12

- multimedia/yt-dlp/Makefile
Bump yt-dlp to 2025.08.22.
Changelog: https://github.com/yt-dlp/yt-dlp/releases/tag/2025.08.22
---
---
> yt-dlp: bump to 2025.08.22

- libs/libradcli/Config.in
- libs/libradcli/Makefile
**Maintainer:** @nmav.
The provided Config.in was never sourced from the Makefile, making it impossible to toggle TLS support.
This commit adds the necessary Makefile glue to fix this.
Also default to TLS disabled, as was the de-facto case since Config.in was never sourced (and thus the default 'y' never enabled).
(cherry picked from commit 5ffca82f54e7bb611c04ddcc60ee3f81f36cf77e)
---
- **OpenWrt Version: 24.10**
- **OpenWrt Target/Subtarget: x86**
- **OpenWrt Device: NUC**
---
```bash
```
> [24.10] libradcli: fix build options

- lang/python/django-restframework/Makefile
**Maintainer:** @commodo
Assign PKG_CPE_ID to DRF.
---
> django-restframework: assign PKG_CPE_ID

- net/adblock-fast/Makefile
- net/adblock-fast/files/README.md
- net/adblock-fast/files/etc/init.d/adblock-fast
Maintainer: me
Compile tested: x86_64, Dell EMC Edge 640vn, OpenWrt 24.10.2
Run tested: x86_64, Dell EMC Edge 640vn, OpenWrt 24.10.2
Description:
README:
* update header
Init-script:
* set an earlier start to get triggers to work
* better str_contains
* improve readability of json() by getting rid of cascading case statements
* add new errors/status messages to get_text()
* prepare get_text() for localization by switching to inline printf
* adjust shellcheck disable comments where needed
* parse unbound config for DNS hijack ports
* test if the archived cache exists on boot and proceed to use it if it does
* add trigger waiting status so that luci app can display correct status
* do not run adb_config_update on boot, speeding up trigger setup
(cherry picked from commit …
> [24.10] adblock-fast: update to 1.1.4-r12

- multimedia/yt-dlp/Makefile
Backport #27342 to 24.10.
---
---
> [24.10] yt-dlp: bump to 2025.08.22

- utils/lsof/Makefile
adding --without-libtirpc to CONFIGURE_ARGS fixing the issue in the Description Ref.: https://github.com/openwrt/packages/issues/27357 + version bump.
**Maintainer:**
Maxim Storchak [m.storchak@gmail.com](mailto:m.storchak@gmail.com)
Ref.: https://github.com/openwrt/packages/issues/27357
---
- snapshot
- qualcommax/ipq807x
- nbg7815
---
```bash
```
> lsof: fix compilation issue with "libtirpc"

- libs/libtirpc/Makefile
**Maintainer:** @hnyman 
Version 1.3.7 introduced a feature which moved symbols into an optional database section[1]. Add corresponding configure args to fix the build with our packages.
- **OpenWrt Target/Subtarget:** x86/64 (using external toolchain from snapshot)
- **OpenWrt Device:** Not run tested, only build tested
---
```bash
```
> libtirpc: fix build for client packages

- net/ampr-ripd/Makefile
- net/ampr-ripd/files/99-ampr-ripd
- net/ampr-ripd/files/ampr-ripd-config
- net/ampr-ripd/files/ampr-ripd-init
Maintainer: Dan Srebnick (K2IE)
Compile tested:  x86 and aarch64
Run tested: x86 and aarch64 23.05.5 and 24.10.0
Description:
This package is intended for licensed radio amateurs who wish to participate on the Net 44 IPIP mesh.  You must be assigned a network via the ARDC portal.  See https://portal.ampr.org/ for more information.
> ampr-ripd: initial package release

- net/nginx/Makefile
**Maintainer:** @Ansuel
Looking at the official CPE dictionary [1], `cpe:/a:nginx:nginx` was only used until 1.21.4 inclusively. Later it was renamed to `cpe:/a:f5:nginx`, and it showed up in a few more non-contiguous versions numbers after 1.21.4.
In all nginx security advisories [2] starting from year 2024, the CPE ID used is `cpe:/a:f5:nginx_open_source`. This includes versions 1.25.0 and newer.
Update the CPE ID to the newest known value of `cpe:/a:f5:nginx_open_source` used in nginx's own security advirosies/CVEs.
[1]: https://nvd.nist.gov/products/cpe
[2]: https://nginx.org/en/security_advisories.html
This should be applied to OpenWrt 24.10 (nginx 1.26.1) and 23.05 (nginx 1.25.0) as well, so that generated SBOMs would contain the correct CPE ID for those nginx …
> nginx: update CPE ID

- net/sing-box/Makefile
**Maintainer: me
The tiny version disables tailscale by default for small package size. OpenWrt also has the tailscale package as an alternative. We prefer to keep the base version has the same build tags with the upstream releases for compatibility.
---
- **OpenWrt Version: snapshots
- **OpenWrt Target/Subtarget: x86/x86-64
- **OpenWrt Device: x86
---
```bash
```
> sing-box: add variant tiny

- net/acme-common/Makefile
- net/acme-common/files/acme.uci-defaults
/etc/init.d/acme start migration in the crontab should also delete the existing /etc/init.d/acme start line.
Otherwise, on every sysupgrade that carries forward existing configurations, a new 'acme renew' line is added to the crontab.
Also, do not add an 'acme renew' crontab line if it already exists.
**Maintainer:** @feckert @tohojo 
Currently, I'm getting a new `0 0 * * * /etc/init.d/acme renew` line added to my crontab every time I do a snapshot upgrade that preserves my configuration. 
I traced this to `net/acme-common/files/acme.uci-defaults`:
1. It  adds that line when it sees `acme start` in the crontab as part of a migration to `acme renew`.
2. Since the migration doesn't actually remove the `acme start` line from the crontab, the `acme renew` line gets re-added …
> acme-common: cleanup acme start crontab migration

- net/stunnel/Makefile
Update stunnel to latest version 5.75
---
- **OpenWrt Version: master**
- **OpenWrt Target/Subtarget: x86/64**
- **OpenWrt Device: APU3**
Starting without config:
```
root@G3-10940 ~ # stunnel -v
[.] stunnel 5.75 on x86_64-openwrt-linux-gnu platform
[.] Compiled/running with OpenSSL 3.5.2 5 Aug 2025
[!] Invalid configuration file name "-v"
[!] realpath: No such file or directory (2)
```
---
> stunnel: update to the latest version 5.75

- net/modemmanager/Makefile
- net/modemmanager/files/lib/netifd/proto/modemmanager.sh
modemmanager: add missing ppp ifname option value
modemmanager: always reset the init_eps if not configured
---
- **OpenWrt Version: master**
- **OpenWrt Target/Subtarget: x86/64**
- **OpenWrt Device: APU3**
---
> modemmanager: always add ifname option to ppp connection and delete initial eps 

- net/snort3/Makefile
Changelog: https://github.com/snort3/snort3/releases/tag/3.9.5.0
- **OpenWrt Device:** Intel N150 PC
---
```bash
```
> snort3: update to 3.9.5.0

- net/netbird/Makefile
- net/netbird/files/netbird.init
- Supersedes: https://github.com/openwrt/packages/pull/27354.
- Removed unnecessary parameters from the `netbird` init script that attempted to reestablish the connection when changing the `wan` state, this should be managed by `netbird` itself.
- Updated `netbird` multiple times (0.52.2, 0.53.0, and 0.55.1) to maintain a version history:
- **0.52.2**: Introduced [profiles feature](https://docs.netbird.io/how-to/profiles) and moved the configuration from `/etc/netbird/config.json` to `/var/lib/netbird`. This poses a risk of configuration loss on OpenWrt, as `/var` is a link to `/tmp`. This behavior has been [reported …
> netbird: update to 0.55.1, cleanup init script, add support for profile feature

- net/lighttpd/Makefile
- net/lighttpd/patches/020-meson-mod_webdav_min.patch
Description:
lighttpd: update to lighttpd 1.4.82 release hash
Release notes:
https://www.lighttpd.net/2025/9/12/1.4.82/
```bash
```
> lighttpd: update to lighttpd 1.4.82 release hash

- libs/cjson/Makefile
**Maintainer:** @karlp
This is a bugfix release
Full release notes available at:
https://github.com/DaveGamble/cJSON/releases/tag/v1.7.19
---
- **OpenWrt Version:** snapshot r29619
- **OpenWrt Device:** x86 VM
---
> cjson: update to 1.7.19

- net/ampr-ripd/Makefile
- net/ampr-ripd/files/99-ampr-ripd
- net/ampr-ripd/files/ampr-ripd-config
- net/ampr-ripd/files/ampr-ripd-init
- net/ampr-ripd/test.sh
**Maintainer:** @k2ie
ampr-ripd is a modified RIPv2 listener that provides route
information for ARDC IPIP Mesh tunnels.  It is intended for use
only by licensed amateur radio operators.
cherry picked using -x from commit 19249742cda92b6895ba236ca6fb3acac5abeacc and commit 551ef4a7c1abe3be192d7eba9f7a193e54e92dd0
backported from PR #27375 and #26259
---
- **OpenWrt Version:** 24.10.1
- **OpenWrt Target/Subtarget:** bcm27xx-bcm2711
- **OpenWrt Device:** RPi CM4
---
> [24.10] ampr-ripd: add new package

- net/lighttpd/Makefile
- net/lighttpd/patches/020-meson-mod_webdav_min.patch
- net/lighttpd/patches/030-Revert-TLS-modify-TLS-defaults-to-MinProtocol-TLSv1.3.patch
**Maintainer:** me (@gstrauss)
Backport: #27259 and #27435
lighttpd: update to lighttpd 1.4.82 release hash
Release notes:
https://www.lighttpd.net/2025/8/13/1.4.80/
https://www.lighttpd.net/2025/8/17/1.4.81/
https://www.lighttpd.net/2025/9/12/1.4.82/
---
Compile tested: arm_cortex-a9 OpenWrt 24.10
---
```bash
```
> lighttpd: update to lighttpd 1.4.82 release hash - backport to openwrt 24.10

- lang/php8/Makefile
https://www.php.net/ChangeLog-8.php#8.2.29
---
- **OpenWrt Version:**  v23.05.6
- **OpenWrt Target/Subtarget:** mxs
- **OpenWrt Device:** Duckbill
---
> [23.05] php8: update to 8.2.29

- lang/php8/Makefile
https://www.php.net/ChangeLog-8.php#8.3.25
---
- **OpenWrt Version:** 
- **OpenWrt Target/Subtarget:** mxs
- **OpenWrt Device:** Duckbill
---
> [24.10] php8 update to 8.3.25

- net/lighttpd/Makefile
- net/lighttpd/patches/020-meson-mod_webdav_min.patch
- net/lighttpd/patches/030-Revert-TLS-modify-TLS-defaults-to-MinProtocol-TLSv1.3.patch
**Maintainer:** me (@gstrauss)
Backport: #27259 and #27435
lighttpd: update to lighttpd 1.4.82 release hash
Release notes:
https://www.lighttpd.net/2025/8/13/1.4.80/
https://www.lighttpd.net/2025/8/17/1.4.81/
https://www.lighttpd.net/2025/9/12/1.4.82/
---
Compile tested: arm_cortex-a9 OpenWrt 23.05
---
```bash
```
> lighttpd: update to lighttpd 1.4.82 release hash - backport to openwrt 23.05

- net/hev-socks5-server/Makefile
**Maintainer:** @heiher
Update to 2.10.0.
https://github.com/heiher/hev-socks5-server/releases/tag/2.10.0
---
---
> hev-socks5-server: update to 2.10.0

- net/dnscrypt-proxy2/Makefile
**Maintainer:** @BKPepe
This is a continuation of https://github.com/openwrt/packages/pull/26452 but for version 2.1.14 and some code removed that seemed unnecessary.
- update dnscrypt-proxy2 to version 2.1.14
- add ```GO_PKG_INSTALL_EXTRA:= dnscrypt-proxy/static/``` to fix build error ```src/github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy/templates.go:12:12: pattern static/js/monitoring.js: no matching files found```
---
- **OpenWrt Device:** Generic PC
---
> dnscrypt-proxy2: update to version 2.1.14

- lang/ruby/Makefile
- lang/ruby/patches/010-fix-riscv64-build.patch
- lang/ruby/ruby_find_pkgsdeps
- lang/ruby/ruby_missingfiles
Ruby 3.4.0 is a major release that introduces several changes:
- Adds `it` block parameter reference
- Switches default parser to Prism
- Implements Happy Eyeballs Version 2 in the socket library
- Improves YJIT
- Adds Modular GC
- And more (see changelog for full details)
Subsequent minor releases include:
- 3.4.1: fixes version description
- 3.4.2: routine bugfix release
- 3.4.3: routine bugfix release
- 3.4.4: routine bugfix release (Linux-specific)
- 3.4.5: routine bugfix release, adds GCC 15 support
Packaging changes:
- (NEW) ruby-repl_type_completor (packaging the repl_type_completor gem)
- Refreshed package dependencies
- Updated `ruby_missingfiles` (detects unpacked files) to use `apk`
- Refactored `ruby_find_pkgsdeps` (detects inter-package dependencies) to use the Ruby parser …
> ruby: update to 3.4.5

- net/bind/Makefile
- net/bind/files/named.init
What started in #20183 as a attempt to clean up noise in the logfiles, turned out to be causing denial-of-service for dual-stack and especially IPv6-only environments.
Breaking core network functionality cannot possibly be less important than cosmetic issues, and those affected by log spam can avoid it via other means (e.g. "query-source-v6 none;" in named.conf).
There's no reliable heuristic for determining whether there's IPv6 connectivity at the time bind is started which will catch any and all corner cases, as discussed in #26327.
So, remove this logic for now. If a suitable heuristic can be devised, it can always be added in a subsequent patch, but I have my doubts.
(Also, quote one variable to make shellcheck happy)
Closes: #26327
Closes: #20468
**Maintainer:** @nmeyerhans
<sub>(You …
> bind: don't break IPv6 support

- net/boinc/Makefile
rom_walton:boinc has been deprecated in favour of universityofcalifornia:boinc_client:
https://nvd.nist.gov/products/cpe/detail/DAC161C5-2154-44BF-916A-EACB524E8B8F
Maintainer:
> boinc: fix PKG_CPE_ID

- utils/gnuplot/Makefile
`gnuplot_project:gnuplot `has been deprecated in favour of `gnuplot:gnuplot`:
https://nvd.nist.gov/products/cpe/detail/DB68C9F5-3330-4749-A6F5-61FF041037CC
Maintainer:
> gnuplot: fix PKG_CPE_ID

- lang/python/python-cryptography/Makefile
`cryptography_project:cryptography` has been deprecated in favour of `cryptography.io:cryptography`:
https://nvd.nist.gov/products/cpe/detail/2EBA50FC-F3F9-40D5-82BD-EFB67F761153
Maintainer:
> python-cryptography: fix PKG_CPE_ID

- libs/cjson/Makefile
`cjson_project:cjson` has been deprecated in favour of `davegamble:cjson`: https://nvd.nist.gov/products/cpe/detail/70BC45DA-D915-4A1D-96AF-84A6CECEE148
Maintainer:
> cjson: fix PKG_CPE_ID

- lang/python/python-certifi/Makefile
**Maintainer:** @cotequeiroz
Assign PKG_CPE_ID to python-certifi and update the package to version 2025.8.3.
Backport of #27245 to 24.10.
---
- **OpenWrt Version:** OpenWrt 24.10
- **OpenWrt Target/Subtarget:** NXP Layerscape / ARMv8 64-bit based boards
---
> [24.10] python-certifi: assign PKG_CPE_ID & update to 2025.8.3

- mail/sendmail/Makefile
- mail/sendmail/files/site.OpenWrt.m4
Buildbot caught an error:
"Berkeley DB file locking needs flock() for version 5.x (and greater?)"
It is caused by leakage of host-installed Berkley DB into the build. Since libmilter is not using the DB and because of convoluted build process of sendmail, we do the workaround  - define a macro which prevents the error without affecting libmilter binary.
> sendmail: fix build on hosts with Berkley DB installed

- net/knot/Makefile
- net/knot/patches/01_zscanner_tests.patch
- net/knot/patches/03_common_stats.patch
**Maintainer:** @salzmdan
**Description:** 
- Release upgrade (https://www.knot-dns.cz/2025-09-18-version-350.html)
- Change of license (details at https://gitlab.nic.cz/knot/knot-dns/-/blob/3.5/distro/pkg/deb/copyright?ref_type=heads)
---
- **OpenWrt Version:** TurrisOS 9.0.0
- **OpenWrt Target/Subtarget:** mvebu/cortexa9
- **OpenWrt Device:** Turris Omnia
---
```bash
```
> knot: update to version 3.5.0

- libs/postgresql/Makefile
- net/haproxy/Makefile
- net/linknx/Makefile
- net/netifyd/Makefile
- net/torsocks/Makefile
uClibc-ng was removed in 2020 from OpenWrt main repo [1]. These things are leftovers.
[1] https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=63fb175203bbf3b336804587c2f5b3a2d8132ec1
cc: @neheb 
Package maintainers:
- postgresql: @dangowrt
- haproxy: @gladiac 
- netifyid: @dsokoloski 
- torsocks: @ja-pa
> treewide: drop anything related to uClibc

- utils/lvm2/Makefile
**Maintainer:** @dangowrt 
remove support of interactive mode in `/sbin/lvm`
Benefits:
- drop dependency on readline and ncurses (-700kb if there are no other users of these libs)
- shrink the `lvm` binary itself (-260k)
Drawback:
- lose interactive shell:
```
lvm> vgchange -ay
4 logical volume(s) in volume group "vg0" now active
lvm>
```
`lvm <subcommand> --params` and `<subcommand> --params` entry points are still available
All use cases in this repo use `lvm <subcommand>` calling convention
---
- **OpenWrt Version:** r31110+2-41aaebad98
- **OpenWrt Target/Subtarget:** qualcommax/ipq807x
- **OpenWrt Device:** Dynalink DL-WRX36
Tested by running the updated lvm binary:
```
PV         VG …
```
> lvm2: disable readline and interactive shell

- admin/syslog-ng/test.sh
It adds a runtime test to verify that the compiled binary in CI/CD runs without segfault and prints the version.
> syslog-ng: add runtime test

- admin/syslog-ng/Makefile
- admin/syslog-ng/files/syslog-ng.conf
Package maintainer: me
No, I am trying to be like others - no run testing (this time). 😆 😆 Waiting for CI/CD.
Release notes:
https://www.syslog-ng.com/community/b/blog/posts/syslog-ng-4-8-3-is-now-available
> syslog-ng: update to version 4.10.0

- net/knot/Makefile
**Maintainer:** @salzmdan
**Description:** 
- Fix problem with hiredis library on some platforms where is automatically detected Redis support.
---
- **OpenWrt Version:** TurrisOS 9.0.0
- **OpenWrt Target/Subtarget:** mvebu/cortexa9
- **OpenWrt Device:** Turris Omnia
---
```bash
```
> knot: fix missing hiredis dependecy on some platforms

- net/frp/Makefile
**Maintainer:** N/A
Change log is available at: https://github.com/fatedier/frp/releases/tag/v0.65.0
- Add NAT traversal configuration options for XTCP proxies and visitors. Support disabling assisted addresses to avoid using slow VPN connections during NAT hole punching.
- Enhanced OIDC client configuration with support for custom TLS certificate verification and proxy settings. Added trustedCaFile, insecureSkipVerify, and proxyURL options for OIDC token endpoint connections.
- Added detailed Prometheus metrics with proxy_counts_detailed metric that includes both proxy type and proxy name labels, enabling monitoring of individual proxy connections instead of just aggregate counts.
---
- **OpenWrt Version: main/snapshot
- **OpenWrt Target/Subtarget: qualcommax/aarch64
- …
> frp: bump to 0.65.0

- libs/gperftools/Makefile
Maintainer: @graysky2
It looks like I will be the one, who will report it to upstream regarding mips (https://github.com/openwrt/packages/pull/21627#issuecomment-3075332950)
> gperftools: allow it for mips

- libs/gperftools/Makefile
Maintainer: @graysky2
Make libunwind support optional depending on package availability.
Previously, gperftools unconditionally enabled libunwind as mandatory dependency, which led to build failures on architectures where libunwind is not provided.
Related to https://github.com/openwrt/packages/issues/27530
> gperftools: make libunwind dependency conditional

- libs/expat/Makefile
**📦 Package Details**
Upstream changelog: https://github.com/libexpat/libexpat/blob/R_2_7_3/expat/Changes
**🧪 Run Testing Details**
- **OpenWrt Version:** trunk
- **OpenWrt Target/Subtarget:** Mediatek/MT7622
- **OpenWrt Device:** Linksys E8450
> expat: upgrade to 2.7.3

- kernel/ovpn-dco/Makefile
**Maintainer:** @zhaojh329 
1. add kmod-crypto-chacha20poly1305 kmod-crypto-lib-chacha20 kmod-crypto-lib-poly1305 for chacha20
2. bump version to 0.2.20250801
---
- **OpenWrt Version:** r31015-20d761cf19
- **OpenWrt Device:** N100 based router
---
> ovpn dco: fix package dependencies and bump version to 0.2.20250801

- net/adblock-fast/Makefile
- net/adblock-fast/files/etc/init.d/adblock-fast
- net/adblock-fast/files/etc/uci-defaults/90-adblock-fast
Maintainer: me
Compile tested: x86_64, Dell EMC Edge 620, OpenWrt 24.10.3
Run tested: x86_64, Dell EMC Edge 620, OpenWrt 24.10.3
Description:
Makefile:
* update version/release Init Script:
* boot up reliability improvements:
- change START from 50 to 20 to ensure procd_add_raw_trigger works on boot
- better logic of checking/using the cache/compressed cache on boot
* new dnsmasq handling/integration logic:
- new logic for checking dnsmasq functionality (similar to dnsmasq init script)
- instead of copying/duplicating adblock-fast files per specified dnsmasq instance, create one file and add softlinks to it for specified dnsmasq instances and make sure it's in the instance's addnmounts
- update dnsmasqConfFile, dnsmasqIpsetFile and dnsmasqNftsetFile to point to the same filename as the …
> [24.10] adblock-fast: update to 1.2.0

- libs/boost/Makefile
**Maintainer:** @ClaymorePT
boostorg.jfrog.io is no longer available for download, so remove it.
use archives.boost.io (fastly cdn) to download first.
---
- OpenWrt Version: r31015-20d761cf19
- OpenWrt Target/Subtarget: x86/64
- OpenWrt Device: N100 based router
---
> boost: fix PKG_SOURCE_URL

- sound/owntone/Makefile
**Maintainer:**
me
Update to version 29.0, see changes here: https://github.com/owntone/owntone-server/releases/tag/29.0
---
- **OpenWrt Version:** trunk
- **OpenWrt Target/Subtarget:** x86
- **OpenWrt Device:** vm
---
> owntone: update to 29.0

- net/nfs-kernel-server/Makefile
**Maintainer:** @graysky2 
Move CONFLICTS definition to the respective v4 packages to avoid creating a recursive dependency.
Fixes: ee3b06e42 ("nfs-kernel-server: provide a NFSv3 and NFSv4 daemon")
Fixes: #27555
---
- **OpenWrt Target/Subtarget:** -
---
> nfs-kernel-server: fix recursive Kconfig dependencies

- net/tailscale/Makefile
Changelog: https://tailscale.com/changelog#2025-09-25
**Maintainer:** me / @mochaaP
**Description:** update tailscale to 1.88.3
---
- **OpenWrt Target/Subtarget:** arm_cortex-a7_neon-vfpv4
- **OpenWrt Device:** AVM FRITZ!Box 7530
---
```bash
```
> tailscale: update to 1.88.3

- net/tunneldigger/Makefile
- net/tunneldigger/files/config.default
- net/tunneldigger/files/tunneldigger.init
**Maintainer:** @PolynomialDivision 
backport of #27448
This is confirmed to be working as a patch on a 23.05 build - it is needed for 24.10 as well
---
- **OpenWrt Version: **
- **OpenWrt Target/Subtarget: **
---
> openwrt-24.10: tunneldigger: add broker_selection option

- net/tunneldigger/Makefile
- net/tunneldigger/files/config.default
- net/tunneldigger/files/tunneldigger.init
**Maintainer:** @PolynomialDivision 
backport of #27448
This is confirmed to be working as a patch on a 23.05 build.
---
- **OpenWrt Version: 23.05 gluon v2023.2.x**
- **OpenWrt Target/Subtarget: **
---
>  openwrt-23.05: tunneldigger: add broker_selection option

- utils/syncthing/Makefile
**Maintainer:** @brvphoenix, me
Bump Syncthing to 2.0.10.
Changelog: https://github.com/syncthing/syncthing/releases/tag/v2.0.10
---
---
> syncthing: bump to 2.0.10

- lang/python/python-packaging/Makefile
- lang/python/python-urllib3/Makefile
**Maintainer:** @BKPepe, @ja-pa, @jefferyto
Update python-hatchling to version 1.27.0.
Update python-packaging to version 25.0.
Update python-urllib3 to version 2.5.0.
---
- **OpenWrt Version:** OpenWrt 24.10
- **OpenWrt Target/Subtarget:** NXP Layerscape / ARMv8 64-bit based boards
---
> python-hatchling, python-packaging, python-urllib3: update to the latest version

- utils/gzip/Makefile
**Maintainer:** @bk138
Release announcement:
https://lists.gnu.org/archive/html/info-gnu/2025-04/msg00007.html
---
- **OpenWrt Target/Subtarget:** powerpc8540/mpc85xx
- **OpenWrt Device:** Turris 1.1
---
```bash
```
> gzip: update to version 1.14

- net/tor/Makefile
Release notes:
https://gitlab.torproject.org/tpo/core/tor/-/blob/tor-0.4.8.18/ChangeLog
> tor: update to version 0.4.18

- net/openvpn/Makefile
- net/openvpn/files/openvpn.options
This lets the --peer-fingerprint openvpn option be parsed which requires a client TLS certificate fingerprint (colon separated SHA256 hash) to match one specified in the option argument, during authentication.
> openvpn: add peer-fingerprint support

- net/openvpn/Config-mbedtls.in
- net/openvpn/Config-openssl.in
- net/openvpn/Config-wolfssl.in
- net/openvpn/Makefile
**Maintainer:** @AuthorReflex @neheb
This is a cherry-pick from https://github.com/openwrt/packages/commit/01fafd69ef276cd3ae80e9a633391d5f7a8d7dfe and https://github.com/openwrt/packages/commit/11e17a3ed625c34501568669303e3f447fe4f693 (see https://github.com/openwrt/packages/pull/25645) to enable DCO by default in the `openvpn` package.
Also cherry-picks 7c88f99 to bump the `PKG_RELEASE`.
Thanks to @sideeffect42 and @wehagy for the work on the initial commits.
---
- **OpenWrt Target/Subtarget:** x86-64
- **OpenWrt Device:** generic
---
> [24.10] openvpn: enable DCO by default

- utils/poemgr/Makefile
**Maintainer:** @blocktrron
* Minor memory leak fix from https://github.com/blocktrron/poemgr/pull/15
* PSX8 + PSX10 + PSX28 support from: https://github.com/blocktrron/poemgr/pull/16
They are now integrated in OpenWrt package. New changes are:
* https://github.com/blocktrron/poemgr/pull/16/commits/17771dd poemgr: Add support for Plasma Cloud PSX28
* https://github.com/blocktrron/poemgr/pull/16/commits/530433d poemgr: Add support for RTL8239 PSE solution
* https://github.com/blocktrron/poemgr/pull/16/commits/8821bad poemgr: Add support for Plasma Cloud PSX8/PSX10
* https://github.com/blocktrron/poemgr/pull/16/commits/ab466a7 poemgr: Add support for IP8008 PSE chip
* https://github.com/blocktrron/poemgr/pull/16/commits/7863fa8 poemgr: Add support to display POE output type …
> poemgr: update to latest HEAD

- utils/docker-compose/Makefile
New upstream release. [Changelog](https://github.com/docker/compose/releases/tag/v2.40.0)
---
---
> docker-compose: Update to version 2.40.0

- utils/mariadb/Makefile
Update to the latest version in 11.8 stable branch.
See https://mariadb.org/11-8-lts-released/ for main changes.
**Maintainer:** @miska
Update to the latest stable version.
---
- **OpenWrt Target/Subtarget:** qualcombe
- **OpenWrt Device:** Turris Omnia NG
---
```bash
```
> mariadb: Update to 11.8.3

- libs/linenoise/Makefile
- libs/sqlite3/Config-cli.in
- libs/sqlite3/Makefile
**Maintainer:** none
1.
Tell `configure` where to find include directories for libreadline and libeditline.
In the case of cross-compilation, `--readline` or `--editline` alone is not enough, configure can't test if the corresponding include file is available:
```
$ grep -E  'CONFIG_SQLITE3_(LIB|READ)'  .config
CONFIG_SQLITE3_LIBEDIT=y
...
Checking for line-editing capability...
Readline support explicitly disabled with --disable-readline
Line-editing support for the sqlite3 shell: none
```
```
$ grep -E  'CONFIG_SQLITE3_(LIB|READ)'  .config
CONFIG_SQLITE3_READLINE=y
...
Checking for line-editing capability...
WARNING: [sqlite-check-line-editing]:  Skipping check for readline.h because we're cross-compiling.
Line-editing support for the sqlite3 shell: none
```
2.
Use …
> sqlite3: fix building with line editing libs

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
Description: Update to v3.2.6
- Fixes [CVE-2025-11230](https://www.haproxy.com/blog/october-2025-cve-2025-11230-haproxy-mjson-library-denial-of-service-vulnerability)
- Updated haproxy PKG_VERSION and PKG_HASH
- See changes: http://git.haproxy.org/?p=haproxy-3.2.git;a=shortlog
> haproxy: update to v3.2.6 (security update)

- net/snort3/Makefile
The libtirpc package is only needed when building with musl, as glibc includes the required RPC functionality. This change  makes libtirpc a conditional dependency and adjusts the build flags accordingly.
Building with x86_64-glibc:
```
...
Feature options:
DAQ Modules:    Dynamic
libatomic:      User-specified
Hyperscan:      ON  
ICONV:          ON
Libunwind:      OFF 
LZMA:           ON
RPC DB:         Built-in
SafeC:          OFF
TCMalloc:       ON
JEMalloc:       OFF
UUID:           ON
NUMA:           OFF
LibML:          OFF
...
```
Building with aarch64_cortex-a76_musl:
```
...
Feature options:
DAQ Modules:    Dynamic
libatomic:      User-specified
Hyperscan:      ON …
```
> snort3: depend on libtirpc only for musl builds
