openwrt/packages

- net/rpcbind/Makefile
- net/rpcbind/files/rpcbind.init
Maintainer: me
Run tested: qemu-arm
Description:
* update to 1.2.5
* fix wrong URL
* adapt to bin/sbin from new version
> rpcbind: update to 1.2.5

- net/nginx/Makefile
- net/nginx/files-luci-support/luci_nginx.conf
- net/nginx/files-luci-support/luci_nginx_ssl.conf
- net/nginx/files-luci-support/luci_uwsgi.conf
this is needed https://github.com/openwrt/luci/pull/2079
> nginx: improve luci config

- net/uwsgi-cgi/Makefile
- net/uwsgi-cgi/files-luci-support/uwsgi.conf
this depends on https://github.com/openwrt/luci/pull/2079 and #6788 
> uwsgi-cgi: improve luci support

- libs/libdmapsharing/Makefile
> libdmapsharing: Update to 3.9.2

- net/dmapd/Makefile
Maintainer: me
Description:
Requires pull request #6645.
> dmapd: update to 0.0.76

- libs/avahi/Makefile
> avahi: Add CPE ID to track CVEs

- net/ariang/Makefile
- net/ariang/files/80_ariang-nginx-support
- net/ariang/files/ariang.conf
This adds nginx support for ariang webui
> ariang: add nginx support

- mail/msmtp/Makefile
Main URL has changed.
Maintainer: unmaintained / @psycho-nico 
> msmtp: Update to 1.6.8

- utils/crelay/Makefile
> crelay: Update to 0.13

- multimedia/gstreamer1/Makefile
> gstreamer1: update to 1.14.2

- multimedia/gst1-plugins-good/Makefile
> gst1-plugins-good: update to 1.14.2

- multimedia/gst1-plugins-base/Makefile
> gst1-plugins-base: update to 1.14.2

- multimedia/gst1-plugins-ugly/Makefile
> gst1-plugins-ugly: update to 1.14.2

- multimedia/gst1-libav/Makefile
> gst1-libav: update to 1.14.2

- libs/libupnp/Makefile
> libupnp: Update to 1.6.25

- net/clamav/Makefile
Maintainer: me
Compile/Run tested: x86_64  OpenWrt SNAPSHOT, r7966-01793e8752
> clamav: enable clamav-milter

- libs/ldns/Makefile
- libs/ldns/patches/100-CVE-2017-1000231.patch
- libs/ldns/patches/101-CVE-2017-1000232.patch
CVE-2017-1000231 and CVE-2017-1000232.
Taken from Fedora.
> ldns: Fix two CVEs

- net/adblock/Makefile
- net/adblock/files/README.md
- net/adblock/files/adblock.sh
Run tested: GL.iNet GL-AR750, OpenWrt SNAPSHOT r7999-36c6ba3735
Description:
* fix uci wrapper calls
* fix link in readme
> adblock: bugfix 3.5.5v2

- libs/libuvc/Makefile
> libuvc: Update to 0.0.6 and switch to codeload

- utils/fio/Makefile
> fio: Update to 3.9

- net/wsdd2/Makefile
- net/wsdd2/patches/001-add_uuid_boot_id.patch
Maintainer: me
Run tested: arm
Description: 
* fixed a invalid triggered error message
> wsdd2: fix invalid error message

- net/i2pd/Makefile
Signed-off-by: David Yang <mmyangfl@gmail.com>
Maintainer: me
Compile tested: openwrt 18.06.0
> i2pd: Update to 2.20.0

- multimedia/motion/Makefile
- multimedia/motion/patches/010-Initialize-the-thread-at-start-of-main.patch
Reported on OpenWrt forums
https://forum.openwrt.org/t/motion-segmentation-fault-after-upgrade-to-4-14-68/21276
> motion: Backport upstream commit to fix running on musl.

- libs/p11-kit/Makefile
> p11-kit: Update to 0.23.14

- libs/apr/Makefile
> apr: Update to 1.6.5

- libs/libuwsc/Makefile
> libuwsc: Update to 3.0.4

- net/samba4/Makefile
- net/samba4/files/samba.config
- net/samba4/files/samba.init
Maintainer: me
Run tested: arm (master)
Description:
* fixes: error 0x80070035
* add triggers to catch hostname changes
> samba4: fix netbios_name

- net/wsdd2/Makefile
- net/wsdd2/files/wsdd2.init
Maintainer: me
Run tested: arm (master)
Description:
* add triggers so changes can be picked up
> wsdd2: fix missing triggers

- CONTRIBUTING.md
Maintainer: @members
Description:
Here are a couple of long-overdue updates. Comments?
@neheb - could you add a sentence or 2 about choosing package source download locations and preferred archive formats. I can include it with this update.
Signed-off-by: Ted Hess \<thess@kitschensync.net\>
> CONTRIBUTING.md: Revise and clarify Copyright and PKG_MAINTANER fields.

- libs/libev/Makefile
Compile tested: ar71xx, ramips, mvebu
Run tested: ar71xx, ramips, mvebu
Signed-off-by: Deng Qingfang <dengqf6@mail2.sysu.edu.cn>
> libev: update to 4.24

- net/nginx/Makefile
> nginx: update to latest release

- utils/rtty/Makefile
> rtty: update to 6.3.0

- utils/hplip/Makefile
- utils/hplip/patches/010-libusb_fix.patch
- utils/hplip/patches/020-remove_cups_dep_on_scan.patch
- utils/hplip/patches/030-replace_unsafe_memcpy_with_memmove.patch
- utils/hplip/patches/040-fix_bool.patch
- utils/hplip/patches/050-fix-glibcisms.patch
Rearranged slightly for consistency between packages.
> hplip: Update to 3.18.9

- lang/python/python-yaml/Makefile
Switch URL to use a more standard location.
Add HTTPS to everything.
Maintainer: @psycho-nico
> python-yaml: Update to 3.13

- net/mwan3/Makefile
- net/mwan3/files/lib/mwan3/mwan3.sh
- net/mwan3/files/usr/libexec/rpcd/mwan3
- net/mwan3/files/usr/sbin/mwan3
- net/mwan3/files/usr/sbin/mwan3track
Maintainer: me
Compile tested: not needed script changes
Run tested: lantiq_xrx200/x86_64, APU3l, OpenWrt 18.06
Description:
- Add commit from pull request https://github.com/openwrt/packages/pull/6199 I think this is usefull but PR originator did not react on my messges. So add this to my PR and we could close this one.
- Add on metric from the main routing table to the dedicated routing table for this interface. So we have the same metric.
- Add uptime information for the interfaces to ubus
- Add downtime information for the interfaces to ubus
> mwan3: improvments

- net/knot/Makefile
- net/knot/patches/01_zscanner_tests.patch
- net/knot/patches/02_knot.conf.patch
Maintainer: me
Run tested: mvebu, Turris Omnia, OpenWRT 15.05
> knot: update to 2.7.3

- net/umurmur/Makefile
Should be a faster download
Maintainer: @fatbob313 
> umurmur: Switch to tarball

- libs/file/Makefile
Get rid of autoreconf to speed up build.
> file: Update to 5.34

- utils/lsof/Makefile
- utils/lsof/patches/003-lsof_selinux.patch
- utils/lsof/patches/004-lsof_ccv.patch
Removed some whitespace and refreshed patches, which was forgotten during
the bump. No actual changes so no release bump.
> lsof: Fix dead URL + cosmetic fixes

- lang/python/openpyxl/Makefile
> openpyxl: Update to 2.5.9

- lang/python/python-mysql/Makefile
> python-mysql: Update to 1.3.13

- lang/python/django-constance/Makefile
> django-constance: Update to 2.3.1

- lang/python/django-restframework/Makefile
> django-restframework: Update to 3.9.0

- utils/hdparm/Makefile
Slightly adjusted Makefile for consistency between projects.
Maintainer: @rkunze 
> hdparm: Update to 9.57

- lang/python/python-requests/Makefile
Switched URL to a sensical version.
Maintainer: @cotequeiroz 
> python-requests: Update to 2.20.0

- libs/libp11/Makefile
- libs/libp11/patches/001-fix-install.patch
Reorganized Makefile a little bit for consistency with other packages.
> libp11: Update to 0.4.9

- utils/yara/Makefile
Switched URL to codeload. The previous redirects to this one.
> yara: Update to 3.8.1

- libs/c-ares/Makefile
> c-ares: Add CPE ID to track CVEs

- utils/openobex/Makefile
- utils/openobex/patches/001-cxx.patch
Add myself as maintainer.
Cosmetic Makefile fixes for consistency between projects.
Maintainer: me
@thess any chance in getting commit access?
> openobex: Update to 1.7.2

- libs/libevdev/Makefile
> libevdev: Update to 1.5.9

- utils/unrar/Makefile
> unrar: Update to 5.6.7

- libs/libsearpc/Makefile
- net/seafile-ccnet/Makefile
Switch to codeload for simplicity. Rearranged Makefile a bit for consistency between Makefiles.
> libsearpc: Update to 3.1.0

- utils/hdparm/Makefile
Add myself as maintainer as agreed previously.
Maintainer: me
https://github.com/openwrt/packages/pull/7241#issuecomment-432132113
> hdparm: Update to 9.58

- lang/python/python-dateutil/Makefile
> python-dateutil: Update to 2.7.5

- lang/python/pytz/Makefile
> pytz: Update to 2018.6

- lang/python/python-certifi/Makefile
> python-certifi: Update to 2018.10.15

- libs/libndpi/Makefile
- libs/libndpi/patches/010-Fixes-600-Backport-of-recent-fixes-e.g.-601.patch
> libndpi: Backport upstream patch to fix compilation

- net/stubby/Makefile
Maintainer: @iamperson347
Description:
Add Jonathan Underwood as co-maintainer
> stubby: add Jonathan Underwood as co-maintainer

- lang/python/python-attrs/Makefile
> python-attrs: Update to 18.2.0

- utils/btrfs-progs/Makefile
- utils/btrfs-progs/patches/010-fix-big-endian.patch
> btrfs-progs: Update to 4.19

- lang/python/django/Makefile
Fixed a race condition in QuerySet.update_or_create() that could result in data loss (#29499).
> django: Update to 1.11.16

- libs/libarchive/Makefile
> libarchive: Update to 3.3.3

- net/nft-qos/Makefile
- net/nft-qos/files/lib/core.sh
- net/nft-qos/files/lib/dynamic.sh
- net/nft-qos/files/lib/monitor.sh
- net/nft-qos/files/lib/priority.sh
- net/nft-qos/files/lib/static.sh
- net/nft-qos/files/nft-qos-dynamic.hotplug
- net/nft-qos/files/nft-qos-monitor.hotplug
- net/nft-qos/files/nft-qos.config
- net/nft-qos/files/nft-qos.init
This is the nftables implementation for qos limit rate
Signed-off-by: Rosy Song <rosysong@rosinson.com>
luci-app is pulled at https://github.com/openwrt/luci/pull/1855
> nft-qos: add new package

- utils/progress/Makefile
- utils/progress/patches/001_set-ncurses-lib.patch
Switched to codeload for easier package bumping
> progress: Update to 0.14

- net/fping/Makefile
Compile tested: ramips, D-Link DIR-860L, OpenWrt master
Run tested: ramips, D-Link DIR-860L, OpenWrt master
Description:
Update fping to 4.1
> fping: Update to 4.1

- utils/dmidecode/Makefile
> dmidecode: Update to 3.2

- libs/qrencode/Makefile
Small Makefile reorganization for consistency.
Maintainer: @jp-bennett 
> qrencode: Update to 4.0.2

- libs/liboping/Makefile
> liboping: Update to 1.10.0

- libs/keyutils/Makefile
- libs/keyutils/patches/04-cflags.patch
Maintainer: @MikePetullo maybe?
> keyutils: Update to 1.5.11

- net/jool/Makefile
Signed-off by Dan Luedtke <mail@danrl.com>
Maintainer: me
> jool: Remove inactive maintainer

- multimedia/crtmpserver/Makefile
Maintainer:  @heil 
Compile tested: only whitespaces
Run tested: only whitespaces
Description:
fix whitespaces
> crtmpserver: fix whitspaces

- lang/python/pillow/Makefile
- lang/python/pillow/patches/010-fix-paths.patch
Switched to pypi for consistency.
> pillow: Update to 5.3.0

- net/nft-qos/Makefile
- net/nft-qos/files/lib/dynamic.sh
- net/nft-qos/files/lib/monitor.sh
Fix identical issue(https://github.com/openwrt/packages/pull/7371) on monitor and dynamic QoS.
Maintainer: me
Compile tested: ar71xx, wr818, master
Run tested: ar71xx, wr818, master
> nft-qos: replace input chain with prerouting for monitor and dynamic

- libs/libopusenc/Makefile
- libs/opusfile/Makefile
- sound/opus-tools/Makefile
Maintainer: @thess / @antonlacon 
Description:
bump to 0.2
> opus-tools: bump to 0.2

- net/keepalived/Makefile
- net/keepalived/files/keepalived.config
- net/keepalived/files/keepalived.init
Maintainer: me / @scrpi 
Run tested: config generation for virtual server
Description:
This change add the possibility to configure a virtual server with uci.
> keepalived: add ipvs uci support

- lang/python/python-pycparser/Makefile
- lang/python/python-pycparser/patches/001-use-external-ply.patch
> python-pycparser: Update to 2.19

- lang/python/python-zope-interface/Makefile
- lang/python/python-zope-interface/patches/001-omit-tests.patch
> python-zope-interface: Update to 4.6.0

- lang/python/python-urllib3/Makefile
> python-urllib3: Update to 1.24..1

- multimedia/gst1-libav/Makefile
- multimedia/gst1-plugins-bad/Makefile
- multimedia/gst1-plugins-bad/patches/001-no-translations.patch
- multimedia/gst1-plugins-bad/patches/002-no-tests.patch
- multimedia/gst1-plugins-bad/patches/003-openssl-deprecated.patch
- multimedia/gst1-plugins-base/Makefile
- multimedia/gst1-plugins-base/patches/001-no-translations.patch
- multimedia/gst1-plugins-base/patches/002-no-tests.patch
- multimedia/gst1-plugins-base/patches/003-no-docs.patch
- multimedia/gst1-plugins-good/Makefile
- multimedia/gst1-plugins-good/patches/001-no-translations.patch
- multimedia/gst1-plugins-good/patches/002-no-tests.patch
- multimedia/gst1-plugins-good/patches/003-no-docs.patch
- multimedia/gst1-plugins-ugly/Makefile
- multimedia/gst1-plugins-ugly/patches/001-no-translations.patch
- multimedia/gst1-plugins-ugly/patches/002-no-tests.patch
- multimedia/gst1-plugins-ugly/patches/003-no-docs.patch
- multimedia/gstreamer1/Makefile
- multimedia/gstreamer1/patches/001-no-translations.patch
- multimedia/gstreamer1/patches/002-no-tests.patch
- multimedia/gstreamer1/patches/003-no-docs.patch
- multimedia/gstreamer1/patches/010-gstplugin-use-lazy-symbol-binding.patch
Disabled a bunch more stuff through the configure script. Refreshed
patches.
Maintainer: @thess @MikePetullo 
I'm not sure patches 2 and 3 are needed. I compiled a build without them. Thoughts?
> gstreamer1: Update to 1.14.4

- net/lftp/Makefile
> lftp: Update to 4.8.4

- net/i2pd/Makefile
> i2pd: Update to 2.22.0

- lang/python/python-requests/Makefile
> python-requests: Update to 2.20.1

- libs/libestr/Makefile
> libestr: Update to 0.1.11

- libs/postgresql/Makefile
> postgresql: Update to 9.6.11

- lang/python/twisted/Makefile
- lang/python/twisted/patches/001-omit-tkconch.patch
- lang/python/twisted/patches/002-omit-tests.patch
> twisted: Update to 18.9.0

- libs/libyaml-cpp/Makefile
Simpler
Maintainer: @StevenHessing 
> libyaml-cpp: Update to 0.6.2 + switch to codeload

- lang/node-mozilla-iot-gateway/README.md
Maintainer: me / @ratkaj 
Compile tested: brcm2708 and mvebu, RPi3 and wrt3200, OpenWrt master
Run tested: brcm2708 and mvebu, RPi3 and wrt3200, OpenWrt master
Description:
Added README.md with instructions.
Signed-off-by: Marko Ratkaj <marko.ratkaj@sartura.hr>
> node-mozilla-iot-gateway: add README.md

- utils/tree/Makefile
> tree: Update to 1.8.0

- lang/python/Flask/Makefile
Update URL to a deterministic one.
> Flask: Update to 1.0.2

- lang/python/Jinja2/Makefile
Switch URL to a deterministic one.
> Jinja2: Update to 2.10

- libs/libcups/Makefile
> libcups: Update to 2.2.9

- mail/nail/Makefile
- mail/nail/patches/010-remove-gssapi.patch
Buildbots are currently failing because of this.
Maintainer: @pfzim 
> nail: Remove GSSAPI dependency

- net/lcdringer/Makefile
> lcdringer: 0.0.3

- libs/libmicrohttpd/Makefile
> libmicrohttpd: Update to 0.9.60

- lang/lua-xavante/Makefile
Switched to codeload + other adjustments.
> lua-xavante: Update to 2.4.0

- lang/lua-wsapi/Makefile
Switched to codeload + other adjustments.
> lua-wsapi: Update to 1.7

- net/Netopeer2/Makefile
- net/Netopeer2/patches/001-fix-for-cmake-build
- net/sysrepo/Makefile
- net/sysrepo/patches/006-update-generated-protobufc-files
Signed-off-by: Mislav Novakovic mislav.novakovic@sartura.hr
Maintainer: me
Compile tested: Broadcom 27xx RPi2 32-bit
Run tested: Broadcom 27xx RPi3 32-bit
Description:
Update to the latest [sysrepo](https://github.com/sysrepo/sysrepo/releases/tag/v0.7.7) release.
> Sysrepo release 0.7.7

- net/krb5/Makefile
- net/krb5/patches/001-fix-uninitialized-warning-errors.patch
> krb5: Update to 1.16.2

- libs/libowfat/Makefile
- libs/libowfat/patches/001-fixbuild.patch
> libowfat: Update to 0.32

- libs/poco/Makefile
- libs/poco/patches/100-configure.patch
- libs/poco/patches/200-strerror.patch
> poco: Update to 1.9.0

- net/unbound/Makefile
- net/unbound/patches/200-openssl-deprecated.patch
Maintainer: me
Tested: TL-Archer-C7v2 (ath79) OpenWrt master
> unbound: update to 1.8.2

- lang/python/python-oauthlib/Makefile
Maintainer: me
Compile tested: brcm47xx & ramips, openwrt master
Description:
Added python3 package, and updated PKG_SOURCE_URL.
Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>
> python-oauthlib: add python3 package

- libs/libcap/Makefile
- libs/libcap/patches/200-change-hardcoded-shell-to-sh.patch
Minor adjustments to Makefile.
> libcap: Update to 2.26

- net/vsftpd/Makefile
- net/vsftpd/patches/010-openssl-deprecated.patch
> vsftpd: Fix compilation without ECC or deprecated APIs

- net/port-mirroring/Makefile
- net/port-mirroring/patches/010-convert-to-unix.patch
- net/port-mirroring/patches/020-fix-musl.patch
Switched to codeload and adjusted Makefile for consistency.
Maintainer: @mmaraya 
> port-mirroring: Update to 1.4.3

- mail/mutt/Makefile
- mail/mutt/patches/010-openssl-deprecated.patch
Added patch to fix compilation without deprecated OpenSSL APIs.
Maintainer: @philenotfound 
> mutt: Update to 1.11.1

- mail/msmtp/Makefile
- mail/msmtp/patches/010-openssl-deprecated.patch
> msmtp: Fix compilation without deprecated OpenSSL APIs

- net/umurmur/Makefile
- net/umurmur/patches/010-deprecated-openssl.patch
> umurmur: Fix compilation without OpenSSL ECC support

- libs/libmraa/Makefile
- libs/libmraa/patches/010-version.patch
It seems git describe is not failing and setting the version properly.
Compile tested: ar71xx mvebu
> libmraa: Add back version patch

- lang/luajit/Makefile
- lang/luajit/patches/010-lua-path.patch
Allows to simplify the Makefile
> luajit: Switch to versioned releases

- .circleci/config.yml
Maintainer: @champtar / @thess 
Description:
Crib some package hash checks from the Travis script.
Noticed no logs were being generated - modified config settings hack
Signed-off-by: Ted Hess \<thess@kitschensync.net>
> CircleCI: Add package HASH check from Travis. Fix build log generation.

- net/clamav/Makefile
> clamav: update to 0.101.0

- net/unbound/Makefile
Maintainer: me
Tested: TL-Archer-C7v2 OpenWrt (master)
Description: bug fix to DNS64
> unbound: update to 1.8.3

- libs/loudmouth/Makefile
- libs/loudmouth/patches/020-openssl-deprecated.patch
> loudmouth: Disable debug and fix no deprecated API compilation

- lang/luv/Makefile
Switched to tarball and rearranged Makefile for consistency.
> luv: Update to 1.22.0-1

- net/nginx/Config.in
- net/nginx/Config_ssl.in
- net/nginx/Makefile
> nginx: add stream SSL and stream SSL preread support

- lang/python/python-requests/Makefile
> python-requests: Update to 2.21.0

- utils/logrotate/Makefile
> logrotate: Update to 3.15.0

- lang/tcl/Makefile
> tcp: Update to 8.6.9

- libs/sqlite3/Makefile
Description:
Hello Etienne,
As discussed. I won't send a pull request for 17.01 as that would kick off another build there basically for nothing :) 
Kind regards,
Seb
> sqlite3: change maintainer

- mail/postfix/Makefile
> postfix: Update to 3.3.2

- lang/python/python-mysql/Makefile
> python-mysql: Update to 1.3.14

- sound/shairport-sync/Makefile
> shairport-sync: Allow usage with uclibc++

- libs/libgpg-error/Makefile
- libs/libgpg-error/patches/001-cross-compile-fix.patch
> libgpg-error: Update to 1.33

- net/samba4/Makefile
> samba4: update to 4.9.4

- utils/tio/Makefile
Rearrange Makefile for consistency.
> tio: Update to 1.32

- net/nut/Makefile
- net/nut/files/nut-server.init
- net/nut/files/nut_server
Maintainer: me / @cshoredaniel 
Compile tested: brcm2708 (Raspberry Pi), openwrt, packages, luci master
Use NUT with existing configuration, modified configuration, verified NUT running as appropriate users, used NUT CGI to check UPS status.
> nut: server init driver updates

- libs/psqlodbc/Makefile
Rearranged Makefile for consistency between packages.
> psqlodbc: Update to 11.00.0000

- net/nginx/Makefile
Update to 1.15.8 and remove PKG_VERSION from modules tarball filename
> nginx: update to 1.15.8 and other

- lang/python/README.md
Maintainer: me
--------------------------------------------------------------------------------
It was a semi-popular request a while back that I put off for a while.
Here's a quick doc.
I'll update it later as things change and I don't forget.
It also lets other people update if something is wrong.
> lang/python/README.md: add doc describing the lang/python subtree

- utils/grep/Makefile
> grep: Update to 3.3

- lang/jamvm/Makefile
Clean up white space and properly clarify the Java version implemented.
Signed-off-by: Daniel Santos <daniel.santos@pobox.com>
Maintainer: Dana H. Myers <k6jq@comcast.net>
Compile tested: ramips, mt7620, v18.06.1
Description:
> jamvm: Clarify and clean up package description

- net/radicale2/Makefile
- net/radicale2/files/radicale2.config
- net/radicale2/files/radicale2.init
- net/radicale2/patches/110-disable-setup_requirements.patch
Maintainer: me / @cshoredaniel 
EDIT: @jefferyto (maintainer of Radicale (1.x))
[**EDIT**: It's ready now]  This isn't ready yet,, but I wanted to make a PR to gather comments.  This is v2 of Radicale CalDAV/CardDAV server for which 1.x is now deprecated (which is currently in the packages repo).  v2 is significantly different so I decided to get a fresh start.
python-dateutils is updated to allow python3 build and a few new dependencies are added.
EDIT: remove merged or no longer relevant PR dependencies
> Radicale 2.x as radicale2

- utils/unzip/Makefile
Run tested: -
Description:
This should fix wrong PKG_CPE_ID
Signed-off-by: Jan Pavlinec <jan.pavlinec@nic.cz>
> unzip: fix PKG_CPE_ID

- libs/libyang/Makefile
- libs/libyang/patches/001-user-types-CHANGE-convert-internal-types-to-canonical
Signed-off-by: Mislav Novakovic mislav.novakovic@sartura.hr
Maintainer: me
Compile tested: Broadcom 27xx RPi2 32-bit
Run tested: Broadcom 27xx RPi3 32-bit
Description:
Update to the latest [libyang](https://github.com/CESNET/libyang/releases/tag/v0.16-r3) release.
> libyang: update to 0.16-r3

- utils/btrfs-progs/Makefile
Remove copyright.
Maintainer: me
> btrfs-progs: Update to 4.20

- net/mwan3/Makefile
- net/mwan3/files/etc/hotplug.d/iface/15-mwan3
- net/mwan3/files/etc/hotplug.d/iface/16-mwan3
- net/mwan3/files/lib/mwan3/mwan3.sh
- net/mwan3/files/usr/sbin/mwan3
- net/mwan3/files/usr/sbin/mwan3rtmon
Maintainer: me
Compile tested: only scripts
Run tested: x86_64 (APU3), OpenWrt master, failover test
Description:
- Lock critical section on rtmon update
- Lock critical section on mwan3 down
- Add logging for critical secion lock
> mwan3: update version

- net/knot/Makefile
> knot: update to 2.7.6

- net/usbip/Makefile
It's versioned and therefore easier to update.
> usbip: Switch usb.ids location to match usbutils

- net/autossh/Makefile
> autossh: Update to 1.4g

- net/clamav/Makefile
> clamav: Update to 0.101.1

- multimedia/motion/Makefile
> motion: Update to 4..2.1

- libs/hwloc/Makefile
> hwloc: Update to 2.0.3

- libs/libsodium/Makefile
> libsodium: Update to 1.0.17

- net/lighttpd/Makefile
- net/lighttpd/patches/020-Disable-auto-loading-mod_authn_file.patch
This should fix #7737
Signed-off-by: David Yang mmyangfl@gmail.com
Maintainer: @MikePetullo
> lighttpd: Fix mod_auth

- utils/prometheus/Makefile
> prometheus: update to 2.7.1

- net/davfs2/Makefile
- net/davfs2/patches/010-main_code_fix.patch
- net/davfs2/patches/100-musl-compat.patch
- net/davfs2/patches/200-davfs2-1.5.4-no-forced-stack-protector.patch
- net/davfs2/patches/300-have_iconv_h.patch
Switched URL to @SAVANNAH for more mirrors.
Added PKG_LICENSE info.
Minor reorganization for consistency between packages.
Maintainer: @fededim 
> davfs2: Update to 1.5.5

- utils/cryptsetup/Makefile
> cryptsetup: Update to 2.0.6

- libs/keyutils/Makefile
- libs/keyutils/patches/010-reproducible-build.patch
> keyutils: Make reproducible

- lang/python/twisted/Makefile
Signed-off-by: Karel Kočí <karel.koci@nic.cz>
Compile tested: Turris Mox, Turris Omnia - OpenWRT master
Run tested: Turris Mox
> twisted: add Python3 variant

- utils/taskwarrior/Makefile
Makefile adjustments for consistency.
Maintainer: @lperkov ??
> taskwarror: Update to 2.5.1

- mail/dovecot/Makefile
- mail/dovecot/patches/100-openssl-deprecated.patch
- mail/dovecot/patches/110-openssl-engine.patch
Fixes https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a9_vfpv3/packages/dovecot/compile.txt
> dovecot: Fix compilation with OpenSSL 1.1

- net/shadowsocks-libev/Makefile
- net/shadowsocks-libev/files/shadowsocks-libev.init
Maintainer: me
Compile tested: malta be on qemu
Run tested: malta be on qemu
Description:
This was mostly motivated by suggestions from @jefferyto in pull request #8233.
> shadowsocks-libev: use jshn.sh for making json config

- lang/python/python-cffi/Makefile
Maintainer: me / @commodo 
Compile tested: armvirt-32, 2019-02-16 snapshot sdk
Description:
> python-cffi: Update to 1.12.1

- net/travelmate/Makefile
- net/travelmate/files/travelmate.init
- net/travelmate/files/travelmate.sh
Run tested: GL-AR750S, OpenWrt SNAPSHOT r9419-d9ab3240a5
Description:
* fix a possible 'reload' race condition
> travelmate: bugfix 1.3.7

- utils/open-vm-tools/Makefile
- utils/open-vm-tools/files/shutdown
- utils/open-vm-tools/files/tools.conf
- utils/open-vm-tools/files/vmtoolsd.init
- utils/open-vm-tools/files/vmware-scsi.hotplug
- utils/open-vm-tools/patches/0001-configure.ac-don-t-use-dnet-config.patch
- utils/open-vm-tools/patches/0002-add-include-sys-sysmacros.h.patch
- utils/open-vm-tools/patches/0003-Use-configure-test-for-struct-timespec.patch
- utils/open-vm-tools/patches/0004-Fix-definition-of-ALLPERMS-and-ACCESSPERMS.patch
- utils/open-vm-tools/patches/0005-Use-configure-to-test-for-feature-instead-of-platfor.patch
- utils/open-vm-tools/patches/0006-Use-configure-test-for-sys-stat.h-include.patch
- utils/open-vm-tools/patches/0007-include-poll.h-instead-of-sys-poll.h.patch
- utils/open-vm-tools/patches/0008-Rename-poll.h-to-vm_poll.h.patch
- utils/open-vm-tools/patches/0009-use-posix-strerror_r-unless-on-gnu-libc-system.patch
- utils/open-vm-tools/patches/0010-Use-uintmax_t-for-handling-rlim_t.patch
- utils/open-vm-tools/patches/0011-Use-off64_t-instead-of-__off64_t.patch
- utils/open-vm-tools/patches/0012-Fix-some-bad-derefs-in-primary-NIC-gathering-code.patch
Add new package,
open-vm-tools is Open Virtual Machine Tools for VMware guest OS
Signed-off-by: Yuhei OKAWA <tochiro.srchack@gmail.com>
Maintainer: me
Compile tested: master and 18.06.2 (x86_64)
Run tested: ESXi 6.5, 6.7 (x86_64)
> open-vm-tools: Add new package open-vm-tools

- net/travelmate/Makefile
- net/travelmate/files/travelmate.sh
Run tested: APU2, AR750s, TL-RE450, HOOTOO TM-05, OpenWrt SNAPSHOT, r9440-0f89c17b57
Description:
* various small tweaks & fixes
* widely tested, ready for forthcoming 19.x branching
> travelmate: release 1.4.0

- net/travelmate/files/README.md
Run tested: -
Description:
* fix typos (provided by @cybrnook)
* add optional wpad requirement (provided by @sindastra)
> travelmate: update readme.md

- libs/vips/Makefile
- libs/vips/patches/010-reproducible-build.patch
> vips: Add Debian's reproducible build patch

- libs/libinput/Makefile
- libs/libinput/patches/010-musl-fix.patch
> libinput: Add missing header to fix compilation

- net/nft-qos/Makefile
- net/nft-qos/files/lib/priority.sh
- net/nft-qos/files/nft-qos.config
Maintainer: me
Compile tested: mips ar71xx, wr818, master
Run tested: mips ar71xx, wr818, master
Description: fix missing semicolon and document improvement
@hnyman @jow-
> nft qos: fix missing semicolon and document improvement

- utils/moreutils/Makefile
> moreutils: Update to 0.63

- net/i2pd/Makefile
- net/i2pd/files/i2pd.config
- net/i2pd/files/i2pd.init
Signed-off-by: David Yang <mmyangfl@gmail.com>
> i2pd: Update to 2.23.0, fix #7845 and #8088

- lang/python/python/patches/001-enable-zlib.patch
- lang/python/python/patches/005-fix-bluetooth-support.patch
- lang/python/python/patches/011-fix-ssl-build-use-have-npn.patch
- lang/python/python/patches/017_lib2to3_fix_pyc_search.patch
git is intollerant when it comes to fuzz. this fixes it.
Maintainer: @commodo / @jefferyto 
No code changes so no release bump.
> python: Refresh patches

- lang/python/python-pyopenssl/Makefile
- lang/python/python-service-identity/Makefile
Maintainer: me / @commodo 
Compile tested: armvirt-32, 2019-02-19 snapshot sdk
Description:
This updates the Python 2 and 3 versions of each package to share the same title field.
This also updates the package title, url and source urls.
> python-pyopenssl,python-service-identity: Update package data

- multimedia/gst1-libav/Makefile
Maintainer: me
Description:
gst1-libav: update to 1.15.2
> gst1-libav: update to 1.15.2

- net/yggdrasil/Makefile
- net/yggdrasil/files/yggdrasil.init
Thanks for quick review & catch @jefferyto
> yggdrasil: remove pkgarch, cleanup space with tabs

- lang/perl-text-csv_xs/Makefile
Maintainer: me, @Naoir
Compile tested: x86_64, generic, HEAD (5a66771)
Run tested: x86_64, generic, HEAD (5a66771), installed on production box
Description:
> perl-text-csv_xs: update to 1.39

- net/travelmate/Makefile
- net/travelmate/files/travelmate.init
- net/travelmate/files/travelmate.sh
Run tested: GL-AR750S, OpenWrt SNAPSHOT r9608-96e0fa94c7
Description:
* fix a json related ressource leak
* add a reload trigger when the wireless config gets changed
* set an interface default 'trm_wwan' (like the LuCI frontend)
* reordered nested loops to optimize the connection handling
> travelmate: 1.4.2

- utils/prometheus/Makefile
- utils/prometheus/patches/no_bzr.patch
> prometheus: update to 2.8.0

- libs/czmq/Makefile
Maintainer: me  @ja-pa 
Compile tested: Turris Omnia (TOS4), OpenWrt 18.06.2
Run tested: Turris Omnia (TOS4), OpenWrt 18.06.2
Description:
This PR adds some package metadata suggested in Issue (fixes https://github.com/openwrt/packages/issues/8500 )
Changes:
-Add URL
-Fix Description and Title
-Add ABI
Signed-off-by: Jan Pavlinec <jan.pavlinec@nic.cz>
> czmq: polishing of Makefile

- net/strongswan/Config.in
- net/strongswan/Makefile
Signed-off-by: Moritz Warning moritzwarning@web.de
Description:
Strongswan occupies around 100 items in menu Netwok/VPN.
This is an attempt to cleanup the items.
> strongswan: collapse menu items

- utils/gddrescue/Makefile
- utils/gddrescue/patches/001-fix_uclibc.patch
Maintainer: me
Compile/Run tested: sunxi r6628-c089671339
> gddrescue: add ddrescue a data recovery tool

- libs/libv4l/Makefile
- libs/libv4l/patches/010-remove-libudev-check.patch
- libs/libv4l/patches/030-getsubopt.patch
Add Alpine Linux patch that fixes a crash under Musl.
> v4l-utils: Update to 1.16.5

- net/wavemon/Makefile
- net/wavemon/patches/010-Scan-screen-resolves-62.patch
Added PKG_BUILD_PARALLEL for faster compilation
> wavemon: Update to 0.9.0

- utils/gammu/Makefile
The InstallDev section needed the same treatment as the Install one.
Maintainer: @aTanW
> gammu: Really fix compilation under 64-bit

- net/snort3/Makefile
- net/snort3/files/snort.config
- net/snort3/files/snort.init
- net/snort3/patches/001-compile.patch
Maintainer: me
Description:
snort3: new package
> snort3: new package

- utils/fio/Makefile
- utils/fio/patches/010-mpcore.patch
Maintainer: me
Compile tested: CNS3xxx
> fio: Fix compilation under mpcore.

- net/rosy-file-server/Makefile
- net/rosy-file-server/files/rosyfs.config
- net/rosy-file-server/files/rosyfs.init
Maintainer: me
Compile tested: ar71xx, wr818, master
Run tested: ar71xx, wr818, master
@hnyman  @jow- 
Description:
This is the configuration management implementation for luci-app-rosy-file-server
https://github.com/openwrt/luci/pull/2404
> rosy-file-server: add new package

- net/unbound/Makefile
> unbound: Fix ECC dependency

- net/nginx/Makefile
> nginx: update to version 1.15.10

- lang/node-arduino-firmata/Makefile
- lang/node-arduino-firmata/files/usr/lib/node/arduino-firmata/lib/arduino-firmata.js
Maintainer: me ,  @blogic 
Compile tested: head r9773-6e060bd, aarch64_cortex-a53_gcc-7.4.0_musl
Run tested: aarch64 (ec2 a1 docker)  (no arduino environment  just a simple test)
Description:
support serialport 7.x
Takeover of PKG_MAINTAINER
Major Makefile Updates
> node-arduino-firmata: support serialport 7.x

- libs/nspr/Makefile
- libs/nspr/patches/001-Makefile.in_rm_BUILD_STRING_and_BUILD_TIME.patch
- libs/nspr/patches/002-Add-ARC-support.patch
- libs/nspr/patches/003-native_and_musl_fix.patch
needed for nss libraries
Maintainer: me tested: x86_64 x86
> nspr: add nspr libs

- net/clamav/Makefile
> clamav: update package to 0.101.2

- utils/powertop/Makefile
- utils/powertop/patches/001-musl-fix-headers.patch
- utils/powertop/patches/002-strerror_r.patch
- utils/powertop/patches/010-src-main-Add-missing-pthread-header.patch
- utils/powertop/patches/020-intel_cpus.cpp-Change-open-parameter-to-const-char.patch
package for monitoring power consumption
depends on #8228 
would be also useful to have CONFIG_CPU_FREQ_STATS
Maintainer: me
Compile/Run tested: x86_64
> powertop: add package

- libs/libstrophe/Makefile
Description:
Installs pkg-config .pc file, helping other packages find libstrophe
> libstrophe: Install pkg-config .pc file

- lang/python/README.md
Description:
This adds more details on the `PYTHON[3]_PKG_SETUP_*` variables, the filespec format, and the build/install processes in general.
> python: Update readme

- libs/file/Makefile
Added some linker flags to reclaim some space.
Compile tested: mvebu ramips
Run tested: Turris Omnia
> file: Update to 5.36

- mail/dovecot/Makefile
- mail/dovecot/patches/100-openssl-deprecated.patch
- mail/dovecot/patches/110-openssl-engine.patch
> dovecot: Fix deprecated API patch

- net/softethervpn5/Makefile
Maintainer: me
Compile tested: arm, bcm53xx (snapshots)
Run tested: arm (mips via qemu)
Description:
* update to 5.01.9670 release
> softethervpn5: update to 5.01.9670

- net/unbound/files/README.md
Maintainer: me
Description: readme change only
> unbound: update readme.md

- multimedia/youtube-dl/Makefile
Maintainer: @ianchi
Co-Maintainer: me (@BKPepe)
Compile tested: cortexa53, Turris MOX, OpenWrt master
Run tested: cortexa53, Turris MOX, OpenWrt master
Description:
- update to version [2019.4.17](https://github.com/ytdl-org/youtube-dl/releases/tag/2019.04.17)
> youtube-dl: update to version 2019.4.17

- lang/lzmq/Makefile
> lzmq: Fix homepage URL

- lang/python/python-twisted/Makefile
- lang/python/python-twisted/patches/001-omit-tkconch.patch
- lang/python/python-twisted/patches/002-omit-tests.patch
Maintainer: me
Compile tested: armvirt-32, 2019-04-18 snapshot sdk
Description:
> python-twisted: Update to 19.2.0, refresh patches

- lang/python/python-hyperlink/Makefile
Maintainer: me
Compile tested: armvirt-32, 2019-04-18 snapshot sdk
Description:
> python-hyperlink: Update to 19.0.0

- net/samba4/Makefile
Maintainer: me
Compile tested: arm (snapshots)
Run tested:
Description:
* fixes openwrt/packages#8721
>  samba4: fix build with parallel jobs

- utils/collectd/Makefile
- utils/collectd/patches/930-fix-lua-callback-registration.patch
Maintainer: @hnyman @jow- 
Compile tested: xrx200 and x86_64(APU3), master
Run tested: lantiq_xrx200 and x86_64(APU3), master, 
Description:
This will enable the lua support for collectd.
The new package name is collectd-mod-lua
> collectd: enable lua support

- utils/slide-switch/Makefile
Maintainer: me
Compile tested: armvirt-32, 2019-04-18 snapshot sdk / ar71xx, 18.06.2 sdk
Run tested: ar71xx, TL-MR3020, 18.06.1
Description:
> slide-switch: Update to 0.9.4

- lang/lua-ev/Makefile
> lua-ev: Add package

- net/nginx/Makefile
Description:
Update nginx to latest stable release 1.16.0
> nginx: update to 1.16.0

- net/miniupnpd/Makefile
- net/miniupnpd/patches/200-remove-default-cflags.patch
> miniupnpd: Fix compilation under glibc

- lang/python/django-appconf/Makefile
- lang/python/django-compressor/Makefile
- lang/python/django-constance/Makefile
- lang/python/django-jsonfield/Makefile
- lang/python/django-picklefield/Makefile
- lang/python/django-postoffice/Makefile
- lang/python/django-restframework/Makefile
- lang/python/django-statici18n/Makefile
- lang/python/django/Makefile
- lang/python/flup/Makefile
- lang/python/gunicorn/Makefile
- lang/python/openpyxl/Makefile
- lang/python/pillow/Makefile
- lang/python/python-dateutil/Makefile
- lang/python/python-mysql/Makefile
- libs/libsearpc/Makefile
- net/seafile-ccnet/Makefile
- net/seafile-seahub/Makefile
- net/seafile-server/Makefile
Maintainer: @kissg1988  --> me
---------------------------------------------------------------------
This change changes the maintainer to
`Alexandru Ardelean <ardeleanalex@gmail.com`
for all Python packages owned by
`Gergely Kiss <mail.gery@gmail.com>`
No functional changes.
> treewide,python: take over maintainership from Gergely Kiss

- net/unbound/Makefile
- net/unbound/files/odhcpd.awk
- net/unbound/files/unbound.sh
Maintainer: me
Tested: Linksys-WRT3200ACM (master)
Description: Bug fixes to resolve #8836 and resolve #8837 
cc: @tribut
> unbound: fix local dns synthesis corner cases

- utils/sumo/Makefile
- utils/sumo/patches/100-configure_fix.patch
Cleaned up Makefile slightly. Updated URL.
> sumo: Update to 1.1.0

- libs/boost/Makefile
- libs/boost/patches/010-uclibc-ng.patch
example: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/i2pd/compile.txt
> boost: Fix compilation with uClibc-ng

- net/dmapd/Makefile
> dmapd: update to 0.0.81

- net/transmission-web-control/Makefile
- net/transmission-web-control/patches/001-remove-ui-original-link.patch
- net/transmission/Makefile
Maintainer: me
Compile tested: [openwrt-sdk-sunxi-cortexa7_gcc-7.4.0_musl_eabi.Linux-x86_64.tar.xz](https://downloads.openwrt.org/snapshots/targets/sunxi/cortexa7/openwrt-sdk-sunxi-cortexa7_gcc-7.4.0_musl_eabi.Linux-x86_64.tar.xz)
Run tested: no
Description:
Transmission Web Control is a custom web UI for Transmission.
https://github.com/ronggang/transmission-web-control/wiki
>  transmission-web-control: add new package

- libs/libimobiledevice/Makefile
- libs/libimobiledevice/patches/010-openssl-deprecated.patch
- libs/libusbmuxd/Makefile
- utils/usbmuxd/Makefile
Description:
Sparked by https://github.com/openwrt/packages/pull/5635 , I updated the packages. I don't use iDevices on my OpenWrt so I can't test it properly.
@michyprima can you test this?
> libimobiledevice packages updated to git

- net/tgt/Makefile
- net/tgt/files/tgt.config
- net/tgt/files/tgt.init
- net/tgt/patches/110-iscsi_tcp-Replace-deprecated-valloc-function.patch
- net/tgt/patches/111-iscsi_tcp-fix-compile-warning.patch
- update to 1.0.77
- apply patches from Rosen Penev for compatibility with uClibc-ng
- add an option for rotation_rate selection
Maintainer: me
Compile tested: ath79, WNDR3800, r9880+3-bd3a18bbe4, musl
Run tested: ath79, WNDR3800, r9880+3-bd3a18bbe4, dd works, rotation rate can be specified
Description:
> tgt: update to 1.0.77

- net/transmission/Makefile
Maintainer: me
Description:
This reverts commit 18c9a03770793e084eab5601d51b21ca4b374f75.
To fix "make menuconfig" shows "recursive dependency detected".
Sorry for my mistake.
> Revert "transmission-web: set conflicts with transmission-web-control"

- net/stubby/files/stubby.init
Signed-off-by: Jonathan G. Underwood <jonathan.underwood@gmail.com>
Maintainer: me
Run tested:
Description:
This fixes the handling of pkis in the UCI configuration file: issue #8888
> [WIP] stubby: fix handling of pkis in config (#8888)

- lang/python/python-packages/Makefile
- lang/python/python3-packages/Makefile
- lang/python/python3-packages/README.md
Maintainer: me
Compile tested: malta/be on QEMU
Run tested: tornado==6.0.2
@laurivosandi
> python3-packages: port from python-packages

- net/samba4/Makefile
- net/samba4/files/samba.init
Maintainer: me
Compile tested: arm (snapshots)
Run tested: arm
Description:
* update to 4.9.7
* add write_list, read_list UCI support
> samba4: update to 4.9.7

- net/tac_plus/Makefile
- net/tac_plus/files/tac_plus.conf
- net/tac_plus/files/tac_plus.init
- net/tac_plus/patches/010-configure-remove-libnsl.patch
Compile tested: 18.06.1@x86_64
Run tested: 18.06.1@x86_64
Description: New package tac_plus (TACACS+ authentication daemon)
Signed-off-by: Bruno Pena <brunompena@gmail.com>
> tac_plus: New package

- mail/postfix/Makefile
- mail/postfix/patches/950-dns_lookup-Fix-compilation-with-uClibc-ng.patch
> postfix: Fix compilation with uClibc-ng

- lang/python/README.md
Maintainer: me, @jefferyto 
---------------------------------------------
By popular demand, via:
https://github.com/openwrt/packages/issues/8892#issuecomment-489992926
> lang/python/README.md: add note about use in other packages feeds

- libs/nss/Makefile
> nss: update to 3.44

- mail/dovecot/Makefile
> dovecot: update to 2.3.6

- lang/python/python-pyasn1-modules/Makefile
Compile tested: armvirt-32, 2019-05-13 snapshot sdk
Description:
> python-pyasn1-modules: Update to 0.2.5

- net/banip/Makefile
- net/banip/files/banip.conf
- net/banip/files/banip.sh
Run tested: GL-AR750S, OpenWrt SNAPSHOT, r9992-86fd8cb435 
Description:
* remove needless sort step to reduce system load
* change maxqueue default in backend and LuCI frontend
to '4' to reduce (default) system load
* cosmetics
> banip: update 0.1.1

- libs/libuwsc/Makefile
- libs/libuwsc/patches/001-fix_find_lua.patch
Maintainer: me
Description:
Lua binding for libuwsc.
> libuwsc: update to 3.3.1

- utils/oath-toolkit/Makefile
- utils/oath-toolkit/patches/oath-toolkit-2.6.2-build-fix.patch
> oath-toolkit: Fix compilation with uClibc-ng

- utils/lxc/Makefile
- utils/lxc/patches/030-prlimit.patch
> lxc: Backport uClibc patch

- net/travelmate/Makefile
- net/travelmate/files/travelmate.sh
Run tested: GL-AR750S / OpenWrt SNAPSHOT, r9992-86fd8cb435
Description:
* fix connection to uplinks with special char '/' in essid
* cosmetics
> travelmate: update 1.4.6

- libs/libfstrm/Makefile
Maintainer: me
Correct issues with TITLE and add URL pointing to the fstrm GitHub Page. Reformat the description so it renders correctly in menuconfig.
Fixes #9022
Signed-off-by: James Taylor <james@jtaylor.id.au>
> libfstrm: fix formality issues

- net/dmapd/Makefile
- net/dmapd/patches/001-make_unit_test_optional.patch
> dmapd: update to 0.0.82

- utils/mg/Makefile
- utils/mg/patches/001-cross_compile_openwrt.patch
- utils/mg/patches/900-musl_compatibility.patch
- utils/mg/patches/901-use_pcre.patch
Maintainer: me 
Compile tested: head r10012-5c742c8, aarch64_cortex-a53_gcc-7.4.0_musl
Run tested: aarch64 (ec2 a1 docker)
Description:
New package for Emacsian.
You can use "Dired", which is Emacsian's favorite.
> mg: add new package - microscopic emacs style editor

- libs/newt/Makefile
> newt: Fix compilation with full NLS

- net/travelmate/Makefile
- net/travelmate/files/travelmate.sh
Run tested: TP-RE450, GL-AR750S
Description:
* tweak 'f_check' function
* code cleanup
> travelmate: update 1.4.7

- libs/slang2/Makefile
Maintainer: me
Compile tested: armvirt-32, 2019-05-23 snapshot sdk
Description:
> slang2: Add oniguruma module

- net/banip/Makefile
- net/banip/files/banip.sh
Run tested: UBNT-ERX, OpenWrt SNAPSHOT r10026-395bef4bba
Description:
* add more IPv4 & IPv6 consistency checks
* various cleanups
> banip: update 0.1.2

- utils/bluez/Makefile
Compile tested: armvirt-64, 2019-05-27 snapshot sdk
Description:
> bluez: Remove bluez-examples

- net/cgi-io/Makefile
The installation name is inconsistent with the code
Maintainer: me
Description:
> cgi-io: Fix bug

- net/banip/Makefile
- net/banip/files/banip.sh
Run tested: UBNT-ERX, OpenWrt SNAPSHOT r10026-395bef4bba
Description:
* change iptables whitelist target from 'ACCEPT' to 'RETURN'
to stop traversing the banIP chain and resume at the next chain
* cosmetics
> banip: update 0.1.3

- utils/dosfstools/Makefile
Compile tested: ramips, arc700
> dosfstools: Fix compilation with full NLS

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/services
- net/ddns-scripts/files/services_ipv6
Maintainer: me / @ffflorian
Run tested: yes
Description:
This adds INWX to the list of DDNS services.
> ddns-scripts: Add INWX service

- libs/opus/Makefile
Maintainer: @thess @antonlacon 
> opus: Update to 1.3.1

- libs/ibrcommon/Makefile
- libs/ibrdtn/Makefile
- libs/ibrdtn/patches/010-Add-operator-to-Bundle-block_elem.patch
- libs/ibrdtn/patches/020-Use-const-iterator-in-const-function-of-MemoryBundle.patch
- libs/ibrdtn/patches/030-Use-std-streamoff-instead-of-std-streampos.patch
- libs/ibrdtn/patches/040-Add-operator-to-BundleID-and-MetaBundle.patch
- net/ibrdtn-tools/Makefile
- net/ibrdtnd/Makefile
- net/ibrdtnd/patches/030-openssl-deprecated.patch
Added upstream and non upstream patches to fix compilation.
Compile tested: ramips, arc700
> ibr*: Switch to uClibc++

- utils/pigz/Makefile
- utils/pigz/patches/001.patch
Signed-off-by: Ken Wong <xinxijishuwyq@gmail.com>
Compile tested: (x86_64,18.06)
Run tested: ((x86_64,18.06)
I have been using it for a while(but my x86 router is running 18.06 mod by lean).
I just build it with the newest openwrt. And test it in VirtualBox. It seems work will.
Description:
> pigz: add package

- libs/libupm/Makefile
- libs/libupm/patches/001-version.patch
- libs/libupm/patches/004-uint8_t.patch
Maintainer: @blogic, me
 Compile tested: ar71xx, LEDE trunk r10251-bec8fb1
 Run tested: NONE
Description:
 update to 2.0.0
add PKG_BUILD_PARALLEL
https://github.com/openwrt/packages/issues/9254
> libupm: update to 2.0.0

- utils/unrar/Makefile
> unrar: Update to 5.7.5

- libs/libfstrm/Makefile
- libs/libnetconf2/Makefile
- libs/libre2/Makefile
- libs/libtins/Makefile
- libs/libuhttpd/Makefile
- multimedia/crtmpserver/Makefile
- net/gnunet-secushare/Makefile
- net/gnunet/Makefile
- net/lora-gateway-hal/Makefile
- net/pagekitec/Makefile
- net/prosody/Makefile
- sound/mocp/Makefile
- utils/i2c-tools/Makefile
- utils/lvm2/Makefile
- utils/oath-toolkit/Makefile
- utils/procps-ng/Makefile
This is inspired by commit openwrt/openwrt@38b22b1e7022d6b386ce25f39d05cc33fc659240 .
Size reduction before compression is huge.
@openwrt/developer , We may need to patch INSTALL_XX to at least warn against symlinks.
```
-rwxr-xr-x 1 yousong yousong  33312 Jun  8 11:51 usr/lib/gnunet/libgnunet_plugin_psycstore_mysql.so
-rwxr-xr-x 1 yousong yousong  33312 Jun  8 11:51 usr/lib/gnunet/libgnunet_plugin_psycstore_mysql.so.0
-rwxr-xr-x 1 yousong yousong  33312 Jun  8 11:51 usr/lib/gnunet/libgnunet_plugin_psycstore_mysql.so.0.0.0
-rw-r--r-- 1 yousong yousong 251992 Jun  8 11:51 usr/lib/libdevmapper.so.1.02
-rw-r--r-- 1 yousong yousong  29088 Jun  8 11:51 usr/lib/libfstrm.so
-rw-r--r-- 1 yousong yousong  29088 Jun  8 11:51 usr/lib/libfstrm.so.0
-rw-r--r-- 1 yousong yousong  29088 Jun  8 11:51 …
```
> treewide: avoid deref symlinks when installing .so

- libs/nss/Makefile
> nss: update to 3.44.1

- libs/p11-kit/Makefile
- libs/p11-kit/patches/010-uclibc.patch
> p11-kit: Fix compilation with uClibc-ng

- net/dnscrypt-proxy/Makefile
- net/dnscrypt-proxy/patches/010-internal.patch
Includes a security fix.
Fixed usage with latest libsodium.
Maintainer: @damianorenfer 
https://github.com/openwrt/packages/issues/9158
> dnscrypt-proxy: Update to latest git revision

- libs/libtorrent/Makefile
- net/rtorrent/Makefile
> RTorrent updates

- libs/protobuf/Makefile
> protobuf: Update to 3.8.0

- libs/libuwsc/Makefile
> libuwsc: update to 3.3.2

- lang/python/python3-bottle/Makefile
Maintainer: me
Compile tested: cortexa53, Turris MOX, OpenWrt master
Run tested: cortexa53, Turris MOX, OpenWrt master
Description:
- update to version 0.12.17
> python3-bottle: update to version 0.12.17

- utils/gkermit/Makefile
- utils/gkermit/patches/010-musl.patch
Cleaned up Makefile for consistency between packages.
Maintainer: @nwf
> gkermit: Fix compilation with -Wimplicit-function-declaration

- libs/libextractor/Makefile
- libs/libextractor/patches/010-musl.patch
Fixes compilation with -Wimplicit-function-declaration
> libextractor: Add missing header

- libs/postgresql/Makefile
- libs/postgresql/patches/001-configure_fixes.patch
Version 11.3 is the current stable relase.
Signed-off-by: Daniel Danzberger <daniel@dd-wrt.com>
Description:
> postgresql: Update to version 11.3

- lang/python/python-sqlalchemy/Makefile
Maintainer: me
Compile tested: Turris MOX, cortexa53, OpenWrt master
Run tested: Turris MOX, cortexa53, OpenWrt master
Description:
- add package [sqlalchemy](https://pypi.org/project/SQLAlchemy/)
Dependencies:
```
>>> import sqlalchemy
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/__init__.py", line 8, in <module>
File "/__init__.py", line 14, in <module>
File "/_collections.py", line 16, in <module>
File "/compat.py", line 110, in <module>
ModuleNotFoundError: No module named 'urllib.parse'
>>>         
>>> import sqlalchemy
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/__init__.py", line 10, in <module>
File "/schema.py", line 12, in <module>
File "/__init__.py", line 8, in <module>
File "/expression.py", line 146, in …
```
> python-sqlalchemy: add package

- net/openfortivpn/Makefile
- net/openfortivpn/files/openfortivpn.config
- net/openfortivpn/files/openfortivpn.init
An open implementation of Fortinet's proprietary PPP+SSL VPN solution
Compile/Run tested: x86
> openfortivpn: add package

- utils/logrotate/Makefile
Various Makefile cleanups.
Maintainer: @bk138
> logrotate: Add ACL support

- libs/libgpg-error/Makefile
- libs/libgpg-error/patches/020-gawk5-support.patch
> libgpg-error: Fix compilation with GAWK 5.0

- net/softethervpn5/Makefile
- net/softethervpn5/patches/001-musl-poll-fix.patch
- net/softethervpn5/patches/002-iconv-defines-fix.patch
- net/softethervpn5/patches/003-iconv-cmake-fix.patch
Maintainer: me
Compile tested: arm (snapshots)
Run tested: arm/qemu (snapshots)
Description:
* update to 5.01.9671
* switch to release tar's
* add cmake iconv and musl patches
> softethervpn5: update to 5.01.9671

- net/adblock/Makefile
- net/adblock/files/README.md
- net/adblock/files/adblock.conf
- net/adblock/files/adblock.sh
Run tested: -
Description:
* clean-up config
- remove youtube source (not working, false positives)
- remove urlhaus source (false positives)
- remove zeus source (discontinued)
> adblock: update 3.6.5-2

- utils/tang/Makefile
- utils/tang/patches/010-makefile.patch
- utils/tang/patches/020-no-systemd.patch
- utils/tang/patches/030-readlink.patch
Added License information.
Cleaned up Makefile for consistency between packages.
Added numerical prefixes to the patches for clarity.
Maintainer: @Tiboris
> tang: Update to version 7

- utils/fio/Makefile
Minor Makefile cleanups.
Maintainer: me
> fio: Update to 3.15

- libs/nss/Makefile
> nss: update to 3.45

- net/sstp-client/Makefile
- net/sstp-client/files/etc/ppp/chap-secrets
- net/sstp-client/files/lib/netifd/proto/sstp.sh
Description: Add netifd script to control SSTP connections.
Script was made by harveyhu2012 and slightly modified by me (rkkoszewski)
It is required for luci-proto-sstp (https://github.com/openwrt/luci/pull/2768)
>  Add netifd script to control SSTP connections.

- libs/leptonica/Makefile
- utils/tessdata/Makefile
- utils/tesseract/Makefile
Maintainer: me
Compile tested: ramips, R6220, 18.06.0-r7188-b0b5c64c22
Run tested: ramips, R6220, 18.06.0-r7188-b0b5c64c22, OCR image to text
Description:
Tesseract is an open source text recognizer (OCR) Engine, available
under the Apache 2.0 license. It can be used directly, or (for
programmers) using an API to extract printed text from images. It
supports a wide variety of languages.
It depends of libleptonica library
> tesseract: leptonica: add package

- net/apfree-wifidog/Makefile
- net/apfree-wifidog/files/wifidogx.init
- net/apfree-wifidog/patches/010-openssl-deprecated.patch
Also added a patch to fix compilation without deprecated OpenSSL APIs.
Minor Makefile cleanups.
Maintainer: @liudf0716 
> apfree-wifidog: Run init script through shellcheck

- net/haproxy/get-latest-patches.sh
Plus some other shellcheck cleanups.
Maintainer: @gladiac1337
> haproxy: Get rid of bashisms from get-latest-patches.sh

- lang/python/MarkupSafe/Makefile
Compile tested: Turris MOX, cortexa53, OpenWrt master
Run tested: Turris MOX, cortexa53, OpenWrt master
Description:
- Improve TITLE and Description
- Remove PKG_UNPACK as it is not necessary
- Correct LICENSE file
> MarkupSafe: Makefile polishing and add src package

- utils/tar/Makefile
> tar: Add zstd capability

- utils/ykpers/Makefile
Cleaned up Makefile for consistency between packages.
Maintainer: @stuwilkins
> ykpers: Update to 1.20.0

- utils/rtklib/Makefile
- utils/rtklib/patches/010-musl.patch
- utils/rtklib/patches/020-no-gfortran.patch
> rtklib: Update to 2.4.3_b32

- net/samba4/Makefile
- net/samba4/files/samba.init
Some performance improvements by batching file writes.
Maintainer: @Andy2244
> samba4: Run init script through shellcheck

- net/ulogd/Makefile
- net/ulogd/patches/010-json-remote.patch
It was requested in #9065 .
Cleaned up Makefile slightly.
Removed inactive maintainer.
Fixes: https://github.com/openwrt/packages/issues/9065
ping @CanadianJeff
> ulogd: Backport JSON network patch

- net/ulogd/Makefile
Maintainer: me
-------------------------------------
Since this package has been abandoned, I don't mind taking it over.
If there are issues with it, I can also investigate, and be a point-man.
> net: ulogd2: add myself as maintainer

- net/stunnel/Makefile
- net/stunnel/files/stunnel.init
Maintainer: me
Compile tested: lantiq_xrx200 and x86_64, APU3, OpenWrt master
Run tested: x86_64, APU3, Openwrt master, start with default config
Description:
Update version to 5.55
Fix shell check warnings
> stunnel: update version to 5.55

- net/zerotier/Makefile
- net/zerotier/patches/0001-find-miniupnpc.h-in-staging-directory.patch
- net/zerotier/patches/0002-remove-pie.patch
- net/zerotier/patches/0003-remove-arm32-conservative-CFLAGS.patch
- net/zerotier/patches/0004-accept-external-linker-flags.patch
Maintainer: me
Compile tested: openwrt master
Run tested: starts, tested with a nexx wt3020
The versioning of this release looks a bit silly. But that is the release tag...
> zerotier: update to zerotier 1.4.0.1

- lang/python/python-pyasn1/Makefile
Compile tested: armvirt-32, 2019-08-01 snapshot sdk
Description:
> python-pyasn1: Update to 0.4.6

- lang/python/python-pyasn1/Makefile
Compile tested: none (cherry-picked from #9648)
Description:
> [openwrt-19.07] python-pyasn1: Update to 0.4.6

- net/stubby/files/README.md
Maintainer: @jonathanunderwood
Compile tested: none (changed README only)
Run tested:  none (changed README only)
> stubby: Fix UCI command in README

- net/nsd/Makefile
- net/nsd/patches/010-musl.patch
- net/nsd/patches/020-openssl.patch
Maintainer: @acinonyx 
Requested at: https://github.com/openwrt/packages/issues/8732
> nsd: Update to 4.2.1

- net/nginx/Makefile
- net/nginx/files-luci-support/luci_nginx.conf
- net/nginx/files-luci-support/luci_nginx_ssl.conf
Run tested: mvebu, WRT1900ACv2
Description:
Update brotli module to the latest git head
Adjust conf files
> nginx: update brotli module

- net/keepalived/Makefile
- net/keepalived/files/keepalived.init
Maintainer: me
Compile tested: lantiq_xrx200 and x86_64, APU3, OpenWrt master
Run tested: x86_64, APU3, Openwrt master, start with default config
Description:
Update version to 2.0.18
Fix shell check warnings
> keepalived: update version to 2.0.18

- net/travelmate/Makefile
- net/travelmate/files/travelmate.sh
Run tested: GL-AR750S, OpenWrt SNAPSHOT r10703-e1f588e446
Description:
* fix logical glitch in last commit
> travelmate: update 1.4.11

- net/kcptun/Makefile
- net/kcptun/files/kcptun-c.conf
- net/kcptun/files/kcptun-c.init
- net/kcptun/files/kcptun-s.conf
- net/kcptun/files/kcptun-s.init
Maintainer: me / @liudf0716
Compile tested: X86_64, Ubuntu 18.04.1 LTS, OpenWrt master r10680-030fc6ab6c
Run tested: ARM, R7800, OpenWrt master r10680-030fc6ab6c, tests done
kcptun is a stable & secure tunnel based on kcp with N:M multiplexing.
https://github.com/xtaci/kcptun
> kcptun: add new package

- net/kcptun/Makefile
- net/kcptun/files/kcptun-c.conf
- net/kcptun/files/kcptun-c.init
- net/kcptun/files/kcptun-s.conf
- net/kcptun/files/kcptun-s.init
Maintainer: me / @liudf0716 
Compile tested: X86_64, Ubuntu 18.04.1 LTS, OpenWrt 19.07
Run tested: ARM, R7800, OpenWrt 19.07, tests done
Description:
kcptun is a stable & secure tunnel based on kcp with N:M multiplexing.
https://github.com/xtaci/kcptun
> [openwrt-19.07]kcptun: add new package

- utils/dump1090/Makefile
- utils/dump1090/files/dump1090.init
Repository was moved.
Also cleaned up Makefile slightly.
Ran init script through shellcheck.
Added several CFLAGS and LDFLAGS for smaller size.
> dump1090: Update to version 3.7.1

- lang/perl-device-usb/Makefile
- lang/perl-device-usb/patches/140-avoid-libusb-name-conflicts.patch
- lang/perl-inline-c/Makefile
- lang/perl-inline-c/patches/100-inline_c-no_compile_hack.patch
- lang/perl-inline-c/patches/110-inline_c-make_system_typemap_overridable.patch
- lang/perl-inline/Makefile
Maintainer: @pprindeville @Naoir
> perl updates

- .github/issue_template
Rephrase the template a bit and add information about
older releases and forks.
> repo: Add more information to the issue template

- lang/python/python-asn1crypto/Makefile
- lang/python/python-evdev/Makefile
- lang/python/python-lxml/Makefile
Maintainer: me, @paulo-raca 
-------------------------------------------------------
They seem to have become popular, so adding src packages for these as well.
Not bumping PKG_RELEASE intentionally, since these packages are new.
> python-{asn1crypto,evdev,lxml}: add -src packages

- net/phantap/Makefile
Maintainer: me
Compile & run tested: GL.iNet GL-AR150 / OpenWrt SNAPSHOT r10756+1-7546be6007
Description:
f5420af phantap: do not capture vlans
5d1bd13 phantap-learn: improve the BPF filter, exclude vlans
be6f7d9 Readme.md: we now support talking to the victim.
8789da5 README.md: fix typo
> phantap: update to latest commit

- lang/python/python-twisted/Makefile
- lang/python/python-twisted/patches/001-omit-tkconch.patch
- lang/python/python-twisted/patches/002-omit-tests.patch
Maintainer: me
Compile tested: armvirt-64, 2019-08-13 snapshot sdk
Description:
> python-twisted: Update to 19.7.0, refresh patches

- lang/python/python-twisted/Makefile
- lang/python/python-twisted/patches/001-omit-tkconch.patch
- lang/python/python-twisted/patches/002-omit-tests.patch
Maintainer: me
Compile tested: none (see #9713)
Description:
> [openwrt-19.07] python-twisted: Update to 19.7.0, refresh patches

- utils/prometheus-node-exporter-lua/Makefile
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/conntrack.lua
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/ltq-dsl.lua
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/netdev.lua
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/openwrt.lua
- utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/wifi_stations.lua
Maintainer: me
Compile & tested: GL.iNet GL-AR150 / OpenWrt 18.06-SNAPSHOT r7842-09bdc14419
Description:
cherry-pick all commits up to 2019.08.14
> [18.06] prometheus-node-exporter-lua: update to 2019.08.14

- utils/syncthing/Makefile
- utils/syncthing/files/etc/config/syncthing
- utils/syncthing/files/etc/init.d/syncthing
- utils/syncthing/files/etc/syncthing/index-v0.14.0.db
Description:
Compile tested: broken
Run tested: broken
Port syncthing to OpenWrt
> syncthing: add package

- net/simple-adblock/Makefile
- net/simple-adblock/files/simple-adblock.init
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 18.06.4
Run tested: mvebu, WRT3200ACM, 18.06.4
Description: prevent multiple restarts on boot-up
> simple-adblock: boot-up optimization

- net/bind/Makefile
Compile tested: ramips, ath79
Run tested: ramips, ath79
Description:
Update bind to 9.14.4
> bind: update to 9.14.4

- net/adblock/Makefile
- net/adblock/files/adblock.sh
Run tested: OpenWrt SNAPSHOT, r10835-0441edfb7f with dnsmasq, kresd and unbound
Description:
* fix a dns restart issue if 'flush dns cache' is set
* fix a suspend/resume issue, the status wasn't properly updated
* fix a long standing query issue
* rework return code handling, mostly for debugging
* various cleanups & cosmetics
> adblock: update 3.8.3

- libs/libssh2/Makefile
Speeds up build and fixes OpenSSL support.
> libssh2: Don't build tests

- net/adblock/Makefile
- net/adblock/files/adblock.mail
- net/adblock/files/adblock.service
- net/adblock/files/adblock.sh
Run tested: TP-Link RE450 v1, OpenWrt SNAPSHOT r10878-2340c646e6
Description:
* fix the 'adb_sysver' output
* pass the adblock version information to the helper scripts correctly
> adblock: update 3.8.4

- net/nut/Makefile
- net/nut/files/nut-monitor.init
- net/nut/files/nut-server.init
- net/nut/files/nutshutdown
Compile tested: TBD
Run tested: TBD
Description:
This series of commits pulls in targeted fixes from 19.07/master.  Unfortunately cherry-picking is
not appropriate as I was not at the top of my game, and master/19.07's commits aren't well organized for just doing a git cherry-pick.
I wanted to make sure this set of changes was acceptable -- I'll be testing in parallel, but would appreciate knowing sooner rather than later if there things that aren't going to be accepted, and I need to make changes for acceptance.
@yousong @neheb @jow-
> [18.06] Targeted fixes based on 19.07/master

- libs/libredblack/Makefile
CFLAGS were not being passed. This was breaking builds with ASLR.
> libredblack: Pass CFLAGS

- libs/keyutils/Makefile
Needed for compilation with PKG_ASLR_PIE.
Replaced Build/Compile with PKG_INSTALL.
Adjusted install paths for consistency.
Added license information.
> keyutils: Add Debian hardening patch

- net/unbound/Makefile
- net/unbound/files/unbound.sh
Maintainer: me
Tested: WRT-3200ACM, master
Description: Unbound 1.9.3
> unbound: update to 1.9.3

- lang/python/python-pyasn1/Makefile
Compile tested: armvirt-64, 2019-09-02 snapshot sdk
Description:
> python-pyasn1: Update to 0.4.7

- lang/python/python-pyasn1/Makefile
Compile tested: none (cherry-picked from #9910)
Description:
> [openwrt-19.07] python-pyasn1: Update to 0.4.7

- sound/alsa-utils/Makefile
- sound/alsa-utils/patches/100-uClibc-compat.patch
- sound/alsa-utils/patches/101-disable-libsamplerate.patch
Added license information.
Change URLs to HTTPS.
> alsa-utils: Update to 1.1.9

- net/ulogd/Makefile
- net/ulogd/patches/020-fix-musl.patch
- net/ulogd/patches/030-ipfix-add.patch
- net/ulogd/patches/040-ipfix-template.patch
IPFIX support was requested.
https://github.com/openwrt/packages/issues/9918
> ulogd2: Backport upstream patches

- libs/nss/Makefile
> nss: update to 3.46

- libs/libfizz/Makefile
Several size optimizations. ~76KB savings.
Maintainer: @ammubhave 
> libfizz: Update to 2019.09.09.00

- net/banip/Makefile
- net/banip/files/banip.sh
Run tested: OpenWrt SNAPSHOT, r10962-c19b9f9a26
Description:
* fix for #9954
> banip: update 0.2.1

- libs/librsocket-cpp/Makefile
- libs/librsocket-cpp/patches/101-do-not-use-gold.patch
> librsocket-cpp: Update to 2019-09-12

- utils/wipe/Makefile
- utils/wipe/patches/001-ignore_git_version_hash_and_fix_release_version.patch
Maintainer: Toni Uhlig matzeton@googlemail.com
Compile tested: x86_64, debian-stable, OpenWrt SNAPSHOT r10907+8-6cea9688af
Run tested: mvebu, linksys3200ac, OpenWrt SNAPSHOT r10907+8-6cea9688af
Description:
wipe is a little command for securely erasing files from magnetic media.
> wipe: add new package

- libs/vips/Makefile
Maintainer: me
Compile tested: x86_64 master 191c3e49
Description:
> vips: update to 8.8.2

- utils/collectd/Makefile
- utils/collectd/files/usr/share/collectd/plugin/cpu.json
- utils/collectd/files/usr/share/collectd/plugin/memory.json
Compile tested: only script chanes
Description:
- Add new memory config values
- Add new cpu config values
> collectd: add additional config option

- libs/liblz4/Makefile
> liblz4: Update to 1.9.2

- utils/collectd/Makefile
- utils/collectd/files/collectd.init
- utils/collectd/files/usr/share/collectd/plugin/logfile.json
Description:
* Add reload trigger on config file change
* add logfile plugin definitions
> collectd: add reload trigger and logfile plugin definition

- utils/zstd/Makefile
Bugfix release.
Maintainer: @ammubhave 
> zstd: Update to 1.4.3

- net/i2pd/Makefile
- net/i2pd/files/i2pd.config
- net/i2pd/files/i2pd.init
- net/i2pd/patches/config.patch
Maintainer: me
Compile tested/Run tested: @LLE8 https://github.com/PurpleI2P/i2pd/issues/345#issuecomment-527158568
> i2pd: Update to 2.28.0

- net/openconnect/Makefile
- net/openconnect/README
- net/openconnect/files/openconnect.sh
> openconnect: allow specifying form_entry list

- net/adblock/files/README.md
Maintainer: @dibdot 
Run tested: -
Description:
Add code blocks for easier reading and change "dns" to "DNS".
> adblock: Cosmetic changes to README.md

- libs/protobuf-c/Makefile
- libs/protobuf/Makefile
- net/ola/Makefile
> protobuf fixes from CMake conversion

- net/proxychains-ng/Makefile
**Compile tested:** R7800 (arm_cortex-a15_neon-vfpv4), OpenWrt git master
**Run tested:** R7800 (arm_cortex-a15_neon-vfpv4), OpenWrt git master
> proxychains-ng: new package

- net/frp/Makefile
Signed-off-by: Richard Yu <yurichard3839@gmail.com>
Maintainer: me
Compile tested: mt7621 snapshot
> frp: update to 0.29.0

- net/xtables-addons/Makefile
- net/xtables-addons/patches/002-restore-support-for-Linux-4.14.patch
- net/xtables-addons/patches/003-restore-support-for-Linux-4.9.patch
- net/xtables-addons/patches/100-add-rtsp-conntrack.patch
- net/xtables-addons/patches/200-add-lua-packetscript.patch
Description:
Update xtables-addons to 3.5
Add xt_PROTO target
> xtables-addons: update to 3.5

- net/simple-adblock/Makefile
- net/simple-adblock/files/README.md
- net/simple-adblock/files/simple-adblock.conf
- net/simple-adblock/files/simple-adblock.hotplug
- net/simple-adblock/files/simple-adblock.init
Maintainer: me
Compile tested: mvebu, WRT3200, 18.06.4
Run tested: mvebu, WRT3200, 18.06.4, start/stop/reload in different scenarios
Also:
- Updated README
- Updated config file
> simple-adblock: bugfix: proper dnsmasq reload on stop, rework start/stop logic

- lang/python/python-attrs/Makefile
Maintainer: me
Compile tested: none (cherry-picked from #10182)
Description:
> [openwrt-19.07] python-attrs: Update to 19.2.0

- net/uacme/Makefile
- net/uacme/files/acme.config
- net/uacme/files/acme.init
- net/uacme/files/run.sh
lightweight client for the RFC8555 ACMEv2 protocol, written in plain C code
with minimal dependencies (libcurl and one of GnuTLS, OpenSSL or mbedTLS).
Maintainer: me
tested: x86
> uacme: add package

- libs/nss/Makefile
and clean some comments
Maintainer: me / @\
Tested x86
> nss: update to 3.46.1

- net/nginx/Makefile
- net/nginx/files-luci-support/luci_uwsgi.conf
This depends on https://github.com/openwrt/packages/pull/10173
> nginx: adds new socket to luci uwsgi config

- net/snort/Makefile
- net/snort/patches/003-include-tirpc.patch
> snort: update to 2.9.15

- libs/vips/Makefile
> vips: update to 8.8.3

- mail/bogofilter/Makefile
> bogofilter: update to 1.2.5

- multimedia/gst1-libav/Makefile
- multimedia/gst1-plugins-bad/Makefile
- multimedia/gst1-plugins-base/Makefile
- multimedia/gst1-plugins-good/Makefile
- multimedia/gst1-plugins-ugly/Makefile
- multimedia/gstreamer1/Makefile
> gstreamer1: update to 1.16.1

- libs/hwloc/Makefile
> hwloc: update to 2.1.0

- lang/python/python-pyasn1-modules/Makefile
Compile tested: armvirt-64, 2019-10-04 snapshot sdk
Description:
> python-pyasn1-modules: Update to 0.2.7

- lang/python/python-pyasn1-modules/Makefile
Compile tested: none (cherry-picked from #10252)
Description:
(cherry picked from 5848f67e41880d995219173bf0098ecb1e95b46a)
> [openwrt-19.07] python-pyasn1-modules: Update to 0.2.7

- net/travelmate/Makefile
- net/travelmate/files/generic-user-pass.login
- net/travelmate/files/travelmate.init
- net/travelmate/files/travelmate.sh
Run tested: GL.iNet GL-AR750S, OpenWrt SNAPSHOT r11240-9d5e266cb1
Description:
* add WPA3 support
* fix service status message
* refine trigger handling
> travelmate: update 1.5.0

- net/adblock/Makefile
- net/adblock/files/README.md
- net/adblock/files/adblock.init
- net/adblock/files/adblock.sh
Run tested: -
Description:
* fix service status message
* refine readme regarding reload cron job (provided by @novoid)
> adblock: minor update 3.8.6-2

- lang/python/python-ipaddress/Makefile
Maintainer: me
Compile tested: armvirt-64, 2019-10-18 snapshot sdk
Description:
> python-ipaddress: Update to 1.0.23

- net/vpnbypass/Makefile
- net/vpnbypass/files/README.md
- net/vpnbypass/files/vpnbypass.init
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 18.06.4
Run tested: mvebu, WRT3200ACM, 18.06.4, start/stop
Description:
This PR fixes the "command not found" on service start/stop.
> vpnbypass: bugfix: PROCD command not found on stop

- net/vpnbypass/Makefile
- net/vpnbypass/files/README.md
- net/vpnbypass/files/vpnbypass.init
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 18.06.4
Run tested: mvebu, WRT3200ACM, 18.06.4, start/stop
Description:
This PR fixes the "command not found" on service start/stop.
> [19.07] vpnbypass: bugfix: PROCD command not found on stop

- net/vpnbypass/Makefile
- net/vpnbypass/files/README.md
- net/vpnbypass/files/vpnbypass.init
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 18.06.4
Run tested: mvebu, WRT3200ACM, 18.06.4, start/stop
Description:
This PR fixes the "command not found" on service start/stop.
> [18.06] vpnbypass: bugfix: PROCD command not found on stop

- net/travelmate/Makefile
- net/travelmate/files/travelmate.sh
Run tested: GL-AR750S, OpenWrt SNAPSHOT r11244-d544bc84a0
Description:
* fix section naming in wireless & travelmate config
* check/enable disabled 'wifi-device' sections
* fix LuCI frontend issues (separate PR)
> travelmate: update 1.5.1

- utils/ncdu/Makefile
Several Makefile cleanups for consistency.
Maintainer: @clehner 
> ncdu: Update to 1.14.1

- net/acme/Makefile
- net/acme/files/run.sh
Maintainer: me
Description: Update acme to latest upstream version and add a command wrapper to
ease debugging.
> A few updates to acme

- utils/ttyd/Makefile
- utils/ttyd/files/ttyd.config
- utils/ttyd/files/ttyd.init
Maintainer: @tsl0922
Compile tested: mt7621 snapshot
Run tested: mir3g snapshot
> ttyd: update to 1.5.2 and add init script

- libs/nss/Makefile
> nss: update to 3.47

- libs/nspr/Makefile
> nspr: update to 4.23

- net/libreswan/Makefile
- net/libreswan/files/ipsec.init
Tested x86
with old startup, after sysupgrade, the service will not be enabled at boot
> libreswan: switch to procd

- net/nginx/Makefile
- net/nginx/patches-dav-nginx/100-drop-libxslt-dep.patch
> nginx: update nginx-dav-ext-module to 3.0

- multimedia/mjpg-streamer/Makefile
- net/usbip/Makefile
- sound/pianod/Makefile
- utils/bluelog/Makefile
> treewide: Replace MD5SUM with HASH

- net/nginx/Config.in
- net/nginx/Config_ssl.in
- net/nginx/Makefile
- net/nginx/files-luci-support/60_nginx-luci-support
- Adds ubus module to nginx
- Select module by default
- Adds script to detect ubus module and append config for luci
> nginx: adds ubus external module

- lang/python/python-zipp/Makefile
Maintainer: me
Compile tested: Turris Omnia (TOS5), OpenWrt master
Run tested: Turris Omnia (TOS5), OpenWrt master
Description:
This PR is based on #8562 . It splits new packages to individuals PR.
> python-zipp: add new package

- net/banip/Makefile
- net/banip/files/banip.init
- net/banip/files/banip.service
- net/banip/files/banip.sh
Run tested: TP-Link RE450 v1, OpenWrt SNAPSHOT r11329-b9d58f7e06
Description:
* fix race condition in download utility detection during boot
* fix multiple possible bugs in ipset creation
* prevent parallel service starts
* refine service trigger handling
* add ssh daemon auto detection
* print to stdout if 'logger' is not available
> banip: update 0.3.5

- net/adblock/Makefile
- net/adblock/files/adblock.mail
- net/adblock/files/adblock.service
- net/adblock/files/adblock.sh
Run tested: TP-Link RE450 v1, OpenWrt SNAPSHOT r11329-b9d58f7e06
Description:
* print to stdout if 'logger' is not available
* small fixes
> adblock: update 3.8.8

- libs/avro/Makefile
- libs/avro/patches/010-pkgconfig.patch
- libs/avro/patches/020-bin-shared.patch
- libs/avro/patches/030-ssize_t.patch
Added utilities package.
Added small size optimization.
Maintainer: @inindev 
> avro-c: Update to 1.9.1

- utils/ap51-flash/Makefile
Added some size optimizations.
Maintainer: @RussellSenior
> ap51-flash: Update to 2019.0.1

- utils/unrar/Makefile
> unrar: Update to 5.8.3

- libs/libsoup/Makefile
Maintainer: me
Description:
Thank you for #10043!
> libsoup: update to 2.68.2 and build with meson

- utils/canutils/Makefile
- utils/canutils/patches/010-error.patch
Switched to codeload for simplicity.
Switched to PKG_INSTALL for consistency.
Added extra utilities added by the newer version.
Maintainer: @toxxin 
Note that the patch is an upstream backport.
> camutils: Update to 2018.02.0

- net/adblock/Makefile
- net/adblock/files/adblock.init
- net/adblock/files/adblock.mail
- net/adblock/files/adblock.service
- net/adblock/files/adblock.sh
Run tested: TP-Link RE450 v1, OpenWrt SNAPSHOT r11398-6f3a293532
Description:
* more startup tweaks
* re-use f_log function in helper scripts
* small fixes / polish up for forthcoming 19.07 release
> adblock: update 3.8.9

- net/banip/Makefile
- net/banip/files/banip.init
- net/banip/files/banip.service
- net/banip/files/banip.sh
Run tested: TP-Link RE450 v1, OpenWrt SNAPSHOT r11398-6f3a293532
Description:
* more startup tweaks
* re-use f_log function in helper scripts
* small fixes / polish up for forthcoming 19.07 release
> banip: update 0.3.6

- lang/perl-cgi/Makefile
- lang/perl-compress-bzip2/Makefile
- lang/perl-dbi/Makefile
- lang/perl-file-sharedir-install/Makefile
- lang/perl-html-form/Makefile
- lang/perl-http-cookies/Makefile
- lang/perl-http-daemon/Makefile
- lang/perl-http-message/Makefile
- lang/perl-http-server-simple/Makefile
- lang/perl-lwp-mediatypes/Makefile
- lang/perl-net-http/Makefile
- lang/perl-sub-uplevel/Makefile
- lang/perl-test-harness/Makefile
- lang/perl-test-warn/Makefile
- lang/perl-text-csv_xs/Makefile
- lang/perl-uri/Makefile
Maintainer: @pprindeville @Naoir
> Massive perl update

- net/samba4/Makefile
- net/samba4/files/smb.conf.template
Maintainer: me
Compile tested: arm (snapshots)
Description:
* update to 4.9.15
* fixes CVE-2019-10218, CVE-2019-14833, CVE-2019-14847
* update smb.conf.template (aio, sendfile)
> samba4: update to 4.9.15

- net/samba4/Makefile
- net/samba4/files/smb.conf.template
Maintainer: me
Compile tested: arm (19.07.0-rc1)
Description:
* update to 4.9.15
* fixes CVE-2019-10218, CVE-2019-14833, CVE-2019-14847
* update smb.conf.template (aio, sendfile)
> [openwrt-19.07] samba4: update to 4.9.15

- net/banip/Makefile
- net/banip/files/banip.hotplug
- net/banip/files/banip.sh
Run tested: UBNT-ERX, OpenWrt SNAPSHOT r11329-b9d58f7e06
Description:
* fix a logical glitch in the hotplug event handler
* properly handle fatal iptables errors - even in subshells
> banip: update 0.3.7

- libs/libmbim/Makefile
Signed-off-by: Nicholas Smith <nicholas.smith@telcoantennas.com.au>
> libmbim: bump libmbim to 1.20.2

- net/dmapd/Makefile
- net/dmapd/files/dmapd.init
> dmapd: update to 0.0.84

- net/modemmanager/Makefile
- net/modemmanager/files/modemmanager.proto
> modemmanager: add IPv6/IPv4v6 support

- net/nextdns/Makefile
- net/nextdns/files/nextdns.config
- net/nextdns/files/nextdns.init
Maintainer: @rs
Signed-off-by: Olivier Poitrey <rs@nextdns.io>
Description:
Cherry pick of https://github.com/openwrt/packages/pull/10535
> nextdns: add DNS over HTTPS with NextDNS integration

- lang/python/python-pyasn1/Makefile
Compile tested: none (cherry-picked from #10572)
Description:
(cherry picked from b99abe8dd8a3c3cd9118e891dd8353802d660ad0)
> [openwrt-19.07] python-pyasn1: Update to 0.4.8

- net/frr/Makefile
- net/frr/files/frrcommon.sh
- net/frr/patches/006-Revert_usage_of_asm-code.patch
- net/frr/patches/007-fix_memory_sanitizer_test.patch
> frr: add missing build options

- lang/python/python-twisted/Makefile
- lang/python/python-twisted/patches/001-omit-tkconch.patch
- lang/python/python-twisted/patches/002-omit-tests.patch
Maintainer: me
Compile tested: none (cherry-picked from #10574)
Description:
(cherry picked from c56770a570d6e87b0bc06dba5c552f5f35253728)
> [openwrt-19.07] python-twisted: Update to 19.10.0, refresh patches

- lang/python/python-zope-interface/Makefile
- lang/python/python-zope-interface/patches/001-omit-tests.patch
Maintainer: me
Compile tested: none (cherry-picked from #10576)
Description:
(cherry picked from 5e8feda04a9b458ce2e61c111ea8256ce7031557)
> [openwrt-19.07] python-zope-interface: Update to 4.7.1, refresh patch

- net/travelmate/Makefile
- net/travelmate/files/travelmate.init
- net/travelmate/files/travelmate.sh
Run tested: TP-Link RE450 v1, OpenWrt SNAPSHOT r11534-567d08104e
Description:
* some init tweaks
* use the usual wifi wrapper for reloads
* compatibility fix for latest wifi-related changes
in master (dynamic wireless radio reconfiguration)
> travelmate: update 1.5.3

- net/yggdrasil/Makefile
- net/yggdrasil/files/yggdrasil.defaults
- net/yggdrasil/files/yggdrasil.init
- net/yggdrasil/files/ygguci
Maintainer: @wfleurant
Compile tested: mips / snapshot
Description:
[WIP] Adding Luci application to configure yggdrasil via web interface
> yggdrasil: Change package configuration to UCI

- utils/ttyd/Makefile
- utils/ttyd/patches/100-log-to-syslog.patch
Maintainer: @tsl0922
Compile tested: sunxi, snapshot
Run tested: sun8i-h2-plus-orangepi-zero
Description:
Fixes #10665
> ttyd: log to syslog

- net/banip/Makefile
- net/banip/files/banip.service
- net/banip/files/banip.sh
Run tested: Raspberry Pi 4 Model B Rev 1.2, OpenWrt SNAPSHOT r11613-f1410902e6
Description:
* fix ssh daemon autodetection
* fix 'sshd' logfile parsing
> banip: update 0.3.11

- libs/nss/Makefile
- libs/nss/patches/001-nss_standalone.patch
- libs/nss/patches/003-openwrt_fix.patch
- libs/nss/patches/010-nanosleep.patch
also refresh patches
Tested x86
Compile tested arm_xscale,armeb_xscale
> nss: update to 3.47.1 and fix xscale

- net/strongswan/files/ipsec.init
Signed-off-by: Paul Fertser <fercerpav@gmail.com>
> strongswan: allow to specify per-connection reqid with UCI

- multimedia/motion/Makefile
- multimedia/motion/files/motion.conf
- multimedia/motion/files/motion.init
- multimedia/motion/patches/001-Remove-poll-option-for-mhd.patch
Maintainer: @roger-
Compile tested: OpenWrt master r11602-5f68333952 on RPi0W
Run tested: OpenWrt master r11602-5f68333952 on RPi0W
> motion: add basic procd init script and fix streaming

- utils/ttyd/Makefile
- utils/ttyd/files/ttyd.init
Maintainer: @tsl0922
Run tested: x86-64 (tested by modifying init script)
Description:
Fixes #10666
> ttyd: add reload trigger

- net/nlbwmon/Makefile
- net/nlbwmon/files/nlbwmon.init
Description:
https://github.com/openwrt/luci/pull/3388
> nlbwmon: add procd reload trigger for nlbwmon config

- libs/google-authenticator-libpam/Makefile
> google-authenticator-libpam: Update to 1.07

- libs/nspr/Makefile
> nspr: update to 4.24

- libs/nss/Makefile
also package libnssckbi.so
Tested x86
> nss: update to 3.48

- net/vpnbypass/Makefile
- net/vpnbypass/files/vpnbypass.init
Description:
https://github.com/openwrt/luci/pull/3388
> vpnbypass: add procd reload trigger for vpnbypass config

- net/adblock/Makefile
- net/adblock/files/adblock.sh
Run tested: GL.iNet GL-AR300M (NAND), OpenWrt SNAPSHOT r11651-487e0631d0
Description:
* fix some whitelist issues (see https://forum.openwrt.org/t/adblock-support-thread/507/1101)
> adblock: bugfix 3.8.14

- net/mtr/Makefile
Run tested: ipq40xx
Description:
Update mtr to 0.93
Add size optimization options
> mtr: update to 0.93

- libs/libqmi/Makefile
> libqmi: update to version 1.24.2

- net/safe-search/Makefile
- net/safe-search/files/hosts/google.default
Maintainer: me / @farmergreg 
Run tested: v19.07.0-rc2 (install, uninstall)
Description:
Periodic update of the list of Google domains using
https://www.google.com/supported_domains
as a reference.
Signed-off-by: Gregory L. Dietsche <gregory.dietsche@cuw.edu>
> net/safe-search Update Google host list.

- sound/shairport-sync/Makefile
- sound/shairport-sync/patches/010-no-cxx.patch
> shairport-sync: Update to 3.3.5

- net/bfdd/Makefile
- net/bfdd/patches/010-uclibc.patch
> bfdd: Fix compilation with uClibc-ng

- net/ariang/Makefile
Description:
Update ariang to 1.1.4
> ariang: update to 1.1.4

- net/knxd/Makefile
- net/knxd/files/knxd.config
- net/knxd/files/knxd.ini
- net/knxd/files/knxd.init
Maintainer: me
Compile tested: ath79, wndr3700, trunk
Run tested: mpc85xx, tl-wdr4900-v1, trunk
Run tested: ath79, wndr3700, trunk
Description:
adjust start script and config file to better comply with procd system
> knxd: adjust startup files to better comply with procd

- libs/libimobiledevice/Makefile
- libs/libimobiledevice/patches/010-format.patch
- libs/libirecovery/Makefile
- libs/libplist/Makefile
- libs/libusbmuxd/Makefile
- utils/idevicerestore/Makefile
- utils/usbmuxd/Makefile
- utils/usbmuxd/files/usbmuxd.init
- utils/usbmuxd/patches/010-config.patch
idevicerestore is a tool to flash iOS firmware without relying on iTunes (which is actually buggier).
> [WIP]Add idevicerestore

- net/restic-rest-server/Makefile
- net/restic-rest-server/files/etc/config/restic-rest-server
- net/restic-rest-server/files/etc/init.d/restic-rest-server
Maintainer: me / @gekmihesg
Compile tested: arm_cortex-a9_vfpv3, WRT3200ACM, master/19.07
Run tested: arm_cortex-a9_vfpv3, WRT3200ACM, master/19.07/18.06
Description:
Adds a package for restic/rest-server@2209f1437e84e31b7620c90568079d4a0c068dd8
> restic-rest-server: add package

- net/samba4/Makefile
Maintainer: me
Run tested:
Description:
* use old workaround for broken unbundle pam patch
@neheb temp fix for #10838
> samba4: fix libpam deps

- net/znc/Makefile
> znc: Update to 1.7.5

- libs/rpcsvc-proto/Makefile
Also fixed compilation with full iconv.
> rpcsvc-proto: Fix compilation with uClibc-ng

- net/zerotier/Makefile
- net/zerotier/files/etc/config/zerotier
- net/zerotier/files/etc/init.d/zerotier
- net/zerotier/patches/0001-find-miniupnpc.h-in-staging-directory.patch
- net/zerotier/patches/0002-remove-pie.patch
- net/zerotier/patches/0003-remove-arm32-conservative-CFLAGS.patch
- net/zerotier/patches/0004-accept-external-linker-flags.patch
- net/zerotier/patches/0005-link-natpmp.patch
Maintainer: me
cherrypick backport from master for openwrt-19.07
> zerotier: backport from master

- admin/zabbix/Makefile
- admin/zabbix/patches/120-uclibc-res.patch
This is similar to a patch that was previously carried.
> zabbix: Fix compilation with uClibc-ng

- utils/smstools3/Makefile
- utils/smstools3/files/smstools3.init
Allows procd to be able to stop the service.
Maintainer: @haraldg 
Fixes: https://github.com/openwrt/packages/issues/10607
> smstools3: Run in foreground

- mail/msmtp/Makefile
> msmtp: Update to 1.8.7

- net/wsdd2/Makefile
- net/wsdd2/files/wsdd2.init
Maintainer: me
Compile tested: arm/mips (master)
Run tested: arm
Description:
* update init for renamed cifsd->smbd
Depends on: #10909
> wsdd2: update init for renamed cifsd->smbd

- net/nginx/Makefile
Fix a bug in LuCI interface.
@hnyman 
> nginx: update ubus module

- net/wsdd2/Makefile
- net/wsdd2/files/wsdd2.init
> wsdd2: fix install warning on compile

- multimedia/mjpg-streamer/Makefile
Fix partially resolve reported issue #10254.
Signed-off-by: Zbyněk Kocur <zbynek.kocur@fel.cvut.cz>
Maintainers: @roger- & @thess
> mjpg-streamer: Fix of the mjpg-streamer modules path

- utils/spi-tools/Makefile
> spi-tools: Update to 0.8.4

- libs/libcap/Makefile
- libs/libcap/patches/100-portability.patch
- libs/libcap/patches/200-change-hardcoded-shell-to-sh.patch
> libcap: Update to 2.30

- utils/tcsh/Makefile
- utils/tcsh/patches/001-sysmalloc.patch
- utils/tcsh/patches/010-wint.patch
- utils/tcsh/patches/020-cross.patch
Updated URL list. Changed to HTTPS also.
Added PKG_INSTALL as is standard with most packages.
Small optimization to shell script.
> tcsh: Update to 6.22.02

- net/transmission/Makefile
- net/transmission/files/transmission.init
--log-error in the init script was overriding it.
Added several optimizations to the init script for speed and correctness.
Maintainer: me
ping @Mosney
> transmission: Fix message_level setting

- libs/apr-util/Makefile
- libs/apr-util/patches/002-fix-gdbm-error-handling.patch
- libs/apr/Makefile
Compile tested: ath79 + arc770 on 19.07
Run tested: ath79 master, run-tested with apache/httpd
Description:
Hi all,
This resolves #10886 and #10884
Kind regards,
Seb
> apr + apr-util: cleanups + add drivers

- multimedia/mjpg-streamer/Makefile
- multimedia/mjpg-streamer/files/mjpg-streamer.init
Rearranged Makefile options for consistency between packages.
> mjpg-streamer: update to latest git version

- libs/libmbim/Makefile
- libs/libqmi/Makefile
- net/modemmanager/Makefile
No need since nothing is being patched.
> modemmanager stuff: don't use autoreconf

- net/git/Makefile
- net/git/patches/310-fix-uname-detection-for-crosscompiling
Compile & run tested: OpenWRT master ar71xx Archer C5 v1
Based on: http://lists.busybox.net/pipermail/buildroot/2016-May/161696.html
This is a rebase of https://github.com/openwrt/packages/pull/9795
Signed-off-by: Mauro Condarelli mc5686@mclink.it
Signed-off-by: Jakub Piotr Cłapa jpc@loee.pl
> git: fix cross compilation on macOS

- lang/node-javascript-obfuscator/Makefile
Signed-off-by: Zbyněk Kocur <zbynek.kocur@fel.cvut.cz>
Maintainer: @zokl 
Compile tested: (x86, x86_64, KVN, openwrt-18.06)
Description:
JavaScript obfuscator is a powerful free obfuscator for JavaScript with a wide number of features that provide protection for your source code.
> node-javascript-obfuscator: add package

- net/wsdd2/Makefile
- net/wsdd2/files/wsdd2.init
Maintainer: me
Compile tested: mips/arm (master)
Run tested: arm/mvebu (master)
Description:
* update for renamed smbd->ksmbd
depends-on: #11131
> wsdd2: update for renamed smbd->ksmbd

- net/ser2net/Makefile
- net/ser2net/files/ser2net.init
Maintainer: @mhei
Compile tested: u7621-06 16m, mt7621, snapshot r12001
Run tested: u7621-06 16m, mt7621, snapshot r12001
Description:
This is in preparation of my JS app for ser2net for luci
Signed-off-by: Michele Primavera <primavera@elmod.it>
> ser2net: fix rpcd reload

- libs/nss/Makefile
> nss: update to 3.49.2

- utils/pciutils/Makefile
- utils/pciutils/patches/101-no-strip.patch
> pciutils: update to 3.6.4

- lang/python/django-appconf/Makefile
- lang/python/django-compressor/Makefile
- lang/python/django-constance/Makefile
- lang/python/django-formtools/Makefile
- lang/python/django-jsonfield/Makefile
- lang/python/django-picklefield/Makefile
- lang/python/django-postoffice/Makefile
- lang/python/django-ranged-response/Makefile
- lang/python/django-restframework/Makefile
- lang/python/django-simple-captcha/Makefile
- lang/python/django-statici18n/Makefile
- lang/python/django-webpack-loader/Makefile
- lang/python/gunicorn/Makefile
- lang/python/python3-netifaces/Makefile
- lang/python/python3-pyroute2/Makefile
- lang/python/python3-unidecode/Makefile
Maintainer: @commodo @cotequeiroz @BKPepe @mmtj 
Description:
* Replace `$(PKG_NAME)` with package name in `call`, `define`, and `eval` lines
* Remove extra "define" in `$(call define Package/.../description)`
> python-packages: Clean up Makefiles

- utils/mariadb/Makefile
- utils/mariadb/patches/130-c11_atomics.patch
- utils/mariadb/patches/140-mips-connect-unaligned.patch
Addresses CVE-2020-2574.
Maintainer: me
Compile tested: ath79 19.07
Run tested: ath79 19.07
Description:
Hi all,
Bump to address CVE.
Kind regards,
Seb
> [19.07] mariadb: security bump to 10.2.31

- multimedia/minidlna/Makefile
- multimedia/minidlna/patches/005-added-support-RMVB.patch
Signed-off-by: Vision Lsm <vision.lsm.2012@gmail.com>
Maintainer: me
Compile tested: sunxi 19.07 sdk
Run tested: sunxi 19.07
Description:
Hi,
It seems that the original project no longer accepts pull requests, but I think it is not difficult to support RMVB files
> minidlna: Added support RMVB

- net/wsdd2/Makefile
- net/wsdd2/files/wsdd2.init
Maintainer: me
Run tested:
Description:
* fix #11194, typos (WG_PARM, reload_trigger)
> wsdd2: fix typos

- net/i2pd/Makefile
- net/i2pd/files/i2pd.init
Maintainer: @yangfl 
@BKPepe can you test if https://github.com/openwrt/packages/issues/11192 is fixed?
> i2pd: fix various issues in 18.06

- utils/syncthing/Makefile
> syncthing: bump to 1.3.4

- libs/nspr/Makefile
> nspr: update to 4.25

- libs/nss/Makefile
> nss: update to 3.50

- libs/avahi/Makefile
- libs/avahi/files/avahi-daemon.init
> avahi: convert to procd

- utils/ttyd/Makefile
- utils/ttyd/patches/200-openssl.patch
Maintainer: me
Compile tested: ci passed
Description:
ttyd: update to 1.6.0
> ttyd: update to 1.6.0

- net/nginx/Makefile
Description:
Update nginx to 1.17.8
> nginx: update to 1.17.8

- net/modemmanager/Makefile
https://lists.freedesktop.org/archives/modemmanager-devel/2020-February/007713.html
> modemmanager: release 1.12.6

- net/nfdump/Makefile
- net/nfdump/files/nfcapd.config
- net/nfdump/files/nfcapd.init
> nfdump: add new package

- net/miniupnpd/Makefile
- net/miniupnpd/files/miniupnpd.hotplug
- net/miniupnpd/files/miniupnpd.init
- net/miniupnpd/files/upnpd.config
- net/miniupnpd/patches/100-no-daemon.patch
Massive cleanup of the shell script. Many issues were fixed.
> miniupnpd: convert to procd

- net/uacme/Makefile
> uacme: update to 1.0.22

- utils/unrar/Makefile
> unrar: update to 5.9.1

- net/cifs-utils/Makefile
- net/cifs-utils/patches/010-no-libtalloc.patch
- net/cifs-utils/patches/020-no-smb3.patch
> cifs-utils: update to 6.10

- utils/grep/Makefile
> grep: update to 3.4

- net/socat/Makefile
> socat: update to 1.7.3.4

- libs/file/Makefile
Fix license information.
Small Makefile cleanups.
> file: update to 5.38

- lang/golang/golang/Makefile
Maintainer: me
Compile tested: armvirt-64, 2020-02-18 snapshot sdk
Description:
> golang: Update to 1.13.8

- utils/coreutils/Makefile
- utils/coreutils/patches/001-no_docs_man_tests.patch
Compile tested: ramips, mvebu, ipq40xx
Run tested: ramips, mvebu, ipq40xx
Description:
Update coreutils to 8.31
> coreutils: update to 8.31

- net/sslh/Makefile
- net/sslh/patches/010-format.patch
Fixed maintainer entry.
Added patch fixing compilation.
> sslh: update to 1.20

- utils/ncdu/Makefile
> ncdu: update to 1.14.2

- utils/bigclown/bigclown-control-tool/Makefile
- utils/bigclown/bigclown-firmware-tool/Makefile
- utils/bigclown/bigclown-gateway/Makefile
- utils/bigclown/bigclown-mqtt2influxdb/Makefile
Maintainer: me
Compile tested: Turris Omnia, Mox, 1.x (OpenWrt 19.07, 18.06, master)
Run tested: Turris Omnia (OpenWrt 19.07)
> Bigclown utils update

- libs/libupnpp/Makefile
- sound/upmpdcli/Makefile
upmpdcli: update to 0.4.6 
Maintainer: @ignisf 
Run tested: malta-glibc
Fairly basic testing was done.
> libupnpp: update to 0.17.2 

- libs/libmpdclient/Makefile
Fix URLs and other small cleanups.
> libmpdclient: update to 2.18

- sound/mpc/Makefile
- sound/mpc/files/pls-handler.sh
Small Makefile cleanups.
Ran script through shellcheck.
> mpc: update to 0.33

- libs/libcap/Makefile
- libs/libcap/patches/200-change-hardcoded-shell-to-sh.patch
> libcap: update to 2.32

- utils/irqbalance/Makefile
- utils/irqbalance/files/irqbalance.config
- utils/irqbalance/files/irqbalance.init
Compile tested: R7800
Run tested: R7800
Added the ability to change the sampling interval and a list of IRQ's to ignore via /etc/config/irqbalance
> irqbalance: add support for interval and banirq

- utils/rtty/Makefile
> rtty: update to 7.1.2

- net/bonding/Makefile
- net/bonding/files/lib/netifd/proto/bonding.sh
Maintainer: me
Compile tested: not needed, only changes in script
Run tested: not done, only added missing policies
Description:
Added missing policies
> bonding: add missing policies

- sound/squeezelite/Makefile
- sound/squeezelite/files/squeezelite.init
- sound/squeezelite/patches/010-select_broadcast_interface.patch
- sound/squeezelite/patches/020-no_libmad.patch
Rebased patches.
Ran init script through shellcheck.
Several Makefile cleanups.
> squeezelite: update to 1.9.6-1206

- lang/golang/golang-values.mk
- lang/golang/golang/Makefile
Maintainer: me
Compile tested: armvirt-64, 2020-03-04 snapshot sdk
Description:
> golang: Update to 1.14

- admin/schroot/Config.in
- admin/schroot/Makefile
- admin/schroot/files/schroot.init
- admin/schroot/patches/01-openwrt.patch
Maintainer: Javier Marcet <javier@marcet.info>
Compile tested: x86-64
Description:
schroot: new package to securely enter a chroot and run a command or login shell
> schroot: new package to securely enter a chroot and run a command or login shell

- devel/meson/Makefile
> meson: update to 0.53.2

- libs/libuhttpd/Makefile
> libuhttpd: Update to 3.1.0

- utils/smartmontools/Makefile
- utils/smartmontools/files/smartd.init
Maintainer: @mstorchak 
Run tested: malta
smartd seems to have a lot of functionality that is unimplemented. This is just a basic conversion.
> smartmontools: convert init script to procd

- libs/libcap/Makefile
- libs/libcap/patches/200-change-hardcoded-shell-to-sh.patch
- libs/libcap/patches/300-uclibc-ng.patch
Added a compatibility fix for musl.
> libcap: update to 2.33

- net/modemmanager/Makefile
https://lists.freedesktop.org/archives/modemmanager-devel/2020-March/007729.html
> modemmanager: release 1.12.8

- libs/libqmi/Makefile
https://lists.freedesktop.org/archives/libqmi-devel/2020-March/003248.html
> libqmi: update to version 1.24.8

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/update_cnkuai_cn.sh
A low-cost domain name service provider in China
Signed-off-by: Chip Lee <chplee@gmail.com>
Maintainer: me / Community
Compile tested: (Atheros AR7161 rev 2, all, OpenWrt 19.07.1 r10911-c155900f66)
Run tested: (Atheros AR7161 rev 2, NETGEAR WNDR3800, OpenWrt 19.07.1 r10911-c155900f66, tests done)
Description:
Append ddns script support for a low-cost domain name service provider in China.
> ddns-scripts: Append ddns script for cnkuai.cn

- libs/libuwifi/Makefile
Update to latest libuwifi version.
> libuwifi: update to latest version

- utils/mc/Makefile
- utils/mc/patches/010-subshell.patch
Compile tested: apu2/x86_64
Run tested: apu2/x86_64
Description:
* changes see http://midnight-commander.org/wiki/NEWS-4.8.24
> mc: update to 4.8.24

- lang/python/python-zope-interface/Makefile
- lang/python/python-zope-interface/patches/001-omit-tests.patch
Maintainer: me
Compile tested: none (cherry-picked from #11582)
Description:
(cherry picked from commit a178662fcef00a1cebbe78253ae28eb1edb418f4)
> [openwrt-19.07] python-zope-interface: Update to 4.7.2, refresh patch

- lang/python/python-enum34/Makefile
- lang/python/python-enum34/patches/001-omit-docs.patch
Maintainer: me
Compile tested: none (cherry-picked from #11421 and #11581)
Description:
> [openwrt-19.07] python-enum34: Update to 1.1.10

- lang/python/python-pycparser/Makefile
Maintainer: me
Compile tested: none (cherry-picked from #11579)
Description:
(cherry picked from commit 931dcfe3aa992a9d23323d749a806d9627e88fa7)
> [openwrt-19.07] python-pycparser: Update to 2.20

- lang/python/python-idna/Makefile
Compile tested: none (cherry-picked from #11422)
Description:
(cherry picked from commit 111d7ae088545615aeb453cee20cf5e9f91c82c9)
> [openwrt-19.07] python-idna: Update to 2.9

- kernel/ksmbd/Makefile
- net/ksmbd-tools/Makefile
This is just a simple version bump. New version fixes big endian issues and SMBv1 ones.
> ksmbd update

- lang/node/Makefile
- lang/node/patches/999-delete_unnecessary_libraries_for_host_execute.patch
Maintainer: @blogic @ianchi 
Compile tested: head r12702-3f3a754, x86_64
 Run tested: x86_64 (VirtualBox)
Description:
modify host icu library path
> node: Change icu version specification

- libs/libcap/Makefile
Made a bunch of libraries explicit for clarity.
> libcap: apply pkgconfig fix to libpsx.pc as well

- utils/syncthing/Makefile
- utils/syncthing/files/etc/config/syncthing
- utils/syncthing/files/etc/init.d/syncthing
- utils/syncthing/files/etc/syncthing/index-v0.14.0.db
Compile tested: ipq40xx / 19.07-SNAPSHOT
Run tested: ipq40xx / 19.07-SNAPSHOT
A backport to 19.07.
> syncthing: backport to 19.07

- net/libreswan/Makefile
> libreswan: update to 3.31

- net/openfortivpn/Makefile
> openfortivpn: update to 1.13.2

- mail/dovecot/Makefile
> dovecot: update to 2.3.10

- libs/nss/Makefile
> nss: update to 3.51

- libs/libuwsc/Makefile
> libuwsc: update to 3.3.4

- net/frr/Makefile
> frr: add libatomic dependency

- net/wsdd2/Makefile
- net/wsdd2/files/wsdd2.init
Fixes: https://github.com/openwrt/packages/issues/11701
> wsdd2: run init script through shellcheck

- utils/rtty/Makefile
> rtty: update to 7.1.3

- libs/h2o/Makefile
- libs/h2o/patches/600-engine.patch
> h2o: fix compilation without engine support

- net/adblock/Makefile
- net/adblock/files/README.md
- net/adblock/files/adblock.sh
- net/adblock/files/adblock.sources
Run tested: Raspberry Pi 4 Model B Rev 1.2, OpenWrt SNAPSHOT r12834-d24e43a7f6
Description:
* add 'wally3k' and 'reg_vn' sources, change 'reg_pl' source
* update readme
* small fixes & cosmetics
> adblock: release 4.0.3

- mail/postfix/Makefile
> postfix: update to 3.5.0

- net/frp/Makefile
Maintainer: me
Compile tested: x86_64, snapshot
Run tested: x86_64, snapshot
> frp: update to 0.32.1

- lang/python/openpyxl/Makefile
Maintainer: me
Compile tested: x86 https://github.com/openwrt/openwrt/commit/d8bde3687a23742d1072be1a55f3b44ae29438ae
Run tested: x86 https://github.com/openwrt/openwrt/commit/d8bde3687a23742d1072be1a55f3b44ae29438ae
-------------------------------------------------
> openpyxl: bump to version 3.0.3

- libs/nss/Makefile
- libs/nss/patches/001-nss_standalone.patch
- libs/nss/patches/003-openwrt_fix.patch
also refresh patches
Maintainer: me
Tested: rockchip
> nss: update to 3.51.1

- libs/p11-kit/Makefile
Converted to meson for faster compilation speed.
> p11-kit: update to 0.23.20

- utils/dump1090/Makefile
> dump1090: update to 3.8.1

- libs/libdrm/Makefile
Converted to meson for faster compilation.
Cleaned up Makefile slightly.
Note that I seem to have disabled all the hardware. Not sure which should be enabled.
> libdrm: update to 2.4.101

- multimedia/gerbera/Makefile
- multimedia/gerbera/files/gerbera.config
- multimedia/gerbera/files/gerbera.init
This is a proper replacement for MiniDLNA with none of its problems.
Took the package from entware and ported it here.
Posting it here to get feedback. I haven't gotten much of an opportunity to test this.
The Turris people will probably be interested in this. MiniDLNA has been a pain point there, at least according to the forums.
I have theories as to why, but no real desire or time to investigate.
> gerbera: add

- libs/libqmi/Makefile
https://lists.freedesktop.org/archives/libqmi-devel/2020-April/003275.html
Description:
> libqmi: update version to 1.24.10

- net/open-isns/Makefile
- net/open-isns/patches/01-security_mode.patch
- net/open-isns/patches/02-fix_signed_vs_unsigned.patch
- net/open-isns/patches/03-include_poll_h.patch
- net/open-isns/patches/04-ignore_write.patch
- net/open-isns/patches/10-without_deprecated_openssl.patch
prerequisite for open-iscsi
Tested x86
needed for open-iscsi
> isns: add open-isns

- libs/libqmi/Makefile
- net/modemmanager/Makefile
These are cherry-picks from git master to put latest stable releases for libqmi and MM in the 19.07 branch.
> libqmi and MM updates for stable 19.07

- utils/dbus/Makefile
- utils/dbus/files/dbus-launch
Ran scripts through shellcheck.
> dbus: update to 1.13.12

- net/freeradius3/Makefile
Maintainer: @Robby- 
Compile tested: ar71xx; Mikrotik 450g; OpenWrt 19.07.2
Run tested: ar71xx; Mikrotik 450g; OpenWrt 19.07.2
Description:
Sister-PR to #11918
> OpenWrt 19: freeradius3: Support building freeradius3-mod-rest

- net/seafile-server/Makefile
Maintainer: me, @jefferyto 
Compile tested: x86 https://github.com/openwrt/openwrt/commit/58bec0d172fb7fc1146bdcdcd0f75b6644890fb6
Run tested:  x86 https://github.com/openwrt/openwrt/commit/58bec0d172fb7fc1146bdcdcd0f75b6644890fb6
-------------------------------------------
>  net: seafile-server: fix build

- libs/libedit/Makefile
Compile tested: ARM Cortex-A9 vfpv3, Turris Omnia, TurrisOS 5.0-dev
Run tested: -
> libedit: update to version 20193112-3.1

- net/acme/Makefile
- net/acme/files/run.sh
> acme: fix some errors

- utils/coreutils/patches/002-ls-restore-831-behavior-on-removed-directories.patch
ls: restore 8.31 behavior on removed directories
Signed-off-by: Scott Roberts <ttocsr@gmail.com>
> coreutils: add upstream patch fixing aarch64 compilation

- libs/jsoncpp/Makefile
> jsoncpp: add size optimizations

- lang/python/python-schema/Makefile
Compile tested: armvirt-64, 2020-04-28 snapshot sdk
Description:
> python-schema: Update to 0.7.2, change download source to PyPI

- net/vpn-policy-routing/Makefile
- net/vpn-policy-routing/files/README.md
- net/vpn-policy-routing/files/vpn-policy-routing.init
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 19.07.2
Run tested: mvebu, WRT3200ACM, 19.07.2, check system log
> vpn-policy-routing: bugfix: remove non-ASCII from log; update README

- net/vpn-policy-routing/Makefile
- net/vpn-policy-routing/files/README.md
- net/vpn-policy-routing/files/vpn-policy-routing.init
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 19.07.2
Run tested: mvebu, WRT3200ACM, 19.07.2, check system log
> [19.07] vpn-policy-routing: bugfix: remove non-ASCII from log; update README

- net/frr/Config.in
- net/frr/Makefile
- net/frr/files/vtysh.conf
- net/frr/patches/010-add_yahng_filter.patch
- net/frr/patches/010-add_yang_routemap.patch
- net/frr/patches/011-mod_yang_routemap_model.patch
- net/frr/patches/012-add_yang_filter.patch
- net/frr/patches/013-backport_northbound.patch
- net/frr/patches/014-backport_northbound.patch
- net/frr/patches/020-7.3_backports.patch
- net/frr/patches/021-7.3_backports.patch
- net/frr/patches/022-7.3_backports.patch
- net/frr/patches/023-7.3_backports.patch
- net/frr/patches/024-7.3_backports.patch
- net/frr/patches/025-7.3_backports.patch
- net/frr/patches/026-7.3_backports.patch
- net/frr/patches/098-fix_mips_libyang.patch
Tested x86,rockchip,mips
Added a change to host install Makefile that lets the proper way to build the package
added fixes staged to 7.3 branch and backported some yang updates for mips runtime
> frr: makefile cleanup and misc fixes

- utils/collectd/Makefile
- utils/collectd/files/usr/share/collectd/plugin/syslog.json
Run tested: x86_64, APU3, openwrt master
Description:
Add missing syslog json plugin description
> collectd: add syslog json plugin

- utils/yara/Makefile
> yara: update to 4.0.0

- utils/rrdtool1/Makefile
- utils/rrdtool1/patches/040-no-e-notation-on-log-display.patch
Improve logarithmic y-axis labelling & fix a libpng compile indentation warning
> Rrdtool1: Improve logarithmic y-axis labelling

- utils/collectd/Makefile
- utils/collectd/files/collectd.init
- utils/collectd/files/exec-scripts/sqm_collectd.sh
- utils/collectd/patches/910-add-cake-qdisc-types.patch
@hnyman 
Is this getting a bit closer?  I know still have to make fq_codel work ;-)
> collectd: collect some stats from cake & mq qdisc instances

- sound/shairport-sync/Makefile
- sound/shairport-sync/files/shairport-sync.init
Use PKG_INSTALL for consistency between packages.
Ran the init script through shellcheck.
I'll keep this as a draft until I can test this script.
> shairport-sync: update to 3.3.6

- sound/pulseaudio/Makefile
> pulseaudio: add lto and gc-sections to reduce size

- utils/domoticz/Makefile
- utils/openzwave/Makefile
> Drop maintainership

- libs/pugixml/Makefile
- libs/spdlog/Makefile
- multimedia/gerbera/Makefile
> gerbera static library changes

- utils/domoticz/Makefile
- utils/domoticz/patches/010-boost-173.patch
> domoticz: fix compilation with boost 1.73

- libs/libqmi/Makefile
https://lists.freedesktop.org/archives/libqmi-devel/2020-May/003296.html
Description:
> libqmi: update version to 1.24.12

- net/modemmanager/Makefile
https://lists.freedesktop.org/archives/modemmanager-devel/2020-May/007828.html
> modemmanager: release 1.12.10

- net/pdns/Makefile
- net/pdns/patches/300-boost-173.patch
> pdns: fix compilation with boost 1.73

- libs/libqmi/Makefile
- net/modemmanager/Makefile
> ModemManager and libqmi stable releases in 19.07

- libs/nss/Makefile
> nss: update to 3.52

- lang/python/django/Makefile
Maintainer: me
Compile tested: https://github.com/openwrt/openwrt/commit/58bec0d172  x86
Run tested: https://github.com/openwrt/openwrt/commit/58bec0d172 x86
-------------------------------------------------------------
> django: bump to version 3.0.6

- libs/libwebp/Makefile
> libwebp: update to 1.1.0

- libs/libmariadb/Makefile
- utils/mariadb-common/Makefile
- utils/mariadb/Makefile
- utils/mariadb/conf/50-server.cnf
- utils/mariadb/files/mysqld.config
- utils/mariadb/files/mysqld.init
- utils/mariadb/patches/190-replace-hostname-in-mysqld_safe.patch
Maintainer: me
Compile tested: ath79 master
Run tested: ath79 19.07
Description:
Hi all,
Some updates that I have been working on. Feedback welcome, as always.
Kind regards,
Seb
> mariadb: updates for config, auth-pam and init

- lang/golang/golang-package.mk
- lang/golang/golang-values.mk
- lang/golang/golang/Makefile
- utils/containerd/Makefile
- utils/docker-ce/Makefile
- utils/runc/Makefile
Maintainer: me
Compile tested: armvirt-32/armvirt-64/at91-sam9x/bcm27xx-bcm2708/malta-be/mvebu-cortexa9/x86-64/x86-generic, 2020-05-13 snapshot sdk
Run tested: armvirt-32/armvirt-64/malta-be/x86-64/x86-generic (qemu), 2020-05-13 snapshot
Description:
These are various improvements/tweaks for both the Go compiler and Go packages. Please see the commit messages for more details.
> golang: Various improvements/tweaks

- net/libreswan/Makefile
- net/libreswan/patches/030-fix_nss_3.52.patch
also add -flto to compiler flags
Tested x86
> libreswan: update to 3.32

- libs/nspr/Makefile
> nspr: nspr add -flto to compile

- libs/nss/Makefile
- libs/nss/patches/003-openwrt_fix.patch
> nss: add -flto and makefile cleanup

- utils/collectd/Makefile
- utils/collectd/files/exec-scripts/sqm_collectd.sh
> collectd: Improve sqm_collectd error reporting

- libs/libebml/Makefile
- libs/libmatroska/Makefile
- multimedia/gerbera/Makefile
> gerbera: add libmatroska support

- libs/libfuse3/Makefile
- utils/fuse/Makefile
- utils/fuse/patches/100-missing_includes.patch
- utils/fuse/patches/112-no_break_on_mknod.patch
- utils/fuse/patches/200-backport_arm64_fuse_kernel_h_clean_includes.patch
This belongs here. All dependent packages are located here.
> fuse: import from base

- README.md
Signed-off-by: Wren Turkal <wt@penguintechs.org>
> Update the SDK URL in the README.

- utils/collectd/Makefile
- utils/collectd/files/exec-scripts/sqm_collectd.sh
> collectd: sqm_collectd: improve error handling

- utils/collectd/Makefile
- utils/collectd/files/exec-scripts/sqm_collectd.sh
> collectd: sqm_collect: tidy interval string handling

- net/nextdns/Makefile
> nextdns: Update to version 1.6.3

- net/nextdns/Makefile
> [19.07] nextdns: Update to version 1.6.3

- net/nginx-util/Makefile
- net/nginx-util/src/CMakeLists.txt
- net/nginx-util/src/nginx-ssl-util.hpp
- net/nginx-util/src/nginx-util.cpp
- net/nginx-util/src/nginx-util.hpp
- net/nginx-util/src/px5g-openssl.hpp
- net/nginx-util/src/px5g.cpp
- net/nginx-util/src/regex-pcre.hpp
- net/nginx-util/src/test-nginx-util-root.sh
- net/nginx-util/src/test-nginx-util.sh
- net/nginx-util/src/test-px5g.sh
- net/nginx-util/src/ubus-cxx.cpp
- net/nginx-util/src/ubus-cxx.hpp
Maintainer: me
Run tested: x86_64, x86_64 qemu, master, run test-nginx-ssl-util-root.sh
Description: These are some parts of #11456:
* fix regex capture (to conform std)
* fix [issues](https://github.com/openwrt/packages/issues/12273) for Clang/libcxx (warnings/includes)
* fix CONFLICTS in the Makefile
* use /bin/sh in host scripts and shellcheck them
* add callback for setting arguments in ubus::call
> nginx-util: fix issues and cleanup

- net/openvswitch/Makefile
- net/openvswitch/patches/0001-netdev-linux-Let-interface-flag-survive-internal-por.patch
- net/openvswitch/patches/0002-python-separate-host-target-python-for-cross-compile.patch
- net/openvswitch/patches/0003-ovs-lib-fix-install_dir.patch
- net/openvswitch/patches/0004-build-trim-build.patch
- net/openvswitch/patches/0005-datapath-unexport-LDFLAGS.patch
- net/openvswitch/patches/0006-datapath-allow-passing-additional-OVS_KERNEL_MAKE_FL.patch
Maintainer: me
Compile tested: mpc85xx, 19.07
Description:
> openvswitch: disable docs, patch for reproducible build

- net/kea/Makefile
- net/kea/patches/001-fix-cross-compile.patch
- net/kea/patches/003-no-test-compile.patch
- net/kea/patches/010-openssl-deprecated.patch
Maintainer: @rosysong @hbl0307106015
Compile tested: CentOS7
This contains several fixes for the host build that are needed to get it to compile.
> [19.07] backport kea changes

- libs/libqmi/Makefile
https://lists.freedesktop.org/archives/libqmi-devel/2020-May/003321.html
> libqmi: update version to 1.24.14

- libs/nss/Makefile
- libs/nss/patches/001-nss_standalone.patch
also enable parallel build as now is safe
Maintainer: me
Tested x86
> nss: update to 3.53

- kernel/ksmbd/Makefile
- kernel/ksmbd/patches/01-keep_kmod_metadata.patch
- net/ksmbd-tools/Makefile
Run tested: ramips:
Description:
Update ksmbd to 3.2.0
Update ksmbd-tools to 3.2.6
> ksmbd: update

- net/unbound/files/README.md
Maintainer: me
Description: README only change. This should resolve #11957
> unbound: suggest matched domain option for dnsmasq link

- net/nginx/Makefile
Run tested: x86_64, x86_64 qemu, master, run luci-nginx
Description: bump to newest version.
> nginx: update to version 1.19.0

- libs/freetype/Makefile
- libs/libpng/Makefile
- utils/dbus/Makefile
these are completely unused
Maintainer: @srdgame @val-kulkov @jow- 
Compile tested: fedora 32, centos 7.
> remove pointless host builds

- utils/cryptsetup/Makefile
> cryptsetup: update to 2.3.3

- utils/unrar/Makefile
- utils/unrar/patches/100-makefile_fixes.patch
Refreshed patch.
Maintainer: @Noltari @thess 
> unrar: update to 5.93

- lang/python/python-cached-property/Makefile
- lang/python/python-docopt/Makefile
- lang/python/python-texttable/Makefile
- lang/python/python-websocket-client/Makefile
Maintainer: Javier Marcet <javier@marcet.info>
Compile tested: x86-64 master
Run tested: x86-64 master
Description:
First part of docker-compose, packages directly required by the former.
This comes from splitting #11155
> Docker compose (1 of 3)

- lang/python/docker-compose/Makefile
- lang/python/python-distro/Makefile
- lang/python/python-dockerpty/Makefile
- lang/python/python-dotenv/Makefile
- lang/python/python-jsonschema/Makefile
Maintainer: Javier Marcet javier@marcet.info
Compile tested: x86-64 master
Run tested: x86-64 master
Description: third and final set of packages which complete docker-compose.
This PR depends on #11363 and #11364, and is the final part from splitting #11155
> Docker compose (3 of 3)

- utils/less/Makefile
> less: update to 562

- utils/yara/Makefile
> yara: update to 4.0.1

- devel/automake/Makefile
> automake: update to 1.16.2

- libs/libarchive/Makefile
> libarchive: update to 3.4.3

- admin/ipmitool/Makefile
- admin/ipmitool/patches/0006-CVE-2020-5208-fru-Fix-buffer-overflow-vulnerabilities.patch
- admin/ipmitool/patches/0007-CVE-2020-5208-fru-Fix-buffer-overflow-in-ipmi_spd_print_fru.patch
- admin/ipmitool/patches/0008-CVE-2020-5208-session-Fix-buffer-overflow-in-ipmi_get_session_info.patch
- admin/ipmitool/patches/0009-CVE-2020-5208-channel-Fix-buffer-overflow.patch
- admin/ipmitool/patches/0010-CVE-2020-5208-lanp-Fix-buffer-overflows-in-get_lan_param_select.patch
- admin/ipmitool/patches/0011-CVE-2020-5208-fru-sdr-Fix-id_string-buffer-overflows.patch
Maintainer: me
All patches has been applied upstream.
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>
> ipmitool: fix CVE-2020-5208

- net/softethervpn5/Makefile
Maintainer: me
Compile tested: arm, mips (master)
Run tested: arm(qemu) (master)
Description:
* update to 9672
> softethervpn5: update to 9672

- utils/less/Makefile
Avoid conflict with busybox
Signed-off-by: Huangbin Zhan <zhanhb88@gmail.com>
> less: update ALTERNATIVES

- utils/zstd/Makefile
- utils/zstd/patches/010-python.patch
This is the case in debian.
Compile tested: debian 10
Fixes: https://github.com/openwrt/packages/issues/12443
> zstd: fix compilation without host distutils

- utils/less/Makefile
Avoid conflict with busybox
Signed-off-by: Huangbin Zhan <zhanhb88@gmail.com>
(cherry picked from commit d866393)
Maintainer: @Zokormazo @BKPepe 
Description: Apply PR #12467 on branch `openwrt-19.07`
> [19.07] less: update ALTERNATIVES

- utils/kmod/Makefile
Signed-off-by: Huangbin Zhan <zhanhb88@gmail.com>
Maintainer: @jdub 
Description: avoid conflict with package ubox
> kmod: add ALTERNATIVES

- lang/python/README.md
Description:
* Remove references to variants
* Fix relative links
* Revise pypi.mk section
> python: Readme updates

- sound/mpd/Makefile
> mpd: update to 0.21.24

- multimedia/ffmpeg/Makefile
Maintainer: @antonlacon @thess 
> ffmpeg: update to 4.2.3

- lang/perl-parse-yapp/Makefile
Maintainer: me
Compile tested: arm/mips (master)
Run tested: arm (qemu) (master)
Description:
* add new perl-parse-yapp (dep for samba4.12)
PS: New dependency for samba-4.12.x
> perl-parse-yapp: new package

- lang/python/python-distro/Makefile
- lang/python/python-dockerpty/Makefile
- lang/python/python-dotenv/Makefile
- lang/python/python-jsonschema/Makefile
- utils/docker-compose/Makefile
Maintainer: me
Run tested: master x86-64
Description:
This PR comes from #11365 which has already been merged.
@jefferyto hadn't reviewed it and asked for a few changes, here they are.
> docker-compose: fix depends after merge in master and move to utils

- net/softethervpn5/Makefile
Maintainer: me
Compile tested: arm (19.07)
Run tested: arm/qemu (19.07)
Description:
* update to 5.01.9674
> [19.07] Softethervpn5: update to 5.01.9674

- libs/rpcsvc-proto/Makefile
Maintainer: me
Compile tested: arm (19.07)
Run tested: arm/qemu (19.07)
Description:
* update to 1.4.1
> [19.07] rpcsvc-proto: update to 1.4.1

- libs/liborcania/Makefile
- libs/libulfius/Makefile
Maintainer: me
Compile tested: x86_64, debian-stable, OpenWrt SNAPSHOT r13247+9-631c437a91
Run tested: mvebu, linksys3200ac, OpenWrt SNAPSHOT r13247+9-631c437a91
Run tested: x86_64, qemu-kvm, OpenWrt SNAPSHOT r13247+9-631c437a91
Description:
Web Framework to build REST APIs, Webservices or any HTTP endpoint in C language.
> libulfius: new package

- net/samba4/Makefile
- net/samba4/waf-cross-answers/aarch64.txt
- net/samba4/waf-cross-answers/arc.txt
- net/samba4/waf-cross-answers/arm.txt
- net/samba4/waf-cross-answers/armeb.txt
- net/samba4/waf-cross-answers/i386.txt
- net/samba4/waf-cross-answers/mips.txt
- net/samba4/waf-cross-answers/mips64.txt
- net/samba4/waf-cross-answers/mips64el.txt
- net/samba4/waf-cross-answers/mipsel.txt
- net/samba4/waf-cross-answers/powerpc.txt
- net/samba4/waf-cross-answers/x86_64.txt
Maintainer: me
Compile tested: all archs (snapshots-sdk)
Run tested: all archs/qemu (snapshots-sdk)
Description:
* update waf-cross-answers for 4.12.x
> samba4: update waf-cross-answers

- net/conserver/Makefile
Add PKG_BUILD_PARALLEL for faster compilation.
Minor whitespace fixes.
Maintainer: @bmork 
> conserver: 8.2.5

- mail/alpine/Makefile
> alpine: update to 2.23

- libs/libxcrypt/Makefile
- utils/shadow/Makefile
Run tested: malta
Made libxcrypt a static library in a non-standard location as other packages were picking it up and breaking.
ping @n8v8R
> added libxcrypt and used for shadow-utils

- utils/collectd/Makefile
- utils/collectd/files/collectd.init
Maintainer: @hnyman @ldir-EDB0 
Run tested: x86_64, APU3, OpenWrt master, run test done
Description:
Fixes #12562
> collectd fix: init uci issues

- net/tcpreplay/Makefile
Maintainer: me
Compile tested: https://github.com/openwrt/openwrt/commit/870588b6ebd8d818f65e5784bc866a8d67de0a31   x86
Run tested:  https://github.com/openwrt/openwrt/commit/870588b6ebd8d818f65e5784bc866a8d67de0a31   x86
> tcpreplay: bump to version 4.3.3

- lang/python/python-requests/Makefile
Maintainer: @BKPepe , me
Compile tested: https://github.com/openwrt/openwrt/commit/870588b6ebd8d818f65e5784bc866a8d67de0a31   x86
Run tested:  https://github.com/openwrt/openwrt/commit/870588b6ebd8d818f65e5784bc866a8d67de0a31   x86
> python-requests: bump to version 2.24.0

- sound/upmpdcli/Makefile
> upmpdcli: update to 1.4.12

- net/ddns-scripts/Makefile
- net/ddns-scripts/files/update_cloudflare_com_v4_token.sh
ddns-scripts: Added api token method for cloudflare ddns script v4
Maintainer: xjboss
Compile tested: mt7621at, gehua_ghl-r-001, OpenWrt R20.5.20 (unoffical fork https://github.com/coolsnowwolf/lede)
Run tested: mt7621at, gehua_ghl-r-001, OpenWrt R20.5.20)
Description: 
I clone update_cloudflare_com_v4.sh script and modify it' authorized method to api token as update_cloudflare_com_v4_token.sh. I test it on my router it is working. It will coexist with original ddns script.
> ddns-scripts: Added api token method for cloudflare ddns script v4

- libs/gdbm/Makefile
- libs/gdbm/patches/999-001-fix-multiple-def-gcc-10.patch
Signed-off-by: Syrone Wong <wong.syrone@gmail.com>
Maintainer: @Naoir 
ping @wongsyrone
> gdbm: fix GCC 10 multiple def compilation error

- utils/syncthing/Makefile
Maintainer: me
Compile/run tested: mvebu/cortexa9
> syncthing: bump to 1.6.1

- net/miniupnpd/Makefile
- net/miniupnpd/files/miniupnpd.init
Add miniupnpd option ipv6_disable.
> add miniupnpd ipv6_disable option, #11971 close

- utils/minicom/Makefile
- utils/minicom/patches/200-gcc10.patch
> minicom: fix compilation with GCC10

- utils/open-plc-utils/Makefile
- utils/open-plc-utils/patches/010-gcc10.patch
> open-plc-utils: fix compilation with GCC10

- utils/ykpers/Makefile
- utils/ykpers/patches/010-gcc10.patch
> ykpers: fix compilation with GCC10

- net/shadowsocks-libev/Makefile
- net/shadowsocks-libev/patches/010-gcc10.patch
> shadowsocks-libev: fix compilation with GCC10

- libs/libowfat/Makefile
- libs/libowfat/patches/010-gcc10.patch
> libowfat: fix compilation under GCC10

- net/stubby/Makefile
- net/stubby/patches/stubby-0.3.0-fix-config-install.patch
Signed-off-by: Jonathan G. Underwood <jonathan.underwood@gmail.com>
Maintainer: me
Description: update to version 0.3.0. This version uses the CMake build system.
> stubby: update to version 0.3.0

- net/stubby/Makefile
- net/stubby/patches/stubby-0.3.0-fix-config-install.patch
Signed-off-by: Jonathan G. Underwood <jonathan.underwood@gmail.com>
Maintainer: me
Description: update to version 0.3.0
> [19.07] stubby: update to version 0.3.0

- sound/forked-daapd/Makefile
- sound/forked-daapd/patches/020-gcc10.patch
> forked-daapd: fix compilation with GCC10

- utils/ykpers/Makefile
- utils/ykpers/patches/020-json-c-0.14.patch
Adjusted package to use PKG_INSTALL for consistency between packages.
Adjusted InstallDev section to install the pkgconf file.
Maintainer: @stuwilkins 
> ykpers: fix compilation with newer json-c

- utils/gnuplot/Makefile
Maintainer: @datafl4sh
Compile tested: x86_64, sunxi
Run tested: x86_64, sunxi
Description: Fixed dependencies.
> gnuplot: Fixed dependencies.

- net/apfree-wifidog/Makefile
- net/apfree-wifidog/patches/020-gcc10.patch
> apfree-wifidog: fix compilation with GCC10

- net/spawn-fcgi/Makefile
> spawn-fcgi: switch to CMake

- net/open-iscsi/Makefile
- net/open-iscsi/files/iscsi-gen-initiatorname
- net/open-iscsi/files/iscsi_discovery
- net/open-iscsi/files/iscsi_fw_login
- net/open-iscsi/files/iscsi_offload
- net/open-iscsi/files/open-iscsi
- net/open-iscsi/patches/0002-idmb_rec_write-check-for-tpgt-first.patch
- net/open-iscsi/patches/0003-idbm_rec_write-seperate-old-and-new-style-writes.patch
- net/open-iscsi/patches/0004-idbw_rec_write-pick-tpgt-from-existing-record.patch
- net/open-iscsi/patches/0015-remove-the-offload-boot-supported-ifdef.patch
- net/open-iscsi/patches/0019-Coverity-scan-fixes.patch
- net/open-iscsi/patches/0023-iscsi_if.h-replace-zero-length-array-with-flexible-a.patch
- net/open-iscsi/patches/01-fixiscsi_iname_core_dumps.patch
- net/open-iscsi/patches/02-change_include_poll_h.patch
- net/open-iscsi/patches/03-ignore_iface_example.patch
iscsi initiator utilities
Tested x86
depends on #11830 and https://github.com/openwrt/openwrt/pull/2918
> open-iscsi: add package open-iscsi

- admin/htop/Makefile
- admin/htop/patches/010-gcc10.patch
> htop: fix compilation with GCC10

- net/mwan3/Makefile
- net/mwan3/files/etc/init.d/mwan3
- net/mwan3/files/lib/mwan3/mwan3.sh
- net/mwan3/files/usr/libexec/rpcd/mwan3
- net/mwan3/files/usr/sbin/mwan3
- net/mwan3/files/usr/sbin/mwan3track
Maintainer: me
Compile tested: no needed only script changes
Run tested: x86_64 lantiq_xrx200, APU3, OpenWrt master
Description:
Sync mwan3 with master.
This pullrequest adds the missing commit from master branch to the stable branch openwrt-19.07.
Following fixes where done in master:
* IPv6 fixes improvements
https://github.com/openwrt/packages/commit/49cf5eac5cfcfbf371e84d8ddaa0e1b55175100f#diff-34590d11545c84b961d1992ce3aefdeb
https://github.com/openwrt/packages/commit/aafdd0730c765f32ed40c8f3b2ef11ec7cece3c0#diff-34590d11545c84b961d1992ce3aefdeb
https://github.com/openwrt/packages/commit/cf38136b005219917098a0562b0833fa28e007d7#diff-34590d11545c84b961d1992ce3aefdeb
* Performance improvements
https://github.com/openwrt/packages/commit/02ebd831c1247508ab5555ffa7dbfebe95e3501d#diff-34590 …
> mwan3: sync with master branch

- libs/leptonica/Makefile
- utils/tesseract/Makefile
- utils/tesseract/patches/010-cmake.patch
> tesseract/leptonica: switch to CMake

- utils/qemu/Makefile
Maintainer: me
Description:
Fixes openwrt/packages#12808
> qemu: explictly --disable-linux-io-uring

- net/mwan3/Makefile
- net/mwan3/files/lib/mwan3/mwan3.sh
Maintainer: me
Description:
With this pullrequest I want to fix some shellcheck warnings.
I think more will follow!
> mwan3: fix some shellcheck warnings

- libs/libmpdclient/Makefile
> libmpdclient: update to 2.19

- libs/rpcsvc-proto/Makefile
> rpcsvc-proto: update to 1.4.2

- net/nginx/Makefile
Maintainer: @Ansuel and @heil 
Run tested: x86_64, x86_64 qemu, master, run luci-nginx.
Description: update to newest version.
> nginx: update to version 1.19.1

- net/zerotier/Makefile
- net/zerotier/patches/030-gcc10.patch
Patch taken from upstream.
Maintainer: @mwarning 
> zerotier: fix compilation with GCC10

- utils/rtty/Makefile
> rtty: update to 7.1.4

- net/kcptun/Makefile
bump to v20200701.
Maintainer: me, @liudf0716, @zhanhb 
Compile tested: ar71xx, x86-64
> kcptun: bump to v20200701

- net/wsdd2/Makefile
- net/wsdd2/files/wsdd2.init
Maintainer: me
Run tested: arm/mvebu (master)
Description:
* Uppercase NB_PARM, if mdns option is not set
* filter commented lines
PS: resolves limbo #12757
> wsdd2: Uppercase NB_PARM

- net/bfdd/Makefile
- net/bfdd/patches/020-gcc10.patch
> bfdd: fix compilation with GCC 10

- net/apinger/Makefile
- net/apinger/patches/020-gcc10.patch
> apinger: fix compilation with GCC 10

- utils/ncdu/Makefile
> ncdu: update to 1.15.1

- utils/device-observatory/Makefile
- utils/device-observatory/patches/020-libmicrohttpd.patch
API change.
Maintainer: @mwarning 
> device-observatory: fix compilation with newer libmicrohttpd

- utils/mc/Makefile
- utils/mc/patches/010-subshell.patch
- utils/mc/patches/020-fix-mouse-handling-newer-terminfo.patch
Run tested: x86 - apu2
Description:
* refreshed patches
* release news: http://midnight-commander.org/wiki/NEWS-4.8.25
> mc: update to 4.8.25

- libs/libulfius/Makefile
- libs/libulfius/patches/010-libmicrohttpd.patch
API change.
Maintainer: @lnslbrty 
> libulfius: fix compilation with newer libmicrohttpd

- utils/mc/Makefile
- utils/mc/patches/010-subshell.patch
- utils/mc/patches/020-fix-mouse-handling-newer-terminfo.patch
Run tested: x86-apu2
Description:
* refreshed patches
* release news: http://midnight-commander.org/wiki/NEWS-4.8.25
> mc [19.07]: update to 4.8.25

- multimedia/gst1-libav/Makefile
- multimedia/gst1-libav/patches/010-distutils.patch
- multimedia/gst1-plugins-bad/Makefile
- multimedia/gst1-plugins-bad/patches/010-distutils.patch
- multimedia/gst1-plugins-base/Makefile
- multimedia/gst1-plugins-base/patches/010-distutils.patch
- multimedia/gst1-plugins-good/Makefile
- multimedia/gst1-plugins-good/patches/010-distutils.patch
- multimedia/gst1-plugins-ugly/Makefile
- multimedia/gst1-plugins-ugly/patches/010-distutils.patch
- multimedia/gstreamer1/Makefile
- multimedia/gstreamer1/patches/010-gstplugin-use-lazy-symbol-binding.patch
- multimedia/gstreamer1/patches/020-distutils.patch
All were patched to remove a host python3-distutils dependency. This should probably be followed upstream...
> gstreamer suite: update to 1.17.2

- net/mwan3/Makefile
- net/mwan3/files/etc/hotplug.d/iface/15-mwan3
- net/mwan3/files/etc/hotplug.d/iface/16-mwan3
- net/mwan3/files/etc/hotplug.d/iface/16-mwan3-user
- net/mwan3/files/lib/mwan3/mwan3.sh
- net/mwan3/files/usr/sbin/mwan3
Description:
- Fix race condition on mwan3 restart
- Revert: also cleanup lock on mwan3 stop
- Remove lock file cleanup entirely
- Unify variable check
> mwan3: update to version 2.8.12

- utils/yara/Makefile
> yara: update to 4.0.2

- utils/unrar/Makefile
> unrar: update to 5.9.4

- utils/ttyd/Makefile
- utils/ttyd/patches/100-log-to-syslog.patch
Refresh patch.
Maintainer: @tsl0922 
> ttyd: update to 1.6.1

- net/unbound/Makefile
Maintainer: me
Tested: Linksys WRT3200ACM
Description: latest version
> unbound: update to 1.11.0

- net/inadyn/Makefile
Remove pic hack.
Fix license information.
Maintainer: @openwrt/package-maintainers 
> inadyn: update to 2.7

- libs/libextractor/Makefile
FFmpeg has patented functionality.
> libextractor: remove ffmpeg plugin

- utils/yara/Makefile
- utils/yara/patches/010-openssl.patch
> yara: fix compilation without deprecated OpenSSL APIs

- net/ntpd/Makefile
- net/ntpd/files/ntpd.init
Compile tested: only scrip change
Run tested: -
Description:
This should fix this usecase #12777 , which is not possible at the moment.
> ntpd: add config include support

- libs/libssh/Makefile
- libs/libssh/patches/0003-CVE-2020-16135.patch
Compile tested: Turris Omnia (TOS5), OpenWrt master
Description:
This PR patches security issue [CVE-2020-16135](https://nvd.nist.gov/vuln/detail/CVE-2020-16135)
Signed-off-by: Jan Pavlinec <jan.pavlinec@nic.cz>
> libssh: patch security issue

- libs/ldns/Makefile
- libs/ldns/patches/001-compile-for-darwin.patch
- libs/ldns/patches/030-signzone.patch
> ldns: fix compilation without deprecated APIs

- utils/lcdproc/Makefile
- utils/lcdproc/patches/120-gcc10.patch
Maintainer: @haraldg @pprindeville 
> lcdproc: fix compilation with GCC 10

- net/netdiscover/Makefile
- net/netdiscover/patches/010-gcc10.patch
> netdiscover: fix compilation with GCC 10

- utils/lcd4linux/Makefile
- utils/lcd4linux/patches/171-allow-to-specify-drv_generic_graphic_real_clear.patch
> lcd4linux: fix compilation with GCC 10

- mail/alpine/Makefile
- mail/alpine/patches/010-cdefs.patch
> alpine: fix compilation without sys/cdefs

- multimedia/tvheadend/Makefile
- multimedia/tvheadend/patches/030-gcc10.patch
> tvheadend: fix compilation with GCC 10

- net/oor/Makefile
- net/oor/patches/010-gcc10.patch
> oor: fix compilation with GCC 10

- utils/stress/Makefile
The original website went down.
> stress: use fossies mirror

- libs/keyutils/Makefile
- libs/keyutils/patches/020-rindex.patch
> keyutils: fix deprecated function usage

- libs/liburcu/Makefile
- libs/liburcu/patches/010-no-tests.patch
Faster compilation
Maintainer: @salzmdan 
> liburcu: don't build docs and tests

- utils/serialconsole/Makefile
- utils/serialconsole/patches/010-deprecated.patch
Maintainer: @stblassitude supposedly
> serialconsole: fix compilation with uClibc-ng

- lang/python/python-hyperlink/Makefile
- lang/python/python-hyperlink/patches/001-omit-tests.patch
Maintainer: me
Compile tested: armvirt-32, 2020-08-11 snapshot sdk
Description:
> python-hyperlink: Update to 20.0.1

- utils/findutils/Makefile
> findutils: do not use selinux

- devel/lpc21isp/Makefile
- devel/lpc21isp/patches/110-bzero.patch
- devel/lpc21isp/patches/120-nanosleep.patch
> lpc2list: remove deprecated functions

- utils/logrotate/Makefile
> logrotate: remove selinux support

- utils/sed/Makefile
Fixes compilation.
Maintainer: @RussellSenior
> sed: don't use selinux

- utils/sysstat/Makefile
- utils/sysstat/patches/010-ldflags.patch
> sysstat: update to 12.4.0

- net/modemmanager/Makefile
https://lists.freedesktop.org/archives/modemmanager-devel/2020-August/008099.html
> modemmanager: bump to 1.14.2

- net/isc-dhcp/Makefile
> isc-dhcp: fix compilation with GCC 10

- net/nginx/Makefile
Maintainer: @Ansuel and @heil 
Run tested: x86_64, x86_64 qemu, master, run luci-nginx
Description: update to newest version.
> nginx: update to version 1.19.2

- libs/libuhttpd/Makefile
> libuhttpd: Update to 3.2.0

- lang/python/django/Makefile
- lang/python/openpyxl/Makefile
Maintainer: me, @peter-stadler (for Django)
Compile tested: x86 https://github.com/openwrt/openwrt/commit/a69949a13f8cf3eca0fccda0d826928034877c9b
Run tested: x86 https://github.com/openwrt/openwrt/commit/a69949a13f8cf3eca0fccda0d826928034877c9b
> django,openpyxl: bump versions

- net/wavemon/Makefile
> wavemon: fix compilation with glibc

- libs/alsa-lib/Makefile
> alsa-lib: update to 1.2.3.2

- devel/ninja/Makefile
> ninja: update to 1.10.1

- libs/p11-kit/Makefile
> p11-kit: update to 0.23.21

- libs/libdcwsocket/Makefile
- libs/libdcwsocket/patches/010-glibc.patch
> libdcwsocket: fix compilation with glibc

- sound/alsa-utils/Makefile
> alsa-utils: update to 1.2.3

- libs/lmdb/Makefile
> lmdb: fix compilation with glibc

- utils/ap51-flash/Makefile
- utils/ap51-flash/files/ap51-flash.init
- utils/ap51-flash/files/ap51-flash.sh
> ap51-flash: run through shellcheck

- utils/stress-ng/Makefile
- utils/stress-ng/patches/010-soft-float.patch
This is a replacement for the old stress utility.
> stress-ng: add

- lang/python/python-host.mk
- lang/python/python3-host.mk
Compile tested: armvirt-32, 19.07.3 sdk
Description:
> [openwrt-19.07] python,python3: Use locked for host pip

- net/kismet/Makefile
- net/kismet/patches/040-uclibc.patch
> kismet: fix compilation under uClibc-ng and GCC10

- net/adblock/Makefile
- net/adblock/files/README.md
- net/adblock/files/adblock.sources
Run tested: Ubiquiti EdgeRouter X, OpenWrt SNAPSHOT r14172-7ef7dbaf70
Description:
* rename 'smarttv' to 'smarttv_tracking'
* added 'firetv_tracking' and 'android_tracking' (thanks @panache67)
* added 'gaming' (thanks @hasanlo in openwrt forum)
* update readme
> adblock: refresh blocklist sources

- libs/libcap/Makefile
> libcap: update to 2.43

- libs/libdrm/Makefile
Cleaned up Install sections for consistency between packages.
> libdrm: update to 2.4.102

- libs/libinput/Makefile
Makes several files explicit in Install sections.
> libinput: update to 1.16.1

- libs/libevdev/Makefile
Clean up Install section to be more explicit about what gets installed.
> libevdev: update to 1.9.1

- net/unbound/Makefile
- net/unbound/files/odhcpd.sh
Maintainer: me
Tested: Linksys WRT3200ACM
Description: https://forum.openwrt.org/t/issues-with-unbound-and-odhcp-setup/66354/24
> unbound: improve odhcpd rapid update robustness

- utils/prometheus/Makefile
> prometheus: bump to 2.20.1

- net/frr/Makefile
- net/frr/patches/098-fix_mips_libyang.patch
add mips fix missed on version upgrade
Maintainer: me
Run tested MT7621
> frr: fix running on mips (again)

- utils/syncthing/Makefile
> syncthing: bump to 1.9.0 and set specific USERID

- libs/libpsl/Makefile
- libs/libpsl/patches/010-python.patch
- multimedia/gst1-libav/Makefile
- multimedia/gst1-plugins-bad/Makefile
- multimedia/gst1-plugins-base/Makefile
- multimedia/gst1-plugins-base/patches/010-distutils.patch
- multimedia/gst1-plugins-good/Makefile
- multimedia/gst1-plugins-ugly/Makefile
- multimedia/gstreamer1/Makefile
I probably should not have updated these to the 1.17 versions, which are not stable releases...
> gstreamer updates

- net/memcached/Makefile
> memcached: update to 1.6.7

- net/ariang/Makefile
> ariang: update to 1.1.17

- lang/node-serialport/Makefile
- lang/node-serialport/patches/001-turn_off_depends.patch
Maintainer: me
Compile tested: head r14505-e6b4238, aarch64 
Run tested: aarch64 (qemu 5.1.0)
Description:
update to 9.0.1
> node-serialport: update to 9.0.1

- utils/vim/test.sh
Maintainer: Marko Ratkaj <marko.ratkaj@sartura.hr>
Run tested: CI
Description:
Run test script to see if compiled binary prints sane output.
> vim: add runtime test

- utils/spi-tools/Makefile
> spi-tools: update to 0.8.5

- devel/meson/Makefile
> meson: update to 0.55.3

- net/vpnbypass/Makefile
- net/vpnbypass/files/README.md
- net/vpnbypass/files/vpnbypass.init
- net/vpnbypass/test.sh
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 19.07.3
Description: updated README, minor code cleanup.
Please merge, I don't have merge rights to packages.
> [19.07] vpnbypass: README update, code cleanup

- net/vpnbypass/Makefile
- net/vpnbypass/files/README.md
- net/vpnbypass/files/vpnbypass.init
- net/vpnbypass/test.sh
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 19.07.3
Description: updated README, minor code cleanup.
Please merge, I don't have merge rights to packages.
> [18.06] vpnbypass: README update, code cleanup

- net/vpnbypass/Makefile
- net/vpnbypass/files/README.md
- net/vpnbypass/files/vpnbypass.init
- net/vpnbypass/test.sh
Maintainer: me
Compile tested: mvebu, WRT3200ACM, 19.07.3
Description: updated README, minor code cleanup.
Please merge, I don't have merge rights to packages.
> vpnbypass: README update, code cleanup

- utils/tmux/test.sh
Maintainer: Maxim Storchak <m.storchak@gmail.com>
Run tested: CI
Description:
Run test script to see if compiled binary prints sane output.
> tmux: add runtime test

- net/frp/Makefile
Maintainer: me
Compile tested: x86_64, snapshot
Run tested: x86_64, snapshot
> frp: update to 0.34.0

- libs/libsoup/Makefile
> libsoup: update to 2.71.1

- net/nextdns/Makefile
> nextdns: Update to version 1.8.4

- net/nextdns/Makefile
> [19.07] nextdns: Update to version 1.8.4

- sound/mpd/Makefile
- sound/mpd/patches/020-npupnp.patch
Refreshes patches and updated MESON_ARGS.
> mpd: update to 0.22

- net/scapy/Makefile
> scapy: update to 2.4.4

- net/travelmate/Makefile
- net/travelmate/files/README.md
- net/travelmate/files/db-bahn.login
- net/travelmate/files/travelmate.mail
- net/travelmate/files/travelmate.sh
- net/travelmate/files/travelmate.vpn
- net/travelmate/files/wifionice.login
Run tested: OpenWrt SNAPSHOT r14571-621297e867
Description:
* fix some remaining vpn issues
* various cleanups
> travelmate: update to 2.0.1

- sound/madplay/Makefile
- sound/madplay/patches/020-no-po.patch
> madplay: fix compilation with full NLS

- net/transmission/Makefile
- net/transmission/patches/010-no-intltool.patch
> transmission: fix compilation with full NLS
