openwrt/packages

libs/pthsem/Makefile
libs/pthsem/patches/001-linux3x-fix.patch

From the README:
This is a modified version of pth with pth-sem.patch and other patches applied
and the build system changed to create different file names.
Martin Kögler
mkoegler@auto.tuwien.ac.at

pthsem: new package

---

net/knxd/Makefile
net/knxd/files/knxd.config
net/knxd/files/knxd.init
net/knxd/patches/0099-openwrt.patch

knxd is a fork of eibd 0.0.5 (from bcusdk) https://www.auto.tuwien.ac.at/~mkoegler/index.php/bcusdk
Hosted on: https://github.com/Makki1/knxd

knxd: new package

---

net/linknx/Makefile
net/linknx/files/linknx.config
net/linknx/files/linknx.init
net/linknx/files/linknx.xml.dist

Linknx is an automation platform providing high level functionalities to EIB/KNX installation. The rules engine allows execution of actions based on complex logical conditions and timers. Lightweight design allows it to run on embedded Linux
Hosted on: http://sourceforge.net/projects/linknx/

linknx: new package

---

libs/pthsem/Makefile

pthsem: fix Makefile to use TABs instead of spaces

---

net/knxd/Makefile

knxd: fix Makefile to use TABs instead of spaces

---

net/openconnect/README

Signed-off-by: Gottfried Haider <gottfried.haider@gmail.com>

openconnect: update README

---

net/prosody/Makefile
net/prosody/patches/010-fix-randomseed.patch

prosody: fix use of randomseed (prosody issue #439)

---

net/linknx/Makefile

linknx: use better macros in Makefile

---

net/knxd/Makefile

knxd: use better macrons in Makefile

---

lang/python-pip/Makefile

Reduce some bloat by removing some Windows binaries; maybe a bigger effort would be in order to reduce bloat; will plan for later.
Fix conflicts with python-setuptools; thanks @Xuefer <xuefer@gmail.com> for reporting
Note: please merge this after PR https://github.com/openwrt/packages/pull/740

Python pip cleanups

---

lang/luaposix/Makefile
lang/luaposix/patches/100-eglibc-compat.patch
lang/luaposix/patches/101-disable-curses.patch

luaposix: update to v33.2.1

---

libs/libuvc/Makefile

Signed-off-by: Roger D <rogerdammit@gmail.com>

libuvc: add package

---

net/linknx/Makefile

linknx: fix permissions, add conffiles in Makefile

---

lang/python-setuptools/Makefile
lang/python-setuptools/patches/0001-remove-windows-support.patch

Fixes issues:
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/seafile-seahub/compile.txt
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/python-pip/compile.txt
http://buildbot.openwrt.org:8010/broken_packages/ar71xx/python-mysql/compile.txt

Python setuptools fix

---

lang/python/Makefile
lang/python/files/python-package.mk
lang/python/patches/150-fix-libffi-x86-64-configure.patch

Python updates

---

net/privoxy-luci/Makefile
net/privoxy-luci/build/i18n-po2lua.pl
net/privoxy-luci/files/luasrc/controller/privoxy.lua
net/privoxy-luci/files/luasrc/model/cbi/privoxy/apperror.lua
net/privoxy-luci/files/luasrc/model/cbi/privoxy/detail.lua

* Makefile
- modified to support new LuCI build structure when building i18n support
- increase "patch" version
* privoxy.lua detail.lua apperror.lua
- modified version detection
- removed function ipgk_version()
* new file build/i18n-po2lua.pl
- copied from luci build system to create lmo language files
Signed-off-by: Christian Schoenebeck <christian.schoenebeck@gmail.com>

luci-app-privoxy: modified to support new LuCI structure

---

utils/gammu/Makefile

---
Makefile |    1 +
1 file changed, 1 insertion(+)

gammu: add libusb dependency

---

net/knxd/Makefile

knxd: bump to latest release, add conffile

---

net/knxd/Makefile

knxd: fix path in Makefile and some cleanups

---

libs/libsodium/Makefile

libs/libsodium: update to 1.0.2

---

lang/python/Makefile
lang/python3/Makefile
lang/python3/files/python3-package.mk

python3: update using python updates as template

---

utils/sockread/Makefile
utils/sockread/src/Makefile
utils/sockread/src/main.c

sockread reads data from a Unix domain socket

sockread: add new package

---

net/coova-chilli/Config.in

coova-chilli: fix typo in Config.in

---

libs/openldap/Makefile
libs/openldap/files/ldap.init

openldap: remove --without-tls

---

sound/madplay/Makefile

https://dev.openwrt.org/ticket/18713

madplay: import from old packages feed

---

utils/hub-ctrl/Makefile

Power on/off USB ports on hubs, see https://forum.openwrt.org/viewtopic.php?id=49012

hub-ctrl: Control USB power on a port by port basis

---

sound/shairport-sync/Makefile
sound/shairport-sync/files/shairport-sync.config
sound/shairport-sync/files/shairport-sync.init

shairport-sync: New package from MikeBrady

---

devel/patch/Makefile

Signed-off-by: Russell Senior <russell@personaltelco.net>

patch: bump to version 2.7.3

---

sound/svox/Makefile
sound/svox/patches/0001-autoconf-building-of-library-using-libtool.patch
sound/svox/patches/0002-gitignore-for-autotools-files.patch
sound/svox/patches/0003-pico2wave-Convert-text-to-.wav-using-svox-text-to-sp.patch
sound/svox/patches/0004-add-header-files.patch
sound/svox/patches/0005-Install-lang-files.patch
sound/svox/patches/0006-Set-picolangdir.patch
sound/svox/patches/0008-64bits.patch
sound/svox/patches/0009-Fix-link-order.patch
sound/svox/patches/0010-platform.patch
sound/svox/patches/0011-subdir.patch
sound/svox/patches/0012-no-headers.patch

Hi!
This is the SVOX PicoTTS text-to-speech engine package. It brings pico2wave, a small footprint TTS especially developed for embedded in automotive (see Makefile desc for details). The first 10 patches came from  http://ftp.de.debian.org/debian/pool/non-free/s/svox/svox_1.0+git20130326-3.debian.tar.xz. The code base is quite old (2013) but AFAIK this is the only one that makes a fully functional SVOX engine with no segfaults whatsoever.
Usage hint:
pico2wave -w /tmp/speech.wav -l en-GB "Hello World"
aplay /tmp/speech.wav
Signed-off-by: Alessandro Di Marco <dmr@ethzero.com>

svox: add package

---

libs/liburcu/Makefile

Thanks to @probonopd for the hint.
Signed-off-by: Christoph Koenig <christoph.koenig@gmail.com>

liburcu: Update to 0.8.6

---

lang/luaposix/Makefile
lang/luaposix/patches/102-disable-compat-deprecated.diff

luaposix: remove deprecated/compatibility modules, remove dependency on luabitop

---

net/privoxy/Makefile

privoxy: new upstream version 3.0.23

---

net/aircrack-ng/Makefile

cleanup, update to latest version, mark myself maintainer
Signed-off-by: Rick Farina (Zero_Chaos) <zerochaos@gentoo.org>

aircrack-ng: import from old packages

---

ipv6/tayga/files/tayga-proto.sh

In some scenarios (e.g. 464xlat) it is desirable to not route the mapped
prefix to tayga's interface. This adds an option 'noroutes' which, when
set to 1, will prevent such routes from being added.
Signed-off-by: Nils Schneider <nils@nilsschneider.net>

tayga: allow more flexible routing

---

net/seafile-ccnet/Makefile
net/seafile-seahub/Makefile
net/seafile-server/Makefile
net/seafile-server/files/seafile.init

seafile: update to version 4.0.6

---

utils/gammu/Makefile

---
Makefile |    2 +-
1 file changed, 1 insertion(+), 1 deletion(-)

gammu: remove unneeded dependencies

---

net/dmapd/patches/002-make_unit_test_optionnal.patch

dmapd: make check library optionnal

---

net/knxd/files/knxd.init

knxd: improve init script

---

utils/lvm2/Makefile
utils/lvm2/files/lvm2.init

lvm2: set cache directory to /tmp/lvm/cache

---

admin/sudo/Makefile

sudo: update to version 1.8.12

---

net/rsync/Makefile
net/rsync/patches/000-CVE-2014-9512.patch

rsync: patch CVE-2014-9512

---

utils/unzip/Makefile
utils/unzip/patches/001-CVE-2014-8139-crc-overflow.patch
utils/unzip/patches/002-CVE-2014-8140-test-compr-eb.patch
utils/unzip/patches/003-CVE-2014-8141-getzip64data.patch
utils/unzip/patches/004-CVE-2014-9636-test-compr-eb.patch

Backports https://github.com/openwrt/packages/commit/857def5d1a07a514c69ef3db39bee5884de4a716 to Barrier Breaker

unzip: patch CVE-2014-8139, CVE-2014-8140, CVE-2014-8141 and CVE-2014-9636

---

net/apcupsd/Makefile
net/apcupsd/files/apccontrol
net/apcupsd/files/apcupsd.conf
net/apcupsd/files/apcupsd.init
net/apcupsd/files/apcupsd_mail.conf
net/apcupsd/files/changeme
net/apcupsd/files/commfailure
net/apcupsd/files/commok
net/apcupsd/files/offbattery
net/apcupsd/files/onbattery
net/apcupsd/patches/010-fix-include-paths.patch

Signed-off-by: Othmar Truniger <Othmar Truniger github@truniger.ch>

apcupsd: move from old packages and Makefile updated

---

net/krb5/Makefile
net/krb5/patches/001-fix-build.patch

krb5: update to 1.13.1

---

libs/libunistring/Makefile

libunistring: update to 0.9.5

---

sound/forked-daapd/Makefile

forked-daapd: update to 22.3

---

net/knot/Makefile

Signed-off-by: Daniel Salzman <daniel.salzman@nic.cz>

knot: update to 1.6.2

---

net/apcupsd/Makefile
net/apcupsd/files/multimon.conf
net/apcupsd/patches/010-fix-usb.patch

apcupsd: add driver modbus-usb

---

lang/php5/Makefile
lang/php5/patches/950-Fix-dl-cross-compiling-issue.patch

php5: update to 5.6.6

---

net/openvswitch/Makefile

openvswitch: limit package to supported kernel versions

---

multimedia/ffmpeg/Makefile

Signed-off-by: Ian Leonard <antonlacon@gmail.com>

ffmpeg: update to 2.5.4

---

libs/opencv/Makefile

Signed-off-by: Jianping Li <summer@wrtnode.com>

update opencv version as 2.4.11

---

mail/mailman/Makefile
mail/mailman/patches/100-postfix.patch

mailman: version upgrade to 2.1.19

---

libs/gnutls/Makefile

- rebased patch series
- compile test + tested with curl (gnutls linked) on a qemu x86_64

Gnutls fixes v2

---

multimedia/gst1-libav/Makefile
multimedia/gst1-plugins-bad/Makefile
multimedia/gst1-plugins-bad/patches/000-gettext.patch
multimedia/gst1-plugins-base/Makefile
multimedia/gst1-plugins-base/patches/001-no_docs.patch
multimedia/gst1-plugins-base/patches/002-no_tests.patch
multimedia/gst1-plugins-base/patches/003-no_translations.patch
multimedia/gst1-plugins-good/Makefile
multimedia/gst1-plugins-good/patches/001-no_docs.patch
multimedia/gst1-plugins-good/patches/002-no_tests.patch
multimedia/gst1-plugins-good/patches/003-no_translations.patch
multimedia/gst1-plugins-ugly/Makefile
multimedia/gst1-plugins-ugly/patches/001-no_docs.patch
multimedia/gst1-plugins-ugly/patches/002-no_tests.patch
multimedia/gst1-plugins-ugly/patches/003-no_translations.patch
multimedia/gstreamer1/Makefile
multimedia/gstreamer1/patches/001-no_docs.patch
multimedia/gstreamer1/patches/002-no_tests.patch
multimedia/gstreamer1/patches/003-no_translations.patch

* Update to lastest stable release
* Refresh / clean patches
* Fix some build dependencies (liboil & libgcrypt)
@MikePetullo -- fyi (or reject)

gstreamer: Update to 1.4.5

---

net/knxd/Makefile
net/knxd/patches/0099-openwrt.patch

knxd: follow new respository

---

lang/vala/Makefile

* update source version to 0.27.1
* fix build dependency issue #702

vala: update to version 0.27.1 + fix build issue

---

net/openvswitch/Makefile

openvswitch: limit kernel package to supported kernel versions

---

net/seafile-seahub/Makefile

seafile: fix download issue with python dependencies

---

utils/kmod/Makefile

Signed-off-by: Jeff Waugh <jdub@bethesignal.org>

kmod: Update to kmod 20, enable parallel build

---

libs/libesmtp/Makefile

libesmtp: streamline makefile

---

libs/pthsem/Makefile

pthsem: streamline makefile

---

net/wshaper/Makefile
net/wshaper/files/wshaper.iface

Signed-off-by: Stanislav German-Evtushenko <ginermail@gmail.com>

wshaper: start wshaper on ifup

---

lang/python/Makefile

python: fix conflicts between python-light & python-base

---

net/linknx/Makefile

linknx: streamline makefile

---

net/mwan3-luci/Makefile
net/mwan3-luci/files/usr/lib/lua/luci/model/cbi/mwan/rule.lua
net/mwan3-luci/files/usr/lib/lua/luci/model/cbi/mwan/ruleconfig.lua

new mwan3 1.6 rule options added:
- sticky
- timeout
- ipset
Signed-off-by: Aedan Renner chipdankly@gmail.com

 mwan3-luci: update to 1.4-2

---

net/stunnel/Makefile
net/stunnel/files/stunnel.conf
net/stunnel/files/stunnel.init
net/stunnel/patches/010_fix_getnameinfo.patch
net/stunnel/patches/011_disable_ssp_linking.patch

stunnel: bring back stunnel

---

net/linknx/Makefile

linknx: fix dependency

---

sound/pianod/Makefile
sound/pianod/files/pianod.init
sound/pianod/patches/005-Fix_IPV6_socket_handling.patch
sound/pianod/patches/010-Configure_add_SSL_options.patch
sound/pianod/patches/020-Use_package_config_h_for_all_modules.patch
sound/pianod/patches/030-Waitress_add_polarssl_variant.patch

* Integrate as OpenWrt daemon
* Build with PolarSSL (replaces GNUTLS)
* Integrate optional pianod-client (WebUI package)
* Fix some socket failure handling and segfaults
TBD:
* Convert remote control interface to use PolarSSL (currently admin TLS disabled)

pianod: Add Pandora Radio player daemon

---

net/dmapd/Makefile

dmapd: update to 0.0.71

---

utils/nano/Makefile

Signed-off-by: Jonathan Bennett jbennett@incomsystems.biz
The pre-release branch we have been tracking is now the stable release.

Update Nano to 2.4 release

---

utils/mc/Makefile

Update Midnight Commander to latest stable release.
Major changes described here: https://www.midnight-commander.org/wiki/NEWS-4.8.14
Signed-off-by: Dirk Brenken <dibdot@gmail.com>

mc: bump version to 4.8.14

---

multimedia/mjpg-streamer/Makefile

mjpg-streamer: Fixed cambozola MD5 sum.

---

net/wget/Makefile

wget: update to 1.16.3

---

utils/haserl/Makefile

haserl: update to 0.9.35

---

net/transmission/patches/030-fix-musl-build.patch

transmission: fix build with musl

---

net/transmission/Makefile
net/transmission/patches/010_libtransmission_fallocate64_eglibc.patch

Signed-off-by: Cezary Jackiewicz <cezary@eko.one.pl>

transmission: fix build problem with fallocate64

---

net/noip/Makefile
net/noip/files/etc/init.d/noip
net/noip/files/etc/no-ip2.conf
net/noip/patches/001-Makefile-DESTDIR.patch
net/noip/patches/002-Makefile-dont-run.patch

This is the client program for noip.com, which is a dynamic dns provider.
Signed-off-by: Lawrence D'Anna <larry@elder-gods.org>

new package: noip

---

net/knxd/Makefile

knxd: fix dependency in makefile

---

mail/mailman/Makefile

mailman: upgrade to 2.1.20

---

multimedia/ffmpeg/Makefile

Signed-off-by: Ian Leonard <antonlacon@gmail.com>

ffmpeg: upgrade to 2.5.5

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/ddns.config
net/ddns-scripts/files/ddns.init
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/dynamic_dns_lucihelper.sh
net/ddns-scripts/files/services_ipv6
net/ddns-scripts/files/tld_names.dat

* fix problem with lucihelper script reported in OpenWrt Ticket 19419
* rewritten split_FQDN fixing detection errors and using zcat
* updated tld_names.dat and .gz compressed to reduce size
* add LoopiaDNS (loopia.se) to services_ipv6

ddns-scripts: bugfixes/update to version 2.4.1-1

---

net/unbound/Makefile
net/unbound/patches/001-conf.patch

unbound 1.5.3 was released on March 10, 2015.

Update net/unbound to version 1.5.3

---

net/dmapd/Makefile

dmapd: update to 0.0.72

---

lang/python3/files/python3-package-ncurses.mk
lang/python3/patches/011-do-not-prefer-ncursesw.patch

python3: force libncurses

---

lang/python/files/python-package-ncurses.mk
lang/python/patches/011-do-not-prefer-ncursesw.patch

Related to PR: https://github.com/openwrt/packages/pull/1157

python: force libncurses

---

net/radicale/Makefile
net/radicale/files/config.template
net/radicale/files/logging.template
net/radicale/files/radicale.config
net/radicale/files/radicale.hotplug
net/radicale/files/radicale.init
net/radicale/files/radicale.rights
net/radicale/files/radicale.users
net/radicale/patches/010-Run-as-user-group-radicale-radicale.patch

Inspired by OpenWrt Ticket System Ticket 9119
Python3 package version currently marked as @BROKEN because no time for testing.

radicale: [NEW] Python-based CalDAV/CardDAV Server

---

libs/gnutls/Makefile

updated OpenWrt header, added license information.

[libs/gnutls] Added gettext-version fixup,

---

net/knot/Makefile
net/knot/patches/03_zscanner_tests.patch

Signed-off-by: Daniel Salzman <daniel.salzman@nic.cz>

knot: update to 1.6.3

---

utils/openocd/Makefile

Signed-off-by: Paul Fertser <fercerpav@gmail.com>

openocd: update to 0.9.0-rc1

---

lang/python3/files/python3-package-lzma.mk

python3: add python3-package-lzma.mk

---

utils/avrdude/Makefile
utils/avrdude/patches/010-configure-fixups.patch

Waiting for someone to test this - I don't have a setup for testing right now. It builds OK.

avrdude: move from oldpackages, update to latest version & build opts

---

net/snort/Makefile

[net/snort] Simple liblzma deps fix

---

net/snort/Makefile

Revert "[net/snort] Simple liblzma deps fix"

---

net/snort/Config.in
net/snort/Makefile

Also added optional lzma support.
Fixes #1196

[net/snort] Replaced build variants with compile options.

---

net/coova-chilli/patches/300-fix-compile-with-cyassl.patch

coova-chilli: fix compile error with cyassl

---

net/coova-chilli/Makefile
net/coova-chilli/patches/200-fix_compile_kmod.patch
net/coova-chilli/patches/201-fix_dereferencing_pointers.patch

coova-chilli: add netfilter kernel module package with patches

---

utils/bc/Makefile
utils/bc/patches/001-disable-doc.patch

Copied from oldpackages and slightly updated.

Add package: bc

---

libs/libvorbis/Makefile

Signed-off-by: Ian Leonard <antonlacon@gmail.com>

libvorbis: upgrade to 1.3.5

---

net/fwknop/Makefile
net/fwknop/files/fwknopd
net/fwknop/files/fwknopd.init

Styling cleanups
signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>

Fwknop: add flexibility to uci support

---

mail/postfix/Makefile

postfix: update to 3.0.1

---

lang/lzmq/Makefile
libs/zmq/Makefile

Also, supplying a better desciripton of this package and general cleanup.
@srdgame - please review

zmq: Make libsodium optional

---

net/tcpproxy/Makefile
net/tcpproxy/patches/001-ragel_generated.patch

tcpproxy: update to version 1.2

---

multimedia/ffmpeg/Makefile

Signed-off-by: Ian Leonard <antonlacon@gmail.com>

ffmpeg: update to 2.6.3, remove stray spaces

---

lang/luarocks/Makefile

Signed-off-by: Nicolas Thill <nico@openwrt.org>

luarocks: update to 2.2.2

---

net/usbip/Makefile
net/usbip/patches/001-upstream_svn_r99.diff
net/usbip/patches/002-upstream_svn_r152.patch

Signed-off-by: Cezary Jackiewicz <cezary.jackiewicz@gmail.com>

usbip: import from old packages

---

net/lftp/Makefile

Signed-off-by: Federico Di Marco fededim@gmail.com

lftp: updated to 4.6.2

---

utils/pps-tools/Makefile

pps-tools: enable for Linux 3.18

---

libs/liblz4/Makefile

Signed-off-by: Darik Horn <dajhorn@vanadac.com>

liblz4: add new package

---

net/fwknop/Makefile
net/fwknop/patches/001-add-keygen.patch

Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>
@sbyx This fix needs to be pushed into for-15.05 as well. Do you want me to cherrypick and pull request, or do you want to just handle that?
Thanks,
Jonathan

Fwknopd: Backport patch to enable keygen in fwknopd

---

net/ntpd/Makefile

ntpd: enable ATOM (PPS) support

---

net/radicale/Makefile
net/radicale/files/radicale.config
net/radicale/files/radicale.hotplug
net/radicale/files/radicale.init

* fixed hotplug script (not restarting on "ifup")
* fixed init script (not stopping in 1 second)
* fixed PKG_MAINTAINER string
* removing not needed comments in config file

radicale: fixed hotplug and init script

---

net/ntpd/Makefile

ntpd: enable ATOM (PPS) support [for-15.05]

---

utils/pps-tools/Makefile

pps-tools: enable for Linux 3.18 [for-15.05]

---

net/ethtool/Makefile

Signed-off-by: Shuoyao Wang <wong.syrone@gmail.com>

ethtool: add missing quotation mark in Makefile

---

net/gnurl/Makefile

...as other packages [do](https://github.com/openwrt/packages/pull/1181).

gnurl: Respect IPv6 settings

---

libs/db47/Makefile

The same thing that just went into master. Fixes #1312 for CC.
Thanks to Florian Fieber and commodo.

db47: Force pthread mutexes, bump PKG_RELEASE [for-15.05]

---

utils/lxc/Makefile

Signed-off-by: Alex Samorukov <samm@os2.kiev.ua>

Add lxc-device applet to the utils/lxc

---

utils/smartmontools/Makefile

smartmontools: update to 6.4

---

net/radicale/Makefile
net/radicale/files/radicale.config
net/radicale/files/radicale.hotplug
net/radicale/files/radicale.init

* fixed hotplug script (not restarting on "ifup")
* fixed init script (not stopping in 1 second)
* fixed PKG_MAINTAINER string
* removing not needed comments in config file

[for-15.05] radicale: update to 0.10-2 (not updated from trunk)

---

utils/f2fs-tools/patches/010-include-byteswap-h.patch

f2fs-tools: fix build with musl

---

utils/acpid/Makefile
utils/acpid/files/acpid.hotplug
utils/acpid/files/acpid.init
utils/acpid/files/default
utils/acpid/patches/001-musl-compat.patch
utils/acpid/patches/002-dont-use-isfdtype.patch

maintainer, ensure musl compatibility
- with acpid kvm based setups can react on acpi shutdown and reboot
actions
Signed-off-by: heil <heil@terminal-consulting.de>

acpid: Import from oldpackages, update to latest version, add myself as

---

libs/libarchive/Makefile

libarchive: add build-variant without libopenssl

---

lang/luaposix/Makefile

luaposix: fix compatibility with musl

---

lang/python-crcmod/Makefile

Signed-off-by: Micke Prag <micke.prag@telldus.se>

python-crcmod: new package

---

libs/libmicrohttpd/Makefile
libs/libmicrohttpd/patches/001-bump-to-r35864.patch

libmicrohttpd: update source

---

sound/forked-daapd/Makefile
sound/forked-daapd/files/forked-daapd.conf

forked-daapd: update to 23.2

---

sound/mpc/Makefile

Signed-off-by: Christoph Koenig <christoph.koenig@gmail.com>

mpc: update to 0.27

---

sound/mpd/Makefile
sound/mpd/patches/210-support_raw_pcm_streams.patch
sound/mpd/patches/220-handle_slow_server_stream_startup.patch

Requres #1487 to build correctly

mpd: Upgrade to 0.19.10, refresh patches

---

net/vpnc-scripts/files/vpnc-script

Resolves #1372
Signed-off-by: Nikos Mavrogiannopoulos <nmav@gnutls.org>

vpnc-script: handle multiple servers in INTERNAL_IP_DNS vars

---

net/iodine/Makefile
net/iodine/patches/100-musl-compatibility.patch

iodine: fix musl compatibility

---

net/linknx/Makefile
net/linknx/patches/010-musl-compat
net/linknx/patches/012-fix-linknx.cpp

linknx: fix musl compatibility

---

net/ola/Makefile
net/ola/files/olad.init

Hi there again,
Trying to get someting happening for https://github.com/openwrt/packages/issues/808, this is a new PR which
* updates ola to 0.9.6
* incorporates @mhei's changes
Please lemme know if #808 still persists and if so, what I can do. Thanks!

ola: Update to 0.9.6, tidy up makefile, try to resolve build dependencies

---

utils/gammu/Makefile

gammu: update to latest 1.36.2 upstream

---

utils/shadow/Makefile
utils/shadow/patches/004-fix-su-controoling-term.patch

Signed-off-by: Pelle Johnsen <pelle.johnsen@gmail.com>
If possible please try to include in 15.05

shadow: fix su controlling terminal #1521

---

net/ngircd/Makefile
net/ngircd/files/ngircd.init

Changed in v2: split work into separate commits

[v2] ngircd: import from oldpackages and update to 22.1

---

net/mwan3-luci/Makefile
net/mwan3-luci/files/etc/hotplug.d/iface/16-mwancustombak
net/mwan3-luci/files/usr/lib/lua/luci/controller/mwan3.lua
net/mwan3-luci/files/usr/lib/lua/luci/model/cbi/mwan/interface.lua
net/mwan3-luci/files/usr/lib/lua/luci/model/cbi/mwan/interfaceconfig.lua
net/mwan3-luci/files/usr/lib/lua/luci/model/cbi/mwan/rule.lua
net/mwan3-luci/files/usr/lib/lua/luci/model/cbi/mwan/ruleconfig.lua

mwan3-luci update to version 1.4-3
Fixed two issues in Chaos Calmer and trunk:
-troubleshooting page not displaying
-UCI arguments out of order because of switch to musl c library from uclibc
Signed-off-by: Aedan "arfett" Renner <chipdankly@gmail.com>

mwan3-luci updates for CC/trunk compatibility

---

net/knot/Makefile

Signed-off-by: Daniel Salzman <daniel.salzman@nic.cz>

knot: update to 1.6.4

---

net/lighttpd/Makefile

See https://github.com/openwrt/packages/pull/925

lighttpd: add liblua deps for lighttpd-mod-cml and lighttpd-mod-magnet

---

libs/libunistring/Makefile

libunistring: update to 0.9.6

---

utils/gammu/Makefile

---
Makefile |    6 +++---
1 file changed, 3 insertions(+), 3 deletions(-)

gammu: bump to the new upstream v1.36.3

---

net/vpnc/Makefile
net/vpnc/files/vpnc.sh

Signed-off-by: Daniel Gimpelevich <daniel@gimpelevich.san-francisco.ca.us>

vpnc: corrected call to proto_add_host_dependency

---

libs/mxml/Makefile

mxml: update to 2.9

---

libs/pthsem/Makefile
libs/pthsem/patches/002-fix-signal.h

pthsem: fix signal.h include path

---

sound/squeezelite/Makefile
sound/squeezelite/files/squeezelite.conf
sound/squeezelite/files/squeezelite.init
sound/squeezelite/patches/005-respect_LDFLAGS.patch
sound/squeezelite/patches/010-wait_for_nonzero_mac.patch
sound/squeezelite/patches/020-no_mpg123.patch
sound/squeezelite/patches/030-fix_musl_compatibilty.patch
sound/squeezelite/patches/040-clear_dynlink_errors.patch

No IR support (yet)
mini version has no codec dependencies (auto-config)
full version has all codecs linked in
ffmpeg is optional for WMA & ALAC support

squeezelite: Import new package

---

lang/python-setuptools/Makefile

python-setuptools: upgrade to version 18.0.1

---

lang/python-pip/Makefile

python-pip: upgrade to version 7.1.0

---

net/strongswan/Makefile

Fixes: #1580 
Signed-off-by: Adam Lebsack <alebsack@gmail.com>

strongswan: Added strongswan-mod-eap-tls 

---

libs/openldap/Makefile

Addresses https://github.com/openwrt/packages/issues/1586.

openldap: remove --without-cyrus-sasl to build SASL support

---

libs/openldap/Makefile

This merges the update of openldap from master to for-15.05.

For 15.05: openldap: update to 2.4.41

---

net/mwan3/Makefile
net/mwan3/files/usr/sbin/mwan3

Fix malformed uci commands. (issue #1502)
Signed-off-by: Jeroen Louwes <jeroen.louwes@gmail.com>

mwan3: update to version 1.6-2

---

multimedia/ffmpeg/Makefile

@antonlacon , @ejurgensen -- any objections?

ffmpeg: Update to latest - 2.7.2

---

net/shadowsocks-libev/Makefile
net/shadowsocks-libev/files/shadowsocks-libev.config
net/shadowsocks-libev/files/shadowsocks-libev.init
net/shadowsocks-libev/files/ss-rules

Fix the multiple UDP source port issue.
Allow using different IP and ports for TCP and UDP
Signed-off-by: Jian Chang <aa65535@live.com>

shadowsocks-libev: bump version

---

net/knxd/Makefile

[for-15.05] knxd: bump to newest version for CC

---

libs/opencv/Makefile

Signed-off-by: lijpsummer <summer@wrtnode.com>

opencv:update to version 3.0.0

---

libs/libstrophe/Config.in
libs/libstrophe/Makefile

Config.in for libxml2/expat XML library choice
Signed-off-by: Chih-Wei Chen <changeway@gmail.com>

Add libstrophe : XMPP client library

---

libs/liblo/patches/001-fix-musl-include.patch

liblo: fix build with musl

---

net/tor/Makefile

Signed-off-by: Ondrej Mikle <ondrej.mikle@nic.cz>

tor: update to 0.2.6.10

---

libs/freetype/Makefile

Signed-off-by: Paul Fertser <fercerpav@gmail.com>

freetype: fix include path for cross-compilation

---

lang/lualanes/patches/100-musl-compat.patch

lualanes: fix musl compatibility

---

utils/crelay/Makefile
utils/crelay/files/crelay.init
utils/crelay/patches/010-link_with_ftdi1.patch

@ondrej1024, @commodo -- Any changes or additions? OK to merge?
Closes #1569
Additional discussion here: https://github.com/ondrej1024/crelay/issues/3

crelay: import usb relay control daemon

---

lang/python-setuptools/Makefile

python-setuptools: add myself as maintainer

---

lang/python-pip/Makefile

python-pip: add myself as maintainer

---

libs/protobuf/Makefile

Signed-off-by: Jacob Siverskog <jacob@teenageengineering.com>

protobuf: add myself as maintainer.

---

net/reaver/Makefile
net/reaver/patches/0001-wpscrack-big-endian-fixes.patch
net/reaver/patches/0002-Use-the-current-directory-for-storing-and-loading-se.patch
net/reaver/patches/0003-wash-wpsmon-use-less-useless-spaces-in-output-to-fit.patch
net/reaver/patches/0100-Include-sys-types.h-for-definition-of-u_char.patch

This can be merged after its removal from oldpackages repository.
- Update copyright year.
- Add PKG_LICENSE:=GPL-2.0 from the Google Code project page.
- Add autoreconf as the PKG_FIXUP method.
- Add myself as the package maintainer.
- Add a patch to fix building with musl-libc.

reaver: import from oldpackages.

---

lang/python-pip/Makefile

python-pip: upgrade to version 7.1.2

---

lang/python-setuptools/Makefile

python-setuptools: upgrade to version 18.2

---

utils/gammu/Makefile

---
Makefile |   14 +++++++++++---
1 file changed, 11 insertions(+), 3 deletions(-)

gammu: bump to mainstream v 1.36.4, full-language version build fix

---

lang/python-egenix-mx-base/Makefile
lang/python-psycopg2/Makefile

I've added the updated versions of python modules from the upstream, that was recently deleted from the development branch.
This is my first contribution there, so I'm not sure that everything was done right. So please notify me about all misconceptions.

python-psycopg2, python-egenix-mx-base: added new versions of packages

---

libs/libstrophe/Makefile

Signed-off-by: Chih-Wei Chen <changeway@gmail.com>

libstrophe : Update to version 0.8.8

---

net/strongswan/Makefile

Signed-off-by: Dirk Feytons <dirk.feytons@gmail.com>

strongswan: add a couple more plugins

---

lang/micropython-lib/Makefile
lang/micropython/Makefile

Current package is fairly outdated (and wasn't particularly stable).
Signed-off-by: Roger D <rogerdammit@gmail.com>

micropython: update to latest (15.05)

---

lang/vala/Makefile

Upgrades vala to version 0.29.3.

vala: upgrade to 0.29.3

---

kernel/exfat-nofuse/Makefile

exfat: Update for Kernel version 4.1+

---

utils/gammu/Makefile

gammu: bump to supstream v1.36.5

---

net/knot/Makefile

Please consider upgrading also the 15.05 branch.
Signed-off-by: Daniel Salzman <daniel.salzman@nic.cz>

knot: update to 1.6.5

---

net/atftp/Makefile
net/atftp/patches/01-missing-u_char-type-patch.patch

TODO:
- add init script for atftpd
- merge '120-retry-option.patch' from old atftp packages.
Signed-off-by: Daniel Danzberger <daniel@dd-wrt.com>

atftp: add new package

---

lang/python-setuptools/Makefile

python-setuptools: upgrade to version 18.3.1

---

utils/joe/Makefile

---
Makefile |   11 ++++-------
1 file changed, 4 insertions(+), 7 deletions(-)

joe: bump to upstream v4.1

---

net/krb5/Makefile

krb5: update to 1.13.2

---

net/scapy/Makefile

scapy: add new package

---

net/aircrack-ng/Makefile

aircrack-ng: use libnl-genl

---

multimedia/grilo-plugins/Makefile

grilo-plugins: add new package

---

multimedia/grilo/Makefile

grilo: add new package

---

sound/shairport-sync/Makefile
sound/shairport-sync/files/shairport-sync.config
sound/shairport-sync/files/shairport-sync.init

- update to latest (2.4.1) version
- add support for config files
- switch uci to config files
Based on: https://github.com/openwrt/packages/pull/1815
Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>

shairport-sync: update to latest version

---

utils/smstools3/Makefile

smstools3: fix CFLAGS and LFLAGS

---

net/chaosvpn/Makefile
net/chaosvpn/files/chaosvpn.hotplug
net/chaosvpn/files/chaosvpn.init

Hello this is a pull request to readd chaosvpn because I missed it since the last update.
I'm not sure that depend on `ip` is right because the also other packages ip-*
This is my first package for openwrt so please check it.
Signed-off-by: Norbert Summer <git@o-g.at>

chaosvpn: add new package

---

utils/less/Makefile

Signed-off-by: Julen Landa Alustiza <julen@zokormazo.info>

less: update to 481

---

utils/gammu/Makefile

gammu: bump to new upstream v1.36.6

---

net/mwan3/Makefile
net/mwan3/files/etc/hotplug.d/iface/15-mwan3
net/mwan3/files/usr/sbin/mwan3

Fix for changed location ip binary
Signed-off-by: Jeroen Louwes <jeroen.louwes@gmail.com>

mwan3: update to version 1.6-3

---

multimedia/lcdgrilo/Makefile
multimedia/lcdgrilo/files/lcdgrilo.init

lcdgrilo: add new package

---

libs/libgee/Makefile
libs/libgee/patches/libgee-0.18.0-no-introspection.patch

libgee: add new package

---

net/keepalived/Makefile

keepalived: update to use only libnl-genl

---

libs/libsodium/Makefile

libs/libsodium: update to 1.0.4

---

net/mwan3-luci/Makefile
net/mwan3-luci/files/usr/lib/lua/luci/controller/mwan3.lua
net/mwan3-luci/files/usr/lib/lua/luci/view/mwan/openwrt_overview_status.htm
net/mwan3-luci/files/usr/lib/lua/luci/view/mwan/overview_interface.htm

Hard-coded location of ip (/usr/bin/ip) in controller file
Added space after "for" in .htm files to clean it up
signed-off-by: Aedan "ARFETT" Renner <chipdankly@gmail.com>

mwan3-luci updated to 1.4-4

---

libs/libsodium/Makefile

libs/libsodium: update to 1.0.5

---

sound/shairport-sync/Makefile

shairport-sync: Add "mini" package (no soxr, no avahi, use polarssl)

---

libs/boost/Makefile

Proposed fix for issue #1912. @ClaymorePT - please review

boost: Add ignore-site-config option to bjam

---

utils/attr/Makefile
utils/attr/patches/100-no-gettext_configure.patch

attr: update to 20150922

---

utils/acl/Makefile
utils/acl/patches/100-no-gettext_configure.patch

acl: update to 20150921

---

utils/tmux/Makefile
utils/tmux/patches/100-b64_ntop-conflict.patch

tmux: update to 2.1

---

libs/libsodium/Makefile

libs/libsodium: update to 1.0.6

---

lang/python-setuptools/Makefile

python-setuptools: upgrade to version 18.5

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

fix for possible query log config change (enabled => disabled)
Please apply to upstream - thank you!

adblock: additional check for running dns query background task

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

fix more corner cases because of mksh to ash migration
fix logical glitch during startup
Now, please apply to upstream - thanks for your patience! 

adblock: fix redirection issues

---

utils/at/Makefile
utils/at/files/atd.init
utils/at/patches/100-remove-glibc-assumption.patch
utils/at/patches/110-getloadavg.patch

* import from oldpackages
* version bump, update hash
* add PKG_LICENSE and PKG_LICENSE_FILES
* update patches
Signed-off-by: Phil Eichinger <phil@zankapfel.net>

at: bring back package

---

utils/at/Makefile
utils/at/files/atd.init

Signed-off-by: Phil Eichinger <phil@zankapfel.net>

at: update init script to use procd

---

lang/python-six/Makefile

From the README:
Six is a Python 2 and 3 compatibility library.  It provides utility functions
for smoothing over the differences between the Python versions with the goal of
writing Python code that is compatible on both Python versions.  See the
documentation for more information on what is provided.

python-six: new package

---

lang/python-ply/Makefile

From the README:
PLY is a 100% Python implementation of the common parsing tools lex
and yacc.

python-ply: new package

---

net/coova-chilli/patches/400-fix-compile-with-musl.patch

coova-chilli: fix compile error with musl

---

multimedia/mjpg-streamer/Makefile
multimedia/mjpg-streamer/patches/060-fix-sigtrap-in-v4l2uvc.patch

Should fix problem reported in #1957 

mjpg-streamer: Fix SIGTRAP in v4l2uvc

---

utils/stress/Makefile

stress: bring it back (from old packages)

---

utils/collectd/Makefile

Previously part of #1801 which has been partly resolved but not completely...

collectd: enable nut plugin

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* fix download parms
* fix tmp vars
* other small fixes

adblock: bugfix release

---

libs/libgee/Makefile

libgee: install Vala-related files

---

utils/joe/files/joerc

---
joerc |    7 -------
1 file changed, 7 deletions(-)

joe: fix key bindings

---

mail/mutt/Makefile
mail/mutt/patches/0001-no-po-and-docs.patch

* import from oldpackagesg
* bump version and update hash
* update patch to new version
* add PKG_LICENSE, PKG_LICENSE_FILES, PKG_MAINTAINER

mutt: bring back from oldpackages

---

utils/dosfstools/Makefile
utils/dosfstools/patches/010-consistent_use_of_uint32.patch

dosfstools: [for-15.05] bump to 3.0.28, fix URLs - dev moved to github

---

utils/gammu/Makefile

gammu: bump to upstream 1.36.7

---

lang/python-setuptools/Makefile

Does not affect nor does fix https://github.com/openwrt/packages/issues/1945
This fixes https://github.com/openwrt/packages/pull/2061 handles issue #1945 

python-setuptools: upgrade to version 18.7

---

lang/python-ply/Makefile

This depends on python-setuptools host install in PR #1985

python-ply: add host compile/install

---

lang/python-enum34/Makefile
lang/python-enum34/patches/001-omit-docs.patch

python-enum34: update to 1.1.1, omit docs and tests from package

---

lang/python-psycopg2/Makefile

Fixes https://github.com/openwrt/packages/issues/1945

python-psycopg2: fix build

---

net/davfs2/Makefile

davfs2: simplified dependencies and added support for LFS

---

lang/python/files/python-host.mk
lang/python/files/python-package.mk

Last one.
Let's see what buildbot finds and if any users (or other packages) get affected.

python: fix HostPython host/target selection

---

lang/python/files/python-host.mk

Tested on python-setuptools.
Fixes https://github.com/openwrt/packages/issues/2113

python: fix HostPython again

---

lang/python/files/python-host.mk

I call this the curse of the End-Of-The-Year for me.

python2: fix typo in HostPython function

---

utils/gammu/Makefile

gammu: bump to new upstream 1.36.8

---

net/unbound/Makefile
net/unbound/patches/001-conf.patch

Bump unbound to version 1.5.7 released on December 10, 2015.

[Unbound] Update to 1.5.7

---

libs/libsodium/Makefile

libs/libsodium: update to 1.0.7

---

net/rsyslog/Makefile

Signed-off-by: Dov Murik <dmurik@us.ibm.com>
Tested on realview.

net/rsyslog: update to 8.15.0

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.conf
net/adblock/files/samples/adblock.conf.sample

* add whocares.org as additional source
* add adblock statistics (requires query log)
* cosmetics

adblock: small changes

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* fix cornercase during domain query removal
I would like to wish you all a merry Christmas & a very happy new year! ;-)

adblock: bugfix

---

lang/php5/Makefile
lang/php5/files/php.ini
lang/php5/patches/102-debian_patches_use_embedded_timezonedb.patch
lang/php5/patches/200-ext-opcache-fix-detection-of-shm-mmap.patch
lang/php5/patches/950-Fix-dl-cross-compiling-issue.patch
lang/php5/pecl.mk

This brings the version of PHP5 in for-15.05 up to the version found in master. This fixes a number of CVEs.

Cherry pick PHP5 updates into for-15.05.

---

lang/python-enum34/Makefile

python-enum34: update to latest version

---

lang/python-cffi/Makefile

python-cffi: update to latest version

---

multimedia/ffmpeg/Makefile

Also make use of the now available xz packaging.

ffmpeg: update to 2.7.4

---

utils/evtest/Makefile

Signed-off-by: Pushpal Sidhu <psidhu@gateworks.com>

evtest: add package

---

multimedia/grilo-plugins/Makefile

grilo-plugins: update to 0.3.0

---

net/scapy/Makefile

scapy: update to 2.3.1

---

net/lighttpd/Makefile

lighttpd: update to 1.4.38

---

lang/luasec/Makefile

luasec: update to 0.5.1

---

libs/libsoup/Makefile

libsoup: update to 2.53.2

---

libs/openldap/Makefile

openldap: update to 2.4.43

---

net/knxd/Makefile

knxd: bump new version

---

multimedia/gst1-libav/Makefile

gst1-libav: update to 1.6.2

---

utils/sane-backends/Makefile

sane-backends: minor Makefile text typo

---

libs/libsodium/Makefile

libs/libsodium: update to 1.0.8

---

net/openvswitch/Makefile

Still more work to be done, but this reduces about 400k from the installed package.

openvswitch: reduce some package bloat

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/update_CloudFlare.sh

This is a backport of #2252 for CC.

ddns-scripts: allow setting CloudFlare 'rec_id' in the config

---

net/mdnsresponder/Makefile
net/mdnsresponder/patches/114-fix_posix_build.patch

Signed-off-by: Jacob Siverskog <jacob@teenage.engineering>

mdnsresponder: bump to 576.30.4.

---

lang/python-setuptools/Makefile
lang/python-setuptools/patches/0001-remove-windows-support.patch

python-setuptools: upgrade to version 19.4

---

lang/python3-setuptools/Makefile
lang/python3-setuptools/patches/0001-remove-windows-support.patch

python3-setuptools: upgrade to version 19.4

---

utils/bonnie++/Makefile
utils/bonnie++/patches/001-cross_compile_fix.patch
utils/bonnie++/patches/002-add-verbose-error-messages.patch

Import bonnie++ from oldpackages:
* update to 1.97
* add license tags
* add myself as maintainer
Signed-off-by: Florian Fainelli <florian@openwrt.org>

utils: Import bonnie++

---

net/rsyslog/Makefile

Compiled the new package successfully for Raspberry Pi target

net/rsyslog: update to 8.16.0

---

net/radicale/Makefile
net/radicale/files/radicale.init
net/radicale/files/radicale.upgrade

* upstream to Radicale 1.1.1
* add file list to be saved on sysupgrade

Radicale: bump to version 1.1.1

---

utils/gammu/Makefile

gammu: bump to upstream v1.37.0

---

libs/protobuf-c/Makefile

Signed-off-by: Jacob Siverskog <jacob@teenage.engineering>

protobuf-c: Bump version to 1.2.1.

---

utils/grep/Makefile

Signed-off-by: Julen Landa Alustiza <julen@zokormazo.info>

grep: update to 2.23

---

lang/python-cryptography/Makefile

python-cryptography: update to latest version

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.conf
net/adblock/files/adblock.init
net/adblock/files/www/adblock/adblock.html
net/adblock/files/www/adblock/index.html

* fix root cause for https timeout issues
* fix startup issues via luci
* detach init start process to fix luci timeout issues
* fix html header in adblock pages
* fix adblock.conf options to single quotes

adblock: 0.70.1

---

net/snort/Config.in
net/snort/Makefile

Fixes https://github.com/openwrt/packages/issues/2160

snort: remove useless mysql/pgsql options

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* fix wan update detection failure

adblock: 0.70.2

---

mail/postfix/Makefile

postfix: version update to 3.0.4

---

utils/nano/Makefile

Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>

Updates to 2.5.3 and updates copyright year.

---

libs/libesmtp/Makefile

libesmtp: add ssl support, new upstream URL

---

lang/python-cffi/Makefile
lang/python-ply/Makefile
lang/python-pycparser/Makefile
lang/python-setuptools/Makefile
lang/python/Makefile
lang/python/files/python-host.mk
lang/python/files/python-package.mk

This changes the prefix for host Python to address the issue raised in https://github.com/openwrt/packages/pull/2360#issuecomment-192148541

Host python changes

---

net/shadowsocks-client/Makefile

I forgot this in last pull request. Please merge this, thanks.

shadowsocks-client: change git repository url

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/dynamic_dns_updater.sh

ddns-scripts: fix comparing IPv6 addresses

---

devel/pkg-config/Makefile

The changes in 0.29.1 center on the treatment of --variable
and --define_variable.
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

pkg-config: update to 0.29.1

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.conf
net/adblock/files/adblock.init

* add sysctl.org as new adblock source
* add main debug switch (by default all stderr outputs are going to /dev/null)
* small cleanups
* first 'stable' release! ;-)

adblock: release 1.0.0

---

lang/python-setuptools/Makefile

python-setuptools: upgrade to version 20.2.2

---

lang/python-pip/Makefile

python-pip: upgrade to version 8.1.0

---

lang/python3-setuptools/Makefile

python3-setuptools: upgrade to version 20.2.2

---

lang/python3-pip/Makefile

python3-pip: upgrade to version 8.1.0

---

sound/shairport-sync/Makefile

Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>

shairport-sync: update to v2.8.1

---

lang/python/files/python-host.mk

python: add rpath for host Python extension modules

---

net/unbound/Makefile

Bump unbound to version 1.5.8 released on March 2, 2016.

[Unbound] Update to 1.5.8

---

net/openvswitch/Makefile
net/openvswitch/patches/0010-lib-ovs-thread-Ensure-that-thread-stacks-are-always-.patch
net/openvswitch/patches/0011-kernel-4-4-support.patch

openvswitch: add support for kernel 4.4

---

lang/python-cryptography/Makefile

python-cryptography: update to 1.3.1

---

lang/python-cffi/Makefile

python-cffi: update to 1.5.2

---

lang/python-idna/Makefile

python-idna: update to 2.1

---

lang/python-ipaddress/Makefile

python-ipaddress: update to 1.0.16

---

lang/python-pyptlib/Makefile

From the setup description:
A python implementation of the Pluggable Transports for Circumvention
specification for Tor

python-pyptlib: new package

---

lang/python-pyasn1-modules/Makefile

From the README:
This is a small but growing collection of ASN.1 data structures
expressed in Python terms using pyasn1 data model.

python-pyasn1-modules: new package

---

lang/python-parsley/Makefile
lang/python-parsley/patches/001-omit-tests.patch

From the setup description:
Parsing and pattern matching made easy.

python-parsley: new package

---

utils/lxc/Makefile

Signed-off-by: Daniel Dickinson <openwrt@daniel.thecshore.com>

utils/lxc: lxc-create templates depend on flock

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* optimize list sort
* simplified block list removal

adblock: update 1.0.1

---

utils/bandwidthd/Makefile
utils/cmdpad/Makefile
utils/crelay/Makefile
utils/gammu/files/gammu.init
utils/openocd/Makefile
utils/opensc/patches/0024-OpenPGP-Fix-crash-after-accessing-inexistent-file.patch
utils/pps-tools/Makefile
utils/smstools3/files/smstools3.init
utils/watchcat/Makefile

utils: Fix typos (found by codespell)

---

net/adblock/Makefile
net/adblock/files/adblock-update.sh

* fix corner case during shallalist backup/restore

adblock: update 1.0.2

---

admin/zabbix/files/mac80211
admin/zabbix/files/network
admin/zabbix/files/wifi
admin/zabbix/patches/015-daemon-foreground.patch

admin/zabbix: Fix typos (found by codespell)

---

utils/pciutils/Makefile

Fixes #2471 without adding unneeded dependency.

pciutils: remove eudev dependency

---

net/krb5/Makefile
net/krb5/patches/001-fix-uninitialized-warning-errors.patch

krb5: update to 1.14.1

---

net/isc-dhcp/Makefile
net/isc-dhcp/files/dhclient-script
net/isc-dhcp/files/dhclient.init
net/isc-dhcp/files/dhclient6.conf
net/isc-dhcp/files/dhclient6.init
net/isc-dhcp/files/dhcpd.conf
net/isc-dhcp/files/dhcpd.init
net/isc-dhcp/files/dhcpd6.conf
net/isc-dhcp/files/dhcpd6.init
net/isc-dhcp/files/dhcrelay4.init
net/isc-dhcp/files/dhcrelay6.init
net/isc-dhcp/files/etc/config/dhcrelay
net/isc-dhcp/patches/000-compile.patch
net/isc-dhcp/patches/100-relay-rfc3527-link-selection.patch
net/isc-dhcp/patches/510-bind-CC.patch

Signed-off-by: Antony Antony <antony@phenome.org>

isc-dhcp: update to 4.3.3 and migrate from oldplackages

---

lang/node-arduino-firmata/Makefile
lang/node-cylon/Makefile
lang/node-hid/Makefile
lang/node-serialport/Makefile

FIX : Error: EACCES, mkdir '/root/.npm/serialport/1.4.6/package'
#2513

node-* : specify npm_config_cache directory

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* remove syntax glitch & cosmetics
* probably the last 1.0.x release

adblock: update 1.0.3

---

net/coova-chilli/files/chilli.config

coova-chilli: add network option in chilli.config

---

multimedia/tvheadend/Makefile

Update to latest minor revision.

tvheadend: update to 4.0.9

---

net/davfs2/Makefile
net/davfs2/patches/010-main_code_fix.patch
net/lftp/Makefile

lftp: updated to 4.7.1, davfs2: updated to 1.5.3 and reintroduced support for libssp

---

libs/boost/Makefile
libs/db47/patches/030-patch.4.7.25.3.patch
libs/faad2/Makefile
libs/libmraa/patches/0002-add-mips-support.patch
libs/libtorrent/Makefile
libs/libxslt/Makefile
libs/vips/patches/001-no_cpp.patch

libs: Fix typos (found by codespell)

---

multimedia/youtube-dl/Makefile

Create youtube-dl package

---

lang/python3/Makefile
lang/python3/files/python3-package-asyncio.mk
lang/python3/files/python3-package-codecs.mk
lang/python3/files/python3-package-ctypes.mk
lang/python3/files/python3-package-dbm.mk
lang/python3/files/python3-package-decimal.mk
lang/python3/files/python3-package-dev.mk
lang/python3/files/python3-package-distutils.mk
lang/python3/files/python3-package-email.mk
lang/python3/files/python3-package-gdbm.mk
lang/python3/files/python3-package-lib2to3.mk
lang/python3/files/python3-package-logging.mk
lang/python3/files/python3-package-lzma.mk
lang/python3/files/python3-package-multiprocessing.mk
lang/python3/files/python3-package-ncurses.mk
lang/python3/files/python3-package-openssl.mk
lang/python3/files/python3-package-pydoc.mk
lang/python3/files/python3-package-sqlite3.mk
lang/python3/files/python3-package-unittest.mk
lang/python3/files/python3-package-xml.mk
lang/python3/files/python3-package.mk

python3: upgrade to version 3.5.1

---

lang/python3-setuptools/Makefile

python3-setuptools upgrade to version 20.7.0

---

lang/python3/Makefile

I ommitted 1 element when pushing the first time.

python3: change $(STAGING_DIR)/host to $(STAGING_DIR_HOST)

---

lang/python3-pip/Makefile

python3-pip: bump to version 8.1.1

---

net/transmission/Makefile

Signed-off-by: Cezary Jackiewicz <cezary@eko.one.pl>

transmission: split packages depending on selected cryptography library

---

libs/libmicrohttpd/Makefile

libmicrohttpd: update to 0.9.49

---

sound/shairport-sync/Makefile
sound/shairport-sync/files/shairport-sync.config
sound/shairport-sync/files/shairport-sync.init

Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>

shairport-sync: update to 2.8.2

---

libs/libsodium/Makefile

libs/libsodium: update to 1.0.10

---

utils/gammu/Makefile

gammu: bump to upstream v 1.37.2

---

libs/libvpx/Makefile

Also inc gst1-plugins-good and toxcore release in order
to avoid package upgrade problems.
Is it ok @MikePetullo and @dangowrt?

libvpx: update to 1.5.0

---

net/davfs2/Makefile

davfs2: updated to 1.5.4

---

multimedia/youtube-dl/Makefile

install certificates so that https sites work by default

youtube-dl: update dependencies

---

net/ncp/Makefile

I am really unsure which license I should specify.
Quote from the source code:
> This is free software; copy and use it as you like.  No warranty.
So I just put in "FREE" there but I guess that's not what you guys expect ;)

add package for ncp (https://www.fefe.de/ncp)

---

libs/libx264/Makefile

libx264: create package

---

utils/hfsprogs/patches/0003-Add-helper-include-files-absent-from-the-upstream-pa.patch
utils/owfs/Makefile

Note that this implies a potential API change for watchcat.

utils: Fix some typos (mostly found by codespell)

---

lang/ruby/Makefile

ruby: updated to 2.3.1

---

net/nut/Makefile

Closes #2652
Signed-off-by: Martin Rowe <martin.p.rowe@gmail.com>

net/nut: Remove whitespace before conffiles

---

libs/libmicrohttpd/Makefile

Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

libmicrohttpd: take over maintainership

---

sound/forked-daapd/Makefile

forked-daapd: Update to version 24.1

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* remove hardcoded paths for system tools like iptables, uci & fetch (wget)
* support openwrt & lede spin-off
* cosmetics & cleanups

adblock: update 1.1.2

---

net/rsyslog/Makefile

Signed-off-by: Dov Murik <dmurik@us.ibm.com>
Built successfully on ARM Realview.

net/rsyslog: update to 8.18.0

---

libs/poco/Makefile

Update package to latest stable version (1.7.3)
Signed-off-by: Jean-Michel Julien <jean-michel.julien@trilliantinc.com>

poco: update to 1.7.3

---

mail/ssmtp/Makefile

* change maintainer email address
* switch to sha256sum fingerprint
* cosmetics

ssmtp: refresh package makefile

---

utils/mc/Makefile

* revert latest gettext change, break builds on various platforms
* changed maintainer email address

mc: bugfix 4.8.17

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* automatic AP mode detection (change nullip address accordingly)
* (de-)compress backups on the fly
* remove hardcoded path for logger
* change maintainer email address
* cosmetics

adblock: update 1.1.10

---

multimedia/icecast/Makefile

Signed-off-by: André Gaul <gaul@gaul.io>

icecast: update to 2.4.3

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.conf

* fix changed winspy source url in default config
* fix adblock counters in config
* cosmetics

adblock: update 1.1.11

---

net/xl2tpd/files/l2tp.sh

Signed-off-by: mogulapranay <mogulapranay57@gmail.com> <mogula.pranay@nxp.com>

xl2tpd: demand option is initialized.

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.conf

* change wget binary naming
* change winspy source url

adblock: update 1.1.12

---

libs/confuse/Makefile

Remove hardcoded URL and use alias instead.

confuse: Use URL alias

---

devel/gcc/Makefile

Remove hardcoded URL and use alias instead.

gcc: Use URL alias

---

utils/smartmontools/Makefile

smartmontools: update to 6.5

---

net/tgt/Makefile
net/tgt/patches/020-usr_Makefile.patch

tgt: update to 1.0.64

---

utils/gammu/Makefile

gammu: bump to upstream v1.37.3

---

net/yaaw/Makefile

Yet Another Aria2 Web Frontend in pure HTML/CSS/Javascirpt.

yaaw: Add package

---

net/webui-aria2/Makefile

webui-aria2: Add package

---

multimedia/crtmpserver/Makefile
multimedia/crtmpserver/patches/010-link-crypt-for-lua.patch
multimedia/crtmpserver/patches/030-default-config.patch
multimedia/crtmpserver/patches/040-use-select.patch
multimedia/crtmpserver/patches/050-add-missing-make-defines.patch
multimedia/crtmpserver/patches/060-add-missing-includes.patch
multimedia/crtmpserver/patches/070-missing-include-gcc-47.patch

- Switch download to the Github clone of crtmpserver
- Rebase patches against latest version
- Pregenerate version.h file
- Disable applestreamingclient as it is broken
Signed-off-by: Jo-Philipp Wich <jo@mein.io>

crtmpserver: fix multiple issues

---

libs/libupnpp/Makefile
sound/upmpdcli/Makefile
sound/upmpdcli/patches/010-Add_icon_config.patch

upmpdcli: Version 1.1.3
libupnpp: Version 0.14
@ignisf - OK?

upmpdcli/libupnpp: Update to latest versions, refresh patch

---

net/aria2/Config.in
net/aria2/Makefile
net/aria2/files/aria2.conf
net/aria2/files/aria2.init

aria2: update to 1.23.0

---

sound/shairport-sync/Makefile
sound/shairport-sync/files/shairport-sync.config
sound/shairport-sync/files/shairport-sync.init

Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>

shairport-sync-next: update to v2.8.4

---

net/aria2/Config.in
net/aria2/Makefile

aria2: Add SFTP support choice

---

net/adblock/Makefile
net/adblock/files/adblock.init

* workaround for LuCI search path issue

adblock: update 1.1.16, release 2

---

utils/lrzsz/Makefile
utils/lrzsz/patches/100-install_delete_fix.patch

Import lrzsz from oldpackages

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.conf
net/adblock/files/adblock.init

* change winspy url again
* various cosmetics left out in former release

adblock: update 1.1.17

---

lang/python-pip/Makefile

python-pip: upgrade to version 8.1.2

---

lang/python-setuptools/Makefile

python-setuptools: upgrade to version 22.0.5

---

net/znc/Makefile

Signed-off-by: Graham Fairweather <xotic750@gmail.com>

znc: Bump to v1.6.3

---

net/znc/files/znc.init

Signed-off-by: Graham Fairweather <xotic750@gmail.com>

znc: Added RUNAS_SHELL variable to assist when using external configuration

---

libs/libssh2/Makefile

libssh2: Bump to v1.7.0

---

net/fwknop/Makefile

Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>

Fwknop: Updates to 2.6.9

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/dynamic_dns_lucihelper.sh
net/ddns-scripts/files/dynamic_dns_updater.sh

Improve the code as suggested by Christian Schoenebeck.
Signed-off-by: Mathias Kresin <dev@kresin.me>

ddns-scripts: initialise the is_glue variable

---

multimedia/grilo-plugins/Makefile

grilo-plugins: update to 0.3.1

---

libs/libsoup/Makefile

libsoup: update to 2.54.1

---

multimedia/lcdgrilo/Makefile

lcdgrilo: update to 0.0.8

---

net/transmission/Makefile

transmission: fix transmission-web dependencies

---

devel/make/Makefile

The release contains a bunch of bug fixes.
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

devel/make: GNU Make 4.2.1

---

net/wget/Makefile

wget: update to 1.18

---

utils/attr/Makefile
utils/attr/patches/100-no-gettext_configure.patch

attr: update to 20160302

---

utils/acl/Makefile
utils/acl/patches/100-no-gettext_configure.patch

acl: update to 20160519

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.init

* small optimizations & cosmetics

adblock: update 1.2.1

---

utils/luci-app-lxc/Makefile
utils/luci-app-lxc/files/controller/lxc.lua
utils/luci-app-lxc/files/view/lxc.htm

Mainly making LuCI LXC app download list of available containers to install. Currently it is kinda ugly but it works. Maybe I'll polish it a little bit later. But my polishing would be just nicer javascript handling more conditions, I'm not going to rewrite it to use rpc.

Little improvement to LXC LuCI app

---

net/znc/Config.in
net/znc/Makefile

Signed-off-by: Graham Fairweather <xotic750@gmail.com>

znc: Added support for ICU through menu configuration

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.init

* restructured sources
* fix logical glitches in config handling
* many corner case fixes & cosmetics
* show runtime errors in LuCI (in lastrun section)

adblock: update 1.2.5

---

net/aria2/Makefile

aria2: update to v1.24.0

---

libs/elektra/Makefile

Notable changes:
Remove the work around introduced for 0.8.16 - the issue has been fixed
upstream.
Signed-off-by: Harald Geyer <harald@ccbib.org>

elektra: Update to 0.8.17

---

net/nginx/Makefile

Signed-off-by: Graham Fairweather <xotic750@gmail.com>

nginx: Bumped nginx-naxsi to v0.54

---

net/aria2/Makefile

aria2: fix md5sum

---

net/adblock/Makefile
net/adblock/files/adblock-update.sh

* small addition in case of a failed list download

adbock: update 1.2.6

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.init

* provide adblock statistics as a separate function
(/etc/init.d/adblock stats)

adblock: update 1.2.7

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_lucihelper.sh
net/ddns-scripts/files/tld_names.dat

- fix misuse of "local" outside functions #2885
- update TLD_names.dat

ddns-scripts: fix misuse of "local"

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.hotplug

* revised hotplug script
* remove wget package dependency
* support uclient-fetch or wget with ssl support

adblock: release 1.3.0

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* fix uclient-fetch detection
* cosmetics

adblock: update 1.3.1

---

net/aircrack-ng/Makefile

airmon-ng: Fix procps-ng dependancy.

---

lang/python/Makefile
lang/python/files/python-package.mk

Thanks to @ryzhovau for reporting.

python: do not allow packaging of windows exe files

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* only a few more fixes
Euro 16: germany vs. italy 6:5 (after 18 penalties!)  :relieved:

adblock: update 1.3.2

---

net/wireguard/Makefile

Signed-off-by: Baptiste Jonglez <git@bitsofnetworks.org>

wireguard: Initial upload

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-update.sh

* enable automatic restore on empty source downloads

adblock: update 1.3.3

---

utils/relayctl/Makefile

The license is BSD-3-Clause.
Indicate license file.
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

relayctl: update license information

---

lang/python-psycopg2/Makefile

Please double check that your commits:
- all start with "<package name>: "
- all contain signed-off-by
- are linked to your github account (you see your logo in front of them) 
Please also read https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md
Thanks for your contribution
Please remove this text (before ---) and fill the following template
Maintainer: me / @<github-user>
Compile tested: (put here arch, model, OpenWRT/LEDE version)
Run tested: (put here arch, model, OpenWRT/LEDE version, tests done)
Description:

python-psycopg2: update to 2.6.2

---

net/softflowd/Makefile
net/softflowd/files/softflowd.init

Maintainer: @rvandegrift
Run tested: chaos_calmer 1.3.2 @ TP-LINK TL-WR1043ND v2
Description: update softflowd.init do use procd
Signed-off-by: Jan Tomášek <jan@tomasek.cz>

softflowd: update softflowd.init do use procd

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* rework/speed up overall sort
* simplified dns error handling

adblock: release 1.4.0

---

net/strongswan/Makefile
net/strongswan/patches/101-musl-fixes.patch
net/strongswan/patches/210-sleep.patch
net/strongswan/patches/305-minimal_dh_plugin.patch

Maintainer: @sbyx 
Compile tested: octeon on LEDE r1005
Run tested: octeon on LEDE r1005

strongswan: bump to 5.5.0

---

net/aria2/Makefile
net/aria2/files/aria2.init

* update init file from @hostkit
* update to latest version

Aria2 Update

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh

* fix two possible overflows in adblock statistics

adblock: update 1.4.1

---

net/mwan3/files/usr/sbin/mwan3
net/mwan3/files/usr/sbin/mwan3track

Maintainer: @Adze1502
Run tested: xrx200, LEDE
Description:
fix mwan3 whitespace typos
Signed-off-by: Florian Eckert Eckert.Florian@googlemail.com

Fix mwan3 whitespace typos

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.conf

* ad broad blocklist source 'hphosts' https://hosts-file.net

adblock: update 1.4.2

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.init

Maintainer: me
Run tested: x86_64, LEDE R1185
Description:
* fix race condition in restricted mode
* cosmetics

adblock: update 1.4.3

---

net/vpnc/README

Maintainer: me / @danielg4
Compile tested: N/A; documentation patch only
Run tested: N/A; documentation patch only
Description: Addressed issue #2908
Signed-off-by: Daniel Gimpelevich <daniel@gimpelevich.san-francisco.ca.us>

vpnc: Add reboot recommendation to README

---

multimedia/gst1-libav/Makefile
multimedia/gst1-plugins-bad/Makefile
multimedia/gst1-plugins-bad/patches/001-no-translations.patch
multimedia/gst1-plugins-bad/patches/002-no-tests.patch
multimedia/gst1-plugins-base/Makefile
multimedia/gst1-plugins-base/patches/001-no-translations.patch
multimedia/gst1-plugins-base/patches/002-no-tests.patch
multimedia/gst1-plugins-base/patches/003-no-docs.patch
multimedia/gst1-plugins-good/Makefile
multimedia/gst1-plugins-good/patches/001-no-translations.patch
multimedia/gst1-plugins-good/patches/002-no-tests.patch
multimedia/gst1-plugins-good/patches/003-no-docs.patch
multimedia/gst1-plugins-ugly/Makefile
multimedia/gst1-plugins-ugly/patches/002-no-tests.patch
multimedia/gst1-plugins-ugly/patches/003-no-docs.patch
multimedia/gstreamer1/Makefile
multimedia/gstreamer1/patches/001-no-translations.patch
multimedia/gstreamer1/patches/002-no-tests.patch
multimedia/gstreamer1/patches/003-no-docs.patch
multimedia/gstreamer1/patches/010-gstplugin-use-lazy-symbol-binding.patch

Maintainer: thess / @thess, @MikePetullo 
Compile tested: mips, arm, neon-vfp
Run tested: 
Description:
Refresh patches, fix dependencies.
Fix cpu build issues in gst-libav. Opus moved to plugins-base.
Add opusparse and hls to plugins-bad.
Add myself as co-maintainer
@MikePetullo - OK with you to merge this?

gstreamer - Upgrade to 1.8.2.

---

lang/twisted/Makefile
lang/twisted/patches/001-fix-zsh-completion.patch
lang/twisted/patches/002-omit-tests.patch

Maintainer: me
Compile tested: ar71xx, TP-Link TL-MR3020, OpenWRT CC / OpenWrt trunk / LEDE trunk
Run tested: none :joy:
Description:
update to 16.3.0

twisted: update to 16.3.0

---

lang/python-enum34/Makefile
lang/python-enum34/patches/001-omit-docs.patch

Maintainer: me
Compile tested: ar71xx, TP-Link TL-MR3020, OpenWRT CC / OpenWrt trunk / LEDE trunk
Run tested: none :joy:
Description:
update to 1.1.6

python-enum34: update to 1.1.6

---

multimedia/youtube-dl/Makefile

Maintainer: @ianchi
Compile tested: (arm ipq806x, Linksys EA8500, LEDE r1325)
Run tested: (arm ipq806x, Linksys EA8500, LEDE r1325)
Description: update to version 2016 08 13

youtube-dl: update version

---

libs/libx264/Makefile

Maintainer: @ianchi
Compile tested: (arm ipq806x, Linksys EA8500, LEDE r1325)
Run tested: (arm ipq806x, Linksys EA8500, LEDE r1325)
Description: update to version 20160815

libx264: update version

---

net/aria2/Makefile

aria2: update to 1.26.0

---

lang/pillow/Makefile
lang/pillow/patches/010-fix-paths.patch

Maintainer: me
Compile tested: ar71xx, Netgear WNDR4300, openwrt r49917
Run tested: -
Description: Upgrade to version 3.3.1

pillow: upgrade to version 3.3.1

---

lang/luai2c/Makefile

Signed-off-by: Frank Edelhaeuser <mrpace2@gmail.com>
Resubmitting previous PR #3087, now with a signed-off commit. Resolves issue #3040.

luai2c: moved upstream project to github

---

.github/issue_template

So that maintainers can receive at least one notification at the issue
creation time ;)
You can open an issue at my repo (https://github.com/yousong/packages) for a preview.

Add an issue template

---

utils/gammu/Makefile

Maintainer: @aTanW
Compile tested: x64 master
Run tested: ar71xx 15.05.1 NETGEAR WNDR3800
---

gammu: bump to the new upstream v1.37.4

---

lang/django-appconf/Makefile
lang/django-compressor/Makefile
lang/django-constance/Makefile
lang/django-jsonfield/Makefile
lang/django-postoffice/Makefile
lang/django-statici18n/Makefile

Maintainer: me
Compile tested: ar71xx, Netgear WNDR4300, openwrt r49926
Run tested: -
Description: Upgrade various django packages to the latest version

Upgrade django packages

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/services
net/ddns-scripts/files/services_ipv6

Maintainer: me
Compile tested: not needed
Run tested: x86 DD
Description:
- Provider duiadns.net: add IPv6 and correct IPv4 url inside services files #3125
- other fixes inside services files

ddns-scripts: fixes to services files

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock-update.sh
net/adblock/files/adblock.init

Maintainer: me
Run tested: x86_64, LEDE r1577
Description:
* refine query function (see online doc)

adblock: update 1.4.9

---

lang/python3-setuptools/Makefile
lang/python3-setuptools/patches/0001-remove-windows-support.patch

python3-setuptools: upgrade to version 27.1.2

---

lang/python-setuptools/Makefile
lang/python-setuptools/patches/0001-remove-windows-support.patch

python-setuptools: upgrade to version 27.1.2

---

net/aria2/Makefile

aria2: update to 1.27.1

---

lang/python3-setuptools/Makefile

Same URL as this https://github.com/openwrt/packages/pull/3189

python3-setuptools: upgrade to version 27.2.0

---

lang/python-ply/Makefile

Maintainer: me
Compile tested: ar71xx, OpenWrt CC / OpenWrt trunk / LEDE master
Description:

python-ply: update to 3.9

---

lang/twisted/Makefile
lang/twisted/patches/002-omit-tests.patch

Maintainer: me
Compile tested: ar71xx, OpenWrt CC / OpenWrt trunk / LEDE master
Description:

twisted: update to 16.4.1

---

lang/zope-interface/Makefile

Maintainer: me
Compile tested: ar71xx, OpenWrt CC / OpenWrt trunk / LEDE master
Description:

zope-interface: update to 4.3.2

---

utils/evtest/Makefile
utils/gpsd/Makefile

Maintainer: me
Description: Update my maintainer email.

psidhu: Update Maintainer Email

---

libs/libedit/Makefile
net/knot/Makefile
net/knot/files/runtests.sh
net/knot/patches/04_cookies_big_endian.patch

Maintainer: @salzmdan
Compile tested: mpc85xx, OpenWRT 14.07
Run tested: mpc85xx, OpenWRT 14.07
Description:
- Update libedit
- Update Knot DNS

Update libedit and Knot DNS

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/services

Maintainer: me
Run tested: no
Description:
* fix answer of changeip.com (#3292)

ddns-scripts: fix answer of changeip.com

---

net/adblock/Makefile
net/adblock/files/adblock-helper.sh

Maintainer: me
Run tested: yes, LEDE r1270
Description:
* turris omnia compatibility fix (#3340)

adblock: update 1.5.2

---

devel/automake/Makefile

Description:
Switch to xz tarball

automake: switch to xz tarball

---

utils/ttyd/Makefile

Maintainer: me
Compile tested: (ramips, PSG1208, LEDE, r1656)
Run tested: (ramips, PSG1208, LEDE, r1656)
Description:
ttyd: update to 1.1.0
Signed-off-by: Shuanglei Tao <tsl0922@gmail.com>

ttyd: update to 1.1.0

---

net/travelmate/Makefile
net/travelmate/files/README.md
net/travelmate/files/travelmate.conf
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: LEDE, r1270
Description:
* a wlan connection manager for travel router
(see readme.md for details)

travelmate: new package, release 0.2.2

---

utils/ap51-flash/Makefile
utils/ap51-flash/files/ap51-flash.config
utils/ap51-flash/files/ap51-flash.init
utils/ap51-flash/files/ap51-flash.sh

Maintainer: Russell Senior / @RussellSenior
Compile tested: ar71xx, Buffalo WZR-HP-AG300H/WZR-600DHP, LEDE reboot-1824-g594f0e80
Description:
Resurrected from old-packages, updated to a current version and made to build again with some help from @jow- 
Signed-off-by: Russell Senior <russell@personaltelco.net>

utils/ap51-flash: import from old-packages and update

---

libs/libwebsockets/Makefile

Compile tested: OpenWRT trunk on mvebu
Run tested: OpenWRT trunk on mvebu

libwebsockets: add full variant with libuv, plugins, CGI

---

devel/libtool-bin/Makefile

Description:
Switch to xz tarball

libtool-bin: switch to xz tarball

---

net/lighttpd/Makefile

Maintainer: me
Description:
lighttpd: update to 1.4.42

lighttpd: update to 1.4.42

---

utils/hd-idle/Makefile

Maintainer: Lim Guo Wei <limguowei@gmail.com> (there seems to be no github user with this name)
Run tested:  the package shows under Disc submenu
Description:Part of a wider housekeeping effort on the packages repository.
Signed-off-by: Alberto Bursi <alberto.bursi@outlook.it>

hd-idle: capitalized submenu name (disc -> Disc)

---

net/fossil/Makefile

Quite self explained. [Checked](https://github.com/Entware-ng/entware-packages/commit/44db206c383797ba5e755971fcb0889e17d84956) on Entware-ng.
@lperkov

fossil: fix source URL

---

net/transmission/Makefile

Another self-explained PR. [Checked](https://github.com/Entware-ng/entware-packages/commit/93228ef8afd6dbf1c47ba1b7586394d546428867) on Entware-ng.
@mstorchak, @nmav.

transmission: fix source URL

---

net/travelmate/Makefile
net/travelmate/files/README.md
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: LEDE r2114
Description:
* small performance optimization, code cleanup
* change copyright notice in makefile

travelmate: update 0.2.5

---

net/travelmate/Makefile
net/travelmate/files/README.md
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: yes, LEDE r2158
Description:
* fix two potential race conditions in ap/sta handling

travelmate: bugfix 0.2.6

---

net/wireguard/Makefile

Maintainer: @zorun
Description:
fixes issue #3515
Signed-off-by: Dan Luedtke <mail@danrl.com>

wireguard-tools: Add missing directory

---

net/gnunet/Makefile

Compile tested: LEDE HEAD
Run tested: kirkwood
Signed-off-by: Nathaniel Wesley Filardo <nwfilardo@gmail.com>

gnunet: add PKG_CONFIG_DEPENDS for all components

---

net/vncrepeater/Makefile
net/vncrepeater/patches/001-uclibcxx_linking.patch
net/vncrepeater/patches/002-cfg-path.patch

Maintainer: Jimmy / @JimmyS83 / robutek@gmail.com
Compile tested: OpenWRT 15.05.1
Run tested: OpenWRT 15.05.1 / TP-LINK WR741ND
Description:
Port of UltraVNC Repeater for linux by Jari Korhonen. Based on latest 0.17 version.

UltraVNC Repeater

---

net/aggregate/Makefile

Maintainer: me
Description: ipv4 cidr prefix aggregator
Signed-off-by: Nikil Mehta <nikil.mehta@gmail.com>

aggregate: Add package

---

libs/libaudiofile/Makefile

Description: libaudiofile: updated source url (v0.3.6)
Signed-off-by: Marek Sedlak bodka.zavinac@gmail.com

libaudiofile: updated source url (v0.3.6)

---

net/wireguard/Makefile

Maintainer: @zorun 
Update to new snapshot version.

net/wireguard: version bump

---

libs/mxml/Makefile

Maintainer: Espen Jurgensen / @ejurgensen
Description: version update

mxml: Update to version 2.10

---

sound/forked-daapd/Makefile

Maintainer: Espen Jurgensen / @ejurgensen
Description: version update
Signed-off-by: Espen Jürgensen espenjurgensen+openwrt@gmail.com

forked-daapd: Update to version 24.2

---

net/linuxptp/Makefile

Signed-off-by: Wojciech Dubowik <klute99@gmail.com>

linuxptp: Update to version 1.8

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/ddns.config
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/dynamic_dns_lucihelper.sh
net/ddns-scripts/files/dynamic_dns_updater.sh

Run tested: LEDE r2138 with luci-app-ddns 2.4.8
Description:
fixes bugs reported in #3616 #3617 #3621

ddns-scripts: various fixes

---

net/opentracker/Makefile

Self-explained.
@dangowrt, please, review.

opentracker: do not rewrite conf files

---

net/reaver/Makefile
net/reaver/patches/0101-pcap-use-65536-as-snaplen.patch

Maintainer: me
Compile tested: malta be on LEDE master
Run tested: pending in #3333 
Description:
Should fix issue #3333

reaver: use 65536 as snaplen with pcap

---

utils/qemu/Makefile

Maintainer: me
Description:
While at it, move these pacakges to submenu Utilities -> Virtualization

qemu: build sub-packages only for selected targets

---

utils/io/Makefile
utils/io/src/io.c

Maintainer: me / @hauke
Compile tested: LEDE master with lantiq
Run tested: LEDE master with Lantiq
Description:
This add the io tool from the old package feed.

io: add io-tool

---

net/tor/Makefile
net/tor/patches/001-torrc.patch

tor: update to version 0.2.8.11

---

net/wireguard/Makefile

Revert "package/wireguard bump version to 0.0.20161216"

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/update_cloudflare_com_v4.sh

Maintainer: me
Description:
- update_cloudflare_com_v4.sh: enclose urls in single quotes
- dynamic_dns_functions.sh: force to return only one ip, if using nslookup to get registered ip

ddns-scripts: fixes for cloudflare v4

---

net/bmon/Makefile

bmon: Bump to 4.0, update copyright

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/update_cloudflare_com_v4.sh
net/ddns-scripts/files/update_godaddy_com_v1.sh

Maintainer: me
Description:
Fix return codes, if ip data at Godaddy.com and Cloudflare.com are
already up to date, handle it as succesful update.

ddns-scripts: fix return codes if provider's data already up to date

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.sh

Maintainer: me / @<github-user>
Run tested: CC / LEDE trunk
Description:
* fixed adblock statistics in CC
* print additional list details in adblock statistics

adblock: update 2.0.3

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.sh

Maintainer: me
Run tested: LEDE trunk
Description:
* small fixes & cosmetics (missed in last commit)

adblock: update 2.0.4

---

net/zerotier/Config.in
net/zerotier/Makefile
net/zerotier/files/zerotier.config
net/zerotier/files/zerotier.init
net/zerotier/patches/0001-Fix-for-running-under-MUSL-libc-e.g.-Alpine-Linux.patch
net/zerotier/patches/0002-fix-build.patch
net/zerotier/patches/0003-workaround_to_avoid_seg_faults.patch
net/zerotier/patches/0005-use-internal-miniupnpc-and-natpmp

Maintainer: me
Compile tested: ar71xx, tl-wr703, OpenWrt 15.05
Run tested: ar71xx, tl-wr703, OpenWrt 15.05 (software connects to servers)
Description:
ZeroTier One is a programm to create a global provider-independent virtual private cloud. This project offers OpenWrt/LEDE packages for ZeroTier.
This is the package that has been maintained at this location so far:
https://github.com/mwarning/zerotier-openwrt

zerotier: add initial package

---

net/zerotier/patches/0005-use-internal-miniupnpc-and-natpmp

Maintainer: me
Compile tested: current head, ar7xx
Run tested: current build starts on my tp-wr703
Description:
Fixes build problem in #3779

zerotier: fix upnp build support

---

lang/luajit/Makefile

Compile tested: No
Run tested: No
Description:
Move luajit to where the other lua stuff lives

lang/luajit: Move to lua submenu

---

net/lftp/Makefile
net/sstp-client/Makefile

sstp-client: updated to 1.0.11 and moved under VPN submenu
Signed-off-by: fededim@gmail.com

lftp: updated to 4.7.5

---

net/sstp-client/Makefile

Signed-off-by: fededim@gmail.com

sstp-client: updated the fake title and description (old carelessness)

---

net/keepalived/Makefile

Maintainer: me / @scrpi
Description:
Talked it over with Ben (@scrpi).
He said he'd be fine with taking over maintainership of this.
@scrpi: please confirm this on PR.
Signed-off-by: Ben Kelly <ben@benjii.net>

keepalived: switch maintainer to Ben Kelly (@scrpi)

---

admin/debootstrap/Makefile

Compile tested: mvebu on OpenWrt trunk
Run tested: mvebu, OpenWrt trunk
Signed-off-by: Denis Osvald <denis.osvald@sartura.hr>

debootstrap: update to version 1.0.87

---

net/tor/Makefile
net/tor/patches/001-torrc.patch

Maintainer: me / @hauke
Compile tested: lantiq + x86
Description:

tor: update to version 0.2.9.8

---

net/bitlbee/Makefile

Maintainer: me
Description: An IRC to other chat networks gateway

bitlbee: Add package

---

net/ifstat/Makefile

Maintainer: me
Description: InterFace STATistics Monitoring

ifstat: Add package

---

net/adblock/Makefile
net/adblock/files/adblock.init
net/adblock/files/adblock.sh

Maintainer: me
Run tested: LEDE Reboot (SNAPSHOT, r3009-968fa53197)
Description:
* fix minor build error in init script
It would be nice if this PR goes to LEDE-17.01 branch as well - thanks!

adblock: bugfix 2.1.2

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/public_suffix_list.dat
net/ddns-scripts/files/services
net/ddns-scripts/files/services_ipv6

Maintainer: me
Run tested: OpenWrt 15.05 & DD trunk & LEDE trunk & LEDE 17.01
Description:
- fix detecting local ip from ip command #3834 and https://forum.lede-project.org/t/bugs-in-ddns-scripts/1000
- minor fixes to services files

[lede-17.01] ddns-scripts: fix detecting local ip from ip command

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/public_suffix_list.dat
net/ddns-scripts/files/services
net/ddns-scripts/files/services_ipv6

Maintainer: me
Run tested: OpenWrt 15.05 & DD trunk & LEDE trunk & LEDE 17.01
Description:
- fix detecting local ip from ip command #3834 and https://forum.lede-project.org/t/bugs-in-ddns-scripts/1000
- minor fixes to services files

[for-15.05] ddns-scripts: backport of 2.7.6-12

---

net/travelmate/Makefile
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: LEDE Reboot (SNAPSHOT, r3009-968fa53197)
Description:
* refine/speed-up (re-)connect handling
* fix minor build error in init script
* better logging & cosmetics
It would be nice if this PR goes to LEDE-17.01 branch as well - thanks!

travelmate: bugfix 0.3.2

---

net/travelmate/Makefile
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: LEDE trunk
Description:
* refine/speed-up (re-)connect handling
* fix minor build error in init script
* better logging & cosmetics

[lede-17.01] travelmate: bugfix 0.3.2

---

utils/progress/Makefile
utils/progress/patches/001_set-ncurses-lib.patch

Maintainer: me
Description: Coreutils Progress Viewer (formerly known as 'cv')

progress: Add package

---

net/fping/Makefile

Maintainer: me
Description: sends ICMP ECHO_REQUEST packets to network hosts

fping: Add package

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh

Maintainer: me
Description:
fix detecting local ip from ip command #3834 and
https://forum.lede-project.org/t/bugs-in-ddns-scripts/1000

ddns-scripts: fix detecting local ip from ip command

---

net/unbound/files/README.md

Maintainer: me
Documentation only - README.md had some bad HOW TO details

unbound: error in README.md for unbound+dnsmasq

---

utils/gammu/Makefile

gammu: bump to new upstream 1.38.1

---

lang/python-pcapy/Makefile

Signed-off-by: Andrew McConachie <andrew@depht.com>
Compile tested: AMD64
Run tested: tested
Description: new release

lang/python-pcapy: Bumped version to 0.11.1

---

mail/postfix/Makefile

postfix: update to 3.1.4

---

admin/netdata/Makefile
admin/netdata/files/netdata.conf
admin/netdata/patches/001-disable_external_plugins_by_default.patch

Maintainer: myself
Compile tested: Kirkwood, iomega iConnect, LEDE trunk
Run tested: Kirkwood, iomega iConnect, LEDE trunk
Description:
* Update to 1.5.0
* Refresh patches
* Make config file more usable out of the box
* Adjust a few default settings

admin/netdata: Update to 1.5.0

---

net/tor/Makefile

Maintainer: me / @hauke
Compile tested: lantiq
Description:
minor bugfix release

tor: update to version 0.2.9.9

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.sh

Maintainer: me
Run tested: LEDE trunk
Description:
* update readme regarding unbound integration
* cosmetics

adblock: 2.3.0 (package release 2)

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/public_suffix_list.dat
net/ddns-scripts/files/services
net/ddns-scripts/files/services_ipv6

Maintainer: me
Description:
- new update url for service "duiadns.net" #3969

ddns-scripts: New update url for service duiadns.net

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/public_suffix_list.dat
net/ddns-scripts/files/services
net/ddns-scripts/files/services_ipv6

Maintainer: me
Run tested: 
Description:
- new update url for service "duiadns.net"

[lede-17.01] ddns-scripts: New update url for service duiadns.net

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/dynamic_dns_functions.sh
net/ddns-scripts/files/public_suffix_list.dat
net/ddns-scripts/files/services
net/ddns-scripts/files/services_ipv6

Maintainer: me
Description:
- new update url for service "duiadns.net" #3969

[for-15.05] ddns-scripts: New update url for service duiadns.net

---

utils/pcmciautils/Makefile
utils/pcmciautils/files/etc/hotplug.d/pcmcia/pcmcia.agent
utils/pcmciautils/files/etc/hotplug.d/pcmcia_socket/pcmcia_socket.agent
utils/pcmciautils/files/etc/init.d/pcmcia
utils/pcmciautils/files/etc/init.d/pcmcia_socket
utils/pcmciautils/patches/001-switch_unsigned.patch
utils/pcmciautils/patches/002-disable_yywrap.patch

Maintainer: me / @tmn505
Compile tested: x86/Legacy, Generic, LEDE ada6d9fecaf5147db51b7f27c548eb66590d8500
Run tested: x86/Legacy, Generic, LEDE ada6d9fecaf5147db51b7f27c548eb66590d8500
Description:
Because this PR lede-project/source#621 there is need for this package to load cis firmware.
Can You also pull it to lede-17.01 branch or is it closed to new packages? Should i make additional PR?

pcmciautils: import from oldpackages

---

net/vpnbypass/Makefile
net/vpnbypass/files/README.md
net/vpnbypass/files/vpnbypass.init

Maintainer: me / @stangri
Compile tested: (ipq806x, Linksys EA8500, LEDE snapshot)
Run tested: (ipq806x, Linksys EA8500, LEDE 17.01-snapshot r3141)
Description: new service trigger, typo fix in output (changed single quote to double quote), reorganized some code.

vpnbypass: new service triggers, typo fix

---

net/wireguard/Makefile

@danrl might want to give his approval.

wireguard: simple package bump to 0.0.20170213

---

net/vpnbypass/Makefile

Sorry about that, I'll rewrite the code to manipulate the file outside the tree later, that's all I have time for in the morning!

vpnbypass: makefile hotfix

---

net/adblock/Makefile
net/adblock/files/adblock.init
net/adblock/files/adblock.sh

Maintainer: me
Run tested: LEDE trunk & Chaos Calmer
Description:
* various optimizations & corner case fixes
* removed no longer needed debug information
* polished up for forthcoming LEDE release ;-)

adblock: update 2.3.1

---

net/travelmate/Makefile
net/travelmate/files/README.md
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: LEDE Reboot SNAPSHOT r3511-04c4b6f7fd
Description:
* add 'enabled' check in init script
* support multiple radios (see online doc)
* fix race condition in ap check

travelmate: update 0.3.5

---

net/bitlbee/Makefile

bitlbee: Update to 3.5.1

---

libs/boost/Makefile

Maintainer: me / @ClaymorePT
Description:
This reverts commit 21091fa0acda1f723d933e83652bc9d0317977e8 which created a regression as stated in https://github.com/openwrt/packages/issues/4089

boost: Revert Commit 21091fa

---

net/travelmate/Makefile
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: TP-LINK RE-450, LEDE Reboot SNAPSHOT r3640-f229f4af31
Description:
* mute useless logging in "active mode"
* optimize startup behaviour
* cosmetics

travelmate: update 0.4.1

---

net/mwan3/Makefile

Maintainer: @Adze1502
Compile tested: --
Run tested: --
Description:
Maintainer does not answer on my PR since months.
So I added me (@feckert) as a co maintainer.

net/mwan3: add me as co maintainer

---

utils/open-plc-utils/Makefile

Fix TITLE and description to contain the actual tool name.
Signed-off-by: Günther Kelleter <guenther.kelleter@devolo.de>
Maintainer: @ffainelli 
Compile tested: OpenWrt 15.05

open-plc-utils: fix menuconfig entries

---

utils/ttyd/Makefile

Maintainer: me
Compile tested: (ramips, mt7620, LEDE@90728c7)
Description:
ttyd: update to 1.3.1
Signed-off-by: Shuanglei Tao <tsl0922@gmail.com>

ttyd: update to 1.3.1

---

net/vpnbypass/Makefile
net/vpnbypass/files/README.md
net/vpnbypass/files/vpnbypass.conf
net/vpnbypass/files/vpnbypass.init

Maintainer: me
Compile tested: (ipq806x, Linksys EA8500, LEDE 17.01.0 release)
Run tested: (ipq806x, Linksys EA8500, LEDE 17.01.0 release)
Description:
Updated enabled/disabled logic based on the feedback from previous PR.

vpnbypass: updated service enable/start logic.

---

admin/openwisp-config/Makefile

See: #4103 
Signed-off-by: Gabriele Gemmi <gabriel@autistici.org>

openwisp-config: new package

---

net/ddns-scripts/Makefile
net/ddns-scripts/files/services

Otherwise the script was stuck in an update loop.

ddns-scripts: update dnsexit.com update URL+response

---

net/cshark/Makefile

Moved over to the LuCI repository.
Signed-off-by: Dan Luedtke <mail@danrl.com>
Maintainer: @lperkov

net/cshark: remove luci-app-cshark

---

net/miniupnpc/Makefile

Install listdevices as well
Signed-off-by: Mo Chen <uncorrupt@gmail.com>

miniupnpc: update to 2.0.20161216

---

net/mwan3/Makefile
net/mwan3/files/etc/hotplug.d/iface/16-mwan3-user
net/mwan3/files/etc/mwan3.user

Maintainer: me
Compile tested: lantiq, xrx200, OpenWRT
Run tested: lantiq, xrx200 OpenWRT
Description:
This PR will add the mwan3 hutplug.d/iface script to the mwan3 packages. In a follow up commit the mwan3 user script in the luci repo well be removed.

net/mwan3: add mwan3.user hotplug script

---

utils/moreutils/Makefile
utils/moreutils/patches/001_disable-manuals.patch

Maintainer: me
Description: additional Unix utilities

moreutils: Add package

---

net/mwan3/Makefile

Maintainer: me
Compile tested:--
Run tested:--
Description:
As discussed in issue https://github.com/openwrt/packages/pull/4122 at me as the main maintainer

net/mwan3: change maintainer

---

net/travelmate/Makefile
net/travelmate/files/travelmate.conf
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: LEDE Reboot SNAPSHOT r3867-313197d707
Description:
* fix stop action in "active" mode
* fix race condition in "active" mode

travelmate: update 0.5.0

---

utils/moreutils/patches/002_no-install-strip.patch

moreutils: Fix build failure due to install stripping

---

net/webui-aria2/Makefile

Refactor makefile and update to last commit

webui-aria2: update to last commit

---

net/mwan3/Makefile
net/mwan3/files/lib/mwan3/mwan3.sh
net/mwan3/files/usr/sbin/mwan3
net/mwan3/files/usr/sbin/mwan3track

Maintainer: me
Compile tested: lantiq, xrx200, LEDE
Run tested: lantiq lantiq, xrx200, LEDE
Description:
Refactoring mwan3track script

Mwan3track refactoring

---

net/siit/Makefile
net/siit/src/siit.c

Maintainer: me
Compile tested: OpenWrt master head

[net/siit] Added compability for Linux >= 4.7.0

---

libs/libpng/Makefile

Compile tested: ramips, MQMaker WiTi board, LEDE trunk
Run tested: Not done
Description:
Sprinkle more symlinks for compatibility

libs/libpng: Add more symlinks

---

net/fping/Makefile

fping: Update to 4.0

---

net/mwan3/Makefile
net/mwan3/files/etc/hotplug.d/iface/15-mwan3
net/mwan3/files/lib/mwan3/mwan3.sh
net/mwan3/files/usr/libexec/rpcd/mwan3
net/mwan3/files/usr/sbin/mwan3
net/mwan3/files/usr/sbin/mwan3track

Maintainer: me
Compile tested: lantiq, xrx200, LEDE
Run tested: lantiq, xrx200, LEDE
Description:
This PR should fix https://github.com/openwrt/packages/issues/4325 and also improves mwan3track kill handling on interface up events

Mwan3 fixes

---

net/dynapoint/Makefile
net/dynapoint/src/dynapoint.lua

Signed-off-by: Hernan Rossetto <hmronline@gmail.com>
Tested with latest sources from LEDE (+17.1)

dynapoint: Updated to latest version (Fixes to make it actually work)

---

libs/udns/Makefile
libs/udns/patches/0001-use-autotools.patch
net/shadowsocks-libev/Makefile

Maintainer: @aa65535 
Compile tested: malta, mips_24kc, LEDE master
Run tested: malta qemu machine with ss-local

shadowsocks-libev: bump to version 3.0.6

---

net/nginx/Makefile
net/nginx/patches/102-sizeof_test_fix.patch

Compile tested: bcm53xx, Buffalo WXR-1900DHP, LEDE Reboot SNAPSHOT r4149-74395d9
Run tested: bcm53xx, Buffalo WXR-1900DHP, LEDE Reboot SNAPSHOT r4149-74395d9; install, uninstall and run tests were successful
Description:
This is a straightforward update to the latest stable version. @heil: please review and approve.
Signed-off-by: Val Kulkov <val.kulkov@gmail.com>

nginx: update to 1.12.0, the latest stable version

---

mail/clamsmtp/Makefile
mail/clamsmtp/files/clamsmtpd.init

Compile/Tested on x86_64 LEDE Reboot (SNAPSHOT, r3640-f229f4a)

mail: add package clamsmtp

---

net/netatalk/Makefile

Maintainer: was: @dangowrt  ; becomes: me
Description:
Referencing discussion from PR https://github.com/openwrt/packages/pull/4402

netatalk: switch maintainer to me

---

net/ipsec-tools/Makefile
net/ipsec-tools/files/functions.sh
net/ipsec-tools/files/racoon
net/ipsec-tools/files/racoon.init

Also added myself as co-maintainer
---
Makefile           |    5 +++--
files/functions.sh |   35 +++++++++++++++++++++++++++++++++++
files/racoon       |    4 ++++
files/racoon.init  |   12 ++++++++----
4 files changed, 50 insertions(+), 6 deletions(-)

ipsec: add ability to configure "none" SA

---

utils/gammu/Makefile

gammu: bunp to a new v1.38.3

---

net/netopeer2/files/netopeer2-server.init

Signed-off-by: Antonio Paunovic antonio.paunovic@sartura.hr
Compile tested: (MIPS_24kc, Hornet-UB, LEDE master )
Run tested: (MIPS_24kc, Hornet-UB, LEDE master)
Description:
Service recovery for slow performing devices.

netopeer2-server: init recovery

---

net/travelmate/Makefile
net/travelmate/files/README.md
net/travelmate/files/travelmate.sh

Maintainer: me
Run tested: LEDE Reboot (SNAPSHOT, r4356-7f91cabd0d)
Description:
* fix wrong connection status in case of an error

travelmate: maintenance update 0.7.5

---

utils/lcdproc/Makefile

lcdproc: respect LDFLAGS

---

utils/coreutils/Makefile

Compile tested: qemu malta be
Run tested: qemu malta be
Fixes #1674

coreutils: stdbuf: fix missing libstdbuf.so

---

utils/gammu/Makefile

gammu: bump to a new upstream v1.38.4

---

net/unbound/Makefile
net/unbound/patches/001-conf.patch

Maintainer: me
Tested: TL-Archer-C7v2 LEDE Trunk
Description: Unbound 1.6.4 released 2017-Jun-27

unbound: update to 1.6.4

---

net/travelmate/Makefile
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.sh

Run tested: LEDE Reboot SNAPSHOT r4533-7887a46f45
Description:
* change start priority to 90 and revert hostapd stuff from last commit
* cosmetics

travelmate: update 0.8.2

---

net/beanstalkd/Makefile
net/beanstalkd/files/beanstalkd.init
net/beanstalkd/patches/900-makefile.patch
net/beanstalkd/patches/901-fix-headers.patch
net/beanstalkd/patches/902-replace-posix_fallocate.patch

Maintainer: me
Compile tested: x86_64, Haswell server, OpenWRT head (871372c42a3)
Have been running in captive testbed with PHP services for several weeks now without issue.
Description:
Add the [beanstalkd](http://kr.github.io/beanstalkd/) work-queue server.

beanstalkd:  initial commit

---

lang/python/python-yaml/Makefile

python-yaml: update source and build for python3

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.conf

Signed-off-by: Patrick Mulder <pcmulder89@gmail.com>

adblock: Added Netherlands as a region.

---

admin/netdata/Makefile
admin/netdata/files/netdata.conf

Maintainer: myself
Compile tested: mvebu, Linksys WRT3200ACM, LEDE trunk
Run tested: mvebu, Linksys WRT3200ACM, LEDE trunk
Description:
Update netdata to 1.7.0
Update URL
Clean up some more stray image files (smaller package)

admin/netdata: Update to 1.7.0

---

.travis.yml
.travis_do.sh

Hello
Here some improvements for our travis checks
An exemple https://travis-ci.org/champtar/packages/builds/256680655

Travis improvements

---

sound/forked-daapd/Makefile

Maintainer: Espen Jürgensen / @ejurgensen
Compile tested: ar7xxxx, OpenWRT trunk
Run tested: no
Description:
Version update

forked-daapd: Update to 25.0

---

utils/lcdproc/Makefile

Maintainer: me and @pprindeville 
Compile tested: mxs, OpenWRT cabb0c506526fe468e4aa985086e50c440192122
Run tested: as above
Description:
Update to latest upstream.

lcdproc: Update to 0.5.9

---

libs/speexdsp/Makefile

Hello Peter @tripolar 
Do you mind bumping speex? There is no big version jumps, but the package can be brushed up a little bit as well.
Best regards,
Sebastian

libs/speex: version bump and refactoring

---

libs/postgresql/Makefile

Signed-off-by: Michael Braun <michael-dev@fami-braun.de>
Please also read https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md
Maintainer: daniel@makrotopia.org
Compile tested: OpenWRT P1020WLAN

postgresql: InstallDev pkg-config files for libpq

---

mail/postfix/Makefile

Fix for #4633
Maintainer: me
Compile tested: LEDE revision 4787e19, ar7xxx
Run tested: LEDE Reboot (HEAD, r2032+3), ar7xxx

postfix: fix sendmail symlink

---

mail/postfix/Makefile
mail/postfix/patches/900_less_overlayfs_rewrites.patch

Fix for #4620
Signed-off-by: Denis Shulyaka Shulyaka@gmail.com
Maintainer: me
Compile tested: LEDE revision 4787e19, ar7xxx
Run tested: LEDE Reboot (HEAD, r2032+3), ar7xxx

postfix: less overlayfs rewrites

---

lang/python/python/files/python-package-install.sh
lang/python/python3/files/python3-package-install.sh

Maintainer: me
Compile tested: https://github.com/lede-project/source/commit/0b7f7606dd509084813571b68ef8bf4f8bfdcee3
Fixes:
https://github.com/openwrt/packages/issues/4681

python,python3: fix opkg collisions with -src packages

---

utils/rpcd-mod-attendedsysupgrade/files/attendedsysupgrade.defaults

use named uci options
@dangowrt 
Signed-off-by: Paul Spooren <paul@spooren.de>

rpcd-mod-attendedsysupgrade: simplify uci options

---

net/nginx/Makefile

fixes: CVE-2017-7529
Signed-off-by: Uwe Arnold <donvipre@gmail.com>

nginx: update to 1.12.1

---

net/aria2/Config.in
net/aria2/Makefile
net/aria2/files/aria2.conf
net/aria2/files/aria2.init

* Add aria2 user and group.
* Use procd to start service.
* Add more supported options.
Maintainer: me / @kuoruan
Compile tested: LEDE 17.01.2

aria2: Rewrite init script

---

net/aria2/Makefile
net/aria2/files/aria2.init

Maintainer: me
Compile tested: Not yet
Run tested: Not yet

aria2: Add missing 'or' in section validate function

---

net/mwan3/Makefile
net/mwan3/files/etc/hotplug.d/iface/15-mwan3
net/mwan3/files/lib/mwan3/mwan3.sh
net/mwan3/files/usr/sbin/mwan3
net/mwan3/files/usr/sbin/mwan3track

Maintainer: me
Compile tested: n/a (only changed a shell script)
Run tested: (lantiq_xrx200, LEDE 17.01.0, tested failover and failback; iptables/ipset/ip checked)
Description:
Add some fixes to mwan3 cherry picked from master (with minor changes to get commits applied)
Tested-by: @rmilecki

net/mwan3: fixes for mwan3 (lede-17.01)

---

mail/fdm/Makefile
mail/fdm/patches/003-base64-fix.patch

Maintainer: Dmitry V. Zimin / @pfzim
Compile tested: ar7xxx/ar9xxx

fdm: bump to latest version

---

net/wireguard/Makefile

Simple version bump.
Changelog:
https://lists.zx2c4.com/pipermail/wireguard/2017-September/001709.html

wireguard: bump to release 0.0.20170918

---

libs/libglog/Makefile

glog is C++ implementation of the Google logging module
Signed-off-by: Amir Sabbaghi <amir@pichak.co>
Compile tested: MIPS, GL-inet 6416 v1 and GL MT300A, LEDE commit 5faad30
Run tested: MIPS, GL-inet 6416 v1 and GL MT300A, LEDE commit 5faad30

glog: new package

---

net/lftp/Makefile

lftp: updated to 4.8.2

---

mail/postfix/Makefile

Compile/Run tested: x86_64 LEDE r4969-67ac017fef

postfix: version bump to 3.2.3

---

net/lftp/Makefile

lftp: compilation bugfix for old openwrt buildroot

---

net/knxd/Makefile
net/knxd/files/knxd.config
net/knxd/files/knxd.init

Signed-off-by: Patrick Grimm <patrick@lunatiki.de>
Maintainer: Othmar Truniger <github@truniger.ch> / @tru7
Compile tested: LEDE 7d905f1e95539f9bc43fad4f2892d916ced546cb
Run tested: VoCore2 ramips_mt76x8
Description:
Fix config file location and init script.

knxd: Fix config file location and init script.

---

admin/sudo/Makefile

Maintainer: me
Compile tested: ar71xx, Netgear WNDR4300, openwrt r50134
Description:
Updates sudo to version 1.8.21p2

sudo: update to 1.8.21p2

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.conf
net/adblock/files/adblock.sh

Maintainer: me / @<github-user>
Run tested: tested by ticket owner 
Description:
* add new list source to default config to block browser-based crypto mining (see #4931)

adblock: update 3.0.3

---

lang/python/chardet/Makefile
lang/python/django-compressor/Makefile
lang/python/django-constance/Makefile
lang/python/django-picklefield/Makefile
lang/python/django-postoffice/Makefile
lang/python/django-restframework/Makefile
lang/python/django-statici18n/Makefile
lang/python/gunicorn/Makefile
lang/python/jdcal/Makefile
lang/python/openpyxl/Makefile
lang/python/python-dateutil/Makefile
lang/python/python-urllib3/Makefile
lang/python/pytz/Makefile
lang/python/simplejson/Makefile

Maintainer: me
Compile tested: ar71xx, Netgear WNDR4300, openwrt r50139
Run tested: -
Description:
Updated several python packages maintained by me to the latest stable version.

Update several python packages

---

libs/libxslt/Makefile

Run tested: mvebu, Turris Omnia, OpenWRT 15.05

libxslt: Update to version 1.1.31

---

sound/fdk-aac/Config.in
sound/fdk-aac/Makefile

Maintainer: myself
Compile tested: mvebu, Linksys WRT3200ACM, LEDE trunk
Run tested: mvebu, Linksys WRT3200ACM, LEDE trunk
Description:
Update to latest commit upstream
Add optimization option

sound/fdk-aac: Update to latest commit

---

lang/perl-text-csv_xs/Makefile

Maintainer: me / @Naoir 
Compile tested: x86_64, generic, LEDE HEAD (1e5e005)
Build new image and booted it.  Ran a script using this module (`xt_geoip_build`) and it worked fine.
Description:

perl: package Text::CSV_XS module

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.conf

Signed-off-by: Nokius <foss@nokius.net>
Maintainer:  @dibdot
Run tested: (ar71xx, WDR4300, OpenWRT trunk))
Description:
add the list for Germany

adblock: add German list

---

utils/rtklib/Makefile

Description:
Fix source repo for rtklib, while at it, bump to a more recent version.

CC: rtklib: move sources / upgrade

---

libs/libupnpp/Makefile
sound/upmpdcli/Config.in
sound/upmpdcli/Makefile
sound/upmpdcli/patches/010-Add_icon_config.patch

Maintainer: @ignisf 
Description:
Sources for 0.9.0 were pulled from the download sites, let's upgrade to more recent versions.

CC: upmpdcli/libupnpp upgrade

---

lang/perl-dbi/Makefile
lang/perl-uri/Makefile
lang/perl-www-mechanize/Makefile

Maintainer: @Naoir 
Description:
Old sources were pulled from the net for URI, WWW-Mechanize and DBI. Upgrade them to more recent versions.

CC: upgrade a couple perl packages

---

utils/taskwarrior/Makefile

Maintainer: @lperkov 
Description:
Upgrade to a more recent version (for which I was able to find a source tarball), bringing to the same level as in master.

CC: utils/taskwarrior: upgrade to 2.4.4

---

libs/mxml/Makefile

Maintainer: @ejurgensen 
Description:
Upgrade mxml to latest version, update download URL to compile on CC.

CC: upgrade mxml, update download URL

---

lang/perl-uri/Makefile

Fixes #5089
Maintainer: @Naoir @pprindeville 
Compile tested: LEDE/master

perl-uri: upgrade to 1.72

---

libs/uw-imap/Makefile
libs/uw-imap/patches/001-fix_Makefiles_and_shlib.patch
libs/uw-imap/patches/002-imap-2004a-doc.patch
libs/uw-imap/patches/003-imap-2007e-overflow.patch
libs/uw-imap/patches/005-imap-2007e-authmd5.patch
libs/uw-imap/patches/006-imap-2007f-format-security.patch
libs/uw-imap/patches/007-imap-2007e-poll.patch

Maintainer: me
Compile/Run tested: x86, x86_64 LEDE r5239-8d3857a347
Description: Devel libs needed for pho7-mod-imap

uw-imap: add uw-imap toolkit, prereq for php7-mod-imap

---

lang/php7/Makefile

Maintainer: @mhei 
Compile/Run tested: x86, x86_64 LEDE r5239-8d3857a347
depends on https://github.com/openwrt/packages/pull/5065

php7: add php7-mod-imap

---

multimedia/ffmpeg/Makefile

Maintainer: me
Compile tested: LEDE latest, ar71xx
Description:
This PR is tentative in order to do some Travis build tests and other config dependencies.
~~Please do not merge yet.~~
Update: LGTM - Travis likes it so it must be good.
@antonlacon - any interest/benefit in moving to 3.3.x ?? 

ffmpeg: Adjusting some build dependencies. Update to 3.2.9

---

lang/php7/Makefile

Maintainer: @mhei 
Compile/Run tested: LEDE version r5442-b0b289ea45

php7: try fix imap build-bot build

---

.travis_do.sh

Maintainer: @lynxis 
* https://travis-ci.org/commodo/packages/builds/310445805 - just this branch
* https://travis-ci.org/commodo/packages/pull_requests - in a PR context
---------------------------------------------------------
This started out as me trying to fix my Python build in a local Travis CI env.
After 40+ minutes, the build still did not stop: https://travis-ci.org/commodo/packages/builds/310413628
There is a bug, where the `.travis_do.sh` script does exit early, and enters an endless loop, when doing a branch build.
It tries to continuously fetch 50 more revisions.
So, I decided to add some limited support for branch builds.
This also allows a simpler testing with Travis before
opening a PR.
This scope of testing is limited to whatever the last …

build,travis: build only last commit in a branch build

---

net/i2pd/Makefile
net/i2pd/files/i2pd.init
net/i2pd/patches/010-cross-compile.patch

Maintainer: me
Compile tested: arch:ar71xx, OpenWRT/LEDE version:Reboot 17.01.4
Run tested: arch:ar71xx, OpenWRT/LEDE version:Reboot 17.01.4, tests done
Description:
full-featured C++ implementation of I2P client

i2pd: Add package

---

net/travelmate/Makefile
net/travelmate/files/travelmate.sh

Run tested: GL-MT300Nv2
Description:
* fix incomplete bssid logic
* add missing package dependencies
* Turris omnia compability fixes (LuCI, separate PR)
* OpenWrt theme fixes (LuCI, separate PR)

travelmate: update 0.9.6

---

net/shorewall-lite/Makefile
net/shorewall6-lite/Makefile

Maintainer: wvdakker@wilsoft.nl
Compile tested: (Zyxel P2812, trunk)
Run tested: (Zyxel P2812, build/install/run)
Description:
Reorder the install section to make it more readable.

Shorewall(6)-lite: Reorder install section

---

lang/ldbus/Makefile
lang/luarocks/Makefile

ldbus: lua bindings for DBUS
Compile tested on: ramips/mt7621
lede master branch, at commit 1928fc93ced752bd1e304ab3837fb41e7a80b9d9

luarocks: Allow building luarocks for the host

---

lang/ruby/Makefile
lang/ruby/ruby_find_pkgsdeps
lang/ruby/ruby_missingfiles

Maintainer: me
Compile tested: OpenWrt r5621-1064e76 x86 and ar71xx
Run tested: OpenWrt r5621-1064e76 x86, using "gem update"

ruby: bump to 2.5.0

---

utils/slide-switch/Makefile

Maintainer: me
Compile tested: ar71xx / ramips / x86, LEDE trunk
Description:
slide-switch: update to latest version

slide-switch: update to latest version

---

libs/libedit/Makefile

Maintainer: me
Run tested: mvebu, Turris Omnia, OpenWRT 15.05

libedit: update to 20170329-3.1

---

libs/liburcu/Makefile

Maintainer: me
Run tested: mvebu, Turris Omnia, OpenWRT 15.05

liburcu: update to 0.9.4

---

net/adblock/Makefile
net/adblock/files/README.md
net/adblock/files/adblock.conf
net/adblock/files/adblock.init
net/adblock/files/adblock.notify
net/adblock/files/adblock.sh

Run tested: current trunk with APU2 / Turris Omnia
Description:
* add pidfile writing / check to prevent further race conditions
* ease the download utility selection: uclient-fetch (default),
wget, curl, aria2c, wget-nossl, busybox-wget are pre-configured
* add debug download logging in case of an error, e.g. wrong url
* change 'malware' blocklist source url
* add logfile information to email template
* LuCI: add 'Download Utility' select box
* LuCI: add new "running" status

adblock: update 3.4.3

---

net/travelmate/Makefile
net/travelmate/files/travelmate.init
net/travelmate/files/travelmate.sh

Run tested: current trunk with APU2 / Turris Omnia
Description:
* add new 'running' status
* rework debug & status output
* LuCI: refine status view
* LuCI: add two missing eap auth variants

travelmate: update 1.0.2

---

lang/python/python-attrs/Makefile
lang/python/python-cryptography/Makefile
lang/python/python-idna/Makefile
lang/python/python-parsley/Makefile
lang/python/python-ply/Makefile
lang/python/python-pyasn1-modules/Makefile
lang/python/python-pyasn1/Makefile
lang/python/python-pycparser/Makefile
lang/python/python-pyopenssl/Makefile
lang/python/python-service-identity/Makefile
lang/python/python-six/Makefile
lang/python/python-zope-interface/Makefile

Maintainer: me
Compile tested: ar71xx, OpenWRT/LEDE trunk
Description:
python-*,python3-*: add src packages for multiple packages

python-*,python3-*: add src packages for multiple packages

---

net/ola/Makefile
net/ola/files/olad.init

Maintainer: @bk138
Compile tested: brcm2708/bcm2708, current git HEAD
Run tested: brcm2708/bcm2708, current git HEAD
Description:
Improve init script and drop now unneeded dependency on sudo.

ola: improve init script

---

lang/python/python-package.mk
lang/python/python/Makefile
lang/python/python3-package.mk
lang/python/python3/Makefile

Maintainer: me
Compile tested: https://github.com/openwrt/openwrt/commit/190c1c3cc8d8534899ef55ab77468a7d52833e94
Related to https://github.com/openwrt/packages/issues/5424

python,python3: disable dependencies between python src packages

---

lang/python/python-incremental/Makefile
lang/python/python-incremental/patches/001-omit-tests.patch

Maintainer: me
Compile tested: ar71xx, OpenWRT/LEDE trunk
Description:
python-incremental: new package
This is a new requirement for the Twisted package.
From the readme:
Incremental is a small library that versions your Python projects.

python-incremental: new package

---

libs/confuse/Makefile

confuse: remove myself as maintainer

---

net/kadnode/Config.in
net/kadnode/Makefile
net/kadnode/files/kadnode.config
net/kadnode/files/kadnode.init
net/kadnode/files/kadnode.postinst
net/kadnode/patches/0001-fix-type-of-returned-address-count.patch

Maintainer: me
Compile tested: ar71xx, current master
Run tested: ar71xx, wr703
Description:
A decentralized DNS resolver (using a BitTorrent DHT and mbedtls).

kadnode: add new package

---

libs/libuwsc/Makefile
utils/rtty/Makefile
utils/rtty/files/rtty.config
utils/rtty/files/rtty.init

Maintainer: me
Compile tested: (mipsel,miwifi-mini, master 7e99a6ba69)
Run tested: (mipsel,miwifi-mini, master 7e99a6ba69)
Description:
A reverse proxy WebTTY. It is composed of the client and the server.
https://github.com/zhaojh329/rtty

rtty: Add package

---

net/zerotier/Makefile
net/zerotier/files/zerotier.config
net/zerotier/files/zerotier.init
net/zerotier/patches/0004-Revert-Do-not-serve-controller-requests-until-init-i.patch

Maintainer: me
Compile tested: ar71xx, LEDE master
Run tested: ar71xx (tl-wdr4300) LEDE 17.01.4
Description:
* add config_path option since the controller mode needs a persisting path to be used
* add patch to fix a bug in the controller code (https://github.com/zerotier/ZeroTierOne/issues/553)
* disable zerotier by default, as the default settings let it connect to a public network

zerotier: support controller mode

---

lang/php7/Makefile
lang/php7/patches/1012-php_iconv_string-null-out-pointer.patch

Maintainer: @mhei 
Compile tested: x86_64, generic, OpenWrt HEAD (059b2f5)
Run tested: continuous integration upstream build/test
Description:

php7: redux of fix for issue #5488

---

net/vpnbypass/Makefile
net/vpnbypass/files/README.md
net/vpnbypass/files/vpnbypass.init

Maintainer: me
Compile tested: mvebu, Linksys WRT3200ACM, 17.01.4
Run tested: ipq806x, Linksys EA8500, 17.01.4 
Description:
- Correctly setup service triggers for WAN/OpenVPN interfaces
- Correctly start/stop/reload from Web UI
- Updated README
- Correctly add/remove ucitrack entries

vpnbypass: better start/stop from Web UI and triggers

---

libs/libtirpc/Makefile
libs/libtirpc/patches/01-Disable-parts-of-TIRPC-requiring-NIS-support.patch
libs/libtirpc/patches/02-replace-__bzero-with-memset-API.patch
libs/libtirpc/patches/03-uClibc-without-RPC-support-and-musl-does-not-install-rpcent.h.patch
libs/libtirpc/patches/04-export_key_secretkey_is_set.patch
libs/libtirpc/patches/05-Disable-DES-authentification-support.patch
libs/libtirpc/patches/06-include-stdint.h-for-uintptr_t.patch

Signed-off-by: Andy Walsh <andy.walsh44+github@gmail.com>
Maintainer: me
Compile tested: (x86_64, Linux ubuntu-vm 4.13.0-19-generic, OpenWrt master (d58c8f40)
Run tested: (arm/mvebu, AC1200AC, OpenWrt master)
Description:
Need this as dep for my upcoming samba4.8 package.

libtirpc: add package v1.0.2

---

net/irssi/Makefile

Description:
Bring up irssi to latest in 0.8.x, update download URL to fix build

CC: net/irssi: upgrade irssi, update download URL

---

multimedia/gst1-plugins-base/Makefile
multimedia/gst1-plugins-base/patches/001-no-translations.patch
multimedia/gst1-plugins-base/patches/002-no-tests.patch
multimedia/gst1-plugins-base/patches/003-no-docs.patch

Maintainer: me
Description:
gst1-plugins-base: update to 1.12.4

gst1-plugins-base: update to 1.12.4

---

multimedia/gst1-plugins-good/Makefile
multimedia/gst1-plugins-good/patches/001-no-translations.patch
multimedia/gst1-plugins-good/patches/002-no-tests.patch
multimedia/gst1-plugins-good/patches/003-no-docs.patch

Maintainer: me
Description:
gst1-plugins-good: update to 1.12.4 Requires pull #5593.

gst1-plugins-good: update to 1.12.4

---

multimedia/gst1-plugins-ugly/Makefile
multimedia/gst1-plugins-ugly/patches/001-no-translations.patch
multimedia/gst1-plugins-ugly/patches/002-no-tests.patch
multimedia/gst1-plugins-ugly/patches/003-no-docs.patch

Maintainer: me
Description:
gst1-plugins-ugly: update to 1.12.4
Requires pull #5593

gst1-plugins-ugly: update to 1.12.4

---

net/isc-dhcp/Makefile
net/isc-dhcp/patches/000-compile.patch
net/isc-dhcp/patches/510-bind-CC.patch

Maintainer: me
Compile tested: x86_64, generic, HEAD (60e07ff)
Run tested: same, built and reinstalled .ipk on testbed
Stopped and restarted the service.  Seems to be running fine and answering requests.
Description:

isc-dhcp: update to 4.4.0

---

net/adblock/Makefile
net/adblock/files/adblock.init
net/adblock/files/adblock.sh

Run tested: APU2, OpenWrt SNAPSHOT r6057+137-3594447a7d
Description:
* maintenance update, just small backend bugfixes

adblock: update 3.5.1

---

mail/mailman/Makefile

Less verbose and more flexible. Cosmetic change.
Maintainer: @Shulyaka

mailman: Use @GNU macro for download link

---

net/ariang/Makefile

Compile tested: r7800 ipq8065 trunk
Run tested: r7800 ipq8065 trunk
Description: Modern webui for aria2 package

ariang: add new package

---

libs/tiff/Makefile

Description:
Hello Jiri,
Removes $(FPIC), updates install defines.
Kind regards,
Seb

Tiff: remove $(FPIC), update install defines

---

libs/libxslt/Makefile

Description:
Hello Jiri,
again FPIC removal and some cleanups.
Have a nice weekend!
Seb

libxslt: remove $(FPIC), clean up install defines

---

libs/libssh2/Makefile

Description:
Hello Jiri,
Fixes CFLAGS and updates the install define.
Kind regards,
Seb

libs/libssh2: Remove $(FPIC), update InstallDev

---

net/pingcheck/Makefile

Maintainer: me
Compile tested: ar71xx, master
Run tested: ar71xx, master
Description: Just update to latest version from Nov 2017

pingcheck: Update to latest version

---

net/mwan3/Makefile

Maintainer: many
Description:
Update jshn package dependencies

mwan3: fix package to dependency

---

net/unbound/files/README.md
net/unbound/files/odhcpd.awk

Maintainer: me
Tested: OpenWrt master / TL-Archer-C7v2
Description: bug fix for SLAAC inference https://github.com/openwrt/packages/pull/5787

unbound: fix SLAAC DNS inference

---

net/reaver/Makefile

reaver: Update to 1.6.4

---

net/clamav/Makefile

Compile/Run tested: x86_64 r6538-5f7d134454

clamav: update clamav to 0.99.4

---

net/wifidog-ng/Makefile
net/wifidog-ng/files/wifidog-ng.hotplug
net/wifidog-ng/files/wifidog-ng.init

wifidog-ng: Update to 1.4.0

---

utils/unrar/Makefile
utils/unrar/patches/100-makefile_fixes.patch

Change links to HTTPS and add CPE_ID.

unrar: Update to 5.6.1.

---

libs/boost/Makefile

Maintainer: @ClaymorePT
Compile tested: LEDE  BCM2708 - Raspberry Pi B/B+/Zero/ZeroW
Description:
This package update provides two new libraries
- **Contract (compiled library) [[1]]**: Contract programming for C++. All contract programming features are supported: Subcontracting, class invariants, postconditions (with old and return values), preconditions, customizable actions on assertion failure (e.g., terminate or throw), optional compilation and checking of assertions, etc, from Lorenzo Caminiti.
- **HOF (header-only library) [[2]]**: Higher-order functions for C++, from Paul Fultz II.
**More info can be found at the usual place [[3]].**
[1]: https://www.boost.org/libs/contract
[2]: https://www.boost.org/libs/hof
[3]: …

boost: Package Version Update -> 1.67.0

---

net/clamav/Makefile

Compile/Run tested: x86_64 r6744-751746c736

clamav: update to 0.100.0

---

net/coova-chilli/Makefile
net/coova-chilli/files/chilli.init

Maintainer: @kaloz 
Run tested: mvebu/generic, Turris Omnia, OpenWrt 15.05 r47055
Description:
able to launch (multiple) chilli instance with procd

coova-chilli: switch to procd

---

net/snort/Makefile

Maintainer: me
Description:
I would like to assume maintainership of the snort package.

snort: set W. Michael Petullo as maintainer

---

net/lftp/Makefile

lftp: updated to 4.8.3

---

net/adblock/files/README.md

small typo in description
Description:

adblock: typo : donwload -> download

---

net/miniupnpd/Makefile
net/miniupnpd/files/upnpd.config

Description:  A couple of tweaks, build size optimisation & change of leasefile location.
Tested on ar71xx Archer C7 v2

Miniupnpdtweaks

---

net/miniupnpd/Makefile

Just when I had my back turned they released another version.

miniupnpd: bump to v2.1 20180508

---

net/aria2/Makefile

Maintainer: me
Compile tested: mt7620
Run tested: mt7620

aria2: Bump 1.34.0

---

admin/atop/Makefile

Maintainer: Toni Uhlig matzeton@googlemail.com
Compile tested: x86_64, debian-stable, OpenWrt SNAPSHOT r6687+2-d13c7acd9e
Run tested: mvebu, linksys3200ac, OpenWrt SNAPSHOT r6687+2-d13c7acd9e
Description:
An advanced interactive monitor for Linux-systems to view the load on system- level and process-level.

atop: add new package

---

net/uwsgi-cgi/LICENSE
net/uwsgi-cgi/Makefile

Compile tested: trunk
Run tested: netgear r7800 
Description: Uwsgi compiled with cgi profile to support plain cgi for ngix webserver

uwsgi-cgi: New package

---

net/uwsgi-cgi/Makefile

uwsgi-cgi: another missing library

---

net/uwsgi-cgi/Makefile

uwsgi-cgi: remove useless dep

---

net/mwan3/Makefile
net/mwan3/files/lib/mwan3/mwan3.sh

Maintainer: me
Compile tested: only scripts
Run tested: x86_64 model, OpenWrt master
Description:
This should fix issue https://github.com/openwrt/packages/issues/5906

net/mwan3: fix Ipv6 RA service

---

lang/python/python-pyserial/Makefile

Maintainer: Micke Prag <micke.prag@telldus.se>
Compile tested: bcm2708 OpenWRT GIT 0f063f8
Run tested: bcm2708 OpenWRT GIT 0f063f8
Description:
Update to version 3.4
Add build for python3
Add source packages
Signed-off-by: Kimmo Vuorinen <kimmo.vuorinen@gmail.com>

python-pyserial: Update to version 3.4

---

libs/faad2/Makefile

faad2: Update to 2.8.8

---

libs/libsamplerate/Makefile

libsamplerate: Update to 0.1.9

---

libs/libogg/Makefile

libogg: Update to 1.3.3

---

libs/p11-kit/Makefile
libs/p11-kit/patches/010-build-Ease-issetugid-check-when-cross-compiling.patch

p11-kit: Update to 0.23.12

---

mail/dovecot/Makefile
mail/dovecot/patches/001-configure_in.patch

Maintainer: me
Compile tested: x86_64, master 4fdc6ca3
Run tested: x86_64, master 4fdc6ca3
Description:
dovecot: update to 2.3.1

dovecot: update to 2.3.1

---

net/addrwatch/Makefile
net/addrwatch/patches/001-fix-sys_siglist.patch
net/addrwatch/patches/002-fix-uclibc-sysconf.patch
net/addrwatch/patches/003-fix-pkt-hash.patch

addrwatch: Update to 1.0.1

---

utils/bandwidthd/Makefile

bandwidthd: Update to 2.0.1-35

---

libs/pcre2/Makefile

pcre2: Update to 10.31

---

net/ariang/Makefile

Permit to remove uhttpd dep if nginx package is selected.

ariang: dep rework

---

libs/file/Makefile

file: Update to 5.33

---

utils/rtty/Makefile

rtty: Update to 5.0.2

---

utils/cryptsetup/Makefile

cryptsetup: Update to 2.0.3

---

libs/glpk/Makefile

glpk: Update to 4.65

---

net/uwsgi-cgi/Makefile
net/uwsgi-cgi/files-luci-support/uwsgi.conf
net/uwsgi-cgi/files-luci-support/uwsgi.init

This adds additional specific files to support luci on the nginx

uwsgi: add luci-support package

---

net/uwsgi-cgi/Makefile
net/uwsgi-cgi/files-luci-support/uwsgi.conf

This fix wrong configuration to the luci uwsgi conf
@hnyman 

uwsgi-cgi: improve uwsgi configuration

---

net/net-snmp/files/snmpd.init

Add snmp_extend config options
Signed-off-by: Xavier Franquet <xavier@franquet.es>
Compile/Run tested: mvebu / linksys 1200ac / openwrt-1806

snmpd: Add snmp_extend config option

---

net/unbound/Makefile
net/unbound/patches/001-conf.patch

Tested: TL-Archer-C7v2 OpenWrt master
Description: upstream bug fixes

unbound: update to 1.7.3

---

libs/freetype/Makefile

freetype: Update to 2.9.1

---

lang/python/python-attrs/Makefile
lang/python/python-automat/Makefile
lang/python/python-automat/patches/001-do-not-use-setuptools-scm-m2r.patch
lang/python/python-automat/patches/002-omit-visualize.patch
lang/python/python-automat/patches/003-omit-tests.patch
lang/python/python-hyperlink/Makefile
lang/python/python-ipaddress/Makefile
lang/python/python-ply/Makefile
lang/python/python-pyasn1/Makefile
lang/python/python-zope-interface/Makefile
lang/python/python-zope-interface/patches/001-omit-tests.patch
lang/python/twisted/Makefile
lang/python/twisted/patches/001-omit-tkconch.patch
lang/python/twisted/patches/002-omit-tests.patch

Maintainer: me
Compile tested: ar71xx / x86-legacy; sdk snapshots (21 Jun)
Description:
Update several python packages to their latest versions.

Python packages update

---

lang/python/python-attrs/Makefile
lang/python/python-automat/Makefile
lang/python/python-automat/patches/001-do-not-use-setuptools-scm-m2r.patch
lang/python/python-automat/patches/002-omit-visualize.patch
lang/python/python-automat/patches/003-omit-tests.patch
lang/python/python-hyperlink/Makefile
lang/python/python-ipaddress/Makefile
lang/python/python-ply/Makefile
lang/python/python-pyasn1/Makefile
lang/python/python-zope-interface/Makefile
lang/python/python-zope-interface/patches/001-omit-tests.patch
lang/python/twisted/Makefile
lang/python/twisted/patches/001-omit-tkconch.patch
lang/python/twisted/patches/002-omit-tests.patch

Maintainer: me
Compile tested: ar71xx; 18.06.0-rc1 sdk
Description:
Update several python packages to their latest versions.

[openwrt-18.06] Python package updates

---

net/unbound/Makefile
net/unbound/files/unbound.init
net/unbound/files/unbound.sh

Maintainer: me
Tested: TL-Archer-C7v2
Description: 
- resolve image builder #6339
- expand on clean up request #6362 
- email change

unbound: limit outside script source to init funciton scope

---

net/unbound/Makefile
net/unbound/files/unbound.init

Maintainer: me
Tested: TL-Archer-C7v2
Description: should resolve image builder #6339 and email change

[openwrt-18.06] unbound: limit outside script source to init funciton scope

---

net/unbound/Makefile
net/unbound/files/unbound.init

Maintainer: me
Tested: TL-Archer-C7v2
Description: should resolve image builder #6339 and email change

[lede-17.01] unbound: limit outside script source to init funciton scope

---

lang/golang/golang-package.mk
lang/golang/golang/Makefile

Maintainer: me
Compile tested: x86-64; sdk snapshot (21 Jun)
Description:
This PR was originally for the first commit, then more changes happened and this PR became a batch update :laughing:

golang: Makefile improvements

---

lang/golang/golang-package.mk
lang/golang/golang/Makefile

Maintainer: me
Compile tested: ar71xx; 18.06.0-rc1 sdk
Description:
This PR was originally for the first commit, then more changes happened and this PR became a batch update :laughing:

[openwrt-18.06] golang: Makefile improvements

---

utils/unrar/Makefile

Fixes a few CVEs.
Maintainer: @Noltari / @thess 

unrar: Update to 5.6.5

---

.travis.yml

Compile tested: x86_64, generic, HEAD
Description:
Run git clone with --quiet option.

travis: don't need git cloning progress

---

utils/mariadb/Makefile
utils/mariadb/conf/my.cnf
utils/mariadb/conf/mysqld.default
utils/mariadb/files/mysqld.init

Maintainer: me
Description:
Updates mariadb plus converts init script to procd.
Hello @hnyman and @jow- 
Can you please merge this as well?
Kind regards,
Seb

[18.06] mariadb: bump to 10.1.34 + procd init

---

libs/zmq/Makefile
libs/zmq/patches/010-disable_pedantic_on_linux_with_ulibc++.patch
libs/zmq/patches/020-map_with_const_string_with_ublic++.patch

Switched to using GitHub generated tarballs. autoreconf is needed anyway.

zmq: Update to 4.1.6

---

libs/apr/Makefile

apr: Update to 1.6.3

---

utils/zsh/Makefile

zsh: Update to 5.5.1

---

lang/lzmq/Makefile

lzmq: Update to 0.4.4

---

multimedia/gst1-plugins-base/Makefile
multimedia/gst1-plugins-base/patches/002-no-tests.patch

Maintainer: me
Compile tested: x86, x86_64, master 4fdc6ca3
Description:
gst1-plugins-base: update to 1.14.1
This merge request requires #6415.

gst1-plugins-base: update to 1.14.1

---

multimedia/gst1-plugins-good/Makefile
multimedia/gst1-plugins-good/patches/002-no-tests.patch

Maintainer: me
Compile tested: x86, x86_64, master 4fdc6ca3
Description:
gst1-plugins-good: update to 1.14.1
This merge request requires #6415 and #6416.

gst1-plugins-good: update to 1.14.1

---

lang/python/python-mysql/Makefile

Compile tested: ar71xx, archs
Description:
Hello Alexandru,
This PR addresses a download failure - which @hnyman spotted - plus build failures on uclibc.
Kind regards,
Seb

python-mysql: fix 404 and uclibc build failures

---

net/unbound/files/README.md

Maintainer: Me
Description: 
**README.md** only. Unbound UCI so far has limited forward configuration lacking setting up DNS over TLS connections. User override files `unbound_srv.conf` and `unbound_ext.conf` can implement this.

unbound: add README recipe for DNS/TLS outside of UCI

---

libs/libantlr3c/Makefile

Added HTTPS everywhere
Maintainer: @ejurgensen 

libantlr3c: Update to 3.4

---

libs/libtalloc/Makefile

libtalloc: Update to 2.1.13

---

net/nginx/Makefile

nginx: bump to latest release

---

libs/libradcli/Makefile

Cosmetic fixes.
Signed-off-by: Rosen Penev <rosenp@gmail.com

libradcli: Update to 1.2.10

---

libs/yaml/Makefile

Some URL fixes.
Maintainer: @psycho-nico 

yaml:  Update to 0.2.1

---

devel/pkg-config/Makefile

pkg-config: Update to 0.29.2

---

libs/tdb/Makefile

Signed-off-by: BangLang Huang <banglang.huang@foxmail.com>
Maintainer: Dmitry V. Zimin <pfzim@mail.ru>
Compile tested: x86, x86_64, OpenWrt trunk
Run tested: x86, x86_64, OpenWrt trunk, test done
Description:
bump to latest version

tdb: bump to latest version

---

libs/libtalloc/Makefile

libtalloc: Update to 2.1.14

---

libs/libuhttpd/Makefile
libs/libuhttpd/patches/001-fix-find-lua.patch

libuhttpd: Update to 2.1.2

---

lang/php7/Makefile

Maintainer: @mhei
Description:
Pull all version bumps and bugfixes into 18.06 release branch.
This also fixes #6404.

[openwrt-18.06] php7: update to latest version and include bugfixes

---

utils/uvcdynctrl/Makefile

uvcdynctrl: Update to 0.2.5

---

net/bonding/Makefile
net/bonding/files/lib/netifd/proto/bonding.sh

Maintainer: me
Compile tested: only a shell script
Run tested: mips
Description:
This is a first version of a netifd proto handler which handles Link Aggregation (Channel Bonding)

net/bonding: added protohandler package for netifd

---

utils/acpica-unix/Makefile

acpica-unix: Update to 20180629

---

net/foolsm/Makefile
net/foolsm/files/connections.conf
net/foolsm/files/foolsm.conf
net/foolsm/files/foolsm.init
net/foolsm/files/foolsm_script
net/foolsm/patches/100-plugin-export-dir.patch
net/foolsm/patches/110-missing-WAIT_ANY.patch

Maintainer: me
Compile tested: ar71xx, wndr4300/wdr4300/archer-c7, 17.01.4
Run tested: same as above
Description:
Add package foolsm for link state monitoring
Signed-off-by: Brian J. Murrell <brian@interlinx.bc.ca>

Add package foolsm

---

net/inadyn/Makefile

inadyn: Update to 2.3.1

---

net/softflowd/Makefile

Found using uscan.
Maintainer: @rvandegrift

softflowd: Fix URL

---

net/linknx/Makefile

linknx: Update to 0.0.1.36 and switch to codeload

---

utils/pciutils/Makefile

pciutils: Update to 3.6.1

---

sound/shairport-sync/Makefile

shairport-sync: Update to 3.2.1

---

net/miniupnpd/Makefile

Practicalities of life have intervened and I am no longer able to
dedicate the time required to look after this package.

miniupnpd: remove my maintainership

---

utils/fio/Makefile

Maintainer: ??? @diizzyy updates this.

fio: Update to 3.8

---

utils/cryptsetup/Makefile

cryptsetup: Update to 2.0.4

---

utils/joe/Makefile

Cosmetic makefile changes
Maintainer: @aTanW 

joe: Update to 4.6

---

utils/gammu/Makefile
utils/gammu/patches/001-iconv-disabling-option.patch
utils/gammu/patches/002-no-fstack-protector.patch
utils/gammu/patches/003-cmake-cross-toolchain.patch
utils/gammu/patches/004-cmake_libdbi_optional.patch

Cosmetic makefile changes.
Maintainer: @aTanW 

gammu: Update to 1.39.0

---

libs/libgphoto2/Makefile
libs/libgphoto2/patches/001-automake-compat.patch
libs/libgphoto2/patches/002-no-docs-examples-test-translations.patch

Maintainer: me
Compile tested: (AR7xxx/AR9xxx, Generic, OpenWrt 18.06.0)
Description: update package 2.5.19

libgphoto2: update package 2.5.19

---

utils/lvm2/Makefile
utils/lvm2/patches/000-compile.patch
utils/lvm2/patches/001-include_fix.patch
utils/lvm2/patches/002-const-stdio.patch
utils/lvm2/patches/003-no-mallinfo.patch
utils/lvm2/patches/004-device-include-goto-lable-as-well.patch

LVM2: Update to 2.02.80

---

lang/python/python-gnupg/Makefile

python-gnupg: Update to 0.4.3

---

utils/grep/Makefile

grep: Update to 3.1

---

net/geth/Makefile

geth: Update to 1.8.13

---

utils/btrfs-progs/Makefile

Cosmetic adjustments
Maintainer: me

btrfs-progs: Update to 4.17.1

---

mail/alpine/Makefile

alpine: Update to 2.21.9999

---

lang/python/python-pyasn1/Makefile

Signed-off-by: Rosen Penev <rosenp@gmail.com
Maintainer: @jefferyto @commodo

python-pyasn1: Update to 0.4.4
